IGLib: IPLab.BilateralForm Class Reference
IPLab.BilateralForm Class Reference
Public Member Functions
BilateralForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
Bitmap Image [set]
IFilter Filter [get]
Private Member Functions
void kernelSizeUpDown_ValueChanged (object sender, EventArgs e)
void spatialFactorUpDown_ValueChanged (object sender, EventArgs e)
void spatialPowerUpDown_ValueChanged (object sender, EventArgs e)
void colorFactorUpDown_ValueChanged (object sender, EventArgs e)
void colorPowerUpDown_ValueChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
BilateralSmoothing filter = new BilateralSmoothing()
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.GroupBox groupBox2
FilterPreview filterPreview
System.Windows.Forms.Button cancelButton
System.Windows.Forms.Button okButton
System.Windows.Forms.NumericUpDown kernelSizeUpDown
System.Windows.Forms.Label label1
System.Windows.Forms.NumericUpDown colorPowerUpDown
System.Windows.Forms.Label label5
System.Windows.Forms.NumericUpDown colorFactorUpDown
System.Windows.Forms.Label label4
System.Windows.Forms.NumericUpDown spatialPowerUpDown
System.Windows.Forms.Label label3
System.Windows.Forms.NumericUpDown spatialFactorUpDown
System.Windows.Forms.Label label2
Constructor & Destructor Documentation
IPLab.BilateralForm.BilateralForm () inline
References IPLab.BilateralForm.colorFactorUpDown, IPLab.BilateralForm.colorPowerUpDown, IPLab.BilateralForm.filter, IPLab.FilterPreview.Filter, IPLab.BilateralForm.filterPreview, IPLab.BilateralForm.InitializeComponent(), IPLab.BilateralForm.kernelSizeUpDown, IPLab.BilateralForm.spatialFactorUpDown, and IPLab.BilateralForm.spatialPowerUpDown.
Member Function Documentation
void IPLab.BilateralForm.kernelSizeUpDown_ValueChanged (object sender, EventArgs e) inline private
References IPLab.BilateralForm.filterPreview, IPLab.BilateralForm.kernelSizeUpDown, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.BilateralForm.InitializeComponent().
void IPLab.BilateralForm.spatialFactorUpDown_ValueChanged (object sender, EventArgs e) inline private
References IPLab.BilateralForm.filterPreview, IPLab.FilterPreview.RefreshFilter(), and IPLab.BilateralForm.spatialFactorUpDown.
Referenced by IPLab.BilateralForm.InitializeComponent().
void IPLab.BilateralForm.spatialPowerUpDown_ValueChanged (object sender, EventArgs e) inline private
References IPLab.BilateralForm.filterPreview, IPLab.FilterPreview.RefreshFilter(), and IPLab.BilateralForm.spatialPowerUpDown.
Referenced by IPLab.BilateralForm.InitializeComponent().
void IPLab.BilateralForm.colorFactorUpDown_ValueChanged (object sender, EventArgs e) inline private
References IPLab.BilateralForm.colorFactorUpDown, IPLab.BilateralForm.filterPreview, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.BilateralForm.InitializeComponent().
void IPLab.BilateralForm.colorPowerUpDown_ValueChanged (object sender, EventArgs e) inline private
References IPLab.BilateralForm.colorPowerUpDown, IPLab.BilateralForm.filterPreview, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.BilateralForm.InitializeComponent().
override void IPLab.BilateralForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IPLab.BilateralForm.components.
void IPLab.BilateralForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IPLab.BilateralForm.cancelButton, IPLab.BilateralForm.colorFactorUpDown, IPLab.BilateralForm.colorFactorUpDown_ValueChanged(), IPLab.BilateralForm.colorPowerUpDown, IPLab.BilateralForm.colorPowerUpDown_ValueChanged(), IPLab.BilateralForm.filterPreview, IPLab.BilateralForm.groupBox1, IPLab.BilateralForm.groupBox2, IPLab.FilterPreview.Image, IPLab.BilateralForm.kernelSizeUpDown, IPLab.BilateralForm.kernelSizeUpDown_ValueChanged(), IPLab.BilateralForm.label1, IPLab.BilateralForm.label2, IPLab.BilateralForm.label3, IPLab.BilateralForm.label4, IPLab.BilateralForm.label5, IPLab.BilateralForm.okButton, IPLab.BilateralForm.spatialFactorUpDown, IPLab.BilateralForm.spatialFactorUpDown_ValueChanged(), IPLab.BilateralForm.spatialPowerUpDown, and IPLab.BilateralForm.spatialPowerUpDown_ValueChanged().
Referenced by IPLab.BilateralForm.BilateralForm().
Member Data Documentation
BilateralSmoothing IPLab.BilateralForm.filter = new BilateralSmoothing() private
Referenced by IPLab.BilateralForm.BilateralForm().
System.ComponentModel.IContainer IPLab.BilateralForm.components = null private
Required designer variable.
Referenced by IPLab.BilateralForm.Dispose().
System.Windows.Forms.GroupBox IPLab.BilateralForm.groupBox1 private
Referenced by IPLab.BilateralForm.InitializeComponent().
System.Windows.Forms.GroupBox IPLab.BilateralForm.groupBox2 private
Referenced by IPLab.BilateralForm.InitializeComponent().
FilterPreview IPLab.BilateralForm.filterPreview private
Referenced by IPLab.BilateralForm.BilateralForm(), IPLab.BilateralForm.colorFactorUpDown_ValueChanged(), IPLab.BilateralForm.colorPowerUpDown_ValueChanged(), IPLab.BilateralForm.InitializeComponent(), IPLab.BilateralForm.kernelSizeUpDown_ValueChanged(), IPLab.BilateralForm.spatialFactorUpDown_ValueChanged(), and IPLab.BilateralForm.spatialPowerUpDown_ValueChanged().
System.Windows.Forms.Button IPLab.BilateralForm.cancelButton private
Referenced by IPLab.BilateralForm.InitializeComponent().
System.Windows.Forms.Button IPLab.BilateralForm.okButton private
Referenced by IPLab.BilateralForm.InitializeComponent().
System.Windows.Forms.NumericUpDown IPLab.BilateralForm.kernelSizeUpDown private
Referenced by IPLab.BilateralForm.BilateralForm(), IPLab.BilateralForm.InitializeComponent(), and IPLab.BilateralForm.kernelSizeUpDown_ValueChanged().
System.Windows.Forms.Label IPLab.BilateralForm.label1 private
Referenced by IPLab.BilateralForm.InitializeComponent().
System.Windows.Forms.NumericUpDown IPLab.BilateralForm.colorPowerUpDown private
Referenced by IPLab.BilateralForm.BilateralForm(), IPLab.BilateralForm.colorPowerUpDown_ValueChanged(), and IPLab.BilateralForm.InitializeComponent().
System.Windows.Forms.Label IPLab.BilateralForm.label5 private
Referenced by IPLab.BilateralForm.InitializeComponent().
System.Windows.Forms.NumericUpDown IPLab.BilateralForm.colorFactorUpDown private
Referenced by IPLab.BilateralForm.BilateralForm(), IPLab.BilateralForm.colorFactorUpDown_ValueChanged(), and IPLab.BilateralForm.InitializeComponent().
System.Windows.Forms.Label IPLab.BilateralForm.label4 private
Referenced by IPLab.BilateralForm.InitializeComponent().
System.Windows.Forms.NumericUpDown IPLab.BilateralForm.spatialPowerUpDown private
Referenced by IPLab.BilateralForm.BilateralForm(), IPLab.BilateralForm.InitializeComponent(), and IPLab.BilateralForm.spatialPowerUpDown_ValueChanged().
System.Windows.Forms.Label IPLab.BilateralForm.label3 private
Referenced by IPLab.BilateralForm.InitializeComponent().
System.Windows.Forms.NumericUpDown IPLab.BilateralForm.spatialFactorUpDown private
Referenced by IPLab.BilateralForm.BilateralForm(), IPLab.BilateralForm.InitializeComponent(), and IPLab.BilateralForm.spatialFactorUpDown_ValueChanged().
System.Windows.Forms.Label IPLab.BilateralForm.label2 private
Referenced by IPLab.BilateralForm.InitializeComponent().
Property Documentation
Bitmap IPLab.BilateralForm.Image set
Referenced by IPLab.ImageDoc.bilateralSmoothingFiltersItem_Click().
IFilter IPLab.BilateralForm.Filter get
Referenced by IPLab.ImageDoc.bilateralSmoothingFiltersItem_Click().
The documentation for this class was generated from the following files:
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/BilateralForm.cs
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/BilateralForm.Designer.cs