IGLib: Meta.Numerics.UncertainMath Class Reference
Meta.Numerics.UncertainMath Class Reference
Contains methods for computing basic mathematical functions of uncertain values.
Static Public Member Functions
static UncertainValue Sqrt (UncertainValue x)
Computes the square root of an uncertain value.
static UncertainValue Sin (UncertainValue x)
Computes the sine of an uncertain value.
static UncertainValue Cos (UncertainValue x)
Computes the cosine of an uncertain value.
static UncertainValue Tan (UncertainValue x)
Computes the tangent of an uncertain value.
static UncertainValue Asin (UncertainValue x)
Computes the arcsine of an uncertain value.
static UncertainValue Acos (UncertainValue x)
Computes the arccosine of an uncertain value.
static UncertainValue Atan (UncertainValue x)
Computes the arctangent of an uncertain value.
static UncertainValue Atan2 (UncertainValue x, UncertainValue y)
Computes the arctangent of the ratio of two uncertain values.
static UncertainValue Exp (UncertainValue x)
Computes e to the power of an uncertain value.
static UncertainValue Log (UncertainValue x)
Computes the natural logarithm of an uncertain value.
static UncertainValue Pow (UncertainValue x, double p)
Computes an uncertain value raised to an arbitrary power.
static UncertainValue Sinh (UncertainValue x)
Computes the hyperbolic sine of an uncertain value.
static UncertainValue Cosh (UncertainValue x)
Computes the hyperbolic cosine of an uncertain value.
static UncertainValue Tanh (UncertainValue x)
Computes the hyperbolic tangent of an uncertain value.
Detailed Description
Contains methods for computing basic mathematical functions of uncertain values.
The methods in this static class perform the same basic mathematical operations as the methods of the System.Math class, accounting for the uncertainty in the inputs to produce a corresponding uncertainty in the output.
As with operations on uncertain values, the methods assume that the uncertainty in input parameters represents the standard deviation of a distribution of measurements, and produce a value for the uncertainty in the output which represent a corresponding standard deviation, under the assumption that the standard deviations are small relative to the best values.
Member Function Documentation
static UncertainValue Meta.Numerics.UncertainMath.Sqrt (UncertainValue x) inline static
Computes the square root of an uncertain value.
Parameters
x The argument.
Returns
The square root of the argument.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Referenced by Test.UncertainMathTest.UncertainMathSqrtSquare(), and Test.UncertainMathTest.UncertainMathValueAgreement().
static UncertainValue Meta.Numerics.UncertainMath.Sin (UncertainValue x) inline static
Computes the sine of an uncertain value.
Parameters
x The argument.
Returns
The sine of the argument.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Referenced by Test.UncertainMathTest.UncertainMathValueAgreement().
static UncertainValue Meta.Numerics.UncertainMath.Cos (UncertainValue x) inline static
Computes the cosine of an uncertain value.
Parameters
x The argument.
Returns
The cosine of the argument.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Referenced by Test.UncertainMathTest.UncertainMathCosACos(), and Test.UncertainMathTest.UncertainMathValueAgreement().
static UncertainValue Meta.Numerics.UncertainMath.Tan (UncertainValue x) inline static
Computes the tangent of an uncertain value.
Parameters
x The argument.
Returns
The tanget of the argument.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Referenced by Test.UncertainMathTest.UncertainMathValueAgreement(), and Test.UncertainValueTest.UncertainValueZeroUncertaintiesTest().
static UncertainValue Meta.Numerics.UncertainMath.Asin (UncertainValue x) inline static
Computes the arcsine of an uncertain value.
Parameters
x The argument.
Returns
The arcsine of the argument.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
static UncertainValue Meta.Numerics.UncertainMath.Acos (UncertainValue x) inline static
Computes the arccosine of an uncertain value.
Parameters
x The argument.
Returns
The arccosine of the argument.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Referenced by Test.UncertainMathTest.UncertainMathCosACos().
static UncertainValue Meta.Numerics.UncertainMath.Atan (UncertainValue x) inline static
Computes the arctangent of an uncertain value.
Parameters
x The argument.
Returns
The arctanget of the argument.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Referenced by Test.UncertainMathTest.UncertainMathValueAgreement(), and Test.UncertainValueTest.UncertainValueZeroUncertaintiesTest().
static UncertainValue Meta.Numerics.UncertainMath.Atan2 (UncertainValue x, UncertainValue y) inline static
Computes the arctangent of the ratio of two uncertain values.
Parameters
x The argument of the numerator.
y The argument of the denominator.
Returns
The arctangent of the quotient.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
static UncertainValue Meta.Numerics.UncertainMath.Exp (UncertainValue x) inline static
Computes e to the power of an uncertain value.
Parameters
x The argument.
Returns
The value of e^x1.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Referenced by Test.UncertainMathTest.UncertainMathLogExp(), Test.UncertainMathTest.UncertainMathValueAgreement(), and Test.UncertainValueTest.UncertainValueZeroUncertaintiesTest().
static UncertainValue Meta.Numerics.UncertainMath.Log (UncertainValue x) inline static
Computes the natural logarithm of an uncertain value.
Parameters
x The argument.
Returns
The value of ln(x1).
References Meta.Numerics.UncertainValue.RelativeUncertainty, Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Referenced by Test.UncertainMathTest.UncertainMathLogExp(), Test.UncertainMathTest.UncertainMathValueAgreement(), and Test.UncertainValueTest.UncertainValueZeroUncertaintiesTest().
static UncertainValue Meta.Numerics.UncertainMath.Pow (UncertainValue x, double p) inline static
Computes an uncertain value raised to an arbitrary power.
Parameters
x The argument.
p The power.
Returns
The argument raised to the specified power.
References Meta.Numerics.UncertainValue.RelativeUncertainty, Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Referenced by Test.UncertainMathTest.UncertainMathSqrtSquare().
static UncertainValue Meta.Numerics.UncertainMath.Sinh (UncertainValue x) inline static
Computes the hyperbolic sine of an uncertain value.
Parameters
x The argument.
Returns
The hyperbolic sine of the argument.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Referenced by Test.UncertainMathTest.UncertainMathValueAgreement().
static UncertainValue Meta.Numerics.UncertainMath.Cosh (UncertainValue x) inline static
Computes the hyperbolic cosine of an uncertain value.
Parameters
x The argument.
Returns
The hyperbolic cosine of the argument.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Referenced by Test.UncertainMathTest.UncertainMathValueAgreement().
static UncertainValue Meta.Numerics.UncertainMath.Tanh (UncertainValue x) inline static
Computes the hyperbolic tangent of an uncertain value.
Parameters
x The argument.
Returns
The hyperbolic tanget of the argument.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Referenced by Test.UncertainMathTest.UncertainMathValueAgreement().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Core/UncertainMath.cs