IGLib: NUnit.Tests.Assemblies.MockTestFixture Class Reference
NUnit.Tests.Assemblies.MockTestFixture Class Reference
Public Member Functions
void MockTest1 ()
void MockTest2 ()
void MockTest3 ()
void FailingTest ()
void TestWithManyProperties ()
void MockTest4 ()
void ExplicitlyRunTest ()
void NotRunnableTest (int a, int b)
void InconclusiveTest ()
void TestWithException ()
Public Attributes
const int Tests = 11
const int Suites = 1
const int Ignored = 1
const int Explicit = 1
const int NotRun = Ignored + Explicit
const int TestsRun = Tests - NotRun
const int ResultCount = Tests - Explicit
const int Failures = 1
const int Errors = 1
const int NotRunnable = 2
const int ErrorsAndFailures = Errors + Failures + NotRunnable
const int Inconclusive = 1
const int Categories = 5
const int MockCategoryTests = 2
Static Protected Member Functions
static void MockTest5 ()
Private Member Functions
void MethodThrowsException ()
Member Function Documentation
void NUnit.Tests.Assemblies.MockTestFixture.MockTest1 () inline
void NUnit.Tests.Assemblies.MockTestFixture.MockTest2 () inline
void NUnit.Tests.Assemblies.MockTestFixture.MockTest3 () inline
References NUnit.Framework.Assert.Pass().
static void NUnit.Tests.Assemblies.MockTestFixture.MockTest5 () inline static protected
void NUnit.Tests.Assemblies.MockTestFixture.FailingTest () inline
References NUnit.Framework.Assert.Fail().
void NUnit.Tests.Assemblies.MockTestFixture.TestWithManyProperties () inline
void NUnit.Tests.Assemblies.MockTestFixture.MockTest4 () inline
void NUnit.Tests.Assemblies.MockTestFixture.ExplicitlyRunTest () inline
void NUnit.Tests.Assemblies.MockTestFixture.NotRunnableTest (int a, int b) inline
void NUnit.Tests.Assemblies.MockTestFixture.InconclusiveTest () inline
References NUnit.Framework.Assert.Inconclusive().
void NUnit.Tests.Assemblies.MockTestFixture.TestWithException () inline
void NUnit.Tests.Assemblies.MockTestFixture.MethodThrowsException () inline private
Member Data Documentation
const int NUnit.Tests.Assemblies.MockTestFixture.Tests = 11
const int NUnit.Tests.Assemblies.MockTestFixture.Suites = 1
const int NUnit.Tests.Assemblies.MockTestFixture.Ignored = 1
const int NUnit.Tests.Assemblies.MockTestFixture.Explicit = 1
const int NUnit.Tests.Assemblies.MockTestFixture.NotRun = Ignored + Explicit
const int NUnit.Tests.Assemblies.MockTestFixture.TestsRun = Tests - NotRun
const int NUnit.Tests.Assemblies.MockTestFixture.ResultCount = Tests - Explicit
const int NUnit.Tests.Assemblies.MockTestFixture.Failures = 1
const int NUnit.Tests.Assemblies.MockTestFixture.Errors = 1
const int NUnit.Tests.Assemblies.MockTestFixture.NotRunnable = 2
const int NUnit.Tests.Assemblies.MockTestFixture.ErrorsAndFailures = Errors + Failures + NotRunnable
const int NUnit.Tests.Assemblies.MockTestFixture.Inconclusive = 1
const int NUnit.Tests.Assemblies.MockTestFixture.Categories = 5
const int NUnit.Tests.Assemblies.MockTestFixture.MockCategoryTests = 2
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/mock-assembly/MockAssembly.cs