IGLib: NUnit.Framework.Attributes.TestCaseSourceTests Class Reference
NUnit.Framework.Attributes.TestCaseSourceTests Class Reference
Classes
class DataSourceClass
class DivideDataProvider
class DivideDataProviderWithReturnValue
Public Member Functions
void SourceCanBeStaticProperty (string source)
void SourceUsingInstancePropertyIsNotRunnable ()
void SourceCanBeStaticMethod (string source)
void SourceUsingInstanceMethodIsNotRunnable ()
void SourceCanBeStaticField (string source)
void SourceUsingInstanceFieldIsNotRunnable ()
void SourceCanBeInstanceOfIEnumerable (string source)
void SourceMayReturnArgumentsAsObjectArray (int n, int d, int q)
void TestAttributeIsOptional (int n, int d, int q)
void SourceMayReturnArgumentsAsIntArray (int n, int d, int q)
void SourceMayReturnSinglePrimitiveArgumentAlone (int n)
int SourceMayReturnArgumentsAsParamSet (int n, int d)
void TestMayUseMultipleSourceAttributes (int n, int d, int q)
void TestWithFourArguments (int n, int d, int q, int r)
void SourceMayBeInAnotherClass (int n, int d, int q)
int SourceMayBeInAnotherClassWithReturn (int n, int d)
void IgnoreTakesPrecedenceOverExpectedException ()
void CanIgnoreIndividualTestCases ()
void CanMarkIndividualTestCasesExplicit ()
void HandlesExceptionInTestCaseSource ()
void HandlesExceptionInTestCaseSource_GuiDisplay (string lhs, string rhs)
void MethodTakingTwoStringArrays (string[] a, string[] b)
Properties
static IEnumerable StaticProperty [get]
static IEnumerable exception_source [get]
Private Member Functions
IEnumerable InstanceMethod ()
Static Private Member Functions
static IEnumerable StaticMethod ()
Static Private Attributes
static object[] StaticField
static object[] testCases
static object[] MyData
static object[] MyIntData
static object[] FourArgs
static int[] EvenNumbers = new int[] { 2, 4, 6, 8 }
static object[] MoreData
static object[] Params
Member Function Documentation
void NUnit.Framework.Attributes.TestCaseSourceTests.SourceCanBeStaticProperty (string source) inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Attributes.TestCaseSourceTests.SourceUsingInstancePropertyIsNotRunnable () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.NotRunnable, and NUnit.TestUtilities.TestBuilder.RunParameterizedMethodSuite().
void NUnit.Framework.Attributes.TestCaseSourceTests.SourceCanBeStaticMethod (string source) inline
References NUnit.Framework.Assert.AreEqual().
static IEnumerable NUnit.Framework.Attributes.TestCaseSourceTests.StaticMethod () inline static private
void NUnit.Framework.Attributes.TestCaseSourceTests.SourceUsingInstanceMethodIsNotRunnable () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.NotRunnable, and NUnit.TestUtilities.TestBuilder.RunParameterizedMethodSuite().
IEnumerable NUnit.Framework.Attributes.TestCaseSourceTests.InstanceMethod () inline private
void NUnit.Framework.Attributes.TestCaseSourceTests.SourceCanBeStaticField (string source) inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Attributes.TestCaseSourceTests.SourceUsingInstanceFieldIsNotRunnable () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.NotRunnable, and NUnit.TestUtilities.TestBuilder.RunParameterizedMethodSuite().
void NUnit.Framework.Attributes.TestCaseSourceTests.SourceCanBeInstanceOfIEnumerable (string source) inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Attributes.TestCaseSourceTests.SourceMayReturnArgumentsAsObjectArray (int n, int d, int q) inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Attributes.TestCaseSourceTests.TestAttributeIsOptional (int n, int d, int q) inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Attributes.TestCaseSourceTests.SourceMayReturnArgumentsAsIntArray (int n, int d, int q) inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Attributes.TestCaseSourceTests.SourceMayReturnSinglePrimitiveArgumentAlone (int n) inline
References NUnit.Framework.Assert.AreEqual().
int NUnit.Framework.Attributes.TestCaseSourceTests.SourceMayReturnArgumentsAsParamSet (int n, int d) inline
void NUnit.Framework.Attributes.TestCaseSourceTests.TestMayUseMultipleSourceAttributes (int n, int d, int q) inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Attributes.TestCaseSourceTests.TestWithFourArguments (int n, int d, int q, int r) inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Attributes.TestCaseSourceTests.SourceMayBeInAnotherClass (int n, int d, int q) inline
References NUnit.Framework.Assert.AreEqual().
int NUnit.Framework.Attributes.TestCaseSourceTests.SourceMayBeInAnotherClassWithReturn (int n, int d) inline
void NUnit.Framework.Attributes.TestCaseSourceTests.IgnoreTakesPrecedenceOverExpectedException () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Interfaces.ResultState.Ignored, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, and NUnit.TestUtilities.TestBuilder.RunParameterizedMethodSuite().
void NUnit.Framework.Attributes.TestCaseSourceTests.CanIgnoreIndividualTestCases () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestFinder.Find(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.PropertyNames.SkipReason, and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.TestCaseSourceTests.CanMarkIndividualTestCasesExplicit () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestFinder.Find(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.PropertyNames.SkipReason, and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.TestCaseSourceTests.HandlesExceptionInTestCaseSource () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ResultState.NotRunnable, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTest(), and NUnit.Framework.Internal.TestSuite.Tests.
void NUnit.Framework.Attributes.TestCaseSourceTests.HandlesExceptionInTestCaseSource_GuiDisplay (string lhs, string rhs) inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Attributes.TestCaseSourceTests.MethodTakingTwoStringArrays (string[] a, string[] b) inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
Member Data Documentation
object [] NUnit.Framework.Attributes.TestCaseSourceTests.StaticField static private
Initial value:
=
            { new object[] { "StaticField" } }
object [] NUnit.Framework.Attributes.TestCaseSourceTests.testCases static private
Initial value:
=
        {
            new TestCaseData(
                new string[] { "A" },
                new string[] { "B" })
        }
object [] NUnit.Framework.Attributes.TestCaseSourceTests.MyData static private
Initial value:
= new object[] {
            new object[] { 12, 3, 4 },
            new object[] { 12, 4, 3 },
            new object[] { 12, 6, 2 } }
object [] NUnit.Framework.Attributes.TestCaseSourceTests.MyIntData static private
Initial value:
= new object[] {
            new int[] { 12, 3, 4 },
            new int[] { 12, 4, 3 },
            new int[] { 12, 6, 2 } }
object [] NUnit.Framework.Attributes.TestCaseSourceTests.FourArgs static private
Initial value:
= new object[] {
            new TestCaseData( 12, 3, 4, 0 ),
            new TestCaseData( 12, 4, 3, 0 ),
            new TestCaseData( 12, 5, 2, 2 ) }
int [] NUnit.Framework.Attributes.TestCaseSourceTests.EvenNumbers = new int[] { 2, 4, 6, 8 } static private
object [] NUnit.Framework.Attributes.TestCaseSourceTests.MoreData static private
Initial value:
= new object[] {
            new object[] { 12, 1, 12 },
            new object[] { 12, 2, 6 } }
object [] NUnit.Framework.Attributes.TestCaseSourceTests.Params static private
Initial value:
= new object[] {
            new TestCaseData(24, 3).Returns(8),
            new TestCaseData(24, 2).Returns(12) }
Property Documentation
IEnumerable NUnit.Framework.Attributes.TestCaseSourceTests.StaticProperty static get private
IEnumerable NUnit.Framework.Attributes.TestCaseSourceTests.exception_source static get private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/TestCaseSourceTests.cs