IGLib: NUnit.Framework.Assertions.StringAssertTests Class Reference
NUnit.Framework.Assertions.StringAssertTests Class Reference
Public Member Functions
void Contains ()
void ContainsFails ()
void DoesNotContain ()
void DoesNotContainFails ()
void StartsWith ()
void StartsWithFails ()
void DoesNotStartWith ()
void DoesNotStartWithFails ()
void EndsWith ()
void EndsWithFails ()
void DoesNotEndWith ()
void DoesNotEndWithFails ()
void CaseInsensitiveCompare ()
void CaseInsensitiveCompareFails ()
void IsMatch ()
void IsMatchFails ()
void DifferentEncodingsOfSameStringAreNotEqual ()
Member Function Documentation
void NUnit.Framework.Assertions.StringAssertTests.Contains () inline
References NUnit.Framework.StringAssert.Contains().
void NUnit.Framework.Assertions.StringAssertTests.ContainsFails () inline
References NUnit.Framework.StringAssert.Contains(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.StringAssertTests.DoesNotContain () inline
References NUnit.Framework.StringAssert.DoesNotContain().
void NUnit.Framework.Assertions.StringAssertTests.DoesNotContainFails () inline
References NUnit.Framework.StringAssert.DoesNotContain(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.StringAssertTests.StartsWith () inline
References NUnit.Framework.StringAssert.StartsWith().
void NUnit.Framework.Assertions.StringAssertTests.StartsWithFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.StringAssert.StartsWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.StringAssertTests.DoesNotStartWith () inline
References NUnit.Framework.StringAssert.DoesNotStartWith().
void NUnit.Framework.Assertions.StringAssertTests.DoesNotStartWithFails () inline
References NUnit.Framework.StringAssert.DoesNotStartWith(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.StringAssertTests.EndsWith () inline
References NUnit.Framework.StringAssert.EndsWith().
void NUnit.Framework.Assertions.StringAssertTests.EndsWithFails () inline
References NUnit.Framework.StringAssert.EndsWith(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.StringAssertTests.DoesNotEndWith () inline
References NUnit.Framework.StringAssert.DoesNotEndWith().
void NUnit.Framework.Assertions.StringAssertTests.DoesNotEndWithFails () inline
References NUnit.Framework.StringAssert.DoesNotEndWith(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.StringAssertTests.CaseInsensitiveCompare () inline
References NUnit.Framework.StringAssert.AreEqualIgnoringCase().
void NUnit.Framework.Assertions.StringAssertTests.CaseInsensitiveCompareFails () inline
References NUnit.Framework.StringAssert.AreEqualIgnoringCase(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.StringAssertTests.IsMatch () inline
References NUnit.Framework.StringAssert.IsMatch().
void NUnit.Framework.Assertions.StringAssertTests.IsMatchFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.StringAssert.IsMatch(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.StringAssertTests.DifferentEncodingsOfSameStringAreNotEqual () inline
References NUnit.Framework.Assert.AreNotEqual().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/StringAssertTests.cs