IGLib: IG.Configer.ConfigerConsole Class Reference
IG.Configer.ConfigerConsole Class Reference
Configer console application main class. Currently contains a lot of tests for basic library functionality. Configer is a tool for modification of (XML) configuration file according to an XML script.
Static Public Member Functions
static void TestReporter ()
Tests the error reporter functionality.
static void ConfigerConsoleMain (string[] args)
The main method of Configer Console application.
static void TestConsoleForm ()
Tests consoleform error reporting functionality.
static void PrimeSpiralSum (int size)
Rešitev naloge praštevilska spirala. Seštejemo diagonali praštevilske spirale, v kateri so nanizana samo praštevila (v originalni praštevilski spirali so po vrsti nanizana vsa števila)
Static Private Member Functions
static void Main (string[] args)
Private Attributes
const string Com_Help = "-?"
const string Com_AutoCorrectAll = "-a"
const string Prog_Name ="ConfigerConsole"
const string Prog_VersionStr = "0.0"
Detailed Description
Configer console application main class. Currently contains a lot of tests for basic library functionality. Configer is a tool for modification of (XML) configuration file according to an XML script.
Member Function Documentation
static void IG.Configer.ConfigerConsole.Main (string[] args) inline static private
References IG.Configer.Configer.ReportError().
static void IG.Configer.ConfigerConsole.TestReporter () inline static
Tests the error reporter functionality.
References IG.Lib.ReporterBase.Global, and IG.Lib.ReporterBase.ReportError().
static void IG.Configer.ConfigerConsole.ConfigerConsoleMain (string[] args) inline static
The main method of Configer Console application.
Parameters
args Command-line arguments. These arguments must be transferred from the application's main method.
References IG.Configer.Configer.Configuration, IG.Lib.DataStore.Load(), IG.Configer.Configer.ReportError(), and IG.Configer.Configer.WriteLine().
static void IG.Configer.ConfigerConsole.TestConsoleForm () inline static
Tests consoleform error reporting functionality.
References IG.Configer.Configer.ReportError(), IG.Forms.ConsoleForm.ReportError(), and IG.Forms.ConsoleForm.WriteLine().
static void IG.Configer.ConfigerConsole.PrimeSpiralSum (int size) inline static
Rešitev naloge praštevilska spirala. Seštejemo diagonali praštevilske spirale, v kateri so nanizana samo praštevila (v originalni praštevilski spirali so po vrsti nanizana vsa števila)
Parameters
size size - simenzija matrike praštevil.
Member Data Documentation
const string IG.Configer.ConfigerConsole.Com_Help = "-?" private
const string IG.Configer.ConfigerConsole.Com_AutoCorrectAll = "-a" private
const string IG.Configer.ConfigerConsole.Prog_Name ="ConfigerConsole" private
const string IG.Configer.ConfigerConsole.Prog_VersionStr = "0.0" private
The documentation for this class was generated from the following file:
igapp/configer/configerconsole.cs