IGLib: alglib.testlincgunit Class Reference
alglib.testlincgunit Class Reference
Static Public Member Functions
static bool testlincg (bool silent)
static bool testlincg (bool silent)
static bool _pexec_testlincg (bool silent)
Public Attributes
const double e0 = 1.0E-6
const double maxcond = 30
Static Private Member Functions
static bool complextest (bool silent)
static bool complexres (bool silent)
static bool basictestx (bool silent)
static bool testrcorrectness (bool silent)
static bool basictestiters (bool silent)
static bool krylovsubspacetest (bool silent)
static bool sparsetest (bool silent)
static bool precondtest (bool silent)
static void gramshmidtortnorm (double[,] a, int n, int k, double eps, ref double[,] b, ref int k2)
static bool frombasis (double[] x, double[,] basis, int n, int k, double eps)
static bool complextest (bool silent)
static bool complexres (bool silent)
static bool basictestx (bool silent)
static bool testrcorrectness (bool silent)
static bool basictestiters (bool silent)
static bool krylovsubspacetest (bool silent)
static bool sparsetest (bool silent)
static bool precondtest (bool silent)
static void gramshmidtortnorm (double[,] a, int n, int k, double eps, ref double[,] b, ref int k2)
static bool frombasis (double[] x, double[,] basis, int n, int k, double eps)
Member Function Documentation
static bool alglib.testlincgunit.testlincg (bool silent) inline static
References alglib.testlincgunit.basictestiters(), alglib.testlincgunit.basictestx(), alglib.testlincgunit.complexres(), alglib.testlincgunit.complextest(), alglib.testlincgunit.krylovsubspacetest(), alglib.testlincgunit.precondtest(), alglib.testlincgunit.sparsetest(), and alglib.testlincgunit.testrcorrectness().
Referenced by alglib.testlincgunit._pexec_testlincg(), and _Test.Main().
static bool alglib.testlincgunit.complextest (bool silent) inline static private
References alglib.testlincgunit.e0, alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetrupdatefreq(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsetxrep(), alglib.math.randomreal(), and alglib.matgen.spdmatrixrndcond().
Referenced by alglib.testlincgunit.testlincg().
static bool alglib.testlincgunit.complexres (bool silent) inline static private
References alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsetxrep(), alglib.math.randomreal(), alglib.matgen.spdmatrixrndcond(), and alglib.math.sqr().
Referenced by alglib.testlincgunit.testlincg().
static bool alglib.testlincgunit.basictestx (bool silent) inline static private
References alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsetxrep(), alglib.math.randomreal(), and alglib.matgen.spdmatrixrndcond().
Referenced by alglib.testlincgunit.testlincg().
static bool alglib.testlincgunit.testrcorrectness (bool silent) inline static private
References alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetxrep(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.matgen.spdmatrixrndcond(), and alglib.math.sqr().
Referenced by alglib.testlincgunit.testlincg().
static bool alglib.testlincgunit.basictestiters (bool silent) inline static private
References alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgrestart(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsetxrep(), alglib.math.randomreal(), and alglib.matgen.spdmatrixrndcond().
Referenced by alglib.testlincgunit.testlincg().
static bool alglib.testlincgunit.krylovsubspacetest (bool silent) inline static private
References alglib.testlincgunit.frombasis(), alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetrupdatefreq(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsetxrep(), alglib.math.randomreal(), and alglib.matgen.spdmatrixrndcond().
Referenced by alglib.testlincgunit.testlincg().
static bool alglib.testlincgunit.sparsetest (bool silent) inline static private
References alglib.lincg.lincgcreate(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsolvesparse(), alglib.math.randomreal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseset(), alglib.matgen.spdmatrixrndcond(), and alglib.math.sqr().
Referenced by alglib.testlincgunit.testlincg().
static bool alglib.testlincgunit.precondtest (bool silent) inline static private
References alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgrestart(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsetxrep(), alglib.math.randomreal(), and alglib.matgen.spdmatrixrndcond().
Referenced by alglib.testlincgunit.testlincg().
static void alglib.testlincgunit.gramshmidtortnorm (double a[,], int n, int k, double eps, ref double b[,], ref int k2) inline static private
Referenced by alglib.testlincgunit.frombasis().
static bool alglib.testlincgunit.frombasis (double[] x, double basis[,], int n, int k, double eps) inline static private
References alglib.testlincgunit.gramshmidtortnorm().
Referenced by alglib.testlincgunit.krylovsubspacetest().
static bool alglib.testlincgunit.testlincg (bool silent) inline static
References alglib.testlincgunit.basictestiters(), alglib.testlincgunit.basictestx(), alglib.testlincgunit.complexres(), alglib.testlincgunit.complextest(), alglib.testlincgunit.krylovsubspacetest(), alglib.testlincgunit.precondtest(), alglib.testlincgunit.sparsetest(), and alglib.testlincgunit.testrcorrectness().
static bool alglib.testlincgunit._pexec_testlincg (bool silent) inline static
References alglib.testlincgunit.testlincg().
Referenced by _Test.Main().
static bool alglib.testlincgunit.complextest (bool silent) inline static private
References alglib.testlincgunit.e0, alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetrupdatefreq(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsetxrep(), alglib.math.randomreal(), and alglib.matgen.spdmatrixrndcond().
static bool alglib.testlincgunit.complexres (bool silent) inline static private
References alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsetxrep(), alglib.math.randomreal(), alglib.matgen.spdmatrixrndcond(), and alglib.math.sqr().
static bool alglib.testlincgunit.basictestx (bool silent) inline static private
References alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsetxrep(), alglib.math.randomreal(), and alglib.matgen.spdmatrixrndcond().
static bool alglib.testlincgunit.testrcorrectness (bool silent) inline static private
References alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetxrep(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.matgen.spdmatrixrndcond(), and alglib.math.sqr().
static bool alglib.testlincgunit.basictestiters (bool silent) inline static private
References alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgrestart(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsetxrep(), alglib.math.randomreal(), and alglib.matgen.spdmatrixrndcond().
static bool alglib.testlincgunit.krylovsubspacetest (bool silent) inline static private
References alglib.testlincgunit.frombasis(), alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetrupdatefreq(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsetxrep(), alglib.math.randomreal(), and alglib.matgen.spdmatrixrndcond().
static bool alglib.testlincgunit.sparsetest (bool silent) inline static private
References alglib.lincg.lincgcreate(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsolvesparse(), alglib.math.randomreal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseset(), alglib.matgen.spdmatrixrndcond(), and alglib.math.sqr().
static bool alglib.testlincgunit.precondtest (bool silent) inline static private
References alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgrestart(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetprecdiag(), alglib.lincg.lincgsetprecunit(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsetxrep(), alglib.lincg.lincgsolvesparse(), alglib.apserv.randomnormal(), alglib.math.randomreal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseset(), and alglib.matgen.spdmatrixrndcond().
static void alglib.testlincgunit.gramshmidtortnorm (double a[,], int n, int k, double eps, ref double b[,], ref int k2) inline static private
static bool alglib.testlincgunit.frombasis (double[] x, double basis[,], int n, int k, double eps) inline static private
References alglib.testlincgunit.gramshmidtortnorm().
Member Data Documentation
const double alglib.testlincgunit.e0 = 1.0E-6
Referenced by alglib.testlincgunit.complextest().
const double alglib.testlincgunit.maxcond = 30
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs