IGLib: alglib.lincg Class Reference
alglib.lincg Class Reference
Classes
class lincgreport
class lincgstate
Static Public Member Functions
static void lincgcreate (int n, lincgstate state)
static void lincgsetstartingpoint (lincgstate state, double[] x)
static void lincgsetb (lincgstate state, double[] b)
static void lincgsetcond (lincgstate state, double epsf, int maxits)
static bool lincgiteration (lincgstate state)
static void lincgsolvesparse (lincgstate state, sparse.sparsematrix a, bool isupper, double[] b)
static void lincgresults (lincgstate state, ref double[] x, lincgreport rep)
static void lincgsetrestartfreq (lincgstate state, int srf)
static void lincgsetrupdatefreq (lincgstate state, int freq)
static void lincgsetxrep (lincgstate state, bool needxrep)
static void lincgrestart (lincgstate state)
static void lincgcreate (int n, lincgstate state)
static void lincgsetstartingpoint (lincgstate state, double[] x)
static void lincgsetb (lincgstate state, double[] b)
static void lincgsetprecunit (lincgstate state)
static void lincgsetprecdiag (lincgstate state)
static void lincgsetcond (lincgstate state, double epsf, int maxits)
static bool lincgiteration (lincgstate state)
static void lincgsolvesparse (lincgstate state, sparse.sparsematrix a, bool isupper, double[] b)
static void lincgresults (lincgstate state, ref double[] x, lincgreport rep)
static void lincgsetrestartfreq (lincgstate state, int srf)
static void lincgsetrupdatefreq (lincgstate state, int freq)
static void lincgsetxrep (lincgstate state, bool needxrep)
static void lincgrestart (lincgstate state)
Public Attributes
const double defaultprecision = 1.0E-6
Static Private Member Functions
static void clearrfields (lincgstate state)
static void updateitersdata (lincgstate state)
static void clearrfields (lincgstate state)
static void updateitersdata (lincgstate state)
Member Function Documentation
static void alglib.lincg.lincgcreate (int n, lincgstate state) inline static
References alglib.ap.assert(), alglib.lincg.lincgstate.b, alglib.lincg.lincgstate.cr, alglib.lincg.lincgstate.cx, alglib.lincg.lincgstate.cz, alglib.lincg.defaultprecision, alglib.lincg.lincgstate.epsf, alglib.rcommstate.ia, alglib.lincg.lincgstate.itsbeforerestart, alglib.lincg.lincgstate.itsbeforerupdate, alglib.lincg.lincgstate.maxits, alglib.lincg.lincgstate.mv, alglib.lincg.lincgstate.n, alglib.lincg.lincgstate.p, alglib.lincg.lincgstate.pv, alglib.lincg.lincgstate.r, alglib.rcommstate.ra, alglib.lincg.lincgstate.rstate, alglib.lincg.lincgstate.running, alglib.lincg.lincgstate.rx, alglib.rcommstate.stage, alglib.lincg.lincgstate.startx, alglib.lincg.updateitersdata(), alglib.lincg.lincgstate.x, alglib.lincg.lincgstate.xrep, and alglib.lincg.lincgstate.z.
Referenced by alglib.testlincgunit.basictestiters(), alglib.testlincgunit.basictestx(), alglib.testlincgunit.complexres(), alglib.testlincgunit.complextest(), alglib.testlincgunit.krylovsubspacetest(), alglib.lincgcreate(), alglib.testlincgunit.precondtest(), alglib.testlincgunit.sparsetest(), and alglib.testlincgunit.testrcorrectness().
static void alglib.lincg.lincgsetstartingpoint (lincgstate state, double[] x) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.lincg.lincgstate.n, alglib.lincg.lincgstate.running, and alglib.lincg.lincgstate.startx.
Referenced by alglib.testlincgunit.basictestiters(), alglib.testlincgunit.basictestx(), alglib.testlincgunit.complexres(), alglib.testlincgunit.complextest(), alglib.testlincgunit.krylovsubspacetest(), alglib.lincgsetstartingpoint(), and alglib.testlincgunit.precondtest().
static void alglib.lincg.lincgsetb (lincgstate state, double[] b) inline static
References alglib.ap.assert(), alglib.lincg.lincgstate.b, alglib.apserv.isfinitevector(), alglib.lincg.lincgstate.n, and alglib.lincg.lincgstate.running.
Referenced by alglib.testlincgunit.basictestiters(), alglib.testlincgunit.basictestx(), alglib.testlincgunit.complexres(), alglib.testlincgunit.complextest(), alglib.testlincgunit.krylovsubspacetest(), alglib.lincg.lincgsolvesparse(), alglib.testlincgunit.precondtest(), and alglib.testlincgunit.testrcorrectness().
static void alglib.lincg.lincgsetcond (lincgstate state, double epsf, int maxits) inline static
References alglib.ap.assert(), alglib.lincg.defaultprecision, alglib.lincg.lincgstate.epsf, alglib.math.isfinite(), alglib.lincg.lincgstate.maxits, and alglib.lincg.lincgstate.running.
Referenced by alglib.testlincgunit.basictestiters(), alglib.testlincgunit.basictestx(), alglib.testlincgunit.complexres(), alglib.testlincgunit.complextest(), alglib.testlincgunit.krylovsubspacetest(), alglib.lincgsetcond(), alglib.testlincgunit.precondtest(), alglib.testlincgunit.sparsetest(), and alglib.testlincgunit.testrcorrectness().
static bool alglib.lincg.lincgiteration (lincgstate state) inline static
References alglib.lincg.lincgstate.alpha, alglib.ap.assert(), alglib.lincg.lincgstate.b, alglib.lincg.lincgstate.beta, alglib.lincg.clearrfields(), alglib.lincg.lincgstate.cr, alglib.lincg.lincgstate.cx, alglib.lincg.lincgstate.cz, alglib.lincg.lincgstate.epsf, alglib.rcommstate.ia, alglib.math.isfinite(), alglib.lincg.lincgstate.itsbeforerestart, alglib.lincg.lincgstate.itsbeforerupdate, alglib.lincg.lincgstate.maxits, alglib.lincg.lincgstate.meritfunction, alglib.lincg.lincgstate.mv, alglib.lincg.lincgstate.n, alglib.lincg.lincgstate.needmv, alglib.lincg.lincgstate.needprec, alglib.lincg.lincgstate.needvmv, alglib.lincg.lincgstate.p, alglib.lincg.lincgstate.pv, alglib.lincg.lincgstate.r, alglib.lincg.lincgstate.r2, alglib.rcommstate.ra, alglib.lincg.lincgstate.repiterationscount, alglib.lincg.lincgstate.repnmv, alglib.lincg.lincgstate.repterminationtype, alglib.lincg.lincgstate.rstate, alglib.lincg.lincgstate.running, alglib.lincg.lincgstate.rx, alglib.rcommstate.stage, alglib.lincg.lincgstate.startx, alglib.lincg.updateitersdata(), alglib.lincg.lincgstate.vmv, alglib.lincg.lincgstate.x, alglib.lincg.lincgstate.xrep, alglib.lincg.lincgstate.xupdated, and alglib.lincg.lincgstate.z.
Referenced by alglib.testlincgunit.basictestiters(), alglib.testlincgunit.basictestx(), alglib.testlincgunit.complexres(), alglib.testlincgunit.complextest(), alglib.testlincgunit.krylovsubspacetest(), alglib.lincg.lincgsolvesparse(), alglib.testlincgunit.precondtest(), and alglib.testlincgunit.testrcorrectness().
static void alglib.lincg.lincgsolvesparse (lincgstate state, sparse.sparsematrix a, bool isupper, double[] b) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.lincg.lincgiteration(), alglib.lincg.lincgrestart(), alglib.lincg.lincgsetb(), alglib.lincg.lincgstate.mv, alglib.lincg.lincgstate.n, alglib.lincg.lincgstate.needmv, alglib.lincg.lincgstate.needprec, alglib.lincg.lincgstate.needvmv, alglib.lincg.lincgstate.pv, alglib.sparse.sparsesmv(), alglib.lincg.lincgstate.vmv, and alglib.lincg.lincgstate.x.
Referenced by alglib.lincgsolvesparse(), alglib.testlincgunit.precondtest(), and alglib.testlincgunit.sparsetest().
static void alglib.lincg.lincgresults (lincgstate state, ref double[] x, lincgreport rep) inline static
References alglib.ap.assert(), alglib.lincg.lincgreport.iterationscount, alglib.lincg.lincgstate.n, alglib.lincg.lincgreport.nmv, alglib.lincg.lincgstate.r2, alglib.lincg.lincgreport.r2, alglib.lincg.lincgstate.repiterationscount, alglib.lincg.lincgstate.repnmv, alglib.lincg.lincgstate.repterminationtype, alglib.lincg.lincgstate.running, alglib.lincg.lincgstate.rx, and alglib.lincg.lincgreport.terminationtype.
Referenced by alglib.testlincgunit.basictestiters(), alglib.testlincgunit.basictestx(), alglib.testlincgunit.complexres(), alglib.testlincgunit.complextest(), alglib.lincgresults(), alglib.testlincgunit.precondtest(), alglib.testlincgunit.sparsetest(), and alglib.testlincgunit.testrcorrectness().
static void alglib.lincg.lincgsetrestartfreq (lincgstate state, int srf) inline static
References alglib.ap.assert(), alglib.lincg.lincgstate.itsbeforerestart, and alglib.lincg.lincgstate.running.
Referenced by alglib.lincgsetrestartfreq().
static void alglib.lincg.lincgsetrupdatefreq (lincgstate state, int freq) inline static
References alglib.ap.assert(), alglib.lincg.lincgstate.itsbeforerupdate, and alglib.lincg.lincgstate.running.
Referenced by alglib.testlincgunit.complextest(), alglib.testlincgunit.krylovsubspacetest(), and alglib.lincgsetrupdatefreq().
static void alglib.lincg.lincgsetxrep (lincgstate state, bool needxrep) inline static
References alglib.lincg.lincgstate.xrep.
Referenced by alglib.testlincgunit.basictestiters(), alglib.testlincgunit.basictestx(), alglib.testlincgunit.complexres(), alglib.testlincgunit.complextest(), alglib.testlincgunit.krylovsubspacetest(), alglib.lincgsetxrep(), alglib.testlincgunit.precondtest(), and alglib.testlincgunit.testrcorrectness().
static void alglib.lincg.lincgrestart (lincgstate state) inline static
References alglib.lincg.clearrfields(), alglib.rcommstate.ia, alglib.rcommstate.ra, alglib.lincg.lincgstate.rstate, and alglib.rcommstate.stage.
Referenced by alglib.testlincgunit.basictestiters(), alglib.lincg.lincgsolvesparse(), and alglib.testlincgunit.precondtest().
static void alglib.lincg.clearrfields (lincgstate state) inline static private
References alglib.lincg.lincgstate.needmtv, alglib.lincg.lincgstate.needmv, alglib.lincg.lincgstate.needmv2, alglib.lincg.lincgstate.needprec, alglib.lincg.lincgstate.needvmv, and alglib.lincg.lincgstate.xupdated.
Referenced by alglib.lincg.lincgiteration(), and alglib.lincg.lincgrestart().
static void alglib.lincg.updateitersdata (lincgstate state) inline static private
References alglib.lincg.lincgstate.repiterationscount, alglib.lincg.lincgstate.repnmv, and alglib.lincg.lincgstate.repterminationtype.
Referenced by alglib.lincg.lincgcreate(), and alglib.lincg.lincgiteration().
static void alglib.lincg.lincgcreate (int n, lincgstate state) inline static
References alglib.ap.assert(), alglib.lincg.defaultprecision, and alglib.lincg.updateitersdata().
static void alglib.lincg.lincgsetstartingpoint (lincgstate state, double[] x) inline static
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
static void alglib.lincg.lincgsetb (lincgstate state, double[] b) inline static
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
static void alglib.lincg.lincgsetprecunit (lincgstate state) inline static
References alglib.ap.assert().
Referenced by alglib.lincgsetprecunit(), and alglib.testlincgunit.precondtest().
static void alglib.lincg.lincgsetprecdiag (lincgstate state) inline static
References alglib.ap.assert().
Referenced by alglib.lincgsetprecdiag(), and alglib.testlincgunit.precondtest().
static void alglib.lincg.lincgsetcond (lincgstate state, double epsf, int maxits) inline static
References alglib.ap.assert(), alglib.lincg.defaultprecision, and alglib.math.isfinite().
static bool alglib.lincg.lincgiteration (lincgstate state) inline static
References alglib.ap.assert(), alglib.lincg.clearrfields(), alglib.math.isfinite(), and alglib.lincg.updateitersdata().
static void alglib.lincg.lincgsolvesparse (lincgstate state, sparse.sparsematrix a, bool isupper, double[] b) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.lincg.lincgiteration(), alglib.lincg.lincgrestart(), alglib.lincg.lincgsetb(), alglib.apserv.rvectorsetlengthatleast(), alglib.sparse.sparsegetdiagonal(), alglib.sparse.sparsesmv(), and alglib.math.sqr().
static void alglib.lincg.lincgresults (lincgstate state, ref double[] x, lincgreport rep) inline static
References alglib.ap.assert().
static void alglib.lincg.lincgsetrestartfreq (lincgstate state, int srf) inline static
References alglib.ap.assert().
static void alglib.lincg.lincgsetrupdatefreq (lincgstate state, int freq) inline static
References alglib.ap.assert().
static void alglib.lincg.lincgsetxrep (lincgstate state, bool needxrep) inline static
static void alglib.lincg.lincgrestart (lincgstate state) inline static
References alglib.lincg.clearrfields().
static void alglib.lincg.clearrfields (lincgstate state) inline static private
static void alglib.lincg.updateitersdata (lincgstate state) inline static private
Member Data Documentation
const double alglib.lincg.defaultprecision = 1.0E-6
Referenced by alglib.lincg.lincgcreate(), and alglib.lincg.lincgsetcond().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/solvers.cs