IGLib: NUnit.Framework.Internal.StackFilter Class Reference
NUnit.Framework.Internal.StackFilter Class Reference
StackFilter class is used to remove internal NUnit entries from a stack trace so that the resulting trace provides better information about the test.
Static Public Member Functions
static string Filter (string rawTrace)
Filters a raw stack trace and returns the result.
Static Private Attributes
static readonly Regex assertOrAssumeRegex
Detailed Description
StackFilter class is used to remove internal NUnit entries from a stack trace so that the resulting trace provides better information about the test.
Member Function Documentation
static string NUnit.Framework.Internal.StackFilter.Filter (string rawTrace) inline static
Filters a raw stack trace and returns the result.
Parameters
rawTrace The original stack trace
Returns
A filtered stack trace
Referenced by NUnit.Framework.Internal.Tests.StackFilterTests.FilterLongTrace(), NUnit.Framework.Internal.Tests.StackFilterTests.FilterShortTraceWithAssert(), NUnit.Framework.Internal.Tests.StackFilterTests.FilterShortTraceWithAssume_Trace1(), NUnit.Framework.Internal.TestResult.RecordException(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipFixture().
Member Data Documentation
readonly Regex NUnit.Framework.Internal.StackFilter.assertOrAssumeRegex static private
Initial value:
= new Regex(
            @" NUnit\.Framework\.Ass(ert|ume)\.")
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/StackFilter.cs