IGLib: IPLab.HolesFillingForm Class Reference
IPLab.HolesFillingForm Class Reference
Public Member Functions
HolesFillingForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
Bitmap Image [set]
IFilter Filter [get]
Private Member Functions
void maxWidthBox_TextChanged (object sender, EventArgs e)
void maxHeightBox_TextChanged (object sender, EventArgs e)
void maxWidthTrackBar_ValueChanged (object sender, EventArgs e)
void maxHeightTrackBar_ValueChanged (object sender, EventArgs e)
void modeCombo_SelectedIndexChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
FillHoles filter = new FillHoles()
bool updating = false
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.TextBox maxHeightBox
System.Windows.Forms.GroupBox groupBox1
FilterPreview filterPreview
System.Windows.Forms.TrackBar maxHeightTrackBar
System.Windows.Forms.Button cancelButton
System.Windows.Forms.TrackBar maxWidthTrackBar
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Label label2
System.Windows.Forms.ComboBox modeCombo
System.Windows.Forms.TextBox maxWidthBox
System.Windows.Forms.Label label1
System.Windows.Forms.Button okButton
Constructor & Destructor Documentation
IPLab.HolesFillingForm.HolesFillingForm () inline
References IPLab.HolesFillingForm.filter, IPLab.FilterPreview.Filter, IPLab.HolesFillingForm.filterPreview, IPLab.HolesFillingForm.InitializeComponent(), IPLab.HolesFillingForm.maxHeightBox, IPLab.HolesFillingForm.maxWidthBox, and IPLab.HolesFillingForm.modeCombo.
Member Function Documentation
void IPLab.HolesFillingForm.maxWidthBox_TextChanged (object sender, EventArgs e) inline private
References IPLab.HolesFillingForm.filterPreview, IPLab.HolesFillingForm.maxWidthBox, IPLab.HolesFillingForm.maxWidthTrackBar, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.HolesFillingForm.InitializeComponent().
void IPLab.HolesFillingForm.maxHeightBox_TextChanged (object sender, EventArgs e) inline private
References IPLab.HolesFillingForm.filterPreview, IPLab.HolesFillingForm.maxHeightBox, IPLab.HolesFillingForm.maxHeightTrackBar, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.HolesFillingForm.InitializeComponent().
void IPLab.HolesFillingForm.maxWidthTrackBar_ValueChanged (object sender, EventArgs e) inline private
References IPLab.HolesFillingForm.maxWidthBox, and IPLab.HolesFillingForm.maxWidthTrackBar.
Referenced by IPLab.HolesFillingForm.InitializeComponent().
void IPLab.HolesFillingForm.maxHeightTrackBar_ValueChanged (object sender, EventArgs e) inline private
References IPLab.HolesFillingForm.maxHeightBox, and IPLab.HolesFillingForm.maxHeightTrackBar.
Referenced by IPLab.HolesFillingForm.InitializeComponent().
void IPLab.HolesFillingForm.modeCombo_SelectedIndexChanged (object sender, EventArgs e) inline private
References IPLab.HolesFillingForm.filterPreview, IPLab.HolesFillingForm.modeCombo, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.HolesFillingForm.InitializeComponent().
override void IPLab.HolesFillingForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IPLab.HolesFillingForm.components.
void IPLab.HolesFillingForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IPLab.HolesFillingForm.cancelButton, IPLab.HolesFillingForm.filterPreview, IPLab.HolesFillingForm.groupBox1, IPLab.HolesFillingForm.groupBox2, IPLab.FilterPreview.Image, IPLab.HolesFillingForm.label1, IPLab.HolesFillingForm.label2, IPLab.HolesFillingForm.maxHeightBox, IPLab.HolesFillingForm.maxHeightBox_TextChanged(), IPLab.HolesFillingForm.maxHeightTrackBar, IPLab.HolesFillingForm.maxHeightTrackBar_ValueChanged(), IPLab.HolesFillingForm.maxWidthBox, IPLab.HolesFillingForm.maxWidthBox_TextChanged(), IPLab.HolesFillingForm.maxWidthTrackBar, IPLab.HolesFillingForm.maxWidthTrackBar_ValueChanged(), IPLab.HolesFillingForm.modeCombo, IPLab.HolesFillingForm.modeCombo_SelectedIndexChanged(), and IPLab.HolesFillingForm.okButton.
Referenced by IPLab.HolesFillingForm.HolesFillingForm().
Member Data Documentation
FillHoles IPLab.HolesFillingForm.filter = new FillHoles() private
Referenced by IPLab.HolesFillingForm.HolesFillingForm().
bool IPLab.HolesFillingForm.updating = false private
System.ComponentModel.IContainer IPLab.HolesFillingForm.components = null private
Required designer variable.
Referenced by IPLab.HolesFillingForm.Dispose().
System.Windows.Forms.TextBox IPLab.HolesFillingForm.maxHeightBox private
Referenced by IPLab.HolesFillingForm.HolesFillingForm(), IPLab.HolesFillingForm.InitializeComponent(), IPLab.HolesFillingForm.maxHeightBox_TextChanged(), and IPLab.HolesFillingForm.maxHeightTrackBar_ValueChanged().
System.Windows.Forms.GroupBox IPLab.HolesFillingForm.groupBox1 private
Referenced by IPLab.HolesFillingForm.InitializeComponent().
FilterPreview IPLab.HolesFillingForm.filterPreview private
Referenced by IPLab.HolesFillingForm.HolesFillingForm(), IPLab.HolesFillingForm.InitializeComponent(), IPLab.HolesFillingForm.maxHeightBox_TextChanged(), IPLab.HolesFillingForm.maxWidthBox_TextChanged(), and IPLab.HolesFillingForm.modeCombo_SelectedIndexChanged().
System.Windows.Forms.TrackBar IPLab.HolesFillingForm.maxHeightTrackBar private
Referenced by IPLab.HolesFillingForm.InitializeComponent(), IPLab.HolesFillingForm.maxHeightBox_TextChanged(), and IPLab.HolesFillingForm.maxHeightTrackBar_ValueChanged().
System.Windows.Forms.Button IPLab.HolesFillingForm.cancelButton private
Referenced by IPLab.HolesFillingForm.InitializeComponent().
System.Windows.Forms.TrackBar IPLab.HolesFillingForm.maxWidthTrackBar private
Referenced by IPLab.HolesFillingForm.InitializeComponent(), IPLab.HolesFillingForm.maxWidthBox_TextChanged(), and IPLab.HolesFillingForm.maxWidthTrackBar_ValueChanged().
System.Windows.Forms.GroupBox IPLab.HolesFillingForm.groupBox2 private
Referenced by IPLab.HolesFillingForm.InitializeComponent().
System.Windows.Forms.Label IPLab.HolesFillingForm.label2 private
Referenced by IPLab.HolesFillingForm.InitializeComponent().
System.Windows.Forms.ComboBox IPLab.HolesFillingForm.modeCombo private
Referenced by IPLab.HolesFillingForm.HolesFillingForm(), IPLab.HolesFillingForm.InitializeComponent(), and IPLab.HolesFillingForm.modeCombo_SelectedIndexChanged().
System.Windows.Forms.TextBox IPLab.HolesFillingForm.maxWidthBox private
Referenced by IPLab.HolesFillingForm.HolesFillingForm(), IPLab.HolesFillingForm.InitializeComponent(), IPLab.HolesFillingForm.maxWidthBox_TextChanged(), and IPLab.HolesFillingForm.maxWidthTrackBar_ValueChanged().
System.Windows.Forms.Label IPLab.HolesFillingForm.label1 private
Referenced by IPLab.HolesFillingForm.InitializeComponent().
System.Windows.Forms.Button IPLab.HolesFillingForm.okButton private
Referenced by IPLab.HolesFillingForm.InitializeComponent().
Property Documentation
Bitmap IPLab.HolesFillingForm.Image set
Referenced by IPLab.ImageDoc.fillHolesMenuItem_Click().
IFilter IPLab.HolesFillingForm.Filter get
Referenced by IPLab.ImageDoc.fillHolesMenuItem_Click().
The documentation for this class was generated from the following files:
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/HolesFillingForm.cs
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/HolesFillingForm.Designer.cs