IGLib: alglib.testablasunit Class Reference
alglib.testablasunit Class Reference
Static Public Member Functions
static bool testablas (bool silent)
static bool testablas (bool silent)
static bool _pexec_testablas (bool silent)
Static Private Member Functions
static void naivematrixmatrixmultiply (double[,] a, int ai1, int ai2, int aj1, int aj2, bool transa, double[,] b, int bi1, int bi2, int bj1, int bj2, bool transb, double alpha, ref double[,] c, int ci1, int ci2, int cj1, int cj2, double beta)
static bool testtrsm (int minn, int maxn)
static bool testsyrk (int minn, int maxn)
static bool testgemm (int minn, int maxn)
static bool testtrans (int minn, int maxn)
static bool testrank1 (int minn, int maxn)
static bool testmv (int minn, int maxn)
static bool testcopy (int minn, int maxn)
static void refcmatrixrighttrsm (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref complex[,] x, int i2, int j2)
static void refcmatrixlefttrsm (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref complex[,] x, int i2, int j2)
static void refrmatrixrighttrsm (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref double[,] x, int i2, int j2)
static void refrmatrixlefttrsm (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref double[,] x, int i2, int j2)
static bool internalcmatrixtrinverse (ref complex[,] a, int n, bool isupper, bool isunittriangular)
static bool internalrmatrixtrinverse (ref double[,] a, int n, bool isupper, bool isunittriangular)
static void refcmatrixsyrk (int n, int k, double alpha, complex[,] a, int ia, int ja, int optypea, double beta, ref complex[,] c, int ic, int jc, bool isupper)
static void refrmatrixsyrk (int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double beta, ref double[,] c, int ic, int jc, bool isupper)
static void refcmatrixgemm (int m, int n, int k, complex alpha, complex[,] a, int ia, int ja, int optypea, complex[,] b, int ib, int jb, int optypeb, complex beta, ref complex[,] c, int ic, int jc)
static void refrmatrixgemm (int m, int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double[,] b, int ib, int jb, int optypeb, double beta, ref double[,] c, int ic, int jc)
static void naivematrixmatrixmultiply (double[,] a, int ai1, int ai2, int aj1, int aj2, bool transa, double[,] b, int bi1, int bi2, int bj1, int bj2, bool transb, double alpha, ref double[,] c, int ci1, int ci2, int cj1, int cj2, double beta)
static bool testtrsm (int minn, int maxn)
static bool testsyrk (int minn, int maxn)
static bool testgemm (int minn, int maxn)
static bool testtrans (int minn, int maxn)
static bool testrank1 (int minn, int maxn)
static bool testmv (int minn, int maxn)
static bool testcopy (int minn, int maxn)
static void refcmatrixrighttrsm (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref complex[,] x, int i2, int j2)
static void refcmatrixlefttrsm (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref complex[,] x, int i2, int j2)
static void refrmatrixrighttrsm (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref double[,] x, int i2, int j2)
static void refrmatrixlefttrsm (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref double[,] x, int i2, int j2)
static bool internalcmatrixtrinverse (ref complex[,] a, int n, bool isupper, bool isunittriangular)
static bool internalrmatrixtrinverse (ref double[,] a, int n, bool isupper, bool isunittriangular)
static void refcmatrixsyrk (int n, int k, double alpha, complex[,] a, int ia, int ja, int optypea, double beta, ref complex[,] c, int ic, int jc, bool isupper)
static void refrmatrixsyrk (int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double beta, ref double[,] c, int ic, int jc, bool isupper)
static void refcmatrixgemm (int m, int n, int k, complex alpha, complex[,] a, int ia, int ja, int optypea, complex[,] b, int ib, int jb, int optypeb, complex beta, ref complex[,] c, int ic, int jc)
static void refrmatrixgemm (int m, int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double[,] b, int ib, int jb, int optypeb, double beta, ref double[,] c, int ic, int jc)
Member Function Documentation
static bool alglib.testablasunit.testablas (bool silent) inline static
References alglib.ablas.ablasblocksize(), alglib.math.machineepsilon, alglib.testablasunit.testcopy(), alglib.testablasunit.testgemm(), alglib.testablasunit.testmv(), alglib.testablasunit.testrank1(), alglib.testablasunit.testsyrk(), alglib.testablasunit.testtrans(), and alglib.testablasunit.testtrsm().
Referenced by alglib.testablasunit._pexec_testablas(), and _Test.Main().
static void alglib.testablasunit.naivematrixmatrixmultiply (double a[,], int ai1, int ai2, int aj1, int aj2, bool transa, double b[,], int bi1, int bi2, int bj1, int bj2, bool transb, double alpha, ref double c[,], int ci1, int ci2, int cj1, int cj2, double beta) inline static private
References alglib.ap.assert(), and alglib.beta().
static bool alglib.testablasunit.testtrsm (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.ablas.cmatrixlefttrsm(), alglib.ablas.cmatrixrighttrsm(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testablasunit.refcmatrixlefttrsm(), alglib.testablasunit.refcmatrixrighttrsm(), alglib.testablasunit.refrmatrixlefttrsm(), alglib.testablasunit.refrmatrixrighttrsm(), alglib.ablas.rmatrixlefttrsm(), alglib.ablas.rmatrixrighttrsm(), alglib.math.sqr(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testablasunit.testablas().
static bool alglib.testablasunit.testsyrk (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.beta(), alglib.ablas.cmatrixsyrk(), alglib.math.conj(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testablasunit.refcmatrixsyrk(), alglib.testablasunit.refrmatrixsyrk(), alglib.ablas.rmatrixsyrk(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testablasunit.testablas().
static bool alglib.testablasunit.testgemm (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.ablas.cmatrixgemm(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testablasunit.refcmatrixgemm(), alglib.testablasunit.refrmatrixgemm(), alglib.ablas.rmatrixgemm(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testablasunit.testablas().
static bool alglib.testablasunit.testtrans (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.ablas.cmatrixtranspose(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.ablas.rmatrixtranspose(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testablasunit.testablas().
static bool alglib.testablasunit.testrank1 (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.ablas.cmatrixrank1(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.ablas.rmatrixrank1(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testablasunit.testablas().
static bool alglib.testablasunit.testmv (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.ablas.cmatrixmv(), alglib.math.conj(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.ablas.rmatrixmv(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testablasunit.testablas().
static bool alglib.testablasunit.testcopy (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.ablas.cmatrixcopy(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.ablas.rmatrixcopy(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testablasunit.testablas().
static void alglib.testablasunit.refcmatrixrighttrsm (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref complex x[,], int i2, int j2) inline static private
References alglib.math.conj(), and alglib.testablasunit.internalcmatrixtrinverse().
Referenced by alglib.testablasunit.testtrsm().
static void alglib.testablasunit.refcmatrixlefttrsm (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref complex x[,], int i2, int j2) inline static private
References alglib.math.conj(), and alglib.testablasunit.internalcmatrixtrinverse().
Referenced by alglib.testablasunit.testtrsm().
static void alglib.testablasunit.refrmatrixrighttrsm (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref double x[,], int i2, int j2) inline static private
References alglib.testablasunit.internalrmatrixtrinverse().
Referenced by alglib.testablasunit.testtrsm().
static void alglib.testablasunit.refrmatrixlefttrsm (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref double x[,], int i2, int j2) inline static private
References alglib.testablasunit.internalrmatrixtrinverse().
Referenced by alglib.testablasunit.testtrsm().
static bool alglib.testablasunit.internalcmatrixtrinverse (ref complex a[,], int n, bool isupper, bool isunittriangular) inline static private
Referenced by alglib.testablasunit.refcmatrixlefttrsm(), and alglib.testablasunit.refcmatrixrighttrsm().
static bool alglib.testablasunit.internalrmatrixtrinverse (ref double a[,], int n, bool isupper, bool isunittriangular) inline static private
Referenced by alglib.testablasunit.refrmatrixlefttrsm(), and alglib.testablasunit.refrmatrixrighttrsm().
static void alglib.testablasunit.refcmatrixsyrk (int n, int k, double alpha, complex a[,], int ia, int ja, int optypea, double beta, ref complex c[,], int ic, int jc, bool isupper) inline static private
References alglib.beta(), and alglib.math.conj().
Referenced by alglib.testablasunit.testsyrk().
static void alglib.testablasunit.refrmatrixsyrk (int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double beta, ref double c[,], int ic, int jc, bool isupper) inline static private
References alglib.beta().
Referenced by alglib.testablasunit.testsyrk().
static void alglib.testablasunit.refcmatrixgemm (int m, int n, int k, complex alpha, complex a[,], int ia, int ja, int optypea, complex b[,], int ib, int jb, int optypeb, complex beta, ref complex c[,], int ic, int jc) inline static private
References alglib.math.conj().
Referenced by alglib.testablasunit.testgemm().
static void alglib.testablasunit.refrmatrixgemm (int m, int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double b[,], int ib, int jb, int optypeb, double beta, ref double c[,], int ic, int jc) inline static private
Referenced by alglib.testablasunit.testgemm().
static bool alglib.testablasunit.testablas (bool silent) inline static
References alglib.ablas.ablasblocksize(), alglib.math.machineepsilon, alglib.testablasunit.testcopy(), alglib.testablasunit.testgemm(), alglib.testablasunit.testmv(), alglib.testablasunit.testrank1(), alglib.testablasunit.testsyrk(), alglib.testablasunit.testtrans(), and alglib.testablasunit.testtrsm().
static bool alglib.testablasunit._pexec_testablas (bool silent) inline static
References alglib.testablasunit.testablas().
Referenced by _Test.Main().
static void alglib.testablasunit.naivematrixmatrixmultiply (double a[,], int ai1, int ai2, int aj1, int aj2, bool transa, double b[,], int bi1, int bi2, int bj1, int bj2, bool transb, double alpha, ref double c[,], int ci1, int ci2, int cj1, int cj2, double beta) inline static private
References alglib.ap.assert(), and alglib.beta().
static bool alglib.testablasunit.testtrsm (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.ablas.cmatrixlefttrsm(), alglib.ablas.cmatrixrighttrsm(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testablasunit.refcmatrixlefttrsm(), alglib.testablasunit.refcmatrixrighttrsm(), alglib.testablasunit.refrmatrixlefttrsm(), alglib.testablasunit.refrmatrixrighttrsm(), alglib.ablas.rmatrixlefttrsm(), alglib.ablas.rmatrixrighttrsm(), alglib.math.sqr(), alglib.complex.x, and alglib.complex.y.
static bool alglib.testablasunit.testsyrk (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.beta(), alglib.ablas.cmatrixsyrk(), alglib.math.conj(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testablasunit.refcmatrixsyrk(), alglib.testablasunit.refrmatrixsyrk(), alglib.ablas.rmatrixsyrk(), alglib.complex.x, and alglib.complex.y.
static bool alglib.testablasunit.testgemm (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.ablas.cmatrixgemm(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testablasunit.refcmatrixgemm(), alglib.testablasunit.refrmatrixgemm(), alglib.ablas.rmatrixgemm(), alglib.complex.x, and alglib.complex.y.
static bool alglib.testablasunit.testtrans (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.ablas.cmatrixtranspose(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.ablas.rmatrixtranspose(), alglib.complex.x, and alglib.complex.y.
static bool alglib.testablasunit.testrank1 (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.ablas.cmatrixrank1(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.ablas.rmatrixrank1(), alglib.complex.x, and alglib.complex.y.
static bool alglib.testablasunit.testmv (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.ablas.cmatrixmv(), alglib.math.conj(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.ablas.rmatrixmv(), alglib.complex.x, and alglib.complex.y.
static bool alglib.testablasunit.testcopy (int minn, int maxn) inline static private
References alglib.math.abscomplex(), alglib.ablas.cmatrixcopy(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.ablas.rmatrixcopy(), alglib.complex.x, and alglib.complex.y.
static void alglib.testablasunit.refcmatrixrighttrsm (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref complex x[,], int i2, int j2) inline static private
References alglib.math.conj(), and alglib.testablasunit.internalcmatrixtrinverse().
static void alglib.testablasunit.refcmatrixlefttrsm (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref complex x[,], int i2, int j2) inline static private
References alglib.math.conj(), and alglib.testablasunit.internalcmatrixtrinverse().
static void alglib.testablasunit.refrmatrixrighttrsm (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref double x[,], int i2, int j2) inline static private
References alglib.testablasunit.internalrmatrixtrinverse().
static void alglib.testablasunit.refrmatrixlefttrsm (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref double x[,], int i2, int j2) inline static private
References alglib.testablasunit.internalrmatrixtrinverse().
static bool alglib.testablasunit.internalcmatrixtrinverse (ref complex a[,], int n, bool isupper, bool isunittriangular) inline static private
static bool alglib.testablasunit.internalrmatrixtrinverse (ref double a[,], int n, bool isupper, bool isunittriangular) inline static private
static void alglib.testablasunit.refcmatrixsyrk (int n, int k, double alpha, complex a[,], int ia, int ja, int optypea, double beta, ref complex c[,], int ic, int jc, bool isupper) inline static private
References alglib.beta(), and alglib.math.conj().
static void alglib.testablasunit.refrmatrixsyrk (int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double beta, ref double c[,], int ic, int jc, bool isupper) inline static private
References alglib.beta().
static void alglib.testablasunit.refcmatrixgemm (int m, int n, int k, complex alpha, complex a[,], int ia, int ja, int optypea, complex b[,], int ib, int jb, int optypeb, complex beta, ref complex c[,], int ic, int jc) inline static private
References alglib.math.conj().
static void alglib.testablasunit.refrmatrixgemm (int m, int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double b[,], int ib, int jb, int optypeb, double beta, ref double c[,], int ic, int jc) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs