IGLib: FutureTest.FutureTest Class Reference
FutureTest.FutureTest Class Reference
Public Member Functions
void STA ()
void Bell1 ()
void TestCumulant2 ()
void TestNormal ()
void Repro ()
void BetaExercise ()
void BesselExactTest ()
void TestGammaValues ()
void TestConstants ()
void AiryTest ()
void ComputeChiTest ()
void ComputeBesselExpansionParameter (double z, out double xi, out double phi, out double[] a, out double[] b)
void BesselUAE ()
void BesselFix ()
void BesselYSeries ()
void CumulantTest ()
void TwoSampleKS ()
void ChiSquareDistribution ()
void TwoSampleKS2 ()
void Test2 ()
void Test12 ()
void ET ()
void EigenTest ()
void TestNormalOrderStatistic ()
void TestInverseKS ()
void TestCubicHermite ()
void TestParabolicFit ()
delegate void FuncWithDerivative (double x, out double f, out double fp)
double FindMinimum (Func< double, double > f, double x, double d, EvaluationSettings settings)
void TestMinimizationWithoutDerivative ()
void TestOldMinimization ()
void TestMinimizationWithDerivative ()
void MultiRootTest ()
void TestBeta ()
Static Public Member Functions
static double InverseQ (double Q)
static double ApproximateInverseBetaSeries (double a, double b, double P)
static double ApproximateInverseBeta (double a, double b, double P)
static double RefineInverseBeta (double a, double b, double P, double x)
Private Member Functions
void TwoByTwoSchur (ref double a11, ref double a12, ref double a21, ref double a22, out double s, out double c)
double FindMinimumWithDerivative (FuncWithDerivative f, double a, double b)
double FindMinimumWithDerivative (FuncWithDerivative f, double a, double b, double u, double fu, double fpu, double v, double fv, double fpv, EvaluationSettings settings)
void CosineWithDerivative (double x, out double f, out double fp)
void GammaWithDerivative (double x, out double f, out double fp)
void XLogXWithDerivative (double x, out double f, out double fp)
void ExponentialDecayWithDerivative (double x, out double f, out double fp)
void AbsoluteValueWithDerivative (double x, out double f, out double fp)
void CoshWithDerivative (double x, out double f, out double fp)
void SechWithDerivative (double x, out double f, out double fp)
void FourthPowerWithDerivative (double x, out double f, out double fp)
void FermatFactor (int n)
void PollardRhoFactor (int n)
Static Private Member Functions
static double BesselY (int n, double x)
static double BesselY_Series2 (int n, double x)
static double BesselY_Series (int n, double x)
static double EqualKS (int n, int c)
static void Frexp (double value, out bool sign, out long mantissa, out int exponent)
static double GaussHermiteIntegrate (Func< double, double > f)
static double NormalMeanOrderStatisticExpansion (int i, int n)
static double NormalMeanOrderStatisticExpansion2 (int i, int n)
static void ComputePowerSet (double y, out double y4, out double y9, out double y16, out double y25)
static void ParabolicFit (double x1, double f1, double x2, double f2, double x3, double f3, out double x0, out double fpp)
static void CubicHermiteMinimum (double x0, double f0, double m0, double x1, double f1, double m1, out double x, out double fpp)
static void CubicHermiteMinimum (double f0, double m0, double f1, double m1, out double t, out double fpp)
static double FindMinimum (Func< double, double > f, double a, double b)
static double FindMinimum (Func< double, double > f, double a, double b, double u, double fu, double v, double fv, double w, double fw, EvaluationSettings settings, int count)
static void WriteMatrix (AnyRectangularMatrix A)
Static Private Attributes
static double[] xs
static double[] ws
static readonly double SqrtTwo = Math.Sqrt(2.0)
static readonly double SqrtPI = Math.Sqrt(Math.PI)
Member Function Documentation
void FutureTest.FutureTest.STA () inline
References Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMinimum(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.MoreMath.Sqr().
void FutureTest.FutureTest.Bell1 () inline
References Meta.Numerics.Matrices.RectangularMatrix.SingularValueDecomposition().
void FutureTest.FutureTest.TestCumulant2 () inline
References Meta.Numerics.Statistics.Distributions.MomentMath.CentralToCumulant(), Meta.Numerics.Statistics.Distributions.MomentMath.CentralToRaw(), Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Cumulant(), Meta.Numerics.Statistics.Distributions.MomentMath.CumulantToCentral(), Meta.Numerics.Statistics.Distributions.MomentMath.CumulantToRaw(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Mean, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Moment(), and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.MomentAboutMean().
void FutureTest.FutureTest.TestNormal () inline
References Meta.Numerics.Statistics.Distributions.NormalDistribution.InverseLeftProbability(), and Meta.Numerics.Statistics.Distributions.NormalDistribution.InverseRightProbability().
void FutureTest.FutureTest.Repro () inline
void FutureTest.FutureTest.BetaExercise () inline
void FutureTest.FutureTest.BesselExactTest () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), and Meta.Numerics.MoreMath.Sqr().
void FutureTest.FutureTest.TestGammaValues () inline
References Meta.Numerics.Functions.AdvancedMath.Gamma().
void FutureTest.FutureTest.TestConstants () inline
void FutureTest.FutureTest.AiryTest () inline
References Meta.Numerics.Functions.AdvancedMath.Airy(), Meta.Numerics.Functions.AdvancedMath.AiryAi(), and Meta.Numerics.Functions.SolutionPair.FirstSolutionValue.
void FutureTest.FutureTest.ComputeChiTest () inline
References Meta.Numerics.Functions.AdvancedMath.Airy(), Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Functions.SolutionPair.FirstSolutionDerivative, Meta.Numerics.Functions.SolutionPair.FirstSolutionValue, and Meta.Numerics.MoreMath.Pow().
void FutureTest.FutureTest.ComputeBesselExpansionParameter (double z, out double xi, out double phi, out double[] a, out double[] b) inline
void FutureTest.FutureTest.BesselUAE () inline
References Meta.Numerics.Functions.AdvancedMath.Airy(), Meta.Numerics.Functions.SolutionPair.FirstSolutionDerivative, Meta.Numerics.Functions.SolutionPair.FirstSolutionValue, Meta.Numerics.Functions.SolutionPair.SecondSolutionDerivative, and Meta.Numerics.Functions.SolutionPair.SecondSolutionValue.
void FutureTest.FutureTest.BesselFix () inline
References Meta.Numerics.Functions.AdvancedMath.Airy(), Meta.Numerics.Functions.SolutionPair.FirstSolutionDerivative, Meta.Numerics.Functions.SolutionPair.FirstSolutionValue, Meta.Numerics.Functions.SolutionPair.SecondSolutionDerivative, and Meta.Numerics.Functions.SolutionPair.SecondSolutionValue.
void FutureTest.FutureTest.BesselYSeries () inline
References Meta.Numerics.Functions.AdvancedMath.BesselY().
static double FutureTest.FutureTest.BesselY (int n, double x) inline static private
References Meta.Numerics.Functions.AdvancedMath.EulerGamma, Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.Functions.AdvancedIntegerMath.HarmonicNumber(), and Meta.Numerics.MoreMath.Pow().
static double FutureTest.FutureTest.BesselY_Series2 (int n, double x) inline static private
References Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), and Meta.Numerics.MoreMath.Pow().
static double FutureTest.FutureTest.BesselY_Series (int n, double x) inline static private
References Meta.Numerics.Functions.AdvancedMath.EulerGamma, Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.Functions.AdvancedIntegerMath.HarmonicNumber(), and Meta.Numerics.MoreMath.Pow().
void FutureTest.FutureTest.CumulantTest () inline
References Meta.Numerics.Statistics.Distributions.MomentMath.CumulantToCentral(), Meta.Numerics.Statistics.Distributions.MomentMath.CumulantToRaw(), Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.Statistics.Distributions.Distribution.Moment(), Meta.Numerics.Statistics.Distributions.Distribution.MomentAboutMean(), and Meta.Numerics.Statistics.Distributions.MomentMath.RawToCumulant().
void FutureTest.FutureTest.TwoSampleKS () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.GCF(), Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.LatticePathSum(), Meta.Numerics.Functions.AdvancedIntegerMath.LCM(), Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.Maximum, and Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.Minimum.
void FutureTest.FutureTest.ChiSquareDistribution () inline
References Meta.Numerics.Statistics.Histogram.Add(), Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Histogram.ChiSquaredTest(), Meta.Numerics.Statistics.Distributions.ChiSquaredDistribution.DegreesOfFreedom, Meta.Numerics.Statistics.TestResult.Distribution, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.GetRandomValue(), Meta.Numerics.Statistics.Sample.KuiperTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, and Meta.Numerics.Statistics.TestResult.Statistic.
void FutureTest.FutureTest.TwoSampleKS2 () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Histogram.ChiSquaredTest(), Meta.Numerics.Statistics.Histogram.Count, Meta.Numerics.Statistics.Distributions.ChiSquaredDistribution.DegreesOfFreedom, Meta.Numerics.Statistics.TestResult.Distribution, Meta.Numerics.Statistics.Distributions.NormalDistribution.GetRandomValue(), Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Functions.AdvancedIntegerMath.LCM(), Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.ProbabilityMass(), Meta.Numerics.Statistics.TestResult.RightProbability, Meta.Numerics.MoreMath.Sqr(), and Meta.Numerics.Statistics.TestResult.Statistic.
static double FutureTest.FutureTest.EqualKS (int n, int c) inline static private
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient().
void FutureTest.FutureTest.Test2 () inline
static void FutureTest.FutureTest.Frexp (double value, out bool sign, out long mantissa, out int exponent) inline static private
void FutureTest.FutureTest.Test12 () inline
void FutureTest.FutureTest.ET () inline
References Meta.Numerics.Matrices.SquareMatrix.Eigensystem().
void FutureTest.FutureTest.TwoByTwoSchur (ref double a11, ref double a12, ref double a21, ref double a22, out double s, out double c) inline private
References Meta.Numerics.MoreMath.Hypot().
void FutureTest.FutureTest.EigenTest () inline
References Meta.Numerics.Matrices.SquareMatrix.Transpose().
static double FutureTest.FutureTest.GaussHermiteIntegrate (Func< double, double > f) inline static private
static double FutureTest.FutureTest.NormalMeanOrderStatisticExpansion (int i, int n) inline static private
References Meta.Numerics.Functions.AdvancedMath.InverseErf().
static double FutureTest.FutureTest.NormalMeanOrderStatisticExpansion2 (int i, int n) inline static private
References Meta.Numerics.Functions.AdvancedMath.InverseErf().
void FutureTest.FutureTest.TestNormalOrderStatistic () inline
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Statistics.Distributions.Distribution.LeftProbability(), Meta.Numerics.Functions.AdvancedIntegerMath.LogFactorial(), Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Statistics.Distributions.Distribution.RightProbability().
static double FutureTest.FutureTest.InverseQ (double Q) inline static
static void FutureTest.FutureTest.ComputePowerSet (double y, out double y4, out double y9, out double y16, out double y25) inline static private
void FutureTest.FutureTest.TestInverseKS () inline
References Meta.Numerics.Statistics.Distributions.Distribution.InverseRightProbability().
static void FutureTest.FutureTest.ParabolicFit (double x1, double f1, double x2, double f2, double x3, double f3, out double x0, out double fpp) inline static private
static void FutureTest.FutureTest.CubicHermiteMinimum (double x0, double f0, double m0, double x1, double f1, double m1, out double x, out double fpp) inline static private
static void FutureTest.FutureTest.CubicHermiteMinimum (double f0, double m0, double f1, double m1, out double t, out double fpp) inline static private
References Meta.Numerics.MoreMath.Pow().
void FutureTest.FutureTest.TestCubicHermite () inline
void FutureTest.FutureTest.TestParabolicFit () inline
static double FutureTest.FutureTest.FindMinimum (Func< double, double > f, double a, double b) inline static private
static double FutureTest.FutureTest.FindMinimum (Func< double, double > f, double a, double b, double u, double fu, double v, double fv, double w, double fw, EvaluationSettings settings, int count) inline static private
References Meta.Numerics.Analysis.EvaluationSettings.AbsolutePrecision, Meta.Numerics.Analysis.EvaluationSettings.EvaluationBudget, Meta.Numerics.Functions.AdvancedMath.GoldenRatio, and Meta.Numerics.Analysis.EvaluationSettings.RelativePrecision.
delegate void FutureTest.FutureTest.FuncWithDerivative (double x, out double f, out double fp)
double FutureTest.FutureTest.FindMinimumWithDerivative (FuncWithDerivative f, double a, double b) inline private
double FutureTest.FutureTest.FindMinimumWithDerivative (FuncWithDerivative f, double a, double b, double u, double fu, double fpu, double v, double fv, double fpv, EvaluationSettings settings) inline private
References Meta.Numerics.Analysis.EvaluationSettings.AbsolutePrecision, Meta.Numerics.Analysis.EvaluationSettings.EvaluationBudget, and Meta.Numerics.Analysis.EvaluationSettings.RelativePrecision.
double FutureTest.FutureTest.FindMinimum (Func< double, double > f, double x, double d, EvaluationSettings settings) inline
References Meta.Numerics.Analysis.EvaluationSettings.EvaluationBudget, and Meta.Numerics.Functions.AdvancedMath.GoldenRatio.
void FutureTest.FutureTest.TestMinimizationWithoutDerivative () inline
References Meta.Numerics.Functions.AdvancedMath.Gamma().
void FutureTest.FutureTest.TestOldMinimization () inline
References Meta.Numerics.Analysis.FunctionMath.FindMinimum(), and Meta.Numerics.Interval.FromEndpoints().
void FutureTest.FutureTest.TestMinimizationWithDerivative () inline
void FutureTest.FutureTest.CosineWithDerivative (double x, out double f, out double fp) inline private
void FutureTest.FutureTest.GammaWithDerivative (double x, out double f, out double fp) inline private
References Meta.Numerics.Functions.AdvancedMath.Gamma(), and Meta.Numerics.Functions.AdvancedMath.Psi().
void FutureTest.FutureTest.XLogXWithDerivative (double x, out double f, out double fp) inline private
void FutureTest.FutureTest.ExponentialDecayWithDerivative (double x, out double f, out double fp) inline private
void FutureTest.FutureTest.AbsoluteValueWithDerivative (double x, out double f, out double fp) inline private
void FutureTest.FutureTest.CoshWithDerivative (double x, out double f, out double fp) inline private
void FutureTest.FutureTest.SechWithDerivative (double x, out double f, out double fp) inline private
void FutureTest.FutureTest.FourthPowerWithDerivative (double x, out double f, out double fp) inline private
void FutureTest.FutureTest.FermatFactor (int n) inline private
void FutureTest.FutureTest.PollardRhoFactor (int n) inline private
References Meta.Numerics.Functions.AdvancedIntegerMath.GCF(), and Meta.Numerics.Functions.AdvancedIntegerMath.PowMod().
void FutureTest.FutureTest.MultiRootTest () inline
References Meta.Numerics.Analysis.FunctionMath.FindZero().
static double FutureTest.FutureTest.ApproximateInverseBetaSeries (double a, double b, double P) inline static
References Meta.Numerics.Functions.AdvancedMath.Beta(), and Meta.Numerics.MoreMath.Pow().
static double FutureTest.FutureTest.ApproximateInverseBeta (double a, double b, double P) inline static
References Meta.Numerics.Functions.AdvancedMath.Beta().
static double FutureTest.FutureTest.RefineInverseBeta (double a, double b, double P, double x) inline static
References Meta.Numerics.Functions.AdvancedMath.Beta(), and Meta.Numerics.Functions.AdvancedMath.LeftRegularizedBeta().
void FutureTest.FutureTest.TestBeta () inline
References Meta.Numerics.Statistics.Distributions.NormalDistribution.InverseLeftProbability(), and Meta.Numerics.Functions.AdvancedMath.LeftRegularizedBeta().
static void FutureTest.FutureTest.WriteMatrix (AnyRectangularMatrix A) inline static private
References Meta.Numerics.Matrices.AnyMatrix< T >.ColumnCount, and Meta.Numerics.Matrices.AnyMatrix< T >.RowCount.
Member Data Documentation
double [] FutureTest.FutureTest.xs static private
Initial value:
= new double[] {
            0.22441454747251558515,
            0.67417110703721223600,
            1.1267608176112450721,
            1.5842500109616941485,
            2.0490035736616989118,
            2.5238810170114269742,
            3.0125461375655648257,
            3.5200068130345247113,
            4.0536644024481495039,
            4.6256627564237872650,
            5.2593829276680443674,
            6.0159255614257397173
        }
double [] FutureTest.FutureTest.ws static private
Initial value:
= new double[] {
            0.42693116386869924965,
            0.28617953534644301790,
            0.12773962178455916065,
            3.744547050323074601E-2,
            7.04835581007267097E-3,
            8.23692482688417458E-4,
            5.68869163640437977E-5,
            2.15824570490233363E-6,
            4.01897117494142968E-8,
            3.04625426998756390E-10,
            6.58462024307817006E-13,
            1.66436849648910887E-16
        }
readonly double FutureTest.FutureTest.SqrtTwo = Math.Sqrt(2.0) static private
readonly double FutureTest.FutureTest.SqrtPI = Math.Sqrt(Math.PI) static private
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/FutureTest.cs