IGLib: Test.AdvancedIntegerMathTest Class Reference
Test.AdvancedIntegerMathTest Class Reference
Public Member Functions
void FactorialSpecialCases ()
void FactorialRecurrence ()
void FactorialNegativeArgumentTest ()
void DoubleFactorialSpecialCases ()
void FactorialDoubleFactorialRelationship ()
void HarmonicSpecialCases ()
void HarmonicPsiAgreement ()
void PrimeSpecialCases ()
void PrimeCounts ()
void BinomialCoefficientRecurrence ()
void BinomialCoefficientInequality ()
void BinomialCoefficientSpecialCases ()
void BinomialCoefficientSums ()
void BinomialCoefficientAgreement ()
void BinomialCoefficientInvalidArgumentTest1 ()
void BinomialCoefficientInvalidArgumentTest2 ()
void BinomialCoefficientInvalidArgumentTest3 ()
void GcdLcmTest ()
void IntegerPartitionCounts ()
void IntegerPartitionSums ()
void PowModTest ()
void FibonacciSpecialCases ()
void FibonacciRecurrence ()
Private Member Functions
int CountPrimes (int n)
int CountValues (IEnumerable enumeration)
Member Function Documentation
void Test.AdvancedIntegerMathTest.FactorialSpecialCases () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.Factorial().
void Test.AdvancedIntegerMathTest.FactorialRecurrence () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.Factorial().
void Test.AdvancedIntegerMathTest.FactorialNegativeArgumentTest () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.Factorial().
void Test.AdvancedIntegerMathTest.DoubleFactorialSpecialCases () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.DoubleFactorial().
void Test.AdvancedIntegerMathTest.FactorialDoubleFactorialRelationship () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.LogDoubleFactorial(), and Meta.Numerics.Functions.AdvancedIntegerMath.LogFactorial().
void Test.AdvancedIntegerMathTest.HarmonicSpecialCases () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.HarmonicNumber().
void Test.AdvancedIntegerMathTest.HarmonicPsiAgreement () inline
References Meta.Numerics.Functions.AdvancedMath.EulerGamma, Meta.Numerics.Functions.AdvancedIntegerMath.HarmonicNumber(), and Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.AdvancedIntegerMathTest.PrimeSpecialCases () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.IsPrime().
void Test.AdvancedIntegerMathTest.PrimeCounts () inline
References Test.AdvancedIntegerMathTest.CountPrimes().
int Test.AdvancedIntegerMathTest.CountPrimes (int n) inline private
References Meta.Numerics.Functions.AdvancedIntegerMath.IsPrime().
Referenced by Test.AdvancedIntegerMathTest.PrimeCounts().
void Test.AdvancedIntegerMathTest.BinomialCoefficientRecurrence () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient().
void Test.AdvancedIntegerMathTest.BinomialCoefficientInequality () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient().
void Test.AdvancedIntegerMathTest.BinomialCoefficientSpecialCases () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient().
void Test.AdvancedIntegerMathTest.BinomialCoefficientSums () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficients(), and Meta.Numerics.MoreMath.Pow().
void Test.AdvancedIntegerMathTest.BinomialCoefficientAgreement () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient(), and Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficients().
void Test.AdvancedIntegerMathTest.BinomialCoefficientInvalidArgumentTest1 () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient().
void Test.AdvancedIntegerMathTest.BinomialCoefficientInvalidArgumentTest2 () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient().
void Test.AdvancedIntegerMathTest.BinomialCoefficientInvalidArgumentTest3 () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient().
void Test.AdvancedIntegerMathTest.GcdLcmTest () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.GCF(), and Meta.Numerics.Functions.AdvancedIntegerMath.LCM().
void Test.AdvancedIntegerMathTest.IntegerPartitionCounts () inline
References Test.AdvancedIntegerMathTest.CountValues(), and Meta.Numerics.Functions.AdvancedIntegerMath.Partitions().
int Test.AdvancedIntegerMathTest.CountValues (IEnumerable enumeration) inline private
Referenced by Test.AdvancedIntegerMathTest.IntegerPartitionCounts().
void Test.AdvancedIntegerMathTest.IntegerPartitionSums () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.Partitions().
void Test.AdvancedIntegerMathTest.PowModTest () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.PowMod().
void Test.AdvancedIntegerMathTest.FibonacciSpecialCases () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.FibonacciNumber().
void Test.AdvancedIntegerMathTest.FibonacciRecurrence () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.FibonacciNumber().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/AdvancedIntegerMathTest.cs