IGLib: NUnit.Engine.Runners.MasterTestRunner Class Reference
NUnit.Engine.Runners.MasterTestRunner Class Reference
Public Member Functions
MasterTestRunner (IServiceLocator services, TestPackage package)
override void UnloadPackage ()
Unload any loaded TestPackage.
override void StopRun (bool force)
Cancel the ongoing test run. If no test is running, the call is ignored.
Public Member Functions inherited from NUnit.Engine.Runners.AbstractTestRunner
AbstractTestRunner (IServiceLocator services, TestPackage package)
TestEngineResult Explore (TestFilter filter)
Explores the TestPackage and returns information about the tests found. Loads the package if not done previously.
TestEngineResult Load ()
Loads the TestPackage for exploration or execution, saving the result.
TestEngineResult Reload ()
Reload the currently loaded test package, saving the result.
void Unload ()
Unload any loaded TestPackage.
int CountTestCases (TestFilter filter)
Count the test cases that would be run under the specified filter, loading the TestPackage if it is not already loaded.
TestEngineResult Run (ITestEventListener listener, TestFilter filter)
Run the tests in the TestPackage, loading the package if this has not already been done.
AsyncTestEngineResult RunAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
void StartRun (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses. Loads the TestPackage if not already loaded.
void Dispose ()
Public Member Functions inherited from NUnit.Engine.ITestRunner
void Unload ()
Unload any loaded TestPackage. If none is loaded, the call is ignored.
int CountTestCases (TestFilter filter)
Count the test cases that would be run under the specified filter.
Protected Member Functions
override TestEngineResult ExploreTests (TestFilter filter)
Explore a loaded TestPackage and return information about the tests found.
override TestEngineResult LoadPackage ()
Load a TestPackage for possible execution
override int CountTests (TestFilter filter)
Count the test cases that would be run under the specified filter.
override TestEngineResult RunTests (ITestEventListener listener, TestFilter filter)
Run the tests in the loaded TestPackage and return a test result. The tests are run synchronously and the listener interface is notified as it progresses.
override void Dispose (bool disposing)
Dispose of this object.
Protected Member Functions inherited from NUnit.Engine.Runners.AbstractTestRunner
virtual TestEngineResult ReloadPackage ()
Reload the currently loaded test package. Overridden in derived classes to take any additional action.
virtual AsyncTestEngineResult RunTestsAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage, returning immediately. The tests are run asynchronously and the listener interface is notified as it progresses.
bool IsProjectPackage (TestPackage package)
Properties
bool IsTestRunning [get, private set]
Properties inherited from NUnit.Engine.Runners.AbstractTestRunner
IServiceLocator Services [get, private set]
Our Service Context
IProjectService ProjectService [get, private set]
ITestRunnerFactory TestRunnerFactory [get, private set]
TestPackage TestPackage [get, set]
The TestPackage for which this is the runner
TestEngineResult LoadResult [get, set]
The result of the last call to LoadPackage
bool IsPackageLoaded [get]
Gets an indicator of whether the package has been loaded.
Properties inherited from NUnit.Engine.ITestRunner
bool IsTestRunning [get]
Get a flag indicating whether a test is running
Private Member Functions
XmlNode ITestRunner. Load ()
Load a TestPackage for possible execution. The explicit implementation returns an ITestEngineResult for consumption by clients.
XmlNode ITestRunner. Reload ()
Reload the currently loaded test jpackage.
XmlNode ITestRunner. Run (ITestEventListener listener, TestFilter filter)
Run the tests in a loaded TestPackage. The explicit implementation returns an ITestEngineResult for use by external clients.
ITestRun ITestRunner. RunAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
XmlNode ITestRunner. Explore (TestFilter filter)
Explore a loaded TestPackage and return information about the tests found.
void ValidatePackageSettings ()
Static Private Member Functions
static void InsertCommandLineElement (XmlNode resultNode)
static void InsertSettingsElement (XmlNode resultNode, IDictionary< string, object > settings)
static void InsertFilterElement (XmlNode resultNode, TestFilter filter)
Private Attributes
ITestEngineRunner _realRunner
Additional Inherited Members
Protected Attributes inherited from NUnit.Engine.Runners.AbstractTestRunner
const string TEST_RUN_ELEMENT = "test-run"
bool _disposed = false
Constructor & Destructor Documentation
NUnit.Engine.Runners.MasterTestRunner.MasterTestRunner (IServiceLocator services, TestPackage package) inline
Member Function Documentation
override TestEngineResult NUnit.Engine.Runners.MasterTestRunner.ExploreTests (TestFilter filter) inline protected virtual
Explore a loaded TestPackage and return information about the tests found.
Parameters
filter A TestFilter used to select tests
Returns
A TestEngineResult.
Implements NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.ITestEngineRunner.Explore(), NUnit.Engine.TestPackage.FullName, and NUnit.Engine.TestPackage.Name.
override TestEngineResult NUnit.Engine.Runners.MasterTestRunner.LoadPackage () inline protected virtual
Load a TestPackage for possible execution
Returns
A TestEngineResult.
Implements NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.TestPackage.FullName, NUnit.Engine.ITestEngineRunner.Load(), and NUnit.Engine.TestPackage.Name.
override void NUnit.Engine.Runners.MasterTestRunner.UnloadPackage () inline virtual
Unload any loaded TestPackage.
Reimplemented from NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.ITestEngineRunner.Unload().
override int NUnit.Engine.Runners.MasterTestRunner.CountTests (TestFilter filter) inline protected virtual
Count the test cases that would be run under the specified filter.
Parameters
filter A TestFilter
Returns
The count of test cases
Implements NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.ITestEngineRunner.CountTestCases().
override TestEngineResult NUnit.Engine.Runners.MasterTestRunner.RunTests (ITestEventListener listener, TestFilter filter) inline protected virtual
Run the tests in the loaded TestPackage and return a test result. The tests are run synchronously and the listener interface is notified as it progresses.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Returns
A TestEngineResult giving the result of the test execution
Implements NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.TestPackage.FullName, NUnit.Engine.TestPackage.Name, NUnit.Engine.ITestEventListener.OnTestEvent(), NUnit.Engine.ITestEngineRunner.Run(), and NUnit.Engine.TestEngineResult.Xml.
override void NUnit.Engine.Runners.MasterTestRunner.StopRun (bool force) inline virtual
Cancel the ongoing test run. If no test is running, the call is ignored.
Parameters
force If true, cancel any ongoing test threads, otherwise wait for them to complete.
Implements NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.ITestEngineRunner.StopRun().
override void NUnit.Engine.Runners.MasterTestRunner.Dispose (bool disposing) inline protected virtual
Dispose of this object.
Reimplemented from NUnit.Engine.Runners.AbstractTestRunner.
XmlNode ITestRunner. NUnit.Engine.Runners.MasterTestRunner.Load () inline private
Load a TestPackage for possible execution. The explicit implementation returns an ITestEngineResult for consumption by clients.
Returns
An XmlNode representing the loaded assembly.
Implements NUnit.Engine.ITestRunner.
XmlNode ITestRunner. NUnit.Engine.Runners.MasterTestRunner.Reload () inline private
Reload the currently loaded test jpackage.
Returns
An XmlNode representing the loaded package
Exceptions
InvalidOperationException If no package has been loaded
Implements NUnit.Engine.ITestRunner.
XmlNode ITestRunner. NUnit.Engine.Runners.MasterTestRunner.Run (ITestEventListener listener, TestFilter filter) inline private
Run the tests in a loaded TestPackage. The explicit implementation returns an ITestEngineResult for use by external clients.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Returns
An XmlNode giving the result of the test execution
Implements NUnit.Engine.ITestRunner.
ITestRun ITestRunner. NUnit.Engine.Runners.MasterTestRunner.RunAsync (ITestEventListener listener, TestFilter filter) inline private
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
Parameters
listener The listener that is notified as the run progresses
filter A TestFilter used to select tests
Returns
Implements NUnit.Engine.ITestRunner.
XmlNode ITestRunner. NUnit.Engine.Runners.MasterTestRunner.Explore (TestFilter filter) inline private
Explore a loaded TestPackage and return information about the tests found.
Parameters
filter A TestFilter used to select tests
Returns
An XmlNode representing the tests found.
Implements NUnit.Engine.ITestRunner.
void NUnit.Engine.Runners.MasterTestRunner.ValidatePackageSettings () inline private
References NUnit.Engine.RuntimeFramework.CurrentFramework, NUnit.Engine.RuntimeFramework.Parse(), NUnit.Common.PackageSettings.ProcessModel, and NUnit.Common.PackageSettings.RuntimeFramework.
static void NUnit.Engine.Runners.MasterTestRunner.InsertCommandLineElement (XmlNode resultNode) inline static private
static void NUnit.Engine.Runners.MasterTestRunner.InsertSettingsElement (XmlNode resultNode, IDictionary< string, object > settings) inline static private
static void NUnit.Engine.Runners.MasterTestRunner.InsertFilterElement (XmlNode resultNode, TestFilter filter) inline static private
References NUnit.Common.XmlHelper.CreateXmlNode(), and NUnit.Engine.TestFilter.Text.
Member Data Documentation
ITestEngineRunner NUnit.Engine.Runners.MasterTestRunner._realRunner private
Property Documentation
bool NUnit.Engine.Runners.MasterTestRunner.IsTestRunning get private set
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Runners/MasterTestRunner.cs