IGLib: IPLab.ConvolutionForm Class Reference
IPLab.ConvolutionForm Class Reference
Summary description for ConvolutionForm.
Public Member Functions
ConvolutionForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
IFilter Filter [get]
Bitmap Image [set]
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void sizeCombo_SelectedIndexChanged (object sender, System.EventArgs e)
void grid_ValueChanged (object sender, IPLab.GridEventArgs e)
void UpdateFilter ()
void saveButton_Click (object sender, System.EventArgs e)
void loadButton_Click (object sender, System.EventArgs e)
void thresholdBox_TextChanged (object sender, EventArgs e)
Private Attributes
System.Windows.Forms.Button cancelButton
System.Windows.Forms.ComboBox sizeCombo
System.Windows.Forms.GroupBox groupBox1
IPLab.GridArrayInt grid
System.Windows.Forms.Label label1
int[,] kernel
AForge.Imaging.Filters.Convolution filter
System.Windows.Forms.Button okButton
System.Windows.Forms.Button saveButton
System.Windows.Forms.Button loadButton
System.Windows.Forms.SaveFileDialog sfd
System.Windows.Forms.OpenFileDialog ofd
IPLab.FilterPreview filterPreview
System.Windows.Forms.GroupBox groupBox2
Label label2
TextBox thresholdBox
System.ComponentModel.Container components = null
Required designer variable.
Static Private Attributes
static int[] sizes = new int[] { 3, 5, 7, 9, 11, 13, 15 }
Detailed Description
Summary description for ConvolutionForm.
Constructor & Destructor Documentation
IPLab.ConvolutionForm.ConvolutionForm () inline
References IPLab.ConvolutionForm.filter, IPLab.ConvolutionForm.grid, IPLab.ConvolutionForm.InitializeComponent(), IPLab.GridArrayInt.LoadData(), and IPLab.ConvolutionForm.sizeCombo.
Member Function Documentation
override void IPLab.ConvolutionForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References IPLab.ConvolutionForm.components.
void IPLab.ConvolutionForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IPLab.ConvolutionForm.ConvolutionForm().
void IPLab.ConvolutionForm.sizeCombo_SelectedIndexChanged (object sender, System.EventArgs e) inline private
References IPLab.ConvolutionForm.grid, IPLab.GridArrayInt.LoadData(), IPLab.ConvolutionForm.sizeCombo, and IPLab.ConvolutionForm.UpdateFilter().
void IPLab.ConvolutionForm.grid_ValueChanged (object sender, IPLab.GridEventArgs e) inline private
References IPLab.ConvolutionForm.UpdateFilter().
void IPLab.ConvolutionForm.UpdateFilter () inline private
References IPLab.Convolution, IPLab.ConvolutionForm.filter, IPLab.FilterPreview.Filter, and IPLab.ConvolutionForm.filterPreview.
Referenced by IPLab.ConvolutionForm.grid_ValueChanged(), IPLab.ConvolutionForm.loadButton_Click(), IPLab.ConvolutionForm.sizeCombo_SelectedIndexChanged(), and IPLab.ConvolutionForm.thresholdBox_TextChanged().
void IPLab.ConvolutionForm.saveButton_Click (object sender, System.EventArgs e) inline private
References IPLab.ConvolutionForm.sfd.
void IPLab.ConvolutionForm.loadButton_Click (object sender, System.EventArgs e) inline private
References IPLab.ConvolutionForm.grid, IPLab.GridArrayInt.LoadData(), IPLab.ConvolutionForm.ofd, IPLab.ConvolutionForm.sizeCombo, and IPLab.ConvolutionForm.UpdateFilter().
void IPLab.ConvolutionForm.thresholdBox_TextChanged (object sender, EventArgs e) inline private
References IPLab.ConvolutionForm.UpdateFilter().
Member Data Documentation
System.Windows.Forms.Button IPLab.ConvolutionForm.cancelButton private
System.Windows.Forms.ComboBox IPLab.ConvolutionForm.sizeCombo private
Referenced by IPLab.ConvolutionForm.ConvolutionForm(), IPLab.ConvolutionForm.loadButton_Click(), and IPLab.ConvolutionForm.sizeCombo_SelectedIndexChanged().
System.Windows.Forms.GroupBox IPLab.ConvolutionForm.groupBox1 private
IPLab.GridArrayInt IPLab.ConvolutionForm.grid private
Referenced by IPLab.ConvolutionForm.ConvolutionForm(), IPLab.ConvolutionForm.loadButton_Click(), and IPLab.ConvolutionForm.sizeCombo_SelectedIndexChanged().
System.Windows.Forms.Label IPLab.ConvolutionForm.label1 private
int [] IPLab.ConvolutionForm.sizes = new int[] { 3, 5, 7, 9, 11, 13, 15 } static private
int [,] IPLab.ConvolutionForm.kernel private
AForge.Imaging.Filters.Convolution IPLab.ConvolutionForm.filter private
Referenced by IPLab.ConvolutionForm.ConvolutionForm(), and IPLab.ConvolutionForm.UpdateFilter().
System.Windows.Forms.Button IPLab.ConvolutionForm.okButton private
System.Windows.Forms.Button IPLab.ConvolutionForm.saveButton private
System.Windows.Forms.Button IPLab.ConvolutionForm.loadButton private
System.Windows.Forms.SaveFileDialog IPLab.ConvolutionForm.sfd private
Referenced by IPLab.ConvolutionForm.saveButton_Click().
System.Windows.Forms.OpenFileDialog IPLab.ConvolutionForm.ofd private
Referenced by IPLab.ConvolutionForm.loadButton_Click().
IPLab.FilterPreview IPLab.ConvolutionForm.filterPreview private
Referenced by IPLab.ConvolutionForm.UpdateFilter().
System.Windows.Forms.GroupBox IPLab.ConvolutionForm.groupBox2 private
Label IPLab.ConvolutionForm.label2 private
TextBox IPLab.ConvolutionForm.thresholdBox private
System.ComponentModel.Container IPLab.ConvolutionForm.components = null private
Required designer variable.
Referenced by IPLab.ConvolutionForm.Dispose().
Property Documentation
IFilter IPLab.ConvolutionForm.Filter get
Referenced by IPLab.ImageDoc.Convolution().
Bitmap IPLab.ConvolutionForm.Image set
Referenced by IPLab.ImageDoc.Convolution().
The documentation for this class was generated from the following file:
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/ConvolutionForm.cs