IGLib: IPLab.MathMorphologyForm Class Reference
IPLab.MathMorphologyForm Class Reference
Summary description for MathMorphologyForm.
Public Types
enum FilterTypes { FilterTypes.Simple = 0, FilterTypes.HitAndMiss = 1 }
Public Member Functions
MathMorphologyForm (FilterTypes filterType)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
IFilter Filter [get]
Bitmap Image [set]
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void sizeCombo_SelectedIndexChanged (object sender, System.EventArgs e)
void operatorCombo_SelectedIndexChanged (object sender, System.EventArgs e)
void grid_ValueChanged (object sender, IPLab.GridEventArgs e)
void UpdateFilter ()
void saveButton_Click (object sender, System.EventArgs e)
void loadButton_Click (object sender, System.EventArgs e)
Private Attributes
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.ComboBox sizeCombo
System.Windows.Forms.Label label1
IPLab.GridArrayInt grid
System.Windows.Forms.Label label2
System.Windows.Forms.ComboBox operatorCombo
short[,] se
AForge.Imaging.Filters.IFilter filter
System.Windows.Forms.Button OkButton
System.Windows.Forms.Button cancelButton
System.Windows.Forms.Button loadButton
System.Windows.Forms.Button saveButton
System.Windows.Forms.OpenFileDialog ofd
System.Windows.Forms.SaveFileDialog sfd
System.Windows.Forms.GroupBox groupBox2
IPLab.FilterPreview filterPreview
FilterTypes filterType = FilterTypes.Simple
System.Windows.Forms.Label legendLabel
System.ComponentModel.Container components = null
Required designer variable.
Static Private Attributes
static int[] sizes = new int[] { 3, 5, 7, 9, 11, 13, 15 }
Detailed Description
Summary description for MathMorphologyForm.
Member Enumeration Documentation
enum IPLab.MathMorphologyForm.FilterTypes
Enumerator
Simple
HitAndMiss
Constructor & Destructor Documentation
IPLab.MathMorphologyForm.MathMorphologyForm (FilterTypes filterType) inline
References IPLab.MathMorphologyForm.filterType, IPLab.MathMorphologyForm.grid, IPLab.MathMorphologyForm.InitializeComponent(), IPLab.MathMorphologyForm.legendLabel, IPLab.GridArrayInt.LoadData(), IPLab.MathMorphologyForm.operatorCombo, and IPLab.MathMorphologyForm.sizeCombo.
Member Function Documentation
override void IPLab.MathMorphologyForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References IPLab.MathMorphologyForm.components.
void IPLab.MathMorphologyForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IPLab.MathMorphologyForm.MathMorphologyForm().
void IPLab.MathMorphologyForm.sizeCombo_SelectedIndexChanged (object sender, System.EventArgs e) inline private
References IPLab.MathMorphologyForm.grid, IPLab.GridArrayInt.LoadData(), IPLab.MathMorphologyForm.sizeCombo, and IPLab.MathMorphologyForm.UpdateFilter().
void IPLab.MathMorphologyForm.operatorCombo_SelectedIndexChanged (object sender, System.EventArgs e) inline private
References IPLab.MathMorphologyForm.UpdateFilter().
void IPLab.MathMorphologyForm.grid_ValueChanged (object sender, IPLab.GridEventArgs e) inline private
References IPLab.MathMorphologyForm.UpdateFilter().
void IPLab.MathMorphologyForm.UpdateFilter () inline private
References IPLab.MathMorphologyForm.filter, IPLab.FilterPreview.Filter, IPLab.MathMorphologyForm.filterPreview, IPLab.MathMorphologyForm.HitAndMiss, and IPLab.MathMorphologyForm.operatorCombo.
Referenced by IPLab.MathMorphologyForm.grid_ValueChanged(), IPLab.MathMorphologyForm.loadButton_Click(), IPLab.MathMorphologyForm.operatorCombo_SelectedIndexChanged(), and IPLab.MathMorphologyForm.sizeCombo_SelectedIndexChanged().
void IPLab.MathMorphologyForm.saveButton_Click (object sender, System.EventArgs e) inline private
References IPLab.MathMorphologyForm.sfd.
void IPLab.MathMorphologyForm.loadButton_Click (object sender, System.EventArgs e) inline private
References IPLab.MathMorphologyForm.grid, IPLab.GridArrayInt.LoadData(), IPLab.MathMorphologyForm.ofd, IPLab.MathMorphologyForm.sizeCombo, and IPLab.MathMorphologyForm.UpdateFilter().
Member Data Documentation
System.Windows.Forms.GroupBox IPLab.MathMorphologyForm.groupBox1 private
System.Windows.Forms.ComboBox IPLab.MathMorphologyForm.sizeCombo private
Referenced by IPLab.MathMorphologyForm.loadButton_Click(), IPLab.MathMorphologyForm.MathMorphologyForm(), and IPLab.MathMorphologyForm.sizeCombo_SelectedIndexChanged().
System.Windows.Forms.Label IPLab.MathMorphologyForm.label1 private
IPLab.GridArrayInt IPLab.MathMorphologyForm.grid private
Referenced by IPLab.MathMorphologyForm.loadButton_Click(), IPLab.MathMorphologyForm.MathMorphologyForm(), and IPLab.MathMorphologyForm.sizeCombo_SelectedIndexChanged().
System.Windows.Forms.Label IPLab.MathMorphologyForm.label2 private
System.Windows.Forms.ComboBox IPLab.MathMorphologyForm.operatorCombo private
Referenced by IPLab.MathMorphologyForm.MathMorphologyForm(), and IPLab.MathMorphologyForm.UpdateFilter().
int [] IPLab.MathMorphologyForm.sizes = new int[] { 3, 5, 7, 9, 11, 13, 15 } static private
short [,] IPLab.MathMorphologyForm.se private
AForge.Imaging.Filters.IFilter IPLab.MathMorphologyForm.filter private
Referenced by IPLab.MathMorphologyForm.UpdateFilter().
System.Windows.Forms.Button IPLab.MathMorphologyForm.OkButton private
System.Windows.Forms.Button IPLab.MathMorphologyForm.cancelButton private
System.Windows.Forms.Button IPLab.MathMorphologyForm.loadButton private
System.Windows.Forms.Button IPLab.MathMorphologyForm.saveButton private
System.Windows.Forms.OpenFileDialog IPLab.MathMorphologyForm.ofd private
Referenced by IPLab.MathMorphologyForm.loadButton_Click().
System.Windows.Forms.SaveFileDialog IPLab.MathMorphologyForm.sfd private
Referenced by IPLab.MathMorphologyForm.saveButton_Click().
System.Windows.Forms.GroupBox IPLab.MathMorphologyForm.groupBox2 private
IPLab.FilterPreview IPLab.MathMorphologyForm.filterPreview private
Referenced by IPLab.MathMorphologyForm.UpdateFilter().
FilterTypes IPLab.MathMorphologyForm.filterType = FilterTypes.Simple private
Referenced by IPLab.MathMorphologyForm.MathMorphologyForm().
System.Windows.Forms.Label IPLab.MathMorphologyForm.legendLabel private
Referenced by IPLab.MathMorphologyForm.MathMorphologyForm().
System.ComponentModel.Container IPLab.MathMorphologyForm.components = null private
Required designer variable.
Referenced by IPLab.MathMorphologyForm.Dispose().
Property Documentation
IFilter IPLab.MathMorphologyForm.Filter get
Referenced by IPLab.ImageDoc.hitAndMissFiltersItem_Click(), and IPLab.ImageDoc.Morphology().
Bitmap IPLab.MathMorphologyForm.Image set
Referenced by IPLab.ImageDoc.hitAndMissFiltersItem_Click(), and IPLab.ImageDoc.Morphology().
The documentation for this class was generated from the following file:
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/MathMorphologyForm.cs