IGLib: Package IG.Lib.Old
Package IG.Lib.Old
Classes
interface IReporter
Interface from which all reporters inherit.
class Reporter
Base IG class for reporting, tracing and logging; provides a global reporter and a basis for creation of local reporters. This class is identical to the IGLib class (copied directly). IN EFA, refer to the derived class Reporter!
Enumerations
enum ReportType { ReportType.Error = 1, ReportType.Warning, ReportType.Info, ReportType.Undefined }
Defines the type of a report.
enum ReportLevel {
ReportLevel.Off = 0, ReportLevel.Error, ReportLevel.Warning, ReportLevel.Info,
ReportLevel.Verbose
}
Defines the level of output when launching reports.
Functions
delegate void ReportDelegate (Reporter reporter, ReportType messagetype, string errorlocation, string errormessage)
Reports an error.
delegate string ReportLocationDelegate (Reporter reporter, ReportType messagetype, string location, Exception ex)
Assembles the error location desctiption.
delegate string ReportMessageDelegate (Reporter reporter, ReportType messagetype, string basicmessage, Exception ex)
Assembles error description (without any decoration, this is added by talling methods).
delegate void ReserveReportErrorDelegate (Reporter reporter, ReportType messagetype, string location, string message, Exception ex, Exception ex1)
Reports errors occurred in error reporting methods when exceptions are thrown within them. Methods assigned to these delegates must be bullet proof. They must report the original error (being reported when an exception occurred) as well as the exception that occurred uin the error reporting method.
Enumeration Type Documentation
enum IG.Lib.Old.ReportType
Defines the type of a report.
Enumerator
Error
Warning
Info
Undefined
enum IG.Lib.Old.ReportLevel
Defines the level of output when launching reports.
Enumerator
Off
Error
Warning
Info
Verbose
Function Documentation
delegate void IG.Lib.Old.ReportDelegate (Reporter reporter, ReportType messagetype, string errorlocation, string errormessage)
Reports an error.
Parameters
reporter Reference to the reporter class where all s necessary data is fond. In particular, the Obj member contains a user-set object reference used by the delegate functions.
messagetype Type of the message that is launched.
errorlocation User-defined string containing (sometimes supplemental to the Exception object) specification of error location (e.g. a class or module name)
errormessage User-provided string containing (sometimes supplemental to the Exception object) error description.
Referenced by IG.Lib.Old.Reporter.SetDefaultReportDlg().
delegate string IG.Lib.Old.ReportLocationDelegate (Reporter reporter, ReportType messagetype, string location, Exception ex)
Assembles the error location desctiption.
Parameters
reporter Reference to the reporter class where all s necessary data is fond. In particular, the Obj member contains a user-set object reference used by the delegate functions.
messagetype Type of the message that is launched.
location User-provided string containing (sometimes supplemental to the Exception object) specification of error location (e.g. a class or module name)
ex Exception to be reported.
Returns
A string describing error location.
Referenced by IG.Forms.ReporterForms.SetDefaultReportLocationDlg(), IG.Lib.ReporterConsole.SetDefaultReportLocationDlg(), and IG.Lib.Old.Reporter.SetDefaultReportLocationDlg().
delegate string IG.Lib.Old.ReportMessageDelegate (Reporter reporter, ReportType messagetype, string basicmessage, Exception ex)
Assembles error description (without any decoration, this is added by talling methods).
Parameters
reporter Reference to the reporter class where all s necessary data is fond. In particular, the Obj member contains a user-set object reference used by the delegate functions.
messagetype Type of the message that is launched.
basicmessage User-provided string containing (sometimes supplemental to the Exception object) error description.
ex Exception to be reported.
Referenced by IG.Forms.ReporterForms.SetDefaultReportMessageDlg(), IG.Lib.ReporterConsole.SetDefaultReportMessageDlg(), and IG.Lib.Old.Reporter.SetDefaultReportMessageDlg().
delegate void IG.Lib.Old.ReserveReportErrorDelegate (Reporter reporter, ReportType messagetype, string location, string message, Exception ex, Exception ex1)
Reports errors occurred in error reporting methods when exceptions are thrown within them. Methods assigned to these delegates must be bullet proof. They must report the original error (being reported when an exception occurred) as well as the exception that occurred uin the error reporting method.
Parameters
reporter Reference to the reporter class where all s necessary data is fond. In particular, the Obj member contains a user-set object reference used by the delegate functions. This object should be used with special care within reserve reporting functions because it may be corrupted.
messagetype Type of the message that is launched.
location User-provided string containing (sometimes supplemental to the Exception object) specification of error location (e.g. a class or module name)
message User-provided string containing (sometimes supplemental to the Exception object) error description.
ex Original exception that was being reported.
ex1 Exception that was thrwn by the error reporting function.
Referenced by IG.Forms.ReporterForms.SetDefaultReserveReportErrorDlg(), and IG.Lib.Old.Reporter.SetDefaultReserveReportErrorDlg().