IGLib: NUnit.TestUtilities.TestDirectory Class Reference
NUnit.TestUtilities.TestDirectory Class Reference
Creates a directory for testing purposes
Public Member Functions
TestDirectory ()
void Dispose ()
Clean up after ourselves
override string ToString ()
Returns the full path of the contained test directory
Properties
DirectoryInfo Directory [get]
Gets the test directory.
Private Attributes
DirectoryInfo _testDir
Detailed Description
Creates a directory for testing purposes
Constructor & Destructor Documentation
NUnit.TestUtilities.TestDirectory.TestDirectory () inline
References NUnit.Framework.Is.False, NUnit.Framework.Assume.That(), and NUnit.Framework.Is.True.
Member Function Documentation
void NUnit.TestUtilities.TestDirectory.Dispose () inline
Clean up after ourselves
Referenced by NUnit.Framework.Assertions.DirectoryAssertTests.TearDown(), and NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.TearDown().
override string NUnit.TestUtilities.TestDirectory.ToString () inline
Returns the full path of the contained test directory
Referenced by NUnit.Framework.Assertions.DirectoryAssertTests.AreEqualPassesWithDirectoryInfos(), NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualFailsWithDirectoryInfos(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenStringExists(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsPassesWhenStringExists(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenIgnoreDirectoriesIsTrueWithDirectoryString(), and NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.PassesWhenDirectoryStringExists().
Member Data Documentation
DirectoryInfo NUnit.TestUtilities.TestDirectory._testDir private
Property Documentation
DirectoryInfo NUnit.TestUtilities.TestDirectory.Directory get
Gets the test directory.
Referenced by NUnit.Framework.Assertions.DirectoryAssertTests.AreEqualFailsWithDirectoryInfos(), NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualPassesIfActualIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualPassesIfExpectedIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualPassesWithDirectoryInfos(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenDirectoryInfoExists(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsPassesWhenDirectoryInfoExists(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenIgnoreDirectoriesIsTrueWithDirectoryInfo(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.PassesWhenDirectoryInfoExists(), and NUnit.Framework.Assertions.DirectoryAssertTests.SetUp().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/TestUtilities/TestDirectory.cs