IGLib: alglib.testalglibbasicsunit.rec1 Class Reference
alglib.testalglibbasicsunit.rec1 Class Reference
Public Member Functions
rec1 ()
rec1 ()
override void init ()
override alglib.apobject make_copy ()
Public Attributes
bool bfield
double rfield
int ifield
complex cfield
bool[] b1field
double[] r1field
int[] i1field
complex[] c1field
bool[,] b2field
double[,] r2field
int[,] i2field
complex[,] c2field
Constructor & Destructor Documentation
alglib.testalglibbasicsunit.rec1.rec1 () inline
Referenced by alglib.testalglibbasicsunit.rec1.make_copy().
alglib.testalglibbasicsunit.rec1.rec1 () inline
References alglib.testalglibbasicsunit.rec1.init().
Member Function Documentation
override void alglib.testalglibbasicsunit.rec1.init () inline virtual
Implements alglib.apobject.
Referenced by alglib.testalglibbasicsunit.rec1.rec1().
override alglib.apobject alglib.testalglibbasicsunit.rec1.make_copy () inline virtual
Implements alglib.apobject.
References alglib.testalglibbasicsunit.rec1.bfield, alglib.testalglibbasicsunit.rec1.cfield, alglib.testalglibbasicsunit.rec1.ifield, alglib.testalglibbasicsunit.rec1.rec1(), and alglib.testalglibbasicsunit.rec1.rfield.
Member Data Documentation
bool alglib.testalglibbasicsunit.rec1.bfield
Referenced by alglib.testalglibbasicsunit.rec1.make_copy().
double alglib.testalglibbasicsunit.rec1.rfield
Referenced by alglib.testalglibbasicsunit.rec1.make_copy().
int alglib.testalglibbasicsunit.rec1.ifield
Referenced by alglib.testalglibbasicsunit.rec1.make_copy().
complex alglib.testalglibbasicsunit.rec1.cfield
Referenced by alglib.testalglibbasicsunit.rec1.make_copy().
bool [] alglib.testalglibbasicsunit.rec1.b1field
double [] alglib.testalglibbasicsunit.rec1.r1field
int [] alglib.testalglibbasicsunit.rec1.i1field
complex [] alglib.testalglibbasicsunit.rec1.c1field
bool [,] alglib.testalglibbasicsunit.rec1.b2field
double [,] alglib.testalglibbasicsunit.rec1.r2field
int [,] alglib.testalglibbasicsunit.rec1.i2field
complex [,] alglib.testalglibbasicsunit.rec1.c2field
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs