IGLib: alglib.mlptrain Class Reference
alglib.mlptrain Class Reference
Classes
class mlpcvreport
class mlpetrnsession
class mlpparallelizationcv
class mlpreport
class mlptrainer
class smlptrnsession
Static Public Member Functions
static void mlptrainlm (mlpbase.multilayerperceptron network, double[,] xy, int npoints, double decay, int restarts, ref int info, mlpreport rep)
static void mlptrainlbfgs (mlpbase.multilayerperceptron network, double[,] xy, int npoints, double decay, int restarts, double wstep, int maxits, ref int info, mlpreport rep)
static void mlptraines (mlpbase.multilayerperceptron network, double[,] trnxy, int trnsize, double[,] valxy, int valsize, double decay, int restarts, ref int info, mlpreport rep)
static void mlpkfoldcvlbfgs (mlpbase.multilayerperceptron network, double[,] xy, int npoints, double decay, int restarts, double wstep, int maxits, int foldscount, ref int info, mlpreport rep, mlpcvreport cvrep)
static void mlpkfoldcvlm (mlpbase.multilayerperceptron network, double[,] xy, int npoints, double decay, int restarts, int foldscount, ref int info, mlpreport rep, mlpcvreport cvrep)
static void mlptrainlm (mlpbase.multilayerperceptron network, double[,] xy, int npoints, double decay, int restarts, ref int info, mlpreport rep)
static void mlptrainlbfgs (mlpbase.multilayerperceptron network, double[,] xy, int npoints, double decay, int restarts, double wstep, int maxits, ref int info, mlpreport rep)
static void mlptraines (mlpbase.multilayerperceptron network, double[,] trnxy, int trnsize, double[,] valxy, int valsize, double decay, int restarts, ref int info, mlpreport rep)
static void mlpkfoldcvlbfgs (mlpbase.multilayerperceptron network, double[,] xy, int npoints, double decay, int restarts, double wstep, int maxits, int foldscount, ref int info, mlpreport rep, mlpcvreport cvrep)
static void mlpkfoldcvlm (mlpbase.multilayerperceptron network, double[,] xy, int npoints, double decay, int restarts, int foldscount, ref int info, mlpreport rep, mlpcvreport cvrep)
static void mlpkfoldcv (mlptrainer s, mlpbase.multilayerperceptron network, int nrestarts, int foldscount, mlpreport rep)
static void _pexec_mlpkfoldcv (mlptrainer s, mlpbase.multilayerperceptron network, int nrestarts, int foldscount, mlpreport rep)
static void mlpcreatetrainer (int nin, int nout, mlptrainer s)
static void mlpcreatetrainercls (int nin, int nclasses, mlptrainer s)
static void mlpsetdataset (mlptrainer s, double[,] xy, int npoints)
static void mlpsetsparsedataset (mlptrainer s, sparse.sparsematrix xy, int npoints)
static void mlpsetdecay (mlptrainer s, double decay)
static void mlpsetcond (mlptrainer s, double wstep, int maxits)
static void mlpsetalgobatch (mlptrainer s)
static void mlptrainnetwork (mlptrainer s, mlpbase.multilayerperceptron network, int nrestarts, mlpreport rep)
static void _pexec_mlptrainnetwork (mlptrainer s, mlpbase.multilayerperceptron network, int nrestarts, mlpreport rep)
static void mlpstarttraining (mlptrainer s, mlpbase.multilayerperceptron network, bool randomstart)
static bool mlpcontinuetraining (mlptrainer s, mlpbase.multilayerperceptron network)
static bool _pexec_mlpcontinuetraining (mlptrainer s, mlpbase.multilayerperceptron network)
static void mlpebagginglm (mlpe.mlpensemble ensemble, double[,] xy, int npoints, double decay, int restarts, ref int info, mlpreport rep, mlpcvreport ooberrors)
static void mlpebagginglbfgs (mlpe.mlpensemble ensemble, double[,] xy, int npoints, double decay, int restarts, double wstep, int maxits, ref int info, mlpreport rep, mlpcvreport ooberrors)
static void mlpetraines (mlpe.mlpensemble ensemble, double[,] xy, int npoints, double decay, int restarts, ref int info, mlpreport rep)
static void mlptrainensemblees (mlptrainer s, mlpe.mlpensemble ensemble, int nrestarts, mlpreport rep)
static void _pexec_mlptrainensemblees (mlptrainer s, mlpe.mlpensemble ensemble, int nrestarts, mlpreport rep)
Public Attributes
const double mindecay = 0.001
const int defaultlbfgsfactor = 6
Static Private Member Functions
static void mlpkfoldcvgeneral (mlpbase.multilayerperceptron n, double[,] xy, int npoints, double decay, int restarts, int foldscount, bool lmalgorithm, double wstep, int maxits, ref int info, mlpreport rep, mlpcvreport cvrep)
static void mlpkfoldsplit (double[,] xy, int npoints, int nclasses, int foldscount, bool stratifiedsplits, ref int[] folds)
static void mlpkfoldcvgeneral (mlpbase.multilayerperceptron n, double[,] xy, int npoints, double decay, int restarts, int foldscount, bool lmalgorithm, double wstep, int maxits, ref int info, mlpreport rep, mlpcvreport cvrep)
static void mlpkfoldsplit (double[,] xy, int npoints, int nclasses, int foldscount, bool stratifiedsplits, ref int[] folds)
static void mthreadcv (mlptrainer s, int rowsize, int nrestarts, int[] folds, int fold, int dfold, double[,] cvy, alglib.smp.shared_pool pooldatacv)
static void mlptrainnetworkx (mlptrainer s, int nrestarts, int algokind, int[] trnsubset, int trnsubsetsize, int[] valsubset, int valsubsetsize, mlpbase.multilayerperceptron network, mlpreport rep, bool isrootcall, alglib.smp.shared_pool sessions)
static void mlptrainensemblex (mlptrainer s, mlpe.mlpensemble ensemble, int idx0, int idx1, int nrestarts, int trainingmethod, apserv.sinteger ngrad, bool isrootcall, alglib.smp.shared_pool esessions)
static void mlpstarttrainingx (mlptrainer s, bool randomstart, int algokind, int[] subset, int subsetsize, smlptrnsession session)
static bool mlpcontinuetrainingx (mlptrainer s, int[] subset, int subsetsize, ref int ngradbatch, smlptrnsession session)
static void mlpebagginginternal (mlpe.mlpensemble ensemble, double[,] xy, int npoints, double decay, int restarts, double wstep, int maxits, bool lmalgorithm, ref int info, mlpreport rep, mlpcvreport ooberrors)
static void initmlptrnsession (mlpbase.multilayerperceptron networktrained, bool randomizenetwork, mlptrainer trainer, smlptrnsession session)
static void initmlptrnsessions (mlpbase.multilayerperceptron networktrained, bool randomizenetwork, mlptrainer trainer, alglib.smp.shared_pool sessions)
static void initmlpetrnsession (mlpbase.multilayerperceptron individualnetwork, mlptrainer trainer, mlpetrnsession session)
static void initmlpetrnsessions (mlpbase.multilayerperceptron individualnetwork, mlptrainer trainer, alglib.smp.shared_pool sessions)
Member Function Documentation
static void alglib.mlptrain.mlptrainlm (mlpbase.multilayerperceptron network, double xy[,], int npoints, double decay, int restarts, ref int info, mlpreport rep) inline static
Referenced by alglib.mlptrainlm(), alglib.testmlptrainunit.testmlptrain(), alglib.testmlptrainunit.testmlptrainclass(), and alglib.testmlptrainunit.testmlptrainregr().
static void alglib.mlptrain.mlptrainlbfgs (mlpbase.multilayerperceptron network, double xy[,], int npoints, double decay, int restarts, double wstep, int maxits, ref int info, mlpreport rep) inline static
Referenced by alglib.mlptrainlbfgs(), alglib.testmlptrainunit.testmlprestarts(), alglib.testmlptrainunit.testmlptrainclass(), and alglib.testmlptrainunit.testmlptrainregr().
static void alglib.mlptrain.mlptraines (mlpbase.multilayerperceptron network, double trnxy[,], int trnsize, double valxy[,], int valsize, double decay, int restarts, ref int info, mlpreport rep) inline static
Referenced by alglib.mlptraines(), and alglib.testmlptrainunit.testmlptraines().
static void alglib.mlptrain.mlpkfoldcvlbfgs (mlpbase.multilayerperceptron network, double xy[,], int npoints, double decay, int restarts, double wstep, int maxits, int foldscount, ref int info, mlpreport rep, mlpcvreport cvrep) inline static
Referenced by alglib.mlpkfoldcvlbfgs().
static void alglib.mlptrain.mlpkfoldcvlm (mlpbase.multilayerperceptron network, double xy[,], int npoints, double decay, int restarts, int foldscount, ref int info, mlpreport rep, mlpcvreport cvrep) inline static
Referenced by alglib.mlpkfoldcvlm().
static void alglib.mlptrain.mlpkfoldcvgeneral (mlpbase.multilayerperceptron n, double xy[,], int npoints, double decay, int restarts, int foldscount, bool lmalgorithm, double wstep, int maxits, ref int info, mlpreport rep, mlpcvreport cvrep) inline static private
static void alglib.mlptrain.mlpkfoldsplit (double xy[,], int npoints, int nclasses, int foldscount, bool stratifiedsplits, ref int[] folds) inline static private
static void alglib.mlptrain.mlptrainlm (mlpbase.multilayerperceptron network, double xy[,], int npoints, double decay, int restarts, ref int info, mlpreport rep) inline static
static void alglib.mlptrain.mlptrainlbfgs (mlpbase.multilayerperceptron network, double xy[,], int npoints, double decay, int restarts, double wstep, int maxits, ref int info, mlpreport rep) inline static
static void alglib.mlptrain.mlptraines (mlpbase.multilayerperceptron network, double trnxy[,], int trnsize, double valxy[,], int valsize, double decay, int restarts, ref int info, mlpreport rep) inline static
static void alglib.mlptrain.mlpkfoldcvlbfgs (mlpbase.multilayerperceptron network, double xy[,], int npoints, double decay, int restarts, double wstep, int maxits, int foldscount, ref int info, mlpreport rep, mlpcvreport cvrep) inline static
static void alglib.mlptrain.mlpkfoldcvlm (mlpbase.multilayerperceptron network, double xy[,], int npoints, double decay, int restarts, int foldscount, ref int info, mlpreport rep, mlpcvreport cvrep) inline static
static void alglib.mlptrain.mlpkfoldcv (mlptrainer s, mlpbase.multilayerperceptron network, int nrestarts, int foldscount, mlpreport rep) inline static
Referenced by alglib.mlpkfoldcv(), and alglib.testmlptrainunit.testmlpcverror().
static void alglib.mlptrain._pexec_mlpkfoldcv (mlptrainer s, mlpbase.multilayerperceptron network, int nrestarts, int foldscount, mlpreport rep) inline static
Referenced by alglib.smp_mlpkfoldcv().
static void alglib.mlptrain.mlpcreatetrainer (int nin, int nout, mlptrainer s) inline static
Referenced by alglib.mlpcreatetrainer(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlptrainunit.testmlprestarts(), alglib.testmlptrainunit.testmlptrainensregr(), alglib.testmlptrainunit.testmlptrainregr(), alglib.testmlptrainunit.testmlpxorregr(), and alglib.testmlptrainunit.testmlpzeroweights().
static void alglib.mlptrain.mlpcreatetrainercls (int nin, int nclasses, mlptrainer s) inline static
Referenced by alglib.mlpcreatetrainercls(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlptrainunit.testmlptrainclass(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlpxorcls(), and alglib.testmlptrainunit.testmlpzeroweights().
static void alglib.mlptrain.mlpsetdataset (mlptrainer s, double xy[,], int npoints) inline static
Referenced by alglib.mlpsetdataset(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlptrainunit.testmlprestarts(), alglib.testmlptrainunit.testmlptrainclass(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlptrainensregr(), alglib.testmlptrainunit.testmlptrainregr(), alglib.testmlptrainunit.testmlpxorcls(), alglib.testmlptrainunit.testmlpxorregr(), and alglib.testmlptrainunit.testmlpzeroweights().
static void alglib.mlptrain.mlpsetsparsedataset (mlptrainer s, sparse.sparsematrix xy, int npoints) inline static
Referenced by alglib.mlpsetsparsedataset(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlptrainunit.testmlprestarts(), alglib.testmlptrainunit.testmlptrainclass(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlptrainensregr(), alglib.testmlptrainunit.testmlptrainregr(), alglib.testmlptrainunit.testmlpxorcls(), alglib.testmlptrainunit.testmlpxorregr(), and alglib.testmlptrainunit.testmlpzeroweights().
static void alglib.mlptrain.mlpsetdecay (mlptrainer s, double decay) inline static
Referenced by alglib.mlpsetdecay(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlptrainunit.testmlprestarts(), alglib.testmlptrainunit.testmlptrainclass(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlptrainensregr(), alglib.testmlptrainunit.testmlptrainregr(), alglib.testmlptrainunit.testmlpxorcls(), alglib.testmlptrainunit.testmlpxorregr(), and alglib.testmlptrainunit.testmlpzeroweights().
static void alglib.mlptrain.mlpsetcond (mlptrainer s, double wstep, int maxits) inline static
Referenced by alglib.mlpsetcond(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlptrainunit.testmlprestarts(), alglib.testmlptrainunit.testmlptrainclass(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlptrainensregr(), alglib.testmlptrainunit.testmlptrainregr(), alglib.testmlptrainunit.testmlpxorcls(), alglib.testmlptrainunit.testmlpxorregr(), and alglib.testmlptrainunit.testmlpzeroweights().
static void alglib.mlptrain.mlpsetalgobatch (mlptrainer s) inline static
Referenced by alglib.mlpsetalgobatch().
static void alglib.mlptrain.mlptrainnetwork (mlptrainer s, mlpbase.multilayerperceptron network, int nrestarts, mlpreport rep) inline static
Referenced by alglib.mlptrainnetwork(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlptrainunit.testmlprestarts(), alglib.testmlptrainunit.testmlptrainclass(), alglib.testmlptrainunit.testmlptrainregr(), alglib.testmlptrainunit.testmlpxorcls(), alglib.testmlptrainunit.testmlpxorregr(), and alglib.testmlptrainunit.testmlpzeroweights().
static void alglib.mlptrain._pexec_mlptrainnetwork (mlptrainer s, mlpbase.multilayerperceptron network, int nrestarts, mlpreport rep) inline static
Referenced by alglib.smp_mlptrainnetwork().
static void alglib.mlptrain.mlpstarttraining (mlptrainer s, mlpbase.multilayerperceptron network, bool randomstart) inline static
Referenced by alglib.mlpstarttraining(), alglib.testmlptrainunit.testmlpxorcls(), alglib.testmlptrainunit.testmlpxorregr(), and alglib.testmlptrainunit.testmlpzeroweights().
static bool alglib.mlptrain.mlpcontinuetraining (mlptrainer s, mlpbase.multilayerperceptron network) inline static
Referenced by alglib.mlpcontinuetraining(), alglib.testmlptrainunit.testmlpxorcls(), alglib.testmlptrainunit.testmlpxorregr(), and alglib.testmlptrainunit.testmlpzeroweights().
static bool alglib.mlptrain._pexec_mlpcontinuetraining (mlptrainer s, mlpbase.multilayerperceptron network) inline static
Referenced by alglib.smp_mlpcontinuetraining().
static void alglib.mlptrain.mlpebagginglm (mlpe.mlpensemble ensemble, double xy[,], int npoints, double decay, int restarts, ref int info, mlpreport rep, mlpcvreport ooberrors) inline static
Referenced by alglib.mlpebagginglm(), and alglib.testmlptrainunit.testmlptrainens().
static void alglib.mlptrain.mlpebagginglbfgs (mlpe.mlpensemble ensemble, double xy[,], int npoints, double decay, int restarts, double wstep, int maxits, ref int info, mlpreport rep, mlpcvreport ooberrors) inline static
Referenced by alglib.mlpebagginglbfgs(), and alglib.testmlptrainunit.testmlptrainens().
static void alglib.mlptrain.mlpetraines (mlpe.mlpensemble ensemble, double xy[,], int npoints, double decay, int restarts, ref int info, mlpreport rep) inline static
Referenced by alglib.mlpetraines(), alglib.testmlptrainunit.testmlptrainenscls(), and alglib.testmlptrainunit.testmlptrainensregr().
static void alglib.mlptrain.mlptrainensemblees (mlptrainer s, mlpe.mlpensemble ensemble, int nrestarts, mlpreport rep) inline static
Referenced by alglib.mlptrainensemblees(), alglib.testmlptrainunit.testmlptrainenscls(), and alglib.testmlptrainunit.testmlptrainensregr().
static void alglib.mlptrain._pexec_mlptrainensemblees (mlptrainer s, mlpe.mlpensemble ensemble, int nrestarts, mlpreport rep) inline static
Referenced by alglib.smp_mlptrainensemblees().
static void alglib.mlptrain.mlpkfoldcvgeneral (mlpbase.multilayerperceptron n, double xy[,], int npoints, double decay, int restarts, int foldscount, bool lmalgorithm, double wstep, int maxits, ref int info, mlpreport rep, mlpcvreport cvrep) inline static private
static void alglib.mlptrain.mlpkfoldsplit (double xy[,], int npoints, int nclasses, int foldscount, bool stratifiedsplits, ref int[] folds) inline static private
static void alglib.mlptrain.mthreadcv (mlptrainer s, int rowsize, int nrestarts, int[] folds, int fold, int dfold, double cvy[,], alglib.smp.shared_pool pooldatacv) inline static private
static void alglib.mlptrain.mlptrainnetworkx (mlptrainer s, int nrestarts, int algokind, int[] trnsubset, int trnsubsetsize, int[] valsubset, int valsubsetsize, mlpbase.multilayerperceptron network, mlpreport rep, bool isrootcall, alglib.smp.shared_pool sessions) inline static private
static void alglib.mlptrain.mlptrainensemblex (mlptrainer s, mlpe.mlpensemble ensemble, int idx0, int idx1, int nrestarts, int trainingmethod, apserv.sinteger ngrad, bool isrootcall, alglib.smp.shared_pool esessions) inline static private
static void alglib.mlptrain.mlpstarttrainingx (mlptrainer s, bool randomstart, int algokind, int[] subset, int subsetsize, smlptrnsession session) inline static private
static bool alglib.mlptrain.mlpcontinuetrainingx (mlptrainer s, int[] subset, int subsetsize, ref int ngradbatch, smlptrnsession session) inline static private
static void alglib.mlptrain.mlpebagginginternal (mlpe.mlpensemble ensemble, double xy[,], int npoints, double decay, int restarts, double wstep, int maxits, bool lmalgorithm, ref int info, mlpreport rep, mlpcvreport ooberrors) inline static private
static void alglib.mlptrain.initmlptrnsession (mlpbase.multilayerperceptron networktrained, bool randomizenetwork, mlptrainer trainer, smlptrnsession session) inline static private
static void alglib.mlptrain.initmlptrnsessions (mlpbase.multilayerperceptron networktrained, bool randomizenetwork, mlptrainer trainer, alglib.smp.shared_pool sessions) inline static private
static void alglib.mlptrain.initmlpetrnsession (mlpbase.multilayerperceptron individualnetwork, mlptrainer trainer, mlpetrnsession session) inline static private
static void alglib.mlptrain.initmlpetrnsessions (mlpbase.multilayerperceptron individualnetwork, mlptrainer trainer, alglib.smp.shared_pool sessions) inline static private
Member Data Documentation
const double alglib.mlptrain.mindecay = 0.001
const int alglib.mlptrain.defaultlbfgsfactor = 6
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/dataanalysis.cs