IGLib: NUnit.Engine.Services.ProjectLoaders.VSProject Class Reference
NUnit.Engine.Services.ProjectLoaders.VSProject Class Reference
This class allows loading information about configurations and assemblies in a Visual Studio project file and inspecting them. Only the most common project types are supported and an exception is thrown if an attempt is made to load an invalid file or one of an unknown type.
Classes
class ProjectConfig
Public Member Functions
VSProject (string projectPath)
TestPackage GetTestPackage ()
Gets a test package for the primary or active configuration within the project. The package includes all the assemblies and any settings specified in the project format.
TestPackage GetTestPackage (string configName)
Gets a TestPackage for a specific configuration within the project. The package includes all the assemblies and any settings specified in the project format.
Static Public Member Functions
static bool IsProjectFile (string path)
static bool IsSolutionFile (string path)
Properties
string ProjectPath [get, private set]
The path to the project
string ActiveConfigName [get]
Gets the active configuration, as defined by the particular project. For a VS project, we use the first config found.
IList< string > ConfigNames [get]
string Name [get]
The name of the project.
Properties inherited from NUnit.Engine.Extensibility.IProject
string ProjectPath [get]
Gets the path to the file storing this project, if any. If the project has not been saved, this is null.
string ActiveConfigName [get]
Gets the active configuration, as defined by the particular project.
IList< string > ConfigNames [get]
Gets a list of the configs for this project
Private Member Functions
void Load ()
Load a project in various ways, depending on the extension.
bool TryLoadLegacyProject ()
Load a project in the legacy VS2003 format. Note that this method is not called for C++ projects using the same format, because the details differ.
void LoadMSBuildProject ()
Load a non-C++ project in the MsBuild format introduced with VS2005
void LoadLegacyCppProject ()
Load a C++ project in the legacy format, which was used for C++ much longer than it was used for the other languages supported.
void ThrowInvalidFileType (string projectPath)
void ThrowInvalidFormat (string projectPath, Exception e)
string SafeAttributeValue (XmlNode node, string attrName)
string RequiredAttributeValue (XmlNode node, string name)
Static Private Member Functions
static string GetConfigNameFromCondition (XmlElement configNode)
Private Attributes
const string SOLUTION_EXTENSION = ".sln"
VS Solution extension
XmlDocument _doc
The XML representation of the project
IDictionary< string,
ProjectConfig > _configs = new Dictionary<string, ProjectConfig>()
The list of all our configs
Static Private Attributes
static readonly string[] PROJECT_EXTENSIONS = { ".csproj", ".vbproj", ".vjsproj", ".vcproj", ".fsproj" }
VS Project extentions
Detailed Description
This class allows loading information about configurations and assemblies in a Visual Studio project file and inspecting them. Only the most common project types are supported and an exception is thrown if an attempt is made to load an invalid file or one of an unknown type.
Constructor & Destructor Documentation
NUnit.Engine.Services.ProjectLoaders.VSProject.VSProject (string projectPath) inline
Member Function Documentation
TestPackage NUnit.Engine.Services.ProjectLoaders.VSProject.GetTestPackage () inline
Gets a test package for the primary or active configuration within the project. The package includes all the assemblies and any settings specified in the project format.
Returns
A TestPackage
Implements NUnit.Engine.Extensibility.IProject.
TestPackage NUnit.Engine.Services.ProjectLoaders.VSProject.GetTestPackage (string configName) inline
Gets a TestPackage for a specific configuration within the project. The package includes all the assemblies and any settings specified in the project format.
Parameters
configName The name of the config to use
Returns
A TestPackage for the named configuration.
Implements NUnit.Engine.Extensibility.IProject.
References NUnit.Engine.TestPackage.AddSubPackage().
static bool NUnit.Engine.Services.ProjectLoaders.VSProject.IsProjectFile (string path) inline static
Referenced by NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.CanLoadFrom(), NUnit.Engine.Services.ProjectLoaders.VSSolution.Load(), NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.LoadFrom(), and NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.NotWebProject().
static bool NUnit.Engine.Services.ProjectLoaders.VSProject.IsSolutionFile (string path) inline static
Referenced by NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.CanLoadFrom(), and NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.LoadFrom().
void NUnit.Engine.Services.ProjectLoaders.VSProject.Load () inline private
Load a project in various ways, depending on the extension.
bool NUnit.Engine.Services.ProjectLoaders.VSProject.TryLoadLegacyProject () inline private
Load a project in the legacy VS2003 format. Note that this method is not called for C++ projects using the same format, because the details differ.
Returns
True if this project is in the VS2003 format, otherwise false.
void NUnit.Engine.Services.ProjectLoaders.VSProject.LoadMSBuildProject () inline private
Load a non-C++ project in the MsBuild format introduced with VS2005
void NUnit.Engine.Services.ProjectLoaders.VSProject.LoadLegacyCppProject () inline private
Load a C++ project in the legacy format, which was used for C++ much longer than it was used for the other languages supported.
void NUnit.Engine.Services.ProjectLoaders.VSProject.ThrowInvalidFileType (string projectPath) inline private
void NUnit.Engine.Services.ProjectLoaders.VSProject.ThrowInvalidFormat (string projectPath, Exception e) inline private
string NUnit.Engine.Services.ProjectLoaders.VSProject.SafeAttributeValue (XmlNode node, string attrName) inline private
string NUnit.Engine.Services.ProjectLoaders.VSProject.RequiredAttributeValue (XmlNode node, string name) inline private
static string NUnit.Engine.Services.ProjectLoaders.VSProject.GetConfigNameFromCondition (XmlElement configNode) inline static private
Member Data Documentation
readonly string [] NUnit.Engine.Services.ProjectLoaders.VSProject.PROJECT_EXTENSIONS = { ".csproj", ".vbproj", ".vjsproj", ".vcproj", ".fsproj" } static private
VS Project extentions
const string NUnit.Engine.Services.ProjectLoaders.VSProject.SOLUTION_EXTENSION = ".sln" private
VS Solution extension
XmlDocument NUnit.Engine.Services.ProjectLoaders.VSProject._doc private
The XML representation of the project
IDictionary<string, ProjectConfig> NUnit.Engine.Services.ProjectLoaders.VSProject._configs = new Dictionary<string, ProjectConfig>() private
The list of all our configs
Property Documentation
string NUnit.Engine.Services.ProjectLoaders.VSProject.ProjectPath get private set
The path to the project
string NUnit.Engine.Services.ProjectLoaders.VSProject.ActiveConfigName get
Gets the active configuration, as defined by the particular project. For a VS project, we use the first config found.
IList<string> NUnit.Engine.Services.ProjectLoaders.VSProject.ConfigNames get
Referenced by NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.NoConfigurations().
string NUnit.Engine.Services.ProjectLoaders.VSProject.Name get
The name of the project.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/Addins/vs-project-loader/VSProject.cs