IGLib: Test.AdvancedMathTest Class Reference
Test.AdvancedMathTest Class Reference
Public Member Functions
void IntegerBesselSpecialCase ()
void IntegerBesselNegativeOrder ()
void IntegerBesselNegativeArgument ()
void IntegerBesselRecurrence ()
void IntegerBesselWronskian ()
void BesselJ0Integral ()
void BesselY0Integral ()
void IntegerBesselJIntegral ()
void BesselKapteynIntegral ()
void BesselLipshitzIntegral ()
void BesselWeberIntegral ()
void IntegerBesselRealBesselAgreement ()
void FullBesselRealBesselAgreement ()
void FullBesselWronskian ()
void FullBesselDerivative ()
void FullModifiedBesselDerivitive ()
void RealBesselWronskian ()
void RealBesselRecurrence ()
void RealBesselInequality ()
void RealBesselFresnel ()
void BesselTower ()
void RealBesselJIntegral ()
void SphericalBesselSpecialCase ()
void SphericalBesselRecurrence ()
void SphericalBesselNegativeOrder ()
void SphericalBesselWronskian ()
void SphericalBesselRealBesselAgreement ()
void SphericalBesselTower ()
void GammaRecurrsion ()
void GammaSpecialCases ()
void GammaReflection ()
void GammaInequality ()
void GammaIntegral ()
void GammaTrottIdentity ()
void LogGammaDuplication ()
void LogGammaTriplication ()
void LogGammaNegativeArgument ()
void GammaRatioInequality ()
void PsiSpecialCases ()
void PsiRecurrence ()
void PsiReflection ()
void PsiDuplication ()
void TriGammaSpecialCases ()
void TriGammaReflection ()
void TetraGammaReflection ()
void PolyGammaRiemann ()
void PolyGammaDuplication ()
void PolyGammaIntegral ()
void PolyGammaRecurrence ()
void DigammaAgreement ()
void RegularizedIncompleteGammaRecurrence ()
void RegularizedIncompleteGammaExponential ()
void RegularizedIncompleteGammaUnitarity ()
void IncompleteGammaInequality ()
void IncompleteGammaIntegerInequality ()
void IncompleteGammaErfc ()
void IncompleteGammaExp ()
void BetaSpecialValues ()
void BetaIntegral ()
void BetaRecurrence ()
void BetaTransformationTest ()
void BetaInequality ()
void IncompleteBetaLimits ()
void IncompleteBetaIdentity1 ()
void IncompleteBetaIdentity2 ()
void IncompleteBetaRecurrence ()
void ErfNegativeArgumentsTest ()
void ErrorFunctionSpecialCases ()
void InverseErrofFunctionSpecialCases ()
void InverseErfTest ()
void InverseErfIntegralTest ()
void ErfIntegralTest ()
void ErrorFunctionComplementarity ()
void ErfcInequality ()
void ErfcIntegral ()
void IntegralESpecialCaseTest ()
void IntegralE1Inequality ()
void IntegralEInequality ()
void IntegralERecurrence ()
void IntegralEIntegral ()
void IntegralEIncompleteGamma ()
void IntegralEInvalidArgumentTest ()
void RiemannZetaSpecialCaseTest ()
void RiemannZetaReflectionTest ()
void ReimannZetaPrimesTest ()
void DirichletEtaSpecialCaseTest ()
void DawsonSpecialCaseTest ()
void DawsonInequalityTest ()
void DawsonIntegralTest ()
void FresnelReflectionTest ()
void FresnelSIntegralTest ()
void FresnelCIntegralTest ()
void IntegralSiDefinition ()
void IntegralCiSiIntegrals ()
void LambertTest ()
void LambertSpecialCaseTest ()
void CoulombEtaZeroTest ()
void CoulombWronskianTest ()
void CoulombRecursionTest ()
void ModifiedBesselArgumentZeroTest ()
void ModifiedBesselWronskianTest ()
void ModifiedBesselHalfIntegerOrderTest ()
void ModifiedBesselTower ()
void ModifiedBesselIntegralTest ()
void ModifiedBesselAgreement ()
void ModifiedBesselWronskian ()
void BesselModifiedBesselRelationship ()
void AiryIntegral ()
void AiryZeroArgument ()
void AiryIntegrals ()
void AiryBairyIntegral ()
void AiryWronskian ()
void GoldenRatioTest ()
void CatalanIntegralTest ()
void DiLogSpecialCases ()
void DiLogDuplication ()
void DiLogBailyIdentity ()
void DiLogExpIntegral ()
void DiLogLogIntegral ()
void PolyLogSpecialCases ()
void PolyLogOneHalf ()
void TriLogSpecialCases ()
void TriLogBaileyLadders ()
void PolyLogIntegration ()
void PolyLogDuplication ()
void EllipticKSpecialCases ()
void EllipticKInequality ()
void EllipticKIntegration ()
void EllipticKCatalanIntegral ()
void EllipticFSpecialCases ()
void EllipticFIntegration ()
void CarlsonFDuplication ()
void CarlsonFSpecialCases ()
void CarlsonFInequality ()
void CarlsonDSymmetrizedSum ()
void CarslonDSpecialCases ()
void CarlsonLegendreRelation ()
void CarlsonLemniscaticValues ()
void EllipticESPecialCases ()
void EllipticLegendreRelation ()
void EllipticEIntegration ()
void EllipticLandenTransform ()
void EllipticKCarlsonFRelationship ()
void EllipticFBetaRelationship ()
void EllipticFIntegral ()
void ClausenSpecialValues ()
void ClausenIntegral ()
void ClausenSymmetries ()
void IntegralTiDefinition ()
Private Member Functions
bool BesselYInRange (double n, double x)
Static Private Member Functions
static void CoulombWronskianHelper (int L, double eta, double rho)
static void CoulombRecursionTestHelper (double L, double eta, double rho, double UM, double U, double UP)
Private Attributes
int[] orders = new int[] { 3, 30, 300 }
double[] arguments = new double[] { 0.11, 1.1, 11.1, 111.1 }
int[] primes = new int[] { 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97 }
Member Function Documentation
bool Test.AdvancedMathTest.BesselYInRange (double n, double x) inline private
References Meta.Numerics.Functions.AdvancedMath.LogGamma().
Referenced by Test.AdvancedMathTest.FullBesselDerivative(), Test.AdvancedMathTest.FullBesselRealBesselAgreement(), Test.AdvancedMathTest.FullBesselWronskian(), Test.AdvancedMathTest.IntegerBesselRealBesselAgreement(), Test.AdvancedMathTest.IntegerBesselRecurrence(), Test.AdvancedMathTest.IntegerBesselWronskian(), Test.AdvancedMathTest.RealBesselInequality(), Test.AdvancedMathTest.RealBesselRecurrence(), Test.AdvancedMathTest.RealBesselWronskian(), Test.AdvancedMathTest.SphericalBesselRealBesselAgreement(), Test.AdvancedMathTest.SphericalBesselRecurrence(), and Test.AdvancedMathTest.SphericalBesselWronskian().
void Test.AdvancedMathTest.IntegerBesselSpecialCase () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), and Meta.Numerics.Functions.AdvancedMath.BesselY().
void Test.AdvancedMathTest.IntegerBesselNegativeOrder () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), and Meta.Numerics.Functions.AdvancedMath.BesselY().
void Test.AdvancedMathTest.IntegerBesselNegativeArgument () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ().
void Test.AdvancedMathTest.IntegerBesselRecurrence () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Functions.AdvancedMath.BesselY(), and Test.AdvancedMathTest.BesselYInRange().
void Test.AdvancedMathTest.IntegerBesselWronskian () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Functions.AdvancedMath.BesselY(), Test.AdvancedMathTest.BesselYInRange(), and Meta.Numerics.Functions.AdvancedMath.LogGamma().
void Test.AdvancedMathTest.BesselJ0Integral () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.BesselY0Integral () inline
References Meta.Numerics.Functions.AdvancedMath.BesselY(), Meta.Numerics.Functions.AdvancedMath.EulerGamma, Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.IntegerBesselJIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.BesselKapteynIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.BesselLipshitzIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.BesselWeberIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.IntegerBesselRealBesselAgreement () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Functions.AdvancedMath.BesselY(), and Test.AdvancedMathTest.BesselYInRange().
void Test.AdvancedMathTest.FullBesselRealBesselAgreement () inline
References Meta.Numerics.Functions.AdvancedMath.Bessel(), Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Functions.AdvancedMath.BesselY(), Test.AdvancedMathTest.BesselYInRange(), Meta.Numerics.Functions.SolutionPair.FirstSolutionValue, and Meta.Numerics.Functions.SolutionPair.SecondSolutionValue.
void Test.AdvancedMathTest.FullBesselWronskian () inline
References Meta.Numerics.Functions.AdvancedMath.Bessel(), Test.AdvancedMathTest.BesselYInRange(), Meta.Numerics.Functions.SolutionPair.FirstSolutionDerivative, Meta.Numerics.Functions.SolutionPair.FirstSolutionValue, Meta.Numerics.Functions.SolutionPair.SecondSolutionDerivative, and Meta.Numerics.Functions.SolutionPair.SecondSolutionValue.
void Test.AdvancedMathTest.FullBesselDerivative () inline
References Meta.Numerics.Functions.AdvancedMath.Bessel(), Test.AdvancedMathTest.BesselYInRange(), Meta.Numerics.Functions.SolutionPair.FirstSolutionDerivative, Meta.Numerics.Functions.SolutionPair.FirstSolutionValue, Meta.Numerics.Functions.SolutionPair.SecondSolutionDerivative, and Meta.Numerics.Functions.SolutionPair.SecondSolutionValue.
void Test.AdvancedMathTest.FullModifiedBesselDerivitive () inline
References Meta.Numerics.Functions.SolutionPair.FirstSolutionDerivative, Meta.Numerics.Functions.SolutionPair.FirstSolutionValue, Meta.Numerics.Functions.AdvancedMath.ModifiedBessel(), Meta.Numerics.Functions.SolutionPair.SecondSolutionDerivative, and Meta.Numerics.Functions.SolutionPair.SecondSolutionValue.
void Test.AdvancedMathTest.RealBesselWronskian () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Functions.AdvancedMath.BesselY(), and Test.AdvancedMathTest.BesselYInRange().
void Test.AdvancedMathTest.RealBesselRecurrence () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Functions.AdvancedMath.BesselY(), and Test.AdvancedMathTest.BesselYInRange().
void Test.AdvancedMathTest.RealBesselInequality () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Functions.AdvancedMath.BesselY(), and Test.AdvancedMathTest.BesselYInRange().
void Test.AdvancedMathTest.RealBesselFresnel () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ().
void Test.AdvancedMathTest.BesselTower () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ().
void Test.AdvancedMathTest.RealBesselJIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Functions.AdvancedMath.Gamma(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.SphericalBesselSpecialCase () inline
References Meta.Numerics.Functions.AdvancedMath.SphericalBesselJ(), and Meta.Numerics.Functions.AdvancedMath.SphericalBesselY().
void Test.AdvancedMathTest.SphericalBesselRecurrence () inline
References Test.AdvancedMathTest.BesselYInRange(), Meta.Numerics.Functions.AdvancedMath.SphericalBesselJ(), and Meta.Numerics.Functions.AdvancedMath.SphericalBesselY().
void Test.AdvancedMathTest.SphericalBesselNegativeOrder () inline
References Meta.Numerics.Functions.AdvancedMath.SphericalBesselJ(), and Meta.Numerics.Functions.AdvancedMath.SphericalBesselY().
void Test.AdvancedMathTest.SphericalBesselWronskian () inline
References Test.AdvancedMathTest.BesselYInRange(), Meta.Numerics.Functions.AdvancedMath.SphericalBesselJ(), and Meta.Numerics.Functions.AdvancedMath.SphericalBesselY().
void Test.AdvancedMathTest.SphericalBesselRealBesselAgreement () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Functions.AdvancedMath.BesselY(), Test.AdvancedMathTest.BesselYInRange(), Meta.Numerics.Functions.AdvancedMath.SphericalBesselJ(), and Meta.Numerics.Functions.AdvancedMath.SphericalBesselY().
void Test.AdvancedMathTest.SphericalBesselTower () inline
References Meta.Numerics.Functions.AdvancedMath.IntegralSi(), and Meta.Numerics.Functions.AdvancedMath.SphericalBesselJ().
void Test.AdvancedMathTest.GammaRecurrsion () inline
References Meta.Numerics.Functions.AdvancedMath.Gamma().
void Test.AdvancedMathTest.GammaSpecialCases () inline
References Meta.Numerics.Functions.AdvancedMath.Gamma().
void Test.AdvancedMathTest.GammaReflection () inline
References Meta.Numerics.Functions.AdvancedMath.Gamma().
void Test.AdvancedMathTest.GammaInequality () inline
References Meta.Numerics.Functions.AdvancedMath.Gamma().
void Test.AdvancedMathTest.GammaIntegral () inline
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Functions.AdvancedMath.Gamma(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.GammaTrottIdentity () inline
References Meta.Numerics.Functions.AdvancedMath.Gamma().
void Test.AdvancedMathTest.LogGammaDuplication () inline
References Meta.Numerics.Functions.AdvancedMath.LogGamma().
void Test.AdvancedMathTest.LogGammaTriplication () inline
References Meta.Numerics.Functions.AdvancedMath.LogGamma().
void Test.AdvancedMathTest.LogGammaNegativeArgument () inline
References Meta.Numerics.Functions.AdvancedMath.LogGamma().
void Test.AdvancedMathTest.GammaRatioInequality () inline
References Meta.Numerics.Functions.AdvancedMath.LogGamma().
void Test.AdvancedMathTest.PsiSpecialCases () inline
References Meta.Numerics.Functions.AdvancedMath.EulerGamma, and Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.AdvancedMathTest.PsiRecurrence () inline
References Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.AdvancedMathTest.PsiReflection () inline
References Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.AdvancedMathTest.PsiDuplication () inline
References Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.AdvancedMathTest.TriGammaSpecialCases () inline
References Meta.Numerics.Functions.AdvancedMath.Catalan, and Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.AdvancedMathTest.TriGammaReflection () inline
References Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.AdvancedMathTest.TetraGammaReflection () inline
References Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.AdvancedMathTest.PolyGammaRiemann () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.MoreMath.Pow(), Meta.Numerics.Functions.AdvancedMath.Psi(), and Meta.Numerics.Functions.AdvancedMath.RiemannZeta().
void Test.AdvancedMathTest.PolyGammaDuplication () inline
References Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.AdvancedMathTest.PolyGammaIntegral () inline
References Meta.Numerics.MoreMath.ExpMinusOne(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.AdvancedMathTest.PolyGammaRecurrence () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.AdvancedMathTest.DigammaAgreement () inline
References Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.AdvancedMathTest.RegularizedIncompleteGammaRecurrence () inline
References Meta.Numerics.Functions.AdvancedMath.Gamma(), and Meta.Numerics.Functions.AdvancedMath.LeftRegularizedGamma().
void Test.AdvancedMathTest.RegularizedIncompleteGammaExponential () inline
References Meta.Numerics.Functions.AdvancedMath.RightRegularizedGamma().
void Test.AdvancedMathTest.RegularizedIncompleteGammaUnitarity () inline
References Meta.Numerics.Functions.AdvancedMath.LeftRegularizedGamma(), and Meta.Numerics.Functions.AdvancedMath.RightRegularizedGamma().
void Test.AdvancedMathTest.IncompleteGammaInequality () inline
References Meta.Numerics.Functions.AdvancedMath.Gamma().
void Test.AdvancedMathTest.IncompleteGammaIntegerInequality () inline
References Meta.Numerics.Functions.AdvancedMath.RightRegularizedGamma().
void Test.AdvancedMathTest.IncompleteGammaErfc () inline
References Meta.Numerics.Functions.AdvancedMath.Erfc(), and Meta.Numerics.Functions.AdvancedMath.Gamma().
void Test.AdvancedMathTest.IncompleteGammaExp () inline
References Meta.Numerics.Functions.AdvancedMath.Gamma().
void Test.AdvancedMathTest.BetaSpecialValues () inline
References Meta.Numerics.Functions.AdvancedMath.Beta().
void Test.AdvancedMathTest.BetaIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.Beta(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.BetaRecurrence () inline
References Meta.Numerics.Functions.AdvancedMath.Beta().
void Test.AdvancedMathTest.BetaTransformationTest () inline
References Meta.Numerics.Functions.AdvancedMath.Beta().
void Test.AdvancedMathTest.BetaInequality () inline
References Meta.Numerics.Functions.AdvancedMath.Beta().
void Test.AdvancedMathTest.IncompleteBetaLimits () inline
References Meta.Numerics.Functions.AdvancedMath.LeftRegularizedBeta().
void Test.AdvancedMathTest.IncompleteBetaIdentity1 () inline
References Meta.Numerics.Functions.AdvancedMath.LeftRegularizedBeta().
void Test.AdvancedMathTest.IncompleteBetaIdentity2 () inline
References Meta.Numerics.Functions.AdvancedMath.LeftRegularizedBeta().
void Test.AdvancedMathTest.IncompleteBetaRecurrence () inline
References Meta.Numerics.Functions.AdvancedMath.LeftRegularizedBeta().
void Test.AdvancedMathTest.ErfNegativeArgumentsTest () inline
References Meta.Numerics.Functions.AdvancedMath.Erf().
void Test.AdvancedMathTest.ErrorFunctionSpecialCases () inline
References Meta.Numerics.Functions.AdvancedMath.Erf(), and Meta.Numerics.Functions.AdvancedMath.Erfc().
void Test.AdvancedMathTest.InverseErrofFunctionSpecialCases () inline
References Meta.Numerics.Functions.AdvancedMath.InverseErf(), and Meta.Numerics.Functions.AdvancedMath.InverseErfc().
void Test.AdvancedMathTest.InverseErfTest () inline
References Meta.Numerics.Functions.AdvancedMath.Erf(), Meta.Numerics.Functions.AdvancedMath.Erfc(), Meta.Numerics.Functions.AdvancedMath.InverseErf(), and Meta.Numerics.Functions.AdvancedMath.InverseErfc().
void Test.AdvancedMathTest.InverseErfIntegralTest () inline
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), and Meta.Numerics.Functions.AdvancedMath.InverseErf().
void Test.AdvancedMathTest.ErfIntegralTest () inline
References Meta.Numerics.Functions.AdvancedMath.Erf(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.ErrorFunctionComplementarity () inline
References Meta.Numerics.Functions.AdvancedMath.Erf(), and Meta.Numerics.Functions.AdvancedMath.Erfc().
void Test.AdvancedMathTest.ErfcInequality () inline
References Meta.Numerics.Functions.AdvancedMath.Erfc().
void Test.AdvancedMathTest.ErfcIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.Erfc(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.IntegralESpecialCaseTest () inline
References Meta.Numerics.Functions.AdvancedMath.IntegralE().
void Test.AdvancedMathTest.IntegralE1Inequality () inline
References Meta.Numerics.Functions.AdvancedMath.IntegralE().
void Test.AdvancedMathTest.IntegralEInequality () inline
References Meta.Numerics.Functions.AdvancedMath.IntegralE().
void Test.AdvancedMathTest.IntegralERecurrence () inline
References Meta.Numerics.Functions.AdvancedMath.IntegralE().
void Test.AdvancedMathTest.IntegralEIntegral () inline
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Functions.AdvancedMath.IntegralE(), Meta.Numerics.Analysis.FunctionMath.Integrate(), and Meta.Numerics.MoreMath.Pow().
void Test.AdvancedMathTest.IntegralEIncompleteGamma () inline
References Meta.Numerics.Functions.AdvancedMath.Gamma(), Meta.Numerics.Functions.AdvancedMath.IntegralE(), and Meta.Numerics.MoreMath.Pow().
void Test.AdvancedMathTest.IntegralEInvalidArgumentTest () inline
References Meta.Numerics.Functions.AdvancedMath.IntegralE().
void Test.AdvancedMathTest.RiemannZetaSpecialCaseTest () inline
References Meta.Numerics.Functions.AdvancedMath.RiemannZeta().
void Test.AdvancedMathTest.RiemannZetaReflectionTest () inline
References Meta.Numerics.Functions.AdvancedMath.Gamma(), and Meta.Numerics.Functions.AdvancedMath.RiemannZeta().
void Test.AdvancedMathTest.ReimannZetaPrimesTest () inline
References Test.AdvancedMathTest.primes, and Meta.Numerics.Functions.AdvancedMath.RiemannZeta().
void Test.AdvancedMathTest.DirichletEtaSpecialCaseTest () inline
References Meta.Numerics.Functions.AdvancedMath.DirichletEta().
void Test.AdvancedMathTest.DawsonSpecialCaseTest () inline
void Test.AdvancedMathTest.DawsonInequalityTest () inline
void Test.AdvancedMathTest.DawsonIntegralTest () inline
References Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.FresnelReflectionTest () inline
void Test.AdvancedMathTest.FresnelSIntegralTest () inline
References Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.FresnelCIntegralTest () inline
References Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.IntegralSiDefinition () inline
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Functions.AdvancedMath.IntegralSi(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.IntegralCiSiIntegrals () inline
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Functions.AdvancedMath.IntegralCi(), Meta.Numerics.Functions.AdvancedMath.IntegralSi(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.LambertTest () inline
References Meta.Numerics.Functions.AdvancedMath.LambertW().
void Test.AdvancedMathTest.LambertSpecialCaseTest () inline
References Meta.Numerics.Functions.AdvancedMath.LambertW().
void Test.AdvancedMathTest.CoulombEtaZeroTest () inline
References Meta.Numerics.Functions.AdvancedMath.CoulombF(), and Meta.Numerics.Functions.AdvancedMath.CoulombG().
void Test.AdvancedMathTest.CoulombWronskianTest () inline
References Test.AdvancedMathTest.CoulombWronskianHelper().
static void Test.AdvancedMathTest.CoulombWronskianHelper (int L, double eta, double rho) inline static private
References Meta.Numerics.Functions.AdvancedMath.CoulombF(), and Meta.Numerics.Functions.AdvancedMath.CoulombG().
Referenced by Test.AdvancedMathTest.CoulombWronskianTest().
void Test.AdvancedMathTest.CoulombRecursionTest () inline
References Meta.Numerics.Functions.AdvancedMath.CoulombF(), Meta.Numerics.Functions.AdvancedMath.CoulombG(), and Test.AdvancedMathTest.CoulombRecursionTestHelper().
static void Test.AdvancedMathTest.CoulombRecursionTestHelper (double L, double eta, double rho, double UM, double U, double UP) inline static private
Referenced by Test.AdvancedMathTest.CoulombRecursionTest().
void Test.AdvancedMathTest.ModifiedBesselArgumentZeroTest () inline
References Meta.Numerics.Functions.AdvancedMath.ModifiedBesselI(), and Meta.Numerics.Functions.AdvancedMath.ModifiedBesselK().
void Test.AdvancedMathTest.ModifiedBesselWronskianTest () inline
References Meta.Numerics.Functions.AdvancedMath.ModifiedBesselI(), and Meta.Numerics.Functions.AdvancedMath.ModifiedBesselK().
void Test.AdvancedMathTest.ModifiedBesselHalfIntegerOrderTest () inline
References Meta.Numerics.Functions.AdvancedMath.ModifiedBesselI(), and Meta.Numerics.Functions.AdvancedMath.ModifiedBesselK().
void Test.AdvancedMathTest.ModifiedBesselTower () inline
References Meta.Numerics.Functions.AdvancedMath.ModifiedBesselI().
void Test.AdvancedMathTest.ModifiedBesselIntegralTest () inline
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), and Meta.Numerics.Functions.AdvancedMath.ModifiedBesselI().
void Test.AdvancedMathTest.ModifiedBesselAgreement () inline
References Meta.Numerics.Functions.SolutionPair.FirstSolutionValue, Meta.Numerics.Functions.AdvancedMath.ModifiedBessel(), Meta.Numerics.Functions.AdvancedMath.ModifiedBesselI(), Meta.Numerics.Functions.AdvancedMath.ModifiedBesselK(), and Meta.Numerics.Functions.SolutionPair.SecondSolutionValue.
void Test.AdvancedMathTest.ModifiedBesselWronskian () inline
References Meta.Numerics.Functions.SolutionPair.FirstSolutionDerivative, Meta.Numerics.Functions.SolutionPair.FirstSolutionValue, Meta.Numerics.Functions.AdvancedMath.ModifiedBessel(), Meta.Numerics.Functions.SolutionPair.SecondSolutionDerivative, and Meta.Numerics.Functions.SolutionPair.SecondSolutionValue.
void Test.AdvancedMathTest.BesselModifiedBesselRelationship () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.Functions.AdvancedMath.ModifiedBesselI(), and Meta.Numerics.MoreMath.Pow().
void Test.AdvancedMathTest.AiryIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.AiryAi(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.AiryZeroArgument () inline
References Meta.Numerics.Functions.AdvancedMath.AiryAi(), Meta.Numerics.Functions.AdvancedMath.AiryBi(), and Meta.Numerics.Functions.AdvancedMath.Gamma().
void Test.AdvancedMathTest.AiryIntegrals () inline
References Meta.Numerics.Functions.AdvancedMath.AiryAi(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), and Meta.Numerics.MoreMath.Pow().
void Test.AdvancedMathTest.AiryBairyIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.AiryAi(), Meta.Numerics.Functions.AdvancedMath.AiryBi(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), and Meta.Numerics.MoreMath.Pow().
void Test.AdvancedMathTest.AiryWronskian () inline
References Meta.Numerics.Functions.AdvancedMath.Airy(), Meta.Numerics.Functions.SolutionPair.FirstSolutionDerivative, Meta.Numerics.Functions.SolutionPair.FirstSolutionValue, Meta.Numerics.Functions.SolutionPair.SecondSolutionDerivative, and Meta.Numerics.Functions.SolutionPair.SecondSolutionValue.
void Test.AdvancedMathTest.GoldenRatioTest () inline
References Meta.Numerics.Functions.AdvancedMath.GoldenRatio.
void Test.AdvancedMathTest.CatalanIntegralTest () inline
References Meta.Numerics.Functions.AdvancedMath.Catalan, Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.DiLogSpecialCases () inline
References Meta.Numerics.Functions.AdvancedMath.DiLog(), and Meta.Numerics.Functions.AdvancedMath.GoldenRatio.
void Test.AdvancedMathTest.DiLogDuplication () inline
References Meta.Numerics.Functions.AdvancedMath.DiLog().
void Test.AdvancedMathTest.DiLogBailyIdentity () inline
References Meta.Numerics.Functions.AdvancedMath.DiLog(), and Meta.Numerics.MoreMath.Pow().
void Test.AdvancedMathTest.DiLogExpIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.DiLog(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.DiLogLogIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.DiLog(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.PolyLogSpecialCases () inline
References Meta.Numerics.Functions.AdvancedMath.DirichletEta(), Meta.Numerics.Functions.AdvancedMath.PolyLog(), and Meta.Numerics.Functions.AdvancedMath.RiemannZeta().
void Test.AdvancedMathTest.PolyLogOneHalf () inline
References Meta.Numerics.Functions.AdvancedMath.PolyLog(), Meta.Numerics.MoreMath.Pow(), Meta.Numerics.Functions.AdvancedMath.RiemannZeta(), and Meta.Numerics.MoreMath.Sqr().
void Test.AdvancedMathTest.TriLogSpecialCases () inline
References Meta.Numerics.Functions.AdvancedMath.GoldenRatio, Meta.Numerics.Functions.AdvancedMath.PolyLog(), Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Functions.AdvancedMath.RiemannZeta().
void Test.AdvancedMathTest.TriLogBaileyLadders () inline
References Meta.Numerics.Functions.AdvancedMath.PolyLog(), and Meta.Numerics.Functions.AdvancedMath.RiemannZeta().
void Test.AdvancedMathTest.PolyLogIntegration () inline
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), and Meta.Numerics.Functions.AdvancedMath.PolyLog().
void Test.AdvancedMathTest.PolyLogDuplication () inline
References Meta.Numerics.Functions.AdvancedMath.PolyLog(), and Meta.Numerics.MoreMath.Pow().
void Test.AdvancedMathTest.EllipticKSpecialCases () inline
References Meta.Numerics.Functions.AdvancedMath.EllipticK(), and Meta.Numerics.Functions.AdvancedMath.Gamma().
void Test.AdvancedMathTest.EllipticKInequality () inline
References Meta.Numerics.Functions.AdvancedMath.EllipticK().
void Test.AdvancedMathTest.EllipticKIntegration () inline
References Meta.Numerics.Functions.AdvancedMath.EllipticK(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.EllipticKCatalanIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.Catalan, Meta.Numerics.Functions.AdvancedMath.EllipticK(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.EllipticFSpecialCases () inline
References Meta.Numerics.Functions.AdvancedMath.EllipticF().
void Test.AdvancedMathTest.EllipticFIntegration () inline
References Meta.Numerics.Functions.AdvancedMath.EllipticF(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.CarlsonFDuplication () inline
References Meta.Numerics.Functions.AdvancedMath.CarlsonF().
void Test.AdvancedMathTest.CarlsonFSpecialCases () inline
References Meta.Numerics.Functions.AdvancedMath.CarlsonF().
void Test.AdvancedMathTest.CarlsonFInequality () inline
References Meta.Numerics.Functions.AdvancedMath.CarlsonF().
void Test.AdvancedMathTest.CarlsonDSymmetrizedSum () inline
References Meta.Numerics.Functions.AdvancedMath.CarlsonD(), and Meta.Numerics.Functions.AdvancedMath.CarlsonF().
void Test.AdvancedMathTest.CarslonDSpecialCases () inline
References Meta.Numerics.Functions.AdvancedMath.CarlsonD().
void Test.AdvancedMathTest.CarlsonLegendreRelation () inline
References Meta.Numerics.Functions.AdvancedMath.CarlsonD(), and Meta.Numerics.Functions.AdvancedMath.CarlsonF().
void Test.AdvancedMathTest.CarlsonLemniscaticValues () inline
References Meta.Numerics.Functions.AdvancedMath.CarlsonD(), Meta.Numerics.Functions.AdvancedMath.CarlsonF(), Meta.Numerics.Functions.AdvancedMath.Gamma(), and Meta.Numerics.MoreMath.Pow().
void Test.AdvancedMathTest.EllipticESPecialCases () inline
References Meta.Numerics.Functions.AdvancedMath.EllipticE(), and Meta.Numerics.Functions.AdvancedMath.Gamma().
void Test.AdvancedMathTest.EllipticLegendreRelation () inline
References Meta.Numerics.Functions.AdvancedMath.EllipticE(), and Meta.Numerics.Functions.AdvancedMath.EllipticK().
void Test.AdvancedMathTest.EllipticEIntegration () inline
References Meta.Numerics.Functions.AdvancedMath.EllipticE(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.EllipticLandenTransform () inline
References Meta.Numerics.Functions.AdvancedMath.EllipticE(), and Meta.Numerics.Functions.AdvancedMath.EllipticK().
void Test.AdvancedMathTest.EllipticKCarlsonFRelationship () inline
References Meta.Numerics.Functions.AdvancedMath.CarlsonF(), and Meta.Numerics.Functions.AdvancedMath.EllipticK().
void Test.AdvancedMathTest.EllipticFBetaRelationship () inline
References Meta.Numerics.Functions.AdvancedMath.Beta(), Meta.Numerics.Functions.AdvancedMath.EllipticF(), and Meta.Numerics.MoreMath.Pow().
void Test.AdvancedMathTest.EllipticFIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.EllipticF(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), and Meta.Numerics.MoreMath.Pow().
void Test.AdvancedMathTest.ClausenSpecialValues () inline
References Meta.Numerics.Functions.AdvancedMath.Catalan, Meta.Numerics.Functions.AdvancedMath.Clausen(), and Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.AdvancedMathTest.ClausenIntegral () inline
References Meta.Numerics.Functions.AdvancedMath.Clausen(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
void Test.AdvancedMathTest.ClausenSymmetries () inline
References Meta.Numerics.Functions.AdvancedMath.Clausen().
void Test.AdvancedMathTest.IntegralTiDefinition () inline
References Meta.Numerics.Functions.AdvancedMath.IntegralTi().
Member Data Documentation
int [] Test.AdvancedMathTest.orders = new int[] { 3, 30, 300 } private
double [] Test.AdvancedMathTest.arguments = new double[] { 0.11, 1.1, 11.1, 111.1 } private
int [] Test.AdvancedMathTest.primes = new int[] { 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97 } private
Referenced by Test.AdvancedMathTest.ReimannZetaPrimesTest().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/AdvancedMathTest.cs