IGLib: Test.BugTests Class Reference
Test.BugTests Class Reference
Public Member Functions
void Bug7788 ()
void Bug7686 ()
void Bug7685 ()
void Bug7684 ()
void Bug7213 ()
void Bug7208 ()
void Bug6162 ()
void Bug2811 ()
void Bug5504 ()
void DifficultEigenvalue ()
void Bug5505 ()
void Bug5705 ()
void Bug5886 ()
void Bug6392 ()
void Bug6391 ()
void Bug6988 ()
Private Member Functions
SquareMatrix CyclicMatrix (int n)
Member Function Documentation
void Test.BugTests.Bug7788 () inline
References Meta.Numerics.Statistics.Distributions.Distribution.GetRandomValue(), Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Distributions.Distribution.Median, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation.
void Test.BugTests.Bug7686 () inline
References Meta.Numerics.Matrices.RectangularMatrix.SingularValueDecomposition().
void Test.BugTests.Bug7685 () inline
References Meta.Numerics.Matrices.SquareMatrix.SingularValueDecomposition().
void Test.BugTests.Bug7684 () inline
References Meta.Numerics.Statistics.Distributions.BetaDistribution.InverseLeftProbability(), and Meta.Numerics.Statistics.Distributions.BetaDistribution.LeftProbability().
void Test.BugTests.Bug7213 () inline
References Meta.Numerics.Statistics.Sample.Add(), and Meta.Numerics.Statistics.Distributions.WeibullDistribution.FitToSample().
void Test.BugTests.Bug7208 () inline
References Meta.Numerics.Matrices.SquareMatrix.Eigensystem(), Meta.Numerics.Matrices.ComplexEigensystem.Eigenvalue(), Meta.Numerics.Matrices.ComplexEigensystem.Eigenvector(), Meta.Numerics.Matrices.SquareMatrix.Inverse(), and Meta.Numerics.Complex.Re.
void Test.BugTests.Bug6162 () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.FitResult.Dimension, Meta.Numerics.Statistics.UncertainMeasurementSample.FitToPolynomial(), Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.BivariateSample.PolynomialRegression(), and Meta.Numerics.UncertainValue.Value.
void Test.BugTests.Bug2811 () inline
References Meta.Numerics.Statistics.Distributions.ChiSquaredDistribution.InverseLeftProbability().
SquareMatrix Test.BugTests.CyclicMatrix (int n) inline private
Referenced by Test.BugTests.Bug5504().
void Test.BugTests.Bug5504 () inline
References Meta.Numerics.ComplexMath.Abs(), Meta.Numerics.ComplexMath.Arg(), Test.BugTests.CyclicMatrix(), and Meta.Numerics.Matrices.SquareMatrix.Eigenvalues().
void Test.BugTests.DifficultEigenvalue () inline
References Meta.Numerics.ComplexMath.Abs(), Meta.Numerics.ComplexMath.Arg(), and Meta.Numerics.Matrices.SquareMatrix.Eigenvalues().
void Test.BugTests.Bug5505 () inline
References Meta.Numerics.Analysis.FunctionMath.FindZero().
void Test.BugTests.Bug5705 () inline
References Meta.Numerics.Functions.AdvancedMath.Erf(), and Meta.Numerics.Functions.AdvancedMath.Erfc().
void Test.BugTests.Bug5886 () inline
References Meta.Numerics.Statistics.Distributions.FisherDistribution.InverseLeftProbability(), and Meta.Numerics.Statistics.Distributions.FisherDistribution.LeftProbability().
void Test.BugTests.Bug6392 () inline
void Test.BugTests.Bug6391 () inline
void Test.BugTests.Bug6988 () inline
References Meta.Numerics.Statistics.Sample.InverseLeftProbability(), and Meta.Numerics.Statistics.Sample.LeftProbability().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/Bugs.cs