IGLib: alglib.tsort Class Reference
alglib.tsort Class Reference
Static Public Member Functions
static void tagsort (ref double[] a, int n, ref int[] p1, ref int[] p2)
static void tagsortbuf (ref double[] a, int n, ref int[] p1, ref int[] p2, apserv.apbuffers buf)
static void tagsortfasti (ref double[] a, ref int[] b, ref double[] bufa, ref int[] bufb, int n)
static void tagsortfastr (ref double[] a, ref double[] b, ref double[] bufa, ref double[] bufb, int n)
static void tagsortfast (ref double[] a, ref double[] bufa, int n)
static void tagsortmiddleir (ref int[] a, ref double[] b, int offset, int n)
static void tagheappushi (ref double[] a, ref int[] b, ref int n, double va, int vb)
static void tagheapreplacetopi (ref double[] a, ref int[] b, int n, double va, int vb)
static void tagheappopi (ref double[] a, ref int[] b, ref int n)
static int lowerbound (double[] a, int n, double t)
static int upperbound (double[] a, int n, double t)
static void tagsort (ref double[] a, int n, ref int[] p1, ref int[] p2)
static void tagsortbuf (ref double[] a, int n, ref int[] p1, ref int[] p2, apserv.apbuffers buf)
static void tagsortfasti (ref double[] a, ref int[] b, ref double[] bufa, ref int[] bufb, int n)
static void tagsortfastr (ref double[] a, ref double[] b, ref double[] bufa, ref double[] bufb, int n)
static void tagsortfast (ref double[] a, ref double[] bufa, int n)
static void tagsortmiddleir (ref int[] a, ref double[] b, int offset, int n)
static void tagheappushi (ref double[] a, ref int[] b, ref int n, double va, int vb)
static void tagheapreplacetopi (ref double[] a, ref int[] b, int n, double va, int vb)
static void tagheappopi (ref double[] a, ref int[] b, ref int n)
static int lowerbound (double[] a, int n, double t)
static int upperbound (double[] a, int n, double t)
Static Private Member Functions
static void tagsortfastirec (ref double[] a, ref int[] b, ref double[] bufa, ref int[] bufb, int i1, int i2)
static void tagsortfastrrec (ref double[] a, ref double[] b, ref double[] bufa, ref double[] bufb, int i1, int i2)
static void tagsortfastrec (ref double[] a, ref double[] bufa, int i1, int i2)
static void tagsortfastirec (ref double[] a, ref int[] b, ref double[] bufa, ref int[] bufb, int i1, int i2)
static void tagsortfastrrec (ref double[] a, ref double[] b, ref double[] bufa, ref double[] bufb, int i1, int i2)
static void tagsortfastrec (ref double[] a, ref double[] bufa, int i1, int i2)
Member Function Documentation
static void alglib.tsort.tagsort (ref double[] a, int n, ref int[] p1, ref int[] p2) inline static
References alglib.tsort.tagsortbuf().
Referenced by alglib.ratint.barycentricnormalize(), alglib.bdss.dstie(), alglib.gkq.gkqlegendretbl(), alglib.testbdssunit.testbdss(), and alglib.testtsortunit.testtsort().
static void alglib.tsort.tagsortbuf (ref double[] a, int n, ref int[] p1, ref int[] p2, apserv.apbuffers buf) inline static
References alglib.apserv.ivectorsetlengthatleast(), alglib.apserv.rvectorsetlengthatleast(), and alglib.tsort.tagsortfasti().
Referenced by alglib.optserv.findfeasiblepoint(), and alglib.tsort.tagsort().
static void alglib.tsort.tagsortfasti (ref double[] a, ref int[] b, ref double[] bufa, ref int[] bufb, int n) inline static
References alglib.tsort.tagsortfastirec().
Referenced by alglib.dforest.dfsplitc(), alglib.bdss.dstiefasti(), alglib.spline1d.heapsortdpoints(), alglib.spline1d.heapsortppoints(), alglib.basicstatops.rankx(), alglib.tsort.tagsortbuf(), and alglib.testtsortunit.testtsort().
static void alglib.tsort.tagsortfastr (ref double[] a, ref double[] b, ref double[] bufa, ref double[] bufb, int n) inline static
References alglib.tsort.tagsortfastrrec().
Referenced by alglib.ratint.barycentricbuildfloaterhormann(), alglib.dforest.dfsplitr(), alglib.spline1d.heapsortpoints(), alglib.polint.polynomialbuild(), alglib.testbdssunit.testbdss(), and alglib.testtsortunit.testtsort().
static void alglib.tsort.tagsortfast (ref double[] a, ref double[] bufa, int n) inline static
References alglib.tsort.tagsortfastrec().
Referenced by alglib.basestat.samplepercentile(), and alglib.testtsortunit.testtsort().
static void alglib.tsort.tagsortmiddleir (ref int[] a, ref double[] b, int offset, int n) inline static
Referenced by alglib.testtsortunit.testtsort().
static void alglib.tsort.tagheappushi (ref double[] a, ref int[] b, ref int n, double va, int vb) inline static
Referenced by alglib.nearestneighbor.kdtreequerynnrec().
static void alglib.tsort.tagheapreplacetopi (ref double[] a, ref int[] b, int n, double va, int vb) inline static
Referenced by alglib.nearestneighbor.kdtreequerynnrec(), and alglib.tsort.tagheappopi().
static void alglib.tsort.tagheappopi (ref double[] a, ref int[] b, ref int n) inline static
References alglib.tsort.tagheapreplacetopi().
Referenced by alglib.nearestneighbor.kdtreequeryaknn(), and alglib.nearestneighbor.kdtreequeryrnn().
static int alglib.tsort.lowerbound (double[] a, int n, double t) inline static
static int alglib.tsort.upperbound (double[] a, int n, double t) inline static
static void alglib.tsort.tagsortfastirec (ref double[] a, ref int[] b, ref double[] bufa, ref int[] bufb, int i1, int i2) inline static private
Referenced by alglib.tsort.tagsortfasti(), and alglib.tsort.tagsortfastirec().
static void alglib.tsort.tagsortfastrrec (ref double[] a, ref double[] b, ref double[] bufa, ref double[] bufb, int i1, int i2) inline static private
Referenced by alglib.tsort.tagsortfastr(), and alglib.tsort.tagsortfastrrec().
static void alglib.tsort.tagsortfastrec (ref double[] a, ref double[] bufa, int i1, int i2) inline static private
Referenced by alglib.tsort.tagsortfast(), and alglib.tsort.tagsortfastrec().
static void alglib.tsort.tagsort (ref double[] a, int n, ref int[] p1, ref int[] p2) inline static
References alglib.tsort.tagsortbuf().
static void alglib.tsort.tagsortbuf (ref double[] a, int n, ref int[] p1, ref int[] p2, apserv.apbuffers buf) inline static
References alglib.apserv.ivectorsetlengthatleast(), alglib.apserv.rvectorsetlengthatleast(), and alglib.tsort.tagsortfasti().
static void alglib.tsort.tagsortfasti (ref double[] a, ref int[] b, ref double[] bufa, ref int[] bufb, int n) inline static
References alglib.tsort.tagsortfastirec().
static void alglib.tsort.tagsortfastr (ref double[] a, ref double[] b, ref double[] bufa, ref double[] bufb, int n) inline static
References alglib.tsort.tagsortfastrrec().
static void alglib.tsort.tagsortfast (ref double[] a, ref double[] bufa, int n) inline static
References alglib.tsort.tagsortfastrec().
static void alglib.tsort.tagsortmiddleir (ref int[] a, ref double[] b, int offset, int n) inline static
static void alglib.tsort.tagheappushi (ref double[] a, ref int[] b, ref int n, double va, int vb) inline static
static void alglib.tsort.tagheapreplacetopi (ref double[] a, ref int[] b, int n, double va, int vb) inline static
static void alglib.tsort.tagheappopi (ref double[] a, ref int[] b, ref int n) inline static
References alglib.tsort.tagheapreplacetopi().
static int alglib.tsort.lowerbound (double[] a, int n, double t) inline static
static int alglib.tsort.upperbound (double[] a, int n, double t) inline static
static void alglib.tsort.tagsortfastirec (ref double[] a, ref int[] b, ref double[] bufa, ref int[] bufb, int i1, int i2) inline static private
References alglib.tsort.tagsortfastirec().
static void alglib.tsort.tagsortfastrrec (ref double[] a, ref double[] b, ref double[] bufa, ref double[] bufb, int i1, int i2) inline static private
References alglib.tsort.tagsortfastrrec().
static void alglib.tsort.tagsortfastrec (ref double[] a, ref double[] bufa, int i1, int i2) inline static private
References alglib.tsort.tagsortfastrec().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/alglibinternal.cs