IGLib: NUnit.Framework.Assertions.AssertThatTests Class Reference
NUnit.Framework.Assertions.AssertThatTests Class Reference
Public Member Functions
void AssertionPasses_Boolean ()
void AssertionPasses_BooleanWithMessage ()
void AssertionPasses_BooleanWithMessageAndArgs ()
void AssertionPasses_ActualAndConstraint ()
void AssertionPasses_ActualAndConstraintWithMessage ()
void AssertionPasses_ActualAndConstraintWithMessageAndArgs ()
void AssertionPasses_ActualLambdaAndConstraint ()
void AssertionPasses_ActualLambdaAndConstraintWithMessage ()
void AssertionPasses_ActualLambdaAndConstraintWithMessageAndArgs ()
void AssertionPasses_DelegateAndConstraint ()
void AssertionPasses_DelegateAndConstraintWithMessage ()
void AssertionPasses_DelegateAndConstraintWithMessageAndArgs ()
void FailureThrowsAssertionException_Boolean ()
void FailureThrowsAssertionException_BooleanWithMessage ()
void FailureThrowsAssertionException_BooleanWithMessageAndArgs ()
void FailureThrowsAssertionException_ActualAndConstraint ()
void FailureThrowsAssertionException_ActualAndConstraintWithMessage ()
void FailureThrowsAssertionException_ActualAndConstraintWithMessageAndArgs ()
void FailureThrowsAssertionException_ActualLambdaAndConstraint ()
void FailureThrowsAssertionException_ActualLambdaAndConstraintWithMessage ()
void FailureThrowsAssertionException_ActualLambdaAndConstraintWithMessageAndArgs ()
void FailureThrowsAssertionException_DelegateAndConstraint ()
void FailureThrowsAssertionException_DelegateAndConstraintWithMessage ()
void FailureThrowsAssertionException_DelegateAndConstraintWithMessageAndArgs ()
void AssertionsAreCountedCorrectly ()
void AssertThatWithLambda ()
void AssertThatWithFalseLambda ()
Private Member Functions
int ReturnsFour ()
int ReturnsFive ()
Member Function Documentation
void NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_Boolean () inline
References NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_BooleanWithMessage () inline
References NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_BooleanWithMessageAndArgs () inline
References NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualAndConstraint () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualAndConstraintWithMessage () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualAndConstraintWithMessageAndArgs () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualLambdaAndConstraint () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualLambdaAndConstraintWithMessage () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualLambdaAndConstraintWithMessageAndArgs () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_DelegateAndConstraint () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_DelegateAndConstraintWithMessage () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_DelegateAndConstraintWithMessageAndArgs () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
int NUnit.Framework.Assertions.AssertThatTests.ReturnsFour () inline private
void NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_Boolean () inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_BooleanWithMessage () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_BooleanWithMessageAndArgs () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualAndConstraint () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualAndConstraintWithMessage () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualAndConstraintWithMessageAndArgs () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualLambdaAndConstraint () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualLambdaAndConstraintWithMessage () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualLambdaAndConstraintWithMessageAndArgs () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_DelegateAndConstraint () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_DelegateAndConstraintWithMessage () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_DelegateAndConstraintWithMessageAndArgs () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssertThatTests.AssertionsAreCountedCorrectly () inline
References NUnit.Framework.Internal.TestResult.AssertCount, NUnit.Framework.Internal.TestResult.Children, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestResult.Name, NUnit.TestUtilities.TestBuilder.RunTestFixture(), and NUnit.Framework.Assert.That().
int NUnit.Framework.Assertions.AssertThatTests.ReturnsFive () inline private
void NUnit.Framework.Assertions.AssertThatTests.AssertThatWithLambda () inline
References NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.AssertThatTests.AssertThatWithFalseLambda () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/AssertThatTests.cs