IGLib: Mono.Options.OptionValueCollection Class Reference
Mono.Options.OptionValueCollection Class Reference
Public Member Functions
void Add (string item)
void Clear ()
bool Contains (string item)
void CopyTo (string[] array, int arrayIndex)
bool Remove (string item)
IEnumerator< string > GetEnumerator ()
int IndexOf (string item)
void Insert (int index, string item)
void RemoveAt (int index)
List< string > ToList ()
string[] ToArray ()
override string ToString ()
Properties
bool ICollection. IsSynchronized [get]
object ICollection. SyncRoot [get]
int Count [get]
bool IsReadOnly [get]
bool IList. IsFixedSize [get]
object IList. this[int index] [get, set]
string this[int index] [get, set]
Private Member Functions
void ICollection. CopyTo (Array array, int index)
IEnumerator IEnumerable. GetEnumerator ()
int IList. Add (object value)
bool IList. Contains (object value)
int IList. IndexOf (object value)
void IList. Insert (int index, object value)
void IList. Remove (object value)
void IList. RemoveAt (int index)
void AssertValid (int index)
Private Attributes
List< string > values = new List<string> ()
OptionContext c
Member Function Documentation
void ICollection. Mono.Options.OptionValueCollection.CopyTo (Array array, int index) inline private
void Mono.Options.OptionValueCollection.Add (string item) inline
Referenced by Mono.Options.OptionSet.Invoke(), Mono.Options.OptionSet.Parse(), Mono.Options.OptionSet.ParseBool(), Mono.Options.OptionSet.ParseValue(), and Mono.Options.OptionSet.Unprocessed().
void Mono.Options.OptionValueCollection.Clear () inline
Referenced by Mono.Options.Option.Invoke().
bool Mono.Options.OptionValueCollection.Contains (string item) inline
void Mono.Options.OptionValueCollection.CopyTo (string[] array, int arrayIndex) inline
bool Mono.Options.OptionValueCollection.Remove (string item) inline
IEnumerator IEnumerable. Mono.Options.OptionValueCollection.GetEnumerator () inline private
IEnumerator<string> Mono.Options.OptionValueCollection.GetEnumerator () inline
int IList. Mono.Options.OptionValueCollection.Add (object value) inline private
bool IList. Mono.Options.OptionValueCollection.Contains (object value) inline private
int IList. Mono.Options.OptionValueCollection.IndexOf (object value) inline private
void IList. Mono.Options.OptionValueCollection.Insert (int index, object value) inline private
void IList. Mono.Options.OptionValueCollection.Remove (object value) inline private
void IList. Mono.Options.OptionValueCollection.RemoveAt (int index) inline private
int Mono.Options.OptionValueCollection.IndexOf (string item) inline
void Mono.Options.OptionValueCollection.Insert (int index, string item) inline
void Mono.Options.OptionValueCollection.RemoveAt (int index) inline
void Mono.Options.OptionValueCollection.AssertValid (int index) inline private
References Mono.Options.Option.MaxValueCount, Mono.Options.OptionSet.MessageLocalizer, Mono.Options.OptionContext.Option, Mono.Options.OptionContext.OptionName, Mono.Options.OptionContext.OptionSet, and Mono.Options.Option.OptionValueType.
List<string> Mono.Options.OptionValueCollection.ToList () inline
string [] Mono.Options.OptionValueCollection.ToArray () inline
override string Mono.Options.OptionValueCollection.ToString () inline
Member Data Documentation
List<string> Mono.Options.OptionValueCollection.values = new List<string> () private
OptionContext Mono.Options.OptionValueCollection.c private
Property Documentation
bool ICollection. Mono.Options.OptionValueCollection.IsSynchronized get private
object ICollection. Mono.Options.OptionValueCollection.SyncRoot get private
int Mono.Options.OptionValueCollection.Count get
Referenced by Mono.Options.OptionSet.ParseValue().
bool Mono.Options.OptionValueCollection.IsReadOnly get
bool IList. Mono.Options.OptionValueCollection.IsFixedSize get private
object IList. Mono.Options.OptionValueCollection.this[int index] get set private
string Mono.Options.OptionValueCollection.this[int index] get set
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/Options.cs