IGLib: alglib.lsfit.barycentricfitreport Class Reference
alglib.lsfit.barycentricfitreport Class Reference
Public Member Functions
barycentricfitreport ()
override void init ()
override alglib.apobject make_copy ()
Public Attributes
double taskrcond
int dbest
double rmserror
double avgerror
double avgrelerror
double maxerror
Constructor & Destructor Documentation
alglib.lsfit.barycentricfitreport.barycentricfitreport () inline
References alglib.lsfit.barycentricfitreport.init().
Referenced by alglib.lsfit.barycentricfitreport.make_copy().
Member Function Documentation
override void alglib.lsfit.barycentricfitreport.init () inline virtual
Implements alglib.apobject.
Referenced by alglib.lsfit.barycentricfitreport.barycentricfitreport().
override alglib.apobject alglib.lsfit.barycentricfitreport.make_copy () inline virtual
Implements alglib.apobject.
References alglib.lsfit.barycentricfitreport.avgerror, alglib.lsfit.barycentricfitreport.avgrelerror, alglib.lsfit.barycentricfitreport.barycentricfitreport(), alglib.lsfit.barycentricfitreport.dbest, alglib.lsfit.barycentricfitreport.maxerror, alglib.lsfit.barycentricfitreport.rmserror, and alglib.lsfit.barycentricfitreport.taskrcond.
Member Data Documentation
double alglib.lsfit.barycentricfitreport.taskrcond
Referenced by alglib.lsfit.barycentricfitreport.make_copy().
int alglib.lsfit.barycentricfitreport.dbest
Referenced by alglib.lsfit.barycentricfitreport.make_copy().
double alglib.lsfit.barycentricfitreport.rmserror
Referenced by alglib.lsfit.barycentricfitreport.make_copy().
double alglib.lsfit.barycentricfitreport.avgerror
Referenced by alglib.lsfit.barycentricfitreport.make_copy().
double alglib.lsfit.barycentricfitreport.avgrelerror
Referenced by alglib.lsfit.barycentricfitreport.make_copy().
double alglib.lsfit.barycentricfitreport.maxerror
Referenced by alglib.lsfit.barycentricfitreport.make_copy().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/interpolation.cs