IGLib: IPLab.ColorFilteringForm Class Reference
IPLab.ColorFilteringForm Class Reference
Summary description for ColorFilteringForm.
Public Member Functions
ColorFilteringForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
Bitmap Image [set]
IFilter Filter [get]
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void UpdateFilter ()
void minRBox_TextChanged (object sender, System.EventArgs e)
void maxRBox_TextChanged (object sender, System.EventArgs e)
void minGBox_TextChanged (object sender, System.EventArgs e)
void maxGBox_TextChanged (object sender, System.EventArgs e)
void minBBox_TextChanged (object sender, System.EventArgs e)
void maxBBox_TextChanged (object sender, System.EventArgs e)
void redSlider_ValuesChanged (object sender, System.EventArgs e)
void greenSlider_ValuesChanged (object sender, System.EventArgs e)
void blueSlider_ValuesChanged (object sender, System.EventArgs e)
void fillRBox_TextChanged (object sender, System.EventArgs e)
void fillGBox_TextChanged (object sender, System.EventArgs e)
void fillBBox_TextChanged (object sender, System.EventArgs e)
void UpdateFillColor ()
void fillTypeCombo_SelectedIndexChanged (object sender, System.EventArgs e)
Private Attributes
ColorFiltering filter = new ColorFiltering()
IntRange red = new IntRange(0, 255)
IntRange green = new IntRange(0, 255)
IntRange blue = new IntRange(0, 255)
byte fillR = 0
byte fillG = 0
byte fillB = 0
System.Windows.Forms.GroupBox groupBox3
AForge.Controls.ColorSlider blueSlider
System.Windows.Forms.TextBox fillBBox
System.Windows.Forms.TextBox maxBBox
System.Windows.Forms.Label label8
System.Windows.Forms.TextBox minBBox
System.Windows.Forms.Label label9
System.Windows.Forms.GroupBox groupBox2
AForge.Controls.ColorSlider greenSlider
System.Windows.Forms.TextBox fillGBox
System.Windows.Forms.TextBox maxGBox
System.Windows.Forms.Label label5
System.Windows.Forms.TextBox minGBox
System.Windows.Forms.Label label6
System.Windows.Forms.GroupBox groupBox1
AForge.Controls.ColorSlider redSlider
System.Windows.Forms.TextBox fillRBox
System.Windows.Forms.TextBox maxRBox
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox minRBox
System.Windows.Forms.Label label1
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.Label label10
System.Windows.Forms.Label label3
System.Windows.Forms.Label label4
System.Windows.Forms.GroupBox groupBox5
IPLab.FilterPreview filterPreview
System.Windows.Forms.Button cancelButton
System.Windows.Forms.Button okButton
System.Windows.Forms.Label label7
System.Windows.Forms.ComboBox fillTypeCombo
System.ComponentModel.Container components = null
Required designer variable.
Detailed Description
Summary description for ColorFilteringForm.
Constructor & Destructor Documentation
IPLab.ColorFilteringForm.ColorFilteringForm () inline
References IPLab.ColorFilteringForm.fillB, IPLab.ColorFilteringForm.fillBBox, IPLab.ColorFilteringForm.fillG, IPLab.ColorFilteringForm.fillGBox, IPLab.ColorFilteringForm.fillRBox, IPLab.ColorFilteringForm.fillTypeCombo, IPLab.ColorFilteringForm.filter, IPLab.FilterPreview.Filter, IPLab.ColorFilteringForm.filterPreview, IPLab.ColorFilteringForm.InitializeComponent(), IPLab.ColorFilteringForm.maxBBox, IPLab.ColorFilteringForm.maxGBox, IPLab.ColorFilteringForm.maxRBox, IPLab.ColorFilteringForm.minBBox, IPLab.ColorFilteringForm.minGBox, and IPLab.ColorFilteringForm.minRBox.
Member Function Documentation
override void IPLab.ColorFilteringForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References IPLab.ColorFilteringForm.components.
void IPLab.ColorFilteringForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IPLab.ColorFilteringForm.ColorFilteringForm().
void IPLab.ColorFilteringForm.UpdateFilter () inline private
References IPLab.ColorFilteringForm.blue, IPLab.ColorFilteringForm.filterPreview, IPLab.ColorFilteringForm.green, IPLab.ColorFilteringForm.red, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.ColorFilteringForm.maxBBox_TextChanged(), IPLab.ColorFilteringForm.maxGBox_TextChanged(), IPLab.ColorFilteringForm.maxRBox_TextChanged(), IPLab.ColorFilteringForm.minBBox_TextChanged(), IPLab.ColorFilteringForm.minGBox_TextChanged(), and IPLab.ColorFilteringForm.minRBox_TextChanged().
void IPLab.ColorFilteringForm.minRBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.ColorFilteringForm.minRBox, IPLab.ColorFilteringForm.redSlider, and IPLab.ColorFilteringForm.UpdateFilter().
void IPLab.ColorFilteringForm.maxRBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.ColorFilteringForm.maxRBox, IPLab.ColorFilteringForm.redSlider, and IPLab.ColorFilteringForm.UpdateFilter().
void IPLab.ColorFilteringForm.minGBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.ColorFilteringForm.greenSlider, IPLab.ColorFilteringForm.minGBox, and IPLab.ColorFilteringForm.UpdateFilter().
void IPLab.ColorFilteringForm.maxGBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.ColorFilteringForm.greenSlider, IPLab.ColorFilteringForm.maxGBox, and IPLab.ColorFilteringForm.UpdateFilter().
void IPLab.ColorFilteringForm.minBBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.ColorFilteringForm.blueSlider, IPLab.ColorFilteringForm.minBBox, and IPLab.ColorFilteringForm.UpdateFilter().
void IPLab.ColorFilteringForm.maxBBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.ColorFilteringForm.blueSlider, IPLab.ColorFilteringForm.maxBBox, and IPLab.ColorFilteringForm.UpdateFilter().
void IPLab.ColorFilteringForm.redSlider_ValuesChanged (object sender, System.EventArgs e) inline private
References IPLab.ColorFilteringForm.maxRBox, IPLab.ColorFilteringForm.minRBox, and IPLab.ColorFilteringForm.redSlider.
void IPLab.ColorFilteringForm.greenSlider_ValuesChanged (object sender, System.EventArgs e) inline private
References IPLab.ColorFilteringForm.greenSlider, IPLab.ColorFilteringForm.maxGBox, and IPLab.ColorFilteringForm.minGBox.
void IPLab.ColorFilteringForm.blueSlider_ValuesChanged (object sender, System.EventArgs e) inline private
References IPLab.ColorFilteringForm.blueSlider, IPLab.ColorFilteringForm.maxBBox, and IPLab.ColorFilteringForm.minBBox.
void IPLab.ColorFilteringForm.fillRBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.ColorFilteringForm.fillRBox, and IPLab.ColorFilteringForm.UpdateFillColor().
void IPLab.ColorFilteringForm.fillGBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.ColorFilteringForm.fillG, IPLab.ColorFilteringForm.fillGBox, and IPLab.ColorFilteringForm.UpdateFillColor().
void IPLab.ColorFilteringForm.fillBBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.ColorFilteringForm.fillB, IPLab.ColorFilteringForm.fillBBox, and IPLab.ColorFilteringForm.UpdateFillColor().
void IPLab.ColorFilteringForm.UpdateFillColor () inline private
References IPLab.ColorFilteringForm.blueSlider, IPLab.ColorFilteringForm.fillB, IPLab.ColorFilteringForm.fillG, IPLab.ColorFilteringForm.filterPreview, IPLab.ColorFilteringForm.greenSlider, IPLab.ColorFilteringForm.redSlider, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.ColorFilteringForm.fillBBox_TextChanged(), IPLab.ColorFilteringForm.fillGBox_TextChanged(), and IPLab.ColorFilteringForm.fillRBox_TextChanged().
void IPLab.ColorFilteringForm.fillTypeCombo_SelectedIndexChanged (object sender, System.EventArgs e) inline private
References IPLab.ColorFilteringForm.blueSlider, IPLab.ColorFilteringForm.fillTypeCombo, IPLab.ColorFilteringForm.filterPreview, IPLab.ColorFilteringForm.greenSlider, IPLab.ColorFilteringForm.redSlider, and IPLab.FilterPreview.RefreshFilter().
Member Data Documentation
ColorFiltering IPLab.ColorFilteringForm.filter = new ColorFiltering() private
Referenced by IPLab.ColorFilteringForm.ColorFilteringForm().
IntRange IPLab.ColorFilteringForm.red = new IntRange(0, 255) private
Referenced by IPLab.ColorFilteringForm.UpdateFilter().
IntRange IPLab.ColorFilteringForm.green = new IntRange(0, 255) private
Referenced by IPLab.ColorFilteringForm.UpdateFilter().
IntRange IPLab.ColorFilteringForm.blue = new IntRange(0, 255) private
Referenced by IPLab.ColorFilteringForm.UpdateFilter().
byte IPLab.ColorFilteringForm.fillR = 0 private
byte IPLab.ColorFilteringForm.fillG = 0 private
Referenced by IPLab.ColorFilteringForm.ColorFilteringForm(), IPLab.ColorFilteringForm.fillGBox_TextChanged(), and IPLab.ColorFilteringForm.UpdateFillColor().
byte IPLab.ColorFilteringForm.fillB = 0 private
Referenced by IPLab.ColorFilteringForm.ColorFilteringForm(), IPLab.ColorFilteringForm.fillBBox_TextChanged(), and IPLab.ColorFilteringForm.UpdateFillColor().
System.Windows.Forms.GroupBox IPLab.ColorFilteringForm.groupBox3 private
AForge.Controls.ColorSlider IPLab.ColorFilteringForm.blueSlider private
Referenced by IPLab.ColorFilteringForm.blueSlider_ValuesChanged(), IPLab.ColorFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.ColorFilteringForm.maxBBox_TextChanged(), IPLab.ColorFilteringForm.minBBox_TextChanged(), and IPLab.ColorFilteringForm.UpdateFillColor().
System.Windows.Forms.TextBox IPLab.ColorFilteringForm.fillBBox private
Referenced by IPLab.ColorFilteringForm.ColorFilteringForm(), and IPLab.ColorFilteringForm.fillBBox_TextChanged().
System.Windows.Forms.TextBox IPLab.ColorFilteringForm.maxBBox private
Referenced by IPLab.ColorFilteringForm.blueSlider_ValuesChanged(), IPLab.ColorFilteringForm.ColorFilteringForm(), and IPLab.ColorFilteringForm.maxBBox_TextChanged().
System.Windows.Forms.Label IPLab.ColorFilteringForm.label8 private
System.Windows.Forms.TextBox IPLab.ColorFilteringForm.minBBox private
Referenced by IPLab.ColorFilteringForm.blueSlider_ValuesChanged(), IPLab.ColorFilteringForm.ColorFilteringForm(), and IPLab.ColorFilteringForm.minBBox_TextChanged().
System.Windows.Forms.Label IPLab.ColorFilteringForm.label9 private
System.Windows.Forms.GroupBox IPLab.ColorFilteringForm.groupBox2 private
AForge.Controls.ColorSlider IPLab.ColorFilteringForm.greenSlider private
Referenced by IPLab.ColorFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.ColorFilteringForm.greenSlider_ValuesChanged(), IPLab.ColorFilteringForm.maxGBox_TextChanged(), IPLab.ColorFilteringForm.minGBox_TextChanged(), and IPLab.ColorFilteringForm.UpdateFillColor().
System.Windows.Forms.TextBox IPLab.ColorFilteringForm.fillGBox private
Referenced by IPLab.ColorFilteringForm.ColorFilteringForm(), and IPLab.ColorFilteringForm.fillGBox_TextChanged().
System.Windows.Forms.TextBox IPLab.ColorFilteringForm.maxGBox private
Referenced by IPLab.ColorFilteringForm.ColorFilteringForm(), IPLab.ColorFilteringForm.greenSlider_ValuesChanged(), and IPLab.ColorFilteringForm.maxGBox_TextChanged().
System.Windows.Forms.Label IPLab.ColorFilteringForm.label5 private
System.Windows.Forms.TextBox IPLab.ColorFilteringForm.minGBox private
Referenced by IPLab.ColorFilteringForm.ColorFilteringForm(), IPLab.ColorFilteringForm.greenSlider_ValuesChanged(), and IPLab.ColorFilteringForm.minGBox_TextChanged().
System.Windows.Forms.Label IPLab.ColorFilteringForm.label6 private
System.Windows.Forms.GroupBox IPLab.ColorFilteringForm.groupBox1 private
AForge.Controls.ColorSlider IPLab.ColorFilteringForm.redSlider private
Referenced by IPLab.ColorFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.ColorFilteringForm.maxRBox_TextChanged(), IPLab.ColorFilteringForm.minRBox_TextChanged(), IPLab.ColorFilteringForm.redSlider_ValuesChanged(), and IPLab.ColorFilteringForm.UpdateFillColor().
System.Windows.Forms.TextBox IPLab.ColorFilteringForm.fillRBox private
Referenced by IPLab.ColorFilteringForm.ColorFilteringForm(), and IPLab.ColorFilteringForm.fillRBox_TextChanged().
System.Windows.Forms.TextBox IPLab.ColorFilteringForm.maxRBox private
Referenced by IPLab.ColorFilteringForm.ColorFilteringForm(), IPLab.ColorFilteringForm.maxRBox_TextChanged(), and IPLab.ColorFilteringForm.redSlider_ValuesChanged().
System.Windows.Forms.Label IPLab.ColorFilteringForm.label2 private
System.Windows.Forms.TextBox IPLab.ColorFilteringForm.minRBox private
Referenced by IPLab.ColorFilteringForm.ColorFilteringForm(), IPLab.ColorFilteringForm.minRBox_TextChanged(), and IPLab.ColorFilteringForm.redSlider_ValuesChanged().
System.Windows.Forms.Label IPLab.ColorFilteringForm.label1 private
System.Windows.Forms.GroupBox IPLab.ColorFilteringForm.groupBox4 private
System.Windows.Forms.Label IPLab.ColorFilteringForm.label10 private
System.Windows.Forms.Label IPLab.ColorFilteringForm.label3 private
System.Windows.Forms.Label IPLab.ColorFilteringForm.label4 private
System.Windows.Forms.GroupBox IPLab.ColorFilteringForm.groupBox5 private
IPLab.FilterPreview IPLab.ColorFilteringForm.filterPreview private
Referenced by IPLab.ColorFilteringForm.ColorFilteringForm(), IPLab.ColorFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.ColorFilteringForm.UpdateFillColor(), and IPLab.ColorFilteringForm.UpdateFilter().
System.Windows.Forms.Button IPLab.ColorFilteringForm.cancelButton private
System.Windows.Forms.Button IPLab.ColorFilteringForm.okButton private
System.Windows.Forms.Label IPLab.ColorFilteringForm.label7 private
System.Windows.Forms.ComboBox IPLab.ColorFilteringForm.fillTypeCombo private
Referenced by IPLab.ColorFilteringForm.ColorFilteringForm(), and IPLab.ColorFilteringForm.fillTypeCombo_SelectedIndexChanged().
System.ComponentModel.Container IPLab.ColorFilteringForm.components = null private
Required designer variable.
Referenced by IPLab.ColorFilteringForm.Dispose().
Property Documentation
Bitmap IPLab.ColorFilteringForm.Image set
Referenced by IPLab.ImageDoc.colorFilteringColorFiltersItem_Click().
IFilter IPLab.ColorFilteringForm.Filter get
Referenced by IPLab.ImageDoc.colorFilteringColorFiltersItem_Click().
The documentation for this class was generated from the following file:
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/ColorFilteringForm.cs