IGLib: IG.Old.Matrix_OldNumerics Class Reference
IG.Old.Matrix_OldNumerics Class Reference
Matrix whose vec are real numbers.
Public Member Functions
Matrix_OldNumerics (int dim1, int dim2)
Matrix_OldNumerics (int dim1, int dim2, double comp)
Matrix_OldNumerics (double[,] array)
Matrix_OldNumerics (Matrix_OldNumerics cv)
override double Add (double a, double b)
override double Subtract (double a, double b)
override double Multiply (double a, double b)
override double Divide (double a, double b)
override double Negative (double a)
override double Inverse (double a)
override double Conjugate (double a)
Static Public Member Functions
static Matrix_OldNumerics operator+ (Matrix_OldNumerics a, Matrix_OldNumerics b)
static Matrix_OldNumerics operator- (Matrix_OldNumerics a, Matrix_OldNumerics b)
static Matrix_OldNumerics operator* (Matrix_OldNumerics a, double b)
static Matrix_OldNumerics operator* (double b, Matrix_OldNumerics a)
static Matrix_OldNumerics operator* (Matrix_OldNumerics a, Matrix_OldNumerics b)
Multiplication of two matrices.
static void Example ()
Protected Member Functions
Matrix_OldNumerics ()
Properties
override double Zero [get]
Detailed Description
Matrix whose vec are real numbers.
Constructor & Destructor Documentation
IG.Old.Matrix_OldNumerics.Matrix_OldNumerics () inline protected
IG.Old.Matrix_OldNumerics.Matrix_OldNumerics (int dim1, int dim2) inline
IG.Old.Matrix_OldNumerics.Matrix_OldNumerics (int dim1, int dim2, double comp) inline
IG.Old.Matrix_OldNumerics.Matrix_OldNumerics (double array[,]) inline
IG.Old.Matrix_OldNumerics.Matrix_OldNumerics (Matrix_OldNumerics cv) inline
Member Function Documentation
override double IG.Old.Matrix_OldNumerics.Add (double a, double b) inline
Referenced by IG.Old.Matrix_OldNumerics.operator+().
override double IG.Old.Matrix_OldNumerics.Subtract (double a, double b) inline
Referenced by IG.Old.Matrix_OldNumerics.operator-().
override double IG.Old.Matrix_OldNumerics.Multiply (double a, double b) inline
Referenced by IG.Old.Matrix_OldNumerics.operator*().
override double IG.Old.Matrix_OldNumerics.Divide (double a, double b) inline
override double IG.Old.Matrix_OldNumerics.Negative (double a) inline
override double IG.Old.Matrix_OldNumerics.Inverse (double a) inline
override double IG.Old.Matrix_OldNumerics.Conjugate (double a) inline
static Matrix_OldNumerics IG.Old.Matrix_OldNumerics.operator+ (Matrix_OldNumerics a, Matrix_OldNumerics b) inline static
References IG.Old.Matrix_OldNumerics.Add().
static Matrix_OldNumerics IG.Old.Matrix_OldNumerics.operator- (Matrix_OldNumerics a, Matrix_OldNumerics b) inline static
References IG.Old.Matrix_OldNumerics.Subtract().
static Matrix_OldNumerics IG.Old.Matrix_OldNumerics.operator* (Matrix_OldNumerics a, double b) inline static
References IG.Old.Matrix_OldNumerics.Multiply().
static Matrix_OldNumerics IG.Old.Matrix_OldNumerics.operator* (double b, Matrix_OldNumerics a) inline static
References IG.Old.Matrix_OldNumerics.Multiply().
static Matrix_OldNumerics IG.Old.Matrix_OldNumerics.operator* (Matrix_OldNumerics a, Matrix_OldNumerics b) inline static
Multiplication of two matrices.
static void IG.Old.Matrix_OldNumerics.Example () inline static
Property Documentation
override double IG.Old.Matrix_OldNumerics.Zero get
The documentation for this class was generated from the following file:
igtest/IGLibTestDevExt/z_old/OldNumeric.cs