IGLib: TestWS_GUI.Form1 Class Reference
TestWS_GUI.Form1 Class Reference
Public Member Functions
Form1 ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
delegate void SetTextCallback (string text)
delegate void SetProgressCallback (int value)
void Form1_Load (object sender, EventArgs e)
void aboutToolStripMenuItem_Click (object sender, EventArgs e)
void buttonFolder1_Click (object sender, EventArgs e)
void tabControl1_Click (object sender, EventArgs e)
void fillListBoxPackages ()
void linkLabel1_LinkClicked (object sender, LinkLabelLinkClickedEventArgs e)
void buttonGenerate_Click (object sender, EventArgs e)
void generateXmlPackets (XmlDocument packageXml, int numPack, int size)
string generateId ()
void checkBoxCheckAll_CheckedChanged (object sender, EventArgs e)
void changeCheckBox (object sender)
void fillListBoxSendPackages ()
void buttonSend_Click (object sender, EventArgs e)
List< ThreadData > getListThreadDataFromForm ()
void buttonAdd_Click (object sender, EventArgs e)
void buttonUp_Click (object sender, EventArgs e)
void buttonDown_Click (object sender, EventArgs e)
void buttonRemove_Click (object sender, EventArgs e)
void buttonRemoveAll_Click (object sender, EventArgs e)
void backgroundWorker1_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void SetText (string text)
void SetProgress (int value)
void buttonFolder2_Click (object sender, EventArgs e)
void buttonCancel_Click (object sender, EventArgs e)
void buttonAddThread_Click (object sender, EventArgs e)
TabPage createTab (List< Package > packages, int numSend, int timeLag)
void buttonRemoveThread_Click (object sender, EventArgs e)
void buttonSaveScenario_Click (object sender, EventArgs e)
void buttonLoadScenario_Click (object sender, EventArgs e)
List< ThreadData > xmlToThreadData (String xmlPath)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
String dirPath
String generatePath
String sendPath
XmlWriter xw
StreamReader sr
int st
Random random
int threadCount
TestWS_Lib.TestWS_Lib lib
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.MenuStrip menuStrip1
System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem
System.Windows.Forms.TabControl tabControl1
System.Windows.Forms.TabPage tabPage1
System.Windows.Forms.TabPage tabPage2
System.Windows.Forms.Label label1
System.Windows.Forms.ListBox listBoxPackages
System.Windows.Forms.TextBox numPackages
System.Windows.Forms.Label label2
System.Windows.Forms.FolderBrowserDialog folderBrowserDialog1
System.Windows.Forms.Button buttonGenerate
System.Windows.Forms.LinkLabel linkLabel1
System.Windows.Forms.Label label5
System.Windows.Forms.TextBox textBoxTimeLag
System.Windows.Forms.CheckBox checkBoxCheckAll
System.Windows.Forms.Button buttonSend
System.Windows.Forms.Label label4
System.Windows.Forms.ListBox listBoxSendPackages
System.Windows.Forms.Label label6
System.Windows.Forms.TextBox textBoxNumSendPackages
System.Windows.Forms.TabPage tabPage3
System.Windows.Forms.TextBox textBoxResults
System.Windows.Forms.ProgressBar progressBar1
System.Windows.Forms.Label label7
System.Windows.Forms.TextBox textBoxSize
System.Windows.Forms.Label label8
System.Windows.Forms.ListBox listBoxSelected
System.Windows.Forms.Button buttonDown
System.Windows.Forms.Button buttonRemove
System.Windows.Forms.Button buttonUp
System.Windows.Forms.Button buttonAdd
System.ComponentModel.BackgroundWorker backgroundWorker1
System.Windows.Forms.Button buttonFolder1
System.Windows.Forms.Button buttonFolder2
System.Windows.Forms.Button buttonRemoveAll
System.Windows.Forms.Button buttonCancel
System.Windows.Forms.TabControl tabControlThreads
System.Windows.Forms.TabPage tabPageThread1
System.Windows.Forms.Button buttonRemoveThread
System.Windows.Forms.Button buttonAddThread
System.Windows.Forms.Button buttonSaveScenario
System.Windows.Forms.SaveFileDialog saveFileDialog1
System.Windows.Forms.Button buttonLoadScenario
System.Windows.Forms.OpenFileDialog openFileDialog1
Constructor & Destructor Documentation
TestWS_GUI.Form1.Form1 () inline
References TestWS_GUI.Form1.dirPath, TestWS_GUI.Form1.InitializeComponent(), and TestWS_GUI.Form1.lib.
Member Function Documentation
delegate void TestWS_GUI.Form1.SetTextCallback (string text) private
Referenced by TestWS_GUI.Form1.SetText().
delegate void TestWS_GUI.Form1.SetProgressCallback (int value) private
Referenced by TestWS_GUI.Form1.SetProgress().
void TestWS_GUI.Form1.Form1_Load (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.fillListBoxPackages(), TestWS_GUI.Form1.fillListBoxSendPackages(), and TestWS_GUI.Form1.progressBar1.
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.aboutToolStripMenuItem_Click (object sender, EventArgs e) inline private
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.buttonFolder1_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.fillListBoxPackages(), and TestWS_GUI.Form1.folderBrowserDialog1.
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.tabControl1_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.fillListBoxPackages(), and TestWS_GUI.Form1.fillListBoxSendPackages().
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.fillListBoxPackages () inline private
References TestWS_GUI.Form1.listBoxPackages.
Referenced by TestWS_GUI.Form1.buttonFolder1_Click(), TestWS_GUI.Form1.Form1_Load(), and TestWS_GUI.Form1.tabControl1_Click().
void TestWS_GUI.Form1.linkLabel1_LinkClicked (object sender, LinkLabelLinkClickedEventArgs e) inline private
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.buttonGenerate_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.generateXmlPackets(), TestWS_GUI.Form1.listBoxPackages, TestWS_GUI.Form1.numPackages, and TestWS_GUI.Form1.textBoxSize.
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.generateXmlPackets (XmlDocument packageXml, int numPack, int size) inline private
References TestWS_GUI.Form1.generateId(), and TestWS_GUI.Form1.progressBar1.
Referenced by TestWS_GUI.Form1.buttonGenerate_Click().
string TestWS_GUI.Form1.generateId () inline private
Referenced by TestWS_GUI.Form1.generateXmlPackets().
void TestWS_GUI.Form1.checkBoxCheckAll_CheckedChanged (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.changeCheckBox().
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.changeCheckBox (object sender) inline private
References TestWS_GUI.Form1.listBoxSendPackages.
Referenced by TestWS_GUI.Form1.checkBoxCheckAll_CheckedChanged().
void TestWS_GUI.Form1.fillListBoxSendPackages () inline private
References TestWS_GUI.Form1.listBoxSendPackages.
Referenced by TestWS_GUI.Form1.buttonFolder2_Click(), TestWS_GUI.Form1.Form1_Load(), and TestWS_GUI.Form1.tabControl1_Click().
void TestWS_GUI.Form1.buttonSend_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.backgroundWorker1, TestWS_GUI.Form1.getListThreadDataFromForm(), TestWS_GUI.Form1.lib, TestWS_GUI.Form1.progressBar1, TestWS_Lib.TestWS_Lib.startTesting(), and TestWS_GUI.Form1.textBoxResults.
Referenced by TestWS_GUI.Form1.InitializeComponent().
List<ThreadData> TestWS_GUI.Form1.getListThreadDataFromForm () inline private
References TestWS_Lib.Package.Name, TestWS_Lib.Package.PackageContent, TestWS_Lib.Package.Path, and TestWS_GUI.Form1.tabControlThreads.
Referenced by TestWS_GUI.Form1.buttonSaveScenario_Click(), and TestWS_GUI.Form1.buttonSend_Click().
void TestWS_GUI.Form1.buttonAdd_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.listBoxSendPackages, and TestWS_GUI.Form1.tabControlThreads.
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.buttonUp_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.tabControlThreads.
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.buttonDown_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.tabControlThreads.
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.buttonRemove_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.tabControlThreads.
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.buttonRemoveAll_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.tabControlThreads.
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.backgroundWorker1_DoWork (object sender, DoWorkEventArgs e) inline private
References TestWS_GUI.Form1.lib, TestWS_Lib.TestWS_Lib.ProgressValue, TestWS_Lib.TestWS_Lib.Result, TestWS_GUI.Form1.SetProgress(), TestWS_GUI.Form1.SetText(), and TestWS_Lib.TestWS_Lib.threadsRunning().
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References TestWS_GUI.Form1.lib, TestWS_GUI.Form1.progressBar1, TestWS_Lib.TestWS_Lib.Result, and TestWS_GUI.Form1.textBoxResults.
Referenced by TestWS_GUI.Form1.buttonCancel_Click(), and TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.SetText (string text) inline private
References TestWS_GUI.Form1.SetTextCallback(), and TestWS_GUI.Form1.textBoxResults.
Referenced by TestWS_GUI.Form1.backgroundWorker1_DoWork().
void TestWS_GUI.Form1.SetProgress (int value) inline private
References TestWS_GUI.Form1.progressBar1, and TestWS_GUI.Form1.SetProgressCallback().
Referenced by TestWS_GUI.Form1.backgroundWorker1_DoWork().
void TestWS_GUI.Form1.buttonFolder2_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.fillListBoxSendPackages(), and TestWS_GUI.Form1.folderBrowserDialog1.
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.buttonCancel_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.backgroundWorker1_RunWorkerCompleted(), TestWS_Lib.TestWS_Lib.cancel(), and TestWS_GUI.Form1.lib.
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.buttonAddThread_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.createTab(), and TestWS_GUI.Form1.tabControlThreads.
Referenced by TestWS_GUI.Form1.InitializeComponent().
TabPage TestWS_GUI.Form1.createTab (List< Package > packages, int numSend, int timeLag) inline private
References TestWS_GUI.Form1.label1.
Referenced by TestWS_GUI.Form1.buttonAddThread_Click(), and TestWS_GUI.Form1.buttonLoadScenario_Click().
void TestWS_GUI.Form1.buttonRemoveThread_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.tabControlThreads.
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.buttonSaveScenario_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.getListThreadDataFromForm(), TestWS_Lib.Package.Name, TestWS_Lib.ThreadData.NumSendPackages, TestWS_Lib.ThreadData.Packages, TestWS_Lib.Package.Path, TestWS_GUI.Form1.saveFileDialog1, and TestWS_Lib.ThreadData.TimeLag.
Referenced by TestWS_GUI.Form1.InitializeComponent().
void TestWS_GUI.Form1.buttonLoadScenario_Click (object sender, EventArgs e) inline private
References TestWS_GUI.Form1.createTab(), TestWS_Lib.ThreadData.NumSendPackages, TestWS_GUI.Form1.openFileDialog1, TestWS_Lib.ThreadData.Packages, TestWS_GUI.Form1.tabControlThreads, TestWS_Lib.ThreadData.TimeLag, and TestWS_GUI.Form1.xmlToThreadData().
Referenced by TestWS_GUI.Form1.InitializeComponent().
List<ThreadData> TestWS_GUI.Form1.xmlToThreadData (String xmlPath) inline private
References TestWS_GUI.Form1.dirPath.
Referenced by TestWS_GUI.Form1.buttonLoadScenario_Click().
override void TestWS_GUI.Form1.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References TestWS_GUI.Form1.components.
void TestWS_GUI.Form1.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References TestWS_GUI.Form1.aboutToolStripMenuItem, TestWS_GUI.Form1.aboutToolStripMenuItem_Click(), TestWS_GUI.Form1.backgroundWorker1, TestWS_GUI.Form1.backgroundWorker1_DoWork(), TestWS_GUI.Form1.backgroundWorker1_RunWorkerCompleted(), TestWS_GUI.Form1.buttonAdd, TestWS_GUI.Form1.buttonAdd_Click(), TestWS_GUI.Form1.buttonAddThread, TestWS_GUI.Form1.buttonAddThread_Click(), TestWS_GUI.Form1.buttonCancel, TestWS_GUI.Form1.buttonCancel_Click(), TestWS_GUI.Form1.buttonDown, TestWS_GUI.Form1.buttonDown_Click(), TestWS_GUI.Form1.buttonFolder1, TestWS_GUI.Form1.buttonFolder1_Click(), TestWS_GUI.Form1.buttonFolder2, TestWS_GUI.Form1.buttonFolder2_Click(), TestWS_GUI.Form1.buttonGenerate, TestWS_GUI.Form1.buttonGenerate_Click(), TestWS_GUI.Form1.buttonLoadScenario, TestWS_GUI.Form1.buttonLoadScenario_Click(), TestWS_GUI.Form1.buttonRemove, TestWS_GUI.Form1.buttonRemove_Click(), TestWS_GUI.Form1.buttonRemoveAll, TestWS_GUI.Form1.buttonRemoveAll_Click(), TestWS_GUI.Form1.buttonRemoveThread, TestWS_GUI.Form1.buttonRemoveThread_Click(), TestWS_GUI.Form1.buttonSaveScenario, TestWS_GUI.Form1.buttonSaveScenario_Click(), TestWS_GUI.Form1.buttonSend, TestWS_GUI.Form1.buttonSend_Click(), TestWS_GUI.Form1.buttonUp, TestWS_GUI.Form1.buttonUp_Click(), TestWS_GUI.Form1.checkBoxCheckAll, TestWS_GUI.Form1.checkBoxCheckAll_CheckedChanged(), TestWS_GUI.Form1.fileToolStripMenuItem, TestWS_GUI.Form1.folderBrowserDialog1, TestWS_GUI.Form1.Form1_Load(), TestWS_GUI.Form1.label1, TestWS_GUI.Form1.label2, TestWS_GUI.Form1.label4, TestWS_GUI.Form1.label5, TestWS_GUI.Form1.label6, TestWS_GUI.Form1.label7, TestWS_GUI.Form1.label8, TestWS_GUI.Form1.linkLabel1, TestWS_GUI.Form1.linkLabel1_LinkClicked(), TestWS_GUI.Form1.listBoxPackages, TestWS_GUI.Form1.listBoxSelected, TestWS_GUI.Form1.listBoxSendPackages, TestWS_GUI.Form1.menuStrip1, TestWS_GUI.Form1.numPackages, TestWS_GUI.Form1.openFileDialog1, TestWS_GUI.Form1.progressBar1, TestWS_GUI.Form1.saveFileDialog1, TestWS_GUI.Form1.tabControl1, TestWS_GUI.Form1.tabControl1_Click(), TestWS_GUI.Form1.tabControlThreads, TestWS_GUI.Form1.tabPage1, TestWS_GUI.Form1.tabPage2, TestWS_GUI.Form1.tabPage3, TestWS_GUI.Form1.tabPageThread1, TestWS_GUI.Form1.textBoxNumSendPackages, TestWS_GUI.Form1.textBoxResults, TestWS_GUI.Form1.textBoxSize, and TestWS_GUI.Form1.textBoxTimeLag.
Referenced by TestWS_GUI.Form1.Form1().
Member Data Documentation
String TestWS_GUI.Form1.dirPath private
Referenced by TestWS_GUI.Form1.Form1(), and TestWS_GUI.Form1.xmlToThreadData().
String TestWS_GUI.Form1.generatePath private
String TestWS_GUI.Form1.sendPath private
XmlWriter TestWS_GUI.Form1.xw private
StreamReader TestWS_GUI.Form1.sr private
int TestWS_GUI.Form1.st private
Random TestWS_GUI.Form1.random private
int TestWS_GUI.Form1.threadCount private
TestWS_Lib.TestWS_Lib TestWS_GUI.Form1.lib private
Referenced by TestWS_GUI.Form1.backgroundWorker1_DoWork(), TestWS_GUI.Form1.backgroundWorker1_RunWorkerCompleted(), TestWS_GUI.Form1.buttonCancel_Click(), TestWS_GUI.Form1.buttonSend_Click(), and TestWS_GUI.Form1.Form1().
System.ComponentModel.IContainer TestWS_GUI.Form1.components = null private
Required designer variable.
Referenced by TestWS_GUI.Form1.Dispose().
System.Windows.Forms.MenuStrip TestWS_GUI.Form1.menuStrip1 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.ToolStripMenuItem TestWS_GUI.Form1.fileToolStripMenuItem private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.ToolStripMenuItem TestWS_GUI.Form1.aboutToolStripMenuItem private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.TabControl TestWS_GUI.Form1.tabControl1 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.TabPage TestWS_GUI.Form1.tabPage1 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.TabPage TestWS_GUI.Form1.tabPage2 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Label TestWS_GUI.Form1.label1 private
Referenced by TestWS_GUI.Form1.createTab(), and TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.ListBox TestWS_GUI.Form1.listBoxPackages private
Referenced by TestWS_GUI.Form1.buttonGenerate_Click(), TestWS_GUI.Form1.fillListBoxPackages(), and TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.TextBox TestWS_GUI.Form1.numPackages private
Referenced by TestWS_GUI.Form1.buttonGenerate_Click(), and TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Label TestWS_GUI.Form1.label2 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.FolderBrowserDialog TestWS_GUI.Form1.folderBrowserDialog1 private
Referenced by TestWS_GUI.Form1.buttonFolder1_Click(), TestWS_GUI.Form1.buttonFolder2_Click(), and TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonGenerate private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.LinkLabel TestWS_GUI.Form1.linkLabel1 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Label TestWS_GUI.Form1.label5 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.TextBox TestWS_GUI.Form1.textBoxTimeLag private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.CheckBox TestWS_GUI.Form1.checkBoxCheckAll private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonSend private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Label TestWS_GUI.Form1.label4 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.ListBox TestWS_GUI.Form1.listBoxSendPackages private
Referenced by TestWS_GUI.Form1.buttonAdd_Click(), TestWS_GUI.Form1.changeCheckBox(), TestWS_GUI.Form1.fillListBoxSendPackages(), and TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Label TestWS_GUI.Form1.label6 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.TextBox TestWS_GUI.Form1.textBoxNumSendPackages private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.TabPage TestWS_GUI.Form1.tabPage3 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.TextBox TestWS_GUI.Form1.textBoxResults private
Referenced by TestWS_GUI.Form1.backgroundWorker1_RunWorkerCompleted(), TestWS_GUI.Form1.buttonSend_Click(), TestWS_GUI.Form1.InitializeComponent(), and TestWS_GUI.Form1.SetText().
System.Windows.Forms.ProgressBar TestWS_GUI.Form1.progressBar1 private
Referenced by TestWS_GUI.Form1.backgroundWorker1_RunWorkerCompleted(), TestWS_GUI.Form1.buttonSend_Click(), TestWS_GUI.Form1.Form1_Load(), TestWS_GUI.Form1.generateXmlPackets(), TestWS_GUI.Form1.InitializeComponent(), and TestWS_GUI.Form1.SetProgress().
System.Windows.Forms.Label TestWS_GUI.Form1.label7 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.TextBox TestWS_GUI.Form1.textBoxSize private
Referenced by TestWS_GUI.Form1.buttonGenerate_Click(), and TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Label TestWS_GUI.Form1.label8 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.ListBox TestWS_GUI.Form1.listBoxSelected private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonDown private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonRemove private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonUp private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonAdd private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.ComponentModel.BackgroundWorker TestWS_GUI.Form1.backgroundWorker1 private
Referenced by TestWS_GUI.Form1.buttonSend_Click(), and TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonFolder1 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonFolder2 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonRemoveAll private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonCancel private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.TabControl TestWS_GUI.Form1.tabControlThreads private
Referenced by TestWS_GUI.Form1.buttonAdd_Click(), TestWS_GUI.Form1.buttonAddThread_Click(), TestWS_GUI.Form1.buttonDown_Click(), TestWS_GUI.Form1.buttonLoadScenario_Click(), TestWS_GUI.Form1.buttonRemove_Click(), TestWS_GUI.Form1.buttonRemoveAll_Click(), TestWS_GUI.Form1.buttonRemoveThread_Click(), TestWS_GUI.Form1.buttonUp_Click(), TestWS_GUI.Form1.getListThreadDataFromForm(), and TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.TabPage TestWS_GUI.Form1.tabPageThread1 private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonRemoveThread private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonAddThread private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonSaveScenario private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.SaveFileDialog TestWS_GUI.Form1.saveFileDialog1 private
Referenced by TestWS_GUI.Form1.buttonSaveScenario_Click(), and TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.Button TestWS_GUI.Form1.buttonLoadScenario private
Referenced by TestWS_GUI.Form1.InitializeComponent().
System.Windows.Forms.OpenFileDialog TestWS_GUI.Form1.openFileDialog1 private
Referenced by TestWS_GUI.Form1.buttonLoadScenario_Click(), and TestWS_GUI.Form1.InitializeComponent().
The documentation for this class was generated from the following files:
igtest/tmp_prem/prefa/95_Test/TestWS_GUI/Form1.cs
igtest/tmp_prem/prefa/95_Test/TestWS_GUI/Form1.Designer.cs