IGLib: alglib.sparse Class Reference
alglib.sparse Class Reference
Classes
class sparsematrix
Static Public Member Functions
static void sparsecreate (int m, int n, int k, sparsematrix s)
static void sparsecreatecrs (int m, int n, int[] ner, sparsematrix s)
static void sparsecopy (sparsematrix s0, sparsematrix s1)
static void sparseadd (sparsematrix s, int i, int j, double v)
static void sparseset (sparsematrix s, int i, int j, double v)
static double sparseget (sparsematrix s, int i, int j)
static void sparseconverttocrs (sparsematrix s)
static void sparsemv (sparsematrix s, double[] x, ref double[] y)
static void sparsemtv (sparsematrix s, double[] x, ref double[] y)
static void sparsemv2 (sparsematrix s, double[] x, ref double[] y0, ref double[] y1)
static void sparsesmv (sparsematrix s, bool isupper, double[] x, ref double[] y)
static void sparsemm (sparsematrix s, double[,] a, int k, ref double[,] b)
static void sparsemtm (sparsematrix s, double[,] a, int k, ref double[,] b)
static void sparsemm2 (sparsematrix s, double[,] a, int k, ref double[,] b0, ref double[,] b1)
static void sparsesmm (sparsematrix s, bool isupper, double[,] a, int k, ref double[,] b)
static void sparseresizematrix (sparsematrix s)
static double sparsegetaveragelengthofchain (sparsematrix s)
static bool sparseenumerate (sparsematrix s, ref int t0, ref int t1, ref int i, ref int j, ref double v)
static bool sparserewriteexisting (sparsematrix s, int i, int j, double v)
static void sparsecreate (int m, int n, int k, sparsematrix s)
static void sparsecreatecrs (int m, int n, int[] ner, sparsematrix s)
static void sparsecopy (sparsematrix s0, sparsematrix s1)
static void sparseadd (sparsematrix s, int i, int j, double v)
static void sparseset (sparsematrix s, int i, int j, double v)
static double sparseget (sparsematrix s, int i, int j)
static double sparsegetdiagonal (sparsematrix s, int i)
static void sparseconverttocrs (sparsematrix s)
static void sparsemv (sparsematrix s, double[] x, ref double[] y)
static void sparsemtv (sparsematrix s, double[] x, ref double[] y)
static void sparsemv2 (sparsematrix s, double[] x, ref double[] y0, ref double[] y1)
static void sparsesmv (sparsematrix s, bool isupper, double[] x, ref double[] y)
static void sparsemm (sparsematrix s, double[,] a, int k, ref double[,] b)
static void sparsemtm (sparsematrix s, double[,] a, int k, ref double[,] b)
static void sparsemm2 (sparsematrix s, double[,] a, int k, ref double[,] b0, ref double[,] b1)
static void sparsesmm (sparsematrix s, bool isupper, double[,] a, int k, ref double[,] b)
static void sparseresizematrix (sparsematrix s)
static double sparsegetaveragelengthofchain (sparsematrix s)
static bool sparseenumerate (sparsematrix s, ref int t0, ref int t1, ref int i, ref int j, ref double v)
static bool sparserewriteexisting (sparsematrix s, int i, int j, double v)
static void sparsegetrow (sparsematrix s, int i, ref double[] irow)
static void sparseconverttohash (sparsematrix s)
static void sparsecopytohash (sparsematrix s0, sparsematrix s1)
static void sparsecopytocrs (sparsematrix s0, sparsematrix s1)
static int sparsegetmatrixtype (sparsematrix s)
static bool sparseishash (sparsematrix s)
static bool sparseiscrs (sparsematrix s)
static void sparsefree (sparsematrix s)
static int sparsegetnrows (sparsematrix s)
static int sparsegetncols (sparsematrix s)
Public Attributes
const double desiredloadfactor = 0.66
const double maxloadfactor = 0.75
const double growfactor = 2.00
const int additional = 10
const int linalgswitch = 16
Static Private Member Functions
static void sparseinitduidx (sparsematrix s)
static int hash (int i, int j, int tabsize)
static void sparseinitduidx (sparsematrix s)
static int hash (int i, int j, int tabsize)
Member Function Documentation
static void alglib.sparse.sparsecreate (int m, int n, int k, sparsematrix s) inline static
Referenced by alglib.testsparseunit.basiccopyfunctest(), alglib.testsparseunit.basicfuncrandomtest(), alglib.testsparseunit.basicfunctest(), alglib.testminqpunit.bleictests(), alglib.testminqpunit.choleskytests(), alglib.testsparseunit.createrandom(), alglib.testsparseunit.enumeratetest(), alglib.testlinlsqrunit.preconditionertest(), alglib.testlincgunit.precondtest(), alglib.testsparseunit.rewriteexistingtest(), alglib.sparsecreate(), alglib.testlincgunit.sparsetest(), alglib.testlinlsqrunit.svdtest(), alglib.testmlpbaseunit.testerr(), alglib.testmlpeunit.testerr(), alglib.testsparseunit.testgcmatrixtype(), alglib.testsparseunit.testgetrow(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlpbaseunit.testmlpgbsubset(), alglib.testmlptrainunit.testmlpgbsubset(), alglib.testmlptrainunit.testmlprestarts(), alglib.testmlptrainunit.testmlptrainclass(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlptrainensregr(), alglib.testmlptrainunit.testmlptrainregr(), alglib.testmlptrainunit.testmlpxorcls(), alglib.testmlptrainunit.testmlpxorregr(), alglib.testmlptrainunit.testmlpzeroweights(), alglib.testnormestimatorunit.testnormestimator(), and alglib.testmlpbaseunit.testprocessing().
static void alglib.sparse.sparsecreatecrs (int m, int n, int[] ner, sparsematrix s) inline static
Referenced by alglib.testsparseunit.basiccopyfunctest(), alglib.testsparseunit.basicfunctestcrs(), alglib.testsparseunit.createrandom(), alglib.sparsecreatecrs(), and alglib.testsparseunit.testconvertsm().
static void alglib.sparse.sparsecopy (sparsematrix s0, sparsematrix s1) inline static
Referenced by alglib.testsparseunit.basiccopyfunctest(), alglib.testsparseunit.copyfunctest(), alglib.sparsecopy(), and alglib.testsparseunit.testconvertsm().
static void alglib.sparse.sparseadd (sparsematrix s, int i, int j, double v) inline static
Referenced by alglib.testsparseunit.basiccopyfunctest(), alglib.testsparseunit.basicfuncrandomtest(), alglib.testsparseunit.basicfunctest(), alglib.testsparseunit.createrandom(), alglib.sparseadd(), and alglib.testsparseunit.testconvertsm().
static void alglib.sparse.sparseset (sparsematrix s, int i, int j, double v) inline static
Referenced by alglib.testsparseunit.basiccopyfunctest(), alglib.testsparseunit.basicfuncrandomtest(), alglib.testsparseunit.basicfunctest(), alglib.testsparseunit.basicfunctestcrs(), alglib.testminqpunit.bleictests(), alglib.testminqpunit.choleskytests(), alglib.testsparseunit.createrandom(), alglib.testsparseunit.enumeratetest(), alglib.testlinlsqrunit.preconditionertest(), alglib.testlincgunit.precondtest(), alglib.testsparseunit.rewriteexistingtest(), alglib.sparseset(), alglib.testlincgunit.sparsetest(), alglib.testlinlsqrunit.svdtest(), alglib.testsparseunit.testconvertsm(), alglib.testmlpbaseunit.testerr(), alglib.testmlpeunit.testerr(), alglib.testsparseunit.testgetrow(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlpbaseunit.testmlpgbsubset(), alglib.testmlptrainunit.testmlpgbsubset(), alglib.testmlptrainunit.testmlprestarts(), alglib.testmlptrainunit.testmlptrainclass(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlptrainensregr(), alglib.testmlptrainunit.testmlptrainregr(), alglib.testmlptrainunit.testmlpxorcls(), alglib.testmlptrainunit.testmlpxorregr(), alglib.testnormestimatorunit.testnormestimator(), and alglib.testmlpbaseunit.testprocessing().
static double alglib.sparse.sparseget (sparsematrix s, int i, int j) inline static
Referenced by alglib.testsparseunit.basiccopyfunctest(), alglib.testsparseunit.basicfuncrandomtest(), alglib.testsparseunit.basicfunctest(), alglib.testsparseunit.basicfunctestcrs(), alglib.testsparseunit.copyfunctest(), alglib.testsparseunit.rewriteexistingtest(), alglib.sparseget(), alglib.testsparseunit.testconvertsm(), alglib.testsparseunit.testgetrow(), and alglib.testmlpbaseunit.testgradient().
static void alglib.sparse.sparseconverttocrs (sparsematrix s) inline static
Referenced by alglib.testsparseunit.basiccopyfunctest(), alglib.testsparseunit.basicfuncrandomtest(), alglib.testsparseunit.basicfunctest(), alglib.testsparseunit.createrandom(), alglib.testsparseunit.enumeratetest(), alglib.testlinlsqrunit.preconditionertest(), alglib.testlincgunit.precondtest(), alglib.testsparseunit.rewriteexistingtest(), alglib.sparseconverttocrs(), alglib.testlincgunit.sparsetest(), alglib.testlinlsqrunit.svdtest(), alglib.testsparseunit.testconvertsm(), alglib.testmlpbaseunit.testerr(), alglib.testmlpeunit.testerr(), alglib.testsparseunit.testgcmatrixtype(), alglib.testsparseunit.testgetrow(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlpbaseunit.testmlpgbsubset(), alglib.testmlptrainunit.testmlpgbsubset(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlptrainensregr(), alglib.testmlptrainunit.testmlpzeroweights(), alglib.testnormestimatorunit.testnormestimator(), and alglib.testmlpbaseunit.testprocessing().
static void alglib.sparse.sparsemv (sparsematrix s, double[] x, ref double[] y) inline static
Referenced by alglib.testsparseunit.basicfunctestcrs(), alglib.testsparseunit.copyfunctest(), alglib.testsparseunit.linearfunctionstest(), alglib.linlsqr.linlsqrsolvesparse(), and alglib.sparsemv().
static void alglib.sparse.sparsemtv (sparsematrix s, double[] x, ref double[] y) inline static
Referenced by alglib.testsparseunit.basicfunctestcrs(), alglib.testsparseunit.copyfunctest(), alglib.testsparseunit.linearfunctionstest(), alglib.linlsqr.linlsqrsolvesparse(), and alglib.sparsemtv().
static void alglib.sparse.sparsemv2 (sparsematrix s, double[] x, ref double[] y0, ref double[] y1) inline static
Referenced by alglib.testsparseunit.copyfunctest(), alglib.testsparseunit.linearfunctionstest(), and alglib.sparsemv2().
static void alglib.sparse.sparsesmv (sparsematrix s, bool isupper, double[] x, ref double[] y) inline static
Referenced by alglib.lincg.lincgsolvesparse(), alglib.testsparseunit.linearfunctionsstest(), and alglib.sparsesmv().
static void alglib.sparse.sparsemm (sparsematrix s, double a[,], int k, ref double b[,]) inline static
Referenced by alglib.testsparseunit.linearfunctionsmmtest(), and alglib.sparsemm().
static void alglib.sparse.sparsemtm (sparsematrix s, double a[,], int k, ref double b[,]) inline static
Referenced by alglib.testsparseunit.linearfunctionsmmtest(), and alglib.sparsemtm().
static void alglib.sparse.sparsemm2 (sparsematrix s, double a[,], int k, ref double b0[,], ref double b1[,]) inline static
Referenced by alglib.testsparseunit.linearfunctionsmmtest(), and alglib.sparsemm2().
static void alglib.sparse.sparsesmm (sparsematrix s, bool isupper, double a[,], int k, ref double b[,]) inline static
Referenced by alglib.testsparseunit.linearfunctionssmmtest(), and alglib.sparsesmm().
static void alglib.sparse.sparseresizematrix (sparsematrix s) inline static
Referenced by alglib.sparseresizematrix().
static double alglib.sparse.sparsegetaveragelengthofchain (sparsematrix s) inline static
static bool alglib.sparse.sparseenumerate (sparsematrix s, ref int t0, ref int t1, ref int i, ref int j, ref double v) inline static
Referenced by alglib.testsparseunit.enumeratetest(), alglib.linlsqr.linlsqrsolvesparse(), and alglib.sparseenumerate().
static bool alglib.sparse.sparserewriteexisting (sparsematrix s, int i, int j, double v) inline static
Referenced by alglib.testsparseunit.rewriteexistingtest(), and alglib.sparserewriteexisting().
static void alglib.sparse.sparseinitduidx (sparsematrix s) inline static private
static int alglib.sparse.hash (int i, int j, int tabsize) inline static private
static void alglib.sparse.sparsecreate (int m, int n, int k, sparsematrix s) inline static
static void alglib.sparse.sparsecreatecrs (int m, int n, int[] ner, sparsematrix s) inline static
static void alglib.sparse.sparsecopy (sparsematrix s0, sparsematrix s1) inline static
static void alglib.sparse.sparseadd (sparsematrix s, int i, int j, double v) inline static
static void alglib.sparse.sparseset (sparsematrix s, int i, int j, double v) inline static
static double alglib.sparse.sparseget (sparsematrix s, int i, int j) inline static
static double alglib.sparse.sparsegetdiagonal (sparsematrix s, int i) inline static
Referenced by alglib.testsparseunit.basicfunctest(), alglib.lincg.lincgsolvesparse(), and alglib.sparsegetdiagonal().
static void alglib.sparse.sparseconverttocrs (sparsematrix s) inline static
static void alglib.sparse.sparsemv (sparsematrix s, double[] x, ref double[] y) inline static
static void alglib.sparse.sparsemtv (sparsematrix s, double[] x, ref double[] y) inline static
static void alglib.sparse.sparsemv2 (sparsematrix s, double[] x, ref double[] y0, ref double[] y1) inline static
static void alglib.sparse.sparsesmv (sparsematrix s, bool isupper, double[] x, ref double[] y) inline static
static void alglib.sparse.sparsemm (sparsematrix s, double a[,], int k, ref double b[,]) inline static
static void alglib.sparse.sparsemtm (sparsematrix s, double a[,], int k, ref double b[,]) inline static
static void alglib.sparse.sparsemm2 (sparsematrix s, double a[,], int k, ref double b0[,], ref double b1[,]) inline static
static void alglib.sparse.sparsesmm (sparsematrix s, bool isupper, double a[,], int k, ref double b[,]) inline static
static void alglib.sparse.sparseresizematrix (sparsematrix s) inline static
static double alglib.sparse.sparsegetaveragelengthofchain (sparsematrix s) inline static
static bool alglib.sparse.sparseenumerate (sparsematrix s, ref int t0, ref int t1, ref int i, ref int j, ref double v) inline static
static bool alglib.sparse.sparserewriteexisting (sparsematrix s, int i, int j, double v) inline static
static void alglib.sparse.sparsegetrow (sparsematrix s, int i, ref double[] irow) inline static
Referenced by alglib.sparsegetrow(), alglib.testsparseunit.testgetrow(), alglib.testmlptrainunit.testmlptrainenscls(), and alglib.testmlptrainunit.testmlptrainensregr().
static void alglib.sparse.sparseconverttohash (sparsematrix s) inline static
Referenced by alglib.sparseconverttohash(), alglib.testsparseunit.testconvertsm(), alglib.testsparseunit.testgcmatrixtype(), and alglib.testmlpbaseunit.testprocessing().
static void alglib.sparse.sparsecopytohash (sparsematrix s0, sparsematrix s1) inline static
Referenced by alglib.sparsecopytohash(), alglib.testsparseunit.testconvertsm(), and alglib.testsparseunit.testgcmatrixtype().
static void alglib.sparse.sparsecopytocrs (sparsematrix s0, sparsematrix s1) inline static
Referenced by alglib.sparsecopytocrs(), alglib.testsparseunit.testconvertsm(), and alglib.testsparseunit.testgcmatrixtype().
static int alglib.sparse.sparsegetmatrixtype (sparsematrix s) inline static
Referenced by alglib.sparsegetmatrixtype(), and alglib.testsparseunit.testgcmatrixtype().
static bool alglib.sparse.sparseishash (sparsematrix s) inline static
Referenced by alglib.sparseishash(), and alglib.testsparseunit.testgcmatrixtype().
static bool alglib.sparse.sparseiscrs (sparsematrix s) inline static
Referenced by alglib.sparseiscrs(), and alglib.testsparseunit.testgcmatrixtype().
static void alglib.sparse.sparsefree (sparsematrix s) inline static
Referenced by alglib.sparsefree().
static int alglib.sparse.sparsegetnrows (sparsematrix s) inline static
Referenced by alglib.sparsegetnrows().
static int alglib.sparse.sparsegetncols (sparsematrix s) inline static
Referenced by alglib.sparsegetncols().
static void alglib.sparse.sparseinitduidx (sparsematrix s) inline static private
static int alglib.sparse.hash (int i, int j, int tabsize) inline static private
Member Data Documentation
const double alglib.sparse.desiredloadfactor = 0.66
const double alglib.sparse.maxloadfactor = 0.75
const double alglib.sparse.growfactor = 2.00
const int alglib.sparse.additional = 10
const int alglib.sparse.linalgswitch = 16
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/linalg.cs