IGLib: PipeServer.Form1 Class Reference
PipeServer.Form1 Class Reference
Public Member Functions
Form1 ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void pipeServer_MessageReceived (Server.Client client, string message)
void DisplayMessageReceived (Server.Client client, string message)
void btnStart_Click (object sender, EventArgs e)
void btnSend_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Server pipeServer
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.TextBox tbPipeName
System.Windows.Forms.Label lblPipeName
System.Windows.Forms.Button btnStart
System.Windows.Forms.TextBox tbSend
System.Windows.Forms.Label lblSend
System.Windows.Forms.Button btnSend
System.Windows.Forms.Label lblReceived
System.Windows.Forms.TextBox tbReceived
Constructor & Destructor Documentation
PipeServer.Form1.Form1 () inline
References PipeServer.Form1.InitializeComponent(), PipeServer.Server.MessageReceived, PipeServer.Server.MessageReceivedHandler(), and PipeServer.Form1.pipeServer_MessageReceived().
Member Function Documentation
void PipeServer.Form1.pipeServer_MessageReceived (Server.Client client, string message) inline private
References client(), PipeServer.Form1.DisplayMessageReceived(), and PipeServer.Server.MessageReceivedHandler().
Referenced by PipeServer.Form1.Form1().
void PipeServer.Form1.DisplayMessageReceived (Server.Client client, string message) inline private
References PipeServer.Form1.tbReceived.
Referenced by PipeServer.Form1.pipeServer_MessageReceived().
void PipeServer.Form1.btnStart_Click (object sender, EventArgs e) inline private
References PipeServer.Form1.btnStart, PipeServer.Server.PipeName, PipeServer.Server.Running, PipeServer.Server.Start(), and PipeServer.Form1.tbPipeName.
Referenced by PipeServer.Form1.InitializeComponent().
void PipeServer.Form1.btnSend_Click (object sender, EventArgs e) inline private
References PipeServer.Server.SendMessage(), and PipeServer.Form1.tbSend.
Referenced by PipeServer.Form1.InitializeComponent().
override void PipeServer.Form1.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References PipeServer.Form1.components.
void PipeServer.Form1.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References PipeServer.Form1.btnSend, PipeServer.Form1.btnSend_Click(), PipeServer.Form1.btnStart, PipeServer.Form1.btnStart_Click(), PipeServer.Form1.lblPipeName, PipeServer.Form1.lblReceived, PipeServer.Form1.lblSend, PipeServer.Form1.tbPipeName, PipeServer.Form1.tbReceived, and PipeServer.Form1.tbSend.
Referenced by PipeServer.Form1.Form1().
Member Data Documentation
Server PipeServer.Form1.pipeServer private
System.ComponentModel.IContainer PipeServer.Form1.components = null private
Required designer variable.
Referenced by PipeServer.Form1.Dispose().
System.Windows.Forms.TextBox PipeServer.Form1.tbPipeName private
Referenced by PipeServer.Form1.btnStart_Click(), and PipeServer.Form1.InitializeComponent().
System.Windows.Forms.Label PipeServer.Form1.lblPipeName private
Referenced by PipeServer.Form1.InitializeComponent().
System.Windows.Forms.Button PipeServer.Form1.btnStart private
Referenced by PipeServer.Form1.btnStart_Click(), and PipeServer.Form1.InitializeComponent().
System.Windows.Forms.TextBox PipeServer.Form1.tbSend private
Referenced by PipeServer.Form1.btnSend_Click(), and PipeServer.Form1.InitializeComponent().
System.Windows.Forms.Label PipeServer.Form1.lblSend private
Referenced by PipeServer.Form1.InitializeComponent().
System.Windows.Forms.Button PipeServer.Form1.btnSend private
Referenced by PipeServer.Form1.InitializeComponent().
System.Windows.Forms.Label PipeServer.Form1.lblReceived private
Referenced by PipeServer.Form1.InitializeComponent().
System.Windows.Forms.TextBox PipeServer.Form1.tbReceived private
Referenced by PipeServer.Form1.DisplayMessageReceived(), and PipeServer.Form1.InitializeComponent().
The documentation for this class was generated from the following files:
igsandbox/InterprocessCommunication/named_pipe_examples_master/C# client & server - named pipe/PipeServer/PipeServer/Form1.cs
igsandbox/InterprocessCommunication/named_pipe_examples_master/C# client & server - named pipe/PipeServer/PipeServer/Form1.Designer.cs