IGLib: alglib.dforest Class Reference
alglib.dforest Class Reference
Classes
class decisionforest
class dfinternalbuffers
class dfreport
Static Public Member Functions
static void dfbuildrandomdecisionforest (double[,] xy, int npoints, int nvars, int nclasses, int ntrees, double r, ref int info, decisionforest df, dfreport rep)
static void dfbuildrandomdecisionforestx1 (double[,] xy, int npoints, int nvars, int nclasses, int ntrees, int nrndvars, double r, ref int info, decisionforest df, dfreport rep)
static void dfbuildinternal (double[,] xy, int npoints, int nvars, int nclasses, int ntrees, int samplesize, int nfeatures, int flags, ref int info, decisionforest df, dfreport rep)
static void dfprocess (decisionforest df, double[] x, ref double[] y)
static void dfprocessi (decisionforest df, double[] x, ref double[] y)
static double dfrelclserror (decisionforest df, double[,] xy, int npoints)
static double dfavgce (decisionforest df, double[,] xy, int npoints)
static double dfrmserror (decisionforest df, double[,] xy, int npoints)
static double dfavgerror (decisionforest df, double[,] xy, int npoints)
static double dfavgrelerror (decisionforest df, double[,] xy, int npoints)
static void dfcopy (decisionforest df1, decisionforest df2)
static void dfalloc (alglib.serializer s, decisionforest forest)
static void dfserialize (alglib.serializer s, decisionforest forest)
static void dfunserialize (alglib.serializer s, decisionforest forest)
static void dfbuildrandomdecisionforest (double[,] xy, int npoints, int nvars, int nclasses, int ntrees, double r, ref int info, decisionforest df, dfreport rep)
static void dfbuildrandomdecisionforestx1 (double[,] xy, int npoints, int nvars, int nclasses, int ntrees, int nrndvars, double r, ref int info, decisionforest df, dfreport rep)
static void dfbuildinternal (double[,] xy, int npoints, int nvars, int nclasses, int ntrees, int samplesize, int nfeatures, int flags, ref int info, decisionforest df, dfreport rep)
static void dfprocess (decisionforest df, double[] x, ref double[] y)
static void dfprocessi (decisionforest df, double[] x, ref double[] y)
static double dfrelclserror (decisionforest df, double[,] xy, int npoints)
static double dfavgce (decisionforest df, double[,] xy, int npoints)
static double dfrmserror (decisionforest df, double[,] xy, int npoints)
static double dfavgerror (decisionforest df, double[,] xy, int npoints)
static double dfavgrelerror (decisionforest df, double[,] xy, int npoints)
static void dfcopy (decisionforest df1, decisionforest df2)
static void dfalloc (alglib.serializer s, decisionforest forest)
static void dfserialize (alglib.serializer s, decisionforest forest)
static void dfunserialize (alglib.serializer s, decisionforest forest)
Public Attributes
const int innernodewidth = 3
const int leafnodewidth = 2
const int dfusestrongsplits = 1
const int dfuseevs = 2
const int dffirstversion = 0
Static Private Member Functions
static int dfclserror (decisionforest df, double[,] xy, int npoints)
static void dfprocessinternal (decisionforest df, int offs, double[] x, ref double[] y)
static void dfbuildtree (double[,] xy, int npoints, int nvars, int nclasses, int nfeatures, int nvarsinpool, int flags, dfinternalbuffers bufs)
static void dfbuildtreerec (double[,] xy, int npoints, int nvars, int nclasses, int nfeatures, int nvarsinpool, int flags, ref int numprocessed, int idx1, int idx2, dfinternalbuffers bufs)
static void dfsplitc (ref double[] x, ref int[] c, ref int[] cntbuf, int n, int nc, int flags, ref int info, ref double threshold, ref double e, ref double[] sortrbuf, ref int[] sortibuf)
static void dfsplitr (ref double[] x, ref double[] y, int n, int flags, ref int info, ref double threshold, ref double e, ref double[] sortrbuf, ref double[] sortrbuf2)
static int dfclserror (decisionforest df, double[,] xy, int npoints)
static void dfprocessinternal (decisionforest df, int offs, double[] x, ref double[] y)
static void dfbuildtree (double[,] xy, int npoints, int nvars, int nclasses, int nfeatures, int nvarsinpool, int flags, dfinternalbuffers bufs, hqrnd.hqrndstate rs)
static void dfbuildtreerec (double[,] xy, int npoints, int nvars, int nclasses, int nfeatures, int nvarsinpool, int flags, ref int numprocessed, int idx1, int idx2, dfinternalbuffers bufs, hqrnd.hqrndstate rs)
static void dfsplitc (ref double[] x, ref int[] c, ref int[] cntbuf, int n, int nc, int flags, ref int info, ref double threshold, ref double e, ref double[] sortrbuf, ref int[] sortibuf)
static void dfsplitr (ref double[] x, ref double[] y, int n, int flags, ref int info, ref double threshold, ref double e, ref double[] sortrbuf, ref double[] sortrbuf2)
Member Function Documentation
static void alglib.dforest.dfbuildrandomdecisionforest (double xy[,], int npoints, int nvars, int nclasses, int ntrees, double r, ref int info, decisionforest df, dfreport rep) inline static
References alglib.dforest.dfbuildinternal(), and alglib.dforest.dfuseevs.
Referenced by alglib.dfbuildrandomdecisionforest().
static void alglib.dforest.dfbuildrandomdecisionforestx1 (double xy[,], int npoints, int nvars, int nclasses, int ntrees, int nrndvars, double r, ref int info, decisionforest df, dfreport rep) inline static
References alglib.dforest.dfbuildinternal().
Referenced by alglib.dfbuildrandomdecisionforestx1().
static void alglib.dforest.dfbuildinternal (double xy[,], int npoints, int nvars, int nclasses, int ntrees, int samplesize, int nfeatures, int flags, ref int info, decisionforest df, dfreport rep) inline static
References alglib.dforest.dfreport.avgce, alglib.dforest.dfreport.avgerror, alglib.dforest.dfreport.avgrelerror, alglib.dforest.decisionforest.bufsize, alglib.dforest.dfinternalbuffers.classibuf, alglib.dforest.dfavgce(), alglib.dforest.dfavgerror(), alglib.dforest.dfavgrelerror(), alglib.dforest.dfbuildtree(), alglib.dforest.dfprocessinternal(), alglib.dforest.dfrelclserror(), alglib.dforest.dfrmserror(), alglib.dforest.dfinternalbuffers.evsbin, alglib.dforest.dfinternalbuffers.evssplits, alglib.dforest.dfinternalbuffers.idxbuf, alglib.math.minrealnumber, alglib.dforest.decisionforest.nclasses, alglib.dforest.decisionforest.ntrees, alglib.dforest.decisionforest.nvars, alglib.dforest.dfreport.oobavgce, alglib.dforest.dfreport.oobavgerror, alglib.dforest.dfreport.oobavgrelerror, alglib.dforest.dfreport.oobrelclserror, alglib.dforest.dfreport.oobrmserror, alglib.math.randominteger(), alglib.dforest.dfreport.relclserror, alglib.dforest.dfreport.rmserror, alglib.dforest.dfinternalbuffers.sortibuf, alglib.dforest.dfinternalbuffers.sortrbuf, alglib.dforest.dfinternalbuffers.sortrbuf2, alglib.math.sqr(), alglib.dforest.dfinternalbuffers.tmpbufi, alglib.dforest.dfinternalbuffers.tmpbufr, alglib.dforest.dfinternalbuffers.tmpbufr2, alglib.dforest.dfinternalbuffers.treebuf, alglib.dforest.decisionforest.trees, and alglib.dforest.dfinternalbuffers.varpool.
Referenced by alglib.testdforestunit.basictest1(), alglib.testdforestunit.basictest2(), alglib.testdforestunit.basictest3(), alglib.testdforestunit.basictest4(), alglib.testdforestunit.basictest5(), alglib.dforest.dfbuildrandomdecisionforest(), alglib.dforest.dfbuildrandomdecisionforestx1(), alglib.testdforestunit.testprocessing(), and alglib.testdforestunit.unsetdf().
static void alglib.dforest.dfprocess (decisionforest df, double[] x, ref double[] y) inline static
References alglib.dforest.dfprocessinternal(), alglib.dforest.decisionforest.nclasses, alglib.dforest.decisionforest.ntrees, and alglib.dforest.decisionforest.trees.
Referenced by alglib.testdforestunit.basictest1(), alglib.testdforestunit.basictest2(), alglib.testdforestunit.basictest3(), alglib.testdforestunit.basictest4(), alglib.testdforestunit.basictest5(), alglib.dforest.dfavgce(), alglib.dforest.dfavgerror(), alglib.dforest.dfavgrelerror(), alglib.dforest.dfclserror(), alglib.dfprocess(), alglib.dforest.dfprocessi(), alglib.dforest.dfrmserror(), and alglib.testdforestunit.testprocessing().
static void alglib.dforest.dfprocessi (decisionforest df, double[] x, ref double[] y) inline static
References alglib.dforest.dfprocess().
Referenced by alglib.dfprocessi().
static double alglib.dforest.dfrelclserror (decisionforest df, double xy[,], int npoints) inline static
References alglib.dforest.dfclserror().
Referenced by alglib.dforest.dfbuildinternal(), and alglib.dfrelclserror().
static double alglib.dforest.dfavgce (decisionforest df, double xy[,], int npoints) inline static
References alglib.dforest.dfprocess(), alglib.math.minrealnumber, alglib.dforest.decisionforest.nclasses, and alglib.dforest.decisionforest.nvars.
Referenced by alglib.dfavgce(), and alglib.dforest.dfbuildinternal().
static double alglib.dforest.dfrmserror (decisionforest df, double xy[,], int npoints) inline static
References alglib.dforest.dfprocess(), alglib.dforest.decisionforest.nclasses, alglib.dforest.decisionforest.nvars, and alglib.math.sqr().
Referenced by alglib.dforest.dfbuildinternal(), and alglib.dfrmserror().
static double alglib.dforest.dfavgerror (decisionforest df, double xy[,], int npoints) inline static
References alglib.dforest.dfprocess(), alglib.dforest.decisionforest.nclasses, and alglib.dforest.decisionforest.nvars.
Referenced by alglib.dfavgerror(), and alglib.dforest.dfbuildinternal().
static double alglib.dforest.dfavgrelerror (decisionforest df, double xy[,], int npoints) inline static
References alglib.dforest.dfprocess(), alglib.dforest.decisionforest.nclasses, and alglib.dforest.decisionforest.nvars.
Referenced by alglib.dfavgrelerror(), and alglib.dforest.dfbuildinternal().
static void alglib.dforest.dfcopy (decisionforest df1, decisionforest df2) inline static
References alglib.dforest.decisionforest.bufsize, alglib.dforest.decisionforest.nclasses, alglib.dforest.decisionforest.ntrees, alglib.dforest.decisionforest.nvars, and alglib.dforest.decisionforest.trees.
Referenced by alglib.testdforestunit.testprocessing().
static void alglib.dforest.dfalloc (alglib.serializer s, decisionforest forest) inline static
References alglib.apserv.allocrealarray(), alglib.dforest.decisionforest.bufsize, and alglib.dforest.decisionforest.trees.
Referenced by alglib.dfserialize(), and alglib.testdforestunit.testprocessing().
static void alglib.dforest.dfserialize (alglib.serializer s, decisionforest forest) inline static
References alglib.dforest.decisionforest.bufsize, alglib.scodes.getrdfserializationcode(), alglib.dforest.decisionforest.nclasses, alglib.dforest.decisionforest.ntrees, alglib.dforest.decisionforest.nvars, alglib.apserv.serializerealarray(), and alglib.dforest.decisionforest.trees.
Referenced by alglib.dfserialize(), and alglib.testdforestunit.testprocessing().
static void alglib.dforest.dfunserialize (alglib.serializer s, decisionforest forest) inline static
References alglib.ap.assert(), alglib.dforest.decisionforest.bufsize, alglib.scodes.getrdfserializationcode(), alglib.dforest.decisionforest.nclasses, alglib.dforest.decisionforest.ntrees, alglib.dforest.decisionforest.nvars, alglib.dforest.decisionforest.trees, and alglib.apserv.unserializerealarray().
Referenced by alglib.dfunserialize(), and alglib.testdforestunit.testprocessing().
static int alglib.dforest.dfclserror (decisionforest df, double xy[,], int npoints) inline static private
References alglib.dforest.dfprocess(), alglib.dforest.decisionforest.nclasses, and alglib.dforest.decisionforest.nvars.
Referenced by alglib.dforest.dfrelclserror().
static void alglib.dforest.dfprocessinternal (decisionforest df, int offs, double[] x, ref double[] y) inline static private
References alglib.dforest.innernodewidth, alglib.dforest.decisionforest.nclasses, and alglib.dforest.decisionforest.trees.
Referenced by alglib.dforest.dfbuildinternal(), and alglib.dforest.dfprocess().
static void alglib.dforest.dfbuildtree (double xy[,], int npoints, int nvars, int nclasses, int nfeatures, int nvarsinpool, int flags, dfinternalbuffers bufs) inline static private
References alglib.ap.assert(), alglib.dforest.dfbuildtreerec(), alglib.dforest.dfinternalbuffers.idxbuf, and alglib.dforest.dfinternalbuffers.treebuf.
Referenced by alglib.dforest.dfbuildinternal().
static void alglib.dforest.dfbuildtreerec (double xy[,], int npoints, int nvars, int nclasses, int nfeatures, int nvarsinpool, int flags, ref int numprocessed, int idx1, int idx2, dfinternalbuffers bufs) inline static private
References alglib.ap.assert(), alglib.dforest.dfinternalbuffers.classibuf, alglib.dforest.dfsplitc(), alglib.dforest.dfsplitr(), alglib.dforest.dfinternalbuffers.evsbin, alglib.dforest.dfinternalbuffers.evssplits, alglib.dforest.dfinternalbuffers.idxbuf, alglib.dforest.innernodewidth, alglib.dforest.leafnodewidth, alglib.math.randominteger(), alglib.dforest.dfinternalbuffers.sortibuf, alglib.dforest.dfinternalbuffers.sortrbuf, alglib.dforest.dfinternalbuffers.sortrbuf2, alglib.math.sqr(), alglib.dforest.dfinternalbuffers.tmpbufi, alglib.dforest.dfinternalbuffers.tmpbufr, alglib.dforest.dfinternalbuffers.tmpbufr2, alglib.dforest.dfinternalbuffers.treebuf, and alglib.dforest.dfinternalbuffers.varpool.
Referenced by alglib.dforest.dfbuildtree().
static void alglib.dforest.dfsplitc (ref double[] x, ref int[] c, ref int[] cntbuf, int n, int nc, int flags, ref int info, ref double threshold, ref double e, ref double[] sortrbuf, ref int[] sortibuf) inline static private
References alglib.ap.assert(), alglib.math.maxrealnumber, alglib.math.sqr(), and alglib.tsort.tagsortfasti().
Referenced by alglib.dforest.dfbuildtreerec().
static void alglib.dforest.dfsplitr (ref double[] x, ref double[] y, int n, int flags, ref int info, ref double threshold, ref double e, ref double[] sortrbuf, ref double[] sortrbuf2) inline static private
References alglib.ap.assert(), alglib.math.maxrealnumber, alglib.math.sqr(), and alglib.tsort.tagsortfastr().
Referenced by alglib.dforest.dfbuildtreerec().
static void alglib.dforest.dfbuildrandomdecisionforest (double xy[,], int npoints, int nvars, int nclasses, int ntrees, double r, ref int info, decisionforest df, dfreport rep) inline static
static void alglib.dforest.dfbuildrandomdecisionforestx1 (double xy[,], int npoints, int nvars, int nclasses, int ntrees, int nrndvars, double r, ref int info, decisionforest df, dfreport rep) inline static
static void alglib.dforest.dfbuildinternal (double xy[,], int npoints, int nvars, int nclasses, int ntrees, int samplesize, int nfeatures, int flags, ref int info, decisionforest df, dfreport rep) inline static
static void alglib.dforest.dfprocess (decisionforest df, double[] x, ref double[] y) inline static
static void alglib.dforest.dfprocessi (decisionforest df, double[] x, ref double[] y) inline static
static double alglib.dforest.dfrelclserror (decisionforest df, double xy[,], int npoints) inline static
static double alglib.dforest.dfavgce (decisionforest df, double xy[,], int npoints) inline static
static double alglib.dforest.dfrmserror (decisionforest df, double xy[,], int npoints) inline static
static double alglib.dforest.dfavgerror (decisionforest df, double xy[,], int npoints) inline static
static double alglib.dforest.dfavgrelerror (decisionforest df, double xy[,], int npoints) inline static
static void alglib.dforest.dfcopy (decisionforest df1, decisionforest df2) inline static
static void alglib.dforest.dfalloc (alglib.serializer s, decisionforest forest) inline static
static void alglib.dforest.dfserialize (alglib.serializer s, decisionforest forest) inline static
static void alglib.dforest.dfunserialize (alglib.serializer s, decisionforest forest) inline static
static int alglib.dforest.dfclserror (decisionforest df, double xy[,], int npoints) inline static private
static void alglib.dforest.dfprocessinternal (decisionforest df, int offs, double[] x, ref double[] y) inline static private
static void alglib.dforest.dfbuildtree (double xy[,], int npoints, int nvars, int nclasses, int nfeatures, int nvarsinpool, int flags, dfinternalbuffers bufs, hqrnd.hqrndstate rs) inline static private
static void alglib.dforest.dfbuildtreerec (double xy[,], int npoints, int nvars, int nclasses, int nfeatures, int nvarsinpool, int flags, ref int numprocessed, int idx1, int idx2, dfinternalbuffers bufs, hqrnd.hqrndstate rs) inline static private
static void alglib.dforest.dfsplitc (ref double[] x, ref int[] c, ref int[] cntbuf, int n, int nc, int flags, ref int info, ref double threshold, ref double e, ref double[] sortrbuf, ref int[] sortibuf) inline static private
static void alglib.dforest.dfsplitr (ref double[] x, ref double[] y, int n, int flags, ref int info, ref double threshold, ref double e, ref double[] sortrbuf, ref double[] sortrbuf2) inline static private
Member Data Documentation
const int alglib.dforest.innernodewidth = 3
Referenced by alglib.dforest.dfbuildtreerec(), and alglib.dforest.dfprocessinternal().
const int alglib.dforest.leafnodewidth = 2
Referenced by alglib.dforest.dfbuildtreerec().
const int alglib.dforest.dfusestrongsplits = 1
const int alglib.dforest.dfuseevs = 2
Referenced by alglib.dforest.dfbuildrandomdecisionforest().
const int alglib.dforest.dffirstversion = 0
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/dataanalysis.cs