IGLib: alglib.hqrnd.hqrndstate Class Reference
alglib.hqrnd.hqrndstate Class Reference
Public Member Functions
hqrndstate ()
override void init ()
override alglib.apobject make_copy ()
Public Attributes
int s1
int s2
double v
int magicv
Constructor & Destructor Documentation
alglib.hqrnd.hqrndstate.hqrndstate () inline
References alglib.hqrnd.hqrndstate.init().
Referenced by alglib.hqrnd.hqrndstate.make_copy().
Member Function Documentation
override void alglib.hqrnd.hqrndstate.init () inline virtual
Implements alglib.apobject.
Referenced by alglib.hqrnd.hqrndstate.hqrndstate().
override alglib.apobject alglib.hqrnd.hqrndstate.make_copy () inline virtual
Implements alglib.apobject.
References alglib.hqrnd.hqrndstate.hqrndstate(), alglib.hqrnd.hqrndstate.magicv, alglib.hqrnd.hqrndstate.s1, and alglib.hqrnd.hqrndstate.s2.
Member Data Documentation
int alglib.hqrnd.hqrndstate.s1
Referenced by alglib.hqrnd.hqrndseed(), and alglib.hqrnd.hqrndstate.make_copy().
int alglib.hqrnd.hqrndstate.s2
Referenced by alglib.hqrnd.hqrndseed(), and alglib.hqrnd.hqrndstate.make_copy().
double alglib.hqrnd.hqrndstate.v
Referenced by alglib.hqrnd.hqrndseed(), and alglib.hqrnd.hqrnduniformr().
int alglib.hqrnd.hqrndstate.magicv
Referenced by alglib.hqrnd.hqrndseed(), and alglib.hqrnd.hqrndstate.make_copy().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/alglibmisc.cs