IGLib: alglib.densesolver Class Reference
alglib.densesolver Class Reference
Classes
class densesolverlsreport
class densesolverreport
Static Public Member Functions
static void rmatrixsolve (double[,] a, int n, double[] b, ref int info, densesolverreport rep, ref double[] x)
static void rmatrixsolvem (double[,] a, int n, double[,] b, int m, bool rfs, ref int info, densesolverreport rep, ref double[,] x)
static void rmatrixlusolve (double[,] lua, int[] p, int n, double[] b, ref int info, densesolverreport rep, ref double[] x)
static void rmatrixlusolvem (double[,] lua, int[] p, int n, double[,] b, int m, ref int info, densesolverreport rep, ref double[,] x)
static void rmatrixmixedsolve (double[,] a, double[,] lua, int[] p, int n, double[] b, ref int info, densesolverreport rep, ref double[] x)
static void rmatrixmixedsolvem (double[,] a, double[,] lua, int[] p, int n, double[,] b, int m, ref int info, densesolverreport rep, ref double[,] x)
static void cmatrixsolvem (complex[,] a, int n, complex[,] b, int m, bool rfs, ref int info, densesolverreport rep, ref complex[,] x)
static void cmatrixsolve (complex[,] a, int n, complex[] b, ref int info, densesolverreport rep, ref complex[] x)
static void cmatrixlusolvem (complex[,] lua, int[] p, int n, complex[,] b, int m, ref int info, densesolverreport rep, ref complex[,] x)
static void cmatrixlusolve (complex[,] lua, int[] p, int n, complex[] b, ref int info, densesolverreport rep, ref complex[] x)
static void cmatrixmixedsolvem (complex[,] a, complex[,] lua, int[] p, int n, complex[,] b, int m, ref int info, densesolverreport rep, ref complex[,] x)
static void cmatrixmixedsolve (complex[,] a, complex[,] lua, int[] p, int n, complex[] b, ref int info, densesolverreport rep, ref complex[] x)
static void spdmatrixsolvem (double[,] a, int n, bool isupper, double[,] b, int m, ref int info, densesolverreport rep, ref double[,] x)
static void spdmatrixsolve (double[,] a, int n, bool isupper, double[] b, ref int info, densesolverreport rep, ref double[] x)
static void spdmatrixcholeskysolvem (double[,] cha, int n, bool isupper, double[,] b, int m, ref int info, densesolverreport rep, ref double[,] x)
static void spdmatrixcholeskysolve (double[,] cha, int n, bool isupper, double[] b, ref int info, densesolverreport rep, ref double[] x)
static void hpdmatrixsolvem (complex[,] a, int n, bool isupper, complex[,] b, int m, ref int info, densesolverreport rep, ref complex[,] x)
static void hpdmatrixsolve (complex[,] a, int n, bool isupper, complex[] b, ref int info, densesolverreport rep, ref complex[] x)
static void hpdmatrixcholeskysolvem (complex[,] cha, int n, bool isupper, complex[,] b, int m, ref int info, densesolverreport rep, ref complex[,] x)
static void hpdmatrixcholeskysolve (complex[,] cha, int n, bool isupper, complex[] b, ref int info, densesolverreport rep, ref complex[] x)
static void rmatrixsolvels (double[,] a, int nrows, int ncols, double[] b, double threshold, ref int info, densesolverlsreport rep, ref double[] x)
static void rmatrixsolve (double[,] a, int n, double[] b, ref int info, densesolverreport rep, ref double[] x)
static void rmatrixsolvem (double[,] a, int n, double[,] b, int m, bool rfs, ref int info, densesolverreport rep, ref double[,] x)
static void rmatrixlusolve (double[,] lua, int[] p, int n, double[] b, ref int info, densesolverreport rep, ref double[] x)
static void rmatrixlusolvem (double[,] lua, int[] p, int n, double[,] b, int m, ref int info, densesolverreport rep, ref double[,] x)
static void rmatrixmixedsolve (double[,] a, double[,] lua, int[] p, int n, double[] b, ref int info, densesolverreport rep, ref double[] x)
static void rmatrixmixedsolvem (double[,] a, double[,] lua, int[] p, int n, double[,] b, int m, ref int info, densesolverreport rep, ref double[,] x)
static void cmatrixsolvem (complex[,] a, int n, complex[,] b, int m, bool rfs, ref int info, densesolverreport rep, ref complex[,] x)
static void cmatrixsolve (complex[,] a, int n, complex[] b, ref int info, densesolverreport rep, ref complex[] x)
static void cmatrixlusolvem (complex[,] lua, int[] p, int n, complex[,] b, int m, ref int info, densesolverreport rep, ref complex[,] x)
static void cmatrixlusolve (complex[,] lua, int[] p, int n, complex[] b, ref int info, densesolverreport rep, ref complex[] x)
static void cmatrixmixedsolvem (complex[,] a, complex[,] lua, int[] p, int n, complex[,] b, int m, ref int info, densesolverreport rep, ref complex[,] x)
static void cmatrixmixedsolve (complex[,] a, complex[,] lua, int[] p, int n, complex[] b, ref int info, densesolverreport rep, ref complex[] x)
static void spdmatrixsolvem (double[,] a, int n, bool isupper, double[,] b, int m, ref int info, densesolverreport rep, ref double[,] x)
static void spdmatrixsolve (double[,] a, int n, bool isupper, double[] b, ref int info, densesolverreport rep, ref double[] x)
static void spdmatrixcholeskysolvem (double[,] cha, int n, bool isupper, double[,] b, int m, ref int info, densesolverreport rep, ref double[,] x)
static void spdmatrixcholeskysolve (double[,] cha, int n, bool isupper, double[] b, ref int info, densesolverreport rep, ref double[] x)
static void hpdmatrixsolvem (complex[,] a, int n, bool isupper, complex[,] b, int m, ref int info, densesolverreport rep, ref complex[,] x)
static void hpdmatrixsolve (complex[,] a, int n, bool isupper, complex[] b, ref int info, densesolverreport rep, ref complex[] x)
static void hpdmatrixcholeskysolvem (complex[,] cha, int n, bool isupper, complex[,] b, int m, ref int info, densesolverreport rep, ref complex[,] x)
static void hpdmatrixcholeskysolve (complex[,] cha, int n, bool isupper, complex[] b, ref int info, densesolverreport rep, ref complex[] x)
static void rmatrixsolvels (double[,] a, int nrows, int ncols, double[] b, double threshold, ref int info, densesolverlsreport rep, ref double[] x)
Static Private Member Functions
static void rmatrixlusolveinternal (double[,] lua, int[] p, double scalea, int n, double[,] a, bool havea, double[,] b, int m, ref int info, densesolverreport rep, ref double[,] x)
static void spdmatrixcholeskysolveinternal (double[,] cha, double sqrtscalea, int n, bool isupper, double[,] a, bool havea, double[,] b, int m, ref int info, densesolverreport rep, ref double[,] x)
static void cmatrixlusolveinternal (complex[,] lua, int[] p, double scalea, int n, complex[,] a, bool havea, complex[,] b, int m, ref int info, densesolverreport rep, ref complex[,] x)
static void hpdmatrixcholeskysolveinternal (complex[,] cha, double sqrtscalea, int n, bool isupper, complex[,] a, bool havea, complex[,] b, int m, ref int info, densesolverreport rep, ref complex[,] x)
static int densesolverrfsmax (int n, double r1, double rinf)
static int densesolverrfsmaxv2 (int n, double r2)
static void rbasiclusolve (double[,] lua, int[] p, double scalea, int n, ref double[] xb, ref double[] tmp)
static void spdbasiccholeskysolve (double[,] cha, double sqrtscalea, int n, bool isupper, ref double[] xb, ref double[] tmp)
static void cbasiclusolve (complex[,] lua, int[] p, double scalea, int n, ref complex[] xb, ref complex[] tmp)
static void hpdbasiccholeskysolve (complex[,] cha, double sqrtscalea, int n, bool isupper, ref complex[] xb, ref complex[] tmp)
static void rmatrixlusolveinternal (double[,] lua, int[] p, double scalea, int n, double[,] a, bool havea, double[,] b, int m, ref int info, densesolverreport rep, ref double[,] x)
static void spdmatrixcholeskysolveinternal (double[,] cha, double sqrtscalea, int n, bool isupper, double[,] a, bool havea, double[,] b, int m, ref int info, densesolverreport rep, ref double[,] x)
static void cmatrixlusolveinternal (complex[,] lua, int[] p, double scalea, int n, complex[,] a, bool havea, complex[,] b, int m, ref int info, densesolverreport rep, ref complex[,] x)
static void hpdmatrixcholeskysolveinternal (complex[,] cha, double sqrtscalea, int n, bool isupper, complex[,] a, bool havea, complex[,] b, int m, ref int info, densesolverreport rep, ref complex[,] x)
static int densesolverrfsmax (int n, double r1, double rinf)
static int densesolverrfsmaxv2 (int n, double r2)
static void rbasiclusolve (double[,] lua, int[] p, double scalea, int n, ref double[] xb, ref double[] tmp)
static void spdbasiccholeskysolve (double[,] cha, double sqrtscalea, int n, bool isupper, ref double[] xb, ref double[] tmp)
static void cbasiclusolve (complex[,] lua, int[] p, double scalea, int n, ref complex[] xb, ref complex[] tmp)
static void hpdbasiccholeskysolve (complex[,] cha, double sqrtscalea, int n, bool isupper, ref complex[] xb, ref complex[] tmp)
Member Function Documentation
static void alglib.densesolver.rmatrixsolve (double a[,], int n, double[] b, ref int info, densesolverreport rep, ref double[] x) inline static
References alglib.densesolver.rmatrixsolvem().
Referenced by alglib.rmatrixsolve(), and alglib.testdensesolverunit.testrsolver().
static void alglib.densesolver.rmatrixsolvem (double a[,], int n, double b[,], int m, bool rfs, ref int info, densesolverreport rep, ref double x[,]) inline static
References alglib.trfac.rmatrixlu(), and alglib.densesolver.rmatrixlusolveinternal().
Referenced by alglib.densesolver.rmatrixsolve(), alglib.rmatrixsolvem(), and alglib.testdensesolverunit.testrsolver().
static void alglib.densesolver.rmatrixlusolve (double lua[,], int[] p, int n, double[] b, ref int info, densesolverreport rep, ref double[] x) inline static
References alglib.densesolver.rmatrixlusolvem().
Referenced by alglib.rmatrixlusolve(), and alglib.testdensesolverunit.testrsolver().
static void alglib.densesolver.rmatrixlusolvem (double lua[,], int[] p, int n, double b[,], int m, ref int info, densesolverreport rep, ref double x[,]) inline static
References alglib.densesolver.rmatrixlusolveinternal().
Referenced by alglib.densesolver.rmatrixlusolve(), alglib.rmatrixlusolvem(), and alglib.testdensesolverunit.testrsolver().
static void alglib.densesolver.rmatrixmixedsolve (double a[,], double lua[,], int[] p, int n, double[] b, ref int info, densesolverreport rep, ref double[] x) inline static
References alglib.densesolver.rmatrixmixedsolvem().
Referenced by alglib.rmatrixmixedsolve(), and alglib.testdensesolverunit.testrsolver().
static void alglib.densesolver.rmatrixmixedsolvem (double a[,], double lua[,], int[] p, int n, double b[,], int m, ref int info, densesolverreport rep, ref double x[,]) inline static
References alglib.densesolver.rmatrixlusolveinternal().
Referenced by alglib.densesolver.rmatrixmixedsolve(), alglib.rmatrixmixedsolvem(), and alglib.testdensesolverunit.testrsolver().
static void alglib.densesolver.cmatrixsolvem (complex a[,], int n, complex b[,], int m, bool rfs, ref int info, densesolverreport rep, ref complex x[,]) inline static
References alglib.math.abscomplex(), alglib.trfac.cmatrixlu(), and alglib.densesolver.cmatrixlusolveinternal().
Referenced by alglib.densesolver.cmatrixsolve(), alglib.cmatrixsolvem(), and alglib.testdensesolverunit.testcsolver().
static void alglib.densesolver.cmatrixsolve (complex a[,], int n, complex[] b, ref int info, densesolverreport rep, ref complex[] x) inline static
References alglib.densesolver.cmatrixsolvem().
Referenced by alglib.cmatrixsolve(), and alglib.testdensesolverunit.testcsolver().
static void alglib.densesolver.cmatrixlusolvem (complex lua[,], int[] p, int n, complex b[,], int m, ref int info, densesolverreport rep, ref complex x[,]) inline static
References alglib.math.abscomplex(), and alglib.densesolver.cmatrixlusolveinternal().
Referenced by alglib.densesolver.cmatrixlusolve(), alglib.cmatrixlusolvem(), and alglib.testdensesolverunit.testcsolver().
static void alglib.densesolver.cmatrixlusolve (complex lua[,], int[] p, int n, complex[] b, ref int info, densesolverreport rep, ref complex[] x) inline static
References alglib.densesolver.cmatrixlusolvem().
Referenced by alglib.cmatrixlusolve(), and alglib.testdensesolverunit.testcsolver().
static void alglib.densesolver.cmatrixmixedsolvem (complex a[,], complex lua[,], int[] p, int n, complex b[,], int m, ref int info, densesolverreport rep, ref complex x[,]) inline static
References alglib.math.abscomplex(), and alglib.densesolver.cmatrixlusolveinternal().
Referenced by alglib.densesolver.cmatrixmixedsolve(), alglib.cmatrixmixedsolvem(), and alglib.testdensesolverunit.testcsolver().
static void alglib.densesolver.cmatrixmixedsolve (complex a[,], complex lua[,], int[] p, int n, complex[] b, ref int info, densesolverreport rep, ref complex[] x) inline static
References alglib.densesolver.cmatrixmixedsolvem().
Referenced by alglib.cmatrixmixedsolve(), and alglib.testdensesolverunit.testcsolver().
static void alglib.densesolver.spdmatrixsolvem (double a[,], int n, bool isupper, double b[,], int m, ref int info, densesolverreport rep, ref double x[,]) inline static
References alglib.densesolver.densesolverreport.r1, alglib.densesolver.densesolverreport.rinf, alglib.trfac.spdmatrixcholesky(), and alglib.densesolver.spdmatrixcholeskysolveinternal().
Referenced by alglib.densesolver.spdmatrixsolve(), alglib.spdmatrixsolvem(), and alglib.testdensesolverunit.testspdsolver().
static void alglib.densesolver.spdmatrixsolve (double a[,], int n, bool isupper, double[] b, ref int info, densesolverreport rep, ref double[] x) inline static
References alglib.densesolver.spdmatrixsolvem().
Referenced by alglib.spdmatrixsolve(), and alglib.testdensesolverunit.testspdsolver().
static void alglib.densesolver.spdmatrixcholeskysolvem (double cha[,], int n, bool isupper, double b[,], int m, ref int info, densesolverreport rep, ref double x[,]) inline static
References alglib.densesolver.spdmatrixcholeskysolveinternal().
Referenced by alglib.densesolver.spdmatrixcholeskysolve(), alglib.spdmatrixcholeskysolvem(), and alglib.testdensesolverunit.testspdsolver().
static void alglib.densesolver.spdmatrixcholeskysolve (double cha[,], int n, bool isupper, double[] b, ref int info, densesolverreport rep, ref double[] x) inline static
References alglib.densesolver.spdmatrixcholeskysolvem().
Referenced by alglib.logit.mnltrainh(), alglib.spdmatrixcholeskysolve(), and alglib.testdensesolverunit.testspdsolver().
static void alglib.densesolver.hpdmatrixsolvem (complex a[,], int n, bool isupper, complex b[,], int m, ref int info, densesolverreport rep, ref complex x[,]) inline static
References alglib.math.abscomplex(), alglib.trfac.hpdmatrixcholesky(), alglib.densesolver.hpdmatrixcholeskysolveinternal(), alglib.densesolver.densesolverreport.r1, and alglib.densesolver.densesolverreport.rinf.
Referenced by alglib.densesolver.hpdmatrixsolve(), alglib.hpdmatrixsolvem(), and alglib.testdensesolverunit.testhpdsolver().
static void alglib.densesolver.hpdmatrixsolve (complex a[,], int n, bool isupper, complex[] b, ref int info, densesolverreport rep, ref complex[] x) inline static
References alglib.densesolver.hpdmatrixsolvem().
Referenced by alglib.hpdmatrixsolve(), and alglib.testdensesolverunit.testhpdsolver().
static void alglib.densesolver.hpdmatrixcholeskysolvem (complex cha[,], int n, bool isupper, complex b[,], int m, ref int info, densesolverreport rep, ref complex x[,]) inline static
References alglib.math.abscomplex(), and alglib.densesolver.hpdmatrixcholeskysolveinternal().
Referenced by alglib.densesolver.hpdmatrixcholeskysolve(), alglib.hpdmatrixcholeskysolvem(), and alglib.testdensesolverunit.testhpdsolver().
static void alglib.densesolver.hpdmatrixcholeskysolve (complex cha[,], int n, bool isupper, complex[] b, ref int info, densesolverreport rep, ref complex[] x) inline static
References alglib.densesolver.hpdmatrixcholeskysolvem().
Referenced by alglib.hpdmatrixcholeskysolve(), and alglib.testdensesolverunit.testhpdsolver().
static void alglib.densesolver.rmatrixsolvels (double a[,], int nrows, int ncols, double[] b, double threshold, ref int info, densesolverlsreport rep, ref double[] x) inline static
References alglib.densesolver.densesolverlsreport.cx, alglib.densesolver.densesolverrfsmaxv2(), alglib.densesolver.densesolverlsreport.k, alglib.math.machineepsilon, alglib.densesolver.densesolverlsreport.n, alglib.densesolver.densesolverlsreport.r2, alglib.svd.rmatrixsvd(), and alglib.xblas.xdot().
Referenced by alglib.idwint.idwinternalsolver(), alglib.rmatrixsolvels(), and alglib.testdensesolverunit.testrsolver().
static void alglib.densesolver.rmatrixlusolveinternal (double lua[,], int[] p, double scalea, int n, double a[,], bool havea, double b[,], int m, ref int info, densesolverreport rep, ref double x[,]) inline static private
References alglib.ap.assert(), alglib.densesolver.densesolverrfsmax(), alglib.densesolver.densesolverreport.r1, alglib.densesolver.rbasiclusolve(), alglib.rcond.rcondthreshold(), alglib.densesolver.densesolverreport.rinf, alglib.rcond.rmatrixlurcond1(), alglib.rcond.rmatrixlurcondinf(), and alglib.xblas.xdot().
Referenced by alglib.densesolver.rmatrixlusolvem(), alglib.densesolver.rmatrixmixedsolvem(), and alglib.densesolver.rmatrixsolvem().
static void alglib.densesolver.spdmatrixcholeskysolveinternal (double cha[,], double sqrtscalea, int n, bool isupper, double a[,], bool havea, double b[,], int m, ref int info, densesolverreport rep, ref double x[,]) inline static private
References alglib.ap.assert(), alglib.densesolver.densesolverreport.r1, alglib.rcond.rcondthreshold(), alglib.densesolver.densesolverreport.rinf, alglib.densesolver.spdbasiccholeskysolve(), alglib.rcond.spdmatrixcholeskyrcond(), and alglib.math.sqr().
Referenced by alglib.densesolver.spdmatrixcholeskysolvem(), and alglib.densesolver.spdmatrixsolvem().
static void alglib.densesolver.cmatrixlusolveinternal (complex lua[,], int[] p, double scalea, int n, complex a[,], bool havea, complex b[,], int m, ref int info, densesolverreport rep, ref complex x[,]) inline static private
References alglib.math.abscomplex(), alglib.ap.assert(), alglib.densesolver.cbasiclusolve(), alglib.rcond.cmatrixlurcond1(), alglib.rcond.cmatrixlurcondinf(), alglib.densesolver.densesolverrfsmax(), alglib.densesolver.densesolverreport.r1, alglib.rcond.rcondthreshold(), alglib.densesolver.densesolverreport.rinf, and alglib.xblas.xcdot().
Referenced by alglib.densesolver.cmatrixlusolvem(), alglib.densesolver.cmatrixmixedsolvem(), and alglib.densesolver.cmatrixsolvem().
static void alglib.densesolver.hpdmatrixcholeskysolveinternal (complex cha[,], double sqrtscalea, int n, bool isupper, complex a[,], bool havea, complex b[,], int m, ref int info, densesolverreport rep, ref complex x[,]) inline static private
References alglib.math.abscomplex(), alglib.ap.assert(), alglib.densesolver.hpdbasiccholeskysolve(), alglib.rcond.hpdmatrixcholeskyrcond(), alglib.densesolver.densesolverreport.r1, alglib.rcond.rcondthreshold(), alglib.densesolver.densesolverreport.rinf, and alglib.math.sqr().
Referenced by alglib.densesolver.hpdmatrixcholeskysolvem(), and alglib.densesolver.hpdmatrixsolvem().
static int alglib.densesolver.densesolverrfsmax (int n, double r1, double rinf) inline static private
Referenced by alglib.densesolver.cmatrixlusolveinternal(), alglib.densesolver.densesolverrfsmaxv2(), and alglib.densesolver.rmatrixlusolveinternal().
static int alglib.densesolver.densesolverrfsmaxv2 (int n, double r2) inline static private
References alglib.densesolver.densesolverrfsmax().
Referenced by alglib.densesolver.rmatrixsolvels().
static void alglib.densesolver.rbasiclusolve (double lua[,], int[] p, double scalea, int n, ref double[] xb, ref double[] tmp) inline static private
Referenced by alglib.densesolver.rmatrixlusolveinternal().
static void alglib.densesolver.spdbasiccholeskysolve (double cha[,], double sqrtscalea, int n, bool isupper, ref double[] xb, ref double[] tmp) inline static private
Referenced by alglib.densesolver.spdmatrixcholeskysolveinternal().
static void alglib.densesolver.cbasiclusolve (complex lua[,], int[] p, double scalea, int n, ref complex[] xb, ref complex[] tmp) inline static private
Referenced by alglib.densesolver.cmatrixlusolveinternal().
static void alglib.densesolver.hpdbasiccholeskysolve (complex cha[,], double sqrtscalea, int n, bool isupper, ref complex[] xb, ref complex[] tmp) inline static private
References alglib.math.conj().
Referenced by alglib.densesolver.hpdmatrixcholeskysolveinternal().
static void alglib.densesolver.rmatrixsolve (double a[,], int n, double[] b, ref int info, densesolverreport rep, ref double[] x) inline static
References alglib.densesolver.rmatrixsolvem().
static void alglib.densesolver.rmatrixsolvem (double a[,], int n, double b[,], int m, bool rfs, ref int info, densesolverreport rep, ref double x[,]) inline static
References alglib.trfac.rmatrixlu(), and alglib.densesolver.rmatrixlusolveinternal().
static void alglib.densesolver.rmatrixlusolve (double lua[,], int[] p, int n, double[] b, ref int info, densesolverreport rep, ref double[] x) inline static
References alglib.densesolver.rmatrixlusolvem().
static void alglib.densesolver.rmatrixlusolvem (double lua[,], int[] p, int n, double b[,], int m, ref int info, densesolverreport rep, ref double x[,]) inline static
References alglib.densesolver.rmatrixlusolveinternal().
static void alglib.densesolver.rmatrixmixedsolve (double a[,], double lua[,], int[] p, int n, double[] b, ref int info, densesolverreport rep, ref double[] x) inline static
References alglib.densesolver.rmatrixmixedsolvem().
static void alglib.densesolver.rmatrixmixedsolvem (double a[,], double lua[,], int[] p, int n, double b[,], int m, ref int info, densesolverreport rep, ref double x[,]) inline static
References alglib.densesolver.rmatrixlusolveinternal().
static void alglib.densesolver.cmatrixsolvem (complex a[,], int n, complex b[,], int m, bool rfs, ref int info, densesolverreport rep, ref complex x[,]) inline static
References alglib.math.abscomplex(), alglib.trfac.cmatrixlu(), and alglib.densesolver.cmatrixlusolveinternal().
static void alglib.densesolver.cmatrixsolve (complex a[,], int n, complex[] b, ref int info, densesolverreport rep, ref complex[] x) inline static
References alglib.densesolver.cmatrixsolvem().
static void alglib.densesolver.cmatrixlusolvem (complex lua[,], int[] p, int n, complex b[,], int m, ref int info, densesolverreport rep, ref complex x[,]) inline static
References alglib.math.abscomplex(), and alglib.densesolver.cmatrixlusolveinternal().
static void alglib.densesolver.cmatrixlusolve (complex lua[,], int[] p, int n, complex[] b, ref int info, densesolverreport rep, ref complex[] x) inline static
References alglib.densesolver.cmatrixlusolvem().
static void alglib.densesolver.cmatrixmixedsolvem (complex a[,], complex lua[,], int[] p, int n, complex b[,], int m, ref int info, densesolverreport rep, ref complex x[,]) inline static
References alglib.math.abscomplex(), and alglib.densesolver.cmatrixlusolveinternal().
static void alglib.densesolver.cmatrixmixedsolve (complex a[,], complex lua[,], int[] p, int n, complex[] b, ref int info, densesolverreport rep, ref complex[] x) inline static
References alglib.densesolver.cmatrixmixedsolvem().
static void alglib.densesolver.spdmatrixsolvem (double a[,], int n, bool isupper, double b[,], int m, ref int info, densesolverreport rep, ref double x[,]) inline static
References alglib.trfac.spdmatrixcholesky(), and alglib.densesolver.spdmatrixcholeskysolveinternal().
static void alglib.densesolver.spdmatrixsolve (double a[,], int n, bool isupper, double[] b, ref int info, densesolverreport rep, ref double[] x) inline static
References alglib.densesolver.spdmatrixsolvem().
static void alglib.densesolver.spdmatrixcholeskysolvem (double cha[,], int n, bool isupper, double b[,], int m, ref int info, densesolverreport rep, ref double x[,]) inline static
References alglib.densesolver.spdmatrixcholeskysolveinternal().
static void alglib.densesolver.spdmatrixcholeskysolve (double cha[,], int n, bool isupper, double[] b, ref int info, densesolverreport rep, ref double[] x) inline static
References alglib.densesolver.spdmatrixcholeskysolvem().
static void alglib.densesolver.hpdmatrixsolvem (complex a[,], int n, bool isupper, complex b[,], int m, ref int info, densesolverreport rep, ref complex x[,]) inline static
References alglib.math.abscomplex(), alglib.trfac.hpdmatrixcholesky(), and alglib.densesolver.hpdmatrixcholeskysolveinternal().
static void alglib.densesolver.hpdmatrixsolve (complex a[,], int n, bool isupper, complex[] b, ref int info, densesolverreport rep, ref complex[] x) inline static
References alglib.densesolver.hpdmatrixsolvem().
static void alglib.densesolver.hpdmatrixcholeskysolvem (complex cha[,], int n, bool isupper, complex b[,], int m, ref int info, densesolverreport rep, ref complex x[,]) inline static
References alglib.math.abscomplex(), and alglib.densesolver.hpdmatrixcholeskysolveinternal().
static void alglib.densesolver.hpdmatrixcholeskysolve (complex cha[,], int n, bool isupper, complex[] b, ref int info, densesolverreport rep, ref complex[] x) inline static
References alglib.densesolver.hpdmatrixcholeskysolvem().
static void alglib.densesolver.rmatrixsolvels (double a[,], int nrows, int ncols, double[] b, double threshold, ref int info, densesolverlsreport rep, ref double[] x) inline static
References alglib.densesolver.densesolverrfsmaxv2(), alglib.math.machineepsilon, alglib.svd.rmatrixsvd(), and alglib.xblas.xdot().
static void alglib.densesolver.rmatrixlusolveinternal (double lua[,], int[] p, double scalea, int n, double a[,], bool havea, double b[,], int m, ref int info, densesolverreport rep, ref double x[,]) inline static private
References alglib.ap.assert(), alglib.densesolver.densesolverrfsmax(), alglib.densesolver.rbasiclusolve(), alglib.rcond.rcondthreshold(), alglib.rcond.rmatrixlurcond1(), alglib.rcond.rmatrixlurcondinf(), and alglib.xblas.xdot().
static void alglib.densesolver.spdmatrixcholeskysolveinternal (double cha[,], double sqrtscalea, int n, bool isupper, double a[,], bool havea, double b[,], int m, ref int info, densesolverreport rep, ref double x[,]) inline static private
References alglib.ap.assert(), alglib.rcond.rcondthreshold(), alglib.densesolver.spdbasiccholeskysolve(), alglib.rcond.spdmatrixcholeskyrcond(), and alglib.math.sqr().
static void alglib.densesolver.cmatrixlusolveinternal (complex lua[,], int[] p, double scalea, int n, complex a[,], bool havea, complex b[,], int m, ref int info, densesolverreport rep, ref complex x[,]) inline static private
References alglib.math.abscomplex(), alglib.ap.assert(), alglib.densesolver.cbasiclusolve(), alglib.rcond.cmatrixlurcond1(), alglib.rcond.cmatrixlurcondinf(), alglib.densesolver.densesolverrfsmax(), alglib.rcond.rcondthreshold(), and alglib.xblas.xcdot().
static void alglib.densesolver.hpdmatrixcholeskysolveinternal (complex cha[,], double sqrtscalea, int n, bool isupper, complex a[,], bool havea, complex b[,], int m, ref int info, densesolverreport rep, ref complex x[,]) inline static private
References alglib.math.abscomplex(), alglib.ap.assert(), alglib.densesolver.hpdbasiccholeskysolve(), alglib.rcond.hpdmatrixcholeskyrcond(), alglib.rcond.rcondthreshold(), and alglib.math.sqr().
static int alglib.densesolver.densesolverrfsmax (int n, double r1, double rinf) inline static private
static int alglib.densesolver.densesolverrfsmaxv2 (int n, double r2) inline static private
References alglib.densesolver.densesolverrfsmax().
static void alglib.densesolver.rbasiclusolve (double lua[,], int[] p, double scalea, int n, ref double[] xb, ref double[] tmp) inline static private
static void alglib.densesolver.spdbasiccholeskysolve (double cha[,], double sqrtscalea, int n, bool isupper, ref double[] xb, ref double[] tmp) inline static private
static void alglib.densesolver.cbasiclusolve (complex lua[,], int[] p, double scalea, int n, ref complex[] xb, ref complex[] tmp) inline static private
static void alglib.densesolver.hpdbasiccholeskysolve (complex cha[,], double sqrtscalea, int n, bool isupper, ref complex[] xb, ref complex[] tmp) inline static private
References alglib.math.conj().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/solvers.cs