IGLib: NUnit.Framework.Has Class Reference
NUnit.Framework.Has Class Reference
Helper class with properties and methods that supply a number of constraints used in Asserts.
Static Public Member Functions
static ConstraintExpression Exactly (int expectedCount)
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding only if a specified number of them succeed.
static
ResolvableConstraintExpression Property (string name)
Returns a new PropertyConstraintExpression, which will either test for the existence of the named property on the object being tested or apply any following constraint to that property.
static
ResolvableConstraintExpression Attribute (Type expectedType)
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
static
ResolvableConstraintExpression Attribute< T > ()
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
static CollectionContainsConstraint Member (object expected)
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
Properties
static ConstraintExpression No [get]
Returns a ConstraintExpression that negates any following constraint.
static ConstraintExpression All [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them succeed.
static ConstraintExpression Some [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if at least one of them succeeds.
static ConstraintExpression None [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them fail.
static
ResolvableConstraintExpression Length [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Length property of the object being tested.
static
ResolvableConstraintExpression Count [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Count property of the object being tested.
static
ResolvableConstraintExpression Message [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Message property of the object being tested.
static
ResolvableConstraintExpression InnerException [get]
Returns a new ConstraintExpression, which will apply the following constraint to the InnerException property of the object being tested.
Detailed Description
Helper class with properties and methods that supply a number of constraints used in Asserts.
Member Function Documentation
static ConstraintExpression NUnit.Framework.Has.Exactly (int expectedCount) inline static
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding only if a specified number of them succeed.
References NUnit.Framework.Constraints.ConstraintExpression.Exactly().
Referenced by NUnit.Framework.Constraints.ConstraintFactory.Exactly(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyOneItemMatches(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyTwoItemsMatch(), and NUnit.Framework.Constraints.ExactCountConstraintTests.ZeroItemsMatch().
static ResolvableConstraintExpression NUnit.Framework.Has.Property (string name) inline static
Returns a new PropertyConstraintExpression, which will either test for the existence of the named property on the object being tested or apply any following constraint to that property.
References NUnit.Framework.Constraints.ConstraintExpression.Property().
Referenced by NUnit.Framework.Syntax.ArbitraryConstraintMatching.ApplyMatchesToProperty(), NUnit.Framework.Internal.Filters.NotFilterTests.BuildFromXml(), NUnit.Framework.Constraints.ToStringTests.CanDisplayPrefixConstraints_Resolved(), NUnit.Framework.Constraints.ToStringTests.CanDisplaySimpleConstraints_Resolved(), NUnit.Framework.Constraints.ToStringTests.CanDisplaySimpleConstraints_Unresolved(), NUnit.Framework.Constraints.ToStringTests.DisplayPrefixConstraints_Unresolved(), NUnit.Framework.Syntax.PropertySyntaxVariations.ExistenceTest(), NUnit.Framework.Constraints.ConstraintFactory.Property(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Syntax.PropertySyntaxVariations.SeparateConstraintTest(), NUnit.Framework.Syntax.PropertyExistsTest.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest_AndFollows.SetUp(), NUnit.Framework.Syntax.AfterTest_PropertyTest.SetUp(), NUnit.Framework.Syntax.PropertyTest_ConstraintFollows.SetUp(), NUnit.Framework.Syntax.PropertyTest_NotFollows.SetUp(), and NUnit.Framework.Syntax.OperatorPrecedenceTests.WithTests().
static ResolvableConstraintExpression NUnit.Framework.Has.Attribute (Type expectedType) inline static
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
References NUnit.Framework.Constraints.ConstraintExpression.Attribute().
Referenced by NUnit.Framework.Constraints.ConstraintFactory.Attribute(), NUnit.Framework.Constraints.AttributeExistsConstraintTests.AttributeTestPropertyValueOnMethodInfo(), NUnit.Framework.Constraints.ToStringTests.CanDisplaySimpleConstraints_Resolved(), NUnit.Framework.Constraints.ToStringTests.CanDisplaySimpleConstraints_Unresolved(), NUnit.Framework.Constraints.ToStringTests.DisplayPrefixConstraints_Unresolved(), NUnit.Framework.Syntax.AttributeTest.SetUp(), NUnit.Framework.Syntax.AttributeTestWithFollowingConstraint.SetUp(), and NUnit.Framework.Syntax.AttributeTest_Generic.SetUp().
static ResolvableConstraintExpression NUnit.Framework.Has.Attribute< T > () inline static
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
static CollectionContainsConstraint NUnit.Framework.Has.Member (object expected) inline static
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
Referenced by NUnit.Framework.Internal.PropertyBagTests.AllKeysAreListed(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.CollectionAssert.Contains(), NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.HasMemberTest(), NUnit.Framework.Syntax.AfterSyntaxUsingLambda.HasMemberTest(), NUnit.Framework.Internal.PropertyBagTests.SetAddsNewSingleValue(), NUnit.Framework.Syntax.CollectionContainsTest.SetUp(), and NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithMultipleTestCasesUsesCorrectNames().
Property Documentation
ConstraintExpression NUnit.Framework.Has.No static get
Returns a ConstraintExpression that negates any following constraint.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.CollectionAssert.DoesNotContain(), and NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests().
ConstraintExpression NUnit.Framework.Has.All static get
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them succeed.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), and NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests().
ConstraintExpression NUnit.Framework.Has.Some static get
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if at least one of them succeeds.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Syntax.SomeTest.SetUp(), NUnit.Framework.Syntax.SomeTest_BeforeBinaryOperators.SetUp(), NUnit.Framework.Syntax.SomeTest_NestedSome.SetUp(), NUnit.Framework.Syntax.SomeTest_UseOfAndSome.SetUp(), NUnit.Framework.Tests.AssertSyntaxTests.SomeItemTests(), and NUnit.Framework.Syntax.OperatorPrecedenceTests.SomeTests().
ConstraintExpression NUnit.Framework.Has.None static get
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them fail.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Tests.AssertSyntaxTests.NoItemTests(), NUnit.Framework.Syntax.NoneTest.SetUp(), and NUnit.Framework.Syntax.OperatorPrecedenceTests.SomeTests().
ResolvableConstraintExpression NUnit.Framework.Has.Length static get
Returns a new ConstraintExpression, which will apply the following constraint to the Length property of the object being tested.
Referenced by NUnit.Engine.Tests.RuntimeFrameworkTests.CanListAvailableFrameworks(), NUnit.Framework.Syntax.PropertySyntaxVariations.ExistenceTest(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Attributes.ApartmentAttributeTests.ChildFixtureRequiresMTA.RequiresMTAAtributeIsInheritable(), NUnit.Framework.Attributes.ApartmentAttributeTests.ChildFixtureRequiresSTA.RequiresSTAAtributeIsInheritable(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.ChildFixtureRequiresThread.RequiresThreadAttributeIsInheritable(), NUnit.Framework.Syntax.PropertySyntaxVariations.SeparateConstraintTest(), and NUnit.Framework.Syntax.LengthTest.SetUp().
ResolvableConstraintExpression NUnit.Framework.Has.Count static get
Returns a new ConstraintExpression, which will apply the following constraint to the Count property of the object being tested.
Referenced by NUnit.Framework.Syntax.ArbitraryConstraintMatching.ApplyMatchesToProperty(), NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfDelegateReturningList(), NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfList(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), and NUnit.Framework.Syntax.CountTest.SetUp().
ResolvableConstraintExpression NUnit.Framework.Has.Message static get
Returns a new ConstraintExpression, which will apply the following constraint to the Message property of the object being tested.
Referenced by NUnit.Framework.Syntax.MessageTest.SetUp().
ResolvableConstraintExpression NUnit.Framework.Has.InnerException static get
Returns a new ConstraintExpression, which will apply the following constraint to the InnerException property of the object being tested.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Has.cs