IGLib: NUnit.Framework.Internal.TestMethod Class Reference
NUnit.Framework.Internal.TestMethod Class Reference
The TestMethod class represents a Test implemented as a method.
Public Member Functions
TestMethod (IMethodInfo method)
Initializes a new instance of the TestMethod class.
TestMethod (IMethodInfo method, Test parentSuite)
Initializes a new instance of the TestMethod class.
override TestResult MakeTestResult ()
Overridden to return a TestCaseResult.
override TNode AddToXml (TNode parentNode, bool recursive)
Returns a TNode representing the current result after adding it as a child of the supplied parent node.
Public Member Functions inherited from NUnit.Framework.Internal.Test
void ApplyAttributesToTest (ICustomAttributeProvider provider)
Modify a newly constructed test by applying any of NUnit's common attributes, based on a supplied ICustomAttributeProvider, which is usually the reflection element from which the test was constructed, but may not be in some instances. The attributes retrieved are saved for use in subsequent operations.
TNode ToXml (bool recursive)
Returns the Xml representation of the test
int CompareTo (object obj)
Compares this test to another test for sorting purposes
Properties
override bool HasChildren [get]
Gets a bool indicating whether the current test has any descendant tests.
override IList< ITest > Tests [get]
Gets this test's child tests
override string XmlElementName [get]
Gets the name used for the top-level element in the XML representation of this test
override string MethodName [get]
Returns the name of the method
Properties inherited from NUnit.Framework.Internal.Test
string Id [get, set]
Gets or sets the id of the test
string Name [get, set]
Gets or sets the name of the test
string FullName [get, set]
Gets or sets the fully qualified name of the test
string ClassName [get]
Gets the name of the class containing this test. Returns null if the test is not associated with a class.
virtual string MethodName [get]
Gets the name of the method implementing this test. Returns null if the test is not implemented as a method.
ITypeInfo TypeInfo [get, private set]
Gets the TypeInfo of the fixture used in running this test or null if no fixture type is associated with it.
IMethodInfo Method [get, set]
Gets a MethodInfo for the method implementing this test. Returns null if the test is not implemented as a method.
RunState RunState [get, set]
Whether or not the test should be run
abstract string XmlElementName [get]
Gets the name used for the top-level element in the XML representation of this test
virtual string TestType [get]
Gets a string representing the type of test. Used as an attribute value in the XML representation of a test and has no other function in the framework.
virtual int TestCaseCount [get]
Gets a count of test cases represented by or contained under this test.
IPropertyBag Properties [get, private set]
Gets the properties for this test
bool IsSuite [get]
Returns true if this is a TestSuite
abstract bool HasChildren [get]
Gets a bool indicating whether the current test has any descendant tests.
ITest Parent [get, set]
Gets the parent as a Test object. Used by the core to set the parent.
abstract
System.Collections.Generic.IList
< ITest > Tests [get]
Gets this test's child tests
virtual object Fixture [get, set]
Gets or sets a fixture object for running this test.
static string IdPrefix [get, set]
Static prefix used for ids in this AppDomain. Set by FrameworkController.
int Seed [get, set]
Gets or Sets the Int value representing the seed for the RandomGenerator
Properties inherited from NUnit.Framework.Interfaces.ITest
string Id [get]
Gets the id of the test
string Name [get]
Gets the name of the test
string FullName [get]
Gets the fully qualified name of the test
string ClassName [get]
Gets the name of the class containing this test. Returns null if the test is not associated with a class.
string MethodName [get]
Gets the name of the method implementing this test. Returns null if the test is not implemented as a method.
ITypeInfo TypeInfo [get]
Gets the Type of the test fixture, if applicable, or null if no fixture type is associated with this test.
IMethodInfo Method [get]
Gets an IMethod for the method implementing this test. Returns null if the test is not implemented as a method.
RunState RunState [get]
Gets the RunState of the test, indicating whether it can be run.
int TestCaseCount [get]
Count of the test cases (1 if this is a test case)
IPropertyBag Properties [get]
Gets the properties of the test
ITest Parent [get]
Gets the parent test, if any.
bool IsSuite [get]
Returns true if this is a test suite
bool HasChildren [get]
Gets a bool indicating whether the current test has any descendant tests.
System.Collections.Generic.IList
< ITest > Tests [get]
Gets this test's child tests
object Fixture [get]
Gets a fixture object for running this test.
Additional Inherited Members
Protected Member Functions inherited from NUnit.Framework.Internal.Test
Test (string name)
Constructs a test given its name
Test (string pathName, string name)
Constructs a test given the path through the test hierarchy to its parent and a name.
Test (ITypeInfo typeInfo)
TODO: Documentation needed for constructor
Test (IMethodInfo method)
Construct a test from a MethodInfo
void PopulateTestNode (TNode thisNode, bool recursive)
Add standard attributes and members to a test node.
Protected Attributes inherited from NUnit.Framework.Internal.Test
MethodInfo[] setUpMethods
The SetUp methods.
MethodInfo[] tearDownMethods
The teardown methods
Detailed Description
The TestMethod class represents a Test implemented as a method.
Constructor & Destructor Documentation
NUnit.Framework.Internal.TestMethod.TestMethod (IMethodInfo method) inline
Initializes a new instance of the TestMethod class.
Parameters
method The method to be used as a test.
NUnit.Framework.Internal.TestMethod.TestMethod (IMethodInfo method, Test parentSuite) inline
Initializes a new instance of the TestMethod class.
Parameters
method The method to be used as a test.
parentSuite The suite or fixture to which the new test will be added
References NUnit.Framework.Internal.Test.FullName.
Member Function Documentation
override TestResult NUnit.Framework.Internal.TestMethod.MakeTestResult () inline virtual
Overridden to return a TestCaseResult.
Returns
A TestResult for this test.
Implements NUnit.Framework.Internal.Test.
Referenced by NUnit.Framework.Internal.TestResultTests.SetUp(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Failed(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Ignored(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Inconclusive(), and NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Passed().
override TNode NUnit.Framework.Internal.TestMethod.AddToXml (TNode parentNode, bool recursive) inline virtual
Returns a TNode representing the current result after adding it as a child of the supplied parent node.
Parameters
parentNode The parent node.
recursive If true, descendant results are included
Returns
Implements NUnit.Framework.Internal.Test.
References NUnit.Framework.Interfaces.TNode.AddAttribute(), and NUnit.Framework.Interfaces.TNode.AddElement().
Property Documentation
override bool NUnit.Framework.Internal.TestMethod.HasChildren get
Gets a bool indicating whether the current test has any descendant tests.
override IList<ITest> NUnit.Framework.Internal.TestMethod.Tests get
Gets this test's child tests
A list of child tests
override string NUnit.Framework.Internal.TestMethod.XmlElementName get
Gets the name used for the top-level element in the XML representation of this test
override string NUnit.Framework.Internal.TestMethod.MethodName get
Returns the name of the method
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Tests/TestMethod.cs