IGLib: CSharpScripter.FormMain Class Reference
CSharpScripter.FormMain Class Reference
Zusammenfassung für Form1.
Public Member Functions
FormMain ()
Protected Member Functions
override void Dispose (bool disposing)
Die verwendeten Ressourcen bereinigen.
Private Member Functions
void InitializeComponent ()
Erforderliche Methode für die Designerunterstützung. Der Inhalt der Methode darf nicht mit dem Code-Editor geändert werden.
void btnQuit_Click (object sender, System.EventArgs e)
void btnLoad_Click (object sender, System.EventArgs e)
void btnCompile_Click (object sender, System.EventArgs e)
void CheckErrors (CompilerErrorCollection cec)
void btnExecute_Click (object sender, System.EventArgs e)
byte[] loadFile (string filename)
Static Private Member Functions
static void Main ()
Der Haupteinstiegspunkt für die Anwendung.
Private Attributes
System.Windows.Forms.RichTextBox rtfCode
System.Windows.Forms.Button btnCompile
System.Windows.Forms.Button btnExecute
System.Windows.Forms.Button btnQuit
System.Windows.Forms.Button btnLoad
System.ComponentModel.Container components = null
Erforderliche Designervariable.
Detailed Description
Zusammenfassung für Form1.
Constructor & Destructor Documentation
CSharpScripter.FormMain.FormMain () inline
References CSharpScripter.FormMain.InitializeComponent().
Referenced by CSharpScripter.FormMain.Main().
Member Function Documentation
override void CSharpScripter.FormMain.Dispose (bool disposing) inline protected
Die verwendeten Ressourcen bereinigen.
References CSharpScripter.FormMain.components.
void CSharpScripter.FormMain.InitializeComponent () inline private
Erforderliche Methode für die Designerunterstützung. Der Inhalt der Methode darf nicht mit dem Code-Editor geändert werden.
Referenced by CSharpScripter.FormMain.FormMain().
static void CSharpScripter.FormMain.Main () inline static private
Der Haupteinstiegspunkt für die Anwendung.
References CSharpScripter.FormMain.FormMain().
void CSharpScripter.FormMain.btnQuit_Click (object sender, System.EventArgs e) inline private
void CSharpScripter.FormMain.btnLoad_Click (object sender, System.EventArgs e) inline private
References CSharpScripter.FormMain.rtfCode.
void CSharpScripter.FormMain.btnCompile_Click (object sender, System.EventArgs e) inline private
References CSharpScripter.FormMain.btnExecute, and CSharpScripter.FormMain.rtfCode.
void CSharpScripter.FormMain.CheckErrors (CompilerErrorCollection cec) inline private
void CSharpScripter.FormMain.btnExecute_Click (object sender, System.EventArgs e) inline private
References CSharpScripter.Command.Execute(), and CSharpScripter.FormMain.loadFile().
byte [] CSharpScripter.FormMain.loadFile (string filename) inline private
Referenced by CSharpScripter.FormMain.btnExecute_Click().
Member Data Documentation
System.Windows.Forms.RichTextBox CSharpScripter.FormMain.rtfCode private
Referenced by CSharpScripter.FormMain.btnCompile_Click(), and CSharpScripter.FormMain.btnLoad_Click().
System.Windows.Forms.Button CSharpScripter.FormMain.btnCompile private
System.Windows.Forms.Button CSharpScripter.FormMain.btnExecute private
Referenced by CSharpScripter.FormMain.btnCompile_Click().
System.Windows.Forms.Button CSharpScripter.FormMain.btnQuit private
System.Windows.Forms.Button CSharpScripter.FormMain.btnLoad private
System.ComponentModel.Container CSharpScripter.FormMain.components = null private
Erforderliche Designervariable.
Referenced by CSharpScripter.FormMain.Dispose().
The documentation for this class was generated from the following file:
igtest/test_iglib_tmp_CSharpScripter1_OLD_TO_DELETE/0000another_project/matheval/FormMain.cs