IGLib: Package IG.Forms
Package IG.Forms
Interface implemented by file viewers (usually GUI components).
Namespaces
package Properties
package Test
Classes
class AlignmentControl
Control for setting horizontal and vertical alignment of items.
class AlignmentControlOld
Control for adjusting alignment.
class AlignmentTestForm
Test form, used only to test if control can be inclded in the form..
class AppTestForms
Test application for forms. Usage: AppTestForms.Init().
class AssemblyInfoControl
class AssemblyInfoForm
class AssemblySelector
class BrowserSimpleControl
class BrowserSimpleForm
class BrowserSimpleWindow
class client_program
class ClientForm
class ClientMessages
class CompilerForm
class CompilerFormOld
class ConsoleForm
Console replacement.
class ControlManipulator
Performs various operations on the specified controls:
class ControlPropertyStore
Stores properties of a specified control, and restores them to on arbitrary controls.
class ControlViewerControl
class ControlViewerForm
Windows form (System.Windows.Forms.Form) that can launch and show arbitrary controls and can create them if necessary.
class CookingTimerControl
class CookingTimerForm
class DialogControl
Highly configurable interactive message box with custom buttons, message, and possibly editable text.
class DialogForm
class DialogFormDemoControl
class DialogFormDemoForm
class DirectorySelector
class DllSelector
class FadingMessage
Manages a fading message window. Windows containing a message are launched in separate threads, closing after a specified time.
class FadingMessageOld
Manages a fading message window. Windows containing a message are launched in separate threads, closing after a specified time.
class FileSelector
class FileViewerControl
class FileViewerForm
class FontEventArgs
EventArgs class that contains font information.
class FontSelectorSimple
Simple control that allows font selection.
class GraphAxisItem
Contains data and methods for manipulating a single axis item of a graph. Axis items manipulate axis labels and axis ticks.
class GraphBase
Graph data & control class.
class GraphBase1
An implementation of the things necessary for most ZedGraphDemos.
class GraphItem
class GraphLineItem
class GraphPlotItem
Representation of a plottable item contained in a graph.
class GraphWindow
class GraphWindowTemplate_Old
Form used for plots.
class HashControl
class HashForm
interface IClosableFromContainedForm
Marker interface indicating that a form can be closed from the contained control.
interface IFileViewer
class igforms_test
A strongly-typed resource class, for looking up localized strings, etc.
class ImageViewerControl
class ImageViewerForm
class IndexChangeEventArgs
Event arguments for events bearing information about an index (of type int) that has changed.
class IndicatorLight
class IndicatorLightTestControl
class IndicatorLightTestForm
class InpuOrOutputtDataDefinitionControl
Control for editing input or output data definitions (only one of these two at a time).
class InputDataDefinitionControl
Control for editing input or output data definitions (only one of these two at a time).
class InputOutputDataDefinitionControl
class InputOutputDataDefinitionForm
class InputParametersControl
Control for editing input parameter values.
class InputParameterSelectorMinMax
Selection of parameter to be varied, together with bounds - for parametric tests.
interface IReporterConsoleForm
interface IReporterFadeMessage
interface IReporterMessageBox
interface IReporterSpeech
class MathematicaCalculatorApp
class MathematicaCalculatorControl
class MessageBoxLauncher
An exemple form that launches various message boxes.
class NeuralInputControl
Control for editing input parameter values.
class NeuralInputParameterSelectorMinMax
Selection of parameter to be varied, together with bounds - for parametric tests.
class NeuralOutputValueSelector
Selection of the output value of interest in an ANN model.
class OutputValueSelector
Selection of the output value of interest in an ANN model.
class ReporterConf
Reporter configuration.
class ReporterConfigurationForm
Reporter configuration.
class ReporterConsoleMsgbox
class ReporterConsoleMsgbox_Base
Base class for reporter classes that contain either reporting via system console, reporting via message box, or both.
class ReporterForms
Reporting system that in particular utilizes forms. Beside the main delegates for assembling location and message strings, this class has three additional delegates for each kind of reporting (i.e. reporting with console consform, message box, fading message or console)
class ReporterMsgbox
class ReportMsg_Examples
class ResourceSelector
class ResourceViewerControl
class ResourceViewerForm
class ScalarFunctionEvaluatorControl
Control for test evaluation of scalar functions.
class ScalarFunctionEvaluatorForm
Control for test evaluation of scalar functions.
class ScalarFunctionScriptControl
Control for definition of scalar functions by user defined expressions (through a script loader).
class ScalarFunctionScriptForm
Window for definition of scalar functions by user defined expressions (through script loader).
class ScriptLoaderForm
class sendigence_test_form
class server_program
class ServerForm
class ServerMessages
class SoundPlayerControlSimple
class SoundPlayerFormSimple
class TestControl
Test control.
class TestForm
Test form.
class TestFormSandbox
class TestLayoutControl
class TestLayoutForm
class TestLoadableScriptInterpreter
class TestTcpClient
class TestTcpMultiThreadedServer
class TestTcpServer
class TestTestControl
class TimerControl
class TimerControlWorking
class TimerForm
class UtilForms
Various forms utilities.
class UtilResponseForms
Utilities that enable uniform behavior of response plotting forms.
class ValueChangeEventArgs
Event arguments for events bearing information about a value of type double that has changed.
class ValueChangeEventArgs< ValueType >
Event arguments for events bearing information about value that has changed.
class VectorFunctionPlotter1d
Form for training artificial neural networks.
class VectorFunctionPlotter1dForm
class VectorFunctionPlotter2d
Form for simple parametric tests (variation of selected parameter) performed on ANN models.
class VectorFunctionPlotter2dForm
class VectorFunctionScriptControl
class VectorFunctionScriptForm
class WindowPositioner
Takes care of windows positioning, relative of absolute to the screen and/or other windows.
class WindowPositionerControl
Control for testing window positioning.
class WindowPositionerForm
Windows form for testing window positioning./summary> $A Igor xx Oct09;
class WindowShiftControlNumeric
Control for setting window positions, relative positions, sizes, positions, shifts, etc.
class WindowShiftControlText
Control for setting window positions, relative positions, sizes, positions, shifts, etc.
class XMLTestPath
class XMLTestPathForm
class XMLTreeView
Summary description for XMLTreeView.
class XmlTreeViewControl
class XmlTreeViewForm
class XMLTreeViewFormOld_Keep_Some_time
Summary description for XMLTreeView.
Functions
delegate void SelectedIdEventHandler (int oldId, int newId)
Delegate for events that are triggered when ID of hte selected object changes.
delegate void ValueChangedEventHandler (double oldValue, double newValue)
Delegate for events that are triggered when ID of hte selected object changes.
delegate void VoidDelegate ()
Summary description for FaidMessage1.
delegate void FormDelegate (Form f)
Reference to a function without arguments & return value.
delegate void ControlDelegate (Control ct)
delegate void FontEventHandler (object sender, FontEventArgs args)
EventArgs type for font related events, contains a font object.
Detailed Description
Interface implemented by file viewers (usually GUI components).
Function Documentation
delegate void IG.Forms.SelectedIdEventHandler (int oldId, int newId)
Delegate for events that are triggered when ID of hte selected object changes.
Parameters
oldId Old ID.
newId New ID.
delegate void IG.Forms.ValueChangedEventHandler (double oldValue, double newValue)
Delegate for events that are triggered when ID of hte selected object changes.
Parameters
oldId Old value.
newId New value.
delegate void IG.Forms.VoidDelegate ()
Summary description for FaidMessage1.
Referenced by IG.Forms.FadingMessageOld.CloseForm(), IG.Sendigence.ConsoleForm.CloseForm(), IG.Forms.ConsoleForm.CloseForm(), IG.Forms.FadingMessage.CloseForm(), IG.Forms.ReporterConf.CloseForm(), IG.Forms.ReporterConfigurationForm.CloseForm(), IG.Sendigence.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.FinalizeReading(), IG.Sendigence.ConsoleForm.HideInput(), IG.Forms.ConsoleForm.HideInput(), IG.Forms.XmlTreeViewControl.LoadFileToListBox(), IG.Forms.XMLTreeView.LoadFileToListBox(), IG.Forms.XMLTreeViewFormOld_Keep_Some_time.LoadFileToListBox(), IG.Forms.XmlTreeViewControl.LoadFileToTextBox(), IG.Forms.XMLTreeView.LoadFileToTextBox(), IG.Forms.XMLTreeViewFormOld_Keep_Some_time.LoadFileToTextBox(), IG.Forms.XmlTreeViewControl.ParseFileToTreeView(), IG.Forms.XMLTreeView.ParseFileToTreeView(), IG.Forms.XMLTreeViewFormOld_Keep_Some_time.ParseFileToTreeView(), IG.Sendigence.ConsoleForm.PrepareForReading(), IG.Forms.ConsoleForm.PrepareForReading(), IG.Sendigence.ConsoleForm.Read(), IG.Forms.ConsoleForm.Read(), IG.Sendigence.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadDouble(), IG.Sendigence.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLine(), IG.Sendigence.ConsoleForm.ReadLong(), IG.Forms.ConsoleForm.ReadLong(), IG.Sendigence.ConsoleForm.ReadString(), IG.Forms.ConsoleForm.ReadString(), IG.Sendigence.ConsoleForm.ShowInput(), IG.Forms.ConsoleForm.ShowInput(), IG.Forms.ConsoleForm.UpdateOutSettings(), IG.Forms.ConsoleForm.UpdateSettings(), IG.Sendigence.ConsoleForm.WriteOutput(), and IG.Forms.ConsoleForm.WriteOutput().
delegate void IG.Forms.FormDelegate (Form f)
Reference to a function without arguments & return value.
delegate void IG.Forms.ControlDelegate (Control ct)
Referenced by IG.Forms.ReporterConf.ConsoleForm_Load(), IG.Forms.ReporterConfigurationForm.ConsoleForm_Load(), IG.Forms.FadingMessageOld.FadeMessage_Load(), IG.Forms.FadingMessage.FadeMessage_Load(), and IG.Forms.ReporterConf.ReporterConf_Load().
delegate void IG.Forms.FontEventHandler (object sender, FontEventArgs args)
EventArgs type for font related events, contains a font object.
Parameters
sender Object that trigered event.
args Event argumets that contain the related font object.