IGLib: alglib.ftbase Class Reference
alglib.ftbase Class Reference
Classes
class fasttransformplan
class ftplan
Static Public Member Functions
static void ftbasegeneratecomplexfftplan (int n, ftplan plan)
static void ftbasegeneraterealfftplan (int n, ftplan plan)
static void ftbasegeneraterealfhtplan (int n, ftplan plan)
static void ftbaseexecuteplan (ref double[] a, int aoffset, int n, ftplan plan)
static void ftbaseexecuteplanrec (ref double[] a, int aoffset, ftplan plan, int entryoffset, int stackptr)
static void ftbasefactorize (int n, int tasktype, ref int n1, ref int n2)
static bool ftbaseissmooth (int n)
static int ftbasefindsmooth (int n)
static int ftbasefindsmootheven (int n)
static double ftbasegetflopestimate (int n)
static void ftcomplexfftplan (int n, int k, fasttransformplan plan)
static void ftapplyplan (fasttransformplan plan, double[] a, int offsa, int repcnt)
static void ftbasefactorize (int n, int tasktype, ref int n1, ref int n2)
static bool ftbaseissmooth (int n)
static int ftbasefindsmooth (int n)
static int ftbasefindsmootheven (int n)
static double ftbasegetflopestimate (int n)
Public Attributes
const int ftbaseplanentrysize = 8
const int ftbasecffttask = 0
const int ftbaserfhttask = 1
const int ftbaserffttask = 2
const int fftcooleytukeyplan = 0
const int fftbluesteinplan = 1
const int fftcodeletplan = 2
const int fhtcooleytukeyplan = 3
const int fhtcodeletplan = 4
const int fftrealcooleytukeyplan = 5
const int fftemptyplan = 6
const int fhtn2plan = 999
const int ftbaseupdatetw = 4
const int ftbasecodeletrecommended = 5
const double ftbaseinefficiencyfactor = 1.3
const int ftbasemaxsmoothfactor = 5
const int coltype = 0
const int coloperandscnt = 1
const int coloperandsize = 2
const int colmicrovectorsize = 3
const int colparam0 = 4
const int colparam1 = 5
const int colparam2 = 6
const int colparam3 = 7
const int colscnt = 8
const int opend = 0
const int opcomplexreffft = 1
const int opbluesteinsfft = 2
const int opcomplexcodeletfft = 3
const int opcomplexcodelettwfft = 4
const int opradersfft = 5
const int opcomplextranspose = -1
const int opcomplexfftfactors = -2
const int opstart = -3
const int opjmp = -4
const int opparallelcall = -5
const int maxradix = 6
const int updatetw = 16
const int recursivethreshold = 1024
const int raderthreshold = 19
Static Private Member Functions
static void ftbasegenerateplanrec (int n, int tasktype, ftplan plan, ref int plansize, ref int precomputedsize, ref int planarraysize, ref int tmpmemsize, ref int stackmemsize, int stackptr)
static void ftbaseprecomputeplanrec (ftplan plan, int entryoffset, int stackptr)
static void ffttwcalc (ref double[] a, int aoffset, int n1, int n2)
static void internalcomplexlintranspose (ref double[] a, int m, int n, int astart, ref double[] buf)
static void internalreallintranspose (ref double[] a, int m, int n, int astart, ref double[] buf)
static void ffticltrec (ref double[] a, int astart, int astride, ref double[] b, int bstart, int bstride, int m, int n)
static void fftirltrec (ref double[] a, int astart, int astride, ref double[] b, int bstart, int bstride, int m, int n)
static void ftbasefindsmoothrec (int n, int seed, int leastfactor, ref int best)
static void fftarrayresize (ref int[] a, ref int asize, int newasize)
static void reffht (ref double[] a, int n, int offs)
static void ftdeterminespacerequirements (int n, ref int precrsize, ref int precisize)
static void ftcomplexfftplanrec (int n, int k, bool childplan, bool topmostplan, ref int rowptr, ref int bluesteinsize, ref int precrptr, ref int preciptr, fasttransformplan plan)
static void ftpushentry (fasttransformplan plan, ref int rowptr, int etype, int eopcnt, int eopsize, int emcvsize, int eparam0)
static void ftpushentry2 (fasttransformplan plan, ref int rowptr, int etype, int eopcnt, int eopsize, int emcvsize, int eparam0, int eparam1)
static void ftpushentry4 (fasttransformplan plan, ref int rowptr, int etype, int eopcnt, int eopsize, int emcvsize, int eparam0, int eparam1, int eparam2, int eparam3)
static void ftapplysubplan (fasttransformplan plan, int subplan, double[] a, int abase, int aoffset, double[] buf, int repcnt)
static void ftapplycomplexreffft (double[] a, int offs, int operandscnt, int operandsize, int microvectorsize, double[] buf)
static void ftapplycomplexcodeletfft (double[] a, int offs, int operandscnt, int operandsize, int microvectorsize)
static void ftapplycomplexcodelettwfft (double[] a, int offs, int operandscnt, int operandsize, int microvectorsize)
static void ftprecomputebluesteinsfft (int n, int m, double[] precr, int offs)
static void ftbluesteinsfft (fasttransformplan plan, double[] a, int abase, int aoffset, int operandscnt, int n, int m, int precoffs, int subplan, double[] bufa, double[] bufb, double[] bufc, double[] bufd)
static void ftprecomputeradersfft (int n, int rq, int riq, double[] precr, int offs)
static void ftradersfft (fasttransformplan plan, double[] a, int abase, int aoffset, int operandscnt, int n, int subplan, int rq, int riq, int precoffs, double[] buf)
static void ftfactorize (int n, bool isroot, ref int n1, ref int n2)
static int ftoptimisticestimate (int n)
static void ffttwcalc (double[] a, int aoffset, int n1, int n2)
static void internalcomplexlintranspose (double[] a, int m, int n, int astart, double[] buf)
static void ffticltrec (double[] a, int astart, int astride, double[] b, int bstart, int bstride, int m, int n)
static void fftirltrec (ref double[] a, int astart, int astride, ref double[] b, int bstart, int bstride, int m, int n)
static void ftbasefindsmoothrec (int n, int seed, int leastfactor, ref int best)
Member Function Documentation
static void alglib.ftbase.ftbasegeneratecomplexfftplan (int n, ftplan plan) inline static
References alglib.ap.assert(), alglib.ftbase.ftbasegenerateplanrec(), alglib.ftbase.ftbaseprecomputeplanrec(), alglib.ftbase.ftplan.plan, alglib.ftbase.ftplan.precomputed, alglib.ftbase.ftplan.stackbuf, and alglib.ftbase.ftplan.tmpbuf.
Referenced by alglib.conv.convc1dcircularinv(), alglib.conv.convc1dinv(), alglib.conv.convc1dx(), alglib.conv.convr1dcircularinv(), alglib.conv.convr1dinv(), alglib.conv.convr1dx(), alglib.fft.fftc1d(), alglib.fft.fftr1d(), and alglib.testfftunit.testfft().
static void alglib.ftbase.ftbasegeneraterealfftplan (int n, ftplan plan) inline static
References alglib.ap.assert(), alglib.ftbase.ftbasegenerateplanrec(), alglib.ftbase.ftbaseprecomputeplanrec(), alglib.ftbase.ftplan.plan, alglib.ftbase.ftplan.precomputed, alglib.ftbase.ftplan.stackbuf, and alglib.ftbase.ftplan.tmpbuf.
static void alglib.ftbase.ftbasegeneraterealfhtplan (int n, ftplan plan) inline static
References alglib.ap.assert(), alglib.ftbase.ftbasegenerateplanrec(), alglib.ftbase.ftbaseprecomputeplanrec(), alglib.ftbase.ftplan.plan, alglib.ftbase.ftplan.precomputed, alglib.ftbase.ftplan.stackbuf, and alglib.ftbase.ftplan.tmpbuf.
static void alglib.ftbase.ftbaseexecuteplan (ref double[] a, int aoffset, int n, ftplan plan) inline static
References alglib.ftbase.ftbaseexecuteplanrec().
Referenced by alglib.conv.convc1dcircularinv(), alglib.conv.convc1dinv(), alglib.conv.convc1dx(), alglib.fft.fftc1d(), alglib.fft.fftr1d(), and alglib.fft.fftr1dinternaleven().
static void alglib.ftbase.ftbaseexecuteplanrec (ref double[] a, int aoffset, ftplan plan, int entryoffset, int stackptr) inline static
References alglib.ftbase.ffttwcalc(), alglib.ftbase.internalcomplexlintranspose(), alglib.ftbase.internalreallintranspose(), alglib.ftbase.ftplan.plan, alglib.ftbase.ftplan.precomputed, alglib.ftbase.reffht(), alglib.ftbase.ftplan.stackbuf, and alglib.ftbase.ftplan.tmpbuf.
Referenced by alglib.ftbase.ftbaseexecuteplan(), and alglib.ftbase.ftbaseprecomputeplanrec().
static void alglib.ftbase.ftbasefactorize (int n, int tasktype, ref int n1, ref int n2) inline static
Referenced by alglib.ftbase.ftbasegenerateplanrec().
static bool alglib.ftbase.ftbaseissmooth (int n) inline static
References alglib.ftbase.ftbasemaxsmoothfactor.
Referenced by alglib.conv.convc1dx(), and alglib.conv.convr1dx().
static int alglib.ftbase.ftbasefindsmooth (int n) inline static
References alglib.ftbase.ftbasefindsmoothrec().
Referenced by alglib.conv.convc1dinv(), alglib.conv.convc1dx(), alglib.ftbase.ftbasegenerateplanrec(), alglib.ftbase.ftcomplexfftplanrec(), and alglib.ftbase.ftdeterminespacerequirements().
static int alglib.ftbase.ftbasefindsmootheven (int n) inline static
References alglib.ftbase.ftbasefindsmoothrec().
Referenced by alglib.conv.convr1dinv(), and alglib.conv.convr1dx().
static double alglib.ftbase.ftbasegetflopestimate (int n) inline static
Referenced by alglib.conv.convc1dx(), and alglib.conv.convr1dx().
static void alglib.ftbase.ftbasegenerateplanrec (int n, int tasktype, ftplan plan, ref int plansize, ref int precomputedsize, ref int planarraysize, ref int tmpmemsize, ref int stackmemsize, int stackptr) inline static private
References alglib.ftbase.fftarrayresize(), alglib.ftbase.fftbluesteinplan, alglib.ftbase.fftcodeletplan, alglib.ftbase.fftcooleytukeyplan, alglib.ftbase.fftemptyplan, alglib.ftbase.fftrealcooleytukeyplan, alglib.ftbase.fhtcodeletplan, alglib.ftbase.fhtcooleytukeyplan, alglib.ftbase.fhtn2plan, alglib.ftbase.ftbasefactorize(), alglib.ftbase.ftbasefindsmooth(), alglib.ftbase.ftbaseplanentrysize, and alglib.ftbase.ftplan.plan.
Referenced by alglib.ftbase.ftbasegeneratecomplexfftplan(), alglib.ftbase.ftbasegeneraterealfftplan(), and alglib.ftbase.ftbasegeneraterealfhtplan().
static void alglib.ftbase.ftbaseprecomputeplanrec (ftplan plan, int entryoffset, int stackptr) inline static private
References alglib.ftbase.ftbaseexecuteplanrec(), alglib.ftbase.ftplan.plan, alglib.ftbase.ftplan.precomputed, and alglib.math.sqr().
Referenced by alglib.ftbase.ftbasegeneratecomplexfftplan(), alglib.ftbase.ftbasegeneraterealfftplan(), and alglib.ftbase.ftbasegeneraterealfhtplan().
static void alglib.ftbase.ffttwcalc (ref double[] a, int aoffset, int n1, int n2) inline static private
References alglib.math.sqr().
Referenced by alglib.ftbase.ftapplysubplan(), and alglib.ftbase.ftbaseexecuteplanrec().
static void alglib.ftbase.internalcomplexlintranspose (ref double[] a, int m, int n, int astart, ref double[] buf) inline static private
References alglib.ftbase.ffticltrec().
Referenced by alglib.ftbase.ftapplysubplan(), and alglib.ftbase.ftbaseexecuteplanrec().
static void alglib.ftbase.internalreallintranspose (ref double[] a, int m, int n, int astart, ref double[] buf) inline static private
References alglib.ftbase.fftirltrec().
Referenced by alglib.ftbase.ftbaseexecuteplanrec().
static void alglib.ftbase.ffticltrec (ref double[] a, int astart, int astride, ref double[] b, int bstart, int bstride, int m, int n) inline static private
References alglib.ap.assert().
Referenced by alglib.ftbase.internalcomplexlintranspose().
static void alglib.ftbase.fftirltrec (ref double[] a, int astart, int astride, ref double[] b, int bstart, int bstride, int m, int n) inline static private
References alglib.ap.assert().
Referenced by alglib.ftbase.internalreallintranspose().
static void alglib.ftbase.ftbasefindsmoothrec (int n, int seed, int leastfactor, ref int best) inline static private
References alglib.ap.assert().
Referenced by alglib.ftbase.ftbasefindsmooth(), and alglib.ftbase.ftbasefindsmootheven().
static void alglib.ftbase.fftarrayresize (ref int[] a, ref int asize, int newasize) inline static private
Referenced by alglib.ftbase.ftbasegenerateplanrec().
static void alglib.ftbase.reffht (ref double[] a, int n, int offs) inline static private
References alglib.ap.assert().
Referenced by alglib.ftbase.ftbaseexecuteplanrec().
static void alglib.ftbase.ftcomplexfftplan (int n, int k, fasttransformplan plan) inline static
References alglib.smp.ae_shared_pool_set_seed(), alglib.ap.assert(), alglib.ftbase.fasttransformplan.bluesteinpool, alglib.ftbase.fasttransformplan.buffer, alglib.ftbase.ftcomplexfftplanrec(), alglib.ftbase.ftdeterminespacerequirements(), alglib.ftbase.fasttransformplan.preci, and alglib.ftbase.fasttransformplan.precr.
Referenced by alglib.conv.convc1dcircularinv(), alglib.conv.convc1dinv(), alglib.conv.convc1dx(), alglib.conv.convr1dcircularinv(), alglib.conv.convr1dinv(), alglib.conv.convr1dx(), alglib.fft.fftc1d(), alglib.fft.fftr1d(), and alglib.testfftunit.testfft().
static void alglib.ftbase.ftapplyplan (fasttransformplan plan, double[] a, int offsa, int repcnt) inline static
References alglib.ftbase.fasttransformplan.buffer, alglib.ftbase.colmicrovectorsize, alglib.ftbase.coloperandscnt, alglib.ftbase.coloperandsize, alglib.ftbase.fasttransformplan.entries, and alglib.ftbase.ftapplysubplan().
Referenced by alglib.conv.convc1dcircularinv(), alglib.conv.convc1dinv(), alglib.conv.convc1dx(), alglib.fft.fftc1d(), alglib.fft.fftr1d(), and alglib.fft.fftr1dinternaleven().
static void alglib.ftbase.ftbasefactorize (int n, int tasktype, ref int n1, ref int n2) inline static
static bool alglib.ftbase.ftbaseissmooth (int n) inline static
References alglib.ftbase.ftbasemaxsmoothfactor.
static int alglib.ftbase.ftbasefindsmooth (int n) inline static
References alglib.ftbase.ftbasefindsmoothrec().
static int alglib.ftbase.ftbasefindsmootheven (int n) inline static
References alglib.ftbase.ftbasefindsmoothrec().
static double alglib.ftbase.ftbasegetflopestimate (int n) inline static
static void alglib.ftbase.ftdeterminespacerequirements (int n, ref int precrsize, ref int precisize) inline static private
References alglib.ftbase.ftbasefindsmooth(), and alglib.ftbase.maxradix.
Referenced by alglib.ftbase.ftcomplexfftplan().
static void alglib.ftbase.ftcomplexfftplanrec (int n, int k, bool childplan, bool topmostplan, ref int rowptr, ref int bluesteinsize, ref int precrptr, ref int preciptr, fasttransformplan plan) inline static private
References alglib.ap.assert(), alglib.ftbase.colparam0, alglib.ftbase.fasttransformplan.entries, alglib.ntheory.findprimitiverootandinverse(), alglib.ftbase.ftbasefindsmooth(), alglib.ftbase.ftfactorize(), alglib.ftbase.ftoptimisticestimate(), alglib.ftbase.ftprecomputebluesteinsfft(), alglib.ftbase.ftprecomputeradersfft(), alglib.ftbase.ftpushentry(), alglib.ftbase.ftpushentry2(), alglib.ftbase.ftpushentry4(), and alglib.ftbase.fasttransformplan.precr.
Referenced by alglib.ftbase.ftcomplexfftplan().
static void alglib.ftbase.ftpushentry (fasttransformplan plan, ref int rowptr, int etype, int eopcnt, int eopsize, int emcvsize, int eparam0) inline static private
References alglib.ftbase.ftpushentry2().
Referenced by alglib.ftbase.ftcomplexfftplanrec().
static void alglib.ftbase.ftpushentry2 (fasttransformplan plan, ref int rowptr, int etype, int eopcnt, int eopsize, int emcvsize, int eparam0, int eparam1) inline static private
References alglib.ftbase.colmicrovectorsize, alglib.ftbase.coloperandscnt, alglib.ftbase.coloperandsize, alglib.ftbase.colparam0, alglib.ftbase.colparam1, alglib.ftbase.colparam2, alglib.ftbase.colparam3, alglib.ftbase.coltype, alglib.ftbase.fasttransformplan.entries, and alglib.apserv.imatrixresize().
Referenced by alglib.ftbase.ftcomplexfftplanrec(), and alglib.ftbase.ftpushentry().
static void alglib.ftbase.ftpushentry4 (fasttransformplan plan, ref int rowptr, int etype, int eopcnt, int eopsize, int emcvsize, int eparam0, int eparam1, int eparam2, int eparam3) inline static private
References alglib.ftbase.colmicrovectorsize, alglib.ftbase.coloperandscnt, alglib.ftbase.coloperandsize, alglib.ftbase.colparam0, alglib.ftbase.colparam1, alglib.ftbase.colparam2, alglib.ftbase.colparam3, alglib.ftbase.coltype, alglib.ftbase.fasttransformplan.entries, and alglib.apserv.imatrixresize().
Referenced by alglib.ftbase.ftcomplexfftplanrec().
static void alglib.ftbase.ftapplysubplan (fasttransformplan plan, int subplan, double[] a, int abase, int aoffset, double[] buf, int repcnt) inline static private
References alglib.ap.assert(), alglib.ftbase.fasttransformplan.bluesteinpool, alglib.ftbase.colmicrovectorsize, alglib.ftbase.coloperandscnt, alglib.ftbase.coloperandsize, alglib.ftbase.colparam0, alglib.ftbase.colparam1, alglib.ftbase.coltype, alglib.ftbase.fasttransformplan.entries, alglib.ftbase.ffttwcalc(), alglib.ftbase.ftapplycomplexcodeletfft(), alglib.ftbase.ftapplycomplexcodelettwfft(), alglib.ftbase.ftapplycomplexreffft(), alglib.ftbase.ftbluesteinsfft(), alglib.ftbase.ftradersfft(), alglib.ftbase.internalcomplexlintranspose(), and alglib.apserv.touchint().
Referenced by alglib.ftbase.ftapplyplan().
static void alglib.ftbase.ftapplycomplexreffft (double[] a, int offs, int operandscnt, int operandsize, int microvectorsize, double[] buf) inline static private
References alglib.ap.assert().
Referenced by alglib.ftbase.ftapplysubplan().
static void alglib.ftbase.ftapplycomplexcodeletfft (double[] a, int offs, int operandscnt, int operandsize, int microvectorsize) inline static private
References alglib.ap.assert().
Referenced by alglib.ftbase.ftapplysubplan().
static void alglib.ftbase.ftapplycomplexcodelettwfft (double[] a, int offs, int operandscnt, int operandsize, int microvectorsize) inline static private
Referenced by alglib.ftbase.ftapplysubplan().
static void alglib.ftbase.ftprecomputebluesteinsfft (int n, int m, double[] precr, int offs) inline static private
Referenced by alglib.ftbase.ftcomplexfftplanrec().
static void alglib.ftbase.ftbluesteinsfft (fasttransformplan plan, double[] a, int abase, int aoffset, int operandscnt, int n, int m, int precoffs, int subplan, double[] bufa, double[] bufb, double[] bufc, double[] bufd) inline static private
Referenced by alglib.ftbase.ftapplysubplan().
static void alglib.ftbase.ftprecomputeradersfft (int n, int rq, int riq, double[] precr, int offs) inline static private
Referenced by alglib.ftbase.ftcomplexfftplanrec().
static void alglib.ftbase.ftradersfft (fasttransformplan plan, double[] a, int abase, int aoffset, int operandscnt, int n, int subplan, int rq, int riq, int precoffs, double[] buf) inline static private
Referenced by alglib.ftbase.ftapplysubplan().
static void alglib.ftbase.ftfactorize (int n, bool isroot, ref int n1, ref int n2) inline static private
Referenced by alglib.ftbase.ftcomplexfftplanrec().
static int alglib.ftbase.ftoptimisticestimate (int n) inline static private
Referenced by alglib.ftbase.ftcomplexfftplanrec().
static void alglib.ftbase.ffttwcalc (double[] a, int aoffset, int n1, int n2) inline static private
static void alglib.ftbase.internalcomplexlintranspose (double[] a, int m, int n, int astart, double[] buf) inline static private
static void alglib.ftbase.ffticltrec (double[] a, int astart, int astride, double[] b, int bstart, int bstride, int m, int n) inline static private
static void alglib.ftbase.fftirltrec (ref double[] a, int astart, int astride, ref double[] b, int bstart, int bstride, int m, int n) inline static private
References alglib.ap.assert().
static void alglib.ftbase.ftbasefindsmoothrec (int n, int seed, int leastfactor, ref int best) inline static private
References alglib.ap.assert().
Member Data Documentation
const int alglib.ftbase.ftbaseplanentrysize = 8
Referenced by alglib.ftbase.ftbasegenerateplanrec().
const int alglib.ftbase.ftbasecffttask = 0
const int alglib.ftbase.ftbaserfhttask = 1
const int alglib.ftbase.ftbaserffttask = 2
const int alglib.ftbase.fftcooleytukeyplan = 0
Referenced by alglib.ftbase.ftbasegenerateplanrec().
const int alglib.ftbase.fftbluesteinplan = 1
Referenced by alglib.ftbase.ftbasegenerateplanrec().
const int alglib.ftbase.fftcodeletplan = 2
Referenced by alglib.ftbase.ftbasegenerateplanrec().
const int alglib.ftbase.fhtcooleytukeyplan = 3
Referenced by alglib.ftbase.ftbasegenerateplanrec().
const int alglib.ftbase.fhtcodeletplan = 4
Referenced by alglib.ftbase.ftbasegenerateplanrec().
const int alglib.ftbase.fftrealcooleytukeyplan = 5
Referenced by alglib.ftbase.ftbasegenerateplanrec().
const int alglib.ftbase.fftemptyplan = 6
Referenced by alglib.ftbase.ftbasegenerateplanrec().
const int alglib.ftbase.fhtn2plan = 999
Referenced by alglib.ftbase.ftbasegenerateplanrec().
const int alglib.ftbase.ftbaseupdatetw = 4
const int alglib.ftbase.ftbasecodeletrecommended = 5
const double alglib.ftbase.ftbaseinefficiencyfactor = 1.3
const int alglib.ftbase.ftbasemaxsmoothfactor = 5
Referenced by alglib.ftbase.ftbaseissmooth().
const int alglib.ftbase.coltype = 0
Referenced by alglib.ftbase.ftapplysubplan(), alglib.ftbase.ftpushentry2(), and alglib.ftbase.ftpushentry4().
const int alglib.ftbase.coloperandscnt = 1
Referenced by alglib.ftbase.ftapplyplan(), alglib.ftbase.ftapplysubplan(), alglib.ftbase.ftpushentry2(), and alglib.ftbase.ftpushentry4().
const int alglib.ftbase.coloperandsize = 2
Referenced by alglib.ftbase.ftapplyplan(), alglib.ftbase.ftapplysubplan(), alglib.ftbase.ftpushentry2(), and alglib.ftbase.ftpushentry4().
const int alglib.ftbase.colmicrovectorsize = 3
Referenced by alglib.ftbase.ftapplyplan(), alglib.ftbase.ftapplysubplan(), alglib.ftbase.ftpushentry2(), and alglib.ftbase.ftpushentry4().
const int alglib.ftbase.colparam0 = 4
Referenced by alglib.ftbase.ftapplysubplan(), alglib.ftbase.ftcomplexfftplanrec(), alglib.ftbase.ftpushentry2(), and alglib.ftbase.ftpushentry4().
const int alglib.ftbase.colparam1 = 5
Referenced by alglib.ftbase.ftapplysubplan(), alglib.ftbase.ftpushentry2(), and alglib.ftbase.ftpushentry4().
const int alglib.ftbase.colparam2 = 6
Referenced by alglib.ftbase.ftpushentry2(), and alglib.ftbase.ftpushentry4().
const int alglib.ftbase.colparam3 = 7
Referenced by alglib.ftbase.ftpushentry2(), and alglib.ftbase.ftpushentry4().
const int alglib.ftbase.colscnt = 8
const int alglib.ftbase.opend = 0
const int alglib.ftbase.opcomplexreffft = 1
const int alglib.ftbase.opbluesteinsfft = 2
const int alglib.ftbase.opcomplexcodeletfft = 3
const int alglib.ftbase.opcomplexcodelettwfft = 4
const int alglib.ftbase.opradersfft = 5
const int alglib.ftbase.opcomplextranspose = -1
const int alglib.ftbase.opcomplexfftfactors = -2
const int alglib.ftbase.opstart = -3
const int alglib.ftbase.opjmp = -4
const int alglib.ftbase.opparallelcall = -5
const int alglib.ftbase.maxradix = 6
Referenced by alglib.ftbase.ftdeterminespacerequirements().
const int alglib.ftbase.updatetw = 16
const int alglib.ftbase.recursivethreshold = 1024
const int alglib.ftbase.raderthreshold = 19
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/alglibinternal.cs