IGLib: NUnit.Framework.Constraints.NUnitEqualityComparer Class Reference
NUnit.Framework.Constraints.NUnitEqualityComparer Class Reference
NUnitEqualityComparer encapsulates NUnit's handling of equality tests between objects.
Classes
class FailurePoint
FailurePoint class represents one point of failure in an equality test.
Public Member Functions
bool AreEqual (object x, object y, ref Tolerance tolerance)
Compares two objects for equality within a tolerance.
Properties
static NUnitEqualityComparer Default [get]
Returns the default NUnitEqualityComparer
bool IgnoreCase [get, set]
Gets and sets a flag indicating whether case should be ignored in determining equality.
bool CompareAsCollection [get, set]
Gets and sets a flag indicating that arrays should be compared as collections, without regard to their shape.
IList< EqualityAdapter > ExternalComparers [get]
Gets the list of external comparers to be used to test for equality. They are applied to members of collections, in place of NUnit's own logic.
IList< FailurePoint > FailurePoints [get]
Gets the list of failure points for the last Match performed. The list consists of objects to be interpreted by the caller. This generally means that the caller may only make use of objects it has placed on the list at a particular depthy.
bool WithSameOffset [get, set]
Flags the comparer to include DateTimeOffset.Offset property in comparison of two DateTimeOffset values.
Private Member Functions
EqualityAdapter GetExternalComparer (object x, object y)
bool ArraysEqual (Array x, Array y, ref Tolerance tolerance)
Helper method to compare two arrays
bool DictionariesEqual (IDictionary x, IDictionary y, ref Tolerance tolerance)
bool DictionaryEntriesEqual (DictionaryEntry x, DictionaryEntry y, ref Tolerance tolerance)
bool CollectionsEqual (ICollection x, ICollection y, ref Tolerance tolerance)
bool StringsEqual (string x, string y)
bool CharsEqual (char x, char y)
bool EnumerablesEqual (IEnumerable x, IEnumerable y, ref Tolerance tolerance)
bool StreamsEqual (Stream x, Stream y)
Static Private Member Functions
static bool FirstImplementsIEquatableOfSecond (Type first, Type second)
static IList< Type > GetEquatableGenericArguments (Type type)
static bool InvokeFirstIEquatableEqualsSecond (object first, object second)
static MethodInfo GetCorrectGenericEqualsMethod (Type first, Type second)
static bool DirectoriesEqual (DirectoryInfo x, DirectoryInfo y)
Method to compare two DirectoryInfo objects
Private Attributes
bool caseInsensitive
If true, all string comparisons will ignore case
bool compareAsCollection
If true, arrays will be treated as collections, allowing those of different dimensions to be compared
List< EqualityAdapter > externalComparers = new List<EqualityAdapter>()
Comparison objects used in comparisons for some constraints.
List< FailurePoint > failurePoints
List of points at which a failure occurred.
Static Private Attributes
static readonly int BUFFER_SIZE = 4096
Detailed Description
NUnitEqualityComparer encapsulates NUnit's handling of equality tests between objects.
Member Function Documentation
bool NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual (object x, object y, ref Tolerance tolerance) inline
Compares two objects for equality within a tolerance.
Referenced by NUnit.Framework.Constraints.EqualConstraint.ApplyTo< TActual >(), NUnit.Framework.Constraints.EqualityComparerTests.CanCompareArrayContainingSelfToSelf(), NUnit.Framework.Constraints.EqualityComparerTests.DifferentDirectoriesAreNotEqual(), NUnit.Framework.Constraints.EqualityComparerTests.EqualItems(), NUnit.Framework.Constraints.EqualityComparerTests.IEnumeratorIsDisposed(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableDifferentTypesSuccess_WhenActualImplementsIEquatable(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableDifferentTypesSuccess_WhenExpectedImplementsIEquatable(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableHasPrecedenceOverDefaultEquals(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableSuccess(), NUnit.Framework.Constraints.EqualityComparerTests.ReferenceEqualityHasPrecedenceOverIEquatable(), NUnit.Framework.Constraints.EqualityComparerTests.SameDirectoriesAreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.SpecialFloatingPointValuesCompareAsEqual(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestToleranceDefault(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestToleranceExact(), and NUnit.Framework.Constraints.EqualityComparerTests.UnequalItems().
static bool NUnit.Framework.Constraints.NUnitEqualityComparer.FirstImplementsIEquatableOfSecond (Type first, Type second) inline static private
static IList<Type> NUnit.Framework.Constraints.NUnitEqualityComparer.GetEquatableGenericArguments (Type type) inline static private
static bool NUnit.Framework.Constraints.NUnitEqualityComparer.InvokeFirstIEquatableEqualsSecond (object first, object second) inline static private
static MethodInfo NUnit.Framework.Constraints.NUnitEqualityComparer.GetCorrectGenericEqualsMethod (Type first, Type second) inline static private
EqualityAdapter NUnit.Framework.Constraints.NUnitEqualityComparer.GetExternalComparer (object x, object y) inline private
References NUnit.Framework.Constraints.EqualityAdapter.CanCompare().
bool NUnit.Framework.Constraints.NUnitEqualityComparer.ArraysEqual (Array x, Array y, ref Tolerance tolerance) inline private
Helper method to compare two arrays
bool NUnit.Framework.Constraints.NUnitEqualityComparer.DictionariesEqual (IDictionary x, IDictionary y, ref Tolerance tolerance) inline private
References NUnit.Framework.Constraints.CollectionTally.Count, and NUnit.Framework.Constraints.CollectionTally.TryRemove().
bool NUnit.Framework.Constraints.NUnitEqualityComparer.DictionaryEntriesEqual (DictionaryEntry x, DictionaryEntry y, ref Tolerance tolerance) inline private
References NUnit.Framework.Constraints.Tolerance.Exact.
bool NUnit.Framework.Constraints.NUnitEqualityComparer.CollectionsEqual (ICollection x, ICollection y, ref Tolerance tolerance) inline private
References NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.ActualHasData, NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.ActualValue, NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.ExpectedHasData, NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.ExpectedValue, and NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.Position.
bool NUnit.Framework.Constraints.NUnitEqualityComparer.StringsEqual (string x, string y) inline private
bool NUnit.Framework.Constraints.NUnitEqualityComparer.CharsEqual (char x, char y) inline private
bool NUnit.Framework.Constraints.NUnitEqualityComparer.EnumerablesEqual (IEnumerable x, IEnumerable y, ref Tolerance tolerance) inline private
References NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.ActualHasData, NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.ActualValue, NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.ExpectedHasData, NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.ExpectedValue, and NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.Position.
static bool NUnit.Framework.Constraints.NUnitEqualityComparer.DirectoriesEqual (DirectoryInfo x, DirectoryInfo y) inline static private
Method to compare two DirectoryInfo objects
Parameters
x first directory to compare
y second directory to compare
Returns
true if equivalent, false if not
bool NUnit.Framework.Constraints.NUnitEqualityComparer.StreamsEqual (Stream x, Stream y) inline private
References NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.ActualHasData, NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.ActualValue, NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.ExpectedHasData, NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.ExpectedValue, and NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoint.Position.
Member Data Documentation
bool NUnit.Framework.Constraints.NUnitEqualityComparer.caseInsensitive private
If true, all string comparisons will ignore case
bool NUnit.Framework.Constraints.NUnitEqualityComparer.compareAsCollection private
If true, arrays will be treated as collections, allowing those of different dimensions to be compared
List<EqualityAdapter> NUnit.Framework.Constraints.NUnitEqualityComparer.externalComparers = new List<EqualityAdapter>() private
Comparison objects used in comparisons for some constraints.
List<FailurePoint> NUnit.Framework.Constraints.NUnitEqualityComparer.failurePoints private
List of points at which a failure occurred.
readonly int NUnit.Framework.Constraints.NUnitEqualityComparer.BUFFER_SIZE = 4096 static private
Property Documentation
NUnitEqualityComparer NUnit.Framework.Constraints.NUnitEqualityComparer.Default static get
Returns the default NUnitEqualityComparer
bool NUnit.Framework.Constraints.NUnitEqualityComparer.IgnoreCase get set
Gets and sets a flag indicating whether case should be ignored in determining equality.
bool NUnit.Framework.Constraints.NUnitEqualityComparer.CompareAsCollection get set
Gets and sets a flag indicating that arrays should be compared as collections, without regard to their shape.
IList<EqualityAdapter> NUnit.Framework.Constraints.NUnitEqualityComparer.ExternalComparers get
Gets the list of external comparers to be used to test for equality. They are applied to members of collections, in place of NUnit's own logic.
Referenced by NUnit.Framework.Constraints.EqualConstraint.Using(), and NUnit.Framework.Constraints.EqualConstraint.Using< T >().
IList<FailurePoint> NUnit.Framework.Constraints.NUnitEqualityComparer.FailurePoints get
Gets the list of failure points for the last Match performed. The list consists of objects to be interpreted by the caller. This generally means that the caller may only make use of objects it has placed on the list at a particular depthy.
bool NUnit.Framework.Constraints.NUnitEqualityComparer.WithSameOffset get set
Flags the comparer to include DateTimeOffset.Offset property in comparison of two DateTimeOffset values.
Using this modifier does not allow to use the Tolerance modifier.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/NUnitEqualityComparer.cs