IGLib: NUnit.Framework.Constraints.ConstraintResult Class Reference
NUnit.Framework.Constraints.ConstraintResult Class Reference
Contain the result of matching a Constraint against an actual value.
Public Member Functions
ConstraintResult (IConstraint constraint, object actualValue)
Constructs a ConstraintResult for a particular Constraint.
ConstraintResult (IConstraint constraint, object actualValue, ConstraintStatus status)
Constructs a ConstraintResult for a particular Constraint.
ConstraintResult (IConstraint constraint, object actualValue, bool isSuccess)
Constructs a ConstraintResult for a particular Constraint.
virtual void WriteMessageTo (MessageWriter writer)
Write the failure message to the MessageWriter provided as an argument. The default implementation simply passes the result and the actual value to the writer, which then displays the constraint description and the value.
virtual void WriteActualValueTo (MessageWriter writer)
Write the actual value for a failing constraint test to a MessageWriter. The default implementation simply writes the raw value of actual, leaving it to the writer to perform any formatting.
Properties
object ActualValue [get, private set]
The actual value that was passed to the Constraint.ApplyTo{TActual}(TActual) method.
ConstraintStatus Status [get, set]
Gets and sets the ResultStatus for this result.
virtual bool IsSuccess [get]
True if actual value meets the Constraint criteria otherwise false.
string Name [get, private set]
Display friendly name of the constraint.
string Description [get, private set]
Description of the constraint may be affected by the state the constraint had when Constraint.ApplyTo{TActual}(TActual) was performed against the actual value.
Detailed Description
Contain the result of matching a Constraint against an actual value.
Constructor & Destructor Documentation
NUnit.Framework.Constraints.ConstraintResult.ConstraintResult (IConstraint constraint, object actualValue) inline
Constructs a ConstraintResult for a particular Constraint.
Parameters
constraint The Constraint to which this result applies.
actualValue The actual value to which the Constraint was applied.
References NUnit.Framework.Constraints.IConstraint.Description, and NUnit.Framework.Constraints.IConstraint.DisplayName.
NUnit.Framework.Constraints.ConstraintResult.ConstraintResult (IConstraint constraint, object actualValue, ConstraintStatus status) inline
Constructs a ConstraintResult for a particular Constraint.
Parameters
constraint The Constraint to which this result applies.
actualValue The actual value to which the Constraint was applied.
status The status of the new ConstraintResult.
NUnit.Framework.Constraints.ConstraintResult.ConstraintResult (IConstraint constraint, object actualValue, bool isSuccess) inline
Constructs a ConstraintResult for a particular Constraint.
Parameters
constraint The Constraint to which this result applies.
actualValue The actual value to which the Constraint was applied.
isSuccess If true, applies a status of Success to the result, otherwise Failure.
Member Function Documentation
virtual void NUnit.Framework.Constraints.ConstraintResult.WriteMessageTo (MessageWriter writer) inline virtual
Write the failure message to the MessageWriter provided as an argument. The default implementation simply passes the result and the actual value to the writer, which then displays the constraint description and the value.
Constraints that need to provide additional details, such as where the error occured can override this.
Parameters
writer The MessageWriter on which to display the message
Reimplemented in NUnit.Framework.Constraints.EqualConstraintResult.
References NUnit.Framework.Constraints.MessageWriter.DisplayDifferences().
virtual void NUnit.Framework.Constraints.ConstraintResult.WriteActualValueTo (MessageWriter writer) inline virtual
Write the actual value for a failing constraint test to a MessageWriter. The default implementation simply writes the raw value of actual, leaving it to the writer to perform any formatting.
Parameters
writer The writer on which the actual value is displayed
Reimplemented in NUnit.Framework.Constraints.ThrowsConstraint.ThrowsConstraintResult, NUnit.Framework.Constraints.AndConstraint.AndConstraintResult, NUnit.Framework.Constraints.ThrowsExceptionConstraint.ThrowsExceptionConstraintResult, and NUnit.Framework.Constraints.ExceptionTypeConstraint.ExceptionTypeConstraintResult.
References NUnit.Framework.Constraints.MessageWriter.WriteActualValue().
Referenced by NUnit.Framework.Internal.TextMessageWriter.WriteActualLine(), and NUnit.Framework.Constraints.AndConstraint.AndConstraintResult.WriteActualValueTo().
Property Documentation
object NUnit.Framework.Constraints.ConstraintResult.ActualValue get private set
The actual value that was passed to the Constraint.ApplyTo{TActual}(TActual) method.
ConstraintStatus NUnit.Framework.Constraints.ConstraintResult.Status get set
Gets and sets the ResultStatus for this result.
Referenced by NUnit.Framework.Constraints.AttributeExistsConstraint.ApplyTo< TActual >().
virtual bool NUnit.Framework.Constraints.ConstraintResult.IsSuccess get
True if actual value meets the Constraint criteria otherwise false.
Referenced by NUnit.Framework.Constraints.DelayedConstraint.ApplyTo< TActual >(), NUnit.Framework.Constraints.ThrowsConstraint.ThrowsConstraintResult.ThrowsConstraintResult(), and NUnit.Framework.Constraints.AndConstraint.AndConstraintResult.WriteActualValueTo().
string NUnit.Framework.Constraints.ConstraintResult.Name get private set
Display friendly name of the constraint.
string NUnit.Framework.Constraints.ConstraintResult.Description get private set
Description of the constraint may be affected by the state the constraint had when Constraint.ApplyTo{TActual}(TActual) was performed against the actual value.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/ConstraintResult.cs