IGLib: NUnit.Framework.Assume Class Reference
NUnit.Framework.Assume Class Reference
Provides static methods to express the assumptions that must be met for a test to give a meaningful result. If an assumption is not met, the test should produce an inconclusive result.
Static Public Member Functions
static new bool Equals (object a, object b)
The Equals method throws an AssertionException. This is done to make sure there is no mistake by calling this function.
static new void ReferenceEquals (object a, object b)
override the default ReferenceEquals to throw an AssertionException. This implementation makes sure there is no mistake in calling this function as part of Assert.
static void That< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an InconclusiveException on failure.
static void That< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr, string message, params object[] args)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an InconclusiveException on failure.
static void That (bool condition, string message, params object[] args)
Asserts that a condition is true. If the condition is false the method throws an InconclusiveException.
static void That (bool condition)
Asserts that a condition is true. If the condition is false the method throws an InconclusiveException.
static void That (Func< bool > condition, string message, params object[] args)
Asserts that a condition is true. If the condition is false the method throws an InconclusiveException.
static void That (Func< bool > condition)
Asserts that a condition is true. If the condition is false the method throws an InconclusiveException.
static void That (TestDelegate code, IResolveConstraint constraint)
Asserts that the code represented by a delegate throws an exception that satisfies the constraint provided.
static void That< TActual > (TActual actual, IResolveConstraint expression)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an InconclusiveException on failure.
static void That< TActual > (TActual actual, IResolveConstraint expression, string message, params object[] args)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an InconclusiveException on failure.
Detailed Description
Provides static methods to express the assumptions that must be met for a test to give a meaningful result. If an assumption is not met, the test should produce an inconclusive result.
Member Function Documentation
static new bool NUnit.Framework.Assume.Equals (object a, object b) inline static
The Equals method throws an AssertionException. This is done to make sure there is no mistake by calling this function.
Parameters
a
b
static new void NUnit.Framework.Assume.ReferenceEquals (object a, object b) inline static
override the default ReferenceEquals to throw an AssertionException. This implementation makes sure there is no mistake in calling this function as part of Assert.
Parameters
a
b
static void NUnit.Framework.Assume.That< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr) inline static
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an InconclusiveException on failure.
Parameters
expr A Constraint expression to be applied
del An ActualValueDelegate returning the value to be tested
static void NUnit.Framework.Assume.That< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr, string message, params object[] args) inline static
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an InconclusiveException on failure.
Parameters
del An ActualValueDelegate returning the value to be tested
expr A Constraint expression to be applied
message The message that will be displayed on failure
args Arguments to be used in formatting the message
static void NUnit.Framework.Assume.That (bool condition, string message, params object[] args) inline static
Asserts that a condition is true. If the condition is false the method throws an InconclusiveException.
Parameters
condition The evaluated condition
message The message to display if the condition is false
args Arguments to be used in formatting the message
Referenced by NUnit.Framework.Tests.ActionAttributeTests.ActionsWrappingParameterizedMethodSuite(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndArraySegment(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndEmptyArraySegment(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraySegmentAndArray(), NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.AssumeSomething(), NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.AssumeSomethingElse(), NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.AssumeTheWorldIsFlat(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualLambdaAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualLambdaAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualLambdaAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_Boolean(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_BooleanLambda(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_BooleanLambdaWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_BooleanLambdaWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_BooleanWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_BooleanWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_DelegateAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_DelegateAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_DelegateAndConstraintWithMessageAndArgs(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanCreateUsingClrVersion(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanCreateUsingClrVersion(), NUnit.Framework.Constraints.ReusableConstraintTests.CanReuseReusableConstraintMultipleTimes(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_FirstChildIsXmlDeclaration(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_FirstChildIsXmlDeclaration(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_SecondChildIsComment(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_SecondChildIsComment(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_ThirdChildIsTestResults(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_ThirdChildIsTestResults(), NUnit.Framework.Assertions.ArrayEqualsFixture.EmptyArraySegmentAndArray(), NUnit.Engine.Services.Tests.ExtensionServiceTests.ExtensionsAreAddedToExtensionPoint(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_Boolean(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanLambda(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanLambdaWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanLambdaWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraintWithMessageAndArgs(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTest(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTestWithinToleranceAndWithSameOffset(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTestWithTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTestWithToleranceAndWithSameOffset(), NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.NeverAssume(), NUnit.Framework.Constraints.EmptyDirectoryConstraintTest.NotEmptyDirectory(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.PositiveEqualityTest(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.PositiveEqualityTestWithTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.PositiveEqualityTestWithToleranceAndWithSameOffset(), NUnit.Engine.Services.Tests.RuntimeFrameworkServiceTests.SelectRuntimeFramework(), NUnit.ConsoleRunner.Tests.ColorConsoleTests.SetUp(), NUnit.Framework.Assertions.DirectoryAssertTests.SetUp(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.SetUp(), NUnit.TestData.DatapointFixture.SquareRootTest.SqrtTimesItselfGivesOriginal(), NUnit.Framework.Attributes.TheoryTests.SqrtTests.SqrtTimesItselfGivesOriginal(), NUnit.Framework.Attributes.TheoryTests.SquareRootTest(), NUnit.TestUtilities.TestDirectory.TestDirectory(), NUnit.TestData.TheoryFixture.TheoryFixture.TestWithAllBadValues(), NUnit.Framework.Assume.That(), NUnit.Framework.Assume.That< TActual >(), NUnit.Framework.Assertions.ArrayEqualsFixture.TwoArraySegments(), and NUnit.Framework.Assertions.ArrayEqualsFixture.TwoEmptyArraySegments().
static void NUnit.Framework.Assume.That (bool condition) inline static
Asserts that a condition is true. If the condition is false the method throws an InconclusiveException.
Parameters
condition The evaluated condition
References NUnit.Framework.Assume.That(), and NUnit.Framework.Is.True.
static void NUnit.Framework.Assume.That (Func< bool > condition, string message, params object[] args) inline static
Asserts that a condition is true. If the condition is false the method throws an InconclusiveException.
Parameters
condition A lambda that returns a Boolean
message The message to display if the condition is false
args Arguments to be used in formatting the message
static void NUnit.Framework.Assume.That (Func< bool > condition) inline static
Asserts that a condition is true. If the condition is false the method throws an InconclusiveException.
Parameters
condition A lambda that returns a Boolean
References NUnit.Framework.Assume.That(), and NUnit.Framework.Is.True.
static void NUnit.Framework.Assume.That (TestDelegate code, IResolveConstraint constraint) inline static
Asserts that the code represented by a delegate throws an exception that satisfies the constraint provided.
Parameters
code A TestDelegate to be executed
constraint A ThrowsConstraint used in the test
References NUnit.Framework.Assume.That().
static void NUnit.Framework.Assume.That< TActual > (TActual actual, IResolveConstraint expression) inline static
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an InconclusiveException on failure.
Parameters
expression A Constraint to be applied
actual The actual value to test
References NUnit.Framework.Assume.That().
static void NUnit.Framework.Assume.That< TActual > (TActual actual, IResolveConstraint expression, string message, params object[] args) inline static
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an InconclusiveException on failure.
Parameters
expression A Constraint expression to be applied
actual The actual value to test
message The message that will be displayed on failure
args Arguments to be used in formatting the message
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Assume.cs