IGLib: NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests Class Reference
NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests Class Reference
Public Member Functions
void ConvertEngineResultToXml ()
void Document_HasThreeChildren ()
void Document_FirstChildIsXmlDeclaration ()
void Document_SecondChildIsComment ()
void Document_ThirdChildIsTestResults ()
void Document_HasTestResults ()
void TestResults_AssemblyPathIsCorrect ()
void TestResults_CounterIsCorrect (string name, int count)
void TestResults_HasValidDateAttribute ()
void TestResults_HasValidTimeAttribute ()
void Environment_HasEnvironmentElement ()
void Environment_HasRequiredAttribute (string name)
void CultureInfo_HasCultureInfoElement ()
void CultureInfo_HasRequiredAttribute (string name)
void TestFixture_ExpectedAttribute (string name, string value)
void TestFixture_HasValidTimeAttribute ()
void TestFixture_ResultIsFailure ()
void TestFixture_SuccessIsFalse ()
void TestFixture_HasCategoryElement ()
void TestFixture_HasPropertyElement ()
void TestCase_ResultIsSuccess ()
void TestCase_ExecutedIsTrue ()
void TestCase_HasCategoryElement ()
void TestCase_HasPropertyElement ()
void TestCase_CategoryElementsDoNotContainProperties ()
void TestCase_PropertyElementsDoNotContainCategories ()
void InvalidTestCase_HasFailedResult ()
Public Member Functions inherited from NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest
void InitializeTestEngineResult ()
Private Member Functions
string RequiredAttribute (XmlNode node, string name)
Private Attributes
XmlDocument _doc
XmlNode _topNode
XmlNode _envNode
XmlNode _cultureNode
XmlNode _fixtureNode
XmlNode _testCaseNode
XmlNode _invalidTestCaseNode
Additional Inherited Members
Protected Member Functions inherited from NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest
string GetLocalPath (string fileName)
Protected Attributes inherited from NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest
const string AssemblyName = "mock-nunit-assembly.exe"
Properties inherited from NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest
TestEngineResult EngineResult [get, private set]
string AssemblyPath [get, private set]
Member Function Documentation
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.ConvertEngineResultToXml () inline
References NUnit.Engine.ServiceContext.Add(), NUnit.Engine.Services.ResultService.GetResultWriter(), NUnit.Framework.Assert.NotNull(), and NUnit.Engine.ServiceContext.ServiceManager.
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_HasThreeChildren () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_FirstChildIsXmlDeclaration () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_SecondChildIsComment () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_ThirdChildIsTestResults () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_HasTestResults () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestResults_AssemblyPathIsCorrect () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestResults_CounterIsCorrect (string name, int count) inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestResults_HasValidDateAttribute () inline
References NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestResults_HasValidTimeAttribute () inline
References NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Environment_HasEnvironmentElement () inline
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Environment_HasRequiredAttribute (string name) inline
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.CultureInfo_HasCultureInfoElement () inline
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.CultureInfo_HasRequiredAttribute (string name) inline
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_ExpectedAttribute (string name, string value) inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_HasValidTimeAttribute () inline
References NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_ResultIsFailure () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_SuccessIsFalse () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_HasCategoryElement () inline
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_HasPropertyElement () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_ResultIsSuccess () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_ExecutedIsTrue () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_HasCategoryElement () inline
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_HasPropertyElement () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_CategoryElementsDoNotContainProperties () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_PropertyElementsDoNotContainCategories () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
void NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.InvalidTestCase_HasFailedResult () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
string NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.RequiredAttribute (XmlNode node, string name) inline private
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
Member Data Documentation
XmlDocument NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests._doc private
XmlNode NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests._topNode private
XmlNode NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests._envNode private
XmlNode NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests._cultureNode private
XmlNode NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests._fixtureNode private
XmlNode NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests._testCaseNode private
XmlNode NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests._invalidTestCaseNode private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/ResultWriters/NUnit2XmlResultWriterTests.cs