IGLib: alglib.testfftunit Class Reference
alglib.testfftunit Class Reference
Static Public Member Functions
static bool testfft (bool silent)
static bool testfft (bool silent)
static bool _pexec_testfft (bool silent)
Static Private Member Functions
static void reffftc1d (ref complex[] a, int n)
static void reffftc1dinv (ref complex[] a, int n)
static void refinternalcfft (ref double[] a, int nn, bool inversefft)
static void refinternalrfft (double[] a, int nn, ref complex[] f)
static void reffftc1d (ref complex[] a, int n)
static void reffftc1dinv (ref complex[] a, int n)
static void refinternalcfft (ref double[] a, int nn, bool inversefft)
static void refinternalrfft (double[] a, int nn, ref complex[] f)
static void quicktest (int n, ref double referr, ref double refrerr)
Member Function Documentation
static bool alglib.testfftunit.testfft (bool silent) inline static
References alglib.math.abscomplex(), alglib.fft.fftc1d(), alglib.fft.fftc1dinv(), alglib.fft.fftr1d(), alglib.fft.fftr1dinternaleven(), alglib.fft.fftr1dinv(), alglib.fft.fftr1dinvinternaleven(), alglib.ftbase.ftbasegeneratecomplexfftplan(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.testfftunit.reffftc1d(), alglib.testfftunit.reffftc1dinv(), alglib.testfftunit.refinternalrfft(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testfftunit._pexec_testfft(), and _Test.Main().
static void alglib.testfftunit.reffftc1d (ref complex[] a, int n) inline static private
References alglib.ap.assert(), and alglib.testfftunit.refinternalcfft().
Referenced by alglib.testfftunit.testfft().
static void alglib.testfftunit.reffftc1dinv (ref complex[] a, int n) inline static private
References alglib.ap.assert(), and alglib.testfftunit.refinternalcfft().
Referenced by alglib.testfftunit.testfft().
static void alglib.testfftunit.refinternalcfft (ref double[] a, int nn, bool inversefft) inline static private
Referenced by alglib.testfftunit.reffftc1d(), alglib.testfftunit.reffftc1dinv(), and alglib.testfftunit.refinternalrfft().
static void alglib.testfftunit.refinternalrfft (double[] a, int nn, ref complex[] f) inline static private
References alglib.testfftunit.refinternalcfft(), and alglib.complex.x.
Referenced by alglib.testfftunit.testfft().
static bool alglib.testfftunit.testfft (bool silent) inline static
References alglib.math.abscomplex(), alglib.fft.fftc1d(), alglib.fft.fftc1dinv(), alglib.fft.fftr1d(), alglib.fft.fftr1dinternaleven(), alglib.fft.fftr1dinv(), alglib.fft.fftr1dinvinternaleven(), alglib.ftbase.ftcomplexfftplan(), alglib.math.machineepsilon, alglib.testfftunit.quicktest(), alglib.math.randomreal(), alglib.testfftunit.reffftc1d(), alglib.testfftunit.reffftc1dinv(), alglib.testfftunit.refinternalrfft(), alglib.complex.x, and alglib.complex.y.
static bool alglib.testfftunit._pexec_testfft (bool silent) inline static
References alglib.testfftunit.testfft().
Referenced by _Test.Main().
static void alglib.testfftunit.reffftc1d (ref complex[] a, int n) inline static private
References alglib.ap.assert(), and alglib.testfftunit.refinternalcfft().
static void alglib.testfftunit.reffftc1dinv (ref complex[] a, int n) inline static private
References alglib.ap.assert(), and alglib.testfftunit.refinternalcfft().
static void alglib.testfftunit.refinternalcfft (ref double[] a, int nn, bool inversefft) inline static private
static void alglib.testfftunit.refinternalrfft (double[] a, int nn, ref complex[] f) inline static private
References alglib.testfftunit.refinternalcfft(), and alglib.complex.x.
static void alglib.testfftunit.quicktest (int n, ref double referr, ref double refrerr) inline static private
References alglib.math.abscomplex(), alglib.fft.fftc1d(), alglib.fft.fftc1dinv(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testfftunit.testfft().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs