IGLib: alglib.testmlpbaseunit Class Reference
alglib.testmlpbaseunit Class Reference
Static Public Member Functions
static bool testmlpbase (bool silent)
static bool _pexec_testmlpbase (bool silent)
Static Private Member Functions
static double vectordiff (double[] g0, double[] g1, int n, double s)
static void createnetwork (mlpbase.multilayerperceptron network, int nkind, double a1, double a2, int nin, int nhid1, int nhid2, int nout)
static void unsetnetwork (mlpbase.multilayerperceptron network)
static void testinformational (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err)
static void testprocessing (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err)
static void testgradient (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, int sizemin, int sizemax, ref bool err)
static void testhessian (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err)
static void testerr (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, int sizemin, int sizemax, ref bool err)
static void spectests (ref bool inferrors, ref bool procerrors, ref bool graderrors, ref bool hesserrors, ref bool errerrors)
static bool testmlpgbsubset ()
Member Function Documentation
static bool alglib.testmlpbaseunit.testmlpbase (bool silent) inline static
References alglib.testmlpbaseunit.spectests(), alglib.testmlpbaseunit.testerr(), alglib.testmlpbaseunit.testgradient(), alglib.testmlpbaseunit.testhessian(), alglib.testmlpbaseunit.testinformational(), alglib.testmlpbaseunit.testmlpgbsubset(), and alglib.testmlpbaseunit.testprocessing().
Referenced by alglib.testmlpbaseunit._pexec_testmlpbase(), and _Test.Main().
static bool alglib.testmlpbaseunit._pexec_testmlpbase (bool silent) inline static
References alglib.testmlpbaseunit.testmlpbase().
Referenced by _Test.Main().
static double alglib.testmlpbaseunit.vectordiff (double[] g0, double[] g1, int n, double s) inline static private
References alglib.math.sqr().
Referenced by alglib.testmlpbaseunit.testgradient(), and alglib.testmlpbaseunit.testprocessing().
static void alglib.testmlpbaseunit.createnetwork (mlpbase.multilayerperceptron network, int nkind, double a1, double a2, int nin, int nhid1, int nhid2, int nout) inline static private
References alglib.serializer.alloc_start(), alglib.ap.assert(), alglib.serializer.get_string(), alglib.mlpbase.mlpalloc(), alglib.mlpbase.mlpcopy(), alglib.mlpbase.mlpcreate0(), alglib.mlpbase.mlpcreate1(), alglib.mlpbase.mlpcreate2(), alglib.mlpbase.mlpcreateb0(), alglib.mlpbase.mlpcreateb1(), alglib.mlpbase.mlpcreateb2(), alglib.mlpbase.mlpcreatec0(), alglib.mlpbase.mlpcreatec1(), alglib.mlpbase.mlpcreatec2(), alglib.mlpbase.mlpcreater0(), alglib.mlpbase.mlpcreater1(), alglib.mlpbase.mlpcreater2(), alglib.mlpbase.mlprandomizefull(), alglib.mlpbase.mlpserialize(), alglib.mlpbase.mlpunserialize(), alglib.math.randominteger(), alglib.serializer.sstart_str(), alglib.serializer.stop(), and alglib.serializer.ustart_str().
Referenced by alglib.testmlpbaseunit.testerr(), alglib.testmlpbaseunit.testgradient(), alglib.testmlpbaseunit.testhessian(), alglib.testmlpbaseunit.testinformational(), alglib.testmlpbaseunit.testmlpgbsubset(), and alglib.testmlpbaseunit.testprocessing().
static void alglib.testmlpbaseunit.unsetnetwork (mlpbase.multilayerperceptron network) inline static private
References alglib.mlpbase.mlpcreate0().
Referenced by alglib.testmlpbaseunit.testprocessing().
static void alglib.testmlpbaseunit.testinformational (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err) inline static private
References alglib.testmlpbaseunit.createnetwork(), alglib.math.machineepsilon, alglib.mlpbase.mlpactivationfunction(), alglib.mlpbase.mlpgetinputscaling(), alglib.mlpbase.mlpgetinputscount(), alglib.mlpbase.mlpgetlayersize(), alglib.mlpbase.mlpgetneuroninfo(), alglib.mlpbase.mlpgetoutputscaling(), alglib.mlpbase.mlpgetoutputscount(), alglib.mlpbase.mlpgetweight(), alglib.mlpbase.mlpgetweightscount(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlpproperties(), and alglib.math.randomreal().
Referenced by alglib.testmlpbaseunit.testmlpbase().
static void alglib.testmlpbaseunit.testprocessing (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err) inline static private
References alglib.serializer.alloc_start(), alglib.ap.assert(), alglib.testmlpbaseunit.createnetwork(), alglib.serializer.get_string(), alglib.math.machineepsilon, alglib.mlpbase.mlpalloc(), alglib.mlpbase.mlpcopy(), alglib.mlpbase.mlpcopyshared(), alglib.mlpbase.mlpcopytunableparameters(), alglib.mlpbase.mlpexporttunableparameters(), alglib.mlpbase.mlpimporttunableparameters(), alglib.mlpbase.mlpinitpreprocessor(), alglib.mlpbase.mlpinitpreprocessorsparse(), alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlpproperties(), alglib.mlpbase.mlprandomize(), alglib.mlpbase.mlprandomizefull(), alglib.mlpbase.mlpserialize(), alglib.mlpbase.mlpunserialize(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.seterrorflag(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparseconverttohash(), alglib.sparse.sparsecreate(), alglib.sparse.sparseset(), alglib.serializer.sstart_str(), alglib.serializer.stop(), alglib.testmlpbaseunit.unsetnetwork(), alglib.serializer.ustart_str(), and alglib.testmlpbaseunit.vectordiff().
Referenced by alglib.testmlpbaseunit.testmlpbase().
static void alglib.testmlpbaseunit.testgradient (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, int sizemin, int sizemax, ref bool err) inline static private
References alglib.testmlpbaseunit.createnetwork(), alglib.math.maxrealnumber, alglib.mlpbase.mlperror(), alglib.mlpbase.mlperrorn(), alglib.mlpbase.mlperrorsparse(), alglib.mlpbase.mlperrorsparsesubset(), alglib.mlpbase.mlperrorsubset(), alglib.mlpbase.mlpgrad(), alglib.mlpbase.mlpgradbatch(), alglib.mlpbase.mlpgradbatchsparse(), alglib.mlpbase.mlpgradbatchsparsesubset(), alglib.mlpbase.mlpgradbatchsubset(), alglib.mlpbase.mlpgradn(), alglib.mlpbase.mlpgradnbatch(), alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlpproperties(), alglib.mlpbase.mlprandomizefull(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.seterrorflag(), alglib.apserv.seterrorflagdiff(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseget(), alglib.sparse.sparseset(), alglib.math.sqr(), and alglib.testmlpbaseunit.vectordiff().
Referenced by alglib.testmlpbaseunit.testmlpbase().
static void alglib.testmlpbaseunit.testhessian (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err) inline static private
References alglib.ap.assert(), alglib.testmlpbaseunit.createnetwork(), alglib.mlpbase.mlpgrad(), alglib.mlpbase.mlpgradn(), alglib.mlpbase.mlphessianbatch(), alglib.mlpbase.mlphessiannbatch(), alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpproperties(), alglib.mlpbase.mlprandomizefull(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testmlpbaseunit.testmlpbase().
static void alglib.testmlpbaseunit.testerr (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, int sizemin, int sizemax, ref bool err) inline static private
References alglib.testmlpbaseunit.createnetwork(), alglib.math.maxrealnumber, alglib.mlpbase.mlpallerrorssparsesubset(), alglib.mlpbase.mlpallerrorssubset(), alglib.mlpbase.mlpavgce(), alglib.mlpbase.mlpavgcesparse(), alglib.mlpbase.mlpavgerror(), alglib.mlpbase.mlpavgerrorsparse(), alglib.mlpbase.mlpavgrelerror(), alglib.mlpbase.mlpavgrelerrorsparse(), alglib.mlpbase.mlpclserror(), alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlpproperties(), alglib.mlpbase.mlprandomizefull(), alglib.mlpbase.mlprelclserror(), alglib.mlpbase.mlprelclserrorsparse(), alglib.mlpbase.mlprmserror(), alglib.mlpbase.mlprmserrorsparse(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.seterrorflag(), alglib.apserv.seterrorflagdiff(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseset(), and alglib.math.sqr().
Referenced by alglib.testmlpbaseunit.testmlpbase().
static void alglib.testmlpbaseunit.spectests (ref bool inferrors, ref bool procerrors, ref bool graderrors, ref bool hesserrors, ref bool errerrors) inline static private
References alglib.math.isfinite(), alglib.mlpbase.mlpcreate1(), alglib.mlpbase.mlpcreatec1(), alglib.mlpbase.mlperror(), alglib.mlpbase.mlpgetweightscount(), alglib.mlpbase.mlpgradbatch(), and alglib.apserv.seterrorflag().
Referenced by alglib.testmlpbaseunit.testmlpbase().
static bool alglib.testmlpbaseunit.testmlpgbsubset () inline static private
References alglib.testmlpbaseunit.createnetwork(), alglib.mlpbase.mlpgradbatch(), alglib.mlpbase.mlpgradbatchsparse(), alglib.mlpbase.mlpgradbatchsparsesubset(), alglib.mlpbase.mlpgradbatchsubset(), alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpproperties(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
Referenced by alglib.testmlpbaseunit.testmlpbase().
The documentation for this class was generated from the following file:
igtest/numerics/alglib_0.8.2/tests/test_c.cs