IGLib: Meta.Numerics.Matrices.TridiagonalLUDecomposition Class Reference
Meta.Numerics.Matrices.TridiagonalLUDecomposition Class Reference
Represents the LU decomposition of a tridiagonal matrix.
Public Member Functions
double Determinant ()
Computes the determinant of the original matrix.
ColumnVector Solve (IList< double > rhs)
Solves a tridiagonal system of linear equations.
SquareMatrix Inverse ()
Computes the inverse of the original matrix.
Properties
int Dimension [get]
Gets the dimension of the original matrix.
Private Attributes
int n
int[] P
int parity
double[] L
double[] D
double[] U
double[] V
Detailed Description
Represents the LU decomposition of a tridiagonal matrix.
Member Function Documentation
double Meta.Numerics.Matrices.TridiagonalLUDecomposition.Determinant () inline
Computes the determinant of the original matrix.
Returns
The determinant det M.
Referenced by Test.TridiagonalMatrixTest.TridiagonalMatrixLUDecompositionTest().
ColumnVector Meta.Numerics.Matrices.TridiagonalLUDecomposition.Solve (IList< double > rhs) inline
Solves a tridiagonal system of linear equations.
Parameters
rhs The right-hand side vector b.
Returns
A vector x which satisties Ax = b.
Referenced by Test.TridiagonalMatrixTest.TridiagonalMatrixLUDecompositionTest().
SquareMatrix Meta.Numerics.Matrices.TridiagonalLUDecomposition.Inverse () inline
Computes the inverse of the original matrix.
Returns
The matrix M-1.
Referenced by Test.TridiagonalMatrixTest.TridiagonalMatrixLUDecompositionTest().
Member Data Documentation
int Meta.Numerics.Matrices.TridiagonalLUDecomposition.n private
int [] Meta.Numerics.Matrices.TridiagonalLUDecomposition.P private
int Meta.Numerics.Matrices.TridiagonalLUDecomposition.parity private
double [] Meta.Numerics.Matrices.TridiagonalLUDecomposition.L private
double [] Meta.Numerics.Matrices.TridiagonalLUDecomposition.D private
double [] Meta.Numerics.Matrices.TridiagonalLUDecomposition.U private
double [] Meta.Numerics.Matrices.TridiagonalLUDecomposition.V private
Property Documentation
int Meta.Numerics.Matrices.TridiagonalLUDecomposition.Dimension get
Gets the dimension of the original matrix.
Referenced by Test.TridiagonalMatrixTest.TridiagonalMatrixLUDecompositionTest().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Matrices/TridiagonalMatrix.cs