IGLib: NUnit.Engine.Services.DriverService Class Reference
NUnit.Engine.Services.DriverService Class Reference
The DriverService provides drivers able to load and run tests using various frameworks.
Public Member Functions
IFrameworkDriver GetDriver (AppDomain domain, string assemblyPath)
Get a driver suitable for use with a particular test assembly.
override void StartService ()
Initialize the Service
Public Member Functions inherited from NUnit.Engine.Services.Service
virtual void StopService ()
Do any cleanup needed before terminating the service
void Dispose ()
Private Attributes
IList< IDriverFactory > _factories = new List<IDriverFactory>()
Additional Inherited Members
Protected Member Functions inherited from NUnit.Engine.Services.Service
virtual void Dispose (bool disposing)
Protected Attributes inherited from NUnit.Engine.Services.Service
bool _disposed = false
Properties inherited from NUnit.Engine.Services.Service
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get, protected set]
Gets the ServiceStatus of this service
Properties inherited from NUnit.Engine.IService
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get]
Gets the ServiceStatus of this service
Detailed Description
The DriverService provides drivers able to load and run tests using various frameworks.
Member Function Documentation
IFrameworkDriver NUnit.Engine.Services.DriverService.GetDriver (AppDomain domain, string assemblyPath) inline
Get a driver suitable for use with a particular test assembly.
Parameters
domain The AppDomain to use for the tests
assemblyPath The full path to the test assembly
Returns
Implements NUnit.Engine.IDriverService.
Referenced by NUnit.Engine.Services.Tests.DriverServiceTests.CorrectDriverIsUsed().
override void NUnit.Engine.Services.DriverService.StartService () inline virtual
Initialize the Service
Reimplemented from NUnit.Engine.Services.Service.
References NUnit.Engine.Services.ExtensionService.GetExtensionNode(), and NUnit.Engine.ServiceContext.GetService().
Member Data Documentation
IList<IDriverFactory> NUnit.Engine.Services.DriverService._factories = new List<IDriverFactory>() private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/DriverService.cs