IGLib: CShell.Framework.Results.OpenDocumentResult Class Reference
CShell.Framework.Results.OpenDocumentResult Class Reference
Public Member Functions
OpenDocumentResult (IDocument document)
OpenDocumentResult (string path)
OpenDocumentResult (Uri uri)
OpenDocumentResult (Type documentType)
override void Execute (ActionExecutionContext context)
OpenDocumentResult (IDocument document)
OpenDocumentResult (string path)
OpenDocumentResult (Uri uri)
OpenDocumentResult (Type documentType)
override void Execute (ActionExecutionContext context)
Private Attributes
readonly IDocument document
readonly Type documentType
readonly Uri uri
IShell shell
Additional Inherited Members
Protected Member Functions inherited from CShell.Framework.Results.OpenResultBase< TTarget >
virtual void OnCompleted (Exception exception)
virtual void OnCompleted (Exception exception)
Protected Attributes inherited from CShell.Framework.Results.OpenResultBase< TTarget >
Action< TTarget > _setData
Action< TTarget > _onConfigure
Action< TTarget > _onShutDown
Properties inherited from CShell.Framework.Results.OpenResultBase< TTarget >
Action< TTarget > IOpenResult
< TTarget >. OnConfigure [get, set]
Action< TTarget > IOpenResult
< TTarget >. OnShutDown [get, set]
Properties inherited from CShell.Framework.Results.IOpenResult< TChild >
Action< TChild > OnConfigure [get, set]
Action< TChild > OnShutDown [get, set]
Events inherited from CShell.Framework.Results.OpenResultBase< TTarget >
EventHandler
< ResultCompletionEventArgs > Completed
Constructor & Destructor Documentation
CShell.Framework.Results.OpenDocumentResult.OpenDocumentResult (IDocument document) inline
CShell.Framework.Results.OpenDocumentResult.OpenDocumentResult (string path) inline
CShell.Framework.Results.OpenDocumentResult.OpenDocumentResult (Uri uri) inline
CShell.Framework.Results.OpenDocumentResult.OpenDocumentResult (Type documentType) inline
CShell.Framework.Results.OpenDocumentResult.OpenDocumentResult (IDocument document) inline
CShell.Framework.Results.OpenDocumentResult.OpenDocumentResult (string path) inline
CShell.Framework.Results.OpenDocumentResult.OpenDocumentResult (Uri uri) inline
CShell.Framework.Results.OpenDocumentResult.OpenDocumentResult (Type documentType) inline
Member Function Documentation
override void CShell.Framework.Results.OpenDocumentResult.Execute (ActionExecutionContext context) inline virtual
Implements CShell.Framework.Results.OpenResultBase< TTarget >.
References CShell.Shell.GetDocument(), and CShell.Framework.Services.IShell.OpenDocument().
override void CShell.Framework.Results.OpenDocumentResult.Execute (ActionExecutionContext context) inline virtual
Implements CShell.Framework.Results.OpenResultBase< TTarget >.
References CShell.Shell.GetDocument(), and CShell.Framework.Services.IShell.OpenDocument().
Member Data Documentation
readonly IDocument CShell.Framework.Results.OpenDocumentResult.document private
readonly Type CShell.Framework.Results.OpenDocumentResult.documentType private
readonly Uri CShell.Framework.Results.OpenDocumentResult.uri private
IShell CShell.Framework.Results.OpenDocumentResult.shell private
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Results/OpenDocumentResult.cs