IGLib: NUnit.Framework.Internal.Commands.TestCommand Class Reference
NUnit.Framework.Internal.Commands.TestCommand Class Reference abstract
TestCommand is the abstract base class for all test commands in the framework. A TestCommand represents a single stage in the execution of a test, e.g.: SetUp/TearDown, checking for Timeout, verifying the returned result from a method, etc.
Public Member Functions
TestCommand (Test test)
Construct a TestCommand for a test.
abstract TestResult Execute (TestExecutionContext context)
Runs the test in a specified context, returning a TestResult.
Properties
Test Test [get, private set]
Gets the test associated with this command.
Detailed Description
TestCommand is the abstract base class for all test commands in the framework. A TestCommand represents a single stage in the execution of a test, e.g.: SetUp/TearDown, checking for Timeout, verifying the returned result from a method, etc.
TestCommands may decorate other test commands so that the execution of a lower-level command is nested within that of a higher level command. All nested commands are executed synchronously, as a single unit. Scheduling test execution on separate threads is handled at a higher level, using the task dispatcher.
Constructor & Destructor Documentation
NUnit.Framework.Internal.Commands.TestCommand.TestCommand (Test test) inline
Construct a TestCommand for a test.
Parameters
test The test to be executed
Member Function Documentation
abstract TestResult NUnit.Framework.Internal.Commands.TestCommand.Execute (TestExecutionContext context) pure virtual
Runs the test in a specified context, returning a TestResult.
Parameters
context The TestExecutionContext to be used for running the test.
Returns
A TestResult
Implemented in NUnit.Framework.Attributes.Tests.CommandWrapperTests.ExpectedExceptionAttribute.ExpectedExceptionCommand, NUnit.Framework.RepeatAttribute.RepeatedTestCommand, NUnit.Framework.RetryAttribute.RetryCommand, NUnit.Framework.Internal.Commands.OneTimeSetUpCommand, NUnit.Framework.Internal.Commands.SetUpTearDownCommand, NUnit.Framework.Internal.Commands.OneTimeTearDownCommand, NUnit.Framework.Internal.Commands.TestMethodCommand, NUnit.Framework.Internal.Commands.TestActionCommand, NUnit.Framework.Internal.Commands.MaxTimeCommand, NUnit.Framework.Internal.Commands.SkipCommand, NUnit.Framework.Internal.Commands.ApplyChangesToContextCommand, and NUnit.Framework.Internal.Commands.TheoryResultCommand.
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeTearDown(), and NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork().
Property Documentation
Test NUnit.Framework.Internal.Commands.TestCommand.Test get private set
Gets the test associated with this command.
Referenced by NUnit.Framework.Internal.Commands.SetUpTearDownCommand.SetUpTearDownCommand(), and NUnit.Framework.Internal.Commands.TestActionCommand.TestActionCommand().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Commands/TestCommand.cs