IGLib: Mono.Options.OptionSet Class Reference
Mono.Options.OptionSet Class Reference
Classes
class ActionOption
class ActionOption< T >
class ActionOption< TKey, TValue >
Public Member Functions
OptionSet ()
OptionSet (Converter< string, string > localizer)
new OptionSet Add (Option option)
OptionSet Add (string prototype, Action< string > action)
OptionSet Add (string prototype, string description, Action< string > action)
OptionSet Add (string prototype, OptionAction< string, string > action)
OptionSet Add (string prototype, string description, OptionAction< string, string > action)
OptionSet Add< T > (string prototype, Action< T > action)
OptionSet Add< T > (string prototype, string description, Action< T > action)
OptionSet Add< TKey, TValue > (string prototype, OptionAction< TKey, TValue > action)
OptionSet Add< TKey, TValue > (string prototype, string description, OptionAction< TKey, TValue > action)
List< string > Parse (IEnumerable< string > arguments)
void WriteOptionDescriptions (TextWriter o)
Protected Member Functions
override string GetKeyForItem (Option item)
Option GetOptionForName (string option)
override void InsertItem (int index, Option item)
override void RemoveItem (int index)
override void SetItem (int index, Option item)
virtual OptionContext CreateOptionContext ()
bool GetOptionParts (string argument, out string flag, out string name, out string sep, out string value)
virtual bool Parse (string argument, OptionContext c)
Properties
Converter< string, string > MessageLocalizer [get]
Private Member Functions
void AddImpl (Option option)
void ParseValue (string option, OptionContext c)
bool ParseBool (string option, string n, OptionContext c)
bool ParseBundledValue (string f, string n, OptionContext c)
bool WriteOptionPrototype (TextWriter o, Option p, ref int written)
Static Private Member Functions
static bool Unprocessed (ICollection< string > extra, Option def, OptionContext c, string argument)
static void Invoke (OptionContext c, string name, string value, Option option)
static int GetNextOptionIndex (string[] names, int i)
static void Write (TextWriter o, ref int n, string s)
static string GetArgumentName (int index, int maxIndex, string description)
static string GetDescription (string description)
static IEnumerable< string > GetLines (string description)
static bool IsEolChar (char c)
static int GetLineEnd (int start, int length, string description)
Private Attributes
Converter< string, string > localizer
readonly Regex ValueOption
const int OptionWidth = 29
Constructor & Destructor Documentation
Mono.Options.OptionSet.OptionSet () inline
Mono.Options.OptionSet.OptionSet (Converter< string, string > localizer) inline
Member Function Documentation
override string Mono.Options.OptionSet.GetKeyForItem (Option item) inline protected
Option Mono.Options.OptionSet.GetOptionForName (string option) inline protected
override void Mono.Options.OptionSet.InsertItem (int index, Option item) inline protected
override void Mono.Options.OptionSet.RemoveItem (int index) inline protected
override void Mono.Options.OptionSet.SetItem (int index, Option item) inline protected
void Mono.Options.OptionSet.AddImpl (Option option) inline private
new OptionSet Mono.Options.OptionSet.Add (Option option) inline
References Mono.Options.OptionSet.Add().
Referenced by Mono.Options.OptionSet.Add().
OptionSet Mono.Options.OptionSet.Add (string prototype, Action< string > action) inline
OptionSet Mono.Options.OptionSet.Add (string prototype, string description, Action< string > action) inline
OptionSet Mono.Options.OptionSet.Add (string prototype, OptionAction< string, string > action) inline
OptionSet Mono.Options.OptionSet.Add (string prototype, string description, OptionAction< string, string > action) inline
OptionSet Mono.Options.OptionSet.Add< T > (string prototype, Action< T > action) inline
OptionSet Mono.Options.OptionSet.Add< T > (string prototype, string description, Action< T > action) inline
OptionSet Mono.Options.OptionSet.Add< TKey, TValue > (string prototype, OptionAction< TKey, TValue > action) inline
OptionSet Mono.Options.OptionSet.Add< TKey, TValue > (string prototype, string description, OptionAction< TKey, TValue > action) inline
virtual OptionContext Mono.Options.OptionSet.CreateOptionContext () inline protected virtual
List<string> Mono.Options.OptionSet.Parse (IEnumerable< string > arguments) inline
References Mono.Options.Option.Invoke(), Mono.Options.OptionContext.Option, and Mono.Options.OptionContext.OptionIndex.
static bool Mono.Options.OptionSet.Unprocessed (ICollection< string > extra, Option def, OptionContext c, string argument) inline static private
References Mono.Options.OptionValueCollection.Add(), Mono.Options.Option.Invoke(), Mono.Options.OptionContext.Option, and Mono.Options.OptionContext.OptionValues.
bool Mono.Options.OptionSet.GetOptionParts (string argument, out string flag, out string name, out string sep, out string value) inline protected
virtual bool Mono.Options.OptionSet.Parse (string argument, OptionContext c) inline protected virtual
References Mono.Options.OptionValueCollection.Add(), Mono.Options.Option.Invoke(), Mono.Options.OptionContext.Option, Mono.Options.OptionContext.OptionName, Mono.Options.OptionContext.OptionValues, and Mono.Options.Option.OptionValueType.
void Mono.Options.OptionSet.ParseValue (string option, OptionContext c) inline private
References Mono.Options.OptionValueCollection.Add(), Mono.Options.OptionValueCollection.Count, Mono.Options.Option.Invoke(), Mono.Options.Option.MaxValueCount, Mono.Options.OptionContext.Option, Mono.Options.OptionContext.OptionName, Mono.Options.OptionContext.OptionValues, and Mono.Options.Option.OptionValueType.
bool Mono.Options.OptionSet.ParseBool (string option, string n, OptionContext c) inline private
References Mono.Options.OptionValueCollection.Add(), Mono.Options.Option.Invoke(), Mono.Options.OptionContext.Option, Mono.Options.OptionContext.OptionName, and Mono.Options.OptionContext.OptionValues.
bool Mono.Options.OptionSet.ParseBundledValue (string f, string n, OptionContext c) inline private
References Mono.Options.OptionContext.Option, Mono.Options.OptionContext.OptionName, and Mono.Options.Option.OptionValueType.
static void Mono.Options.OptionSet.Invoke (OptionContext c, string name, string value, Option option) inline static private
References Mono.Options.OptionValueCollection.Add(), Mono.Options.Option.Invoke(), Mono.Options.OptionContext.Option, Mono.Options.OptionContext.OptionName, and Mono.Options.OptionContext.OptionValues.
void Mono.Options.OptionSet.WriteOptionDescriptions (TextWriter o) inline
References Mono.Options.Option.Description.
bool Mono.Options.OptionSet.WriteOptionPrototype (TextWriter o, Option p, ref int written) inline private
References Mono.Options.Option.Description, Mono.Options.Option.MaxValueCount, and Mono.Options.Option.OptionValueType.
static int Mono.Options.OptionSet.GetNextOptionIndex (string[] names, int i) inline static private
static void Mono.Options.OptionSet.Write (TextWriter o, ref int n, string s) inline static private
static string Mono.Options.OptionSet.GetArgumentName (int index, int maxIndex, string description) inline static private
static string Mono.Options.OptionSet.GetDescription (string description) inline static private
static IEnumerable<string> Mono.Options.OptionSet.GetLines (string description) inline static private
static bool Mono.Options.OptionSet.IsEolChar (char c) inline static private
static int Mono.Options.OptionSet.GetLineEnd (int start, int length, string description) inline static private
Member Data Documentation
Converter<string, string> Mono.Options.OptionSet.localizer private
readonly Regex Mono.Options.OptionSet.ValueOption private
Initial value:
= new Regex (
            @"^(?<flag>--|-|/)(?<name>[^:=]+)((?<sep>[:=])(?<value>.*))?$")
const int Mono.Options.OptionSet.OptionWidth = 29 private
Property Documentation
Converter<string, string> Mono.Options.OptionSet.MessageLocalizer get
Referenced by Mono.Options.OptionValueCollection.AssertValid(), and Mono.Options.Option.Parse< T >().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/Options.cs