IGLib: Test.ContingencyTableTest Class Reference
Test.ContingencyTableTest Class Reference
Public Member Functions
void ContingencyTableOperations ()
void ContingencyTableProbabilitiesAndUncertainties ()
Private Member Functions
void ChooseRandomCell (double[,] pp, double p, out int r, out int c)
Member Function Documentation
void Test.ContingencyTableTest.ContingencyTableOperations () inline
References Meta.Numerics.Statistics.ContingencyTable.ColumnCount, Meta.Numerics.Statistics.ContingencyTable.ColumnTotal(), Meta.Numerics.Statistics.ContingencyTable.RowCount, Meta.Numerics.Statistics.ContingencyTable.RowTotal(), and Meta.Numerics.Statistics.ContingencyTable.Total.
void Test.ContingencyTableTest.ChooseRandomCell (double pp[,], double p, out int r, out int c) inline private
Referenced by Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties().
void Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Test.ContingencyTableTest.ChooseRandomCell(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.ContingencyTable.Increment(), Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, Meta.Numerics.Statistics.ContingencyTable.Probability(), Meta.Numerics.Statistics.ContingencyTable.ProbabilityOfColumn(), Meta.Numerics.Statistics.ContingencyTable.ProbabilityOfColumnConditionalOnRow(), Meta.Numerics.Statistics.ContingencyTable.ProbabilityOfRow(), Meta.Numerics.Statistics.ContingencyTable.ProbabilityOfRowConditionalOnColumn(), Meta.Numerics.Statistics.ContingencyTable.Total, Meta.Numerics.UncertainValue.Uncertainty, Meta.Numerics.UncertainValue.Value, Meta.Numerics.Statistics.BivariateSample.X, and Meta.Numerics.Statistics.BivariateSample.Y.
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/ContingencyTableTest.cs