IGLib: alglib.testldaunit Class Reference
alglib.testldaunit Class Reference
Static Public Member Functions
static bool testlda (bool silent)
static bool testlda (bool silent)
static bool _pexec_testlda (bool silent)
Static Private Member Functions
static void gensimpleset (int nfeatures, int nclasses, int nsamples, int axis, ref double[,] xy)
static void gendeg1set (int nfeatures, int nclasses, int nsamples, int axis, ref double[,] xy)
static double generatenormal (double mean, double sigma)
static bool testwn (double[,] xy, double[,] wn, int ns, int nf, int nc, int ndeg)
static double calcj (int nf, double[,] st, double[,] sw, double[] w, ref double p, ref double q)
static void fishers (double[,] xy, int npoints, int nfeatures, int nclasses, ref double[,] st, ref double[,] sw)
static void gensimpleset (int nfeatures, int nclasses, int nsamples, int axis, ref double[,] xy)
static void gendeg1set (int nfeatures, int nclasses, int nsamples, int axis, ref double[,] xy)
static double generatenormal (double mean, double sigma)
static bool testwn (double[,] xy, double[,] wn, int ns, int nf, int nc, int ndeg)
static double calcj (int nf, double[,] st, double[,] sw, double[] w, ref double p, ref double q)
static void fishers (double[,] xy, int npoints, int nfeatures, int nclasses, ref double[,] st, ref double[,] sw)
Member Function Documentation
static bool alglib.testldaunit.testlda (bool silent) inline static
References alglib.lda.fisherlda(), alglib.lda.fisherldan(), alglib.testldaunit.gendeg1set(), alglib.testldaunit.gensimpleset(), alglib.math.randominteger(), and alglib.testldaunit.testwn().
Referenced by alglib.testldaunit._pexec_testlda(), and _Test.Main().
static void alglib.testldaunit.gensimpleset (int nfeatures, int nclasses, int nsamples, int axis, ref double xy[,]) inline static private
References alglib.ap.assert(), and alglib.testldaunit.generatenormal().
Referenced by alglib.testldaunit.testlda().
static void alglib.testldaunit.gendeg1set (int nfeatures, int nclasses, int nsamples, int axis, ref double xy[,]) inline static private
References alglib.ap.assert(), and alglib.testldaunit.generatenormal().
Referenced by alglib.testldaunit.testlda().
static double alglib.testldaunit.generatenormal (double mean, double sigma) inline static private
References alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testldaunit.gendeg1set(), and alglib.testldaunit.gensimpleset().
static bool alglib.testldaunit.testwn (double xy[,], double wn[,], int ns, int nf, int nc, int ndeg) inline static private
References alglib.testldaunit.calcj(), alglib.testldaunit.fishers(), alglib.math.machineepsilon, alglib.blas.matrixmatrixmultiply(), and alglib.evd.smatrixevd().
Referenced by alglib.testldaunit.testlda().
static double alglib.testldaunit.calcj (int nf, double st[,], double sw[,], double[] w, ref double p, ref double q) inline static private
Referenced by alglib.testldaunit.testwn().
static void alglib.testldaunit.fishers (double xy[,], int npoints, int nfeatures, int nclasses, ref double st[,], ref double sw[,]) inline static private
Referenced by alglib.testldaunit.testwn().
static bool alglib.testldaunit.testlda (bool silent) inline static
References alglib.lda.fisherlda(), alglib.lda.fisherldan(), alglib.testldaunit.gendeg1set(), alglib.testldaunit.gensimpleset(), alglib.math.randominteger(), and alglib.testldaunit.testwn().
static bool alglib.testldaunit._pexec_testlda (bool silent) inline static
References alglib.testldaunit.testlda().
Referenced by _Test.Main().
static void alglib.testldaunit.gensimpleset (int nfeatures, int nclasses, int nsamples, int axis, ref double xy[,]) inline static private
References alglib.ap.assert(), and alglib.testldaunit.generatenormal().
static void alglib.testldaunit.gendeg1set (int nfeatures, int nclasses, int nsamples, int axis, ref double xy[,]) inline static private
References alglib.ap.assert(), and alglib.testldaunit.generatenormal().
static double alglib.testldaunit.generatenormal (double mean, double sigma) inline static private
References alglib.math.randominteger(), and alglib.math.randomreal().
static bool alglib.testldaunit.testwn (double xy[,], double wn[,], int ns, int nf, int nc, int ndeg) inline static private
References alglib.testldaunit.calcj(), alglib.testldaunit.fishers(), alglib.math.machineepsilon, alglib.blas.matrixmatrixmultiply(), and alglib.evd.smatrixevd().
static double alglib.testldaunit.calcj (int nf, double st[,], double sw[,], double[] w, ref double p, ref double q) inline static private
static void alglib.testldaunit.fishers (double xy[,], int npoints, int nfeatures, int nclasses, ref double st[,], ref double sw[,]) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs