IGLib: IG.Forms.CompilerForm Class Reference
IG.Forms.CompilerForm Class Reference
Public Member Functions
CompilerForm ()
Initializes form components and internal variables.
Public Attributes
ReporterConsoleMsgbox Reporter = new ReporterConsoleMsgbox()
Protected Member Functions
void ReportError (string message, Exception ex)
Launches error report.
void CheckReadyToRun ()
Checks whether the compiled code is ready to run, and enables the Run button accordingly.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
RuntimeCompiler Compiler = new RuntimeCompiler()
Properties
Logger Logger [get]
Gets compiler's logger.
Private Member Functions
void btnLoad_Click (object sender, System.EventArgs e)
Loads code template into the rich textbox.
void ChooseFile ()
void btnLoadFromFile_Click (object sender, EventArgs e)
void btnCompile_Click (object sender, System.EventArgs e)
Compilation of code.
void btnExecute_Click (object sender, System.EventArgs e)
void btnQuit_Click (object sender, System.EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Logger _logger = null
string _filePath = "../../testdata/"
bool _fileChosen = false
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.RichTextBox rtfCode
System.Windows.Forms.Button btnLoad
System.Windows.Forms.Button btnCompile
System.Windows.Forms.Button btnExecute
System.Windows.Forms.Button btnQuit
System.Windows.Forms.Button btnLoadFromFile
Constructor & Destructor Documentation
IG.Forms.CompilerForm.CompilerForm () inline
Initializes form components and internal variables.
Member Function Documentation
void IG.Forms.CompilerForm.ReportError (string message, Exception ex) inline protected
Launches error report.
Parameters
message Custom part of the message shown in report.
ex Exception that was thrown.
void IG.Forms.CompilerForm.CheckReadyToRun () inline protected
Checks whether the compiled code is ready to run, and enables the Run button accordingly.
References IG.Lib.RuntimeCompiler.ReadyToRun.
void IG.Forms.CompilerForm.btnLoad_Click (object sender, System.EventArgs e) inline private
Loads code template into the rich textbox.
References IG.Lib.RuntimeCompiler.CodeBase.
void IG.Forms.CompilerForm.ChooseFile () inline private
void IG.Forms.CompilerForm.btnLoadFromFile_Click (object sender, EventArgs e) inline private
void IG.Forms.CompilerForm.btnCompile_Click (object sender, System.EventArgs e) inline private
Compilation of code.
References IG.Lib.Logger.Clear(), IG.Lib.RuntimeCompiler.Code, IG.Lib.RuntimeCompiler.Compile(), IG.Lib.Logger.GetErrorsReport(), IG.Lib.Logger.GetReport(), IG.Lib.Logger.GetWarningsReport(), IG.Lib.Logger.HasErrors(), IG.Lib.Logger.HasWarnings(), IG.Lib.RuntimeCompiler.ReadyToRun, IG.Lib.Logger.Report(), IG.Lib.ReporterBase.ReportError(), and IG.Forms.ReporterConsoleMsgbox_Base.UseMessageBox.
void IG.Forms.CompilerForm.btnExecute_Click (object sender, System.EventArgs e) inline private
References IG.Lib.RuntimeCompiler.LibraryPath, IG.Lib.RuntimeCompiler.LoadFile(), IG.Lib.IRunnableOld.Run(), and IG.Lib.RuntimeCompiler.RunnableFullClass.
void IG.Forms.CompilerForm.btnQuit_Click (object sender, System.EventArgs e) inline private
override void IG.Forms.CompilerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
void IG.Forms.CompilerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Member Data Documentation
RuntimeCompiler IG.Forms.CompilerForm.Compiler = new RuntimeCompiler() protected
ReporterConsoleMsgbox IG.Forms.CompilerForm.Reporter = new ReporterConsoleMsgbox()
Referenced by IG.Test.RuntimeCompilerMain.Main().
Logger IG.Forms.CompilerForm._logger = null private
string IG.Forms.CompilerForm._filePath = "../../testdata/" private
bool IG.Forms.CompilerForm._fileChosen = false private
System.ComponentModel.IContainer IG.Forms.CompilerForm.components = null private
Required designer variable.
System.Windows.Forms.RichTextBox IG.Forms.CompilerForm.rtfCode private
System.Windows.Forms.Button IG.Forms.CompilerForm.btnLoad private
System.Windows.Forms.Button IG.Forms.CompilerForm.btnCompile private
System.Windows.Forms.Button IG.Forms.CompilerForm.btnExecute private
System.Windows.Forms.Button IG.Forms.CompilerForm.btnQuit private
System.Windows.Forms.Button IG.Forms.CompilerForm.btnLoadFromFile private
Property Documentation
Logger IG.Forms.CompilerForm.Logger get protected
Gets compiler's logger.
The documentation for this class was generated from the following files:
igtest/test_iglib_tmp_CSharpScripter1_OLD_TO_DELETE/dynamicloader/loadableclasses/tests/CompilerForm.cs
igtest/test_iglib_tmp_CSharpScripter1_OLD_TO_DELETE/dynamicloader/loadableclasses/tests/CompilerForm.Designer.cs