IGLib: Meta.Numerics.Functions.AdvancedComplexMath Class Reference
Meta.Numerics.Functions.AdvancedComplexMath Class Reference
Contains methods that compute advanced functions of complex arguments.
Static Public Member Functions
static Complex Faddeeva (Complex z)
Computes the complex Faddeeva function.
static Complex Erf (Complex z)
Computes the complex error function.
static Complex Ein (Complex z)
Computes the entire complex exponential integral.
static Complex Gamma (Complex z)
Computes the complex Gamma function.
static Complex LogGamma (Complex z)
Compute the complex log Gamma function.
static Complex Psi (Complex z)
Computes the complex digamma (&#x3C8;) function.
static Complex DiLog (Complex z)
Computes the complex dilogarithm function, also called Spence's function.
static Complex RiemannZeta (Complex z)
Computes the Riemann zeta function for complex values.
Static Private Member Functions
static Complex Faddeeva_Weideman (Complex z)
static Complex Erf_Series (Complex z)
static Complex Faddeeva_ContinuedFraction (Complex z)
static Complex Faddeeva_Taylor (Complex z0, Complex w0, Complex dz)
static Complex Ein_Series (Complex z)
static Complex IntegeralE1_ContinuedFraction (Complex z)
static Complex IntegralEi_AsymptoticSeries (Complex z)
static bool IsEinSeriesPrefered (Complex z)
static Complex LogGamma_Stirling (Complex z)
static Complex DiLog_Series_0 (Complex z)
static Complex DiLog_Series_1 (Complex e)
static Complex DiLog_Log_Series (Complex z)
static Complex RiemannZeta_LaurentSeries (Complex z)
static int RiemannZeta_EulerMaclaurin_N (double s, double t)
static Complex RiemannZeta_EulerMaclaurin (Complex z, int n)
Static Private Attributes
static readonly double Faddeeva_Weideman_L = Math.Sqrt(40.0 / Math.Sqrt(2.0))
static readonly double[] Faddeeva_Weideman_Coefficients
static readonly double baseN = Math.Log(2.0 / Global.Accuracy)
Detailed Description
Contains methods that compute advanced functions of complex arguments.
Member Function Documentation
static Complex Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva (Complex z) inline static
Computes the complex Faddeeva function.
Parameters
z The complex argument.
Returns
The complex value of w(z).
The Faddeeva function w(z) is related to the error function with a complex argument.
It also has an integral representation.
For purely imaginary values, it reduces to the complementary error function (AdvancedMath.Erfc). For purely real values, it reduces to Dawson's integral (AdvancedMath.Dawson).
It appears in the computation of the Voigt line profile function V(x;&#x3C3;,&#x3B3;).
Near the origin, w(z) &#x2248; 1. To accurately determine w(z) - 1 in this region, use the Erf function. Away from the origin near the large negative imaginary axis, the magnitude w(z) increases rapidly and may overflow.
See also
AdvancedComplexMath.Erf, AdvancedMath.Erf, AdvancedMath.Erfc, AdvancedMath.Dawson
References Meta.Numerics.ComplexMath.Abs(), Meta.Numerics.ComplexMath.Exp(), Meta.Numerics.ComplexMath.I, and Meta.Numerics.Complex.Im.
Referenced by Test.AdvancedComplexMathTest.ComplexErfFaddevaAgreement(), Test.AdvancedComplexMathTest.ComplexFaddeevaConjugation(), Test.AdvancedComplexMathTest.ComplexFaddeevaDawson(), and Test.AdvancedComplexMathTest.ComplexFaddeevaSpecialCase().
static Complex Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva_Weideman (Complex z) inline static private
References Meta.Numerics.ComplexMath.I.
static Complex Meta.Numerics.Functions.AdvancedComplexMath.Erf_Series (Complex z) inline static private
static Complex Meta.Numerics.Functions.AdvancedComplexMath.Erf (Complex z) inline static
Computes the complex error function.
Parameters
z The complex argument.
Returns
The value of erf(z).
This function is the analytic continuation of the error function (AdvancedMath.Erf) to the complex plane.
The image below shows the complex error function near the origin, using domain coloring.
The complex error function is entire: it has no poles, cuts, or discontinuities anywhere in the complex plane.
For pure imaginary arguments, erf(z) reduces to the Dawson integral (AdvancedMath.Dawson).
Away from the origin near the real axis, the real part of erf(z) quickly approaches &#x0b1;1. To accurately determine the small difference erf(z) &#8723; 1 in this region, use the Faddeeva function. Away from the origin near the imaginary axis, the magnitude of erf(z) increases very quickly. Although erf(z) may overflow in this region, you can still accurately determine the value of the product erf(z) exp(z2) using the Faddeeva function.
See also
AdvancedMath.Erf, AdvancedMath.Dawson, AdvancedComplexMath.Faddeeva
References Meta.Numerics.ComplexMath.Abs(), Meta.Numerics.ComplexMath.Exp(), Meta.Numerics.ComplexMath.I, and Meta.Numerics.Complex.Re.
Referenced by Test.AdvancedComplexMathTest.ComplexErfFaddevaAgreement(), Test.AdvancedComplexMathTest.ComplexErfFresnel(), Test.AdvancedComplexMathTest.ComplexErfSpecialCase(), and Test.AdvancedComplexMathTest.ComplexErfSymmetries().
static Complex Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva_ContinuedFraction (Complex z) inline static private
References Meta.Numerics.ComplexMath.I.
static Complex Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva_Taylor (Complex z0, Complex w0, Complex dz) inline static private
References Meta.Numerics.ComplexMath.I.
static Complex Meta.Numerics.Functions.AdvancedComplexMath.Ein (Complex z) inline static
Computes the entire complex exponential integral.
Parameters
z The complex argument.
Returns
The value of Ein(z).
The entire exponential integral function can be defined by an integral or an equivalent series.
Both Ei(z) and E1(x) and be obtained from Ein(z).
Unlike either Ei(z) or E1(z), Ein(z) is entire, that is, it has no poles or cuts anywhere in the complex plane.
References Meta.Numerics.Functions.AdvancedMath.EulerGamma, Meta.Numerics.ComplexMath.Log(), and Meta.Numerics.Complex.Re.
Referenced by Test.AdvancedComplexMathTest.ComplexEinAgreement().
static Complex Meta.Numerics.Functions.AdvancedComplexMath.Ein_Series (Complex z) inline static private
static Complex Meta.Numerics.Functions.AdvancedComplexMath.IntegeralE1_ContinuedFraction (Complex z) inline static private
References Meta.Numerics.ComplexMath.Exp().
static Complex Meta.Numerics.Functions.AdvancedComplexMath.IntegralEi_AsymptoticSeries (Complex z) inline static private
References Meta.Numerics.ComplexMath.Exp().
static bool Meta.Numerics.Functions.AdvancedComplexMath.IsEinSeriesPrefered (Complex z) inline static private
References Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
static Complex Meta.Numerics.Functions.AdvancedComplexMath.Gamma (Complex z) inline static
Computes the complex Gamma function.
Parameters
z The complex argument.
Returns
The complex value of &#x393;(z).
The image below shows the complex &#x393; function near the origin using domain coloring.
See also
AdvancedMath.Gamma(double)
References Meta.Numerics.ComplexMath.Exp(), Meta.Numerics.Complex.Re, and Meta.Numerics.ComplexMath.Sin().
Referenced by Test.AdvancedComplexMathTest.ComplexGammaConjugation(), Test.AdvancedComplexMathTest.ComplexGammaInequality(), Test.AdvancedComplexMathTest.ComplexGammaKnownLines(), Test.AdvancedComplexMathTest.ComplexGammaRecurrance(), and Meta.Numerics.Functions.AdvancedComplexMath.RiemannZeta().
static Complex Meta.Numerics.Functions.AdvancedComplexMath.LogGamma (Complex z) inline static
Compute the complex log Gamma function.
Parameters
z The complex argument, which must have a non-negative real part.
Returns
The complex value ln(&#x393;(z)).
Exceptions
ArgumentOutOfRangeException The real part of z is negative.
See also
AdvancedMath.LogGamma
References Meta.Numerics.ComplexMath.Abs(), and Meta.Numerics.Complex.Re.
Referenced by Test.AdvancedComplexMathTest.ComplexLogGammaAgreement(), Test.AdvancedComplexMathTest.ComplexLogGammaConjugation(), and Meta.Numerics.Functions.AdvancedMath.Coulomb_Asymptotic().
static Complex Meta.Numerics.Functions.AdvancedComplexMath.LogGamma_Stirling (Complex z) inline static private
References Meta.Numerics.Complex.Conjugate, Meta.Numerics.Complex.Im, Meta.Numerics.ComplexMath.Log(), and Meta.Numerics.Complex.Re.
static Complex Meta.Numerics.Functions.AdvancedComplexMath.Psi (Complex z) inline static
Computes the complex digamma (&#x3C8;) function.
Parameters
z The complex argument.
Returns
The value of &#x3C8;(z).
The image below shows the complex &#x3C8; function near the origin using domain coloring.
See also
AdvancedMath.Psi(double)
References Meta.Numerics.Complex.Re, and Meta.Numerics.ComplexMath.Tan().
Referenced by Test.AdvancedComplexMathTest.ComplexPsiConjugation(), Test.AdvancedComplexMathTest.ComplexPsiDuplication(), Test.AdvancedComplexMathTest.ComplexPsiImaginaryParts(), Test.AdvancedComplexMathTest.ComplexPsiRecurrence(), and Meta.Numerics.Functions.AdvancedMath.Coulomb_Zero_Series().
static Complex Meta.Numerics.Functions.AdvancedComplexMath.DiLog (Complex z) inline static
Computes the complex dilogarithm function, also called Spence's function.
Parameters
z The complex argument.
Returns
The value Li2(z).
This function is the analyic continuation of the dilogarithm function (AdvancedMath.DiLog) into the complex plane.
The image below shows the complex dilogarithm function near the origin, using domain coloring.
See also
AdvancedMath.DiLog
References Meta.Numerics.ComplexMath.Abs(), Meta.Numerics.Complex.Conjugate, Meta.Numerics.Complex.Im, Meta.Numerics.ComplexMath.Log(), and Meta.Numerics.Complex.Re.
Referenced by Test.AdvancedComplexMathTest.ComplexDiLogAgreement(), Test.AdvancedComplexMathTest.ComplexDiLogBranchCut(), Test.AdvancedComplexMathTest.ComplexDiLogClausen(), Test.AdvancedComplexMathTest.ComplexDiLogConjugation(), Test.AdvancedComplexMathTest.ComplexDiLogSymmetry(), and Test.AdvancedComplexMathTest.ComplexDiLogUnitCircle().
static Complex Meta.Numerics.Functions.AdvancedComplexMath.DiLog_Series_0 (Complex z) inline static private
static Complex Meta.Numerics.Functions.AdvancedComplexMath.DiLog_Series_1 (Complex e) inline static private
References Meta.Numerics.ComplexMath.Log().
static Complex Meta.Numerics.Functions.AdvancedComplexMath.DiLog_Log_Series (Complex z) inline static private
References Meta.Numerics.ComplexMath.Log().
static Complex Meta.Numerics.Functions.AdvancedComplexMath.RiemannZeta (Complex z) inline static
Computes the Riemann zeta function for complex values.
Parameters
z The argument.
Returns
The value of &#x3B6;(z).
As the imaginary part of the argument increases, the computation of the zeta function becomes slower and more difficult. The computation time is approximately proprotional to the imaginary part of z. The result also slowly looses accuracy for arguments with very large imaginary parts; for arguments with z.Im of order 10^d, approximately the last d digits of the result are suspect.
References Meta.Numerics.ComplexMath.Abs(), Meta.Numerics.Complex.Conjugate, Meta.Numerics.ComplexMath.Cos(), Meta.Numerics.Functions.AdvancedComplexMath.Gamma(), Meta.Numerics.Complex.Im, Meta.Numerics.Complex.One, Meta.Numerics.ComplexMath.Pow(), and Meta.Numerics.Complex.Re.
Referenced by Test.AdvancedComplexMathTest.ComplexRealRiemannZetaAgreement(), Test.AdvancedComplexMathTest.ComplexReimannZetaPrimesTest(), and Test.AdvancedComplexMathTest.ComplexRiemannZetaZeros().
static Complex Meta.Numerics.Functions.AdvancedComplexMath.RiemannZeta_LaurentSeries (Complex z) inline static private
static int Meta.Numerics.Functions.AdvancedComplexMath.RiemannZeta_EulerMaclaurin_N (double s, double t) inline static private
static Complex Meta.Numerics.Functions.AdvancedComplexMath.RiemannZeta_EulerMaclaurin (Complex z, int n) inline static private
References Meta.Numerics.Functions.AdvancedIntegerMath.BernoulliNumber(), Meta.Numerics.Complex.One, and Meta.Numerics.ComplexMath.Pow().
Member Data Documentation
readonly double Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva_Weideman_L = Math.Sqrt(40.0 / Math.Sqrt(2.0)) static private
readonly double [] Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva_Weideman_Coefficients static private
readonly double Meta.Numerics.Functions.AdvancedComplexMath.baseN = Math.Log(2.0 / Global.Accuracy) static private
The documentation for this class was generated from the following files:
igtest/numerics/MetaNumerics/Numerics/Numerics/Functions/AdvancedMath_Error.cs
igtest/numerics/MetaNumerics/Numerics/Numerics/Functions/AdvancedMath_Riemann.cs
igtest/numerics/MetaNumerics/Numerics/Numerics/Functions/AdvancedMath_Exponential.cs
igtest/numerics/MetaNumerics/Numerics/Numerics/Functions/AdvancedMath_Gamma.cs
igtest/numerics/MetaNumerics/Numerics/Numerics/Functions/AdvancedMath_Polylog.cs