IGLib: NUnit.Framework.Attributes.RetryAttributeTests Class Reference
NUnit.Framework.Attributes.RetryAttributeTests Class Reference
Public Member Functions
void RetryWorksAsExpected (Type fixtureType, string outcome, int nTries)
void CategoryWorksWithRetry ()
Member Function Documentation
void NUnit.Framework.Attributes.RetryAttributeTests.RetryWorksAsExpected (Type fixtureType, string outcome, int nTries) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.Reflect.Construct(), NUnit.TestData.RepeatingTests.RepeatingTestsFixtureBase.Count, NUnit.Framework.Is.EqualTo(), NUnit.TestData.RepeatingTests.RepeatingTestsFixtureBase.FixtureSetupCount, NUnit.TestData.RepeatingTests.RepeatingTestsFixtureBase.FixtureTeardownCount, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.RepeatingTests.RepeatingTestsFixtureBase.SetupCount, NUnit.TestData.RepeatingTests.RepeatingTestsFixtureBase.TeardownCount, NUnit.Framework.Assert.That(), and NUnit.Framework.Interfaces.ResultState.ToString().
void NUnit.Framework.Attributes.RetryAttributeTests.CategoryWorksWithRetry () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.IsNotNull(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Internal.TestSuite.Tests.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/RetryAttributeTests.cs