IGLib: alglib.testinverseupdateunit Class Reference
alglib.testinverseupdateunit Class Reference
Static Public Member Functions
static bool testinverseupdate (bool silent)
static bool testinverseupdate (bool silent)
static bool _pexec_testinverseupdate (bool silent)
Static Private Member Functions
static void makeacopy (double[,] a, int m, int n, ref double[,] b)
static void matlu (ref double[,] a, int m, int n, ref int[] pivots)
static void generaterandomorthogonalmatrix (ref double[,] a0, int n)
static void generaterandommatrixcond (ref double[,] a0, int n, double c)
static bool invmattr (ref double[,] a, int n, bool isupper, bool isunittriangular)
static bool invmatlu (ref double[,] a, int[] pivots, int n)
static bool invmat (ref double[,] a, int n)
static double matrixdiff (double[,] a, double[,] b, int m, int n)
static bool updandinv (ref double[,] a, double[] u, double[] v, int n)
static void makeacopy (double[,] a, int m, int n, ref double[,] b)
static void matlu (ref double[,] a, int m, int n, ref int[] pivots)
static void generaterandomorthogonalmatrix (ref double[,] a0, int n)
static void generaterandommatrixcond (ref double[,] a0, int n, double c)
static bool invmattr (ref double[,] a, int n, bool isupper, bool isunittriangular)
static bool invmatlu (ref double[,] a, int[] pivots, int n)
static bool invmat (ref double[,] a, int n)
static double matrixdiff (double[,] a, double[,] b, int m, int n)
static bool updandinv (ref double[,] a, double[] u, double[] v, int n)
Member Function Documentation
static bool alglib.testinverseupdateunit.testinverseupdate (bool silent) inline static
References alglib.testinverseupdateunit.generaterandommatrixcond(), alglib.testinverseupdateunit.invmat(), alglib.testinverseupdateunit.makeacopy(), alglib.testinverseupdateunit.matrixdiff(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.inverseupdate.rmatrixinvupdatecolumn(), alglib.inverseupdate.rmatrixinvupdaterow(), alglib.inverseupdate.rmatrixinvupdatesimple(), alglib.inverseupdate.rmatrixinvupdateuv(), and alglib.testinverseupdateunit.updandinv().
Referenced by alglib.testinverseupdateunit._pexec_testinverseupdate(), and _Test.Main().
static void alglib.testinverseupdateunit.makeacopy (double a[,], int m, int n, ref double b[,]) inline static private
Referenced by alglib.testinverseupdateunit.testinverseupdate().
static void alglib.testinverseupdateunit.matlu (ref double a[,], int m, int n, ref int[] pivots) inline static private
References alglib.ap.assert().
Referenced by alglib.testinverseupdateunit.invmat(), and alglib.testinverseupdateunit.updandinv().
static void alglib.testinverseupdateunit.generaterandomorthogonalmatrix (ref double a0[,], int n) inline static private
References alglib.math.randomreal().
Referenced by alglib.testinverseupdateunit.generaterandommatrixcond().
static void alglib.testinverseupdateunit.generaterandommatrixcond (ref double a0[,], int n, double c) inline static private
References alglib.testinverseupdateunit.generaterandomorthogonalmatrix(), and alglib.math.randomreal().
Referenced by alglib.testinverseupdateunit.testinverseupdate().
static bool alglib.testinverseupdateunit.invmattr (ref double a[,], int n, bool isupper, bool isunittriangular) inline static private
Referenced by alglib.testinverseupdateunit.invmatlu().
static bool alglib.testinverseupdateunit.invmatlu (ref double a[,], int[] pivots, int n) inline static private
References alglib.testinverseupdateunit.invmattr().
Referenced by alglib.testinverseupdateunit.invmat(), and alglib.testinverseupdateunit.updandinv().
static bool alglib.testinverseupdateunit.invmat (ref double a[,], int n) inline static private
References alglib.testinverseupdateunit.invmatlu(), and alglib.testinverseupdateunit.matlu().
Referenced by alglib.testinverseupdateunit.testinverseupdate().
static double alglib.testinverseupdateunit.matrixdiff (double a[,], double b[,], int m, int n) inline static private
Referenced by alglib.testinverseupdateunit.testinverseupdate().
static bool alglib.testinverseupdateunit.updandinv (ref double a[,], double[] u, double[] v, int n) inline static private
References alglib.testinverseupdateunit.invmatlu(), and alglib.testinverseupdateunit.matlu().
Referenced by alglib.testinverseupdateunit.testinverseupdate().
static bool alglib.testinverseupdateunit.testinverseupdate (bool silent) inline static
References alglib.testinverseupdateunit.generaterandommatrixcond(), alglib.testinverseupdateunit.invmat(), alglib.testinverseupdateunit.makeacopy(), alglib.testinverseupdateunit.matrixdiff(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.inverseupdate.rmatrixinvupdatecolumn(), alglib.inverseupdate.rmatrixinvupdaterow(), alglib.inverseupdate.rmatrixinvupdatesimple(), alglib.inverseupdate.rmatrixinvupdateuv(), and alglib.testinverseupdateunit.updandinv().
static bool alglib.testinverseupdateunit._pexec_testinverseupdate (bool silent) inline static
References alglib.testinverseupdateunit.testinverseupdate().
Referenced by _Test.Main().
static void alglib.testinverseupdateunit.makeacopy (double a[,], int m, int n, ref double b[,]) inline static private
static void alglib.testinverseupdateunit.matlu (ref double a[,], int m, int n, ref int[] pivots) inline static private
References alglib.ap.assert().
static void alglib.testinverseupdateunit.generaterandomorthogonalmatrix (ref double a0[,], int n) inline static private
References alglib.math.randomreal().
static void alglib.testinverseupdateunit.generaterandommatrixcond (ref double a0[,], int n, double c) inline static private
References alglib.testinverseupdateunit.generaterandomorthogonalmatrix(), and alglib.math.randomreal().
static bool alglib.testinverseupdateunit.invmattr (ref double a[,], int n, bool isupper, bool isunittriangular) inline static private
static bool alglib.testinverseupdateunit.invmatlu (ref double a[,], int[] pivots, int n) inline static private
References alglib.testinverseupdateunit.invmattr().
static bool alglib.testinverseupdateunit.invmat (ref double a[,], int n) inline static private
References alglib.testinverseupdateunit.invmatlu(), and alglib.testinverseupdateunit.matlu().
static double alglib.testinverseupdateunit.matrixdiff (double a[,], double b[,], int m, int n) inline static private
static bool alglib.testinverseupdateunit.updandinv (ref double a[,], double[] u, double[] v, int n) inline static private
References alglib.testinverseupdateunit.invmatlu(), and alglib.testinverseupdateunit.matlu().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs