IGLib: Test.PolynomialTest Class Reference
Test.PolynomialTest Class Reference
Public Member Functions
void PolynomialProperties ()
void PolynomialNegation ()
void PolynomialArithmetic ()
void PolynomialDivisionIdentity ()
void PolynomialRemainderTheorem ()
void PolynomialCalculus ()
void PolynomialFit ()
Member Function Documentation
void Test.PolynomialTest.PolynomialProperties () inline
References Meta.Numerics.Polynomial.Coefficient(), Meta.Numerics.Polynomial.Degree, and Meta.Numerics.Polynomial.FromCoefficients().
void Test.PolynomialTest.PolynomialNegation () inline
References Meta.Numerics.Polynomial.Degree, Meta.Numerics.Polynomial.Evaluate(), and Meta.Numerics.Polynomial.FromCoefficients().
void Test.PolynomialTest.PolynomialArithmetic () inline
References Meta.Numerics.Polynomial.Degree, Meta.Numerics.Polynomial.Evaluate(), and Meta.Numerics.Polynomial.FromCoefficients().
void Test.PolynomialTest.PolynomialDivisionIdentity () inline
References Meta.Numerics.Polynomial.Coefficient(), Meta.Numerics.Polynomial.Degree, Meta.Numerics.Polynomial.Divide(), and Meta.Numerics.Polynomial.FromCoefficients().
void Test.PolynomialTest.PolynomialRemainderTheorem () inline
References Meta.Numerics.Polynomial.Coefficient(), Meta.Numerics.Polynomial.Degree, Meta.Numerics.Polynomial.Divide(), and Meta.Numerics.Polynomial.FromCoefficients().
void Test.PolynomialTest.PolynomialCalculus () inline
References Meta.Numerics.Polynomial.Differentiate(), Meta.Numerics.Polynomial.Evaluate(), Meta.Numerics.Polynomial.FromCoefficients(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), and Meta.Numerics.Polynomial.Integrate().
void Test.PolynomialTest.PolynomialFit () inline
References Meta.Numerics.Polynomial.Coefficient(), Meta.Numerics.Polynomial.Degree, Meta.Numerics.Polynomial.Evaluate(), Meta.Numerics.Polynomial.FromCoefficients(), and Meta.Numerics.Polynomial.FromPoints().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/PolynomialTest.cs