IGLib: IG.Script.Script_11_10_clanek_neural_01 Class Reference
IG.Script.Script_11_10_clanek_neural_01 Class Reference
Classes
class StoredScriptSettings
In methods of this class you will find all the settings that apply to this script.
Public Member Functions
Script_11_10_clanek_neural_01 ()
virtual double PenaltyTerm (double constraintFunctionValue)
Calculates a single penalty term dependent on the value of the constraint function.
virtual double PenaltyTermsSum (IVector parameters)
Returns the sum of all penalty terms.
virtual void CheckAnalysisRequest (IAnalysisResults anRes)
Checks the specified analysis request and throws exception in case of inconsistency.
virtual double Objective1 (IVector param)
Calculates and returns value of the objective function at specified vector of parameters.
override void Analyse (IAnalysisResults anRes)
Performs direct analysis for optimization problems. This method must be overridden in derived classes where one wants to have direct analysis defined.
virtual SampledDataElement GetTrainingElement (int i)
Gets the training element with the specified index (chosen out of al training points, including verificaion points).
virtual bool IsVerificationPoint (int trainingPointIndex)
Whether the training point with the specified index is a verification points and has not been used in training.
List< SampledDataElement > GetTrainingElements (bool includeVerificationPoints)
Returns a list of all neural training elements.
List< SampledDataElement > GetTrainingElements (bool includeVerificationPoints, bool includeNonVerificationPoints)
Returns a list of all neural training elements.
virtual void GetNeuralInputPerturbance (double ratio, ref IVector perturbance)
Returns a perturbance vector whose componenets represent magnitudes of perturbances of neural input parameters with the specified relative ratio with corresponding parameters' scaling lengths.
virtual void GetNeuralOutputPerturbance (double ratio, ref IVector perturbance)
Returns a perturbance vector whose componenets represent magnitudes of perturbances of neural output values with the specified relative ratio with corresponding values' scaling lengths.
virtual void GetNeuralInputVector (double relativeComponents, ref IVector inputVector)
Returns an input vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
virtual void GetNeuralOutputVector (double relativeComponents, ref IVector outputVector)
Returns an output vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
virtual void GetNeuralInputVector (IVector relativeComponents, ref IVector inputVector)
Returns an input vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
virtual void GetNeuralOutputVector (IVector relativeComponents, ref IVector outputVector)
Returns an output vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
virtual void GetNeuralInputRelative (IVector inputVector, ref IVector relativeComponents)
Calculates relative components (running from 0 to 1 within bounds for specified vector component) for the specified vector of neural input parameters.
virtual void GetNeuralOutputRelative (IVector outputVector, ref IVector relativeComponents)
Calculates relative components (running from 0 to 1 within bounds for specified vector component) for the specified vector of neural output values.
virtual double InputDistance (IVector v1, IVector v2)
Returns measure of distance between two vectors in the space of input parameters. Euclidean norm scaled accorging to individual parameter ranges is returned.
virtual double OutputDistance (IVector v1, IVector v2)
Returns measure of distance between two vectors in the space of output parameters. Euclidean norm scaled accorging to individual parameter ranges is returned.
virtual double InputDistance (IVector v1, int trainingPointIndex)
Returns measure of distance between the specified neural input vector and vector of input parameters of the training point with the specified index.
virtual double OutputDistance (IVector v1, int trainingPointIndex)
Returns measure of distance between the specified neural output values vector and vector of output values of the training point with the specified index.
virtual int GetClosestInputIndex (IVector v1, bool includeVerificationPoints)
Returns index of training element with the shortest distance of its input parameters to the specified vector.
virtual int GetClosestOutputIndex (IVector v1, bool includeVerificationPoints)
Returns index of training element with the shortest distance of its output values to the specified vector of output values.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, params IVector[] points)
For each point in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, bool printIndividualPointsComp, params IVector[] points)
For each point in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, params SampledDataElement[] points)
For each point (training element) in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, bool printIndividualPointsComp, params SampledDataElement[] points)
For each point (training element) in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
virtual void NeuralCalculate (params double[] inputParameters)
Calculates approximation at specified input parameters.
virtual void NeuralCalculate (IVector inputParameters)
Calculates approximation at specified input parameters.
virtual void NeuralCalculate (IVector inputParameters, ref IVector outputValues)
Calculates approximation at specified input parameters.
virtual List< SampledDataElement > GetRandomTrainingElements (int numElements, bool includeVerificationPoints)
Creates and returns a list of training elements that are randomly chosen from the current training set. Trainingpoints that are not verification points are always included in the set of points for selection.
virtual List< SampledDataElement > GetRandomTrainingElements (int numElements, bool includeVerificationPoints, bool includeNonVerificationPoints)
Creates and returns a list of training elements that are randomly chosen from the current training set.
virtual List< SampledDataElement > GetRandomTrainingElements (IRandomGenerator rand, int numElements, bool includeVerificationPoints)
Creates and returns a list of training elements that are randomly chosen from the current training set. Trainingpoints that are not verification points are always included in the set of points for selection.
virtual List< SampledDataElement > GetRandomTrainingElements (IRandomGenerator rand, int numElements, bool includeVerificationPoints, bool includeNonVerificationPoints)
Creates and returns a list of training elements that are randomly chosen from the current training set.
virtual void TestDistances (int referencePointIndex, int maxNumPoints)
Test of distances of a specified number of training points with respect to the training point with specified index, in the input parameters space as well as in the output parameter space.
virtual void TestNeuralSpeed (int numEvaluations)
Performs test of speed of calculation of neural network.
virtual void PrintNeuralData ()
This example demonstrates how to extract data necessary for definition of optimization problems.
Public Member Functions inherited from IG.Script.S_11_10_Clanek_Neural_Base
S_11_10_Clanek_Neural_Base ()
override void TransfNeuralToOptimizationParameters (IVector neuralParameters, ref IVector optimizationParameters)
Maps input parameters for neural network to optimization input parameters.
override void TransfOptimizationToNeuralParameters (IVector optimizationParameters, ref IVector neuralParameters)
Maps optimization input parameters to neural network input parameters.
virtual void InitOptimizationData ()
Prepares all the data needed by the direct analysis function.
virtual void PrintOptimizationData ()
Prints alll the data used by direct analysis.
virtual void PrintOptimizationParametersWithDescriptions (IVector parameters)
Prints values of the specified optimization parameters together with ranges and descriptions.
Public Member Functions inherited from IG.Script.LoadableScriptShellNeural
LoadableScriptShellNeural ()
override void Analyse (Num.IAnalysisResults anRes)
Dummy analysis, jsut throws the exception.
override void TransfSimulationToNeuralInput (IVector original, ref IVector result)
Transforms the specified vector of simulation input parameters to the vector of neural input parameters and stores the vector to the specified variable.
override void TransfNeuralToSimulationInput (IVector original, ref IVector result)
Transforms the specified vector of neural input parameters to the vector of simulation input parameters and stores the vector to the specified variable.
override void TransfSimulationToNeuralOutput (IVector original, ref IVector result)
Transforms the specified vector of simulation output values (results) to the vector of neural output values and stores the vector to the specified variable.
override void TransfNeuralToSimulationOutput (IVector original, ref IVector result)
Transforms the specified vector of neural output values to the vector of simulation output values (results) and stores the vector to the specified variable.
Public Member Functions inherited from IG.Script.LoadableScriptShellNeuralBase
LoadableScriptShellNeuralBase ()
override void Analyse (Num.IAnalysisResults anRes)
Dummy analysis, jsut throws the exception.
virtual string Test (string[] arguments)
Runs a custom basic test.
virtual string Custom (string[] arguments)
Runs a custom test.
virtual string RunParallelSimulations (string[] arguments)
Runs multiple simulations in parallel threads and saves results in each parallel thread.
virtual string CollectParallelSimulationResults (string[] arguments)
Collects results of simulations run in parallel threads, joins them into a single object and saves them.
override void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds commands to the internal interpreter.
virtual IVector TestApproximation (IVector parameters)
Performs a test approximation at the specified vector of parameters and outputs and returns results.
virtual IVector[][] TestApproximationTable (int numPoints)
Calculates a table of specified number of approximations, with parameters running between two points that are chosen by the algorithm.
virtual IVector[][] TestApproximationTable (IVector param1, IVector param2, int numPoints)
Performs a table of approximatinos between two specified vectors of approximation input parameters, and outputs results. It also returns the table of results (approximated output values in form of vectors).
virtual AnalysisResults TestAnalysis (IVector parameters)
Performs test analysis at the specified optimization parameters and outputs results.
virtual AnalysisResults[] TestAnalysisTable (int numPoints)
Calculates a table of specified number of analyses, with parameters running between two points that are chosen by the algorithm.
virtual AnalysisResults[] TestAnalysisTable (IVector param1, IVector param2, int numPoints)
Performs a table of direct analyses between two specified vectors of optimization parameters, and outputs results. It also returns the table of analysis results.
virtual void OptimizeSimplex ()
delegate string ParallelRunDelegate (int threadIndex)
virtual void ParSimBegin (int numThreads)
Launches parallel jobs.
virtual void GatherParallelResults (int numThreads)
Reads results form all parallel threads, gathers them in a single training set, and saves them in the template optimiation directory.
virtual string ParSimGetOptimizationDirectoryPath (int threadIndex)
Returns path to the directory containing optimization data for the specified parallel thread.
virtual string ParSimGetMutexName (int threadIndex)
Returns name of the mutex for locking data on disk that is used by the specified parallel thread.
virtual string ParSimGetParallelResultsFilePath (int threadIndex)
Returns path of the file where resuls of calculation in the specified parallel thread are stored.
virtual string GetParallelResultFilePath ()
Returns path of the file where resuls of calculation in the specified parallel thread are stored.
virtual void ParSimPreparelDirectory (int threadIndex)
Prepares data for running calculations in the parallel thread with the specified index.
void ParSimAddResults (int threadIndex, SampledDataSet results)
Reads results of the specified thread and adds them to the existing training set.
string ParSimRunJob (int threadIndex)
Runs the job in the specified parallel thread.
virtual void ParSimGetNextInput (ref IVector simInput)
Generates the next vector of simulation input parameters that will be used for calculation of a new parallel simulation.
virtual void ParSimGetNextNeuralInput (ref IVector simInput)
Generates the next vector of neural input parameters that will be used for calculation of a new training element.
virtual string ParSimGetSimulationDirectoryPath (int threadIndex)
Returns the simulation directory for the specified parallel calculation thread.
virtual
IResponseEvaluatorVectorSimple ParSimGetSimulator (int threadIndex)
Creates simulator file manager for the simulator that will the specified parallel task.
List< SampledDataElement > GetTrainingElements (bool includeVerificationPoints)
Returns a list of all neural training elements.
List< SampledDataElement > GetTrainingElements (bool includeVerificationPoints, bool includeNonVerificationPoints)
Returns a list of all neural training elements.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, params IVector[] points)
For each point in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, bool printIndividualPointsComp, params IVector[] points)
For each point in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, params SampledDataElement[] points)
For each point (training element) in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, bool printIndividualPointsComp, params SampledDataElement[] points)
For each point (training element) in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
virtual IVector GetRandomNeuralInput ()
Creates and returns a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters.
virtual void GetRandomNeuralInput (IRandomGenerator rand, ref IVector result)
Generates a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters, and stores it to the specified vector.
virtual IVector GetRandomNeuralInput (IRandomGenerator rand)
Creates and returns a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters.
virtual void GetRandomNeuralInput (ref IVector result)
Generates a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters.
virtual IVector GetRandomNeuralOutput ()
Creates and returns a random vector of neural output values whose elements (components) lie within the lower and upper bounds on values.
virtual IVector GetRandomNeuralOutput (IRandomGenerator rand)
Creates and returns a random vector of neural output values whose elements (components) lie within the lower and upper bounds on values.
virtual void GetRandomNeuralOutput (ref IVector result)
Generates a random vector of neural output values whose elements (components) lie within the lower and upper bounds on values.
virtual void GetRandomNeuralOutput (IRandomGenerator rand, ref IVector result)
Generates a random vector of neural output values whose elements (components) lie within the lower and upper bounds on neural output values, and stores it to the specified vector.
virtual void PrepareNeuronsTable (int minNeurons, int maxNeurons, int numNeurons, ref int[] neurpnsTable)
Prepares table of neurons in geometric sequence.
void TrainANN (int annType, int NumNeurons, int MaxEpochs, int EpochsInBundle, double LearnignRate, double Momentum, double InputSafetyFactor, double OutputSafetyFactor, double PercentVerificationPoints)
Train the artificial neural network.
virtual string CreateDistortedModelData (string[] arguments)
Creates data for distorted model and stores the data in the specified directory.
void SaveSensitivityCSV ()
Saves sensitivity test in csv file.
Public Member Functions inherited from IG.Lib.LoadableScriptShellBase
LoadableScriptShellBase ()
Constructor.
virtual bool RepairSimulationParameters (IVector parameters)
Repairs simulation parameters, if necessary, in such a way that values are consistent with simuation data (e.g. spacing of nodes).
virtual void SimulatorCalculateResponse (IResponseEvaluatorVectorSimple simulator, IVector inputParameters, ref IVector outputValues)
Calculates vector response by the specified simulator, and stores output values to the specified vector variable.
void SimulatorCalculateResponse (IVector parameters, ref IVector outputValues)
Calculates vector response by the main simulator of the script, and stores output values to the specified vector variable.
Public Member Functions inherited from IG.Lib.LoadableScriptOptShellBaseControllable
LoadableScriptOptShellBaseControllable ()
Creates a LoadableScriptOptBase object.
Public Member Functions inherited from IG.Lib.LoadableScriptOptBase
LoadableScriptOptBase ()
Creates the LoadableScriptOptBase object.
Public Member Functions inherited from IG.Lib.LoadableScriptBase
LoadableScriptBase ()
Argument-less constructor. If argument-less constructor is called then initialization is not performed and will be performed later.
string Run (string[] arguments)
Performs the action of this object. Override this in derived classes!
void Initialize (string[] arguments)
Initializes the object. If not called explicitly, this method is automatically called at the first call to the Run method.
virtual string Script_DefaultInitialize (string[] arguments)
Default initialization method for scripts.
virtual string Script_DefaultRun (string[] arguments)
Default run method for the script. Can be used when only installed commands are run by hte script.
virtual
ICommandLineApplicationInterpreter Script_CreateInterpreterWithoutCommands ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
delegate string Script_CommandDelegate (string[] args)
Delegate for commands that are installed on script's internal interpreter (property Script_Interpreter).
void Script_AddCommand (string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
virtual void Script_AddCommand (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings, string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
string Script_GetHelpString (string scriptCommandName)
Returns help string for internal script command with specified name, or null if help string is not installed for such a command.
void Script_PrintCommandsHelp ()
Prits help for the installed internal commands of the script.
virtual bool Script_ContainsCommand (string commandName)
Returns true if the internal script's interpreter contains a command with specified name, false otherwise.
virtual bool Script_ContainsScriptCommand (string commandName)
Returns true if the specified command is script command (i.e. its first argument is command-name and it is run through the Script_CommandAdapter object).
virtual void Script_RemoveCommand (string commandName)
Removes the specified internal script command from the internal interpreter of the current scripting object.
virtual void Script_RemoveAllCommands ()
Removes ALL internal script commands from the internal interpreter of the current scripting object.
string Script_Run (string[] arguments)
Runs internal script command.
string Script_Run (string commandName, params string[] otherArguments)
Runs internal script command.
virtual void Script_PrintArguments (string messageString, string[] arguments)
Prints the specified array of string arguments (usually passed as command-line arguments).
Public Attributes
int AnalysisOutputLevel = 0
Level of output during analysis.
double dPenalty = 0.05
Characteristic length for penalty function
double hPenalty = 5
Characteristic height of penalty function.
Public Attributes inherited from IG.Script.S_11_10_Clanek_Neural_Base
int BilletDimensionIndex = 10
double BilletDimension = 140
Public Attributes inherited from IG.Script.LoadableScriptShellNeuralBase
const string ConstTest = "Test"
Comamnd name for test.
const string ConstHelpTest = "Test of functionality."
const string ConstCustom = "Custom"
Comamnd name for test.
const string ConstHelpCustom = "Custom command that can be quickly modified as needed, for performing."
const string ConstRunParallel = "RunParallel"
Comamnd name for running parallel simulations.
const string ConstHelpRunParallel = "Runs parallel simulations. Args: numThreads numRunsPerThread"
const string ConstCollectParallel = "collectparallel"
Comamnd name for running parallel simulations.
const string ConstHelpCollectParallel = "Collects results of parallel simulations. Args: numThreads"
const string ConstCreateDistortedModelData = "CreateDistortedModelData"
Comamnd name for testing network response for centered point from verification or training points for all Inputs/outputs.
const string ConstHelpCreateDistortedModelData
string ParallelResultsFilename = "ParallelResults"
int ParSimNumRuns = 2
Number of runs of simulator in each parallel thread.
int ParSimNumThreads = 2
Number of jobs that can be executed in parallel.
int ParSimSavingFrequency = 4
Specifies how often the results are saved.
string ParSimResultFilename = "GatheredNeuralTrainingData.json"
bool saveGraphs = false
Public Attributes inherited from IG.Lib.LoadableScriptBase
const string ConstDefaultHelp = "Help"
Default command name for help.
const string ConstHelpDefaultUniversal = "?"
Universal name of the help command.
const string ConstDefaultTestScrip = "TestScript"
Default command name for test method.
Protected Member Functions
override void InitializeThis (string[] arguments)
Initializes the current object.
override string RunThis (string[] arguments)
Runs action of the current object.
Protected Member Functions inherited from IG.Script.LoadableScriptShellNeuralBase
virtual void LoadJson (string path, ref INeuralApproximator network)
Loads the neural network approximator from the specified file.
virtual void SaveJson (INeuralApproximator approximator, string trainedNetworkFilePath)
Saves the specified trained network to a file.
virtual INeuralApproximator CreateApproximator (int annType=2)
Creates and returns a new neural network approximator, with the basic properties pre-set to default values, dependent on the type of the requires approximator.
virtual void PrintInternalCommandAndArguments (string[] arguments)
Prints internal command being executed and its actual arguments
virtual void GetSimulationInputDefault (ref IVector result)
Gets the vector of default values of simulation parameters and stores it in the specified vector.
virtual void GetSimulationInputMin (ref IVector result)
Gets the vector of lower bounds on simulation parameters and stores it in the specified vector.
virtual void GetSimulationInputMax (ref IVector result)
Gets the vector of upper bounds on simulation parameters and stores it in the specified vector.
virtual void ParSimPrepareDirectories (int numThreads)
Prepares data for the specified number of parallel execution threads.
virtual void ParSimWaitAllCompletion ()
Waits until all parallel jobs complete.
virtual void ParSimAsyncCallback (IAsyncResult ar)
Callback method for asynchronous runs.
virtual string ParSimGetDirectoryExtension (int threadIndex)
Returns directory extension for data directory used in the specified parallel calculation thread.
virtual void GetNeuralInputDefault (ref IVector result)
Gets the vector of default values of neural parameters and stores it in the specified vector.
virtual void GetNeuralInputMin (ref IVector result)
Gets the vector of lower bounds on neural parameters and stores it in the specified vector.
virtual void GetNeuralInputMax (ref IVector result)
Gets the vector of upper bounds on neural parameters and stores it in the specified vector.
virtual void GetRandomNeuralInputFromDataDefinition (IRandomGenerator rand, ref IVector result)
Generates a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters, and stores it to the specified vector.
Protected Member Functions inherited from IG.Lib.LoadableScriptShellBase
virtual void CreateNewSimulator (string simulatorPath, ref IResponseEvaluatorVectorSimple simulator)
Creates a new simulator that uses the specified simulator directory, and stores it to the specified variable.
Protected Member Functions inherited from IG.Lib.LoadableScriptBase
delegate string CommandMethod (string commandName, string[] args)
Delegate for internal command methods.
ICommandLineApplicationInterpreter Script_CreateInterpreter ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
virtual string Script_CommandHelp (string[] arguments)
Prints help.
virtual string Script_CommandTestScript (string[] arguments)
Prints help.
Protected Attributes
IVector auxNeuralInput
Protected Attributes inherited from IG.Script.LoadableScriptShellNeuralBase
IVector _simulationInputDefault
IVector _simulationInputMin
IVector _simulationInputMax
IBoundingBox _simulationInputBounds
string _parallelResultsFilename = "ParallelResults"
string _parallelResultsFileExtension = ".json"
List< IAsyncResult > ParallelResults
object ParSimProcessDelayLock = new object()
int ParSimProcessDelayMilliseconds = 500
Minimal delay between two successive launches of simulator processes, in milliseconds. This delay is introduced in order to prevent unusual errors that occur when running two simulator processes at approcimately the same time (although they use completely separate data directory structures).
List< IVector > _sensitivityResultsVerification
List< IVector > _sensitivityResultsTraining
INeuralApproximator _trainedNetwork
SampledDataSet _trainingData
SampledDataSet _verificationData
IVector _neuralInputDefault
IVector _neuralInputMin
IVector _neuralInputMax
IBoundingBox _neuralInputBounds
Protected Attributes inherited from IG.Lib.LoadableScriptShellBase
IResponseEvaluatorVectorSimple _simulator
string _projectName
string _simulationName
Protected Attributes inherited from IG.Lib.LoadableScriptOptBase
StopWatch1 _timer = null
bool _checkOptimizationDirectoryExistence = true
Whether to check existence of optimization directory when set. Also applies to working directory.
Protected Attributes inherited from IG.Lib.LoadableScriptBase
string _embeddedCommandName = null
int _outputLevel = DefaultOutputLevel
ICommandLineApplicationInterpreter _script_interpreter
Properties
virtual
NeuraApproximationFileManager NeuralFM [get]
File manager that provides access to trained neural network and related data.
virtual INeuralApproximator TrainedNetwork [get]
Trained neural network.
virtual InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
virtual SampledDataSet NeuralTrainingData [get]
Gets the training data.
virtual int NumAllTrainingPoints [get]
Gets number of all training points, including verification points.
virtual IVector SomeNeuralInput [get]
Returns some vector of input parameters that is within the range.
virtual IVector NeuralInputParameters [get]
Vector of input parameters read form the file.
Properties inherited from IG.Script.S_11_10_Clanek_Neural_Base
override int NumNeuralParameters [get, protected set]
Number of neural network input parameters.
override int NumNeuralOutputs [get, protected set]
Number of neural network output values.
override int NumOptimizationParameters [get, protected set]
Number of optimization parameters.
override int NumOptimizationConstraints [get, protected set]
Number of optimization constraints.
bool IsAnalysisDataInitialized [get, protected set]
Flag indicating whether auxiliary analysis data is initialized, i.e. whether the InitOptimizationData method has been called.
IVector ParamOptMin [get, protected set]
Minimal values of optimization parameters.
IVector ParamOptMax [get, protected set]
Maximal values of optimization parameters.
IVector ParamOptScales [get, protected set]
Scaling lengths for optimization parameters.
IVector ParamOptTargets [get, protected set]
Targeted optimization parameters.
string[] ParamOptNames [get, protected set]
Names of optimization parameters.
IVector OutputMin [get, protected set]
Minimal values for NN approximation output quantities.
IVector OutputMax [get, protected set]
Maximal values for NN approximation output quantities.
IVector OutputScales [get, protected set]
Scaling lengths for NN approximation output quantities.
IVector OutputTargets [get, protected set]
Targeted output values.
string[] OutputNames [get, protected set]
Names of neural network's approximation output quantities.
Properties inherited from IG.Script.LoadableScriptShellNeural
override
IResponseEvaluatorVectorSimple Simulator [get, protected set]
override int NumOptimizationParameters [get, protected set]
Throws NotImplementedException.
override int NumOptimizationConstraints [get, protected set]
Throws NotImplementedException.
Properties inherited from IG.Script.LoadableScriptShellNeuralBase
abstract int NumOptimizationParameters [get, protected set]
Number of optimization parameters.
abstract int NumOptimizationConstraints [get, protected set]
Number of optimization constraints.
virtual InputOutputDataDefiniton SimulationDataDefinition [get]
Simulation data definition (input and output used by simulator).
virtual int NumSimulationParameters [get, protected set]
Number of simulation input parameters.
virtual int NumSimulationOutputs [get, protected set]
Number of simulation output values.
virtual IBoundingBox SimulationInputBounds [get, protected set]
Bounds on simulation input parameters.
string ParallelResultsFileExtension [get, protected set]
virtual
NeuraApproximationFileManager NeuralFM [get]
File manager that provides access to trained neural network and related data.
virtual INeuralApproximator TrainedNetwork [get, protected set]
Trained neural network.
virtual List< IVector > SensitivityVerificationResults [get, protected set]
virtual List< IVector > SensitivityTrainingResults [get, protected set]
virtual INeuralApproximator XXX_TrainedNetwork [get, protected set]
Trained neural network.
virtual InputOutputDataDefiniton NeuralDataDefinition [get, protected set]
Neural data definition.
virtual SampledDataSet TrainingData [get, set]
virtual SampledDataSet VerificationData [get, set]
virtual int NumNeuralParameters [get, protected set]
Number of neural network input parameters.
virtual int NumNeuralOutputs [get, protected set]
Number of neural network output values.
virtual IBoundingBox NeuralInputBounds [get, protected set]
Bounds on neural input parameters.
virtual SampledDataSet NeuralTrainingData [get]
Gets the training data.
virtual int NumAllTrainingPoints [get]
Gets number of all training points, including verification points.
virtual IVector SomeNeuralInput [get]
Returns some vector of input parameters that is within the range.
virtual IVector NeuralInputFromFile [get]
Vector of input parameters read form the file.
Properties inherited from IG.Lib.LoadableScriptShellBase
abstract
IResponseEvaluatorVectorSimple Simulator [get, protected set]
Simulator that is used to calculate vector response.
virtual bool SimulatorSuppressOutput [get, set]
A flag indicating whether simulators should suppress output or not, default is false.
virtual string ProjectName [get, protected set]
Name of the current project, used in some simulation and other interfaces.
virtual string SimulationName [get, protected set]
Name of the current simulation, used in some simulation and other interfaces.
Properties inherited from IG.Lib.LoadableScriptOptShellBaseControllable
bool IsLoadable [get, set]
Either or not the script can be dynamically loaded.
bool IsRunnable [get, set]
Either or not the script can be run (some scripts only support other tasks).
Properties inherited from IG.Lib.LoadableScriptOptBase
StopWatch1 Timer [get]
virtual IRandomGenerator Random [get, protected set]
Random generator used by the current object.
virtual string OptimizationDirectory [get, set]
Optimization directory. This directory is a base directory for data used optimization and neural network - based approximation servers and for other directories that contain data for specific tasks.
virtual string WorkingDirectory [get, set]
Working directory. This directory is a base directory for data used by the script. It is usually obtained as parent directory of the optimization directory.
virtual IAnalysis Analysis [get, protected set]
Direct analysis object used in optimization. Initialized when first accessed with the embedded class, whose analysis function calls Analyse(...).
Properties inherited from IG.Lib.LoadableScriptBase
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
string[] InitializationArguments [get, set]
Arguments used by the initialization method. WARNING: arguments can only be set before initialization is performed. Initialization is performed either implicitly at the first call to the Run method or explicitly by calling the Initialize method.
virtual bool IsInitialized [get, protected set]
Whether the object has been initialized or not.
static int DefaultOutputLevel [get, set]
int OutputLevel [get, set]
Level of output to console produced by some operations of the current object.
virtual
ICommandLineApplicationInterpreter Script_Interpreter [get, protected set]
Script's internal interpreter that takes care for execution of installed internal commands.
SortedList< string, string > Script_CommandHelpStrings [get]
Contains help strings associated with script commands installed on interpreter.
Properties inherited from IG.Lib.ILoadableScript
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
string[] InitializationArguments [get, set]
Arguments used by the initialization method.
bool IsInitialized [get]
Whether the object has been initialized or not.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Properties inherited from IG.Lib.ILoadableScriptC
bool IsLoadable [get, set]
Either or not the script can be dynamically loaded.
bool IsRunnable [get, set]
Either or not the script can be run (some scripts only support other tasks).
Properties inherited from IG.Num.INeuralModel
INeuralApproximator TrainedNetwork [get]
Traint artificial neural network.
InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
Private Attributes
IVector auxNeuralOutput
NeuraApproximationFileManager _neuralFileManager
INeuralApproximator _trainedNetwork
InputOutputDataDefiniton _neuralDataDefinition
SampledDataSet _neuralTrainingData
IVector _someInput
Additional Inherited Members
Static Public Attributes inherited from IG.Script.LoadableScriptShellNeuralBase
static string TrainedNetworkAlternativeLovation = null
If different than null, this static property provides alternative location of the file which neural network approximator is resd from, in terms of path relative to optimization directory.
Constructor & Destructor Documentation
IG.Script.Script_11_10_clanek_neural_01.Script_11_10_clanek_neural_01 () inline
Member Function Documentation
override void IG.Script.Script_11_10_clanek_neural_01.InitializeThis (string[] arguments) inline protected virtual
Initializes the current object.
Reimplemented from IG.Script.LoadableScriptShellNeural.
override string IG.Script.Script_11_10_clanek_neural_01.RunThis (string[] arguments) inline protected virtual
Runs action of the current object.
Parameters
arguments Command-line arguments of the action.
Reimplemented from IG.Script.LoadableScriptShellNeural.
References IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), and IG.Lib.StopWatch1.Time.
virtual double IG.Script.Script_11_10_clanek_neural_01.PenaltyTerm (double constraintFunctionValue) inline virtual
Calculates a single penalty term dependent on the value of the constraint function.
Parameters
constraintFunctionValue Value of the constraint function for which penalty term is evaluated.
virtual double IG.Script.Script_11_10_clanek_neural_01.PenaltyTermsSum (IVector parameters) inline virtual
Returns the sum of all penalty terms.
Parameters
parameters Optimization parameters.
Returns
virtual void IG.Script.Script_11_10_clanek_neural_01.CheckAnalysisRequest (IAnalysisResults anRes) inline virtual
Checks the specified analysis request and throws exception in case of inconsistency.
Parameters
anRes Object containing analaysis request data.
References IG.Num.IAnalysisResults.Parameters, IG.Num.IAnalysisResults.ReqConstraintHessians, IG.Num.IAnalysisResults.ReqObjective, IG.Num.IAnalysisResults.ReqObjectiveGradient, and IG.Num.IAnalysisResults.ReqObjectiveHessian.
virtual double IG.Script.Script_11_10_clanek_neural_01.Objective1 (IVector param) inline virtual
Calculates and returns value of the objective function at specified vector of parameters.
override void IG.Script.Script_11_10_clanek_neural_01.Analyse (IAnalysisResults anRes) inline virtual
Performs direct analysis for optimization problems. This method must be overridden in derived classes where one wants to have direct analysis defined.
Parameters
anRes IAnalysisResults object where input parameters are loaded on the call, and where analysis results are stored after the call.
In order to perform the direct analysis, an embedded Analysis object is used. This object's analysis method calls the current Analyse method in order to actually perform the analysis.
Implements IG.Lib.LoadableScriptOptBase.
References IG.Num.IAnalysisResults.CalculatedObjective, IG.Num.IAnalysisResults.Objective, IG.Num.IAnalysisResults.Parameters, and IG.Num.IAnalysisResults.ReqObjective.
virtual SampledDataElement IG.Script.Script_11_10_clanek_neural_01.GetTrainingElement (int i) inline virtual
Gets the training element with the specified index (chosen out of al training points, including verificaion points).
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
virtual bool IG.Script.Script_11_10_clanek_neural_01.IsVerificationPoint (int trainingPointIndex) inline virtual
Whether the training point with the specified index is a verification points and has not been used in training.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
List<SampledDataElement> IG.Script.Script_11_10_clanek_neural_01.GetTrainingElements (bool includeVerificationPoints) inline
Returns a list of all neural training elements.
The returned list is created anew.
Parameters
includeVerificationPoints Flag indicating whether verification points are also included in the returned list.
List<SampledDataElement> IG.Script.Script_11_10_clanek_neural_01.GetTrainingElements (bool includeVerificationPoints, bool includeNonVerificationPoints) inline
Returns a list of all neural training elements.
The returned list is created anew.
Parameters
includeVerificationPoints Flag indicating whether verification points are also included in the returned list.
includeNonVerificationPoints Flag indicating whether non-verification points are included in the returned list.
virtual void IG.Script.Script_11_10_clanek_neural_01.GetNeuralInputPerturbance (double ratio, ref IVector perturbance) inline virtual
Returns a perturbance vector whose componenets represent magnitudes of perturbances of neural input parameters with the specified relative ratio with corresponding parameters' scaling lengths.
Parameters
ratio Ratio between perturbance component and scaling length of each parameter.
Scaling length is either the difference between maximal and minimal value, or 0.
Parameters
perturbance Vector where perturbance magnitudes are stored.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
virtual void IG.Script.Script_11_10_clanek_neural_01.GetNeuralOutputPerturbance (double ratio, ref IVector perturbance) inline virtual
Returns a perturbance vector whose componenets represent magnitudes of perturbances of neural output values with the specified relative ratio with corresponding values' scaling lengths.
Parameters
ratio Ratio between perturbance component and scaling length of each value.
Scaling length is either the difference between maximal and minimal value, or 0.
Parameters
perturbance Vector where perturbance magnitudes are stored.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
virtual void IG.Script.Script_11_10_clanek_neural_01.GetNeuralInputVector (double relativeComponents, ref IVector inputVector) inline virtual
Returns an input vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
Parameters
relativeComponents Relative coordinate of all vector components of the returned vector, which run from 0 to 1 within the range of components (defined by minimal and maximal bounds).
inputVector Object where generated vector is stored.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
virtual void IG.Script.Script_11_10_clanek_neural_01.GetNeuralOutputVector (double relativeComponents, ref IVector outputVector) inline virtual
Returns an output vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
Parameters
relativeComponents Relative coordinate of all vector components of the returned vector, which run from 0 to 1 within the range of components (defined by minimal and maximal bounds).
inputVector Object where generated vector is stored.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
virtual void IG.Script.Script_11_10_clanek_neural_01.GetNeuralInputVector (IVector relativeComponents, ref IVector inputVector) inline virtual
Returns an input vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
Parameters
relativeComponents Relative coordinates of all vector components of the returned vector, which run from 0 to 1 within the range of components (defined by minimal and maximal bounds).
inputVector Object where generated vector is stored.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
virtual void IG.Script.Script_11_10_clanek_neural_01.GetNeuralOutputVector (IVector relativeComponents, ref IVector outputVector) inline virtual
Returns an output vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
Parameters
relativeComponents Relative coordinates of all vector components of the returned vector, which run from 0 to 1 within the range of components (defined by minimal and maximal bounds).
inputVector Object where generated vector is stored.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
virtual void IG.Script.Script_11_10_clanek_neural_01.GetNeuralInputRelative (IVector inputVector, ref IVector relativeComponents) inline virtual
Calculates relative components (running from 0 to 1 within bounds for specified vector component) for the specified vector of neural input parameters.
Parameters
inputVector Vector of input parameters for neural network.
relativeComponents Vector where transformed relative components of the specified vector are stored.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
virtual void IG.Script.Script_11_10_clanek_neural_01.GetNeuralOutputRelative (IVector outputVector, ref IVector relativeComponents) inline virtual
Calculates relative components (running from 0 to 1 within bounds for specified vector component) for the specified vector of neural output values.
Parameters
outputVector Vector of output values in neural network approximator's output space.
relativeComponents Vector where transformed relative components of the specified vector are stored.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
virtual double IG.Script.Script_11_10_clanek_neural_01.InputDistance (IVector v1, IVector v2) inline virtual
Returns measure of distance between two vectors in the space of input parameters. Euclidean norm scaled accorging to individual parameter ranges is returned.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
virtual double IG.Script.Script_11_10_clanek_neural_01.OutputDistance (IVector v1, IVector v2) inline virtual
Returns measure of distance between two vectors in the space of output parameters. Euclidean norm scaled accorging to individual parameter ranges is returned.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Num.InputOutputDataDefiniton.OutputLength.
virtual double IG.Script.Script_11_10_clanek_neural_01.InputDistance (IVector v1, int trainingPointIndex) inline virtual
Returns measure of distance between the specified neural input vector and vector of input parameters of the training point with the specified index.
Parameters
v1 First vector in space of input parameter for calculating distance.
trainingPointIndex Index of training point for obtaining the second input vector.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
virtual double IG.Script.Script_11_10_clanek_neural_01.OutputDistance (IVector v1, int trainingPointIndex) inline virtual
Returns measure of distance between the specified neural output values vector and vector of output values of the training point with the specified index.
Parameters
v1 First vector in space of output values for calculating distance.
trainingPointIndex Index of training point for obtaining the second output vector.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
virtual int IG.Script.Script_11_10_clanek_neural_01.GetClosestInputIndex (IVector v1, bool includeVerificationPoints) inline virtual
Returns index of training element with the shortest distance of its input parameters to the specified vector.
Parameters
v1 Vector to which the distance is observed.
countVerificationPoints Whether verification points are included or not.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
virtual int IG.Script.Script_11_10_clanek_neural_01.GetClosestOutputIndex (IVector v1, bool includeVerificationPoints) inline virtual
Returns index of training element with the shortest distance of its output values to the specified vector of output values.
Parameters
v1 Vector to which the distance is observed.
countVerificationPoints Whether verification points are included or not.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
void IG.Script.Script_11_10_clanek_neural_01.TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, params IVector[] points) inline
For each point in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
Result of this test can give some rough feeling about filling of space (but very rough because anisotropy can not be detected in this way).
Parameters
numClosestPoints Number of closest points that are written.
includeVerificationPoints Whether verification points are included or not.
printByComponents If true then results are also printed by components.
points Points that are checked for closest trainnig data points.
void IG.Script.Script_11_10_clanek_neural_01.TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, bool printIndividualPointsComp, params IVector[] points) inline
For each point in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
For individual points, differences are not printed by components.
Result of this test can give some rough feeling about filling of space (but very rough because anisotropy can not be detected in this way).
Parameters
numClosestPoints Number of closest points that are written.
includeVerificationPoints Whether verification points are included or not.
printByComponents If true then results are also printed by components.
printIndividualPointsComp If true then individual components of differences are printed for individual points (otherwise, they are only printed in statistics).
points Points that are checked for closest trainnig data points.
References IG.Num.SampledDataElement.Index, IG.Num.SampledDataElement.InputParameters, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.VectorBase.Subtract(), IG.Lib.StopWatch1.Time, IG.Num.IVector.ToString(), and IG.Lib.StopWatch1.TotalTime.
void IG.Script.Script_11_10_clanek_neural_01.TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, params SampledDataElement[] points) inline
For each point (training element) in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
For individual points, differences are not printed by components.
Result of this test can give some rough feeling about filling of space (but very rough because anisotropy can not be detected in this way).
Parameters
numClosestPoints Number of closest points that are written.
includeVerificationPoints Whether verification points are included or not.
printByComponents If true then results are also printed by components.
points Points that are checked for closest trainnig data points.
void IG.Script.Script_11_10_clanek_neural_01.TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, bool printIndividualPointsComp, params SampledDataElement[] points) inline
For each point (training element) in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
Result of this test can give some rough feeling about filling of space (but very rough because anisotropy can not be detected in this way).
Parameters
numClosestPoints Number of closest points that are written.
includeVerificationPoints Whether verification points are included or not.
printByComponents If true then results are also printed by components.
printIndividualPoints If true then individual components of differences are printed for
Parameters
points Points that are checked for closest trainnig data points.
References IG.Num.SampledDataElement.Index, IG.Num.SampledDataElement.InputParameters, IG.Num.SampledDataElement.OutputValues, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.VectorBase.Subtract(), IG.Lib.StopWatch1.Time, IG.Num.IVector.ToString(), and IG.Lib.StopWatch1.TotalTime.
virtual void IG.Script.Script_11_10_clanek_neural_01.NeuralCalculate (params double[] inputParameters) inline virtual
Calculates approximation at specified input parameters.
Parameters
inputParameters Input parameters.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
virtual void IG.Script.Script_11_10_clanek_neural_01.NeuralCalculate (IVector inputParameters) inline virtual
Calculates approximation at specified input parameters.
Parameters
inputParameters Input parameters.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
virtual void IG.Script.Script_11_10_clanek_neural_01.NeuralCalculate (IVector inputParameters, ref IVector outputValues) inline virtual
Calculates approximation at specified input parameters.
Parameters
inputParameters Input parameters.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
virtual List<SampledDataElement> IG.Script.Script_11_10_clanek_neural_01.GetRandomTrainingElements (int numElements, bool includeVerificationPoints) inline virtual
Creates and returns a list of training elements that are randomly chosen from the current training set. Trainingpoints that are not verification points are always included in the set of points for selection.
The global random generator is used to select training elements.
Parameters
numElements Number of elemnts that are randomly selected and put into the returned list. If the number of all available elements is smaller than this number then exception is thrown.
includeVerificationPoints A flag indicationg whether verification elements should also be included.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.RandomGenerator.Global.
virtual List<SampledDataElement> IG.Script.Script_11_10_clanek_neural_01.GetRandomTrainingElements (int numElements, bool includeVerificationPoints, bool includeNonVerificationPoints) inline virtual
Creates and returns a list of training elements that are randomly chosen from the current training set.
The global random generator is used to select training elements.
Parameters
numElements Number of elemnts that are randomly selected and put into the returned list. If the number of all available elements is smaller than this number then exception is thrown.
includeVerificationPoints A flag indicationg whether verification elements should also be included.
includeNonVerificationPoints A flag indicating whether non-verification elements should be included in the list.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.RandomGenerator.Global.
virtual List<SampledDataElement> IG.Script.Script_11_10_clanek_neural_01.GetRandomTrainingElements (IRandomGenerator rand, int numElements, bool includeVerificationPoints) inline virtual
Creates and returns a list of training elements that are randomly chosen from the current training set. Trainingpoints that are not verification points are always included in the set of points for selection.
Parameters
rand Random generator used for random selection of training elements.
numElements Number of elemnts that are randomly selected and put into the returned list. If the number of all available elements is smaller than this number then exception is thrown.
includeVerificationPoints A flag indicationg whether verification elements should also be included.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
virtual List<SampledDataElement> IG.Script.Script_11_10_clanek_neural_01.GetRandomTrainingElements (IRandomGenerator rand, int numElements, bool includeVerificationPoints, bool includeNonVerificationPoints) inline virtual
Creates and returns a list of training elements that are randomly chosen from the current training set.
Parameters
rand Random generator used for random selection of training elements.
numElements Number of elemnts that are randomly selected and put into the returned list. If the number of all available elements is smaller than this number then exception is thrown.
includeVerificationPoints A flag indicationg whether verification elements should also be included.
includeNonVerificationPoints A flag indicating whether non-verification elements should be included in the list.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.IRandomGenerator.Next().
virtual void IG.Script.Script_11_10_clanek_neural_01.TestDistances (int referencePointIndex, int maxNumPoints) inline virtual
Test of distances of a specified number of training points with respect to the training point with specified index, in the input parameters space as well as in the output parameter space.
Parameters
referencePointIndex Index of the point for which distances are calculated.
maxNumPoints Maximal number of points taken in the test.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.IBoundingBox.GetMax(), and IG.Num.IBoundingBox.Update().
virtual void IG.Script.Script_11_10_clanek_neural_01.TestNeuralSpeed (int numEvaluations) inline virtual
Performs test of speed of calculation of neural network.
Parameters
numEvaluations Number of times the approximation is calculated.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
virtual void IG.Script.Script_11_10_clanek_neural_01.PrintNeuralData () inline virtual
This example demonstrates how to extract data necessary for definition of optimization problems.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputOutputElementDefinition.Description, IG.Num.InputOutputDataDefiniton.LoadJson(), IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Num.InputOutputElementDefinition.Name, IG.Neural.NeuraApproximationFileManager.NeuralDataDefinitionPath, and IG.Num.InputOutputElementDefinition.TargetValue.
Member Data Documentation
int IG.Script.Script_11_10_clanek_neural_01.AnalysisOutputLevel = 0
Level of output during analysis.
This region defines how neural network input parameters are mapped to optimization parameters and vice versa.
double IG.Script.Script_11_10_clanek_neural_01.dPenalty = 0.05
Characteristic length for penalty function
double IG.Script.Script_11_10_clanek_neural_01.hPenalty = 5
Characteristic height of penalty function.
IVector IG.Script.Script_11_10_clanek_neural_01.auxNeuralInput protected
IVector IG.Script.Script_11_10_clanek_neural_01.auxNeuralOutput private
NeuraApproximationFileManager IG.Script.Script_11_10_clanek_neural_01._neuralFileManager private
INeuralApproximator IG.Script.Script_11_10_clanek_neural_01._trainedNetwork private
InputOutputDataDefiniton IG.Script.Script_11_10_clanek_neural_01._neuralDataDefinition private
SampledDataSet IG.Script.Script_11_10_clanek_neural_01._neuralTrainingData private
IVector IG.Script.Script_11_10_clanek_neural_01._someInput private
Property Documentation
virtual NeuraApproximationFileManager IG.Script.Script_11_10_clanek_neural_01.NeuralFM get
File manager that provides access to trained neural network and related data.
virtual INeuralApproximator IG.Script.Script_11_10_clanek_neural_01.TrainedNetwork get
Trained neural network.
virtual InputOutputDataDefiniton IG.Script.Script_11_10_clanek_neural_01.NeuralDataDefinition get
Neural data definition.
virtual SampledDataSet IG.Script.Script_11_10_clanek_neural_01.NeuralTrainingData get
Gets the training data.
virtual int IG.Script.Script_11_10_clanek_neural_01.NumAllTrainingPoints get
Gets number of all training points, including verification points.
virtual IVector IG.Script.Script_11_10_clanek_neural_01.SomeNeuralInput get
Returns some vector of input parameters that is within the range.
This methods just reads and returns the current vector of input parameter from the directory for the first time, and then returns the same vector every time.
virtual IVector IG.Script.Script_11_10_clanek_neural_01.NeuralInputParameters get
Vector of input parameters read form the file.
The documentation for this class was generated from the following file:
shelldev/extensions/ExtShellIT/00testscriptsext/igor/archive/11_10_clanek_neural/Script_11_10_clanek_neural_01.cs