IGLib: Mono.Options.Option Class Reference
Mono.Options.Option Class Reference abstract
Public Member Functions
string[] GetNames ()
string[] GetValueSeparators ()
void Invoke (OptionContext c)
override string ToString ()
Protected Member Functions
Option (string prototype, string description)
Option (string prototype, string description, int maxValueCount)
abstract void OnParseComplete (OptionContext c)
Static Protected Member Functions
static T Parse< T > (string value, OptionContext c)
Properties
string Prototype [get]
string Description [get]
OptionValueType OptionValueType [get]
int MaxValueCount [get]
Private Member Functions
OptionValueType ParsePrototype ()
Static Private Member Functions
static void AddSeparators (string name, int end, ICollection< string > seps)
Private Attributes
string prototype
string description
string[] names
OptionValueType type
int count
string[] separators
Static Private Attributes
static readonly char[] NameTerminator = new char[]{'=', ':'}
Constructor & Destructor Documentation
Mono.Options.Option.Option (string prototype, string description) inline protected
Mono.Options.Option.Option (string prototype, string description, int maxValueCount) inline protected
Member Function Documentation
string [] Mono.Options.Option.GetNames () inline
string [] Mono.Options.Option.GetValueSeparators () inline
static T Mono.Options.Option.Parse< T > (string value, OptionContext c) inline static protected
References Mono.Options.OptionSet.MessageLocalizer, Mono.Options.OptionContext.OptionName, and Mono.Options.OptionContext.OptionSet.
OptionValueType Mono.Options.Option.ParsePrototype () inline private
static void Mono.Options.Option.AddSeparators (string name, int end, ICollection< string > seps) inline static private
void Mono.Options.Option.Invoke (OptionContext c) inline
References Mono.Options.OptionValueCollection.Clear(), Mono.Options.OptionContext.Option, Mono.Options.OptionContext.OptionName, and Mono.Options.OptionContext.OptionValues.
Referenced by Mono.Options.OptionSet.Invoke(), Mono.Options.OptionSet.Parse(), Mono.Options.OptionSet.ParseBool(), Mono.Options.OptionSet.ParseValue(), and Mono.Options.OptionSet.Unprocessed().
abstract void Mono.Options.Option.OnParseComplete (OptionContext c) protected pure virtual
Implemented in Mono.Options.OptionSet.ActionOption< TKey, TValue >, Mono.Options.OptionSet.ActionOption< T >, and Mono.Options.OptionSet.ActionOption.
override string Mono.Options.Option.ToString () inline
Member Data Documentation
string Mono.Options.Option.prototype private
string Mono.Options.Option.description private
string [] Mono.Options.Option.names private
OptionValueType Mono.Options.Option.type private
int Mono.Options.Option.count private
string [] Mono.Options.Option.separators private
readonly char [] Mono.Options.Option.NameTerminator = new char[]{'=', ':'} static private
Property Documentation
string Mono.Options.Option.Prototype get
string Mono.Options.Option.Description get
Referenced by Mono.Options.OptionSet.WriteOptionDescriptions(), and Mono.Options.OptionSet.WriteOptionPrototype().
OptionValueType Mono.Options.Option.OptionValueType get
Referenced by Mono.Options.OptionValueCollection.AssertValid(), Mono.Options.OptionSet.Parse(), Mono.Options.OptionSet.ParseBundledValue(), Mono.Options.OptionSet.ParseValue(), and Mono.Options.OptionSet.WriteOptionPrototype().
int Mono.Options.Option.MaxValueCount get
Referenced by Mono.Options.OptionValueCollection.AssertValid(), Mono.Options.OptionSet.ParseValue(), and Mono.Options.OptionSet.WriteOptionPrototype().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/Options.cs