IGLib: alglib.basestat Class Reference
alglib.basestat Class Reference
Static Public Member Functions
static void samplemoments (double[] x, int n, ref double mean, ref double variance, ref double skewness, ref double kurtosis)
static double samplemean (double[] x, int n)
static double samplevariance (double[] x, int n)
static double sampleskewness (double[] x, int n)
static double samplekurtosis (double[] x, int n)
static void sampleadev (double[] x, int n, ref double adev)
static void samplemedian (double[] x, int n, ref double median)
static void samplepercentile (double[] x, int n, double p, ref double v)
static double cov2 (double[] x, double[] y, int n)
static double pearsoncorr2 (double[] x, double[] y, int n)
static double spearmancorr2 (double[] x, double[] y, int n)
static void covm (double[,] x, int n, int m, ref double[,] c)
static void pearsoncorrm (double[,] x, int n, int m, ref double[,] c)
static void spearmancorrm (double[,] x, int n, int m, ref double[,] c)
static void covm2 (double[,] x, double[,] y, int n, int m1, int m2, ref double[,] c)
static void pearsoncorrm2 (double[,] x, double[,] y, int n, int m1, int m2, ref double[,] c)
static void spearmancorrm2 (double[,] x, double[,] y, int n, int m1, int m2, ref double[,] c)
static double pearsoncorrelation (double[] x, double[] y, int n)
static double spearmanrankcorrelation (double[] x, double[] y, int n)
static void samplemoments (double[] x, int n, ref double mean, ref double variance, ref double skewness, ref double kurtosis)
static double samplemean (double[] x, int n)
static double samplevariance (double[] x, int n)
static double sampleskewness (double[] x, int n)
static double samplekurtosis (double[] x, int n)
static void sampleadev (double[] x, int n, ref double adev)
static void samplemedian (double[] x, int n, ref double median)
static void samplepercentile (double[] x, int n, double p, ref double v)
static double cov2 (double[] x, double[] y, int n)
static double pearsoncorr2 (double[] x, double[] y, int n)
static double spearmancorr2 (double[] x, double[] y, int n)
static void covm (double[,] x, int n, int m, ref double[,] c)
static void _pexec_covm (double[,] x, int n, int m, ref double[,] c)
static void pearsoncorrm (double[,] x, int n, int m, ref double[,] c)
static void _pexec_pearsoncorrm (double[,] x, int n, int m, ref double[,] c)
static void spearmancorrm (double[,] x, int n, int m, ref double[,] c)
static void _pexec_spearmancorrm (double[,] x, int n, int m, ref double[,] c)
static void covm2 (double[,] x, double[,] y, int n, int m1, int m2, ref double[,] c)
static void _pexec_covm2 (double[,] x, double[,] y, int n, int m1, int m2, ref double[,] c)
static void pearsoncorrm2 (double[,] x, double[,] y, int n, int m1, int m2, ref double[,] c)
static void _pexec_pearsoncorrm2 (double[,] x, double[,] y, int n, int m1, int m2, ref double[,] c)
static void spearmancorrm2 (double[,] x, double[,] y, int n, int m1, int m2, ref double[,] c)
static void _pexec_spearmancorrm2 (double[,] x, double[,] y, int n, int m1, int m2, ref double[,] c)
static void rankdata (double[,] xy, int npoints, int nfeatures)
static void _pexec_rankdata (double[,] xy, int npoints, int nfeatures)
static void rankdatacentered (double[,] xy, int npoints, int nfeatures)
static void _pexec_rankdatacentered (double[,] xy, int npoints, int nfeatures)
static double pearsoncorrelation (double[] x, double[] y, int n)
static double spearmanrankcorrelation (double[] x, double[] y, int n)
Static Private Member Functions
static void rankdatarec (double[,] xy, int i0, int i1, int nfeatures, bool iscentered, alglib.smp.shared_pool pool, int basecasecost)
static void rankdatabasecase (double[,] xy, int i0, int i1, int nfeatures, bool iscentered, apserv.apbuffers buf0, apserv.apbuffers buf1)
Member Function Documentation
static void alglib.basestat.samplemoments (double[] x, int n, ref double mean, ref double variance, ref double skewness, ref double kurtosis) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.math.sqr().
Referenced by alglib.bdss.dsnormalize(), alglib.bdss.dsnormalizec(), alglib.linreg.lrbuilds(), alglib.linreg.lrbuildzs(), alglib.basestat.samplekurtosis(), alglib.basestat.samplemean(), alglib.samplemoments(), alglib.basestat.sampleskewness(), alglib.basestat.samplevariance(), and alglib.testbasestatunit.testbasestat().
static double alglib.basestat.samplemean (double[] x, int n) inline static
References alglib.basestat.samplemoments().
Referenced by alglib.samplemean(), and alglib.testbasestatunit.testbasestat().
static double alglib.basestat.samplevariance (double[] x, int n) inline static
References alglib.basestat.samplemoments().
Referenced by alglib.samplevariance(), and alglib.testbasestatunit.testbasestat().
static double alglib.basestat.sampleskewness (double[] x, int n) inline static
References alglib.basestat.samplemoments().
Referenced by alglib.sampleskewness(), and alglib.testbasestatunit.testbasestat().
static double alglib.basestat.samplekurtosis (double[] x, int n) inline static
References alglib.basestat.samplemoments().
Referenced by alglib.samplekurtosis(), and alglib.testbasestatunit.testbasestat().
static void alglib.basestat.sampleadev (double[] x, int n, ref double adev) inline static
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
Referenced by alglib.sampleadev(), and alglib.testbasestatunit.testbasestat().
static void alglib.basestat.samplemedian (double[] x, int n, ref double median) inline static
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
Referenced by alglib.samplemedian(), and alglib.testbasestatunit.testbasestat().
static void alglib.basestat.samplepercentile (double[] x, int n, double p, ref double v) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.tsort.tagsortfast().
Referenced by alglib.samplepercentile(), and alglib.testbasestatunit.testbasestat().
static double alglib.basestat.cov2 (double[] x, double[] y, int n) inline static
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
Referenced by alglib.cov2(), and alglib.testbasestatunit.testbasestat().
static double alglib.basestat.pearsoncorr2 (double[] x, double[] y, int n) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.math.sqr().
Referenced by alglib.testclusteringunit.distfunc(), alglib.pearsoncorr2(), alglib.basestat.pearsoncorrelation(), alglib.basestat.spearmancorr2(), and alglib.testbasestatunit.testbasestat().
static double alglib.basestat.spearmancorr2 (double[] x, double[] y, int n) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.basestat.pearsoncorr2(), and alglib.basicstatops.rankx().
Referenced by alglib.testclusteringunit.distfunc(), alglib.spearmancorr2(), alglib.basestat.spearmanrankcorrelation(), and alglib.testbasestatunit.testbasestat().
static void alglib.basestat.covm (double x[,], int n, int m, ref double c[,]) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), and alglib.ablas.rmatrixsyrk().
Referenced by alglib.basestat._pexec_covm(), alglib.covm(), alglib.basestat.pearsoncorrm(), and alglib.testbasestatunit.testbasestat().
static void alglib.basestat.pearsoncorrm (double x[,], int n, int m, ref double c[,]) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), and alglib.basestat.covm().
Referenced by alglib.basestat._pexec_pearsoncorrm(), alglib.pearsoncorrm(), and alglib.testbasestatunit.testbasestat().
static void alglib.basestat.spearmancorrm (double x[,], int n, int m, ref double c[,]) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), alglib.basicstatops.rankx(), and alglib.ablas.rmatrixsyrk().
Referenced by alglib.basestat._pexec_spearmancorrm(), alglib.spearmancorrm(), and alglib.testbasestatunit.testbasestat().
static void alglib.basestat.covm2 (double x[,], double y[,], int n, int m1, int m2, ref double c[,]) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), and alglib.ablas.rmatrixgemm().
Referenced by alglib.basestat._pexec_covm2(), alglib.covm2(), and alglib.testbasestatunit.testbasestat().
static void alglib.basestat.pearsoncorrm2 (double x[,], double y[,], int n, int m1, int m2, ref double c[,]) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), and alglib.ablas.rmatrixgemm().
Referenced by alglib.basestat._pexec_pearsoncorrm2(), alglib.pearsoncorrm2(), and alglib.testbasestatunit.testbasestat().
static void alglib.basestat.spearmancorrm2 (double x[,], double y[,], int n, int m1, int m2, ref double c[,]) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), alglib.basicstatops.rankx(), and alglib.ablas.rmatrixgemm().
Referenced by alglib.basestat._pexec_spearmancorrm2(), alglib.spearmancorrm2(), and alglib.testbasestatunit.testbasestat().
static double alglib.basestat.pearsoncorrelation (double[] x, double[] y, int n) inline static
References alglib.basestat.pearsoncorr2().
Referenced by alglib.pearsoncorrelation().
static double alglib.basestat.spearmanrankcorrelation (double[] x, double[] y, int n) inline static
References alglib.basestat.spearmancorr2().
Referenced by alglib.spearmanrankcorrelation().
static void alglib.basestat.samplemoments (double[] x, int n, ref double mean, ref double variance, ref double skewness, ref double kurtosis) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.math.sqr().
static double alglib.basestat.samplemean (double[] x, int n) inline static
References alglib.basestat.samplemoments().
static double alglib.basestat.samplevariance (double[] x, int n) inline static
References alglib.basestat.samplemoments().
static double alglib.basestat.sampleskewness (double[] x, int n) inline static
References alglib.basestat.samplemoments().
static double alglib.basestat.samplekurtosis (double[] x, int n) inline static
References alglib.basestat.samplemoments().
static void alglib.basestat.sampleadev (double[] x, int n, ref double adev) inline static
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
static void alglib.basestat.samplemedian (double[] x, int n, ref double median) inline static
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
static void alglib.basestat.samplepercentile (double[] x, int n, double p, ref double v) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.tsort.tagsortfast().
static double alglib.basestat.cov2 (double[] x, double[] y, int n) inline static
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
static double alglib.basestat.pearsoncorr2 (double[] x, double[] y, int n) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.math.sqr().
static double alglib.basestat.spearmancorr2 (double[] x, double[] y, int n) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.basestat.pearsoncorr2(), and alglib.basicstatops.rankx().
static void alglib.basestat.covm (double x[,], int n, int m, ref double c[,]) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), alglib.ablas.rmatrixenforcesymmetricity(), and alglib.ablas.rmatrixsyrk().
static void alglib.basestat._pexec_covm (double x[,], int n, int m, ref double c[,]) inline static
References alglib.basestat.covm().
Referenced by alglib.smp_covm().
static void alglib.basestat.pearsoncorrm (double x[,], int n, int m, ref double c[,]) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), and alglib.basestat.covm().
static void alglib.basestat._pexec_pearsoncorrm (double x[,], int n, int m, ref double c[,]) inline static
References alglib.basestat.pearsoncorrm().
Referenced by alglib.smp_pearsoncorrm().
static void alglib.basestat.spearmancorrm (double x[,], int n, int m, ref double c[,]) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), alglib.basestat.rankdata(), alglib.ablas.rmatrixenforcesymmetricity(), alglib.ablas.rmatrixsyrk(), and alglib.ablas.rmatrixtranspose().
static void alglib.basestat._pexec_spearmancorrm (double x[,], int n, int m, ref double c[,]) inline static
References alglib.basestat.spearmancorrm().
Referenced by alglib.smp_spearmancorrm().
static void alglib.basestat.covm2 (double x[,], double y[,], int n, int m1, int m2, ref double c[,]) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), and alglib.ablas.rmatrixgemm().
static void alglib.basestat._pexec_covm2 (double x[,], double y[,], int n, int m1, int m2, ref double c[,]) inline static
References alglib.basestat.covm2().
Referenced by alglib.smp_covm2().
static void alglib.basestat.pearsoncorrm2 (double x[,], double y[,], int n, int m1, int m2, ref double c[,]) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), and alglib.ablas.rmatrixgemm().
static void alglib.basestat._pexec_pearsoncorrm2 (double x[,], double y[,], int n, int m1, int m2, ref double c[,]) inline static
References alglib.basestat.pearsoncorrm2().
Referenced by alglib.smp_pearsoncorrm2().
static void alglib.basestat.spearmancorrm2 (double x[,], double y[,], int n, int m1, int m2, ref double c[,]) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), alglib.basestat.rankdata(), alglib.ablas.rmatrixgemm(), and alglib.ablas.rmatrixtranspose().
static void alglib.basestat._pexec_spearmancorrm2 (double x[,], double y[,], int n, int m1, int m2, ref double c[,]) inline static
References alglib.basestat.spearmancorrm2().
Referenced by alglib.smp_spearmancorrm2().
static void alglib.basestat.rankdata (double xy[,], int npoints, int nfeatures) inline static
References alglib.smp.ae_shared_pool_set_seed(), alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), alglib.apserv.inttoreal(), alglib.apserv.logbase2(), alglib.basestat.rankdatabasecase(), and alglib.basestat.rankdatarec().
Referenced by alglib.basestat._pexec_rankdata(), alglib.rankdata(), alglib.basestat.spearmancorrm(), alglib.basestat.spearmancorrm2(), and alglib.testbasestatunit.testranking().
static void alglib.basestat._pexec_rankdata (double xy[,], int npoints, int nfeatures) inline static
References alglib.basestat.rankdata().
Referenced by alglib.smp_rankdata().
static void alglib.basestat.rankdatacentered (double xy[,], int npoints, int nfeatures) inline static
References alglib.smp.ae_shared_pool_set_seed(), alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), alglib.apserv.inttoreal(), alglib.apserv.logbase2(), alglib.basestat.rankdatabasecase(), and alglib.basestat.rankdatarec().
Referenced by alglib.basestat._pexec_rankdatacentered(), alglib.clustering.clusterizergetdistances(), alglib.rankdatacentered(), and alglib.testbasestatunit.testranking().
static void alglib.basestat._pexec_rankdatacentered (double xy[,], int npoints, int nfeatures) inline static
References alglib.basestat.rankdatacentered().
Referenced by alglib.smp_rankdatacentered().
static double alglib.basestat.pearsoncorrelation (double[] x, double[] y, int n) inline static
References alglib.basestat.pearsoncorr2().
static double alglib.basestat.spearmanrankcorrelation (double[] x, double[] y, int n) inline static
References alglib.basestat.spearmancorr2().
static void alglib.basestat.rankdatarec (double xy[,], int i0, int i1, int nfeatures, bool iscentered, alglib.smp.shared_pool pool, int basecasecost) inline static private
References alglib.ap.assert(), alglib.apserv.inttoreal(), alglib.apserv.logbase2(), and alglib.basestat.rankdatabasecase().
Referenced by alglib.basestat.rankdata(), and alglib.basestat.rankdatacentered().
static void alglib.basestat.rankdatabasecase (double xy[,], int i0, int i1, int nfeatures, bool iscentered, apserv.apbuffers buf0, apserv.apbuffers buf1) inline static private
References alglib.ap.assert(), and alglib.basicstatops.rankx().
Referenced by alglib.basestat.rankdata(), alglib.basestat.rankdatacentered(), and alglib.basestat.rankdatarec().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/statistics.cs