IGLib: IG.Num.MatrixBaseDev Class Reference
IG.Num.MatrixBaseDev Class Reference
Development of matrix operations.
Static Public Member Functions
static IMatrix CreateRandomSymmetricPositiveDefinite (int dim, IRandomGenerator rnd)
Attemps to create and return a symmetric positive definite square matrix.
static IMatrix CreateRandomSymmetricPositiveDefinite (int dim)
Attemps to create and return a symmetric positive definite square matrix.
static int DecomposeLLTPlain (IMatrix m1, IMatrix res)
LLT (Choleski) DECOMPOSITION (symmetric positive definite matrices)
static int DecomposeLLTPlain (IMatrix m1, IMatrix res, double smalltol)
Performs Choleski (LLT) decomposition of a matrix and stores result to the specified matrix. Can be done in place. WARNING: Dimensions are not checked, therefore dimensions of arguments must be consistent. Method also does not control whethe matrix is symmetric, but it simply operates on the lower triangle of the original.
static int DecomposeLLT (IMatrix m1, IMatrix res, double smalltol)
static int DecomposeLLT (IMatrix m1, ref IMatrix res, double smalltol)
static void SolveLLTPlain (IMatrix L, IVector b, IVector x)
Solves a linear system of equations by using a Choleski (LLT) decomposition of the system matrix. Linear system to be solved is L LT x = b, where L is a lower triangular matrix. Can be done in place, x and b can be the same vectors. WARNING: Dimensions are not checked, therefore dimensions of arguments must be consistent.
static void SolveLLT (IMatrix L, IVector b, IVector x)
static void SolveLLT (IMatrix L, IVector b, ref IVector x)
static void GetFactorsLLTPlain (IMatrix LLT, IMatrix L, IMatrix LT)
Splits the LLT product contained in a lower triangular part of a single matrix into separate lower triangular and upper diagonal factors, and stores them in the specified matrices. matrices. Both matrices where the split part is stored can be the same objects as the original matrix. WARNING: This method does not check consistency of matrix dimensons.
static void GetFactorsLLT (IMatrix LLT, IMatrix L, IMatrix LT)
static void GetFactorsLLT (IMatrix LLT, ref IMatrix L, ref IMatrix LT)
static bool TestMatrixDecompositions (bool printReports)
Tests various matrix and vector decompositions with fixed tolerance of 1.0E-6.
static bool TestMatrixDecompositions (double tolerance)
Tests various matrix and vector decompositions, without printing reports.
static bool TestMatrixDecompositions ()
Tests various matrix and vector decompositions with fixed tolerance of 1.0E-6 and without printing reports.
static bool TestMatrixDecompositions (double tolerance, bool printReports)
Tests various matrix and vector decompositions.
Static Public Member Functions inherited from IG.Num.MatrixBase
static int Index (int dim1, int dim2, int row, int column)
Returns flat index corresponding to the specified row and column indices of a matrix with specified dimensions.
static int Index (IMatrix mat, int row, int column)
Calculates and returns flat index corresponding to the specified row and column indices of the specified matrix.
static void Indices (int dim1, int dim2, int flatIndex, out int row, out int column)
Returns (through output arguments) row and column indices corresponding to the specified flat index in a matrix with the specified dimensions.
static void Indices (IMatrix mat, int flatIndex, out int row, out int column)
Returns (through output arguments) row and column indices corresponding to the specified flat index in the specified matrix.
static void SetZero (IMatrix mat)
Sets all components of the specified matrix to 0.
static void SetConstant (IMatrix mat, double elementValue)
Sets all components of the specified matrix to the specified value.
static void SetIdentity (IMatrix mat)
Sets the specified matrix to identity matrix. WARNING: Works only for square matrices (exception is thrown if matrix is not square). For nonsquare matrices, use SetDiagonal(1.0)!
static void SetDiagonal (IMatrix mat, IVector diagonal)
Sets the current matrix to the diagonal matrix with diagonal element specified by a vector.
static void SetDiagonal (IMatrix mat, double diagonalElement)
Sets the current matrix to the diagonal matrix with all diagonal elements equal to the specified value. Matrix does not need to be a square matrix.
static void SetRandom (IMatrix mat)
Sets the specified matrix such that it contains random elements on the interval (0,1].
static void SetRandom (IMatrix mat, IRandomGenerator rnd=null)
Sets the current matrix such that it contains random elements on the interval (0,1].
static void SetRandomSymmetric (IMatrix mat)
Sets the specified matrix such that it is symmetric and contains random elements on the interval (0,1].
static void SetRandomSymmetric (IMatrix mat, IRandomGenerator rnd)
Sets the specified matrix such that it is symmetric and contains random elements on the interval (0,1].
static void SetRandomAntiSymmetric (IMatrix mat)
Sets the specified matrix such that it is antisymmetric and contains random elements on the interval (0,1].
static void SetRandomAntiSymmetric (IMatrix mat, IRandomGenerator rnd)
Sets the specified matrix such that it is antisymmetric and contains random elements on the interval (0,1].
static void SetRandomLowerTriangular (IMatrix mat)
Sets the specified matrix such that it is lower triangular and contains random elements on the interval (0,1].
static void SetRandomLowerTriangular (IMatrix mat, IRandomGenerator rnd)
Sets the specified matrix such that it is lower triangular and contains random elements on the interval (0,1].
static void SetRandomUpperTriangular (IMatrix mat)
Sets the specified matrix such that it is upper triangular and contains random elements on the interval (0,1].
static void SetRandomUpperTriangular (IMatrix mat, IRandomGenerator rnd)
Sets the specified matrix such that it is upper triangular and contains random elements on the interval (0,1].
static void SetRandomSymmetricPositiveDefinite (IMatrix mat)
Sets the specified matrix such that it is positive definite and contains random elements on the interval (0,1].
static void SetRandomSymmetricPositiveDefinite (IMatrix mat, IRandomGenerator rnd)
Sets the specified matrix such that it is positive definite and contains random elements.
static void SetRandomPositiveDiagonallyDominant (IMatrix mat, IRandomGenerator rnd=null, double dominancyFactor=100.0)
Sets the specified matrix such that it is has random elements and is diagonally dominant with positive diagonal elements, i.e. any diagonal element is greater by absolute value than sum of absolute values of nondiagonal elements in the corresponding column.
static void SetRandomPositiveDiagonallyDominant (IMatrix mat, double dominancyFactor)
Sets the specified matrix such that it is has random elements and is diagonally dominant with positive diagonal elements, i.e. any diagonal element is greater by absolute value than sum of absolute values of nondiagonal elements in the corresponding column.
static void SetRandomPositiveDiagonallyDominantSymmetric (IMatrix mat, IRandomGenerator rnd=null, double dominancyFactor=100.0)
Sets the specified matrix such that it is has random elements and is symmetric diagonally dominant with positive diagonal elements, i.e. any diagonal element is greater by absolute value than sum of absolute values of nondiagonal elements in the corresponding column.
static void SetRandomPositiveDiagonallyDominantSymmetric (IMatrix mat, double dominancyFactor)
Sets the specified matrix such that it is has random elements and is symmetric diagonally dominant with positive diagonal elements, i.e. any diagonal element is greater by absolute value than sum of absolute values of nondiagonal elements in the corresponding column.
static double SetRandomInvertible (IMatrix mat, IRandomGenerator rnd=null)
Sets the specified QUADRATIC matrix such that it is has random elements and is nonsingular.
static double SetRandomPositiveDefiniteSymmetric (IMatrix mat, IRandomGenerator rnd=null)
Sets the specified QUADRATIC matrix such that it is has random elements and is a symmetric positive definite matrix.
static bool IsSquare (IMatrix mat)
Returns true if the specified matrix is a square matrix, and false if not. If the matrix is null then false is returned.
static bool IsSymmetric (IMatrix mat)
Returns true if the specified matrix is symmetric, and false if not. If the matrix is null then false is returned.
static bool IsSymmetric (IMatrix mat, double relativeRMSTolerance)
Returns true if the specified matrix is symmetric within some tolerance, and false if not. If the matrix is null then false is returned.
static int Compare (IMatrix m1, IMatrix m2)
Compares two matrices and returns -1 if the first matrix is smaller than the second one, 0 if matrices are equal, and 1 if the first matrix is greater. Matrix that is null is considered smaller than a matrix that is not null. Two null matrices are considered equal. Matrix with smaller dimension is considered smaller than a matrix with greater dimension. Matrices with equal dimensions ar compared by elements. The first element that is different decides which matrix is considered greater.
static void Resize (ref IMatrix mat, IMatrix template, int rowCount, int columnCount)
Resizes, if necessary, the specified matrix according to the required dimensions. If the matrix is initially null then a new matrix is created. If in this case a template matrix is specified then the newly created matrix will be of the same type as that template matrix, because it is created by the GetNew() method on that matrix. If dimensions of the initial matrix do not match the required dim., then matrix is resized. If the specified matrix dimension is less or equal to 0 then matrix is resized with the same dimensions as those of the template matirx. If in this case the template matrix is null, an exception is thrown. WARNINGS: Components are NOT preserved and have in general undefined values after operation is performed. If matrix and template are both null then the type of nawly created matrix is Matrix.
static void Resize (ref IMatrix mat, int rowCount, int columnCount)
Resizes, if necessary, the specified matrix according to the required dimensions. If the matrix is initially null then a new matrix (of type Matrix) is created. If dimensions of the initial matrix do not match the required dimensions, then matrix is resized. Components are NOT preserved and have in general undefined values after operation is performed. WARNING: If the matrix is initially null then the type of the newly created matrix is Matrix.
static void Resize (ref IMatrix mat, IMatrix template)
Resizes, if necessary, the specified matrix according to the dimensions of the specified template matrix. If the matrix is initially null then a new matrix is created. In this case the newly created matrix will be of the same type as that template matrix, because it is created by the GetNew() method on that matrix. If dimensions of the initial matrix do not match the dimensions of the template matrix, then matrix is resized. If the template matrix is null, then an exception is thrown. WARNINGS: Components are NOT preserved and have in general undefined values after operation is performed. If matrix and template are null then the type of newly created matrix is Matrix.
static void CopyPlain (IMatrix a, IMatrix result)
Copies components of a matrix to another matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of the copied matrix and result storage must match.
static void Copy (IMatrix a, IMatrix result)
Copies components of a matrix to another matrix. WARNING: dimensions of the copied matrix and result storage must match.
static void Copy (IMatrix a, ref IMatrix result)
Copies components of a matrix to another matrix. Resulting matrix is allocated or reallocated if necessary.
static void CopyPlain (MatrixBase_MathNetNumerics a, IMatrix result)
Copies components of a matrix to another matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of the copied matrix and result storage must match.
static void Copy (MatrixBase_MathNetNumerics a, IMatrix result)
Copies components of a matrix to another matrix. WARNING: dimensions of the copied matrix and result storage must match.
static void Copy (MatrixBase_MathNetNumerics a, ref IMatrix result)
Copies components of a matrix to another matrix. Resulting matrix is allocated or reallocated if necessary.
static void CopyPlain (IMatrix a, Matrix_MathNetNumercs result)
Copies components of a matrix to another matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of the copied matrix and result storage must match.
static void Copy (IMatrix a, Matrix_MathNetNumercs result)
Copies components of a matrix to another matrix. WARNING: dimensions of the copied matrix and result storage must match.
static void Copy (IMatrix a, ref Matrix_MathNetNumercs result)
Copies components of a matrix to another matrix. Resulting matrix is allocated or reallocated if necessary.
static void NegatePlain (IMatrix a, IMatrix result)
Stores a negative matrix of the operand in another matrix. Can be done in-place. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of the operand and result storage must match.
static void Negate (IMatrix a, IMatrix result)
Stores a negative matrix of the operand in another matrix. Can be done in-place. WARNING: dimensions of the operand and result storage must match.
static void Negate (IMatrix a, ref IMatrix result)
Stores a negative matrix of the operand in another matrix. Can be done in-place. Resulting matrix is allocated or reallocated if necessary.
static void TransposePlain (IMatrix a, IMatrix result)
Stores transpose of the operand in another matrix. Can be done in-place. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of the operand and result storage must match.
static void Transpose (IMatrix a, IMatrix result)
Stores transpose of the operand in another matrix. Can be done in-place. WARNING: dimensions of the operand and result storage must match.
static void Transpose (IMatrix a, ref IMatrix result)
Stores transpose of the matrix operand in another matrix. Can be done in-place. Resulting matrix is allocated or reallocated if necessary.
static void SymmetrizePlain (IMatrix a, IMatrix sym, IMatrix antiSym)
Calculates symmetric and antisymmetric part of the specified matrix (symmetric part is stored in the first result argument but is calculated last, such that it overrides antisymmetric when both arguments point to the same matrix object).
static void Symmetrize (IMatrix a, IMatrix sym, IMatrix antiSym)
Calculates symmetric and antisymmetric part of the specified matrix (symmetric part is stored in the first result argument but is calculated last, such that it overrides antisymmetric when both arguments point to the same matrix object).
static void Symmetrize (IMatrix a, ref IMatrix sym, ref IMatrix antiSym)
Stores symmetrized and antisymmetirzed matrix obtained from the specified matrix. Resulting matrix is allocated or reallocated if necessary.
static void SymmetricPartPlain (IMatrix a, IMatrix result)
Stores symmetric part of a square matrix operand in another matrix. Symmetrization is performed by averaging of non-diagonal terms and their transposed terms. Can be done in-place. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of the operand and result storage must match.
static void SymmetricPart (IMatrix a, IMatrix result)
Stores symmetric part of a square matrix operand in another matrix. Symmetrization is performed by averaging of non-diagonal terms and their transposed terms. Can be done in-place. WARNING: dimensions of the operand and result storage must match.
static void SymmetricPart (IMatrix a, ref IMatrix result)
Stores symmetric part of a square matrix operand in another matrix. Symmetrization is performed by averaging of non-diagonal terms and their transposed terms. Can be done in-place. Resulting matrix is allocated or reallocated if necessary.
static void AntisymmetricPartPlain (IMatrix a, IMatrix result)
Stores antisymmetric part of a square matrix operand in another matrix. Antisymmetrization is performed by subtracting non-diagonal terms and their transposed terms, division by 2 and storing result in one matrix element and its negative value in another element. Can be done in-place. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of the operand and result storage must match.
static void AntisymmetricPart (IMatrix a, IMatrix result)
Stores antisymmetric part of a square matrix operand in another matrix. Antisymmetrization is performed by subtracting non-diagonal terms and their transposed terms, division by 2 and storing result in one matrix element and its negative value in another element. Can be done in-place. WARNING: dimensions of the operand and result storage must match.
static void AntisymmetricPart (IMatrix a, ref IMatrix result)
Stores antisymmetric part of a square matrix operand in another matrix. Antisymmetrization is performed by subtracting non-diagonal terms and their transposed terms, division by 2 and storing result in one matrix element and its negative value in another element. Can be done in-place. Resulting matrix is allocated or reallocated if necessary.
static void AddPlain (IMatrix a, IMatrix b, IMatrix result)
Sums two matrices and stores the result in the specified result matrix. Operation can be performed in place. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void Add (IMatrix a, IMatrix b, IMatrix result)
Sums two matrices and stores the result in the specified result matrix. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void Add (IMatrix a, IMatrix b, ref IMatrix result)
Sums two matrices and stores the result in the specified result matrix. Operation can be performed in place. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void SubtractPlain (IMatrix a, IMatrix b, IMatrix result)
Subtracts two matrices and stores the result in the specified result matrix. Operation can be performed in place. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void Subtract (IMatrix a, IMatrix b, IMatrix result)
Subtracts two matrices and stores the result in the specified result matrix. Operation can be performed in place. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void Subtract (IMatrix a, IMatrix b, ref IMatrix result)
Subtracts two matrices and stores the result in the specified result matrix. Operation can be performed in place. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void ArrayMultiplyPlain (IMatrix a, IMatrix b, IMatrix result)
Element-by-element multiplication. This operation can be performed in place. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void ArrayMultiply (IMatrix a, IMatrix b, IMatrix result)
Element-by-element multiplication. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void ArrayMultiply (IMatrix a, IMatrix b, ref IMatrix result)
Element-by-element multiplication. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void ArrayDividePlain (IMatrix a, IMatrix b, IMatrix result)
Element-by-element division. This operation can be performed in place. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void ArrayDivide (IMatrix a, IMatrix b, IMatrix result)
Element-by-element division. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void ArrayDivide (IMatrix a, IMatrix b, ref IMatrix result)
Element-by-element division. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void ArrayPowerPlain (IMatrix a, double power, IMatrix result)
Element-by-element raise to power. This operation can be performed in place. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void ArrayPower (IMatrix a, double power, IMatrix result)
Element-by-element raise to power. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void ArrayPower (IMatrix a, double power, ref IMatrix result)
Element-by-element raise to power. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void ArrayMapPlain (IMatrix a, Converter< double, double > mapping, IMatrix result)
Element-by-element mapping of an arbitrary function. This operation can be performed in place. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void ArrayMap (IMatrix a, Converter< double, double > mapping, IMatrix result)
Element-by-element mapping of an arbitrary function. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void ArrayMap (IMatrix a, Converter< double, double > mapping, ref IMatrix result)
Element-by-element mapping of an arbitrary function. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void MultiplyPlain (IMatrix a, IMatrix b, IMatrix result)
R=A*B. Multiplies two matrices and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void Multiply (IMatrix a, IMatrix b, IMatrix result)
R=A*B. Multiplies two matrices and stores the result in the specified result matrix. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void Multiply (IMatrix a, IMatrix b, ref IMatrix result)
R=A*B. Multiplies two matrices and stores the result in the specified result matrix. WARNING: dimensions of operands must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyTranspMatPlain (IMatrix a, IMatrix b, IMatrix result)
R=A^T*B Calculates product of transposed matrix and a matrix, and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyTranspMat (IMatrix a, IMatrix b, IMatrix result)
R=A^T*B Multiplies two matrices and stores the result in the specified result matrix. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyTranspMat (IMatrix a, IMatrix b, ref IMatrix result)
R=A^T*B Multiplies two matrices and stores the result in the specified result matrix. WARNING: dimensions of operands must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyMatTranspPlain (IMatrix a, IMatrix b, IMatrix result)
R=A*B^T. Multiplies a matrix by transpose of another matrix and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyMatTransp (IMatrix a, IMatrix b, IMatrix result)
R=A*B^T. Multiplies a matrix by transpose of another matrix and stores the result in the specified result matrix. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyMatTransp (IMatrix a, IMatrix b, ref IMatrix result)
R=A*B^T. Multiplies a matrix by transpose of another matrix and stores the result in the specified result matrix. WARNING: dimensions of operands must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyTranspTranspPlain (IMatrix a, IMatrix b, IMatrix result)
R=A^T*B^T. Multiplies transposed matrix by another transposed matrix, and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyTranspTransp (IMatrix a, IMatrix b, IMatrix result)
R=A^T*B^T. Multiplies transposed matrix by another transposed matrix, and stores the result in the specified result matrix. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyTranspTransp (IMatrix a, IMatrix b, ref IMatrix result)
R=A^T*B^T. Multiplies transposed matrix by another transposed matrix, and stores the result in the specified result matrix. WARNING: dimensions of operands must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyPlain (IMatrix a, IMatrix b, IMatrix c, IMatrix result)
R=A*B*C. Multiplies three matrices and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void Multiply (IMatrix a, IMatrix b, IMatrix c, IMatrix result)
R=A*B*C. Multiplies three matrices and stores the result in the specified result matrix. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void Multiply (IMatrix a, IMatrix b, IMatrix c, ref IMatrix result)
R=A*B*C. Multiplies three matrices and stores the result in the specified result matrix. WARNING: dimensions of operands must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyTranspMatTranspPlain (IMatrix a, IMatrix b, IMatrix c, IMatrix result)
R=A^T*B*C^T. Multiplies three matrices (transposed first argument, second argument, and transposed third argument) and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all arguments must be consistent, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyTranspMatTransp (IMatrix a, IMatrix b, IMatrix c, IMatrix result)
R=A^T*B*C^T. Multiplies three matrices (transposed first argument, second argument, and transposed third argument) and stores the result in the specified result matrix. WARNING: dimensions of all arguments must be consistent, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyTranspMatTransp (IMatrix a, IMatrix b, IMatrix c, ref IMatrix result)
R=A^T*B*C^T. Multiplies three matrices (transposed first argument, second argument, and transposed third argument) and stores the result in the specified result matrix. WARNING: dimensions of operands must be consistent, otherwise an exception is thrown. WARNING: This operation can not be performed in place. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyTranspMatMatPlain (IMatrix a, IMatrix b, IMatrix c, IMatrix result)
R=A^T*B*C. Multiplies three matrices (transposed first argument, second argument, and third argument) and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all arguments must be consistent, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyTranspMatMat (IMatrix a, IMatrix b, IMatrix c, IMatrix result)
R=A^T*B*C. Multiplies three matrices (transposed first argument, second argument, and third argument) and stores the result in the specified result matrix. WARNING: dimensions of all arguments must be consistent, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyTranspMatMat (IMatrix a, IMatrix b, IMatrix c, ref IMatrix result)
R=A^T*B*C. Multiplies three matrices (transposed first argument, second argument, and third argument) and stores the result in the specified result matrix. WARNING: dimensions of operands must be consistent, otherwise an exception is thrown. WARNING: This operation can not be performed in place. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyMatMatTranspPlain (IMatrix a, IMatrix b, IMatrix c, IMatrix result)
R=A*B*C^T. Multiplies three matrices (first argumet, second argumet, and transposed third argument) and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyMatMatTransp (IMatrix a, IMatrix b, IMatrix c, IMatrix result)
R=A*B*C^T. Multiplies three matrices (first argumet, second argumet, and transposed third argument) and stores the result in the specified result matrix. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyMatMatTransp (IMatrix a, IMatrix b, IMatrix c, ref IMatrix result)
R=A*B*C^T. Multiplies three matrices (first argumet, second argumet, and transposed third argument) and stores the result in the specified result matrix. WARNING: dimensions of operands must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyMatTranspMatPlain (IMatrix a, IMatrix b, IMatrix c, IMatrix result)
R=A*B^T*C. Multiplies three matrices (first argument, transposed second argument, and third argument) and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyMatTranspMat (IMatrix a, IMatrix b, IMatrix c, IMatrix result)
R=A*B^T*C. Multiplies three matrices (first argument, transposed second argument, and third argument) and stores the result in the specified result matrix. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyMatTranspMat (IMatrix a, IMatrix b, IMatrix c, ref IMatrix result)
R=A*B^T*C. Multiplies three matrices (first argument, transposed second argument, and third argument) and stores the result in the specified result matrix. WARNING: dimensions of operands must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyTranspTranspTranspPlain (IMatrix a, IMatrix b, IMatrix c, IMatrix result)
R=A^T*B^T*C^T. Multiplies three matrices and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyTranspTranspTransp (IMatrix a, IMatrix b, IMatrix c, IMatrix result)
R=A^T*B^T*C^T. Multiplies three matrices and stores the result in the specified result matrix. WARNING: dimensions of matrices must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place.
static void MultiplyTranspTranspTransp (IMatrix a, IMatrix b, IMatrix c, ref IMatrix result)
R=A^T*B^T*C^T. Multiplies three matrices and stores the result in the specified result matrix. WARNING: dimensions of operands must match, otherwise an exception is thrown. WARNING: This operation can not be performed in place. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyPlain (IMatrix a, IVector b, IVector result)
R=A*b. Multiplies a matrix with a vector and stores the result in the specified result vector. Operation can not be performed in place. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void Multiply (IMatrix a, IVector b, IVector result)
R=A*b. Multiplies a matrix with a vector and stores the result in the specified result vector. Operation can not be performed in place. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void Multiply (IMatrix a, IVector b, ref IVector result)
R=A*b. Multiplies matrix by scalar and stores the result in the specified result matrix. Operation can not be performed in place. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyTranspVecPlain (IMatrix a, IVector b, IVector result)
R=A^T*b. Multiplies a transposed matrix with a vector and stores the result in the specified result vector. Operation can not be performed in place. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void MultiplyTranspVec (IMatrix a, IVector b, IVector result)
R=A^T*b. Multiplies a transposed matrix with a vector and stores the result in the specified result vector. Operation can not be performed in place. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void MultiplyTranspVec (IMatrix a, IVector b, ref IVector result)
R=A^T*b. Multiplies transposed matrix by scalar and stores the result in the specified result matrix. Operation can not be performed in place. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then the result is re-allocated.
static double MultiplyPlain (IVector left, IMatrix a, IVector right)
R=a^T*M*b. Left-multiplies a matrix with a vector (transposed), right multiplies the result vith another vector, and returns the final result. Can be performed in place. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static double Multiply (IVector left, IMatrix a, IVector right)
R=a^T*M*b. Left-multiplies a matrix with a vector (transposed), right multiplies the result vith another vector, and returns the final result. Can be performed in place. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static double Multiply (IVector left, IMatrix a, IVector right, ref IVector result)
R=a^T*M*b. Left-multiplies a matrix with a vector (transposed), right multiplies the result vith another vector, and returns the final result. Can be performed in place. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyPlain (IMatrix a, double b, IMatrix result)
Multiplies matrix by scalar and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. This operation can be performed in place. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void Multiply (IMatrix a, double b, IMatrix result)
Multiplies matrix by scalar and stores the result in the specified result matrix. This operation can be performed in place. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void Multiply (IMatrix a, double b, ref IMatrix result)
Multiplies matrix by scalar and stores the result in the specified result matrix. This operation can be performed in place. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then the result is re-allocated.
static void DividePlain (IMatrix a, double b, IMatrix result)
Divides matrix by scalar and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. This operation can be performed in place. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void Divide (IMatrix a, double b, IMatrix result)
Divides matrix by scalar and stores the result in the specified result matrix. This operation can be performed in place. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void Divide (IMatrix a, double b, ref IMatrix result)
Divides matrix by scalar and stores the result in the specified result matrix. This operation can be performed in place. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyDiagonalPlain (IVector diag, IMatrix a, IMatrix result)
Left-multiplies a matrix with a diagonal matrix, and stores the result in the specified result matrix. R=diag(d)*A This is a plain version of the method that does not perform any consistency checks. The operation can be done in place. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void MultiplyDiagonal (IVector diag, IMatrix a, IMatrix result)
Right-multiplies a matrix with a diagonal matrix, and stores the result in the specified result matrix. R=diag(d)*A WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void MultiplyDiagonal (IVector diag, IMatrix a, ref IMatrix result)
Right-multiplies a matrix with a diagonal matrix, and stores the result in the specified result matrix. R=diag(d)*A WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyInverseDiagonalPlain (IVector diag, IMatrix a, IMatrix result)
Left-multiplies a matrix with inverse of a diagonal matrix, and stores the result in the specified result matrix. R=diag(d)^-1*A This is a plain version of the method that does not perform any consistency checks. The operation can be done in place. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void MultiplyInverseDiagonal (IVector diag, IMatrix a, IMatrix result)
Right-multiplies a matrix with inverse of a diagonal matrix, and stores the result in the specified result matrix. R=diag(d)^-1*A WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void MultiplyInverseDiagonal (IVector diag, IMatrix a, ref IMatrix result)
Right-multiplies a matrix with inverse of a diagonal matrix, and stores the result in the specified result matrix. R=diag(d)^-1*A WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyDiagonalPlain (IMatrix a, IVector diag, IMatrix result)
Right-multiplies a matrix with a diagonal matrix, and stores the result in the specified result matrix. R=A*diag(d) This is a plain version of the method that does not perform any consistency checks. The operation can be done in place. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void MultiplyDiagonal (IMatrix a, IVector diag, IMatrix result)
Right-multiplies a matrix with a diagonal matrix, and stores the result in the specified result matrix. R=A*diag(d) WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void MultiplyDiagonal (IMatrix a, IVector diag, ref IMatrix result)
Right-multiplies a matrix with a diagonal matrix, and stores the result in the specified result matrix. R=A*diag(d) WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then the result is re-allocated.
static void MultiplyInverseDiagonalPlain (IMatrix a, IVector diag, IMatrix result)
Right-multiplies a matrix with inverse of a diagonal matrix, and stores the result in the specified result matrix. R=A*diag(d)^-1 This is a plain version of the method that does not perform any consistency checks. The operation can be done in place. WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void MultiplyInverseDiagonal (IMatrix a, IVector diag, IMatrix result)
Right-multiplies a matrix with inverse of a diagonal matrix, and stores the result in the specified result matrix. R=A*diag(d)^-1 WARNING: dimensions of matrices must match, otherwise an exception is thrown.
static void MultiplyInverseDiagonal (IMatrix a, IVector diag, ref IMatrix result)
Right-multiplies a matrix with inverse of a diagonal matrix, and stores the result in the specified result matrix. R=A*diag(d)^-1 WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then the result is re-allocated.
static int GetHashCode (IMatrix mat)
Returns hashRet code of the specified matrix.
static bool Equals (IMatrix m1, IMatrix m2)
Returns true if the specified matrices are equal, false if not.
static int GetHashFunctionInt (IMatrix mat)
Returns an integer valued hashRet function of the specified matrix object.
static string GetHashFunctionString (IMatrix mat)
Returns a string valued hashRet function of the specified matrix object.
static string ToStringReadable (IMatrix mat, int accuracy=4, int padding=8)
Returns a readable string form of a matrix, accuracy and padding can be set.
static string ToStringNewlines (IMatrix mat)
Returns a string representation of the specified matrix with newlines inserted after each row. Rows and elements are printed in comma separated lists in curly brackets.
static string ToStringNewlines (IMatrix mat, string elementFormat)
Returns a string representation of the specified matrix with newlines inserted after each row, with the specified format for elements of the matrix. Rows and elements are printed in comma separated lists in curly brackets.
static string ToString (IMatrix mat)
Returns string representation of the current matrix in the standard IGLib form (Mathematica-like format but with C representation of numbers). Rows and elements are printed in comma separated lists in curly brackets.
static string ToStringMath (IMatrix mat)
Returns string representation of the current matrix in the standard IGLib form (Mathematica-like format but with C representation of numbers). Rows and elements are printed in comma separated lists in curly brackets.
static string ToString (IMatrix mat, string elementFormat)
Returns string representation of the current matrix in the standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified format for elements of the matrix. Rows and elements are printed in comma separated lists in curly brackets.
static string ToStringMath (IMatrix mat, string elementFormat)
Returns string representation of the current matrix in the standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified format for elements of the matrix. Rows and elements are printed in comma separated lists in curly brackets.
static void SaveJson (IMatrix mat, string filePath)
Saves (serializes) the specified matrix to the specified JSON file. File is owerwritten if it exists.
static void SaveJson (IMatrix mat, string filePath, bool append)
Saves (serializes) the specified matrix to the specified JSON file.
static void LoadJson (string filePath, ref IMatrix matRestored)
Restores (deserializes) a matrix object from the specified file in JSON format.
static MatrixBase operator+ (MatrixBase m)
Unary plus, returns the operand.
static MatrixBase operator- (MatrixBase m)
Unary negation, returns the negative operand.
static MatrixBase operator+ (MatrixBase a, MatrixBase b)
Matrix addition.
static MatrixBase operator- (MatrixBase a, MatrixBase b)
Matrix subtraction.
static MatrixBase operator* (MatrixBase a, MatrixBase b)
Product of two matrices.
static VectorBase operator* (MatrixBase a, VectorBase b)
Product of a matrix and a vector.
static MatrixBase operator* (MatrixBase a, double b)
Product of a matrix by a scalar.
static MatrixBase operator* (double a, MatrixBase b)
Product of a matrix by a scalar.
static MatrixBase operator/ (MatrixBase a, double b)
Matrix subtraction.
static double DeterminantSlow (IMatrix A)
Simpler but slower (compared to Determinant) implementation of determinant calculation of an arbitrary square real matrix.
static double Determinant (IMatrix A, ref int[] auxPermutations, ref IMatrix auxLU)
Calculates and returns determinant of a real-valued square matrix.
static void LuDecompose (IMatrix A, out int toggle, ref int[] perm, ref IMatrix result)
Calculates thr Doolittle LU decomposition with partial pivoting (LUP) of a square real matrix.
static void LuSolve (IMatrix luMatrix, int[] perm, IVector b, ref IVector auxVec, ref IVector x)
Solves a system of equations with the specified right-hand sides and the specified LU decomposition of the system matrix.
static void LuSolve (IMatrix luMatrix, int[] perm, IMatrix B, ref IVector auxVec, ref IVector auxRight, ref IVector auxX, ref IMatrix X)
Calculates inverse of the matrix from its specified LU decomposition.
static void LuInverse (IMatrix luMatrix, int[] perm, ref IVector auxRight, ref IVector auxX, ref IMatrix res)
Calculates inverse of the matrix from its specified LU decomposition.
static double LuDeterminant (IMatrix luMatrix, int toggle)
Calculates and returns matrix determinant form its specified LU decomposition.
static void LuExtractLower (IMatrix matLu, ref IMatrix result)
Extracts the lower part of the Doolittle specified LU decomposition (1s on diagonal, 0s in above diagonal) and stores it in the specified result matrix.
static IMatrix LuExtractUpper (IMatrix matLu, ref IMatrix result)
Extracts the upper part of the specified Doolittle LU decomposition 0s below diagonal) and stores it in the specified result matrix.
static void PermutationArrayToMatrix (int[] perm, ref IMatrix res)
Calculates and stores permutation matrix that correspond to the specified permutation array.
static void Permute (IMatrix A, int[] permutations, ref IMatrix result)
Permutes rows of the specified aquare matrix according to the specified permutations array.
static void UnPermute (IMatrix Apermuted, int[] permutations, ref int[] auxArray, ref IMatrix result)
Unpermutes the product of the specified DooLittle LU decomposition according to permutations array.
static bool TestLuDecomposition (int dim, int numRepetitions=1, double tol=1e-6, int outputLevel=0, IRandomGenerator randomGenerator=null, IMatrix A=null, IVector b=null)
Performs a test of calculatons performed via LU decomposition of a matrix. Calculation times and error extents are measured and reported (if specified).
static void TestLuDecompositionDemo ()
Demonstration of usae of LU decomposition.
static bool LdltDecompose (IMatrix A, ref IMatrix result, double tol=1e-12)
Calculates LDLT decomposition of a real symmetric square matrix.
static void LdltSolve (IMatrix decomposed, IVector b, ref IVector x)
Solves a system of eauations with the specified LDLT decomposition of a real symmetric square matrix.
static void LdltSolve (IMatrix ldltMatrix, IMatrix B, ref IVector auxX, ref IMatrix X)
Calculates inverse of the matrix from its specified LDLT-decomposed matrix.
static void LdltInverse (IMatrix ldltMatrix, ref IVector auxX, ref IMatrix res)
Calculates inverse of the matrix from its specified LDLT decomposition.
static double LdltDeterminant (IMatrix ldltMatrix)
Calculates and returns determinant of a square symmetric matrix form its specified LDLT decomposition.
static void LdltExtractLower (IMatrix matLdlt, ref IMatrix result)
Extracts the lower part of the specified LDLT decomposition (1s on diagonal, 0s above diagonal) and stores it in the specified result matrix.
static IMatrix LdltExtractUpper (IMatrix matLdlt, ref IMatrix result)
Extracts the upper part of the specified LDLT decomposition (1s on diagonal, 0s in below diagonal) and stores it in the specified result matrix.
static IMatrix LdltExtractDiagonal (IMatrix matLdlt, ref IMatrix result)
Extracts the diagonal part of the specified LDLT decomposition and stores it in the specified result matrix.
static bool TestLdltDecomposition (int dim, int numRepetitions=1, double tol=1e-6, int outputLevel=0, IRandomGenerator randomGenerator=null, IMatrix A=null, IVector b=null)
Performs a test of calculatons performed via LDLT decomposition of a matrix. Calculation times and error extents are measured and reported (if specified).
static bool CholeskyDecompose (IMatrix A, ref IMatrix result, double tol=1e-12)
Calculates Cholesky decomposition of a real symmetric square matrix.
static void CholeskySolve (IMatrix decomposed, IVector b, ref IVector x)
Solves a system of eauations with the specified Cholesky decomposition of a real symmetric square matrix.
static void CholeskySolve (IMatrix CholeskyMatrix, IMatrix B, ref IVector auxX, ref IMatrix X)
Calculates inverse of the matrix from its specified Cholesky-decomposed matrix.
static void CholeskyInverse (IMatrix CholeskyMatrix, ref IVector auxX, ref IMatrix res)
Calculates inverse of the matrix from its specified Cholesky decomposition.
static double CholeskyDeterminant (IMatrix CholeskyMatrix)
Calculates and returns determinant of a square symmetric matrix form its specified Cholesky decomposition.
static void CholeskyExtractLower (IMatrix matCholesky, ref IMatrix result)
Extracts the lower part of the specified Cholesky decomposition (0s above diagonal) and stores it in the specified result matrix.
static IMatrix CholeskyExtractUpper (IMatrix matCholesky, ref IMatrix result)
Extracts the upper part of the specified Cholesky decomposition (0s in below diagonal) and stores it in the specified result matrix.
static bool TestCholeskyDecomposition (int dim, int numRepetitions=1, double tol=1e-6, int outputLevel=0, IRandomGenerator randomGenerator=null, IMatrix A=null, IVector b=null)
Performs test of calculatons performed via Cholesky decomposition of a matrix. Calculation times and error extents are measured and reported (if specified so).
static void TestCholeskyDecompositionDemo ()
Demonstration of usae of Cholesky decomposition.
static bool QrDecomposeGrammSchmidt (IMatrix A, ref IMatrix resQ, ref IMatrix resR, double tol=1e-12)
Calculates QR decomposition of a real invertible matrix by using Gramm-Schmidt orthogonalization.
static bool QrDecompose (IMatrix A, ref IMatrix resQ, ref IMatrix resR, double tol=1e-12)
Calculates QR decomposition of a real invertible matrix.
static void QrSolve (IMatrix factorQ, IMatrix factorR, IVector b, ref IVector x)
Solves a system of eauations with the specified QR decomposition of a real symmetric square matrix.
static void QrSolve (IMatrix factorQ, IMatrix factorR, IMatrix B, ref IVector auxB, ref IVector auxX, ref IMatrix X)
Calculates inverse of the matrix from its specified LDLT-decomposed matrix.
static void QrInverse (IMatrix factorQ, IMatrix factorR, ref IVector auxB, ref IVector auxX, ref IMatrix res)
Calculates inverse of the matrix from its specified LDLT decomposition.
static bool TestMatrixProducts (bool printReports)
Tests various matrix and vector products with fixed tolerance of 1.0E-6.
static bool TestMatrixProducts (double tolerance)
Tests various matrix and vector products, without printing reports.
static bool TestMatrixProducts ()
Tests various matrix and vector products with fixed tolerance of 1.0E-6 and without printing reports.
static bool TestMatrixProducts (double tolerance, bool printReports)
Tests various matrix and vector products.
static void TestStaticMethodCommon ()
A test method, just prints some output.
static void TestStaticMethodSpecific ()
A test method, just prints some output.
static bool TestIndices (int dim1=3, int dim2=4, IMatrix providedMatrix=null)
Performs test of converson between double indexing and flat indexing of matric elements,. Returns true if successful, false othwrwise.
Static Private Member Functions
static bool TestDecompositionLLT (double tolerance, bool printReports)
Tests Cholecki decomposition of a matrix.
static bool TestSolveLLT (double tolerance, bool printReports)
Tests solution of a system of equations with a Choleski-decomposed matrix.
Additional Inherited Members
Public Member Functions inherited from IG.Num.MatrixBase
abstract MatrixBase GetCopyBase ()
Creates and returns a copy of the current matrix.
abstract MatrixBase GetNewBase (int rowCount, int columnCount)
Creates and returns a new matrix with the specified dimensions, and of the same type as the current matrix.
abstract MatrixBase GetNewBase ()
Creates and returns a new matrix with the same dimensions and of the same type as the current matrix.
abstract VectorBase GetNewVectorBase (int length)
Creates and returns a new vector with the specified dimension, and of the type that is consistent with the type of the current vector.
virtual IMatrix GetCopy ()
Creates and returns a copy of the current matrix.
virtual IMatrix GetNew (int rowCount, int columnCount)
Creates and returns a new matrix with the specified dimensions, and of the same type as the current matrix.
virtual IMatrix GetNew ()
Creates and returns a new matrix with the same dimensions and of the same type as the current matrix.
virtual IVector GetNewVector (int length)
Creates and returns a new vector with the specified dimension, and of the type that is consistent with the type of the current vector.
virtual double[,] ToArray ()
Creates and returns a rectangular 2D array that contains a component-wise copy of the matrix.
virtual double[][] ToJaggedArray ()
Creates and returns a jagged 2D array that contains a component-wise copy of the matrix.
virtual int Index (int row, int column)
Calculates and returns flat index corresponding to the specified row and column indices of the current matrix.
virtual void Indices (int flatIndex, out int row, out int column)
Returns (through output arguments) row and column indices corresponding to the specified flat index in the current matrix.
virtual void SetZero ()
Sets all components of the current matrix to 0.
virtual void SetConstant (double elementValue)
Sets all components of the current matrix to the specified value.
virtual void SetIdentity ()
Sets the current matrix to identity matrix. WARNING: Exception is thrown if a matrix is not square. For nonsquare matrices, use SetDiagonal(1.0)!
virtual void SetRandom ()
Sets the current matrix such that it contains random elements on the interval (0,1].
virtual void SetRandom (IRandomGenerator rnd)
Sets the current matrix such that it contains random elements on the interval (0,1].
virtual void SetDiagonal (double diagonalElement)
Sets the current matrix to the diagonal matrix with all diagonal elements equal to the specified value. Matrix does not need to be a square matrix.
virtual void SetDiagonal (IVector diagonal)
Sets the current matrix to the diagonal matrix with diagonal element specified by a vector.
virtual bool IsSquare ()
Returns true if the current matrix is a square matrix, and false if not.
virtual bool IsSymmetric ()
Returns true if the current matrix is symmetric, and false if not. If the matrix is not a square matrix then false is returned.
virtual bool IsSymmetric (double relativeRMSTolerance=0.0)
Returns true if the specified matrix is symmetric within some tolerance, and false if not. If the matrix is null then false is returned.
virtual void Negate ()
Negates the current matrix.
virtual void Transpose ()
Transposes the current matrix. WARNING: this operation can only be done on square matrices!
override int GetHashCode ()
Returns the hashRet code (hashRet function) of the current matrix.
override bool Equals (Object obj)
Returns a value indicating whether the specified object is equal to the current matrix.
int GetHashFunctionInt ()
Returns an integer valued hashRet function of the current matrix object.
string GetHashFunctionString ()
Returns a string valued hashRet function of the current matrix object.
override string ToString ()
Returns string representation of the current matrix in the standard IGLib form. Rows and elements are printed in comma separated lists in curly brackets.
virtual string ToStringReadable (int accuracy=4, int padding=8)
Returns a readable an easily string form of a matrix, accuracy and padding can be set.
virtual string ToStringNewlines ()
Returns a string representation of this matrix with newlines inserted after each row. Rows and elements are printed in comma separated lists in curly brackets.
virtual string ToStringNewlines (string elementFormat)
Returns a string representation of this matrix with newlines inserted after each row, with the specified format for elements of the matrix. Rows and elements are printed in comma separated lists in curly brackets.
virtual string ToStringMath ()
Returns string representation of the current matrix in the standard IGLib form (Mathematica-like format but with C representation of numbers). Rows and elements are printed in comma separated lists in curly brackets.
virtual string ToString (string elementFormat)
Returns a string representation of the current matrix in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified format for elements of the matrix.
virtual string ToStringMath (string elementFormat)
Returns a string representation of the current matrix in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified format for elements of the matrix.
Static Protected Member Functions inherited from IG.Num.MatrixBase
static void LuSolveNoPermutationsPlain (IMatrix luMatrix, IVector b, IVector x)
Solves a system of equations with the specified LU decomposition with already permuted b.
static bool CheckTestResult (IMatrix result, IMatrix referenceResult, double tolerance, bool printReports)
Checks whether the difference between matrix result of the tested operation and some reference result is within the specified tolerance.
static bool CheckTestResult (IVector result, IVector referenceResult, double tolerance, bool printReports)
Checks whether the difference between matrix result of the tested operation and some reference result is within the specified tolerance.
Properties inherited from IG.Num.MatrixBase
abstract int RowCount [get]
Gets the number of rows of the current matrix.
abstract int ColumnCount [get]
Gets the number of columns of the current matrix.
virtual int Count [get]
Gets total number of elements.
virtual IMatrix T [get]
Returns a new matrix that is transpose of the current matrix.
virtual double this[int flatIndex] [get, set]
Gets or set the element indexed by a flat index in the Matrix.
virtual double this[int row, int column] [get, set]
Gets or set the element indexed by (i, j) in the Matrix.
virtual double Trace [get]
Gets matrix trace (sum of diagonal terms).
virtual double NormForbenius [get]
Gets Forbenious (or Euclidean) norm of the matrix - square root of sum of squares of elements.
virtual double NormEuclidean [get]
Gets Forbenious (or Euclidean) norm of the matrix - square root of sum of squares of elements.
virtual double Norm [get]
Gets Forbenious (or Euclidean) norm of the matrix - square root of sum of squares of elements.
static MatrixStore MatrixStore [get]
Gets the matrix store for recycling auxiliary matrices.
Detailed Description
Development of matrix operations.
$A Igor May09;
Member Function Documentation
static IMatrix IG.Num.MatrixBaseDev.CreateRandomSymmetricPositiveDefinite (int dim, IRandomGenerator rnd) inline static
Attemps to create and return a symmetric positive definite square matrix.
Parameters
dim Dimention of the matrix.
rnd Random number generator.
References IG.Num.MatrixBase.MultiplyTranspMat(), IG.Num.IRandomGenerator.NextDouble(), and IG.Num.MatrixBase.SymmetricPartPlain().
static IMatrix IG.Num.MatrixBaseDev.CreateRandomSymmetricPositiveDefinite (int dim) inline static
Attemps to create and return a symmetric positive definite square matrix.
Parameters
dim Dimention of the matrix.
rnd Random number generator.
static int IG.Num.MatrixBaseDev.DecomposeLLTPlain (IMatrix m1, IMatrix res) inline static
LLT (Choleski) DECOMPOSITION (symmetric positive definite matrices)
Performs Choleski (LLT) decomposition of a matrix and stores result to the specified matrix. Can be done in place. WARNING: Dimensions are not checked, therefore dimensions of arguments must be consistent. Method also does not control whethe matrix is symmetric, but it simply operates on the lower triangle of the original.
Parameters
m1 Matrix whose Choleski decomposition is performed. It must be symmetric and positive definite in order for operation to succeed.
res Resulting matrix where the decomposed matrix is stored. Can be the same matrix as m1. Only lower triangle is stored, and elements above diagonal are 0. Diagonal elements are positive.
Returns
0 if the decomposition has been successfully performed (i.e. the matrix is positive definite). A negative number otherwise: minus row number (1-based) if the calculated diagonal element in this row is zero.
Transcribed from IOptLib C library.
$A Igor May09;
static int IG.Num.MatrixBaseDev.DecomposeLLTPlain (IMatrix m1, IMatrix res, double smalltol) inline static
Performs Choleski (LLT) decomposition of a matrix and stores result to the specified matrix. Can be done in place. WARNING: Dimensions are not checked, therefore dimensions of arguments must be consistent. Method also does not control whethe matrix is symmetric, but it simply operates on the lower triangle of the original.
Parameters
m1 Matrix whose Choleski decomposition is performed. It must be symmetric and positive definite in order for operation to succeed.
res Resulting matrix where the decomposed matrix is stored. Can be the same matrix as m1. Only lower triangle is stored, and elements above diagonal are 0. Diagonal elements are positive.
smalltol Tolerance for size of diagonal element and ratio between minimal and maximal diagonal element. Can be 0. If the mentioned values are less or equal to the tolerance then it is considered that decomposition can not be performed.
Returns
0 if the decomposition has been successfully performed (i.e. the matrix is positive definite). A negative number otherwise: minus row number (1-based) if the calculated diagonal element in this row is zero (within tolerance). minus number of rows minus 1 if the ratio between minimal and maximal diagonal element is below the tolerance.
Transcribed from IOptLib C library.
$A Igor May09;
static int IG.Num.MatrixBaseDev.DecomposeLLT (IMatrix m1, IMatrix res, double smalltol) inline static
static int IG.Num.MatrixBaseDev.DecomposeLLT (IMatrix m1, ref IMatrix res, double smalltol) inline static
References IG.Num.IMatrix.GetNew().
static void IG.Num.MatrixBaseDev.SolveLLTPlain (IMatrix L, IVector b, IVector x) inline static
Solves a linear system of equations by using a Choleski (LLT) decomposition of the system matrix. Linear system to be solved is L LT x = b, where L is a lower triangular matrix. Can be done in place, x and b can be the same vectors. WARNING: Dimensions are not checked, therefore dimensions of arguments must be consistent.
Parameters
L Choleski decomposition of the matrix of the system.
b Vector of right-hand sides.
x Vector where solution is stored.
The function is usually used for back-substitution after the Choleski (LLT) decomposition for positive definite matrices. A system of equations with a symmetric invertible matrix A can be converted to a system with a positive definite matrix by multiplying the matrix and the right-hand side vector by AT: A x = b => (AT A) x = (AT b). This is however not feasible because preparation of the system takes much more time th is much better to perform the LDLT deocmposition. Transcribed from IOptLib C library.
$A Igor May09;
static void IG.Num.MatrixBaseDev.SolveLLT (IMatrix L, IVector b, IVector x) inline static
static void IG.Num.MatrixBaseDev.SolveLLT (IMatrix L, IVector b, ref IVector x) inline static
References IG.Num.IMatrix.GetNewVector().
static void IG.Num.MatrixBaseDev.GetFactorsLLTPlain (IMatrix LLT, IMatrix L, IMatrix LT) inline static
Splits the LLT product contained in a lower triangular part of a single matrix into separate lower triangular and upper diagonal factors, and stores them in the specified matrices. matrices. Both matrices where the split part is stored can be the same objects as the original matrix. WARNING: This method does not check consistency of matrix dimensons.
Parameters
LLT A matrix containing the lower triangular Choleski product.
L Matrix where the lower triangular factor is stored.
LT Matrix where the upper triangular factor is stored.
static void IG.Num.MatrixBaseDev.GetFactorsLLT (IMatrix LLT, IMatrix L, IMatrix LT) inline static
static void IG.Num.MatrixBaseDev.GetFactorsLLT (IMatrix LLT, ref IMatrix L, ref IMatrix LT) inline static
References IG.Num.IMatrix.GetNew().
static bool IG.Num.MatrixBaseDev.TestDecompositionLLT (double tolerance, bool printReports) inline static private
Tests Cholecki decomposition of a matrix.
Parameters
tolerance Tolerance (on norm of the difference) for the test to pass.
printReports Specifies whether to print reports or not.
Returns
true if the test passes, false if not.
static bool IG.Num.MatrixBaseDev.TestSolveLLT (double tolerance, bool printReports) inline static private
Tests solution of a system of equations with a Choleski-decomposed matrix.
Parameters
tolerance Tolerance (on norm of the difference) for the test to pass.
printReports Specifies whether to print reports or not.
Returns
true if the test passes, false if not.
References IG.Num.IVector.SetRandom().
static bool IG.Num.MatrixBaseDev.TestMatrixDecompositions (bool printReports) inline static
Tests various matrix and vector decompositions with fixed tolerance of 1.0E-6.
Parameters
printReports Specifies whether to print short reports to console or not.
Returns
True if all tests have passed, and false if there is an error.
Referenced by IG.Script.Script_Numeric.TestMatrixOperations().
static bool IG.Num.MatrixBaseDev.TestMatrixDecompositions (double tolerance) inline static
Tests various matrix and vector decompositions, without printing reports.
Parameters
tolerance Tolerance for difference between product and test expression below which any individual test passes. Must be greater than 0.
Returns
True if all tests have passed, and false if there is an error.
static bool IG.Num.MatrixBaseDev.TestMatrixDecompositions () inline static
Tests various matrix and vector decompositions with fixed tolerance of 1.0E-6 and without printing reports.
Returns
True if all tests have passed, and false if there is an error.
static bool IG.Num.MatrixBaseDev.TestMatrixDecompositions (double tolerance, bool printReports) inline static
Tests various matrix and vector decompositions.
Parameters
tolerance Tolerance for difference between product and test expression below which any individual test passes. Must be greater than 0.
printReports Specifies whether to print short reports to console or not.
Returns
True if all tests have passed, and false if there is an error.
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/0develop/matrix/MatrixBaseDev.cs