IGLib: alglib.testminlbfgsunit Class Reference
alglib.testminlbfgsunit Class Reference
Static Public Member Functions
static bool testminlbfgs (bool silent)
static bool testminlbfgs (bool silent)
static bool _pexec_testminlbfgs (bool silent)
Static Private Member Functions
static void testfunc1 (minlbfgs.minlbfgsstate state)
static void testfunc2 (minlbfgs.minlbfgsstate state)
static void testfunc3 (minlbfgs.minlbfgsstate state)
static void calciip2 (minlbfgs.minlbfgsstate state, int n)
static void testpreconditioning (ref bool err)
static void testother (ref bool err)
static bool gradientchecktest ()
static void funcderiv (double a, double b, double c, double d, double x0, double x1, double x2, double[] x, int functype, ref double f, ref double[] g)
static void testfunc1 (minlbfgs.minlbfgsstate state)
static void testfunc2 (minlbfgs.minlbfgsstate state)
static void testfunc3 (minlbfgs.minlbfgsstate state)
static void calciip2 (minlbfgs.minlbfgsstate state, int n)
static void testpreconditioning (ref bool err)
static void testother (ref bool err)
static bool gradientchecktest ()
static void funcderiv (double a, double b, double c, double d, double x0, double x1, double x2, double[] x, int functype, ref double f, ref double[] g)
Member Function Documentation
static bool alglib.testminlbfgsunit.testminlbfgs (bool silent) inline static
References alglib.testminlbfgsunit.gradientchecktest(), alglib.minlbfgs.minlbfgscreate(), alglib.minlbfgs.minlbfgscreatef(), alglib.minlbfgs.minlbfgsiteration(), alglib.minlbfgs.minlbfgsrestartfrom(), alglib.minlbfgs.minlbfgsresults(), alglib.minlbfgs.minlbfgssetcond(), alglib.minlbfgs.minlbfgssetstpmax(), alglib.math.randomreal(), alglib.math.sqr(), alglib.testminlbfgsunit.testfunc2(), alglib.testminlbfgsunit.testfunc3(), alglib.testminlbfgsunit.testother(), and alglib.testminlbfgsunit.testpreconditioning().
Referenced by alglib.testminlbfgsunit._pexec_testminlbfgs(), and _Test.Main().
static void alglib.testminlbfgsunit.testfunc1 (minlbfgs.minlbfgsstate state) inline static private
References alglib.math.maxrealnumber, and alglib.math.sqr().
static void alglib.testminlbfgsunit.testfunc2 (minlbfgs.minlbfgsstate state) inline static private
References alglib.math.maxrealnumber, and alglib.math.sqr().
Referenced by alglib.testminlbfgsunit.testminlbfgs().
static void alglib.testminlbfgsunit.testfunc3 (minlbfgs.minlbfgsstate state) inline static private
References alglib.math.maxrealnumber, and alglib.math.sqr().
Referenced by alglib.testminlbfgsunit.testminlbfgs().
static void alglib.testminlbfgsunit.calciip2 (minlbfgs.minlbfgsstate state, int n) inline static private
References alglib.math.sqr().
Referenced by alglib.testminlbfgsunit.testpreconditioning().
static void alglib.testminlbfgsunit.testpreconditioning (ref bool err) inline static private
References alglib.testminlbfgsunit.calciip2(), alglib.minlbfgs.minlbfgscreate(), alglib.minlbfgs.minlbfgsiteration(), alglib.minlbfgs.minlbfgsrestartfrom(), alglib.minlbfgs.minlbfgsresults(), alglib.minlbfgs.minlbfgssetpreccholesky(), alglib.minlbfgs.minlbfgssetprecdefault(), alglib.minlbfgs.minlbfgssetprecdiag(), alglib.minlbfgs.minlbfgssetprecscale(), alglib.minlbfgs.minlbfgssetscale(), alglib.math.randominteger(), alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testminlbfgsunit.testminlbfgs().
static void alglib.testminlbfgsunit.testother (ref bool err) inline static private
References alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.minlbfgs.minlbfgscreate(), alglib.minlbfgs.minlbfgscreatef(), alglib.minlbfgs.minlbfgsiteration(), alglib.minlbfgs.minlbfgsrestartfrom(), alglib.minlbfgs.minlbfgsresults(), alglib.minlbfgs.minlbfgssetcond(), alglib.minlbfgs.minlbfgssetprecdiag(), alglib.minlbfgs.minlbfgssetprecscale(), alglib.minlbfgs.minlbfgssetscale(), alglib.minlbfgs.minlbfgssetstpmax(), alglib.minlbfgs.minlbfgssetxrep(), alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testminlbfgsunit.testminlbfgs().
static bool alglib.testminlbfgsunit.gradientchecktest () inline static private
References alglib.testminlbfgsunit.funcderiv(), alglib.minlbfgs.minlbfgscreate(), alglib.minlbfgs.minlbfgsiteration(), alglib.minlbfgs.minlbfgsrestartfrom(), alglib.minlbfgs.minlbfgsresults(), alglib.minlbfgs.minlbfgssetcond(), alglib.minlbfgs.minlbfgssetgradientcheck(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testminlbfgsunit.testminlbfgs().
static void alglib.testminlbfgsunit.funcderiv (double a, double b, double c, double d, double x0, double x1, double x2, double[] x, int functype, ref double f, ref double[] g) inline static private
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.math.sqr().
Referenced by alglib.testminlbfgsunit.gradientchecktest().
static bool alglib.testminlbfgsunit.testminlbfgs (bool silent) inline static
References alglib.testminlbfgsunit.gradientchecktest(), alglib.minlbfgs.minlbfgscreate(), alglib.minlbfgs.minlbfgscreatef(), alglib.minlbfgs.minlbfgsiteration(), alglib.minlbfgs.minlbfgsrestartfrom(), alglib.minlbfgs.minlbfgsresults(), alglib.minlbfgs.minlbfgssetcond(), alglib.minlbfgs.minlbfgssetstpmax(), alglib.math.randomreal(), alglib.math.sqr(), alglib.testminlbfgsunit.testfunc2(), alglib.testminlbfgsunit.testfunc3(), alglib.testminlbfgsunit.testother(), and alglib.testminlbfgsunit.testpreconditioning().
static bool alglib.testminlbfgsunit._pexec_testminlbfgs (bool silent) inline static
References alglib.testminlbfgsunit.testminlbfgs().
Referenced by _Test.Main().
static void alglib.testminlbfgsunit.testfunc1 (minlbfgs.minlbfgsstate state) inline static private
References alglib.math.maxrealnumber, and alglib.math.sqr().
static void alglib.testminlbfgsunit.testfunc2 (minlbfgs.minlbfgsstate state) inline static private
References alglib.math.maxrealnumber, and alglib.math.sqr().
static void alglib.testminlbfgsunit.testfunc3 (minlbfgs.minlbfgsstate state) inline static private
References alglib.math.maxrealnumber, and alglib.math.sqr().
static void alglib.testminlbfgsunit.calciip2 (minlbfgs.minlbfgsstate state, int n) inline static private
References alglib.math.sqr().
static void alglib.testminlbfgsunit.testpreconditioning (ref bool err) inline static private
References alglib.testminlbfgsunit.calciip2(), alglib.minlbfgs.minlbfgscreate(), alglib.minlbfgs.minlbfgsiteration(), alglib.minlbfgs.minlbfgsrestartfrom(), alglib.minlbfgs.minlbfgsresults(), alglib.minlbfgs.minlbfgssetpreccholesky(), alglib.minlbfgs.minlbfgssetprecdefault(), alglib.minlbfgs.minlbfgssetprecdiag(), alglib.minlbfgs.minlbfgssetprecscale(), alglib.minlbfgs.minlbfgssetscale(), alglib.math.randominteger(), alglib.math.randomreal(), and alglib.math.sqr().
static void alglib.testminlbfgsunit.testother (ref bool err) inline static private
References alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.minlbfgs.minlbfgscreate(), alglib.minlbfgs.minlbfgscreatef(), alglib.minlbfgs.minlbfgsiteration(), alglib.minlbfgs.minlbfgsrestartfrom(), alglib.minlbfgs.minlbfgsresults(), alglib.minlbfgs.minlbfgssetcond(), alglib.minlbfgs.minlbfgssetprecdiag(), alglib.minlbfgs.minlbfgssetprecscale(), alglib.minlbfgs.minlbfgssetscale(), alglib.minlbfgs.minlbfgssetstpmax(), alglib.minlbfgs.minlbfgssetxrep(), alglib.math.randomreal(), and alglib.math.sqr().
static bool alglib.testminlbfgsunit.gradientchecktest () inline static private
References alglib.testminlbfgsunit.funcderiv(), alglib.minlbfgs.minlbfgscreate(), alglib.minlbfgs.minlbfgsiteration(), alglib.minlbfgs.minlbfgsrestartfrom(), alglib.minlbfgs.minlbfgsresults(), alglib.minlbfgs.minlbfgssetcond(), alglib.minlbfgs.minlbfgssetgradientcheck(), alglib.math.randominteger(), alglib.apserv.randomnormal(), and alglib.math.randomreal().
static void alglib.testminlbfgsunit.funcderiv (double a, double b, double c, double d, double x0, double x1, double x2, double[] x, int functype, ref double f, ref double[] g) inline static private
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.math.sqr().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs