IGLib: NUnit.Framework.CultureAttribute Class Reference
NUnit.Framework.CultureAttribute Class Reference
CultureAttribute is used to mark a test fixture or an individual method as applying to a particular Culture only.
Public Member Functions
CultureAttribute ()
Constructor with no cultures specified, for use with named property syntax.
CultureAttribute (string cultures)
Constructor taking one or more cultures
void ApplyToTest (Test test)
Causes a test to be skipped if this CultureAttribute is not satisfied.
bool IsCultureSupported (string culture)
Test to determine if the a particular culture or comma- delimited set of cultures is in use.
bool IsCultureSupported (string[] cultures)
Test to determine if one of a collection of cultures is being used currently.
Public Member Functions inherited from NUnit.Framework.IncludeExcludeAttribute
IncludeExcludeAttribute ()
Constructor with no included items specified, for use with named property syntax.
IncludeExcludeAttribute (string include)
Constructor taking one or more included items
Public Member Functions inherited from NUnit.Framework.NUnitAttribute
NUnitAttribute ()
Default constructor
Private Member Functions
bool IsCultureSupported ()
Tests to determine if the current culture is supported based on the properties of this attribute.
Private Attributes
CultureDetector cultureDetector = new CultureDetector()
CultureInfo currentCulture = CultureInfo.CurrentCulture
Additional Inherited Members
Properties inherited from NUnit.Framework.IncludeExcludeAttribute
string Include [get, set]
Name of the item that is needed in order for a test to run. Multiple items may be given, separated by a comma.
string Exclude [get, set]
Name of the item to be excluded. Multiple items may be given, separated by a comma.
string Reason [get, set]
The reason for including or excluding the test
Detailed Description
CultureAttribute is used to mark a test fixture or an individual method as applying to a particular Culture only.
Constructor & Destructor Documentation
NUnit.Framework.CultureAttribute.CultureAttribute () inline
Constructor with no cultures specified, for use with named property syntax.
NUnit.Framework.CultureAttribute.CultureAttribute (string cultures) inline
Constructor taking one or more cultures
Parameters
cultures Comma-deliminted list of cultures
Member Function Documentation
void NUnit.Framework.CultureAttribute.ApplyToTest (Test test) inline
Causes a test to be skipped if this CultureAttribute is not satisfied.
Parameters
test The test to modify
Implements NUnit.Framework.Interfaces.IApplyToTest.
References NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Interfaces.IPropertyBag.Set(), and NUnit.Framework.Internal.PropertyNames.SkipReason.
Referenced by NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeExcludingCurrentCultureSkipsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeExcludingOtherCultureRunsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeIncludingCurrentCultureRunsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeIncludingOtherCultureSkipsTest(), and NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeWithMultipleCulturesIncluded().
bool NUnit.Framework.CultureAttribute.IsCultureSupported () inline private
Tests to determine if the current culture is supported based on the properties of this attribute.
Returns
True, if the current culture is supported
References NUnit.Framework.Internal.CultureDetector.IsCultureSupported().
bool NUnit.Framework.CultureAttribute.IsCultureSupported (string culture) inline
Test to determine if the a particular culture or comma- delimited set of cultures is in use.
Parameters
culture Name of the culture or comma-separated list of culture ids
Returns
True if the culture is in use on the system
bool NUnit.Framework.CultureAttribute.IsCultureSupported (string[] cultures) inline
Test to determine if one of a collection of cultures is being used currently.
Parameters
cultures
Returns
Member Data Documentation
CultureDetector NUnit.Framework.CultureAttribute.cultureDetector = new CultureDetector() private
CultureInfo NUnit.Framework.CultureAttribute.currentCulture = CultureInfo.CurrentCulture private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Attributes/CultureAttribute.cs