IGLib: igsandbox/InterprocessCommunication/named_pipe_examples_master/C++ server & C# clien HALF-DUPLEX/ClientCsharp/SnmpAbb/Program.cs File Reference
Program.cs File Reference
Classes
class CSPipe.Program
Namespaces
package CSPipe
Functions
void client ()
Function Documentation
void client ()
Referenced by IG.Test.Tasks.AccessTheWebAsync(), IG.Lib.CommandLineApplicationInterpreter.CmdPipeClientCreate(), IG.Lib.CommandLineApplicationInterpreter.CreatePipeClient(), IG.Forms.TestTcpMultiThreadedServer.ListenerLoop(), PipeServer.Server.ListenForClients(), IG.Forms.client_program.Main(), IG.Lib.CommandLineApplicationInterpreter.PipeClientGetServerResponse(), IG.Lib.CommandLineApplicationInterpreter.PipeClientInfo(), PipeServer.Form1.pipeServer_MessageReceived(), PipeServer.Server.Read(), IG.Lib.CommandLineApplicationInterpreter.RemovePipeClients(), and PipeServer.Server.SendMessage().