IGLib: NUnit.Engine.Services.DomainManager Class Reference
NUnit.Engine.Services.DomainManager Class Reference
The DomainManager class handles the creation and unloading of domains as needed and keeps track of all existing domains.
Classes
class DomainUnloader
class TargetFrameworkAgent
Public Member Functions
AppDomain CreateDomain (TestPackage package)
Construct an application domain for running a test package
void Unload (AppDomain domain)
void DeleteShadowCopyPath ()
override void StartService ()
Initialize the Service
Public Member Functions inherited from NUnit.Engine.Services.Service
virtual void StopService ()
Do any cleanup needed before terminating the service
void Dispose ()
Static Public Member Functions
static string GetApplicationBase (TestPackage package)
Figure out the ApplicationBase for a package
static string GetConfigFile (string appBase, TestPackage package)
static string GetCommonAppBase (IList< TestPackage > packages)
static string GetCommonAppBase (IList< string > assemblies)
static string GetPrivateBinPath (string basePath, string fileName)
static string GetPrivateBinPath (string appBase, TestPackage package)
static string GetPrivateBinPath (string basePath, IList< TestPackage > packages)
static string GetPrivateBinPath (string basePath, IList< string > assemblies)
Private Member Functions
AppDomainSetup CreateAppDomainSetup (TestPackage package)
string GetCachePath ()
Get the location for caching and delete any old cache info
bool IsTestDomain (AppDomain domain)
Static Private Member Functions
static bool IsExecutable (string fileName)
static void DeleteCacheDir (DirectoryInfo cacheDir)
Helper method to delete the cache dir. This method deals with a bug that occurs when files are marked read-only and deletes each file separately in order to give better exception information when problems occur.
static void SetTargetFramework (string assemblyPath, AppDomainSetup setup)
Private Attributes
ISettings _settingsService
string _shadowCopyPath = Path.Combine(NUnitConfiguration.NUnitBinDirectory, "ShadowCopyCache")
Static Private Attributes
static Logger log = InternalTrace.GetLogger(typeof(DomainManager))
Additional Inherited Members
Protected Member Functions inherited from NUnit.Engine.Services.Service
virtual void Dispose (bool disposing)
Protected Attributes inherited from NUnit.Engine.Services.Service
bool _disposed = false
Properties inherited from NUnit.Engine.Services.Service
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get, protected set]
Gets the ServiceStatus of this service
Properties inherited from NUnit.Engine.IService
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get]
Gets the ServiceStatus of this service
Detailed Description
The DomainManager class handles the creation and unloading of domains as needed and keeps track of all existing domains.
Member Function Documentation
AppDomain NUnit.Engine.Services.DomainManager.CreateDomain (TestPackage package) inline
Construct an application domain for running a test package
Parameters
package The TestPackage to be run
Referenced by NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomain(), NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified(), NUnit.Engine.Services.Tests.DomainManagerTests.CanUnloadDomain(), NUnit.Engine.Runners.TestDomainRunner.LoadPackage(), and NUnit.Engine.Services.Tests.DomainManagerTests.UnloadingTwiceDoesNoHarm().
AppDomainSetup NUnit.Engine.Services.DomainManager.CreateAppDomainSetup (TestPackage package) inline private
References NUnit.Engine.TestPackage.FullName, and NUnit.Engine.TestPackage.SubPackages.
void NUnit.Engine.Services.DomainManager.Unload (AppDomain domain) inline
References NUnit.Engine.Services.DomainManager.DomainUnloader.Unload().
Referenced by NUnit.Engine.Services.Tests.DomainManagerTests.CanUnloadDomain(), NUnit.Engine.Services.Tests.DomainManagerTests.UnloadingTwiceDoesNoHarm(), and NUnit.Engine.Runners.TestDomainRunner.UnloadPackage().
static string NUnit.Engine.Services.DomainManager.GetApplicationBase (TestPackage package) inline static
Figure out the ApplicationBase for a package
Parameters
package The package
Returns
The ApplicationBase
References NUnit.Common.Guard.ArgumentNotNull(), NUnit.Common.PackageSettings.BasePath, NUnit.Engine.TestPackage.FullName, and NUnit.Engine.TestPackage.SubPackages.
Referenced by NUnit.Engine.Services.Tests.DomainManagerStaticTests.ApplicationBaseTests().
static string NUnit.Engine.Services.DomainManager.GetConfigFile (string appBase, TestPackage package) inline static
References NUnit.Common.Guard.ArgumentNotNull(), NUnit.Common.Guard.ArgumentNotNullOrEmpty(), NUnit.Common.PackageSettings.ConfigurationFile, NUnit.Engine.TestPackage.FullName, and NUnit.Engine.TestPackage.SubPackages.
Referenced by NUnit.Engine.Services.Tests.DomainManagerStaticTests.ConfigFileTests().
static bool NUnit.Engine.Services.DomainManager.IsExecutable (string fileName) inline static private
string NUnit.Engine.Services.DomainManager.GetCachePath () inline private
Get the location for caching and delete any old cache info
static void NUnit.Engine.Services.DomainManager.DeleteCacheDir (DirectoryInfo cacheDir) inline static private
Helper method to delete the cache dir. This method deals with a bug that occurs when files are marked read-only and deletes each file separately in order to give better exception information when problems occur.
TODO: This entire method is problematic. Should we be doing it?
Parameters
cacheDir
References NUnit.Common.Debug.
bool NUnit.Engine.Services.DomainManager.IsTestDomain (AppDomain domain) inline private
static string NUnit.Engine.Services.DomainManager.GetCommonAppBase (IList< TestPackage > packages) inline static
Referenced by NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_OneElement(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_ThreeElements_DifferentDirectories(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_TwoElements_DifferentDirectories(), and NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_TwoElements_SameDirectory().
static string NUnit.Engine.Services.DomainManager.GetCommonAppBase (IList< string > assemblies) inline static
References NUnit.Engine.Internal.PathUtils.SamePathOrUnder().
static string NUnit.Engine.Services.DomainManager.GetPrivateBinPath (string basePath, string fileName) inline static
Referenced by NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetPrivateBinPath(), and NUnit.Engine.Services.Tests.DomainManagerStaticTests.PrivateBinPathTests().
static string NUnit.Engine.Services.DomainManager.GetPrivateBinPath (string appBase, TestPackage package) inline static
References NUnit.Common.PackageSettings.AutoBinPath, NUnit.Engine.TestPackage.FullName, NUnit.Common.PackageSettings.PrivateBinPath, and NUnit.Engine.TestPackage.SubPackages.
static string NUnit.Engine.Services.DomainManager.GetPrivateBinPath (string basePath, IList< TestPackage > packages) inline static
static string NUnit.Engine.Services.DomainManager.GetPrivateBinPath (string basePath, IList< string > assemblies) inline static
References NUnit.Engine.Internal.PathUtils.RelativePath().
void NUnit.Engine.Services.DomainManager.DeleteShadowCopyPath () inline
override void NUnit.Engine.Services.DomainManager.StartService () inline virtual
Initialize the Service
Reimplemented from NUnit.Engine.Services.Service.
References NUnit.Engine.ServiceContext.GetService(), and NUnit.Engine.ISettings.GetSetting().
static void NUnit.Engine.Services.DomainManager.SetTargetFramework (string assemblyPath, AppDomainSetup setup) inline static private
References NUnit.Engine.Services.DomainManager.TargetFrameworkAgent.GetTargetFrameworkName().
Member Data Documentation
Logger NUnit.Engine.Services.DomainManager.log = InternalTrace.GetLogger(typeof(DomainManager)) static private
ISettings NUnit.Engine.Services.DomainManager._settingsService private
string NUnit.Engine.Services.DomainManager._shadowCopyPath = Path.Combine(NUnitConfiguration.NUnitBinDirectory, "ShadowCopyCache") private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/DomainManager.cs