IGLib: MainTest Class Reference
MainTest Class Reference
Static Public Member Functions
static bool doc_test_bool (bool val, bool test_val)
static bool doc_test_int (int val, int test_val)
static bool doc_test_real (double val, double test_val, double _threshold)
static bool doc_test_complex (alglib.complex val, alglib.complex test_val, double _threshold)
static bool doc_test_bool_vector (bool[] val, bool[] test_val)
static bool doc_test_bool_matrix (bool[,] val, bool[,] test_val)
static bool doc_test_int_vector (int[] val, int[] test_val)
static bool doc_test_int_matrix (int[,] val, int[,] test_val)
static bool doc_test_real_vector (double[] val, double[] test_val, double _threshold)
static bool doc_test_real_matrix (double[,] val, double[,] test_val, double _threshold)
static bool doc_test_complex_vector (alglib.complex[] val, alglib.complex[] test_val, double _threshold)
static bool doc_test_complex_matrix (alglib.complex[,] val, alglib.complex[,] test_val, double _threshold)
static void spoil_vector_by_adding_element< T > (ref T[] x)
static void spoil_vector_by_deleting_element< T > (ref T[] x)
static void spoil_matrix_by_adding_row< T > (ref T[,] x)
static void spoil_matrix_by_deleting_row< T > (ref T[,] x)
static void spoil_matrix_by_adding_col< T > (ref T[,] x)
static void spoil_matrix_by_deleting_col< T > (ref T[,] x)
static void spoil_vector_by_value< T > (ref T[] x, T val)
static void spoil_matrix_by_value< T > (ref T[,] x, T val)
static void function1_func (double[] x, ref double func, object obj)
static void function1_grad (double[] x, ref double func, double[] grad, object obj)
static void function1_hess (double[] x, ref double func, double[] grad, double[,] hess, object obj)
static void function1_fvec (double[] x, double[] fi, object obj)
static void function1_jac (double[] x, double[] fi, double[,] jac, object obj)
static void function2_func (double[] x, ref double func, object obj)
static void function2_grad (double[] x, ref double func, double[] grad, object obj)
static void function2_hess (double[] x, ref double func, double[] grad, double[,] hess, object obj)
static void function2_fvec (double[] x, double[] fi, object obj)
static void function2_jac (double[] x, double[] fi, double[,] jac, object obj)
static void bad_func (double[] x, ref double func, object obj)
static void bad_grad (double[] x, ref double func, double[] grad, object obj)
static void bad_hess (double[] x, ref double func, double[] grad, double[,] hess, object obj)
static void bad_fvec (double[] x, double[] fi, object obj)
static void bad_jac (double[] x, double[] fi, double[,] jac, object obj)
static void function_cx_1_func (double[] c, double[] x, ref double func, object obj)
static void function_cx_1_grad (double[] c, double[] x, ref double func, double[] grad, object obj)
static void function_cx_1_hess (double[] c, double[] x, ref double func, double[] grad, double[,] hess, object obj)
static void ode_function_1_diff (double[] y, double x, double[] dy, object obj)
static void int_function_1_func (double x, double xminusa, double bminusx, ref double y, object obj)
static void function_debt_func (double[] c, double[] x, ref double func, object obj)
static void s1_grad (double[] x, ref double func, double[] grad, object obj)
static int Main (string[] args)
static bool doc_test_bool (bool val, bool test_val)
static bool doc_test_int (int val, int test_val)
static bool doc_test_real (double val, double test_val, double _threshold)
static bool doc_test_complex (alglib.complex val, alglib.complex test_val, double _threshold)
static bool doc_test_bool_vector (bool[] val, bool[] test_val)
static bool doc_test_bool_matrix (bool[,] val, bool[,] test_val)
static bool doc_test_int_vector (int[] val, int[] test_val)
static bool doc_test_int_matrix (int[,] val, int[,] test_val)
static bool doc_test_real_vector (double[] val, double[] test_val, double _threshold)
static bool doc_test_real_matrix (double[,] val, double[,] test_val, double _threshold)
static bool doc_test_complex_vector (alglib.complex[] val, alglib.complex[] test_val, double _threshold)
static bool doc_test_complex_matrix (alglib.complex[,] val, alglib.complex[,] test_val, double _threshold)
static void spoil_vector_by_adding_element< T > (ref T[] x)
static void spoil_vector_by_deleting_element< T > (ref T[] x)
static void spoil_matrix_by_adding_row< T > (ref T[,] x)
static void spoil_matrix_by_deleting_row< T > (ref T[,] x)
static void spoil_matrix_by_adding_col< T > (ref T[,] x)
static void spoil_matrix_by_deleting_col< T > (ref T[,] x)
static void spoil_vector_by_value< T > (ref T[] x, T val)
static void spoil_matrix_by_value< T > (ref T[,] x, T val)
static void function1_func (double[] x, ref double func, object obj)
static void function1_grad (double[] x, ref double func, double[] grad, object obj)
static void function1_hess (double[] x, ref double func, double[] grad, double[,] hess, object obj)
static void function1_fvec (double[] x, double[] fi, object obj)
static void function1_jac (double[] x, double[] fi, double[,] jac, object obj)
static void function2_func (double[] x, ref double func, object obj)
static void function2_grad (double[] x, ref double func, double[] grad, object obj)
static void function2_hess (double[] x, ref double func, double[] grad, double[,] hess, object obj)
static void function2_fvec (double[] x, double[] fi, object obj)
static void function2_jac (double[] x, double[] fi, double[,] jac, object obj)
static void bad_func (double[] x, ref double func, object obj)
static void bad_grad (double[] x, ref double func, double[] grad, object obj)
static void bad_hess (double[] x, ref double func, double[] grad, double[,] hess, object obj)
static void bad_fvec (double[] x, double[] fi, object obj)
static void bad_jac (double[] x, double[] fi, double[,] jac, object obj)
static void function_cx_1_func (double[] c, double[] x, ref double func, object obj)
static void function_cx_1_grad (double[] c, double[] x, ref double func, double[] grad, object obj)
static void function_cx_1_hess (double[] c, double[] x, ref double func, double[] grad, double[,] hess, object obj)
static void ode_function_1_diff (double[] y, double x, double[] dy, object obj)
static void int_function_1_func (double x, double xminusa, double bminusx, ref double y, object obj)
static void function_debt_func (double[] c, double[] x, ref double func, object obj)
static void s1_grad (double[] x, ref double func, double[] grad, object obj)
static void Main (string[] args)
Member Function Documentation
static bool MainTest.doc_test_bool (bool val, bool test_val) inline static
static bool MainTest.doc_test_int (int val, int test_val) inline static
Referenced by Main().
static bool MainTest.doc_test_real (double val, double test_val, double _threshold) inline static
Referenced by Main().
static bool MainTest.doc_test_complex (alglib.complex val, alglib.complex test_val, double _threshold) inline static
References alglib.math.abscomplex().
static bool MainTest.doc_test_bool_vector (bool[] val, bool[] test_val) inline static
static bool MainTest.doc_test_bool_matrix (bool val[,], bool test_val[,]) inline static
static bool MainTest.doc_test_int_vector (int[] val, int[] test_val) inline static
Referenced by Main().
static bool MainTest.doc_test_int_matrix (int val[,], int test_val[,]) inline static
Referenced by Main().
static bool MainTest.doc_test_real_vector (double[] val, double[] test_val, double _threshold) inline static
Referenced by Main().
static bool MainTest.doc_test_real_matrix (double val[,], double test_val[,], double _threshold) inline static
Referenced by Main().
static bool MainTest.doc_test_complex_vector (alglib.complex[] val, alglib.complex[] test_val, double _threshold) inline static
References alglib.math.abscomplex().
static bool MainTest.doc_test_complex_matrix (alglib.complex val[,], alglib.complex test_val[,], double _threshold) inline static
References alglib.math.abscomplex().
Referenced by Main().
static void MainTest.spoil_vector_by_adding_element< T > (ref T[] x) inline static
Type Constraints
T : new()
static void MainTest.spoil_vector_by_deleting_element< T > (ref T[] x) inline static
Type Constraints
T : new()
static void MainTest.spoil_matrix_by_adding_row< T > (ref T x[,]) inline static
Type Constraints
T : new()
static void MainTest.spoil_matrix_by_deleting_row< T > (ref T x[,]) inline static
Type Constraints
T : new()
static void MainTest.spoil_matrix_by_adding_col< T > (ref T x[,]) inline static
Type Constraints
T : new()
static void MainTest.spoil_matrix_by_deleting_col< T > (ref T x[,]) inline static
Type Constraints
T : new()
static void MainTest.spoil_vector_by_value< T > (ref T[] x, T val) inline static
References alglib.math.randominteger().
static void MainTest.spoil_matrix_by_value< T > (ref T x[,], T val) inline static
References alglib.math.randominteger().
static void MainTest.function1_func (double[] x, ref double func, object obj) inline static
static void MainTest.function1_grad (double[] x, ref double func, double[] grad, object obj) inline static
static void MainTest.function1_hess (double[] x, ref double func, double[] grad, double hess[,], object obj) inline static
static void MainTest.function1_fvec (double[] x, double[] fi, object obj) inline static
static void MainTest.function1_jac (double[] x, double[] fi, double jac[,], object obj) inline static
static void MainTest.function2_func (double[] x, ref double func, object obj) inline static
static void MainTest.function2_grad (double[] x, ref double func, double[] grad, object obj) inline static
static void MainTest.function2_hess (double[] x, ref double func, double[] grad, double hess[,], object obj) inline static
static void MainTest.function2_fvec (double[] x, double[] fi, object obj) inline static
static void MainTest.function2_jac (double[] x, double[] fi, double jac[,], object obj) inline static
static void MainTest.bad_func (double[] x, ref double func, object obj) inline static
static void MainTest.bad_grad (double[] x, ref double func, double[] grad, object obj) inline static
static void MainTest.bad_hess (double[] x, ref double func, double[] grad, double hess[,], object obj) inline static
static void MainTest.bad_fvec (double[] x, double[] fi, object obj) inline static
static void MainTest.bad_jac (double[] x, double[] fi, double jac[,], object obj) inline static
static void MainTest.function_cx_1_func (double[] c, double[] x, ref double func, object obj) inline static
static void MainTest.function_cx_1_grad (double[] c, double[] x, ref double func, double[] grad, object obj) inline static
static void MainTest.function_cx_1_hess (double[] c, double[] x, ref double func, double[] grad, double hess[,], object obj) inline static
static void MainTest.ode_function_1_diff (double[] y, double x, double[] dy, object obj) inline static
static void MainTest.int_function_1_func (double x, double xminusa, double bminusx, ref double y, object obj) inline static
static void MainTest.function_debt_func (double[] c, double[] x, ref double func, object obj) inline static
static void MainTest.s1_grad (double[] x, ref double func, double[] grad, object obj) inline static
static int MainTest.Main (string[] args) inline static
References alglib.cmatrixinverse(), alglib.cov2(), alglib.covm(), alglib.covm2(), doc_test_complex_matrix(), doc_test_int(), doc_test_real(), doc_test_real_matrix(), doc_test_real_vector(), alglib.filterema(), alglib.filterlrma(), alglib.filtersma(), alglib.hpdmatrixinverse(), alglib.kdtreebuild(), alglib.kdtreequeryknn(), alglib.kdtreequeryresultsx(), alglib.kdtreeserialize(), alglib.kdtreeunserialize(), alglib.pearsoncorr2(), alglib.pearsoncorrm(), alglib.pearsoncorrm2(), alglib.rmatrixinverse(), alglib.sampleadev(), alglib.samplemedian(), alglib.samplemoments(), alglib.samplepercentile(), alglib.spdmatrixinverse(), alglib.spearmancorr2(), alglib.spearmancorrm(), and alglib.spearmancorrm2().
static bool MainTest.doc_test_bool (bool val, bool test_val) inline static
static bool MainTest.doc_test_int (int val, int test_val) inline static
static bool MainTest.doc_test_real (double val, double test_val, double _threshold) inline static
static bool MainTest.doc_test_complex (alglib.complex val, alglib.complex test_val, double _threshold) inline static
References alglib.math.abscomplex().
static bool MainTest.doc_test_bool_vector (bool[] val, bool[] test_val) inline static
static bool MainTest.doc_test_bool_matrix (bool val[,], bool test_val[,]) inline static
static bool MainTest.doc_test_int_vector (int[] val, int[] test_val) inline static
static bool MainTest.doc_test_int_matrix (int val[,], int test_val[,]) inline static
static bool MainTest.doc_test_real_vector (double[] val, double[] test_val, double _threshold) inline static
static bool MainTest.doc_test_real_matrix (double val[,], double test_val[,], double _threshold) inline static
static bool MainTest.doc_test_complex_vector (alglib.complex[] val, alglib.complex[] test_val, double _threshold) inline static
References alglib.math.abscomplex().
static bool MainTest.doc_test_complex_matrix (alglib.complex val[,], alglib.complex test_val[,], double _threshold) inline static
References alglib.math.abscomplex().
static void MainTest.spoil_vector_by_adding_element< T > (ref T[] x) inline static
Type Constraints
T : new()
static void MainTest.spoil_vector_by_deleting_element< T > (ref T[] x) inline static
Type Constraints
T : new()
static void MainTest.spoil_matrix_by_adding_row< T > (ref T x[,]) inline static
Type Constraints
T : new()
static void MainTest.spoil_matrix_by_deleting_row< T > (ref T x[,]) inline static
Type Constraints
T : new()
static void MainTest.spoil_matrix_by_adding_col< T > (ref T x[,]) inline static
Type Constraints
T : new()
static void MainTest.spoil_matrix_by_deleting_col< T > (ref T x[,]) inline static
Type Constraints
T : new()
static void MainTest.spoil_vector_by_value< T > (ref T[] x, T val) inline static
References alglib.math.randominteger().
static void MainTest.spoil_matrix_by_value< T > (ref T x[,], T val) inline static
References alglib.math.randominteger().
static void MainTest.function1_func (double[] x, ref double func, object obj) inline static
static void MainTest.function1_grad (double[] x, ref double func, double[] grad, object obj) inline static
static void MainTest.function1_hess (double[] x, ref double func, double[] grad, double hess[,], object obj) inline static
static void MainTest.function1_fvec (double[] x, double[] fi, object obj) inline static
static void MainTest.function1_jac (double[] x, double[] fi, double jac[,], object obj) inline static
static void MainTest.function2_func (double[] x, ref double func, object obj) inline static
static void MainTest.function2_grad (double[] x, ref double func, double[] grad, object obj) inline static
static void MainTest.function2_hess (double[] x, ref double func, double[] grad, double hess[,], object obj) inline static
static void MainTest.function2_fvec (double[] x, double[] fi, object obj) inline static
static void MainTest.function2_jac (double[] x, double[] fi, double jac[,], object obj) inline static
static void MainTest.bad_func (double[] x, ref double func, object obj) inline static
static void MainTest.bad_grad (double[] x, ref double func, double[] grad, object obj) inline static
static void MainTest.bad_hess (double[] x, ref double func, double[] grad, double hess[,], object obj) inline static
static void MainTest.bad_fvec (double[] x, double[] fi, object obj) inline static
static void MainTest.bad_jac (double[] x, double[] fi, double jac[,], object obj) inline static
static void MainTest.function_cx_1_func (double[] c, double[] x, ref double func, object obj) inline static
static void MainTest.function_cx_1_grad (double[] c, double[] x, ref double func, double[] grad, object obj) inline static
static void MainTest.function_cx_1_hess (double[] c, double[] x, ref double func, double[] grad, double hess[,], object obj) inline static
static void MainTest.ode_function_1_diff (double[] y, double x, double[] dy, object obj) inline static
static void MainTest.int_function_1_func (double x, double xminusa, double bminusx, ref double y, object obj) inline static
static void MainTest.function_debt_func (double[] c, double[] x, ref double func, object obj) inline static
static void MainTest.s1_grad (double[] x, ref double func, double[] grad, object obj) inline static
static void MainTest.Main (string[] args) inline static
References alglib.alloc_counter_activate(), alglib.clusterizercreate(), alglib.clusterizerrunahc(), alglib.clusterizersetpoints(), alglib.cov2(), alglib.covm(), alglib.covm2(), doc_test_int(), doc_test_int_matrix(), doc_test_int_vector(), doc_test_real(), doc_test_real_matrix(), alglib.kdtreebuild(), alglib.kdtreequeryknn(), alglib.kdtreequeryresultsx(), alglib.kdtreeserialize(), alglib.kdtreeunserialize(), alglib.pearsoncorr2(), alglib.pearsoncorrm(), alglib.pearsoncorrm2(), alglib.rmatrixgemm(), alglib.rmatrixsyrk(), alglib.sampleadev(), alglib.samplemedian(), alglib.samplemoments(), alglib.samplepercentile(), alglib.setnworkers(), alglib.smp_rmatrixgemm(), alglib.smp_rmatrixsyrk(), alglib.spearmancorr2(), alglib.spearmancorrm(), and alglib.spearmancorrm2().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_i.cs