IGLib: NUnit.Framework.Compatibility.AttributeHelper Class Reference
NUnit.Framework.Compatibility.AttributeHelper Class Reference
Provides a platform-independent methods for getting attributes for use by AttributeConstraint and AttributeExistsConstraint.
Static Public Member Functions
static Attribute[] GetCustomAttributes (object actual, Type attributeType, bool inherit)
Gets the custom attributes from the given object.
Detailed Description
Provides a platform-independent methods for getting attributes for use by AttributeConstraint and AttributeExistsConstraint.
Member Function Documentation
static Attribute [] NUnit.Framework.Compatibility.AttributeHelper.GetCustomAttributes (object actual, Type attributeType, bool inherit) inline static
Gets the custom attributes from the given object.
Portable libraries do not have an ICustomAttributeProvider, so we need to cast to each of it's direct subtypes and try to get attributes off those instead.
Parameters
actual The actual.
attributeType Type of the attribute.
inherit if set to true [inherit].
Returns
A list of the given attribute on the given object.
Referenced by NUnit.Framework.Constraints.AttributeConstraint.ApplyTo< TActual >(), NUnit.Framework.Constraints.AttributeExistsConstraint.ApplyTo< TActual >(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnAssemblies(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnClasses(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnDerivedClasses(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnFields(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnMethods(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnParameters(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnProperties(), and NUnit.Framework.Tests.Compatibility.AttributeHelperTests.DoesNotGetAttributesOnDerivedClassesWhenInheritedIsFalse().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Compatibility/AttributeHelper.cs