IGLib: IG.Neural.Applications.DemoNeuralOld Class Reference
IG.Neural.Applications.DemoNeuralOld Class Reference
Public Member Functions
DemoNeuralOld ()
void PreparePlotter2D ()
void DecorHandler ()
void DefaultGraph2D ()
void RemoveDefaultActors ()
void TrainingPointsGraph ()
void RemoveTrainingPointsActors ()
void ApproximationGraph ()
void RemoveApprovimationActors ()
void ApproximationContourGraph ()
void RemoveApprovimationContureActors ()
void DefaultContourGraph ()
void RemoveDefaultContureActors ()
void SclarBar2D (double minRange, double maxRange, ColorScale Color)
void Bounds2D ()
Static Public Member Functions
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
Public Attributes
System.ComponentModel.BackgroundWorker backgroundWorker1D
System.ComponentModel.BackgroundWorker backgroundWorker2D
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void LoadForm (object sender, EventArgs e)
void PredictFromApproximator (ref IVector[] exactInputParameters1D, ref IVector[] approximatedOutputValues1D)
Calculate approximation response on verification points stored in approximator.
IRealFunction createFunction1D ()
Creates a function loader and uses it for dynamic definition of functions.
void EnableControls1D (bool enabled)
void InitializeApproximator1D ()
Clean the approximator.
void GraphDimensions1D (SampledDataSet data1D)
Prepare graph for 1 dimension.
void PrepareTrainingPoints1D (bool randomPoints1D)
Preparing training points.
void WriteDefaultFunction1D ()
Write default Function for 1 dimension.
void WriteTrainingPoints1D (SampledDataSet trainingData1D)
Write training points for 1 dimension.
void WriteApproxGraf1D ()
Write approximation line 1 dimension.
void WriteErrors1D ()
Write training and verification errors in text box.
void ClearDefaultGraph ()
Clear Graph with default function for 1 dimension.
void ClearApproximationGraph ()
Clear Graph with approximative function for 1 dimension.
void ClearTrainingGraph ()
Clear Graph with training points for 1 dimension.
void ClearErrorGraph1D ()
Clear Graph with error convergence for 1 dimension.
void btnReset1D_Click (object sender, EventArgs e)
Reset button.
void btStart1D_Click (object sender, EventArgs e)
Start training button.
void btStop1D_Click (object sender, EventArgs e)
void TrainNetworkThread1D ()
void btnGenerateOptData1D_Click (object sender, EventArgs e)
Generate training data button.
void rbMaxTrainError_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void cbSelfMade1D_CheckedChanged (object sender, EventArgs e)
Enable posibility to self made the equation.
void cbEquation1D_SelectedIndexChanged (object sender, EventArgs e)
Select equation from the list.
void tbSelfMadeEquation1D_TextChanged (object sender, EventArgs e)
void numSamples1D_ValueChanged (object sender, EventArgs e)
Number of training samples generated.
void numLowXLimit1D_ValueChanged (object sender, EventArgs e)
Lower limit for x-axes on the graph.
void numHighXLimit1D_ValueChanged (object sender, EventArgs e)
Higher limit for x-axes on the graph.
void numMaxEpoch1D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle1D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS1D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate1D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum1D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron1D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL21D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety1D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety1D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker1D_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker1D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void InitializeApproximator2D ()
Clean and initialize the approximator.
void InitializeTrainingData2D ()
Clean and initialize the training data set.
void InitializeVerificationData2D ()
Clean and initialize the verification data set.
void InitializeDefaultData2D ()
Clean and initialize the default data set.
void WriteErrors2D ()
Write training and verification errors in text box.
void ClearErrorGraph2D ()
Clear Graph with error convergence for 2 dimension.
void btReset2D_Click (object sender, EventArgs e)
Reset button.
void btStart2D_Click (object sender, EventArgs e)
Start training button.
void btStop2D_Click (object sender, EventArgs e)
Stop training button.
void TrainNetworkThread2D ()
void btnGenerateOptData2D_Click (object sender, EventArgs e)
Generate training data button.
void rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void cbSelfMade2D_CheckedChanged (object sender, EventArgs e)
Enable posibility to self made the equation.
void cbTrainingPoints2D_CheckedChanged (object sender, EventArgs e)
Enable training points on graph.
void cbDefaultSurface2D_CheckedChanged (object sender, EventArgs e)
Enable surface for default function on graph.
void cbDefaultGreed2D_CheckedChanged (object sender, EventArgs e)
Enable greed for default function on graph.
void cbApproximationSurface2D_CheckedChanged (object sender, EventArgs e)
Enable surface for approximation function on graph.
void cbApproximationGreed2D_CheckedChanged (object sender, EventArgs e)
Enable greed for approximation function on graph.
void cbContourDefault2D_CheckedChanged (object sender, EventArgs e)
Enable conture for default function on graph.
void cbContourApproximation2D_CheckedChanged (object sender, EventArgs e)
Enable conture for approximation function on graph.
void trackbDefaultGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of default function.
void trackbApproxGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of approximation function.
void trackbContourGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of contures.
void cbEquation2D_SelectedIndexChanged (object sender, EventArgs e)
Select equation from the list.
void tbSelfMadeEquation2D_TextChanged (object sender, EventArgs e)
void numSamplesX2D_ValueChanged (object sender, EventArgs e)
Number of training samples on X axe.
void numSamplesY2D_ValueChanged (object sender, EventArgs e)
Number of training samples on Y axe.
void numLowXLimit2D_ValueChanged (object sender, EventArgs e)
Lower limit for x-axes on the graph.
void numHighXLimit2D_ValueChanged (object sender, EventArgs e)
Higher limit for x-axes on the graph.
void numHighYLimit2D_ValueChanged (object sender, EventArgs e)
Higher limit for y-axes on the graph.
void numLowYLimit2D_ValueChanged (object sender, EventArgs e)
Lower limit for y-axes on the graph.
void numMaxEpoch2D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle2D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS2D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate2D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum2D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron2D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety2D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety2D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
SampledDataSet trainingData1D = null
SampledDataSet verificationData1D = null
SampledDataSet defaultFunctionData1D = null
INeuralApproximator approximator1D = new NeuralApproximatorAforge()
NeuralNetworks network1D
int hiddenNeuronL11D = 5
int hiddenNeuronL21D = 0
int maxEpoch1D = 5000
int epochInBundle1D = 500
double rmsError1D = 0.001
double learningRate1D = 0.3
double momentum1D = 0.6
int samples1D = 6
double lowHorizontalLimit1D = -5.0
double highHorizontalLimit1D = 5.0
double lowVerificationHorizontalLimit1D = -5.0
double highVerificationHorizontalLimit1D = 5.0
double inputSafetyFactor1D = 1.3
double outputSafetyFactor1D = 1.3
int thread1D = 0
string equation1D = "x*x"
bool maxTrainErrorEnabled1D = true
bool rmsTrainErrorEnabled1D = false
bool maxVerErrorEnabled1D = false
bool rmsVerErrorEnabled1D = false
GraphPane pane1D
GraphPane pane1DError
LineItem trainingPoints1D
LineItem approximatedLine1D
LineItem defaultFunction1D
LineItem errorConvergenceFunction1D
SampledDataSet trainingData2D = null
SampledDataSet verificationData2D = null
SampledDataSet defaultFunctionData2D = null
INeuralApproximator approximator2D = new NeuralApproximatorAforge()
NeuralNetworks network2D
int hiddenNeuronL12D = 5
int hiddenNeuronL22D = 0
int maxEpoch2D = 5000
int epochInBundle2D = 500
double rmsError2D = 0.001
double learningRate2D = 0.3
double momentum2D = 0.6
int samplesX2D = 5
int samplesY2D = 5
double lowHorizontalLimit2D = -5.0
double highHorizontalLimit2D = 5.0
double lowVerticalLimit2D = 5.0
double highVerticalLimit2D = 5.0
double lowVerificationHorizontalLimit2D = -5.0
double highVerificationHorizontalLimit2D = 5.0
double inputSafetyFactor2D = 1.3
double outputSafetyFactor2D = 1.3
int thread12D = 0
string equation2D = "x*x + y*y"
string[] variableNames2D = { "x", "y" }
bool maxTrainErrorEnabled2D = true
bool rmsTrainErrorEnabled2D = false
bool maxVerErrorEnabled2D = false
bool rmsVerErrorEnabled2D = false
bool defaultSurfaceonGraph = false
bool defaultGreedonGraph = true
bool trainingPointsonGraph = true
bool approximationSurfaceonGraph = true
bool approximationGreedonGraph = false
bool contureDefaultonGraph = false
bool contureApproximationonGraph = false
bool stopTraining2D = false
bool stopTraining1D = false
double opacityDefaultGraph2D = 0.5
double opacityApproxGraph2D = 0.7
double opacityContourGraph2D = 1.0
int numAllXPoints2D = 100
int numAllYPoints2D = 100
GraphPane pane2DError
LineItem errorConvergenceFunction2D
VtkPlotter plotter2D
BoundingBox2d paramBounds2D
Func2dFromScalarFunction iFunctionDefault2D
VtkSurfacePlot plotDefault2D
VtkSurfacePlot plotTrainingPoints2D
VtkSurfacePlot plotApproximation2D
Func2dFromScalarFunction iFunctionTraining2D
Func2dFromApproximator iFunctionApproximator2D
ExampleValueFunctionDiff3D iFunctionDifference2D
VtkContourPlot plotApproximationConture2D
VtkContourPlot plotDefaultConture2D
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.TabControl tabControl
System.Windows.Forms.TabPage tabPage1D
System.Windows.Forms.TabPage tabPage2D
ZedGraph.ZedGraphControl functionGraph
System.Windows.Forms.Button btLoad1D
System.Windows.Forms.CheckBox cbSelfMade1D
System.Windows.Forms.TextBox tbSelfMadeEquation1D
System.Windows.Forms.ComboBox cbEquation1D
System.Windows.Forms.Label label19
System.Windows.Forms.NumericUpDown numHighXLimit1D
System.Windows.Forms.NumericUpDown numLowXLimit1D
System.Windows.Forms.NumericUpDown numSamples1D
System.Windows.Forms.Label label9
System.Windows.Forms.CheckBox cbRandomData1D
System.Windows.Forms.Button btnGenerateOptData1D
System.Windows.Forms.NumericUpDown numHiddenNeuron1D
System.Windows.Forms.Label label11
System.Windows.Forms.NumericUpDown numMomentum1D
System.Windows.Forms.NumericUpDown numLearningRate1D
System.Windows.Forms.NumericUpDown numRMS1D
System.Windows.Forms.NumericUpDown numEpochBundle1D
System.Windows.Forms.NumericUpDown numMaxEpoch1D
System.Windows.Forms.Label label8
System.Windows.Forms.Label label7
System.Windows.Forms.Label label6
System.Windows.Forms.Label label5
System.Windows.Forms.Label label4
System.Windows.Forms.NumericUpDown numOutputSafety1D
System.Windows.Forms.Label label16
System.Windows.Forms.NumericUpDown numInputSafety1D
System.Windows.Forms.Label label15
System.Windows.Forms.Button btnReset1D
System.Windows.Forms.Button btStart1D
ZedGraph.ZedGraphControl errorConvergence1D
System.Windows.Forms.TextBox tbRmsVerError1D
System.Windows.Forms.TextBox tbMaxVerError1D
System.Windows.Forms.Label label2
System.Windows.Forms.Label label1
System.Windows.Forms.TextBox tbRmsTrainError1D
System.Windows.Forms.Label label12
System.Windows.Forms.Label label13
System.Windows.Forms.TextBox tbMaxTrainError1D
System.Windows.Forms.NumericUpDown numOutputSafety2D
System.Windows.Forms.Label label17
System.Windows.Forms.NumericUpDown numInputSafety2D
System.Windows.Forms.Label label18
System.Windows.Forms.Label label20
System.Windows.Forms.NumericUpDown numMomentum2D
System.Windows.Forms.NumericUpDown numLearningRate2D
System.Windows.Forms.NumericUpDown numRMS2D
System.Windows.Forms.NumericUpDown numEpochBundle2D
System.Windows.Forms.NumericUpDown numMaxEpoch2D
System.Windows.Forms.Label label21
System.Windows.Forms.Label label22
System.Windows.Forms.Label label23
System.Windows.Forms.Label label24
System.Windows.Forms.Label label25
System.Windows.Forms.CheckBox cbRandomData2D
System.Windows.Forms.Button btnGenerateOptData2D
System.Windows.Forms.NumericUpDown numSamplesX2D
System.Windows.Forms.Label label14
System.Windows.Forms.ComboBox cbEquation2D
System.Windows.Forms.TextBox tbSelfMadeEquation2D
System.Windows.Forms.Label label3
System.Windows.Forms.CheckBox cbSelfMade2D
System.Windows.Forms.Button btLoad2D
System.Windows.Forms.TabPage tabPage1
System.Windows.Forms.Button btReset2D
System.Windows.Forms.Button btStart2D
System.Windows.Forms.Button btLoadANN1D
System.Windows.Forms.Button btSaveANN1D
System.Windows.Forms.Button btLoadANN2D
System.Windows.Forms.Button btSaveANN2D
System.Windows.Forms.TextBox tbEquationError1D
System.Windows.Forms.NumericUpDown numHiddenNeuronL21D
System.Windows.Forms.RadioButton rbRmsTrainError
System.Windows.Forms.RadioButton rbMaxTrainError
System.Windows.Forms.RadioButton rbRmsVerError
System.Windows.Forms.RadioButton rbMaxVerError
System.Windows.Forms.NumericUpDown numHiddenNeuronL22D
System.Windows.Forms.NumericUpDown numHiddenNeuron2D
System.Windows.Forms.TextBox tbEquationError2D
System.Windows.Forms.RadioButton rbRmsTrainError2D
System.Windows.Forms.RadioButton rbMaxTrainError2D
System.Windows.Forms.RadioButton rbRmsVerError2D
System.Windows.Forms.RadioButton rbMaxVerError2D
System.Windows.Forms.TextBox tbRmsTrainError2D
System.Windows.Forms.Label label26
System.Windows.Forms.Label label27
System.Windows.Forms.TextBox tbMaxTrainError2D
System.Windows.Forms.TextBox tbRmsVerError2D
System.Windows.Forms.TextBox tbMaxVerError2D
System.Windows.Forms.Label label28
System.Windows.Forms.Label label29
ZedGraph.ZedGraphControl errorConvergence2D
System.Windows.Forms.NumericUpDown numHighXLimit2D
System.Windows.Forms.Label label30
System.Windows.Forms.NumericUpDown numHighYLimit2D
System.Windows.Forms.NumericUpDown numLowYLimit2D
System.Windows.Forms.NumericUpDown numLowXLimit2D
System.Windows.Forms.Label label31
System.Windows.Forms.Label label32
System.Windows.Forms.Label label33
System.Windows.Forms.GroupBox groupBox5
System.Windows.Forms.GroupBox groupBox6
System.Windows.Forms.GroupBox groupBox7
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.CheckBox cbDefaultGreed2D
System.Windows.Forms.TrackBar trackbDefaultGraph2D
System.Windows.Forms.CheckBox cbDefaultSurface2D
System.Windows.Forms.Label label35
System.Windows.Forms.CheckBox cbApproximationGreed2D
System.Windows.Forms.CheckBox cbApproximationSurface2D
System.Windows.Forms.Label label34
System.Windows.Forms.TrackBar trackbApproxGraph2D
System.Windows.Forms.CheckBox cbTrainingPoints2D
System.Windows.Forms.Label label36
System.Windows.Forms.GroupBox groupBox9
System.Windows.Forms.TrackBar trackbContourGraph2D
System.Windows.Forms.Label label37
System.Windows.Forms.CheckBox cbContourDefault2D
System.Windows.Forms.CheckBox cbContourApproximation2D
System.Windows.Forms.GroupBox groupBox8
System.Windows.Forms.NumericUpDown numSamplesY2D
System.Windows.Forms.Label label10
System.Windows.Forms.Button btStop1D
System.Windows.Forms.Button btStop2D
Static Private Attributes
static readonly Color enabledColor1D = Color.Tomato
static readonly Color disabledColor1D = Color.Goldenrod
Constructor & Destructor Documentation
IG.Neural.Applications.DemoNeuralOld.DemoNeuralOld () inline
Member Function Documentation
void IG.Neural.Applications.DemoNeuralOld.LoadForm (object sender, EventArgs e) inline private
void IG.Neural.Applications.DemoNeuralOld.PredictFromApproximator (ref IVector[] exactInputParameters1D, ref IVector[] approximatedOutputValues1D) inline private
Calculate approximation response on verification points stored in approximator.
Parameters
exactInputParameters1D Exact input parameters from verification points.
approximatedOutputValues1D Approximated output values from verification points.
References IG.Num.Vector.Length.
IRealFunction IG.Neural.Applications.DemoNeuralOld.createFunction1D () inline private
Creates a function loader and uses it for dynamic definition of functions.
References IG.Lib.RealFunctionLoader.CreateRealFunction(), IG.Lib.RealFunctionLoader.IndependentVariableName, IG.Lib.RealFunctionLoader.InvalidateDefinitions(), and IG.Lib.RealFunctionLoader.ValueDefinitionString.
static ColorScale IG.Neural.Applications.DemoNeuralOld.CreateGreenRedYellow (double minValue, double maxValue) inline static
void IG.Neural.Applications.DemoNeuralOld.EnableControls1D (bool enabled) inline private
void IG.Neural.Applications.DemoNeuralOld.InitializeApproximator1D () inline private
Clean the approximator.
void IG.Neural.Applications.DemoNeuralOld.GraphDimensions1D (SampledDataSet data1D) inline private
Prepare graph for 1 dimension.
Parameters
data Data set.
References IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), and IG.Num.SampledDataSet.Length.
void IG.Neural.Applications.DemoNeuralOld.PrepareTrainingPoints1D (bool randomPoints1D) inline private
Preparing training points.
References IG.Num.SampledDataSet.AddElement(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), and IG.Num.SampledDataSet.Length.
void IG.Neural.Applications.DemoNeuralOld.WriteDefaultFunction1D () inline private
Write default Function for 1 dimension.
References IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), and IG.Num.SampledDataSet.Length.
void IG.Neural.Applications.DemoNeuralOld.WriteTrainingPoints1D (SampledDataSet trainingData1D) inline private
Write training points for 1 dimension.
Parameters
trainingData1D Training data.
References IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.InputLength, IG.Num.SampledDataSet.Length, and IG.Num.SampledDataSet.OutputLength.
void IG.Neural.Applications.DemoNeuralOld.WriteApproxGraf1D () inline private
Write approximation line 1 dimension.
void IG.Neural.Applications.DemoNeuralOld.WriteErrors1D () inline private
Write training and verification errors in text box.
References IG.Num.INeuralApproximator.ConvergenceErrorsTrainingMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsTrainingRmsList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationRmsList, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), and IG.Num.INeuralApproximator.GetErrorsVerificationRms().
void IG.Neural.Applications.DemoNeuralOld.ClearDefaultGraph () inline private
Clear Graph with default function for 1 dimension.
void IG.Neural.Applications.DemoNeuralOld.ClearApproximationGraph () inline private
Clear Graph with approximative function for 1 dimension.
void IG.Neural.Applications.DemoNeuralOld.ClearTrainingGraph () inline private
Clear Graph with training points for 1 dimension.
void IG.Neural.Applications.DemoNeuralOld.ClearErrorGraph1D () inline private
Clear Graph with error convergence for 1 dimension.
void IG.Neural.Applications.DemoNeuralOld.btnReset1D_Click (object sender, EventArgs e) inline private
Reset button.
void IG.Neural.Applications.DemoNeuralOld.btStart1D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Neural.NeuralNetworks.EpochBundle, IG.Neural.NeuralNetworks.HiddenNeuron1L, IG.Neural.NeuralNetworks.HiddenNeuron2L, IG.Neural.NeuralNetworks.InputSafetyFactor, IG.Neural.NeuralNetworks.LearningRate, IG.Neural.NeuralNetworks.MaxEpoch, IG.Neural.NeuralNetworks.Momentum, IG.Neural.NeuralNetworks.OutputSafetyFactor, and IG.Neural.NeuralNetworks.RMS.
void IG.Neural.Applications.DemoNeuralOld.btStop1D_Click (object sender, EventArgs e) inline private
References IG.Neural.NeuralNetworks.BreakTraining.
void IG.Neural.Applications.DemoNeuralOld.TrainNetworkThread1D () inline private
void IG.Neural.Applications.DemoNeuralOld.btnGenerateOptData1D_Click (object sender, EventArgs e) inline private
Generate training data button.
References IG.Neural.TestFunctions.GenerateFunctionTrainingSamples().
void IG.Neural.Applications.DemoNeuralOld.rbMaxTrainError_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained.
void IG.Neural.Applications.DemoNeuralOld.rbRmsTrainError_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained.
void IG.Neural.Applications.DemoNeuralOld.rbMaxVerError_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained.
void IG.Neural.Applications.DemoNeuralOld.rbRmsVerError_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained.
void IG.Neural.Applications.DemoNeuralOld.cbSelfMade1D_CheckedChanged (object sender, EventArgs e) inline private
Enable posibility to self made the equation.
void IG.Neural.Applications.DemoNeuralOld.cbEquation1D_SelectedIndexChanged (object sender, EventArgs e) inline private
Select equation from the list.
void IG.Neural.Applications.DemoNeuralOld.tbSelfMadeEquation1D_TextChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.DemoNeuralOld.numSamples1D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples generated.
void IG.Neural.Applications.DemoNeuralOld.numLowXLimit1D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for x-axes on the graph.
void IG.Neural.Applications.DemoNeuralOld.numHighXLimit1D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for x-axes on the graph.
void IG.Neural.Applications.DemoNeuralOld.numMaxEpoch1D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
void IG.Neural.Applications.DemoNeuralOld.numEpochBundle1D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
void IG.Neural.Applications.DemoNeuralOld.numRMS1D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
void IG.Neural.Applications.DemoNeuralOld.numLearningRate1D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
void IG.Neural.Applications.DemoNeuralOld.numMomentum1D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
void IG.Neural.Applications.DemoNeuralOld.numHiddenNeuron1D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
void IG.Neural.Applications.DemoNeuralOld.numHiddenNeuronL21D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
void IG.Neural.Applications.DemoNeuralOld.numInputSafety1D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
void IG.Neural.Applications.DemoNeuralOld.numOutputSafety1D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
void IG.Neural.Applications.DemoNeuralOld.backgroundWorker1D_DoWork (object sender, DoWorkEventArgs e) inline private
References IG.Neural.NeuralNetworks.BreakTraining, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), and IG.Neural.NeuralNetworks.TrainNetwork().
void IG.Neural.Applications.DemoNeuralOld.backgroundWorker1D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
void IG.Neural.Applications.DemoNeuralOld.InitializeApproximator2D () inline private
Clean and initialize the approximator.
void IG.Neural.Applications.DemoNeuralOld.InitializeTrainingData2D () inline private
Clean and initialize the training data set.
void IG.Neural.Applications.DemoNeuralOld.InitializeVerificationData2D () inline private
Clean and initialize the verification data set.
void IG.Neural.Applications.DemoNeuralOld.InitializeDefaultData2D () inline private
Clean and initialize the default data set.
void IG.Neural.Applications.DemoNeuralOld.WriteErrors2D () inline private
Write training and verification errors in text box.
References IG.Num.INeuralApproximator.ConvergenceErrorsTrainingMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsTrainingRmsList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationRmsList, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), and IG.Num.INeuralApproximator.GetErrorsVerificationRms().
void IG.Neural.Applications.DemoNeuralOld.ClearErrorGraph2D () inline private
Clear Graph with error convergence for 2 dimension.
void IG.Neural.Applications.DemoNeuralOld.PreparePlotter2D () inline
void IG.Neural.Applications.DemoNeuralOld.DecorHandler () inline
References IG.Gr3d.VtkPlotter.BackGround, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
void IG.Neural.Applications.DemoNeuralOld.DefaultGraph2D () inline
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
void IG.Neural.Applications.DemoNeuralOld.RemoveDefaultActors () inline
References IG.Gr3d.VtkPlotBase.RemoveActors().
void IG.Neural.Applications.DemoNeuralOld.TrainingPointsGraph () inline
References IG.Num.SampledDataSet.AddElement(), IG.Num.SampledDataSet.Clear(), IG.Gr3d.VtkSurfacePlot.Create(), IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Num.Field< TElement >.GetValue(), IG.Num.Field< TElement >.Length, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Gr3d.VtkSurfacePlotBase.PointColor, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.RandomPoints, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
void IG.Neural.Applications.DemoNeuralOld.RemoveTrainingPointsActors () inline
References IG.Gr3d.VtkPlotBase.RemoveActors().
void IG.Neural.Applications.DemoNeuralOld.ApproximationGraph () inline
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LineColorScale, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, and IG.Gr3d.VtkSurfacePlot.ValueFunctionOfCoordinates.
void IG.Neural.Applications.DemoNeuralOld.RemoveApprovimationActors () inline
References IG.Gr3d.VtkPlotBase.RemoveActors().
void IG.Neural.Applications.DemoNeuralOld.ApproximationContourGraph () inline
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
void IG.Neural.Applications.DemoNeuralOld.RemoveApprovimationContureActors () inline
References IG.Gr3d.VtkPlotBase.RemoveActors().
void IG.Neural.Applications.DemoNeuralOld.DefaultContourGraph () inline
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
void IG.Neural.Applications.DemoNeuralOld.RemoveDefaultContureActors () inline
References IG.Gr3d.VtkPlotBase.RemoveActors().
void IG.Neural.Applications.DemoNeuralOld.SclarBar2D (double minRange, double maxRange, ColorScale Color) inline
References IG.Gr3d.VtkPlotter.DecorationHandler, IG.Gr3d.VtkDecorationHandler.LookUpTableColorScale, IG.Gr3d.VtkDecorationHandler.LookUpTableMaxRange, IG.Gr3d.VtkDecorationHandler.LookUpTableMinRange, IG.Gr3d.VtkDecorationHandler.ScalarBarNumberOfLabels, IG.Gr3d.VtkDecorationHandler.ScalarBarTitle, and IG.Gr3d.VtkDecorationHandler.ShowScalarBar.
void IG.Neural.Applications.DemoNeuralOld.Bounds2D () inline
void IG.Neural.Applications.DemoNeuralOld.btReset2D_Click (object sender, EventArgs e) inline private
Reset button.
void IG.Neural.Applications.DemoNeuralOld.btStart2D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.NeuralNetworks.EpochBundle, IG.Num.Field< TElement >.GetValue(), IG.Neural.NeuralNetworks.HiddenNeuron1L, IG.Neural.NeuralNetworks.HiddenNeuron2L, IG.Num.SampledDataSet.InputLength, IG.Neural.NeuralNetworks.InputSafetyFactor, IG.Neural.NeuralNetworks.LearningRate, IG.Neural.NeuralNetworks.MaxEpoch, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Neural.NeuralNetworks.Momentum, IG.Num.SampledDataSet.OutputLength, IG.Neural.NeuralNetworks.OutputSafetyFactor, IG.Gr3d.VtkPlotter.RemovePlotObject(), and IG.Neural.NeuralNetworks.RMS.
void IG.Neural.Applications.DemoNeuralOld.btStop2D_Click (object sender, EventArgs e) inline private
Stop training button.
References IG.Neural.NeuralNetworks.BreakTraining.
void IG.Neural.Applications.DemoNeuralOld.TrainNetworkThread2D () inline private
void IG.Neural.Applications.DemoNeuralOld.btnGenerateOptData2D_Click (object sender, EventArgs e) inline private
Generate training data button.
References IG.Gr3d.VtkPlotter.ResetCamera(), and IG.Gr3d.VtkPlotter.ShowPlot().
void IG.Neural.Applications.DemoNeuralOld.rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained.
void IG.Neural.Applications.DemoNeuralOld.rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained.
void IG.Neural.Applications.DemoNeuralOld.rbMaxVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained.
void IG.Neural.Applications.DemoNeuralOld.rbRmsVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained.
void IG.Neural.Applications.DemoNeuralOld.cbSelfMade2D_CheckedChanged (object sender, EventArgs e) inline private
Enable posibility to self made the equation.
void IG.Neural.Applications.DemoNeuralOld.cbTrainingPoints2D_CheckedChanged (object sender, EventArgs e) inline private
Enable training points on graph.
void IG.Neural.Applications.DemoNeuralOld.cbDefaultSurface2D_CheckedChanged (object sender, EventArgs e) inline private
Enable surface for default function on graph.
void IG.Neural.Applications.DemoNeuralOld.cbDefaultGreed2D_CheckedChanged (object sender, EventArgs e) inline private
Enable greed for default function on graph.
void IG.Neural.Applications.DemoNeuralOld.cbApproximationSurface2D_CheckedChanged (object sender, EventArgs e) inline private
Enable surface for approximation function on graph.
void IG.Neural.Applications.DemoNeuralOld.cbApproximationGreed2D_CheckedChanged (object sender, EventArgs e) inline private
Enable greed for approximation function on graph.
void IG.Neural.Applications.DemoNeuralOld.cbContourDefault2D_CheckedChanged (object sender, EventArgs e) inline private
Enable conture for default function on graph.
void IG.Neural.Applications.DemoNeuralOld.cbContourApproximation2D_CheckedChanged (object sender, EventArgs e) inline private
Enable conture for approximation function on graph.
void IG.Neural.Applications.DemoNeuralOld.trackbDefaultGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of default function.
void IG.Neural.Applications.DemoNeuralOld.trackbApproxGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of approximation function.
void IG.Neural.Applications.DemoNeuralOld.trackbContourGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of contures.
void IG.Neural.Applications.DemoNeuralOld.cbEquation2D_SelectedIndexChanged (object sender, EventArgs e) inline private
Select equation from the list.
void IG.Neural.Applications.DemoNeuralOld.tbSelfMadeEquation2D_TextChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.DemoNeuralOld.numSamplesX2D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples on X axe.
void IG.Neural.Applications.DemoNeuralOld.numSamplesY2D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples on Y axe.
void IG.Neural.Applications.DemoNeuralOld.numLowXLimit2D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for x-axes on the graph.
void IG.Neural.Applications.DemoNeuralOld.numHighXLimit2D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for x-axes on the graph.
void IG.Neural.Applications.DemoNeuralOld.numHighYLimit2D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for y-axes on the graph.
void IG.Neural.Applications.DemoNeuralOld.numLowYLimit2D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for y-axes on the graph.
void IG.Neural.Applications.DemoNeuralOld.numMaxEpoch2D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
void IG.Neural.Applications.DemoNeuralOld.numEpochBundle2D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
void IG.Neural.Applications.DemoNeuralOld.numRMS2D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
void IG.Neural.Applications.DemoNeuralOld.numLearningRate2D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
void IG.Neural.Applications.DemoNeuralOld.numMomentum2D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
void IG.Neural.Applications.DemoNeuralOld.numHiddenNeuron2D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
void IG.Neural.Applications.DemoNeuralOld.numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
void IG.Neural.Applications.DemoNeuralOld.numInputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
void IG.Neural.Applications.DemoNeuralOld.numOutputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
void IG.Neural.Applications.DemoNeuralOld.backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e) inline private
References IG.Neural.NeuralNetworks.BreakTraining, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), and IG.Neural.NeuralNetworks.TrainNetwork().
void IG.Neural.Applications.DemoNeuralOld.backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References IG.Gr3d.VtkPlotter.ResetCamera(), and IG.Gr3d.VtkPlotter.ShowPlot().
override void IG.Neural.Applications.DemoNeuralOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
void IG.Neural.Applications.DemoNeuralOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Member Data Documentation
readonly Color IG.Neural.Applications.DemoNeuralOld.enabledColor1D = Color.Tomato static private
readonly Color IG.Neural.Applications.DemoNeuralOld.disabledColor1D = Color.Goldenrod static private
SampledDataSet IG.Neural.Applications.DemoNeuralOld.trainingData1D = null private
SampledDataSet IG.Neural.Applications.DemoNeuralOld.verificationData1D = null private
SampledDataSet IG.Neural.Applications.DemoNeuralOld.defaultFunctionData1D = null private
INeuralApproximator IG.Neural.Applications.DemoNeuralOld.approximator1D = new NeuralApproximatorAforge() private
NeuralNetworks IG.Neural.Applications.DemoNeuralOld.network1D private
int IG.Neural.Applications.DemoNeuralOld.hiddenNeuronL11D = 5 private
int IG.Neural.Applications.DemoNeuralOld.hiddenNeuronL21D = 0 private
int IG.Neural.Applications.DemoNeuralOld.maxEpoch1D = 5000 private
int IG.Neural.Applications.DemoNeuralOld.epochInBundle1D = 500 private
double IG.Neural.Applications.DemoNeuralOld.rmsError1D = 0.001 private
double IG.Neural.Applications.DemoNeuralOld.learningRate1D = 0.3 private
double IG.Neural.Applications.DemoNeuralOld.momentum1D = 0.6 private
int IG.Neural.Applications.DemoNeuralOld.samples1D = 6 private
double IG.Neural.Applications.DemoNeuralOld.lowHorizontalLimit1D = -5.0 private
double IG.Neural.Applications.DemoNeuralOld.highHorizontalLimit1D = 5.0 private
double IG.Neural.Applications.DemoNeuralOld.lowVerificationHorizontalLimit1D = -5.0 private
double IG.Neural.Applications.DemoNeuralOld.highVerificationHorizontalLimit1D = 5.0 private
double IG.Neural.Applications.DemoNeuralOld.inputSafetyFactor1D = 1.3 private
double IG.Neural.Applications.DemoNeuralOld.outputSafetyFactor1D = 1.3 private
int IG.Neural.Applications.DemoNeuralOld.thread1D = 0 private
string IG.Neural.Applications.DemoNeuralOld.equation1D = "x*x" private
bool IG.Neural.Applications.DemoNeuralOld.maxTrainErrorEnabled1D = true private
bool IG.Neural.Applications.DemoNeuralOld.rmsTrainErrorEnabled1D = false private
bool IG.Neural.Applications.DemoNeuralOld.maxVerErrorEnabled1D = false private
bool IG.Neural.Applications.DemoNeuralOld.rmsVerErrorEnabled1D = false private
GraphPane IG.Neural.Applications.DemoNeuralOld.pane1D private
GraphPane IG.Neural.Applications.DemoNeuralOld.pane1DError private
LineItem IG.Neural.Applications.DemoNeuralOld.trainingPoints1D private
LineItem IG.Neural.Applications.DemoNeuralOld.approximatedLine1D private
LineItem IG.Neural.Applications.DemoNeuralOld.defaultFunction1D private
LineItem IG.Neural.Applications.DemoNeuralOld.errorConvergenceFunction1D private
SampledDataSet IG.Neural.Applications.DemoNeuralOld.trainingData2D = null private
SampledDataSet IG.Neural.Applications.DemoNeuralOld.verificationData2D = null private
SampledDataSet IG.Neural.Applications.DemoNeuralOld.defaultFunctionData2D = null private
INeuralApproximator IG.Neural.Applications.DemoNeuralOld.approximator2D = new NeuralApproximatorAforge() private
NeuralNetworks IG.Neural.Applications.DemoNeuralOld.network2D private
int IG.Neural.Applications.DemoNeuralOld.hiddenNeuronL12D = 5 private
int IG.Neural.Applications.DemoNeuralOld.hiddenNeuronL22D = 0 private
int IG.Neural.Applications.DemoNeuralOld.maxEpoch2D = 5000 private
int IG.Neural.Applications.DemoNeuralOld.epochInBundle2D = 500 private
double IG.Neural.Applications.DemoNeuralOld.rmsError2D = 0.001 private
double IG.Neural.Applications.DemoNeuralOld.learningRate2D = 0.3 private
double IG.Neural.Applications.DemoNeuralOld.momentum2D = 0.6 private
int IG.Neural.Applications.DemoNeuralOld.samplesX2D = 5 private
int IG.Neural.Applications.DemoNeuralOld.samplesY2D = 5 private
double IG.Neural.Applications.DemoNeuralOld.lowHorizontalLimit2D = -5.0 private
double IG.Neural.Applications.DemoNeuralOld.highHorizontalLimit2D = 5.0 private
double IG.Neural.Applications.DemoNeuralOld.lowVerticalLimit2D = 5.0 private
double IG.Neural.Applications.DemoNeuralOld.highVerticalLimit2D = 5.0 private
double IG.Neural.Applications.DemoNeuralOld.lowVerificationHorizontalLimit2D = -5.0 private
double IG.Neural.Applications.DemoNeuralOld.highVerificationHorizontalLimit2D = 5.0 private
double IG.Neural.Applications.DemoNeuralOld.inputSafetyFactor2D = 1.3 private
double IG.Neural.Applications.DemoNeuralOld.outputSafetyFactor2D = 1.3 private
int IG.Neural.Applications.DemoNeuralOld.thread12D = 0 private
string IG.Neural.Applications.DemoNeuralOld.equation2D = "x*x + y*y" private
string [] IG.Neural.Applications.DemoNeuralOld.variableNames2D = { "x", "y" } private
bool IG.Neural.Applications.DemoNeuralOld.maxTrainErrorEnabled2D = true private
bool IG.Neural.Applications.DemoNeuralOld.rmsTrainErrorEnabled2D = false private
bool IG.Neural.Applications.DemoNeuralOld.maxVerErrorEnabled2D = false private
bool IG.Neural.Applications.DemoNeuralOld.rmsVerErrorEnabled2D = false private
bool IG.Neural.Applications.DemoNeuralOld.defaultSurfaceonGraph = false private
bool IG.Neural.Applications.DemoNeuralOld.defaultGreedonGraph = true private
bool IG.Neural.Applications.DemoNeuralOld.trainingPointsonGraph = true private
bool IG.Neural.Applications.DemoNeuralOld.approximationSurfaceonGraph = true private
bool IG.Neural.Applications.DemoNeuralOld.approximationGreedonGraph = false private
bool IG.Neural.Applications.DemoNeuralOld.contureDefaultonGraph = false private
bool IG.Neural.Applications.DemoNeuralOld.contureApproximationonGraph = false private
bool IG.Neural.Applications.DemoNeuralOld.stopTraining2D = false private
bool IG.Neural.Applications.DemoNeuralOld.stopTraining1D = false private
double IG.Neural.Applications.DemoNeuralOld.opacityDefaultGraph2D = 0.5 private
double IG.Neural.Applications.DemoNeuralOld.opacityApproxGraph2D = 0.7 private
double IG.Neural.Applications.DemoNeuralOld.opacityContourGraph2D = 1.0 private
int IG.Neural.Applications.DemoNeuralOld.numAllXPoints2D = 100 private
int IG.Neural.Applications.DemoNeuralOld.numAllYPoints2D = 100 private
GraphPane IG.Neural.Applications.DemoNeuralOld.pane2DError private
LineItem IG.Neural.Applications.DemoNeuralOld.errorConvergenceFunction2D private
VtkPlotter IG.Neural.Applications.DemoNeuralOld.plotter2D private
BoundingBox2d IG.Neural.Applications.DemoNeuralOld.paramBounds2D private
Func2dFromScalarFunction IG.Neural.Applications.DemoNeuralOld.iFunctionDefault2D private
VtkSurfacePlot IG.Neural.Applications.DemoNeuralOld.plotDefault2D private
VtkSurfacePlot IG.Neural.Applications.DemoNeuralOld.plotTrainingPoints2D private
VtkSurfacePlot IG.Neural.Applications.DemoNeuralOld.plotApproximation2D private
Func2dFromScalarFunction IG.Neural.Applications.DemoNeuralOld.iFunctionTraining2D private
Func2dFromApproximator IG.Neural.Applications.DemoNeuralOld.iFunctionApproximator2D private
ExampleValueFunctionDiff3D IG.Neural.Applications.DemoNeuralOld.iFunctionDifference2D private
VtkContourPlot IG.Neural.Applications.DemoNeuralOld.plotApproximationConture2D private
VtkContourPlot IG.Neural.Applications.DemoNeuralOld.plotDefaultConture2D private
System.ComponentModel.IContainer IG.Neural.Applications.DemoNeuralOld.components = null private
Required designer variable.
System.Windows.Forms.TabControl IG.Neural.Applications.DemoNeuralOld.tabControl private
System.Windows.Forms.TabPage IG.Neural.Applications.DemoNeuralOld.tabPage1D private
System.Windows.Forms.TabPage IG.Neural.Applications.DemoNeuralOld.tabPage2D private
ZedGraph.ZedGraphControl IG.Neural.Applications.DemoNeuralOld.functionGraph private
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btLoad1D private
System.Windows.Forms.CheckBox IG.Neural.Applications.DemoNeuralOld.cbSelfMade1D private
System.Windows.Forms.TextBox IG.Neural.Applications.DemoNeuralOld.tbSelfMadeEquation1D private
System.Windows.Forms.ComboBox IG.Neural.Applications.DemoNeuralOld.cbEquation1D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label19 private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numHighXLimit1D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numLowXLimit1D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numSamples1D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label9 private
System.Windows.Forms.CheckBox IG.Neural.Applications.DemoNeuralOld.cbRandomData1D private
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btnGenerateOptData1D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numHiddenNeuron1D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label11 private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numMomentum1D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numLearningRate1D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numRMS1D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numEpochBundle1D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numMaxEpoch1D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label8 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label7 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label6 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label5 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label4 private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numOutputSafety1D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label16 private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numInputSafety1D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label15 private
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btnReset1D private
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btStart1D private
ZedGraph.ZedGraphControl IG.Neural.Applications.DemoNeuralOld.errorConvergence1D private
System.Windows.Forms.TextBox IG.Neural.Applications.DemoNeuralOld.tbRmsVerError1D private
System.Windows.Forms.TextBox IG.Neural.Applications.DemoNeuralOld.tbMaxVerError1D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label2 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label1 private
System.Windows.Forms.TextBox IG.Neural.Applications.DemoNeuralOld.tbRmsTrainError1D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label12 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label13 private
System.Windows.Forms.TextBox IG.Neural.Applications.DemoNeuralOld.tbMaxTrainError1D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numOutputSafety2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label17 private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numInputSafety2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label18 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label20 private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numMomentum2D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numLearningRate2D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numRMS2D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numEpochBundle2D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numMaxEpoch2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label21 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label22 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label23 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label24 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label25 private
System.Windows.Forms.CheckBox IG.Neural.Applications.DemoNeuralOld.cbRandomData2D private
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btnGenerateOptData2D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numSamplesX2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label14 private
System.Windows.Forms.ComboBox IG.Neural.Applications.DemoNeuralOld.cbEquation2D private
System.Windows.Forms.TextBox IG.Neural.Applications.DemoNeuralOld.tbSelfMadeEquation2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label3 private
System.Windows.Forms.CheckBox IG.Neural.Applications.DemoNeuralOld.cbSelfMade2D private
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btLoad2D private
System.Windows.Forms.TabPage IG.Neural.Applications.DemoNeuralOld.tabPage1 private
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btReset2D private
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btStart2D private
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btLoadANN1D private
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btSaveANN1D private
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btLoadANN2D private
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btSaveANN2D private
System.Windows.Forms.TextBox IG.Neural.Applications.DemoNeuralOld.tbEquationError1D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numHiddenNeuronL21D private
System.Windows.Forms.RadioButton IG.Neural.Applications.DemoNeuralOld.rbRmsTrainError private
System.Windows.Forms.RadioButton IG.Neural.Applications.DemoNeuralOld.rbMaxTrainError private
System.Windows.Forms.RadioButton IG.Neural.Applications.DemoNeuralOld.rbRmsVerError private
System.Windows.Forms.RadioButton IG.Neural.Applications.DemoNeuralOld.rbMaxVerError private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numHiddenNeuronL22D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numHiddenNeuron2D private
System.Windows.Forms.TextBox IG.Neural.Applications.DemoNeuralOld.tbEquationError2D private
System.Windows.Forms.RadioButton IG.Neural.Applications.DemoNeuralOld.rbRmsTrainError2D private
System.Windows.Forms.RadioButton IG.Neural.Applications.DemoNeuralOld.rbMaxTrainError2D private
System.Windows.Forms.RadioButton IG.Neural.Applications.DemoNeuralOld.rbRmsVerError2D private
System.Windows.Forms.RadioButton IG.Neural.Applications.DemoNeuralOld.rbMaxVerError2D private
System.Windows.Forms.TextBox IG.Neural.Applications.DemoNeuralOld.tbRmsTrainError2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label26 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label27 private
System.Windows.Forms.TextBox IG.Neural.Applications.DemoNeuralOld.tbMaxTrainError2D private
System.Windows.Forms.TextBox IG.Neural.Applications.DemoNeuralOld.tbRmsVerError2D private
System.Windows.Forms.TextBox IG.Neural.Applications.DemoNeuralOld.tbMaxVerError2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label28 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label29 private
ZedGraph.ZedGraphControl IG.Neural.Applications.DemoNeuralOld.errorConvergence2D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numHighXLimit2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label30 private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numHighYLimit2D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numLowYLimit2D private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numLowXLimit2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label31 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label32 private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label33 private
System.Windows.Forms.GroupBox IG.Neural.Applications.DemoNeuralOld.groupBox5 private
System.Windows.Forms.GroupBox IG.Neural.Applications.DemoNeuralOld.groupBox6 private
System.Windows.Forms.GroupBox IG.Neural.Applications.DemoNeuralOld.groupBox7 private
System.Windows.Forms.GroupBox IG.Neural.Applications.DemoNeuralOld.groupBox3 private
System.Windows.Forms.GroupBox IG.Neural.Applications.DemoNeuralOld.groupBox1 private
System.Windows.Forms.GroupBox IG.Neural.Applications.DemoNeuralOld.groupBox2 private
System.Windows.Forms.GroupBox IG.Neural.Applications.DemoNeuralOld.groupBox4 private
System.Windows.Forms.CheckBox IG.Neural.Applications.DemoNeuralOld.cbDefaultGreed2D private
System.Windows.Forms.TrackBar IG.Neural.Applications.DemoNeuralOld.trackbDefaultGraph2D private
System.Windows.Forms.CheckBox IG.Neural.Applications.DemoNeuralOld.cbDefaultSurface2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label35 private
System.Windows.Forms.CheckBox IG.Neural.Applications.DemoNeuralOld.cbApproximationGreed2D private
System.Windows.Forms.CheckBox IG.Neural.Applications.DemoNeuralOld.cbApproximationSurface2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label34 private
System.Windows.Forms.TrackBar IG.Neural.Applications.DemoNeuralOld.trackbApproxGraph2D private
System.Windows.Forms.CheckBox IG.Neural.Applications.DemoNeuralOld.cbTrainingPoints2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label36 private
System.Windows.Forms.GroupBox IG.Neural.Applications.DemoNeuralOld.groupBox9 private
System.Windows.Forms.TrackBar IG.Neural.Applications.DemoNeuralOld.trackbContourGraph2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label37 private
System.Windows.Forms.CheckBox IG.Neural.Applications.DemoNeuralOld.cbContourDefault2D private
System.Windows.Forms.CheckBox IG.Neural.Applications.DemoNeuralOld.cbContourApproximation2D private
System.Windows.Forms.GroupBox IG.Neural.Applications.DemoNeuralOld.groupBox8 private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.DemoNeuralOld.numSamplesY2D private
System.Windows.Forms.Label IG.Neural.Applications.DemoNeuralOld.label10 private
System.ComponentModel.BackgroundWorker IG.Neural.Applications.DemoNeuralOld.backgroundWorker1D
System.ComponentModel.BackgroundWorker IG.Neural.Applications.DemoNeuralOld.backgroundWorker2D
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btStop1D private
System.Windows.Forms.Button IG.Neural.Applications.DemoNeuralOld.btStop2D private
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/FormsOld/Old/DemoNeuralOld.cs
shelldev/lib/extended/LibNeuralExtForms/FormsOld/Old/DemoNeuralOld.Designer.cs