IGLib: Meta.Numerics.Statistics.Distributions.Distribution Class Reference
Meta.Numerics.Statistics.Distributions.Distribution Class Reference abstract
Represents all continuous, univariate probability distribution.
Public Member Functions
abstract double ProbabilityDensity (double x)
Returns the probability density at the given point.
virtual double LeftProbability (double x)
Returns the cumulative probability to the left of (below) the given point.
virtual double RightProbability (double x)
Return the cumulative probability to the right of (above) the given point.
virtual double InverseLeftProbability (double P)
Returns the point at which the cumulative distribution function attains a given value.
virtual double InverseRightProbability (double Q)
Returns the point at which the right probability function attains the given value.
override double Moment (int r)
Computes a raw moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth raw moment of the distribution.
See also
Moment
override double MomentAboutMean (int r)
Computes a central moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth central moment of the distribution.
See also
Moment
virtual double ExpectationValue (Func< double, double > f)
Computes the expectation value of the given function.
virtual double GetRandomValue (Random rng)
Returns a random value.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Cumulant (int r)
Computes a cumulant of the distribution.
Properties
virtual double Median [get]
Gets the median of the distribution.
virtual Interval Support [get]
Gets the interval over which the distribution is nonvanishing.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Detailed Description
Represents all continuous, univariate probability distribution.
Member Function Documentation
abstract double Meta.Numerics.Statistics.Distributions.Distribution.ProbabilityDensity (double x) pure virtual
Returns the probability density at the given point.
Parameters
x The reference point.
Returns
The probability density p(x).
The probability density function (PDF) gives the relative probability of obtaining different values.
Implemented in Test.TestDistribution, Meta.Numerics.Statistics.Distributions.ParetoDistribution, Meta.Numerics.Statistics.Distributions.WaldDistribution, Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution, Meta.Numerics.Statistics.Distributions.BetaDistribution, Meta.Numerics.Statistics.Distributions.KuiperDistribution, Meta.Numerics.Statistics.Distributions.LogisticDistribution, Meta.Numerics.Statistics.Distributions.GammaDistribution, Meta.Numerics.Statistics.Distributions.LognormalDistribution, Meta.Numerics.Statistics.Distributions.TriangularDistribution, Meta.Numerics.Statistics.Distributions.WeibullDistribution, Meta.Numerics.Statistics.Distributions.FisherDistribution, Meta.Numerics.Statistics.Distributions.GumbelDistribution, Meta.Numerics.Statistics.Distributions.CauchyDistribution, Meta.Numerics.Statistics.Distributions.ChiSquaredDistribution, Meta.Numerics.Statistics.Distributions.NormalDistribution, Meta.Numerics.Statistics.Distributions.ExponentialDistribution, Meta.Numerics.Statistics.Distributions.StudentDistribution, Meta.Numerics.Statistics.Distributions.UniformDistribution, Meta.Numerics.Statistics.Distributions.PearsonRDistribution, and Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.
Referenced by Test.DistributionTest.DistributionCentralMomentIntegral(), Test.DistributionTest.DistributionMeanIntegral(), Test.DistributionTest.DistributionProbabilityIntegral(), Test.DistributionTest.DistributionProbabilityTestHelper(), Test.DistributionTest.DistributionRawMomentIntegral(), Test.DistributionTest.DistributionVarianceIntegral(), Test.DistributionTest.OutsideDistributionSupport(), and Test.SampleTest.TestMoments().
virtual double Meta.Numerics.Statistics.Distributions.Distribution.LeftProbability (double x) inline virtual
Returns the cumulative probability to the left of (below) the given point.
Parameters
x The reference point.
Returns
The integrated probability to obtain a result below the reference point.
The left probability function is commonly called the cumulative distribution function (CDF).
Reimplemented in Meta.Numerics.Statistics.Distributions.ParetoDistribution, Meta.Numerics.Statistics.Distributions.LognormalDistribution, Meta.Numerics.Statistics.Distributions.GammaDistribution, Meta.Numerics.Statistics.Distributions.WaldDistribution, Meta.Numerics.Statistics.Distributions.CauchyDistribution, Meta.Numerics.Statistics.Distributions.BetaDistribution, Meta.Numerics.Statistics.Distributions.LogisticDistribution, Meta.Numerics.Statistics.Distributions.WeibullDistribution, Meta.Numerics.Statistics.Distributions.TriangularDistribution, Meta.Numerics.Statistics.Distributions.FisherDistribution, Meta.Numerics.Statistics.Distributions.PearsonRDistribution, Meta.Numerics.Statistics.Distributions.GumbelDistribution, Meta.Numerics.Statistics.Distributions.KolmogorovDistribution, Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution, Meta.Numerics.Statistics.Distributions.ChiSquaredDistribution, Meta.Numerics.Statistics.Distributions.NormalDistribution, Meta.Numerics.Statistics.Distributions.ExponentialDistribution, Meta.Numerics.Statistics.Distributions.StudentDistribution, Meta.Numerics.Statistics.Distributions.UniformDistribution, and Meta.Numerics.Statistics.Distributions.KuiperDistribution.
References Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
Referenced by Meta.Numerics.Statistics.Sample.ComputeDStatistics(), Test.DistributionTest.DistributionProbabilityIntegral(), Test.DistributionTest.DistributionProbabilityTestHelper(), Test.DistributionTest.OutsideDistributionSupport(), and FutureTest.FutureTest.TestNormalOrderStatistic().
virtual double Meta.Numerics.Statistics.Distributions.Distribution.RightProbability (double x) inline virtual
Return the cumulative probability to the right of (above) the given point.
Parameters
x The reference point.
Returns
The integrated probability 1-P(x1) to obtain a result above the reference point.
In survival analysis, the right probability function is commonly called the survival function, because it gives the fraction of the population remaining after the given time.
Reimplemented in Meta.Numerics.Statistics.Distributions.ParetoDistribution, Meta.Numerics.Statistics.Distributions.LognormalDistribution, Meta.Numerics.Statistics.Distributions.GammaDistribution, Meta.Numerics.Statistics.Distributions.CauchyDistribution, Meta.Numerics.Statistics.Distributions.BetaDistribution, Meta.Numerics.Statistics.Distributions.LogisticDistribution, Meta.Numerics.Statistics.Distributions.TriangularDistribution, Meta.Numerics.Statistics.Distributions.WeibullDistribution, Meta.Numerics.Statistics.Distributions.FisherDistribution, Meta.Numerics.Statistics.Distributions.GumbelDistribution, Meta.Numerics.Statistics.Distributions.KolmogorovDistribution, Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution, Meta.Numerics.Statistics.Distributions.ExponentialDistribution, Meta.Numerics.Statistics.Distributions.NormalDistribution, Meta.Numerics.Statistics.Distributions.ChiSquaredDistribution, Meta.Numerics.Statistics.Distributions.StudentDistribution, and Meta.Numerics.Statistics.Distributions.KuiperDistribution.
Referenced by Test.DistributionTest.DistributionProbabilityIntegral(), Test.DistributionTest.DistributionProbabilityTestHelper(), Test.DistributionTest.OutsideDistributionSupport(), and FutureTest.FutureTest.TestNormalOrderStatistic().
virtual double Meta.Numerics.Statistics.Distributions.Distribution.InverseLeftProbability (double P) inline virtual
Returns the point at which the cumulative distribution function attains a given value.
Parameters
P The left cumulative probability P, which must lie between 0 and 1.
Returns
The value x at which LeftProbability equals P.
The inverse left probability is commonly called the quantile function. Given a quantile, it tells which variable value is the lower border of that quantile.
Exceptions
ArgumentOutOfRangeException P lies outside [0,1].
Reimplemented in Meta.Numerics.Statistics.Distributions.GammaDistribution, Meta.Numerics.Statistics.Distributions.ParetoDistribution, Meta.Numerics.Statistics.Distributions.BetaDistribution, Meta.Numerics.Statistics.Distributions.FisherDistribution, Meta.Numerics.Statistics.Distributions.NormalDistribution, Meta.Numerics.Statistics.Distributions.LognormalDistribution, Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution, Meta.Numerics.Statistics.Distributions.CauchyDistribution, Meta.Numerics.Statistics.Distributions.TriangularDistribution, Meta.Numerics.Statistics.Distributions.LogisticDistribution, Meta.Numerics.Statistics.Distributions.WeibullDistribution, Meta.Numerics.Statistics.Distributions.GumbelDistribution, Meta.Numerics.Statistics.Distributions.ExponentialDistribution, Meta.Numerics.Statistics.Distributions.ChiSquaredDistribution, Meta.Numerics.Statistics.Distributions.StudentDistribution, and Meta.Numerics.Statistics.Distributions.UniformDistribution.
References Meta.Numerics.Analysis.FunctionMath.FindZero().
Referenced by Test.MultivariateSampleTest.CreateMultivariateNormalSample(), Test.DistributionTest.DistributionInvalidProbabilityInput(), Test.DistributionTest.DistributionMedian(), Test.DistributionTest.DistributionMonotonicity(), Test.DistributionTest.FisherTest(), Test.MultivariateSampleTest.MultivariateLinearRegressionTest(), Test.SampleTest.SampleComparisonTest(), Test.DistributionTest.StudentTest(), Test.DistributionTest.StudentTest2(), Test.RandomTest.TimeGammaGenerators(), and Test.RandomTest.TimeNormalGenerators().
virtual double Meta.Numerics.Statistics.Distributions.Distribution.InverseRightProbability (double Q) inline virtual
Returns the point at which the right probability function attains the given value.
Parameters
Q The right cumulative probability, which must lie between 0 and 1.
Returns
The value x for which RightProbability equals Q.
Reimplemented in Meta.Numerics.Statistics.Distributions.BetaDistribution, Meta.Numerics.Statistics.Distributions.ParetoDistribution, Meta.Numerics.Statistics.Distributions.FisherDistribution, Meta.Numerics.Statistics.Distributions.NormalDistribution, Meta.Numerics.Statistics.Distributions.LognormalDistribution, Meta.Numerics.Statistics.Distributions.CauchyDistribution, Meta.Numerics.Statistics.Distributions.LogisticDistribution, Meta.Numerics.Statistics.Distributions.WeibullDistribution, Meta.Numerics.Statistics.Distributions.ExponentialDistribution, and Meta.Numerics.Statistics.Distributions.UniformDistribution.
References Meta.Numerics.Analysis.FunctionMath.FindZero().
Referenced by FutureTest.FutureTest.TestInverseKS().
override double Meta.Numerics.Statistics.Distributions.Distribution.Moment (int r) inline virtual
Computes a raw moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth raw moment of the distribution.
See also
Moment
Implements Meta.Numerics.Statistics.Distributions.UnivariateDistribution.
Reimplemented in Meta.Numerics.Statistics.Distributions.LognormalDistribution, Meta.Numerics.Statistics.Distributions.TriangularDistribution, Meta.Numerics.Statistics.Distributions.KuiperDistribution, Meta.Numerics.Statistics.Distributions.KolmogorovDistribution, Meta.Numerics.Statistics.Distributions.GammaDistribution, Meta.Numerics.Statistics.Distributions.GumbelDistribution, Meta.Numerics.Statistics.Distributions.WeibullDistribution, Meta.Numerics.Statistics.Distributions.FisherDistribution, Meta.Numerics.Statistics.Distributions.LogisticDistribution, Meta.Numerics.Statistics.Distributions.ParetoDistribution, Meta.Numerics.Statistics.Distributions.StudentDistribution, Meta.Numerics.Statistics.Distributions.ExponentialDistribution, Meta.Numerics.Statistics.Distributions.NormalDistribution, Meta.Numerics.Statistics.Distributions.PearsonRDistribution, Meta.Numerics.Statistics.Distributions.UniformDistribution, and Meta.Numerics.Statistics.Distributions.WaldDistribution.
References Meta.Numerics.MoreMath.Pow().
Referenced by FutureTest.FutureTest.CumulantTest(), Test.DiscreteDistributionTest.DiscreteContinuousAgreement(), Test.DistributionTest.DistributionMomentTranslations(), Test.DistributionTest.DistributionRawMomentIntegral(), Test.SampleTest.SampleMoments(), and Test.SampleTest.TestMoments().
override double Meta.Numerics.Statistics.Distributions.Distribution.MomentAboutMean (int r) inline virtual
Computes a central moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth central moment of the distribution.
See also
Moment
Reimplemented from Meta.Numerics.Statistics.Distributions.UnivariateDistribution.
Reimplemented in Meta.Numerics.Statistics.Distributions.LognormalDistribution, Meta.Numerics.Statistics.Distributions.TriangularDistribution, Meta.Numerics.Statistics.Distributions.KuiperDistribution, Meta.Numerics.Statistics.Distributions.KolmogorovDistribution, Meta.Numerics.Statistics.Distributions.FisherDistribution, Meta.Numerics.Statistics.Distributions.GammaDistribution, Meta.Numerics.Statistics.Distributions.WeibullDistribution, Meta.Numerics.Statistics.Distributions.LogisticDistribution, Meta.Numerics.Statistics.Distributions.UniformDistribution, Meta.Numerics.Statistics.Distributions.GumbelDistribution, Meta.Numerics.Statistics.Distributions.ParetoDistribution, Meta.Numerics.Statistics.Distributions.StudentDistribution, Meta.Numerics.Statistics.Distributions.ExponentialDistribution, Meta.Numerics.Statistics.Distributions.NormalDistribution, Meta.Numerics.Statistics.Distributions.WaldDistribution, and Meta.Numerics.Statistics.Distributions.PearsonRDistribution.
References Meta.Numerics.MoreMath.Pow().
Referenced by FutureTest.FutureTest.CumulantTest(), Test.DiscreteDistributionTest.DiscreteContinuousAgreement(), Test.DistributionTest.DistributionCentralMomentIntegral(), Test.DistributionTest.DistributionMomentTranslations(), Test.DistributionTest.DistributionSkewness(), Test.SampleTest.SampleMoments(), Test.SampleTest.TestMoments(), and Test.NullDistributionTests.TwoSampleKolmogorovNullDistributionTest().
virtual double Meta.Numerics.Statistics.Distributions.Distribution.ExpectationValue (Func< double, double > f) inline virtual
Computes the expectation value of the given function.
Parameters
f The function.
Returns
The expectation value of the function.
References Meta.Numerics.Analysis.FunctionMath.Integrate().
Referenced by Test.DistributionTest.TransformedBetaMoments().
virtual double Meta.Numerics.Statistics.Distributions.Distribution.GetRandomValue (Random rng) inline virtual
Returns a random value.
Parameters
rng A random number generator.
Returns
A number distributed according to the distribution.
Note that the random number generator rng will be advanced by this method. The next call to its generator methods will not give the same value as it would had it not been passed to this method.
Reimplemented in Meta.Numerics.Statistics.Distributions.GammaDistribution, Meta.Numerics.Statistics.Distributions.BetaDistribution, Meta.Numerics.Statistics.Distributions.NormalDistribution, Meta.Numerics.Statistics.Distributions.LognormalDistribution, Meta.Numerics.Statistics.Distributions.CauchyDistribution, and Meta.Numerics.Statistics.Distributions.StudentDistribution.
Referenced by Test.SampleTest.AnovaDistribution(), Test.BivariateSampleTest.BivariateLinearRegression(), Test.BivariateSampleTest.BivariatePolynomialRegression(), Test.BugTests.Bug7788(), Test.SampleTest.CreateSample(), Test.DistributionTest.FisherInversion(), Test.DistributionTest.InverseGaussianSummation(), Test.MultivariateSampleTest.MultivariateMoments(), Test.SampleTest.SignTestDistribution(), Test.SampleTest.TTestDistribution(), Test.DistributionTest.UniformOrderStatistics(), Test.SampleTest.WaldFitUncertainties(), and Test.SampleTest.ZTestDistribution().
Property Documentation
virtual double Meta.Numerics.Statistics.Distributions.Distribution.Median get
Gets the median of the distribution.
The median is the point with equal integrated probability above and below, i.e. with P(x1) = 0.5.
Referenced by Test.BugTests.Bug7788(), Test.DistributionTest.DistributionBase(), Test.DistributionTest.DistributionCentralInequality(), Test.DistributionTest.DistributionMedian(), and Test.SampleTest.SignTestDistribution().
virtual Interval Meta.Numerics.Statistics.Distributions.Distribution.Support get
Gets the interval over which the distribution is nonvanishing.
Referenced by Test.DiscreteDistributionTest.DiscreteContinuousAgreement(), Test.DistributionTest.DistributionCentralMomentIntegral(), Test.DistributionTest.DistributionMeanIntegral(), Test.DistributionTest.DistributionProbabilityIntegral(), Test.DistributionTest.DistributionRawMomentIntegral(), Test.DistributionTest.DistributionVarianceIntegral(), Test.DistributionTest.OutsideDistributionSupport(), and Test.SampleTest.TestMoments().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/Distribution.cs