IGLib: IG.Configer.Configer Class Reference
IG.Configer.Configer Class Reference
Public Member Functions
Configer ()
void AutoCorrectAll ()
Automatically correct all configuration files as it is specified in Configuration.
Static Public Member Functions
static void ReportError (Exception ex)
static void WriteLine (string str)
Public Attributes
const string AddrFile = "/File"
DataStore Configuration =null
Static Public Attributes
static bool _ConsoleApp =true
Private Attributes
const string AddrFilePath = "/Path"
Constructor & Destructor Documentation
IG.Configer.Configer.Configer () inline
Member Function Documentation
static void IG.Configer.Configer.ReportError (Exception ex) inline static
Referenced by IG.Configer.ConfigerConsole.ConfigerConsoleMain(), IG.Configer.ConfigerConsole.Main(), and IG.Configer.ConfigerConsole.TestConsoleForm().
static void IG.Configer.Configer.WriteLine (string str) inline static
References IG.Forms.UtilForms.AppConsole, and IG.Forms.ConsoleForm.WriteLine().
Referenced by IG.Configer.Configer.AutoCorrectAll(), and IG.Configer.ConfigerConsole.ConfigerConsoleMain().
void IG.Configer.Configer.AutoCorrectAll () inline
Automatically correct all configuration files as it is specified in Configuration.
References IG.Lib.DataStore.GetElements(), and IG.Configer.Configer.WriteLine().
Member Data Documentation
const string IG.Configer.Configer.AddrFile = "/File"
const string IG.Configer.Configer.AddrFilePath = "/Path" private
bool IG.Configer.Configer._ConsoleApp =true static
DataStore IG.Configer.Configer.Configuration =null
Referenced by IG.Configer.ConfigerConsole.ConfigerConsoleMain().
The documentation for this class was generated from the following file:
igapp/configer/configerlib.cs