IGLib: alglib.idwint Class Reference
alglib.idwint Class Reference
Classes
class idwinterpolant
Static Public Member Functions
static double idwcalc (idwinterpolant z, double[] x)
static void idwbuildmodifiedshepard (double[,] xy, int n, int nx, int d, int nq, int nw, idwinterpolant z)
static void idwbuildmodifiedshepardr (double[,] xy, int n, int nx, double r, idwinterpolant z)
static void idwbuildnoisy (double[,] xy, int n, int nx, int d, int nq, int nw, idwinterpolant z)
static double idwcalc (idwinterpolant z, double[] x)
static void idwbuildmodifiedshepard (double[,] xy, int n, int nx, int d, int nq, int nw, idwinterpolant z)
static void idwbuildmodifiedshepardr (double[,] xy, int n, int nx, double r, idwinterpolant z)
static void idwbuildnoisy (double[,] xy, int n, int nx, int d, int nq, int nw, idwinterpolant z)
Public Attributes
const double idwqfactor = 1.5
const int idwkmin = 5
Static Private Member Functions
static double idwcalcq (idwinterpolant z, double[] x, int k)
static void idwinit1 (int n, int nx, int d, int nq, int nw, idwinterpolant z)
static void idwinternalsolver (ref double[] y, ref double[] w, ref double[,] fmatrix, ref double[] temp, int n, int m, ref int info, ref double[] x, ref double taskrcond)
static double idwcalcq (idwinterpolant z, double[] x, int k)
static void idwinit1 (int n, int nx, int d, int nq, int nw, idwinterpolant z)
static void idwinternalsolver (ref double[] y, ref double[] w, ref double[,] fmatrix, ref double[] temp, int n, int m, ref int info, ref double[] x, ref double taskrcond)
Member Function Documentation
static double alglib.idwint.idwcalc (idwinterpolant z, double[] x) inline static
References alglib.idwint.idwcalcq(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryresultsdistances(), alglib.nearestneighbor.kdtreequeryresultstags(), alglib.nearestneighbor.kdtreequeryrnn(), alglib.idwint.idwinterpolant.modeltype, alglib.idwint.idwinterpolant.nw, alglib.idwint.idwinterpolant.nx, alglib.idwint.idwinterpolant.r, alglib.idwint.idwinterpolant.rbuf, alglib.math.sqr(), alglib.idwint.idwinterpolant.tbuf, and alglib.idwint.idwinterpolant.tree.
Referenced by alglib.idwcalc(), alglib.testidwintunit.testdegree(), alglib.testidwintunit.testnoisy(), alglib.testidwintunit.testrxy(), and alglib.testidwintunit.testxy().
static void alglib.idwint.idwbuildmodifiedshepard (double xy[,], int n, int nx, int d, int nq, int nw, idwinterpolant z) inline static
References alglib.ap.assert(), alglib.idwint.idwinterpolant.debugbestrcond, alglib.idwint.idwinterpolant.debugsolverfailures, alglib.idwint.idwinterpolant.debugworstrcond, alglib.idwint.idwinit1(), alglib.idwint.idwinternalsolver(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryresultsdistances(), alglib.nearestneighbor.kdtreequeryresultsxy(), alglib.idwint.idwinterpolant.modeltype, alglib.idwint.idwinterpolant.q, alglib.math.sqr(), and alglib.idwint.idwinterpolant.tree.
Referenced by alglib.idwbuildmodifiedshepard(), alglib.testidwintunit.testdegree(), alglib.testidwintunit.testnoisy(), and alglib.testidwintunit.testxy().
static void alglib.idwint.idwbuildmodifiedshepardr (double xy[,], int n, int nx, double r, idwinterpolant z) inline static
References alglib.ap.assert(), alglib.idwint.idwinit1(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.idwint.idwinterpolant.modeltype, alglib.idwint.idwinterpolant.q, alglib.idwint.idwinterpolant.r, and alglib.idwint.idwinterpolant.tree.
Referenced by alglib.idwbuildmodifiedshepardr(), and alglib.testidwintunit.testrxy().
static void alglib.idwint.idwbuildnoisy (double xy[,], int n, int nx, int d, int nq, int nw, idwinterpolant z) inline static
References alglib.ap.assert(), alglib.idwint.idwinterpolant.debugbestrcond, alglib.idwint.idwinterpolant.debugsolverfailures, alglib.idwint.idwinterpolant.debugworstrcond, alglib.idwint.idwinit1(), alglib.idwint.idwinternalsolver(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryresultsdistances(), alglib.nearestneighbor.kdtreequeryresultsxy(), alglib.idwint.idwinterpolant.modeltype, alglib.idwint.idwinterpolant.q, and alglib.idwint.idwinterpolant.tree.
Referenced by alglib.idwbuildnoisy(), and alglib.testidwintunit.testnoisy().
static double alglib.idwint.idwcalcq (idwinterpolant z, double[] x, int k) inline static private
References alglib.idwint.idwinterpolant.d, alglib.idwint.idwinterpolant.nx, and alglib.idwint.idwinterpolant.q.
Referenced by alglib.idwint.idwcalc().
static void alglib.idwint.idwinit1 (int n, int nx, int d, int nq, int nw, idwinterpolant z) inline static private
References alglib.idwint.idwinterpolant.d, alglib.idwint.idwinterpolant.debugbestrcond, alglib.idwint.idwinterpolant.debugsolverfailures, alglib.idwint.idwinterpolant.debugworstrcond, alglib.idwint.idwinterpolant.n, alglib.idwint.idwinterpolant.nw, alglib.idwint.idwinterpolant.nx, alglib.idwint.idwinterpolant.q, alglib.idwint.idwinterpolant.rbuf, alglib.idwint.idwinterpolant.tbuf, alglib.idwint.idwinterpolant.xbuf, and alglib.idwint.idwinterpolant.xybuf.
Referenced by alglib.idwint.idwbuildmodifiedshepard(), alglib.idwint.idwbuildmodifiedshepardr(), and alglib.idwint.idwbuildnoisy().
static void alglib.idwint.idwinternalsolver (ref double[] y, ref double[] w, ref double fmatrix[,], ref double[] temp, int n, int m, ref int info, ref double[] x, ref double taskrcond) inline static private
References alglib.reflections.generatereflection(), alglib.math.machineepsilon, alglib.densesolver.rmatrixsolvels(), and alglib.rcond.rmatrixtrrcondinf().
Referenced by alglib.idwint.idwbuildmodifiedshepard(), and alglib.idwint.idwbuildnoisy().
static double alglib.idwint.idwcalc (idwinterpolant z, double[] x) inline static
References alglib.idwint.idwcalcq(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryresultsdistances(), alglib.nearestneighbor.kdtreequeryresultstags(), alglib.nearestneighbor.kdtreequeryrnn(), and alglib.math.sqr().
static void alglib.idwint.idwbuildmodifiedshepard (double xy[,], int n, int nx, int d, int nq, int nw, idwinterpolant z) inline static
References alglib.ap.assert(), alglib.idwint.idwinit1(), alglib.idwint.idwinternalsolver(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryresultsdistances(), alglib.nearestneighbor.kdtreequeryresultsxy(), and alglib.math.sqr().
static void alglib.idwint.idwbuildmodifiedshepardr (double xy[,], int n, int nx, double r, idwinterpolant z) inline static
References alglib.ap.assert(), alglib.idwint.idwinit1(), and alglib.nearestneighbor.kdtreebuildtagged().
static void alglib.idwint.idwbuildnoisy (double xy[,], int n, int nx, int d, int nq, int nw, idwinterpolant z) inline static
References alglib.ap.assert(), alglib.idwint.idwinit1(), alglib.idwint.idwinternalsolver(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryresultsdistances(), and alglib.nearestneighbor.kdtreequeryresultsxy().
static double alglib.idwint.idwcalcq (idwinterpolant z, double[] x, int k) inline static private
static void alglib.idwint.idwinit1 (int n, int nx, int d, int nq, int nw, idwinterpolant z) inline static private
static void alglib.idwint.idwinternalsolver (ref double[] y, ref double[] w, ref double fmatrix[,], ref double[] temp, int n, int m, ref int info, ref double[] x, ref double taskrcond) inline static private
References alglib.reflections.generatereflection(), alglib.math.machineepsilon, alglib.densesolver.rmatrixsolvels(), and alglib.rcond.rmatrixtrrcondinf().
Member Data Documentation
const double alglib.idwint.idwqfactor = 1.5
const int alglib.idwint.idwkmin = 5
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/interpolation.cs