IGLib: MailslotNative Class Reference
MailslotNative Class Reference
The class exposes kernel32.dll methods for Mailslot communication.
Public Member Functions
static bool ReadFile (IntPtr hFile, byte[] lpBuffer, int nNumberOfBytesToRead, out int lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, and starts at the position that the file pointer indicates
static bool WriteFile (IntPtr handle, byte[] lpBuffer, int nNumberOfBytesToWrite, out int lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to the specified file at the position specified by the file pointer.
static bool CloseHandle (IntPtr hObject)
Closes an open object handle
static bool GetMailslotInfo (IntPtr hMailslot, IntPtr lpMaxMessageSize, out int lpNextSize, out int lpMessageCount, IntPtr lpReadTimeout)
Retrieves information about the specified mailslot
static IntPtr CreateMailslot (string lpName, uint nMaxMessageSize, int lReadTimeout, IntPtr lpSecurityAttributes)
Creates an instance of a mailslot and returns a handle for subsequent operations.
static IntPtr CreateFile (string lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr SecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, IntPtr hTemplateFile)
open an instance of a mailslot and returns a handle for subsequent operations.
static bool ReadFile (IntPtr hFile, byte[] lpBuffer, int nNumberOfBytesToRead, out int lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, and starts at the position that the file pointer indicates
static bool WriteFile (IntPtr handle, byte[] lpBuffer, int nNumberOfBytesToWrite, out int lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to the specified file at the position specified by the file pointer.
static bool CloseHandle (IntPtr hObject)
Closes an open object handle
static bool GetMailslotInfo (IntPtr hMailslot, IntPtr lpMaxMessageSize, out int lpNextSize, out int lpMessageCount, IntPtr lpReadTimeout)
Retrieves information about the specified mailslot
static IntPtr CreateMailslot (string lpName, uint nMaxMessageSize, int lReadTimeout, IntPtr lpSecurityAttributes)
Creates an instance of a mailslot and returns a handle for subsequent operations.
static IntPtr CreateFile (string lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr SecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, IntPtr hTemplateFile)
open an instance of a mailslot and returns a handle for subsequent operations.
Public Attributes
const int MAILSLOT_WAIT_FOREVER = -1
mailslot waits forever for a message
const int INVALID_HANDLE_VALUE = -1
Invalid operating system handle.
const int MAILSLOT_NO_MESSAGE = -1
There is no next message
Private Member Functions
static bool SetMailslotInfo (IntPtr hMailslot, uint lReadTimeout)
Sets the time-out value used by the specified mailslot for a read operation
static bool SetMailslotInfo (IntPtr hMailslot, uint lReadTimeout)
Sets the time-out value used by the specified mailslot for a read operation
Detailed Description
The class exposes kernel32.dll methods for Mailslot communication.
The class exposes kernel32.dll methods for MailSlot communication.
Member Function Documentation
static bool MailslotNative.ReadFile (IntPtr hFile, byte[] lpBuffer, int nNumberOfBytesToRead, out int lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, and starts at the position that the file pointer indicates
Parameters
hFile A handle to the file to be read
lpBuffer A buffer that receives the data read from a file
nNumberOfBytesToRead The maximum number of bytes to be read
lpNumberOfBytesRead the number of bytes read
lpOverlapped A pointer to an OVERLAPPED structure.
Returns
The ReadFile functiona returns when one of the following conditions is met:A write operation completes on the write end of the pipe;The number of bytes requested is read;An error occurs
Referenced by Program.ReadMailslot().
static bool MailslotNative.WriteFile (IntPtr handle, byte[] lpBuffer, int nNumberOfBytesToWrite, out int lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to the specified file at the position specified by the file pointer.
Parameters
handle A handle to the file
lpBuffer A buffer containing the data to be written to the file.
nNumberOfBytesToWrite The number of bytes to be written to the file.
lpNumberOfBytesWritten the number of bytes written.
lpOverlapped A pointer to an OVERLAPPED structure.
Returns
If the function succeeds, the return value is nonzero.
Referenced by Program.WriteMailslot().
static bool MailslotNative.CloseHandle (IntPtr hObject)
Closes an open object handle
Parameters
hObject A valid handle to an open object
Returns
If the function succeeds, the return value is nonzero.
Referenced by Program.Main().
static bool MailslotNative.GetMailslotInfo (IntPtr hMailslot, IntPtr lpMaxMessageSize, out int lpNextSize, out int lpMessageCount, IntPtr lpReadTimeout)
Retrieves information about the specified mailslot
Parameters
hMailslot A handle to a mailslot
lpMaxMessageSize The maximum message size, in bytes, allowed for this mailslot
lpNextSize The size of the next message in bytes
lpMessageCount The total number of messages waiting to be read
lpReadTimeout The amount of time, in milliseconds, a read operation can wait for a message to be written to the mailslot before a time-out occurs.
Returns
Referenced by Program.ReadMailslot().
static IntPtr MailslotNative.CreateMailslot (string lpName, uint nMaxMessageSize, int lReadTimeout, IntPtr lpSecurityAttributes)
Creates an instance of a mailslot and returns a handle for subsequent operations.
Parameters
lpName mailslot name
nMaxMessageSize The maximum size of a single message
lReadTimeout The time a read operation can wait for a message
lpSecurityAttributes Security attributes
Returns
If the function succeeds, the return value is a handle to the server end of a mailslot instance.
Referenced by Program.Main().
static IntPtr MailslotNative.CreateFile (string lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr SecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, IntPtr hTemplateFile)
open an instance of a mailslot and returns a handle for subsequent operations.
Parameters
lpFileName mailslot name
dwDesiredAccess The access to the object
dwShareMode The sharing mode of an object
SecurityAttributes Security attributes
dwCreationDisposition An action to take on files that exist and do not exist
dwFlagsAndAttributes The file attributes and flags
hTemplateFile A handle to a template file with the GENERIC_READ access right
Returns
If the function succeeds, the return value is a handle to the server end of a mailslot instance
Referenced by Program.Main().
static bool MailslotNative.SetMailslotInfo (IntPtr hMailslot, uint lReadTimeout) private
Sets the time-out value used by the specified mailslot for a read operation
Parameters
hMailslot A handle to a mailslot
lReadTimeout The time a read operation can wait for a message to be written to the mailslot before a time-out occurs, in milliseconds
Returns
If the function succeeds, the return value is nonzero. If the function fails, the return value is zero
static bool MailslotNative.ReadFile (IntPtr hFile, byte[] lpBuffer, int nNumberOfBytesToRead, out int lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, and starts at the position that the file pointer indicates
Parameters
hFile A handle to the file to be read
lpBuffer A buffer that receives the data read from a file
nNumberOfBytesToRead The maximum number of bytes to be read
lpNumberOfBytesRead the number of bytes read
lpOverlapped A pointer to an OVERLAPPED structure.
Returns
The ReadFile functiona returns when one of the following conditions is met: A write operation completes on the write end of the pipe; The number of bytes requested is read; An error occurs.
static bool MailslotNative.WriteFile (IntPtr handle, byte[] lpBuffer, int nNumberOfBytesToWrite, out int lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to the specified file at the position specified by the file pointer.
Parameters
handle A handle to the file
lpBuffer A buffer containing the data to be written to the file.
nNumberOfBytesToWrite The number of bytes to be written to the file.
lpNumberOfBytesWritten the number of bytes written.
lpOverlapped A pointer to an OVERLAPPED structure.
Returns
If the function succeeds, the return value is nonzero.
static bool MailslotNative.CloseHandle (IntPtr hObject)
Closes an open object handle
Parameters
hObject A valid handle to an open object
Returns
If the function succeeds, the return value is nonzero.
Parameters
hObject / handle to kernel object
static bool MailslotNative.GetMailslotInfo (IntPtr hMailslot, IntPtr lpMaxMessageSize, out int lpNextSize, out int lpMessageCount, IntPtr lpReadTimeout)
Retrieves information about the specified mailslot
Parameters
hMailslot A handle to a mailslot
lpMaxMessageSize The maximum message size, in bytes, allowed for this mailslot
lpNextSize The size of the next message in bytes
lpMessageCount The total number of messages waiting to be read
lpReadTimeout The amount of time, in milliseconds, a read operation can wait for a message to be written to the mailslot before a time-out occurs.
Returns
static IntPtr MailslotNative.CreateMailslot (string lpName, uint nMaxMessageSize, int lReadTimeout, IntPtr lpSecurityAttributes)
Creates an instance of a mailslot and returns a handle for subsequent operations.
Parameters
lpName mailslot name
nMaxMessageSize The maximum size of a single message
lReadTimeout The time a read operation can wait for a message
lpSecurityAttributes Security attributes
Returns
If the function succeeds, the return value is a handle to the server end of a mailslot instance.
static IntPtr MailslotNative.CreateFile (string lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr SecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, IntPtr hTemplateFile)
open an instance of a mailslot and returns a handle for subsequent operations.
Parameters
lpFileName mailslot name
dwDesiredAccess The access to the object
dwShareMode The sharing mode of an object
SecurityAttributes Security attributes
dwCreationDisposition An action to take on files that exist and do not exist
dwFlagsAndAttributes The file attributes and flags
hTemplateFile A handle to a template file with the GENERIC_READ access right
Returns
If the function succeeds, the return value is a handle to the server end of a mailslot instance
static bool MailslotNative.SetMailslotInfo (IntPtr hMailslot, uint lReadTimeout) private
Sets the time-out value used by the specified mailslot for a read operation
Parameters
hMailslot A handle to a mailslot
lReadTimeout The time a read operation can wait for a message to be written to the mailslot before a time-out occurs, in milliseconds
Returns
If the function succeeds, the return value is nonzero. If the function fails, the return value is zero
Member Data Documentation
const int MailslotNative.MAILSLOT_WAIT_FOREVER = -1
mailslot waits forever for a message
Referenced by Program.Main().
const int MailslotNative.INVALID_HANDLE_VALUE = -1
Invalid operating system handle.
Referenced by Program.Main().
const int MailslotNative.MAILSLOT_NO_MESSAGE = -1
There is no next message
Referenced by Program.ReadMailslot().
The documentation for this class was generated from the following file:
igsandbox/InterprocessCommunication/named_pipe_examples_master/Inter-Process Communication (IPC)/CSMailslotClient/MailslotNative.cs