IGLib: alglib.optserv Class Reference
alglib.optserv Class Reference
Static Public Member Functions
static void trimprepare (double f, ref double threshold)
static void trimfunction (ref double f, ref double[] g, int n, double threshold)
static bool enforceboundaryconstraints (ref double[] x, double[] bl, bool[] havebl, double[] bu, bool[] havebu, int nmain, int nslack)
static void projectgradientintobc (double[] x, ref double[] g, double[] bl, bool[] havebl, double[] bu, bool[] havebu, int nmain, int nslack)
static void calculatestepbound (double[] x, double[] d, double alpha, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack, ref int variabletofreeze, ref double valuetofreeze, ref double maxsteplen)
static int postprocessboundedstep (ref double[] x, double[] xprev, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack, int variabletofreeze, double valuetofreeze, double steptaken, double maxsteplen)
static void filterdirection (ref double[] d, double[] x, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, double[] s, int nmain, int nslack, double droptol)
static int numberofchangedconstraints (double[] x, double[] xprev, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack)
static bool findfeasiblepoint (ref double[] x, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack, double[,] ce, int k, double epsi, ref int qpits, ref int gpaits)
static bool derivativecheck (double f0, double df0, double f1, double df1, double f, double df, double width)
static void trimprepare (double f, ref double threshold)
static void trimfunction (ref double f, ref double[] g, int n, double threshold)
static bool enforceboundaryconstraints (ref double[] x, double[] bl, bool[] havebl, double[] bu, bool[] havebu, int nmain, int nslack)
static void projectgradientintobc (double[] x, ref double[] g, double[] bl, bool[] havebl, double[] bu, bool[] havebu, int nmain, int nslack)
static void calculatestepbound (double[] x, double[] d, double alpha, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack, ref int variabletofreeze, ref double valuetofreeze, ref double maxsteplen)
static int postprocessboundedstep (ref double[] x, double[] xprev, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack, int variabletofreeze, double valuetofreeze, double steptaken, double maxsteplen)
static void filterdirection (ref double[] d, double[] x, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, double[] s, int nmain, int nslack, double droptol)
static int numberofchangedconstraints (double[] x, double[] xprev, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack)
static bool findfeasiblepoint (ref double[] x, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack, double[,] ce, int k, double epsi, ref int qpits, ref int gpaits)
static bool derivativecheck (double f0, double df0, double f1, double df1, double f, double df, double width)
Member Function Documentation
static void alglib.optserv.trimprepare (double f, ref double threshold) inline static
Referenced by alglib.minbleic.minbleiciteration(), and alglib.mincg.mincgiteration().
static void alglib.optserv.trimfunction (ref double f, ref double[] g, int n, double threshold) inline static
Referenced by alglib.mincg.mincgiteration().
static bool alglib.optserv.enforceboundaryconstraints (ref double[] x, double[] bl, bool[] havebl, double[] bu, bool[] havebu, int nmain, int nslack) inline static
Referenced by alglib.optserv.findfeasiblepoint().
static void alglib.optserv.projectgradientintobc (double[] x, ref double[] g, double[] bl, bool[] havebl, double[] bu, bool[] havebu, int nmain, int nslack) inline static
References alglib.ap.assert().
Referenced by alglib.optserv.findfeasiblepoint().
static void alglib.optserv.calculatestepbound (double[] x, double[] d, double alpha, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack, ref int variabletofreeze, ref double valuetofreeze, ref double maxsteplen) inline static
References alglib.ap.assert(), alglib.math.maxrealnumber, and alglib.apserv.safeminposrv().
Referenced by alglib.optserv.findfeasiblepoint().
static int alglib.optserv.postprocessboundedstep (ref double[] x, double[] xprev, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack, int variabletofreeze, double valuetofreeze, double steptaken, double maxsteplen) inline static
References alglib.ap.assert().
Referenced by alglib.optserv.findfeasiblepoint().
static void alglib.optserv.filterdirection (ref double[] d, double[] x, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, double[] s, int nmain, int nslack, double droptol) inline static
References alglib.ap.assert(), and alglib.math.sqr().
Referenced by alglib.optserv.findfeasiblepoint().
static int alglib.optserv.numberofchangedconstraints (double[] x, double[] xprev, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack) inline static
Referenced by alglib.optserv.findfeasiblepoint().
static bool alglib.optserv.findfeasiblepoint (ref double[] x, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack, double ce[,], int k, double epsi, ref int qpits, ref int gpaits) inline static
References alglib.optserv.calculatestepbound(), alglib.optserv.enforceboundaryconstraints(), alglib.optserv.filterdirection(), alglib.math.machineepsilon, alglib.optserv.numberofchangedconstraints(), alglib.optserv.postprocessboundedstep(), alglib.optserv.projectgradientintobc(), alglib.svd.rmatrixsvd(), alglib.math.sqr(), and alglib.tsort.tagsortbuf().
Referenced by alglib.minbleic.minbleiciteration().
static bool alglib.optserv.derivativecheck (double f0, double df0, double f1, double df1, double f, double df, double width) inline static
Referenced by alglib.minbleic.minbleiciteration(), and alglib.mincg.mincgiteration().
static void alglib.optserv.trimprepare (double f, ref double threshold) inline static
static void alglib.optserv.trimfunction (ref double f, ref double[] g, int n, double threshold) inline static
static bool alglib.optserv.enforceboundaryconstraints (ref double[] x, double[] bl, bool[] havebl, double[] bu, bool[] havebu, int nmain, int nslack) inline static
static void alglib.optserv.projectgradientintobc (double[] x, ref double[] g, double[] bl, bool[] havebl, double[] bu, bool[] havebu, int nmain, int nslack) inline static
References alglib.ap.assert().
static void alglib.optserv.calculatestepbound (double[] x, double[] d, double alpha, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack, ref int variabletofreeze, ref double valuetofreeze, ref double maxsteplen) inline static
References alglib.ap.assert(), alglib.math.maxrealnumber, and alglib.apserv.safeminposrv().
static int alglib.optserv.postprocessboundedstep (ref double[] x, double[] xprev, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack, int variabletofreeze, double valuetofreeze, double steptaken, double maxsteplen) inline static
References alglib.ap.assert().
static void alglib.optserv.filterdirection (ref double[] d, double[] x, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, double[] s, int nmain, int nslack, double droptol) inline static
References alglib.ap.assert(), and alglib.math.sqr().
static int alglib.optserv.numberofchangedconstraints (double[] x, double[] xprev, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack) inline static
static bool alglib.optserv.findfeasiblepoint (ref double[] x, double[] bndl, bool[] havebndl, double[] bndu, bool[] havebndu, int nmain, int nslack, double ce[,], int k, double epsi, ref int qpits, ref int gpaits) inline static
References alglib.optserv.calculatestepbound(), alglib.optserv.enforceboundaryconstraints(), alglib.optserv.filterdirection(), alglib.math.machineepsilon, alglib.optserv.numberofchangedconstraints(), alglib.optserv.postprocessboundedstep(), alglib.optserv.projectgradientintobc(), alglib.svd.rmatrixsvd(), alglib.math.sqr(), and alglib.tsort.tagsortbuf().
static bool alglib.optserv.derivativecheck (double f0, double df0, double f1, double df1, double f, double df, double width) inline static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/optimization.cs