IGLib: IG.MPetekLib.Application.Scripts.LinearOscillator._09SingleResonanceCurvePlot Class Reference
IG.MPetekLib.Application.Scripts.LinearOscillator._09SingleResonanceCurvePlot Class Reference
Primerjam numerično rešitev z analitično.
Static Public Member Functions
static void Run (string[] arguments)
Performs a driven oscillations test and plots the results.
Detailed Description
Primerjam numerično rešitev z analitično.
Member Function Documentation
static void IG.MPetekLib.Application.Scripts.LinearOscillator._09SingleResonanceCurvePlot.Run (string[] arguments) inline static
Performs a driven oscillations test and plots the results.
Plotting is performed in the main thread.
References IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.AngularFrequencySquare, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.CalcAnalyticalAmplitudeVsDrivingFrequnecy(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.CalcSteadyStateAmplitudeVsDrivingFrequency(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.DampingCoefficient, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.DomainDensityMultiplier, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.EndingDrivingAngularFrequency, IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.NewCurveFromPlottableData(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.NSamplesForResonanceCurve, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.Solver, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.StartingDrivingAngularFrequency, and IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.StepSize.
Referenced by IG.Script.AppMarkoPetek.App09SingleResonanceCurvePlot().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/application/scripts/LinearOscillator/09SingleResonanceCurvePlot.cs