IGLib: alglib.nleq.nleqreport Class Reference
alglib.nleq.nleqreport Class Reference
Public Member Functions
nleqreport ()
override void init ()
override alglib.apobject make_copy ()
Public Attributes
int iterationscount
int nfunc
int njac
int terminationtype
Constructor & Destructor Documentation
alglib.nleq.nleqreport.nleqreport () inline
References alglib.nleq.nleqreport.init().
Referenced by alglib.nleq.nleqreport.make_copy().
Member Function Documentation
override void alglib.nleq.nleqreport.init () inline virtual
Implements alglib.apobject.
Referenced by alglib.nleq.nleqreport.nleqreport().
override alglib.apobject alglib.nleq.nleqreport.make_copy () inline virtual
Implements alglib.apobject.
References alglib.nleq.nleqreport.iterationscount, alglib.nleq.nleqreport.nfunc, alglib.nleq.nleqreport.njac, alglib.nleq.nleqreport.nleqreport(), and alglib.nleq.nleqreport.terminationtype.
Member Data Documentation
int alglib.nleq.nleqreport.iterationscount
Referenced by alglib.nleq.nleqreport.make_copy(), and alglib.nleq.nleqresultsbuf().
int alglib.nleq.nleqreport.nfunc
Referenced by alglib.nleq.nleqreport.make_copy(), and alglib.nleq.nleqresultsbuf().
int alglib.nleq.nleqreport.njac
Referenced by alglib.nleq.nleqreport.make_copy(), and alglib.nleq.nleqresultsbuf().
int alglib.nleq.nleqreport.terminationtype
Referenced by alglib.nleq.nleqreport.make_copy(), and alglib.nleq.nleqresultsbuf().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/solvers.cs