IGLib: alglib.xdebug Class Reference
alglib.xdebug Class Reference
Static Public Member Functions
static int xdebugb1count (bool[] a)
static void xdebugb1not (bool[] a)
static void xdebugb1appendcopy (ref bool[] a)
static void xdebugb1outeven (int n, ref bool[] a)
static int xdebugi1sum (int[] a)
static void xdebugi1neg (int[] a)
static void xdebugi1appendcopy (ref int[] a)
static void xdebugi1outeven (int n, ref int[] a)
static double xdebugr1sum (double[] a)
static void xdebugr1neg (double[] a)
static void xdebugr1appendcopy (ref double[] a)
static void xdebugr1outeven (int n, ref double[] a)
static complex xdebugc1sum (complex[] a)
static void xdebugc1neg (complex[] a)
static void xdebugc1appendcopy (ref complex[] a)
static void xdebugc1outeven (int n, ref complex[] a)
static int xdebugb2count (bool[,] a)
static void xdebugb2not (bool[,] a)
static void xdebugb2transpose (ref bool[,] a)
static void xdebugb2outsin (int m, int n, ref bool[,] a)
static int xdebugi2sum (int[,] a)
static void xdebugi2neg (int[,] a)
static void xdebugi2transpose (ref int[,] a)
static void xdebugi2outsin (int m, int n, ref int[,] a)
static double xdebugr2sum (double[,] a)
static void xdebugr2neg (double[,] a)
static void xdebugr2transpose (ref double[,] a)
static void xdebugr2outsin (int m, int n, ref double[,] a)
static complex xdebugc2sum (complex[,] a)
static void xdebugc2neg (complex[,] a)
static void xdebugc2transpose (ref complex[,] a)
static void xdebugc2outsincos (int m, int n, ref complex[,] a)
static double xdebugmaskedbiasedproductsum (int m, int n, double[,] a, double[,] b, bool[,] c)
Member Function Documentation
static int alglib.xdebug.xdebugb1count (bool[] a) inline static
Referenced by alglib.xdebugb1count().
static void alglib.xdebug.xdebugb1not (bool[] a) inline static
Referenced by alglib.xdebugb1not().
static void alglib.xdebug.xdebugb1appendcopy (ref bool[] a) inline static
Referenced by alglib.xdebugb1appendcopy().
static void alglib.xdebug.xdebugb1outeven (int n, ref bool[] a) inline static
Referenced by alglib.xdebugb1outeven().
static int alglib.xdebug.xdebugi1sum (int[] a) inline static
Referenced by alglib.xdebugi1sum().
static void alglib.xdebug.xdebugi1neg (int[] a) inline static
Referenced by alglib.xdebugi1neg().
static void alglib.xdebug.xdebugi1appendcopy (ref int[] a) inline static
Referenced by alglib.xdebugi1appendcopy().
static void alglib.xdebug.xdebugi1outeven (int n, ref int[] a) inline static
Referenced by alglib.xdebugi1outeven().
static double alglib.xdebug.xdebugr1sum (double[] a) inline static
Referenced by alglib.xdebugr1sum().
static void alglib.xdebug.xdebugr1neg (double[] a) inline static
Referenced by alglib.xdebugr1neg().
static void alglib.xdebug.xdebugr1appendcopy (ref double[] a) inline static
Referenced by alglib.xdebugr1appendcopy().
static void alglib.xdebug.xdebugr1outeven (int n, ref double[] a) inline static
Referenced by alglib.xdebugr1outeven().
static complex alglib.xdebug.xdebugc1sum (complex[] a) inline static
Referenced by alglib.xdebugc1sum().
static void alglib.xdebug.xdebugc1neg (complex[] a) inline static
Referenced by alglib.xdebugc1neg().
static void alglib.xdebug.xdebugc1appendcopy (ref complex[] a) inline static
Referenced by alglib.xdebugc1appendcopy().
static void alglib.xdebug.xdebugc1outeven (int n, ref complex[] a) inline static
References alglib.complex.x.
Referenced by alglib.xdebugc1outeven().
static int alglib.xdebug.xdebugb2count (bool a[,]) inline static
Referenced by alglib.xdebugb2count().
static void alglib.xdebug.xdebugb2not (bool a[,]) inline static
Referenced by alglib.xdebugb2not().
static void alglib.xdebug.xdebugb2transpose (ref bool a[,]) inline static
Referenced by alglib.xdebugb2transpose().
static void alglib.xdebug.xdebugb2outsin (int m, int n, ref bool a[,]) inline static
Referenced by alglib.xdebugb2outsin().
static int alglib.xdebug.xdebugi2sum (int a[,]) inline static
Referenced by alglib.xdebugi2sum().
static void alglib.xdebug.xdebugi2neg (int a[,]) inline static
Referenced by alglib.xdebugi2neg().
static void alglib.xdebug.xdebugi2transpose (ref int a[,]) inline static
Referenced by alglib.xdebugi2transpose().
static void alglib.xdebug.xdebugi2outsin (int m, int n, ref int a[,]) inline static
Referenced by alglib.xdebugi2outsin().
static double alglib.xdebug.xdebugr2sum (double a[,]) inline static
Referenced by alglib.xdebugr2sum().
static void alglib.xdebug.xdebugr2neg (double a[,]) inline static
Referenced by alglib.xdebugr2neg().
static void alglib.xdebug.xdebugr2transpose (ref double a[,]) inline static
Referenced by alglib.xdebugr2transpose().
static void alglib.xdebug.xdebugr2outsin (int m, int n, ref double a[,]) inline static
Referenced by alglib.xdebugr2outsin().
static complex alglib.xdebug.xdebugc2sum (complex a[,]) inline static
Referenced by alglib.xdebugc2sum().
static void alglib.xdebug.xdebugc2neg (complex a[,]) inline static
Referenced by alglib.xdebugc2neg().
static void alglib.xdebug.xdebugc2transpose (ref complex a[,]) inline static
Referenced by alglib.xdebugc2transpose().
static void alglib.xdebug.xdebugc2outsincos (int m, int n, ref complex a[,]) inline static
Referenced by alglib.xdebugc2outsincos().
static double alglib.xdebug.xdebugmaskedbiasedproductsum (int m, int n, double a[,], double b[,], bool c[,]) inline static
References alglib.ap.assert().
Referenced by alglib.xdebugmaskedbiasedproductsum().
The documentation for this class was generated from the following file:
igtest/numerics/alglib_0.8.2/src/alglibmisc.cs