IGLib: NUnit.Engine.ITestEventListener Interface Reference
NUnit.Engine.ITestEventListener Interface Reference
The ITestListener interface is used to receive notices of significant events while a test is running. It's single method accepts an Xml string, which may represent any event generated by the test framework, the driver or any of the runners internal to the engine. Use of Xml means that any driver and framework may add additional events and the engine will simply pass them on through this interface.
Public Member Functions
void OnTestEvent (string report)
Handle a progress report or other event.
Detailed Description
The ITestListener interface is used to receive notices of significant events while a test is running. It's single method accepts an Xml string, which may represent any event generated by the test framework, the driver or any of the runners internal to the engine. Use of Xml means that any driver and framework may add additional events and the engine will simply pass them on through this interface.
Member Function Documentation
void NUnit.Engine.ITestEventListener.OnTestEvent (string report)
Handle a progress report or other event.
Parameters
report An XML progress report.
Implemented in NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.NullListener, NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.NullListener, NUnit.ConsoleRunner.TestEventHandler, and NUnit.Engine.RunTestsCallbackHandler.NullListener.
Referenced by NUnit.Engine.Drivers.TestEventAdapter.OnTestFinished(), NUnit.Engine.Drivers.TestEventAdapter.OnTestStarted(), NUnit.Engine.RunTestsCallbackHandler.ReportProgress(), and NUnit.Engine.Runners.MasterTestRunner.RunTests().
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.api/ITestEventListener.cs