IGLib: IGTest.ProgramIGTest Class Reference
IGTest.ProgramIGTest Class Reference
Static Public Attributes
static IReporter _rep = new ReporterConsole()
Properties
static Premisa.ReporterMsg.Reporter R [get]
Reporter for this class.
static IReporter R [get]
Reporter for this class.
Static Private Member Functions
static void Main (string[] args)
static void TestMsgObservationEvent (string MessageFile)
Reads observatin event message from the specified XML file and outputs the contents. File must contian data according to specification of SpecimenOservationEvent. DOES NOT convert the object back to XML!!!
static void TestMsgObservationEvent (string MessageFilename, string ModelFile, string OutputXmlFile, string FindingsFile)
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationEvent.
static void TestMsgObservationEvent (string MessageFilename, string ModelFile, string OutputXmlFile, string FindingsFile, bool SendToCalypso)
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationEvent.
static void TestMsgFinancialTransaction (string MessageFile)
Reads financial transaction message from the specified XML file and outputs the contents. File must contian data according to specification of DetailedFinancialTransaction. DOES NOT convert the object back to XML!!!
static void TestMsgFinancialTransaction (string MessageFilename, string ModelFile, string OutputXmlFile)
Test without sending to Calypso.
static void TestMsgFinancialTransaction (string MessageFilename, string ModelFile, string OutputXmlFile, bool SendToCalypso)
Test of a message read from the specified file and reads its data. Message contained in the file must be of type DetailedFinancialTransaction.
static void TestFindings (string FindingsFile)
Reads findings data from the specified XML file and outputs the contents. File must contian data according to specification of Findings. DOES NOT convert the object back to XML!!!
static void TestFindings (string FindingsFile, string OutputXmlFile, bool CreateXmlInputFormat)
Reads findings data from the specified XML file and outputs the contents, then writes data back to XML. File must contian data according to specification of Findings.
static void ReceiveSpecimenObservationOrder (bool TakeFromQueue)
Testing of receiving SpecimenObservationOrder:
static void TestMsgObservationOrder (string MessageFilename)
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationOrder
static void TestMsgObservationOrderNullify (string MessageFilename, string OutputXmlFile)
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationOrder
static void TestMsgObservationOrderNullifySend (string MessageFilename, string MessageId)
Sends the nullification request for the specified Observation order message.
static void TestcalypsoWsSimple ()
Simple test of web service, just receives an Id and a message.
static void TestCalypsoWs ()
Gets the specific test from the Calypso web service.
static void TestW3cWs ()
This tests a simple web service from W3C in order to check the outwards connection.
static void TestNumberConverter ()
Tests conversion form Arabic to Roman numbers and conversely.
static void Main (string[] args)
static void TestMsgObservationEvent (string MessageFile)
Reads observatin event message from the specified XML file and outputs the contents. File must contian data according to specification of SpecimenOservationEvent. DOES NOT convert the object back to XML!!!
static void TestMsgObservationEvent (string MessageFilename, string ModelFile, string OutputXmlFile, string FindingsFile)
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationEvent.
static void TestMsgObservationEvent (string MessageFilename, string ModelFile, string OutputXmlFile, string FindingsFile, bool SendToCalypso)
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationEvent.
static void TestMsgFinancialTransaction (string MessageFile)
Reads financial transaction message from the specified XML file and outputs the contents. File must contian data according to specification of DetailedFinancialTransaction. DOES NOT convert the object back to XML!!!
static void TestMsgFinancialTransaction (string MessageFilename, string ModelFile, string OutputXmlFile)
Test without sending to Calypso.
static void TestMsgFinancialTransaction (string MessageFilename, string ModelFile, string OutputXmlFile, bool SendToCalypso)
Test of a message read from the specified file and reads its data. Message contained in the file must be of type DetailedFinancialTransaction.
static void TestFindings (string FindingsFile)
Reads findings data from the specified XML file and outputs the contents. File must contian data according to specification of Findings. DOES NOT convert the object back to XML!!!
static void TestFindings (string FindingsFile, string OutputXmlFile, bool CreateXmlInputFormat)
Reads findings data from the specified XML file and outputs the contents, then writes data back to XML. File must contian data according to specification of Findings.
static void ReceiveSpecimenObservationOrder (bool TakeFromQueue)
Testing of receiving SpecimenObservationOrder:
static void TestMsgObservationOrder (string MessageFilename)
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationOrder
static void TestMsgObservationOrderNullify (string MessageFilename, string OutputXmlFile)
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationOrder
static void TestMsgObservationOrderNullifySend (string MessageFilename, string MessageId)
Sends the nullification request for the specified Observation order message.
static void TestcalypsoWsSimple ()
Simple test of web service, just receives an Id and a message.
static void TestCalypsoWs ()
Gets the specific test from the Calypso web service.
Member Function Documentation
static void IGTest.ProgramIGTest.Main (string[] args) inline static private
References IGTest.ProgramIGTest.R, IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), IGTest.ProgramIGTest.TestCalypsoWs(), IGTest.ProgramIGTest.TestcalypsoWsSimple(), IGTest.ProgramIGTest.TestMsgFinancialTransaction(), IGTest.ProgramIGTest.TestMsgObservationEvent(), IGTest.ProgramIGTest.TestMsgObservationOrder(), IGTest.ProgramIGTest.TestMsgObservationOrderNullify(), and IGTest.ProgramIGTest.TestMsgObservationOrderNullifySend().
static void IGTest.ProgramIGTest.TestMsgObservationEvent (string MessageFile) inline static private
Reads observatin event message from the specified XML file and outputs the contents. File must contian data according to specification of SpecimenOservationEvent. DOES NOT convert the object back to XML!!!
Parameters
MessageFile Name of the file containing the message.
Referenced by IGTest.ProgramIGTest.Main(), and IGTest.ProgramIGTest.TestMsgObservationEvent().
static void IGTest.ProgramIGTest.TestMsgObservationEvent (string MessageFilename, string ModelFile, string OutputXmlFile, string FindingsFile) inline static private
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationEvent.
Parameters
MessageFilename Name of the file containing the message. If not specified then name is obtained from application settings.
ModelFile Name of the file that is used as a model for message construction. Its specification is obligatory when object is converted to XML.
OutputXmlFile Name of the file to which XML representation of the object is written after object contents is read (interpreted).
FindingsFile Name of the file that contains findings to be included in the message. If not specified then findings are just transcribed from the XML file.
References IGTest.ProgramIGTest.TestMsgObservationEvent().
static void IGTest.ProgramIGTest.TestMsgObservationEvent (string MessageFilename, string ModelFile, string OutputXmlFile, string FindingsFile, bool SendToCalypso) inline static private
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationEvent.
Parameters
MessageFilename Name of the file containing the message. If not specified then name is obtained from application settings.
ModelFile Name of the file that is used as a model for message construction. Its specification is obligatory when object is converted to XML.
OutputXmlFile Name of the file to which XML representation of the object is written after object contents is read (interpreted).
FindingsFile Name of the file that contains findings to be included in the message. If not specified then findings are just transcribed from the XML file.
References LabexBis.BisCommunicationSettings.ExampleFile(), LabexBis.Calypso.Global, IGTest.ProgramIGTest.R, LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), LabexBis.Calypso.SendMessageToBis(), LabexBis.Calypso.Settings, and LabexBis.BisCommunicationSettings.ToString().
static void IGTest.ProgramIGTest.TestMsgFinancialTransaction (string MessageFile) inline static private
Reads financial transaction message from the specified XML file and outputs the contents. File must contian data according to specification of DetailedFinancialTransaction. DOES NOT convert the object back to XML!!!
Parameters
MessageFile Name of the file containing the message.
Referenced by IGTest.ProgramIGTest.Main(), and IGTest.ProgramIGTest.TestMsgFinancialTransaction().
static void IGTest.ProgramIGTest.TestMsgFinancialTransaction (string MessageFilename, string ModelFile, string OutputXmlFile) inline static private
Test without sending to Calypso.
References IGTest.ProgramIGTest.TestMsgFinancialTransaction().
static void IGTest.ProgramIGTest.TestMsgFinancialTransaction (string MessageFilename, string ModelFile, string OutputXmlFile, bool SendToCalypso) inline static private
Test of a message read from the specified file and reads its data. Message contained in the file must be of type DetailedFinancialTransaction.
Parameters
MessageFilename Name of the file containing the message. If not specified then name is obtained from application settings.
ModelFile Name of the file that is used as a model for message construction. Its specification is obligatory when object is converted to XML.
OutputXmlFile Name of the file to which XML representation of the object is written after object contents is read (interpreted).
References LabexBis.BisCommunicationSettings.ExampleFile(), LabexBis.Calypso.Global, IGTest.ProgramIGTest.R, LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), LabexBis.Calypso.SendMessageToBis(), LabexBis.Calypso.Settings, and LabexBis.BisCommunicationSettings.ToString().
static void IGTest.ProgramIGTest.TestFindings (string FindingsFile) inline static private
Reads findings data from the specified XML file and outputs the contents. File must contian data according to specification of Findings. DOES NOT convert the object back to XML!!!
Parameters
MessageFile Name of the file containing the message.
Referenced by IGTest.ProgramIGTest.TestFindings().
static void IGTest.ProgramIGTest.TestFindings (string FindingsFile, string OutputXmlFile, bool CreateXmlInputFormat) inline static private
Reads findings data from the specified XML file and outputs the contents, then writes data back to XML. File must contian data according to specification of Findings.
Parameters
MessageFile Name of the file containing the message.
OutputXmlFile Name of the file to wghich Xml is saved.
CreateXmlInputFormat If true then XML is created in iput format when created from data.
References IGTest.ProgramIGTest.R.
static void IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder (bool TakeFromQueue) inline static private
Testing of receiving SpecimenObservationOrder:
Parameters
TakeFromQueue Indicates whether the received message should be taken from the queue if everything is OK.
References LabexBis.Calypso.ConfirmMessageReceipt(), LabexBis.Calypso.GetMessage(), LabexBis.Calypso.Global, IGTest.ProgramIGTest.R, LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), LabexBis.Calypso.SaveIncomingMessage(), LabexBis.Calypso.Settings, and LabexBis.BisCommunicationSettings.ToString().
Referenced by IGTest.ProgramIGTest.Main().
static void IGTest.ProgramIGTest.TestMsgObservationOrder (string MessageFilename) inline static private
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationOrder
Parameters
MessageFilename Name of the file containing the message. If not specified then name is obtained from application settings.
References LabexBis.BisCommunicationSettings.ExampleFile(), LabexBis.Calypso.Global, LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), and LabexBis.Calypso.Settings.
Referenced by IGTest.ProgramIGTest.Main().
static void IGTest.ProgramIGTest.TestMsgObservationOrderNullify (string MessageFilename, string OutputXmlFile) inline static private
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationOrder
Parameters
MessageFilename Name of the file containing the message.
OutputXmlFile Name of the file containing the message. If not specified then name is obtained from application settings.
References LabexBis.BisCommunicationSettings.ExampleFile(), LabexBis.Calypso.Global, LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), and LabexBis.Calypso.Settings.
Referenced by IGTest.ProgramIGTest.Main().
static void IGTest.ProgramIGTest.TestMsgObservationOrderNullifySend (string MessageFilename, string MessageId) inline static private
Sends the nullification request for the specified Observation order message.
Parameters
MessageFilename Name of the file that contains the message.
MessageId Id of the message.
References LabexBis.Calypso.Global, IGTest.ProgramIGTest.R, LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), LabexBis.Calypso.SendOoNullifyToBis(), and LabexBis.Calypso.Settings.
Referenced by IGTest.ProgramIGTest.Main().
static void IGTest.ProgramIGTest.TestcalypsoWsSimple () inline static private
Simple test of web service, just receives an Id and a message.
References LabexBis.Calypso.GetMessage(), LabexBis.Calypso.GetUniqueID(), LabexBis.Calypso.Global, LabexBis.BisCommunicationSettings.IncomingFileName(), IGTest.ProgramIGTest.R, LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), LabexBis.Calypso.Settings, and LabexBis.BisCommunicationSettings.ToString().
Referenced by IGTest.ProgramIGTest.Main().
static void IGTest.ProgramIGTest.TestCalypsoWs () inline static private
Gets the specific test from the Calypso web service.
References LabexBis.Calypso.GetMessage(), LabexBis.Calypso.Global, LabexBis.BisCommunicationSettings.MessageFile, IGTest.ProgramIGTest.R, LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), LabexBis.Calypso.SendMessageToMyself(), LabexBis.Calypso.Settings, LabexBis.Calypso.TestWs(), and LabexBis.BisCommunicationSettings.ToString().
Referenced by IGTest.ProgramIGTest.Main().
static void IGTest.ProgramIGTest.TestW3cWs () inline static private
This tests a simple web service from W3C in order to check the outwards connection.
References IGTest.TestWebReference.TempConvert.Url.
static void IGTest.ProgramIGTest.TestNumberConverter () inline static private
Tests conversion form Arabic to Roman numbers and conversely.
static void IGTest.ProgramIGTest.Main (string[] args) inline static private
References IGTest.ProgramIGTest.R, IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), IGTest.ProgramIGTest.TestCalypsoWs(), IGTest.ProgramIGTest.TestcalypsoWsSimple(), IGTest.ProgramIGTest.TestMsgFinancialTransaction(), IGTest.ProgramIGTest.TestMsgObservationEvent(), IGTest.ProgramIGTest.TestMsgObservationOrder(), IGTest.ProgramIGTest.TestMsgObservationOrderNullify(), and IGTest.ProgramIGTest.TestMsgObservationOrderNullifySend().
static void IGTest.ProgramIGTest.TestMsgObservationEvent (string MessageFile) inline static private
Reads observatin event message from the specified XML file and outputs the contents. File must contian data according to specification of SpecimenOservationEvent. DOES NOT convert the object back to XML!!!
Parameters
MessageFile Name of the file containing the message.
References IGTest.ProgramIGTest.TestMsgObservationEvent().
static void IGTest.ProgramIGTest.TestMsgObservationEvent (string MessageFilename, string ModelFile, string OutputXmlFile, string FindingsFile) inline static private
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationEvent.
Parameters
MessageFilename Name of the file containing the message. If not specified then name is obtained from application settings.
ModelFile Name of the file that is used as a model for message construction. Its specification is obligatory when object is converted to XML.
OutputXmlFile Name of the file to which XML representation of the object is written after object contents is read (interpreted).
FindingsFile Name of the file that contains findings to be included in the message. If not specified then findings are just transcribed from the XML file.
References IGTest.ProgramIGTest.TestMsgObservationEvent().
static void IGTest.ProgramIGTest.TestMsgObservationEvent (string MessageFilename, string ModelFile, string OutputXmlFile, string FindingsFile, bool SendToCalypso) inline static private
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationEvent.
Parameters
MessageFilename Name of the file containing the message. If not specified then name is obtained from application settings.
ModelFile Name of the file that is used as a model for message construction. Its specification is obligatory when object is converted to XML.
OutputXmlFile Name of the file to which XML representation of the object is written after object contents is read (interpreted).
FindingsFile Name of the file that contains findings to be included in the message. If not specified then findings are just transcribed from the XML file.
References IG.Lib.ParsableXmlObject.Doc, LabexBis.BisCommunicationSettings.ExampleFile(), LabexBis.Calypso.Global, IG.Lib.ParsableXmlObject.Load(), IG.Lib.MsgObservationEvent.LoadFindings(), IG.Lib.MsgBase.MessageNumber, IGTest.ProgramIGTest.R, IG.Lib.MsgObservationEvent.Read(), LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), IG.Lib.ParsableXmlObject.Save(), LabexBis.Calypso.SendMessageToBis(), IG.Lib.MsgBaseWithModel.SetModelFile(), IG.Lib.MsgBase.SetSenderLabex(), LabexBis.Calypso.Settings, LabexBis.BisCommunicationSettings.ToString(), IG.Lib.MsgObservationEvent.ToXml(), and IG.Lib.ParsableXmlObject.WriteToConsole().
static void IGTest.ProgramIGTest.TestMsgFinancialTransaction (string MessageFile) inline static private
Reads financial transaction message from the specified XML file and outputs the contents. File must contian data according to specification of DetailedFinancialTransaction. DOES NOT convert the object back to XML!!!
Parameters
MessageFile Name of the file containing the message.
References IGTest.ProgramIGTest.TestMsgFinancialTransaction().
static void IGTest.ProgramIGTest.TestMsgFinancialTransaction (string MessageFilename, string ModelFile, string OutputXmlFile) inline static private
Test without sending to Calypso.
References IGTest.ProgramIGTest.TestMsgFinancialTransaction().
static void IGTest.ProgramIGTest.TestMsgFinancialTransaction (string MessageFilename, string ModelFile, string OutputXmlFile, bool SendToCalypso) inline static private
Test of a message read from the specified file and reads its data. Message contained in the file must be of type DetailedFinancialTransaction.
Parameters
MessageFilename Name of the file containing the message. If not specified then name is obtained from application settings.
ModelFile Name of the file that is used as a model for message construction. Its specification is obligatory when object is converted to XML.
OutputXmlFile Name of the file to which XML representation of the object is written after object contents is read (interpreted).
References IG.Lib.ParsableXmlObject.Doc, LabexBis.BisCommunicationSettings.ExampleFile(), LabexBis.Calypso.Global, IG.Lib.ParsableXmlObject.Load(), IG.Lib.MsgBase.MessageNumber, IGTest.ProgramIGTest.R, IG.Lib.MsgFinancialTransaction.Read(), LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), IG.Lib.ParsableXmlObject.Save(), LabexBis.Calypso.SendMessageToBis(), IG.Lib.MsgBaseWithModel.SetModelFile(), IG.Lib.MsgBase.SetSenderLabex(), LabexBis.Calypso.Settings, LabexBis.BisCommunicationSettings.ToString(), IG.Lib.MsgFinancialTransaction.ToXml(), and IG.Lib.ParsableXmlObject.WriteToConsole().
static void IGTest.ProgramIGTest.TestFindings (string FindingsFile) inline static private
Reads findings data from the specified XML file and outputs the contents. File must contian data according to specification of Findings. DOES NOT convert the object back to XML!!!
Parameters
MessageFile Name of the file containing the message.
References IGTest.ProgramIGTest.TestFindings().
static void IGTest.ProgramIGTest.TestFindings (string FindingsFile, string OutputXmlFile, bool CreateXmlInputFormat) inline static private
Reads findings data from the specified XML file and outputs the contents, then writes data back to XML. File must contian data according to specification of Findings.
Parameters
MessageFile Name of the file containing the message.
OutputXmlFile Name of the file to wghich Xml is saved.
CreateXmlInputFormat If true then XML is created in iput format when created from data.
References IG.Lib.ParsableXmlObject.Doc, IG.Lib.ParsableXmlObject.Load(), IGTest.ProgramIGTest.R, IG.Lib.DocFindings.Read(), IG.Lib.ParsableXmlObject.Save(), IG.Lib.DocFindings.ToXml(), IG.Lib.ParsableXmlObject.WriteToConsole(), and IG.Lib.DocFindings.XmlCreateInputFormat.
static void IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder (bool TakeFromQueue) inline static private
Testing of receiving SpecimenObservationOrder:
Parameters
TakeFromQueue Indicates whether the received message should be taken from the queue if everything is OK.
References LabexBis.Calypso.ConfirmMessageReceipt(), IG.Lib.MsgObervationOrder.GetBisOrderId(), LabexBis.Calypso.GetMessage(), LabexBis.Calypso.Global, IG.Lib.ParsableXmlObject.LoadXml(), IG.Lib.MsgBase.MessageId, IG.Lib.MsgBase.MessageXml, IGTest.ProgramIGTest.R, IG.Lib.ParsableXmlObject.Read(), LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), LabexBis.Calypso.SaveIncomingMessage(), LabexBis.Calypso.Settings, LabexBis.BisCommunicationSettings.ToString(), IG.Lib.MsgBase.Type, and IG.Lib.ParsableXmlObject.WriteToConsole().
static void IGTest.ProgramIGTest.TestMsgObservationOrder (string MessageFilename) inline static private
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationOrder
Parameters
MessageFilename Name of the file containing the message. If not specified then name is obtained from application settings.
References LabexBis.BisCommunicationSettings.ExampleFile(), LabexBis.Calypso.Global, IG.Lib.ParsableXmlObject.Load(), IG.Lib.MsgObervationOrder.Read(), LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), LabexBis.Calypso.Settings, and IG.Lib.ParsableXmlObject.WriteToConsole().
static void IGTest.ProgramIGTest.TestMsgObservationOrderNullify (string MessageFilename, string OutputXmlFile) inline static private
Test of a message read from the specified file and reads its data. Message contained in the file must be of type SpecimenObservationOrder
Parameters
MessageFilename Name of the file containing the message.
OutputXmlFile Name of the file containing the message. If not specified then name is obtained from application settings.
References IG.Lib.ParsableXmlObject.Doc, LabexBis.BisCommunicationSettings.ExampleFile(), LabexBis.Calypso.Global, IG.Lib.ParsableXmlObject.Load(), IG.Lib.MsgObervationOrder.PrepareOoNullify(), IG.Lib.MsgObervationOrder.Read(), LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), LabexBis.Calypso.Settings, and IG.Lib.ParsableXmlObject.WriteToConsole().
static void IGTest.ProgramIGTest.TestMsgObservationOrderNullifySend (string MessageFilename, string MessageId) inline static private
Sends the nullification request for the specified Observation order message.
Parameters
MessageFilename Name of the file that contains the message.
MessageId Id of the message.
References LabexBis.Calypso.Global, IG.Lib.ParsableXmlObject.Load(), IG.Lib.MsgBase.MessageId, IGTest.ProgramIGTest.R, LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), LabexBis.Calypso.SendOoNullifyToBis(), and LabexBis.Calypso.Settings.
static void IGTest.ProgramIGTest.TestcalypsoWsSimple () inline static private
Simple test of web service, just receives an Id and a message.
References LabexBis.Calypso.GetMessage(), LabexBis.Calypso.GetUniqueID(), LabexBis.Calypso.Global, LabexBis.BisCommunicationSettings.IncomingFileName(), IGTest.ProgramIGTest.R, LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), LabexBis.Calypso.Settings, and LabexBis.BisCommunicationSettings.ToString().
static void IGTest.ProgramIGTest.TestCalypsoWs () inline static private
Gets the specific test from the Calypso web service.
References LabexBis.Calypso.GetMessage(), LabexBis.Calypso.Global, IG.Lib.ParsableXmlObject.LoadXml(), LabexBis.BisCommunicationSettings.MessageFile, IGTest.ProgramIGTest.R, IG.Lib.MsgObervationOrder.Read(), LabexBis.BisCommunicationSettings.ReadSettingsAppConfig(), LabexBis.Calypso.SendMessageToMyself(), LabexBis.Calypso.Settings, LabexBis.Calypso.TestWs(), LabexBis.BisCommunicationSettings.ToString(), IG.Lib.MsgBase.Type, and IG.Lib.ParsableXmlObject.WriteToConsole().
Member Data Documentation
IReporter IGTest.ProgramIGTest._rep = new ReporterConsole() static
Property Documentation
Premisa.ReporterMsg.Reporter IGTest.ProgramIGTest.R static get
Reporter for this class.
Referenced by IGTest.ProgramIGTest.Main(), IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), IGTest.ProgramIGTest.TestCalypsoWs(), IGTest.ProgramIGTest.TestcalypsoWsSimple(), IGTest.ProgramIGTest.TestFindings(), IGTest.ProgramIGTest.TestMsgFinancialTransaction(), IGTest.ProgramIGTest.TestMsgObservationEvent(), and IGTest.ProgramIGTest.TestMsgObservationOrderNullifySend().
IReporter IGTest.ProgramIGTest.R static get
Reporter for this class.
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/IGTest/Program_igt.cs