IGLib: alglib.testratintunit Class Reference
alglib.testratintunit Class Reference
Static Public Member Functions
static bool testratint (bool silent)
static bool testratint (bool silent)
static bool _pexec_testratint (bool silent)
Static Private Member Functions
static void poldiff2 (double[] x, double[] f, int n, double t, ref double p, ref double dp, ref double d2p)
static void brcunset (ratint.barycentricinterpolant b)
static bool is1dsolution (int n, double[] y, double[] w, double c)
static void poldiff2 (double[] x, double[] f, int n, double t, ref double p, ref double dp, ref double d2p)
static void brcunset (ratint.barycentricinterpolant b)
static bool is1dsolution (int n, double[] y, double[] w, double c)
Member Function Documentation
static bool alglib.testratintunit.testratint (bool silent) inline static
References alglib.ratint.barycentricbuildfloaterhormann(), alglib.ratint.barycentricbuildxyw(), alglib.ratint.barycentriccalc(), alglib.ratint.barycentriccopy(), alglib.ratint.barycentricdiff1(), alglib.ratint.barycentricdiff2(), alglib.ratint.barycentriclintransx(), alglib.ratint.barycentriclintransy(), alglib.ratint.barycentricunpack(), alglib.testratintunit.brcunset(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.math.minrealnumber, alglib.testratintunit.poldiff2(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testratintunit._pexec_testratint(), and _Test.Main().
static void alglib.testratintunit.poldiff2 (double[] x, double[] f, int n, double t, ref double p, ref double dp, ref double d2p) inline static private
Referenced by alglib.testratintunit.testratint().
static void alglib.testratintunit.brcunset (ratint.barycentricinterpolant b) inline static private
References alglib.ratint.barycentricbuildxyw().
Referenced by alglib.testratintunit.testratint().
static bool alglib.testratintunit.is1dsolution (int n, double[] y, double[] w, double c) inline static private
References alglib.math.sqr().
static bool alglib.testratintunit.testratint (bool silent) inline static
References alglib.ratint.barycentricbuildfloaterhormann(), alglib.ratint.barycentricbuildxyw(), alglib.ratint.barycentriccalc(), alglib.ratint.barycentriccopy(), alglib.ratint.barycentricdiff1(), alglib.ratint.barycentricdiff2(), alglib.ratint.barycentriclintransx(), alglib.ratint.barycentriclintransy(), alglib.ratint.barycentricunpack(), alglib.testratintunit.brcunset(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.math.minrealnumber, alglib.testratintunit.poldiff2(), alglib.math.randominteger(), and alglib.math.randomreal().
static bool alglib.testratintunit._pexec_testratint (bool silent) inline static
References alglib.testratintunit.testratint().
Referenced by _Test.Main().
static void alglib.testratintunit.poldiff2 (double[] x, double[] f, int n, double t, ref double p, ref double dp, ref double d2p) inline static private
static void alglib.testratintunit.brcunset (ratint.barycentricinterpolant b) inline static private
References alglib.ratint.barycentricbuildxyw().
static bool alglib.testratintunit.is1dsolution (int n, double[] y, double[] w, double c) inline static private
References alglib.math.sqr().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs