IGLib: AP1.Mathe Class Reference
AP1.Mathe Class Reference
Static Public Member Functions
static double RandomReal ()
static int RandomInteger (int N)
static double Sqr (double X)
static double AbsComplex (Complex z)
static Complex Conj (Complex z)
static Complex CSqr (Complex z)
Public Attributes
const double MachineEpsilon = 5E-16
const double MaxRealNumber = 1E300
const double MinRealNumber = 1E-300
Static Public Attributes
static System.Random RndObject = new System.Random(System.DateTime.Now.Millisecond)
Member Function Documentation
static double AP1.Mathe.RandomReal () inline static
References AP1.Mathe.RndObject.
Referenced by NumLib.ExampleAlgLib2008.OptimizeRosenbrockOriginal().
static int AP1.Mathe.RandomInteger (int N) inline static
References AP1.Mathe.RndObject.
static double AP1.Mathe.Sqr (double X) inline static
Referenced by AlgLib.lbfgs.mcstep(), NumLib.ExampleAlgLib2008.OptimizeRosenbrock(), and NumLib.ExampleAlgLib2008.OptimizeRosenbrockOriginal().
static double AP1.Mathe.AbsComplex (Complex z) inline static
References AP1.Complex.x, and AP1.Complex.y.
static Complex AP1.Mathe.Conj (Complex z) inline static
References AP1.Complex.x, and AP1.Complex.y.
static Complex AP1.Mathe.CSqr (Complex z) inline static
References AP1.Complex.x, and AP1.Complex.y.
Member Data Documentation
System.Random AP1.Mathe.RndObject = new System.Random(System.DateTime.Now.Millisecond) static
Referenced by AP1.Mathe.RandomInteger(), and AP1.Mathe.RandomReal().
const double AP1.Mathe.MachineEpsilon = 5E-16
const double AP1.Mathe.MaxRealNumber = 1E300
const double AP1.Mathe.MinRealNumber = 1E-300
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/opt/alglib/Alglib_Old_UniMb/AlgLib2008/OriginalCode/ap.cs