IGLib: DotNetMatrix.GeneralMatrix Class Reference
DotNetMatrix.GeneralMatrix Class Reference
.NET GeneralMatrix class.
Public Member Functions
GeneralMatrix (int m, int n)
Construct an m-by-n matrix of zeros.
GeneralMatrix (int m, int n, double s)
Construct an m-by-n constant matrix.
GeneralMatrix (double[][] A)
Construct a matrix from a 2-D array.
GeneralMatrix (double[][] A, int m, int n)
Construct a matrix quickly without checking arguments.
GeneralMatrix (double[] vals, int m)
Construct a matrix from a one-dimensional packed array
virtual GeneralMatrix Copy ()
Make a deep copy of a matrix
virtual double GetElement (int i, int j)
Get a single element.
virtual GeneralMatrix GetMatrix (int i0, int i1, int j0, int j1)
Get a submatrix.
virtual GeneralMatrix GetMatrix (int[] r, int[] c)
Get a submatrix.
virtual GeneralMatrix GetMatrix (int i0, int i1, int[] c)
Get a submatrix.
virtual GeneralMatrix GetMatrix (int[] r, int j0, int j1)
Get a submatrix.
virtual void SetElement (int i, int j, double s)
Set a single element.
virtual void SetMatrix (int i0, int i1, int j0, int j1, GeneralMatrix X)
Set a submatrix.
virtual void SetMatrix (int[] r, int[] c, GeneralMatrix X)
Set a submatrix.
virtual void SetMatrix (int[] r, int j0, int j1, GeneralMatrix X)
Set a submatrix.
virtual void SetMatrix (int i0, int i1, int[] c, GeneralMatrix X)
Set a submatrix.
virtual GeneralMatrix Transpose ()
Matrix transpose.
virtual double Norm1 ()
One norm
virtual double Norm2 ()
Two norm
virtual double NormInf ()
Infinity norm
virtual double NormF ()
Frobenius norm
virtual GeneralMatrix UnaryMinus ()
Unary minus
virtual GeneralMatrix Add (GeneralMatrix B)
C = A + B
virtual GeneralMatrix AddEquals (GeneralMatrix B)
A = A + B
virtual GeneralMatrix Subtract (GeneralMatrix B)
C = A - B
virtual GeneralMatrix SubtractEquals (GeneralMatrix B)
A = A - B
virtual GeneralMatrix ArrayMultiply (GeneralMatrix B)
Element-by-element multiplication, C = A.*B
virtual GeneralMatrix ArrayMultiplyEquals (GeneralMatrix B)
Element-by-element multiplication in place, A = A.*B
virtual GeneralMatrix ArrayRightDivide (GeneralMatrix B)
Element-by-element right division, C = A./B
virtual GeneralMatrix ArrayRightDivideEquals (GeneralMatrix B)
Element-by-element right division in place, A = A./B
virtual GeneralMatrix ArrayLeftDivide (GeneralMatrix B)
Element-by-element left division, C = A.
virtual GeneralMatrix ArrayLeftDivideEquals (GeneralMatrix B)
Element-by-element left division in place, A = A.
virtual GeneralMatrix Multiply (double s)
Multiply a matrix by a scalar, C = s*A
virtual GeneralMatrix MultiplyEquals (double s)
Multiply a matrix by a scalar in place, A = s*A
virtual GeneralMatrix Multiply (GeneralMatrix B)
Linear algebraic matrix multiplication, A * B
virtual LUDecomposition LUD ()
LU Decomposition
virtual QRDecomposition QRD ()
QR Decomposition
virtual CholeskyDecomposition chol ()
Cholesky Decomposition
virtual SingularValueDecomposition SVD ()
Singular Value Decomposition
virtual EigenvalueDecomposition Eigen ()
Eigenvalue Decomposition
virtual GeneralMatrix Solve (GeneralMatrix B)
Solve A*X = B
virtual GeneralMatrix SolveTranspose (GeneralMatrix B)
Solve X*A = B, which is also A'*X' = B'
virtual GeneralMatrix Inverse ()
Matrix inverse or pseudoinverse
virtual double Determinant ()
GeneralMatrix determinant
virtual int Rank ()
GeneralMatrix rank
virtual double Condition ()
Matrix condition (2 norm)
virtual double Trace ()
Matrix trace.
void Dispose ()
Do not make this method virtual. A derived class should not be able to override this method.
System.Object Clone ()
Clone the GeneralMatrix object.
GeneralMatrix (int m, int n)
Construct an m-by-n matrix of zeros.
GeneralMatrix (int m, int n, double s)
Construct an m-by-n constant matrix.
GeneralMatrix (double[][] A)
Construct a matrix from a 2-D array.
GeneralMatrix (double[][] A, int m, int n)
Construct a matrix quickly without checking arguments.
GeneralMatrix (double[] vals, int m)
Construct a matrix from a one-dimensional packed array
virtual GeneralMatrix Copy ()
Make a deep copy of a matrix
virtual double GetElement (int i, int j)
Get a single element.
virtual GeneralMatrix GetMatrix (int i0, int i1, int j0, int j1)
Get a submatrix.
virtual GeneralMatrix GetMatrix (int[] r, int[] c)
Get a submatrix.
virtual GeneralMatrix GetMatrix (int i0, int i1, int[] c)
Get a submatrix.
virtual GeneralMatrix GetMatrix (int[] r, int j0, int j1)
Get a submatrix.
virtual void SetElement (int i, int j, double s)
Set a single element.
virtual void SetMatrix (int i0, int i1, int j0, int j1, GeneralMatrix X)
Set a submatrix.
virtual void SetMatrix (int[] r, int[] c, GeneralMatrix X)
Set a submatrix.
virtual void SetMatrix (int[] r, int j0, int j1, GeneralMatrix X)
Set a submatrix.
virtual void SetMatrix (int i0, int i1, int[] c, GeneralMatrix X)
Set a submatrix.
virtual GeneralMatrix Transpose ()
Matrix transpose.
virtual double Norm1 ()
One norm
virtual double Norm2 ()
Two norm
virtual double NormInf ()
Infinity norm
virtual double NormF ()
Frobenius norm
virtual GeneralMatrix UnaryMinus ()
Unary minus
virtual GeneralMatrix Add (GeneralMatrix B)
C = A + B
virtual GeneralMatrix AddEquals (GeneralMatrix B)
A = A + B
virtual GeneralMatrix Subtract (GeneralMatrix B)
C = A - B
virtual GeneralMatrix SubtractEquals (GeneralMatrix B)
A = A - B
virtual GeneralMatrix ArrayMultiply (GeneralMatrix B)
Element-by-element multiplication, C = A.*B
virtual GeneralMatrix ArrayMultiplyEquals (GeneralMatrix B)
Element-by-element multiplication in place, A = A.*B
virtual GeneralMatrix ArrayRightDivide (GeneralMatrix B)
Element-by-element right division, C = A./B
virtual GeneralMatrix ArrayRightDivideEquals (GeneralMatrix B)
Element-by-element right division in place, A = A./B
virtual GeneralMatrix ArrayLeftDivide (GeneralMatrix B)
Element-by-element left division, C = A.
virtual GeneralMatrix ArrayLeftDivideEquals (GeneralMatrix B)
Element-by-element left division in place, A = A.
virtual GeneralMatrix Multiply (double s)
Multiply a matrix by a scalar, C = s*A
virtual GeneralMatrix MultiplyEquals (double s)
Multiply a matrix by a scalar in place, A = s*A
virtual GeneralMatrix Multiply (GeneralMatrix B)
Linear algebraic matrix multiplication, A * B
virtual LUDecomposition LUD ()
LU Decomposition
virtual QRDecomposition QRD ()
QR Decomposition
virtual CholeskyDecomposition chol ()
Cholesky Decomposition
virtual SingularValueDecomposition SVD ()
Singular Value Decomposition
virtual EigenvalueDecomposition Eigen ()
Eigenvalue Decomposition
virtual GeneralMatrix Solve (GeneralMatrix B)
Solve A*X = B
virtual GeneralMatrix SolveTranspose (GeneralMatrix B)
Solve X*A = B, which is also A'*X' = B'
virtual GeneralMatrix Inverse ()
Matrix inverse or pseudoinverse
virtual double Determinant ()
GeneralMatrix determinant
virtual int Rank ()
GeneralMatrix rank
virtual double Condition ()
Matrix condition (2 norm)
virtual double Trace ()
Matrix trace.
void Dispose ()
Do not make this method virtual. A derived class should not be able to override this method.
System.Object Clone ()
Clone the GeneralMatrix object.
Static Public Member Functions
static GeneralMatrix Create (double[][] A)
Construct a matrix from a copy of a 2-D array.
static GeneralMatrix operator+ (GeneralMatrix m1, GeneralMatrix m2)
Addition of matrices
static GeneralMatrix operator- (GeneralMatrix m1, GeneralMatrix m2)
Subtraction of matrices
static GeneralMatrix operator* (GeneralMatrix m1, GeneralMatrix m2)
Multiplication of matrices
static GeneralMatrix Random (int m, int n)
Generate matrix with random elements
static GeneralMatrix Identity (int m, int n)
Generate identity matrix
static GeneralMatrix Create (double[][] A)
Construct a matrix from a copy of a 2-D array.
static GeneralMatrix operator+ (GeneralMatrix m1, GeneralMatrix m2)
Addition of matrices
static GeneralMatrix operator- (GeneralMatrix m1, GeneralMatrix m2)
Subtraction of matrices
static GeneralMatrix operator* (GeneralMatrix m1, GeneralMatrix m2)
Multiplication of matrices
static GeneralMatrix Random (int m, int n)
Generate matrix with random elements
static GeneralMatrix Identity (int m, int n)
Generate identity matrix
Properties
virtual double[][] Array [get]
Access the internal two-dimensional array.
virtual double[][] ArrayCopy [get]
Copy the internal two-dimensional array.
virtual double[] ColumnPackedCopy [get]
Make a one-dimensional column packed copy of the internal array.
virtual double[] RowPackedCopy [get]
Make a one-dimensional row packed copy of the internal array.
virtual int RowDimension [get]
Get row dimension.
virtual int ColumnDimension [get]
Get column dimension.
Private Member Functions
void CheckMatrixDimensions (GeneralMatrix B)
Check if size(A) == size(B) *
void Dispose (bool disposing)
Dispose(bool disposing) executes in two distinct scenarios. If disposing equals true, the method has been called directly or indirectly by a user's code. Managed and unmanaged resources can be disposed. If disposing equals false, the method has been called by the runtime from inside the finalizer and you should not reference other objects. Only unmanaged resources can be disposed.
~GeneralMatrix ()
This destructor will run only if the Dispose method does not get called. It gives your base class the opportunity to finalize. Do not provide destructors in types derived from this class.
void ISerializable. GetObjectData (SerializationInfo info, StreamingContext context)
A method called when serializing this class
void CheckMatrixDimensions (GeneralMatrix B)
Check if size(A) == size(B) *
void Dispose (bool disposing)
Dispose(bool disposing) executes in two distinct scenarios. If disposing equals true, the method has been called directly or indirectly by a user's code. Managed and unmanaged resources can be disposed. If disposing equals false, the method has been called by the runtime from inside the finalizer and you should not reference other objects. Only unmanaged resources can be disposed.
~GeneralMatrix ()
This destructor will run only if the Dispose method does not get called. It gives your base class the opportunity to finalize. Do not provide destructors in types derived from this class.
void ISerializable. GetObjectData (SerializationInfo info, StreamingContext context)
A method called when serializing this class
Private Attributes
double[][] A
Array for internal storage of elements. internal array storage.
int m
Row and column dimensions. row dimension. column dimension.
int n
Detailed Description
.NET GeneralMatrix class.
The .NET GeneralMatrix Class provides the fundamental operations of numerical linear algebra. Various constructors create Matrices from two dimensional arrays of double precision floating point numbers. Various "gets" and "sets" provide access to submatrices and matrix elements. Several methods implement basic matrix arithmetic, including matrix addition and multiplication, matrix norms, and element-by-element array operations. Methods for reading and printing matrices are also included. All the operations in this version of the GeneralMatrix Class involve real matrices. Complex matrices may be handled in a future version.
Five fundamental matrix decompositions, which consist of pairs or triples of matrices, permutation vectors, and the like, produce results in five decomposition classes. These decompositions are accessed by the GeneralMatrix class to compute solutions of simultaneous linear equations, determinants, inverses and other matrix functions. The five decompositions are:
Cholesky Decomposition of symmetric, positive definite matrices.
LU Decomposition of rectangular matrices.
QR Decomposition of rectangular matrices.
Singular Value Decomposition of rectangular matrices.
Eigenvalue Decomposition of both symmetric and nonsymmetric square matrices.
Example of use:
Solve a linear system A x = b and compute the residual norm, ||b - A x||.
double[][] vals = {{1.,2.,3},{4.,5.,6.},{7.,8.,10.}};
GeneralMatrix A = new GeneralMatrix(vals);
GeneralMatrix b = GeneralMatrix.Random(3,1);
GeneralMatrix x = A.Solve(b);
GeneralMatrix r = A.Multiply(x).Subtract(b);
double rnorm = r.NormInf();
<author> The MathWorks, Inc. and the National Institute of Standards and Technology. </author> <version> 5 August 1998 </version>
Constructor & Destructor Documentation
DotNetMatrix.GeneralMatrix.GeneralMatrix (int m, int n) inline
Construct an m-by-n matrix of zeros.
Parameters
m Number of rows.
n Number of colums.
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.GeneralMatrix.Add(), DotNetMatrix.GeneralMatrix.ArrayLeftDivide(), DotNetMatrix.GeneralMatrix.ArrayMultiply(), DotNetMatrix.GeneralMatrix.ArrayRightDivide(), DotNetMatrix.GeneralMatrix.Copy(), DotNetMatrix.GeneralMatrix.Create(), DotNetMatrix.GeneralMatrix.GetMatrix(), DotNetMatrix.GeneralMatrix.Identity(), DotNetMatrix.GeneralMatrix.Multiply(), DotNetMatrix.GeneralMatrix.Random(), DotNetMatrix.GeneralMatrix.Subtract(), DotNetMatrix.GeneralMatrix.Transpose(), and DotNetMatrix.GeneralMatrix.UnaryMinus().
DotNetMatrix.GeneralMatrix.GeneralMatrix (int m, int n, double s) inline
Construct an m-by-n constant matrix.
Parameters
m Number of rows.
n Number of colums.
s Fill the matrix with this scalar value.
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
DotNetMatrix.GeneralMatrix.GeneralMatrix (double A[][]) inline
Construct a matrix from a 2-D array.
Parameters
A Two-dimensional array of doubles.
Exceptions
System.ArgumentException All rows must have the same length
See also
Create
References DotNetMatrix.GeneralMatrix.A, and DotNetMatrix.GeneralMatrix.m.
DotNetMatrix.GeneralMatrix.GeneralMatrix (double A[][], int m, int n) inline
Construct a matrix quickly without checking arguments.
Parameters
A Two-dimensional array of doubles.
m Number of rows.
n Number of colums.
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
DotNetMatrix.GeneralMatrix.GeneralMatrix (double[] vals, int m) inline
Construct a matrix from a one-dimensional packed array
Parameters
vals One-dimensional array of doubles, packed by columns (ala Fortran).
m Number of rows.
Exceptions
System.ArgumentException Array length must be a multiple of m.
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
DotNetMatrix.GeneralMatrix.~GeneralMatrix () inline private
This destructor will run only if the Dispose method does not get called. It gives your base class the opportunity to finalize. Do not provide destructors in types derived from this class.
References DotNetMatrix.GeneralMatrix.Dispose().
DotNetMatrix.GeneralMatrix.GeneralMatrix (int m, int n) inline
Construct an m-by-n matrix of zeros.
Parameters
m Number of rows.
n Number of colums.
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
DotNetMatrix.GeneralMatrix.GeneralMatrix (int m, int n, double s) inline
Construct an m-by-n constant matrix.
Parameters
m Number of rows.
n Number of colums.
s Fill the matrix with this scalar value.
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
DotNetMatrix.GeneralMatrix.GeneralMatrix (double A[][]) inline
Construct a matrix from a 2-D array.
Parameters
A Two-dimensional array of doubles.
Exceptions
System.ArgumentException All rows must have the same length
See also
Create
References DotNetMatrix.GeneralMatrix.A, and DotNetMatrix.GeneralMatrix.m.
DotNetMatrix.GeneralMatrix.GeneralMatrix (double A[][], int m, int n) inline
Construct a matrix quickly without checking arguments.
Parameters
A Two-dimensional array of doubles.
m Number of rows.
n Number of colums.
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
DotNetMatrix.GeneralMatrix.GeneralMatrix (double[] vals, int m) inline
Construct a matrix from a one-dimensional packed array
Parameters
vals One-dimensional array of doubles, packed by columns (ala Fortran).
m Number of rows.
Exceptions
System.ArgumentException Array length must be a multiple of m.
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
DotNetMatrix.GeneralMatrix.~GeneralMatrix () inline private
This destructor will run only if the Dispose method does not get called. It gives your base class the opportunity to finalize. Do not provide destructors in types derived from this class.
References DotNetMatrix.GeneralMatrix.Dispose().
Member Function Documentation
static GeneralMatrix DotNetMatrix.GeneralMatrix.Create (double A[][]) inline static
Construct a matrix from a copy of a 2-D array.
Parameters
A Two-dimensional array of doubles.
Exceptions
System.ArgumentException All rows must have the same length
References DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Copy () inline virtual
Make a deep copy of a matrix
References DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.GeneralMatrix.Clone(), and DotNetMatrix.test.TestMatrix.Main().
virtual double DotNetMatrix.GeneralMatrix.GetElement (int i, int j) inline virtual
Get a single element.
Parameters
i Row index.
j Column index.
Returns
A(i,j)
Exceptions
System.IndexOutOfRangeException
Referenced by DotNetMatrix.examples.MagicSquareExample.magic(), DotNetMatrix.test.TestMatrix.Main(), and DotNetMatrix.GeneralMatrix.SetMatrix().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.GetMatrix (int i0, int i1, int j0, int j1) inline virtual
Get a submatrix.
Parameters
i0 Initial row index
i1 Final row index
j0 Initial column index
j1 Final column index
Returns
A(i0:i1,j0:j1)
Exceptions
System.IndexOutOfRangeException Submatrix indices
References DotNetMatrix.GeneralMatrix.Array, and DotNetMatrix.GeneralMatrix.GeneralMatrix().
Referenced by DotNetMatrix.test.TestMatrix.Main(), DotNetMatrix.examples.MagicSquareExample.Main(), DotNetMatrix.QRDecomposition.Solve(), and DotNetMatrix.LUDecomposition.Solve().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.GetMatrix (int[] r, int[] c) inline virtual
Get a submatrix.
Parameters
r Array of row indices.
c Array of column indices.
Returns
A(r(:),c(:))
Exceptions
System.IndexOutOfRangeException Submatrix indices
References DotNetMatrix.GeneralMatrix.Array, and DotNetMatrix.GeneralMatrix.GeneralMatrix().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.GetMatrix (int i0, int i1, int[] c) inline virtual
Get a submatrix.
Parameters
i0 Initial row index
i1 Final row index
c Array of column indices.
Returns
A(i0:i1,c(:))
Exceptions
System.IndexOutOfRangeException Submatrix indices
References DotNetMatrix.GeneralMatrix.Array, and DotNetMatrix.GeneralMatrix.GeneralMatrix().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.GetMatrix (int[] r, int j0, int j1) inline virtual
Get a submatrix.
Parameters
r Array of row indices.
j0 Initial column index
j1 Final column index
Returns
A(r(:),j0:j1)
Exceptions
System.IndexOutOfRangeException Submatrix indices
References DotNetMatrix.GeneralMatrix.Array, and DotNetMatrix.GeneralMatrix.GeneralMatrix().
virtual void DotNetMatrix.GeneralMatrix.SetElement (int i, int j, double s) inline virtual
Set a single element.
Parameters
i Row index.
j Column index.
s A(i,j).
Exceptions
System.IndexOutOfRangeException
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual void DotNetMatrix.GeneralMatrix.SetMatrix (int i0, int i1, int j0, int j1, GeneralMatrix X) inline virtual
Set a submatrix.
Parameters
i0 Initial row index
i1 Final row index
j0 Initial column index
j1 Final column index
X A(i0:i1,j0:j1)
Exceptions
System.IndexOutOfRangeException Submatrix indices
References DotNetMatrix.GeneralMatrix.GetElement().
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual void DotNetMatrix.GeneralMatrix.SetMatrix (int[] r, int[] c, GeneralMatrix X) inline virtual
Set a submatrix.
Parameters
r Array of row indices.
c Array of column indices.
X A(r(:),c(:))
Exceptions
System.IndexOutOfRangeException Submatrix indices
References DotNetMatrix.GeneralMatrix.GetElement().
virtual void DotNetMatrix.GeneralMatrix.SetMatrix (int[] r, int j0, int j1, GeneralMatrix X) inline virtual
Set a submatrix.
Parameters
r Array of row indices.
j0 Initial column index
j1 Final column index
X A(r(:),j0:j1)
Exceptions
System.IndexOutOfRangeException Submatrix indices
References DotNetMatrix.GeneralMatrix.GetElement().
virtual void DotNetMatrix.GeneralMatrix.SetMatrix (int i0, int i1, int[] c, GeneralMatrix X) inline virtual
Set a submatrix.
Parameters
i0 Initial row index
i1 Final row index
c Array of column indices.
X A(i0:i1,c(:))
Exceptions
System.IndexOutOfRangeException Submatrix indices
References DotNetMatrix.GeneralMatrix.GetElement().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Transpose () inline virtual
Matrix transpose.
Returns
A'
References DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main(), DotNetMatrix.examples.MagicSquareExample.Main(), and DotNetMatrix.GeneralMatrix.SolveTranspose().
virtual double DotNetMatrix.GeneralMatrix.Norm1 () inline virtual
One norm
Returns
maximum column sum.
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.check(), DotNetMatrix.test.TestMatrix.Main(), and DotNetMatrix.examples.MagicSquareExample.Main().
virtual double DotNetMatrix.GeneralMatrix.Norm2 () inline virtual
Two norm
Returns
maximum singular value.
Referenced by DotNetMatrix.GeneralMatrix.Norm2().
virtual double DotNetMatrix.GeneralMatrix.NormInf () inline virtual
Infinity norm
Returns
maximum row sum.
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual double DotNetMatrix.GeneralMatrix.NormF () inline virtual
Frobenius norm
Returns
sqrt of sum of squares of all elements.
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.UnaryMinus () inline virtual
Unary minus
Returns
-A
References DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Add (GeneralMatrix B) inline virtual
C = A + B
Parameters
B another matrix
Returns
A + B
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main(), DotNetMatrix.examples.MagicSquareExample.Main(), and DotNetMatrix.GeneralMatrix.operator+().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.AddEquals (GeneralMatrix B) inline virtual
A = A + B
Parameters
B another matrix
Returns
A + B
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Subtract (GeneralMatrix B) inline virtual
C = A - B
Parameters
B another matrix
Returns
A - B
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.check(), DotNetMatrix.test.TestMatrix.Main(), DotNetMatrix.examples.MagicSquareExample.Main(), and DotNetMatrix.GeneralMatrix.operator-().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.SubtractEquals (GeneralMatrix B) inline virtual
A = A - B
Parameters
B another matrix
Returns
A - B
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.ArrayMultiply (GeneralMatrix B) inline virtual
Element-by-element multiplication, C = A.*B
Parameters
B another matrix
Returns
A.*B
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.ArrayMultiplyEquals (GeneralMatrix B) inline virtual
Element-by-element multiplication in place, A = A.*B
Parameters
B another matrix
Returns
A.*B
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.ArrayRightDivide (GeneralMatrix B) inline virtual
Element-by-element right division, C = A./B
Parameters
B another matrix
Returns
A./B
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.ArrayRightDivideEquals (GeneralMatrix B) inline virtual
Element-by-element right division in place, A = A./B
Parameters
B another matrix
Returns
A./B
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.ArrayLeftDivide (GeneralMatrix B) inline virtual
Element-by-element left division, C = A.
Parameters
B another matrix
Returns
A.
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.ArrayLeftDivideEquals (GeneralMatrix B) inline virtual
Element-by-element left division in place, A = A.
Parameters
B another matrix
Returns
A.
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Multiply (double s) inline virtual
Multiply a matrix by a scalar, C = s*A
Parameters
s scalar
Returns
s*A
References DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main(), DotNetMatrix.examples.MagicSquareExample.Main(), and DotNetMatrix.GeneralMatrix.operator*().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.MultiplyEquals (double s) inline virtual
Multiply a matrix by a scalar in place, A = s*A
Parameters
s scalar
Returns
replace A by s*A
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Multiply (GeneralMatrix B) inline virtual
Linear algebraic matrix multiplication, A * B
Parameters
B another matrix
Returns
Matrix product, A * B
Exceptions
System.ArgumentException Matrix inner dimensions must agree.
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
static GeneralMatrix DotNetMatrix.GeneralMatrix.operator+ (GeneralMatrix m1, GeneralMatrix m2) inline static
Addition of matrices
Parameters
m1
m2
Returns
References DotNetMatrix.GeneralMatrix.Add().
static GeneralMatrix DotNetMatrix.GeneralMatrix.operator- (GeneralMatrix m1, GeneralMatrix m2) inline static
Subtraction of matrices
Parameters
m1
m2
Returns
References DotNetMatrix.GeneralMatrix.Subtract().
static GeneralMatrix DotNetMatrix.GeneralMatrix.operator* (GeneralMatrix m1, GeneralMatrix m2) inline static
Multiplication of matrices
Parameters
m1
m2
Returns
References DotNetMatrix.GeneralMatrix.Multiply().
virtual LUDecomposition DotNetMatrix.GeneralMatrix.LUD () inline virtual
LU Decomposition
Returns
LUDecomposition
See also
LUDecomposition
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual QRDecomposition DotNetMatrix.GeneralMatrix.QRD () inline virtual
QR Decomposition
Returns
QRDecomposition
See also
QRDecomposition
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual CholeskyDecomposition DotNetMatrix.GeneralMatrix.chol () inline virtual
Cholesky Decomposition
Returns
CholeskyDecomposition
See also
CholeskyDecomposition
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual SingularValueDecomposition DotNetMatrix.GeneralMatrix.SVD () inline virtual
Singular Value Decomposition
Returns
SingularValueDecomposition
See also
SingularValueDecomposition
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual EigenvalueDecomposition DotNetMatrix.GeneralMatrix.Eigen () inline virtual
Eigenvalue Decomposition
Returns
EigenvalueDecomposition
See also
EigenvalueDecomposition
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Solve (GeneralMatrix B) inline virtual
Solve A*X = B
Parameters
B right hand side
Returns
solution if A is square, least squares solution otherwise
Referenced by DotNetMatrix.GeneralMatrix.Inverse(), DotNetMatrix.test.TestMatrix.Main(), DotNetMatrix.GeneralMatrix.Solve(), and DotNetMatrix.GeneralMatrix.SolveTranspose().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.SolveTranspose (GeneralMatrix B) inline virtual
Solve X*A = B, which is also A'*X' = B'
Parameters
B right hand side
Returns
solution if A is square, least squares solution otherwise.
References DotNetMatrix.GeneralMatrix.Solve(), and DotNetMatrix.GeneralMatrix.Transpose().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Inverse () inline virtual
Matrix inverse or pseudoinverse
Returns
inverse(A) if A is square, pseudoinverse otherwise.
References DotNetMatrix.GeneralMatrix.Identity(), and DotNetMatrix.GeneralMatrix.Solve().
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual double DotNetMatrix.GeneralMatrix.Determinant () inline virtual
GeneralMatrix determinant
Returns
determinant
References DotNetMatrix.LUDecomposition.Determinant().
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual int DotNetMatrix.GeneralMatrix.Rank () inline virtual
GeneralMatrix rank
Returns
effective numerical rank, obtained from SVD.
References DotNetMatrix.SingularValueDecomposition.Rank().
Referenced by DotNetMatrix.test.TestMatrix.Main(), and DotNetMatrix.examples.MagicSquareExample.Main().
virtual double DotNetMatrix.GeneralMatrix.Condition () inline virtual
Matrix condition (2 norm)
Returns
ratio of largest to smallest singular value.
References DotNetMatrix.SingularValueDecomposition.Condition().
Referenced by DotNetMatrix.test.TestMatrix.Main(), and DotNetMatrix.examples.MagicSquareExample.Main().
virtual double DotNetMatrix.GeneralMatrix.Trace () inline virtual
Matrix trace.
Returns
sum of the diagonal elements.
Referenced by DotNetMatrix.test.TestMatrix.Main(), and DotNetMatrix.examples.MagicSquareExample.Main().
static GeneralMatrix DotNetMatrix.GeneralMatrix.Random (int m, int n) inline static
Generate matrix with random elements
Parameters
m Number of rows.
n Number of colums.
Returns
An m-by-n matrix with uniformly distributed random elements.
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.test.TestMatrix.Main().
static GeneralMatrix DotNetMatrix.GeneralMatrix.Identity (int m, int n) inline static
Generate identity matrix
Parameters
m Number of rows.
n Number of colums.
Returns
An m-by-n matrix with ones on the diagonal and zeros elsewhere.
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.GeneralMatrix.Inverse(), and DotNetMatrix.test.TestMatrix.Main().
void DotNetMatrix.GeneralMatrix.CheckMatrixDimensions (GeneralMatrix B) inline private
Check if size(A) == size(B) *
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
Referenced by DotNetMatrix.GeneralMatrix.Add(), DotNetMatrix.GeneralMatrix.AddEquals(), DotNetMatrix.GeneralMatrix.ArrayLeftDivide(), DotNetMatrix.GeneralMatrix.ArrayLeftDivideEquals(), DotNetMatrix.GeneralMatrix.ArrayMultiply(), DotNetMatrix.GeneralMatrix.ArrayMultiplyEquals(), DotNetMatrix.GeneralMatrix.ArrayRightDivide(), DotNetMatrix.GeneralMatrix.ArrayRightDivideEquals(), DotNetMatrix.GeneralMatrix.Subtract(), and DotNetMatrix.GeneralMatrix.SubtractEquals().
void DotNetMatrix.GeneralMatrix.Dispose () inline
Do not make this method virtual. A derived class should not be able to override this method.
Referenced by DotNetMatrix.GeneralMatrix.~GeneralMatrix().
void DotNetMatrix.GeneralMatrix.Dispose (bool disposing) inline private
Dispose(bool disposing) executes in two distinct scenarios. If disposing equals true, the method has been called directly or indirectly by a user's code. Managed and unmanaged resources can be disposed. If disposing equals false, the method has been called by the runtime from inside the finalizer and you should not reference other objects. Only unmanaged resources can be disposed.
Parameters
disposing
System.Object DotNetMatrix.GeneralMatrix.Clone () inline
Clone the GeneralMatrix object.
References DotNetMatrix.GeneralMatrix.Copy().
void ISerializable. DotNetMatrix.GeneralMatrix.GetObjectData (SerializationInfo info, StreamingContext context) inline private
A method called when serializing this class
Parameters
info
context
static GeneralMatrix DotNetMatrix.GeneralMatrix.Create (double A[][]) inline static
Construct a matrix from a copy of a 2-D array.
Parameters
A Two-dimensional array of doubles.
Exceptions
System.ArgumentException All rows must have the same length
References DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Copy () inline virtual
Make a deep copy of a matrix
References DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual double DotNetMatrix.GeneralMatrix.GetElement (int i, int j) inline virtual
Get a single element.
Parameters
i Row index.
j Column index.
Returns
A(i,j)
Exceptions
System.IndexOutOfRangeException
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.GetMatrix (int i0, int i1, int j0, int j1) inline virtual
Get a submatrix.
Parameters
i0 Initial row index
i1 Final row index
j0 Initial column index
j1 Final column index
Returns
A(i0:i1,j0:j1)
Exceptions
System.IndexOutOfRangeException Submatrix indices
References DotNetMatrix.GeneralMatrix.GeneralMatrix().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.GetMatrix (int[] r, int[] c) inline virtual
Get a submatrix.
Parameters
r Array of row indices.
c Array of column indices.
Returns
A(r(:),c(:))
Exceptions
System.IndexOutOfRangeException Submatrix indices
References DotNetMatrix.GeneralMatrix.GeneralMatrix().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.GetMatrix (int i0, int i1, int[] c) inline virtual
Get a submatrix.
Parameters
i0 Initial row index
i1 Final row index
c Array of column indices.
Returns
A(i0:i1,c(:))
Exceptions
System.IndexOutOfRangeException Submatrix indices
References DotNetMatrix.GeneralMatrix.GeneralMatrix().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.GetMatrix (int[] r, int j0, int j1) inline virtual
Get a submatrix.
Parameters
r Array of row indices.
j0 Initial column index
j1 Final column index
Returns
A(r(:),j0:j1)
Exceptions
System.IndexOutOfRangeException Submatrix indices
References DotNetMatrix.GeneralMatrix.GeneralMatrix().
virtual void DotNetMatrix.GeneralMatrix.SetElement (int i, int j, double s) inline virtual
Set a single element.
Parameters
i Row index.
j Column index.
s A(i,j).
Exceptions
System.IndexOutOfRangeException
virtual void DotNetMatrix.GeneralMatrix.SetMatrix (int i0, int i1, int j0, int j1, GeneralMatrix X) inline virtual
Set a submatrix.
Parameters
i0 Initial row index
i1 Final row index
j0 Initial column index
j1 Final column index
X A(i0:i1,j0:j1)
Exceptions
System.IndexOutOfRangeException Submatrix indices
virtual void DotNetMatrix.GeneralMatrix.SetMatrix (int[] r, int[] c, GeneralMatrix X) inline virtual
Set a submatrix.
Parameters
r Array of row indices.
c Array of column indices.
X A(r(:),c(:))
Exceptions
System.IndexOutOfRangeException Submatrix indices
virtual void DotNetMatrix.GeneralMatrix.SetMatrix (int[] r, int j0, int j1, GeneralMatrix X) inline virtual
Set a submatrix.
Parameters
r Array of row indices.
j0 Initial column index
j1 Final column index
X A(r(:),j0:j1)
Exceptions
System.IndexOutOfRangeException Submatrix indices
virtual void DotNetMatrix.GeneralMatrix.SetMatrix (int i0, int i1, int[] c, GeneralMatrix X) inline virtual
Set a submatrix.
Parameters
i0 Initial row index
i1 Final row index
c Array of column indices.
X A(i0:i1,c(:))
Exceptions
System.IndexOutOfRangeException Submatrix indices
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Transpose () inline virtual
Matrix transpose.
Returns
A'
References DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual double DotNetMatrix.GeneralMatrix.Norm1 () inline virtual
One norm
Returns
maximum column sum.
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual double DotNetMatrix.GeneralMatrix.Norm2 () inline virtual
Two norm
Returns
maximum singular value.
References DotNetMatrix.GeneralMatrix.Norm2().
virtual double DotNetMatrix.GeneralMatrix.NormInf () inline virtual
Infinity norm
Returns
maximum row sum.
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual double DotNetMatrix.GeneralMatrix.NormF () inline virtual
Frobenius norm
Returns
sqrt of sum of squares of all elements.
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.UnaryMinus () inline virtual
Unary minus
Returns
-A
References DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Add (GeneralMatrix B) inline virtual
C = A + B
Parameters
B another matrix
Returns
A + B
References DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.AddEquals (GeneralMatrix B) inline virtual
A = A + B
Parameters
B another matrix
Returns
A + B
References DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Subtract (GeneralMatrix B) inline virtual
C = A - B
Parameters
B another matrix
Returns
A - B
References DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.SubtractEquals (GeneralMatrix B) inline virtual
A = A - B
Parameters
B another matrix
Returns
A - B
References DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.ArrayMultiply (GeneralMatrix B) inline virtual
Element-by-element multiplication, C = A.*B
Parameters
B another matrix
Returns
A.*B
References DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.ArrayMultiplyEquals (GeneralMatrix B) inline virtual
Element-by-element multiplication in place, A = A.*B
Parameters
B another matrix
Returns
A.*B
References DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.ArrayRightDivide (GeneralMatrix B) inline virtual
Element-by-element right division, C = A./B
Parameters
B another matrix
Returns
A./B
References DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.ArrayRightDivideEquals (GeneralMatrix B) inline virtual
Element-by-element right division in place, A = A./B
Parameters
B another matrix
Returns
A./B
References DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.ArrayLeftDivide (GeneralMatrix B) inline virtual
Element-by-element left division, C = A.
Parameters
B another matrix
Returns
A.
References DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.ArrayLeftDivideEquals (GeneralMatrix B) inline virtual
Element-by-element left division in place, A = A.
Parameters
B another matrix
Returns
A.
References DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Multiply (double s) inline virtual
Multiply a matrix by a scalar, C = s*A
Parameters
s scalar
Returns
s*A
References DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.MultiplyEquals (double s) inline virtual
Multiply a matrix by a scalar in place, A = s*A
Parameters
s scalar
Returns
replace A by s*A
References DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Multiply (GeneralMatrix B) inline virtual
Linear algebraic matrix multiplication, A * B
Parameters
B another matrix
Returns
Matrix product, A * B
Exceptions
System.ArgumentException Matrix inner dimensions must agree.
References DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
static GeneralMatrix DotNetMatrix.GeneralMatrix.operator+ (GeneralMatrix m1, GeneralMatrix m2) inline static
Addition of matrices
Parameters
m1
m2
Returns
static GeneralMatrix DotNetMatrix.GeneralMatrix.operator- (GeneralMatrix m1, GeneralMatrix m2) inline static
Subtraction of matrices
Parameters
m1
m2
Returns
static GeneralMatrix DotNetMatrix.GeneralMatrix.operator* (GeneralMatrix m1, GeneralMatrix m2) inline static
Multiplication of matrices
Parameters
m1
m2
Returns
virtual LUDecomposition DotNetMatrix.GeneralMatrix.LUD () inline virtual
LU Decomposition
Returns
LUDecomposition
See also
LUDecomposition
virtual QRDecomposition DotNetMatrix.GeneralMatrix.QRD () inline virtual
QR Decomposition
Returns
QRDecomposition
See also
QRDecomposition
virtual CholeskyDecomposition DotNetMatrix.GeneralMatrix.chol () inline virtual
Cholesky Decomposition
Returns
CholeskyDecomposition
See also
CholeskyDecomposition
virtual SingularValueDecomposition DotNetMatrix.GeneralMatrix.SVD () inline virtual
Singular Value Decomposition
Returns
SingularValueDecomposition
See also
SingularValueDecomposition
virtual EigenvalueDecomposition DotNetMatrix.GeneralMatrix.Eigen () inline virtual
Eigenvalue Decomposition
Returns
EigenvalueDecomposition
See also
EigenvalueDecomposition
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Solve (GeneralMatrix B) inline virtual
Solve A*X = B
Parameters
B right hand side
Returns
solution if A is square, least squares solution otherwise
References DotNetMatrix.GeneralMatrix.Solve().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.SolveTranspose (GeneralMatrix B) inline virtual
Solve X*A = B, which is also A'*X' = B'
Parameters
B right hand side
Returns
solution if A is square, least squares solution otherwise.
References DotNetMatrix.GeneralMatrix.Solve(), and DotNetMatrix.GeneralMatrix.Transpose().
virtual GeneralMatrix DotNetMatrix.GeneralMatrix.Inverse () inline virtual
Matrix inverse or pseudoinverse
Returns
inverse(A) if A is square, pseudoinverse otherwise.
References DotNetMatrix.GeneralMatrix.Identity(), and DotNetMatrix.GeneralMatrix.Solve().
virtual double DotNetMatrix.GeneralMatrix.Determinant () inline virtual
GeneralMatrix determinant
Returns
determinant
References DotNetMatrix.LUDecomposition.Determinant().
virtual int DotNetMatrix.GeneralMatrix.Rank () inline virtual
GeneralMatrix rank
Returns
effective numerical rank, obtained from SVD.
References DotNetMatrix.SingularValueDecomposition.Rank().
virtual double DotNetMatrix.GeneralMatrix.Condition () inline virtual
Matrix condition (2 norm)
Returns
ratio of largest to smallest singular value.
References DotNetMatrix.SingularValueDecomposition.Condition().
virtual double DotNetMatrix.GeneralMatrix.Trace () inline virtual
Matrix trace.
Returns
sum of the diagonal elements.
static GeneralMatrix DotNetMatrix.GeneralMatrix.Random (int m, int n) inline static
Generate matrix with random elements
Parameters
m Number of rows.
n Number of colums.
Returns
An m-by-n matrix with uniformly distributed random elements.
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
static GeneralMatrix DotNetMatrix.GeneralMatrix.Identity (int m, int n) inline static
Generate identity matrix
Parameters
m Number of rows.
n Number of colums.
Returns
An m-by-n matrix with ones on the diagonal and zeros elsewhere.
References DotNetMatrix.GeneralMatrix.A, DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.m, and DotNetMatrix.GeneralMatrix.n.
void DotNetMatrix.GeneralMatrix.CheckMatrixDimensions (GeneralMatrix B) inline private
Check if size(A) == size(B) *
void DotNetMatrix.GeneralMatrix.Dispose () inline
Do not make this method virtual. A derived class should not be able to override this method.
void DotNetMatrix.GeneralMatrix.Dispose (bool disposing) inline private
Dispose(bool disposing) executes in two distinct scenarios. If disposing equals true, the method has been called directly or indirectly by a user's code. Managed and unmanaged resources can be disposed. If disposing equals false, the method has been called by the runtime from inside the finalizer and you should not reference other objects. Only unmanaged resources can be disposed.
Parameters
disposing
System.Object DotNetMatrix.GeneralMatrix.Clone () inline
Clone the GeneralMatrix object.
References DotNetMatrix.GeneralMatrix.Copy().
void ISerializable. DotNetMatrix.GeneralMatrix.GetObjectData (SerializationInfo info, StreamingContext context) inline private
A method called when serializing this class
Parameters
info
context
Member Data Documentation
double [][] DotNetMatrix.GeneralMatrix.A private
Array for internal storage of elements. internal array storage.
Referenced by DotNetMatrix.GeneralMatrix.Add(), DotNetMatrix.GeneralMatrix.AddEquals(), DotNetMatrix.GeneralMatrix.ArrayLeftDivide(), DotNetMatrix.GeneralMatrix.ArrayLeftDivideEquals(), DotNetMatrix.GeneralMatrix.ArrayMultiply(), DotNetMatrix.GeneralMatrix.ArrayMultiplyEquals(), DotNetMatrix.GeneralMatrix.ArrayRightDivide(), DotNetMatrix.GeneralMatrix.ArrayRightDivideEquals(), DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.Identity(), DotNetMatrix.GeneralMatrix.Multiply(), DotNetMatrix.GeneralMatrix.Random(), DotNetMatrix.GeneralMatrix.Subtract(), and DotNetMatrix.GeneralMatrix.SubtractEquals().
int DotNetMatrix.GeneralMatrix.m private
Row and column dimensions. row dimension. column dimension.
Referenced by DotNetMatrix.GeneralMatrix.Add(), DotNetMatrix.GeneralMatrix.AddEquals(), DotNetMatrix.GeneralMatrix.ArrayLeftDivide(), DotNetMatrix.GeneralMatrix.ArrayLeftDivideEquals(), DotNetMatrix.GeneralMatrix.ArrayMultiply(), DotNetMatrix.GeneralMatrix.ArrayMultiplyEquals(), DotNetMatrix.GeneralMatrix.ArrayRightDivide(), DotNetMatrix.GeneralMatrix.ArrayRightDivideEquals(), DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.Copy(), DotNetMatrix.GeneralMatrix.Create(), DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.Identity(), DotNetMatrix.GeneralMatrix.Multiply(), DotNetMatrix.GeneralMatrix.MultiplyEquals(), DotNetMatrix.GeneralMatrix.Norm1(), DotNetMatrix.GeneralMatrix.NormF(), DotNetMatrix.GeneralMatrix.NormInf(), DotNetMatrix.GeneralMatrix.Random(), DotNetMatrix.GeneralMatrix.Subtract(), DotNetMatrix.GeneralMatrix.SubtractEquals(), DotNetMatrix.GeneralMatrix.Transpose(), and DotNetMatrix.GeneralMatrix.UnaryMinus().
int DotNetMatrix.GeneralMatrix.n private
Referenced by DotNetMatrix.GeneralMatrix.Add(), DotNetMatrix.GeneralMatrix.AddEquals(), DotNetMatrix.GeneralMatrix.ArrayLeftDivide(), DotNetMatrix.GeneralMatrix.ArrayLeftDivideEquals(), DotNetMatrix.GeneralMatrix.ArrayMultiply(), DotNetMatrix.GeneralMatrix.ArrayMultiplyEquals(), DotNetMatrix.GeneralMatrix.ArrayRightDivide(), DotNetMatrix.GeneralMatrix.ArrayRightDivideEquals(), DotNetMatrix.GeneralMatrix.CheckMatrixDimensions(), DotNetMatrix.GeneralMatrix.Copy(), DotNetMatrix.GeneralMatrix.Create(), DotNetMatrix.GeneralMatrix.GeneralMatrix(), DotNetMatrix.GeneralMatrix.Identity(), DotNetMatrix.GeneralMatrix.Multiply(), DotNetMatrix.GeneralMatrix.MultiplyEquals(), DotNetMatrix.GeneralMatrix.Norm1(), DotNetMatrix.GeneralMatrix.NormF(), DotNetMatrix.GeneralMatrix.NormInf(), DotNetMatrix.GeneralMatrix.Random(), DotNetMatrix.GeneralMatrix.Subtract(), DotNetMatrix.GeneralMatrix.SubtractEquals(), DotNetMatrix.GeneralMatrix.Transpose(), and DotNetMatrix.GeneralMatrix.UnaryMinus().
Property Documentation
virtual double [][] DotNetMatrix.GeneralMatrix.Array get
Access the internal two-dimensional array.
Returns
Pointer to the two-dimensional array of matrix elements.
Referenced by DotNetMatrix.GeneralMatrix.Add(), DotNetMatrix.GeneralMatrix.ArrayLeftDivide(), DotNetMatrix.GeneralMatrix.ArrayMultiply(), DotNetMatrix.GeneralMatrix.ArrayRightDivide(), DotNetMatrix.CholeskyDecomposition.CholeskyDecomposition(), DotNetMatrix.GeneralMatrix.Copy(), DotNetMatrix.GeneralMatrix.Create(), DotNetMatrix.EigenvalueDecomposition.EigenvalueDecomposition(), DotNetMatrix.GeneralMatrix.GetMatrix(), DotNetMatrix.GeneralMatrix.Identity(), DotNetMatrix.test.TestMatrix.Main(), DotNetMatrix.GeneralMatrix.Multiply(), DotNetMatrix.GeneralMatrix.Random(), DotNetMatrix.LUDecomposition.Solve(), DotNetMatrix.GeneralMatrix.Subtract(), DotNetMatrix.GeneralMatrix.Transpose(), and DotNetMatrix.GeneralMatrix.UnaryMinus().
virtual double [][] DotNetMatrix.GeneralMatrix.ArrayCopy get
Copy the internal two-dimensional array.
Returns
Two-dimensional array copy of matrix elements.
Referenced by DotNetMatrix.LUDecomposition.LUDecomposition(), DotNetMatrix.test.TestMatrix.Main(), DotNetMatrix.QRDecomposition.QRDecomposition(), DotNetMatrix.SingularValueDecomposition.SingularValueDecomposition(), DotNetMatrix.CholeskyDecomposition.Solve(), and DotNetMatrix.QRDecomposition.Solve().
virtual double [] DotNetMatrix.GeneralMatrix.ColumnPackedCopy get
Make a one-dimensional column packed copy of the internal array.
Returns
Matrix elements packed in a one-dimensional array by columns.
Referenced by DotNetMatrix.test.TestMatrix.Main().
virtual double [] DotNetMatrix.GeneralMatrix.RowPackedCopy get
Make a one-dimensional row packed copy of the internal array.
Returns
Matrix elements packed in a one-dimensional array by rows.
Referenced by DotNetMatrix.test.TestMatrix.Main().
int DotNetMatrix.GeneralMatrix.RowDimension get
Get row dimension.
Returns
m, the number of rows.
Referenced by DotNetMatrix.CholeskyDecomposition.CholeskyDecomposition(), DotNetMatrix.LUDecomposition.LUDecomposition(), DotNetMatrix.test.TestMatrix.Main(), DotNetMatrix.QRDecomposition.QRDecomposition(), DotNetMatrix.SingularValueDecomposition.SingularValueDecomposition(), DotNetMatrix.CholeskyDecomposition.Solve(), DotNetMatrix.QRDecomposition.Solve(), and DotNetMatrix.LUDecomposition.Solve().
int DotNetMatrix.GeneralMatrix.ColumnDimension get
Get column dimension.
Returns
n, the number of columns.
Referenced by DotNetMatrix.CholeskyDecomposition.CholeskyDecomposition(), DotNetMatrix.EigenvalueDecomposition.EigenvalueDecomposition(), DotNetMatrix.LUDecomposition.LUDecomposition(), DotNetMatrix.test.TestMatrix.Main(), DotNetMatrix.QRDecomposition.QRDecomposition(), DotNetMatrix.SingularValueDecomposition.SingularValueDecomposition(), DotNetMatrix.CholeskyDecomposition.Solve(), DotNetMatrix.QRDecomposition.Solve(), and DotNetMatrix.LUDecomposition.Solve().
The documentation for this class was generated from the following file:
igtest/numerics/DotMatrix/Backup/GeneralMatrix.cs