IGLib: alglib.testnlequnit Class Reference
alglib.testnlequnit Class Reference
Static Public Member Functions
static bool testnleq (bool silent)
static bool testnleq (bool silent)
static bool _pexec_testnleq (bool silent)
Static Private Member Functions
static void testfunchbm (nleq.nleqstate state)
static void testfunchb1 (nleq.nleqstate state)
static void testfuncshbm (nleq.nleqstate state)
static void testfunchbm (nleq.nleqstate state)
static void testfunchb1 (nleq.nleqstate state)
static void testfuncshbm (nleq.nleqstate state)
Member Function Documentation
static bool alglib.testnlequnit.testnleq (bool silent) inline static
References alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.nleq.nleqcreatelm(), alglib.nleq.nleqiteration(), alglib.nleq.nleqrestartfrom(), alglib.nleq.nleqresults(), alglib.nleq.nleqsetcond(), alglib.nleq.nleqsetstpmax(), alglib.nleq.nleqsetxrep(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.math.sqr(), alglib.testnlequnit.testfunchb1(), alglib.testnlequnit.testfunchbm(), and alglib.testnlequnit.testfuncshbm().
Referenced by alglib.testnlequnit._pexec_testnleq(), and _Test.Main().
static void alglib.testnlequnit.testfunchbm (nleq.nleqstate state) inline static private
References alglib.ap.assert(), and alglib.math.sqr().
Referenced by alglib.testnlequnit.testnleq().
static void alglib.testnlequnit.testfunchb1 (nleq.nleqstate state) inline static private
References alglib.ap.assert(), and alglib.math.sqr().
Referenced by alglib.testnlequnit.testnleq().
static void alglib.testnlequnit.testfuncshbm (nleq.nleqstate state) inline static private
References alglib.ap.assert(), and alglib.math.sqr().
Referenced by alglib.testnlequnit.testnleq().
static bool alglib.testnlequnit.testnleq (bool silent) inline static
References alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.nleq.nleqcreatelm(), alglib.nleq.nleqiteration(), alglib.nleq.nleqrestartfrom(), alglib.nleq.nleqresults(), alglib.nleq.nleqsetcond(), alglib.nleq.nleqsetstpmax(), alglib.nleq.nleqsetxrep(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.math.sqr(), alglib.testnlequnit.testfunchb1(), alglib.testnlequnit.testfunchbm(), and alglib.testnlequnit.testfuncshbm().
static bool alglib.testnlequnit._pexec_testnleq (bool silent) inline static
References alglib.testnlequnit.testnleq().
Referenced by _Test.Main().
static void alglib.testnlequnit.testfunchbm (nleq.nleqstate state) inline static private
References alglib.ap.assert(), and alglib.math.sqr().
static void alglib.testnlequnit.testfunchb1 (nleq.nleqstate state) inline static private
References alglib.ap.assert(), and alglib.math.sqr().
static void alglib.testnlequnit.testfuncshbm (nleq.nleqstate state) inline static private
References alglib.ap.assert(), and alglib.math.sqr().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs