IGLib: alglib.testlsfitunit Class Reference
alglib.testlsfitunit Class Reference
Static Public Member Functions
static bool testlsfit (bool silent)
static bool testlsfit (bool silent)
static bool _pexec_testlsfit (bool silent)
Static Private Member Functions
static void testpolynomialfitting (ref bool fiterrors)
static void testrationalfitting (ref bool fiterrors)
static void testsplinefitting (ref bool fiterrors)
static void testgeneralfitting (ref bool llserrors, ref bool nlserrors)
static bool isglssolution (int n, int m, int k, double[] y, double[] w, double[,] fmatrix, double[,] cmatrix, double[] c)
static double getglserror (int n, int m, double[] y, double[] w, double[,] fmatrix, double[] c)
static void fitlinearnonlinear (int m, int deravailable, double[,] xy, lsfit.lsfitstate state, ref bool nlserrors)
static void testgradientcheck (ref bool testg)
static void funcderiv (double[] c, double[] x, double[] x0, int k, int m, int functype, ref double f, ref double[] g)
static void testpolynomialfitting (ref bool fiterrors)
static void testrationalfitting (ref bool fiterrors)
static void testsplinefitting (ref bool fiterrors)
static void testgeneralfitting (ref bool llserrors, ref bool nlserrors)
static bool isglssolution (int n, int m, int k, double[] y, double[] w, double[,] fmatrix, double[,] cmatrix, double[] c)
static double getglserror (int n, int m, double[] y, double[] w, double[,] fmatrix, double[] c)
static void fitlinearnonlinear (int m, int deravailable, double[,] xy, lsfit.lsfitstate state, ref bool nlserrors)
static void testgradientcheck (ref bool testg)
static void funcderiv (double[] c, double[] x, double[] x0, int k, int m, int functype, ref double f, ref double[] g)
static void checkerrorsinparameters (double[,] a, double[] y, double[] w, double noiselevel, double[] c0, double[] c1, lsfit.lsfitreport rep, int n, int k, double tol, ref bool errors)
Member Function Documentation
static bool alglib.testlsfitunit.testlsfit (bool silent) inline static
References alglib.testlsfitunit.testgeneralfitting(), alglib.testlsfitunit.testgradientcheck(), alglib.testlsfitunit.testpolynomialfitting(), alglib.testlsfitunit.testrationalfitting(), and alglib.testlsfitunit.testsplinefitting().
Referenced by alglib.testlsfitunit._pexec_testlsfit(), and _Test.Main().
static void alglib.testlsfitunit.testpolynomialfitting (ref bool fiterrors) inline static private
References alglib.apserv.approxequalrel(), alglib.ap.assert(), alglib.ratint.barycentriccalc(), alglib.ratint.barycentricdiff1(), alglib.math.machineepsilon, alglib.polint.polynomialbuild(), alglib.lsfit.polynomialfit(), alglib.lsfit.polynomialfitwc(), alglib.math.randomreal(), alglib.math.sqr(), and alglib.apserv.taskgenint1d().
Referenced by alglib.testlsfitunit.testlsfit().
static void alglib.testlsfitunit.testrationalfitting (ref bool fiterrors) inline static private
References alglib.apserv.approxequalrel(), alglib.ap.assert(), alglib.ratint.barycentricbuildfloaterhormann(), alglib.ratint.barycentriccalc(), alglib.ratint.barycentricdiff1(), alglib.lsfit.barycentricfitfloaterhormann(), alglib.lsfit.barycentricfitfloaterhormannwc(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testlsfitunit.testlsfit().
static void alglib.testlsfitunit.testsplinefitting (ref bool fiterrors) inline static private
References alglib.apserv.approxequalrel(), alglib.ap.assert(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1dbuildhermite(), alglib.spline1d.spline1dcalc(), alglib.spline1d.spline1ddiff(), alglib.lsfit.spline1dfitcubic(), alglib.lsfit.spline1dfitcubicwc(), alglib.lsfit.spline1dfithermite(), alglib.lsfit.spline1dfithermitewc(), alglib.lsfit.spline1dfitpenalized(), alglib.lsfit.spline1dfitpenalizedw(), and alglib.math.sqr().
Referenced by alglib.testlsfitunit.testlsfit().
static void alglib.testlsfitunit.testgeneralfitting (ref bool llserrors, ref bool nlserrors) inline static private
References alglib.testlsfitunit.fitlinearnonlinear(), alglib.testlsfitunit.isglssolution(), alglib.lsfit.lsfitcreatef(), alglib.lsfit.lsfitcreatefg(), alglib.lsfit.lsfitcreatefgh(), alglib.lsfit.lsfitcreatewf(), alglib.lsfit.lsfitcreatewfg(), alglib.lsfit.lsfitcreatewfgh(), alglib.lsfit.lsfititeration(), alglib.lsfit.lsfitlinear(), alglib.lsfit.lsfitlinearc(), alglib.lsfit.lsfitlinearw(), alglib.lsfit.lsfitlinearwc(), alglib.lsfit.lsfitresults(), alglib.lsfit.lsfitsetcond(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.math.minrealnumber, alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testlsfitunit.testlsfit().
static bool alglib.testlsfitunit.isglssolution (int n, int m, int k, double[] y, double[] w, double fmatrix[,], double cmatrix[,], double[] c) inline static private
References alglib.testlsfitunit.getglserror(), alglib.math.machineepsilon, and alglib.svd.rmatrixsvd().
Referenced by alglib.testlsfitunit.testgeneralfitting().
static double alglib.testlsfitunit.getglserror (int n, int m, double[] y, double[] w, double fmatrix[,], double[] c) inline static private
References alglib.math.sqr().
Referenced by alglib.testlsfitunit.isglssolution().
static void alglib.testlsfitunit.fitlinearnonlinear (int m, int deravailable, double xy[,], lsfit.lsfitstate state, ref bool nlserrors) inline static private
References alglib.lsfit.lsfititeration().
Referenced by alglib.testlsfitunit.testgeneralfitting().
static void alglib.testlsfitunit.testgradientcheck (ref bool testg) inline static private
References alglib.testlsfitunit.funcderiv(), alglib.lsfit.lsfitcreatefg(), alglib.lsfit.lsfititeration(), alglib.lsfit.lsfitresults(), alglib.lsfit.lsfitsetbc(), alglib.lsfit.lsfitsetcond(), alglib.lsfit.lsfitsetgradientcheck(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testlsfitunit.testlsfit().
static void alglib.testlsfitunit.funcderiv (double[] c, double[] x, double[] x0, int k, int m, int functype, ref double f, ref double[] g) inline static private
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.math.sqr().
Referenced by alglib.testlsfitunit.testgradientcheck().
static bool alglib.testlsfitunit.testlsfit (bool silent) inline static
References alglib.testlsfitunit.testgeneralfitting(), alglib.testlsfitunit.testgradientcheck(), alglib.testlsfitunit.testpolynomialfitting(), alglib.testlsfitunit.testrationalfitting(), and alglib.testlsfitunit.testsplinefitting().
static bool alglib.testlsfitunit._pexec_testlsfit (bool silent) inline static
References alglib.testlsfitunit.testlsfit().
Referenced by _Test.Main().
static void alglib.testlsfitunit.testpolynomialfitting (ref bool fiterrors) inline static private
References alglib.apserv.approxequalrel(), alglib.ap.assert(), alglib.ratint.barycentriccalc(), alglib.ratint.barycentricdiff1(), alglib.math.machineepsilon, alglib.polint.polynomialbuild(), alglib.lsfit.polynomialfit(), alglib.lsfit.polynomialfitwc(), alglib.math.randomreal(), alglib.math.sqr(), and alglib.apserv.taskgenint1d().
static void alglib.testlsfitunit.testrationalfitting (ref bool fiterrors) inline static private
References alglib.apserv.approxequalrel(), alglib.ap.assert(), alglib.ratint.barycentricbuildfloaterhormann(), alglib.ratint.barycentriccalc(), alglib.ratint.barycentricdiff1(), alglib.lsfit.barycentricfitfloaterhormann(), alglib.lsfit.barycentricfitfloaterhormannwc(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.math.randomreal(), and alglib.math.sqr().
static void alglib.testlsfitunit.testsplinefitting (ref bool fiterrors) inline static private
References alglib.apserv.approxequalrel(), alglib.ap.assert(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1dbuildhermite(), alglib.spline1d.spline1dcalc(), alglib.spline1d.spline1ddiff(), alglib.lsfit.spline1dfitcubic(), alglib.lsfit.spline1dfitcubicwc(), alglib.lsfit.spline1dfithermite(), alglib.lsfit.spline1dfithermitewc(), alglib.lsfit.spline1dfitpenalized(), alglib.lsfit.spline1dfitpenalizedw(), and alglib.math.sqr().
static void alglib.testlsfitunit.testgeneralfitting (ref bool llserrors, ref bool nlserrors) inline static private
References alglib.testlsfitunit.fitlinearnonlinear(), alglib.math.isfinite(), alglib.testlsfitunit.isglssolution(), alglib.lsfit.lsfitcreatef(), alglib.lsfit.lsfitcreatefg(), alglib.lsfit.lsfitcreatefgh(), alglib.lsfit.lsfitcreatewf(), alglib.lsfit.lsfitcreatewfg(), alglib.lsfit.lsfitcreatewfgh(), alglib.lsfit.lsfititeration(), alglib.lsfit.lsfitlinear(), alglib.lsfit.lsfitlinearc(), alglib.lsfit.lsfitlinearw(), alglib.lsfit.lsfitlinearwc(), alglib.lsfit.lsfitresults(), alglib.lsfit.lsfitsetcond(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.math.minrealnumber, alglib.apserv.randomnormal(), alglib.math.randomreal(), alglib.apserv.seterrorflag(), and alglib.math.sqr().
static bool alglib.testlsfitunit.isglssolution (int n, int m, int k, double[] y, double[] w, double fmatrix[,], double cmatrix[,], double[] c) inline static private
References alglib.testlsfitunit.getglserror(), alglib.math.machineepsilon, and alglib.svd.rmatrixsvd().
static double alglib.testlsfitunit.getglserror (int n, int m, double[] y, double[] w, double fmatrix[,], double[] c) inline static private
References alglib.math.sqr().
static void alglib.testlsfitunit.fitlinearnonlinear (int m, int deravailable, double xy[,], lsfit.lsfitstate state, ref bool nlserrors) inline static private
References alglib.lsfit.lsfititeration().
static void alglib.testlsfitunit.testgradientcheck (ref bool testg) inline static private
References alglib.testlsfitunit.funcderiv(), alglib.lsfit.lsfitcreatefg(), alglib.lsfit.lsfititeration(), alglib.lsfit.lsfitresults(), alglib.lsfit.lsfitsetbc(), alglib.lsfit.lsfitsetcond(), alglib.lsfit.lsfitsetgradientcheck(), alglib.math.randominteger(), and alglib.math.randomreal().
static void alglib.testlsfitunit.funcderiv (double[] c, double[] x, double[] x0, int k, int m, int functype, ref double f, ref double[] g) inline static private
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.math.sqr().
static void alglib.testlsfitunit.checkerrorsinparameters (double a[,], double[] y, double[] w, double noiselevel, double[] c0, double[] c1, lsfit.lsfitreport rep, int n, int k, double tol, ref bool errors) inline static private
References alglib.math.machineepsilon, and alglib.math.sqr().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs