IGLib: NUnit.Framework.Attributes.MaxTimeTests Class Reference
NUnit.Framework.Attributes.MaxTimeTests Class Reference
Tests for MaxTime decoration.
Public Member Functions
void MaxTimeNotExceeded ()
void MaxTimeExceeded ()
void MaxTimeExceededOnTestCase ()
void FailureReport ()
void FailureReportHasPriorityOverMaxTime ()
void ErrorReportHasPriorityOverMaxTime ()
Detailed Description
Tests for MaxTime decoration.
Member Function Documentation
void NUnit.Framework.Attributes.MaxTimeTests.MaxTimeNotExceeded () inline
void NUnit.Framework.Attributes.MaxTimeTests.MaxTimeExceeded () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.ChildFailure, NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Does.Contain(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.MaxTimeTests.MaxTimeExceededOnTestCase () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.ChildFailure, NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Does.Contain(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.MaxTimeTests.FailureReport () inline
References NUnit.Framework.Assert.Fail(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
void NUnit.Framework.Attributes.MaxTimeTests.FailureReportHasPriorityOverMaxTime () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.ChildFailure, NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.MaxTimeTests.ErrorReportHasPriorityOverMaxTime () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.ChildFailure, NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Does.Contain(), NUnit.Framework.Interfaces.ResultState.Error, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/MaxTimeTests.cs