IGLib: NUnit.Samples.Money.IMoney Interface Reference
NUnit.Samples.Money.IMoney Interface Reference
The common interface for simple Monies and MoneyBags.
Public Member Functions
IMoney Add (IMoney m)
Adds a money to this money.
IMoney AddMoney (Money m)
Adds a simple Money to this money. This is a helper method for implementing double dispatch.
IMoney AddMoneyBag (MoneyBag s)
Adds a MoneyBag to this money. This is a helper method for implementing double dispatch.
IMoney Multiply (int factor)
Multiplies a money by the given factor.
IMoney Negate ()
Negates this money.
IMoney Subtract (IMoney m)
Subtracts a money from this money.
Properties
bool IsZero [get]
True if this money is zero.
Detailed Description
The common interface for simple Monies and MoneyBags.
Member Function Documentation
IMoney NUnit.Samples.Money.IMoney.Add (IMoney m)
Adds a money to this money.
Implemented in NUnit.Samples.Money.MoneyBag, and NUnit.Samples.Money.Money.
Referenced by NUnit.Samples.Money.MoneyBag.AppendMoney().
IMoney NUnit.Samples.Money.IMoney.AddMoney (Money m)
Adds a simple Money to this money. This is a helper method for implementing double dispatch.
Implemented in NUnit.Samples.Money.MoneyBag, and NUnit.Samples.Money.Money.
Referenced by NUnit.Samples.Money.Money.Add().
IMoney NUnit.Samples.Money.IMoney.AddMoneyBag (MoneyBag s)
Adds a MoneyBag to this money. This is a helper method for implementing double dispatch.
Implemented in NUnit.Samples.Money.MoneyBag, and NUnit.Samples.Money.Money.
Referenced by NUnit.Samples.Money.MoneyBag.Add().
IMoney NUnit.Samples.Money.IMoney.Multiply (int factor)
Multiplies a money by the given factor.
Implemented in NUnit.Samples.Money.MoneyBag, and NUnit.Samples.Money.Money.
IMoney NUnit.Samples.Money.IMoney.Negate ()
Negates this money.
Implemented in NUnit.Samples.Money.MoneyBag, and NUnit.Samples.Money.Money.
Referenced by NUnit.Samples.Money.Money.Subtract(), and NUnit.Samples.Money.MoneyBag.Subtract().
IMoney NUnit.Samples.Money.IMoney.Subtract (IMoney m)
Subtracts a money from this money.
Implemented in NUnit.Samples.Money.MoneyBag, and NUnit.Samples.Money.Money.
Property Documentation
bool NUnit.Samples.Money.IMoney.IsZero get
True if this money is zero.
Referenced by NUnit.Samples.Money.MoneyBag.AppendMoney(), NUnit.Samples.Money.MoneyTest.BagMultiply(), and NUnit.Samples.Money.MoneyTest.IsZero().
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1/samples/csharp/money/IMoney.cs