IGLib: alglib.testblasunit Class Reference
alglib.testblasunit Class Reference
Static Public Member Functions
static bool testblas (bool silent)
static bool testblas (bool silent)
static bool _pexec_testblas (bool silent)
Static Private Member Functions
static void naivematrixmatrixmultiply (double[,] a, int ai1, int ai2, int aj1, int aj2, bool transa, double[,] b, int bi1, int bi2, int bj1, int bj2, bool transb, double alpha, ref double[,] c, int ci1, int ci2, int cj1, int cj2, double beta)
static void naivematrixmatrixmultiply (double[,] a, int ai1, int ai2, int aj1, int aj2, bool transa, double[,] b, int bi1, int bi2, int bj1, int bj2, bool transb, double alpha, ref double[,] c, int ci1, int ci2, int cj1, int cj2, double beta)
Member Function Documentation
static bool alglib.testblasunit.testblas (bool silent) inline static
References alglib.blas.columnidxabsmax(), alglib.blas.copyandtranspose(), alglib.blas.copymatrix(), alglib.blas.inplacetranspose(), alglib.math.machineepsilon, alglib.blas.matrixmatrixmultiply(), alglib.blas.matrixvectormultiply(), alglib.math.maxrealnumber, alglib.math.minrealnumber, alglib.testblasunit.naivematrixmatrixmultiply(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.blas.rowidxabsmax(), alglib.math.sqr(), alglib.blas.upperhessenberg1norm(), alglib.blas.vectoridxabsmax(), and alglib.blas.vectornorm2().
Referenced by alglib.testblasunit._pexec_testblas(), and _Test.Main().
static void alglib.testblasunit.naivematrixmatrixmultiply (double a[,], int ai1, int ai2, int aj1, int aj2, bool transa, double b[,], int bi1, int bi2, int bj1, int bj2, bool transb, double alpha, ref double c[,], int ci1, int ci2, int cj1, int cj2, double beta) inline static private
References alglib.ap.assert(), and alglib.beta().
Referenced by alglib.testblasunit.testblas().
static bool alglib.testblasunit.testblas (bool silent) inline static
References alglib.blas.columnidxabsmax(), alglib.blas.copyandtranspose(), alglib.blas.copymatrix(), alglib.blas.inplacetranspose(), alglib.math.machineepsilon, alglib.blas.matrixmatrixmultiply(), alglib.blas.matrixvectormultiply(), alglib.math.maxrealnumber, alglib.math.minrealnumber, alglib.testblasunit.naivematrixmatrixmultiply(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.blas.rowidxabsmax(), alglib.math.sqr(), alglib.blas.upperhessenberg1norm(), alglib.blas.vectoridxabsmax(), and alglib.blas.vectornorm2().
static bool alglib.testblasunit._pexec_testblas (bool silent) inline static
References alglib.testblasunit.testblas().
Referenced by _Test.Main().
static void alglib.testblasunit.naivematrixmatrixmultiply (double a[,], int ai1, int ai2, int aj1, int aj2, bool transa, double b[,], int bi1, int bi2, int bj1, int bj2, bool transb, double alpha, ref double c[,], int ci1, int ci2, int cj1, int cj2, double beta) inline static private
References alglib.ap.assert(), and alglib.beta().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs