IGLib: alglib.math Class Reference
alglib.math Class Reference
Static Public Member Functions
static bool isfinite (double d)
static double randomreal ()
static int randominteger (int N)
static double sqr (double X)
static double abscomplex (complex z)
static complex conj (complex z)
static complex csqr (complex z)
static bool isfinite (double d)
static double randomreal ()
static int randominteger (int N)
static double sqr (double X)
static double abscomplex (complex z)
static complex conj (complex z)
static complex csqr (complex z)
Public Attributes
const double machineepsilon = 5E-16
const double maxrealnumber = 1E300
const double minrealnumber = 1E-300
Static Public Attributes
static System.Random rndobject = new System.Random(System.DateTime.Now.Millisecond + 1000*System.DateTime.Now.Second + 60*1000*System.DateTime.Now.Minute)
Member Function Documentation
static bool alglib.math.isfinite (double d) inline static
Referenced by alglib.testclusteringunit.advancedahctests(), alglib.apserv.apservisfinitecmatrix(), alglib.apserv.apservisfinitectrmatrix(), alglib.apserv.apservisfinitematrix(), alglib.apserv.apservisfiniteornanmatrix(), alglib.autogk.autogksingular(), alglib.autogk.autogksmooth(), alglib.autogk.autogksmoothw(), alglib.clustering.clusterizersetdistances(), alglib.cqmodels.cqmseta(), alglib.cqmodels.cqmsetactiveset(), alglib.cqmodels.cqmsetd(), alglib.cqmodels.cqmsetq(), alglib.fft.fftr1dinv(), alglib.testmincgunit.funcderiv(), alglib.testminbleicunit.funcderiv(), alglib.testminlbfgsunit.funcderiv(), alglib.testminlmunit.gradientchecktest(), alglib.apserv.isfinitecvector(), alglib.apserv.isfinitertrmatrix(), alglib.apserv.isfinitevector(), alglib.ap.ishermitian(), alglib.ap.issymmetric(), alglib.lincg.lincgiteration(), alglib.lincg.lincgsetcond(), alglib.linlsqr.linlsqrsetcond(), alglib.linlsqr.linlsqrsetlambdai(), alglib.minbleic.minbleiccreatef(), alglib.minbleic.minbleicsetbc(), alglib.minbleic.minbleicsetgradientcheck(), alglib.minbleic.minbleicsetinnercond(), alglib.minbleic.minbleicsetoutercond(), alglib.minbleic.minbleicsetprecdiag(), alglib.minbleic.minbleicsetscale(), alglib.minbleic.minbleicsetstpmax(), alglib.mincg.mincgcreatef(), alglib.mincg.mincgsetcond(), alglib.mincg.mincgsetgradientcheck(), alglib.mincg.mincgsetprecdiag(), alglib.mincg.mincgsetscale(), alglib.mincg.mincgsetstpmax(), alglib.mincg.mincgsuggeststep(), alglib.mlpbase.mlpsetinputscaling(), alglib.mlpbase.mlpsetneuroninfo(), alglib.mlpbase.mlpsetoutputscaling(), alglib.mlpbase.mlpsetweight(), alglib.nleq.nleqsetcond(), alglib.nleq.nleqsetstpmax(), alglib.odesolver.odesolverrkck(), alglib.polint.polynomialbar2cheb(), alglib.polint.polynomialbar2pow(), alglib.polint.polynomialbuildcheb1(), alglib.polint.polynomialbuildcheb2(), alglib.polint.polynomialbuildeqdist(), alglib.polint.polynomialcalccheb1(), alglib.polint.polynomialcalccheb2(), alglib.polint.polynomialcalceqdist(), alglib.polint.polynomialcheb2bar(), alglib.polint.polynomialpow2bar(), alglib.basestat.samplepercentile(), alglib.testmlpbaseunit.spectests(), alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1dconvcubic(), alglib.spline1d.spline1dconvdiff2cubic(), alglib.spline1d.spline1dconvdiffcubic(), alglib.spline1d.spline1dgriddiff2cubic(), alglib.spline1d.spline1dgriddiffcubic(), alglib.testcqmodelsunit.testcqmodels(), alglib.testmcpdunit.testec(), alglib.testlsfitunit.testgeneralfitting(), alglib.testminbleicunit.testgradientcheck(), and alglib.testalglibbasicsunit.testieeespecial().
static double alglib.math.randomreal () inline static
References alglib.math.rndobject.
Referenced by alglib.testclusteringunit.advancedahctests(), alglib.testlinlsqrunit.analytictest(), alglib.testclusteringunit.basicahctests(), alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testspline3dunit.basictest(), alglib.testdforestunit.basictest1(), alglib.testdforestunit.basictest2(), alglib.testdforestunit.basictest3(), alglib.testdforestunit.basictest4(), alglib.testlincgunit.basictestiters(), alglib.testlincgunit.basictestx(), alglib.testlinlsqrunit.bidiagonaltest(), alglib.testminqpunit.bleictests(), alglib.testspline3dunit.buildrndgrid(), alglib.testminqpunit.choleskytests(), alglib.testortfacunit.cmatrixfillsparsea(), alglib.testevdunit.cmatrixfillsparsea(), alglib.testevdunit.cmatrixhermitiansplit(), alglib.testlincgunit.complexres(), alglib.testlincgunit.complextest(), alglib.testsparseunit.copyfunctest(), alglib.testalglibbasicsunit.createpoolandrecords(), alglib.testsparseunit.createrandom(), alglib.testevdunit.cunset1d(), alglib.testmatinvunit.cunset1d(), alglib.testdensesolverunit.cunset1d(), alglib.testevdunit.cunset2d(), alglib.testmatinvunit.cunset2d(), alglib.testdensesolverunit.cunset2d(), alglib.testminqpunit.ecqptest(), alglib.testspline1dunit.enumerateallsplines(), alglib.testsparseunit.enumeratetest(), alglib.testsvdunit.fillsparsea(), alglib.testschurunit.fillsparsea(), alglib.testbdsvdunit.fillsparsede(), alglib.testminqpunit.functest1(), alglib.testminqpunit.functest2(), alglib.testlinregunit.generatenormal(), alglib.testldaunit.generatenormal(), alglib.testinverseupdateunit.generaterandommatrixcond(), alglib.testinverseupdateunit.generaterandomorthogonalmatrix(), alglib.testlinregunit.generaterandomtask(), alglib.testlinregunit.generatetask(), alglib.testmincgunit.gradientchecktest(), alglib.testminlbfgsunit.gradientchecktest(), alglib.testminlmunit.gradientchecktest(), alglib.testhqrndunit.hqrndcontinuoustest(), alglib.testhqrndunit.hqrnddiscretetest(), alglib.testminqpunit.icqptest(), alglib.testrbfunit.irregularrbftest(), alglib.testclusteringunit.kmeansinfinitelooptest(), alglib.testlincgunit.krylovsubspacetest(), alglib.testsparseunit.linearfunctionsmmtest(), alglib.testsparseunit.linearfunctionssmmtest(), alglib.testsparseunit.linearfunctionsstest(), alglib.testsparseunit.linearfunctionstest(), alglib.testrbfunit.linearitymodelrbftest(), XTest.Main(), alglib.mlpbase.mlpcreate(), alglib.mlpbase.mlprandomize(), alglib.mlpbase.mlprandomizefull(), alglib.logit.mnltrainh(), alglib.testlinlsqrunit.mwcranksvdtest(), alglib.testlinlsqrunit.mwicranksvdtest(), alglib.testlinlsqrunit.preconditionertest(), alglib.testlincgunit.precondtest(), alglib.testfftunit.quicktest(), alglib.apserv.randomnormal(), alglib.testlinlsqrunit.reportcorrectnesstest(), alglib.testsparseunit.rewriteexistingtest(), alglib.testortfacunit.rmatrixfillsparsea(), alglib.testevdunit.rmatrixfillsparsea(), alglib.testevdunit.rmatrixsymmetricsplit(), alglib.testdforestunit.rnormal(), alglib.testclusteringunit.rnormal(), alglib.testkmeansunit.rnormal(), alglib.testdforestunit.rsphere(), alglib.testclusteringunit.rsphere(), alglib.testkmeansunit.rsphere(), alglib.kmeans.selectcenterpp(), alglib.testrbfunit.serializationtest(), alglib.testminbleicunit.setrandompreconditioner(), alglib.testminqpunit.simpletest(), alglib.testlincgunit.sparsetest(), alglib.testrbfunit.specialtest(), alglib.testrbfunit.sqrdegmatrixrbftest(), alglib.testlinlsqrunit.stoppingcriteriatest(), alglib.testlinlsqrunit.svdtest(), alglib.apserv.taskgenint1d(), alglib.apserv.taskgenint1dcheb1(), alglib.apserv.taskgenint1dcheb2(), alglib.apserv.taskgenint1dequidist(), alglib.testbasestatunit.testbasestat(), alglib.testmcpdunit.testbc(), alglib.testbdssunit.testbdss(), alglib.testbdsvdunit.testbdsvd(), alglib.testblasunit.testblas(), alglib.testchebyshevunit.testchebyshev(), alglib.testmatinvunit.testcinv(), alglib.testrcondunit.testcmatrixrcond(), alglib.testrcondunit.testcmatrixtrrcond(), alglib.testalglibbasicsunit.testcomplexarithmetics(), alglib.testminbleicunit.testconv(), alglib.testconvunit.testconv(), alglib.testsparseunit.testconvertsm(), alglib.testablasunit.testcopy(), alglib.testcorrunit.testcorr(), alglib.testcqmodelsunit.testcqmodels(), alglib.testcreflectionsunit.testcreflections(), alglib.testdensesolverunit.testcsolver(), alglib.testmatinvunit.testctrinv(), alglib.testidwintunit.testdegree(), alglib.testmcpdunit.testec(), alglib.testmcpdunit.testentryexit(), alglib.testmlpbaseunit.testerr(), alglib.testmlpeunit.testerr(), alglib.testmatgenunit.testeult(), alglib.testevdunit.testevdset(), alglib.testfblsunit.testfbls(), alglib.testminbleicunit.testfeasibility(), alglib.testfftunit.testfft(), alglib.testfhtunit.testfht(), alglib.testablasunit.testgemm(), alglib.testlsfitunit.testgeneralfitting(), alglib.testsparseunit.testgetrow(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testgradient(), alglib.testminbleicunit.testgradientcheck(), alglib.testlsfitunit.testgradientcheck(), alglib.testhblasunit.testhblas(), alglib.testhermiteunit.testhermite(), alglib.testmlpbaseunit.testhessian(), alglib.testmlptrainunit.testhessian(), alglib.testmatinvunit.testhpdinv(), alglib.testrcondunit.testhpdmatrixrcond(), alglib.testdensesolverunit.testhpdsolver(), alglib.testhqrndunit.testhqrnd(), alglib.testidwintunit.testidwint(), alglib.testmlpbaseunit.testinformational(), alglib.testmlptrainunit.testinformational(), alglib.testinverseupdateunit.testinverseupdate(), alglib.testnearestneighborunit.testkdtreeserialization(), alglib.testnearestneighborunit.testkdtuniform(), alglib.testlaguerreunit.testlaguerre(), alglib.testmcpdunit.testlc(), alglib.testlegendreunit.testlegendre(), alglib.testlinregunit.testlinreg(), alglib.testspline2dunit.testlintrans(), alglib.testspline3dunit.testlintrans(), alglib.testmatgenunit.testmatgen(), alglib.testmincgunit.testmincg(), alglib.testminlbfgsunit.testminlbfgs(), alglib.testminlmunit.testminlm(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlpeunit.testmlpe(), alglib.testmlpbaseunit.testmlpgbsubset(), alglib.testmlptrainunit.testmlpgbsubset(), alglib.testmlptrainunit.testmlprestarts(), alglib.testmlptrainunit.testmlptrainclass(), alglib.testmlptrainunit.testmlptrainens(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlptrainensregr(), alglib.testmlptrainunit.testmlptraines(), alglib.testspline1dunit.testmonotonespline(), alglib.testablasunit.testmv(), alglib.testnearestneighborunit.testnearestneighbor(), alglib.testnlequnit.testnleq(), alglib.testidwintunit.testnoisy(), alglib.testnormestimatorunit.testnormestimator(), alglib.testodesolverunit.testodesolver(), alglib.testortfacunit.testortfac(), alglib.testmincgunit.testother(), alglib.testminbleicunit.testother(), alglib.testminlbfgsunit.testother(), alglib.testpcaunit.testpca(), alglib.testpolintunit.testpolint(), alglib.testlsfitunit.testpolynomialfitting(), alglib.testmincgunit.testpreconditioning(), alglib.testminbleicunit.testpreconditioning(), alglib.testminlbfgsunit.testpreconditioning(), alglib.testdforestunit.testprocessing(), alglib.testmlpbaseunit.testprocessing(), alglib.testmlptrainunit.testprocessing(), alglib.testmlpeunit.testprocessing(), alglib.testpsplineunit.testpspline(), alglib.testablasunit.testrank1(), alglib.testbasestatunit.testranking(), alglib.testratintunit.testratint(), alglib.testlsfitunit.testrationalfitting(), alglib.testortfacunit.testrbdproblem(), alglib.testlincgunit.testrcorrectness(), alglib.testreflectionsunit.testreflections(), alglib.testmatinvunit.testrinv(), alglib.testrcondunit.testrmatrixrcond(), alglib.testrcondunit.testrmatrixtrrcond(), alglib.testdensesolverunit.testrsolver(), alglib.testmatinvunit.testrtrinv(), alglib.testsafesolveunit.testsafesolve(), alglib.testsblasunit.testsblas(), alglib.testschurunit.testschur(), alglib.testalglibbasicsunit.testserializationfunctions(), alglib.testmcpdunit.testsimple(), alglib.testsnnlsunit.testsnnls(), alglib.testspdgevdunit.testspdgevd(), alglib.testmatinvunit.testspdinv(), alglib.testrcondunit.testspdmatrixrcond(), alglib.testdensesolverunit.testspdsolver(), alglib.testnearestneighborunit.testspecialcases(), alglib.testspline1dunit.testspline1d(), alglib.testspline2dunit.testspline2d(), alglib.testspline2dunit.testspline2dvf(), alglib.testlsfitunit.testsplinefitting(), alglib.testsvdunit.testsvd(), alglib.testablasunit.testsyrk(), alglib.testevdunit.testtdevdbiproblem(), alglib.testevdunit.testtdevdproblem(), alglib.testablasunit.testtrans(), alglib.testtrfacunit.testtrfac(), alglib.testspline3dunit.testtrilinearresample(), alglib.testtrlinsolveunit.testtrlinsolve(), alglib.testablasunit.testtrsm(), alglib.testspline1dunit.testunpack(), alglib.testspline2dunit.testunpack(), alglib.testspline3dunit.testunpack(), alglib.testxblasunit.testxblas(), alglib.testtsortunit.unset1d(), alglib.testnearestneighborunit.unset1d(), alglib.testbdssunit.unset1d(), alglib.testevdunit.unset1d(), alglib.testmatinvunit.unset1d(), alglib.testdensesolverunit.unset1d(), alglib.testodesolverunit.unset1d(), alglib.testidwintunit.unset1d(), alglib.testspline1dunit.unset1d(), alglib.testpsplineunit.unset1d(), alglib.testtsortunit.unset2d(), alglib.testnearestneighborunit.unset2d(), alglib.testbdssunit.unset2d(), alglib.testevdunit.unset2d(), alglib.testmatgenunit.unset2d(), alglib.testmatinvunit.unset2d(), alglib.testdensesolverunit.unset2d(), alglib.testodesolverunit.unset2d(), alglib.testidwintunit.unset2d(), alglib.testmatgenunit.unset2dc(), alglib.testspline1dunit.unsetspline1d(), and alglib.testnearestneighborunit.vnorm().
static int alglib.math.randominteger (int N) inline static
References alglib.math.rndobject.
Referenced by alglib.testclusteringunit.advancedahctests(), alglib.testsparseunit.basicfuncrandomtest(), alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testspline3dunit.basictest(), alglib.testdforestunit.basictest1(), alglib.testminqpunit.bleictests(), alglib.testspline3dunit.buildrndgrid(), alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.testalglibbasicsunit.createpoolandrecords(), alglib.testsparseunit.createrandom(), alglib.dforest.dfbuildinternal(), alglib.dforest.dfbuildtreerec(), alglib.testminqpunit.ecqptest(), alglib.testsparseunit.enumeratetest(), alglib.testminqpunit.functest2(), alglib.testlinregunit.generatenormal(), alglib.testldaunit.generatenormal(), alglib.testmincgunit.gradientchecktest(), alglib.testminlbfgsunit.gradientchecktest(), alglib.testminlmunit.gradientchecktest(), alglib.testhqrndunit.hqrnddiscretetest(), alglib.hqrnd.hqrndrandomize(), alglib.testminqpunit.icqptest(), alglib.testrbfunit.irregularrbftest(), alglib.kmeans.kmeansgenerate(), alglib.testclusteringunit.kmeanssimpletest1(), alglib.testrbfunit.linearitymodelrbftest(), XTest.Main(), alglib.testalglibbasicsunit.performtestsort0(), alglib.testalglibbasicsunit.performtestsort1(), alglib.testalglibbasicsunit.performtestsort2(), alglib.testfftunit.quicktest(), alglib.testsparseunit.rewriteexistingtest(), alglib.testrbfunit.serializationtest(), alglib.testminqpunit.setrandomalgo(), alglib.testminqpunit.simpletest(), alglib.testkmeansunit.simpletest1(), MainTest.spoil_matrix_by_value< T >(), MainTest.spoil_vector_by_value< T >(), alglib.testrbfunit.sqrdegmatrixrbftest(), alglib.testlinlsqrunit.stoppingcriteriatest(), alglib.testautogkunit.testautogk(), alglib.testbasestatunit.testbasestat(), alglib.testmcpdunit.testbc(), alglib.testbdssunit.testbdss(), alglib.testblasunit.testblas(), alglib.testmatinvunit.testcinv(), alglib.testortfacunit.testclqproblem(), alglib.testrcondunit.testcmatrixrcond(), alglib.testrcondunit.testcmatrixtrrcond(), alglib.testsparseunit.testconvertsm(), alglib.testablasunit.testcopy(), alglib.testcqmodelsunit.testcqmodels(), alglib.testortfacunit.testcqrproblem(), alglib.testcreflectionsunit.testcreflections(), alglib.testdensesolverunit.testcsolver(), alglib.testmcpdunit.testec(), alglib.testmcpdunit.testentryexit(), alglib.testmlpbaseunit.testerr(), alglib.testmlpeunit.testerr(), alglib.testfblsunit.testfbls(), alglib.testminbleicunit.testfeasibility(), alglib.testablasunit.testgemm(), alglib.testsparseunit.testgetrow(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testgradient(), alglib.testminbleicunit.testgradientcheck(), alglib.testlsfitunit.testgradientcheck(), alglib.testmlpbaseunit.testhessian(), alglib.testmlptrainunit.testhessian(), alglib.testevdunit.testhevdbiproblem(), alglib.testmatinvunit.testhpdinv(), alglib.testrcondunit.testhpdmatrixrcond(), alglib.testdensesolverunit.testhpdsolver(), alglib.testhqrndunit.testhqrnd(), alglib.testinverseupdateunit.testinverseupdate(), alglib.testnearestneighborunit.testkdtreeserialization(), alglib.testnearestneighborunit.testkdtuniform(), alglib.testmcpdunit.testlc(), alglib.testldaunit.testlda(), alglib.testlinregunit.testlinreg(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlpeunit.testmlpe(), alglib.testmlpbaseunit.testmlpgbsubset(), alglib.testmlptrainunit.testmlpgbsubset(), alglib.testmlptrainunit.testmlptrainclass(), alglib.testmlptrainunit.testmlptrainens(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlptrainensregr(), alglib.testmlptrainunit.testmlpzeroweights(), alglib.testspline1dunit.testmonotonespline(), alglib.testablasunit.testmv(), alglib.testnearestneighborunit.testnearestneighbor(), alglib.testnlequnit.testnleq(), alglib.testodesolverunit.testodesolver(), alglib.testortfacunit.testortfac(), alglib.testpolintunit.testpolint(), alglib.testminbleicunit.testpreconditioning(), alglib.testminlbfgsunit.testpreconditioning(), alglib.testdforestunit.testprocessing(), alglib.testmlpbaseunit.testprocessing(), alglib.testmlptrainunit.testprocessing(), alglib.testmlpeunit.testprocessing(), alglib.testpsplineunit.testpspline(), alglib.testablasunit.testrank1(), alglib.testbasestatunit.testranking(), alglib.testratintunit.testratint(), alglib.testortfacunit.testrbdproblem(), alglib.testreflectionsunit.testreflections(), alglib.testmatinvunit.testrinv(), alglib.testortfacunit.testrlqproblem(), alglib.testrcondunit.testrmatrixrcond(), alglib.testrcondunit.testrmatrixtrrcond(), alglib.testortfacunit.testrqrproblem(), alglib.testdensesolverunit.testrsolver(), alglib.testidwintunit.testrxy(), alglib.testsafesolveunit.testsafesolve(), alglib.testalglibbasicsunit.testserializationfunctions(), alglib.testevdunit.testsevdbiproblem(), alglib.testmcpdunit.testsimple(), alglib.testalglibbasicsunit.testsort2func(), alglib.testmatinvunit.testspdinv(), alglib.testrcondunit.testspdmatrixrcond(), alglib.testdensesolverunit.testspdsolver(), alglib.testspline1dunit.testspline1d(), alglib.testspline2dunit.testspline2d(), alglib.testspline2dunit.testspline2dvf(), alglib.testlsfitunit.testsplinefitting(), alglib.testablasunit.testsyrk(), alglib.testevdunit.testtdevdbiproblem(), alglib.testablasunit.testtrans(), alglib.testtrfacunit.testtrfac(), alglib.testspline3dunit.testtrilinearresample(), alglib.testtrlinsolveunit.testtrlinsolve(), alglib.testablasunit.testtrsm(), alglib.testtsortunit.testtsort(), alglib.testidwintunit.testxy(), alglib.testtsortunit.unset1di(), and alglib.testbdssunit.unset1di().
static double alglib.math.sqr (double X) inline static
Referenced by alglib.testminlmunit.axmb(), alglib.ratint.barycentricdiff1(), alglib.ratint.barycentricdiff2(), alglib.testdforestunit.basictest3(), alglib.testdforestunit.basictest4(), alglib.bessel.besselj0(), alglib.bessel.besselj1(), alglib.bessel.bessely0(), alglib.bessel.bessely1(), alglib.testmincgunit.calciip2(), alglib.testminbleicunit.calciip2(), alglib.testminlbfgsunit.calciip2(), alglib.testhqrndunit.calculatemv(), alglib.testlinregunit.calculatemv(), alglib.testpcaunit.calculatemv(), alglib.testlsfitunit.checkerrorsinparameters(), alglib.creflections.complexgeneratereflection(), alglib.testlincgunit.complexres(), alglib.cqmodels.cqmdebugconstrainedevale(), alglib.cqmodels.cqmdebugconstrainedevalt(), alglib.cqmodels.cqmeval(), alglib.cqmodels.cqmevalx(), alglib.cqmodels.cqmrebuild(), alglib.cqmodels.cqmsolveea(), alglib.cqmodels.cqmxtadx2(), alglib.dforest.dfbuildinternal(), alglib.dforest.dfbuildtreerec(), alglib.dforest.dfrmserror(), alglib.dforest.dfsplitc(), alglib.dforest.dfsplitr(), alglib.spline1d.diffthreepoint(), alglib.testclusteringunit.distfunc(), alglib.bdss.dserraccumulate(), alglib.bdss.dsoptimalsplit2fast(), alglib.normaldistr.errorfunctionc(), alglib.ftbase.ffttwcalc(), alglib.optserv.filterdirection(), alglib.optserv.findfeasiblepoint(), alglib.ftbase.ftbaseprecomputeplanrec(), alglib.variancetests.ftest(), alglib.testmincgunit.funcderiv(), alglib.testminbleicunit.funcderiv(), alglib.testminlbfgsunit.funcderiv(), alglib.testlsfitunit.funcderiv(), alglib.reflections.generatereflection(), alglib.rotations.generaterotation(), alglib.testlsfitunit.getglserror(), alglib.gkq.gkqgenerategaussjacobi(), alglib.gkq.gkqlegendrecalc(), alglib.gq.gqgenerategaussjacobi(), alglib.gq.gqgenerategausslegendre(), alglib.gq.gqgenerategausslobattorec(), alglib.gq.gqgenerategaussradaurec(), alglib.gq.gqgeneraterec(), alglib.densesolver.hpdmatrixcholeskysolveinternal(), alglib.hqrnd.hqrndnormal2(), alglib.hqrnd.hqrndunit2(), alglib.testminqpunit.icqptest(), alglib.idwint.idwbuildmodifiedshepard(), alglib.idwint.idwcalc(), alglib.testratintunit.is1dsolution(), alglib.testspline1dunit.is1dsolution(), alglib.testlinlsqrunit.isitgoodsolution(), alglib.jarquebera.jarqueberastatistic(), alglib.nearestneighbor.kdtreeinitbox(), alglib.nearestneighbor.kdtreequeryaknn(), alglib.nearestneighbor.kdtreequerynnrec(), alglib.nearestneighbor.kdtreequeryrnn(), alglib.testspline1dunit.lconst(), alglib.lincg.lincgsolvesparse(), alglib.linlsqr.linlsqrsolvesparse(), alglib.linreg.lrbuild(), alglib.linreg.lrbuildz(), alglib.linreg.lrinternal(), alglib.linreg.lrlines(), alglib.linreg.lrrmserror(), alglib.mannwhitneyu.mannwhitneyutest(), alglib.linmin.mcstep(), alglib.minbleic.minbleiciteration(), alglib.mincg.mincgiteration(), alglib.mlpbase.mlpactivationfunction(), alglib.mlpbase.mlpchunkedgradient(), alglib.mlpbase.mlpgrad(), alglib.mlpbase.mlpgradn(), alglib.mlpbase.mlphessianbatchinternal(), alglib.mlpbase.mlpinitpreprocessor(), alglib.mlpbase.mlpinternalcalculategradient(), alglib.logit.mnlmcstep(), alglib.nleq.nleqiteration(), alglib.variancetests.onesamplevariancetest(), alglib.basestat.pearsoncorr2(), alglib.correlationtests.pearsoncorrelationsignificance(), alglib.polint.polynomialbuildcheb1(), alglib.polint.polynomialcalccheb1(), alglib.polint.polynomialcalccheb2(), alglib.minbleic.projectpointandunscale(), alglib.testmatgenunit.pythag(), alglib.blas.pythag2(), alglib.apserv.randomnormal(), alglib.testdforestunit.rnormal(), alglib.testclusteringunit.rnormal(), alglib.testkmeansunit.rnormal(), alglib.apserv.safepythag2(), alglib.apserv.safepythag3(), alglib.basestat.samplemoments(), alglib.testlincgunit.sparsetest(), alglib.densesolver.spdmatrixcholeskysolveinternal(), alglib.correlationtests.spearmanrankcorrelationsignificance(), alglib.spline1d.spline1dbuildhermite(), alglib.spline1d.spline1dbuildmonotone(), alglib.spline1d.spline1ddiff(), alglib.spline1d.spline1dgriddiff2cubic(), alglib.testrbfunit.sqrdegmatrixrbftest(), alglib.testlinlsqrunit.stoppingcriteriatest(), alglib.studentttests.studentttest1(), alglib.studentttests.studentttest2(), alglib.testbasestatunit.testbasestat(), alglib.testblasunit.testblas(), alglib.testalglibbasicsunit.testcomplexarithmetics(), alglib.testminbleicunit.testconv(), alglib.testcqmodelsunit.testcqmodels(), alglib.testmlpbaseunit.testerr(), alglib.testmlpeunit.testerr(), alglib.testminbleicunit.testfeasibility(), alglib.testmincgunit.testfunc1(), alglib.testminlbfgsunit.testfunc1(), alglib.testmincgunit.testfunc2(), alglib.testminlbfgsunit.testfunc2(), alglib.testmincgunit.testfunc3(), alglib.testminlbfgsunit.testfunc3(), alglib.testnlequnit.testfunchb1(), alglib.testnlequnit.testfunchbm(), alglib.testnlequnit.testfuncshbm(), alglib.testlsfitunit.testgeneralfitting(), alglib.testgqunit.testgq(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testgradient(), alglib.testhqrndunit.testhqrnd(), alglib.testidwintunit.testidwint(), alglib.testlinregunit.testlinreg(), alglib.testmincgunit.testmincg(), alglib.testminlbfgsunit.testminlbfgs(), alglib.testminlmunit.testminlm(), alglib.testnlequnit.testnleq(), alglib.testidwintunit.testnoisy(), alglib.testodesolverunit.testodesolver(), alglib.testmincgunit.testother(), alglib.testminbleicunit.testother(), alglib.testminlbfgsunit.testother(), alglib.testpcaunit.testpca(), alglib.testlsfitunit.testpolynomialfitting(), alglib.testmincgunit.testpreconditioning(), alglib.testminlbfgsunit.testpreconditioning(), alglib.testlsfitunit.testrationalfitting(), alglib.testlincgunit.testrcorrectness(), alglib.testspline1dunit.testspline1d(), alglib.testlsfitunit.testsplinefitting(), alglib.testablasunit.testtrsm(), alglib.testspline1dunit.testunpack(), alglib.testminlmunit.tryreproducefixedbugs(), alglib.testspline2dunit.twodnumder(), alglib.studentttests.unequalvariancettest(), alglib.testmlpbaseunit.vectordiff(), alglib.blas.vectornorm2(), alglib.testnearestneighborunit.vnorm(), alglib.xblas.xcdot(), and alglib.xblas.xfastpow().
static double alglib.math.abscomplex (complex z) inline static
References alglib.complex.x, and alglib.complex.y.
Referenced by alglib.safesolve.cbasicsolveandupdate(), alglib.testmatinvunit.cmatrixcheckinverse(), alglib.testdensesolverunit.cmatrixchecksolutionm(), alglib.densesolver.cmatrixlusolveinternal(), alglib.densesolver.cmatrixlusolvem(), alglib.densesolver.cmatrixmixedsolvem(), alglib.testrcondunit.cmatrixrefrcond(), alglib.safesolve.cmatrixscaledtrsafesolve(), alglib.densesolver.cmatrixsolvem(), alglib.creflections.complexgeneratereflection(), MainTest.doc_test_complex(), MainTest.doc_test_complex_matrix(), MainTest.doc_test_complex_vector(), alglib.testmatinvunit.hpdmatrixcheckinverse(), alglib.densesolver.hpdmatrixcholeskysolveinternal(), alglib.densesolver.hpdmatrixcholeskysolvem(), alglib.densesolver.hpdmatrixsolvem(), alglib.ap.ishermitian(), XTest.Main(), alglib.testfftunit.quicktest(), alglib.testortfacunit.testclqproblem(), alglib.testtrfacunit.testcluproblem(), alglib.testalglibbasicsunit.testcomplexarithmetics(), alglib.testconvunit.testconv(), alglib.testablasunit.testcopy(), alglib.testcorrunit.testcorr(), alglib.testevdunit.testcort(), alglib.testevdunit.testcproduct(), alglib.testortfacunit.testcqrproblem(), alglib.testcreflectionsunit.testcreflections(), alglib.testdensesolverunit.testcsolver(), alglib.testortfacunit.testctdproblem(), alglib.testmatinvunit.testctrinv(), alglib.testfftunit.testfft(), alglib.testablasunit.testgemm(), alglib.testhblasunit.testhblas(), alglib.testevdunit.testhevdbiproblem(), alglib.testmatgenunit.testmatgen(), alglib.testablasunit.testmv(), alglib.testablasunit.testrank1(), alglib.testsafesolveunit.testsafesolve(), alglib.testablasunit.testsyrk(), alglib.testablasunit.testtrans(), alglib.testtrfacunit.testtrfac(), alglib.testablasunit.testtrsm(), and alglib.testxblasunit.testxblas().
static complex alglib.math.conj (complex z) inline static
References alglib.complex.x, and alglib.complex.y.
Referenced by alglib.ablasf.cmatrixgemmk(), alglib.ablas.cmatrixgemmk(), alglib.testevdunit.cmatrixhermitiansplit(), alglib.ablas.cmatrixlefttrsm2(), alglib.ortfac.cmatrixlq(), alglib.ablas.cmatrixmv(), alglib.ortfac.cmatrixqr(), alglib.ablas.cmatrixrighttrsm2(), alglib.safesolve.cmatrixscaledtrsafesolve(), alglib.ablas.cmatrixsyrk2(), alglib.creflections.complexapplyreflectionfromtheleft(), alglib.creflections.complexapplyreflectionfromtheright(), alglib.creflections.complexgeneratereflection(), alglib.corr.corrc1d(), alglib.corr.corrc1dcircular(), alglib.fft.fftr1d(), alglib.hblas.hermitianmatrixvectormultiply(), alglib.hblas.hermitianrank2update(), alglib.densesolver.hpdbasiccholeskysolve(), alglib.testmatinvunit.hpdmatrixcheckinverse(), alglib.testmatgenunit.ishpd(), alglib.testablasunit.refcmatrixgemm(), alglib.testablasunit.refcmatrixlefttrsm(), alglib.testablasunit.refcmatrixrighttrsm(), alglib.testablasunit.refcmatrixsyrk(), alglib.testcorrunit.refcorrc1d(), alglib.testcorrunit.refcorrc1dcircular(), alglib.testortfacunit.testclqproblem(), alglib.testevdunit.testcort(), alglib.testevdunit.testcproduct(), alglib.testortfacunit.testcqrproblem(), alglib.testcreflectionsunit.testcreflections(), alglib.testortfacunit.testctdproblem(), alglib.testevdunit.testevdset(), alglib.testhblasunit.testhblas(), alglib.testevdunit.testhevdbiproblem(), alglib.testmatgenunit.testmatgen(), alglib.testablasunit.testmv(), alglib.testortfacunit.testortfac(), alglib.testsafesolveunit.testsafesolve(), alglib.testablasunit.testsyrk(), and alglib.testtrfacunit.testtrfac().
static complex alglib.math.csqr (complex z) inline static
References alglib.complex.x, and alglib.complex.y.
static bool alglib.math.isfinite (double d) inline static
static double alglib.math.randomreal () inline static
static int alglib.math.randominteger (int N) inline static
static double alglib.math.sqr (double X) inline static
static double alglib.math.abscomplex (complex z) inline static
static complex alglib.math.conj (complex z) inline static
static complex alglib.math.csqr (complex z) inline static
Member Data Documentation
static System Random alglib.math.rndobject = new System.Random(System.DateTime.Now.Millisecond + 1000*System.DateTime.Now.Second + 60*1000*System.DateTime.Now.Minute) static
Referenced by _Test.call_unittest(), alglib.math.randominteger(), and alglib.math.randomreal().
const double alglib.math.machineepsilon = 5E-16
Referenced by alglib.testclusteringunit.advancedahctests(), alglib.airyf.airy(), alglib.autogk.autogkinternaliteration(), alglib.hsschur.aux2x2schur(), alglib.ratint.barycentricnormalize(), alglib.testsparseunit.basicfunctestcrs(), alglib.testspline3dunit.basictest(), alglib.testdforestunit.basictest1(), alglib.testdforestunit.basictest2(), alglib.testdforestunit.basictest3(), alglib.testdforestunit.basictest5(), alglib.bessel.besseljn(), alglib.bessel.besselkn(), alglib.spline1d.bisectmethod(), alglib.testgqunit.buildgausshermitequadrature(), alglib.testgqunit.buildgaussjacobiquadrature(), alglib.testgqunit.buildgausslaguerrequadrature(), alglib.testgqunit.buildgausslegendrequadrature(), alglib.testlsfitunit.checkerrorsinparameters(), alglib.testmatinvunit.cmatrixcheckinverse(), alglib.testmatinvunit.cmatrixcheckinversesingular(), alglib.testdensesolverunit.cmatrixchecksingularm(), alglib.testdensesolverunit.cmatrixchecksolutionm(), alglib.testsparseunit.copyfunctest(), alglib.cqmodels.cqmevalx(), alglib.testminqpunit.ecqptest(), alglib.elliptic.ellipticintegralkhighprecision(), alglib.testclusteringunit.errorsinmerges(), alglib.expintegrals.exponentialintegralen(), alglib.optserv.findfeasiblepoint(), alglib.lda.fisherldan(), alglib.reflections.generatereflection(), alglib.gkq.gkqgenerategausslegendre(), alglib.gkq.gkqlegendretbl(), alglib.testmatinvunit.hpdmatrixcheckinverse(), alglib.trigintegrals.hyperbolicsinecosineintegrals(), alglib.idwint.idwinternalsolver(), alglib.ibetaf.incompletebeta(), alglib.ibetaf.incompletebetafe(), alglib.ibetaf.incompletebetafe2(), alglib.ibetaf.incompletebetaps(), alglib.elliptic.incompleteellipticintegrale(), alglib.elliptic.incompleteellipticintegralk(), alglib.hsschur.internalauxschur(), alglib.hsschur.internalschurdecomposition(), alglib.ibetaf.invincompletebeta(), alglib.testlsfitunit.isglssolution(), alglib.testlinlsqrunit.isitgoodsolution(), alglib.jacobianelliptic.jacobianellipticfunctions(), alglib.testclusteringunit.kmeansinfinitelooptest(), alglib.testsparseunit.linearfunctionsmmtest(), alglib.testsparseunit.linearfunctionssmmtest(), alglib.testsparseunit.linearfunctionsstest(), alglib.testsparseunit.linearfunctionstest(), alglib.linlsqr.linlsqrcreate(), alglib.linreg.lrinternal(), alglib.linreg.lrlines(), alglib.minbleic.minbleiciteration(), alglib.logit.mnltrainh(), alglib.minbleic.rebuildcexe(), alglib.testmatinvunit.rmatrixcheckinverse(), alglib.testmatinvunit.rmatrixcheckinversesingular(), alglib.testdensesolverunit.rmatrixchecksingularm(), alglib.testdensesolverunit.rmatrixchecksolutionm(), alglib.densesolver.rmatrixsolvels(), alglib.trlinsolve.safesolvetriangular(), alglib.testmatinvunit.spdmatrixcheckinverse(), alglib.testminqpunit.specialicqptests(), alglib.spline1d.spline1dbuildmonotone(), alglib.studenttdistr.studenttdistribution(), alglib.testablasunit.testablas(), alglib.testautogkunit.testautogk(), alglib.testbasestatunit.testbasestat(), alglib.testbdssunit.testbdss(), alglib.testbdsvdunit.testbdsvd(), alglib.testblasunit.testblas(), alglib.testortfacunit.testclqproblem(), alglib.testalglibbasicsunit.testcomplexarithmetics(), alglib.testconvunit.testconv(), alglib.testablasunit.testcopy(), alglib.testcorrunit.testcorr(), alglib.testcqmodelsunit.testcqmodels(), alglib.testortfacunit.testcqrproblem(), alglib.testcreflectionsunit.testcreflections(), alglib.testdensesolverunit.testcsolver(), alglib.testidwintunit.testdegree(), alglib.testdensesolverunit.testdensesolver(), alglib.testfiltersunit.testema(), alglib.testmatgenunit.testeult(), alglib.testevdunit.testevd(), alglib.testfblsunit.testfbls(), alglib.testfftunit.testfft(), alglib.testfhtunit.testfht(), alglib.testgammafuncunit.testgammafunc(), alglib.testablasunit.testgemm(), alglib.testlsfitunit.testgeneralfitting(), alglib.testgkqunit.testgkq(), alglib.testgqunit.testgq(), alglib.testhblasunit.testhblas(), alglib.testmatinvunit.testhpdinv(), alglib.testhqrndunit.testhqrnd(), alglib.testmlpbaseunit.testinformational(), alglib.testmlptrainunit.testinformational(), alglib.testnearestneighborunit.testkdtreeserialization(), alglib.testnearestneighborunit.testkdtuniform(), alglib.testmcpdunit.testlc(), alglib.testlinregunit.testlinreg(), alglib.testspline2dunit.testlintrans(), alglib.testspline3dunit.testlintrans(), alglib.testfiltersunit.testlrma(), alglib.testmatgenunit.testmatgen(), alglib.testmatinvunit.testmatinv(), alglib.testminlmunit.testminlm(), alglib.testspline1dunit.testmonotonespline(), alglib.testablasunit.testmv(), alglib.testnlequnit.testnleq(), alglib.testortfacunit.testortfac(), alglib.testmincgunit.testother(), alglib.testminbleicunit.testother(), alglib.testminlbfgsunit.testother(), alglib.testpcaunit.testpca(), alglib.testpolintunit.testpolint(), alglib.testlsfitunit.testpolynomialfitting(), alglib.testdforestunit.testprocessing(), alglib.testmlpbaseunit.testprocessing(), alglib.testmlptrainunit.testprocessing(), alglib.testmlpeunit.testprocessing(), alglib.testpsplineunit.testpspline(), alglib.testablasunit.testrank1(), alglib.testbasestatunit.testranking(), alglib.testratintunit.testratint(), alglib.testlsfitunit.testrationalfitting(), alglib.testortfacunit.testrbdproblem(), alglib.testlincgunit.testrcorrectness(), alglib.testreflectionsunit.testreflections(), alglib.testortfacunit.testrlqproblem(), alglib.testortfacunit.testrqrproblem(), alglib.testdensesolverunit.testrsolver(), alglib.testidwintunit.testrxy(), alglib.testsafesolveunit.testsafesolve(), alglib.testsblasunit.testsblas(), alglib.testschurunit.testschur(), alglib.testfiltersunit.testsma(), alglib.testspdgevdunit.testspdgevd(), alglib.testmatinvunit.testspdinv(), alglib.testspline1dunit.testspline1d(), alglib.testspline2dunit.testspline2d(), alglib.testspline2dunit.testspline2dvf(), alglib.testlsfitunit.testsplinefitting(), alglib.testsvdunit.testsvd(), alglib.testablasunit.testsyrk(), alglib.testablasunit.testtrans(), alglib.testtrfacunit.testtrfac(), alglib.testspline3dunit.testtrilinearresample(), alglib.testtrlinsolveunit.testtrlinsolve(), alglib.testablasunit.testtrsm(), alglib.testspline1dunit.testunpack(), alglib.testspline2dunit.testunpack(), alglib.testspline3dunit.testunpack(), alglib.testldaunit.testwn(), alglib.testxblasunit.testxblas(), alglib.testidwintunit.testxy(), and alglib.xblas.xsum().
const double alglib.math.maxrealnumber = 1E300
Referenced by alglib.airyf.airy(), alglib.bessel.besselkn(), alglib.betaf.beta(), alglib.optserv.calculatestepbound(), alglib.safesolve.cmatrixscaledtrsafesolve(), alglib.creflections.complexgeneratereflection(), alglib.conv.convc1dx(), alglib.conv.convr1dx(), alglib.dforest.dfsplitc(), alglib.dforest.dfsplitr(), alglib.bdss.dserraccumulate(), alglib.bdss.dsgetmeanmindistance(), alglib.bdss.dsoptimalsplit2(), alglib.bdss.dsoptimalsplit2fast(), alglib.bdss.dsoptimalsplitk(), alglib.bdss.dssplitk(), alglib.testclusteringunit.errorsinmerges(), alglib.reflections.generatereflection(), alglib.gkq.gkqgenerategaussjacobi(), alglib.gq.gqgenerategaussjacobi(), alglib.gq.gqgenerategausslaguerre(), alglib.trigintegrals.hyperbolicsinecosineintegrals(), alglib.ibetaf.incompletebeta(), alglib.ibetaf.incompletebetaps(), alglib.nleq.increaselambda(), alglib.ibetaf.invincompletebeta(), alglib.normaldistr.invnormaldistribution(), alglib.studenttdistr.invstudenttdistribution(), alglib.kmeans.kmeansgenerate(), alglib.testclusteringunit.kmeanssimpletest1(), alglib.nleq.nleqiteration(), alglib.psif.psi(), alglib.safesolve.rmatrixscaledtrsafesolve(), alglib.mlpbase.safecrossentropy(), alglib.apserv.saferdiv(), alglib.kmeans.selectcenterpp(), alglib.testkmeansunit.simpletest1(), alglib.trigintegrals.sinecosineintegrals(), alglib.testblasunit.testblas(), alglib.testrcondunit.testcmatrixrcond(), alglib.testrcondunit.testcmatrixtrrcond(), alglib.testcreflectionsunit.testcreflections(), alglib.testmlpbaseunit.testerr(), alglib.testmlpeunit.testerr(), alglib.testmincgunit.testfunc1(), alglib.testminlbfgsunit.testfunc1(), alglib.testmincgunit.testfunc2(), alglib.testminlbfgsunit.testfunc2(), alglib.testmincgunit.testfunc3(), alglib.testminlbfgsunit.testfunc3(), alglib.testlsfitunit.testgeneralfitting(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testgradient(), alglib.testrcondunit.testhpdmatrixrcond(), alglib.testalglibbasicsunit.testieeespecial(), alglib.testminlmunit.testminlm(), alglib.testmlptrainunit.testmlpxorcls(), alglib.testnlequnit.testnleq(), alglib.testmincgunit.testother(), alglib.testminbleicunit.testother(), alglib.testminlbfgsunit.testother(), alglib.testpolintunit.testpolint(), alglib.testratintunit.testratint(), alglib.testlsfitunit.testrationalfitting(), alglib.testreflectionsunit.testreflections(), alglib.testrcondunit.testrmatrixrcond(), alglib.testrcondunit.testrmatrixtrrcond(), alglib.testsafesolveunit.testsafesolve(), alglib.testrcondunit.testspdmatrixrcond(), and alglib.testxblasunit.testxblas().
const double alglib.math.minrealnumber = 1E-300
Referenced by alglib.creflections.complexgeneratereflection(), alglib.nleq.decreaselambda(), alglib.dforest.dfavgce(), alglib.dforest.dfbuildinternal(), alglib.reflections.generatereflection(), alglib.ibetaf.incompletebeta(), alglib.ibetaf.incompletebetaps(), alglib.hsschur.internalauxschur(), alglib.hsschur.internalschurdecomposition(), alglib.ibetaf.invincompletebeta(), alglib.logit.mnlavgce(), alglib.logit.mnltrainh(), alglib.polint.polynomialcalccheb1(), alglib.polint.polynomialcalccheb2(), alglib.polint.polynomialcalceqdist(), alglib.mlpbase.safecrossentropy(), alglib.apserv.saferdiv(), alglib.trlinsolve.safesolvetriangular(), alglib.testblasunit.testblas(), alglib.testlsfitunit.testgeneralfitting(), alglib.testalglibbasicsunit.testieeespecial(), alglib.testratintunit.testratint(), and alglib.testreflectionsunit.testreflections().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/ap.cs