IGLib: NUnit.Framework.Internal.TestMethodSignatureTests Class Reference
NUnit.Framework.Internal.TestMethodSignatureTests Class Reference
Public Member Functions
void InstanceTestMethodIsRunnable ()
void StaticTestMethodIsRunnable ()
void TestMethodWithoutParametersWithArgumentsProvidedIsNotRunnable ()
void TestMethodWithArgumentsNotProvidedIsNotRunnable ()
void TestMethodHasAttributesAppliedCorrectlyEvenIfNotRunnable ()
void TestMethodWithArgumentsProvidedIsRunnable ()
void TestMethodWithWrongNumberOfArgumentsProvidedIsNotRunnable ()
void TestMethodWithWrongArgumentTypesProvidedGivesError ()
void StaticTestMethodWithArgumentsNotProvidedIsNotRunnable ()
void StaticTestMethodWithArgumentsProvidedIsRunnable ()
void StaticTestMethodWithWrongNumberOfArgumentsProvidedIsNotRunnable ()
void StaticTestMethodWithWrongArgumentTypesProvidedGivesError ()
void TestMethodWithConvertibleArgumentsIsRunnable ()
void TestMethodWithNonConvertibleArgumentsGivesError ()
void ProtectedTestMethodIsNotRunnable ()
void PrivateTestMethodIsNotRunnable ()
void TestMethodWithReturnTypeIsNotRunnable ()
void TestMethodWithExpectedReturnTypeIsRunnable ()
void TestMethodWithMultipleTestCasesExecutesMultipleTimes ()
void TestMethodWithMultipleTestCasesUsesCorrectNames ()
void RunningTestsThroughFixtureGivesCorrectResults ()
Static Private Attributes
static Type fixtureType = typeof(TestMethodSignatureFixture)
Member Function Documentation
void NUnit.Framework.Internal.TestMethodSignatureTests.InstanceTestMethodIsRunnable () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.StaticTestMethodIsRunnable () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithoutParametersWithArgumentsProvidedIsNotRunnable () inline
References NUnit.TestUtilities.TestAssert.ChildNotRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithArgumentsNotProvidedIsNotRunnable () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodHasAttributesAppliedCorrectlyEvenIfNotRunnable () inline
References NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), NUnit.Framework.Internal.PropertyNames.MaxTime, NUnit.Framework.Internal.PropertyNames.SkipReason, and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithArgumentsProvidedIsRunnable () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithWrongNumberOfArgumentsProvidedIsNotRunnable () inline
References NUnit.TestUtilities.TestAssert.ChildNotRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithWrongArgumentTypesProvidedGivesError () inline
References NUnit.Framework.Interfaces.ResultState.Error, and NUnit.TestUtilities.TestAssert.IsRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.StaticTestMethodWithArgumentsNotProvidedIsNotRunnable () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.StaticTestMethodWithArgumentsProvidedIsRunnable () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.StaticTestMethodWithWrongNumberOfArgumentsProvidedIsNotRunnable () inline
References NUnit.TestUtilities.TestAssert.ChildNotRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.StaticTestMethodWithWrongArgumentTypesProvidedGivesError () inline
References NUnit.Framework.Interfaces.ResultState.Error, and NUnit.TestUtilities.TestAssert.IsRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithConvertibleArgumentsIsRunnable () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithNonConvertibleArgumentsGivesError () inline
References NUnit.Framework.Interfaces.ResultState.Error, and NUnit.TestUtilities.TestAssert.IsRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.ProtectedTestMethodIsNotRunnable () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.PrivateTestMethodIsNotRunnable () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithReturnTypeIsNotRunnable () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithExpectedReturnTypeIsRunnable () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
void NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithMultipleTestCasesExecutesMultipleTimes () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunParameterizedMethodSuite(), NUnit.Framework.Interfaces.ResultState.Success, NUnit.TestUtilities.ResultSummary.TestsRun, and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithMultipleTestCasesUsesCorrectNames () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.FullName, NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Has.Member(), NUnit.Framework.Internal.Test.Name, NUnit.Framework.Internal.TestSuite.TestCaseCount, and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.TestMethodSignatureTests.RunningTestsThroughFixtureGivesCorrectResults () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.Errors, NUnit.TestUtilities.ResultSummary.Failed, NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.Failures, NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.NotRunnable, NUnit.TestUtilities.ResultSummary.ResultCount, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestUtilities.ResultSummary.Skipped, NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.Tests, NUnit.TestUtilities.ResultSummary.TestsRun, and NUnit.Framework.Assert.That().
Member Data Documentation
Type NUnit.Framework.Internal.TestMethodSignatureTests.fixtureType = typeof(TestMethodSignatureFixture) static private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/TestMethodSignatureTests.cs