IGLib: IG.Script._01LPSimple Class Reference
IG.Script._01LPSimple Class Reference
Solves a simple LP program using the simplex algorithm.
Static Public Member Functions
static void Run (string[] arguments)
Detailed Description
Solves a simple LP program using the simplex algorithm.
Member Function Documentation
static void IG.Script._01LPSimple.Run (string[] arguments) inline static
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Gr.PlotZedgraphCurve.LinesVisible, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.Gr.PlotZedgraphCurve.PointColor, IG.Gr.PlotZedgraphCurve.PointSize, IG.Gr.PlotZedgraphCurve.PointsVisible, IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot(), IG.Gr.PlotterZedGraph.Title, IG.Gr.PlotterZedGraph.Window, IG.Gr.PlotterZedGraph.XAxisScaleFont, and IG.Gr.PlotterZedGraph.YAxisScaleFont.
Referenced by IG.Script.AppMarkoPetekExt.App01LPSimple().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/extended/Guest_Marko_Petek_LibExt/application/scripts/01LPSimple.cs