IGLib: XMLEncryption.Form1 Class Reference
XMLEncryption.Form1 Class Reference
Public Member Functions
Form1 ()
Form1 ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void encryptToolStripMenuItem_Click (object sender, EventArgs e)
void decryptToolStripMenuItem_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void encryptToolStripMenuItem_Click (object sender, EventArgs e)
void decryptToolStripMenuItem_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
RSACryptoServiceProvider rsa
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.SplitContainer splitContainer1
System.Windows.Forms.TextBox txtXml
System.Windows.Forms.TextBox txtEncryptedXml
System.Windows.Forms.StatusStrip statusStrip1
System.Windows.Forms.MenuStrip menuStrip1
System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem encryptToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem decryptToolStripMenuItem
System.Windows.Forms.Label warningLbl
Detailed Description
Constructor & Destructor Documentation
XMLEncryption.Form1.Form1 () inline
References XMLEncryption.Form1.InitializeComponent().
XMLEncryption.Form1.Form1 () inline
References XMLEncryption.Form1.InitializeComponent().
Member Function Documentation
void XMLEncryption.Form1.encryptToolStripMenuItem_Click (object sender, EventArgs e) inline private
Loads the Xml into an Xml document and encrypts the full document from the root it does not cover selecting and encrypting individual nodes in the document however the place where this code would be placed is highlighted.
It also doesn't cover loading or saving the asymmetric keys, the key is created in the encrypt method and because of the way the application works the same key is used to decrypt a new key is generated every time an encyption is ran
Parameters
sender
e
References XMLEncryption.Form1.txtEncryptedXml, and XMLEncryption.Form1.txtXml.
Referenced by XMLEncryption.Form1.InitializeComponent().
void XMLEncryption.Form1.decryptToolStripMenuItem_Click (object sender, EventArgs e) inline private
Parameters
sender
e
References XMLEncryption.Form1.txtEncryptedXml, and XMLEncryption.Form1.txtXml.
Referenced by XMLEncryption.Form1.InitializeComponent().
override void XMLEncryption.Form1.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References XMLEncryption.Form1.components.
void XMLEncryption.Form1.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References XMLEncryption.Form1.decryptToolStripMenuItem, XMLEncryption.Form1.decryptToolStripMenuItem_Click(), XMLEncryption.Form1.encryptToolStripMenuItem, XMLEncryption.Form1.encryptToolStripMenuItem_Click(), XMLEncryption.Form1.fileToolStripMenuItem, XMLEncryption.Form1.menuStrip1, XMLEncryption.Form1.splitContainer1, XMLEncryption.Form1.statusStrip1, XMLEncryption.Form1.txtEncryptedXml, and XMLEncryption.Form1.txtXml.
Referenced by XMLEncryption.Form1.Form1().
void XMLEncryption.Form1.encryptToolStripMenuItem_Click (object sender, EventArgs e) inline private
Loads the Xml into an Xml document and encrypts the full document from the root it does not cover selecting and encrypting individual nodes in the document however the place where this code would be placed is highlighted.
It also doesn't cover loading or saving the asymmetric keys, the key is created in the encrypt method and because of the way the application works the same key is used to decrypt a new key is generated every time an encyption is ran
Parameters
sender
e
References XMLEncryption.Form1.txtEncryptedXml, and XMLEncryption.Form1.txtXml.
void XMLEncryption.Form1.decryptToolStripMenuItem_Click (object sender, EventArgs e) inline private
Parameters
sender
e
References XMLEncryption.Form1.txtEncryptedXml, and XMLEncryption.Form1.txtXml.
override void XMLEncryption.Form1.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References XMLEncryption.Form1.components.
void XMLEncryption.Form1.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References XMLEncryption.Form1.decryptToolStripMenuItem, XMLEncryption.Form1.decryptToolStripMenuItem_Click(), XMLEncryption.Form1.encryptToolStripMenuItem, XMLEncryption.Form1.encryptToolStripMenuItem_Click(), XMLEncryption.Form1.fileToolStripMenuItem, XMLEncryption.Form1.menuStrip1, XMLEncryption.Form1.splitContainer1, XMLEncryption.Form1.statusStrip1, XMLEncryption.Form1.txtEncryptedXml, XMLEncryption.Form1.txtXml, and XMLEncryption.Form1.warningLbl.
Member Data Documentation
RSACryptoServiceProvider XMLEncryption.Form1.rsa private
RSA asymmetric algorithim used to encrypt the session key, key is generated during the encryption process in this example a key is generated however in an actual application you will need to load and save the keys as appropriate
System ComponentModel IContainer XMLEncryption.Form1.components = null private
Required designer variable.
Referenced by XMLEncryption.Form1.Dispose().
System Windows Forms SplitContainer XMLEncryption.Form1.splitContainer1 private
Referenced by XMLEncryption.Form1.InitializeComponent().
System Windows Forms TextBox XMLEncryption.Form1.txtXml private
Referenced by XMLEncryption.Form1.decryptToolStripMenuItem_Click(), XMLEncryption.Form1.encryptToolStripMenuItem_Click(), and XMLEncryption.Form1.InitializeComponent().
System Windows Forms TextBox XMLEncryption.Form1.txtEncryptedXml private
Referenced by XMLEncryption.Form1.decryptToolStripMenuItem_Click(), XMLEncryption.Form1.encryptToolStripMenuItem_Click(), and XMLEncryption.Form1.InitializeComponent().
System Windows Forms StatusStrip XMLEncryption.Form1.statusStrip1 private
Referenced by XMLEncryption.Form1.InitializeComponent().
System Windows Forms MenuStrip XMLEncryption.Form1.menuStrip1 private
Referenced by XMLEncryption.Form1.InitializeComponent().
System Windows Forms ToolStripMenuItem XMLEncryption.Form1.fileToolStripMenuItem private
Referenced by XMLEncryption.Form1.InitializeComponent().
System Windows Forms ToolStripMenuItem XMLEncryption.Form1.encryptToolStripMenuItem private
Referenced by XMLEncryption.Form1.InitializeComponent().
System Windows Forms ToolStripMenuItem XMLEncryption.Form1.decryptToolStripMenuItem private
Referenced by XMLEncryption.Form1.InitializeComponent().
System.Windows.Forms.Label XMLEncryption.Form1.warningLbl private
Referenced by XMLEncryption.Form1.InitializeComponent().
The documentation for this class was generated from the following files:
igtest/iglib_sandbox/encryption/XMLEncryption/Backup/Form1.cs
igtest/iglib_sandbox/encryption/XMLEncryption/Backup/Form1.Designer.cs