IGLib: TestEvaluator.Test Class Reference
TestEvaluator.Test Class Reference
Summary description for Class1.
Static Private Member Functions
static void Main (string[] args)
The main entry point for the application.
static void Main (string[] args)
The main entry point for the application.
Detailed Description
Summary description for Class1.
Member Function Documentation
static void TestEvaluator.Test.Main (string[] args) inline static private
The main entry point for the application.
References ADOGuy.Evaluator.Evaluate(), ADOGuy.Evaluator.EvaluateBool(), ADOGuy.Evaluator.EvaluateInt(), ADOGuy.Evaluator.EvaluateString(), ADOGuy.Evaluator.EvaluateToBool(), ADOGuy.Evaluator.EvaluateToInteger(), ADOGuy.Evaluator.EvaluateToObject(), and ADOGuy.Evaluator.EvaluateToString().
static void TestEvaluator.Test.Main (string[] args) inline static private
The main entry point for the application.
References ADOGuy.Evaluator.Evaluate(), ADOGuy.Evaluator.EvaluateBool(), ADOGuy.Evaluator.EvaluateInt(), ADOGuy.Evaluator.EvaluateString(), ADOGuy.Evaluator.EvaluateToBool(), ADOGuy.Evaluator.EvaluateToInteger(), ADOGuy.Evaluator.EvaluateToObject(), and ADOGuy.Evaluator.EvaluateToString().
The documentation for this class was generated from the following file:
igtest/tmp_CSharpEvaluator/Backup/TestEvaluator/Test.cs