IGLib: alglib.testminqpunit Class Reference
alglib.testminqpunit Class Reference
Static Public Member Functions
static bool testminqp (bool silent)
static bool simpletest ()
static bool functest1 ()
static bool functest2 ()
static bool consoletest ()
static bool testminqp (bool silent)
static bool _pexec_testminqp (bool silent)
static bool simpletest ()
static bool functest1 ()
static bool functest2 ()
static bool consoletest ()
static bool choleskytests ()
static bool bleictests ()
Static Private Member Functions
static bool ecqptest ()
static bool icqptest ()
static double projectedantigradnorm (int n, double[] x, double[] g, double[] bndl, double[] bndu)
static bool ecqptest ()
static bool icqptest ()
static bool specialicqptests ()
static double projectedantigradnorm (int n, double[] x, double[] g, double[] bndl, double[] bndu)
static void setrandomalgo (minqp.minqpstate s)
Member Function Documentation
static bool alglib.testminqpunit.testminqp (bool silent) inline static
References alglib.testminqpunit.ecqptest(), alglib.testminqpunit.functest1(), alglib.testminqpunit.functest2(), alglib.testminqpunit.icqptest(), and alglib.testminqpunit.simpletest().
Referenced by alglib.testminqpunit._pexec_testminqp(), and _Test.Main().
static bool alglib.testminqpunit.simpletest () inline static
References alglib.apserv.boundval(), alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetbc(), alglib.minqp.minqpsetorigin(), alglib.minqp.minqpsetquadraticterm(), alglib.minqp.minqpsetstartingpoint(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testminqpunit.testminqp().
static bool alglib.testminqpunit.functest1 () inline static
References alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetlinearterm(), alglib.minqp.minqpsetorigin(), alglib.minqp.minqpsetquadraticterm(), alglib.minqp.minqpsetstartingpoint(), alglib.math.randomreal(), and alglib.matgen.spdmatrixrndcond().
Referenced by alglib.testminqpunit.testminqp().
static bool alglib.testminqpunit.functest2 () inline static
References alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetbc(), alglib.minqp.minqpsetlinearterm(), alglib.minqp.minqpsetorigin(), alglib.minqp.minqpsetquadraticterm(), alglib.minqp.minqpsetstartingpoint(), alglib.testminqpunit.projectedantigradnorm(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.ablas.rmatrixmv(), and alglib.matgen.spdmatrixrndcond().
Referenced by alglib.testminqpunit.testminqp().
static bool alglib.testminqpunit.consoletest () inline static
References alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetbc(), alglib.minqp.minqpsetlinearterm(), alglib.minqp.minqpsetorigin(), alglib.minqp.minqpsetquadraticterm(), alglib.testminqpunit.projectedantigradnorm(), and alglib.ablas.rmatrixmv().
static bool alglib.testminqpunit.ecqptest () inline static private
References alglib.math.machineepsilon, alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetbc(), alglib.minqp.minqpsetlc(), alglib.minqp.minqpsetlinearterm(), alglib.minqp.minqpsetorigin(), alglib.minqp.minqpsetquadraticterm(), alglib.minqp.minqpsetstartingpoint(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.ablas.rmatrixcopy(), alglib.matgen.rmatrixrndorthogonal(), alglib.ablas.rmatrixsyrk(), and alglib.matgen.spdmatrixrndcond().
Referenced by alglib.testminqpunit.testminqp().
static bool alglib.testminqpunit.icqptest () inline static private
References alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetbc(), alglib.minqp.minqpsetlc(), alglib.minqp.minqpsetlinearterm(), alglib.minqp.minqpsetorigin(), alglib.minqp.minqpsetquadraticterm(), alglib.minqp.minqpsetstartingpoint(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.matgen.rmatrixrndcond(), alglib.matgen.rmatrixrndorthogonal(), alglib.ablas.rmatrixsyrk(), alglib.ablas.rmatrixtranspose(), alglib.matgen.spdmatrixrndcond(), and alglib.math.sqr().
Referenced by alglib.testminqpunit.testminqp().
static double alglib.testminqpunit.projectedantigradnorm (int n, double[] x, double[] g, double[] bndl, double[] bndu) inline static private
References alglib.ap.assert().
Referenced by alglib.testminqpunit.consoletest(), and alglib.testminqpunit.functest2().
static bool alglib.testminqpunit.testminqp (bool silent) inline static
References alglib.testminqpunit.bleictests(), alglib.testminqpunit.choleskytests(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.functest1(), alglib.testminqpunit.functest2(), alglib.testminqpunit.icqptest(), alglib.testminqpunit.simpletest(), and alglib.testminqpunit.specialicqptests().
static bool alglib.testminqpunit._pexec_testminqp (bool silent) inline static
References alglib.testminqpunit.testminqp().
Referenced by _Test.Main().
static bool alglib.testminqpunit.simpletest () inline static
References alglib.apserv.boundval(), alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetbc(), alglib.minqp.minqpsetorigin(), alglib.minqp.minqpsetquadraticterm(), alglib.minqp.minqpsetstartingpoint(), alglib.math.randominteger(), alglib.math.randomreal(), and alglib.testminqpunit.setrandomalgo().
static bool alglib.testminqpunit.functest1 () inline static
References alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetlinearterm(), alglib.minqp.minqpsetorigin(), alglib.minqp.minqpsetquadraticterm(), alglib.minqp.minqpsetstartingpoint(), alglib.math.randomreal(), alglib.testminqpunit.setrandomalgo(), and alglib.matgen.spdmatrixrndcond().
static bool alglib.testminqpunit.functest2 () inline static
References alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetbc(), alglib.minqp.minqpsetlinearterm(), alglib.minqp.minqpsetorigin(), alglib.minqp.minqpsetquadraticterm(), alglib.minqp.minqpsetstartingpoint(), alglib.testminqpunit.projectedantigradnorm(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.ablas.rmatrixmv(), alglib.testminqpunit.setrandomalgo(), and alglib.matgen.spdmatrixrndcond().
static bool alglib.testminqpunit.consoletest () inline static
References alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetbc(), alglib.minqp.minqpsetlinearterm(), alglib.minqp.minqpsetorigin(), alglib.minqp.minqpsetquadraticterm(), alglib.testminqpunit.projectedantigradnorm(), alglib.ablas.rmatrixmv(), and alglib.testminqpunit.setrandomalgo().
static bool alglib.testminqpunit.choleskytests () inline static
References alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetalgocholesky(), alglib.minqp.minqpsetbc(), alglib.minqp.minqpsetquadraticterm(), alglib.minqp.minqpsetquadratictermsparse(), alglib.minqp.minqpsetstartingpoint(), alglib.math.randomreal(), alglib.apserv.seterrorflag(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
Referenced by alglib.testminqpunit.testminqp().
static bool alglib.testminqpunit.bleictests () inline static
References alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetalgobleic(), alglib.minqp.minqpsetbc(), alglib.minqp.minqpsetlc(), alglib.minqp.minqpsetlinearterm(), alglib.minqp.minqpsetquadraticterm(), alglib.minqp.minqpsetquadratictermsparse(), alglib.minqp.minqpsetscale(), alglib.minqp.minqpsetstartingpoint(), alglib.math.randominteger(), alglib.apserv.randomnormal(), alglib.math.randomreal(), alglib.apserv.seterrorflag(), alglib.sparse.sparsecreate(), alglib.sparse.sparseset(), and alglib.matgen.spdmatrixrndcond().
Referenced by alglib.testminqpunit.testminqp().
static bool alglib.testminqpunit.ecqptest () inline static private
References alglib.math.machineepsilon, alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetbc(), alglib.minqp.minqpsetlc(), alglib.minqp.minqpsetlinearterm(), alglib.minqp.minqpsetorigin(), alglib.minqp.minqpsetquadraticterm(), alglib.minqp.minqpsetstartingpoint(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.randomunit(), alglib.ablas.rmatrixcopy(), alglib.matgen.rmatrixrndorthogonal(), alglib.ablas.rmatrixsyrk(), alglib.apserv.seterrorflag(), alglib.testminqpunit.setrandomalgo(), and alglib.matgen.spdmatrixrndcond().
static bool alglib.testminqpunit.icqptest () inline static private
References alglib.apserv.boundval(), alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetbc(), alglib.minqp.minqpsetlc(), alglib.minqp.minqpsetlinearterm(), alglib.minqp.minqpsetorigin(), alglib.minqp.minqpsetquadraticterm(), alglib.minqp.minqpsetstartingpoint(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.matgen.rmatrixrndcond(), alglib.matgen.rmatrixrndorthogonal(), alglib.ablas.rmatrixsyrk(), alglib.ablas.rmatrixtranspose(), alglib.apserv.seterrorflag(), alglib.testminqpunit.setrandomalgo(), alglib.matgen.spdmatrixrndcond(), and alglib.math.sqr().
static bool alglib.testminqpunit.specialicqptests () inline static private
References alglib.math.machineepsilon, alglib.minqp.minqpcreate(), alglib.minqp.minqpoptimize(), alglib.minqp.minqpresults(), alglib.minqp.minqpsetbc(), alglib.minqp.minqpsetlc(), alglib.minqp.minqpsetlinearterm(), alglib.minqp.minqpsetquadraticterm(), alglib.minqp.minqpsetstartingpoint(), and alglib.testminqpunit.setrandomalgo().
Referenced by alglib.testminqpunit.testminqp().
static double alglib.testminqpunit.projectedantigradnorm (int n, double[] x, double[] g, double[] bndl, double[] bndu) inline static private
References alglib.ap.assert().
static void alglib.testminqpunit.setrandomalgo (minqp.minqpstate s) inline static private
References alglib.minqp.minqpsetalgobleic(), alglib.minqp.minqpsetalgocholesky(), and alglib.math.randominteger().
Referenced by alglib.testminqpunit.consoletest(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.functest1(), alglib.testminqpunit.functest2(), alglib.testminqpunit.icqptest(), alglib.testminqpunit.simpletest(), and alglib.testminqpunit.specialicqptests().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs