IGLib: NUnit.Framework.Syntax.ThrowsTests Class Reference
NUnit.Framework.Syntax.ThrowsTests Class Reference
Classes
class MyClass
Public Member Functions
void ThrowsException ()
void ThrowsExceptionWithConstraint ()
void ThrowsExceptionTypeOf ()
void ThrowsTypeOf ()
void ThrowsTypeOfAndConstraint ()
void ThrowsExceptionTypeOfAndConstraint ()
void ThrowsTypeOfWithConstraint ()
void ThrowsInstanceOf ()
void ThrowsExceptionInstanceOf ()
void DelegateThrowsException ()
void LambdaThrowsException ()
void LambdaThrowsExceptionWithMessage ()
Member Function Documentation
void NUnit.Framework.Syntax.ThrowsTests.ThrowsException () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Throws.Exception, and NUnit.Framework.Constraints.IResolveConstraint.Resolve().
void NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionWithConstraint () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintExpression.EqualTo(), NUnit.Framework.Throws.Exception, NUnit.Framework.Constraints.ConstraintExpression.Property(), NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Constraints.ConstraintExpression.With.
void NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionTypeOf () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Throws.Exception, NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Constraints.ConstraintExpression.TypeOf().
void NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOf () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Throws.TypeOf().
void NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOfAndConstraint () inline
References NUnit.Framework.Constraints.Constraint.And, NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintExpression.EqualTo(), NUnit.Framework.Constraints.ConstraintExpression.Property(), NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Throws.TypeOf().
void NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionTypeOfAndConstraint () inline
References NUnit.Framework.Constraints.Constraint.And, NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintExpression.EqualTo(), NUnit.Framework.Throws.Exception, NUnit.Framework.Constraints.ConstraintExpression.Property(), NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Constraints.ConstraintExpression.TypeOf().
void NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOfWithConstraint () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintExpression.EqualTo(), NUnit.Framework.Constraints.ConstraintExpression.Property(), NUnit.Framework.Constraints.IResolveConstraint.Resolve(), NUnit.Framework.Throws.TypeOf(), and NUnit.Framework.Constraints.Constraint.With.
void NUnit.Framework.Syntax.ThrowsTests.ThrowsInstanceOf () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Throws.InstanceOf(), and NUnit.Framework.Constraints.IResolveConstraint.Resolve().
void NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionInstanceOf () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Throws.Exception, NUnit.Framework.Constraints.ConstraintExpression.InstanceOf(), and NUnit.Framework.Constraints.IResolveConstraint.Resolve().
void NUnit.Framework.Syntax.ThrowsTests.DelegateThrowsException () inline
References NUnit.Framework.Throws.Exception, and NUnit.Framework.Assert.That().
void NUnit.Framework.Syntax.ThrowsTests.LambdaThrowsException () inline
References NUnit.Framework.Throws.InstanceOf(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Syntax.ThrowsTests.LambdaThrowsExceptionWithMessage () inline
References NUnit.Framework.Constraints.Constraint.And, NUnit.Framework.Constraints.ConstraintExpression.EqualTo(), NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Constraints.ConstraintExpression.Message, and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Syntax/ThrowsTests.cs