IGLib: NUnit.Framework.CategoryAttribute Class Reference
NUnit.Framework.CategoryAttribute Class Reference
Attribute used to apply a category to a test
Public Member Functions
CategoryAttribute (string name)
Construct attribute for a given category based on a name. The name may not contain the characters ',', '+', '-' or '!'. However, this is not checked in the constructor since it would cause an error to arise at as the test was loaded without giving a clear indication of where the problem is located. The error is handled in NUnitFramework.cs by marking the test as not runnable.
void ApplyToTest (Test test)
Modifies a test by adding a category to it.
Public Member Functions inherited from NUnit.Framework.NUnitAttribute
NUnitAttribute ()
Default constructor
Protected Member Functions
CategoryAttribute ()
Protected constructor uses the Type name as the name of the category.
Protected Attributes
string categoryName
The name of the category
Properties
string Name [get]
The name of the category
Detailed Description
Attribute used to apply a category to a test
Constructor & Destructor Documentation
NUnit.Framework.CategoryAttribute.CategoryAttribute (string name) inline
Construct attribute for a given category based on a name. The name may not contain the characters ',', '+', '-' or '!'. However, this is not checked in the constructor since it would cause an error to arise at as the test was loaded without giving a clear indication of where the problem is located. The error is handled in NUnitFramework.cs by marking the test as not runnable.
Parameters
name The name of the category
NUnit.Framework.CategoryAttribute.CategoryAttribute () inline protected
Protected constructor uses the Type name as the name of the category.
Member Function Documentation
void NUnit.Framework.CategoryAttribute.ApplyToTest (Test test) inline
Modifies a test by adding a category to it.
Parameters
test The test to modify
Implements NUnit.Framework.Interfaces.IApplyToTest.
References NUnit.Framework.Interfaces.IPropertyBag.Add(), NUnit.Framework.Internal.PropertyNames.Category, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Interfaces.IPropertyBag.Set(), and NUnit.Framework.Internal.PropertyNames.SkipReason.
Referenced by NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsCategory(), NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsCategoryOnNonRunnableTest(), and NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsMultipleCategories().
Member Data Documentation
string NUnit.Framework.CategoryAttribute.categoryName protected
The name of the category
Property Documentation
string NUnit.Framework.CategoryAttribute.Name get
The name of the category
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Attributes/CategoryAttribute.cs