IGLib: LabexUtilities.SettingsReader Class Reference
LabexUtilities.SettingsReader Class Reference
Provides functionality for retrieving settings from various sources such as application settings file or PADO server configuration file.
Public Types
enum SettingSource { SettingSource.Unknown = 0, SettingSource.AppConfig, SettingSource.PadoServer }
Public Member Functions
string GetSetting (string settingname)
Retrieves the specified setting from the current settings source.
bool GetBooleanSetting (string settingname)
Retrieves the specified boolean setting from the current settings source.
long GetIntegerSetting (string settingname)
Retrieves the specified integer setting from the current settings source. If the specific setting is not specified in the configuration then 0 is returned.
long GetIntegerSetting (string settingname, long defaultvalue)
Retrieves the specified integer setting from the current settings source.
string GetSettingAppConfig (string settingname)
bool GetBooleanSettingAppConfig (string settingname)
string GetSettingPadoServer (Premisa.PadoInterfaces.itfPadoServer server, string settingname)
Retrieves the specified setting from the PADO Server's connfiguration file.
bool GetBooleanSettingPadoServer (Premisa.PadoInterfaces.itfPadoServer server, string settingname)
Retrieves the specified boolean setting from the PADO Server's connfiguration file.
string GetSettingPadoServer (Premisa.PadoServerClasses.clsPadoObjectManager om, string settingname)
Retrieves the specified setting from the PADO Server's connfiguration file.
bool GetBooleanSettingPadoServer (Premisa.PadoServerClasses.clsPadoObjectManager om, string settingname)
Retrieves the specified boolean setting from the PADO Server's connfiguration file.
Public Attributes
object lockobj = new object()
bool ExpandEnvironmentVariables = true
Protected Member Functions
void SetSourceAppconfig ()
Sets the source of settings to application configuration file. Warning: A call to this method and subsequent reading operations must be enclosed in a lock block, more specifically in "lock (lockobj) { .. }".
void SetSourcePadoServer (Premisa.PadoInterfaces.itfPadoServer padoserver)
Sets the source of settings to the Pado Server configuration file. Warning: A call to this method and subsequent reading operations must be enclosed in a lock block, more specifically in "lock (lockobj) { .. }".
void SetSourcePadoServer (Premisa.PadoServerClasses.clsPadoObjectManager om)
Sets the source of settings to the Pado Server configuration file. Warning: A call to this method and subsequent reading operations must be enclosed in a lock block, more specifically in "lock (lockobj) { .. }".
Protected Attributes
SettingSource Source = SettingSource.Unknown
Private Member Functions
bool ToBoolean (string strsetting)
Converts a string representation of a boolean setting to boolean. Strings "true", "yes" and "on" (regardless of capitalization) or non-zero integer representations result to true, anything else (including null or empty string) result in false.
long ToInt (string strsetting)
Converts a string representation of an integer setting to an integer value. If the setting is not defined then 0 is returned.
long ToInt (string strsetting, long defaultvalue)
Converts a string representation of an integer setting to an integer value.
Private Attributes
Premisa.PadoInterfaces.itfPadoServer PadoServer = null
Detailed Description
Provides functionality for retrieving settings from various sources such as application settings file or PADO server configuration file.
Member Enumeration Documentation
enum LabexUtilities.SettingsReader.SettingSource
Enumerator
Unknown
AppConfig
PadoServer
Member Function Documentation
bool LabexUtilities.SettingsReader.ToBoolean (string strsetting) inline private
Converts a string representation of a boolean setting to boolean. Strings "true", "yes" and "on" (regardless of capitalization) or non-zero integer representations result to true, anything else (including null or empty string) result in false.
Parameters
strsetting String representation of the specific setting.
Returns
Boolean value corresponding to the setting.
Referenced by LabexUtilities.SettingsReader.GetBooleanSetting(), LabexUtilities.SettingsReader.GetBooleanSettingAppConfig(), and LabexUtilities.SettingsReader.GetBooleanSettingPadoServer().
long LabexUtilities.SettingsReader.ToInt (string strsetting) inline private
Converts a string representation of an integer setting to an integer value. If the setting is not defined then 0 is returned.
Parameters
strsetting String representation of the specific setting.
Returns
Long integer value corresponding to the setting.
Referenced by LabexUtilities.SettingsReader.GetIntegerSetting().
long LabexUtilities.SettingsReader.ToInt (string strsetting, long defaultvalue) inline private
Converts a string representation of an integer setting to an integer value.
Parameters
strsetting String representation of the specific setting.
defaultvalue Default value returned in the case that the setting is not defined.
Returns
Long integer value corresponding to the setting.
void LabexUtilities.SettingsReader.SetSourceAppconfig () inline protected
Sets the source of settings to application configuration file. Warning: A call to this method and subsequent reading operations must be enclosed in a lock block, more specifically in "lock (lockobj) { .. }".
void LabexUtilities.SettingsReader.SetSourcePadoServer (Premisa.PadoInterfaces.itfPadoServer padoserver) inline protected
Sets the source of settings to the Pado Server configuration file. Warning: A call to this method and subsequent reading operations must be enclosed in a lock block, more specifically in "lock (lockobj) { .. }".
Parameters
padoserver Reference to the Pado Server through wihich the server settings can be accessed.
References LabexUtilities.SettingsReader.PadoServer.
void LabexUtilities.SettingsReader.SetSourcePadoServer (Premisa.PadoServerClasses.clsPadoObjectManager om) inline protected
Sets the source of settings to the Pado Server configuration file. Warning: A call to this method and subsequent reading operations must be enclosed in a lock block, more specifically in "lock (lockobj) { .. }".
Parameters
om Reference to the Pado ObjectManager through wihich the server settings can be accessed.
References LabexUtilities.SettingsReader.PadoServer.
string LabexUtilities.SettingsReader.GetSetting (string settingname) inline
Retrieves the specified setting from the current settings source.
Parameters
settingname Setting name.
References LabexUtilities.SettingsReader.GetSettingAppConfig(), LabexUtilities.SettingsReader.GetSettingPadoServer(), and LabexUtilities.SettingsReader.PadoServer.
Referenced by LabexUtilities.SettingsReader.GetBooleanSetting(), and LabexUtilities.SettingsReader.GetIntegerSetting().
bool LabexUtilities.SettingsReader.GetBooleanSetting (string settingname) inline
Retrieves the specified boolean setting from the current settings source.
Parameters
settingname Setting name.
References LabexUtilities.SettingsReader.GetSetting(), and LabexUtilities.SettingsReader.ToBoolean().
long LabexUtilities.SettingsReader.GetIntegerSetting (string settingname) inline
Retrieves the specified integer setting from the current settings source. If the specific setting is not specified in the configuration then 0 is returned.
Parameters
settingname Setting name.
References LabexUtilities.SettingsReader.GetSetting(), and LabexUtilities.SettingsReader.ToInt().
long LabexUtilities.SettingsReader.GetIntegerSetting (string settingname, long defaultvalue) inline
Retrieves the specified integer setting from the current settings source.
Parameters
settingname Setting name.
defaultvalue Value returned in the case that the correspondig setting is not defined.
References LabexUtilities.SettingsReader.GetSetting(), and LabexUtilities.SettingsReader.ToInt().
string LabexUtilities.SettingsReader.GetSettingAppConfig (string settingname) inline
Referenced by LabexUtilities.SettingsReader.GetBooleanSettingAppConfig(), and LabexUtilities.SettingsReader.GetSetting().
bool LabexUtilities.SettingsReader.GetBooleanSettingAppConfig (string settingname) inline
References LabexUtilities.SettingsReader.GetSettingAppConfig(), and LabexUtilities.SettingsReader.ToBoolean().
string LabexUtilities.SettingsReader.GetSettingPadoServer (Premisa.PadoInterfaces.itfPadoServer server, string settingname) inline
Retrieves the specified setting from the PADO Server's connfiguration file.
Parameters
server Pado server whose setting file defines the settings.
settingname Setting name.
Referenced by LabexUtilities.SettingsReader.GetBooleanSettingPadoServer(), LabexUtilities.SettingsReader.GetSetting(), and LabexUtilities.SettingsReader.GetSettingPadoServer().
bool LabexUtilities.SettingsReader.GetBooleanSettingPadoServer (Premisa.PadoInterfaces.itfPadoServer server, string settingname) inline
Retrieves the specified boolean setting from the PADO Server's connfiguration file.
Parameters
om
settingname
References LabexUtilities.SettingsReader.GetSettingPadoServer(), and LabexUtilities.SettingsReader.ToBoolean().
Referenced by LabexUtilities.SettingsReader.GetBooleanSettingPadoServer().
string LabexUtilities.SettingsReader.GetSettingPadoServer (Premisa.PadoServerClasses.clsPadoObjectManager om, string settingname) inline
Retrieves the specified setting from the PADO Server's connfiguration file.
References LabexUtilities.SettingsReader.GetSettingPadoServer().
bool LabexUtilities.SettingsReader.GetBooleanSettingPadoServer (Premisa.PadoServerClasses.clsPadoObjectManager om, string settingname) inline
Retrieves the specified boolean setting from the PADO Server's connfiguration file.
References LabexUtilities.SettingsReader.GetBooleanSettingPadoServer().
Member Data Documentation
object LabexUtilities.SettingsReader.lockobj = new object()
bool LabexUtilities.SettingsReader.ExpandEnvironmentVariables = true
SettingSource LabexUtilities.SettingsReader.Source = SettingSource.Unknown protected
Premisa.PadoInterfaces.itfPadoServer LabexUtilities.SettingsReader.PadoServer = null private
Referenced by LabexUtilities.SettingsReader.GetSetting(), and LabexUtilities.SettingsReader.SetSourcePadoServer().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/LabexUtilitiesCs/SettingsRreader.cs