IGLib: NUnit.TestUtilities.Fakes Class Reference
NUnit.TestUtilities.Fakes Class Reference
Fakes provides static methods for creating test dummies of various kinds
Static Public Member Functions
static FakeTestMethod GetTestMethod (Type type, string name)
static FakeTestMethod GetTestMethod (object obj, string name)
static FakeWorkItem GetWorkItem (Test test, TestExecutionContext context)
static FakeWorkItem GetWorkItem (Test test)
static FakeWorkItem GetWorkItem (Type type, string name, TestExecutionContext context)
static FakeWorkItem GetWorkItem (Type type, string name)
static FakeWorkItem GetWorkItem (object obj, string name, TestExecutionContext context)
static FakeWorkItem GetWorkItem (object obj, string name)
static FakeTestMethod GetTestMethod (Type type, string name)
static FakeTestMethod GetTestMethod (object obj, string name)
static FakeWorkItem GetWorkItem (Test test, TestExecutionContext context)
static FakeWorkItem GetWorkItem (Test test)
static FakeWorkItem GetWorkItem (Type type, string name, TestExecutionContext context)
static FakeWorkItem GetWorkItem (Type type, string name)
static FakeWorkItem GetWorkItem (object obj, string name, TestExecutionContext context)
static FakeWorkItem GetWorkItem (object obj, string name)
Detailed Description
Fakes provides static methods for creating test dummies of various kinds
Member Function Documentation
static FakeTestMethod NUnit.TestUtilities.Fakes.GetTestMethod (Type type, string name) inline static
Referenced by NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Failed(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Ignored(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Inconclusive(), NUnitLite.Tests.TextUITests.TestFinished_NoOutput(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Passed(), NUnitLite.Tests.TextUITests.TestFinished_WithOutput(), and NUnitLite.Tests.TeamCityEventListenerTests.TestStarted().
static FakeTestMethod NUnit.TestUtilities.Fakes.GetTestMethod (object obj, string name) inline static
static FakeWorkItem NUnit.TestUtilities.Fakes.GetWorkItem (Test test, TestExecutionContext context) inline static
static FakeWorkItem NUnit.TestUtilities.Fakes.GetWorkItem (Test test) inline static
static FakeWorkItem NUnit.TestUtilities.Fakes.GetWorkItem (Type type, string name, TestExecutionContext context) inline static
static FakeWorkItem NUnit.TestUtilities.Fakes.GetWorkItem (Type type, string name) inline static
static FakeWorkItem NUnit.TestUtilities.Fakes.GetWorkItem (object obj, string name, TestExecutionContext context) inline static
static FakeWorkItem NUnit.TestUtilities.Fakes.GetWorkItem (object obj, string name) inline static
static FakeTestMethod NUnit.TestUtilities.Fakes.GetTestMethod (Type type, string name) inline static
static FakeTestMethod NUnit.TestUtilities.Fakes.GetTestMethod (object obj, string name) inline static
static FakeWorkItem NUnit.TestUtilities.Fakes.GetWorkItem (Test test, TestExecutionContext context) inline static
static FakeWorkItem NUnit.TestUtilities.Fakes.GetWorkItem (Test test) inline static
static FakeWorkItem NUnit.TestUtilities.Fakes.GetWorkItem (Type type, string name, TestExecutionContext context) inline static
static FakeWorkItem NUnit.TestUtilities.Fakes.GetWorkItem (Type type, string name) inline static
static FakeWorkItem NUnit.TestUtilities.Fakes.GetWorkItem (object obj, string name, TestExecutionContext context) inline static
static FakeWorkItem NUnit.TestUtilities.Fakes.GetWorkItem (object obj, string name) inline static
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/nunitlite.tests/TestUtilities/Fakes.cs