IGLib: NUnitLite.NUnit2XmlOutputWriter Class Reference
NUnitLite.NUnit2XmlOutputWriter Class Reference
NUnit2XmlOutputWriter is able to create an xml file representing the result of a test run in NUnit 2.x format.
Public Member Functions
override void WriteTestFile (ITest test, TextWriter writer)
Write info about a test
override void WriteResultFile (ITestResult result, TextWriter writer, IDictionary runSettings, TestFilter filter)
Writes the result of a test run to a specified TextWriter.
Public Member Functions inherited from NUnitLite.OutputWriter
void WriteResultFile (ITestResult result, string outputPath, IDictionary runSettings, TestFilter filter)
Writes a test result to a file
void WriteTestFile (ITest test, string outputPath)
Writes test info to a file
Private Member Functions
void WriteXmlOutput (ITestResult result, XmlWriter xmlWriter)
void InitializeXmlFile (ITestResult result)
void WriteCultureInfo ()
void WriteEnvironment ()
void WriteResultElement (ITestResult result)
void TerminateXmlFile ()
void StartTestElement (ITestResult result)
string TranslateResult (ResultState resultState)
void WriteCategories (ITestResult result)
void WriteProperties (ITestResult result)
void WriteReasonElement (string message)
void WriteFailureElement (string message, string stackTrace)
void WriteChildResults (ITestResult result)
void WriteCData (string text)
Private Attributes
XmlWriter xmlWriter
Detailed Description
NUnit2XmlOutputWriter is able to create an xml file representing the result of a test run in NUnit 2.x format.
Member Function Documentation
override void NUnitLite.NUnit2XmlOutputWriter.WriteTestFile (ITest test, TextWriter writer) inline virtual
Write info about a test
Parameters
test The test
writer A TextWriter
Implements NUnitLite.OutputWriter.
override void NUnitLite.NUnit2XmlOutputWriter.WriteResultFile (ITestResult result, TextWriter writer, IDictionary runSettings, TestFilter filter) inline virtual
Writes the result of a test run to a specified TextWriter.
Parameters
result The test result for the run
writer The TextWriter to which the xml will be written
Implements NUnitLite.OutputWriter.
References NUnitLite.NUnit2XmlOutputWriter.WriteXmlOutput().
Referenced by NUnitLite.Tests.NUnit2XmlOutputWriterTests.RunMockAssemblyTests().
void NUnitLite.NUnit2XmlOutputWriter.WriteXmlOutput (ITestResult result, XmlWriter xmlWriter) inline private
References NUnitLite.NUnit2XmlOutputWriter.InitializeXmlFile(), NUnitLite.NUnit2XmlOutputWriter.TerminateXmlFile(), NUnitLite.NUnit2XmlOutputWriter.WriteResultElement(), and NUnitLite.NUnit2XmlOutputWriter.xmlWriter.
Referenced by NUnitLite.NUnit2XmlOutputWriter.WriteResultFile().
void NUnitLite.NUnit2XmlOutputWriter.InitializeXmlFile (ITestResult result) inline private
References NUnitLite.ResultSummary.ErrorCount, NUnitLite.ResultSummary.FailureCount, NUnit.Framework.Interfaces.ITestResult.FullName, NUnitLite.ResultSummary.IgnoreCount, NUnitLite.ResultSummary.InconclusiveCount, NUnitLite.ResultSummary.InvalidCount, NUnitLite.ResultSummary.SkipCount, NUnit.Framework.Interfaces.ITestResult.StartTime, NUnitLite.ResultSummary.TestCount, NUnitLite.NUnit2XmlOutputWriter.WriteCultureInfo(), and NUnitLite.NUnit2XmlOutputWriter.WriteEnvironment().
Referenced by NUnitLite.NUnit2XmlOutputWriter.WriteXmlOutput().
void NUnitLite.NUnit2XmlOutputWriter.WriteCultureInfo () inline private
Referenced by NUnitLite.NUnit2XmlOutputWriter.InitializeXmlFile().
void NUnitLite.NUnit2XmlOutputWriter.WriteEnvironment () inline private
References NUnit.Common.AssemblyHelper.GetAssemblyName().
Referenced by NUnitLite.NUnit2XmlOutputWriter.InitializeXmlFile().
void NUnitLite.NUnit2XmlOutputWriter.WriteResultElement (ITestResult result) inline private
References NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Interfaces.ITestResult.StackTrace, NUnitLite.NUnit2XmlOutputWriter.StartTestElement(), NUnit.Framework.Interfaces.ResultState.Status, NUnit.Framework.Interfaces.ITestResult.Test, NUnitLite.NUnit2XmlOutputWriter.WriteCategories(), NUnitLite.NUnit2XmlOutputWriter.WriteChildResults(), NUnitLite.NUnit2XmlOutputWriter.WriteFailureElement(), NUnitLite.NUnit2XmlOutputWriter.WriteProperties(), and NUnitLite.NUnit2XmlOutputWriter.WriteReasonElement().
Referenced by NUnitLite.NUnit2XmlOutputWriter.WriteChildResults(), and NUnitLite.NUnit2XmlOutputWriter.WriteXmlOutput().
void NUnitLite.NUnit2XmlOutputWriter.TerminateXmlFile () inline private
Referenced by NUnitLite.NUnit2XmlOutputWriter.WriteXmlOutput().
void NUnitLite.NUnit2XmlOutputWriter.StartTestElement (ITestResult result) inline private
References NUnit.Framework.Interfaces.ITestResult.AssertCount, NUnit.Framework.Interfaces.IPropertyBag.ContainsKey(), NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Interfaces.ITestResult.Duration, NUnit.Framework.Interfaces.ITest.FullName, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Interfaces.ITest.Name, NUnit.Framework.Interfaces.ITestResult.Name, NUnit.Framework.Interfaces.ITest.Properties, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Interfaces.ResultState.Status, NUnit.Framework.Interfaces.ITestResult.Test, NUnit.Framework.Internal.Test.TestType, and NUnitLite.NUnit2XmlOutputWriter.TranslateResult().
Referenced by NUnitLite.NUnit2XmlOutputWriter.WriteResultElement().
string NUnitLite.NUnit2XmlOutputWriter.TranslateResult (ResultState resultState) inline private
References NUnit.Framework.Interfaces.ResultState.Label, and NUnit.Framework.Interfaces.ResultState.Status.
Referenced by NUnitLite.NUnit2XmlOutputWriter.StartTestElement().
void NUnitLite.NUnit2XmlOutputWriter.WriteCategories (ITestResult result) inline private
References NUnit.Framework.Internal.PropertyNames.Category, NUnit.Framework.Interfaces.IPropertyBag.ContainsKey(), NUnit.Framework.Interfaces.ITest.Properties, and NUnit.Framework.Interfaces.ITestResult.Test.
Referenced by NUnitLite.NUnit2XmlOutputWriter.WriteResultElement().
void NUnitLite.NUnit2XmlOutputWriter.WriteProperties (ITestResult result) inline private
References NUnit.Framework.Internal.PropertyNames.Category, NUnit.Framework.Interfaces.ITest.Properties, and NUnit.Framework.Interfaces.ITestResult.Test.
Referenced by NUnitLite.NUnit2XmlOutputWriter.WriteResultElement().
void NUnitLite.NUnit2XmlOutputWriter.WriteReasonElement (string message) inline private
References NUnitLite.NUnit2XmlOutputWriter.WriteCData().
Referenced by NUnitLite.NUnit2XmlOutputWriter.WriteResultElement().
void NUnitLite.NUnit2XmlOutputWriter.WriteFailureElement (string message, string stackTrace) inline private
References NUnitLite.NUnit2XmlOutputWriter.WriteCData().
Referenced by NUnitLite.NUnit2XmlOutputWriter.WriteResultElement().
void NUnitLite.NUnit2XmlOutputWriter.WriteChildResults (ITestResult result) inline private
References NUnit.Framework.Interfaces.ITestResult.Children, and NUnitLite.NUnit2XmlOutputWriter.WriteResultElement().
Referenced by NUnitLite.NUnit2XmlOutputWriter.WriteResultElement().
void NUnitLite.NUnit2XmlOutputWriter.WriteCData (string text) inline private
Referenced by NUnitLite.NUnit2XmlOutputWriter.WriteFailureElement(), and NUnitLite.NUnit2XmlOutputWriter.WriteReasonElement().
Member Data Documentation
XmlWriter NUnitLite.NUnit2XmlOutputWriter.xmlWriter private
Referenced by NUnitLite.NUnit2XmlOutputWriter.WriteXmlOutput().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/nunitlite.runner/OutputWriters/NUnit2XmlOutputWriter.cs