IGLib: IG.Num.BoundingBox3d Class Reference
IG.Num.BoundingBox3d Class Reference
A 3D bounding box.
Public Member Functions
BoundingBox3d ()
Creates a 3D bounding box with unspecified bounds; minimal co-ordinate components equal to BoundingBoxBase.UndefinedMin and maximal co-ordinate components equal do BoundingBoxBase.UndefinedMax.
BoundingBox3d (double minX, double maxX, double minY, double maxY, double minZ, double maxZ)
Creates a 3D bounding box with the specified bounds.
BoundingBox3d (IVector coordinates)
Creates a bounding box and initializes it in such a way that minimal and maximal co-ordinate components equal to components of the spacified vector.
BoundingBox3d (IVector min, IVector max)
Creates a bounding box of the specified dimension and initializes it in such a way that minimal and maximal co-ordinate components equal to components of the spacified vectors.
BoundingBox3d (IBoundingBox bounds)
Constructs a 3D bounding box of the specified dimension and initializes it in such a way that its bounds correspond to those of the specified bounding box.
BoundingBox3d (double[] coordinates)
Creates a bounding box and initializes it in such a way that minimal and maximal co-ordinate components equal to components of the spacified array.
BoundingBox3d (double[] min, double[] max)
Creates a bounding box and initializes it in such a way that minimal and maximal co-ordinate components equal to components of the spacified arrays.
void Update (vec3 coordinates)
Updates the bounding box in such a way that the specified co-ordinates fit in it.
void Update (params vec3[] points)
Updates the bounding box in such a way that all specified points fit in it.
void Update (Vector3d coordinates)
Updates the bounding box in such a way that the specified co-ordinates fit in it.
void Update (params Vector3d[] points)
Updates the bounding box in such a way that all specified points fit in it.
Public Member Functions inherited from IG.Num.BoundingBoxBase
BoundingBoxBase (int dimension)
Creates a bounding box of the specified dimension and initializes it in such a way that minimal co-ordinate components equal to BoundingBoxBase.UndefinedMin and maximal co-ordinate components equal do BoundingBoxBase.UndefinedMax.
BoundingBoxBase (IVector coordinates)
Creates a bounding box and initializes it in such a way that minimal and maximal co-ordinate components equal to components of the spacified vector.
BoundingBoxBase (IVector min, IVector max)
Constructs a bounding box of the specified dimension and initializes it in such a way that minimal and maximal co-ordinate components equal to components of the spacified vectors.
BoundingBoxBase (IBoundingBox bounds)
Constructs a bounding box of the specified dimension and initializes it in such a way that its bounds correspond to those of the specified bounding box.
BoundingBoxBase (double[] coordinates)
Creates a bounding box and initializes it in such a way that minimal and maximal co-ordinate components equal to components of the spacified array.
BoundingBoxBase (double[] min, double[] max)
Creates a bounding box and initializes it in such a way that minimal and maximal co-ordinate components equal to components of the spacified arrays.
void SetDimensionAndReset (int newDimension)
Changes dimension of the current bounding box to the specified dimension and resets the bounding box. Existent bounds information is lost.
void Reset ()
Resets all components of vector of minimal coordinates to BoundingBoxBase.UndefinedMin, and all components of vector of maximal coordinates to BoundingBoxBase.UndefinedMax.
void Reset (int componentIndex)
Resets the specified component of vector of minimal coordinates to UndefinedMin, and the same component of vector of maximal coordinates to UndefinedMax.
void ResetMin (int componentIndex)
Resets the specified minimal coordinate value to UndefinedMin.
void ResetMax (int componentIndex)
Resets the specified maximal coordinate value to UndefinedMax.
bool LiesOutside (IVector coordinates)
Returns true if the speciifed co-ordinates lie outside of the bounding box, and false otherwise.
bool LiesOutside (params double[] coordinates)
Returns true if the speciifed co-ordinates lie outside of the bounding box, and false otherwise. If the specified coordinates are null then false is returned.
bool LiesOutside (int componentIndex, double coordinate)
Returns true of the specified co-ordinate lies outside of the bounding box, and false otherwise.
bool LiesOutside (IBoundingBox bounds)
Returns true if the specified bounding box lise outside of the current bounding box, and false otherwise. If the specified bounding box is null then false is returned.
void Update (IVector coordinates)
Updates the bounding box in such a way that the specified vector fits in it. If the specified vector is null then this method has no effect.
void Update (params IVector[] points)
Updates the bounding box in such a way that all specified vectors fit in it.
void Update (params double[] coordinates)
Updates the bounding box in such a way that a vector with the specified co-ordinates fits in it.
void Update (int componentIndex, double coordinate)
Updates the bounding box in such a way that the specified value of the specified co-ordinate component (defined by co-ordinate index) fits in it.
void Update (int componentIndex, params double[] coordinates)
Updates the bounding box in such a way that all specified values of the specified co-ordinate component fit in it.
void Update (IBoundingBox bounds)
Updates the bounding box in such a way that the specified other bounding box fits in it. If the specified bounding box is null then this method has no effect.
void UpdateAll (params double[] coordinates)
Updates the current bounding box in such a way that in all components, all specified coordinates fit in it. This is for example useful to define a hypercube (equal minimum and maximum in all components), in this case just minimal and maximal bounds are specified as arguments.
void Shrink (IBoundingBox outerBounds)
Reduces (if necessary) the current bounding box in such a way that the specified bounding box contains it.
void Shrink (int which, double minBound, double maxBound)
Reduces (if necessary) the current bounding box in such a way that the specified component falls within the interval specified by the lower and upper bound.
void ExpandOrShrinkInterval (int componentIndex, double factor)
Symmetrically expands or shrinks the interval between the bounds for the specified component for the specified factor.
void ExpandOrShrinkInterval (double factor)
Symmetrically expands or shrinks the intervals between the bounds for all components for the specified factor. Factors greater than 1 mean expansion, factors lesser than 1 mean shrinkage, and fators lesser than 0 are invalid.
void ExpandOrShrinkInterval (double factor, double zeroIntervalLengthReplacemnt)
Symmetrically expands or shrinks the intervals between the bounds for all components for the specified factor, and takes care that minimal interval lengths are not 0. Factors greater than 1 mean expansion, factors lesser than 1 mean shrinkage, and fators lesser than 0 are invalid. Remark: components where minimal bound is set above maximal are not treated specially.
void SetMin (int componentIndex, double min)
Sets minimal value for the specified coponent of the bounding box.
void SetMax (int componentIndex, double max)
Sets maximal value for the specified coponent of the bounding box.
void SetBounds (int componentIndex, double min, double max)
Sets minimal and maximal value for the specified coponent of the bounding box.
double GetMin (int componentIndex)
Returns the lower bound on the specified co-ordinate component of the bounding box.
double GetMax (int componentIndex)
Returns the upper bound on the specified co-ordinate component of the bounding box.
void GetMin (ref IVector min)
Gets the vector of lower bounds on co-ordinates of the current bounding box and stores it in the specified object.
void GetMax (ref IVector max)
Gets the vector of upper bounds on co-ordinates of the current bounding box and stores it in the specified object.
double GetIntervalLength (int componentIndex)
Returns interval length for the specified co-ordinate component (i.e. difference between the upper and lower bound), or 0 if either lower or upper bound is not defined for this component.
void GetIntervalLengths (ref IVector intervals)
Gets the interval lengths for co-ordinates of the current bounding box (i.e. differences) and stores them in the specified vector object.
void GetRelativeCoordinates (IVector absoluteCoordinates, ref IVector relativeCoordinates)
Calculates relative coordinates, with respect to the current bounding box, that correspond to the specified absolute (or physical or actual) coordinates.
void GetAbsoluteCoordinates (IVector relativeCoordinates, ref IVector absoluteCoordinates)
Calculates absolute (physical) coordinates, with respect to the current bounding box, that correspond to the specified relative coordinates.
bool IsMinDefined (int componentIndex)
Returns true if maximum value is defined for the specified component, false otherwise.
bool IsMaxDefined (int componentIndex)
Returns true if maximum value is defined for the specified component, false otherwise.
override string ToString ()
void GetRandomPoint (ref IVector point)
Creates a random point contained in the current bounding box by using the global random number generator, and stores that point into the specified vector. The random point is generated according to a uniform distribution within the bounding box.
void GetRandomPoint (ref IVector point, IRandomGenerator rand)
Creates a random point contained in the current bounding box by using the specified random number generator, and stores that point into the specified vector. The random point is generated according to a uniform distribution within the bounding box.
void Copy (IBoundingBox original, IBoundingBox copy)
Copies state of the specified bounding box to anotherv(target) bounding box.
Protected Member Functions
override IVector CreateVector (int dim)
Creates and returns a new vector that is consistent with the definition of bounding box.
Protected Member Functions inherited from IG.Num.BoundingBoxBase
void ResetMin ()
Sets all components of vector of minimal coordinates to UndefinedMin.
void ResetMax ()
Sets all components of vector of maximal coordinates to UndefinedMax.
Properties
double MinX [get]
Gets the lower bound in the first coordinate.
double MaxX [get]
Gets the upper bound in the first coordinate.
double MinY [get]
Gets the lower bound in the second coordinate.
double MaxY [get]
Gets the upper bound in the second coordinate.
double MinZ [get]
Gets the lower bound in the third coordinate.
double MaxZ [get]
Gets the upper bound in the third coordinate.
Properties inherited from IG.Num.BoundingBoxBase
IVector MinAuxiliary [get, set]
Auxiliary property, gets or sets vector of minimal co-ordinates.
IVector MaxAuxiliary [get, set]
Auxiliary property, gets or sets vector of maximal co-ordinates.
int Dimension [get, protected set]
Gets dimension of the bounding box space.
virtual IVector Min [get, set]
Gets or sets the vector of minimal co-ordinates of the bounding box.
virtual IVector Max [get, set]
Gets or sets the vector of maximal co-ordinates of the bounding box.
Properties inherited from IG.Num.IBoundingBox
int Dimension [get]
Gets dimension of the bounding box space.
IVector Min [get, set]
Gets or sets the vector of minimal co-ordinates of the bounding box.
IVector Max [get, set]
Gets or sets the vector of maximal co-ordinates of the bounding box.
Additional Inherited Members
Static Public Member Functions inherited from IG.Num.BoundingBoxBase
static BoundingBox Create (int dimension, double min, double max)
Creates and returns a bounding box with specified dimension and minimum and maximum bounds equal in all components.
static BoundingBox Create (params IVector[] points)
Creates and returns a minimal bounding box that contains all the specified points.
static double Map (IBoundingBox original, IBoundingBox target, int whichComponent, double value)
Mapping from one bounding box to another. Returns a single component mapped by a mapping that maps the original to the target bounding box. If one of the bounding boxes is not specified then the performed mapping is identity mapping and does not change the value.
static void Map (IBoundingBox original, IBoundingBox target, IVector value, ref IVector result)
Mapping from one bounding box to another. Maps a vector from the original to the target space. Mapped vector is stored to a specified vector. If one of the bounding boxes is not specified then the performed mapping is identity mapping and does not change the value.
Protected Attributes inherited from IG.Num.BoundingBoxBase
const double UndefinedMin = double.MinValue
const double UndefinedMax = double.MaxValue
Detailed Description
A 3D bounding box.
Constructor & Destructor Documentation
IG.Num.BoundingBox3d.BoundingBox3d () inline
Creates a 3D bounding box with unspecified bounds; minimal co-ordinate components equal to BoundingBoxBase.UndefinedMin and maximal co-ordinate components equal do BoundingBoxBase.UndefinedMax.
IG.Num.BoundingBox3d.BoundingBox3d (double minX, double maxX, double minY, double maxY, double minZ, double maxZ) inline
Creates a 3D bounding box with the specified bounds.
Parameters
minX Lower bound in the first coordinate.
maxX Upper bound in the first coordinate.
minY Lower bound in the second coordinate.
maxY Upper bound in the second coordinate.
minZ Lower bound in the third coordinate.
maxZ Upper bound in the third coordinate.
IG.Num.BoundingBox3d.BoundingBox3d (IVector coordinates) inline
Creates a bounding box and initializes it in such a way that minimal and maximal co-ordinate components equal to components of the spacified vector.
Parameters
coordinates Vector of coordinates to which minimal and maximal co-ordines of the bounding box are set.
IG.Num.BoundingBox3d.BoundingBox3d (IVector min, IVector max) inline
Creates a bounding box of the specified dimension and initializes it in such a way that minimal and maximal co-ordinate components equal to components of the spacified vectors.
Parameters
min Vector of minimal coordinates.
max Vector of macimal coordinates.
IG.Num.BoundingBox3d.BoundingBox3d (IBoundingBox bounds) inline
Constructs a 3D bounding box of the specified dimension and initializes it in such a way that its bounds correspond to those of the specified bounding box.
The specified bounding box must be different than null, otherwise exception is thrown.
Parameters
bounds Bounds with which the constructed bounding box is initialized.
IG.Num.BoundingBox3d.BoundingBox3d (double[] coordinates) inline
Creates a bounding box and initializes it in such a way that minimal and maximal co-ordinate components equal to components of the spacified array.
Parameters
coordinates Array of coordinates to which minimal and maximal co-ordines of the bounding box are set.
IG.Num.BoundingBox3d.BoundingBox3d (double[] min, double[] max) inline
Creates a bounding box and initializes it in such a way that minimal and maximal co-ordinate components equal to components of the spacified arrays.
Parameters
min Array of components to which minimal co-ordines of the bounding box are set.
max Array of components to which maximal co-ordines of the bounding box are set.
Member Function Documentation
void IG.Num.BoundingBox3d.Update (vec3 coordinates) inline
Updates the bounding box in such a way that the specified co-ordinates fit in it.
Parameters
coordinates Vector of oordinates for which the bounding box is updated in such a way that they fit in it.
References IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Referenced by IG.Gr3d.VtkPlotBase.ExampleSurfacePlotManualScaled(), IG.Gr3d.VtkPlotBase.ExampleSurfacePlotScaled(), IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Script.S_13_5_Convection.PlotTrainingAndVerificationPointResponse2D(), IG.MPetekLib.Application.Scripts.LinearOscillator._11MultipleResCurvesPlot3D.ResonanceCurveHarmonicFamily3dWithManualScaling(), IG.MPetekLib.Application.Scripts.LinearOscillator._11MultipleResCurvesPlot3D.Run(), IG.Neural.Forms.NeuralControl2D.ShowPlot(), and IG.Gr3d.VtkPlotBase.UpdateBoundsCoordinates().
void IG.Num.BoundingBox3d.Update (params vec3[] points) inline
Updates the bounding box in such a way that all specified points fit in it.
If the array of points is empty or null then this function has no effect.
Parameters
points Coordinate vectors of points for which the bounding box is updated in such a way that they fit in it.
void IG.Num.BoundingBox3d.Update (Vector3d coordinates) inline
Updates the bounding box in such a way that the specified co-ordinates fit in it.
If the specified coordinates are null then this method has no effect.
Parameters
coordinates Vector of oordinates for which the bounding box is updated in such a way that they fit in it.
References IG.Num.Vector3d.X, IG.Num.Vector3d.Y, and IG.Num.Vector3d.Z.
void IG.Num.BoundingBox3d.Update (params Vector3d[] points) inline
Updates the bounding box in such a way that all specified points fit in it.
If the specified array of points is empty or null then this function has no effect. Elements of the array that are null are ignored.
Parameters
points Coordinate vectors of points for which the bounding box is updated in such a way that they fit in it.
override IVector IG.Num.BoundingBox3d.CreateVector (int dim) inline protected virtual
Creates and returns a new vector that is consistent with the definition of bounding box.
Parameters
dim Dimension of vector space.
Implements IG.Num.BoundingBoxBase.
Property Documentation
double IG.Num.BoundingBox3d.MinX get
Gets the lower bound in the first coordinate.
double IG.Num.BoundingBox3d.MaxX get
Gets the upper bound in the first coordinate.
double IG.Num.BoundingBox3d.MinY get
Gets the lower bound in the second coordinate.
double IG.Num.BoundingBox3d.MaxY get
Gets the upper bound in the second coordinate.
double IG.Num.BoundingBox3d.MinZ get
Gets the lower bound in the third coordinate.
Referenced by IG.MPetekLib.Application.Scripts.LinearOscillator._11MultipleResCurvesPlot3D.ApplySurfacePlottterSettingsDefault(), IG.Neural.Forms.NeuralParametricTest2d.ApplySurfacePlottterSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault(), and IG.Script.S_13_5_Convection.ApplySurfacePlottterSettingsDefault().
double IG.Num.BoundingBox3d.MaxZ get
Gets the upper bound in the third coordinate.
Referenced by IG.MPetekLib.Application.Scripts.LinearOscillator._11MultipleResCurvesPlot3D.ApplySurfacePlottterSettingsDefault(), IG.Neural.Forms.NeuralParametricTest2d.ApplySurfacePlottterSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault(), and IG.Script.S_13_5_Convection.ApplySurfacePlottterSettingsDefault().
The documentation for this class was generated from the following file:
iglib/igbase/numeric/BoundingBox.cs