IGLib: NUnit.Framework.ExplicitAttribute Class Reference
NUnit.Framework.ExplicitAttribute Class Reference
ExplicitAttribute marks a test or test fixture so that it will only be run if explicitly executed from the gui or command line or if it is included by use of a filter. The test will not be run simply because an enclosing suite is run.
Public Member Functions
ExplicitAttribute ()
Default constructor
ExplicitAttribute (string reason)
Constructor with a reason
void ApplyToTest (Test test)
Modifies a test by marking it as explicit.
Public Member Functions inherited from NUnit.Framework.NUnitAttribute
NUnitAttribute ()
Default constructor
Private Attributes
string reason
Detailed Description
ExplicitAttribute marks a test or test fixture so that it will only be run if explicitly executed from the gui or command line or if it is included by use of a filter. The test will not be run simply because an enclosing suite is run.
Constructor & Destructor Documentation
NUnit.Framework.ExplicitAttribute.ExplicitAttribute () inline
Default constructor
NUnit.Framework.ExplicitAttribute.ExplicitAttribute (string reason) inline
Constructor with a reason
Parameters
reason The reason test is marked explicit
Member Function Documentation
void NUnit.Framework.ExplicitAttribute.ApplyToTest (Test test) inline
Modifies a test by marking it as explicit.
Parameters
test The test to modify
Implements NUnit.Framework.Interfaces.IApplyToTest.
References NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Interfaces.IPropertyBag.Set(), and NUnit.Framework.Internal.PropertyNames.SkipReason.
Referenced by NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeMakesTestExplicit(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeSetsIgnoreReason(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeWithIgnoreIgnoresTest(), and NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithExplicitIgnoresTest().
Member Data Documentation
string NUnit.Framework.ExplicitAttribute.reason private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Attributes/ExplicitAttribute.cs