IGLib: CShell.Modules.Workspace.Module Class Reference
CShell.Modules.Workspace.Module Class Reference
Public Member Functions
Module ()
override void Initialize ()
IEnumerable< IResult > AddReferenceFromGac ()
Module ()
override void Initialize ()
IEnumerable< IResult > AddReferenceFromGac ()
Public Member Functions inherited from CShell.Framework.ModuleBase
void Dispose ()
void Dispose ()
Private Member Functions
IEnumerable< IResult > AddNewFile ()
IEnumerable< IResult > AddNewFolder ()
IEnumerable< IResult > AddReferenceFromFile ()
FolderViewModel GetSelectedFolder ()
IEnumerable< IResult > AddNewFile ()
IEnumerable< IResult > AddNewFolder ()
IEnumerable< IResult > AddReferenceFromFile ()
FolderViewModel GetSelectedFolder ()
Static Private Member Functions
static IEnumerable< IResult > OpenWorkspaceExplorer ()
static IEnumerable< IResult > OpenWorkspaceExplorer ()
Private Attributes
IWorkspaceActivator workspaceActivator
Additional Inherited Members
Protected Member Functions inherited from CShell.Framework.ModuleBase
virtual void Dispose (bool disposing)
virtual void Dispose (bool disposing)
Properties inherited from CShell.Framework.ModuleBase
IShell Shell [get]
IMenu MainMenu [get]
IToolBar ToolBar [get]
int Order [get, set]
Properties inherited from CShell.Framework.IModule
int Order [get]
Constructor & Destructor Documentation
CShell.Modules.Workspace.Module.Module () inline
CShell.Modules.Workspace.Module.Module () inline
Member Function Documentation
override void CShell.Modules.Workspace.Module.Initialize () inline virtual
Implements CShell.Framework.ModuleBase.
References CShell.Framework.Menus.MenuItemBase.Add(), CShell.Framework.Menus.MenuItemBase.Separator, and CShell.Framework.Menus.StandardMenuItem.WithActivator().
static IEnumerable<IResult> CShell.Modules.Workspace.Module.OpenWorkspaceExplorer () inline static private
IEnumerable<IResult> CShell.Modules.Workspace.Module.AddNewFile () inline private
IEnumerable<IResult> CShell.Modules.Workspace.Module.AddNewFolder () inline private
IEnumerable<IResult> CShell.Modules.Workspace.Module.AddReferenceFromFile () inline private
References CShell.Workspace.Assemblies, CShell.Constants.AssemblyFileFilter, CShell.Framework.Results.Show.Dialog(), and CShell.Shell.Workspace.
IEnumerable<IResult> CShell.Modules.Workspace.Module.AddReferenceFromGac () inline
References CShell.Workspace.Assemblies, CShell.Framework.Results.Show.Dialog(), and CShell.Shell.Workspace.
FolderViewModel CShell.Modules.Workspace.Module.GetSelectedFolder () inline private
override void CShell.Modules.Workspace.Module.Initialize () inline virtual
Implements CShell.Framework.ModuleBase.
References CShell.Framework.Menus.MenuItemBase.Add(), CShell.Framework.Menus.MenuItemBase.Separator, and CShell.Framework.Menus.StandardMenuItem.WithActivator().
static IEnumerable<IResult> CShell.Modules.Workspace.Module.OpenWorkspaceExplorer () inline static private
IEnumerable<IResult> CShell.Modules.Workspace.Module.AddNewFile () inline private
IEnumerable<IResult> CShell.Modules.Workspace.Module.AddNewFolder () inline private
IEnumerable<IResult> CShell.Modules.Workspace.Module.AddReferenceFromFile () inline private
References CShell.Workspace.Assemblies, CShell.Constants.AssemblyFileFilter, CShell.Framework.Results.Show.Dialog(), and CShell.Shell.Workspace.
IEnumerable<IResult> CShell.Modules.Workspace.Module.AddReferenceFromGac () inline
References CShell.Workspace.Assemblies, CShell.Framework.Results.Show.Dialog(), and CShell.Shell.Workspace.
FolderViewModel CShell.Modules.Workspace.Module.GetSelectedFolder () inline private
Member Data Documentation
IWorkspaceActivator CShell.Modules.Workspace.Module.workspaceActivator private
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Workspace/Module.cs