IGLib: IPLab.IDocumentsHost Interface Reference
IPLab.IDocumentsHost Interface Reference
IDocumentsHost interface Provides connectione between documents and the main widnow
Public Member Functions
bool NewDocument (Bitmap image)
bool NewDocument (ComplexImage image)
Bitmap GetImage (object sender, String text, Size size, PixelFormat format)
Properties
bool CreateNewDocumentOnChange [get]
bool RememberOnChange [get]
Detailed Description
IDocumentsHost interface Provides connectione between documents and the main widnow
Member Function Documentation
bool IPLab.IDocumentsHost.NewDocument (Bitmap image)
Implemented in IPLab.MainForm.
Referenced by IPLab.ImageDoc.ApplyFilter(), IPLab.FourierDoc.backwardFourierItem_Click(), IPLab.ImageDoc.blobExtractorFiltersItem_Click(), IPLab.ImageDoc.Clone(), IPLab.ImageDoc.ForwardFourierTransformation(), and IPLab.ImageDoc.quadrilateralFinderMenuItem_Click().
bool IPLab.IDocumentsHost.NewDocument (ComplexImage image)
Implemented in IPLab.MainForm.
Bitmap IPLab.IDocumentsHost.GetImage (object sender, String text, Size size, PixelFormat format)
Implemented in IPLab.MainForm.
Referenced by IPLab.ImageDoc.addTwosrcFiltersItem_Click(), IPLab.ImageDoc.CreateStereoAnaglyph(), IPLab.ImageDoc.differenceTwosrcFiltersItem_Click(), IPLab.ImageDoc.intersectTwosrcFiltersItem_Click(), IPLab.ImageDoc.maskFilterMenuItem_Click(), IPLab.ImageDoc.mergeTwosrcFiltersItem_Click(), IPLab.ImageDoc.morphTwosrcFiltersItem_Click(), IPLab.ImageDoc.moveTowardsTwosrcFiltersItem_Click(), IPLab.ImageDoc.replaceBlueColorFiltersItem_Click(), IPLab.ImageDoc.replaceCbFiltersItem_Click(), IPLab.ImageDoc.replaceCrFiltersItem_Click(), IPLab.ImageDoc.replaceGreenColorFiltersItem_Click(), IPLab.ImageDoc.replaceRedColorFiltersItem_Click(), IPLab.ImageDoc.replaceYFiltersItem_Click(), and IPLab.ImageDoc.subtractTwosrcFiltersItem_Click().
Property Documentation
bool IPLab.IDocumentsHost.CreateNewDocumentOnChange get
Referenced by IPLab.ImageDoc.ApplyFilter(), and IPLab.ImageDoc.quadrilateralFinderMenuItem_Click().
bool IPLab.IDocumentsHost.RememberOnChange get
Referenced by IPLab.ImageDoc.ApplyFilter(), and IPLab.ImageDoc.quadrilateralFinderMenuItem_Click().
The documentation for this interface was generated from the following file:
igsandbox/imageprocessing/iplab_new_GPL/Sources/IDocumentsHost.cs