IGLib: TestWS_Lib.TestWS_Lib Class Reference
TestWS_Lib.TestWS_Lib Class Reference
Public Member Functions
TestWS_Lib ()
void startTesting (List< ThreadData > listThreadData)
void cancel ()
bool threadsRunning ()
Properties
String Result [get]
A string containing results from the WS.
int ProgressValue [get]
1/10 of currently done percentage.
XmlDocument ResultDocument [get]
XmlDocument, containing results from the WS.
Private Member Functions
void threadWork (List< Package > selectedPackages, int numSendPackages, int timeLag, int numThreads, int internalThreadNum)
void SetText (String text)
void SetProgress (int value)
Private Attributes
List< Thread > threadList
EFA_WS.Service service
String result
int progressValue
XmlDocument resultDocument
Constructor & Destructor Documentation
TestWS_Lib.TestWS_Lib.TestWS_Lib () inline
Member Function Documentation
void TestWS_Lib.TestWS_Lib.startTesting (List< ThreadData > listThreadData) inline
References TestWS_Lib.ThreadData.NumSendPackages, TestWS_Lib.ThreadData.Packages, and TestWS_Lib.ThreadData.TimeLag.
Referenced by TestWS_GUI.Form1.buttonSend_Click(), and TestWS_Console.Test_Console.run().
void TestWS_Lib.TestWS_Lib.threadWork (List< Package > selectedPackages, int numSendPackages, int timeLag, int numThreads, int internalThreadNum) inline private
References TestWS_Lib.Package.Name, and TestWS_Lib.Package.PackageContent.
void TestWS_Lib.TestWS_Lib.SetText (String text) inline private
void TestWS_Lib.TestWS_Lib.SetProgress (int value) inline private
void TestWS_Lib.TestWS_Lib.cancel () inline
Referenced by TestWS_GUI.Form1.buttonCancel_Click().
bool TestWS_Lib.TestWS_Lib.threadsRunning () inline
Referenced by TestWS_GUI.Form1.backgroundWorker1_DoWork(), and TestWS_Console.Test_Console.displayResults().
Member Data Documentation
List<Thread> TestWS_Lib.TestWS_Lib.threadList private
EFA_WS.Service TestWS_Lib.TestWS_Lib.service private
String TestWS_Lib.TestWS_Lib.result private
int TestWS_Lib.TestWS_Lib.progressValue private
XmlDocument TestWS_Lib.TestWS_Lib.resultDocument private
Property Documentation
String TestWS_Lib.TestWS_Lib.Result get
A string containing results from the WS.
Referenced by TestWS_GUI.Form1.backgroundWorker1_DoWork(), TestWS_GUI.Form1.backgroundWorker1_RunWorkerCompleted(), and TestWS_Console.Test_Console.displayResults().
int TestWS_Lib.TestWS_Lib.ProgressValue get
1/10 of currently done percentage.
Referenced by TestWS_GUI.Form1.backgroundWorker1_DoWork(), and TestWS_Console.Test_Console.displayResults().
XmlDocument TestWS_Lib.TestWS_Lib.ResultDocument get
XmlDocument, containing results from the WS.
Referenced by TestWS_Console.Test_Console.compareXmls(), and TestWS_Console.Test_Console.writeXml().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prefa/95_Test/TestWS_Lib/TestWS_Lib.cs