IGLib: PipeClient.Client Class Reference
PipeClient.Client Class Reference
Public Member Functions
static SafeFileHandle CreateFile (String pipeName, uint dwDesiredAccess, uint dwShareMode, IntPtr lpSecurityAttributes, uint dwCreationDisposition, uint dwFlagsAndAttributes, IntPtr hTemplate)
delegate void MessageReceivedHandler (string message)
void Connect ()
Connects to the server
void Read ()
Reads data from the server
void SendMessage (string message)
Sends a message to the server
Public Attributes
const uint GENERIC_READ = (0x80000000)
const uint GENERIC_WRITE = (0x40000000)
const uint OPEN_EXISTING = 3
const uint FILE_FLAG_OVERLAPPED = (0x40000000)
const int BUFFER_SIZE = 4096
Properties
bool Connected [get]
string PipeName [get, set]
Events
MessageReceivedHandler MessageReceived
Private Attributes
string pipeName
FileStream stream
SafeFileHandle handle
Thread readThread
bool connected
Member Function Documentation
static SafeFileHandle PipeClient.Client.CreateFile (String pipeName, uint dwDesiredAccess, uint dwShareMode, IntPtr lpSecurityAttributes, uint dwCreationDisposition, uint dwFlagsAndAttributes, IntPtr hTemplate)
Referenced by PipeClient.Client.Connect().
delegate void PipeClient.Client.MessageReceivedHandler (string message)
Referenced by PipeClient.Form1.Form1(), and PipeClient.Form1.pipeClient_MessageReceived().
void PipeClient.Client.Connect () inline
Connects to the server
References PipeClient.Client.CreateFile(), and PipeClient.Client.Read().
Referenced by PipeClient.Form1.btnStart_Click().
void PipeClient.Client.Read () inline
Reads data from the server
References PipeClient.Client.BUFFER_SIZE, and PipeClient.Client.MessageReceived.
Referenced by PipeClient.Client.Connect().
void PipeClient.Client.SendMessage (string message) inline
Sends a message to the server
Parameters
message
Referenced by PipeClient.Form1.btnSend_Click().
Member Data Documentation
const uint PipeClient.Client.GENERIC_READ = (0x80000000)
const uint PipeClient.Client.GENERIC_WRITE = (0x40000000)
const uint PipeClient.Client.OPEN_EXISTING = 3
const uint PipeClient.Client.FILE_FLAG_OVERLAPPED = (0x40000000)
const int PipeClient.Client.BUFFER_SIZE = 4096
Referenced by PipeClient.Client.Read().
string PipeClient.Client.pipeName private
FileStream PipeClient.Client.stream private
SafeFileHandle PipeClient.Client.handle private
Thread PipeClient.Client.readThread private
bool PipeClient.Client.connected private
Property Documentation
bool PipeClient.Client.Connected get
Referenced by PipeClient.Form1.btnStart_Click().
string PipeClient.Client.PipeName get set
Referenced by PipeClient.Form1.btnStart_Click().
Event Documentation
MessageReceivedHandler PipeClient.Client.MessageReceived
Referenced by PipeClient.Form1.Form1(), and PipeClient.Client.Read().
The documentation for this class was generated from the following file:
igsandbox/InterprocessCommunication/named_pipe_examples_master/C# client & server - named pipe/PipeClient/PipeClient/Client.cs