IGLib: IG.Old.Vector_OldNumerics Class Reference
IG.Old.Vector_OldNumerics Class Reference
XVector whose vec are real numbers.
Public Member Functions
Vector_OldNumerics (int dimension)
Vector_OldNumerics (int dimension, double comp)
Vector_OldNumerics (double[] array)
Vector_OldNumerics (Vector_OldNumerics cv)
Static Public Member Functions
static Vector_OldNumerics operator+ (Vector_OldNumerics a, Vector_OldNumerics b)
static Vector_OldNumerics operator- (Vector_OldNumerics a, Vector_OldNumerics b)
static Vector_OldNumerics operator* (Vector_OldNumerics a, Vector_OldNumerics b)
static Vector_OldNumerics operator* (Vector_OldNumerics a, double b)
static Vector_OldNumerics operator* (double b, Vector_OldNumerics a)
Protected Member Functions
Vector_OldNumerics ()
override double Add (double a, double b)
override double Subtract (double a, double b)
override double Multiply (double a, double b)
override double Divide (double a, double b)
override double Negative (double a)
override double Inverse (double a)
override double Conjugate (double a)
Properties
override double Zero [get]
Detailed Description
XVector whose vec are real numbers.
Constructor & Destructor Documentation
IG.Old.Vector_OldNumerics.Vector_OldNumerics () inline protected
IG.Old.Vector_OldNumerics.Vector_OldNumerics (int dimension) inline
IG.Old.Vector_OldNumerics.Vector_OldNumerics (int dimension, double comp) inline
IG.Old.Vector_OldNumerics.Vector_OldNumerics (double[] array) inline
IG.Old.Vector_OldNumerics.Vector_OldNumerics (Vector_OldNumerics cv) inline
Member Function Documentation
override double IG.Old.Vector_OldNumerics.Add (double a, double b) inline protected
Referenced by IG.Old.Vector_OldNumerics.operator+().
override double IG.Old.Vector_OldNumerics.Subtract (double a, double b) inline protected
Referenced by IG.Old.Vector_OldNumerics.operator-().
override double IG.Old.Vector_OldNumerics.Multiply (double a, double b) inline protected
Referenced by IG.Old.Vector_OldNumerics.operator*().
override double IG.Old.Vector_OldNumerics.Divide (double a, double b) inline protected
override double IG.Old.Vector_OldNumerics.Negative (double a) inline protected
override double IG.Old.Vector_OldNumerics.Inverse (double a) inline protected
override double IG.Old.Vector_OldNumerics.Conjugate (double a) inline protected
static Vector_OldNumerics IG.Old.Vector_OldNumerics.operator+ (Vector_OldNumerics a, Vector_OldNumerics b) inline static
References IG.Old.Vector_OldNumerics.Add().
static Vector_OldNumerics IG.Old.Vector_OldNumerics.operator- (Vector_OldNumerics a, Vector_OldNumerics b) inline static
References IG.Old.Vector_OldNumerics.Subtract().
static Vector_OldNumerics IG.Old.Vector_OldNumerics.operator* (Vector_OldNumerics a, Vector_OldNumerics b) inline static
static Vector_OldNumerics IG.Old.Vector_OldNumerics.operator* (Vector_OldNumerics a, double b) inline static
References IG.Old.Vector_OldNumerics.Multiply().
static Vector_OldNumerics IG.Old.Vector_OldNumerics.operator* (double b, Vector_OldNumerics a) inline static
References IG.Old.Vector_OldNumerics.Multiply().
Property Documentation
override double IG.Old.Vector_OldNumerics.Zero get protected
The documentation for this class was generated from the following file:
igtest/IGLibTestDevExt/z_old/OldNumeric.cs