IGLib: IG.Old.Vector_OldNumerics< ComponentType > Class Template Reference
IG.Old.Vector_OldNumerics< ComponentType > Class Template Reference abstract
Public Member Functions
Vector_OldNumerics (int dim1, ComponentType comp)
Vector_OldNumerics (ComponentType[] array)
void Init (int dim)
Initializes a matrix with dimendions dim1 and dim2.
void Init (int dim, ComponentType comp)
Initializes a vector with dimendion length and sets all vec to comp.
void Init (ComponentType[] array)
Initializes a vector with dimendion length and sets all vec to comp.
void Init (Vector_OldNumerics< ComponentType > v)
Initializes a vector with dimendion length and sets all vec to comp.
override string ToString ()
Redefinition of Tostring(), converts a vector to string representation.
void Add (Vector_OldNumerics< ComponentType > a)
XVector addition.
void Subtract (Vector_OldNumerics< ComponentType > a)
XVector subtraction.
void Multiply (ComponentType scalar)
Multiplication of a vector by a scalar.
ComponentType RightScalarProduct (Vector_OldNumerics< ComponentType > a)
Right scalar product.
ComponentType LeftScalarProduct (Vector_OldNumerics< ComponentType > a)
Right scalar product.
Static Public Member Functions
static ComponentType[] Copy (Vector_OldNumerics< ComponentType > v)
static void Example ()
Protected Member Functions
Vector_OldNumerics ()
abstract ComponentType Add (ComponentType a, ComponentType b)
abstract ComponentType Subtract (ComponentType a, ComponentType b)
abstract ComponentType Multiply (ComponentType a, ComponentType b)
abstract ComponentType Divide (ComponentType a, ComponentType b)
abstract ComponentType Negative (ComponentType a)
abstract ComponentType Inverse (ComponentType a)
abstract ComponentType Conjugate (ComponentType a)
Protected Attributes
int _dim
ComponentType[] _tab
Properties
int Dimension [get]
Returns vector dimension.
int Dimension2 [get]
Returns vector dimension.
int d [get]
Synonyme for Dimension, returns vector dimension.
virtual ComponentType this[int ind] [get, set]
Gets or sets a specific vector componene.
abstract ComponentType Zero [get]
Constructor & Destructor Documentation
IG.Old.Vector_OldNumerics< ComponentType >.Vector_OldNumerics () inline protected
IG.Old.Vector_OldNumerics< ComponentType >.Vector_OldNumerics (int dim1, ComponentType comp) inline
IG.Old.Vector_OldNumerics< ComponentType >.Vector_OldNumerics (ComponentType[] array) inline
Member Function Documentation
void IG.Old.Vector_OldNumerics< ComponentType >.Init (int dim) inline
Initializes a matrix with dimendions dim1 and dim2.
Parameters
dim1 Number of rows.
dim2 Number of columns.
void IG.Old.Vector_OldNumerics< ComponentType >.Init (int dim, ComponentType comp) inline
Initializes a vector with dimendion length and sets all vec to comp.
Parameters
length XVector dimension.
void IG.Old.Vector_OldNumerics< ComponentType >.Init (ComponentType[] array) inline
Initializes a vector with dimendion length and sets all vec to comp.
Parameters
length XVector dimension.
void IG.Old.Vector_OldNumerics< ComponentType >.Init (Vector_OldNumerics< ComponentType > v) inline
Initializes a vector with dimendion length and sets all vec to comp.
Parameters
length XVector dimension.
References IG.Old.Vector_OldNumerics< ComponentType >.Dimension.
static ComponentType [] IG.Old.Vector_OldNumerics< ComponentType >.Copy (Vector_OldNumerics< ComponentType > v) inline static
References IG.Old.Vector_OldNumerics< ComponentType >.Dimension.
override string IG.Old.Vector_OldNumerics< ComponentType >.ToString () inline
Redefinition of Tostring(), converts a vector to string representation.
Returns
Referenced by IG.Old.Vector_OldNumerics< ComponentType >.Example().
abstract ComponentType IG.Old.Vector_OldNumerics< ComponentType >.Add (ComponentType a, ComponentType b) protected pure virtual
abstract ComponentType IG.Old.Vector_OldNumerics< ComponentType >.Subtract (ComponentType a, ComponentType b) protected pure virtual
abstract ComponentType IG.Old.Vector_OldNumerics< ComponentType >.Multiply (ComponentType a, ComponentType b) protected pure virtual
abstract ComponentType IG.Old.Vector_OldNumerics< ComponentType >.Divide (ComponentType a, ComponentType b) protected pure virtual
abstract ComponentType IG.Old.Vector_OldNumerics< ComponentType >.Negative (ComponentType a) protected pure virtual
abstract ComponentType IG.Old.Vector_OldNumerics< ComponentType >.Inverse (ComponentType a) protected pure virtual
abstract ComponentType IG.Old.Vector_OldNumerics< ComponentType >.Conjugate (ComponentType a) protected pure virtual
void IG.Old.Vector_OldNumerics< ComponentType >.Add (Vector_OldNumerics< ComponentType > a) inline
XVector addition.
References IG.Old.Vector_OldNumerics< ComponentType >.Dimension.
void IG.Old.Vector_OldNumerics< ComponentType >.Subtract (Vector_OldNumerics< ComponentType > a) inline
XVector subtraction.
References IG.Old.Vector_OldNumerics< ComponentType >.Dimension.
void IG.Old.Vector_OldNumerics< ComponentType >.Multiply (ComponentType scalar) inline
Multiplication of a vector by a scalar.
ComponentType IG.Old.Vector_OldNumerics< ComponentType >.RightScalarProduct (Vector_OldNumerics< ComponentType > a) inline
Right scalar product.
References IG.Old.Vector_OldNumerics< ComponentType >.Dimension, and Zero.
Referenced by IG.Old.ComplexVector_OldNumerics.operator*().
ComponentType IG.Old.Vector_OldNumerics< ComponentType >.LeftScalarProduct (Vector_OldNumerics< ComponentType > a) inline
Right scalar product.
References IG.Old.Vector_OldNumerics< ComponentType >.Dimension, and Zero.
static void IG.Old.Vector_OldNumerics< ComponentType >.Example () inline static
References IG.Old.Vector_OldNumerics< ComponentType >.ToString().
Member Data Documentation
int IG.Old.Vector_OldNumerics< ComponentType >._dim protected
ComponentType [] IG.Old.Vector_OldNumerics< ComponentType >._tab protected
Property Documentation
int IG.Old.Vector_OldNumerics< ComponentType >.Dimension get
Returns vector dimension.
Referenced by IG.Old.Vector_OldNumerics< ComponentType >.Add(), IG.Old.Vector_OldNumerics< ComponentType >.Copy(), IG.Old.Vector_OldNumerics< ComponentType >.Init(), IG.Old.Vector_OldNumerics< ComponentType >.LeftScalarProduct(), IG.Old.Vector_OldNumerics< ComponentType >.RightScalarProduct(), and IG.Old.Vector_OldNumerics< ComponentType >.Subtract().
int IG.Old.Vector_OldNumerics< ComponentType >.Dimension2 get
Returns vector dimension.
int IG.Old.Vector_OldNumerics< ComponentType >.d get
Synonyme for Dimension, returns vector dimension.
virtual ComponentType IG.Old.Vector_OldNumerics< ComponentType >.this[int ind] get set
Gets or sets a specific vector componene.
Parameters
ind Component index running from 0 to l-1.
Returns
a referance to a component for a reference type ComponentType or its value for value types.
abstract ComponentType IG.Old.Vector_OldNumerics< ComponentType >.Zero get protected
The documentation for this class was generated from the following file:
igtest/IGLibTestDevExt/z_old/OldNumeric.cs