IGLib: Test.NullDistributionTests Class Reference
Test.NullDistributionTests Class Reference
Public Member Functions
void KolmogorovNullDistributionTest ()
void KuiperNullDistributionTest ()
void TwoSampleKolmogorovNullDistributionTest ()
void SpearmanNullDistributionTest ()
void KendallNullDistributionTest ()
Member Function Documentation
void Test.NullDistributionTests.KolmogorovNullDistributionTest () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.TestResult.Distribution, Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.Sample.KuiperTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationVariance, Meta.Numerics.Statistics.TestResult.RightProbability, Meta.Numerics.Statistics.TestResult.Statistic, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Variance.
void Test.NullDistributionTests.KuiperNullDistributionTest () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.TestResult.Distribution, Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.Sample.KuiperTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationVariance, Meta.Numerics.Statistics.TestResult.RightProbability, Meta.Numerics.Statistics.TestResult.Statistic, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Variance.
void Test.NullDistributionTests.TwoSampleKolmogorovNullDistributionTest () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.Sample.Count, Meta.Numerics.Statistics.TestResult.Distribution, Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Functions.AdvancedIntegerMath.LCM(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Distributions.Distribution.MomentAboutMean(), Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationMomentAboutMean(), Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation, and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.NullDistributionTests.SpearmanNullDistributionTest () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.TestResult.Distribution, Meta.Numerics.Statistics.Sample.KuiperTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationVariance, Meta.Numerics.Statistics.TestResult.RightProbability, Meta.Numerics.Statistics.BivariateSample.SpearmanRhoTest(), Meta.Numerics.Statistics.TestResult.Statistic, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Variance.
void Test.NullDistributionTests.KendallNullDistributionTest () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.TestResult.Distribution, Meta.Numerics.Statistics.BivariateSample.KendallTauTest(), Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationVariance, Meta.Numerics.Statistics.TestResult.Statistic, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Variance.
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/NullDistributionTests.cs