IGLib: NUnit.Framework.Internal.DefaultResultTests Class Reference
NUnit.Framework.Internal.DefaultResultTests Class Reference
Public Member Functions
void TestResultIsInconclusive ()
void SuiteResultIsInconclusive ()
void TestResultXmlNodeIsInconclusive ()
void SuiteResultXmlNodeIsInconclusive ()
void SuiteResultXmlNodeHasOneChildTest ()
Public Member Functions inherited from NUnit.Framework.Internal.TestResultTests
void SetUp ()
void TestResultBasicInfo ()
void SuiteResultBasicInfo ()
void TestResultXmlNodeBasicInfo ()
void SuiteResultXmlNodeBasicInfo ()
Protected Member Functions
override void SimulateTestRun ()
Additional Inherited Members
Protected Attributes inherited from NUnit.Framework.Internal.TestResultTests
TestResult testResult
TestResult suiteResult
TestMethod test
double expectedDuration
DateTime expectedStart
DateTime expectedEnd
Properties inherited from NUnit.Framework.Internal.TestResultTests
virtual ResultState ResultState [get]
virtual string ReasonNodeName [get]
Member Function Documentation
override void NUnit.Framework.Internal.DefaultResultTests.SimulateTestRun () inline protected virtual
Implements NUnit.Framework.Internal.TestResultTests.
void NUnit.Framework.Internal.DefaultResultTests.TestResultIsInconclusive () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Inconclusive, NUnit.Framework.Interfaces.ResultState.ResultState(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.DefaultResultTests.SuiteResultIsInconclusive () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Inconclusive, and NUnit.Framework.Interfaces.ResultState.ResultState().
void NUnit.Framework.Internal.DefaultResultTests.TestResultXmlNodeIsInconclusive () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.TNode.Attributes.
void NUnit.Framework.Internal.DefaultResultTests.SuiteResultXmlNodeIsInconclusive () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.TNode.Attributes.
void NUnit.Framework.Internal.DefaultResultTests.SuiteResultXmlNodeHasOneChildTest () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.TNode.SelectNodes().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/TestResultTests.cs