IGLib: CSSendWM_COPYDATA.ClientForm Class Reference
CSSendWM_COPYDATA.ClientForm Class Reference
Public Member Functions
ClientForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void bnSendMessage_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Button bnSendMessage
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox tbMessage
System.Windows.Forms.TextBox tbNumber
Constructor & Destructor Documentation
CSSendWM_COPYDATA.ClientForm.ClientForm () inline
References CSSendWM_COPYDATA.ClientForm.InitializeComponent().
Member Function Documentation
void CSSendWM_COPYDATA.ClientForm.bnSendMessage_Click (object sender, EventArgs e) inline private
References COPYDATASTRUCT.cbData, WindowNative.FindWindow(), COPYDATASTRUCT.lpData, WindowNative.SendMessage(), CSSendWM_COPYDATA.ClientForm.tbMessage, CSSendWM_COPYDATA.ClientForm.tbNumber, and WindowNative.WM_COPYDATA.
Referenced by CSSendWM_COPYDATA.ClientForm.InitializeComponent().
override void CSSendWM_COPYDATA.ClientForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References CSSendWM_COPYDATA.ClientForm.components.
void CSSendWM_COPYDATA.ClientForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References CSSendWM_COPYDATA.ClientForm.bnSendMessage, CSSendWM_COPYDATA.ClientForm.bnSendMessage_Click(), CSSendWM_COPYDATA.ClientForm.groupBox1, CSSendWM_COPYDATA.ClientForm.label1, CSSendWM_COPYDATA.ClientForm.label2, CSSendWM_COPYDATA.ClientForm.tbMessage, and CSSendWM_COPYDATA.ClientForm.tbNumber.
Referenced by CSSendWM_COPYDATA.ClientForm.ClientForm().
Member Data Documentation
System.ComponentModel.IContainer CSSendWM_COPYDATA.ClientForm.components = null private
Required designer variable.
Referenced by CSSendWM_COPYDATA.ClientForm.Dispose().
System.Windows.Forms.GroupBox CSSendWM_COPYDATA.ClientForm.groupBox1 private
Referenced by CSSendWM_COPYDATA.ClientForm.InitializeComponent().
System.Windows.Forms.Button CSSendWM_COPYDATA.ClientForm.bnSendMessage private
Referenced by CSSendWM_COPYDATA.ClientForm.InitializeComponent().
System.Windows.Forms.Label CSSendWM_COPYDATA.ClientForm.label1 private
Referenced by CSSendWM_COPYDATA.ClientForm.InitializeComponent().
System.Windows.Forms.Label CSSendWM_COPYDATA.ClientForm.label2 private
Referenced by CSSendWM_COPYDATA.ClientForm.InitializeComponent().
System.Windows.Forms.TextBox CSSendWM_COPYDATA.ClientForm.tbMessage private
Referenced by CSSendWM_COPYDATA.ClientForm.bnSendMessage_Click(), and CSSendWM_COPYDATA.ClientForm.InitializeComponent().
System.Windows.Forms.TextBox CSSendWM_COPYDATA.ClientForm.tbNumber private
Referenced by CSSendWM_COPYDATA.ClientForm.bnSendMessage_Click(), and CSSendWM_COPYDATA.ClientForm.InitializeComponent().
The documentation for this class was generated from the following files:
igsandbox/InterprocessCommunication/named_pipe_examples_master/Inter-Process Communication (IPC)/CSSendWM_COPYDATA/ClientForm.cs
igsandbox/InterprocessCommunication/named_pipe_examples_master/Inter-Process Communication (IPC)/CSSendWM_COPYDATA/ClientForm.Designer.cs