IGLib: PipeNative Class Reference
PipeNative Class Reference
The class exposes kernel32.dll methods for named pipes communication.
Public Member Functions
static uint GetLastError ()
Retrieves the calling thread's last-error code value.
static IntPtr CreateNamedPipe (String lpName, PipeOpenMode dwOpenMode, PipeMode dwPipeMode, uint nMaxInstances, uint nOutBufferSize, uint nInBufferSize, uint nDefaultTimeOut, IntPtr pipeSecurityAttributes)
Creates an instance of a named pipe and returns a handle for subsequent pipe operations.
static bool ConnectNamedPipe (IntPtr hHandle, IntPtr lpOverlapped)
Enables a named pipe server process to wait for a client process to connect to an instance of a named pipe.
static bool WaitNamedPipe (String name, int timeout)
Waits until either a time-out interval elapses or an instance of the specified named pipe is available for connection.
static bool SetNamedPipeHandleState (IntPtr hHandle, ref PipeMode lpMode, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout)
Sets the read mode and the blocking mode of the specified named pipe.
static IntPtr CreateFile (String lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr fileSecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, uint hTemplateFile)
Creates or opens a file, directory, physical disk, volume, console buffer, tape drive, communications resource, mailslot, or named pipe.
static bool ReadFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToRead, out uint lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, starting at the position indicated by the file pointer.
static bool WriteFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToWrite, out uint lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to a file at the position specified by the file pointer.
static bool CloseHandle (IntPtr hHandle)
Closes an open object handle.
static bool FlushFileBuffers (IntPtr hHandle)
Flushes the buffers of the specified file and causes all buffered data to be written to the file.
static bool DisconnectNamedPipe (IntPtr hHandle)
Disconnects the server end of a named pipe instance from a client process.
static uint GetLastError ()
Retrieves the calling thread's last-error code value.
static IntPtr CreateNamedPipe (String lpName, PipeOpenMode dwOpenMode, PipeMode dwPipeMode, uint nMaxInstances, uint nOutBufferSize, uint nInBufferSize, uint nDefaultTimeOut, IntPtr pipeSecurityAttributes)
Creates an instance of a named pipe and returns a handle for subsequent pipe operations.
static bool ConnectNamedPipe (IntPtr hHandle, IntPtr lpOverlapped)
Enables a named pipe server process to wait for a client process to connect to an instance of a named pipe.
static bool WaitNamedPipe (String name, int timeout)
Waits until either a time-out interval elapses or an instance of the specified named pipe is available for connection.
static bool SetNamedPipeHandleState (IntPtr hHandle, ref PipeMode lpMode, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout)
Sets the read mode and the blocking mode of the specified named pipe.
static IntPtr CreateFile (String lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr fileSecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, uint hTemplateFile)
Creates or opens a file, directory, physical disk, volume, console buffer, tape drive, communications resource, mailslot, or named pipe.
static bool ReadFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToRead, out uint lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, starting at the position indicated by the file pointer.
static bool WriteFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToWrite, out uint lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to a file at the position specified by the file pointer.
static bool CloseHandle (IntPtr hHandle)
Closes an open object handle.
static bool FlushFileBuffers (IntPtr hHandle)
Flushes the buffers of the specified file and causes all buffered data to be written to the file.
static bool DisconnectNamedPipe (IntPtr hHandle)
Disconnects the server end of a named pipe instance from a client process.
static uint GetLastError ()
Retrieves the calling thread's last-error code value.
static IntPtr CreateNamedPipe (String lpName, PipeOpenMode dwOpenMode, PipeMode dwPipeMode, uint nMaxInstances, uint nOutBufferSize, uint nInBufferSize, uint nDefaultTimeOut, IntPtr pipeSecurityAttributes)
Creates an instance of a named pipe and returns a handle for subsequent pipe operations.
static bool ConnectNamedPipe (IntPtr hHandle, IntPtr lpOverlapped)
Enables a named pipe server process to wait for a client process to connect to an instance of a named pipe.
static bool WaitNamedPipe (String name, int timeout)
Waits until either a time-out interval elapses or an instance of the specified named pipe is available for connection.
static bool SetNamedPipeHandleState (IntPtr hHandle, ref PipeMode lpMode, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout)
Sets the read mode and the blocking mode of the specified named pipe.
static IntPtr CreateFile (String lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr fileSecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, uint hTemplateFile)
Creates or opens a file, directory, physical disk, volume, console buffer, tape drive, communications resource, mailslot, or named pipe.
static bool ReadFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToRead, out uint lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, starting at the position indicated by the file pointer.
static bool WriteFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToWrite, out uint lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to a file at the position specified by the file pointer.
static bool CloseHandle (IntPtr hHandle)
Closes an open object handle.
static bool FlushFileBuffers (IntPtr hHandle)
Flushes the buffers of the specified file and causes all buffered data to be written to the file.
static bool DisconnectNamedPipe (IntPtr hHandle)
Disconnects the server end of a named pipe instance from a client process.
static uint GetLastError ()
Retrieves the calling thread's last-error code value.
static IntPtr CreateNamedPipe (String lpName, PipeOpenMode dwOpenMode, PipeMode dwPipeMode, uint nMaxInstances, uint nOutBufferSize, uint nInBufferSize, uint nDefaultTimeOut, IntPtr pipeSecurityAttributes)
Creates an instance of a named pipe and returns a handle for subsequent pipe operations.
static bool ConnectNamedPipe (IntPtr hHandle, IntPtr lpOverlapped)
Enables a named pipe server process to wait for a client process to connect to an instance of a named pipe.
static bool WaitNamedPipe (String name, int timeout)
Waits until either a time-out interval elapses or an instance of the specified named pipe is available for connection.
static bool SetNamedPipeHandleState (IntPtr hHandle, ref PipeMode lpMode, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout)
Sets the read mode and the blocking mode of the specified named pipe.
static IntPtr CreateFile (String lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr fileSecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, uint hTemplateFile)
Creates or opens a file, directory, physical disk, volume, console buffer, tape drive, communications resource, mailslot, or named pipe.
static bool ReadFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToRead, out uint lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, starting at the position indicated by the file pointer.
static bool WriteFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToWrite, out uint lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to a file at the position specified by the file pointer.
static bool CloseHandle (IntPtr hHandle)
Closes an open object handle.
static bool FlushFileBuffers (IntPtr hHandle)
Flushes the buffers of the specified file and causes all buffered data to be written to the file.
static bool DisconnectNamedPipe (IntPtr hHandle)
Disconnects the server end of a named pipe instance from a client process.
static uint GetLastError ()
Retrieves the calling thread's last-error code value.
static IntPtr CreateNamedPipe (String lpName, PipeOpenMode dwOpenMode, PipeMode dwPipeMode, uint nMaxInstances, uint nOutBufferSize, uint nInBufferSize, uint nDefaultTimeOut, IntPtr pipeSecurityAttributes)
Creates an instance of a named pipe and returns a handle for subsequent pipe operations.
static bool ConnectNamedPipe (IntPtr hHandle, IntPtr lpOverlapped)
Enables a named pipe server process to wait for a client process to connect to an instance of a named pipe.
static bool WaitNamedPipe (String name, int timeout)
Waits until either a time-out interval elapses or an instance of the specified named pipe is available for connection.
static bool SetNamedPipeHandleState (IntPtr hHandle, ref PipeMode lpMode, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout)
Sets the read mode and the blocking mode of the specified named pipe.
static IntPtr CreateFile (String lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr fileSecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, uint hTemplateFile)
Creates or opens a file, directory, physical disk, volume, console buffer, tape drive, communications resource, mailslot, or named pipe.
static bool ReadFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToRead, out uint lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, starting at the position indicated by the file pointer.
static bool WriteFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToWrite, out uint lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to a file at the position specified by the file pointer.
static bool CloseHandle (IntPtr hHandle)
Closes an open object handle.
static bool FlushFileBuffers (IntPtr hHandle)
Flushes the buffers of the specified file and causes all buffered data to be written to the file.
static bool DisconnectNamedPipe (IntPtr hHandle)
Disconnects the server end of a named pipe instance from a client process.
Public Attributes
const uint PIPE_UNLIMITED_INSTANCES = 255
Unlimited server pipe instances.
const ulong ERROR_SUCCESS = 0
The operation completed successfully.
const ulong ERROR_CANNOT_CONNECT_TO_PIPE = 2
The system cannot find the file specified.
const ulong ERROR_PIPE_BUSY = 231
All pipe instances are busy.
const ulong ERROR_NO_DATA = 232
The pipe is being closed.
const ulong ERROR_PIPE_NOT_CONNECTED = 233
No process is on the other end of the pipe.
const ulong ERROR_MORE_DATA = 234
More data is available.
const ulong ERROR_PIPE_CONNECTED = 535
There is a process on other end of the pipe.
const ulong ERROR_PIPE_LISTENING = 536
Waiting for a process to open the other end of the pipe.
const uint NMPWAIT_WAIT_FOREVER = 0xffffffff
Waits indefinitely when connecting to a pipe.
const uint NMPWAIT_NOWAIT = 0x00000001
Does not wait for the named pipe.
const uint NMPWAIT_USE_DEFAULT_WAIT = 0x00000000
Uses the default time-out specified in a call to the CreateNamedPipe method.
const int INVALID_HANDLE_VALUE = -1
Invalid operating system handle.
Detailed Description
The class exposes kernel32.dll methods for named pipes communication.
Member Function Documentation
static uint PipeNative.GetLastError ()
Retrieves the calling thread's last-error code value.
Returns
The return value is the calling thread's last-error code value.
Referenced by Program.answerSNMP(), Program.listenToSNMP(), Program.PInvokeNativePipeClient(), and Program.PInvokeNativePipeServer().
static IntPtr PipeNative.CreateNamedPipe (String lpName, PipeOpenMode dwOpenMode, PipeMode dwPipeMode, uint nMaxInstances, uint nOutBufferSize, uint nInBufferSize, uint nDefaultTimeOut, IntPtr pipeSecurityAttributes)
Creates an instance of a named pipe and returns a handle for subsequent pipe operations.
Parameters
lpName Pipe name
dwOpenMode Pipe open mode
dwPipeMode Pipe-specific modes
nMaxInstances Maximum number of instances
nOutBufferSize Output buffer size
nInBufferSize Input buffer size
nDefaultTimeOut Time-out interval
pipeSecurityAttributes Security attributes
Returns
If the function succeeds, the return value is a handle to the server end of a named pipe instance.
Referenced by Program.answerSNMP(), Program.listenToSNMP(), and Program.PInvokeNativePipeServer().
static bool PipeNative.ConnectNamedPipe (IntPtr hHandle, IntPtr lpOverlapped)
Enables a named pipe server process to wait for a client process to connect to an instance of a named pipe.
Parameters
hHandle Handle to the server end of a named pipe instance.
lpOverlapped Pointer to an Overlapped object.
Returns
If the function succeeds, the return value is nonzero.
Referenced by Program.answerSNMP(), Program.listenToSNMP(), and Program.PInvokeNativePipeServer().
static bool PipeNative.WaitNamedPipe (String name, int timeout)
Waits until either a time-out interval elapses or an instance of the specified named pipe is available for connection.
Parameters
name Pointer to a null-terminated string that specifies the name of the named pipe.
timeout Number of milliseconds that the function will wait for an instance of the named pipe to be available.
Returns
If an instance of the pipe is available before the time-out interval elapses, the return value is nonzero.
Referenced by Program.PInvokeNativePipeClient().
static bool PipeNative.SetNamedPipeHandleState (IntPtr hHandle, ref PipeMode lpMode, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout)
Sets the read mode and the blocking mode of the specified named pipe.
If the specified handle is to the client end of a named pipe and if the named pipe server process is on a remote computer, the function can also be used to control local buffering.
Parameters
hHandle Handle to the named pipe instance.
lpMode Pointer to a variable that supplies the new mode.
lpMaxCollectionCount Pointer to a variable that specifies the maximum number of bytes collected on the client computer before transmission to the server.
lpCollectDataTimeout Pointer to a variable that specifies the maximum time, in milliseconds, that can pass before a remote named pipe transfers information over the network.
Returns
If the function succeeds, the return value is nonzero.
Referenced by Program.PInvokeNativePipeClient().
static IntPtr PipeNative.CreateFile (String lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr fileSecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, uint hTemplateFile)
Creates or opens a file, directory, physical disk, volume, console buffer, tape drive, communications resource, mailslot, or named pipe.
Parameters
lpFileName File name.
dwDesiredAccess Access to the object (reading, writing, or both).
dwShareMode Sharing mode of the object (reading, writing, both, or neither).
fileSecurityAttributes Pointer to a SecurityAttributes object that determines whether the returned handle can be inherited by child processes.
dwCreationDisposition Action to take on files that exist, and which action to take when files do not exist
dwFlagsAndAttributes File attributes and flags.
hTemplateFile Handle to a template file.
Returns
If the function succeeds, the return value is an open handle to the specified file.
Referenced by Program.PInvokeNativePipeClient().
static bool PipeNative.ReadFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToRead, out uint lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, starting at the position indicated by the file pointer.
Parameters
hHandle Handle to the file to be read.
lpBuffer Pointer to the buffer that receives the data read from the file.
nNumberOfBytesToRead Number of bytes to be read from the file.
lpNumberOfBytesRead Pointer to the variable that receives the number of bytes read.
lpOverlapped Pointer to an Overlapped object.
Returns
The ReadFile function returns when one of the following conditions is met: a write operation completes on the write end of the pipe, the number of bytes requested has been read, or an error occurs.
Referenced by Program.answerSNMP(), Program.listenToSNMP(), Program.PInvokeNativePipeClient(), and Program.PInvokeNativePipeServer().
static bool PipeNative.WriteFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToWrite, out uint lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to a file at the position specified by the file pointer.
Parameters
hHandle Handle to the file.
lpBuffer Pointer to the buffer containing the data to be written to the file.
nNumberOfBytesToWrite Number of bytes to be write to the file.
lpNumberOfBytesWritten Pointer to the variable that receives the number of bytes written.
lpOverlapped Pointer to an Overlapped object.
Returns
If the function succeeds, the return value is nonzero.
Referenced by Program.answerSNMP(), Program.PInvokeNativePipeClient(), and Program.PInvokeNativePipeServer().
static bool PipeNative.CloseHandle (IntPtr hHandle)
Closes an open object handle.
Parameters
hHandle Handle to an open object.
Returns
If the function succeeds, the return value is nonzero.
Referenced by Program.answerSNMP(), Program.listenToSNMP(), Program.PInvokeNativePipeClient(), and Program.PInvokeNativePipeServer().
static bool PipeNative.FlushFileBuffers (IntPtr hHandle)
Flushes the buffers of the specified file and causes all buffered data to be written to the file.
Parameters
hHandle Handle to an open file.
Returns
If the function succeeds, the return value is nonzero.
Referenced by Program.answerSNMP(), Program.listenToSNMP(), and Program.PInvokeNativePipeServer().
static bool PipeNative.DisconnectNamedPipe (IntPtr hHandle)
Disconnects the server end of a named pipe instance from a client process.
Parameters
hHandle Handle to an instance of a named pipe.
Returns
If the function succeeds, the return value is nonzero.
Referenced by Program.answerSNMP(), Program.listenToSNMP(), and Program.PInvokeNativePipeServer().
static uint PipeNative.GetLastError ()
Retrieves the calling thread's last-error code value.
Returns
The return value is the calling thread's last-error code value.
static IntPtr PipeNative.CreateNamedPipe (String lpName, PipeOpenMode dwOpenMode, PipeMode dwPipeMode, uint nMaxInstances, uint nOutBufferSize, uint nInBufferSize, uint nDefaultTimeOut, IntPtr pipeSecurityAttributes)
Creates an instance of a named pipe and returns a handle for subsequent pipe operations.
Parameters
lpName Pipe name
dwOpenMode Pipe open mode
dwPipeMode Pipe-specific modes
nMaxInstances Maximum number of instances
nOutBufferSize Output buffer size
nInBufferSize Input buffer size
nDefaultTimeOut Time-out interval
pipeSecurityAttributes Security attributes
Returns
If the function succeeds, the return value is a handle to the server end of a named pipe instance.
static bool PipeNative.ConnectNamedPipe (IntPtr hHandle, IntPtr lpOverlapped)
Enables a named pipe server process to wait for a client process to connect to an instance of a named pipe.
Parameters
hHandle Handle to the server end of a named pipe instance.
lpOverlapped Pointer to an Overlapped object.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.WaitNamedPipe (String name, int timeout)
Waits until either a time-out interval elapses or an instance of the specified named pipe is available for connection.
Parameters
name Pointer to a null-terminated string that specifies the name of the named pipe.
timeout Number of milliseconds that the function willwait for an instance of the named pipe to be available.
Returns
If an instance of the pipe is available before the time-out interval elapses, the return value is nonzero.
static bool PipeNative.SetNamedPipeHandleState (IntPtr hHandle, ref PipeMode lpMode, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout)
Sets the read mode and the blocking mode of the specified named pipe.
If the specified handle is to the client end of a named pipe and if the named pipe server process is on a remote computer, the function can also be used to control local buffering.
Parameters
hHandle Handle to the named pipe instance.
lpMode Pointer to a variable that supplies the new mode.
lpMaxCollectionCount Pointer to a variable that specifies the maximum number of bytes collected on the client computer before transmission to the server.
lpCollectDataTimeout Pointer to a variable that specifies the maximum time, in milliseconds, that can pass before a remote named pipe transfers information over the network.
Returns
If the function succeeds, the return value is nonzero.
static IntPtr PipeNative.CreateFile (String lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr fileSecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, uint hTemplateFile)
Creates or opens a file, directory, physical disk, volume, console buffer, tape drive, communications resource, mailslot, or named pipe.
Parameters
lpFileName File name.
dwDesiredAccess Access to the object (reading, writing, or both).
dwShareMode Sharing mode of the object (reading, writing, both, or neither).
fileSecurityAttributes Pointer to a SecurityAttributes object that determines whether the returned handle can be inherited by child processes.
dwCreationDisposition Action to take on files that exist, and which action to take when files do not exist
dwFlagsAndAttributes File attributes and flags.
hTemplateFile Handle to a template file.
Returns
If the function succeeds, the return value is an open handle to the specified file.
static bool PipeNative.ReadFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToRead, out uint lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, starting at the position indicated by the file pointer.
Parameters
hHandle Handle to the file to be read.
lpBuffer Pointer to the buffer that receives the data read from the file.
nNumberOfBytesToRead Number of bytes to be read from the file.
lpNumberOfBytesRead Pointer to the variable that receives the number of bytes read.
lpOverlapped Pointer to an Overlapped object.
Returns
The ReadFile function returns when one of the following conditions is met: a write operation completes on the write end of the pipe, the number of bytes requested has been read, or an error occurs.
static bool PipeNative.WriteFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToWrite, out uint lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to a file at the position specified by the file pointer.
Parameters
hHandle Handle to the file.
lpBuffer Pointer to the buffer containing the data to be written to the file.
nNumberOfBytesToWrite Number of bytes to be write to the file.
lpNumberOfBytesWritten Pointer to the variable that receives the number of bytes written.
lpOverlapped Pointer to an Overlapped object.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.CloseHandle (IntPtr hHandle)
Closes an open object handle.
Parameters
hHandle Handle to an open object.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.FlushFileBuffers (IntPtr hHandle)
Flushes the buffers of the specified file and causes all buffered data to be written to the file.
Parameters
hHandle Handle to an open file.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.DisconnectNamedPipe (IntPtr hHandle)
Disconnects the server end of a named pipe instance from a client process.
Parameters
hHandle Handle to an instance of a named pipe.
Returns
If the function succeeds, the return value is nonzero.
static uint PipeNative.GetLastError ()
Retrieves the calling thread's last-error code value.
Returns
The return value is the calling thread's last-error code value.
static IntPtr PipeNative.CreateNamedPipe (String lpName, PipeOpenMode dwOpenMode, PipeMode dwPipeMode, uint nMaxInstances, uint nOutBufferSize, uint nInBufferSize, uint nDefaultTimeOut, IntPtr pipeSecurityAttributes)
Creates an instance of a named pipe and returns a handle for subsequent pipe operations.
Parameters
lpName Pipe name
dwOpenMode Pipe open mode
dwPipeMode Pipe-specific modes
nMaxInstances Maximum number of instances
nOutBufferSize Output buffer size
nInBufferSize Input buffer size
nDefaultTimeOut Time-out interval
pipeSecurityAttributes Security attributes
Returns
If the function succeeds, the return value is a handle to the server end of a named pipe instance.
static bool PipeNative.ConnectNamedPipe (IntPtr hHandle, IntPtr lpOverlapped)
Enables a named pipe server process to wait for a client process to connect to an instance of a named pipe.
Parameters
hHandle Handle to the server end of a named pipe instance.
lpOverlapped Pointer to an Overlapped object.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.WaitNamedPipe (String name, int timeout)
Waits until either a time-out interval elapses or an instance of the specified named pipe is available for connection.
Parameters
name Pointer to a null-terminated string that specifies the name of the named pipe.
timeout Number of milliseconds that the function will wait for an instance of the named pipe to be available.
Returns
If an instance of the pipe is available before the time-out interval elapses, the return value is nonzero.
static bool PipeNative.SetNamedPipeHandleState (IntPtr hHandle, ref PipeMode lpMode, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout)
Sets the read mode and the blocking mode of the specified named pipe.
If the specified handle is to the client end of a named pipe and if the named pipe server process is on a remote computer, the function can also be used to control local buffering.
Parameters
hHandle Handle to the named pipe instance.
lpMode Pointer to a variable that supplies the new mode.
lpMaxCollectionCount Pointer to a variable that specifies the maximum number of bytes collected on the client computer before transmission to the server.
lpCollectDataTimeout Pointer to a variable that specifies the maximum time, in milliseconds, that can pass before a remote named pipe transfers information over the network.
Returns
If the function succeeds, the return value is nonzero.
static IntPtr PipeNative.CreateFile (String lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr fileSecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, uint hTemplateFile)
Creates or opens a file, directory, physical disk, volume, console buffer, tape drive, communications resource, mailslot, or named pipe.
Parameters
lpFileName File name.
dwDesiredAccess Access to the object (reading, writing, or both).
dwShareMode Sharing mode of the object (reading, writing, both, or neither).
fileSecurityAttributes Pointer to a SecurityAttributes object that determines whether the returned handle can be inherited by child processes.
dwCreationDisposition Action to take on files that exist, and which action to take when files do not exist
dwFlagsAndAttributes File attributes and flags.
hTemplateFile Handle to a template file.
Returns
If the function succeeds, the return value is an open handle to the specified file.
static bool PipeNative.ReadFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToRead, out uint lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, starting at the position indicated by the file pointer.
Parameters
hHandle Handle to the file to be read.
lpBuffer Pointer to the buffer that receives the data read from the file.
nNumberOfBytesToRead Number of bytes to be read from the file.
lpNumberOfBytesRead Pointer to the variable that receives the number of bytes read.
lpOverlapped Pointer to an Overlapped object.
Returns
The ReadFile function returns when one of the following conditions is met: a write operation completes on the write end of the pipe, the number of bytes requested has been read, or an error occurs.
static bool PipeNative.WriteFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToWrite, out uint lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to a file at the position specified by the file pointer.
Parameters
hHandle Handle to the file.
lpBuffer Pointer to the buffer containing the data to be written to the file.
nNumberOfBytesToWrite Number of bytes to be write to the file.
lpNumberOfBytesWritten Pointer to the variable that receives the number of bytes written.
lpOverlapped Pointer to an Overlapped object.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.CloseHandle (IntPtr hHandle)
Closes an open object handle.
Parameters
hHandle Handle to an open object.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.FlushFileBuffers (IntPtr hHandle)
Flushes the buffers of the specified file and causes all buffered data to be written to the file.
Parameters
hHandle Handle to an open file.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.DisconnectNamedPipe (IntPtr hHandle)
Disconnects the server end of a named pipe instance from a client process.
Parameters
hHandle Handle to an instance of a named pipe.
Returns
If the function succeeds, the return value is nonzero.
static uint PipeNative.GetLastError ()
Retrieves the calling thread's last-error code value.
Returns
The return value is the calling thread's last-error code value.
static IntPtr PipeNative.CreateNamedPipe (String lpName, PipeOpenMode dwOpenMode, PipeMode dwPipeMode, uint nMaxInstances, uint nOutBufferSize, uint nInBufferSize, uint nDefaultTimeOut, IntPtr pipeSecurityAttributes)
Creates an instance of a named pipe and returns a handle for subsequent pipe operations.
Parameters
lpName Pipe name
dwOpenMode Pipe open mode
dwPipeMode Pipe-specific modes
nMaxInstances Maximum number of instances
nOutBufferSize Output buffer size
nInBufferSize Input buffer size
nDefaultTimeOut Time-out interval
pipeSecurityAttributes Security attributes
Returns
If the function succeeds, the return value is a handle to the server end of a named pipe instance.
static bool PipeNative.ConnectNamedPipe (IntPtr hHandle, IntPtr lpOverlapped)
Enables a named pipe server process to wait for a client process to connect to an instance of a named pipe.
Parameters
hHandle Handle to the server end of a named pipe instance.
lpOverlapped Pointer to an Overlapped object.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.WaitNamedPipe (String name, int timeout)
Waits until either a time-out interval elapses or an instance of the specified named pipe is available for connection.
Parameters
name Pointer to a null-terminated string that specifies the name of the named pipe.
timeout Number of milliseconds that the function willwait for an instance of the named pipe to be available.
Returns
If an instance of the pipe is available before the time-out interval elapses, the return value is nonzero.
static bool PipeNative.SetNamedPipeHandleState (IntPtr hHandle, ref PipeMode lpMode, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout)
Sets the read mode and the blocking mode of the specified named pipe.
If the specified handle is to the client end of a named pipe and if the named pipe server process is on a remote computer, the function can also be used to control local buffering.
Parameters
hHandle Handle to the named pipe instance.
lpMode Pointer to a variable that supplies the new mode.
lpMaxCollectionCount Pointer to a variable that specifies the maximum number of bytes collected on the client computer before transmission to the server.
lpCollectDataTimeout Pointer to a variable that specifies the maximum time, in milliseconds, that can pass before a remote named pipe transfers information over the network.
Returns
If the function succeeds, the return value is nonzero.
static IntPtr PipeNative.CreateFile (String lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr fileSecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, uint hTemplateFile)
Creates or opens a file, directory, physical disk, volume, console buffer, tape drive, communications resource, mailslot, or named pipe.
Parameters
lpFileName File name.
dwDesiredAccess Access to the object (reading, writing, or both).
dwShareMode Sharing mode of the object (reading, writing, both, or neither).
fileSecurityAttributes Pointer to a SecurityAttributes object that determines whether the returned handle can be inherited by child processes.
dwCreationDisposition Action to take on files that exist, and which action to take when files do not exist
dwFlagsAndAttributes File attributes and flags.
hTemplateFile Handle to a template file.
Returns
If the function succeeds, the return value is an open handle to the specified file.
static bool PipeNative.ReadFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToRead, out uint lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, starting at the position indicated by the file pointer.
Parameters
hHandle Handle to the file to be read.
lpBuffer Pointer to the buffer that receives the data read from the file.
nNumberOfBytesToRead Number of bytes to be read from the file.
lpNumberOfBytesRead Pointer to the variable that receives the number of bytes read.
lpOverlapped Pointer to an Overlapped object.
Returns
The ReadFile function returns when one of the following conditions is met: a write operation completes on the write end of the pipe, the number of bytes requested has been read, or an error occurs.
static bool PipeNative.WriteFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToWrite, out uint lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to a file at the position specified by the file pointer.
Parameters
hHandle Handle to the file.
lpBuffer Pointer to the buffer containing the data to be written to the file.
nNumberOfBytesToWrite Number of bytes to be write to the file.
lpNumberOfBytesWritten Pointer to the variable that receives the number of bytes written.
lpOverlapped Pointer to an Overlapped object.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.CloseHandle (IntPtr hHandle)
Closes an open object handle.
Parameters
hHandle Handle to an open object.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.FlushFileBuffers (IntPtr hHandle)
Flushes the buffers of the specified file and causes all buffered data to be written to the file.
Parameters
hHandle Handle to an open file.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.DisconnectNamedPipe (IntPtr hHandle)
Disconnects the server end of a named pipe instance from a client process.
Parameters
hHandle Handle to an instance of a named pipe.
Returns
If the function succeeds, the return value is nonzero.
static uint PipeNative.GetLastError ()
Retrieves the calling thread's last-error code value.
Returns
The return value is the calling thread's last-error code value.
static IntPtr PipeNative.CreateNamedPipe (String lpName, PipeOpenMode dwOpenMode, PipeMode dwPipeMode, uint nMaxInstances, uint nOutBufferSize, uint nInBufferSize, uint nDefaultTimeOut, IntPtr pipeSecurityAttributes)
Creates an instance of a named pipe and returns a handle for subsequent pipe operations.
Parameters
lpName Pipe name
dwOpenMode Pipe open mode
dwPipeMode Pipe-specific modes
nMaxInstances Maximum number of instances
nOutBufferSize Output buffer size
nInBufferSize Input buffer size
nDefaultTimeOut Time-out interval
pipeSecurityAttributes Security attributes
Returns
If the function succeeds, the return value is a handle to the server end of a named pipe instance.
static bool PipeNative.ConnectNamedPipe (IntPtr hHandle, IntPtr lpOverlapped)
Enables a named pipe server process to wait for a client process to connect to an instance of a named pipe.
Parameters
hHandle Handle to the server end of a named pipe instance.
lpOverlapped Pointer to an Overlapped object.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.WaitNamedPipe (String name, int timeout)
Waits until either a time-out interval elapses or an instance of the specified named pipe is available for connection.
Parameters
name Pointer to a null-terminated string that specifies the name of the named pipe.
timeout Number of milliseconds that the function will wait for an instance of the named pipe to be available.
Returns
If an instance of the pipe is available before the time-out interval elapses, the return value is nonzero.
static bool PipeNative.SetNamedPipeHandleState (IntPtr hHandle, ref PipeMode lpMode, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout)
Sets the read mode and the blocking mode of the specified named pipe.
If the specified handle is to the client end of a named pipe and if the named pipe server process is on a remote computer, the function can also be used to control local buffering.
Parameters
hHandle Handle to the named pipe instance.
lpMode Pointer to a variable that supplies the new mode.
lpMaxCollectionCount Pointer to a variable that specifies the maximum number of bytes collected on the client computer before transmission to the server.
lpCollectDataTimeout Pointer to a variable that specifies the maximum time, in milliseconds, that can pass before a remote named pipe transfers information over the network.
Returns
If the function succeeds, the return value is nonzero.
static IntPtr PipeNative.CreateFile (String lpFileName, FileDesiredAccess dwDesiredAccess, FileShareMode dwShareMode, IntPtr fileSecurityAttributes, FileCreationDisposition dwCreationDisposition, uint dwFlagsAndAttributes, uint hTemplateFile)
Creates or opens a file, directory, physical disk, volume, console buffer, tape drive, communications resource, mailslot, or named pipe.
Parameters
lpFileName File name.
dwDesiredAccess Access to the object (reading, writing, or both).
dwShareMode Sharing mode of the object (reading, writing, both, or neither).
fileSecurityAttributes Pointer to a SecurityAttributes object that determines whether the returned handle can be inherited by child processes.
dwCreationDisposition Action to take on files that exist, and which action to take when files do not exist
dwFlagsAndAttributes File attributes and flags.
hTemplateFile Handle to a template file.
Returns
If the function succeeds, the return value is an open handle to the specified file.
static bool PipeNative.ReadFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToRead, out uint lpNumberOfBytesRead, IntPtr lpOverlapped)
Reads data from a file, starting at the position indicated by the file pointer.
Parameters
hHandle Handle to the file to be read.
lpBuffer Pointer to the buffer that receives the data read from the file.
nNumberOfBytesToRead Number of bytes to be read from the file.
lpNumberOfBytesRead Pointer to the variable that receives the number of bytes read.
lpOverlapped Pointer to an Overlapped object.
Returns
The ReadFile function returns when one of the following conditions is met: a write operation completes on the write end of the pipe, the number of bytes requested has been read, or an error occurs.
static bool PipeNative.WriteFile (IntPtr hHandle, byte[] lpBuffer, uint nNumberOfBytesToWrite, out uint lpNumberOfBytesWritten, IntPtr lpOverlapped)
Writes data to a file at the position specified by the file pointer.
Parameters
hHandle Handle to the file.
lpBuffer Pointer to the buffer containing the data to be written to the file.
nNumberOfBytesToWrite Number of bytes to be write to the file.
lpNumberOfBytesWritten Pointer to the variable that receives the number of bytes written.
lpOverlapped Pointer to an Overlapped object.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.CloseHandle (IntPtr hHandle)
Closes an open object handle.
Parameters
hHandle Handle to an open object.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.FlushFileBuffers (IntPtr hHandle)
Flushes the buffers of the specified file and causes all buffered data to be written to the file.
Parameters
hHandle Handle to an open file.
Returns
If the function succeeds, the return value is nonzero.
static bool PipeNative.DisconnectNamedPipe (IntPtr hHandle)
Disconnects the server end of a named pipe instance from a client process.
Parameters
hHandle Handle to an instance of a named pipe.
Returns
If the function succeeds, the return value is nonzero.
Member Data Documentation
const uint PipeNative.PIPE_UNLIMITED_INSTANCES = 255
Unlimited server pipe instances.
Referenced by Program.answerSNMP(), Program.listenToSNMP(), and Program.PInvokeNativePipeServer().
const ulong PipeNative.ERROR_SUCCESS = 0
The operation completed successfully.
const ulong PipeNative.ERROR_CANNOT_CONNECT_TO_PIPE = 2
The system cannot find the file specified.
const ulong PipeNative.ERROR_PIPE_BUSY = 231
All pipe instances are busy.
Referenced by Program.PInvokeNativePipeClient().
const ulong PipeNative.ERROR_NO_DATA = 232
The pipe is being closed.
const ulong PipeNative.ERROR_PIPE_NOT_CONNECTED = 233
No process is on the other end of the pipe.
const ulong PipeNative.ERROR_MORE_DATA = 234
More data is available.
Referenced by Program.PInvokeNativePipeClient().
const ulong PipeNative.ERROR_PIPE_CONNECTED = 535
There is a process on other end of the pipe.
Referenced by Program.answerSNMP(), Program.listenToSNMP(), and Program.PInvokeNativePipeServer().
const ulong PipeNative.ERROR_PIPE_LISTENING = 536
Waiting for a process to open the other end of the pipe.
const uint PipeNative.NMPWAIT_WAIT_FOREVER = 0xffffffff
Waits indefinitely when connecting to a pipe.
const uint PipeNative.NMPWAIT_NOWAIT = 0x00000001
Does not wait for the named pipe.
const uint PipeNative.NMPWAIT_USE_DEFAULT_WAIT = 0x00000000
Uses the default time-out specified in a call to the CreateNamedPipe method.
Referenced by Program.answerSNMP(), Program.listenToSNMP(), and Program.PInvokeNativePipeServer().
const int PipeNative.INVALID_HANDLE_VALUE = -1
Invalid operating system handle.
Referenced by Program.answerSNMP(), Program.listenToSNMP(), Program.PInvokeNativePipeClient(), and Program.PInvokeNativePipeServer().
The documentation for this class was generated from the following file:
igsandbox/InterprocessCommunication/named_pipe_examples_master/C++ client & C# server FULL-DUPLEX/CSPipeServer/CSPipeServer/PipeNative.cs