IGLib: NUnit.Framework.Constraints.ConstraintTestBaseNoData Class Reference
NUnit.Framework.Constraints.ConstraintTestBaseNoData Class Reference
Public Member Functions
void ProvidesProperDescription ()
void ProvidesProperStringRepresentation ()
Protected Attributes
Constraint theConstraint
string expectedDescription = "<NOT SET>"
string stringRepresentation = "<NOT SET>"
Member Function Documentation
void NUnit.Framework.Constraints.ConstraintTestBaseNoData.ProvidesProperDescription () inline
References NUnit.Framework.Constraints.Constraint.Description, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.ConstraintTestBaseNoData.ProvidesProperStringRepresentation () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.Constraint.ToString().
Member Data Documentation
Constraint NUnit.Framework.Constraints.ConstraintTestBaseNoData.theConstraint protected
string NUnit.Framework.Constraints.ConstraintTestBaseNoData.expectedDescription = "<NOT SET>" protected
string NUnit.Framework.Constraints.ConstraintTestBaseNoData.stringRepresentation = "<NOT SET>" protected
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/ConstraintTestBase.cs