IGLib: alglib.apserv Class Reference
alglib.apserv Class Reference
Classes
class apbuffers
class sboolean
class sbooleanarray
class scomplex
class scomplexarray
class sinteger
class sintegerarray
class sreal
class srealarray
Static Public Member Functions
static bool approxequalrel (double a, double b, double tol)
static void taskgenint1d (double a, double b, int n, ref double[] x, ref double[] y)
static void taskgenint1dequidist (double a, double b, int n, ref double[] x, ref double[] y)
static void taskgenint1dcheb1 (double a, double b, int n, ref double[] x, ref double[] y)
static void taskgenint1dcheb2 (double a, double b, int n, ref double[] x, ref double[] y)
static bool aredistinct (double[] x, int n)
static bool aresameboolean (bool v1, bool v2)
static void bvectorsetlengthatleast (ref bool[] x, int n)
static void ivectorsetlengthatleast (ref int[] x, int n)
static void rvectorsetlengthatleast (ref double[] x, int n)
static void rmatrixsetlengthatleast (ref double[,] x, int m, int n)
static void rmatrixresize (ref double[,] x, int m, int n)
static bool isfinitevector (double[] x, int n)
static bool isfinitecvector (complex[] z, int n)
static bool apservisfinitematrix (double[,] x, int m, int n)
static bool apservisfinitecmatrix (complex[,] x, int m, int n)
static bool isfinitertrmatrix (double[,] x, int n, bool isupper)
static bool apservisfinitectrmatrix (complex[,] x, int n, bool isupper)
static bool apservisfiniteornanmatrix (double[,] x, int m, int n)
static double safepythag2 (double x, double y)
static double safepythag3 (double x, double y, double z)
static int saferdiv (double x, double y, ref double r)
static double safeminposrv (double x, double y, double v)
static void apperiodicmap (ref double x, double a, double b, ref double k)
static double boundval (double x, double b1, double b2)
static void alloccomplex (alglib.serializer s, complex v)
static void serializecomplex (alglib.serializer s, complex v)
static complex unserializecomplex (alglib.serializer s)
static void allocrealarray (alglib.serializer s, double[] v, int n)
static void serializerealarray (alglib.serializer s, double[] v, int n)
static void unserializerealarray (alglib.serializer s, ref double[] v)
static void allocintegerarray (alglib.serializer s, int[] v, int n)
static void serializeintegerarray (alglib.serializer s, int[] v, int n)
static void unserializeintegerarray (alglib.serializer s, ref int[] v)
static void allocrealmatrix (alglib.serializer s, double[,] v, int n0, int n1)
static void serializerealmatrix (alglib.serializer s, double[,] v, int n0, int n1)
static void unserializerealmatrix (alglib.serializer s, ref double[,] v)
static void copyintegerarray (int[] src, ref int[] dst)
static void copyrealarray (double[] src, ref double[] dst)
static void copyrealmatrix (double[,] src, ref double[,] dst)
static int recsearch (ref int[] a, int nrec, int nheader, int i0, int i1, int[] b)
static bool seterrorflag (ref bool flag, bool cond)
static bool seterrorflagdiff (ref bool flag, double val, double refval, double tol, double s)
static void touchint (ref int a)
static void touchreal (ref double a)
static double inttoreal (int a)
static double logbase2 (double x)
static bool approxequalrel (double a, double b, double tol)
static void taskgenint1d (double a, double b, int n, ref double[] x, ref double[] y)
static void taskgenint1dequidist (double a, double b, int n, ref double[] x, ref double[] y)
static void taskgenint1dcheb1 (double a, double b, int n, ref double[] x, ref double[] y)
static void taskgenint1dcheb2 (double a, double b, int n, ref double[] x, ref double[] y)
static bool aredistinct (double[] x, int n)
static bool aresameboolean (bool v1, bool v2)
static void bvectorsetlengthatleast (ref bool[] x, int n)
static void ivectorsetlengthatleast (ref int[] x, int n)
static void rvectorsetlengthatleast (ref double[] x, int n)
static void rmatrixsetlengthatleast (ref double[,] x, int m, int n)
static void rmatrixresize (ref double[,] x, int m, int n)
static void imatrixresize (ref int[,] x, int m, int n)
static bool isfinitevector (double[] x, int n)
static bool isfinitecvector (complex[] z, int n)
static bool apservisfinitematrix (double[,] x, int m, int n)
static bool apservisfinitecmatrix (complex[,] x, int m, int n)
static bool isfinitertrmatrix (double[,] x, int n, bool isupper)
static bool apservisfinitectrmatrix (complex[,] x, int n, bool isupper)
static bool apservisfiniteornanmatrix (double[,] x, int m, int n)
static double safepythag2 (double x, double y)
static double safepythag3 (double x, double y, double z)
static int saferdiv (double x, double y, ref double r)
static double safeminposrv (double x, double y, double v)
static void apperiodicmap (ref double x, double a, double b, ref double k)
static double randomnormal ()
static void randomunit (int n, ref double[] x)
static void inc (ref int v)
static void dec (ref int v)
static void countdown (ref int v)
static double boundval (double x, double b1, double b2)
static void alloccomplex (alglib.serializer s, complex v)
static void serializecomplex (alglib.serializer s, complex v)
static complex unserializecomplex (alglib.serializer s)
static void allocrealarray (alglib.serializer s, double[] v, int n)
static void serializerealarray (alglib.serializer s, double[] v, int n)
static void unserializerealarray (alglib.serializer s, ref double[] v)
static void allocintegerarray (alglib.serializer s, int[] v, int n)
static void serializeintegerarray (alglib.serializer s, int[] v, int n)
static void unserializeintegerarray (alglib.serializer s, ref int[] v)
static void allocrealmatrix (alglib.serializer s, double[,] v, int n0, int n1)
static void serializerealmatrix (alglib.serializer s, double[,] v, int n0, int n1)
static void unserializerealmatrix (alglib.serializer s, ref double[,] v)
static void copyintegerarray (int[] src, ref int[] dst)
static void copyrealarray (double[] src, ref double[] dst)
static void copyrealmatrix (double[,] src, ref double[,] dst)
static int recsearch (ref int[] a, int nrec, int nheader, int i0, int i1, int[] b)
static void splitlengtheven (int tasksize, ref int task0, ref int task1)
static void splitlength (int tasksize, int chunksize, ref int task0, ref int task1)
Member Function Documentation
static bool alglib.apserv.approxequalrel (double a, double b, double tol) inline static
Referenced by alglib.testlsfitunit.testpolynomialfitting(), alglib.testlsfitunit.testrationalfitting(), and alglib.testlsfitunit.testsplinefitting().
static void alglib.apserv.taskgenint1d (double a, double b, int n, ref double[] x, ref double[] y) inline static
References alglib.ap.assert(), and alglib.math.randomreal().
Referenced by alglib.testlsfitunit.testpolynomialfitting().
static void alglib.apserv.taskgenint1dequidist (double a, double b, int n, ref double[] x, ref double[] y) inline static
References alglib.ap.assert(), and alglib.math.randomreal().
Referenced by alglib.testpolintunit.testpolint(), and alglib.testpsplineunit.testpspline().
static void alglib.apserv.taskgenint1dcheb1 (double a, double b, int n, ref double[] x, ref double[] y) inline static
References alglib.ap.assert(), and alglib.math.randomreal().
Referenced by alglib.testpolintunit.testpolint().
static void alglib.apserv.taskgenint1dcheb2 (double a, double b, int n, ref double[] x, ref double[] y) inline static
References alglib.ap.assert(), and alglib.math.randomreal().
Referenced by alglib.testpolintunit.testpolint().
static bool alglib.apserv.aredistinct (double[] x, int n) inline static
References alglib.ap.assert().
Referenced by alglib.polint.polynomialbuild(), alglib.spline1d.spline1dbuildakima(), alglib.spline1d.spline1dbuildcatmullrom(), alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1dbuildhermite(), alglib.spline1d.spline1dbuildlinear(), alglib.spline1d.spline1dbuildmonotone(), alglib.spline1d.spline1dconvcubic(), alglib.spline1d.spline1dconvdiff2cubic(), alglib.spline1d.spline1dconvdiffcubic(), alglib.spline1d.spline1dgriddiff2cubic(), and alglib.spline1d.spline1dgriddiffcubic().
static bool alglib.apserv.aresameboolean (bool v1, bool v2) inline static
static void alglib.apserv.bvectorsetlengthatleast (ref bool[] x, int n) inline static
Referenced by alglib.cqmodels.cqminit(), alglib.minbleic.minbleiciteration(), and alglib.snnls.snnlsinit().
static void alglib.apserv.ivectorsetlengthatleast (ref int[] x, int n) inline static
Referenced by alglib.minbleic.minbleicsetlc(), alglib.spline1d.spline1drootsandextrema(), and alglib.tsort.tagsortbuf().
static void alglib.apserv.rvectorsetlengthatleast (ref double[] x, int n) inline static
Referenced by alglib.testspline3dunit.basictest(), alglib.testspline3dunit.buildrndgrid(), alglib.cqmodels.cqmadx(), alglib.cqmodels.cqmconstrainedoptimum(), alglib.cqmodels.cqmgradunconstrained(), alglib.cqmodels.cqminit(), alglib.cqmodels.cqmrebuild(), alglib.cqmodels.cqmsetb(), alglib.cqmodels.cqmsetd(), alglib.cqmodels.cqmsetq(), alglib.lincg.lincgsolvesparse(), alglib.linlsqr.linlsqrsolvesparse(), alglib.minbleic.minbleiciteration(), alglib.minbleic.minbleicsetprecdiag(), alglib.mincg.mincgsetprecdiagfast(), alglib.mincg.mincgsetpreclowrankfast(), alglib.snnls.snnlsinit(), alglib.spline1d.solvecubicpolinom(), alglib.spline1d.spline1drootsandextrema(), alglib.tsort.tagsortbuf(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlptrainensregr(), alglib.testspline2dunit.testspline2dvf(), alglib.testspline3dunit.testtrilinearresample(), and alglib.testspline3dunit.testunpack().
static void alglib.apserv.rmatrixsetlengthatleast (ref double x[,], int m, int n) inline static
Referenced by alglib.clustering.clusterizersetdistances(), alglib.clustering.clusterizersetpoints(), alglib.cqmodels.cqmrebuild(), alglib.cqmodels.cqmrewritedensediagonal(), alglib.cqmodels.cqmseta(), alglib.cqmodels.cqmsetq(), alglib.minbleic.minbleiciteration(), alglib.minbleic.minbleicsetlc(), alglib.mincg.mincgsetpreclowrankfast(), alglib.snnls.snnlsinit(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlptrainensregr(), and alglib.testspline2dunit.testspline2dvf().
static void alglib.apserv.rmatrixresize (ref double x[,], int m, int n) inline static
static bool alglib.apserv.isfinitevector (double[] x, int n) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
Referenced by alglib.basestat.cov2(), alglib.cqmodels.cqmadx(), alglib.cqmodels.cqmdebugconstrainedevale(), alglib.cqmodels.cqmdebugconstrainedevalt(), alglib.cqmodels.cqmeval(), alglib.cqmodels.cqmevalx(), alglib.cqmodels.cqmgradunconstrained(), alglib.cqmodels.cqmsetb(), alglib.cqmodels.cqmsetd(), alglib.cqmodels.cqmsetq(), alglib.cqmodels.cqmxtadx2(), alglib.fft.fftr1d(), alglib.filters.filterema(), alglib.filters.filterlrma(), alglib.filters.filtersma(), alglib.testminlmunit.funcderiv(), alglib.testlsfitunit.funcderiv(), alglib.nearestneighbor.kdtreequeryaknn(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryrnn(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsolvesparse(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsolvesparse(), alglib.minbleic.minbleiccreate(), alglib.minbleic.minbleiccreatef(), alglib.minbleic.minbleicrestartfrom(), alglib.mincg.mincgcreate(), alglib.mincg.mincgcreatef(), alglib.mincg.mincgrestartfrom(), alglib.nleq.nleqcreatelm(), alglib.nleq.nleqrestartfrom(), alglib.odesolver.odesolverrkck(), alglib.basestat.pearsoncorr2(), alglib.polint.polynomialbuild(), alglib.polint.polynomialbuildcheb1(), alglib.polint.polynomialbuildcheb2(), alglib.polint.polynomialbuildeqdist(), alglib.polint.polynomialcalccheb1(), alglib.polint.polynomialcalccheb2(), alglib.polint.polynomialcalceqdist(), alglib.polint.polynomialcheb2bar(), alglib.lsfit.polynomialfit(), alglib.polint.polynomialpow2bar(), alglib.basestat.sampleadev(), alglib.basestat.samplemedian(), alglib.basestat.samplemoments(), alglib.basestat.samplepercentile(), alglib.basestat.spearmancorr2(), alglib.spline1d.spline1dbuildakima(), alglib.spline1d.spline1dbuildcatmullrom(), alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1dbuildhermite(), alglib.spline1d.spline1dbuildlinear(), alglib.spline1d.spline1dbuildmonotone(), alglib.spline1d.spline1dconvcubic(), alglib.spline1d.spline1dconvdiff2cubic(), alglib.spline1d.spline1dconvdiffcubic(), alglib.spline1d.spline1dgriddiff2cubic(), and alglib.spline1d.spline1dgriddiffcubic().
static bool alglib.apserv.isfinitecvector (complex[] z, int n) inline static
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.complex.x.
Referenced by alglib.fft.fftc1d(), and alglib.fft.fftc1dinv().
static bool alglib.apserv.apservisfinitematrix (double x[,], int m, int n) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
Referenced by alglib.clustering.clusterizergetdistances(), alglib.clustering.clusterizersetpoints(), alglib.basestat.covm(), alglib.basestat.covm2(), alglib.cqmodels.cqmsetq(), alglib.nearestneighbor.kdtreebuild(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.minbleic.minbleicsetlc(), alglib.basestat.pearsoncorrm(), alglib.basestat.pearsoncorrm2(), alglib.basestat.rankdata(), alglib.basestat.rankdatacentered(), alglib.basestat.spearmancorrm(), and alglib.basestat.spearmancorrm2().
static bool alglib.apserv.apservisfinitecmatrix (complex x[,], int m, int n) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
static bool alglib.apserv.isfinitertrmatrix (double x[,], int n, bool isupper) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
Referenced by alglib.cqmodels.cqmseta().
static bool alglib.apserv.apservisfinitectrmatrix (complex x[,], int n, bool isupper) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
static bool alglib.apserv.apservisfiniteornanmatrix (double x[,], int m, int n) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
static double alglib.apserv.safepythag2 (double x, double y) inline static
References alglib.math.sqr().
Referenced by alglib.linlsqr.linlsqriteration(), and alglib.testpsplineunit.testpspline().
static double alglib.apserv.safepythag3 (double x, double y, double z) inline static
References alglib.math.sqr().
Referenced by alglib.testpsplineunit.testpspline().
static int alglib.apserv.saferdiv (double x, double y, ref double r) inline static
References alglib.math.maxrealnumber, and alglib.math.minrealnumber.
static double alglib.apserv.safeminposrv (double x, double y, double v) inline static
Referenced by alglib.optserv.calculatestepbound(), and alglib.minbleic.minbleiciteration().
static void alglib.apserv.apperiodicmap (ref double x, double a, double b, ref double k) inline static
References alglib.ap.assert().
Referenced by alglib.spline1d.spline1dcalc(), alglib.spline1d.spline1dconvcubic(), alglib.spline1d.spline1dconvdiff2cubic(), alglib.spline1d.spline1dconvdiffcubic(), alglib.spline1d.spline1ddiff(), and alglib.spline1d.spline1dintegrate().
static double alglib.apserv.boundval (double x, double b1, double b2) inline static
Referenced by alglib.testminqpunit.icqptest(), alglib.testminqpunit.simpletest(), alglib.testminbleicunit.testfeasibility(), and alglib.testminlmunit.testminlm().
static void alglib.apserv.alloccomplex (alglib.serializer s, complex v) inline static
static void alglib.apserv.serializecomplex (alglib.serializer s, complex v) inline static
References alglib.complex.x, and alglib.complex.y.
static complex alglib.apserv.unserializecomplex (alglib.serializer s) inline static
References alglib.complex.x, and alglib.complex.y.
static void alglib.apserv.allocrealarray (alglib.serializer s, double[] v, int n) inline static
Referenced by alglib.dforest.dfalloc(), and alglib.nearestneighbor.kdtreealloc().
static void alglib.apserv.serializerealarray (alglib.serializer s, double[] v, int n) inline static
Referenced by alglib.dforest.dfserialize(), and alglib.nearestneighbor.kdtreeserialize().
static void alglib.apserv.unserializerealarray (alglib.serializer s, ref double[] v) inline static
Referenced by alglib.dforest.dfunserialize(), and alglib.nearestneighbor.kdtreeunserialize().
static void alglib.apserv.allocintegerarray (alglib.serializer s, int[] v, int n) inline static
Referenced by alglib.nearestneighbor.kdtreealloc(), and alglib.mlpbase.mlpalloc().
static void alglib.apserv.serializeintegerarray (alglib.serializer s, int[] v, int n) inline static
Referenced by alglib.nearestneighbor.kdtreeserialize(), and alglib.mlpbase.mlpserialize().
static void alglib.apserv.unserializeintegerarray (alglib.serializer s, ref int[] v) inline static
Referenced by alglib.nearestneighbor.kdtreeunserialize(), and alglib.mlpbase.mlpunserialize().
static void alglib.apserv.allocrealmatrix (alglib.serializer s, double v[,], int n0, int n1) inline static
Referenced by alglib.nearestneighbor.kdtreealloc().
static void alglib.apserv.serializerealmatrix (alglib.serializer s, double v[,], int n0, int n1) inline static
Referenced by alglib.nearestneighbor.kdtreeserialize().
static void alglib.apserv.unserializerealmatrix (alglib.serializer s, ref double v[,]) inline static
Referenced by alglib.nearestneighbor.kdtreeunserialize().
static void alglib.apserv.copyintegerarray (int[] src, ref int[] dst) inline static
Referenced by alglib.mlpbase.mlpcopy().
static void alglib.apserv.copyrealarray (double[] src, ref double[] dst) inline static
Referenced by alglib.mlpbase.mlpcopy().
static void alglib.apserv.copyrealmatrix (double src[,], ref double dst[,]) inline static
Referenced by alglib.mlpbase.mlpcopy().
static int alglib.apserv.recsearch (ref int[] a, int nrec, int nheader, int i0, int i1, int[] b) inline static
Referenced by alglib.mlpbase.mlpgetneuroninfo(), alglib.mlpbase.mlpgetweight(), alglib.mlpbase.mlpsetneuroninfo(), and alglib.mlpbase.mlpsetweight().
static bool alglib.apserv.seterrorflag (ref bool flag, bool cond) inline static
Referenced by alglib.testminqpunit.bleictests(), alglib.testminqpunit.choleskytests(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.icqptest(), alglib.apserv.seterrorflagdiff(), alglib.testmlpbaseunit.spectests(), alglib.testmlpbaseunit.testerr(), alglib.testlsfitunit.testgeneralfitting(), alglib.testmlpbaseunit.testgradient(), alglib.testhqrndunit.testhqrnd(), alglib.testmlptrainunit.testmlptrainensregr(), alglib.testminbleicunit.testother(), and alglib.testmlpbaseunit.testprocessing().
static bool alglib.apserv.seterrorflagdiff (ref bool flag, double val, double refval, double tol, double s) inline static
References alglib.apserv.seterrorflag().
Referenced by alglib.testmlpbaseunit.testerr(), alglib.testmlpeunit.testerr(), alglib.testmlpbaseunit.testgradient(), and alglib.testmlptrainunit.testmlptrainensregr().
static void alglib.apserv.touchint (ref int a) inline static
Referenced by alglib.reflections.applyreflectionfromtheright(), alglib.bdss.dsoptimalsplitk(), alglib.ftbase.ftapplysubplan(), alglib.hsschur.internalschurdecomposition(), and alglib.sblas.symmetricmatrixvectormultiply().
static void alglib.apserv.touchreal (ref double a) inline static
static double alglib.apserv.inttoreal (int a) inline static
Referenced by alglib.basestat.rankdata(), alglib.basestat.rankdatacentered(), and alglib.basestat.rankdatarec().
static double alglib.apserv.logbase2 (double x) inline static
Referenced by alglib.basestat.rankdata(), alglib.basestat.rankdatacentered(), and alglib.basestat.rankdatarec().
static bool alglib.apserv.approxequalrel (double a, double b, double tol) inline static
static void alglib.apserv.taskgenint1d (double a, double b, int n, ref double[] x, ref double[] y) inline static
References alglib.ap.assert(), and alglib.math.randomreal().
static void alglib.apserv.taskgenint1dequidist (double a, double b, int n, ref double[] x, ref double[] y) inline static
References alglib.ap.assert(), and alglib.math.randomreal().
static void alglib.apserv.taskgenint1dcheb1 (double a, double b, int n, ref double[] x, ref double[] y) inline static
References alglib.ap.assert(), and alglib.math.randomreal().
static void alglib.apserv.taskgenint1dcheb2 (double a, double b, int n, ref double[] x, ref double[] y) inline static
References alglib.ap.assert(), and alglib.math.randomreal().
static bool alglib.apserv.aredistinct (double[] x, int n) inline static
References alglib.ap.assert().
static bool alglib.apserv.aresameboolean (bool v1, bool v2) inline static
static void alglib.apserv.bvectorsetlengthatleast (ref bool[] x, int n) inline static
static void alglib.apserv.ivectorsetlengthatleast (ref int[] x, int n) inline static
static void alglib.apserv.rvectorsetlengthatleast (ref double[] x, int n) inline static
static void alglib.apserv.rmatrixsetlengthatleast (ref double x[,], int m, int n) inline static
static void alglib.apserv.rmatrixresize (ref double x[,], int m, int n) inline static
static void alglib.apserv.imatrixresize (ref int x[,], int m, int n) inline static
Referenced by alglib.ftbase.ftpushentry2(), and alglib.ftbase.ftpushentry4().
static bool alglib.apserv.isfinitevector (double[] x, int n) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
static bool alglib.apserv.isfinitecvector (complex[] z, int n) inline static
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.complex.x.
static bool alglib.apserv.apservisfinitematrix (double x[,], int m, int n) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
static bool alglib.apserv.apservisfinitecmatrix (complex x[,], int m, int n) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
static bool alglib.apserv.isfinitertrmatrix (double x[,], int n, bool isupper) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
static bool alglib.apserv.apservisfinitectrmatrix (complex x[,], int n, bool isupper) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
static bool alglib.apserv.apservisfiniteornanmatrix (double x[,], int m, int n) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
static double alglib.apserv.safepythag2 (double x, double y) inline static
References alglib.math.sqr().
static double alglib.apserv.safepythag3 (double x, double y, double z) inline static
References alglib.math.sqr().
static int alglib.apserv.saferdiv (double x, double y, ref double r) inline static
References alglib.math.maxrealnumber, and alglib.math.minrealnumber.
static double alglib.apserv.safeminposrv (double x, double y, double v) inline static
static void alglib.apserv.apperiodicmap (ref double x, double a, double b, ref double k) inline static
References alglib.ap.assert().
static double alglib.apserv.randomnormal () inline static
References alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testminqpunit.bleictests(), alglib.testmincgunit.gradientchecktest(), alglib.testminlbfgsunit.gradientchecktest(), alglib.testminlmunit.gradientchecktest(), alglib.testlinlsqrunit.preconditionertest(), alglib.testlincgunit.precondtest(), alglib.apserv.randomunit(), alglib.testminbleicunit.testconv(), alglib.testlsfitunit.testgeneralfitting(), and alglib.testminbleicunit.testgradientcheck().
static void alglib.apserv.randomunit (int n, ref double[] x) inline static
References alglib.ap.assert(), and alglib.apserv.randomnormal().
Referenced by alglib.testminqpunit.ecqptest().
static void alglib.apserv.inc (ref int v) inline static
static void alglib.apserv.dec (ref int v) inline static
static void alglib.apserv.countdown (ref int v) inline static
static double alglib.apserv.boundval (double x, double b1, double b2) inline static
static void alglib.apserv.alloccomplex (alglib.serializer s, complex v) inline static
static void alglib.apserv.serializecomplex (alglib.serializer s, complex v) inline static
References alglib.complex.x, and alglib.complex.y.
static complex alglib.apserv.unserializecomplex (alglib.serializer s) inline static
References alglib.complex.x, and alglib.complex.y.
static void alglib.apserv.allocrealarray (alglib.serializer s, double[] v, int n) inline static
static void alglib.apserv.serializerealarray (alglib.serializer s, double[] v, int n) inline static
static void alglib.apserv.unserializerealarray (alglib.serializer s, ref double[] v) inline static
static void alglib.apserv.allocintegerarray (alglib.serializer s, int[] v, int n) inline static
static void alglib.apserv.serializeintegerarray (alglib.serializer s, int[] v, int n) inline static
static void alglib.apserv.unserializeintegerarray (alglib.serializer s, ref int[] v) inline static
static void alglib.apserv.allocrealmatrix (alglib.serializer s, double v[,], int n0, int n1) inline static
static void alglib.apserv.serializerealmatrix (alglib.serializer s, double v[,], int n0, int n1) inline static
static void alglib.apserv.unserializerealmatrix (alglib.serializer s, ref double v[,]) inline static
static void alglib.apserv.copyintegerarray (int[] src, ref int[] dst) inline static
static void alglib.apserv.copyrealarray (double[] src, ref double[] dst) inline static
static void alglib.apserv.copyrealmatrix (double src[,], ref double dst[,]) inline static
static int alglib.apserv.recsearch (ref int[] a, int nrec, int nheader, int i0, int i1, int[] b) inline static
static void alglib.apserv.splitlengtheven (int tasksize, ref int task0, ref int task1) inline static
References alglib.ap.assert().
static void alglib.apserv.splitlength (int tasksize, int chunksize, ref int task0, ref int task1) inline static
References alglib.ap.assert().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/alglibinternal.cs