IGLib: NUnit.Framework.Internal.Filters.IdFilterTests Class Reference
NUnit.Framework.Internal.Filters.IdFilterTests Class Reference
Public Member Functions
void CreateFilter ()
void IsNotEmpty ()
void MatchTest ()
void PassTest ()
void ExplicitMatchTest ()
Public Member Functions inherited from NUnit.Framework.Internal.Filters.TestFilterTests
void SetUpSuite ()
Private Attributes
TestFilter _filter
Additional Inherited Members
Public Attributes inherited from NUnit.Framework.Internal.Filters.TestFilterTests
const string DUMMY_CLASS = "NUnit.Framework.Internal.Filters.TestFilterTests+DummyFixture"
Protected Attributes inherited from NUnit.Framework.Internal.Filters.TestFilterTests
readonly TestSuite _dummyFixture = TestBuilder.MakeFixture(typeof(DummyFixture))
readonly TestSuite _anotherFixture = TestBuilder.MakeFixture(typeof(AnotherFixture))
readonly TestSuite _yetAnotherFixture = TestBuilder.MakeFixture(typeof(YetAnotherFixture))
readonly TestSuite _fixtureWithMultipleTests = TestBuilder.MakeFixture (typeof (FixtureWithMultipleTests))
readonly TestSuite _topLevelSuite = new TestSuite("MySuite")
Member Function Documentation
void NUnit.Framework.Internal.Filters.IdFilterTests.CreateFilter () inline
void NUnit.Framework.Internal.Filters.IdFilterTests.IsNotEmpty () inline
References NUnit.Framework.Assert.False(), and NUnit.Framework.Internal.TestFilter.IsEmpty.
void NUnit.Framework.Internal.Filters.IdFilterTests.MatchTest () inline
References NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.Match(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.Filters.IdFilterTests.PassTest () inline
References NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.Pass(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.Filters.IdFilterTests.ExplicitMatchTest () inline
References NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.IsExplicitMatch(), and NUnit.Framework.Assert.That().
Member Data Documentation
TestFilter NUnit.Framework.Internal.Filters.IdFilterTests._filter private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/Filters/IdFilterTests.cs