IGLib: NUnit.Framework.RequiresThreadAttribute Class Reference
NUnit.Framework.RequiresThreadAttribute Class Reference
Marks a test that must run on a separate thread.
Public Member Functions
RequiresThreadAttribute ()
Construct a RequiresThreadAttribute
RequiresThreadAttribute (ApartmentState apartment)
Construct a RequiresThreadAttribute, specifying the apartment
Public Member Functions inherited from NUnit.Framework.PropertyAttribute
PropertyAttribute (string propertyName, string propertyValue)
Construct a PropertyAttribute with a name and string value
PropertyAttribute (string propertyName, int propertyValue)
Construct a PropertyAttribute with a name and int value
PropertyAttribute (string propertyName, double propertyValue)
Construct a PropertyAttribute with a name and double value
Public Member Functions inherited from NUnit.Framework.NUnitAttribute
NUnitAttribute ()
Default constructor
Private Member Functions
void IApplyToTest. ApplyToTest (Test test)
Modifies a test by adding properties to it.
Additional Inherited Members
Protected Member Functions inherited from NUnit.Framework.PropertyAttribute
PropertyAttribute ()
Constructor for derived classes that set the property dictionary directly.
PropertyAttribute (object propertyValue)
Constructor for use by derived classes that use the name of the type as the property name. Derived classes must ensure that the Type of the property value is a standard type supported by the BCL. Any custom types will cause a serialization Exception when in the client.
Properties inherited from NUnit.Framework.PropertyAttribute
IPropertyBag Properties [get]
Gets the property dictionary for this attribute
Detailed Description
Marks a test that must run on a separate thread.
Constructor & Destructor Documentation
NUnit.Framework.RequiresThreadAttribute.RequiresThreadAttribute () inline
Construct a RequiresThreadAttribute
NUnit.Framework.RequiresThreadAttribute.RequiresThreadAttribute (ApartmentState apartment) inline
Construct a RequiresThreadAttribute, specifying the apartment
References NUnit.Framework.Internal.PropertyNames.ApartmentState.
Member Function Documentation
void IApplyToTest. NUnit.Framework.RequiresThreadAttribute.ApplyToTest (Test test) inline private virtual
Modifies a test by adding properties to it.
Parameters
test The test to modify
Reimplemented from NUnit.Framework.PropertyAttribute.
Referenced by NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeMaySetApartmentState(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeSetsRequiresThread(), and NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeSetsRequiresThreadOnNonRunnableTest().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Attributes/RequiresThreadAttribute.cs