IGLib: IPLab.BlobsFilteringForm Class Reference
IPLab.BlobsFilteringForm Class Reference
Public Member Functions
BlobsFilteringForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
Bitmap Image [set]
IFilter Filter [get]
Private Member Functions
void minWidthBox_TextChanged (object sender, EventArgs e)
void minHeightBox_TextChanged (object sender, EventArgs e)
void minWidthTrackBar_ValueChanged (object sender, EventArgs e)
void minHeightTrackBar_ValueChanged (object sender, EventArgs e)
void modeCombo_SelectedIndexChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
BlobsFiltering filter = new BlobsFiltering()
bool updating = false
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBox1
FilterPreview filterPreview
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Label label1
System.Windows.Forms.ComboBox modeCombo
System.Windows.Forms.TextBox minWidthBox
System.Windows.Forms.TrackBar minWidthTrackBar
System.Windows.Forms.TrackBar minHeightTrackBar
System.Windows.Forms.TextBox minHeightBox
System.Windows.Forms.Label label2
System.Windows.Forms.Button cancelButton
System.Windows.Forms.Button okButton
Constructor & Destructor Documentation
IPLab.BlobsFilteringForm.BlobsFilteringForm () inline
References IPLab.BlobsFilteringForm.filter, IPLab.FilterPreview.Filter, IPLab.BlobsFilteringForm.filterPreview, IPLab.BlobsFilteringForm.InitializeComponent(), IPLab.BlobsFilteringForm.minHeightBox, IPLab.BlobsFilteringForm.minWidthBox, and IPLab.BlobsFilteringForm.modeCombo.
Member Function Documentation
void IPLab.BlobsFilteringForm.minWidthBox_TextChanged (object sender, EventArgs e) inline private
References IPLab.BlobsFilteringForm.filterPreview, IPLab.BlobsFilteringForm.minWidthBox, IPLab.BlobsFilteringForm.minWidthTrackBar, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.BlobsFilteringForm.InitializeComponent().
void IPLab.BlobsFilteringForm.minHeightBox_TextChanged (object sender, EventArgs e) inline private
References IPLab.BlobsFilteringForm.filterPreview, IPLab.BlobsFilteringForm.minHeightBox, IPLab.BlobsFilteringForm.minHeightTrackBar, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.BlobsFilteringForm.InitializeComponent().
void IPLab.BlobsFilteringForm.minWidthTrackBar_ValueChanged (object sender, EventArgs e) inline private
References IPLab.BlobsFilteringForm.minWidthBox, and IPLab.BlobsFilteringForm.minWidthTrackBar.
Referenced by IPLab.BlobsFilteringForm.InitializeComponent().
void IPLab.BlobsFilteringForm.minHeightTrackBar_ValueChanged (object sender, EventArgs e) inline private
References IPLab.BlobsFilteringForm.minHeightBox, and IPLab.BlobsFilteringForm.minHeightTrackBar.
Referenced by IPLab.BlobsFilteringForm.InitializeComponent().
void IPLab.BlobsFilteringForm.modeCombo_SelectedIndexChanged (object sender, EventArgs e) inline private
References IPLab.BlobsFilteringForm.filterPreview, IPLab.BlobsFilteringForm.modeCombo, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.BlobsFilteringForm.InitializeComponent().
override void IPLab.BlobsFilteringForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IPLab.BlobsFilteringForm.components.
void IPLab.BlobsFilteringForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IPLab.BlobsFilteringForm.cancelButton, IPLab.BlobsFilteringForm.filterPreview, IPLab.BlobsFilteringForm.groupBox1, IPLab.BlobsFilteringForm.groupBox2, IPLab.FilterPreview.Image, IPLab.BlobsFilteringForm.label1, IPLab.BlobsFilteringForm.label2, IPLab.BlobsFilteringForm.minHeightBox, IPLab.BlobsFilteringForm.minHeightBox_TextChanged(), IPLab.BlobsFilteringForm.minHeightTrackBar, IPLab.BlobsFilteringForm.minHeightTrackBar_ValueChanged(), IPLab.BlobsFilteringForm.minWidthBox, IPLab.BlobsFilteringForm.minWidthBox_TextChanged(), IPLab.BlobsFilteringForm.minWidthTrackBar, IPLab.BlobsFilteringForm.minWidthTrackBar_ValueChanged(), IPLab.BlobsFilteringForm.modeCombo, IPLab.BlobsFilteringForm.modeCombo_SelectedIndexChanged(), and IPLab.BlobsFilteringForm.okButton.
Referenced by IPLab.BlobsFilteringForm.BlobsFilteringForm().
Member Data Documentation
BlobsFiltering IPLab.BlobsFilteringForm.filter = new BlobsFiltering() private
Referenced by IPLab.BlobsFilteringForm.BlobsFilteringForm().
bool IPLab.BlobsFilteringForm.updating = false private
System.ComponentModel.IContainer IPLab.BlobsFilteringForm.components = null private
Required designer variable.
Referenced by IPLab.BlobsFilteringForm.Dispose().
System.Windows.Forms.GroupBox IPLab.BlobsFilteringForm.groupBox1 private
Referenced by IPLab.BlobsFilteringForm.InitializeComponent().
FilterPreview IPLab.BlobsFilteringForm.filterPreview private
Referenced by IPLab.BlobsFilteringForm.BlobsFilteringForm(), IPLab.BlobsFilteringForm.InitializeComponent(), IPLab.BlobsFilteringForm.minHeightBox_TextChanged(), IPLab.BlobsFilteringForm.minWidthBox_TextChanged(), and IPLab.BlobsFilteringForm.modeCombo_SelectedIndexChanged().
System.Windows.Forms.GroupBox IPLab.BlobsFilteringForm.groupBox2 private
Referenced by IPLab.BlobsFilteringForm.InitializeComponent().
System.Windows.Forms.Label IPLab.BlobsFilteringForm.label1 private
Referenced by IPLab.BlobsFilteringForm.InitializeComponent().
System.Windows.Forms.ComboBox IPLab.BlobsFilteringForm.modeCombo private
Referenced by IPLab.BlobsFilteringForm.BlobsFilteringForm(), IPLab.BlobsFilteringForm.InitializeComponent(), and IPLab.BlobsFilteringForm.modeCombo_SelectedIndexChanged().
System.Windows.Forms.TextBox IPLab.BlobsFilteringForm.minWidthBox private
Referenced by IPLab.BlobsFilteringForm.BlobsFilteringForm(), IPLab.BlobsFilteringForm.InitializeComponent(), IPLab.BlobsFilteringForm.minWidthBox_TextChanged(), and IPLab.BlobsFilteringForm.minWidthTrackBar_ValueChanged().
System.Windows.Forms.TrackBar IPLab.BlobsFilteringForm.minWidthTrackBar private
Referenced by IPLab.BlobsFilteringForm.InitializeComponent(), IPLab.BlobsFilteringForm.minWidthBox_TextChanged(), and IPLab.BlobsFilteringForm.minWidthTrackBar_ValueChanged().
System.Windows.Forms.TrackBar IPLab.BlobsFilteringForm.minHeightTrackBar private
Referenced by IPLab.BlobsFilteringForm.InitializeComponent(), IPLab.BlobsFilteringForm.minHeightBox_TextChanged(), and IPLab.BlobsFilteringForm.minHeightTrackBar_ValueChanged().
System.Windows.Forms.TextBox IPLab.BlobsFilteringForm.minHeightBox private
Referenced by IPLab.BlobsFilteringForm.BlobsFilteringForm(), IPLab.BlobsFilteringForm.InitializeComponent(), IPLab.BlobsFilteringForm.minHeightBox_TextChanged(), and IPLab.BlobsFilteringForm.minHeightTrackBar_ValueChanged().
System.Windows.Forms.Label IPLab.BlobsFilteringForm.label2 private
Referenced by IPLab.BlobsFilteringForm.InitializeComponent().
System.Windows.Forms.Button IPLab.BlobsFilteringForm.cancelButton private
Referenced by IPLab.BlobsFilteringForm.InitializeComponent().
System.Windows.Forms.Button IPLab.BlobsFilteringForm.okButton private
Referenced by IPLab.BlobsFilteringForm.InitializeComponent().
Property Documentation
Bitmap IPLab.BlobsFilteringForm.Image set
Referenced by IPLab.ImageDoc.filterBlobsMenuItem_Click().
IFilter IPLab.BlobsFilteringForm.Filter get
Referenced by IPLab.ImageDoc.filterBlobsMenuItem_Click().
The documentation for this class was generated from the following files:
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/BlobsFilteringForm.cs
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/BlobsFilteringForm.Designer.cs