IGLib: Test.SampleTest Class Reference
Test.SampleTest Class Reference
Public Member Functions
void SampleManipulations ()
void SampleCopy ()
void LowSampleMoments ()
void SampleMoments ()
void SamplePopulationMomentEstimateVariances ()
void SampleMedian ()
void SampleInterquartileRange ()
void NormalFit ()
void NormalFitUncertainties ()
void ExponentialFit ()
void ExponentialFitUncertainty ()
void LognormalFit ()
void BetaFit ()
void BetaFitUncertainty ()
void GammaFit ()
void GammaFitUncertainty ()
void WaldFitUncertainties ()
void SampleFitChiSquaredTest ()
void WeibullFit ()
void WeibullFitUncertainties ()
void TTestDistribution ()
void SignTestDistribution ()
void SampleComparisonTest ()
void TestMoments (Distribution d)
void SampleKolmogorovSmirnovTest ()
void SampleKuiperTest ()
void SampleMaximumLikelihoodFit ()
void SampleFisherFTest ()
void SampleMannWhitneyTest ()
void AnovaTest ()
void AnovaDistribution ()
void AnovaStudentAgreement ()
void ZTestDistribution ()
void KruskalWallis ()
void SampleTransform ()
Static Private Member Functions
static Sample CreateSample (Distribution distribution, int count)
static Sample CreateSample (Distribution distribution, int count, int seed)
Private Attributes
Distribution[] distributions
Member Function Documentation
void Test.SampleTest.SampleManipulations () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Sample.Clear(), Meta.Numerics.Statistics.Sample.Contains(), Meta.Numerics.Statistics.Sample.Count, and Meta.Numerics.Statistics.Sample.Remove().
void Test.SampleTest.SampleCopy () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Sample.Copy(), and Meta.Numerics.Statistics.Sample.Count.
void Test.SampleTest.LowSampleMoments () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Sample.Count, Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.Sample.Remove(), and Meta.Numerics.Statistics.Sample.Variance.
static Sample Test.SampleTest.CreateSample (Distribution distribution, int count) inline static private
Referenced by Test.SampleTest.BetaFit(), Test.SampleTest.BetaFitUncertainty(), Test.SampleTest.ExponentialFit(), Test.SampleTest.ExponentialFitUncertainty(), Test.SampleTest.GammaFit(), Test.SampleTest.GammaFitUncertainty(), Test.SampleTest.KruskalWallis(), Test.SampleTest.LognormalFit(), Test.SampleTest.NormalFit(), Test.SampleTest.SampleComparisonTest(), Test.SampleTest.SampleFisherFTest(), Test.SampleTest.SampleFitChiSquaredTest(), Test.SampleTest.SampleInterquartileRange(), Test.SampleTest.SampleKolmogorovSmirnovTest(), Test.SampleTest.SampleKuiperTest(), Test.SampleTest.SampleMannWhitneyTest(), Test.SampleTest.SampleMaximumLikelihoodFit(), Test.SampleTest.SampleMoments(), Test.SampleTest.WeibullFit(), and Test.SampleTest.WeibullFitUncertainties().
static Sample Test.SampleTest.CreateSample (Distribution distribution, int count, int seed) inline static private
References Meta.Numerics.Statistics.Sample.Add(), and Meta.Numerics.Statistics.Distributions.Distribution.GetRandomValue().
void Test.SampleTest.SampleMoments () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.Sample.Count, Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Distributions.Distribution.Moment(), Meta.Numerics.Statistics.Distributions.Distribution.MomentAboutMean(), Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationMoment(), Meta.Numerics.Statistics.Sample.PopulationMomentAboutMean(), Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation.
void Test.SampleTest.SamplePopulationMomentEstimateVariances () inline
References Meta.Numerics.Statistics.MultivariateSample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.Statistics.MultivariateSample.Column(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.MultivariateSample.Dimension, Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.Sample.Name, Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationMomentAboutMean(), Meta.Numerics.Statistics.Sample.PopulationVariance, Meta.Numerics.MoreMath.Sqr(), Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
void Test.SampleTest.SampleMedian () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Sample.Maximum, Meta.Numerics.Statistics.Sample.Median, and Meta.Numerics.Statistics.Sample.Minimum.
void Test.SampleTest.SampleInterquartileRange () inline
References Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Sample.InterquartileRange, Meta.Numerics.Statistics.Sample.InverseLeftProbability(), Meta.Numerics.Interval.LeftEndpoint, and Meta.Numerics.Interval.RightEndpoint.
void Test.SampleTest.NormalFit () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Distributions.ExponentialDistribution.FitToSample(), Meta.Numerics.Statistics.Distributions.NormalDistribution.FitToSample(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.FitResult.Parameter(), and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation.
void Test.SampleTest.NormalFitUncertainties () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.Statistics.FitResult.Covariance(), Meta.Numerics.Statistics.Distributions.NormalDistribution.FitToSample(), Meta.Numerics.Statistics.Distributions.NormalDistribution.Mean, Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.BivariateSample.PopulationCovariance, Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationVariance, Meta.Numerics.Statistics.Distributions.NormalDistribution.StandardDeviation, Meta.Numerics.UncertainValue.Value, Meta.Numerics.Statistics.BivariateSample.X, and Meta.Numerics.Statistics.BivariateSample.Y.
void Test.SampleTest.ExponentialFit () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Distributions.ExponentialDistribution.FitToSample(), Meta.Numerics.Statistics.Distributions.NormalDistribution.FitToSample(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Distributions.ExponentialDistribution.Mean, and Meta.Numerics.Statistics.FitResult.Parameter().
void Test.SampleTest.ExponentialFitUncertainty () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Distributions.ExponentialDistribution.FitToSample(), Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
void Test.SampleTest.LognormalFit () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Distributions.NormalDistribution.FitToSample(), Meta.Numerics.Statistics.Distributions.LognormalDistribution.FitToSample(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Distributions.LognormalDistribution.Mu, Meta.Numerics.Statistics.FitResult.Parameter(), and Meta.Numerics.Statistics.Distributions.LognormalDistribution.Sigma.
void Test.SampleTest.BetaFit () inline
References Meta.Numerics.Statistics.Distributions.BetaDistribution.Alpha, Meta.Numerics.Statistics.Distributions.BetaDistribution.Beta, Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Distributions.NormalDistribution.FitToSample(), Meta.Numerics.Statistics.Distributions.BetaDistribution.FitToSample(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.TestResult.LeftProbability, and Meta.Numerics.Statistics.FitResult.Parameter().
void Test.SampleTest.BetaFitUncertainty () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Distributions.BetaDistribution.FitToSample(), Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, Meta.Numerics.UncertainValue.Uncertainty, Meta.Numerics.UncertainValue.Value, Meta.Numerics.Statistics.BivariateSample.X, and Meta.Numerics.Statistics.BivariateSample.Y.
void Test.SampleTest.GammaFit () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Distributions.GammaDistribution.FitToSample(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.Distributions.GammaDistribution.ScaleParameter, and Meta.Numerics.Statistics.Distributions.GammaDistribution.ShapeParameter.
void Test.SampleTest.GammaFitUncertainty () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Distributions.GammaDistribution.FitToSample(), Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, Meta.Numerics.UncertainValue.Uncertainty, Meta.Numerics.UncertainValue.Value, Meta.Numerics.Statistics.BivariateSample.X, and Meta.Numerics.Statistics.BivariateSample.Y.
void Test.SampleTest.WaldFitUncertainties () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.Statistics.FitResult.Covariance(), Meta.Numerics.Statistics.Distributions.WaldDistribution.FitToSample(), Meta.Numerics.Statistics.Distributions.Distribution.GetRandomValue(), Meta.Numerics.Statistics.Distributions.WaldDistribution.Mean, Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.BivariateSample.PopulationCovariance, Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationVariance, Meta.Numerics.Statistics.Distributions.WaldDistribution.ShapeParameter, Meta.Numerics.UncertainValue.Value, Meta.Numerics.Statistics.BivariateSample.X, and Meta.Numerics.Statistics.BivariateSample.Y.
void Test.SampleTest.SampleFitChiSquaredTest () inline
References Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Distributions.ExponentialDistribution.FitToSample(), Meta.Numerics.Statistics.Distributions.NormalDistribution.FitToSample(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, and Meta.Numerics.Statistics.TestResult.LeftProbability.
void Test.SampleTest.WeibullFit () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.FitToSample(), Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.ScaleParameter, and Meta.Numerics.Statistics.Distributions.WeibullDistribution.ShapeParameter.
void Test.SampleTest.WeibullFitUncertainties () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.MultivariateSample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.Statistics.MultivariateSample.Column(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.FitResult.Covariance(), Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.FitToSample(), Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, Meta.Numerics.UncertainValue.Uncertainty, Meta.Numerics.UncertainValue.Value, Meta.Numerics.Statistics.BivariateSample.X, and Meta.Numerics.Statistics.BivariateSample.Y.
void Test.SampleTest.TTestDistribution () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.Sample.Count, Meta.Numerics.Statistics.Distributions.Distribution.GetRandomValue(), Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation, Meta.Numerics.Statistics.TestResult.Statistic, and Meta.Numerics.Statistics.Sample.StudentTTest().
void Test.SampleTest.SignTestDistribution () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.Sample.Count, Meta.Numerics.Statistics.Distributions.Distribution.GetRandomValue(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Mean, Meta.Numerics.Statistics.Distributions.Distribution.Median, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationMomentAboutMean(), Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, Meta.Numerics.Statistics.Sample.SignTest(), Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation, and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.SampleTest.SampleComparisonTest () inline
References Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Distributions.Distribution.InverseLeftProbability(), Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.TestResult.RightProbability, and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.SampleTest.TestMoments (Distribution d) inline
References Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Distributions.Distribution.Moment(), Meta.Numerics.Statistics.Distributions.Distribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.Distribution.ProbabilityDensity(), Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation, and Meta.Numerics.Statistics.Distributions.Distribution.Support.
void Test.SampleTest.SampleKolmogorovSmirnovTest () inline
References Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.TestResult.Distribution, Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation, and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.SampleTest.SampleKuiperTest () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.TestResult.Distribution, Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.Sample.KuiperTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation, and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.SampleTest.SampleMaximumLikelihoodFit () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.Sample.Count, Meta.Numerics.Statistics.FitResult.Covariance(), Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.FitResult.Dimension, Meta.Numerics.Statistics.Sample.MaximumLikelihoodFit(), Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
void Test.SampleTest.SampleFisherFTest () inline
References Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Sample.FisherFTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.TestResult.RightProbability, and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.SampleTest.SampleMannWhitneyTest () inline
References Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Sample.MannWhitneyTest(), Meta.Numerics.Statistics.TestResult.RightProbability, and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.SampleTest.AnovaTest () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Sample.Count, Meta.Numerics.Statistics.AnovaRow.DegreesOfFreedom, Meta.Numerics.Statistics.OneWayAnovaResult.Factor, Meta.Numerics.Statistics.Sample.OneWayAnovaTest(), Meta.Numerics.Statistics.OneWayAnovaResult.Residual, Meta.Numerics.Statistics.OneWayAnovaResult.Result, Meta.Numerics.Statistics.AnovaTestRow.Result, Meta.Numerics.Statistics.TestResult.Statistic, Meta.Numerics.Statistics.AnovaRow.SumOfSquares, and Meta.Numerics.Statistics.OneWayAnovaResult.Total.
void Test.SampleTest.AnovaDistribution () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.OneWayAnovaResult.Factor, Meta.Numerics.Statistics.Distributions.Distribution.GetRandomValue(), Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Sample.OneWayAnovaTest(), Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, Meta.Numerics.Statistics.AnovaTestRow.Result, and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.SampleTest.AnovaStudentAgreement () inline
References Meta.Numerics.Statistics.Distributions.StudentDistribution.DegreesOfFreedom, Meta.Numerics.Statistics.TestResult.Distribution, Meta.Numerics.Statistics.OneWayAnovaResult.Factor, Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.Sample.OneWayAnovaTest(), Meta.Numerics.MoreMath.Pow(), Meta.Numerics.Statistics.AnovaTestRow.Result, Meta.Numerics.Statistics.TestResult.Statistic, Meta.Numerics.Statistics.Sample.StudentTTest(), and Meta.Numerics.Statistics.Sample.Variance.
void Test.SampleTest.ZTestDistribution () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Distributions.Distribution.GetRandomValue(), Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation, Meta.Numerics.Statistics.TestResult.Statistic, and Meta.Numerics.Statistics.Sample.ZTest().
void Test.SampleTest.KruskalWallis () inline
References Test.SampleTest.CreateSample(), Meta.Numerics.Statistics.Sample.KruskalWallisTest(), and Meta.Numerics.Statistics.TestResult.RightProbability.
void Test.SampleTest.SampleTransform () inline
References Meta.Numerics.Statistics.Sample.Maximum, Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.Sample.Minimum, Meta.Numerics.Statistics.Sample.Transform(), and Meta.Numerics.Statistics.Sample.Variance.
Member Data Documentation
Distribution [] Test.SampleTest.distributions private
Initial value:
= new Distribution[] {
            new UniformDistribution(Interval.FromEndpoints(-2.0,1.0)),
            new NormalDistribution(3.0,2.0),
            new ExponentialDistribution(2.0),
        }
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/SampleTest.cs