IGLib: alglib.testpolintunit Class Reference
alglib.testpolintunit Class Reference
Static Public Member Functions
static bool testpolint (bool silent)
static bool testpolint (bool silent)
static bool _pexec_testpolint (bool silent)
Static Private Member Functions
static double internalpolint (double[] x, double[] f, int n, double t)
static void brcunset (ratint.barycentricinterpolant b)
static double internalpolint (double[] x, double[] f, int n, double t)
static void brcunset (ratint.barycentricinterpolant b)
Member Function Documentation
static bool alglib.testpolintunit.testpolint (bool silent) inline static
References alglib.ratint.barycentriccalc(), alglib.testpolintunit.brcunset(), alglib.testpolintunit.internalpolint(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.polint.polynomialbar2cheb(), alglib.polint.polynomialbar2pow(), alglib.polint.polynomialbuild(), alglib.polint.polynomialbuildcheb1(), alglib.polint.polynomialbuildcheb2(), alglib.polint.polynomialbuildeqdist(), alglib.polint.polynomialcalccheb1(), alglib.polint.polynomialcalccheb2(), alglib.polint.polynomialcalceqdist(), alglib.polint.polynomialcheb2bar(), alglib.polint.polynomialpow2bar(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.taskgenint1dcheb1(), alglib.apserv.taskgenint1dcheb2(), and alglib.apserv.taskgenint1dequidist().
Referenced by alglib.testpolintunit._pexec_testpolint(), and _Test.Main().
static double alglib.testpolintunit.internalpolint (double[] x, double[] f, int n, double t) inline static private
Referenced by alglib.testpolintunit.testpolint().
static void alglib.testpolintunit.brcunset (ratint.barycentricinterpolant b) inline static private
References alglib.ratint.barycentricbuildxyw().
Referenced by alglib.testpolintunit.testpolint().
static bool alglib.testpolintunit.testpolint (bool silent) inline static
References alglib.ratint.barycentriccalc(), alglib.testpolintunit.brcunset(), alglib.testpolintunit.internalpolint(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.polint.polynomialbar2cheb(), alglib.polint.polynomialbar2pow(), alglib.polint.polynomialbuild(), alglib.polint.polynomialbuildcheb1(), alglib.polint.polynomialbuildcheb2(), alglib.polint.polynomialbuildeqdist(), alglib.polint.polynomialcalccheb1(), alglib.polint.polynomialcalccheb2(), alglib.polint.polynomialcalceqdist(), alglib.polint.polynomialcheb2bar(), alglib.polint.polynomialpow2bar(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.taskgenint1dcheb1(), alglib.apserv.taskgenint1dcheb2(), and alglib.apserv.taskgenint1dequidist().
static bool alglib.testpolintunit._pexec_testpolint (bool silent) inline static
References alglib.testpolintunit.testpolint().
Referenced by _Test.Main().
static double alglib.testpolintunit.internalpolint (double[] x, double[] f, int n, double t) inline static private
static void alglib.testpolintunit.brcunset (ratint.barycentricinterpolant b) inline static private
References alglib.ratint.barycentricbuildxyw().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs