IGLib: IG.Script.ScriptExtExamples.ProgramPipeTest Class Reference
IG.Script.ScriptExtExamples.ProgramPipeTest Class Reference
Public Member Functions
void ThreadStartServer ()
void ThreadStartClient (object obj)
Member Function Documentation
void IG.Script.ScriptExtExamples.ProgramPipeTest.ThreadStartServer () inline
Referenced by IG.Script.ScriptExtExamples.NamedPipes(), and IG.Script.ScriptExtExamples.NamedPipeServer().
void IG.Script.ScriptExtExamples.ProgramPipeTest.ThreadStartClient (object obj) inline
References IG.Lib.Util.SleepSeconds().
Referenced by IG.Script.ScriptExtExamples.NamedPipeClient(), and IG.Script.ScriptExtExamples.NamedPipes().
The documentation for this class was generated from the following file:
shelldev/extensions/ExtShellIT/00testscriptsext/tests/ScriptExtExamples.cs