IGLib: IPLab.GridArrayInt Class Reference
IPLab.GridArrayInt Class Reference
GridArrayInt
Classes
class CellBehavior
Public Member Functions
delegate void GridEventHandler (object sender, GridEventArgs e)
GridArrayInt ()
void LoadData (Array array)
void Colorize ()
Protected Member Functions
virtual void OnCellClicked (int col, int row)
virtual void OnValueChanged (int col, int row)
Events
GridEventHandler CellClicked
GridEventHandler ValueChanged
Private Attributes
Array array
CellBehavior behavior
Detailed Description
GridArrayInt
Constructor & Destructor Documentation
IPLab.GridArrayInt.GridArrayInt () inline
Referenced by IPLab.GridArrayInt.CellBehavior.OnClick(), and IPLab.GridArrayInt.CellBehavior.OnValueChanged().
Member Function Documentation
delegate void IPLab.GridArrayInt.GridEventHandler (object sender, GridEventArgs e)
void IPLab.GridArrayInt.LoadData (Array array) inline
References IPLab.GridArrayInt.array, and IPLab.GridArrayInt.Colorize().
Referenced by IPLab.ConvolutionForm.ConvolutionForm(), IPLab.ConvolutionForm.loadButton_Click(), IPLab.MathMorphologyForm.loadButton_Click(), IPLab.MathMorphologyForm.MathMorphologyForm(), IPLab.ConvolutionForm.sizeCombo_SelectedIndexChanged(), and IPLab.MathMorphologyForm.sizeCombo_SelectedIndexChanged().
void IPLab.GridArrayInt.Colorize () inline
Referenced by IPLab.GridArrayInt.LoadData().
virtual void IPLab.GridArrayInt.OnCellClicked (int col, int row) inline protected virtual
References IPLab.GridArrayInt.CellClicked.
virtual void IPLab.GridArrayInt.OnValueChanged (int col, int row) inline protected virtual
References IPLab.GridArrayInt.ValueChanged.
Member Data Documentation
Array IPLab.GridArrayInt.array private
Referenced by IPLab.GridArrayInt.LoadData().
CellBehavior IPLab.GridArrayInt.behavior private
Event Documentation
GridEventHandler IPLab.GridArrayInt.CellClicked
Referenced by IPLab.GridArrayInt.OnCellClicked().
GridEventHandler IPLab.GridArrayInt.ValueChanged
Referenced by IPLab.GridArrayInt.OnValueChanged().
The documentation for this class was generated from the following file:
igsandbox/imageprocessing/iplab_new_GPL/Sources/Controls/GridArrayInt.cs