IGLib: Test.SparseSquareMatrixTest Class Reference
Test.SparseSquareMatrixTest Class Reference
Public Member Functions
SparseSquareMatrix CreateRandomSparseSquareMatrix (int dim, int fill, Random rng)
void SparseSquareMatrixManipulation ()
void SparseSquareMatrixRowsAndColumns ()
void SparseSquareMatrixCopy ()
void SparseSquareMatrixAgreement ()
void SparseSquareMatrixSolutionAgreement ()
void SparseSquareMatrixPotential ()
Static Private Member Functions
static double PotentialSolution (int x, int y, int n)
Member Function Documentation
SparseSquareMatrix Test.SparseSquareMatrixTest.CreateRandomSparseSquareMatrix (int dim, int fill, Random rng) inline
Referenced by Test.SparseSquareMatrixTest.SparseSquareMatrixRowsAndColumns().
void Test.SparseSquareMatrixTest.SparseSquareMatrixManipulation () inline
References Meta.Numerics.Matrices.SparseSquareMatrix.Dimension, Meta.Numerics.Matrices.SparseSquareMatrix.FillCount, and Meta.Numerics.Matrices.SparseSquareMatrix.FillFraction.
void Test.SparseSquareMatrixTest.SparseSquareMatrixRowsAndColumns () inline
References Meta.Numerics.Matrices.SparseSquareMatrix.Column(), Meta.Numerics.Matrices.AnySquareMatrix.ColumnCount, Test.SparseSquareMatrixTest.CreateRandomSparseSquareMatrix(), Meta.Numerics.Matrices.SparseSquareMatrix.Row(), and Meta.Numerics.Matrices.AnySquareMatrix.RowCount.
void Test.SparseSquareMatrixTest.SparseSquareMatrixCopy () inline
References Meta.Numerics.Matrices.SparseSquareMatrix.Copy(), Meta.Numerics.Matrices.SparseSquareMatrix.Dimension, and Meta.Numerics.Matrices.SparseSquareMatrix.FillCount.
void Test.SparseSquareMatrixTest.SparseSquareMatrixAgreement () inline
void Test.SparseSquareMatrixTest.SparseSquareMatrixSolutionAgreement () inline
References Meta.Numerics.Matrices.SquareMatrix.LUDecomposition(), Meta.Numerics.Matrices.LUDecomposition.Solve(), and Meta.Numerics.Matrices.SparseSquareMatrix.Solve().
void Test.SparseSquareMatrixTest.SparseSquareMatrixPotential () inline
References Test.SparseSquareMatrixTest.PotentialSolution(), and Meta.Numerics.Matrices.SparseSquareMatrix.Solve().
static double Test.SparseSquareMatrixTest.PotentialSolution (int x, int y, int n) inline static private
Referenced by Test.SparseSquareMatrixTest.SparseSquareMatrixPotential().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/SparseSquareMatrixTest.cs