IGLib: alglib.gq Class Reference
alglib.gq Class Reference
Static Public Member Functions
static void gqgeneraterec (double[] alpha, double[] beta, double mu0, int n, ref int info, ref double[] x, ref double[] w)
static void gqgenerategausslobattorec (double[] alpha, double[] beta, double mu0, double a, double b, int n, ref int info, ref double[] x, ref double[] w)
static void gqgenerategaussradaurec (double[] alpha, double[] beta, double mu0, double a, int n, ref int info, ref double[] x, ref double[] w)
static void gqgenerategausslegendre (int n, ref int info, ref double[] x, ref double[] w)
static void gqgenerategaussjacobi (int n, double alpha, double beta, ref int info, ref double[] x, ref double[] w)
static void gqgenerategausslaguerre (int n, double alpha, ref int info, ref double[] x, ref double[] w)
static void gqgenerategausshermite (int n, ref int info, ref double[] x, ref double[] w)
static void gqgeneraterec (double[] alpha, double[] beta, double mu0, int n, ref int info, ref double[] x, ref double[] w)
static void gqgenerategausslobattorec (double[] alpha, double[] beta, double mu0, double a, double b, int n, ref int info, ref double[] x, ref double[] w)
static void gqgenerategaussradaurec (double[] alpha, double[] beta, double mu0, double a, int n, ref int info, ref double[] x, ref double[] w)
static void gqgenerategausslegendre (int n, ref int info, ref double[] x, ref double[] w)
static void gqgenerategaussjacobi (int n, double alpha, double beta, ref int info, ref double[] x, ref double[] w)
static void gqgenerategausslaguerre (int n, double alpha, ref int info, ref double[] x, ref double[] w)
static void gqgenerategausshermite (int n, ref int info, ref double[] x, ref double[] w)
Member Function Documentation
static void alglib.gq.gqgeneraterec (double[] alpha, double[] beta, double mu0, int n, ref int info, ref double[] x, ref double[] w) inline static
References alglib.evd.smatrixtdevd(), and alglib.math.sqr().
Referenced by alglib.gkq.gkqgeneraterec(), alglib.gq.gqgenerategausshermite(), alglib.gq.gqgenerategaussjacobi(), alglib.gq.gqgenerategausslaguerre(), alglib.gq.gqgenerategausslegendre(), alglib.gqgeneraterec(), and alglib.testgqunit.testgq().
static void alglib.gq.gqgenerategausslobattorec (double[] alpha, double[] beta, double mu0, double a, double b, int n, ref int info, ref double[] x, ref double[] w) inline static
References alglib.evd.smatrixtdevd(), and alglib.math.sqr().
Referenced by alglib.gqgenerategausslobattorec(), and alglib.testgqunit.testgq().
static void alglib.gq.gqgenerategaussradaurec (double[] alpha, double[] beta, double mu0, double a, int n, ref int info, ref double[] x, ref double[] w) inline static
References alglib.evd.smatrixtdevd(), and alglib.math.sqr().
Referenced by alglib.gqgenerategaussradaurec(), and alglib.testgqunit.testgq().
static void alglib.gq.gqgenerategausslegendre (int n, ref int info, ref double[] x, ref double[] w) inline static
References alglib.beta(), alglib.gq.gqgeneraterec(), and alglib.math.sqr().
Referenced by alglib.gqgenerategausslegendre(), alglib.testgkqunit.testgkq(), and alglib.testgqunit.testgq().
static void alglib.gq.gqgenerategaussjacobi (int n, double alpha, double beta, ref int info, ref double[] x, ref double[] w) inline static
References alglib.beta(), alglib.gq.gqgeneraterec(), alglib.gammafunc.lngamma(), alglib.math.maxrealnumber, and alglib.math.sqr().
Referenced by alglib.gqgenerategaussjacobi(), alglib.testgkqunit.testgkq(), and alglib.testgqunit.testgq().
static void alglib.gq.gqgenerategausslaguerre (int n, double alpha, ref int info, ref double[] x, ref double[] w) inline static
References alglib.gq.gqgeneraterec(), alglib.gammafunc.lngamma(), and alglib.math.maxrealnumber.
Referenced by alglib.gqgenerategausslaguerre(), and alglib.testgqunit.testgq().
static void alglib.gq.gqgenerategausshermite (int n, ref int info, ref double[] x, ref double[] w) inline static
References alglib.gq.gqgeneraterec().
Referenced by alglib.gqgenerategausshermite(), and alglib.testgqunit.testgq().
static void alglib.gq.gqgeneraterec (double[] alpha, double[] beta, double mu0, int n, ref int info, ref double[] x, ref double[] w) inline static
References alglib.evd.smatrixtdevd(), and alglib.math.sqr().
static void alglib.gq.gqgenerategausslobattorec (double[] alpha, double[] beta, double mu0, double a, double b, int n, ref int info, ref double[] x, ref double[] w) inline static
References alglib.evd.smatrixtdevd(), and alglib.math.sqr().
static void alglib.gq.gqgenerategaussradaurec (double[] alpha, double[] beta, double mu0, double a, int n, ref int info, ref double[] x, ref double[] w) inline static
References alglib.evd.smatrixtdevd(), and alglib.math.sqr().
static void alglib.gq.gqgenerategausslegendre (int n, ref int info, ref double[] x, ref double[] w) inline static
References alglib.beta(), alglib.gq.gqgeneraterec(), and alglib.math.sqr().
static void alglib.gq.gqgenerategaussjacobi (int n, double alpha, double beta, ref int info, ref double[] x, ref double[] w) inline static
References alglib.beta(), alglib.gq.gqgeneraterec(), alglib.gammafunc.lngamma(), alglib.math.maxrealnumber, and alglib.math.sqr().
static void alglib.gq.gqgenerategausslaguerre (int n, double alpha, ref int info, ref double[] x, ref double[] w) inline static
References alglib.gq.gqgeneraterec(), alglib.gammafunc.lngamma(), and alglib.math.maxrealnumber.
static void alglib.gq.gqgenerategausshermite (int n, ref int info, ref double[] x, ref double[] w) inline static
References alglib.gq.gqgeneraterec().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/integration.cs