IGLib: Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution Class Reference
Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution Class Reference
Public Member Functions
KolmogorovTwoSampleExactDistribution (int n, int m)
long LatticePathSum (int c)
override double LeftExclusiveProbability (int k)
Computes the probability of obtaining a value less than the given value.
override double LeftInclusiveProbability (int k)
Computes the probability of obtaining a value less than or equal to the given value.
override double ProbabilityMass (int k)
Returns the probability of the obtaining the given value.
override double ExpectationValue (Func< int, double > f)
Computes the expectation value of an artibrary function.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.DiscreteDistribution
virtual double RightExclusiveProbability (int k)
Computes the probability of obtaining a value greater than the given value.
virtual int InverseLeftProbability (double P)
Computes the value corresponding to the given percentile.
override double Moment (int r)
Gets a raw moment of the distribution.
override double MomentAboutMean (int r)
Gets a central moment of the distribution.
virtual int GetRandomValue (Random rng)
Produces a random integer drawn from the distribution.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Cumulant (int r)
Computes a cumulant of the distribution.
Properties
override int Maximum [get]
override int Minimum [get]
override double Mean [get]
override double Variance [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.DiscreteDistribution
abstract int Minimum [get]
Gets the smallest value in the distribution.
abstract int Maximum [get]
Gets the largest value in the distribution.
override double Mean [get]
Gets the mean of the distribution.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Private Attributes
readonly int n
readonly int m
Constructor & Destructor Documentation
Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.KolmogorovTwoSampleExactDistribution (int n, int m) inline
Member Function Documentation
long Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.LatticePathSum (int c) inline
Referenced by FutureTest.FutureTest.TwoSampleKS().
override double Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.LeftExclusiveProbability (int k) inline virtual
Computes the probability of obtaining a value less than the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value strictly less than k .
See also
RightExclusiveProbability
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
override double Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.LeftInclusiveProbability (int k) inline virtual
Computes the probability of obtaining a value less than or equal to the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value les than or equal to k .
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient(), and Meta.Numerics.Functions.AdvancedIntegerMath.GCF().
override double Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.ProbabilityMass (int k) inline virtual
Returns the probability of the obtaining the given value.
Parameters
k The value.
Returns
The probability of obtaining the value.
Implements Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient(), and Meta.Numerics.Functions.AdvancedIntegerMath.GCF().
Referenced by FutureTest.FutureTest.TwoSampleKS2().
override double Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.ExpectationValue (Func< int, double > f) inline virtual
Computes the expectation value of an artibrary function.
Parameters
f The function.
Returns
The expectation value of the function.
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
Member Data Documentation
readonly int Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.n private
readonly int Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.m private
Property Documentation
override int Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.Maximum get
Referenced by FutureTest.FutureTest.TwoSampleKS().
override int Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.Minimum get
Referenced by FutureTest.FutureTest.TwoSampleKS().
override double Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.Mean get
override double Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.Variance get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/KolmogorovTwoSampleExactDistribution.cs