IGLib: NUnit.Engine.Api.Tests.TestPackageTests_MultipleAssemblies Class Reference
NUnit.Engine.Api.Tests.TestPackageTests_MultipleAssemblies Class Reference
Public Member Functions
void CreatePackage ()
void PackageIsAnonymous ()
void PackageContainsThreeSubpackages ()
Private Attributes
TestPackage package
Member Function Documentation
void NUnit.Engine.Api.Tests.TestPackageTests_MultipleAssemblies.CreatePackage () inline
void NUnit.Engine.Api.Tests.TestPackageTests_MultipleAssemblies.PackageIsAnonymous () inline
References NUnit.Engine.TestPackage.FullName, and NUnit.Framework.Assert.Null().
void NUnit.Engine.Api.Tests.TestPackageTests_MultipleAssemblies.PackageContainsThreeSubpackages () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestPackage.SubPackages, and NUnit.Framework.Assert.That().
Member Data Documentation
TestPackage NUnit.Engine.Api.Tests.TestPackageTests_MultipleAssemblies.package private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Api/TestPackageTests.cs