IGLib: NUnit.Framework.Constraints.IResolveConstraint Interface Reference
NUnit.Framework.Constraints.IResolveConstraint Interface Reference
The IResolveConstraint interface is implemented by all complete and resolvable constraints and expressions.
Public Member Functions
IConstraint Resolve ()
Return the top-level constraint for this expression
Detailed Description
The IResolveConstraint interface is implemented by all complete and resolvable constraints and expressions.
Member Function Documentation
IConstraint NUnit.Framework.Constraints.IResolveConstraint.Resolve ()
Return the top-level constraint for this expression
Returns
Implemented in NUnit.Framework.Constraints.Constraint, NUnit.Framework.Constraints.ConstraintBuilder, NUnit.Framework.Constraints.ResolvableConstraintExpression, and NUnit.Framework.Constraints.ReusableConstraint.
Referenced by NUnit.Framework.Constraints.ToStringTests.CanDisplayPrefixConstraints_Resolved(), NUnit.Framework.Constraints.ToStringTests.CanDisplaySimpleConstraints_Resolved(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraint(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintAfterPrefix(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintsUnderAndOperator(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchLambda(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchPredicate(), NUnit.Framework.Constraints.ToStringTests.DisplayBinaryConstraints_Resolved(), NUnit.Framework.Constraints.AndConstraintTests.HandlesFirstPartFailing(), NUnit.Framework.Constraints.ConstraintExpression.Matches(), NUnit.Framework.Constraints.Constraint.operator!(), NUnit.Framework.Constraints.Constraint.operator&(), NUnit.Framework.Constraints.Constraint.operator|(), NUnit.Framework.Constraints.PrefixConstraint.PrefixConstraint(), NUnit.Framework.Constraints.ResolvableConstraintExpression.Resolve(), NUnit.Framework.Constraints.ReusableConstraint.ReusableConstraint(), NUnit.Framework.Syntax.SyntaxTest.SupportedByConstraintBuilder(), NUnit.Framework.Syntax.SyntaxTest.SupportedByInheritedSyntax(), NUnit.Framework.Syntax.SyntaxTest.SupportedByStaticSyntax(), NUnit.Framework.Syntax.ThrowsTests.ThrowsException(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionInstanceOf(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionTypeOf(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionTypeOfAndConstraint(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionWithConstraint(), NUnit.Framework.Syntax.ThrowsTests.ThrowsInstanceOf(), NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOf(), NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOfAndConstraint(), and NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOfWithConstraint().
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/IResolveConstraint.cs