IGLib: NUnit.Common.Logger Class Reference
NUnit.Common.Logger Class Reference
Provides internal logging to the NUnit framework
Public Member Functions
Logger (string name, InternalTraceLevel level, TextWriter writer)
Initializes a new instance of the Logger class.
void Error (string message)
Logs the message at error level.
void Error (string message, params object[] args)
Logs the message at error level.
void Warning (string message)
Logs the message at warm level.
void Warning (string message, params object[] args)
Logs the message at warning level.
void Info (string message)
Logs the message at info level.
void Info (string message, params object[] args)
Logs the message at info level.
void Debug (string message)
Logs the message at debug level.
void Debug (string message, params object[] args)
Logs the message at debug level.
Private Member Functions
void Log (InternalTraceLevel level, string message)
void Log (InternalTraceLevel level, string format, params object[] args)
void WriteLog (InternalTraceLevel level, string message)
Private Attributes
string name
string fullname
InternalTraceLevel maxLevel
TextWriter writer
Static Private Attributes
static readonly string TIME_FMT = "HH:mm:ss.fff"
static readonly string TRACE_FMT = "{0} {1,-5} [{2,2}] {3}: {4}"
Detailed Description
Provides internal logging to the NUnit framework
Constructor & Destructor Documentation
NUnit.Common.Logger.Logger (string name, InternalTraceLevel level, TextWriter writer) inline
Initializes a new instance of the Logger class.
Parameters
name The name.
level The log level.
writer The writer where logs are sent.
Member Function Documentation
void NUnit.Common.Logger.Error (string message) inline
Logs the message at error level.
Parameters
message The message.
Implements NUnit.Common.ILogger.
Referenced by NUnit.Framework.Api.DefaultTestAssemblyBuilder.GetFixtures(), NUnit.Engine.Services.TestAgency.ReleaseAgent(), NUnit.Engine.Services.DomainManager.DomainUnloader.Unload(), and NUnit.Engine.Services.DomainManager.DomainUnloader.UnloadOnThread().
void NUnit.Common.Logger.Error (string message, params object[] args) inline
Logs the message at error level.
Parameters
message The message.
args The message arguments.
Implements NUnit.Common.ILogger.
void NUnit.Common.Logger.Warning (string message) inline
Logs the message at warm level.
Parameters
message The message.
Implements NUnit.Common.ILogger.
void NUnit.Common.Logger.Warning (string message, params object[] args) inline
Logs the message at warning level.
Parameters
message The message.
args The message arguments.
Implements NUnit.Common.ILogger.
void NUnit.Common.Logger.Info (string message) inline
Logs the message at info level.
Parameters
message The message.
Implements NUnit.Common.ILogger.
Referenced by NUnit.Engine.Services.TestAgency.LaunchAgentProcess(), NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync(), and NUnit.Engine.Services.DomainManager.DomainUnloader.Unload().
void NUnit.Common.Logger.Info (string message, params object[] args) inline
Logs the message at info level.
Parameters
message The message.
args The message arguments.
Implements NUnit.Common.ILogger.
void NUnit.Common.Logger.Debug (string message) inline
Logs the message at debug level.
Parameters
message The message.
Implements NUnit.Common.ILogger.
Referenced by NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build(), NUnit.Engine.Services.TestAgency.CreateRemoteAgent(), NUnit.Framework.Api.DefaultTestAssemblyBuilder.GetFixtures(), NUnit.Engine.Services.TestAgency.LaunchAgentProcess(), NUnit.Engine.Services.TestAgency.ReleaseAgent(), and NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework().
void NUnit.Common.Logger.Debug (string message, params object[] args) inline
Logs the message at debug level.
Parameters
message The message.
args The message arguments.
Implements NUnit.Common.ILogger.
void NUnit.Common.Logger.Log (InternalTraceLevel level, string message) inline private
void NUnit.Common.Logger.Log (InternalTraceLevel level, string format, params object[] args) inline private
void NUnit.Common.Logger.WriteLog (InternalTraceLevel level, string message) inline private
Member Data Documentation
readonly string NUnit.Common.Logger.TIME_FMT = "HH:mm:ss.fff" static private
readonly string NUnit.Common.Logger.TRACE_FMT = "{0} {1,-5} [{2,2}] {3}: {4}" static private
string NUnit.Common.Logger.name private
string NUnit.Common.Logger.fullname private
InternalTraceLevel NUnit.Common.Logger.maxLevel private
TextWriter NUnit.Common.Logger.writer private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/Logging/Logger.cs