IGLib: alglib.nleq Class Reference
alglib.nleq Class Reference
Classes
class nleqreport
class nleqstate
Static Public Member Functions
static void nleqcreatelm (int n, int m, double[] x, nleqstate state)
static void nleqsetcond (nleqstate state, double epsf, int maxits)
static void nleqsetxrep (nleqstate state, bool needxrep)
static void nleqsetstpmax (nleqstate state, double stpmax)
static bool nleqiteration (nleqstate state)
static void nleqresults (nleqstate state, ref double[] x, nleqreport rep)
static void nleqresultsbuf (nleqstate state, ref double[] x, nleqreport rep)
static void nleqrestartfrom (nleqstate state, double[] x)
static void nleqcreatelm (int n, int m, double[] x, nleqstate state)
static void nleqsetcond (nleqstate state, double epsf, int maxits)
static void nleqsetxrep (nleqstate state, bool needxrep)
static void nleqsetstpmax (nleqstate state, double stpmax)
static bool nleqiteration (nleqstate state)
static void nleqresults (nleqstate state, ref double[] x, nleqreport rep)
static void nleqresultsbuf (nleqstate state, ref double[] x, nleqreport rep)
static void nleqrestartfrom (nleqstate state, double[] x)
Public Attributes
const int armijomaxfev = 20
Static Private Member Functions
static void clearrequestfields (nleqstate state)
static bool increaselambda (ref double lambdav, ref double nu, double lambdaup)
static void decreaselambda (ref double lambdav, ref double nu, double lambdadown)
static void clearrequestfields (nleqstate state)
static bool increaselambda (ref double lambdav, ref double nu, double lambdaup)
static void decreaselambda (ref double lambdav, ref double nu, double lambdadown)
Member Function Documentation
static void alglib.nleq.nleqcreatelm (int n, int m, double[] x, nleqstate state) inline static
References alglib.ap.assert(), alglib.nleq.nleqstate.candstep, alglib.nleq.nleqstate.fi, alglib.apserv.isfinitevector(), alglib.nleq.nleqstate.j, alglib.nleq.nleqstate.m, alglib.nleq.nleqstate.n, alglib.nleq.nleqrestartfrom(), alglib.nleq.nleqsetcond(), alglib.nleq.nleqsetstpmax(), alglib.nleq.nleqsetxrep(), alglib.nleq.nleqstate.rightpart, alglib.nleq.nleqstate.x, and alglib.nleq.nleqstate.xbase.
Referenced by alglib.nleqcreatelm(), and alglib.testnlequnit.testnleq().
static void alglib.nleq.nleqsetcond (nleqstate state, double epsf, int maxits) inline static
References alglib.ap.assert(), alglib.nleq.nleqstate.epsf, alglib.math.isfinite(), and alglib.nleq.nleqstate.maxits.
Referenced by alglib.nleq.nleqcreatelm(), alglib.nleqsetcond(), and alglib.testnlequnit.testnleq().
static void alglib.nleq.nleqsetxrep (nleqstate state, bool needxrep) inline static
References alglib.nleq.nleqstate.xrep.
Referenced by alglib.nleq.nleqcreatelm(), alglib.nleqsetxrep(), and alglib.testnlequnit.testnleq().
static void alglib.nleq.nleqsetstpmax (nleqstate state, double stpmax) inline static
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.nleq.nleqstate.stpmax.
Referenced by alglib.nleq.nleqcreatelm(), alglib.nleqsetstpmax(), and alglib.testnlequnit.testnleq().
static bool alglib.nleq.nleqiteration (nleqstate state) inline static
References alglib.rcommstate.ba, alglib.nleq.nleqstate.candstep, alglib.nleq.nleqstate.cgbuf, alglib.nleq.clearrequestfields(), alglib.nleq.decreaselambda(), alglib.nleq.nleqstate.epsf, alglib.nleq.nleqstate.f, alglib.nleq.nleqstate.fbase, alglib.fbls.fblssolvecgx(), alglib.nleq.nleqstate.fi, alglib.nleq.nleqstate.fprev, alglib.rcommstate.ia, alglib.nleq.increaselambda(), alglib.nleq.nleqstate.j, alglib.linmin.linminnormalized(), alglib.nleq.nleqstate.m, alglib.nleq.nleqstate.maxits, alglib.math.maxrealnumber, alglib.nleq.nleqstate.n, alglib.nleq.nleqstate.needf, alglib.nleq.nleqstate.needfij, alglib.rcommstate.ra, alglib.nleq.nleqstate.repiterationscount, alglib.nleq.nleqstate.repnfunc, alglib.nleq.nleqstate.repnjac, alglib.nleq.nleqstate.repterminationtype, alglib.nleq.nleqstate.rightpart, alglib.ablas.rmatrixmv(), alglib.nleq.nleqstate.rstate, alglib.math.sqr(), alglib.rcommstate.stage, alglib.nleq.nleqstate.stpmax, alglib.nleq.nleqstate.x, alglib.nleq.nleqstate.xbase, alglib.nleq.nleqstate.xrep, and alglib.nleq.nleqstate.xupdated.
Referenced by alglib.nleqiteration(), and alglib.testnlequnit.testnleq().
static void alglib.nleq.nleqresults (nleqstate state, ref double[] x, nleqreport rep) inline static
References alglib.nleq.nleqresultsbuf().
Referenced by alglib.nleqresults(), and alglib.testnlequnit.testnleq().
static void alglib.nleq.nleqresultsbuf (nleqstate state, ref double[] x, nleqreport rep) inline static
References alglib.nleq.nleqreport.iterationscount, alglib.nleq.nleqstate.n, alglib.nleq.nleqreport.nfunc, alglib.nleq.nleqreport.njac, alglib.nleq.nleqstate.repiterationscount, alglib.nleq.nleqstate.repnfunc, alglib.nleq.nleqstate.repnjac, alglib.nleq.nleqstate.repterminationtype, alglib.nleq.nleqreport.terminationtype, and alglib.nleq.nleqstate.xbase.
Referenced by alglib.nleq.nleqresults(), and alglib.nleqresultsbuf().
static void alglib.nleq.nleqrestartfrom (nleqstate state, double[] x) inline static
References alglib.ap.assert(), alglib.rcommstate.ba, alglib.nleq.clearrequestfields(), alglib.rcommstate.ia, alglib.apserv.isfinitevector(), alglib.nleq.nleqstate.n, alglib.rcommstate.ra, alglib.nleq.nleqstate.rstate, alglib.rcommstate.stage, and alglib.nleq.nleqstate.x.
Referenced by alglib.nleq.nleqcreatelm(), alglib.nleqrestartfrom(), and alglib.testnlequnit.testnleq().
static void alglib.nleq.clearrequestfields (nleqstate state) inline static private
References alglib.nleq.nleqstate.needf, alglib.nleq.nleqstate.needfij, and alglib.nleq.nleqstate.xupdated.
Referenced by alglib.nleq.nleqiteration(), and alglib.nleq.nleqrestartfrom().
static bool alglib.nleq.increaselambda (ref double lambdav, ref double nu, double lambdaup) inline static private
References alglib.math.maxrealnumber.
Referenced by alglib.nleq.nleqiteration().
static void alglib.nleq.decreaselambda (ref double lambdav, ref double nu, double lambdadown) inline static private
References alglib.math.minrealnumber.
Referenced by alglib.nleq.nleqiteration().
static void alglib.nleq.nleqcreatelm (int n, int m, double[] x, nleqstate state) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.nleq.nleqrestartfrom(), alglib.nleq.nleqsetcond(), alglib.nleq.nleqsetstpmax(), and alglib.nleq.nleqsetxrep().
static void alglib.nleq.nleqsetcond (nleqstate state, double epsf, int maxits) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
static void alglib.nleq.nleqsetxrep (nleqstate state, bool needxrep) inline static
static void alglib.nleq.nleqsetstpmax (nleqstate state, double stpmax) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
static bool alglib.nleq.nleqiteration (nleqstate state) inline static
References alglib.nleq.clearrequestfields(), alglib.nleq.decreaselambda(), alglib.fbls.fblssolvecgx(), alglib.nleq.increaselambda(), alglib.linmin.linminnormalized(), alglib.math.maxrealnumber, alglib.ablas.rmatrixmv(), and alglib.math.sqr().
static void alglib.nleq.nleqresults (nleqstate state, ref double[] x, nleqreport rep) inline static
References alglib.nleq.nleqresultsbuf().
static void alglib.nleq.nleqresultsbuf (nleqstate state, ref double[] x, nleqreport rep) inline static
static void alglib.nleq.nleqrestartfrom (nleqstate state, double[] x) inline static
References alglib.ap.assert(), alglib.nleq.clearrequestfields(), and alglib.apserv.isfinitevector().
static void alglib.nleq.clearrequestfields (nleqstate state) inline static private
static bool alglib.nleq.increaselambda (ref double lambdav, ref double nu, double lambdaup) inline static private
References alglib.math.maxrealnumber.
static void alglib.nleq.decreaselambda (ref double lambdav, ref double nu, double lambdadown) inline static private
References alglib.math.minrealnumber.
Member Data Documentation
const int alglib.nleq.armijomaxfev = 20
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/solvers.cs