IGLib: Test.BinaryContingencyTableTest Class Reference
Test.BinaryContingencyTableTest Class Reference
Public Member Functions
void BCT ()
void BinaryContingencyNullTest ()
void BinaryContingencyInvalidConstructionTest ()
void BinaryContingencyTest ()
Static Private Member Functions
static BinaryContingencyTable CreateExperiment (double p, double q0, double q1, int N)
Member Function Documentation
static BinaryContingencyTable Test.BinaryContingencyTableTest.CreateExperiment (double p, double q0, double q1, int N) inline static private
Referenced by Test.BinaryContingencyTableTest.BinaryContingencyNullTest(), and Test.BinaryContingencyTableTest.BinaryContingencyTest().
void Test.BinaryContingencyTableTest.BCT () inline
void Test.BinaryContingencyTableTest.BinaryContingencyNullTest () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.Statistics.ContingencyTable.ColumnTotal(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.BinaryContingencyTableTest.CreateExperiment(), Meta.Numerics.Statistics.BinaryContingencyTable.FisherExactTest(), Meta.Numerics.Statistics.BinaryContingencyTable.LogOddsRatio, Meta.Numerics.Statistics.BinaryContingencyTable.OddsRatio, Meta.Numerics.Statistics.TestResult.RightProbability, Meta.Numerics.Statistics.ContingencyTable.RowTotal(), and Meta.Numerics.Statistics.ContingencyTable.Total.
void Test.BinaryContingencyTableTest.BinaryContingencyInvalidConstructionTest () inline
void Test.BinaryContingencyTableTest.BinaryContingencyTest () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.Statistics.ContingencyTable.ColumnTotal(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.BinaryContingencyTableTest.CreateExperiment(), Meta.Numerics.Statistics.BinaryContingencyTable.FisherExactTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.BinaryContingencyTable.LogOddsRatio, Meta.Numerics.Statistics.BinaryContingencyTable.OddsRatio, Meta.Numerics.Statistics.ContingencyTable.PearsonChiSquaredTest(), Meta.Numerics.Statistics.TestResult.RightProbability, Meta.Numerics.Statistics.ContingencyTable.RowTotal(), and Meta.Numerics.Statistics.ContingencyTable.Total.
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/BinaryContingencyTableTest.cs