IGLib: Test.DistributionTest Class Reference
Test.DistributionTest Class Reference
Public Member Functions
void DistributionMedian ()
void DistributionSkewness ()
void DistributionCentralInequality ()
void DistributionMonotonicity ()
void DistributionProbability ()
void DistributionUnitarityIntegral ()
void DistributionMeanIntegral ()
void DistributionVarianceIntegral ()
void DistributionRawMomentIntegral ()
void DistributionCentralMomentIntegral ()
void DistributionProbabilityIntegral ()
void DistributionInvalidProbabilityInput ()
void StudentTest2 ()
void StudentTest ()
void FisherTest ()
void UniformOrderStatistics ()
void FisherInversion ()
void GammaFromExponential ()
void InverseGaussianSummation ()
void CauchyStudentAgreement ()
void CauchyFWHM ()
void DistributionRandomDeviates ()
void OutsideDistributionSupport ()
void DistributionBase ()
void BetaInversion ()
void TransformedBetaMoments ()
void DistributionMomentTranslations ()
void TimeOperations ()
Static Public Member Functions
static Distribution[] GetDistributions ()
Private Member Functions
void DistributionProbabilityTestHelper (Distribution distribution, double x)
Private Attributes
Distribution[] distributions
double[] probabilities
double[] cs = new double[] { 0.02, 0.2, 2.0, 20.0, 200.0 }
Member Function Documentation
static Distribution [] Test.DistributionTest.GetDistributions () inline static
References Meta.Numerics.Interval.FromEndpoints().
Referenced by Test.UnivariateDistributionTest.Initialize().
void Test.DistributionTest.DistributionMedian () inline
References Meta.Numerics.Statistics.Distributions.Distribution.InverseLeftProbability(), and Meta.Numerics.Statistics.Distributions.Distribution.Median.
void Test.DistributionTest.DistributionSkewness () inline
References Meta.Numerics.Statistics.Distributions.Distribution.MomentAboutMean(), and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Skewness.
void Test.DistributionTest.DistributionCentralInequality () inline
References Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Distributions.Distribution.Median, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation.
void Test.DistributionTest.DistributionMonotonicity () inline
References Meta.Numerics.Statistics.Distributions.Distribution.InverseLeftProbability().
void Test.DistributionTest.DistributionProbability () inline
References Test.DistributionTest.DistributionProbabilityTestHelper().
void Test.DistributionTest.DistributionProbabilityTestHelper (Distribution distribution, double x) inline private
References Meta.Numerics.Statistics.Distributions.Distribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.Distribution.ProbabilityDensity(), and Meta.Numerics.Statistics.Distributions.Distribution.RightProbability().
Referenced by Test.DistributionTest.DistributionProbability().
void Test.DistributionTest.DistributionUnitarityIntegral () inline
References Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Statistics.Distributions.GammaDistribution.ProbabilityDensity(), and Meta.Numerics.Statistics.Distributions.GammaDistribution.Support.
void Test.DistributionTest.DistributionMeanIntegral () inline
References Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Distributions.Distribution.ProbabilityDensity(), and Meta.Numerics.Statistics.Distributions.Distribution.Support.
void Test.DistributionTest.DistributionVarianceIntegral () inline
References Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Distributions.Distribution.ProbabilityDensity(), Meta.Numerics.Statistics.Distributions.GammaDistribution.ShapeParameter, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation, Meta.Numerics.Statistics.Distributions.Distribution.Support, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Variance.
void Test.DistributionTest.DistributionRawMomentIntegral () inline
References Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Statistics.Distributions.Distribution.Moment(), Meta.Numerics.Statistics.Distributions.Distribution.ProbabilityDensity(), and Meta.Numerics.Statistics.Distributions.Distribution.Support.
void Test.DistributionTest.DistributionCentralMomentIntegral () inline
References Meta.Numerics.Analysis.EvaluationSettings.AbsolutePrecision, Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Distributions.Distribution.MomentAboutMean(), Meta.Numerics.MoreMath.Pow(), Meta.Numerics.Statistics.Distributions.Distribution.ProbabilityDensity(), Meta.Numerics.Analysis.EvaluationSettings.RelativePrecision, and Meta.Numerics.Statistics.Distributions.Distribution.Support.
void Test.DistributionTest.DistributionProbabilityIntegral () inline
References Meta.Numerics.Analysis.EvaluationSettings.AbsolutePrecision, Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Interval.LeftEndpoint, Meta.Numerics.Statistics.Distributions.Distribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.Distribution.ProbabilityDensity(), Meta.Numerics.Interval.RightEndpoint, Meta.Numerics.Statistics.Distributions.Distribution.RightProbability(), Meta.Numerics.Statistics.Distributions.Distribution.Support, and Meta.Numerics.Interval.Width.
void Test.DistributionTest.DistributionInvalidProbabilityInput () inline
References Meta.Numerics.Statistics.Distributions.Distribution.InverseLeftProbability().
void Test.DistributionTest.StudentTest2 () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Distributions.Distribution.InverseLeftProbability(), Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), and Meta.Numerics.Statistics.TestResult.LeftProbability.
void Test.DistributionTest.StudentTest () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Sample.Count, Meta.Numerics.Statistics.Distributions.Distribution.InverseLeftProbability(), Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, and Meta.Numerics.UncertainValue.Value.
void Test.DistributionTest.FisherTest () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Distributions.Distribution.InverseLeftProbability(), Meta.Numerics.Statistics.Sample.KuiperTest(), and Meta.Numerics.Statistics.TestResult.LeftProbability.
void Test.DistributionTest.UniformOrderStatistics () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Distributions.Distribution.GetRandomValue(), Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), and Meta.Numerics.Statistics.TestResult.LeftProbability.
void Test.DistributionTest.FisherInversion () inline
References Meta.Numerics.Statistics.Distributions.FisherDistribution.DenominatorDegreesOfFreedom, Meta.Numerics.Statistics.Distributions.Distribution.GetRandomValue(), Meta.Numerics.Statistics.Distributions.FisherDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.FisherDistribution.NumeratorDegreesOfFreedom, and Meta.Numerics.Statistics.Distributions.FisherDistribution.RightProbability().
void Test.DistributionTest.GammaFromExponential () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), and Meta.Numerics.Statistics.TestResult.LeftProbability.
void Test.DistributionTest.InverseGaussianSummation () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Distributions.Distribution.GetRandomValue(), Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), and Meta.Numerics.Statistics.TestResult.LeftProbability.
void Test.DistributionTest.CauchyStudentAgreement () inline
void Test.DistributionTest.CauchyFWHM () inline
References Meta.Numerics.Statistics.Distributions.CauchyDistribution.FullWithAtHalfMaximum, Meta.Numerics.Statistics.Distributions.CauchyDistribution.Median, and Meta.Numerics.Statistics.Distributions.CauchyDistribution.ProbabilityDensity().
void Test.DistributionTest.DistributionRandomDeviates () inline
References Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), and Meta.Numerics.Statistics.TestResult.LeftProbability.
void Test.DistributionTest.OutsideDistributionSupport () inline
References Meta.Numerics.Interval.LeftEndpoint, Meta.Numerics.Statistics.Distributions.Distribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.Distribution.ProbabilityDensity(), Meta.Numerics.Interval.RightEndpoint, Meta.Numerics.Statistics.Distributions.Distribution.RightProbability(), and Meta.Numerics.Statistics.Distributions.Distribution.Support.
void Test.DistributionTest.DistributionBase () inline
References Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Distributions.Distribution.Median, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Skewness, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation.
void Test.DistributionTest.BetaInversion () inline
void Test.DistributionTest.TransformedBetaMoments () inline
References Meta.Numerics.Statistics.Distributions.BetaDistribution.Alpha, Meta.Numerics.Statistics.Distributions.BetaDistribution.Beta, Meta.Numerics.Statistics.Distributions.Distribution.ExpectationValue(), Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Functions.AdvancedMath.Psi().
void Test.DistributionTest.DistributionMomentTranslations () inline
References Meta.Numerics.Statistics.Distributions.MomentMath.CentralToRaw(), Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Distributions.Distribution.Moment(), and Meta.Numerics.Statistics.Distributions.Distribution.MomentAboutMean().
void Test.DistributionTest.TimeOperations () inline
References Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Cumulant().
Member Data Documentation
Distribution [] Test.DistributionTest.distributions private
Initial value:
= new Distribution[] {
            new CauchyDistribution(1.0, 2.0),
            new UniformDistribution(Interval.FromEndpoints(-2.0,1.0)), new UniformDistribution(Interval.FromEndpoints(7.0, 9.0)),
            new NormalDistribution(3.0,2.0),
            new ExponentialDistribution(2.0),
            new ChiSquaredDistribution(3),
            new StudentDistribution(5),
            new LognormalDistribution(0.2,0.4),
            new WeibullDistribution(2.0, 3.0),
            new LogisticDistribution(-4.0,5.0),
            new FisherDistribution(4.0, 7.0),
            new KuiperDistribution(),
            new KolmogorovDistribution(),
            new TriangularDistribution(1.0,2.0,4.0),
            new BetaDistribution(0.5, 2.0),
            new ParetoDistribution(1.0, 3.0),
            new WaldDistribution(3.0, 1.0),
            new PearsonRDistribution(7),
            new GammaDistribution(0.8), new GammaDistribution(3.0, 5.0), new GammaDistribution(96.2),
            new GumbelDistribution(1.2, 2.3)
        }
double [] Test.DistributionTest.probabilities private
Initial value:
= new double[] {
            0.00001, 0.01, 0.05, 0.1, 1.0 / 3.0, 1.0 / 2.0, 2.0 / 3.0, 0.9, 0.95, 0.99999
        }
double [] Test.DistributionTest.cs = new double[] { 0.02, 0.2, 2.0, 20.0, 200.0 } private
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/DistributionTest.cs