IGLib: alglib.testrcondunit Class Reference
alglib.testrcondunit Class Reference
Static Public Member Functions
static bool testrcond (bool silent)
static bool testrcond (bool silent)
static bool _pexec_testrcond (bool silent)
Public Attributes
const double threshold50 = 0.25
const double threshold90 = 0.10
Static Private Member Functions
static void rmatrixmakeacopy (double[,] a, int m, int n, ref double[,] b)
static void rmatrixdrophalf (ref double[,] a, int n, bool droplower)
static void cmatrixdrophalf (ref complex[,] a, int n, bool droplower)
static void rmatrixgenzero (ref double[,] a0, int n)
static bool rmatrixinvmattr (ref double[,] a, int n, bool isupper, bool isunittriangular)
static bool rmatrixinvmatlu (ref double[,] a, int[] pivots, int n)
static bool rmatrixinvmat (ref double[,] a, int n)
static void rmatrixrefrcond (double[,] a, int n, ref double rc1, ref double rcinf)
static void cmatrixmakeacopy (complex[,] a, int m, int n, ref complex[,] b)
static void cmatrixgenzero (ref complex[,] a0, int n)
static bool cmatrixinvmattr (ref complex[,] a, int n, bool isupper, bool isunittriangular)
static bool cmatrixinvmatlu (ref complex[,] a, int[] pivots, int n)
static bool cmatrixinvmat (ref complex[,] a, int n)
static void cmatrixrefrcond (complex[,] a, int n, ref double rc1, ref double rcinf)
static bool testrmatrixtrrcond (int maxn, int passcount)
static bool testcmatrixtrrcond (int maxn, int passcount)
static bool testrmatrixrcond (int maxn, int passcount)
static bool testspdmatrixrcond (int maxn, int passcount)
static bool testcmatrixrcond (int maxn, int passcount)
static bool testhpdmatrixrcond (int maxn, int passcount)
static void rmatrixmakeacopy (double[,] a, int m, int n, ref double[,] b)
static void rmatrixdrophalf (ref double[,] a, int n, bool droplower)
static void cmatrixdrophalf (ref complex[,] a, int n, bool droplower)
static void rmatrixgenzero (ref double[,] a0, int n)
static bool rmatrixinvmattr (ref double[,] a, int n, bool isupper, bool isunittriangular)
static bool rmatrixinvmatlu (ref double[,] a, int[] pivots, int n)
static bool rmatrixinvmat (ref double[,] a, int n)
static void rmatrixrefrcond (double[,] a, int n, ref double rc1, ref double rcinf)
static void cmatrixmakeacopy (complex[,] a, int m, int n, ref complex[,] b)
static void cmatrixgenzero (ref complex[,] a0, int n)
static bool cmatrixinvmattr (ref complex[,] a, int n, bool isupper, bool isunittriangular)
static bool cmatrixinvmatlu (ref complex[,] a, int[] pivots, int n)
static bool cmatrixinvmat (ref complex[,] a, int n)
static void cmatrixrefrcond (complex[,] a, int n, ref double rc1, ref double rcinf)
static bool testrmatrixtrrcond (int maxn, int passcount)
static bool testcmatrixtrrcond (int maxn, int passcount)
static bool testrmatrixrcond (int maxn, int passcount)
static bool testspdmatrixrcond (int maxn, int passcount)
static bool testcmatrixrcond (int maxn, int passcount)
static bool testhpdmatrixrcond (int maxn, int passcount)
Member Function Documentation
static bool alglib.testrcondunit.testrcond (bool silent) inline static
References alglib.testrcondunit.testcmatrixrcond(), alglib.testrcondunit.testcmatrixtrrcond(), alglib.testrcondunit.testhpdmatrixrcond(), alglib.testrcondunit.testrmatrixrcond(), alglib.testrcondunit.testrmatrixtrrcond(), and alglib.testrcondunit.testspdmatrixrcond().
Referenced by alglib.testrcondunit._pexec_testrcond(), and _Test.Main().
static void alglib.testrcondunit.rmatrixmakeacopy (double a[,], int m, int n, ref double b[,]) inline static private
Referenced by alglib.testrcondunit.rmatrixrefrcond(), alglib.testrcondunit.testrmatrixrcond(), alglib.testrcondunit.testrmatrixtrrcond(), and alglib.testrcondunit.testspdmatrixrcond().
static void alglib.testrcondunit.rmatrixdrophalf (ref double a[,], int n, bool droplower) inline static private
Referenced by alglib.testrcondunit.testspdmatrixrcond().
static void alglib.testrcondunit.cmatrixdrophalf (ref complex a[,], int n, bool droplower) inline static private
Referenced by alglib.testrcondunit.testhpdmatrixrcond().
static void alglib.testrcondunit.rmatrixgenzero (ref double a0[,], int n) inline static private
Referenced by alglib.testrcondunit.testrmatrixrcond(), and alglib.testrcondunit.testrmatrixtrrcond().
static bool alglib.testrcondunit.rmatrixinvmattr (ref double a[,], int n, bool isupper, bool isunittriangular) inline static private
Referenced by alglib.testrcondunit.rmatrixinvmatlu().
static bool alglib.testrcondunit.rmatrixinvmatlu (ref double a[,], int[] pivots, int n) inline static private
References alglib.testrcondunit.rmatrixinvmattr().
Referenced by alglib.testrcondunit.rmatrixinvmat().
static bool alglib.testrcondunit.rmatrixinvmat (ref double a[,], int n) inline static private
References alglib.testrcondunit.rmatrixinvmatlu(), and alglib.trfac.rmatrixlu().
Referenced by alglib.testrcondunit.rmatrixrefrcond().
static void alglib.testrcondunit.rmatrixrefrcond (double a[,], int n, ref double rc1, ref double rcinf) inline static private
References alglib.testrcondunit.rmatrixinvmat(), and alglib.testrcondunit.rmatrixmakeacopy().
Referenced by alglib.testrcondunit.testrmatrixrcond(), alglib.testrcondunit.testrmatrixtrrcond(), and alglib.testrcondunit.testspdmatrixrcond().
static void alglib.testrcondunit.cmatrixmakeacopy (complex a[,], int m, int n, ref complex b[,]) inline static private
Referenced by alglib.testrcondunit.cmatrixrefrcond(), alglib.testrcondunit.testcmatrixrcond(), alglib.testrcondunit.testcmatrixtrrcond(), and alglib.testrcondunit.testhpdmatrixrcond().
static void alglib.testrcondunit.cmatrixgenzero (ref complex a0[,], int n) inline static private
Referenced by alglib.testrcondunit.testcmatrixrcond(), and alglib.testrcondunit.testcmatrixtrrcond().
static bool alglib.testrcondunit.cmatrixinvmattr (ref complex a[,], int n, bool isupper, bool isunittriangular) inline static private
Referenced by alglib.testrcondunit.cmatrixinvmatlu().
static bool alglib.testrcondunit.cmatrixinvmatlu (ref complex a[,], int[] pivots, int n) inline static private
References alglib.testrcondunit.cmatrixinvmattr().
Referenced by alglib.testrcondunit.cmatrixinvmat().
static bool alglib.testrcondunit.cmatrixinvmat (ref complex a[,], int n) inline static private
References alglib.testrcondunit.cmatrixinvmatlu(), and alglib.trfac.cmatrixlu().
Referenced by alglib.testrcondunit.cmatrixrefrcond().
static void alglib.testrcondunit.cmatrixrefrcond (complex a[,], int n, ref double rc1, ref double rcinf) inline static private
References alglib.math.abscomplex(), alglib.testrcondunit.cmatrixinvmat(), and alglib.testrcondunit.cmatrixmakeacopy().
Referenced by alglib.testrcondunit.testcmatrixrcond(), alglib.testrcondunit.testcmatrixtrrcond(), and alglib.testrcondunit.testhpdmatrixrcond().
static bool alglib.testrcondunit.testrmatrixtrrcond (int maxn, int passcount) inline static private
References alglib.math.maxrealnumber, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testrcondunit.rmatrixgenzero(), alglib.testrcondunit.rmatrixmakeacopy(), alglib.testrcondunit.rmatrixrefrcond(), alglib.rcond.rmatrixtrrcond1(), and alglib.rcond.rmatrixtrrcondinf().
Referenced by alglib.testrcondunit.testrcond().
static bool alglib.testrcondunit.testcmatrixtrrcond (int maxn, int passcount) inline static private
References alglib.testrcondunit.cmatrixgenzero(), alglib.testrcondunit.cmatrixmakeacopy(), alglib.testrcondunit.cmatrixrefrcond(), alglib.rcond.cmatrixtrrcond1(), alglib.rcond.cmatrixtrrcondinf(), alglib.math.maxrealnumber, alglib.math.randominteger(), alglib.math.randomreal(), and alglib.complex.x.
Referenced by alglib.testrcondunit.testrcond().
static bool alglib.testrcondunit.testrmatrixrcond (int maxn, int passcount) inline static private
References alglib.math.maxrealnumber, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testrcondunit.rmatrixgenzero(), alglib.trfac.rmatrixlu(), alglib.rcond.rmatrixlurcond1(), alglib.rcond.rmatrixlurcondinf(), alglib.testrcondunit.rmatrixmakeacopy(), alglib.rcond.rmatrixrcond1(), alglib.rcond.rmatrixrcondinf(), alglib.testrcondunit.rmatrixrefrcond(), and alglib.matgen.rmatrixrndcond().
Referenced by alglib.testrcondunit.testrcond().
static bool alglib.testrcondunit.testspdmatrixrcond (int maxn, int passcount) inline static private
References alglib.math.maxrealnumber, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testrcondunit.rmatrixdrophalf(), alglib.testrcondunit.rmatrixmakeacopy(), alglib.testrcondunit.rmatrixrefrcond(), alglib.trfac.spdmatrixcholesky(), alglib.rcond.spdmatrixcholeskyrcond(), alglib.rcond.spdmatrixrcond(), and alglib.matgen.spdmatrixrndcond().
Referenced by alglib.testrcondunit.testrcond().
static bool alglib.testrcondunit.testcmatrixrcond (int maxn, int passcount) inline static private
References alglib.testrcondunit.cmatrixgenzero(), alglib.trfac.cmatrixlu(), alglib.rcond.cmatrixlurcond1(), alglib.rcond.cmatrixlurcondinf(), alglib.testrcondunit.cmatrixmakeacopy(), alglib.rcond.cmatrixrcond1(), alglib.rcond.cmatrixrcondinf(), alglib.testrcondunit.cmatrixrefrcond(), alglib.matgen.cmatrixrndcond(), alglib.math.maxrealnumber, alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testrcondunit.testrcond().
static bool alglib.testrcondunit.testhpdmatrixrcond (int maxn, int passcount) inline static private
References alglib.testrcondunit.cmatrixdrophalf(), alglib.testrcondunit.cmatrixmakeacopy(), alglib.testrcondunit.cmatrixrefrcond(), alglib.trfac.hpdmatrixcholesky(), alglib.rcond.hpdmatrixcholeskyrcond(), alglib.rcond.hpdmatrixrcond(), alglib.matgen.hpdmatrixrndcond(), alglib.math.maxrealnumber, alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testrcondunit.testrcond().
static bool alglib.testrcondunit.testrcond (bool silent) inline static
References alglib.testrcondunit.testcmatrixrcond(), alglib.testrcondunit.testcmatrixtrrcond(), alglib.testrcondunit.testhpdmatrixrcond(), alglib.testrcondunit.testrmatrixrcond(), alglib.testrcondunit.testrmatrixtrrcond(), and alglib.testrcondunit.testspdmatrixrcond().
static bool alglib.testrcondunit._pexec_testrcond (bool silent) inline static
References alglib.testrcondunit.testrcond().
Referenced by _Test.Main().
static void alglib.testrcondunit.rmatrixmakeacopy (double a[,], int m, int n, ref double b[,]) inline static private
static void alglib.testrcondunit.rmatrixdrophalf (ref double a[,], int n, bool droplower) inline static private
static void alglib.testrcondunit.cmatrixdrophalf (ref complex a[,], int n, bool droplower) inline static private
static void alglib.testrcondunit.rmatrixgenzero (ref double a0[,], int n) inline static private
static bool alglib.testrcondunit.rmatrixinvmattr (ref double a[,], int n, bool isupper, bool isunittriangular) inline static private
static bool alglib.testrcondunit.rmatrixinvmatlu (ref double a[,], int[] pivots, int n) inline static private
References alglib.testrcondunit.rmatrixinvmattr().
static bool alglib.testrcondunit.rmatrixinvmat (ref double a[,], int n) inline static private
References alglib.testrcondunit.rmatrixinvmatlu(), and alglib.trfac.rmatrixlu().
static void alglib.testrcondunit.rmatrixrefrcond (double a[,], int n, ref double rc1, ref double rcinf) inline static private
References alglib.testrcondunit.rmatrixinvmat(), and alglib.testrcondunit.rmatrixmakeacopy().
static void alglib.testrcondunit.cmatrixmakeacopy (complex a[,], int m, int n, ref complex b[,]) inline static private
static void alglib.testrcondunit.cmatrixgenzero (ref complex a0[,], int n) inline static private
static bool alglib.testrcondunit.cmatrixinvmattr (ref complex a[,], int n, bool isupper, bool isunittriangular) inline static private
static bool alglib.testrcondunit.cmatrixinvmatlu (ref complex a[,], int[] pivots, int n) inline static private
References alglib.testrcondunit.cmatrixinvmattr().
static bool alglib.testrcondunit.cmatrixinvmat (ref complex a[,], int n) inline static private
References alglib.testrcondunit.cmatrixinvmatlu(), and alglib.trfac.cmatrixlu().
static void alglib.testrcondunit.cmatrixrefrcond (complex a[,], int n, ref double rc1, ref double rcinf) inline static private
References alglib.math.abscomplex(), alglib.testrcondunit.cmatrixinvmat(), and alglib.testrcondunit.cmatrixmakeacopy().
static bool alglib.testrcondunit.testrmatrixtrrcond (int maxn, int passcount) inline static private
References alglib.math.maxrealnumber, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testrcondunit.rmatrixgenzero(), alglib.testrcondunit.rmatrixmakeacopy(), alglib.testrcondunit.rmatrixrefrcond(), alglib.rcond.rmatrixtrrcond1(), and alglib.rcond.rmatrixtrrcondinf().
static bool alglib.testrcondunit.testcmatrixtrrcond (int maxn, int passcount) inline static private
References alglib.testrcondunit.cmatrixgenzero(), alglib.testrcondunit.cmatrixmakeacopy(), alglib.testrcondunit.cmatrixrefrcond(), alglib.rcond.cmatrixtrrcond1(), alglib.rcond.cmatrixtrrcondinf(), alglib.math.maxrealnumber, alglib.math.randominteger(), alglib.math.randomreal(), and alglib.complex.x.
static bool alglib.testrcondunit.testrmatrixrcond (int maxn, int passcount) inline static private
References alglib.math.maxrealnumber, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testrcondunit.rmatrixgenzero(), alglib.trfac.rmatrixlu(), alglib.rcond.rmatrixlurcond1(), alglib.rcond.rmatrixlurcondinf(), alglib.testrcondunit.rmatrixmakeacopy(), alglib.rcond.rmatrixrcond1(), alglib.rcond.rmatrixrcondinf(), alglib.testrcondunit.rmatrixrefrcond(), and alglib.matgen.rmatrixrndcond().
static bool alglib.testrcondunit.testspdmatrixrcond (int maxn, int passcount) inline static private
References alglib.math.maxrealnumber, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testrcondunit.rmatrixdrophalf(), alglib.testrcondunit.rmatrixmakeacopy(), alglib.testrcondunit.rmatrixrefrcond(), alglib.trfac.spdmatrixcholesky(), alglib.rcond.spdmatrixcholeskyrcond(), alglib.rcond.spdmatrixrcond(), and alglib.matgen.spdmatrixrndcond().
static bool alglib.testrcondunit.testcmatrixrcond (int maxn, int passcount) inline static private
References alglib.testrcondunit.cmatrixgenzero(), alglib.trfac.cmatrixlu(), alglib.rcond.cmatrixlurcond1(), alglib.rcond.cmatrixlurcondinf(), alglib.testrcondunit.cmatrixmakeacopy(), alglib.rcond.cmatrixrcond1(), alglib.rcond.cmatrixrcondinf(), alglib.testrcondunit.cmatrixrefrcond(), alglib.matgen.cmatrixrndcond(), alglib.math.maxrealnumber, alglib.math.randominteger(), and alglib.math.randomreal().
static bool alglib.testrcondunit.testhpdmatrixrcond (int maxn, int passcount) inline static private
References alglib.testrcondunit.cmatrixdrophalf(), alglib.testrcondunit.cmatrixmakeacopy(), alglib.testrcondunit.cmatrixrefrcond(), alglib.trfac.hpdmatrixcholesky(), alglib.rcond.hpdmatrixcholeskyrcond(), alglib.rcond.hpdmatrixrcond(), alglib.matgen.hpdmatrixrndcond(), alglib.math.maxrealnumber, alglib.math.randominteger(), and alglib.math.randomreal().
Member Data Documentation
const double alglib.testrcondunit.threshold50 = 0.25
const double alglib.testrcondunit.threshold90 = 0.10
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs