IGLib: Meta.Numerics.Matrices.RealEigensystem Class Reference
Meta.Numerics.Matrices.RealEigensystem Class Reference
Represents a collection of real eigenvalues and eigenvectors.
Public Member Functions
double Eigenvalue (int n)
Gets a specified eigenvalue.
ColumnVector Eigenvector (int n)
Gets a specified eigenvector.
SquareMatrix TransformMatrix ()
Gets the transformation matrix that diagonalizes the original matrix.
Properties
int Dimension [get]
Gets the dimension of the eigensystem.
Private Attributes
readonly int dimension
readonly double[] eigenvalues
readonly double[] eigenvectorStorage
Detailed Description
Represents a collection of real eigenvalues and eigenvectors.
Member Function Documentation
double Meta.Numerics.Matrices.RealEigensystem.Eigenvalue (int n) inline
Gets a specified eigenvalue.
Parameters
n The (zero-based) index of the eigenvalue.
Returns
The n th eigenvalue.
Referenced by Test.SymmetricMatrixTest.SymmetricRandomMatrixEigenvectors().
ColumnVector Meta.Numerics.Matrices.RealEigensystem.Eigenvector (int n) inline
Gets a specified eigenvector.
Parameters
n The (zero-based) index of the eigenvector.
Returns
The n th eigenvector.
The returned vector is read-only. If you need to make changes to it, you can call ColumnVector.Copy to obtain a writable copy.
Referenced by Test.SymmetricMatrixTest.SymmetricRandomMatrixEigenvectors().
SquareMatrix Meta.Numerics.Matrices.RealEigensystem.TransformMatrix () inline
Gets the transformation matrix that diagonalizes the original matrix.
Returns
The orthogonal matrix V such that VTAV = D, where A is the orignal matrix and D is diagonal.
The returned matrix is read-only. If you need to make changes to it, you can call SquareMatrix.Copy to obtain a writable copy.
Referenced by Test.SymmetricMatrixTest.SymmetricRandomMatrixEigenvectors().
Member Data Documentation
readonly int Meta.Numerics.Matrices.RealEigensystem.dimension private
readonly double [] Meta.Numerics.Matrices.RealEigensystem.eigenvalues private
readonly double [] Meta.Numerics.Matrices.RealEigensystem.eigenvectorStorage private
Property Documentation
int Meta.Numerics.Matrices.RealEigensystem.Dimension get
Gets the dimension of the eigensystem.
Referenced by Test.SymmetricMatrixTest.SymmetricRandomMatrixEigenvectors().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Matrices/RealEigensystem.cs