IGLib: CShell.Modules.Workspace.ViewModels.FolderViewModel Class Reference
CShell.Modules.Workspace.ViewModels.FolderViewModel Class Reference
Public Member Functions
FolderViewModel (DirectoryInfo info, CShell.Workspace workspace)
IEnumerable< IResult > AddNewFile ()
IEnumerable< IResult > AddNewFolder ()
IEnumerable< IResult > Delete ()
IEnumerable< IResult > Rename ()
FolderViewModel (DirectoryInfo info, CShell.Workspace workspace)
IEnumerable< IResult > AddNewFile ()
IEnumerable< IResult > AddNewFolder ()
IEnumerable< IResult > Delete ()
IEnumerable< IResult > Rename ()
Static Public Member Functions
static string WildcardToRegex (string pattern)
static string WildcardToRegex (string pattern)
Protected Member Functions
FolderViewModel (string path, CShell.Workspace workspace)
BindableCollection< TreeViewModel > LoadChildren ()
override void EditModeFinished ()
FolderViewModel (string path, CShell.Workspace workspace)
BindableCollection< TreeViewModel > LoadChildren ()
override void EditModeFinished ()
Protected Attributes
DirectoryInfo directoryInfo
Properties
override Uri IconSource [get]
string RelativePath [get]
string ToolTip [get]
override IObservableCollection
< TreeViewModel > Children [get]
Properties inherited from CShell.Modules.Workspace.ViewModels.TreeViewModel
virtual string DisplayName [get, set]
Private Attributes
readonly CShell.Workspace workspace
BindableCollection< TreeViewModel > children
Constructor & Destructor Documentation
CShell.Modules.Workspace.ViewModels.FolderViewModel.FolderViewModel (string path, CShell.Workspace workspace) inline protected
CShell.Modules.Workspace.ViewModels.FolderViewModel.FolderViewModel (DirectoryInfo info, CShell.Workspace workspace) inline
CShell.Modules.Workspace.ViewModels.FolderViewModel.FolderViewModel (string path, CShell.Workspace workspace) inline protected
CShell.Modules.Workspace.ViewModels.FolderViewModel.FolderViewModel (DirectoryInfo info, CShell.Workspace workspace) inline
Member Function Documentation
BindableCollection<TreeViewModel> CShell.Modules.Workspace.ViewModels.FolderViewModel.LoadChildren () inline protected
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.FolderViewModel.AddNewFile () inline
References CShell.Constants.DefaultExtension, CShell.Framework.Results.Show.Dialog(), and CShell.Constants.FileTypes.
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.FolderViewModel.AddNewFolder () inline
References CShell.Framework.Results.Show.FolderDialog(), and CShell.Framework.Results.ShowFolderDialogResult.SelectedFolder.
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.FolderViewModel.Delete () inline
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.FolderViewModel.Rename () inline
override void CShell.Modules.Workspace.ViewModels.FolderViewModel.EditModeFinished () inline protected
static string CShell.Modules.Workspace.ViewModels.FolderViewModel.WildcardToRegex (string pattern) inline static
BindableCollection<TreeViewModel> CShell.Modules.Workspace.ViewModels.FolderViewModel.LoadChildren () inline protected
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.FolderViewModel.AddNewFile () inline
References CShell.Constants.DefaultExtension, CShell.Framework.Results.Show.Dialog(), and CShell.Constants.FileTypes.
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.FolderViewModel.AddNewFolder () inline
References CShell.Framework.Results.Show.FolderDialog(), and CShell.Framework.Results.ShowFolderDialogResult.SelectedFolder.
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.FolderViewModel.Delete () inline
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.FolderViewModel.Rename () inline
override void CShell.Modules.Workspace.ViewModels.FolderViewModel.EditModeFinished () inline protected
static string CShell.Modules.Workspace.ViewModels.FolderViewModel.WildcardToRegex (string pattern) inline static
Member Data Documentation
DirectoryInfo CShell.Modules.Workspace.ViewModels.FolderViewModel.directoryInfo protected
readonly CShell Workspace CShell.Modules.Workspace.ViewModels.FolderViewModel.workspace private
BindableCollection< TreeViewModel > CShell.Modules.Workspace.ViewModels.FolderViewModel.children private
Property Documentation
override Uri CShell.Modules.Workspace.ViewModels.FolderViewModel.IconSource get
string CShell.Modules.Workspace.ViewModels.FolderViewModel.RelativePath get
string CShell.Modules.Workspace.ViewModels.FolderViewModel.ToolTip get
override IObservableCollection< TreeViewModel > CShell.Modules.Workspace.ViewModels.FolderViewModel.Children get
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Workspace/ViewModels/FolderViewModel.cs