IGLib: IG.Sendigence.ConsoleForm Class Reference
IG.Sendigence.ConsoleForm Class Reference
Summary description for ConsoleForm.
Public Types
enum Styles {
Styles.Normal, Styles.Error, Styles.Mark, Styles.Normal,
Styles.Error, Styles.Mark
}
enum Styles {
Styles.Normal, Styles.Error, Styles.Mark, Styles.Normal,
Styles.Error, Styles.Mark
}
Public Member Functions
ConsoleForm ()
Argument-less constructor, does not launch the window in a parallel thread.
ConsoleForm (string msgtext)
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
void HideForm ()
void CloseForm ()
Closes the form by properly (i.e. thread-safe) calling the Close() and Dispose().
void Write (bool block, string str)
void Write (string str)
void WriteLine (bool block, string str)
Writes a string to the output console and appends a newline character.
void WriteLine (string str)
void Write (Char arg)
void Write (Boolean arg)
void Write (Char[] arg)
void Write (Decimal arg)
void Write (Double arg)
void Write (Int32 arg)
void Write (Int64 arg)
void Write (Object arg)
void Write (Single arg)
void Write (UInt32 arg)
void Write (UInt64 arg)
void Write (String arg, Object arg1)
void Write (String arg, Object[] arg1)
void Write (Char[] arg, Int32 arg1, Int32 arg2)
void Write (String arg, Object arg1, Object arg2)
void Write (String arg, Object arg1, Object arg2, Object arg3)
void WriteLine (Char arg)
void WriteLine (Boolean arg)
void WriteLine (Char[] arg)
void WriteLine (Decimal arg)
void WriteLine (Double arg)
void WriteLine (Int32 arg)
void WriteLine (Int64 arg)
void WriteLine (Object arg)
void WriteLine (Single arg)
void WriteLine (UInt32 arg)
void WriteLine (UInt64 arg)
void WriteLine (String arg, Object arg1)
void WriteLine (String arg, Object[] arg1)
void WriteLine (Char[] arg, Int32 arg1, Int32 arg2)
void WriteLine (String arg, Object arg1, Object arg2)
void WriteLine (String arg, Object arg1, Object arg2, Object arg3)
void ReportError (string errorstr)
ConsoleForm utility for reporting errors (not global).
void ReportError (Exception e)
Reports an error (including logging, etc., dependent on the current settings).
void ReportError (Exception e, string additional)
void HideInput ()
void ShowInput ()
string ReadLine ()
Reads a single line string from the input console and returns it.
string ReadLine (string Message)
void ReadString (ref string str)
void ReadString (ref string str, string Message)
int Read ()
Reads a single character from the input console and returns it as integer.
int Read (string Message)
double ReadDouble (ref double Value)
double ReadDouble (ref double Value, string Message)
double ReadDouble ()
Reads a floating point number from the input console and returns it.
double ReadDouble (string Message)
long ReadLong (ref long Value)
long ReadLong (ref long Value, string Message)
long ReadLong ()
Reads a floating point number from the input console and returns it.
long ReadLong (string Message)
void ShowThread ()
Shows a fading message in a new thread.
void ShowThread (string title)
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
ConsoleForm ()
Argument-less constructor, does not launch the window in a parallel thread.
ConsoleForm (string msgtext)
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
void HideForm ()
void CloseForm ()
Closes the form by properly (i.e. thread-safe) calling the Close() and Dispose().
void Write (bool block, string str)
void Write (string str)
void WriteLine (bool block, string str)
Writes a string to the output console and appends a newline character.
void WriteLine (string str)
void Write (Char arg)
void Write (Boolean arg)
void Write (Char[] arg)
void Write (Decimal arg)
void Write (Double arg)
void Write (Int32 arg)
void Write (Int64 arg)
void Write (Object arg)
void Write (Single arg)
void Write (UInt32 arg)
void Write (UInt64 arg)
void Write (String arg, Object arg1)
void Write (String arg, Object[] arg1)
void Write (Char[] arg, Int32 arg1, Int32 arg2)
void Write (String arg, Object arg1, Object arg2)
void Write (String arg, Object arg1, Object arg2, Object arg3)
void WriteLine (Char arg)
void WriteLine (Boolean arg)
void WriteLine (Char[] arg)
void WriteLine (Decimal arg)
void WriteLine (Double arg)
void WriteLine (Int32 arg)
void WriteLine (Int64 arg)
void WriteLine (Object arg)
void WriteLine (Single arg)
void WriteLine (UInt32 arg)
void WriteLine (UInt64 arg)
void WriteLine (String arg, Object arg1)
void WriteLine (String arg, Object[] arg1)
void WriteLine (Char[] arg, Int32 arg1, Int32 arg2)
void WriteLine (String arg, Object arg1, Object arg2)
void WriteLine (String arg, Object arg1, Object arg2, Object arg3)
void ReportError (string errorstr)
ConsoleForm utility for reporting errors (not global).
void ReportError (Exception e)
Reports an error (including logging, etc., dependent on the current settings).
void ReportError (Exception e, string additional)
void HideInput ()
void ShowInput ()
string ReadLine ()
Reads a single line string from the input console and returns it.
string ReadLine (string Message)
void ReadString (ref string str)
void ReadString (ref string str, string Message)
int Read ()
Reads a single character from the input console and returns it as integer.
int Read (string Message)
double ReadDouble (ref double Value)
double ReadDouble (ref double Value, string Message)
double ReadDouble ()
Reads a floating point number from the input console and returns it.
double ReadDouble (string Message)
long ReadLong (ref long Value)
long ReadLong (ref long Value, string Message)
long ReadLong ()
Reads a floating point number from the input console and returns it.
long ReadLong (string Message)
void ShowThread ()
Shows a fading message in a new thread.
void ShowThread (string title)
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
Public Attributes
bool IsClosable = true
bool WriteInput = true
If false then the form can not be closed or dispoded.
string Title = "Console"
Protected Attributes
string OutBuf =null
bool OutputStarted =false
Properties
bool IsBackground [get, set]
Color OutBackColor [get, set]
Output console background color.
Color OutForeColor [get, set]
Output console foreground color.
Color OutSelectionColor [get, set]
Output console foreground color.
Private Member Functions
void baseConsoleForm ()
Required designer variable.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void FormThreadFunc ()
Shows the window in a separate thread.
void ConsoleForm_Load (object sender, System.EventArgs args)
void ConsoleForm_Dispose (object sender, System.EventArgs e)
void ConsoleForm_FormClosing (object sender, FormClosingEventArgs e)
void CloseBtn_Click (object sender, EventArgs e)
void HideBtn_Click (object sender, EventArgs e)
void WriteOutput ()
void ReserveReportError (string errorstr)
void ReserveReportError (Exception e)
void ReserveReportError (Exception e, string additional)
void PrepareForReading ()
void FinalizeReading ()
void WaitResult ()
void RunInputConfirmationDelegate ()
void InputConfirm_Read ()
void InputConfirm_ReadDouble ()
void InputConfirm_ReadLong ()
void InputChk_CheckedChanged (object sender, EventArgs e)
void ConfirmInputBtn_Click (object sender, EventArgs e)
void InBox_PreviewKeyDown (object sender, PreviewKeyDownEventArgs e)
void InBox_KeyUp (object sender, KeyEventArgs e)
void InBox_KeyPress (object sender, KeyPressEventArgs e)
void chkWrap_CheckedChanged (object sender, EventArgs e)
void baseConsoleForm ()
Required designer variable.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void FormThreadFunc ()
Shows the window in a separate thread.
void ConsoleForm_Load (object sender, System.EventArgs args)
void ConsoleForm_Dispose (object sender, System.EventArgs e)
void ConsoleForm_FormClosing (object sender, FormClosingEventArgs e)
void CloseBtn_Click (object sender, EventArgs e)
void HideBtn_Click (object sender, EventArgs e)
void WriteOutput ()
void ReserveReportError (string errorstr)
void ReserveReportError (Exception e)
void ReserveReportError (Exception e, string additional)
void PrepareForReading ()
void FinalizeReading ()
void WaitResult ()
void RunInputConfirmationDelegate ()
void InputConfirm_Read ()
void InputConfirm_ReadDouble ()
void InputConfirm_ReadLong ()
void InputChk_CheckedChanged (object sender, EventArgs e)
void ConfirmInputBtn_Click (object sender, EventArgs e)
void InBox_PreviewKeyDown (object sender, PreviewKeyDownEventArgs e)
void InBox_KeyUp (object sender, KeyEventArgs e)
void InBox_KeyPress (object sender, KeyPressEventArgs e)
void chkWrap_CheckedChanged (object sender, EventArgs e)
Private Attributes
bool bgthread = true
If true then Input messages are repeated in the output console.
object InputLock = new object()
object OutputLock = new object()
Color OBg = Color.White
Color OFg = Color.Blue
Color OSelFg = Color.Blue
Color IBg = Color.White
Color IFg = Color.Violet
Color ILblNormalBg =Color.Gray
Color ILblNormalFg =Color.Black
Color ILblActiveBg =Color.Yellow
Color ILblActiveFg =Color.Blue
Color ILblErrorBg =Color.Red
Color ILblErrorFg =Color.Blue
System.Windows.Forms.Button HideBtn
Panel TitlePanel
Panel OutputOuterPnl
Panel ControlPanel
Label TitleLbl
RichTextBox OutBox
Label OutputLbl
Panel InputPnl
RichTextBox InBox
Label InputLbl
Label InputMsgLbl
Button ConfirmInputBtn
CheckBox InputChk
Button button1
Label StatusLbl
Thread formthread = null
bool OutputEnded =false
int RecCountWrite = 0
int RecCountError = 0
object ErrorLock = new object()
string InputResultString =null
string InputMessage =null
bool ReadStarted =false
bool ReadFinished =false
bool MultiLineInput = false
bool SingleCharacterInput = false
bool DeleteLastNewline = false
bool SelectInput =false
int KeyValue = 0
Keys KeyData = Keys.None
Keys KeyCode =Keys.None
IFormatProvider FormatProvider = System.Globalization.CultureInfo.CreateSpecificCulture("")
Detailed Description
Summary description for ConsoleForm.
Member Enumeration Documentation
enum IG.Sendigence.ConsoleForm.Styles
Handles a form that can be use as console output and input window, for logging messages, etc. Input and output window are separated. The window can be launched in a separate thread.
Enumerator
Normal
Error
Mark
Normal
Error
Mark
enum IG.Sendigence.ConsoleForm.Styles
Handles a form that can be use as console output and input window, for logging messages, etc. Input and output window are separated. The window can be launched in a separate thread.
Enumerator
Normal
Error
Mark
Normal
Error
Mark
Constructor & Destructor Documentation
IG.Sendigence.ConsoleForm.ConsoleForm () inline
Argument-less constructor, does not launch the window in a parallel thread.
IG.Sendigence.ConsoleForm.ConsoleForm (string msgtext) inline
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
IG.Sendigence.ConsoleForm.ConsoleForm () inline
Argument-less constructor, does not launch the window in a parallel thread.
IG.Sendigence.ConsoleForm.ConsoleForm (string msgtext) inline
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
Member Function Documentation
void IG.Sendigence.ConsoleForm.baseConsoleForm () inline private
Required designer variable.
void IG.Sendigence.ConsoleForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
void IG.Sendigence.ConsoleForm.FormThreadFunc () inline private
Shows the window in a separate thread.
void IG.Sendigence.ConsoleForm.ConsoleForm_Load (object sender, System.EventArgs args) inline private
void IG.Sendigence.ConsoleForm.ConsoleForm_Dispose (object sender, System.EventArgs e) inline private
void IG.Sendigence.ConsoleForm.ConsoleForm_FormClosing (object sender, FormClosingEventArgs e) inline private
void IG.Sendigence.ConsoleForm.CloseBtn_Click (object sender, EventArgs e) inline private
void IG.Sendigence.ConsoleForm.HideBtn_Click (object sender, EventArgs e) inline private
void IG.Sendigence.ConsoleForm.HideForm () inline
void IG.Sendigence.ConsoleForm.CloseForm () inline
Closes the form by properly (i.e. thread-safe) calling the Close() and Dispose().
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.WriteOutput () inline private
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.Write (bool block, string str) inline
Writes a string to the output console. If block=true, then it blocks until the string is actually written.
void IG.Sendigence.ConsoleForm.Write (string str) inline
References IG.Sendigence.ConsoleForm.Write().
Referenced by IG.Sendigence.ConsoleForm.Write().
void IG.Sendigence.ConsoleForm.WriteLine (bool block, string str) inline
Writes a string to the output console and appends a newline character.
void IG.Sendigence.ConsoleForm.WriteLine (string str) inline
References IG.Sendigence.ConsoleForm.WriteLine().
Referenced by IG.Sendigence.ConsoleForm.WriteLine().
void IG.Sendigence.ConsoleForm.Write (Char arg) inline
void IG.Sendigence.ConsoleForm.Write (Boolean arg) inline
void IG.Sendigence.ConsoleForm.Write (Char[] arg) inline
void IG.Sendigence.ConsoleForm.Write (Decimal arg) inline
void IG.Sendigence.ConsoleForm.Write (Double arg) inline
void IG.Sendigence.ConsoleForm.Write (Int32 arg) inline
void IG.Sendigence.ConsoleForm.Write (Int64 arg) inline
void IG.Sendigence.ConsoleForm.Write (Object arg) inline
void IG.Sendigence.ConsoleForm.Write (Single arg) inline
void IG.Sendigence.ConsoleForm.Write (UInt32 arg) inline
void IG.Sendigence.ConsoleForm.Write (UInt64 arg) inline
void IG.Sendigence.ConsoleForm.Write (String arg, Object arg1) inline
void IG.Sendigence.ConsoleForm.Write (String arg, Object[] arg1) inline
void IG.Sendigence.ConsoleForm.Write (Char[] arg, Int32 arg1, Int32 arg2) inline
void IG.Sendigence.ConsoleForm.Write (String arg, Object arg1, Object arg2) inline
void IG.Sendigence.ConsoleForm.Write (String arg, Object arg1, Object arg2, Object arg3) inline
void IG.Sendigence.ConsoleForm.WriteLine (Char arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Boolean arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Char[] arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Decimal arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Double arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Int32 arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Int64 arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Object arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Single arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (UInt32 arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (UInt64 arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (String arg, Object arg1) inline
void IG.Sendigence.ConsoleForm.WriteLine (String arg, Object[] arg1) inline
void IG.Sendigence.ConsoleForm.WriteLine (Char[] arg, Int32 arg1, Int32 arg2) inline
void IG.Sendigence.ConsoleForm.WriteLine (String arg, Object arg1, Object arg2) inline
void IG.Sendigence.ConsoleForm.WriteLine (String arg, Object arg1, Object arg2, Object arg3) inline
void IG.Sendigence.ConsoleForm.ReportError (string errorstr) inline
ConsoleForm utility for reporting errors (not global).
void IG.Sendigence.ConsoleForm.ReportError (Exception e) inline
Reports an error (including logging, etc., dependent on the current settings).
void IG.Sendigence.ConsoleForm.ReportError (Exception e, string additional) inline
Reports an error (including logging, etc., dependent on the current settings). An additonal string is appended to error report.
void IG.Sendigence.ConsoleForm.ReserveReportError (string errorstr) inline private
void IG.Sendigence.ConsoleForm.ReserveReportError (Exception e) inline private
void IG.Sendigence.ConsoleForm.ReserveReportError (Exception e, string additional) inline private
void IG.Sendigence.ConsoleForm.HideInput () inline
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.ShowInput () inline
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.PrepareForReading () inline private
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.FinalizeReading () inline private
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.WaitResult () inline private
void IG.Sendigence.ConsoleForm.RunInputConfirmationDelegate () inline private
void IG.Sendigence.ConsoleForm.InputConfirm_Read () inline private
string IG.Sendigence.ConsoleForm.ReadLine () inline
Reads a single line string from the input console and returns it.
string IG.Sendigence.ConsoleForm.ReadLine (string Message) inline
Reads a single line string from the input console and returns it. If Message!=Null then Message is written above the input form before reading.
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.ReadString (ref string str) inline
void IG.Sendigence.ConsoleForm.ReadString (ref string str, string Message) inline
Reads a multiple line string from the input console and returns it in OutStr. If Message!=Null then Message is written above the input form before reading.
References IG.Forms.VoidDelegate().
int IG.Sendigence.ConsoleForm.Read () inline
Reads a single character from the input console and returns it as integer.
int IG.Sendigence.ConsoleForm.Read (string Message) inline
Reads a single character from the input console and returns it as integer. If Message!=null then it is written above the input form before reading starts.
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.InputConfirm_ReadDouble () inline private
double IG.Sendigence.ConsoleForm.ReadDouble (ref double Value) inline
Reads a floating point number from the input console and returns it in Value. Initial value of the number is set to Value prior to reading.
double IG.Sendigence.ConsoleForm.ReadDouble (ref double Value, string Message) inline
Reads a floating point number from the input console and returns it in Value. If Message!=null then it is written above the input form before reading starts. Initial value of the number is set to Value prior to reading.
References IG.Forms.VoidDelegate().
double IG.Sendigence.ConsoleForm.ReadDouble () inline
Reads a floating point number from the input console and returns it.
double IG.Sendigence.ConsoleForm.ReadDouble (string Message) inline
Reads a floating point number from the input console and returns it. If Message!=null then it is written above the input form before reading starts.
void IG.Sendigence.ConsoleForm.InputConfirm_ReadLong () inline private
long IG.Sendigence.ConsoleForm.ReadLong (ref long Value) inline
Reads a floating point number from the input console and returns it in Value. Initial value of the number is set to Value prior to reading.
long IG.Sendigence.ConsoleForm.ReadLong (ref long Value, string Message) inline
Reads a floating point number from the input console and returns it in Value. If Message!=null then it is written above the input form before reading starts. Initial value of the number is set to Value prior to reading.
References IG.Forms.VoidDelegate().
long IG.Sendigence.ConsoleForm.ReadLong () inline
Reads a floating point number from the input console and returns it.
long IG.Sendigence.ConsoleForm.ReadLong (string Message) inline
Reads a floating point number from the input console and returns it. If Message!=null then it is written above the input form before reading starts.
void IG.Sendigence.ConsoleForm.ShowThread () inline
Shows a fading message in a new thread.
void IG.Sendigence.ConsoleForm.ShowThread (string title) inline
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
void IG.Sendigence.ConsoleForm.InputChk_CheckedChanged (object sender, EventArgs e) inline private
void IG.Sendigence.ConsoleForm.ConfirmInputBtn_Click (object sender, EventArgs e) inline private
void IG.Sendigence.ConsoleForm.InBox_PreviewKeyDown (object sender, PreviewKeyDownEventArgs e) inline private
void IG.Sendigence.ConsoleForm.InBox_KeyUp (object sender, KeyEventArgs e) inline private
void IG.Sendigence.ConsoleForm.InBox_KeyPress (object sender, KeyPressEventArgs e) inline private
void IG.Sendigence.ConsoleForm.chkWrap_CheckedChanged (object sender, EventArgs e) inline private
void IG.Sendigence.ConsoleForm.baseConsoleForm () inline private
Required designer variable.
void IG.Sendigence.ConsoleForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
void IG.Sendigence.ConsoleForm.FormThreadFunc () inline private
Shows the window in a separate thread.
void IG.Sendigence.ConsoleForm.ConsoleForm_Load (object sender, System.EventArgs args) inline private
void IG.Sendigence.ConsoleForm.ConsoleForm_Dispose (object sender, System.EventArgs e) inline private
void IG.Sendigence.ConsoleForm.ConsoleForm_FormClosing (object sender, FormClosingEventArgs e) inline private
void IG.Sendigence.ConsoleForm.CloseBtn_Click (object sender, EventArgs e) inline private
void IG.Sendigence.ConsoleForm.HideBtn_Click (object sender, EventArgs e) inline private
void IG.Sendigence.ConsoleForm.HideForm () inline
void IG.Sendigence.ConsoleForm.CloseForm () inline
Closes the form by properly (i.e. thread-safe) calling the Close() and Dispose().
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.WriteOutput () inline private
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.Write (bool block, string str) inline
Writes a string to the output console. If block=true, then it blocks until the string is actually written.
void IG.Sendigence.ConsoleForm.Write (string str) inline
References IG.Sendigence.ConsoleForm.Write().
Referenced by IG.Sendigence.ConsoleForm.Write().
void IG.Sendigence.ConsoleForm.WriteLine (bool block, string str) inline
Writes a string to the output console and appends a newline character.
void IG.Sendigence.ConsoleForm.WriteLine (string str) inline
References IG.Sendigence.ConsoleForm.WriteLine().
Referenced by IG.Sendigence.ConsoleForm.WriteLine().
void IG.Sendigence.ConsoleForm.Write (Char arg) inline
void IG.Sendigence.ConsoleForm.Write (Boolean arg) inline
void IG.Sendigence.ConsoleForm.Write (Char[] arg) inline
void IG.Sendigence.ConsoleForm.Write (Decimal arg) inline
void IG.Sendigence.ConsoleForm.Write (Double arg) inline
void IG.Sendigence.ConsoleForm.Write (Int32 arg) inline
void IG.Sendigence.ConsoleForm.Write (Int64 arg) inline
void IG.Sendigence.ConsoleForm.Write (Object arg) inline
void IG.Sendigence.ConsoleForm.Write (Single arg) inline
void IG.Sendigence.ConsoleForm.Write (UInt32 arg) inline
void IG.Sendigence.ConsoleForm.Write (UInt64 arg) inline
void IG.Sendigence.ConsoleForm.Write (String arg, Object arg1) inline
void IG.Sendigence.ConsoleForm.Write (String arg, Object[] arg1) inline
void IG.Sendigence.ConsoleForm.Write (Char[] arg, Int32 arg1, Int32 arg2) inline
void IG.Sendigence.ConsoleForm.Write (String arg, Object arg1, Object arg2) inline
void IG.Sendigence.ConsoleForm.Write (String arg, Object arg1, Object arg2, Object arg3) inline
void IG.Sendigence.ConsoleForm.WriteLine (Char arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Boolean arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Char[] arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Decimal arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Double arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Int32 arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Int64 arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Object arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (Single arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (UInt32 arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (UInt64 arg) inline
void IG.Sendigence.ConsoleForm.WriteLine (String arg, Object arg1) inline
void IG.Sendigence.ConsoleForm.WriteLine (String arg, Object[] arg1) inline
void IG.Sendigence.ConsoleForm.WriteLine (Char[] arg, Int32 arg1, Int32 arg2) inline
void IG.Sendigence.ConsoleForm.WriteLine (String arg, Object arg1, Object arg2) inline
void IG.Sendigence.ConsoleForm.WriteLine (String arg, Object arg1, Object arg2, Object arg3) inline
void IG.Sendigence.ConsoleForm.ReportError (string errorstr) inline
ConsoleForm utility for reporting errors (not global).
void IG.Sendigence.ConsoleForm.ReportError (Exception e) inline
Reports an error (including logging, etc., dependent on the current settings).
void IG.Sendigence.ConsoleForm.ReportError (Exception e, string additional) inline
Reports an error (including logging, etc., dependent on the current settings). An additonal string is appended to error report.
void IG.Sendigence.ConsoleForm.ReserveReportError (string errorstr) inline private
void IG.Sendigence.ConsoleForm.ReserveReportError (Exception e) inline private
void IG.Sendigence.ConsoleForm.ReserveReportError (Exception e, string additional) inline private
void IG.Sendigence.ConsoleForm.HideInput () inline
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.ShowInput () inline
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.PrepareForReading () inline private
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.FinalizeReading () inline private
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.WaitResult () inline private
void IG.Sendigence.ConsoleForm.RunInputConfirmationDelegate () inline private
void IG.Sendigence.ConsoleForm.InputConfirm_Read () inline private
string IG.Sendigence.ConsoleForm.ReadLine () inline
Reads a single line string from the input console and returns it.
string IG.Sendigence.ConsoleForm.ReadLine (string Message) inline
Reads a single line string from the input console and returns it. If Message!=Null then Message is written above the input form before reading.
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.ReadString (ref string str) inline
void IG.Sendigence.ConsoleForm.ReadString (ref string str, string Message) inline
Reads a multiple line string from the input console and returns it in OutStr. If Message!=Null then Message is written above the input form before reading.
References IG.Forms.VoidDelegate().
int IG.Sendigence.ConsoleForm.Read () inline
Reads a single character from the input console and returns it as integer.
int IG.Sendigence.ConsoleForm.Read (string Message) inline
Reads a single character from the input console and returns it as integer. If Message!=null then it is written above the input form before reading starts.
References IG.Forms.VoidDelegate().
void IG.Sendigence.ConsoleForm.InputConfirm_ReadDouble () inline private
double IG.Sendigence.ConsoleForm.ReadDouble (ref double Value) inline
Reads a floating point number from the input console and returns it in Value. Initial value of the number is set to Value prior to reading.
double IG.Sendigence.ConsoleForm.ReadDouble (ref double Value, string Message) inline
Reads a floating point number from the input console and returns it in Value. If Message!=null then it is written above the input form before reading starts. Initial value of the number is set to Value prior to reading.
References IG.Forms.VoidDelegate().
double IG.Sendigence.ConsoleForm.ReadDouble () inline
Reads a floating point number from the input console and returns it.
double IG.Sendigence.ConsoleForm.ReadDouble (string Message) inline
Reads a floating point number from the input console and returns it. If Message!=null then it is written above the input form before reading starts.
void IG.Sendigence.ConsoleForm.InputConfirm_ReadLong () inline private
long IG.Sendigence.ConsoleForm.ReadLong (ref long Value) inline
Reads a floating point number from the input console and returns it in Value. Initial value of the number is set to Value prior to reading.
long IG.Sendigence.ConsoleForm.ReadLong (ref long Value, string Message) inline
Reads a floating point number from the input console and returns it in Value. If Message!=null then it is written above the input form before reading starts. Initial value of the number is set to Value prior to reading.
References IG.Forms.VoidDelegate().
long IG.Sendigence.ConsoleForm.ReadLong () inline
Reads a floating point number from the input console and returns it.
long IG.Sendigence.ConsoleForm.ReadLong (string Message) inline
Reads a floating point number from the input console and returns it. If Message!=null then it is written above the input form before reading starts.
void IG.Sendigence.ConsoleForm.ShowThread () inline
Shows a fading message in a new thread.
void IG.Sendigence.ConsoleForm.ShowThread (string title) inline
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
void IG.Sendigence.ConsoleForm.InputChk_CheckedChanged (object sender, EventArgs e) inline private
void IG.Sendigence.ConsoleForm.ConfirmInputBtn_Click (object sender, EventArgs e) inline private
void IG.Sendigence.ConsoleForm.InBox_PreviewKeyDown (object sender, PreviewKeyDownEventArgs e) inline private
void IG.Sendigence.ConsoleForm.InBox_KeyUp (object sender, KeyEventArgs e) inline private
void IG.Sendigence.ConsoleForm.InBox_KeyPress (object sender, KeyPressEventArgs e) inline private
void IG.Sendigence.ConsoleForm.chkWrap_CheckedChanged (object sender, EventArgs e) inline private
Member Data Documentation
bool IG.Sendigence.ConsoleForm.IsClosable = true
bool IG.Sendigence.ConsoleForm.WriteInput = true
If false then the form can not be closed or dispoded.
bool IG.Sendigence.ConsoleForm.bgthread = true private
If true then Input messages are repeated in the output console.
object IG.Sendigence.ConsoleForm.InputLock = new object() private
object IG.Sendigence.ConsoleForm.OutputLock = new object() private
string IG.Sendigence.ConsoleForm.Title = "Console"
Color IG.Sendigence.ConsoleForm.OBg = Color.White private
Color IG.Sendigence.ConsoleForm.OFg = Color.Blue private
Color IG.Sendigence.ConsoleForm.OSelFg = Color.Blue private
Color IG.Sendigence.ConsoleForm.IBg = Color.White private
Color IG.Sendigence.ConsoleForm.IFg = Color.Violet private
Color IG.Sendigence.ConsoleForm.ILblNormalBg =Color.Gray private
Color IG.Sendigence.ConsoleForm.ILblNormalFg =Color.Black private
Color IG.Sendigence.ConsoleForm.ILblActiveBg =Color.Yellow private
Color IG.Sendigence.ConsoleForm.ILblActiveFg =Color.Blue private
Color IG.Sendigence.ConsoleForm.ILblErrorBg =Color.Red private
Color IG.Sendigence.ConsoleForm.ILblErrorFg =Color.Blue private
System Windows Forms Button IG.Sendigence.ConsoleForm.HideBtn private
Panel IG.Sendigence.ConsoleForm.TitlePanel private
Panel IG.Sendigence.ConsoleForm.OutputOuterPnl private
Panel IG.Sendigence.ConsoleForm.ControlPanel private
Label IG.Sendigence.ConsoleForm.TitleLbl private
RichTextBox IG.Sendigence.ConsoleForm.OutBox private
Label IG.Sendigence.ConsoleForm.OutputLbl private
Panel IG.Sendigence.ConsoleForm.InputPnl private
RichTextBox IG.Sendigence.ConsoleForm.InBox private
Label IG.Sendigence.ConsoleForm.InputLbl private
Label IG.Sendigence.ConsoleForm.InputMsgLbl private
Button IG.Sendigence.ConsoleForm.ConfirmInputBtn private
CheckBox IG.Sendigence.ConsoleForm.InputChk private
Button IG.Sendigence.ConsoleForm.button1 private
Label IG.Sendigence.ConsoleForm.StatusLbl private
Thread IG.Sendigence.ConsoleForm.formthread = null private
string IG.Sendigence.ConsoleForm.OutBuf =null protected
bool IG.Sendigence.ConsoleForm.OutputStarted =false protected
bool IG.Sendigence.ConsoleForm.OutputEnded =false private
int IG.Sendigence.ConsoleForm.RecCountWrite = 0 private
int IG.Sendigence.ConsoleForm.RecCountError = 0 private
object IG.Sendigence.ConsoleForm.ErrorLock = new object() private
string IG.Sendigence.ConsoleForm.InputResultString =null private
string IG.Sendigence.ConsoleForm.InputMessage =null private
bool IG.Sendigence.ConsoleForm.ReadStarted =false private
bool IG.Sendigence.ConsoleForm.ReadFinished =false private
bool IG.Sendigence.ConsoleForm.MultiLineInput = false private
bool IG.Sendigence.ConsoleForm.SingleCharacterInput = false private
bool IG.Sendigence.ConsoleForm.DeleteLastNewline = false private
bool IG.Sendigence.ConsoleForm.SelectInput =false private
int IG.Sendigence.ConsoleForm.KeyValue = 0 private
Keys IG.Sendigence.ConsoleForm.KeyData = Keys.None private
Keys IG.Sendigence.ConsoleForm.KeyCode =Keys.None private
IFormatProvider IG.Sendigence.ConsoleForm.FormatProvider = System.Globalization.CultureInfo.CreateSpecificCulture("") private
Property Documentation
bool IG.Sendigence.ConsoleForm.IsBackground get set
Color IG.Sendigence.ConsoleForm.OutBackColor get set
Output console background color.
Color IG.Sendigence.ConsoleForm.OutForeColor get set
Output console foreground color.
Color IG.Sendigence.ConsoleForm.OutSelectionColor get set
Output console foreground color.
The documentation for this class was generated from the following file:
igapp/copy/sendigence/form_1.cs