IGLib: alglib.testclusteringunit Class Reference
alglib.testclusteringunit Class Reference
Static Public Member Functions
static bool testclustering (bool silent)
static bool _pexec_testclustering (bool silent)
Static Private Member Functions
static bool basicahctests ()
static bool advancedahctests ()
static void kmeanssimpletest1 (int nvars, int nc, int passcount, ref bool converrors, ref bool othererrors, ref bool simpleerrors)
static void kmeansinfinitelooptest (ref bool othererrors)
static void kmeansrestartstest (ref bool converrors, ref bool restartserrors)
static double rnormal ()
static void rsphere (ref double[,] xy, int n, int i)
static double distfunc (double[] x0, double[] x1, int d, int disttype)
static bool errorsinmerges (double[,] d, int npoints, clustering.ahcreport rep, int ahcalgo)
Member Function Documentation
static bool alglib.testclusteringunit.testclustering (bool silent) inline static
References alglib.testclusteringunit.advancedahctests(), alglib.testclusteringunit.basicahctests(), alglib.testclusteringunit.kmeansinfinitelooptest(), alglib.testclusteringunit.kmeansrestartstest(), and alglib.testclusteringunit.kmeanssimpletest1().
Referenced by alglib.testclusteringunit._pexec_testclustering(), and _Test.Main().
static bool alglib.testclusteringunit._pexec_testclustering (bool silent) inline static
References alglib.testclusteringunit.testclustering().
Referenced by _Test.Main().
static bool alglib.testclusteringunit.basicahctests () inline static private
References alglib.clustering.clusterizercreate(), alglib.clustering.clusterizergetkclusters(), alglib.clustering.clusterizerrunahc(), alglib.clustering.clusterizerseparatedbycorr(), alglib.clustering.clusterizerseparatedbydist(), alglib.clustering.clusterizersetahcalgo(), alglib.clustering.clusterizersetdistances(), alglib.clustering.clusterizersetpoints(), and alglib.math.randomreal().
Referenced by alglib.testclusteringunit.testclustering().
static bool alglib.testclusteringunit.advancedahctests () inline static private
References alglib.clustering.clusterizercreate(), alglib.clustering.clusterizergetdistances(), alglib.clustering.clusterizerrunahc(), alglib.clustering.clusterizersetahcalgo(), alglib.clustering.clusterizersetdistances(), alglib.clustering.clusterizersetpoints(), alglib.testclusteringunit.distfunc(), alglib.testclusteringunit.errorsinmerges(), alglib.math.isfinite(), alglib.math.machineepsilon, alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testclusteringunit.testclustering().
static void alglib.testclusteringunit.kmeanssimpletest1 (int nvars, int nc, int passcount, ref bool converrors, ref bool othererrors, ref bool simpleerrors) inline static private
References alglib.clustering.clusterizercreate(), alglib.clustering.clusterizerrunkmeans(), alglib.clustering.clusterizersetkmeanslimits(), alglib.clustering.clusterizersetpoints(), alglib.math.maxrealnumber, alglib.math.randominteger(), and alglib.testclusteringunit.rsphere().
Referenced by alglib.testclusteringunit.testclustering().
static void alglib.testclusteringunit.kmeansinfinitelooptest (ref bool othererrors) inline static private
References alglib.clustering.clusterizercreate(), alglib.clustering.clusterizerrunkmeans(), alglib.clustering.clusterizersetkmeanslimits(), alglib.clustering.clusterizersetpoints(), alglib.math.machineepsilon, and alglib.math.randomreal().
Referenced by alglib.testclusteringunit.testclustering().
static void alglib.testclusteringunit.kmeansrestartstest (ref bool converrors, ref bool restartserrors) inline static private
References alglib.clustering.clusterizercreate(), alglib.clustering.clusterizerrunkmeans(), alglib.clustering.clusterizersetkmeanslimits(), alglib.clustering.clusterizersetpoints(), and alglib.testclusteringunit.rsphere().
Referenced by alglib.testclusteringunit.testclustering().
static double alglib.testclusteringunit.rnormal () inline static private
References alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testclusteringunit.rsphere().
static void alglib.testclusteringunit.rsphere (ref double xy[,], int n, int i) inline static private
References alglib.math.randomreal(), and alglib.testclusteringunit.rnormal().
Referenced by alglib.testclusteringunit.kmeansrestartstest(), and alglib.testclusteringunit.kmeanssimpletest1().
static double alglib.testclusteringunit.distfunc (double[] x0, double[] x1, int d, int disttype) inline static private
References alglib.ap.assert(), alglib.basestat.pearsoncorr2(), alglib.basestat.spearmancorr2(), and alglib.math.sqr().
Referenced by alglib.testclusteringunit.advancedahctests().
static bool alglib.testclusteringunit.errorsinmerges (double d[,], int npoints, clustering.ahcreport rep, int ahcalgo) inline static private
References alglib.clustering.clusterizergetkclusters(), alglib.math.machineepsilon, and alglib.math.maxrealnumber.
Referenced by alglib.testclusteringunit.advancedahctests().
The documentation for this class was generated from the following file:
igtest/numerics/alglib_0.8.2/tests/test_c.cs