IGLib: Meta.Numerics.Statistics.Distributions.PoissonDistribution Class Reference
Meta.Numerics.Statistics.Distributions.PoissonDistribution Class Reference
Represented a Poisson distribution.
Public Member Functions
PoissonDistribution (double mu)
Creates a new instance of a Poisson distribution.
override double ProbabilityMass (int k)
Returns the probability of the obtaining the given value.
Parameters
k The value.
Returns
The probability of obtaining the value.
override double LeftInclusiveProbability (int k)
Computes the probability of obtaining a value less than or equal to the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value les than or equal to k .
override double LeftExclusiveProbability (int k)
Computes the probability of obtaining a value less than the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value strictly less than k .
See also
RightExclusiveProbability
override double RightExclusiveProbability (int k)
Computes the probability of obtaining a value greater than the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value strictly greater than k .
See also
LeftExclusiveProbability
override int InverseLeftProbability (double P)
Computes the value corresponding to the given percentile.
Parameters
P The percentile.
Returns
The value.
override double Moment (int r)
Gets a raw moment of the distribution.
Parameters
r The order of the moment.
Returns
The raw moment Mr.
override double MomentAboutMean (int r)
Gets a central moment of the distribution.
Parameters
r The order of the moment.
Returns
The central moment Cr.
override double Cumulant (int r)
Computes a cumulant of the distribution.
Parameters
r The index of the cumulant to compute.
Returns
The rth cumulant of the distribution.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.DiscreteDistribution
virtual double ExpectationValue (Func< int, double > f)
Computes the expectation value of an artibrary function.
virtual int GetRandomValue (Random rng)
Produces a random integer drawn from the distribution.
Properties
override int Minimum [get]
override int Maximum [get]
override double Mean [get]
override double Variance [get]
override double Skewness [get]
override double ExcessKurtosis [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.DiscreteDistribution
abstract int Minimum [get]
Gets the smallest value in the distribution.
abstract int Maximum [get]
Gets the largest value in the distribution.
override double Mean [get]
Gets the mean of the distribution.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Private Member Functions
void ComputePoissonRawMoments (double[] M)
void ComputePoissonCentralMoments (double[] C)
Private Attributes
readonly double mu
Detailed Description
Represented a Poisson distribution.
Constructor & Destructor Documentation
Meta.Numerics.Statistics.Distributions.PoissonDistribution.PoissonDistribution (double mu) inline
Creates a new instance of a Poisson distribution.
Parameters
mu The mean, which must be positive.
Member Function Documentation
override double Meta.Numerics.Statistics.Distributions.PoissonDistribution.ProbabilityMass (int k) inline virtual
Returns the probability of the obtaining the given value.
Parameters
k The value.
Returns
The probability of obtaining the value.
Implements Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
References Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.Functions.AdvancedIntegerMath.LogFactorial(), and Meta.Numerics.MoreMath.Pow().
override double Meta.Numerics.Statistics.Distributions.PoissonDistribution.LeftInclusiveProbability (int k) inline virtual
Computes the probability of obtaining a value less than or equal to the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value les than or equal to k .
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
References Meta.Numerics.Functions.AdvancedMath.RightRegularizedGamma().
override double Meta.Numerics.Statistics.Distributions.PoissonDistribution.LeftExclusiveProbability (int k) inline virtual
Computes the probability of obtaining a value less than the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value strictly less than k .
See also
RightExclusiveProbability
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
override double Meta.Numerics.Statistics.Distributions.PoissonDistribution.RightExclusiveProbability (int k) inline virtual
Computes the probability of obtaining a value greater than the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value strictly greater than k .
See also
LeftExclusiveProbability
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
References Meta.Numerics.Functions.AdvancedMath.LeftRegularizedGamma().
override int Meta.Numerics.Statistics.Distributions.PoissonDistribution.InverseLeftProbability (double P) inline virtual
Computes the value corresponding to the given percentile.
Parameters
P The percentile.
Returns
The value.
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
Referenced by Test.DiscreteDistributionTest.PoissonBug().
override double Meta.Numerics.Statistics.Distributions.PoissonDistribution.Moment (int r) inline virtual
Gets a raw moment of the distribution.
Parameters
r The order of the moment.
Returns
The raw moment Mr.
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
override double Meta.Numerics.Statistics.Distributions.PoissonDistribution.MomentAboutMean (int r) inline virtual
Gets a central moment of the distribution.
Parameters
r The order of the moment.
Returns
The central moment Cr.
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
void Meta.Numerics.Statistics.Distributions.PoissonDistribution.ComputePoissonRawMoments (double[] M) inline private
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficients().
void Meta.Numerics.Statistics.Distributions.PoissonDistribution.ComputePoissonCentralMoments (double[] C) inline private
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficients().
override double Meta.Numerics.Statistics.Distributions.PoissonDistribution.Cumulant (int r) inline virtual
Computes a cumulant of the distribution.
Parameters
r The index of the cumulant to compute.
Returns
The rth cumulant of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.UnivariateDistribution.
Member Data Documentation
readonly double Meta.Numerics.Statistics.Distributions.PoissonDistribution.mu private
Property Documentation
override int Meta.Numerics.Statistics.Distributions.PoissonDistribution.Minimum get
override int Meta.Numerics.Statistics.Distributions.PoissonDistribution.Maximum get
override double Meta.Numerics.Statistics.Distributions.PoissonDistribution.Mean get
override double Meta.Numerics.Statistics.Distributions.PoissonDistribution.Variance get
override double Meta.Numerics.Statistics.Distributions.PoissonDistribution.Skewness get
override double Meta.Numerics.Statistics.Distributions.PoissonDistribution.ExcessKurtosis get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/PoissonDistribution.cs