IGLib: alglib.linmin Class Reference
alglib.linmin Class Reference
Classes
class armijostate
class linminstate
Static Public Member Functions
static void linminnormalized (ref double[] d, ref double stp, int n)
static void mcsrch (int n, ref double[] x, ref double f, ref double[] g, double[] s, ref double stp, double stpmax, double gtol, ref int info, ref int nfev, ref double[] wa, linminstate state, ref int stage)
static void armijocreate (int n, double[] x, double f, double[] s, double stp, double stpmax, int fmax, armijostate state)
static bool armijoiteration (armijostate state)
static void armijoresults (armijostate state, ref int info, ref double stp, ref double f)
static void linminnormalized (ref double[] d, ref double stp, int n)
static void mcsrch (int n, ref double[] x, ref double f, ref double[] g, double[] s, ref double stp, double stpmax, double gtol, ref int info, ref int nfev, ref double[] wa, linminstate state, ref int stage)
static void armijocreate (int n, double[] x, double f, double[] s, double stp, double stpmax, int fmax, armijostate state)
static bool armijoiteration (armijostate state)
static void armijoresults (armijostate state, ref int info, ref double stp, ref double f)
Public Attributes
const double ftol = 0.001
const double xtol = 100*math.machineepsilon
const int maxfev = 20
const double stpmin = 1.0E-50
const double defstpmax = 1.0E+50
const double armijofactor = 1.3
Static Private Member Functions
static void mcstep (ref double stx, ref double fx, ref double dx, ref double sty, ref double fy, ref double dy, ref double stp, double fp, double dp, ref bool brackt, double stmin, double stmax, ref int info)
static void mcstep (ref double stx, ref double fx, ref double dx, ref double sty, ref double fy, ref double dy, ref double stp, double fp, double dp, ref bool brackt, double stmin, double stmax, ref int info)
Member Function Documentation
static void alglib.linmin.linminnormalized (ref double[] d, ref double stp, int n) inline static
Referenced by alglib.mincg.mincgiteration(), and alglib.nleq.nleqiteration().
static void alglib.linmin.mcsrch (int n, ref double[] x, ref double f, ref double[] g, double[] s, ref double stp, double stpmax, double gtol, ref int info, ref int nfev, ref double[] wa, linminstate state, ref int stage) inline static
References alglib.linmin.linminstate.brackt, alglib.linmin.defstpmax, alglib.linmin.linminstate.dg, alglib.linmin.linminstate.dginit, alglib.linmin.linminstate.dgm, alglib.linmin.linminstate.dgtest, alglib.linmin.linminstate.dgx, alglib.linmin.linminstate.dgxm, alglib.linmin.linminstate.dgy, alglib.linmin.linminstate.dgym, alglib.linmin.linminstate.finit, alglib.linmin.linminstate.fm, alglib.linmin.linminstate.ftest1, alglib.linmin.linminstate.fx, alglib.linmin.linminstate.fxm, alglib.linmin.linminstate.fy, alglib.linmin.linminstate.fym, alglib.linmin.linminstate.infoc, alglib.linmin.mcstep(), alglib.linmin.linminstate.stage1, alglib.linmin.linminstate.stmax, alglib.linmin.linminstate.stmin, alglib.linmin.stpmin, alglib.linmin.linminstate.stx, alglib.linmin.linminstate.sty, alglib.linmin.linminstate.width, alglib.linmin.linminstate.width1, and alglib.linmin.linminstate.xtrapf.
Referenced by alglib.mincg.mincgiteration().
static void alglib.linmin.armijocreate (int n, double[] x, double f, double[] s, double stp, double stpmax, int fmax, armijostate state) inline static
References alglib.linmin.armijostate.fcur, alglib.linmin.armijostate.fmax, alglib.rcommstate.ia, alglib.linmin.armijostate.n, alglib.rcommstate.ra, alglib.linmin.armijostate.rstate, alglib.linmin.armijostate.s, alglib.rcommstate.stage, alglib.linmin.armijostate.stplen, alglib.linmin.armijostate.stpmax, alglib.linmin.armijostate.x, and alglib.linmin.armijostate.xbase.
static bool alglib.linmin.armijoiteration (armijostate state) inline static
References alglib.linmin.armijofactor, alglib.linmin.armijostate.f, alglib.linmin.armijostate.fcur, alglib.linmin.armijostate.fmax, alglib.rcommstate.ia, alglib.linmin.armijostate.info, alglib.linmin.armijostate.n, alglib.linmin.armijostate.needf, alglib.linmin.armijostate.nfev, alglib.rcommstate.ra, alglib.linmin.armijostate.rstate, alglib.linmin.armijostate.s, alglib.rcommstate.stage, alglib.linmin.armijostate.stplen, alglib.linmin.armijostate.stpmax, alglib.linmin.armijostate.x, and alglib.linmin.armijostate.xbase.
static void alglib.linmin.armijoresults (armijostate state, ref int info, ref double stp, ref double f) inline static
References alglib.linmin.armijostate.fcur, alglib.linmin.armijostate.info, and alglib.linmin.armijostate.stplen.
static void alglib.linmin.mcstep (ref double stx, ref double fx, ref double dx, ref double sty, ref double fy, ref double dy, ref double stp, double fp, double dp, ref bool brackt, double stmin, double stmax, ref int info) inline static private
References alglib.math.sqr().
Referenced by alglib.linmin.mcsrch().
static void alglib.linmin.linminnormalized (ref double[] d, ref double stp, int n) inline static
static void alglib.linmin.mcsrch (int n, ref double[] x, ref double f, ref double[] g, double[] s, ref double stp, double stpmax, double gtol, ref int info, ref int nfev, ref double[] wa, linminstate state, ref int stage) inline static
References alglib.linmin.defstpmax, alglib.linmin.mcstep(), and alglib.linmin.stpmin.
static void alglib.linmin.armijocreate (int n, double[] x, double f, double[] s, double stp, double stpmax, int fmax, armijostate state) inline static
static bool alglib.linmin.armijoiteration (armijostate state) inline static
References alglib.linmin.armijofactor.
static void alglib.linmin.armijoresults (armijostate state, ref int info, ref double stp, ref double f) inline static
static void alglib.linmin.mcstep (ref double stx, ref double fx, ref double dx, ref double sty, ref double fy, ref double dy, ref double stp, double fp, double dp, ref bool brackt, double stmin, double stmax, ref int info) inline static private
References alglib.math.sqr().
Member Data Documentation
const double alglib.linmin.ftol = 0.001
const double alglib.linmin.xtol = 100*math.machineepsilon
const int alglib.linmin.maxfev = 20
const double alglib.linmin.stpmin = 1.0E-50
Referenced by alglib.linmin.mcsrch().
const double alglib.linmin.defstpmax = 1.0E+50
Referenced by alglib.linmin.mcsrch().
const double alglib.linmin.armijofactor = 1.3
Referenced by alglib.linmin.armijoiteration().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/alglibinternal.cs