IGLib: CShell.Framework.Results.Show Class Reference
CShell.Framework.Results.Show Class Reference
Static Public Member Functions
static ShowDialogResult Dialog (object dialogViewModel, IDictionary< string, object > setting=null)
static ShowDialogResult Dialog< TViewModel > (IDictionary< string, object > setting=null)
static ShowCommonDialogResult Dialog (CommonDialog commonDialog)
static ShowFolderDialogResult FolderDialog (string selectedFolder=null)
static ShowToolResult< TTool > Tool< TTool > ()
static ShowToolResult< TTool > Tool< TTool > (TTool tool)
static OpenDocumentResult Document (IDocument document)
static OpenDocumentResult Document (string path)
static OpenDocumentResult Document< T > ()
static ShowDialogResult Dialog (object dialogViewModel, IDictionary< string, object > setting=null)
static ShowDialogResult Dialog< TViewModel > (IDictionary< string, object > setting=null)
static ShowCommonDialogResult Dialog (CommonDialog commonDialog)
static ShowFolderDialogResult FolderDialog (string selectedFolder=null)
static ShowToolResult< TTool > Tool< TTool > ()
static ShowToolResult< TTool > Tool< TTool > (TTool tool)
static OpenDocumentResult Document (IDocument document)
static OpenDocumentResult Document (string path)
static OpenDocumentResult Document< T > ()
Member Function Documentation
static ShowDialogResult CShell.Framework.Results.Show.Dialog (object dialogViewModel, IDictionary< string, object > setting = null) inline static
Referenced by CShell.Modules.Help.Module.About(), CShell.Modules.Workspace.ViewModels.FolderViewModel.AddNewFile(), CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AddReferenceFromFile(), CShell.Modules.Workspace.Module.AddReferenceFromFile(), CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AddReferenceFromGac(), CShell.Modules.Workspace.Module.AddReferenceFromGac(), CShell.Modules.Workspace.ViewModels.RootFolderViewModel.ChangeRootFolder(), CShell.Modules.Shell.Module.NewFile(), CShell.Modules.Shell.Module.NewWorkspace(), CShell.Modules.Shell.ViewModels.MainMenuViewModel.OpenFile(), CShell.Modules.Shell.Module.OpenFile(), CShell.Modules.Shell.Module.OpenWorkspace(), and CShell.Modules.Shell.Module.SaveAs().
static ShowDialogResult CShell.Framework.Results.Show.Dialog< TViewModel > (IDictionary< string, object > setting = null) inline static
static ShowCommonDialogResult CShell.Framework.Results.Show.Dialog (CommonDialog commonDialog) inline static
static ShowFolderDialogResult CShell.Framework.Results.Show.FolderDialog (string selectedFolder = null) inline static
Referenced by CShell.Modules.Workspace.ViewModels.FolderViewModel.AddNewFolder(), and CShell.Modules.Workspace.ViewModels.RootFolderSettingsViewModel.Browse().
static ShowToolResult<TTool> CShell.Framework.Results.Show.Tool< TTool > () inline static
Type Constraints
TTool : ITool
static ShowToolResult<TTool> CShell.Framework.Results.Show.Tool< TTool > (TTool tool) inline static
Type Constraints
TTool : ITool
static OpenDocumentResult CShell.Framework.Results.Show.Document (IDocument document) inline static
Referenced by CShell.Modules.Shell.Module.NewFile(), CShell.Shell.Open(), CShell.Modules.Shell.ViewModels.MainMenuViewModel.OpenFile(), and CShell.Modules.Shell.Module.OpenFile().
static OpenDocumentResult CShell.Framework.Results.Show.Document (string path) inline static
static OpenDocumentResult CShell.Framework.Results.Show.Document< T > () inline static
Type Constraints
T : IDocument
static ShowDialogResult CShell.Framework.Results.Show.Dialog (object dialogViewModel, IDictionary< string, object > setting = null) inline static
static ShowDialogResult CShell.Framework.Results.Show.Dialog< TViewModel > (IDictionary< string, object > setting = null) inline static
static ShowCommonDialogResult CShell.Framework.Results.Show.Dialog (CommonDialog commonDialog) inline static
static ShowFolderDialogResult CShell.Framework.Results.Show.FolderDialog (string selectedFolder = null) inline static
static ShowToolResult<TTool> CShell.Framework.Results.Show.Tool< TTool > () inline static
Type Constraints
TTool : ITool
static ShowToolResult<TTool> CShell.Framework.Results.Show.Tool< TTool > (TTool tool) inline static
Type Constraints
TTool : ITool
static OpenDocumentResult CShell.Framework.Results.Show.Document (IDocument document) inline static
static OpenDocumentResult CShell.Framework.Results.Show.Document (string path) inline static
static OpenDocumentResult CShell.Framework.Results.Show.Document< T > () inline static
Type Constraints
T : IDocument
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Results/Show.cs