IGLib: NUnit.Framework.Assert Class Reference
NUnit.Framework.Assert Class Reference
The Assert class contains a collection of static methods that implement the most common assertions used in NUnit.
Static Public Member Functions
static void Greater (int arg1, int arg2, string message, params object[] args)
Verifies that the first int is greater than the second int. If it is not, then an AssertionException is thrown.
static void Greater (int arg1, int arg2)
Verifies that the first int is greater than the second int. If it is not, then an AssertionException is thrown.
static void Greater (uint arg1, uint arg2, string message, params object[] args)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Greater (uint arg1, uint arg2)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Greater (long arg1, long arg2, string message, params object[] args)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Greater (long arg1, long arg2)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Greater (ulong arg1, ulong arg2, string message, params object[] args)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Greater (ulong arg1, ulong arg2)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Greater (decimal arg1, decimal arg2, string message, params object[] args)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Greater (decimal arg1, decimal arg2)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Greater (double arg1, double arg2, string message, params object[] args)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Greater (double arg1, double arg2)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Greater (float arg1, float arg2, string message, params object[] args)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Greater (float arg1, float arg2)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Greater (IComparable arg1, IComparable arg2, string message, params object[] args)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Greater (IComparable arg1, IComparable arg2)
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
static void Less (int arg1, int arg2, string message, params object[] args)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (int arg1, int arg2)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (uint arg1, uint arg2, string message, params object[] args)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (uint arg1, uint arg2)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (long arg1, long arg2, string message, params object[] args)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (long arg1, long arg2)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (ulong arg1, ulong arg2, string message, params object[] args)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (ulong arg1, ulong arg2)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (decimal arg1, decimal arg2, string message, params object[] args)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (decimal arg1, decimal arg2)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (double arg1, double arg2, string message, params object[] args)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (double arg1, double arg2)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (float arg1, float arg2, string message, params object[] args)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (float arg1, float arg2)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (IComparable arg1, IComparable arg2, string message, params object[] args)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void Less (IComparable arg1, IComparable arg2)
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (int arg1, int arg2, string message, params object[] args)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (int arg1, int arg2)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (uint arg1, uint arg2, string message, params object[] args)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (uint arg1, uint arg2)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (long arg1, long arg2, string message, params object[] args)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (long arg1, long arg2)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (ulong arg1, ulong arg2, string message, params object[] args)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (ulong arg1, ulong arg2)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (decimal arg1, decimal arg2, string message, params object[] args)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (decimal arg1, decimal arg2)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (double arg1, double arg2, string message, params object[] args)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (double arg1, double arg2)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (float arg1, float arg2, string message, params object[] args)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (float arg1, float arg2)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (IComparable arg1, IComparable arg2, string message, params object[] args)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void GreaterOrEqual (IComparable arg1, IComparable arg2)
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (int arg1, int arg2, string message, params object[] args)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (int arg1, int arg2)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (uint arg1, uint arg2, string message, params object[] args)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (uint arg1, uint arg2)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (long arg1, long arg2, string message, params object[] args)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (long arg1, long arg2)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (ulong arg1, ulong arg2, string message, params object[] args)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (ulong arg1, ulong arg2)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (decimal arg1, decimal arg2, string message, params object[] args)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (decimal arg1, decimal arg2)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (double arg1, double arg2, string message, params object[] args)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (double arg1, double arg2)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (float arg1, float arg2, string message, params object[] args)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (float arg1, float arg2)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (IComparable arg1, IComparable arg2, string message, params object[] args)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void LessOrEqual (IComparable arg1, IComparable arg2)
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
static void True (bool?condition, string message, params object[] args)
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
static void True (bool condition, string message, params object[] args)
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
static void True (bool?condition)
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
static void True (bool condition)
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
static void IsTrue (bool?condition, string message, params object[] args)
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
static void IsTrue (bool condition, string message, params object[] args)
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
static void IsTrue (bool?condition)
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
static void IsTrue (bool condition)
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
static void False (bool?condition, string message, params object[] args)
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
static void False (bool condition, string message, params object[] args)
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
static void False (bool?condition)
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
static void False (bool condition)
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
static void IsFalse (bool?condition, string message, params object[] args)
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
static void IsFalse (bool condition, string message, params object[] args)
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
static void IsFalse (bool?condition)
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
static void IsFalse (bool condition)
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
static void NotNull (object anObject, string message, params object[] args)
Verifies that the object that is passed in is not equal to
static void NotNull (object anObject)
Verifies that the object that is passed in is not equal to
static void IsNotNull (object anObject, string message, params object[] args)
Verifies that the object that is passed in is not equal to
static void IsNotNull (object anObject)
Verifies that the object that is passed in is not equal to
static void Null (object anObject, string message, params object[] args)
Verifies that the object that is passed in is equal to
static void Null (object anObject)
Verifies that the object that is passed in is equal to
static void IsNull (object anObject, string message, params object[] args)
Verifies that the object that is passed in is equal to
static void IsNull (object anObject)
Verifies that the object that is passed in is equal to
static void IsNaN (double aDouble, string message, params object[] args)
Verifies that the double that is passed in is an
static void IsNaN (double aDouble)
Verifies that the double that is passed in is an
static void IsNaN (double?aDouble, string message, params object[] args)
Verifies that the double that is passed in is an
static void IsNaN (double?aDouble)
Verifies that the double that is passed in is an
static void IsEmpty (string aString, string message, params object[] args)
Assert that a string is empty - that is equal to string.Empty
static void IsEmpty (string aString)
Assert that a string is empty - that is equal to string.Empty
static void IsEmpty (IEnumerable collection, string message, params object[] args)
Assert that an array, list or other collection is empty
static void IsEmpty (IEnumerable collection)
Assert that an array, list or other collection is empty
static void IsNotEmpty (string aString, string message, params object[] args)
Assert that a string is not empty - that is not equal to string.Empty
static void IsNotEmpty (string aString)
Assert that a string is not empty - that is not equal to string.Empty
static void IsNotEmpty (IEnumerable collection, string message, params object[] args)
Assert that an array, list or other collection is not empty
static void IsNotEmpty (IEnumerable collection)
Assert that an array, list or other collection is not empty
static new bool Equals (object a, object b)
The Equals method throws an AssertionException. This is done to make sure there is no mistake by calling this function.
static new void ReferenceEquals (object a, object b)
override the default ReferenceEquals to throw an AssertionException. This implementation makes sure there is no mistake in calling this function as part of Assert.
static void Pass (string message, params object[] args)
Throws a SuccessException with the message and arguments that are passed in. This allows a test to be cut short, with a result of success returned to NUnit.
static void Pass (string message)
Throws a SuccessException with the message and arguments that are passed in. This allows a test to be cut short, with a result of success returned to NUnit.
static void Pass ()
Throws a SuccessException with the message and arguments that are passed in. This allows a test to be cut short, with a result of success returned to NUnit.
static void Fail (string message, params object[] args)
Throws an AssertionException with the message and arguments that are passed in. This is used by the other Assert functions.
static void Fail (string message)
Throws an AssertionException with the message that is passed in. This is used by the other Assert functions.
static void Fail ()
Throws an AssertionException. This is used by the other Assert functions.
static void Ignore (string message, params object[] args)
Throws an IgnoreException with the message and arguments that are passed in. This causes the test to be reported as ignored.
static void Ignore (string message)
Throws an IgnoreException with the message that is passed in. This causes the test to be reported as ignored.
static void Ignore ()
Throws an IgnoreException. This causes the test to be reported as ignored.
static void Inconclusive (string message, params object[] args)
Throws an InconclusiveException with the message and arguments that are passed in. This causes the test to be reported as inconclusive.
static void Inconclusive (string message)
Throws an InconclusiveException with the message that is passed in. This causes the test to be reported as inconclusive.
static void Inconclusive ()
Throws an InconclusiveException. This causes the test to be reported as Inconclusive.
static void Contains (object expected, ICollection actual, string message, params object[] args)
Asserts that an object is contained in a list.
static void Contains (object expected, ICollection actual)
Asserts that an object is contained in a list.
static void AreEqual (double expected, double actual, double delta, string message, params object[] args)
Verifies that two doubles are equal considering a delta. If the expected value is infinity then the delta value is ignored. If they are not equal then an AssertionException is thrown.
static void AreEqual (double expected, double actual, double delta)
Verifies that two doubles are equal considering a delta. If the expected value is infinity then the delta value is ignored. If they are not equal then an AssertionException is thrown.
static void AreEqual (double expected, double?actual, double delta, string message, params object[] args)
Verifies that two doubles are equal considering a delta. If the expected value is infinity then the delta value is ignored. If they are not equal then an AssertionException is thrown.
static void AreEqual (double expected, double?actual, double delta)
Verifies that two doubles are equal considering a delta. If the expected value is infinity then the delta value is ignored. If they are not equal then an AssertionException is thrown.
static void AreEqual (object expected, object actual, string message, params object[] args)
Verifies that two objects are equal. Two objects are considered equal if both are null, or if both have the same value. NUnit has special semantics for some object types. If they are not equal an AssertionException is thrown.
static void AreEqual (object expected, object actual)
Verifies that two objects are equal. Two objects are considered equal if both are null, or if both have the same value. NUnit has special semantics for some object types. If they are not equal an AssertionException is thrown.
static void AreNotEqual (object expected, object actual, string message, params object[] args)
Verifies that two objects are not equal. Two objects are considered equal if both are null, or if both have the same value. NUnit has special semantics for some object types. If they are equal an AssertionException is thrown.
static void AreNotEqual (object expected, object actual)
Verifies that two objects are not equal. Two objects are considered equal if both are null, or if both have the same value. NUnit has special semantics for some object types. If they are equal an AssertionException is thrown.
static void AreSame (object expected, object actual, string message, params object[] args)
Asserts that two objects refer to the same object. If they are not the same an AssertionException is thrown.
static void AreSame (object expected, object actual)
Asserts that two objects refer to the same object. If they are not the same an AssertionException is thrown.
static void AreNotSame (object expected, object actual, string message, params object[] args)
Asserts that two objects do not refer to the same object. If they are the same an AssertionException is thrown.
static void AreNotSame (object expected, object actual)
Asserts that two objects do not refer to the same object. If they are the same an AssertionException is thrown.
static Exception Throws (IResolveConstraint expression, TestDelegate code, string message, params object[] args)
Verifies that a delegate throws a particular exception when called.
static Exception Throws (IResolveConstraint expression, TestDelegate code)
Verifies that a delegate throws a particular exception when called.
static Exception Throws (Type expectedExceptionType, TestDelegate code, string message, params object[] args)
Verifies that a delegate throws a particular exception when called.
static Exception Throws (Type expectedExceptionType, TestDelegate code)
Verifies that a delegate throws a particular exception when called.
static TActual Throws< TActual > (TestDelegate code, string message, params object[] args)
Verifies that a delegate throws a particular exception when called.
static TActual Throws< TActual > (TestDelegate code)
Verifies that a delegate throws a particular exception when called.
static Exception Catch (TestDelegate code, string message, params object[] args)
Verifies that a delegate throws an exception when called and returns it.
static Exception Catch (TestDelegate code)
Verifies that a delegate throws an exception when called and returns it.
static Exception Catch (Type expectedExceptionType, TestDelegate code, string message, params object[] args)
Verifies that a delegate throws an exception of a certain Type or one derived from it when called and returns it.
static Exception Catch (Type expectedExceptionType, TestDelegate code)
Verifies that a delegate throws an exception of a certain Type or one derived from it when called and returns it.
static TActual Catch< TActual > (TestDelegate code, string message, params object[] args)
Verifies that a delegate throws an exception of a certain Type or one derived from it when called and returns it.
static TActual Catch< TActual > (TestDelegate code)
Verifies that a delegate throws an exception of a certain Type or one derived from it when called and returns it.
static void DoesNotThrow (TestDelegate code, string message, params object[] args)
Verifies that a delegate does not throw an exception
static void DoesNotThrow (TestDelegate code)
Verifies that a delegate does not throw an exception.
static void That (bool condition, string message, params object[] args)
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
static void That (bool condition)
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
static void That (Func< bool > condition, string message, params object[] args)
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
static void That (Func< bool > condition)
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
static void That< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
static void That< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr, string message, params object[] args)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
static void That (TestDelegate code, IResolveConstraint constraint)
Asserts that the code represented by a delegate throws an exception that satisfies the constraint provided.
static void That (TestDelegate code, IResolveConstraint constraint, string message, params string[] args)
Asserts that the code represented by a delegate throws an exception that satisfies the constraint provided.
static void That< TActual > (TActual actual, IResolveConstraint expression)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
static void That< TActual > (TActual actual, IResolveConstraint expression, string message, params object[] args)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
static void ByVal (object actual, IResolveConstraint expression)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure. Used as a synonym for That in rare cases where a private setter causes a Visual Basic compilation error.
static void ByVal (object actual, IResolveConstraint expression, string message, params object[] args)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure. Used as a synonym for That in rare cases where a private setter causes a Visual Basic compilation error.
static void IsAssignableFrom (Type expected, object actual, string message, params object[] args)
Asserts that an object may be assigned a value of a given Type.
static void IsAssignableFrom (Type expected, object actual)
Asserts that an object may be assigned a value of a given Type.
static void IsAssignableFrom< TExpected > (object actual, string message, params object[] args)
Asserts that an object may be assigned a value of a given Type.
static void IsAssignableFrom< TExpected > (object actual)
Asserts that an object may be assigned a value of a given Type.
static void IsNotAssignableFrom (Type expected, object actual, string message, params object[] args)
Asserts that an object may not be assigned a value of a given Type.
static void IsNotAssignableFrom (Type expected, object actual)
Asserts that an object may not be assigned a value of a given Type.
static void IsNotAssignableFrom< TExpected > (object actual, string message, params object[] args)
Asserts that an object may not be assigned a value of a given Type.
static void IsNotAssignableFrom< TExpected > (object actual)
Asserts that an object may not be assigned a value of a given Type.
static void IsInstanceOf (Type expected, object actual, string message, params object[] args)
Asserts that an object is an instance of a given type.
static void IsInstanceOf (Type expected, object actual)
Asserts that an object is an instance of a given type.
static void IsInstanceOf< TExpected > (object actual, string message, params object[] args)
Asserts that an object is an instance of a given type.
static void IsInstanceOf< TExpected > (object actual)
Asserts that an object is an instance of a given type.
static void IsNotInstanceOf (Type expected, object actual, string message, params object[] args)
Asserts that an object is not an instance of a given type.
static void IsNotInstanceOf (Type expected, object actual)
Asserts that an object is not an instance of a given type.
static void IsNotInstanceOf< TExpected > (object actual, string message, params object[] args)
Asserts that an object is not an instance of a given type.
static void IsNotInstanceOf< TExpected > (object actual)
Asserts that an object is not an instance of a given type.
Protected Member Functions
Assert ()
We don't actually want any instances of this object, but some people like to inherit from it to add other static methods. Hence, the protected constructor disallows any instances of this object.
Static Protected Member Functions
static void AssertDoublesAreEqual (double expected, double actual, double delta, string message, object[] args)
Helper for Assert.AreEqual(double expected, double actual, ...) allowing code generation to work consistently.
Static Private Member Functions
static void IncrementAssertCount ()
Detailed Description
The Assert class contains a collection of static methods that implement the most common assertions used in NUnit.
Constructor & Destructor Documentation
NUnit.Framework.Assert.Assert () inline protected
We don't actually want any instances of this object, but some people like to inherit from it to add other static methods. Hence, the protected constructor disallows any instances of this object.
Member Function Documentation
static void NUnit.Framework.Assert.Greater (int arg1, int arg2, string message, params object[] args) inline static
Verifies that the first int is greater than the second int. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), NUnit.Framework.Assertions.GreaterFixture.FailureMessage(), NUnit.Framework.Assertions.GreaterFixture.Greater(), NUnit.Framework.Assertions.GreaterFixture.MixedTypes(), NUnit.Framework.Assertions.GreaterFixture.NotGreater(), NUnit.Framework.Assertions.GreaterFixture.NotGreaterIComparable(), and NUnit.Framework.Assertions.GreaterFixture.NotGreaterWhenEqual().
static void NUnit.Framework.Assert.Greater (int arg1, int arg2) inline static
Verifies that the first int is greater than the second int. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (uint arg1, uint arg2, string message, params object[] args) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (uint arg1, uint arg2) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (long arg1, long arg2, string message, params object[] args) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (long arg1, long arg2) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (ulong arg1, ulong arg2, string message, params object[] args) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (ulong arg1, ulong arg2) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (decimal arg1, decimal arg2, string message, params object[] args) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (decimal arg1, decimal arg2) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (double arg1, double arg2, string message, params object[] args) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (double arg1, double arg2) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (float arg1, float arg2, string message, params object[] args) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (float arg1, float arg2) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (IComparable arg1, IComparable arg2, string message, params object[] args) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Greater (IComparable arg1, IComparable arg2) inline static
Verifies that the first value is greater than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (int arg1, int arg2, string message, params object[] args) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), NUnit.Framework.Assertions.LessFixture.FailureMessage(), NUnit.Framework.Assertions.LessFixture.Less(), NUnit.Framework.Assertions.LessFixture.MixedTypes(), NUnit.Framework.Assertions.LessFixture.NotLess(), NUnit.Framework.Assertions.LessFixture.NotLessIComparable(), and NUnit.Framework.Assertions.LessFixture.NotLessWhenEqual().
static void NUnit.Framework.Assert.Less (int arg1, int arg2) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (uint arg1, uint arg2, string message, params object[] args) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (uint arg1, uint arg2) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (long arg1, long arg2, string message, params object[] args) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (long arg1, long arg2) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (ulong arg1, ulong arg2, string message, params object[] args) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (ulong arg1, ulong arg2) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (decimal arg1, decimal arg2, string message, params object[] args) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (decimal arg1, decimal arg2) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (double arg1, double arg2, string message, params object[] args) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (double arg1, double arg2) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (float arg1, float arg2, string message, params object[] args) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (float arg1, float arg2) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (IComparable arg1, IComparable arg2, string message, params object[] args) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Less (IComparable arg1, IComparable arg2) inline static
Verifies that the first value is less than the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThan(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (int arg1, int arg2, string message, params object[] args) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), NUnit.Framework.Assertions.GreaterEqualFixture.FailureMessage(), NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Decimal(), NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Double(), NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Float(), NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Int32(), NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Long(), NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_UInt32(), NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_ULong(), NUnit.Framework.Assertions.GreaterEqualFixture.MixedTypes(), NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterEqualIComparable(), and NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterOrEqual().
static void NUnit.Framework.Assert.GreaterOrEqual (int arg1, int arg2) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (uint arg1, uint arg2, string message, params object[] args) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (uint arg1, uint arg2) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (long arg1, long arg2, string message, params object[] args) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (long arg1, long arg2) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (ulong arg1, ulong arg2, string message, params object[] args) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (ulong arg1, ulong arg2) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (decimal arg1, decimal arg2, string message, params object[] args) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (decimal arg1, decimal arg2) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (double arg1, double arg2, string message, params object[] args) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (double arg1, double arg2) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (float arg1, float arg2, string message, params object[] args) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (float arg1, float arg2) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (IComparable arg1, IComparable arg2, string message, params object[] args) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.GreaterOrEqual (IComparable arg1, IComparable arg2) inline static
Verifies that the first value is greater than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be greater
arg2 The second value, expected to be less
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (int arg1, int arg2, string message, params object[] args) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), NUnit.Framework.Assertions.LessEqualFixture.FailureMessage(), NUnit.Framework.Assertions.LessEqualFixture.LessOrEqual(), NUnit.Framework.Assertions.LessEqualFixture.MixedTypes(), NUnit.Framework.Assertions.LessEqualFixture.NotLessEqualIComparable(), and NUnit.Framework.Assertions.LessEqualFixture.NotLessOrEqual().
static void NUnit.Framework.Assert.LessOrEqual (int arg1, int arg2) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (uint arg1, uint arg2, string message, params object[] args) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (uint arg1, uint arg2) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (long arg1, long arg2, string message, params object[] args) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (long arg1, long arg2) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (ulong arg1, ulong arg2, string message, params object[] args) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (ulong arg1, ulong arg2) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (decimal arg1, decimal arg2, string message, params object[] args) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (decimal arg1, decimal arg2) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (double arg1, double arg2, string message, params object[] args) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (double arg1, double arg2) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (float arg1, float arg2, string message, params object[] args) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (float arg1, float arg2) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (IComparable arg1, IComparable arg2, string message, params object[] args) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.LessOrEqual (IComparable arg1, IComparable arg2) inline static
Verifies that the first value is less than or equal to the second value. If it is not, then an AssertionException is thrown.
Parameters
arg1 The first value, expected to be less
arg2 The second value, expected to be greater
References NUnit.Framework.Is.LessThanOrEqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.True (bool? condition, string message, params object[] args) inline static
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
Parameters
condition The evaluated condition
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
Referenced by NUnitLite.Tests.CommandLineTests.AssemblyAloneIsValid(), NUnit.ConsoleRunner.Tests.CommandLineTests.AssemblyAloneIsValid(), NUnitLite.Tests.CommandLineTests.AssemblyName(), NUnit.ConsoleRunner.Tests.CommandLineTests.AssemblyName(), NUnit.Framework.Internal.Filters.NotFilterTests.BuildFromXml(), NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Constraints.EqualityComparerTests.CanCompareArrayContainingSelfToSelf(), NUnit.Engine.Tests.TestEngineResultTests.CanCreateFromXmlNode(), NUnit.Engine.Tests.TestEngineResultTests.CanCreateFromXmlString(), NUnitLite.Tests.CommandLineTests.CanRecognizeLowerCaseOptionValues(), NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeLowerCaseOptionValues(), NUnitLite.Tests.CommandLineTests.CanRecognizeStringOptions(), NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeStringOptions(), NUnit.ConsoleRunner.Tests.CommandLineTests.CanRegognizeInProcessOption(), NUnit.Engine.Services.Tests.DomainManagerTests.CheckDomainIsUnloaded(), NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePath(), NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePath(), NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePathAndFormat(), NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePathAndFormat(), NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePathAndTransform(), NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePathAndTransform(), NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePathUsingEqualSign(), NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePathUsingEqualSign(), NUnitLite.Tests.CommandLineTests.ExploreOptionWithoutPath(), NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithoutPath(), NUnitLite.Tests.CommandLineTests.FileNameWithoutResultOptionLooksLikeParameter(), NUnit.ConsoleRunner.Tests.CommandLineTests.FileNameWithoutResultOptionLooksLikeParameter(), NUnit.Framework.Constraints.EqualityComparerTests.IEnumeratorIsDisposed(), NUnit.Framework.Internal.Filters.NotFilterTests.MatchTest(), NUnit.ConsoleRunner.Tests.CommandLineTests.NoInputFiles(), NUnitLite.Tests.CommandLineTests.NoInputFiles(), NUnit.Framework.Internal.Filters.NotFilterTests.PassTest(), NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbabilityOneIsAlwaysTrue(), NUnitLite.Tests.CommandLineTests.ResultOptionMayBeRepeated(), NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionMayBeRepeated(), NUnitLite.Tests.CommandLineTests.ResultOptionWithFilePath(), NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithFilePath(), NUnitLite.Tests.CommandLineTests.ResultOptionWithFilePathAndFormat(), NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithFilePathAndFormat(), NUnitLite.Tests.CommandLineTests.ResultOptionWithFilePathAndTransform(), NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithFilePathAndTransform(), NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.ShouldRetTeamCityAsTrueWhenHasEnvironmentVariable_TEAMCITY_PROJECT_NAME(), NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Internal.SuccessResultTests.SuiteResultIsSuccess(), NUnit.Framework.Internal.SuccessResultTests.TestResultIsSuccess(), NUnitLite.Tests.CommandLineTests.TimeoutIsMinusOneIfNoOptionIsProvided(), NUnit.ConsoleRunner.Tests.CommandLineTests.TimeoutIsMinusOneIfNoOptionIsProvided(), NUnitLite.Tests.CommandLineTests.TimeoutParsesIntValueCorrectly(), and NUnit.ConsoleRunner.Tests.CommandLineTests.TimeoutParsesIntValueCorrectly().
static void NUnit.Framework.Assert.True (bool condition, string message, params object[] args) inline static
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
Parameters
condition The evaluated condition
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
static void NUnit.Framework.Assert.True (bool? condition) inline static
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
Parameters
condition The evaluated condition
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
static void NUnit.Framework.Assert.True (bool condition) inline static
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
Parameters
condition The evaluated condition
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
static void NUnit.Framework.Assert.IsTrue (bool? condition, string message, params object[] args) inline static
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
Parameters
condition The evaluated condition
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
Referenced by NUnit.Framework.Internal.PlatformDetectionTests.ArrayOfPlatforms(), IG.Test.TestCrypto.AsymmetricAlgorithmTypes(), NUnit.Samples.Money.MoneyTest.BagMultiply(), NUnit.Framework.Internal.SetUpTearDownTests.BaseSetUpIsCalledFirstTearDownLast(), NUnit.Framework.Assertions.EqualsFixture.Byte(), NUnit.Framework.Constraints.NumericsTests.CanMatchDecimalWithoutToleranceMode(), NUnit.Framework.Constraints.NumericsTests.CanMatchDecimalWithPercentage(), NUnit.Framework.Constraints.NumericsTests.CanMatchIntegralsWithPercentage(), NUnit.Framework.Constraints.NumericsTests.CanMatchWithoutToleranceMode(), NUnit.Framework.Internal.SetUpTearDownTests.CheckInheritedSetUpAndTearDownAreCalled(), NUnit.Framework.Internal.SetUpTearDownTests.CheckOverriddenSetUpAndTearDownAreNotCalled(), IG.Test.TestMatrixDecompositonMathNet.Cholesky_MathNet(), IG.Test.TestMatrixDecomposition.Cholesky_MatrixBase(), IG.Test.TestMatrixDecomposition.Cholesky_PositiveSemidefinite_MatrixBase(), NUnit.Framework.Assertions.EqualsFixture.Decimal(), NUnit.Framework.Internal.PlatformDetectionTests.DetectExactVersion(), NUnit.Framework.Constraints.FloatingPointNumericsTests.DoubleEqualityWithUlps(), IG.Test.TestMatrixDecompositonMathNet.Eigen_MathNet(), NUnit.Framework.Assertions.EqualsFixture.Equals(), NUnit.Framework.Constraints.NumericsTests.FailsOnDecimalAbovePercentage(), NUnit.Framework.Constraints.NumericsTests.FailsOnDecimalBelowPercentage(), NUnit.Framework.Constraints.NumericsTests.FailsOnIntegralsOutsideOfPercentage(), NUnit.Framework.Internal.SetUpTearDownTests.FailureInBaseSetUpCausesDerivedSetUpAndTearDownToBeSkipped(), NUnit.Framework.Assertions.EqualsFixture.Float(), NUnit.Framework.Constraints.FloatingPointNumericsTests.FloatEqualityWithUlps(), NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInSetUp(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableDifferentTypesSuccess_WhenActualImplementsIEquatable(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableDifferentTypesSuccess_WhenExpectedImplementsIEquatable(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableSuccess(), NUnit.Framework.Assertions.EqualsFixture.Int(), NUnit.Engine.Tests.AsyncTestEngineResultTests.IsComplete_TrueIfComplete(), NUnit.Framework.Assertions.ConditionAssertTests.IsTrue(), NUnit.Framework.Tests.AssertSyntaxTests.IsTrue(), NUnit.Framework.Assertions.ConditionAssertTests.IsTrueFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsTrueFailsForNullable(), NUnit.Framework.Assertions.ConditionAssertTests.IsTrueNullable(), NUnit.Samples.Money.MoneyTest.IsZero(), IG.Test.TestMatrixDecomposition.LDLT_Indefinite_MatrixBase(), IG.Test.TestMatrixDecomposition.LDLT_MatrixBase(), IG.Test.TestMatrixDecomposition.LU_MatrixBase(), NUnit.Framework.Internal.SetUpTearDownTests.MakeSureSetUpAndTearDownAreCalled(), NUnit.Samples.Money.MoneyTest.MoneyBagEquals(), NUnit.Samples.Money.MoneyTest.MoneyEquals(), NUnit.Framework.Internal.SetUpTearDownTests.MultipleSetUpAndTearDownMethodsAreCalled(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtD5(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustD5(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustNormalizedD5(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustNormalizedUnmodifiedD5(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustUnmodifiedD5(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNormalizedD5(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNormalizedUnmodifiedD5(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtRobustD7(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtUnmodifiedD5(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_Exclude(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_Include(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_IncludeAndExclude(), IG.Test.TestMatrixDecomposition.Qr_MatrixBase(), IG.Test.TestMatrixDecomposition.QrGrammSchmidt_MatrixBase(), NUnit.Framework.Constraints.EqualityComparerTests.ReferenceEqualityHasPrecedenceOverIEquatable(), NUnit.TestData.RepeatingTests.RepeatFailOnSecondTryFixture.RepeatFailOnThird(), NUnit.TestData.RepeatingTests.RepeatFailOnThirdTryFixture.RepeatFailOnThird(), NUnit.TestData.RepeatingTests.RepeatSuccessFixture.RepeatSuccess(), NUnit.Framework.Assertions.EqualsFixture.Short(), NUnit.Framework.Assertions.EqualsFixture.String(), NUnit.TestData.RepeatingTests.RetrySucceedsOnFirstTryFixture.SucceedsEveryTime(), NUnit.TestData.RepeatingTests.RetrySucceedsOnSecondTryFixture.SucceedsOnSecondTry(), NUnit.TestData.RepeatingTests.RetrySucceedsOnThirdTryFixture.SucceedsOnThirdTry(), IG.Test.TestCrypto.SymmetricAlgorithmTypes(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestToleranceDefault(), NUnit.TestData.RepeatingTests.RepeatedTestWithCategory.TestWithCategory(), NUnit.TestData.RepeatingTests.RetryTestWithCategoryFixture.TestWithCategory(), NUnit.Framework.Assertions.EqualsFixture.UInt(), NUnit.Engine.Tests.AsyncTestEngineResultTests.Wait_AllowsMultipleWaits(), NUnit.Engine.Tests.AsyncTestEngineResultTests.Wait_ReturnsFalseTillTestCompletes(), NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.WaitAll_SingleTask(), NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.WaitAll_SingleThread_MultipleTasks(), and NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.WaitAll_TwoThreads_MultipleTasks().
static void NUnit.Framework.Assert.IsTrue (bool condition, string message, params object[] args) inline static
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
Parameters
condition The evaluated condition
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
static void NUnit.Framework.Assert.IsTrue (bool? condition) inline static
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
Parameters
condition The evaluated condition
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
static void NUnit.Framework.Assert.IsTrue (bool condition) inline static
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
Parameters
condition The evaluated condition
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
static void NUnit.Framework.Assert.False (bool? condition, string message, params object[] args) inline static
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
Parameters
condition The evaluated condition
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.False, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.NotFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml_TopLevelDefaultsToAnd(), NUnitLite.Tests.CommandLineTests.CanRecognizeStringOptions(), NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeStringOptions(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml_Regex(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CheckExtension(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml_Regex(), NUnit.Framework.Internal.PropertyBagTests.ContainsKey(), NUnit.Framework.Constraints.CollectionEquivalentConstraintTests.EquivalentFailsWithDuplicateElementInActual(), NUnit.Framework.Constraints.CollectionEquivalentConstraintTests.EquivalentFailsWithDuplicateElementInExpected(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.ExplicitMatch_SingleName(), NUnit.Framework.Internal.Filters.AndFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.IdFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.OrFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.NotFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.IdFilter_FromXml(), NUnitLite.Tests.CommandLineTests.InvalidCommandLineParms(), NUnit.ConsoleRunner.Tests.CommandLineTests.InvalidCommandLineParms(), NUnitLite.Tests.CommandLineTests.InvalidOption(), NUnit.ConsoleRunner.Tests.CommandLineTests.InvalidOption(), NUnit.Framework.Internal.Filters.AndFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.NotFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.OrFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.IdFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.CategoryFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.PropertyFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.TestNameFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.FullNameFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesNothihngExplicitly(), NUnit.Framework.Internal.Filters.AndFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.NotFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.OrFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.IdFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_FromXml(), NUnitLite.Tests.CommandLineTests.MissingValuesAreReported(), NUnit.ConsoleRunner.Tests.CommandLineTests.MissingValuesAreReported(), NUnit.Framework.Internal.Filters.AndFilterTests.PassTest(), NUnit.Framework.Internal.Filters.OrFilterTests.PassTest(), NUnit.Framework.Internal.Filters.IdFilterTests.PassTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.PassTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.PassTest(), NUnit.Framework.Internal.Filters.NotFilterTests.PassTest(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_ProcessBitNess(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml_Regex(), NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbabilityZeroIsAlwaysFalse(), NUnitLite.Tests.CommandLineTests.ResultOptionWithoutFileNameIsInvalid(), NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithoutFileNameIsInvalid(), NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.ShouldRetTeamCityAsFalseWhenHasNotEnvironmentVariable_TEAMCITY_PROJECT_NAME(), NUnit.Framework.Internal.ResultStateTests.TestEquality_Null(), NUnit.Framework.Internal.ResultStateTests.TestEquality_WrongType(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml_Regex(), NUnitLite.Tests.CommandLineTests.TimeoutCausesErrorIfValueIsNotInteger(), NUnit.ConsoleRunner.Tests.CommandLineTests.TimeoutCausesErrorIfValueIsNotInteger(), NUnit.Framework.Constraints.EqualityComparerTests.UnequalItems(), and NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.ValidExtensions().
static void NUnit.Framework.Assert.False (bool condition, string message, params object[] args) inline static
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
Parameters
condition The evaluated condition
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.False, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.False (bool? condition) inline static
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
Parameters
condition The evaluated condition
References NUnit.Framework.Is.False, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.False (bool condition) inline static
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
Parameters
condition The evaluated condition
References NUnit.Framework.Is.False, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsFalse (bool? condition, string message, params object[] args) inline static
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
Parameters
condition The evaluated condition
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.False, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Internal.PlatformDetectionTests.ArrayOfPlatforms(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfString(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CannotLoadWebProject(), NUnit.Framework.Internal.SetUpTearDownTests.CheckOverriddenSetUpAndTearDownAreNotCalled(), NUnit.Framework.Internal.PlatformDetectionTests.DetectExactVersion(), NUnit.Framework.Constraints.FloatingPointNumericsTests.DoubleEqualityWithUlps(), NUnit.TestData.RepeatingTests.RetryFailsEveryTimeFixture.FailsEveryTime(), NUnit.Framework.Constraints.DelayedConstraintTests.FailsWithBadDelegates(), NUnit.Framework.Constraints.ConstraintTestBase.FailsWithBadValues(), NUnit.Framework.Constraints.ThrowsConstraintTestBase.FailsWithBadValues(), NUnit.Framework.Internal.SetUpTearDownTests.FailureInBaseSetUpCausesDerivedSetUpAndTearDownToBeSkipped(), NUnit.Framework.Constraints.FloatingPointNumericsTests.FloatEqualityWithUlps(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableHasPrecedenceOverDefaultEquals(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.IgnoredFixtureShouldNotCallFixtureSetUpOrTearDown(), NUnit.Engine.Tests.AsyncTestEngineResultTests.IsComplete_FalseIfNotComplete(), NUnit.Framework.Assertions.ConditionAssertTests.IsFalse(), NUnit.Framework.Tests.AssertSyntaxTests.IsFalse(), NUnit.Framework.Assertions.ConditionAssertTests.IsFalseFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsFalseFailsForNullable(), NUnit.Framework.Assertions.ConditionAssertTests.IsFalseNullable(), NUnit.Samples.Money.MoneyTest.MoneyBagEquals(), NUnit.Samples.Money.MoneyTest.MoneyEquals(), NUnit.Samples.Money.MoneyTest.MoneyHash(), NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.NotWebProject(), TstPerson.NUnit_Example_IsNameJohnSmith(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_Exclude(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_Include(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_IncludeAndExclude(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_InvalidPlatform(), NUnit.TestData.RepeatingTests.RepeatFailOnFirstTryFixture.RepeatFailOnFirst(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestToleranceExact(), NUnit.Engine.Tests.AsyncTestEngineResultTests.Wait_ReturnsFalseTillTestCompletes(), NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.WaitAll_SingleTask(), NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.WaitAll_SingleThread_MultipleTasks(), and NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.WaitAll_TwoThreads_MultipleTasks().
static void NUnit.Framework.Assert.IsFalse (bool condition, string message, params object[] args) inline static
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
Parameters
condition The evaluated condition
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.False, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsFalse (bool? condition) inline static
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
Parameters
condition The evaluated condition
References NUnit.Framework.Is.False, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsFalse (bool condition) inline static
Asserts that a condition is false. If the condition is true the method throws an AssertionException.
Parameters
condition The evaluated condition
References NUnit.Framework.Is.False, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.NotNull (object anObject, string message, params object[] args) inline static
Verifies that the object that is passed in is not equal to
null If the object is null then an AssertionException is thrown.
Parameters
anObject The object that is to be tested
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.Not, NUnit.Framework.Constraints.ConstraintExpression.Null, and NUnit.Framework.Assert.That().
Referenced by NUnit.Engine.Api.Tests.ServiceLocatorTests.CanAccessService(), NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomain(), NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified(), NUnit.Framework.Internal.TestExecutionContextTests.CanCreateObjectInAppDomain(), NUnit.Engine.Services.Tests.ExtensionServiceTests.CanGetExtensionPointByPath(), NUnit.Engine.Services.Tests.ExtensionServiceTests.CanGetExtensionPointByType(), NUnit.Engine.Services.Tests.ResultServiceTests.CanGetWriter(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple_XmlOutput(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_XmlOutput(), NUnit.Framework.Internal.TestXmlTests.CheckXmlForTest(), NUnit.Framework.Attributes.DerivedPropertyAttributeTests.ConstructWithNoArgs< T >(), NUnit.Framework.Attributes.DerivedPropertyAttributeTests.ConstructWithOneArg< T >(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.ConvertEngineResultToXml(), NUnit.ConsoleRunner.Tests.ResultReporterTests.CreateResult(), NUnitLite.Tests.TextUITests.CreateResult(), NUnit.TestUtilities.TestAssert.IsNotRunnable(), NUnit.TestUtilities.TestAssert.IsRunnable(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.RunMockAssemblyTests(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.runSchemaValidatorTest(), NUnit.Framework.Tests.ActionAttributeTests.Setup(), NUnit.Framework.Internal.TestResultTests.SuiteResultXmlNodeBasicInfo(), NUnit.Framework.Internal.FailedResultTests.SuiteResultXmlNodeIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultXmlNodeIsFailure(), NUnit.Framework.Tests.TestContextTests.TestCanAccessWorkDirectory(), NUnit.Framework.Internal.TestResultTests.TestResultXmlNodeBasicInfo(), NUnit.Framework.Internal.FailedResultTests.TestResultXmlNodeIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.TestResultXmlNodeIsIgnored(), NUnit.Framework.Internal.InconclusiveResultTests.TestResultXmlNodeIsInconclusive(), NUnit.Framework.Internal.NotRunnableResultTests.TestResultXmlNodeIsNotRunnable(), and NUnit.Framework.Internal.SuccessResultTests.TestResultXmlNodeIsSuccess().
static void NUnit.Framework.Assert.NotNull (object anObject) inline static
Verifies that the object that is passed in is not equal to
null If the object is null then an AssertionException is thrown.
Parameters
anObject The object that is to be tested
References NUnit.Framework.Is.Not, NUnit.Framework.Constraints.ConstraintExpression.Null, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNotNull (object anObject, string message, params object[] args) inline static
Verifies that the object that is passed in is not equal to
null If the object is null then an AssertionException is thrown.
Parameters
anObject The object that is to be tested
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.Not, NUnit.Framework.Constraints.ConstraintExpression.Null, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Internal.SetUpFixtureTests.AssemblySetUpFixtureReplacesAssemblyNodeInTree(), NUnit.Framework.Assertions.NullableTypesTests.CanTestForNull(), NUnit.Framework.Attributes.RepeatAttributeTests.CategoryWorksWithRepeatedTest(), NUnit.Framework.Attributes.RetryAttributeTests.CategoryWorksWithRetry(), NUnit.Framework.Assertions.AssertThrowsTests.CorrectExceptionIsReturnedToMethod(), NUnit.Framework.Attributes.PropertyAttributeTests.CustomPropertyAttribute(), NUnit.Engine.Services.Tests.RecentFilesTests.EmptyList(), NUnit.ConsoleRunner.Tests.CommandLineTests.GetFieldInfo(), NUnitLite.Tests.CommandLineTests.GetPropertyInfo(), NUnit.ConsoleRunner.Tests.CommandLineTests.GetPropertyInfo(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureSetup(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleExceptionInFixtureConstructor(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleIgnoreInFixtureSetup(), NUnit.Framework.Internal.SetUpFixtureTests.InvalidAssemblySetUpFixtureIsLoadedCorrectly(), NUnit.Framework.Tests.AssertSyntaxTests.IsNotNull(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotNull(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotNullFails(), and NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureReplacesNamespaceNodeInTree().
static void NUnit.Framework.Assert.IsNotNull (object anObject) inline static
Verifies that the object that is passed in is not equal to
null If the object is null then an AssertionException is thrown.
Parameters
anObject The object that is to be tested
References NUnit.Framework.Is.Not, NUnit.Framework.Constraints.ConstraintExpression.Null, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.Null (object anObject, string message, params object[] args) inline static
Verifies that the object that is passed in is equal to
null If the object is not null then an AssertionException is thrown.
Parameters
anObject The object that is to be tested
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.Null, and NUnit.Framework.Assert.That().
Referenced by NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CanLoadEmptyProject(), NUnitLite.Tests.CommandLineTests.DefaultResultSpecification(), NUnit.ConsoleRunner.Tests.CommandLineTests.DefaultResultSpecification(), NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePath(), NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePath(), NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePathAndFormat(), NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePathAndFormat(), NUnit.Common.Tests.OutputSpecificationTests.FileNameOnly(), NUnit.Common.Tests.OutputSpecificationTests.FileNamePlusFormat(), NUnit.Framework.Attributes.TheoryTests.NullDatapointIsOK(), NUnit.Engine.Api.Tests.TestPackageTests_MultipleAssemblies.PackageIsAnonymous(), NUnitLite.Tests.CommandLineTests.ResultOptionMayBeRepeated(), NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionMayBeRepeated(), NUnitLite.Tests.CommandLineTests.ResultOptionWithFilePath(), NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithFilePath(), NUnitLite.Tests.CommandLineTests.ResultOptionWithFilePathAndFormat(), NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithFilePathAndFormat(), NUnit.Framework.Internal.FailedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultIsInconclusive(), NUnit.Framework.Internal.FailedResultTests.SuiteResultXmlNodeIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultXmlNodeIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.TestResultXmlNodeIsIgnored(), NUnit.Framework.Internal.InconclusiveResultTests.TestResultXmlNodeIsInconclusive(), NUnit.Framework.Internal.NotRunnableResultTests.TestResultXmlNodeIsNotRunnable(), and NUnit.Framework.Internal.SuccessResultTests.TestResultXmlNodeIsSuccess().
static void NUnit.Framework.Assert.Null (object anObject) inline static
Verifies that the object that is passed in is equal to
null If the object is not null then an AssertionException is thrown.
Parameters
anObject The object that is to be tested
References NUnit.Framework.Is.Null, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNull (object anObject, string message, params object[] args) inline static
Verifies that the object that is passed in is equal to
null If the object is not null then an AssertionException is thrown.
Parameters
anObject The object that is to be tested
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.Null, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Attributes.TestCaseAttributeTests.CanPassNullAsFirstArgument(), NUnit.Framework.Assertions.NullableTypesTests.CanTestForNull(), NUnit.Framework.Tests.AssertSyntaxTests.IsNull(), NUnit.Framework.Assertions.ConditionAssertTests.IsNull(), NUnit.Framework.Assertions.ConditionAssertTests.IsNullFails(), NUnit.Framework.Tests.Attributes.AuthorTests.NoAuthor(), NUnit.Framework.Attributes.DescriptionTests.NoDescription(), NUnit.Framework.Tests.Attributes.TestOfTests.NoTestOf(), NUnit.Framework.Attributes.TestCaseAttributeTests.NullableSimpleFormalParametersWithNullArgument(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultXmlNodeIsInconclusive(), and NUnit.Framework.Internal.InconclusiveResultTests.TestResultXmlNodeIsInconclusive().
static void NUnit.Framework.Assert.IsNull (object anObject) inline static
Verifies that the object that is passed in is equal to
null If the object is not null then an AssertionException is thrown.
Parameters
anObject The object that is to be tested
References NUnit.Framework.Is.Null, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNaN (double aDouble, string message, params object[] args) inline static
Verifies that the double that is passed in is an
NaN value. If the object is not NaN then an AssertionException is thrown.
Parameters
aDouble The value that is to be tested
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.NaN, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Assertions.NullableTypesTests.CanTestForNaN(), NUnit.Framework.Tests.AssertSyntaxTests.IsNaN(), NUnit.Framework.Assertions.ConditionAssertTests.IsNaN(), and NUnit.Framework.Assertions.ConditionAssertTests.IsNaNFails().
static void NUnit.Framework.Assert.IsNaN (double aDouble) inline static
Verifies that the double that is passed in is an
NaN value. If the object is not NaN then an AssertionException is thrown.
Parameters
aDouble The value that is to be tested
References NUnit.Framework.Is.NaN, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNaN (double? aDouble, string message, params object[] args) inline static
Verifies that the double that is passed in is an
NaN value. If the object is not NaN then an AssertionException is thrown.
Parameters
aDouble The value that is to be tested
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.NaN, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNaN (double? aDouble) inline static
Verifies that the double that is passed in is an
NaN value. If the object is not NaN then an AssertionException is thrown.
Parameters
aDouble The value that is to be tested
References NUnit.Framework.Is.NaN, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsEmpty (string aString, string message, params object[] args) inline static
Assert that a string is empty - that is equal to string.Empty
Parameters
aString The string to be tested
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.EmptyCollectionTests(), NUnit.Framework.Tests.AssertSyntaxTests.EmptyStringTests(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmpty(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNonEmptyArray(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNonEmptyIEnumerable(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNullString(), and NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnString().
static void NUnit.Framework.Assert.IsEmpty (string aString) inline static
Assert that a string is empty - that is equal to string.Empty
Parameters
aString The string to be tested
References NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsEmpty (IEnumerable collection, string message, params object[] args) inline static
Assert that an array, list or other collection is empty
Parameters
collection An array, list or other collection implementing ICollection
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsEmpty (IEnumerable collection) inline static
Assert that an array, list or other collection is empty
Parameters
collection An array, list or other collection implementing ICollection
References NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNotEmpty (string aString, string message, params object[] args) inline static
Assert that a string is not empty - that is not equal to string.Empty
Parameters
aString The string to be tested
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Constraints.ConstraintExpression.Empty, NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.EmptyCollectionTests(), NUnit.Framework.Tests.AssertSyntaxTests.EmptyStringTests(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmpty(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyArray(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyArrayList(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyHashTable(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyIEnumerable(), and NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyString().
static void NUnit.Framework.Assert.IsNotEmpty (string aString) inline static
Assert that a string is not empty - that is not equal to string.Empty
Parameters
aString The string to be tested
References NUnit.Framework.Constraints.ConstraintExpression.Empty, NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNotEmpty (IEnumerable collection, string message, params object[] args) inline static
Assert that an array, list or other collection is not empty
Parameters
collection An array, list or other collection implementing ICollection
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Constraints.ConstraintExpression.Empty, NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNotEmpty (IEnumerable collection) inline static
Assert that an array, list or other collection is not empty
Parameters
collection An array, list or other collection implementing ICollection
References NUnit.Framework.Constraints.ConstraintExpression.Empty, NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
static new bool NUnit.Framework.Assert.Equals (object a, object b) inline static
The Equals method throws an AssertionException. This is done to make sure there is no mistake by calling this function.
Parameters
a
b
Referenced by NUnit.Framework.Assertions.EqualsFixture.EqualsThrowsException().
static new void NUnit.Framework.Assert.ReferenceEquals (object a, object b) inline static
override the default ReferenceEquals to throw an AssertionException. This implementation makes sure there is no mistake in calling this function as part of Assert.
Parameters
a
b
Referenced by NUnit.Framework.Assertions.EqualsFixture.ReferenceEqualsThrowsException().
static void NUnit.Framework.Assert.Pass (string message, params object[] args) inline static
Throws a SuccessException with the message and arguments that are passed in. This allows a test to be cut short, with a result of success returned to NUnit.
Parameters
message The message to initialize the AssertionException with.
args Arguments to be used in formatting the message
Referenced by NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.AnotherPassingTest(), NUnit.Framework.Assertions.AssertPassTests.AssertPassReturnsSuccess(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetStaticMethodsOnBase(), NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceAtEndOfSuccessMessage(), NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceInSuccessMessage(), NUnit.Tests.Assemblies.MockTestFixture.MockTest3(), NUnit.Framework.Assert.Pass(), NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.PassingTest(), NUnit.Framework.Assertions.AssertPassTests.SubsequentFailureIsIrrelevant(), NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownFixtureWithTestCases.Success(), NUnit.Framework.Tests.TestContextOneTimeTearDownTests.TestExplicit(), NUnit.TestData.TheoryFixture.TheoryFixture.TestWithAllBadValues(), NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownFixtureWithTheories.TheoryTest(), NUnit.Framework.Assertions.AssertPassTests.ThrowsSuccessException(), NUnit.Framework.Assertions.AssertPassTests.ThrowsSuccessExceptionWithMessage(), and NUnit.Framework.Assertions.AssertPassTests.ThrowsSuccessExceptionWithMessageAndArgs().
static void NUnit.Framework.Assert.Pass (string message) inline static
Throws a SuccessException with the message and arguments that are passed in. This allows a test to be cut short, with a result of success returned to NUnit.
Parameters
message The message to initialize the AssertionException with.
References NUnit.Framework.Assert.Pass().
static void NUnit.Framework.Assert.Pass () inline static
Throws a SuccessException with the message and arguments that are passed in. This allows a test to be cut short, with a result of success returned to NUnit.
References NUnit.Framework.Assert.Pass().
static void NUnit.Framework.Assert.Fail (string message, params object[] args) inline static
Throws an AssertionException with the message and arguments that are passed in. This is used by the other Assert functions.
Parameters
message The message to initialize the AssertionException with.
args Arguments to be used in formatting the message
Referenced by NUnit.TestData.AssertFailFixture.AssertFailFixture.CallAssertFail(), NUnit.TestData.AssertFailFixture.AssertFailFixture.CallAssertFailWithMessage(), NUnit.TestData.AssertFailFixture.AssertFailFixture.CallAssertFailWithMessageAndArgs(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetStaticMethodsOnBase(), NUnit.Engine.Services.Tests.ExtensionServiceTests.CanListExtensionPoints(), NUnit.Engine.Services.Tests.ExtensionServiceTests.CanListExtensions(), NUnit.TestUtilities.UniqueValues.Check< T >(), NUnit.Framework.Constraints.EqualTests.CheckExceptionMessage(), NUnit.Framework.Internal.PlatformDetectionTests.CheckPlatforms(), NUnit.Framework.Attributes.RandomAttributeTests.CheckRandomResult(), NUnit.Framework.Syntax.InvalidCodeTests.CodeShouldNotCompile(), NUnit.Framework.Syntax.InvalidCodeTests.CodeShouldNotCompileAsFinishedConstraint(), NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceAtEndOfFailureMessage(), NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceInFailureMessage(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotFindStaticMethodsOnBase(), NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualMessageDisplaysAllDigits(), NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualMessageDisplaysDefaultTolerance(), NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualMessageDisplaysTolerance(), NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualWithNanDoesNotDisplayDefaultTolerance(), NUnit.Framework.Tests.ActionAttributeTests.ExpectedOutput_InCorrectOrder(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectFailure(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectMatch(), NUnit.Framework.Assert.Fail(), NUnit.TestData.TestContextData.TestTestContextInTearDown.FailingTest(), NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.FailingTest(), NUnit.Tests.Assemblies.MockTestFixture.FailingTest(), NUnit.Framework.Attributes.MaxTimeTests.FailureReport(), NUnit.Framework.Assertions.EqualsFixture.FloatNotEqualMessageDisplaysAllDigits(), NUnit.Framework.Assertions.EqualsFixture.FloatNotEqualMessageDisplaysTolerance(), NUnit.Framework.Constraints.CollectionSubsetConstraintTests.HonorsIgnoreCase(), NUnit.Framework.Constraints.CollectionSupersetConstraintTests.HonorsIgnoreCase(), NUnit.Framework.Constraints.CollectionEquivalentConstraintTests.HonorsIgnoreCase(), NUnit.Framework.Constraints.CollectionContainsConstraintTests.IgnoreCaseIsHonored(), NUnit.TestData.MaxTimeFixtureWithFailure.MaxTimeExceeded(), NUnit.TestData.RepeatingTests.RetryWithIgnoreAttributeFixture.RepeatShouldIgnore(), NUnit.TestData.RepeatingTests.RepeatedTestWithIgnoreAttribute.RepeatShouldIgnore(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.runSchemaValidatorTest(), NUnit.TestData.TestContextData.TestStateRecordingFixture.SetUp(), NUnit.Framework.Assertions.AssertPassTests.SubsequentFailureIsIrrelevant(), NUnit.Framework.Constraints.ConstraintTestBase.SucceedsWithGoodValues(), NUnit.Framework.Constraints.ThrowsConstraintTestBase.SucceedsWithGoodValues(), NUnit.TestData.RepeatingTests.RetryIgnoredOnSecondTryFixture.Test(), NUnit.TestData.RepeatingTests.RetryIgnoredOnThirdTryFixture.Test(), NUnit.TestData.RepeatingTests.RetryErrorOnSecondTryFixture.Test(), NUnit.TestData.RepeatingTests.RetryErrorOnThirdTryFixture.Test(), NUnit.TestData.TestContextData.TestStateRecordingFixture.TheTest(), NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionException(), NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionException_MessageSpecified(), NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionExceptionWithMessage(), NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionExceptionWithMessageAndArgs(), NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.Validate(), and NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder.Verify().
static void NUnit.Framework.Assert.Fail (string message) inline static
Throws an AssertionException with the message that is passed in. This is used by the other Assert functions.
Parameters
message The message to initialize the AssertionException with.
References NUnit.Framework.Assert.Fail().
static void NUnit.Framework.Assert.Fail () inline static
Throws an AssertionException. This is used by the other Assert functions.
References NUnit.Framework.Assert.Fail().
static void NUnit.Framework.Assert.Ignore (string message, params object[] args) inline static
Throws an IgnoreException with the message and arguments that are passed in. This causes the test to be reported as ignored.
Parameters
message The message to initialize the AssertionException with.
args Arguments to be used in formatting the message
Referenced by NUnit.TestData.AssertIgnoreData.IgnoredTestCaseFixture.CallsIgnore(), NUnit.TestData.AssertIgnoreData.IgnoredTestSuiteFixture.FixtureSetUp(), NUnit.Framework.Assert.Ignore(), NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.IgnoredTest(), NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.IgnoredTestThree(), NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.IgnoredTestTwo(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWithUserMessage(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWithUserMessage_ArrayOfArgs(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWithUserMessage_OneArg(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWithUserMessage_ThreeArgs(), NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodCallsIgnore(), NUnit.TestData.TestContextData.TestStateRecordingFixture.SetUp(), NUnit.TestData.AssertIgnoreData.IgnoreInSetUpFixture.SetUp(), NUnit.TestData.OneTimeSetUpTearDownData.IgnoreInFixtureSetUp.SetUpCallsIgnore(), NUnit.TestData.RepeatingTests.RetryIgnoredOnFirstTryFixture.Test(), NUnit.TestData.RepeatingTests.RepeatIgnoredOnFirstTryFixture.Test(), NUnit.TestData.RepeatingTests.RetryIgnoredOnSecondTryFixture.Test(), NUnit.TestData.RepeatingTests.RepeatIgnoredOnSecondTryFixture.Test(), NUnit.TestData.RepeatingTests.RetryIgnoredOnThirdTryFixture.Test(), NUnit.TestData.RepeatingTests.RepeatIgnoredOnThirdTryFixture.Test(), NUnit.Framework.Internal.FailedResultTests.TestResultXmlNodeEscapesInvalidXmlCharacters(), NUnit.Framework.Assertions.AssertIgnoreTests.ThrowsIgnoreException(), NUnit.Framework.Assertions.AssertIgnoreTests.ThrowsIgnoreExceptionWithMessage(), and NUnit.Framework.Assertions.AssertIgnoreTests.ThrowsIgnoreExceptionWithMessageAndArgs().
static void NUnit.Framework.Assert.Ignore (string message) inline static
Throws an IgnoreException with the message that is passed in. This causes the test to be reported as ignored.
Parameters
message The message to initialize the AssertionException with.
References NUnit.Framework.Assert.Ignore().
static void NUnit.Framework.Assert.Ignore () inline static
Throws an IgnoreException. This causes the test to be reported as ignored.
References NUnit.Framework.Assert.Ignore().
static void NUnit.Framework.Assert.Inconclusive (string message, params object[] args) inline static
Throws an InconclusiveException with the message and arguments that are passed in. This causes the test to be reported as inconclusive.
Parameters
message The message to initialize the InconclusiveException with.
args Arguments to be used in formatting the message
Referenced by NUnit.Framework.Assert.Inconclusive(), NUnit.Tests.Assemblies.MockTestFixture.InconclusiveTest(), NUnit.ConsoleRunner.Tests.ColorConsoleTests.SetUp(), NUnit.TestData.TestContextData.TestStateRecordingFixture.TheTest(), NUnit.Framework.Assertions.AssertInconclusiveTests.ThrowsInconclusiveException(), NUnit.Framework.Assertions.AssertInconclusiveTests.ThrowsInconclusiveExceptionWithMessage(), and NUnit.Framework.Assertions.AssertInconclusiveTests.ThrowsInconclusiveExceptionWithMessageAndArgs().
static void NUnit.Framework.Assert.Inconclusive (string message) inline static
Throws an InconclusiveException with the message that is passed in. This causes the test to be reported as inconclusive.
Parameters
message The message to initialize the InconclusiveException with.
References NUnit.Framework.Assert.Inconclusive().
static void NUnit.Framework.Assert.Inconclusive () inline static
Throws an InconclusiveException. This causes the test to be reported as Inconclusive.
References NUnit.Framework.Assert.Inconclusive().
static void NUnit.Framework.Assert.Contains (object expected, ICollection actual, string message, params object[] args) inline static
Asserts that an object is contained in a list.
Parameters
expected The expected object
actual The list to be examined
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Assertions.ListContentsTests.ArrayFails(), NUnit.Framework.Assertions.ListContentsTests.ArrayListFails(), NUnit.Framework.Assertions.ListContentsTests.ArrayListSucceeds(), NUnit.Framework.Assertions.ListContentsTests.ArraySucceeds(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Assertions.ListContentsTests.DifferentTypesMayBeEqual(), NUnit.Framework.Assertions.ListContentsTests.EmptyArrayFails(), NUnit.TestUtilities.SimpleEventRecorder.EventMatcher.MatchEvent(), and NUnit.Framework.Assertions.ListContentsTests.NullArrayIsError().
static void NUnit.Framework.Assert.Contains (object expected, ICollection actual) inline static
Asserts that an object is contained in a list.
Parameters
expected The expected object
actual The list to be examined
References NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.AreEqual (double expected, double actual, double delta, string message, params object[] args) inline static
Verifies that two doubles are equal considering a delta. If the expected value is infinity then the delta value is ignored. If they are not equal then an AssertionException is thrown.
Parameters
expected The expected value
actual The actual value
delta The maximum acceptable difference between the the expected and the actual
message The message to display in case of failure
args Array of objects to be used in formatting the message
Referenced by NUnit.Samples.SimpleCSharpTest.Add(), IG.Test.TestApproximationBase.Approximation_Wls_Exact(), IG.Test.TestApproximationBase.Approximation_Wls_Perturbed(), NUnit.Framework.Assertions.CollectionAssertTest.AreEqual(), NUnit.Framework.Attributes.TestCaseAttributeTests.ArgumentsAreCoalescedInObjectArray(), NUnit.Framework.Attributes.TestCaseAttributeTests.ArgumentsOfDifferentTypeAreCoalescedInObjectArray(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndCollection(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayIsEqualToItself(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayOfIntAndArrayOfDouble(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysDeclaredAsDifferentTypes(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfArrays(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfDecimal(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfDouble(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfInt(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfMixedTypes(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfString(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysPassedAsObjects(), NUnitLite.Tests.CommandLineTests.AssemblyAloneIsValid(), NUnit.ConsoleRunner.Tests.CommandLineTests.AssemblyAloneIsValid(), NUnitLite.Tests.CommandLineTests.AssemblyName(), NUnit.ConsoleRunner.Tests.CommandLineTests.AssemblyName(), NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.AssemblyPathIsUsedAsFilePath(), NUnit.Framework.Internal.SetUpFixtureTests.AssemblySetUpFixtureReplacesAssemblyNodeInTree(), NUnit.Framework.Internal.SetUpFixtureTests.AssemblySetupFixtureWrapsExecutionOfTest(), NUnit.Framework.Internal.SetUpTearDownTests.SetupCallDerived.AssertCount(), NUnit.Framework.Assertions.AssertFailTests.AssertFailWorks(), NUnit.Framework.Assertions.AssertFailTests.AssertFailWorksWithMessage(), NUnit.Framework.Assertions.AssertFailTests.AssertFailWorksWithMessageAndArgs(), NUnit.Framework.Tests.Attributes.AuthorTests.Author(), NUnit.Framework.Tests.Attributes.AuthorTests.AuthorOnTestCase(), NUnit.Framework.Internal.UnexpectedExceptionTests.BadStackTraceIsHandled(), NUnit.Samples.Money.MoneyTest.BagMultiply(), NUnit.Samples.Money.MoneyTest.BagNegate(), NUnit.Samples.Money.MoneyTest.BagSimpleAdd(), NUnit.Samples.Money.MoneyTest.BagSubtract(), NUnit.Samples.Money.MoneyTest.BagSumAdd(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.BaseSetUpCalledFirstAndTearDownCalledLast(), NUnit.Framework.Assertions.EqualsFixture.Bug524CharIntComparision(), NUnit.Framework.Assertions.EqualsFixture.Bug575936Int32Int64Comparison(), IG.Test.TestMatrixOperations.ByHand_MultiplyMatrix(), IG.Test.TestMatrixOperations.ByHand_MultiplyMatrixVector(), IG.Test.TestMatrixOperations.ByHand_ScalarProduct(), IG.Test.TestMatrixOperations.ByHand_Transpose(), NUnit.Framework.Assertions.EqualsFixture.Byte(), NUnit.Framework.Internal.ResultStateTests.Cancelled_ReturnsResultStateWithPropertiesCorrectlySet(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableDecimals(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableDoubles(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableEnums(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableInts(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableMixedNumerics(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableStructs(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareWithTolerance(), NUnit.Framework.Internal.TestFixtureTests.CanConstructFrom(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertStringToDateTime(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertStringToNullableDateTime(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertStringToNullableTimeSpan(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertStringToTimeSpan(), NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomain(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanCreateUsingClrVersion(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanCreateUsingClrVersion(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanCreateUsingFrameworkVersion(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanCreateUsingFrameworkVersion(), NUnit.Framework.Attributes.PropertyAttributeTests.CanDeriveFromPropertyAttribute(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanDisplayFrameworkAsString(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanDisplayFrameworkAsString(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetMethodByName(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetMethodByNameAndArgs(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetMethodByNameAndBindingFlags(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetPropertyWithBindingFlags(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CanLoadVsProject(), NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchDictionaries_DifferentOrder(), NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchDictionaries_Failure(), NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchDictionaries_SameOrder(), NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchHashtables_DifferentOrder(), NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchHashtables_Failure(), NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchHashtables_SameOrder(), NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchHashtableWithDictionary(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanParseRuntimeFramework(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanParseRuntimeFramework(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanPassArrayAsArgument(), NUnitLite.Tests.CommandLineTests.CanRecognizeBooleanOptions(), NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeBooleanOptions(), NUnitLite.Tests.CommandLineTests.CanRecognizeIntOptions(), NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeIntOptions(), NUnitLite.Tests.CommandLineTests.CanRecognizeLowerCaseOptionValues(), NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeLowerCaseOptionValues(), NUnitLite.Tests.CommandLineTests.CanRecognizeStringOptions(), NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeStringOptions(), NUnit.ConsoleRunner.Tests.CommandLineTests.CanRegognizeInProcessOption(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.NestedFixture.CanSetCultureOnFixture(), NUnit.Framework.Attributes.ParameterizedTestFixtureTests.CanSpecifyCategory(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyCategory(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyDescription(), NUnit.Framework.Attributes.ParameterizedTestFixtureTests.CanSpecifyMultipleCategories(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyMultipleCategories(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyTestName_FixedText(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyTestName_WithMethodName(), NUnit.Framework.Attributes.RepeatAttributeTests.CategoryWorksWithRepeatedTest(), NUnit.Framework.Attributes.RetryAttributeTests.CategoryWorksWithRetry(), NUnit.Engine.Services.Tests.RecentFilesTests.CheckAddItems(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.CheckInheritedSetUpAndTearDownAreCalled(), NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains(), NUnit.Engine.Services.Tests.RecentFilesTests.CheckMockValues(), NUnit.Framework.Internal.PlatformDetectionTests.CheckPlatforms(), NUnit.Framework.Internal.ResultStateTests.ChildFailure_ReturnsResultStateWithPropertiesSet(), IG.Test.TestMatrixDecompositonMathNet.Cholesky_MathNet(), IG.Test.TestMatrixDecomposition.Cholesky_MatrixBase(), IG.Test.TestMatrixDecomposition.Cholesky_PositiveSemidefinite_MatrixBase(), NUnit.Framework.Internal.GenericTestMethodTests.Combinatorial_OneTypeParameterOnTwoArgs< T >(), NUnit.Framework.Internal.GenericTestMethodTests.Combinatorial_TwoTypeParameters< T1, T2 >(), NUnit.Engine.Services.Tests.RecentFilesTests.CountAtMax(), NUnit.Engine.Services.Tests.RecentFilesTests.CountAtMin(), NUnit.Engine.Services.Tests.RecentFilesTests.CountDefault(), NUnit.Engine.Services.Tests.RecentFilesTests.CountOverMax(), NUnit.Engine.Services.Tests.RecentFilesTests.CountUnderMin(), NUnit.Framework.Internal.UnexpectedExceptionTests.CustomExceptionIsHandled(), NUnit.Framework.Assertions.EqualsFixture.DateTimeEqual(), NUnit.Framework.Assertions.EqualsFixture.DateTimeNotEqual(), NUnit.Framework.Assertions.EqualsFixture.Decimal(), NUnitLite.Tests.CommandLineTests.DefaultResultSpecification(), NUnit.ConsoleRunner.Tests.CommandLineTests.DefaultResultSpecification(), NUnit.Framework.Attributes.DescriptionTests.Description(), NUnit.Framework.Attributes.DescriptionTests.DescriptionOnTestCase(), NUnit.Framework.Assertions.EqualsFixture.DirectoryInfoEqual(), NUnit.Framework.Assertions.EqualsFixture.DirectoryInfoNotEqual(), NUnit.Framework.Assertions.ArrayEqualsFixture.DoubleDimensionedArrays(), NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualMessageDisplaysAllDigits(), NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualMessageDisplaysDefaultTolerance(), NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualMessageDisplaysTolerance(), NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualWithNanDoesNotDisplayDefaultTolerance(), IG.Test.TestMatrixDecompositonMathNet.Eigen_MathNet(), NUnit.Engine.Services.Tests.RecentFilesTests.EmptyList(), NUnit.Framework.Assertions.EqualsFixture.EnumsEqual(), NUnit.Framework.Assertions.EqualsFixture.EnumsNotEqual(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTestsWithTolerance(), NUnit.Framework.Assertions.EqualsFixture.Equals(), NUnit.Samples.SimpleCSharpTest.Equals(), NUnit.Framework.Assertions.EqualsFixture.EqualsFail(), NUnit.Framework.Assertions.EqualsFixture.EqualsNaNFails(), NUnit.Framework.Assertions.EqualsFixture.EqualsNull(), NUnit.Framework.Assertions.EqualsFixture.EqualsSameTypes(), NUnit.Framework.Internal.ResultStateTests.Error_ReturnsResultStateWithPropertiesCorrectlySet(), NUnit.Framework.Attributes.MaxTimeTests.ErrorReportHasPriorityOverMaxTime(), NUnit.Framework.Tests.AssertSyntaxTests.ExactTypeTests(), NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectFailure(), NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePath(), NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePath(), NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePathAndFormat(), NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePathAndFormat(), NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePathAndTransform(), NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePathAndTransform(), NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePathUsingEqualSign(), NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePathUsingEqualSign(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.FailedBaseSetUpCausesDerivedSetUpAndTeardownToBeSkipped(), NUnit.Framework.Internal.UnexpectedExceptionTests.FailRecordsInnerException(), NUnit.Framework.Internal.UnexpectedExceptionTests.FailRecordsNestedInnerException(), NUnit.Framework.Internal.ResultStateTests.Failure_ReturnsResultStateWithPropertiesCorrectlySet(), NUnit.Framework.Attributes.MaxTimeTests.FailureReportHasPriorityOverMaxTime(), NUnitLite.Tests.CommandLineTests.FileNameWithoutResultOptionLooksLikeParameter(), NUnit.ConsoleRunner.Tests.CommandLineTests.FileNameWithoutResultOptionLooksLikeParameter(), NUnit.Framework.Assertions.ArrayEqualsFixture.FiveDimensionedArrays(), NUnit.Framework.Tests.Attributes.AuthorTests.FixtureAuthor(), NUnit.Framework.Attributes.DescriptionTests.FixtureDescription(), NUnit.Framework.Tests.Attributes.TestOfTests.FixtureTestOf(), NUnit.Framework.Internal.TestFixtureTests.FixtureUsingIgnoreAttributeIsIgnored(), NUnit.Framework.Internal.TestFixtureTests.FixtureUsingIgnorePropertyIsIgnored(), NUnit.Framework.Internal.TestFixtureTests.FixtureUsingIgnoreReasonPropertyIsIgnored(), NUnit.Framework.Assertions.EqualsFixture.Float(), NUnit.Framework.Assertions.EqualsFixture.FloatNotEqualMessageDisplaysAllDigits(), NUnit.Framework.Assertions.EqualsFixture.FloatNotEqualMessageDisplaysTolerance(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromSolutionWithDisabledProject(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromVSSolution2003(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromVSSolution2005(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromWebApplication(), NUnit.Core.Tests.Generic.SimpleGenericMethods.GenericTestMethodWithOneTypeParameter< T >(), NUnit.Core.Tests.Generic.SimpleGenericMethods.GenericTestMethodWithTwoTypeParameters< T1, T2 >(), NUnit.Core.Tests.Generic.SimpleGenericMethods.GenericTestMethodWithTwoTypeParameters_Reversed< T1, T2 >(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_OneElement(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_ThreeElements_DifferentDirectories(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_TwoElements_DifferentDirectories(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_TwoElements_SameDirectory(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetPrivateBinPath(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureSetup(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureTearDown(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureTearDownAfterErrorInFixtureSetUp(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureTearDownAfterErrorInTest(), NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInBothSetUpAndTearDown(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleExceptionInFixtureConstructor(), NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInSetUp(), NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInTearDown(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleIgnoreInFixtureSetup(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleSetUpAndTearDownWithTestInName(), NUnit.Framework.Attributes.TestCaseSourceTests.HandlesExceptionInTestCaseSource(), NUnit.Framework.Attributes.TestCaseSourceTests.HandlesExceptionInTestCaseSource_GuiDisplay(), NUnit.Framework.Attributes.TestCaseAttributeTests.HandlesParamsArrayAsLastArgument(), NUnit.Framework.Attributes.TestCaseAttributeTests.HandlesParamsArrayAsSoleArgument(), NUnit.Framework.Attributes.TestCaseAttributeTests.HandlesParamsArrayWithNoItemsAsLastArgument(), NUnit.Framework.Attributes.TestCaseAttributeTests.HandlesParamsArrayWithOneItemAsLastArgument(), NUnit.Framework.Attributes.TestCaseAttributeTests.HandlesParamsArrayWithOneItemAsSoleArgument(), NUnit.Framework.Assertions.EqualsFixture.IEquatableSuccess_OldSyntax(), NUnit.Framework.Internal.ResultStateTests.Ignored_ReturnsResultStateWithPropertiesCorrectlySet(), NUnit.Framework.Attributes.TestCaseSourceTests.IgnoreTakesPrecedenceOverExpectedException(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWithUserMessage(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWithUserMessage_ArrayOfArgs(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWithUserMessage_OneArg(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWithUserMessage_ThreeArgs(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWorksForTestCase(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWorksForTestSuite(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWorksFromSetUp(), NUnit.Framework.Internal.ResultStateTests.Inconclusive_ReturnsResultStateWithPropertiesCorrectlySet(), NUnit.Framework.Attributes.SetCultureAttributeTests.NestedBehavior.InheritedRussian(), NUnit.Framework.Attributes.SetCultureAttributeTests.NestedBehavior.InheritedRussianWithUIFrench(), NUnit.Framework.Attributes.AttributeInheritanceTests.InheritedTestAttributeIsRecognized(), NUnit.Framework.Assertions.EqualsFixture.Int(), NUnit.Framework.Attributes.TestCaseAttributeTests.IntegerDivisionWithResultPassedToTest(), NUnit.Framework.Assertions.EqualsFixture.IntegerEquals(), NUnit.Framework.Assertions.EqualsFixture.IntegerLongComparison(), NUnit.Framework.Internal.SetUpFixtureTests.InvalidAssemblySetUpFixtureIsLoadedCorrectly(), NUnitLite.Tests.CommandLineTests.InvalidCommandLineParms(), NUnit.ConsoleRunner.Tests.CommandLineTests.InvalidCommandLineParms(), NUnitLite.Tests.CommandLineTests.InvalidOption(), NUnit.ConsoleRunner.Tests.CommandLineTests.InvalidOption(), NUnit.TestUtilities.TestAssert.IsNotRunnable(), NUnit.TestUtilities.TestAssert.IsRunnable(), NUnit.Framework.Assertions.ArrayEqualsFixture.JaggedArrays(), NUnit.Framework.Internal.ResultStateTests.Label_ConstructorWithOneArguments_ReturnsStringEmpty(), NUnit.Framework.Internal.ResultStateTests.Label_ConstructorWithTwoArguments_ReturnsConstructorArgumentLabel(), NUnit.Framework.Internal.ResultStateTests.Label_ConstructorWithTwoArgumentsLabelArgumentIsNull_ReturnsEmptyString(), IG.Test.TestMatrixDecomposition.LDLT_Indefinite_MatrixBase(), IG.Test.TestMatrixDecomposition.LDLT_MatrixBase(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadEmptyConfigs(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadNormalProject(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadProjectWithComplexSettings(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadProjectWithManualBinPath(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.LoadWithFrenchCanadianCulture(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.LoadWithFrenchCulture(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.LoadWithRussianCulture(), IG.Test.TestMatrixDecompositonMathNet.LU_MathNet(), IG.Test.TestMatrixDecomposition.LU_MatrixBase(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.MakeSureSetUpAndTearDownAreCalled(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.MakeSureSetUpAndTearDownAreCalledOnFixtureWithTestCases(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.MakeSureSetUpAndTearDownAreCalledOnFixtureWithTheories(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.MakeSureSetUpAndTearDownAreNotCalledOnExplicitFixture(), NUnit.Core.Tests.ParameterizedTestFixtureWithTypeAsArgument.MakeSureTypeIsInSystemNamespace(), NUnit.Framework.Attributes.ParameterizedTestFixtureWithTypeAsArgument.MakeSureTypeIsInSystemNamespace(), NUnit.Framework.Attributes.MaxTimeTests.MaxTimeExceeded(), NUnit.Framework.Attributes.MaxTimeTests.MaxTimeExceededOnTestCase(), NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodWithInstanceFieldAsSource(), NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodWithInstanceMethodAsSource(), NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodWithInstancePropertyAsSource(), NUnit.Framework.Attributes.ValueSourceTests.MethodWithValueSourceInstanceField(), NUnit.Framework.Attributes.ValueSourceTests.MethodWithValueSourceInstanceMethod(), NUnit.Framework.Attributes.ValueSourceTests.MethodWithValueSourceInstanceProperty(), NUnit.Framework.Constraints.FloatingPointNumericsTests.MirroredDoubleReinterpretation(), NUnit.Framework.Constraints.FloatingPointNumericsTests.MirroredFloatReinterpretation(), NUnit.Framework.Constraints.FloatingPointNumericsTests.MirroredIntegerReinterpretation(), NUnit.Framework.Constraints.FloatingPointNumericsTests.MirroredLongReinterpretation(), NUnitLite.Tests.CommandLineTests.MissingValuesAreReported(), NUnit.ConsoleRunner.Tests.CommandLineTests.MissingValuesAreReported(), NUnit.Samples.Money.MoneyTest.MixedSimpleAdd(), NUnit.Samples.Money.MoneyTest.MoneyBagHash(), NUnit.Samples.Money.MoneyTest.MoneyHash(), NUnit.Framework.Attributes.ValueSourceTests.MultipleArguments(), NUnit.ConsoleRunner.Tests.MakeTestPackageTests.MultipleAssemblies(), IG.Test.TestMatrixOperations.MultiplyMatMatTransp(), IG.Test.TestMatrixOperations.MultiplyVectorMatrixVector(), NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureReplacesNamespaceNodeInTree(), NUnit.Framework.Assertions.EqualsFixture.NanEqualsFails(), NUnit.Framework.Assertions.EqualsFixture.NanEqualsNaNSucceeds(), NUnit.Framework.Assertions.EqualsFixture.NegInfinityEqualsInfinity(), NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.NoConfigurations(), NUnit.ConsoleRunner.Tests.CommandLineTests.NoInputFiles(), NUnitLite.Tests.CommandLineTests.NoInputFiles(), NUnitLite.Tests.CommandLineTests.NoResultSuppressesAllResultSpecifications(), NUnit.ConsoleRunner.Tests.CommandLineTests.NoResultSuppressesAllResultSpecifications(), NUnitLite.Tests.CommandLineTests.NoResultSuppressesDefaultResultSpecification(), NUnit.ConsoleRunner.Tests.CommandLineTests.NoResultSuppressesDefaultResultSpecification(), NUnit.Samples.Money.MoneyTest.Normalize(), NUnit.Samples.Money.MoneyTest.Normalize2(), NUnit.Samples.Money.MoneyTest.Normalize3(), NUnit.Samples.Money.MoneyTest.Normalize4(), NUnit.Framework.Internal.ResultStateTests.NotRunnable_ReturnsResultStateWithPropertiesCorrectlySet(), NUnit.Framework.Attributes.TestCaseAttributeTests.NullableIntegerDivisionWithResultPassedToTest(), NUnit.Framework.Attributes.TestCaseAttributeTests.NullableSimpleFormalParametersWithArgument(), TstPerson.NUnit_Example_BalanceAfterCarPurchase(), TstPerson.NUnit_Example_BalanceBeforeCarPurchase(), TstPerson.NUnit_Example_IsAgeEqual(), TstPerson.NUnit_Example_IsNameJohnAbraham(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtRobustD7(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.OverriddenSetUpAndTearDownAreNotCalled(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_Exclude(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_Include(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_IncludeAndExclude(), NUnit.Framework.Assertions.EqualsFixture.PosInfinityEqualsInfinity(), NUnit.Framework.Assertions.EqualsFixture.PosInfinityNotEquals(), NUnit.Framework.Assertions.EqualsFixture.PosInfinityNotEqualsNegInfinity(), NUnit.Samples.Money.MoneyTest.Print(), NUnit.Framework.Attributes.PropertyAttributeTests.PropertiesWithNumericValues(), NUnit.Framework.Attributes.PropertyAttributeTests.PropertyWorksOnFixtures(), IG.Test.TestMatrixDecompositonMathNet.QR_MathNet(), IG.Test.TestMatrixDecomposition.Qr_MatrixBase(), IG.Test.TestMatrixDecomposition.QrGrammSchmidt_MatrixBase(), NUnit.Framework.Attributes.DescriptionTests.ReflectionTest(), NUnit.Framework.Tests.Attributes.AuthorTests.ReflectionTest(), NUnit.Framework.Tests.Attributes.TestOfTests.ReflectionTest(), NUnit.Framework.Attributes.RepeatAttributeTests.RepeatWorksAsExpected(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.RerunFixtureAfterSetUpFixed(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.RerunFixtureAfterTearDownFixed(), NUnitLite.Tests.CommandLineTests.ResultOptionMayBeRepeated(), NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionMayBeRepeated(), NUnitLite.Tests.CommandLineTests.ResultOptionWithFilePath(), NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithFilePath(), NUnitLite.Tests.CommandLineTests.ResultOptionWithFilePathAndFormat(), NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithFilePathAndFormat(), NUnitLite.Tests.CommandLineTests.ResultOptionWithFilePathAndTransform(), NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithFilePathAndTransform(), NUnitLite.Tests.CommandLineTests.ResultOptionWithoutFileNameIsInvalid(), NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithoutFileNameIsInvalid(), NUnit.Framework.Attributes.RetryAttributeTests.RetryWorksAsExpected(), NUnit.Framework.Tests.Attributes.AuthorTests.SeparateAuthorAttribute(), NUnit.Framework.Tests.Attributes.AuthorTests.SeparateAuthorWithEmailAttribute(), NUnit.Framework.Attributes.DescriptionTests.SeparateDescriptionAttribute(), NUnit.Framework.Tests.Attributes.TestOfTests.SeparateTestOfAttribute(), NUnit.Framework.Tests.Attributes.TestOfTests.SeparateTestOfStringMethod(), NUnit.Framework.Internal.TestExecutionContextTests.SetAndRestoreCurrentCulture(), NUnit.Framework.Internal.TestExecutionContextTests.SetAndRestoreCurrentPrincipal(), NUnit.Framework.Internal.TestExecutionContextTests.SetAndRestoreCurrentUICulture(), NUnit.Framework.Attributes.SetCultureAttributeTests.SetBothCulturesToFrench(), NUnit.Framework.Attributes.SetCultureAttributeTests.SetBothCulturesToFrenchCanadian(), NUnit.Framework.Attributes.SetCultureAttributeTests.SetBothCulturesToRussian(), NUnit.Framework.Attributes.SetCultureAttributeTests.SetMixedCulturesToFrenchAndUIFrenchCanadian(), NUnit.Framework.Attributes.SetCultureAttributeTests.SetMixedCulturesToRussianAndUIEnglishUS(), NUnit.Framework.Attributes.SetCultureAttributeTests.SetUICultureOnlyToFrench(), NUnit.Framework.Attributes.SetCultureAttributeTests.SetUICultureOnlyToFrenchCanadian(), NUnit.Framework.Attributes.SetCultureAttributeTests.SetUICultureOnlyToRussian(), NUnit.Framework.Internal.SetUpTearDownTests.SetUpAndTearDownCounter(), NUnit.Framework.Assertions.EqualsFixture.Short(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoOutput(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenOutputIsEmpty(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenParallelizedTestsFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenTestsFromNUnit2(), NUnitLite.Tests.CommandLineTests.ShouldSetTeamCityFlagAccordingToArgsAndDefauls(), NUnit.ConsoleRunner.Tests.CommandLineTests.ShouldSetTeamCityFlagAccordingToArgsAndDefauls(), NUnit.Samples.Money.MoneyTest.SimpleAdd(), NUnit.Samples.Money.MoneyTest.SimpleBagAdd(), NUnit.Samples.Money.MoneyTest.SimpleMultiply(), NUnit.Samples.Money.MoneyTest.SimpleNegate(), NUnit.Samples.Money.MoneyTest.SimpleSubtract(), NUnit.ConsoleRunner.Tests.MakeTestPackageTests.SingleAssembly(), NUnit.Common.Tests.TestNameParserTests.SingleName(), NUnit.Framework.Assertions.EqualsFixture.SinglePosInfinityNotEqualsNegInfinity(), NUnit.Framework.Internal.ResultStateTests.Site_ConstructorWithOneArguments_ReturnsTest(), NUnit.Framework.Internal.ResultStateTests.Site_ConstructorWithThreeArguments_ReturnsSite(), NUnit.Framework.Internal.ResultStateTests.Site_ConstructorWithTwoArguments_ReturnsTest(), NUnit.Framework.Internal.ResultStateTests.Skipped_ReturnsResultStateWithPropertiesCorrectlySet(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceCanBeInstanceOfIEnumerable(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceCanBeStaticField(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceCanBeStaticMethod(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceCanBeStaticProperty(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceMayBeInAnotherClass(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceMayReturnArgumentsAsIntArray(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceMayReturnArgumentsAsObjectArray(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceMayReturnSinglePrimitiveArgumentAlone(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceUsingInstanceFieldIsNotRunnable(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceUsingInstanceMethodIsNotRunnable(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceUsingInstancePropertyIsNotRunnable(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.StaticBaseSetUpCalledFirstAndTearDownCalledLast(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.StaticClassSetUpAndTearDownAreCalled(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.StaticSetUpAndTearDownAreCalled(), NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.StaticTestMethodWithArgumentsProvided(), NUnit.Framework.Internal.ResultStateTests.Status_ConstructorWithOneArguments_ReturnsConstructorArgumentStatus(), NUnit.Framework.Internal.ResultStateTests.Status_ConstructorWithTwoArguments_ReturnsConstructorArgumentStatus(), NUnit.Framework.Assertions.EqualsFixture.String(), NUnit.Framework.Internal.ResultStateTests.Success_ReturnsResultStateWithPropertiesCorrectlySet(), NUnit.Framework.Internal.TestResultTests.SuiteResultBasicInfo(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.FailedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.SuiteResultIsIgnored(), NUnit.Framework.Internal.DefaultResultTests.SuiteResultIsInconclusive(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultIsInconclusive(), NUnit.Framework.Internal.SuccessResultTests.SuiteResultIsSuccess(), NUnit.Framework.Internal.TestResultTests.SuiteResultXmlNodeBasicInfo(), NUnit.Framework.Internal.MixedResultTests.SuiteResultXmlNodeHasFourChildTests(), NUnit.Framework.Internal.DefaultResultTests.SuiteResultXmlNodeHasOneChildTest(), NUnit.Framework.Internal.SuccessResultTests.SuiteResultXmlNodeHasOneChildTest(), NUnit.Framework.Internal.IgnoredResultTests.SuiteResultXmlNodeHasOneChildTest(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultXmlNodeHasOneChildTest(), NUnit.Framework.Internal.FailedResultTests.SuiteResultXmlNodeHasOneChildTest(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultXmlNodeHasOneChildTest(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultXmlNodeIsFailure(), NUnit.Framework.Internal.FailedResultTests.SuiteResultXmlNodeIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultXmlNodeIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.SuiteResultXmlNodeIsIgnored(), NUnit.Framework.Internal.DefaultResultTests.SuiteResultXmlNodeIsInconclusive(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultXmlNodeIsInconclusive(), NUnit.Framework.Internal.SuccessResultTests.SuiteResultXmlNodeIsSuccess(), IG.Test.TestCrypto.SymmetricEncryptionFilesPlain(), IG.Test.TestCrypto.SymmetricEncryptionStringBase(), IG.Test.TestCrypto.SymmetricEncryptionStringPlain(), IG.Test.TestCrypto.SymmetricEncryptionStringPlainRandom(), IG.Test.TestCrypto.Test_EncryptStringTobytes_DecryptStringFromBytes(), NUnit.Framework.Attributes.TestCaseSourceTests.TestAttributeIsOptional(), NUnit.Framework.Internal.GenericTestMethodTests.TestCase_OneTypeParameterOnTwoArgs< T >(), NUnit.Framework.Internal.GenericTestMethodTests.TestCase_TwoTypeParameters< T1, T2 >(), NUnit.Framework.Internal.GenericTestMethodTests.TestCase_TwoTypeParameters_Reversed< T1, T2 >(), NUnit.Framework.Attributes.TestCaseAttributeTests.TestCaseRunnableState(), NUnit.Framework.Internal.GenericTestMethodTests.TestCaseSource_OneTypeParameterOnTwoArgs< T >(), NUnit.Framework.Internal.GenericTestMethodTests.TestCaseSource_TwoTypeParameters< T1, T2 >(), NUnit.Core.Tests.Generic.SimpleGenericFixture< TList >.TestCollectionCount(), NUnit.Framework.Internal.GenericTestFixture_IList< T >.TestCollectionCount(), NUnit.Core.Tests.ParameterizedTestFixture.TestEquality(), NUnit.Framework.Attributes.ParameterizedTestFixture.TestEquality(), NUnit.Framework.Internal.ResultStateTests.TestEquality_StatusAndLabelSpecified(), NUnit.Framework.Internal.ResultStateTests.TestEquality_StatusAndSiteSpecified(), NUnit.Framework.Internal.ResultStateTests.TestEquality_StatusLabelAndSiteSpecified(), NUnit.Framework.Internal.ResultStateTests.TestEquality_StatusSpecified(), NUnit.Framework.Attributes.TestCaseSourceTests.TestMayUseMultipleSourceAttributes(), NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithArgumentsProvided(), NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithConvertibleArguments(), NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithMultipleTestCases(), NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithNonConvertibleArguments(), NUnit.Framework.Tests.Attributes.TestOfTests.TestOf(), NUnit.Framework.Tests.Attributes.TestOfTests.TestOfOnTestCase(), NUnit.Framework.Internal.TestResultTests.TestResultBasicInfo(), NUnit.Framework.Internal.FailedResultTests.TestResultIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.TestResultIsIgnored(), NUnit.Framework.Internal.DefaultResultTests.TestResultIsInconclusive(), NUnit.Framework.Internal.InconclusiveResultTests.TestResultIsInconclusive(), NUnit.Framework.Internal.NotRunnableResultTests.TestResultIsNotRunnable(), NUnit.Framework.Internal.SuccessResultTests.TestResultIsSuccess(), NUnit.Framework.Internal.TestResultTests.TestResultXmlNodeBasicInfo(), NUnit.Framework.Internal.FailedResultTests.TestResultXmlNodeIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.TestResultXmlNodeIsIgnored(), NUnit.Framework.Internal.DefaultResultTests.TestResultXmlNodeIsInconclusive(), NUnit.Framework.Internal.InconclusiveResultTests.TestResultXmlNodeIsInconclusive(), NUnit.Framework.Internal.NotRunnableResultTests.TestResultXmlNodeIsNotRunnable(), NUnit.Framework.Internal.SuccessResultTests.TestResultXmlNodeIsSuccess(), NUnit.Framework.Attributes.ChangesMadeInFixtureSetUp.TestThatChangesPersistUsingSameThread(), NUnit.Framework.Attributes.ChangesMadeInFixtureSetUp.TestThatChangesPersistUsingSeparateThread(), NUnit.Framework.Attributes.TestCaseSourceTests.TestWithFourArguments(), NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.ThreadedAssertProc(), NUnit.Framework.Syntax.ThrowsTests.ThrowsException(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionInstanceOf(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionTypeOf(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionTypeOfAndConstraint(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionWithConstraint(), NUnit.Framework.Syntax.ThrowsTests.ThrowsInstanceOf(), NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOf(), NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOfAndConstraint(), NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOfWithConstraint(), NUnitLite.Tests.CommandLineTests.TimeoutCausesErrorIfValueIsNotInteger(), NUnit.ConsoleRunner.Tests.CommandLineTests.TimeoutCausesErrorIfValueIsNotInteger(), NUnitLite.Tests.CommandLineTests.TimeoutIsMinusOneIfNoOptionIsProvided(), NUnit.ConsoleRunner.Tests.CommandLineTests.TimeoutIsMinusOneIfNoOptionIsProvided(), NUnitLite.Tests.CommandLineTests.TimeoutParsesIntValueCorrectly(), NUnit.ConsoleRunner.Tests.CommandLineTests.TimeoutParsesIntValueCorrectly(), NUnit.Framework.Internal.ResultStateTests.ToString_Constructor_ReturnsExpectedString(), NUnit.Framework.Assertions.ArrayEqualsFixture.TripleDimensionedArrays(), NUnit.Common.Tests.TestNameParserTests.TwoNames(), NUnit.Framework.Assertions.EqualsFixture.UInt(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceCanBeStaticField(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceCanBeStaticMethod(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceCanBeStaticProperty(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayBeInAnotherClass(), NUnit.TestUtilities.SimpleEventRecorder.Verify(), NUnit.Engine.Tests.AsyncTestEngineResultTests.Wait_ReturnsFalseTillTestCompletes(), NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.WaitAll_SingleThread_MultipleTasks(), NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.WaitAll_TwoThreads_MultipleTasks(), NUnit.ConsoleRunner.Tests.MakeTestPackageTests.WhenNoOptionsAreSpecified_PackageContainsWorkDirectorySettingOnly(), NUnit.ConsoleRunner.Tests.MakeTestPackageTests.WhenOptionIsSpecified_PackageIncludesSetting(), NUnitLite.Tests.MakeRunSettingsTests.WhenSeedIsSpecified_RunSettingsIncludeIt(), NUnitLite.Tests.MakeRunSettingsTests.WhenTimeoutIsSpecified_RunSettingsIncludeIt(), NUnitLite.Tests.MakeRunSettingsTests.WhenWorkDirectoryIsSpecified_RunSettingsIncludeIt(), and NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.WithUnmanagedCpp().
static void NUnit.Framework.Assert.AreEqual (double expected, double actual, double delta) inline static
Verifies that two doubles are equal considering a delta. If the expected value is infinity then the delta value is ignored. If they are not equal then an AssertionException is thrown.
Parameters
expected The expected value
actual The actual value
delta The maximum acceptable difference between the the expected and the actual
static void NUnit.Framework.Assert.AreEqual (double expected, double? actual, double delta, string message, params object[] args) inline static
Verifies that two doubles are equal considering a delta. If the expected value is infinity then the delta value is ignored. If they are not equal then an AssertionException is thrown.
Parameters
expected The expected value
actual The actual value
delta The maximum acceptable difference between the the expected and the actual
message The message to display in case of failure
args Array of objects to be used in formatting the message
static void NUnit.Framework.Assert.AreEqual (double expected, double? actual, double delta) inline static
Verifies that two doubles are equal considering a delta. If the expected value is infinity then the delta value is ignored. If they are not equal then an AssertionException is thrown.
Parameters
expected The expected value
actual The actual value
delta The maximum acceptable difference between the the expected and the actual
static void NUnit.Framework.Assert.AreEqual (object expected, object actual, string message, params object[] args) inline static
Verifies that two objects are equal. Two objects are considered equal if both are null, or if both have the same value. NUnit has special semantics for some object types. If they are not equal an AssertionException is thrown.
Parameters
expected The value that is expected
actual The actual value
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.AreEqual (object expected, object actual) inline static
Verifies that two objects are equal. Two objects are considered equal if both are null, or if both have the same value. NUnit has special semantics for some object types. If they are not equal an AssertionException is thrown.
Parameters
expected The value that is expected
actual The actual value
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.AreNotEqual (object expected, object actual, string message, params object[] args) inline static
Verifies that two objects are not equal. Two objects are considered equal if both are null, or if both have the same value. NUnit has special semantics for some object types. If they are equal an AssertionException is thrown.
Parameters
expected The value that is expected
actual The actual value
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Assertions.ArrayNotEqualFixture.ArraysDeclaredAsDifferentTypes(), NUnit.Framework.Assertions.NotEqualFixture.ArraysNotEqual(), NUnit.Framework.Assertions.NotEqualFixture.ArraysNotEqualFails(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysWithDifferentDimensionsMatchedAsCollection(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysWithDifferentRanksComparedAsCollection(), NUnit.Framework.Assertions.StringAssertTests.DifferentEncodingsOfSameStringAreNotEqual(), NUnit.Framework.Assertions.ArrayNotEqualFixture.DifferentLengthArrays(), NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualMessageDisplaysAllDigits(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTests(), NUnit.Framework.Tests.AssertSyntaxTests.ExactTypeTests(), NUnit.Framework.Assertions.EqualsFixture.FloatNotEqualMessageDisplaysAllDigits(), NUnit.Framework.Assertions.NotEqualFixture.NotEqual(), NUnit.Framework.Assertions.NotEqualFixture.NotEqualFails(), NUnit.Framework.Assertions.NotEqualFixture.NotEqualSameTypes(), NUnit.Framework.Assertions.NotEqualFixture.NullEqualsNull(), NUnit.Framework.Assertions.NotEqualFixture.NullNotEqualToNonNull(), NUnit.Framework.Attributes.CombinatorialTests.RandomArgsAreIndependent(), NUnit.Framework.Assertions.ArrayNotEqualFixture.SameLengthDifferentContent(), IG.Test.TestCrypto.SymmetricEncryptionFilesPlain(), NUnit.Framework.Internal.ResultStateTests.TestEquality_LabelDiffers(), NUnit.Framework.Internal.ResultStateTests.TestEquality_Null(), NUnit.Framework.Internal.ResultStateTests.TestEquality_SiteDiffers(), NUnit.Framework.Internal.ResultStateTests.TestEquality_StatusDiffers(), NUnit.Framework.Internal.ResultStateTests.TestEquality_WrongType(), NUnit.Core.Tests.ParameterizedTestFixture.TestInequality(), NUnit.Framework.Attributes.ParameterizedTestFixture.TestInequality(), and NUnit.Framework.Assertions.NotEqualFixture.UInt().
static void NUnit.Framework.Assert.AreNotEqual (object expected, object actual) inline static
Verifies that two objects are not equal. Two objects are considered equal if both are null, or if both have the same value. NUnit has special semantics for some object types. If they are equal an AssertionException is thrown.
Parameters
expected The value that is expected
actual The actual value
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.AreSame (object expected, object actual, string message, params object[] args) inline static
Asserts that two objects refer to the same object. If they are not the same an AssertionException is thrown.
Parameters
expected The expected object
actual The actual object
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.SameAs(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Assertions.SameFixture.Same(), NUnit.Framework.Assertions.SameFixture.SameFails(), and NUnit.Framework.Assertions.SameFixture.SameValueTypes().
static void NUnit.Framework.Assert.AreSame (object expected, object actual) inline static
Asserts that two objects refer to the same object. If they are not the same an AssertionException is thrown.
Parameters
expected The expected object
actual The actual object
References NUnit.Framework.Is.SameAs(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.AreNotSame (object expected, object actual, string message, params object[] args) inline static
Asserts that two objects do not refer to the same object. If they are the same an AssertionException is thrown.
Parameters
expected The expected object
actual The actual object
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Assertions.NotSameFixture.NotSame(), and NUnit.Framework.Assertions.NotSameFixture.NotSameFails().
static void NUnit.Framework.Assert.AreNotSame (object expected, object actual) inline static
Asserts that two objects do not refer to the same object. If they are the same an AssertionException is thrown.
Parameters
expected The expected object
actual The actual object
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.AssertDoublesAreEqual (double expected, double actual, double delta, string message, object[] args) inline static protected
Helper for Assert.AreEqual(double expected, double actual, ...) allowing code generation to work consistently.
Parameters
expected The expected value
actual The actual value
delta The maximum acceptable difference between the the expected and the actual
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IncrementAssertCount () inline static private
References NUnit.Framework.Internal.TestExecutionContext.CurrentContext, and NUnit.Framework.Internal.TestExecutionContext.IncrementAssertCount().
static Exception NUnit.Framework.Assert.Throws (IResolveConstraint expression, TestDelegate code, string message, params object[] args) inline static
Verifies that a delegate throws a particular exception when called.
Parameters
expression A constraint to be satisfied by the exception
code A TestSnippet delegate
message The message that will be displayed on failure
args Arguments to be used in formatting the message
Referenced by IG.Test.TestMatrixDecompositonMathNet.AccessOutOfRangeMatrix1(), IG.Test.TestMatrixOperations.AccessOutOfRangeMatrix1(), IG.Test.TestMatrixOperations.AccessOutOfRangeMatrix2(), IG.Test.TestMatrixOperations.AccessOutOfRangeMatrix3(), IG.Test.TestMatrixOperations.AccessOutOfRangeMatrix4(), IG.Test.TestVectorOperations.AccessOutOfRangeVector1(), IG.Test.TestMatrixOperations.AccessOutOfRangeVector1(), IG.Test.TestVectorOperations.AccessOutOfRangeVector2(), IG.Test.TestMatrixOperations.AccessOutOfRangeVector2(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ActualArrayIsLonger(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreInRangeFailureMessage(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreInstancesOfTypeFailureMessage(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreNotNullFails(), NUnit.Framework.Assertions.CollectionAssertTest.AreEqual_UsingIterator_Fails(), NUnit.Framework.Assertions.CollectionAssertTest.AreEqual_UsingLinqQuery_Fails(), NUnit.Framework.Assertions.CollectionAssertTest.AreEqualFail(), NUnit.Framework.Assertions.CollectionAssertTest.AreEqualFailCount(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWhenOneIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.AreEqualFailsWithDirectoryInfos(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithFileInfos(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithFiles(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithStreams(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithTextFilesAfterReadingBothFiles(), NUnit.Framework.Assertions.CollectionAssertTest.AreNotEqual_Fails(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWhenBothAreNull(), NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualFailsWithDirectoryInfos(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithFileInfos(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithFiles(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithStreams(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualIteratesOverTheEntireFileAndFails(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArrayAndCollection_Failure(), NUnit.Framework.Assertions.ListContentsTests.ArrayFails(), NUnit.Framework.Assertions.ListContentsTests.ArrayListFails(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysDeclaredAsDifferentTypes(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysHaveDifferentRanks(), NUnit.Framework.Assertions.NotEqualFixture.ArraysNotEqualFails(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysWithDifferentDimensionsAsCollection(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysWithDifferentRanksAsCollection(), NUnit.Framework.Assertions.AssertThatTests.AssertThatWithFalseLambda(), NUnit.Framework.Assertions.AssertThrowsTests.BaseExceptionThrown(), NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchDictionaries_Failure(), NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchHashtables_Failure(), NUnit.Framework.Assertions.StringAssertTests.CaseInsensitiveCompareFails(), IG.Test.TestMatrixDecomposition.Cholesky_PositiveSemidefinite_MatrixBase(), NUnit.Framework.Assertions.StringAssertTests.ContainsFails(), NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_EmptyICollection(), NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_EmptyIList(), NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_ICollection(), NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_ILIst(), NUnit.Framework.Assertions.AssertThrowsTests.CorrectExceptionIsReturnedToMethod(), NUnit.Framework.Assertions.AssertThrowsTests.CorrectExceptionThrown(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_WithoutLoad_ThrowsInvalidOperation(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperation(), NUnit.Framework.Assertions.EqualsFixture.DateTimeNotEqual(), NUnit.Framework.Assertions.AssertThrowsTests.DerivedExceptionThrown(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.DifferentArrayTypesEqualFails(), NUnit.Framework.Assertions.EqualsFixture.DirectoryInfoNotEqual(), NUnit.Framework.Assertions.CollectionAssertTest.DoesNotContain_Fails(), NUnit.Framework.Assertions.StringAssertTests.DoesNotContainFails(), NUnit.Framework.Assertions.StringAssertTests.DoesNotEndWithFails(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenDirectoryInfoExists(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenDirectoryInfoIsNull(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenFileInfoExists(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenFileInfoIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenStringExists(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenStringExists(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenStringIsEmpty(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenStringIsEmpty(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenStringIsNull(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenStringIsNull(), NUnit.Framework.Assertions.StringAssertTests.DoesNotStartWithFails(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.DoubleDimensionedArrays(), NUnit.Framework.Attributes.RangeAttributeTests.DoubleRangeAndNegativeStep(), NUnit.Framework.Attributes.RangeAttributeTests.DoubleRangeAndStep_Reversed(), NUnit.Framework.Attributes.RangeAttributeTests.DoubleRangeAndZeroStep(), NUnit.Framework.Assertions.ListContentsTests.EmptyArrayFails(), NUnit.Framework.Assertions.StringAssertTests.EndsWithFails(), NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.EnqueueCannotBeCalledAfterWorkHasStarted(), NUnit.Framework.Assertions.EqualsFixture.EnumsNotEqual(), NUnit.Framework.Assertions.EqualsFixture.EqualsFail(), NUnit.Framework.Assertions.EqualsFixture.EqualsNaNFails(), NUnit.Framework.Assertions.EqualsFixture.EqualsThrowsException(), NUnit.Framework.Assertions.CollectionAssertTest.EquivalentFailOne(), NUnit.Framework.Assertions.CollectionAssertTest.EquivalentFailTwo(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfDaysPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfHoursPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfMillisecondsPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfMinutesPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfPercentPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfSecondsPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfTicksPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfUlpsIsUsedOnDecimal(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfUlpsIsUsedOnIntegralType(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfUlpsPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorWithPercentAndUlpsToleranceModes(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorWithUlpsAndPercentToleranceModes(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyOneItemMatchFails(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyTwoItemsMatchFails(), NUnit.Framework.Assertions.TypeAssertTests.ExactTypeFails(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenDirectoryInfoDoesNotExist(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenDirectoryInfoIsNull(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenFileInfoDoesNotExist(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenFileInfoIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenStringDoesNotExist(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenStringDoesNotExist(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenStringIsEmpty(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenStringIsEmpty(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenStringIsNull(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenStringIsNull(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ExpectedArrayIsLonger(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Framework.Constraints.EqualTests.FailedStringMatchShowsFailurePosition(), NUnit.Framework.Constraints.NumericsTests.FailsOnDecimalAbovePercentage(), NUnit.Framework.Constraints.NumericsTests.FailsOnDecimalBelowPercentage(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.FailsOnDoublesOutsideOfRelativeTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.FailsOnDoublesOutsideOfUlpTolerance(), NUnit.Framework.Constraints.NumericsTests.FailsOnIntegralsOutsideOfPercentage(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.FailsOnSinglesOutsideOfRelativeTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.FailsOnSinglesOutsideOfUlpTolerance(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenDirectoryInfoIsNull(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenFileInfoIsNull(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenIgnoreDirectoriesIsTrueWithDirectoryInfo(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenIgnoreFilesIsTrueWithFileInfo(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenNotStringOrDirectoryInfo(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenStringIsEmpty(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenStringIsNull(), NUnit.Framework.Constraints.CollectionEqualsTests.FailureMatchingArrayAndCollection(), NUnit.Framework.Assertions.GreaterFixture.FailureMessage(), NUnit.Framework.Assertions.LessEqualFixture.FailureMessage(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.FailureOnSingleDimensionedArrays(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualLambdaAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualLambdaAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualLambdaAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_Boolean(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_BooleanWithMessage(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_BooleanWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_DelegateAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_DelegateAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_DelegateAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_Boolean(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanLambda(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanLambdaWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanLambdaWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraintWithMessageAndArgs(), NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.FileNotFoundError(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.FiveDimensionedArrays(), NUnit.Framework.Attributes.RangeAttributeTests.FloatRangeAndNegativeStep(), NUnit.Framework.Attributes.RangeAttributeTests.FloatRangeAndStep_Reversed(), NUnit.Framework.Attributes.RangeAttributeTests.FloatRangeAndZeroStep(), IG.Test.TestCryptoIGLib.IGLibSaltOutOfRange1(), IG.Test.TestCryptoIGLib.IGLibSaltOutOfRange2(), IG.Test.TestCryptoIGLib.IGLibSaltOutOfRange3(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithInvalidDateThrowsException(), NUnit.Framework.Attributes.RangeAttributeTests.IntRangeAndNegativeStep(), NUnit.Framework.Attributes.RangeAttributeTests.IntRangeAndStep_Reversed(), NUnit.Framework.Attributes.RangeAttributeTests.IntRangeAndZeroStep(), NUnit.Framework.Constraints.ComparisonConstraintTestBase.InvalidDataThrowsArgumentException(), NUnit.Framework.Constraints.RangeConstraintTest.InvalidDataThrowsArgumentException(), NUnit.Framework.Constraints.EmptyConstraintTest.InvalidDataThrowsArgumentException(), NUnit.Framework.Constraints.PropertyTest.InvalidDataThrowsArgumentException(), NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.InvalidXmlFormat(), NUnit.Framework.Assertions.TypeAssertTests.IsAssignableFromFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNonEmptyArray(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNonEmptyIEnumerable(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNullString(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnString(), NUnit.Framework.Assertions.ConditionAssertTests.IsFalseFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsFalseFailsForNullable(), NUnit.Framework.Assertions.TypeAssertTests.IsInstanceOfFails(), NUnit.Framework.Assertions.StringAssertTests.IsMatchFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsNaNFails(), NUnit.Framework.Assertions.TypeAssertTests.IsNotAssignableFromFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyArray(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyArrayList(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyHashTable(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyIEnumerable(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyString(), NUnit.Framework.Assertions.TypeAssertTests.IsNotInstanceOfFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotNullFails(), NUnit.Framework.Assertions.CollectionAssertTest.IsNotSubsetOf_Fails(), NUnit.Framework.Assertions.ConditionAssertTests.IsNullFails(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_AtLeastOneArgMustImplementIComparable(), NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_ContainedTypesMustBeCompatible(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_Fails(), NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_Fails(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_Handles_null(), NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_Handles_null(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_TypesMustBeComparable(), NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_TypesMustImplementIComparable(), NUnit.Framework.Assertions.CollectionAssertTest.IsSubsetOf_Fails(), NUnit.Framework.Assertions.ConditionAssertTests.IsTrueFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsTrueFailsForNullable(), NUnit.Framework.Assertions.CollectionAssertTest.ItemsNotNullFailure(), NUnit.Framework.Assertions.CollectionAssertTest.ItemsOfTypeFailure(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.JaggedArrayComparedToSimpleArray(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.JaggedArrays(), NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.LoadInvalidFileType(), NUnit.Framework.Attributes.RangeAttributeTests.LongRangeAndNegativeStep(), NUnit.Framework.Attributes.RangeAttributeTests.LongRangeAndStep_Reversed(), NUnit.Framework.Attributes.RangeAttributeTests.LongRangeAndZeroStep(), NUnit.Framework.Constraints.EqualTests.LongStringsAreTruncated(), NUnit.Framework.Constraints.EqualTests.LongStringsAreTruncatedAtBothEndsIfNecessary(), NUnit.Framework.Constraints.EqualTests.LongStringsAreTruncatedAtFrontEndIfNecessary(), NUnit.Framework.Assertions.EqualsFixture.NanEqualsFails(), NUnit.Framework.Assertions.AssertThrowsTests.NoExceptionThrown(), NUnit.Framework.Constraints.AttributeExistsConstraintTests.NonAttributeThrowsException(), NUnit.Framework.Assertions.FileAssertTests.NonReadableStreamGivesException(), NUnit.Framework.Assertions.FileAssertTests.NonSeekableStreamGivesException(), NUnit.Framework.Constraints.StringConstraintTests.NonStringDataThrowsArgumentException(), NUnit.Framework.Assertions.NotEqualFixture.NotEqualFails(), NUnit.Framework.Assertions.CollectionAssertTest.NotEquivalent_Fails(), NUnit.Framework.Assertions.GreaterFixture.NotGreater(), NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterEqualIComparable(), NUnit.Framework.Assertions.GreaterFixture.NotGreaterIComparable(), NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterOrEqual(), NUnit.Framework.Assertions.GreaterFixture.NotGreaterWhenEqual(), NUnit.Framework.Constraints.NotConstraintTests.NotHonorsIgnoreCaseUsingConstructors(), NUnit.Framework.Constraints.NotConstraintTests.NotHonorsIgnoreCaseUsingPrefixNotation(), NUnit.Framework.Constraints.NotConstraintTests.NotHonorsTolerance(), NUnit.Framework.Assertions.LessFixture.NotLess(), NUnit.Framework.Assertions.LessEqualFixture.NotLessEqualIComparable(), NUnit.Framework.Assertions.LessFixture.NotLessIComparable(), NUnit.Framework.Assertions.LessEqualFixture.NotLessOrEqual(), NUnit.Framework.Assertions.LessFixture.NotLessWhenEqual(), NUnit.Framework.Assertions.NotSameFixture.NotSameFails(), NUnit.Framework.Constraints.BinarySerializableTest.NullArgumentThrowsException(), NUnit.Framework.Constraints.XmlSerializableTest.NullArgumentThrowsException(), NUnit.Framework.Assertions.ListContentsTests.NullArrayIsError(), NUnit.Framework.Constraints.PropertyExistsTests.NullDataThrowsArgumentNullException(), NUnit.Framework.Constraints.PropertyTest.NullDataThrowsArgumentNullException(), NUnit.Framework.Assertions.NotEqualFixture.NullEqualsNull(), NUnit.Framework.Assertions.EqualsFixture.PosInfinityNotEquals(), NUnit.Framework.Assertions.EqualsFixture.PosInfinityNotEqualsNegInfinity(), NUnit.Framework.Assertions.EqualsFixture.ReferenceEqualsThrowsException(), NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.RequiresAtLeastOneThread(), NUnit.Engine.Tests.AsyncTestEngineResultTests.Result_ThrowsIfNotSet(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_WithoutLoad_ReturnsError(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_WithoutLoad_ReturnsError(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_WithoutLoad_ReturnsError(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_WithoutLoad_ReturnsError(), NUnit.Framework.Assertions.SameFixture.SameFails(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.SameLengthDifferentContent(), NUnit.Framework.Assertions.SameFixture.SameValueTypes(), NUnit.Engine.Tests.AsyncTestEngineResultTests.SetResult_ThrowsIfNull(), NUnit.Engine.Tests.AsyncTestEngineResultTests.SetResult_ThrowsIfSetTwice(), NUnit.Framework.Constraints.RangeConstraintTest.ShouldThrowExceptionIfFromIsLessThanTo(), NUnit.Framework.Assertions.EqualsFixture.SinglePosInfinityNotEqualsNegInfinity(), NUnit.Framework.Assertions.StringAssertTests.StartsWithFails(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithoutPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithoutPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatOverload_DoesNotAcceptNegativeDelayValues(), NUnitLite.Tests.CommandLineTests.TimeoutThrowsExceptionIfOptionHasNoValue(), NUnit.ConsoleRunner.Tests.CommandLineTests.TimeoutThrowsExceptionIfOptionHasNoValue(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.TripleDimensionedArrays(), NUnit.Framework.Attributes.RangeAttributeTests.UintRange_Reversed(), NUnit.Framework.Attributes.RangeAttributeTests.UintRangeAndStep_Reversed(), NUnit.Framework.Attributes.RangeAttributeTests.UintRangeAndZeroStep(), NUnit.Framework.Attributes.RangeAttributeTests.UlongRange_Reversed(), NUnit.Framework.Attributes.RangeAttributeTests.UlongRangeAndStep_Reversed(), NUnit.Framework.Attributes.RangeAttributeTests.UlongRangeAndZeroStep(), NUnit.Framework.Assertions.CollectionAssertTest.UniqueFailure(), NUnit.Framework.Assertions.CollectionAssertTest.UniqueFailure_WithTwoNulls(), NUnit.Framework.Assertions.AssertThrowsTests.UnrelatedExceptionThrown(), and NUnit.Framework.Constraints.ExactCountConstraintTests.ZeroItemsMatchFails().
static Exception NUnit.Framework.Assert.Throws (IResolveConstraint expression, TestDelegate code) inline static
Verifies that a delegate throws a particular exception when called.
Parameters
expression A constraint to be satisfied by the exception
code A TestSnippet delegate
static Exception NUnit.Framework.Assert.Throws (Type expectedExceptionType, TestDelegate code, string message, params object[] args) inline static
Verifies that a delegate throws a particular exception when called.
Parameters
expectedExceptionType The exception Type expected
code A TestDelegate
message The message that will be displayed on failure
args Arguments to be used in formatting the message
static Exception NUnit.Framework.Assert.Throws (Type expectedExceptionType, TestDelegate code) inline static
Verifies that a delegate throws a particular exception when called.
Parameters
expectedExceptionType The exception Type expected
code A TestDelegate
static TActual NUnit.Framework.Assert.Throws< TActual > (TestDelegate code, string message, params object[] args) inline static
Verifies that a delegate throws a particular exception when called.
Template Parameters
TActual Type of the expected exception
Parameters
code A TestDelegate
message The message that will be displayed on failure
args Arguments to be used in formatting the message
Type Constraints
TActual : Exception
static TActual NUnit.Framework.Assert.Throws< TActual > (TestDelegate code) inline static
Verifies that a delegate throws a particular exception when called.
Template Parameters
TActual Type of the expected exception
Parameters
code A TestDelegate
Type Constraints
TActual : Exception
static Exception NUnit.Framework.Assert.Catch (TestDelegate code, string message, params object[] args) inline static
Verifies that a delegate throws an exception when called and returns it.
Parameters
code A TestDelegate
message The message that will be displayed on failure
args Arguments to be used in formatting the message
Referenced by NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException(), and NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_WithoutLoad_ThrowsInvalidOperationException().
static Exception NUnit.Framework.Assert.Catch (TestDelegate code) inline static
Verifies that a delegate throws an exception when called and returns it.
Parameters
code A TestDelegate
static Exception NUnit.Framework.Assert.Catch (Type expectedExceptionType, TestDelegate code, string message, params object[] args) inline static
Verifies that a delegate throws an exception of a certain Type or one derived from it when called and returns it.
Parameters
expectedExceptionType The expected Exception Type
code A TestDelegate
message The message that will be displayed on failure
args Arguments to be used in formatting the message
static Exception NUnit.Framework.Assert.Catch (Type expectedExceptionType, TestDelegate code) inline static
Verifies that a delegate throws an exception of a certain Type or one derived from it when called and returns it.
Parameters
expectedExceptionType The expected Exception Type
code A TestDelegate
static TActual NUnit.Framework.Assert.Catch< TActual > (TestDelegate code, string message, params object[] args) inline static
Verifies that a delegate throws an exception of a certain Type or one derived from it when called and returns it.
Parameters
code A TestDelegate
message The message that will be displayed on failure
args Arguments to be used in formatting the message
Type Constraints
TActual : System.Exception
static TActual NUnit.Framework.Assert.Catch< TActual > (TestDelegate code) inline static
Verifies that a delegate throws an exception of a certain Type or one derived from it when called and returns it.
Parameters
code A TestDelegate
Type Constraints
TActual : System.Exception
static void NUnit.Framework.Assert.DoesNotThrow (TestDelegate code, string message, params object[] args) inline static
Verifies that a delegate does not throw an exception
Parameters
code A TestDelegate
message The message that will be displayed on failure
args Arguments to be used in formatting the message
References NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Assertions.AssertThrowsTests.DoesNotThrowFails(), NUnit.Framework.Assertions.AssertThrowsTests.DoesNotThrowSuceeds(), and NUnit.Common.Tests.TestSelectionParserTests.TestParser().
static void NUnit.Framework.Assert.DoesNotThrow (TestDelegate code) inline static
Verifies that a delegate does not throw an exception.
Parameters
code A TestDelegate
static void NUnit.Framework.Assert.That (bool condition, string message, params object[] args) inline static
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
Parameters
condition The evaluated condition
message The message to display if the condition is false
args Arguments to be used in formatting the message
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
Referenced by NUnit.Engine.Services.Tests.ServiceManagerTests.AccessServiceByClass(), NUnit.Engine.Services.Tests.ServiceManagerTests.AccessServiceByInterface(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ActualArrayIsLonger(), NUnit.Framework.Internal.ResultStateTests.AddSiteToResult(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreInRange(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreInRange_UsingGenericComparer(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreInRange_UsingGenericComparison(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreInRange_UsingIComparer(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreInRangeFailureMessage(), NUnit.Framework.CollectionAssert.AllItemsAreInstancesOfType(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreInstancesOfType(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreInstancesOfTypeFailureMessage(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreNotNull(), NUnit.Framework.CollectionAssert.AllItemsAreNotNull(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreNotNullFails(), NUnit.Framework.CollectionAssert.AllItemsAreUnique(), NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Internal.PropertyBagTests.AllKeysAreListed(), NUnit.Framework.Attributes.TheoryTests.AllValuesMayBeSuppliedByAttributes(), NUnit.Framework.Tests.AssertSyntaxTests.AndOperator(), NUnit.Framework.Attributes.ApartmentAttributeTests.ApartmentStateUnknownThrowsException(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.ApplicationBaseTests(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.ApplyMatchesToProperty(), NUnit.Framework.FileAssert.AreEqual(), NUnit.Framework.Assert.AreEqual(), NUnit.Framework.CollectionAssert.AreEqual(), NUnit.Framework.Assertions.CollectionAssertTest.AreEqual_UsingIterator_Fails(), NUnit.Framework.Assertions.CollectionAssertTest.AreEqual_UsingLinqQuery_Fails(), NUnit.Framework.Assertions.CollectionAssertTest.AreEqualFail(), NUnit.Framework.Assertions.CollectionAssertTest.AreEqualFailCount(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWhenOneIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.AreEqualFailsWithDirectoryInfos(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithFileInfos(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithFiles(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithStreams(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithTextFilesAfterReadingBothFiles(), NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesWithSameStream(), NUnit.Framework.CollectionAssert.AreEquivalent(), NUnit.Framework.Assert.AreNotEqual(), NUnit.Framework.CollectionAssert.AreNotEqual(), NUnit.Framework.Assertions.CollectionAssertTest.AreNotEqual_Fails(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWhenBothAreNull(), NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualFailsWithDirectoryInfos(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithFileInfos(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithFiles(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithStreams(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualIteratesOverTheEntireFileAndFails(), NUnit.Framework.CollectionAssert.AreNotEquivalent(), NUnit.Framework.Assert.AreNotSame(), NUnit.Framework.Assert.AreSame(), NUnit.Framework.Tests.ThrowsTests.ArgumentNullException_ConstraintMatchesThrownArgumentNullException(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndArraySegment(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArrayAndCollection_Failure(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndEmptyArraySegment(), NUnit.Framework.Assertions.ListContentsTests.ArrayFails(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayIsEqualToItself(), NUnit.Framework.Assertions.ListContentsTests.ArrayListFails(), IG.Test.TestUtilities.ArraysAndListToString(), IG.Test.TestUtilities.ArraysConcatenateAndEquality(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysDeclaredAsDifferentTypes(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraySegmentAndArray(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysHaveDifferentRanks(), NUnit.Framework.Assertions.NotEqualFixture.ArraysNotEqualFails(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysWithDifferentDimensionsAsCollection(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysWithDifferentRanksAsCollection(), NUnit.Framework.Attributes.TheoryTests.ArrayWithDatapointsAttributeIsUsed(), NUnit.Framework.Internal.SetUpFixtureTests.AssemblySetUpFixtureReplacesAssemblyNodeInTree(), NUnit.Framework.Internal.SetUpFixtureTests.AssemblySetupFixtureWrapsExecutionOfTest(), NUnit.Framework.Assert.AssertDoublesAreEqual(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualLambdaAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualLambdaAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualLambdaAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_Boolean(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_BooleanWithMessage(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_BooleanWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_DelegateAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_DelegateAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_DelegateAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.AssertionsAreCountedCorrectly(), NUnit.Framework.Assertions.AssertThatTests.AssertThatWithFalseLambda(), NUnit.Framework.Assertions.AssertThatTests.AssertThatWithLambda(), NUnit.Framework.Tests.AssertSyntaxTests.AssignableFromTypeTests(), NUnit.Framework.Constraints.AttributeExistsConstraintTests.AttributeExistsOnMethodInfo(), NUnit.Framework.Constraints.AttributeExistsConstraintTests.AttributeTestPropertyValueOnMethodInfo(), NUnit.Engine.Services.Tests.ResultServiceTests.AvailableFormats(), NUnit.Framework.Internal.TestFixtureTests.BadConstructorRunsWithSetUpError(), NUnit.Framework.Assertions.AssertThrowsTests.BaseExceptionThrown(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.BaseSetUpCalledFirstAndTearDownCalledLast(), NUnit.Framework.Internal.TestFixtureTests.FixtureNotNullTestAttribute.BeforeTest(), NUnit.Common.Tests.TokenizerTests.BlankStringReturnsEof(), NUnit.Framework.Attributes.TheoryTests.BooleanArgumentsAreSuppliedAutomatically(), NUnit.TestData.AssertCountFixture.BooleanAssert(), NUnit.Framework.Assertions.EqualsFixture.Bug524CharIntWithoutOverload(), NUnit.Framework.Internal.Filters.EmptyFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.OrFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.NotFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml_TopLevelDefaultsToAnd(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.BuildMethodNameFilter_FromXml_Regex(), NUnit.Framework.Assert.ByVal(), NUnit.Engine.Api.Tests.ServiceLocatorTests.CanAccessService(), NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.CanAccessTestCaseSource(), NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.CanAccessValueSource(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanCallTypeInfoOnAllPlatforms(), NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Constraints.AndConstraintTests.CanCombineTestsWithAndOperator(), NUnit.Framework.Constraints.OrConstraintTests.CanCombineTestsWithOrOperator(), NUnit.Framework.Constraints.GreaterThanConstraintTests.CanCompareIComparables(), NUnit.Framework.Constraints.GreaterThanOrEqualConstraintTests.CanCompareIComparables(), NUnit.Framework.Constraints.LessThanConstraintTests.CanCompareIComparables(), NUnit.Framework.Constraints.LessThanOrEqualConstraintTests.CanCompareIComparables(), NUnit.Framework.Constraints.GreaterThanConstraintTests.CanCompareIComparablesOfT(), NUnit.Framework.Constraints.GreaterThanOrEqualConstraintTests.CanCompareIComparablesOfT(), NUnit.Framework.Constraints.LessThanConstraintTests.CanCompareIComparablesOfT(), NUnit.Framework.Constraints.LessThanOrEqualConstraintTests.CanCompareIComparablesOfT(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableDecimals(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableDoubles(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableInts(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableMixedNumerics(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareWithTolerance(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertIntToNullableByte(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertIntToNullableSByte(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertIntToNullableShort(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertStringToNullableDateTime(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertStringToNullableDecimal(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertStringToNullableTimeSpan(), NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomain(), NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified(), NUnit.Engine.Tests.TestEngineResultTests.CanCreateFromXmlNode(), NUnit.Engine.Tests.TestEngineResultTests.CanCreateFromXmlString(), NUnit.Framework.Constraints.ReusableConstraintTests.CanCreateReusableConstraintByImplicitConversion(), NUnit.Framework.Attributes.CategoryAttributeTests.CanDeriveFromCategoryAttribute(), NUnit.Framework.Constraints.ToStringTests.CanDisplayPrefixConstraints_Resolved(), NUnit.Framework.Constraints.ToStringTests.CanDisplaySimpleConstraints_Resolved(), NUnit.Framework.Constraints.ToStringTests.CanDisplaySimpleConstraints_Unresolved(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanExcludePlatform(), NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.CanGenerateDataFromParameter(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnAssemblies(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnClasses(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnDerivedClasses(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnFields(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnMethods(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnParameters(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnProperties(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetConstructors(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetContructorWithParams(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanGetCurrentFramework(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanGetCurrentFramework(), NUnit.Engine.Services.Tests.ExtensionServiceTests.CanGetExtensionPointByPath(), NUnit.Engine.Services.Tests.ExtensionServiceTests.CanGetExtensionPointByType(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetGenericArguments(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetGenericConstructor(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetGetMethod(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetInterfaces(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetMember(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetProperty(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetPublicField(), NUnit.Framework.Constraints.EqualityComparerTests.CanHandleMultipleImplementationsOfIEquatable(), NUnit.Framework.Attributes.TestFixtureSourceTests.CanIgnoreIndividualFixtures(), NUnit.Framework.Attributes.TestCaseSourceTests.CanIgnoreIndividualTestCases(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanIgnoreIndividualTestCases(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanIncludePlatform(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanListAvailableFrameworks(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CanLoadEmptyProject(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CanLoadVsProject(), NUnit.Framework.Attributes.TestFixtureSourceTests.CanMarkIndividualFixturesExplicit(), NUnit.Framework.Attributes.TestCaseSourceTests.CanMarkIndividualTestCasesExplicit(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanMarkIndividualTestCasesExplicit(), NUnit.Framework.Constraints.CollectionEqualsTests.CanMatchAnArrayWithACollection(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraint(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintAfterPrefix(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintsUnderAndOperator(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDates(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDates(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinDays(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDatesWithinDays(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinHours(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinMilliseconds(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDatesWithinMilliseconds(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinMinutes(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDatesWithinMinutes(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinSeconds(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDatesWithinSeconds(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinTicks(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDatesWithinTicks(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinTimeSpan(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDatesWithinTimeSpan(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.CanMatchDoublesWithRelativeTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.CanMatchDoublesWithUlpTolerance(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchLambda(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchPredicate(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.CanMatchSinglesWithRelativeTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.CanMatchSinglesWithUlpTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.CanMatchSpecialFloatingPointValues(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchTimeSpanWithinMinutes(), NUnit.Framework.Constraints.CollectionEqualsTests.CanMatchTwoCollections(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchUsingIsEqualToWithinTimeSpan(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchUsingIsEqualToWithinTimeSpan(), NUnit.Framework.Internal.TestFixtureTests.CannotRunGenericFixtureWithNoArgsProvided(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.CanReadConfigFile(), NUnit.Framework.Constraints.ReusableConstraintTests.CanReuseReusableConstraintMultipleTimes(), NUnit.Framework.Internal.TestFixtureTests.CanRunGenericFixtureDerivedFromAbstractFixtureWithArgsProvided(), NUnit.Framework.Internal.TestFixtureTests.CanRunGenericFixtureWithProperArgsProvided(), NUnit.Framework.Attributes.CategoryAttributeTests.CanSpecifyOnMethodAndTestCase(), NUnit.Framework.Constraints.CollectionContainsConstraintTests.CanTestContentsOfArray(), NUnit.Framework.Constraints.CollectionContainsConstraintTests.CanTestContentsOfCollectionNotImplementingIList(), NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfDelegateReturningList(), NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfList(), NUnit.Framework.Constraints.CollectionContainsConstraintTests.CanTestContentsOfObjectList(), NUnit.Framework.Constraints.CollectionContainsConstraintTests.CanTestContentsOfSortedList(), NUnit.Framework.Assertions.NullableTypesTests.CanTestForNaN(), NUnit.Framework.Assertions.NullableTypesTests.CanTestForNull(), NUnit.Framework.Constraints.DelayedConstraintTests.CanTestInitiallyNullDelegate(), NUnit.Framework.Constraints.PredicateConstraintTests.CanUseConstraintExpressionSyntax(), NUnit.Framework.Constraints.NotConstraintTests.CanUseNotOperator(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple_XmlOutput(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_XmlOutput(), NUnit.Framework.Assertions.StringAssertTests.CaseInsensitiveCompareFails(), NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsCategory(), NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsCategoryOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsMultipleCategories(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_ToXml_Regex(), NUnit.Framework.Attributes.CategoryAttributeTests.CategoryOnFixture(), NUnit.Framework.Attributes.CategoryAttributeTests.CategoryOnTestMethod(), NUnit.Framework.Attributes.SetUpFixtureAttributeTests.CertainAttributesAreNotAllowed(), NUnit.Framework.Assertions.EqualsFixture.CharCharComparision(), NUnit.Framework.Tests.ActionAttributeTests.CheckActionsOnSuite(), NUnit.Framework.Tests.ActionAttributeTests.CheckActionsOnTestCase(), NUnit.Framework.Attributes.TestFixtureSourceTests.CheckArgument(), NUnit.Framework.Tests.ActionAttributeTests.CheckBeforeAfterActionPair(), NUnit.Framework.Constraints.EqualTests.CheckExceptionMessage(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CheckExtension(), NUnit.Framework.Internal.Tests.TestNamingTests.CheckNames(), NUnit.Framework.Attributes.TestFixtureSourceTests.CheckNotRunnable(), NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms(), NUnit.Framework.Attributes.RandomAttributeTests.CheckRandomResult(), NUnit.Framework.Internal.RandomizerTests.CheckScaleIsZero(), NUnit.TestData.TestFixtureSourceData.TestFixtureSourceTest.CheckSource(), NUnit.TestData.TestFixtureSourceData.TestFixtureSourceDivideTest.CheckSource(), NUnit.Framework.Attributes.ValuesAttributeTests.CheckValues(), NUnit.Framework.Attributes.RangeAttributeTests.CheckValues(), NUnit.Framework.Attributes.RangeAttributeTests.CheckValuesWithinTolerance(), NUnit.Framework.Internal.TestXmlTests.CheckXmlForTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_ToXml_Regex(), NUnit.Framework.Internal.TestExecutionContextTests.Cleanup(), NUnit.Framework.Constraints.MsgUtilTests.ClipExpectedAndActual_StringsDoNotFitInLine(), NUnit.Framework.Constraints.MsgUtilTests.ClipExpectedAndActual_StringsFitInLine(), NUnit.Framework.Constraints.MsgUtilTests.ClipExpectedAndActual_StringTailsFitInLine(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionEquivalenceTests(), NUnit.Framework.Internal.GenericTestMethodTests.Combinatorial_IncompatibleArgsAreNotRunnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.CombinatorialAttribute_NoArgs_NoCases(), NUnit.Framework.Attributes.TestMethodBuilderTests.CombinatorialAttribute_WithArgs_Runnable(), NUnit.Framework.Attributes.ApplyToTestTests.CombinatorialAttributeSetsJoinType(), NUnit.Framework.Attributes.ApplyToTestTests.CombinatorialAttributeSetsJoinTypeOnNonRunnableTest(), NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), NUnit.Framework.Syntax.MixedOperatorOverrides.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.ComplexTests(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.ConfigFileTests(), NUnit.TestData.AssertCountFixture.ConstraintAssert(), NUnit.Framework.Api.FrameworkControllerTests.ConstructController(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.ConstructController_MissingFile_ThrowsArgumentInvalid(), NUnit.Framework.Tests.TestContextTests.ConstructorAccessWorkDirectory(), NUnit.Framework.Tests.TestContextTests.ConstructorCanAccessFixtureName(), NUnit.Framework.Tests.TestContextTests.ConstructorCanAccessTestDirectory(), NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithCombinedArgs(), NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithFixtureArgs(), NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithFixtureArgsAndSetTypeArgs(), NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithJustTypeArgs(), NUnit.Framework.Attributes.DerivedPropertyAttributeTests.ConstructWithNoArgs< T >(), NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithNoArgumentsAndSetTypeArgs(), NUnit.Framework.Attributes.DerivedPropertyAttributeTests.ConstructWithOneArg< T >(), NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithoutArguments(), NUnit.Framework.StringAssert.Contains(), NUnit.Framework.Assert.Contains(), NUnit.Framework.CollectionAssert.Contains(), NUnit.Framework.Assertions.StringAssertTests.ContainsFails(), NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_EmptyICollection(), NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_EmptyIList(), NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_ICollection(), NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_ILIst(), NUnit.Framework.Internal.PropertyBagTests.ContainsKey(), NUnit.Engine.Services.Tests.DriverServiceTests.CorrectDriverIsUsed(), NUnit.Framework.Assertions.AssertThrowsTests.CorrectExceptionIsReturnedToMethod(), NUnit.Framework.Assertions.AssertThrowsTests.CorrectExceptionThrown(), NUnit.Framework.Attributes.Tests.CommandWrapperTests.CorrectExceptionThrown(), NUnit.Framework.Tests.ActionAttributeTests.CorrectNumberOfEventsReceived(), NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests.CorrectRunnerIsUsed(), NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed(), NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed_InvalidExtension(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_BadFile_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_FileNotFound_ReturnsZero(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.CountTestCases_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_WithoutLoad_ThrowsInvalidOperation(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_BadFile_ReturnsZero(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_FileNotFound_ReturnsZero(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperation(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.ConsoleRunner.Tests.ResultReporterTests.CreateResult(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeExcludingCurrentCultureSkipsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeExcludingOtherCultureRunsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeIncludingCurrentCultureRunsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeIncludingOtherCultureSkipsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeWithMultipleCulturesIncluded(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.CultureInfo_HasCultureInfoElement(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.CultureInfo_HasCultureInfoElement(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.CultureInfo_HasRequiredAttribute(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.CultureInfo_HasRequiredAttribute(), NUnit.Engine.Tests.RuntimeFrameworkTests.CurrentFrameworkHasBuildSpecified(), NUnit.Framework.Internal.RuntimeFrameworkTests.CurrentFrameworkHasBuildSpecified(), NUnit.Engine.Tests.RuntimeFrameworkTests.CurrentFrameworkMustBeAvailable(), NUnit.Framework.Attributes.TheoryTests.DatapointAndAttributeDataMayBeCombined(), NUnit.Framework.Assertions.EqualsFixture.DateTimeNotEqual(), NUnit.Engine.Services.Tests.ServiceDependencyTests.DefaultTestRunnerFactory_ProjectServiceError(), NUnit.Engine.Services.Tests.ServiceDependencyTests.DefaultTestRunnerFactory_ProjectServiceMissing(), NUnit.Framework.Syntax.ThrowsTests.DelegateThrowsException(), NUnit.Framework.Attributes.CategoryAttributeTests.DerivedCategoryMayBeInherited(), NUnit.Framework.Assertions.AssertThrowsTests.DerivedExceptionThrown(), NUnit.Framework.Attributes.ApplyToTestTests.DescriptionAttributeSetsDescription(), NUnit.Framework.Attributes.ApplyToTestTests.DescriptionAttributeSetsDescriptionOnNonRunnableTest(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.DifferentArrayTypesEqualFails(), NUnit.Framework.Constraints.EqualityComparerTests.DifferentDirectoriesAreNotEqual(), NUnit.Framework.Assertions.EqualsFixture.DirectoryInfoNotEqual(), NUnit.Framework.Constraints.ToStringTests.DisplayBinaryConstraints_Resolved(), NUnit.Framework.Constraints.ToStringTests.DisplayBinaryConstraints_UnResolved(), NUnitLite.Tests.TextUITests.DisplayError(), NUnitLite.Tests.TextUITests.DisplayErrors(), NUnitLite.Tests.TextUITests.DisplayHeader(), NUnitLite.Tests.TextUITests.DisplayHelp(), NUnit.Framework.Constraints.ToStringTests.DisplayPrefixConstraints_Unresolved(), NUnitLite.Tests.TextUITests.DisplayRequestedOptions(), NUnitLite.Tests.TextUITests.DisplayRuntimeEnvironment(), NUnitLite.Tests.TextUITests.DisplayTestFiles(), NUnitLite.Tests.TextUITests.DisplayWarning(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.DisposeCalledOnceWhenFixtureImplementsIDisposable(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.DisposeCalledOnceWhenFixtureImplementsIDisposableAndHasTestCases(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_FirstChildIsXmlDeclaration(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_FirstChildIsXmlDeclaration(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_HasTestResults(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_HasTestResults(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_HasThreeChildren(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_HasThreeChildren(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_SecondChildIsComment(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_SecondChildIsComment(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_ThirdChildIsTestResults(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_ThirdChildIsTestResults(), NUnit.Framework.StringAssert.DoesNotContain(), NUnit.Framework.CollectionAssert.DoesNotContain(), NUnit.Framework.Assertions.CollectionAssertTest.DoesNotContain_Fails(), NUnit.Framework.StringAssert.DoesNotEndWith(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenDirectoryInfoExists(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenDirectoryInfoIsNull(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenFileInfoExists(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenFileInfoIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenStringExists(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenStringExists(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenStringIsEmpty(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenStringIsEmpty(), NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenStringIsNull(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenStringIsNull(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.DoesNotGetAttributesOnDerivedClassesWhenInheritedIsFalse(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetPrivateField(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetPrivateMemberOnBaseClass(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetStaticMemberOnBaseClass(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetStaticPropertyOnBase(), NUnit.Framework.StringAssert.DoesNotStartWith(), NUnit.Framework.Assert.DoesNotThrow(), NUnit.Framework.Assertions.AssertThrowsTests.DoesNotThrowFails(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.DoubleDimensionedArrays(), NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualMessageDisplaysDefaultTolerance(), NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualMessageDisplaysTolerance(), NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualWithNanDoesNotDisplayDefaultTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.DTimeOffsetCanMatchDatesWithinHours(), NUnit.Common.Tests.XmlHelperTests.ElementContainsElementWithCData(), NUnit.Common.Tests.XmlHelperTests.ElementContainsElementWithInnerText(), NUnit.Framework.Assertions.ListContentsTests.EmptyArrayFails(), NUnit.Framework.Assertions.ArrayEqualsFixture.EmptyArraySegmentAndArray(), NUnit.Framework.Tests.AssertSyntaxTests.EmptyCollectionTests(), NUnit.Framework.Constraints.EmptyDirectoryConstraintTest.EmptyDirectory(), NUnit.Engine.Api.Tests.TestFilterTests.EmptyFilter(), NUnitLite.Tests.CreateTestFilterTests.EmptyFilter(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.EmptyFilter(), NUnit.Framework.Tests.AssertSyntaxTests.EmptyStringTests(), NUnit.Framework.StringAssert.EndsWith(), NUnit.Framework.Assertions.StringAssertTests.EndsWithFails(), NUnit.Framework.Tests.AssertSyntaxTests.EndsWithTests(), NUnit.Framework.Attributes.TheoryTests.EnumArgumentsAreSuppliedAutomatically(), NUnit.Framework.Assertions.EqualsFixture.EnumsNotEqual(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Environment_HasEnvironmentElement(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Environment_HasEnvironmentElement(), NUnit.Framework.Constraints.CollectionEquivalentConstraintTests.EqualCollectionsAreEquivalent(), NUnit.Framework.Tests.AssertSyntaxTests.EqualIgnoringCaseTests(), NUnit.Framework.Constraints.NUnitComparerTests.EqualItems(), NUnit.Framework.Constraints.EqualityComparerTests.EqualItems(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTests(), NUnit.Framework.Syntax.EqualityTests.EqualityTestsUsingDefaultFloatingPointTolerance(), NUnit.Framework.Syntax.EqualityTests.EqualityTestsWithTolerance(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTestsWithTolerance(), NUnit.Framework.Syntax.EqualityTests.EqualityTestsWithTolerance_MixedFloatAndDouble(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTestsWithTolerance_MixedFloatAndDouble(), NUnit.Framework.Syntax.EqualityTests.EqualityTestsWithTolerance_MixingTypesGenerally(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTestsWithTolerance_MixingTypesGenerally(), NUnit.Framework.Assertions.EqualsFixture.EqualsFail(), NUnit.Framework.Assertions.EqualsFixture.EqualsNaNFails(), NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.EqualToTest(), NUnit.Framework.Syntax.AfterSyntaxUsingLambda.EqualToTest(), NUnit.Framework.Assertions.CollectionAssertTest.EquivalentFailOne(), NUnit.Framework.Assertions.CollectionAssertTest.EquivalentFailTwo(), NUnit.Framework.Constraints.CollectionEquivalentConstraintTests.EquivalentHandlesNull(), NUnit.Framework.Constraints.CollectionEquivalentConstraintTests.EquivalentHonorsIgnoreCase(), NUnit.Framework.Constraints.CollectionEquivalentConstraintTests.EquivalentHonorsUsing(), NUnit.Framework.Constraints.CollectionEquivalentConstraintTests.EquivalentIgnoresOrder(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfDaysPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfHoursPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfMillisecondsPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfMinutesPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfPercentPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfSecondsPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfTicksPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfUlpsIsUsedOnDecimal(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfUlpsIsUsedOnIntegralType(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfUlpsPrecedesWithin(), NUnit.Framework.Attributes.MaxTimeTests.ErrorReportHasPriorityOverMaxTime(), NUnit.ConsoleRunner.Tests.ResultReporterTests.ErrorsAndFailuresReportTest(), NUnitLite.Tests.TextUITests.ErrorsAndFailuresReportTest(), NUnit.Framework.Constraints.MsgUtilTests.EscapeControlCharsTest(), NUnit.Framework.Constraints.MsgUtilTests.EscapeNullCharInString(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyOneItemMatches(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyOneItemMatchFails(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyTwoItemsMatch(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyTwoItemsMatchFails(), NUnit.Framework.Assertions.TypeAssertTests.ExactType(), NUnit.Framework.Assertions.TypeAssertTests.ExactTypeFails(), NUnit.Framework.Tests.AssertSyntaxTests.ExactTypeTests(), NUnit.Framework.Internal.TestExecutionContextTests.ExecutionStatusIsPromulgatedAcrossBranches(), NUnit.Framework.Internal.TestExecutionContextTests.ExecutionStatusIsPulledFromHigherContext(), NUnit.Framework.Internal.TestExecutionContextTests.ExecutionStatusIsPushedToHigherContext(), NUnit.Framework.Syntax.PropertySyntaxVariations.ExistenceTest(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenDirectoryInfoDoesNotExist(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenDirectoryInfoIsNull(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenFileInfoDoesNotExist(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenFileInfoIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenStringDoesNotExist(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenStringDoesNotExist(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenStringIsEmpty(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenStringIsEmpty(), NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenStringIsNull(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenStringIsNull(), NUnit.Framework.AssertionHelper.Expect(), NUnit.Framework.AssertionHelper.Expect< TActual >(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ExpectedArrayIsLonger(), NUnit.Framework.Tests.Attributes.TestExpectedResult.ExpectedResultDoesNotBlockApplyToTestAttributes(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeMakesTestExplicit(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeSetsIgnoreReason(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeWithIgnoreIgnoresTest(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.ExplicitMatch_SingleName(), NUnit.Framework.Internal.Filters.AndFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.IdFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.OrFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.ExplicitMatchTest(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Explore_AfterLoad_ReturnsRunnableSuite(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Explore_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Engine.Services.Tests.ExtensionServiceTests.ExtensionsAreAddedToExtensionPoint(), NUnit.Framework.Constraints.RangeTests.FailingInRangeMethod(), NUnit.Framework.Constraints.RangeTests.FailingNotInRangeMethod(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.FailsOnDoublesOutsideOfRelativeTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.FailsOnDoublesOutsideOfUlpTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.FailsOnSinglesOutsideOfRelativeTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.FailsOnSinglesOutsideOfUlpTolerance(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenDirectoryInfoDoesNotExist(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenDirectoryInfoIsNull(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenDirectoryStringDoesNotExist(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenFileInfoDoesNotExist(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenFileInfoIsNull(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenFileStringDoesNotExist(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenIgnoreDirectoriesIsTrueWithDirectoryInfo(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenIgnoreDirectoriesIsTrueWithDirectoryString(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenIgnoreFilesIsTrueWithFileInfo(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenIgnoreFilesIsTrueWithFileString(), NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.FailsWhenKeyIsMissing(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenNotStringOrDirectoryInfo(), NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.FailsWhenNotUsedAgainstADictionary(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.FailsWhenNotUsedAgainstADictionary(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenStringIsEmpty(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenStringIsNull(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.FailsWhenValueIsMissing(), NUnit.Framework.Constraints.ConstraintTestBase.FailsWithBadValues(), NUnit.Framework.Constraints.ThrowsConstraintTestBase.FailsWithBadValues(), NUnit.Framework.Constraints.CollectionEqualsTests.FailureMatchingArrayAndCollection(), NUnit.Framework.Assertions.GreaterFixture.FailureMessage(), NUnit.Framework.Assertions.LessEqualFixture.FailureMessage(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.FailureOnSingleDimensionedArrays(), NUnit.Framework.Attributes.MaxTimeTests.FailureReport(), NUnit.Framework.Attributes.MaxTimeTests.FailureReportHasPriorityOverMaxTime(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualLambdaAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualLambdaAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualLambdaAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_Boolean(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_BooleanWithMessage(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_BooleanWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_DelegateAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_DelegateAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_DelegateAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanLambdaWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanLambdaWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraintWithMessageAndArgs(), NUnit.Framework.Assert.False(), NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.FileNameIsUsedAsPackageName(), NUnit.Common.Tests.OutputSpecificationTests.FileNameOnly(), NUnit.Common.Tests.OutputSpecificationTests.FileNamePlusFormat(), NUnit.Common.Tests.OutputSpecificationTests.FileNamePlusTransform(), NUnit.Framework.Internal.Tests.StackFilterTests.FilterLongTrace(), NUnit.Framework.Internal.Tests.StackFilterTests.FilterShortTraceWithAssert(), NUnit.Framework.Internal.Tests.StackFilterTests.FilterShortTraceWithAssume_Trace1(), NUnit.Engine.Api.Tests.TestFilterTests.FilterWithOneTest(), NUnit.Engine.Api.Tests.TestFilterTests.FilterWithThreeTests(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.FiveDimensionedArrays(), NUnit.Framework.Internal.TestFixtureTests.FixtureInheritingTwoTestFixtureAttributesIsLoadedOnlyOnce(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.FixtureInstancesAreNamedCorrectly(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureFullName(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureId(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureName(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureProperties(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpContextReflectsCurrentPrincipal(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpContextReflectsCurrentUICulture(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpontextReflectsCurrentCulture(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.FixtureWithNoTestsShouldNotCallFixtureSetUpOrTearDown(), NUnit.Framework.Assertions.EqualsFixture.FloatNotEqualMessageDisplaysTolerance(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DateTimeTest(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DecimalIsWrittenToTwentyNineDigits(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DecimalIsWrittenWithTrailingM(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DoubleIsWrittenToSeventeenDigits(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DoubleIsWrittenWithTrailingD(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_FloatIsWrittenToNineDigits(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_FloatIsWrittenWithTrailingF(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_IntegerIsWrittenAsIs(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_StringIsWrittenWithQuotes(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_ToXml_Regex(), NUnit.Common.Tests.AssemblyHelperTests.GetAssemblyPathFromCodeBase(), NUnit.Common.Tests.AssemblyHelperTests.GetNameForAssembly(), NUnit.Common.Tests.AssemblyHelperTests.GetPathForAssembly(), NUnit.Common.Tests.AssemblyHelperTests.GetPathForType(), NUnit.Framework.Internal.PropertyBagTests.GetReturnsSingleValue(), NUnit.Framework.Internal.GenericMethodHelperTests.GetTypeArgumentsForMethodTests(), NUnit.Framework.Assert.Greater(), NUnit.Framework.Assert.GreaterOrEqual(), NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.GreaterTest(), NUnit.Framework.Syntax.AfterSyntaxUsingLambda.GreaterTest(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureTearDown(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureTearDownAfterErrorInFixtureSetUp(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureTearDownAfterErrorInTest(), NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInBothSetUpAndTearDown(), NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInSetUp(), NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInTearDown(), NUnit.Framework.Constraints.AndConstraintTests.HandlesFirstPartFailing(), IG.Test.TestCrypto.HashStringMd5(), IG.Test.TestCrypto.HashStringSaltedMd5(), IG.Test.TestCrypto.HashStringSaltedSha1(), IG.Test.TestCrypto.HashStringSaltedSha256(), IG.Test.TestCrypto.HashStringSaltedSHA512(), IG.Test.TestCrypto.HashStringSha1(), IG.Test.TestCrypto.HashStringSha256(), IG.Test.TestCrypto.HashStringSha512(), IG.Test.TestCrypto.HashTypes(), NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.HasMemberTest(), NUnit.Framework.Syntax.AfterSyntaxUsingLambda.HasMemberTest(), NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.HasNoSubPackages(), NUnit.Framework.Constraints.UniqueItemsTests.HonorsIgnoreCase(), NUnit.Framework.Constraints.CollectionEqualsTests.HonorsIgnoreCase(), NUnit.Common.Tests.TokenizerTests.IdentifierTokens(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.IdFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.IdFilter_ToXml(), NUnit.Framework.Constraints.EqualityComparerTests.IEnumeratorIsDisposed(), NUnit.Framework.Assertions.EqualsFixture.IEquatableSuccess_ConstraintSyntax(), NUnit.Framework.Internal.TestResultOutputTests.IfNothingIsWritten_OutputIsEmpty(), NUnit.Framework.Internal.TestResultOutputTests.IfNothingIsWritten_XmlOutputIsEmpty(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeIgnoresTest(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeIgnoresTestUntilDateSpecified(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeIgnoresTestUntilDateTimeSpecified(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeMarksTestAsRunnableAfterUntilDatePasses(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeSetsIgnoreReason(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeUntilSetsTheReason(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithExplicitIgnoresTest(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithUntilAddsIgnoreUntilDateProperty(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithUntilAddsIgnoreUntilDatePropertyPastUntilDate(), NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.IgnoreCaseIsHonored(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.IgnoreCaseIsHonored(), NUnit.Framework.Constraints.EqualityComparerTests.ImplementingIEquatableDirectlyOnTheClass(), NUnit.Framework.Constraints.EqualityComparerTests.ImplementingIEquatableOnABaseClassOrInterface(), NUnit.Framework.Constraints.EqualityComparerTests.ImplementingIEquatableOnABaseClassOrInterfaceThroughInterface(), NUnit.Framework.Internal.PropertyBagTests.IndexGetsEmptyListIfNameIsNotPresent(), NUnit.Framework.Internal.PropertyBagTests.IndexGetsListOfValues(), NUnit.Framework.Internal.PropertyBagTests.IndexSetsListOfValues(), NUnit.Framework.Attributes.AttributeInheritanceTests.InheritedFixtureAttributeIsRecognized(), NUnit.Engine.Services.Tests.ServiceManagerTests.InitializationFailure(), NUnit.Engine.Services.Tests.ServiceManagerTests.InitializeServices(), NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.InitializeTestEngineResult(), NUnit.Framework.Constraints.RangeTests.InRangeFails(), NUnit.Framework.Constraints.RangeTests.InRangeSucceeds(), NUnit.Framework.Tests.AssertSyntaxTests.InstanceOfTests(), NUnit.Framework.Internal.SetUpFixtureTests.InvalidAssemblySetUpFixtureIsLoadedCorrectly(), NUnit.Framework.Internal.SetUpFixtureTests.InvalidSetUpFixtureTest(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.InvalidTestCase_HasFailedResult(), NUnit.Framework.Assert.IsAssignableFrom(), NUnit.Framework.Assertions.TypeAssertTests.IsAssignableFrom(), NUnit.Framework.Assert.IsAssignableFrom< TExpected >(), NUnit.Framework.Assertions.TypeAssertTests.IsAssignableFromFails(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.IsAssignableFromTest(), NUnit.Framework.Internal.Filters.EmptyFilterTests.IsEmpty(), NUnit.Framework.Assert.IsEmpty(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNonEmptyArray(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNonEmptyIEnumerable(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNullString(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnString(), NUnit.Framework.Tests.AssertSyntaxTests.IsFalse(), NUnit.Framework.Assert.IsFalse(), NUnit.Framework.Assertions.ConditionAssertTests.IsFalseFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsFalseFailsForNullable(), NUnit.Framework.Assertions.TypeAssertTests.IsInstanceOf(), NUnit.Framework.Assert.IsInstanceOf(), NUnit.Framework.Assert.IsInstanceOf< TExpected >(), NUnit.Framework.Assertions.TypeAssertTests.IsInstanceOfFails(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.IsInstanceOfTypeTest(), NUnit.Framework.Assertions.StringAssertTests.IsMatchFails(), NUnit.Framework.Tests.AssertSyntaxTests.IsNaN(), NUnit.Framework.Assert.IsNaN(), NUnit.Framework.Assertions.ConditionAssertTests.IsNaNFails(), NUnit.Framework.Assert.IsNotAssignableFrom(), NUnit.Framework.Assertions.TypeAssertTests.IsNotAssignableFrom(), NUnit.Framework.Assert.IsNotAssignableFrom< TExpected >(), NUnit.Framework.Assertions.TypeAssertTests.IsNotAssignableFromFails(), NUnit.Framework.Assert.IsNotEmpty(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyArray(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyArrayList(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyHashTable(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyIEnumerable(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyString(), NUnit.Framework.Assertions.TypeAssertTests.IsNotInstanceOf(), NUnit.Framework.Assert.IsNotInstanceOf(), NUnit.Framework.Assert.IsNotInstanceOf< TExpected >(), NUnit.Framework.Assertions.TypeAssertTests.IsNotInstanceOfFails(), NUnit.Framework.Tests.AssertSyntaxTests.IsNotNull(), NUnit.Framework.Assert.IsNotNull(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotNullFails(), NUnit.Framework.CollectionAssert.IsNotSubsetOf(), NUnit.Framework.Assertions.CollectionAssertTest.IsNotSubsetOf(), NUnit.Framework.Assertions.CollectionAssertTest.IsNotSubsetOf_Fails(), NUnit.Framework.CollectionAssert.IsNotSupersetOf(), NUnit.Framework.Tests.AssertSyntaxTests.IsNull(), NUnit.Framework.Assert.IsNull(), NUnit.Framework.Assertions.ConditionAssertTests.IsNullFails(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered(), NUnit.Framework.CollectionAssert.IsOrdered(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_2(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_Allows_adjacent_equal_values(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_AtLeastOneArgMustImplementIComparable(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_Fails(), NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_Fails(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_Handles_custom_comparison(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_Handles_custom_comparison2(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_Handles_null(), NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_Handles_null(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_TypesMustBeComparable(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrderedBy(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrderedBy_Comparer(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrderedBy_Handles_heterogeneous_classes_as_long_as_the_property_is_of_same_type(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrderedDescending(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrderedDescending_2(), NUnit.TestUtilities.TestAssert.IsRunnable(), NUnit.Framework.CollectionAssert.IsSubsetOf(), NUnit.Framework.Assertions.CollectionAssertTest.IsSubsetOf(), NUnit.Framework.Assertions.CollectionAssertTest.IsSubsetOf_Fails(), NUnit.Framework.Assertions.CollectionAssertTest.IsSubsetOfHandlesNull(), NUnit.Framework.CollectionAssert.IsSupersetOf(), NUnit.Framework.Tests.AssertSyntaxTests.IsTrue(), NUnit.Framework.Assert.IsTrue(), NUnit.Framework.Assertions.ConditionAssertTests.IsTrueFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsTrueFailsForNullable(), NUnit.Framework.Assertions.CollectionAssertTest.ItemsNotNullFailure(), NUnit.Framework.Assertions.CollectionAssertTest.ItemsOfTypeFailure(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.JaggedArrayComparedToSimpleArray(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.JaggedArrays(), NUnit.Framework.Syntax.ThrowsTests.LambdaThrowsException(), NUnit.Framework.Syntax.ThrowsTests.LambdaThrowsExceptionWithMessage(), NUnit.Framework.Assert.Less(), NUnit.Framework.Assert.LessOrEqual(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Load_GoodFile_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_GoodFile_ReturnsRunnableSuite(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Load_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_Assembly_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_GoodFile_ReturnsRunnableSuite(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesAnything(), NUnit.Framework.Internal.Filters.AndFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.OrFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.IdFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.MatchTest(), NUnit.Framework.Attributes.ApplyToTestTests.MaxTimeAttributeSetsMaxTime(), NUnit.Framework.Attributes.ApplyToTestTests.MaxTimeAttributeSetsMaxTimeOnNonRunnableTest(), NUnit.Framework.Attributes.MaxTimeTests.MaxTimeExceeded(), NUnit.Framework.Attributes.MaxTimeTests.MaxTimeExceededOnTestCase(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_ToXml_Regex(), NUnit.Framework.Attributes.TestCaseSourceTests.MethodTakingTwoStringArrays(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MethodWithoutParamsIsNamedCorrectly(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MethodWithParamsIsNamedCorrectly(), NUnit.Framework.Constraints.RangeTests.MixedRangeTests< TMin, TMax, TVal >(), NUnit.Common.Tests.TokenizerTests.MixedTokens_Complex(), NUnit.Common.Tests.TokenizerTests.MixedTokens_Simple(), NUnit.Common.Tests.OutputSpecificationTests.MultipleFormatSpecifiersNotAllowed(), NUnit.Common.Tests.OutputSpecificationTests.MultipleTransformSpecifiersNotAllowed(), NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureReplacesNamespaceNodeInTree(), NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureWrapsExecutionOfSingleTest(), NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureWrapsExecutionOfTwoTests(), NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureWrapsNestedNamespaceSetUpFixture(), NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpMethodsMayBeStatic(), NUnit.Framework.Assertions.EqualsFixture.NanEqualsFails(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTest(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTestWithinToleranceAndWithSameOffset(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTestWithTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTestWithToleranceAndWithSameOffset(), NUnit.Framework.Attributes.Tests.CommandWrapperTests.NoExceptionThrown(), NUnit.Framework.Assertions.AssertThrowsTests.NoExceptionThrown(), NUnit.Framework.Tests.AssertSyntaxTests.NoItemTests(), NUnit.Framework.Assertions.FileAssertTests.NonReadableStreamGivesException(), NUnit.Framework.Assertions.FileAssertTests.NonSeekableStreamGivesException(), NUnit.Framework.Constraints.EmptyDirectoryConstraintTest.NotEmptyDirectory(), NUnit.Framework.Assertions.NotEqualFixture.NotEqualFails(), NUnit.Framework.Assertions.CollectionAssertTest.NotEquivalent_Fails(), NUnit.Framework.Assertions.GreaterFixture.NotGreater(), NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterEqualIComparable(), NUnit.Framework.Assertions.GreaterFixture.NotGreaterIComparable(), NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterOrEqual(), NUnit.Framework.Assertions.GreaterFixture.NotGreaterWhenEqual(), NUnit.Framework.Constraints.NotConstraintTests.NotHonorsIgnoreCaseUsingConstructors(), NUnit.Framework.Constraints.NotConstraintTests.NotHonorsIgnoreCaseUsingPrefixNotation(), NUnit.Framework.Constraints.NotConstraintTests.NotHonorsTolerance(), NUnit.Framework.Constraints.RangeTests.NotInRangeFails(), NUnit.Framework.Constraints.RangeTests.NotInRangeSucceeds(), NUnit.Framework.Assertions.LessFixture.NotLess(), NUnit.Framework.Assertions.LessEqualFixture.NotLessEqualIComparable(), NUnit.Framework.Assertions.LessFixture.NotLessIComparable(), NUnit.Framework.Assertions.LessEqualFixture.NotLessOrEqual(), NUnit.Framework.Assertions.LessFixture.NotLessWhenEqual(), NUnit.Framework.Assert.NotNull(), NUnit.Framework.Tests.AssertSyntaxTests.NotOperator(), NUnit.Framework.Assertions.NotSameFixture.NotSameFails(), NUnit.Framework.Tests.AssertSyntaxTests.NotTests(), NUnit.Framework.Assert.Null(), NUnit.Framework.Assertions.NotEqualFixture.NullEqualsNull(), NUnit.Common.Tests.TokenizerTests.NullInputThrowsException(), NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.NullTest(), NUnit.Framework.Syntax.AfterSyntaxUsingLambda.NullTest(), NUnit.Engine.Services.Tests.ResultServiceTests.NUnit3Format_NonExistentTransform_ThrowsArgumentException(), NUnit.Engine.Services.Tests.ResultServiceTests.NUnit3Format_NullArgument_ThrowsArgumentNullException(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestAndWhereClause(), NUnitLite.Tests.CreateTestFilterTests.OneTestSelected(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestSelected(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestSelected_XmlEscape(), NUnit.Framework.Internal.TestExecutionContextTests.OneTimeTearDown(), NUnit.Framework.Tests.TestContextOneTimeTearDownTests.OneTimeTearDown(), NUnit.Framework.Tests.AssertSyntaxTests.OrOperator(), NUnit.Engine.Api.Tests.TestPackageTests_MultipleAssemblies.PackageContainsThreeSubpackages(), NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.PackageIDsAreUnique(), NUnit.Framework.Attributes.TestMethodBuilderTests.PairwiseAttribute_NoArgs_NoCases(), NUnit.Framework.Attributes.TestMethodBuilderTests.PairwiseAttribute_WithArgs_Runnable(), NUnit.Framework.Attributes.ApplyToTestTests.PairwiseAttributeSetsJoinType(), NUnit.Framework.Attributes.ApplyToTestTests.PairwiseAttributeSetsJoinTypeOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToContextTests.ParallelizableAttribute(), NUnit.Framework.Internal.NUnitTestCaseBuilderTests.ParametrizedTestCaseTests(), NUnit.Framework.Internal.Filters.EmptyFilterTests.PassesAnything(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.PassesWhenDirectoryInfoExists(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.PassesWhenDirectoryStringExists(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.PassesWhenFileInfoExists(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.PassesWhenFileStringExists(), NUnit.Framework.Internal.Filters.AndFilterTests.PassTest(), NUnit.Framework.Internal.Filters.OrFilterTests.PassTest(), NUnit.Framework.Internal.Filters.IdFilterTests.PassTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.PassTest(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.PassTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.PassTest(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_InvalidPlatform(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_ProcessBitNess(), NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeRunsTest(), NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeSkipsTest(), NUnit.Framework.Assertions.EqualsFixture.PosInfinityNotEquals(), NUnit.Framework.Assertions.EqualsFixture.PosInfinityNotEqualsNegInfinity(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.PositiveEqualityTest(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.PositiveEqualityTestWithTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.PositiveEqualityTestWithToleranceAndWithSameOffset(), IG.Test.TestCrypto.Prerequisites(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.PrivateBinPathTests(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.ProperConfigFileIsUsed(), NUnit.Framework.Constraints.PropertyTest.PropertyEqualToValueWithTolerance(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_ToXml_Regex(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Attributes.PropertyAttributeTests.PropertyWithStringValue(), NUnit.Framework.Constraints.ConstraintTestBaseNoData.ProvidesProperDescription(), NUnit.Framework.Constraints.ConstraintTestBaseNoData.ProvidesProperStringRepresentation(), NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbabilityOutOfRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomByte(), NUnit.Framework.Internal.RandomizerTests.RandomByte(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomByte_ByteRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomByte_IntRange(), NUnit.Framework.Internal.RandomizerTests.RandomByteInRange(), NUnit.Framework.Internal.RandomizerTests.RandomByteInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomByteInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomByteWithMaximum(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDecimal(), NUnit.Framework.Internal.RandomizerTests.RandomDecimal(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDecimal_DoubleRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDecimal_IntRange(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalRangeTooGreat(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalWithMaximum(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDouble(), NUnit.Framework.Internal.RandomizerTests.RandomDouble(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDouble_DoubleRange(), NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange(), NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomDoubleWithMaximum(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomEnum(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomFloat(), NUnit.Framework.Internal.RandomizerTests.RandomFloat(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomFloat_FloatRange(), NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange(), NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomFloatWithMaximum(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomInt(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomInt_IntRange(), NUnit.Framework.Internal.RandomizerTests.Repeatability.RandomizersWithDifferentSeedsReturnDifferentValues(), NUnit.Framework.Internal.RandomizerTests.Repeatability.RandomizersWithSameSeedsReturnSameValues(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomLong(), NUnit.Framework.Internal.RandomizerTests.RandomLong(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomLong_LongRange(), NUnit.Framework.Internal.RandomizerTests.RandomLongInRange(), NUnit.Framework.Internal.RandomizerTests.RandomLongInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomLongInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomLongWithMaximum(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomSByte(), NUnit.Framework.Internal.RandomizerTests.RandomSByte(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomSByte_IntRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomSByte_SByteRange(), NUnit.Framework.Internal.RandomizerTests.RandomSByteInRange(), NUnit.Framework.Internal.RandomizerTests.RandomSbyteInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomSByteInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomSByteWithMaximum(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomShort(), NUnit.Framework.Internal.RandomizerTests.RandomShort(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomShort_IntRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomShort_ShortRange(), NUnit.Framework.Internal.RandomizerTests.RandomShortInRange(), NUnit.Framework.Internal.RandomizerTests.RandomShortInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomShortInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomShortWithMaximum(), NUnit.Framework.Attributes.CombinatorialTests.RandomTest(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUInt(), NUnit.Framework.Internal.RandomizerTests.RandomUInt(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUInt_UIntRange(), NUnit.Framework.Internal.RandomizerTests.RandomUIntInRange(), NUnit.Framework.Internal.RandomizerTests.RandomUintInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomUintInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomUIntWithMaximum(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomULong(), NUnit.Framework.Internal.RandomizerTests.RandomULong(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomULong_ULongRange(), NUnit.Framework.Internal.RandomizerTests.RandomULongInRange(), NUnit.Framework.Internal.RandomizerTests.RandomULongInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomULongInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomULongWithMaximum(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUShort(), NUnit.Framework.Internal.RandomizerTests.RandomUShort(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUShort_IntRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUShort_UShortRange(), NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange(), NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomUShortWithMaximum(), NUnit.Framework.Constraints.RangeTests.RangeBoundaryConditions(), NUnit.Engine.Services.Tests.ServiceDependencyTests.RecentFilesService_SettingsServiceError(), NUnit.Engine.Services.Tests.ServiceDependencyTests.RecentFilesService_SettingsServiceMissing(), NUnit.Framework.Tests.AssertSyntaxTests.RegularExpressionTests(), NUnit.Framework.Attributes.ApplyToTestTests.RepeatAttributeSetsRepeatCount(), NUnit.Framework.Attributes.ApplyToTestTests.RepeatAttributeSetsRepeatCountOnNonRunnableTest(), NUnit.Framework.Attributes.RepeatAttributeTests.RepeatWorksAsExpected(), NUnit.ConsoleRunner.Tests.ResultReporterTests.ReportSequenceTest(), NUnitLite.Tests.TextUITests.ReportSequenceTest(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.RequiredAttribute(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.RequiredAttribute(), NUnit.Framework.Attributes.ApartmentAttributeTests.ChildFixtureRequiresMTA.RequiresMTAAtributeIsInheritable(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresMTAAttributeSetsApartmentState(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresMTAAttributeSetsApartmentStateOnNonRunnableTest(), NUnit.Framework.Attributes.ApartmentAttributeTests.FixtureRequiresMTA.RequiresMTACanBeSetOnTestFixture(), NUnit.Framework.Attributes.ApartmentAttributeTests.ChildFixtureRequiresSTA.RequiresSTAAtributeIsInheritable(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresSTAAttributeSetsApartmentState(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresSTAAttributeSetsApartmentStateOnNonRunnableTest(), NUnit.Framework.Attributes.ApartmentAttributeTests.FixtureRequiresSTA.RequiresSTACanBeSetOnTestFixture(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.ChildFixtureRequiresThread.RequiresThreadAttributeIsInheritable(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeMaySetApartmentState(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeSetsRequiresThread(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeSetsRequiresThreadOnNonRunnableTest(), NUnit.Framework.Attributes.RetryAttributeTests.RetryWorksAsExpected(), NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsDifferentRandomizersForDifferentMethods(), NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForDifferentParametersOfSameMethod(), NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForSameMethod(), NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForSameParameter(), NUnit.Framework.Constraints.SamePathTest_Windows.RootPathEquality(), NUnit.Framework.Constraints.SamePathTest_Linux.RootPathEquality(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Run_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_WithoutLoad_ReturnsError(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_WithoutLoad_ReturnsError(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_WithoutLoad_ReturnsError(), NUnit.Framework.Internal.TestMethodSignatureTests.RunningTestsThroughFixtureGivesCorrectResults(), NUnit.Framework.Attributes.DatapointTests.RunTestOnFixture(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_WithoutLoad_ReturnsError(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccess(), NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccessWithDoubleDefaultValue(), NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccessWithIntDefaultValue(), NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.SameAsTest(), NUnit.Framework.Syntax.AfterSyntaxUsingLambda.SameAsTest(), NUnit.Framework.Constraints.EqualityComparerTests.SameDirectoriesAreEqual(), NUnit.Framework.Assertions.SameFixture.SameFails(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.SameLengthDifferentContent(), NUnit.Framework.Assertions.SameFixture.SameValueTypes(), NUnit.Engine.Services.Tests.RuntimeFrameworkServiceTests.SelectRuntimeFramework(), NUnit.Framework.Syntax.PropertySyntaxVariations.SeparateConstraintTest(), NUnit.Framework.Attributes.TestMethodBuilderTests.SequentialAttribute_NoArgs_NoCases(), NUnit.Framework.Attributes.TestMethodBuilderTests.SequentialAttribute_WithArgs_Runnable(), NUnit.Framework.Attributes.ApplyToTestTests.SequentialAttributeSetsJoinType(), NUnit.Framework.Attributes.ApplyToTestTests.SequentialAttributeSetsJoinTypeOnNonRunnableTest(), NUnit.Engine.Services.Tests.SettingsServiceTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.DomainManagerTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.ProjectServiceTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.TestAgencyTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.ResultServiceTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.DriverServiceTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.RuntimeFrameworkServiceTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.RecentFilesTests.ServiceIsStarted(), NUnit.Framework.Internal.PropertyBagTests.SetAddsNewSingleValue(), NUnit.Framework.Attributes.ApplyToContextTests.SetCultureAttribute(), NUnit.Framework.Attributes.ApplyToTestTests.SetCultureAttributeSetsSetCultureProperty(), NUnit.Framework.Attributes.ApplyToTestTests.SetCultureAttributeSetsSetCulturePropertyOnNonRunnableTest(), NUnit.Framework.Internal.PropertyBagTests.SetReplacesOldValues(), NUnit.Framework.Attributes.ApplyToContextTests.SetUICultureAttribute(), NUnit.Framework.Attributes.ApplyToTestTests.SetUICultureAttributeSetsSetUICultureProperty(), NUnit.Framework.Attributes.ApplyToTestTests.SetUICultureAttributeSetsSetUICulturePropertyOnNonRunnableTest(), NUnit.Framework.Tests.ActionAttributeTests.Setup(), NUnit.Framework.Internal.TextExecutionContextInAppDomain.SetUp(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestFullName(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestId(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestName(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestProperties(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpContextReflectsCurrentCulture(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpContextReflectsCurrentPrincipal(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpContextReflectsCurrentUICulture(), NUnit.Framework.Attributes.TimeoutTests.SetUpTimesOutAndTearDownIsRun(), NUnit.Framework.Constraints.RangeTests.ShouldThrowExceptionIfFromIsLessThanTo(), NUnit.Framework.Syntax.EqualityTests.SimpleEqualityTests(), NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTest(), NUnit.Framework.Attributes.TheoryTests.SimpleTestIgnoresDataPoints(), NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTestUsingBoolean(), NUnit.Framework.Attributes.CombinatorialTests.SingleArgument(), NUnit.Common.Tests.XmlHelperTests.SingleElement(), NUnit.Common.Tests.XmlHelperTests.SingleElementWithAttributes(), NUnit.Framework.Assertions.EqualsFixture.SinglePosInfinityNotEqualsNegInfinity(), NUnitLite.Tests.CreateTestFilterTests.SixTestsFromTwoTestListFiles(), NUnit.Framework.Tests.AssertSyntaxTests.SomeItemTests(), NUnit.Framework.Syntax.OperatorPrecedenceTests.SomeTests(), NUnit.Framework.Constraints.EqualityComparerTests.SpecialFloatingPointValuesCompareAsEqual(), NUnit.Common.Tests.OutputSpecificationTests.SpecMayNotBeNull(), NUnit.Common.Tests.OutputSpecificationTests.SpecOptionMustContainEqualSign(), NUnit.Common.Tests.OutputSpecificationTests.SpecOptionMustContainJustOneEqualSign(), NUnit.TestData.DatapointFixture.SquareRootTest.SqrtTimesItselfGivesOriginal(), NUnit.Framework.Attributes.TheoryTests.SqrtTests.SqrtTimesItselfGivesOriginal(), NUnit.Framework.Attributes.TheoryTests.SquareRootTest(), NUnit.Framework.StringAssert.StartsWith(), NUnit.Framework.Assertions.StringAssertTests.StartsWithFails(), NUnit.Framework.Tests.AssertSyntaxTests.StartsWithTests(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.StaticBaseSetUpCalledFirstAndTearDownCalledLast(), NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Tests.Compatibility.StopwatchTests.StopwatchIsDotNetStopwatch(), NUnit.Common.Tests.TokenizerTests.StringsMayContainEscapedQuoteChar(), NUnit.Common.Tests.TokenizerTests.StringWithDoubleQuotes(), NUnit.Common.Tests.TokenizerTests.StringWithSingleQuotes(), NUnit.Common.Tests.TokenizerTests.StringWithSlashes(), NUnit.Framework.Constraints.SubPathTest_Windows.SubPathOfRoot(), NUnit.Framework.Constraints.SubPathTest_Linux.SubPathOfRoot(), NUnit.Framework.Tests.AssertSyntaxTests.SubsetTests(), NUnit.Framework.Tests.AssertSyntaxTests.SubstringTests(), NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.SucceedsWhenKeyIsPresent(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.SucceedsWhenValueIsPresent(), NUnit.Framework.Constraints.DelayedConstraintTests.SucceedsWithGoodDelegates(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.SuiteHasCorrectNumberOfInstances(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.FailedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.SuccessResultTests.SuiteResultIsSuccess(), NUnit.ConsoleRunner.Tests.ResultReporterTests.SummaryReportTest(), NUnitLite.Tests.TextUITests.SummaryReportTest(), NUnit.Engine.Services.ResultWriters.Tests.XmlTransformResultWriterTests.SummaryTransformTest(), NUnit.Framework.Syntax.SyntaxTest.SupportedByConstraintBuilder(), NUnit.Framework.Syntax.SyntaxTest.SupportedByInheritedSyntax(), NUnit.Framework.Syntax.SyntaxTest.SupportedByStaticSyntax(), NUnit.Framework.Attributes.TestCaseAttributeTests.SupportsNullableDateTime(), NUnit.Framework.Attributes.TestCaseAttributeTests.SupportsNullableDecimal(), NUnit.Framework.Attributes.TestCaseAttributeTests.SupportsNullableTimeSpan(), NUnit.Common.Tests.TokenizerTests.SymbolTokens_DoubleChar(), NUnit.Common.Tests.TokenizerTests.SymbolTokens_SingleChar(), IG.Test.TestCrypto.SymmetricEncryptionStringToBytesPlain(), NUnit.Framework.Tests.TestContextTearDownTests.TearDown(), NUnit.Framework.Attributes.PairwiseTest.Test(), NUnit.Engine.Services.Tests.ServiceDependencyTests.TestAgency_RuntimeFrameworkServiceError(), NUnit.Engine.Services.Tests.ServiceDependencyTests.TestAgency_RuntimeFrameworkServiceMissing(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestAttribute_NoArgs_Runnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestAttribute_WithArgs_NotRunnable(), NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnFullName(), NUnit.Framework.Internal.TestExecutionContextTests.TestCanAccessItsOwnFullName(), NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnId(), NUnit.Framework.Internal.TestExecutionContextTests.TestCanAccessItsOwnId(), NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnMethodName(), NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnName(), NUnit.Framework.Internal.TestExecutionContextTests.TestCanAccessItsOwnName(), NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnProperties(), NUnit.Framework.Internal.TestExecutionContextTests.TestCanAccessItsOwnProperties(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_FailingTest(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_FailureInSetUp(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_IgnoredInSetUp(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_PassingTest(), NUnit.Framework.Tests.TestContextTests.TestCanAccessWorkDirectory(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_CategoryElementsDoNotContainProperties(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_ExecutedIsTrue(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_HasCategoryElement(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_HasPropertyElement(), NUnit.Framework.Internal.GenericTestMethodTests.TestCase_IncompatibleArgsAreNotRunnable(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_PropertyElementsDoNotContainCategories(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_ResultIsSuccess(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseAttribute_NoArgs_NotRunnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseAttribute_RightArgs_Runnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseAttribute_WrongArgs_NotRunnable(), NUnit.Framework.Tests.TestContextTests.TestCaseCanAccessItsOwnFullName(), NUnit.Framework.Tests.TestContextTests.TestCaseCanAccessItsOwnMethodName(), NUnit.Framework.Tests.TestContextTests.TestCaseCanAccessItsOwnName(), NUnit.Framework.Internal.GenericTestMethodTests.TestCaseSource_IncompatibleArgsAreNotRunnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseSourceAttribute_NoArgs_NotRunnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseSourceAttribute_RightArgs_Runnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseSourceAttribute_WrongArgs_NotRunnable(), NUnit.Framework.Constraints.MsgUtilTests.TestClipString(), NUnit.ConsoleRunner.Tests.ColorConsoleTests.TestConstructor(), NUnit.Framework.Tests.TestContextTests.TestContextOut_WritesToResult(), NUnit.Framework.Internal.TestExecutionContextTests.TestContextReflectsCurrentCulture(), NUnit.Framework.Internal.TestExecutionContextTests.TestContextReflectsCurrentPrincipal(), NUnit.Framework.Internal.TestExecutionContextTests.TestContextReflectsCurrentUICulture(), NUnit.Framework.Tests.TestContextTests.TestContextStoresFailureInfoForOneTimeTearDown(), NUnit.Framework.Tests.TestContextTests.TestContextStoresFailureInfoForTearDown(), NUnit.Framework.Tests.TestContextTests.TestContextWrite_WritesToResult(), NUnit.Framework.Tests.TestContextTests.TestContextWriteLine_WritesToResult(), NUnit.Framework.Tests.TestContextOneTimeTearDownTests.TestFalsehood(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Failed(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Ignored(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Inconclusive(), NUnitLite.Tests.TextUITests.TestFinished_NoOutput(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Passed(), NUnitLite.Tests.TextUITests.TestFinished_WithOutput(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_ExpectedAttribute(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_HasCategoryElement(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_HasPropertyElement(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_HasValidTimeAttribute(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_ResultIsFailure(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_SuccessIsFalse(), NUnit.Core.Tests.PairwiseTest.LiveTest.TestFixtureTearDown(), NUnit.Framework.Attributes.PairwiseTest.LiveTest.TestFixtureTearDown(), NUnit.Framework.Tests.Attributes.ValuesAttributeEnumTests.TestFixtureTeardown(), NUnit.ConsoleRunner.Utilities.Tests.ColorStyleTests.TestGetColor(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestGlobalDefaultTolerance_Failure(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestGlobalDefaultTolerance_Success(), NUnitLite.Tests.CreateTestFilterTests.TestListFileMissing(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodHasAttributesAppliedCorrectlyEvenIfNotRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithMultipleTestCasesExecutesMultipleTimes(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithMultipleTestCasesUsesCorrectNames(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestModeMustFollowTolerance(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestModesCanOnlyBeUsedOnce(), NUnit.Framework.Internal.TypeParameterUsedWithTestMethod< T >.TestMyArgType(), NUnit.Framework.Internal.GenericTestFixture_Numeric< T >.TestMyArgType(), NUnit.Framework.Internal.DeduceTypeArgsFromArgs< T1, T2 >.TestMyArgTypes(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_ToXml_Regex(), NUnit.Framework.Internal.TestXmlTests.TestNameWithInvalidCharacter(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestNumericToleranceRequired(), NUnit.Common.Tests.TestSelectionParserTests.TestParser(), NUnit.Common.Tests.TestSelectionParserTests.TestParser_InvalidInput(), NUnit.Framework.Constraints.EqualTests.TestPropertyWithPrivateSetter(), NUnit.Framework.Internal.MinimumDurationResultTests.TestResultHasMinimumDuration(), NUnit.Framework.Internal.DefaultResultTests.TestResultIsInconclusive(), NUnit.Framework.Internal.InconclusiveResultTests.TestResultIsInconclusive(), NUnit.Framework.Internal.SuccessResultTests.TestResultIsSuccess(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_AssemblyPathIsCorrect(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestResults_AssemblyPathIsCorrect(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_CounterIsCorrect(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestResults_CounterIsCorrect(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_HasValidDateAttribute(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestResults_HasValidDateAttribute(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_HasValidTimeAttribute(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestResults_HasValidTimeAttribute(), NUnit.Framework.Internal.FailedResultTests.TestResultXmlNodeEscapesInvalidXmlCharacters(), NUnit.ConsoleRunner.Tests.ResultReporterTests.TestsNotRunTest(), NUnitLite.Tests.TextUITests.TestsNotRunTest(), NUnit.Framework.Tests.ActionAttributeTests.TestsRunSuccessfully(), NUnitLite.Tests.TeamCityEventListenerTests.TestStarted(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_ExpectedAttribute(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_HasTestSuiteElement(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_HasValidTimeAttribute(), NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteFinished(), NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteStarted(), NUnit.Framework.Tests.TestContextTearDownTests.TestTheMeaningOfLife(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutElapsed(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutNotElapsed(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutTestCaseWithOutElapsed(), NUnit.Framework.Attributes.TimeoutTests.TestTimesOutAndTearDownIsRun(), NUnit.Framework.Tests.TestContextOneTimeTearDownTests.TestTruth(), NUnit.Framework.Internal.TestXmlTests.TestTypeTests(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestWithinCanOnlyBeUsedOnce(), NUnit.Framework.Attributes.CategoryAttributeTests.TestWithInvalidCategoryNameIsNotRunnable(), NUnit.Framework.Attributes.ApartmentAttributeTests.TestWithRequiresMTARunsInMTA(), NUnit.Framework.Attributes.ApartmentAttributeTests.TestWithRequiresSTARunsInSTA(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadRunsInSeparateThread(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadRunsSetUpAndTestOnSameThread(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadWithMTAArgRunsOnSeparateThreadInMTA(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadWithSTAArgRunsOnSeparateThreadInSTA(), NUnit.Framework.Attributes.TimeoutTests.TestWithTimeoutRunsOnSeparateThread(), NUnit.Framework.Attributes.TimeoutTests.TestWithTimeoutRunsSetUpAndTestOnSameThread(), NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.TextTest(), NUnit.Framework.Syntax.AfterSyntaxUsingLambda.TextTest(), NUnit.Framework.Assert.That(), NUnit.Framework.Assert.That< TActual >(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithoutPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithoutPolling_ReturnsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithPolling_ReturnsEarly(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithoutPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatOverload_DoesNotAcceptNegativeDelayValues(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatOverload_ZeroDelayIsAllowed(), NUnit.Framework.Attributes.TestMethodBuilderTests.TheoryAttribute_NoArgs_NoCases(), NUnit.Framework.Attributes.TestMethodBuilderTests.TheoryAttribute_WithArgs_Runnable(), NUnit.Framework.Attributes.TheoryTests.TheoryFailsIfAllTestsAreInconclusive(), NUnit.Framework.Attributes.TheoryTests.TheoryWithDatapointsIsRunnable(), NUnit.Framework.Attributes.CombinatorialTests.ThreeArguments_Combinatorial(), NUnit.Framework.Attributes.CombinatorialTests.ThreeArguments_Sequential(), NUnit.TestData.AssertCountFixture.ThreeAsserts(), NUnitLite.Tests.CreateTestFilterTests.ThreeTestsFromATestListFile(), NUnitLite.Tests.CreateTestFilterTests.ThreeTestsSelected(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.ThreeTestsSelected(), NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionException(), NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionException_MessageSpecified(), NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionExceptionWithMessage(), NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionExceptionWithMessageAndArgs(), NUnit.Framework.Assertions.AssertIgnoreTests.ThrowsIgnoreException(), NUnit.Framework.Assertions.AssertIgnoreTests.ThrowsIgnoreExceptionWithMessage(), NUnit.Framework.Assertions.AssertIgnoreTests.ThrowsIgnoreExceptionWithMessageAndArgs(), NUnit.Framework.Assertions.AssertInconclusiveTests.ThrowsInconclusiveException(), NUnit.Framework.Assertions.AssertInconclusiveTests.ThrowsInconclusiveExceptionWithMessage(), NUnit.Framework.Assertions.AssertInconclusiveTests.ThrowsInconclusiveExceptionWithMessageAndArgs(), NUnit.Framework.Assertions.AssertPassTests.ThrowsSuccessException(), NUnit.Framework.Assertions.AssertPassTests.ThrowsSuccessExceptionWithMessage(), NUnit.Framework.Assertions.AssertPassTests.ThrowsSuccessExceptionWithMessageAndArgs(), NUnit.Framework.Attributes.ApplyToContextTests.TimeoutAttribute(), NUnit.Framework.Attributes.TimeoutTests.TimeoutCanBeSetOnTestFixture(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.TopLevelSuiteIsNamedCorrectly(), NUnit.Common.Tests.OutputSpecificationTests.TransformWithNonUserFormatNotAllowed(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.TripleDimensionedArrays(), NUnit.Framework.Assert.True(), NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.TrueTest(), NUnit.Framework.Syntax.AfterSyntaxUsingLambda.TrueTest(), NUnit.Framework.Attributes.CombinatorialTests.TwoArguments_Combinatorial(), NUnit.Framework.Attributes.CombinatorialTests.TwoArguments_Sequential(), NUnit.Framework.Assertions.ArrayEqualsFixture.TwoArraySegments(), NUnit.Framework.Assertions.ArrayEqualsFixture.TwoEmptyArraySegments(), NUnitLite.Tests.CreateTestFilterTests.TwoTestsAndWhereClauseSpecified(), NUnit.Framework.Constraints.NUnitComparerTests.UnequalItems(), NUnit.Framework.Assertions.CollectionAssertTest.UniqueFailure(), NUnit.Framework.Assertions.AssertThrowsTests.UnrelatedExceptionThrown(), NUnit.Common.Tests.OutputSpecificationTests.UserFormatMayBeIndicatedExplicitlyAfterTransform(), NUnit.Common.Tests.OutputSpecificationTests.UserFormatMayBeIndicatedExplicitlyBeforeTransform(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedArrayComparer(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedEqualityComparer(), NUnit.Framework.Constraints.ComparisonConstraintTestBase.UsesProvidedGenericComparer(), NUnit.Framework.Constraints.RangeConstraintTest.UsesProvidedGenericComparer(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.UsesProvidedGenericComparer(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedGenericComparer(), NUnit.Framework.Constraints.ComparisonConstraintTestBase.UsesProvidedGenericComparison(), NUnit.Framework.Constraints.RangeConstraintTest.UsesProvidedGenericComparison(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.UsesProvidedGenericComparison(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedGenericComparison(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedGenericEqualityComparer(), NUnit.Framework.Constraints.ComparisonConstraintTestBase.UsesProvidedIComparer(), NUnit.Framework.Constraints.RangeConstraintTest.UsesProvidedIComparer(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedIComparer(), NUnit.Framework.Constraints.RangeConstraintTest.UsesProvidedLambda(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.UsesProvidedLambda(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedLambda_IntArgs(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedLambda_StringArgs(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedListComparer(), NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.UsingIsHonored(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.UsingIsHonored(), NUnit.Framework.Constraints.CollectionContainsConstraintTests.UsingIsHonored(), NUnit.Engine.Services.Tests.TestFilteringTests.UsingTestFilterBuilderAddTest(), NUnit.Engine.Services.Tests.TestFilteringTests.UsingTestFilterBuilderSelectWhere(), NUnit.Engine.Services.Tests.TestFilteringTests.UsingXml(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.ValidExtensions(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayBeGeneric(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayNotBeInstanceField(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayNotBeInstanceMethod(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayNotBeInstanceProperty(), NUnit.ConsoleRunner.Tests.MakeTestPackageTests.WhenDebugging_NumberOfTestWorkersDefaultsToZero(), NUnit.ConsoleRunner.Tests.MakeTestPackageTests.WhenDebugging_NumberOfTestWorkersMayBeOverridden(), NUnit.ConsoleRunner.Tests.MakeTestPackageTests.WhenNoOptionsAreSpecified_PackageContainsWorkDirectorySettingOnly(), NUnit.ConsoleRunner.Tests.MakeTestPackageTests.WhenOptionIsSpecified_PackageIncludesSetting(), NUnitLite.Tests.MakeRunSettingsTests.WhenSeedIsSpecified_RunSettingsIncludeIt(), NUnitLite.Tests.MakeRunSettingsTests.WhenTimeoutIsSpecified_RunSettingsIncludeIt(), NUnitLite.Tests.MakeRunSettingsTests.WhenWorkDirectoryIsSpecified_RunSettingsIncludeIt(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.WhereClause(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.WhereClause_XmlEscape(), NUnitLite.Tests.CreateTestFilterTests.WhereClauseSpecified(), NUnit.Framework.Syntax.OperatorPrecedenceTests.WithTests(), NUnit.Framework.Internal.SetUpFixtureTests.WithTwoSetUpFixturesBothAreUsed(), NUnit.Common.Tests.TokenizerTests.WordsInUnicode(), NUnit.Framework.Constraints.AllItemsConstraintTests.WorksOnICollection(), NUnit.Framework.Constraints.CollectionEquivalentConstraintTests.WorksWithCollectionsOfArrays(), NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.WorksWithNonGenericDictionary(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.WorksWithNonGenericDictionary(), NUnit.Common.Tests.ExtendedTextWrapperTests.Write(), NUnit.Common.Tests.ExtendedTextWrapperTests.Write_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine_ColorStyle(), NUnit.Framework.Attributes.Tests.CommandWrapperTests.WrongExceptionThrown(), NUnit.Framework.Internal.PropertyBagTests.XmlIsProducedCorrectly(), NUnit.Framework.Constraints.ExactCountConstraintTests.ZeroItemsMatch(), and NUnit.Framework.Constraints.ExactCountConstraintTests.ZeroItemsMatchFails().
static void NUnit.Framework.Assert.That (bool condition) inline static
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
Parameters
condition The evaluated condition
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
static void NUnit.Framework.Assert.That (Func< bool > condition, string message, params object[] args) inline static
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
Parameters
condition A lambda that returns a Boolean
message The message to display if the condition is false
args Arguments to be used in formatting the message
static void NUnit.Framework.Assert.That (Func< bool > condition) inline static
Asserts that a condition is true. If the condition is false the method throws an AssertionException.
Parameters
condition A lambda that returns a Boolean
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
static void NUnit.Framework.Assert.That< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr) inline static
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
Parameters
expr A Constraint expression to be applied
del An ActualValueDelegate returning the value to be tested
References NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.That< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr, string message, params object[] args) inline static
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
Parameters
del An ActualValueDelegate returning the value to be tested
expr A Constraint expression to be applied
message The message that will be displayed on failure
args Arguments to be used in formatting the message
static void NUnit.Framework.Assert.That (TestDelegate code, IResolveConstraint constraint) inline static
Asserts that the code represented by a delegate throws an exception that satisfies the constraint provided.
Parameters
code A TestDelegate to be executed
constraint A ThrowsConstraint used in the test
References NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.That (TestDelegate code, IResolveConstraint constraint, string message, params string[] args) inline static
Asserts that the code represented by a delegate throws an exception that satisfies the constraint provided.
Parameters
code A TestDelegate to be executed
constraint A ThrowsConstraint used in the test
message The message that will be displayed on failure
args Arguments to be used in formatting the message
References NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.That< TActual > (TActual actual, IResolveConstraint expression) inline static
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
Parameters
expression A Constraint to be applied
actual The actual value to test
References NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.That< TActual > (TActual actual, IResolveConstraint expression, string message, params object[] args) inline static
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
Parameters
expression A Constraint expression to be applied
actual The actual value to test
message The message that will be displayed on failure
args Arguments to be used in formatting the message
static void NUnit.Framework.Assert.ByVal (object actual, IResolveConstraint expression) inline static
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure. Used as a synonym for That in rare cases where a private setter causes a Visual Basic compilation error.
Parameters
expression A Constraint to be applied
actual The actual value to test
References NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.ByVal (object actual, IResolveConstraint expression, string message, params object[] args) inline static
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure. Used as a synonym for That in rare cases where a private setter causes a Visual Basic compilation error.
This method is provided for use by VB developers needing to test the value of properties with private setters.
Parameters
expression A Constraint expression to be applied
actual The actual value to test
message The message that will be displayed on failure
args Arguments to be used in formatting the message
References NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsAssignableFrom (Type expected, object actual, string message, params object[] args) inline static
Asserts that an object may be assigned a value of a given Type.
Parameters
expected The expected Type.
actual The object under examination
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.AssignableFrom(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AssignableFromTypeTests(), and NUnit.Framework.Assertions.TypeAssertTests.IsAssignableFrom().
static void NUnit.Framework.Assert.IsAssignableFrom (Type expected, object actual) inline static
Asserts that an object may be assigned a value of a given Type.
Parameters
expected The expected Type.
actual The object under examination
References NUnit.Framework.Is.AssignableFrom(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsAssignableFrom< TExpected > (object actual, string message, params object[] args) inline static
Asserts that an object may be assigned a value of a given Type.
Template Parameters
TExpected The expected Type.
Parameters
actual The object under examination
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.AssignableFrom(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsAssignableFrom< TExpected > (object actual) inline static
Asserts that an object may be assigned a value of a given Type.
Template Parameters
TExpected The expected Type.
Parameters
actual The object under examination
References NUnit.Framework.Is.AssignableFrom(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNotAssignableFrom (Type expected, object actual, string message, params object[] args) inline static
Asserts that an object may not be assigned a value of a given Type.
Parameters
expected The expected Type.
actual The object under examination
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AssignableFromTypeTests(), and NUnit.Framework.Assertions.TypeAssertTests.IsNotAssignableFrom().
static void NUnit.Framework.Assert.IsNotAssignableFrom (Type expected, object actual) inline static
Asserts that an object may not be assigned a value of a given Type.
Parameters
expected The expected Type.
actual The object under examination
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNotAssignableFrom< TExpected > (object actual, string message, params object[] args) inline static
Asserts that an object may not be assigned a value of a given Type.
Template Parameters
TExpected The expected Type.
Parameters
actual The object under examination
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNotAssignableFrom< TExpected > (object actual) inline static
Asserts that an object may not be assigned a value of a given Type.
Template Parameters
TExpected The expected Type.
Parameters
actual The object under examination
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsInstanceOf (Type expected, object actual, string message, params object[] args) inline static
Asserts that an object is an instance of a given type.
Parameters
expected The expected Type
actual The object being examined
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.InstanceOf(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.InstanceOfTests(), and NUnit.Framework.Assertions.TypeAssertTests.IsInstanceOf().
static void NUnit.Framework.Assert.IsInstanceOf (Type expected, object actual) inline static
Asserts that an object is an instance of a given type.
Parameters
expected The expected Type
actual The object being examined
References NUnit.Framework.Is.InstanceOf(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsInstanceOf< TExpected > (object actual, string message, params object[] args) inline static
Asserts that an object is an instance of a given type.
Template Parameters
TExpected The expected Type
Parameters
actual The object being examined
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.InstanceOf(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsInstanceOf< TExpected > (object actual) inline static
Asserts that an object is an instance of a given type.
Template Parameters
TExpected The expected Type
Parameters
actual The object being examined
References NUnit.Framework.Is.InstanceOf(), and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNotInstanceOf (Type expected, object actual, string message, params object[] args) inline static
Asserts that an object is not an instance of a given type.
Parameters
expected The expected Type
actual The object being examined
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.InstanceOfTests(), NUnit.Framework.Assertions.TypeAssertTests.IsNotInstanceOf(), and NUnit.Framework.Assertions.TypeAssertTests.IsNotInstanceOfFails().
static void NUnit.Framework.Assert.IsNotInstanceOf (Type expected, object actual) inline static
Asserts that an object is not an instance of a given type.
Parameters
expected The expected Type
actual The object being examined
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNotInstanceOf< TExpected > (object actual, string message, params object[] args) inline static
Asserts that an object is not an instance of a given type.
Template Parameters
TExpected The expected Type
Parameters
actual The object being examined
message The message to display in case of failure
args Array of objects to be used in formatting the message
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
static void NUnit.Framework.Assert.IsNotInstanceOf< TExpected > (object actual) inline static
Asserts that an object is not an instance of a given type.
Template Parameters
TExpected The expected Type
Parameters
actual The object being examined
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following files:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Assert.Comparisons.cs
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Assert.Conditions.cs
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Assert.cs
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Assert.Equality.cs
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Assert.Exceptions.cs
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Assert.That.cs
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Assert.Types.cs