IGLib: LabexBis.Calypso Class Reference
LabexBis.Calypso Class Reference
Utilities for communication with the web service Calypso.
Public Member Functions
void TestAfterReceiverStarted ()
Performs some tests after the receiver has been started. This function is here for debuggind purposes. It should be called after the receiver is started, and it can be empty in the release version of the application.
bool TestWs (out string Id)
Returns true if the communication web service is responding, and false if it is not.
bool TestWs ()
Returns true if the communication web service is responding, and false if it is not.
string GetUniqueID ()
Gets a unique ID from the Calypso web service and returns it.
void SendMessageToMyself (string message, string msgid)
Sends a msg that is contained in msg, to the Labex queue. If necessary then the msg is modified such that the right receiver is set in it (i.e. Labex)
void SendMessageToBis (string message, string msgid)
Sends a msg that is contained in msg, to the Bis queue.
void SendMessage (string message, string receiver, string msgid)
Sends a msg to the specified receiver through the calypso WS.
void SendOoNullifyToBis (string connectionstring, int IdRsr)
Sends nullification message for the specified Observation order, to the Bis queue. Original observation order message (as stored in the database) is modified in such a way that the right action code, receiver, sender and responder are set in it, and the specified comment is set in the message. Original message XML is obtained from the message table through the ID in tbl01_RSR.
void SendOoNullifyToBis (MsgObervationOrder msg, string comment)
Sends nullification message for the Observation order that is contained in msg, to the Bis queue. msg is modified in such a way that the right action code, receiver, sender and responder are set in it, and the specified comment is set.
void SendOoNullifyToBis (string message, string msgid, string comment)
Sends nullification message for the Observation order that is contained in message, to the Bis queue. message is modified in such a way that the right action code, receiver, sender and responder are set in it, and the specified comment is set.
void ConfirmMessageReceipt (string Id)
Sends confirmation back to the WS massage queue that the msg with the specified ID has been received and treated and that it doed not need to be kept in the queue any more.
void ConfirmMessageReceipt (string Id, string queueName)
Sends confirmation back to the WS massage queue that the msg with the specified ID has been received and treated and that it doed not need to be kept in the queue any more.
void SaveIncomingMessage (MsgBase msg)
Saves the msg Xml to a file. File name is determined according to seddings. No GUID is added to file name.
void SaveIncomingMessage (MsgBase msg, bool addGuid)
Saves the msg Xml to a file. File name is determined according to seddings.
void SaveIncomingMessage (MsgBase msg, string filename)
Saves the msg Xml to a file with a specified name.
MsgBase GetMessage ()
Receives the last msg from the Calypso web service and returns msg object.
void GetMessage (out string Id, out string MessageText)
Receives a msg from the Calypso web service and returns msg Id and Text.
LabexBis.WebReference.Message GetNextMessage ()
Receives a new msg from the Calypso web service and returns it. The msg is also stored to a file whose name is determined from the msg ID.
void Dispose ()
Public Attributes
BisCommunicationSettings Settings = new BisCommunicationSettings()
Protected Member Functions
MsgBase GetMessage (string hl7version)
Receives the last msg from the Calypso web service and returns msg object. The message is also storedto a file whose name is determined from the msg ID. Version of the standard must also be specified.
void GetMessage (string HL7Version, out string Id, out string MessageText)
Receives a msg from the Calypso web service and returns msg Id and Text.
LabexBis.WebReference.Message GetNextMessage (string hl7version)
Receives a new msg from the Calypso web service and returns it.
Properties
static IReporter R [get]
Reporter for this class.
MsgConst Const [get]
Gets objects that contains all constants related to communication messages.
static Calypso Global [get]
Global communication object (application-wide).
LabexBis.WebReference.CalypsoWSNSService Service [get]
Web service used for sending messages between systems.
string ReceiverBis [get]
string ReceiverLabex [get]
Private Member Functions
void ReceiveAndProcessMessage (bool ReadFromWS)
Receives and processes one msg from the callypso server. Dependent on Pado server settings, msg can aldo be read from a file (for testing purposes).
void ReceiverThreadMain ()
Periodically receives messages from Calypso and works them.
void SendMessage (string hl7version, string msg, string receiver, string msgid)
Sending a msg to WS with HL7 version specification.
Private Attributes
LabexBis.WebReference.CalypsoWSNSService _service = null
const string QueueNameLabex = "Labex"
const string QueueNameBis = ""
const string HL7Version = "v30"
bool _dbCmdInitialized = false
int PauseBetweenReads_ms = 5000
int PauseBeforeReads_ms = 400
bool ControlOutputs = true
bool ReceiverRun = false
Static Private Attributes
static IReporter _rep = new ReporterConsole()
static Calypso _global = null
Detailed Description
Utilities for communication with the web service Calypso.
Member Function Documentation
void LabexBis.Calypso.ReceiveAndProcessMessage (bool ReadFromWS) inline private
Receives and processes one msg from the callypso server. Dependent on Pado server settings, msg can aldo be read from a file (for testing purposes).
Parameters
ReadFromWs If false then msg is not read from the web service but from a file.
void LabexBis.Calypso.ReceiverThreadMain () inline private
Periodically receives messages from Calypso and works them.
void LabexBis.Calypso.TestAfterReceiverStarted () inline
Performs some tests after the receiver has been started. This function is here for debuggind purposes. It should be called after the receiver is started, and it can be empty in the release version of the application.
bool LabexBis.Calypso.TestWs (out string Id) inline
Returns true if the communication web service is responding, and false if it is not.
Parameters
Id Output parameter through which a unique Id returned by the web service is obtained when the web service is responding properly.
Returns
References LabexBis.Calypso.GetUniqueID().
Referenced by IGTest.ProgramIGTest.TestCalypsoWs().
bool LabexBis.Calypso.TestWs () inline
Returns true if the communication web service is responding, and false if it is not.
string LabexBis.Calypso.GetUniqueID () inline
Gets a unique ID from the Calypso web service and returns it.
Returns
The ID received from the web service.
References IG.Lib.IReporterBase.Depth, LabexBis.Calypso.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.ReporterBase.ReviseException(), LabexBis.Calypso.Service, and IG.Lib.IReporterBase.TreatInfo.
Referenced by IGTest.ProgramIGTest.TestcalypsoWsSimple(), and LabexBis.Calypso.TestWs().
void LabexBis.Calypso.SendMessageToMyself (string message, string msgid) inline
Sends a msg that is contained in msg, to the Labex queue. If necessary then the msg is modified such that the right receiver is set in it (i.e. Labex)
Parameters
msg Xml document containing the msg to be sent.
msgid Message Id.
References LabexBis.Calypso.ReceiverLabex, and LabexBis.Calypso.SendMessage().
Referenced by IGTest.ProgramIGTest.TestCalypsoWs().
void LabexBis.Calypso.SendMessageToBis (string message, string msgid) inline
Sends a msg that is contained in msg, to the Bis queue.
If necessary then the msg is modified such that the right receiver is set in it (i.e. Bis)
Parameters
msg Xml document containing the msg to be sent.
msgid Message Id.
References LabexBis.Calypso.ReceiverBis, and LabexBis.Calypso.SendMessage().
Referenced by LabexBis.Calypso.SendOoNullifyToBis(), IGTest.ProgramIGTest.TestMsgFinancialTransaction(), and IGTest.ProgramIGTest.TestMsgObservationEvent().
void LabexBis.Calypso.SendMessage (string message, string receiver, string msgid) inline
Sends a msg to the specified receiver through the calypso WS.
Parameters
msg Xml document containing the msg to be sent.
receiver Code of the application that will receive the msg.
msgid Message Id.
References LabexBis.Calypso.HL7Version.
Referenced by LabexBis.Calypso.SendMessageToBis(), and LabexBis.Calypso.SendMessageToMyself().
void LabexBis.Calypso.SendMessage (string hl7version, string msg, string receiver, string msgid) inline private
Sending a msg to WS with HL7 version specification.
Parameters
hl7version Version of the HL7 specification.
msg Xml document containing the msg to be sent.
receiver Code of the application that will receive the msg.
msgid Message Id.
References IG.Lib.IReporterBase.Depth, LabexBis.Calypso.HL7Version, LabexBis.BisCommunicationSettings.OutgoingFileName(), LabexBis.Calypso.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), LabexBis.Calypso.Service, IG.Lib.MsgBase.SetMessageReceiver(), and IG.Lib.IReporterBase.TreatInfo.
void LabexBis.Calypso.SendOoNullifyToBis (string connectionstring, int IdRsr) inline
Sends nullification message for the specified Observation order, to the Bis queue. Original observation order message (as stored in the database) is modified in such a way that the right action code, receiver, sender and responder are set in it, and the specified comment is set in the message. Original message XML is obtained from the message table through the ID in tbl01_RSR.
Parameters
ConnectionString
IdRsR
comment
References LabexBis.Calypso.R, IG.Lib.IReporterBase.ReportError(), and IG.Lib.IReporterBase.ReportInfo().
Referenced by IGTest.ProgramIGTest.TestMsgObservationOrderNullifySend().
void LabexBis.Calypso.SendOoNullifyToBis (MsgObervationOrder msg, string comment) inline
Sends nullification message for the Observation order that is contained in msg, to the Bis queue. msg is modified in such a way that the right action code, receiver, sender and responder are set in it, and the specified comment is set.
Parameters
msg Xml document containing the original observation order to be nullified.
msgid Message Id.
comment Comment that is set in the message.
References IG.Lib.ParsableXmlObject.Doc, IG.Lib.MsgBase.MessageId, IG.Lib.MsgBase.MessageNumber, IG.Lib.MsgObervationOrder.PrepareOoNullify(), LabexBis.Calypso.SendMessageToBis(), and IG.Lib.MsgBase.Type.
void LabexBis.Calypso.SendOoNullifyToBis (string message, string msgid, string comment) inline
Sends nullification message for the Observation order that is contained in message, to the Bis queue. message is modified in such a way that the right action code, receiver, sender and responder are set in it, and the specified comment is set.
Parameters
message Xml document containing the original observation order to be nullified.
msgid Message Id. Needed to form the file name where message is stored before sending.
comment Comment that is set in the message.
References IG.Lib.MsgObervationOrder.PrepareOoNullify(), and LabexBis.Calypso.SendMessageToBis().
void LabexBis.Calypso.ConfirmMessageReceipt (string Id) inline
Sends confirmation back to the WS massage queue that the msg with the specified ID has been received and treated and that it doed not need to be kept in the queue any more.
Parameters
Id Id of the received msg (as obtained from the web service).
References LabexBis.Calypso.QueueNameLabex.
Referenced by IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder().
void LabexBis.Calypso.ConfirmMessageReceipt (string Id, string queueName) inline
Sends confirmation back to the WS massage queue that the msg with the specified ID has been received and treated and that it doed not need to be kept in the queue any more.
Parameters
Id Id of the received msg (as obtained from the web service).
queuwName Name of the queue from which the msg has been picked.
References IG.Lib.IReporterBase.Depth, LabexBis.Calypso.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), LabexBis.Calypso.Service, and IG.Lib.IReporterBase.TreatInfo.
void LabexBis.Calypso.SaveIncomingMessage (MsgBase msg) inline
Saves the msg Xml to a file. File name is determined according to seddings. No GUID is added to file name.
Parameters
msg Message to be saved.
References LabexBis.BisCommunicationSettings.IncomingFileName(), and IG.Lib.MsgBase.MessageId.
Referenced by IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), and LabexBis.Calypso.SaveIncomingMessage().
void LabexBis.Calypso.SaveIncomingMessage (MsgBase msg, bool addGuid) inline
Saves the msg Xml to a file. File name is determined according to seddings.
Parameters
msg Message to be saved.
addGuid If true then GUID is added to file name.
References LabexBis.BisCommunicationSettings.IncomingFileName(), IG.Lib.MsgBase.MessageId, and LabexBis.Calypso.SaveIncomingMessage().
void LabexBis.Calypso.SaveIncomingMessage (MsgBase msg, string filename) inline
Saves the msg Xml to a file with a specified name.
Parameters
msg Message object whose Xml is saved.
filename Name of a file into which the object is saved.
References IG.Lib.MsgBase.MessageXml.
MsgBase LabexBis.Calypso.GetMessage () inline
Receives the last msg from the Calypso web service and returns msg object.
References LabexBis.Calypso.HL7Version.
Referenced by LabexBis.Calypso.GetMessage(), IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), IGTest.ProgramIGTest.TestCalypsoWs(), and IGTest.ProgramIGTest.TestcalypsoWsSimple().
MsgBase LabexBis.Calypso.GetMessage (string hl7version) inline protected
Receives the last msg from the Calypso web service and returns msg object. The message is also storedto a file whose name is determined from the msg ID. Version of the standard must also be specified.
References LabexBis.Calypso.GetMessage(), IG.Lib.MsgBase.GetMessageType(), LabexBis.BisCommunicationSettings.IncomingFileName(), IG.Lib.MsgBase.MessageFile, IG.Lib.MsgBase.MessageId, IG.Lib.MsgBase.MessageXml, LabexBis.Calypso.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
void LabexBis.Calypso.GetMessage (out string Id, out string MessageText) inline
Receives a msg from the Calypso web service and returns msg Id and Text.
Parameters
Id messagestr ID that is a part of the received msg.
MessageText messagestr itself.
References LabexBis.Calypso.GetMessage(), and LabexBis.Calypso.HL7Version.
void LabexBis.Calypso.GetMessage (string HL7Version, out string Id, out string MessageText) inline protected
Receives a msg from the Calypso web service and returns msg Id and Text.
Parameters
hl7version Version of the HL7 standard according to which the msg is assembled.
Id messagestr ID that is a part of the received msg.
MessageText messagestr itself.
References IG.Lib.IReporterBase.Depth, LabexBis.Calypso.GetNextMessage(), LabexBis.Calypso.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
LabexBis.WebReference.Message LabexBis.Calypso.GetNextMessage () inline
Receives a new msg from the Calypso web service and returns it. The msg is also stored to a file whose name is determined from the msg ID.
Returns
The msg received.
References LabexBis.Calypso.HL7Version.
Referenced by LabexBis.Calypso.GetMessage().
LabexBis.WebReference.Message LabexBis.Calypso.GetNextMessage (string hl7version) inline protected
Receives a new msg from the Calypso web service and returns it.
Parameters
hl7version The version of the HL7 standard used for messages.
Returns
The msg received.
References IG.Lib.IReporterBase.Depth, LabexBis.Calypso.HL7Version, LabexBis.Calypso.QueueNameLabex, LabexBis.Calypso.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.ReportWarning(), IG.Lib.ReporterBase.ReviseException(), LabexBis.Calypso.Service, IG.Lib.IReporterBase.TreatInfo, and IG.Lib.IReporterBase.TreatWarning.
void LabexBis.Calypso.Dispose () inline
Member Data Documentation
IReporter LabexBis.Calypso._rep = new ReporterConsole() static private
Calypso LabexBis.Calypso._global = null static private
LabexBis.WebReference.CalypsoWSNSService LabexBis.Calypso._service = null private
const string LabexBis.Calypso.QueueNameLabex = "Labex" private
Referenced by LabexBis.Calypso.ConfirmMessageReceipt(), and LabexBis.Calypso.GetNextMessage().
const string LabexBis.Calypso.QueueNameBis = "" private
const string LabexBis.Calypso.HL7Version = "v30" private
Referenced by LabexBis.Calypso.GetMessage(), LabexBis.Calypso.GetNextMessage(), and LabexBis.Calypso.SendMessage().
BisCommunicationSettings LabexBis.Calypso.Settings = new BisCommunicationSettings()
Referenced by IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), IGTest.ProgramIGTest.TestCalypsoWs(), IGTest.ProgramIGTest.TestcalypsoWsSimple(), IGTest.ProgramIGTest.TestMsgFinancialTransaction(), IGTest.ProgramIGTest.TestMsgObservationEvent(), IGTest.ProgramIGTest.TestMsgObservationOrder(), IGTest.ProgramIGTest.TestMsgObservationOrderNullify(), and IGTest.ProgramIGTest.TestMsgObservationOrderNullifySend().
bool LabexBis.Calypso._dbCmdInitialized = false private
int LabexBis.Calypso.PauseBetweenReads_ms = 5000 private
int LabexBis.Calypso.PauseBeforeReads_ms = 400 private
bool LabexBis.Calypso.ControlOutputs = true private
bool LabexBis.Calypso.ReceiverRun = false private
Property Documentation
IReporter LabexBis.Calypso.R static get
Reporter for this class.
Referenced by LabexBis.Calypso.ConfirmMessageReceipt(), LabexBis.Calypso.GetMessage(), LabexBis.Calypso.GetNextMessage(), LabexBis.Calypso.GetUniqueID(), LabexBis.Calypso.SendMessage(), and LabexBis.Calypso.SendOoNullifyToBis().
MsgConst LabexBis.Calypso.Const get protected
Gets objects that contains all constants related to communication messages.
Calypso LabexBis.Calypso.Global static get
Global communication object (application-wide).
Referenced by IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), IGTest.ProgramIGTest.TestCalypsoWs(), IGTest.ProgramIGTest.TestcalypsoWsSimple(), IGTest.ProgramIGTest.TestMsgFinancialTransaction(), IGTest.ProgramIGTest.TestMsgObservationEvent(), IGTest.ProgramIGTest.TestMsgObservationOrder(), IGTest.ProgramIGTest.TestMsgObservationOrderNullify(), and IGTest.ProgramIGTest.TestMsgObservationOrderNullifySend().
LabexBis.WebReference.CalypsoWSNSService LabexBis.Calypso.Service get protected
Web service used for sending messages between systems.
Referenced by LabexBis.Calypso.ConfirmMessageReceipt(), LabexBis.Calypso.GetNextMessage(), LabexBis.Calypso.GetUniqueID(), and LabexBis.Calypso.SendMessage().
string LabexBis.Calypso.ReceiverBis get
Referenced by LabexBis.Calypso.SendMessageToBis().
string LabexBis.Calypso.ReceiverLabex get
Referenced by LabexBis.Calypso.SendMessageToMyself().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/LabexBis/WSBis.cs