IGLib: NUnit.Common.XmlHelper Class Reference
NUnit.Common.XmlHelper Class Reference
XmlHelper provides static methods for basic XML operations.
Static Public Member Functions
static XmlNode CreateTopLevelElement (string name)
Creates a new top level element node.
static XmlNode CreateXmlNode (string xml)
static void AddAttribute (this XmlNode node, string name, string value)
Adds an attribute with a specified name and value to an existing XmlNode.
static XmlNode AddElement (this XmlNode node, string name)
Adds a new element as a child of an existing XmlNode and returns it.
static XmlNode AddElementWithCDataSection (this XmlNode node, string name, string data)
Adds the a new element as a child of an existing node and returns it. A CDataSection is added to the new element using the data provided.
static string GetAttribute (this XmlNode result, string name)
Gets the value of the given attribute.
static int GetAttribute (this XmlNode result, string name, int defaultValue)
Gets the value of the given attribute as an int.
static double GetAttribute (this XmlNode result, string name, double defaultValue)
Gets the value of the given attribute as a double.
static DateTime GetAttribute (this XmlNode result, string name, DateTime defaultValue)
Gets the value of the given attribute as a DateTime.
Detailed Description
XmlHelper provides static methods for basic XML operations.
Member Function Documentation
static XmlNode NUnit.Common.XmlHelper.CreateTopLevelElement (string name) inline static
Creates a new top level element node.
Parameters
name The element name.
Returns
A new XmlNode
Referenced by NUnit.Engine.Runners.ProcessRunner.CreateFailedResult(), NUnit.Common.Tests.XmlHelperTests.ElementContainsElementWithCData(), NUnit.Common.Tests.XmlHelperTests.ElementContainsElementWithInnerText(), NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccess(), NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccessWithDoubleDefaultValue(), NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccessWithIntDefaultValue(), NUnit.Common.Tests.XmlHelperTests.SingleElement(), and NUnit.Common.Tests.XmlHelperTests.SingleElementWithAttributes().
static XmlNode NUnit.Common.XmlHelper.CreateXmlNode (string xml) inline static
Referenced by NUnit.Engine.Runners.MasterTestRunner.InsertFilterElement().
static void NUnit.Common.XmlHelper.AddAttribute (this XmlNode node, string name, string value) inline static
Adds an attribute with a specified name and value to an existing XmlNode.
Parameters
node The node to which the attribute should be added.
name The name of the attribute.
value The value of the attribute.
Referenced by NUnit.Engine.Runners.ProcessRunner.CreateFailedResult(), and NUnit.Common.Tests.XmlHelperTests.SingleElementWithAttributes().
static XmlNode NUnit.Common.XmlHelper.AddElement (this XmlNode node, string name) inline static
Adds a new element as a child of an existing XmlNode and returns it.
Parameters
node The node to which the element should be added.
name The element name.
Returns
The newly created child element
static XmlNode NUnit.Common.XmlHelper.AddElementWithCDataSection (this XmlNode node, string name, string data) inline static
Adds the a new element as a child of an existing node and returns it. A CDataSection is added to the new element using the data provided.
Parameters
node The node to which the element should be added.
name The element name.
data The data for the CDataSection.
Returns
static string NUnit.Common.XmlHelper.GetAttribute (this XmlNode result, string name) inline static
Gets the value of the given attribute.
Parameters
result The result.
name The name.
Returns
Referenced by NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccess(), and NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccessWithIntDefaultValue().
static int NUnit.Common.XmlHelper.GetAttribute (this XmlNode result, string name, int defaultValue) inline static
Gets the value of the given attribute as an int.
Parameters
result The result.
name The name.
defaultValue The default value.
Returns
static double NUnit.Common.XmlHelper.GetAttribute (this XmlNode result, string name, double defaultValue) inline static
Gets the value of the given attribute as a double.
Parameters
result The result.
name The name.
defaultValue The default value.
Returns
static DateTime NUnit.Common.XmlHelper.GetAttribute (this XmlNode result, string name, DateTime defaultValue) inline static
Gets the value of the given attribute as a DateTime.
Parameters
result The result.
name The name.
defaultValue The default value.
Returns
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/XmlHelper.cs