IGLib: IG.Num.VectorFunctionBaseComponentWise Class Reference
IG.Num.VectorFunctionBaseComponentWise Class Reference abstract
Base class for defining Vector functions whose component-wise evaluation is defined directly.
Public Member Functions
override void Evaluate (IVectorFunctionResults evaluationData)
Performs evaluation of requwester function results and writes them to the provided data structure. Uses Evaluate(IVector, ref bool, ref List{double}, ref bool, ref List{IVector}, ref bool, ref List{IMatrix}) to do the job.
abstract override double Value (IVectorFunctionResults evaluationData, int which)
Calculates and returns the particular component of the vector function value.
abstract override double Derivative (IVectorFunctionResults evaluationData, int which, int component)
Calculates and returns the particular component of the vector function derivative.
abstract override double SecondDerivative (IVectorFunctionResults evaluationData, int which, int rowNum, int columnNum)
Calculates and returns the particular component of the vector function's second derivative (Hessian).
override void Evaluate (IVector parameters, ref bool calculateValues, ref List< double > values, ref bool calculateGradients, ref List< IVector > gradients, ref bool calculateHessians, ref List< IMatrix > hessians)
Calculation of values, gradients, and hessians of the vector function according to request flags. Uses functions for component-wise evaluation to do the job.
Public Member Functions inherited from IG.Num.VectorFunctionBaseGeneral
VectorFunctionBaseGeneral ()
void SetNumParameters (int num)
Sets number of parameters of the current vector function to the specified value.
void SetNumValues (int num)
Sets number of values of the vector function to the specified value.
virtual double Value (IVector parameters, int which)
Calculates and returns the particular component of the vector function value.
virtual double Derivative (IVector parameters, int which, int component)
Calculates and returns the particular component of the vector function derivative.
virtual double SecondDerivative (IVector parameters, int which, int rowNum, int columnNum)
Calculates and returns the particular component of the vector function's second derivative (Hessian).
void Value (IVector parameters, ref List< double > values)
Returns the value of vector function at the specified parameter.
void Derivative (IVector parameters, ref List< IVector > gradients)
Returns the first derivative of this function at the specified parameter.
void SecondDerivative (IVector parameters, ref List< IMatrix > hessians)
Returns the second derivative (Hessian) of this function at the specified arameter.
double LinearCombinationValue (IVectorFunctionResults evaluationData, IVector coefficients)
Returns value of linear combination of functions contained in this vector function, with specified coefficients at specified parameters.
void LinearCombinationDerivative (IVectorFunctionResults evaluationData, IVector coefficients, ref IVector res)
Returns gradient of linear combination of functions contained in this vector function, with specified coefficients at specified parameters.
double LinearCombinationDerivative (IVectorFunctionResults evaluationData, IVector coefficients, int component)
Returns the specified component of gradient of combination of functions contained in this vector function, with specified coefficients at specified parameters.
void LinearCombinationSecondDerivative (IVectorFunctionResults evaluationData, IVector coefficients, ref IMatrix res)
double LinearCombinationSecondDerivative (IVectorFunctionResults evaluationData, IVector coefficients, int rowNum, int columnNum)
Returns the specified component of Hessian of combination of functions contained in this vector function, with specified coefficients at specified parameters.
double LinearCombinationValue (IVector parameters, IVector coefficients)
Returns value of linear combination of functions contained in this vector function, with specified coefficients at specified parameters.
void LinearCombinationDerivative (IVector parameters, IVector coefficients, ref IVector res)
Returns gradient of linear combination of functions contained in this vector function, with specified coefficients at specified parameters.
double LinearCombinationDerivative (IVector parameters, IVector coefficients, int component)
Returns the specified component of gradient of combination of functions contained in this vector function, with specified coefficients at specified parameters.
void LinearCombinationSecondDerivative (IVector parameters, IVector coefficients, ref IMatrix res)
Calculates second derivatives of the linear combination of components of vector functions and stores them to the specified matrix.
double LinearCombinationSecondDerivative (IVector parameters, IVector coefficients, int rowNum, int columnNum)
Returns the specified component of Hessian of combination of functions contained in this vector function, with specified coefficients at specified parameters.
virtual void NumericalDerivative (IVector x, IVector stepSize, ref List< IVector > derivative)
Calculates numerical derivative of this function. Central difference formula is used.
virtual void NumericalSecondDerivative (IVector x, IVector stepsizes, ref List< IVector > secondDerivatives)
Calculates numerical second order derivative of this function. Central difference formula is used.
Properties
override bool ComponentWiseEvaluation [get, protected set]
Returns true, indicating that individual components of functions and eventually their deirvatives is performed directly.
Properties inherited from IG.Num.VectorFunctionBaseGeneral
object Lock [get]
virtual string Name [get, set]
Returns a short name of the function.
virtual string Description [get, set]
Returns a short description of the function.
virtual int NumParameters [get, protected set]
Gets number of parameters of the current vector function (-1 for not defined, in case that function works with different numbers of parameters).
virtual int NumValues [get, protected set]
Gets number of values of the current vector function (-1 for not defined, e.g. in case that function works with different numbers of parameters and number of functions depends on number of parameters).
virtual bool ComponentWiseEvaluation [get, protected set]
Tells whether the function supports evaluation of individual components. If not then evaluation is performed through the Evaluate function.
virtual bool ValueDefined [get, protected set]
Tells whether value of the function is defined by implementation.
virtual bool DerivativeDefined [get, protected set]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
virtual bool SecondDerivativeDefined [get, protected set]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
IVectorFunctionResults AuxResults [get]
VectorFunctionBase.ObjectStoreResults ResultsStore [get]
Store of result objects for reuse.
Properties inherited from IG.Num.IVectorFunction
string Name [get]
Returns a short name of the function.
string Description [get]
Returns a short description of the function.
int NumParameters [get]
Gets number of parameters of the current vector function (-1 for not defined, in case that function works with different numbers of parameters).
int NumValues [get]
Gets number of values of the current vector function (-1 for not defined, e.g. in case that function works with different numbers of parameters and number of functions depends on number of parameters).
bool ValueDefined [get]
Tells whether value of the function is defined by implementation.
bool DerivativeDefined [get]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
bool SecondDerivativeDefined [get]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
bool ComponentWiseEvaluation [get]
Tells whether the function supports evaluation of individual components. If not then evaluation is performed through the Evaluate function.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Additional Inherited Members
Protected Attributes inherited from IG.Num.VectorFunctionBaseGeneral
object _lock = new object()
string _name
string _description
int _numParameters = -1
int _numValues = -1
bool _valuesDefined = true
bool _derivativeDefined = false
bool _secondDerivativeDefined = false
bool _componentEvaluation = false
Detailed Description
Base class for defining Vector functions whose component-wise evaluation is defined directly.
$A Igor xx May09 Dec10; TODO: implement ICloneable
Member Function Documentation
override void IG.Num.VectorFunctionBaseComponentWise.Evaluate (IVectorFunctionResults evaluationData) inline virtual
Performs evaluation of requwester function results and writes them to the provided data structure. Uses Evaluate(IVector, ref bool, ref List{double}, ref bool, ref List{IVector}, ref bool, ref List{IMatrix}) to do the job.
Parameters
evaluationData Data structure where request parameters are obtained and where results are written.
Implements IG.Num.VectorFunctionBaseGeneral.
References IG.Num.IVectorFunctionResults.CalculatedGradients, IG.Num.IVectorFunctionResults.CalculatedHessians, IG.Num.IVectorFunctionResults.CalculatedValues, IG.Num.IVectorFunctionResults.Gradients, IG.Num.IVectorFunctionResults.Hessians, IG.Num.IVectorFunctionResults.NumFunctions, IG.Num.IVectorFunctionResults.NumParameters, IG.Num.IVectorFunctionResults.Parameters, IG.Num.IVectorFunctionResults.ReqGradients, IG.Num.IVectorFunctionResults.ReqHessians, IG.Num.IVectorFunctionResults.ReqValues, IG.Num.IVectorFunctionResults.SetGradientsReference(), IG.Num.IVectorFunctionResults.SetHessiansReference(), IG.Num.IVectorFunctionResults.SetValuesReference(), and IG.Num.IVectorFunctionResults.Values.
abstract override double IG.Num.VectorFunctionBaseComponentWise.Value (IVectorFunctionResults evaluationData, int which) pure virtual
Calculates and returns the particular component of the vector function value.
Parameters
evaluationData Evaluation data that contains function parameters and can store function resuts. If the function does not support component-wise evaluation then results will be stored to this structure and returned from it. This makes reuse possible - when different components are evaluated subsequently with the same parameters, results are calculated only for the first time.
which Specifies which function to evaluate.
Implements IG.Num.VectorFunctionBaseGeneral.
Implemented in IG.Num.QuadraticBasisSafer, IG.Num.QuadraticBasis, IG.Num.LinearBasisSafer, IG.Num.VectorFunctionFromScalar, and IG.Num.LinearBasis.
abstract override double IG.Num.VectorFunctionBaseComponentWise.Derivative (IVectorFunctionResults evaluationData, int which, int component) pure virtual
Calculates and returns the particular component of the vector function derivative.
Parameters
evaluationData Evaluation data that contains function parameters and can store function resuts. If the function does not support component-wise evaluation then results will be stored to this structure and returned from it. This makes reuse possible - when different components are evaluated subsequently with the same parameters, results are calculated only for the first time.
which Specifies which function to take.
component Specifies which compoonent of the gradient should be returned.
Implements IG.Num.VectorFunctionBaseGeneral.
Implemented in IG.Num.QuadraticBasisSafer, IG.Num.QuadraticBasis, IG.Num.LinearBasisSafer, IG.Num.VectorFunctionFromScalar, and IG.Num.LinearBasis.
abstract override double IG.Num.VectorFunctionBaseComponentWise.SecondDerivative (IVectorFunctionResults evaluationData, int which, int rowNum, int columnNum) pure virtual
Calculates and returns the particular component of the vector function's second derivative (Hessian).
Parameters
evaluationData Evaluation data that contains function parameters and can store function resuts. If the function does not support component-wise evaluation then results will be stored to this structure and returned from it. This makes reuse possible - when different components are evaluated subsequently with the same parameters, results are calculated only for the first time.
which Specifies which function to take.
rowNum Specifies which row of the Hessian (matrix of second derivatives) should be returned.
columnNum Specifies which column of the Hessian (matrix of second derivatives) should be returned.
Implements IG.Num.VectorFunctionBaseGeneral.
Implemented in IG.Num.QuadraticBasisSafer, IG.Num.QuadraticBasis, IG.Num.LinearBasisSafer, IG.Num.VectorFunctionFromScalar, and IG.Num.LinearBasis.
override void IG.Num.VectorFunctionBaseComponentWise.Evaluate (IVector parameters, ref bool calculateValues, ref List< double > values, ref bool calculateGradients, ref List< IVector > gradients, ref bool calculateHessians, ref List< IMatrix > hessians) inline virtual
Calculation of values, gradients, and hessians of the vector function according to request flags. Uses functions for component-wise evaluation to do the job.
Parameters
parameters Parameters at which evaluation takes place.
calculateValues Flag for calculation of function values, input/output.
values Function values, output.
calculateGradients Flag for calculation of functions gradients, input/output.
gradients Gradients, output.
calculateHessians Flag for calculation of Hessians, input/output.
hessians Functions' hessians, output.
Returns
Implements IG.Num.VectorFunctionBaseGeneral.
References IG.Num.IVectorFunctionResults.NumFunctions, and IG.Num.IVectorFunctionResults.SetParametersReference().
Property Documentation
override bool IG.Num.VectorFunctionBaseComponentWise.ComponentWiseEvaluation get protected set
Returns true, indicating that individual components of functions and eventually their deirvatives is performed directly.
The documentation for this class was generated from the following file:
iglib/igbase/numeric/FunctionVectorBase.cs