IGLib: Test.PermutationTest Class Reference
Test.PermutationTest Class Reference
Public Member Functions
void PermutationCount ()
void PermutationEquality ()
void PermutationProduct ()
void PermutationInverse ()
void PermutationOrder ()
void PermutationDistribution ()
void PermutationFormat ()
void GenerateGroups ()
Private Member Functions
HashSet< Permutation > GenerateGroup (IList< Permutation > generators)
Member Function Documentation
void Test.PermutationTest.PermutationCount () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.Functions.Permutation.IsDerangement, Meta.Numerics.Functions.Permutation.IsEven, and Meta.Numerics.Functions.Permutation.Permutations().
void Test.PermutationTest.PermutationEquality () inline
References Meta.Numerics.Functions.Permutation.Equals(), Meta.Numerics.Functions.Permutation.GetHashCode(), and Meta.Numerics.Functions.Permutation.Parse().
void Test.PermutationTest.PermutationProduct () inline
References Meta.Numerics.Functions.Permutation.GetRandomPermutation().
void Test.PermutationTest.PermutationInverse () inline
References Meta.Numerics.Functions.Permutation.GetRandomPermutation(), and Meta.Numerics.Functions.Permutation.Inverse().
void Test.PermutationTest.PermutationOrder () inline
References Meta.Numerics.Functions.Permutation.GetRandomPermutation(), Meta.Numerics.Functions.Permutation.IsIdentity, Meta.Numerics.Functions.Permutation.Order, and Meta.Numerics.Functions.Permutation.ToString().
void Test.PermutationTest.PermutationDistribution () inline
References Meta.Numerics.Statistics.Histogram.ChiSquaredTest(), Meta.Numerics.Functions.Permutation.GetRandomPermutation(), Meta.Numerics.Functions.Permutation.Permutations(), and Meta.Numerics.Statistics.TestResult.RightProbability.
void Test.PermutationTest.PermutationFormat () inline
References Meta.Numerics.Functions.Permutation.GetRandomPermutation(), Meta.Numerics.Functions.Permutation.Parse(), and Meta.Numerics.Functions.Permutation.ToString().
void Test.PermutationTest.GenerateGroups () inline
References Test.PermutationTest.GenerateGroup(), and Meta.Numerics.Functions.Permutation.Parse().
HashSet<Permutation> Test.PermutationTest.GenerateGroup (IList< Permutation > generators) inline private
References Meta.Numerics.Functions.Permutation.Identity().
Referenced by Test.PermutationTest.GenerateGroups().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/PermutationTest.cs