IGLib: Test.MultiIntegrateTest Class Reference
Test.MultiIntegrateTest Class Reference
Public Member Functions
Interval[] UnitCube (int d)
Interval[] SymmetricUnitCube (int d)
void SeperableIntegrals ()
void BallVolumeIntegrals ()
void ZetaIntegrals ()
void DoubleIntegrals ()
void WatsonIntegrals ()
void SteinmetzVolume ()
void RambleIntegrals ()
void BoxIntegrals ()
void MoreBox ()
void IsingIntegrals ()
double BoxIntegralB (int d, int r, EvaluationSettings settings)
double BoxIntegralD (int d, int r, EvaluationSettings settings)
void GaussianIntegrals ()
Private Member Functions
double RambleIntegral (int d, int s, EvaluationSettings settings)
Member Function Documentation
Interval [] Test.MultiIntegrateTest.UnitCube (int d) inline
References Meta.Numerics.Interval.FromEndpoints().
Referenced by Test.MultiIntegrateTest.BallVolumeIntegrals(), Test.MultiIntegrateTest.DoubleIntegrals(), Test.MultiIntegrateTest.SeperableIntegrals(), and Test.MultiIntegrateTest.ZetaIntegrals().
Interval [] Test.MultiIntegrateTest.SymmetricUnitCube (int d) inline
References Meta.Numerics.Interval.FromEndpoints().
Referenced by Test.MultiIntegrateTest.SteinmetzVolume().
void Test.MultiIntegrateTest.SeperableIntegrals () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Analysis.IntegrationResult.Estimate, Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), Meta.Numerics.MoreMath.Pow(), and Test.MultiIntegrateTest.UnitCube().
void Test.MultiIntegrateTest.BallVolumeIntegrals () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Analysis.IntegrationResult.Estimate, Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Functions.AdvancedMath.Gamma(), Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), Meta.Numerics.MoreMath.Pow(), Test.MultiIntegrateTest.UnitCube(), and Meta.Numerics.UncertainValue.Value.
void Test.MultiIntegrateTest.ZetaIntegrals () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Analysis.IntegrationResult.Estimate, Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), Meta.Numerics.Functions.AdvancedMath.RiemannZeta(), Test.MultiIntegrateTest.UnitCube(), and Meta.Numerics.UncertainValue.Value.
void Test.MultiIntegrateTest.DoubleIntegrals () inline
References Meta.Numerics.Functions.AdvancedMath.Catalan, Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Analysis.IntegrationResult.Estimate, Meta.Numerics.Functions.AdvancedMath.EulerGamma, Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), and Test.MultiIntegrateTest.UnitCube().
void Test.MultiIntegrateTest.WatsonIntegrals () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Analysis.IntegrationResult.Estimate, Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Functions.AdvancedMath.Gamma(), Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), and Meta.Numerics.MoreMath.Pow().
void Test.MultiIntegrateTest.SteinmetzVolume () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), and Test.MultiIntegrateTest.SymmetricUnitCube().
void Test.MultiIntegrateTest.RambleIntegrals () inline
References Meta.Numerics.Functions.AdvancedMath.Gamma(), Meta.Numerics.MoreMath.Pow(), Test.MultiIntegrateTest.RambleIntegral(), and Meta.Numerics.Analysis.EvaluationSettings.RelativePrecision.
double Test.MultiIntegrateTest.RambleIntegral (int d, int s, EvaluationSettings settings) inline private
References Meta.Numerics.ComplexMath.Abs(), Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), and Meta.Numerics.MoreMath.Pow().
Referenced by Test.MultiIntegrateTest.RambleIntegrals().
void Test.MultiIntegrateTest.BoxIntegrals () inline
References Meta.Numerics.Analysis.EvaluationSettings.RelativePrecision.
void Test.MultiIntegrateTest.MoreBox () inline
void Test.MultiIntegrateTest.IsingIntegrals () inline
References Meta.Numerics.Analysis.IntegrationResult.Estimate, Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), Meta.Numerics.Functions.AdvancedMath.RiemannZeta(), and Meta.Numerics.MoreMath.Sqr().
double Test.MultiIntegrateTest.BoxIntegralB (int d, int r, EvaluationSettings settings) inline
References Meta.Numerics.Analysis.MultiFunctionMath.Integrate().
double Test.MultiIntegrateTest.BoxIntegralD (int d, int r, EvaluationSettings settings) inline
References Meta.Numerics.Analysis.MultiFunctionMath.Integrate().
void Test.MultiIntegrateTest.GaussianIntegrals () inline
References Meta.Numerics.Matrices.SymmetricMatrix.CholeskyDecomposition(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Matrices.CholeskyDecomposition.Determinant(), Meta.Numerics.Analysis.IntegrationResult.Estimate, Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Matrices.ColumnVector.Transpose().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/MultiIntegrateTest.cs