IGLib: IG.Lib.MsgFinancialTransaction Class Reference
IG.Lib.MsgFinancialTransaction Class Reference
Class for holding and manipulating the data about financial transaction. Includes parsing an XML file, storing data internally, and transcription of read data to a PADO object that enables saving data to a database.
Public Member Functions
MsgFinancialTransaction ()
Default constructor, sets the type information.
override void Read ()
Reads msg data from the internal XML document containing the msg.
override void Read (XmlParser data)
Read msg data from an XML document containing the msg.
override void CheckConsistency (AccummulatedReport rep)
Check correctness and consistency of data and creates a report on this.
override string ToString ()
override XmlDocument ToXml ()
Converts a msg to Xml and returns it.
Public Member Functions inherited from IG.Lib.MsgBaseWithModel
void SetModelFile (string FilePath)
Sets the model document for creation of the msg to the contents of the specified file.
void SetModelString (string XmlString)
Sets the model document for creation of the msg to the contents of the specified string.
void SetModelDocument (XmlDocument doc)
Sets the model document for creation of the msg to the contents of the specified string.
Public Member Functions inherited from IG.Lib.MsgBase
void SetSenderLabex ()
Sets msg data such that sender is Labex and receiver is Bis.
void SetSenderBis ()
Sets msg data such that sender is Bis and receiver is Labex.
Public Member Functions inherited from IG.Lib.ParsableXmlObject
virtual void Save (string filename)
Saves contents of the msg to an xml file.
virtual void CreateXml ()
Creates msg Xml from the current msg data and stores it in this object.
virtual void Load (string filename)
Loads msg data from a file containing the XML msg.
virtual void LoadXml (string doc)
Loads msg data from a string containing the XML msg.
virtual void LoadXml (XmlDocument doc)
Loads msg data from an XmlDocument containing XML msg.
virtual void WriteToConsole ()
Writes cntents of the msg in a human readable form to the system console.
virtual void Write (string filename, bool append)
Writes cntents of the msg in a human readable form to a file.
Protected Attributes
string _modelFile = "ModelFileFinancialTransaction"
Protected Attributes inherited from IG.Lib.ParsableXmlObject
XmlBuilder Data = new XmlBuilder()
Properties
override XmlDocument ModelDocument [get, set]
Gets or sets the XML document that is used as model for creation of XML. Warning: Each call to execution of get() makes a clone of an XmlDocument.
Properties inherited from IG.Lib.MsgBaseWithModel
virtual XmlDocument ModelDocument [get, set]
Gets or seta the XML document that is used as model for creation of XML. Warning: Each call to execution of get() makes a clone of an XmlDocument.
Properties inherited from IG.Lib.MsgBase
static MsgConst Const [get]
Gets objects that contains all constants related to communication messages.
string MessageXml [get, set]
Complete msg as obtained from the web service.
Properties inherited from IG.Lib.ParsableXmlObject
virtual IReporter R [get]
Reporter for this class.
XmlDocument Doc [get]
Returns the XML document representing the msg.
Private Member Functions
string GenerateMessageId ()
Returns a generated msg Id.
Private Attributes
string ActionRoot = null
string ActionCode = Const.FtAction
string MessageCode = null
string MessageCodeSystem = null
string BisOrderId = null
string BisOrderIdOid = null
string AuthorId = null
string AuthorIdOid = null
OoStatus OrderStatus = OoStatus.Unknown
DateTime CreationTime = DateTime.Now
DateTime EffectiveTime = DateTime.Now
DateTime ActivityTime = DateTime.Now
List< ServiceDetail > Services = new List<ServiceDetail>()
int Id = null
Static Private Attributes
static int IdWithinSession = 0
Additional Inherited Members
Static Public Member Functions inherited from IG.Lib.MsgBase
static void SetMessageReceiverOld (ref XmlDocument msg, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false. WARNING: searching for receiver element is done through an XPath expression, which may fail due to default namespaces that were not detected.
static void SetMessageReceiver (ref string message, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageReceiver (ref XmlDocument msg, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageReceiver (ref XmlBuilder data, string receiver, out bool changed)
Sets the receiver of the communication msg stored in an Xml builder to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageSender (ref XmlBuilder data, string sender, out bool changed)
Sets the sender of the communication msg stored in an Xml builder to the specified sender, and indicates through an output argument whether the sender has been changed in msg. If the Sender stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageResponder (ref XmlBuilder data, string responder, out bool changed)
Sets the responder of the communication msg stored in an Xml builder to the specified responder, and indicates through an output argument whether the responder has been changed in msg. If the responder stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static MessageType GetMessageType (string msgstring)
Infers the msg type from the XML string containing the msg, and returns it.
static MessageType GetMessageType (XmlDocument msg)
Infers the msg type from the XML document containing the msg, and returns it.
static MessageType GetMessageType (XmlParser data)
Infers the msg type from the XML parser containing the msg, and returns it.
Public Attributes inherited from IG.Lib.MsgBase
MessageType Type = MessageType.Unknown
Message type. Helps with general methods that operate on any datatype of msg.
string MessageId = null
Message ID, obtained form the web service.
string MessageFile = null
Specifies the file where message has been backed up. Warning: this file may be deleted at any time!
string MessageNumber = null
Public Attributes inherited from IG.Lib.ParsableXmlObject
string XmlString = null
Static Protected Attributes inherited from IG.Lib.MsgBase
static string LabexIdLowercase = null
Detailed Description
Class for holding and manipulating the data about financial transaction. Includes parsing an XML file, storing data internally, and transcription of read data to a PADO object that enables saving data to a database.
Constructor & Destructor Documentation
IG.Lib.MsgFinancialTransaction.MsgFinancialTransaction () inline
Default constructor, sets the type information.
Member Function Documentation
override void IG.Lib.MsgFinancialTransaction.Read () inline virtual
Reads msg data from the internal XML document containing the msg.
Implements IG.Lib.ParsableXmlObject.
Referenced by IGTest.ProgramIGTest.TestMsgFinancialTransaction().
override void IG.Lib.MsgFinancialTransaction.Read (XmlParser data) inline virtual
Read msg data from an XML document containing the msg.
Parameters
doc Document containing the msg.
Implements IG.Lib.ParsableXmlObject.
References IG.Lib.ServiceDetail.ActivityTime, IG.Lib.XmlParser.Attribute(), IG.Lib.XmlParser.Back(), IG.Lib.XmlParser.BackToMark(), IG.Lib.ServiceDetail.Code, IG.Lib.ServiceDetail.CodeDescription, IG.Lib.ServiceDetail.CompletionTime, IG.Lib.XmlParser.Current, IG.Lib.XmlParser.CurrentElement, IG.Lib.XmlParser.Doc, IG.Lib.XmlParser.GoToRoot(), IG.Lib.ServiceDetail.Id, IG.Lib.ServiceDetail.IdOid, IG.Lib.XmlParser.Name, IG.Lib.XmlParser.NextElement(), IG.Lib.XmlParser.NextOrCurrentElement(), IG.Lib.ServiceDetail.Quantity, IG.Lib.ParsableXmlObject.AccummulatedReport.Report(), IG.Lib.ReporterBase.ReviseException(), IG.Lib.XmlParser.SetMark(), IG.Lib.ServiceDetail.StartTime, IG.Lib.ServiceDetail.StatusCode, IG.Lib.XmlParser.StepIn(), and IG.Lib.XmlParser.Value.
override void IG.Lib.MsgFinancialTransaction.CheckConsistency (AccummulatedReport rep) inline virtual
Check correctness and consistency of data and creates a report on this.
Parameters
rep Object where error, warning and info reports are accumulated.
Reimplemented from IG.Lib.ParsableXmlObject.
References IG.Lib.ParsableXmlObject.AccummulatedReport.AddError(), and IG.Lib.ParsableXmlObject.AccummulatedReport.AddInfo().
override string IG.Lib.MsgFinancialTransaction.ToString () inline
string IG.Lib.MsgFinancialTransaction.GenerateMessageId () inline private
Returns a generated msg Id.
Message numbers should later be generated in a different way, probably by the database.
override XmlDocument IG.Lib.MsgFinancialTransaction.ToXml () inline virtual
Converts a msg to Xml and returns it.
Implements IG.Lib.ParsableXmlObject.
References IG.Lib.ServiceDetail.ActivityTime, IG.Lib.ServiceDetail.Code, IG.Lib.ServiceDetail.CodeDescription, IG.Lib.ServiceDetail.CompletionTime, IG.Lib.ServiceDetail.Id, IG.Lib.ServiceDetail.IdOid, IG.Lib.ServiceDetail.Quantity, IG.Lib.ReporterBase.ReviseException(), IG.Lib.ServiceDetail.StartTime, and IG.Lib.ServiceDetail.StatusCode.
Referenced by IGTest.ProgramIGTest.TestMsgFinancialTransaction().
Member Data Documentation
string IG.Lib.MsgFinancialTransaction.ActionRoot = null private
string IG.Lib.MsgFinancialTransaction.ActionCode = Const.FtAction private
string IG.Lib.MsgFinancialTransaction.MessageCode = null private
string IG.Lib.MsgFinancialTransaction.MessageCodeSystem = null private
string IG.Lib.MsgFinancialTransaction.BisOrderId = null private
string IG.Lib.MsgFinancialTransaction.BisOrderIdOid = null private
string IG.Lib.MsgFinancialTransaction.AuthorId = null private
string IG.Lib.MsgFinancialTransaction.AuthorIdOid = null private
OoStatus IG.Lib.MsgFinancialTransaction.OrderStatus = OoStatus.Unknown private
DateTime IG.Lib.MsgFinancialTransaction.CreationTime = DateTime.Now private
DateTime IG.Lib.MsgFinancialTransaction.EffectiveTime = DateTime.Now private
DateTime IG.Lib.MsgFinancialTransaction.ActivityTime = DateTime.Now private
List<ServiceDetail> IG.Lib.MsgFinancialTransaction.Services = new List<ServiceDetail>() private
int IG.Lib.MsgFinancialTransaction.Id = null private
int IG.Lib.MsgFinancialTransaction.IdWithinSession = 0 static private
string IG.Lib.MsgFinancialTransaction._modelFile = "ModelFileFinancialTransaction" protected
Property Documentation
override XmlDocument IG.Lib.MsgFinancialTransaction.ModelDocument get set
Gets or sets the XML document that is used as model for creation of XML. Warning: Each call to execution of get() makes a clone of an XmlDocument.
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/LabexBis/MsgFinancialTransaction.cs