IGLib: Itaia.ZedGraphWindow Class Reference
Itaia.ZedGraphWindow Class Reference
Public Member Functions
ZedGraphWindow ()
Public Attributes
ZedGraphPlotDlg PlotDelegate = null
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
ZedGraph.ZedGraphControl GraphControl
Zedgraph control that is used for plotting.
Private Member Functions
void Form1_Load (object sender, EventArgs e)
void Form1_Resize (object sender, EventArgs e)
On resize action, resize the ZedGraphControl to fill most of the Form, with a small margin around the outside
void SetSize ()
string MyPointValueHandler (ZedGraphControl control, GraphPane pane, CurveItem curve, int iPt)
Display customized tooltips when the mouse hovers over a point
void MyContextMenuBuilder (ZedGraphControl control, ContextMenuStrip menuStrip, Point mousePt, ZedGraphControl.ContextMenuObjectState objState)
Customize the context menu by adding a new item to the end of the menu
void AddBetaPoint (object sender, EventArgs args)
Handle the "Add New Beta Point" context menu item. This finds the curve with the CurveItem.Label = "Beta", and adds a new point to it.
void MyZoomEvent (ZedGraphControl control, ZoomState oldState, ZoomState newState)
void btnCancel_Click (object sender, EventArgs e)
void chkBlackBg_CheckedChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox grbox1
System.Windows.Forms.Panel panel1
System.Windows.Forms.Button btnClose
System.Windows.Forms.CheckBox chkBlackBg
Constructor & Destructor Documentation
Itaia.ZedGraphWindow.ZedGraphWindow () inline
References Itaia.ZedGraphWindow.InitializeComponent().
Member Function Documentation
void Itaia.ZedGraphWindow.Form1_Load (object sender, EventArgs e) inline private
References Itaia.ZedGraphWindow.GraphControl, Itaia.ZedGraphWindow.MyContextMenuBuilder(), Itaia.ZedGraphWindow.MyPointValueHandler(), Itaia.ZedGraphWindow.MyZoomEvent(), Itaia.ZedGraphWindow.PlotDelegate, and Itaia.ZedGraphWindow.SetSize().
Referenced by Itaia.ZedGraphWindow.InitializeComponent().
void Itaia.ZedGraphWindow.Form1_Resize (object sender, EventArgs e) inline private
On resize action, resize the ZedGraphControl to fill most of the Form, with a small margin around the outside
References Itaia.ZedGraphWindow.SetSize().
Referenced by Itaia.ZedGraphWindow.InitializeComponent().
void Itaia.ZedGraphWindow.SetSize () inline private
References Itaia.ZedGraphWindow.GraphControl.
Referenced by Itaia.ZedGraphWindow.Form1_Load(), and Itaia.ZedGraphWindow.Form1_Resize().
string Itaia.ZedGraphWindow.MyPointValueHandler (ZedGraphControl control, GraphPane pane, CurveItem curve, int iPt) inline private
Display customized tooltips when the mouse hovers over a point
Referenced by Itaia.ZedGraphWindow.Form1_Load().
void Itaia.ZedGraphWindow.MyContextMenuBuilder (ZedGraphControl control, ContextMenuStrip menuStrip, Point mousePt, ZedGraphControl.ContextMenuObjectState objState) inline private
Customize the context menu by adding a new item to the end of the menu
References Itaia.ZedGraphWindow.AddBetaPoint().
Referenced by Itaia.ZedGraphWindow.Form1_Load().
void Itaia.ZedGraphWindow.AddBetaPoint (object sender, EventArgs args) inline private
Handle the "Add New Beta Point" context menu item. This finds the curve with the CurveItem.Label = "Beta", and adds a new point to it.
References Itaia.ZedGraphWindow.GraphControl.
Referenced by Itaia.ZedGraphWindow.MyContextMenuBuilder().
void Itaia.ZedGraphWindow.MyZoomEvent (ZedGraphControl control, ZoomState oldState, ZoomState newState) inline private
Referenced by Itaia.ZedGraphWindow.Form1_Load().
void Itaia.ZedGraphWindow.btnCancel_Click (object sender, EventArgs e) inline private
References Itaia.ZedGraphWindow.Dispose().
Referenced by Itaia.ZedGraphWindow.InitializeComponent().
void Itaia.ZedGraphWindow.chkBlackBg_CheckedChanged (object sender, EventArgs e) inline private
References Itaia.ZedGraphWindow.chkBlackBg, and Itaia.ZedGraphWindow.GraphControl.
Referenced by Itaia.ZedGraphWindow.InitializeComponent().
override void Itaia.ZedGraphWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References Itaia.ZedGraphWindow.components.
Referenced by Itaia.ZedGraphWindow.btnCancel_Click().
void Itaia.ZedGraphWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References Itaia.ZedGraphWindow.btnCancel_Click(), Itaia.ZedGraphWindow.btnClose, Itaia.ZedGraphWindow.chkBlackBg, Itaia.ZedGraphWindow.chkBlackBg_CheckedChanged(), Itaia.ZedGraphWindow.components, Itaia.ZedGraphWindow.Form1_Load(), Itaia.ZedGraphWindow.Form1_Resize(), Itaia.ZedGraphWindow.GraphControl, Itaia.ZedGraphWindow.grbox1, and Itaia.ZedGraphWindow.panel1.
Referenced by Itaia.ZedGraphWindow.ZedGraphWindow().
Member Data Documentation
ZedGraphPlotDlg Itaia.ZedGraphWindow.PlotDelegate = null
Referenced by Itaia.GraphTest.Example(), and Itaia.ZedGraphWindow.Form1_Load().
System.ComponentModel.IContainer Itaia.ZedGraphWindow.components = null private
Required designer variable.
Referenced by Itaia.ZedGraphWindow.Dispose(), and Itaia.ZedGraphWindow.InitializeComponent().
ZedGraph.ZedGraphControl Itaia.ZedGraphWindow.GraphControl protected
Zedgraph control that is used for plotting.
Referenced by Itaia.ZedGraphWindow.AddBetaPoint(), Itaia.ZedGraphWindow.chkBlackBg_CheckedChanged(), Itaia.ZedGraphWindow.Form1_Load(), Itaia.ZedGraphWindow.InitializeComponent(), and Itaia.ZedGraphWindow.SetSize().
System.Windows.Forms.GroupBox Itaia.ZedGraphWindow.grbox1 private
Referenced by Itaia.ZedGraphWindow.InitializeComponent().
System.Windows.Forms.Panel Itaia.ZedGraphWindow.panel1 private
Referenced by Itaia.ZedGraphWindow.InitializeComponent().
System.Windows.Forms.Button Itaia.ZedGraphWindow.btnClose private
Referenced by Itaia.ZedGraphWindow.InitializeComponent().
System.Windows.Forms.CheckBox Itaia.ZedGraphWindow.chkBlackBg private
Referenced by Itaia.ZedGraphWindow.chkBlackBg_CheckedChanged(), and Itaia.ZedGraphWindow.InitializeComponent().
The documentation for this class was generated from the following files:
igapp/itaia/appitaia/copy/ZedGraphWindow1.cs
igapp/itaia/appitaia/copy/ZedGraphWindow1.designer.cs