IGLib: IG.Crypto.UtilCrypto Class Reference
IG.Crypto.UtilCrypto Class Reference
Basic Cryptographic utilities.
Static Public Member Functions
static PasswordAlgorithmType[] GetPasswordAlgorithmTypes ()
Returns all password algorithm types contained in the enumeration PasswordAlgorithmType
static PasswordAlgorithmType GetPasswordAlgorithmType (string typeString)
Returns a PasswordAlgorithmType value corresponding to the specified string representation.
static PasswordAlgorithmType GetPasswordAlgorithmType (PasswordAlgorithmBase algorithmObject)
Returns the password generation algorithm type, i.e. an enumeration of type PasswordAlgorithmType, for the specified password generation algorithm object.
static string PasswordAlgorithmTypeToString (PasswordAlgorithmType passwordAlgorithmType)
Returns standard string representation of the specified password generation algoithm.
static
IG.Crypto.PasswordAlgorithmBase GetPasswordAlgorithm (PasswordAlgorithmType algorithmType)
Returns the appropriate password generation algorithm according to the specified algorithm type, or null if the type is not recognized or the method is not implemented for that type.
static bool IsCorrectPasswordAlgorithm (DeriveBytes algorithm, PasswordAlgorithmType algorithmType)
Returns true if the specified password generation algorithm corresponds the type specification, false otherwise.
static string CreateRandomPassword (int PasswordLength, string allowedChars=null)
Creates and returns a random password consisting of only allowed characters from the specified string.
static void GetRandomBytes (byte[] byteArray)
Fills the specified byte array with a cryptographically strong sequence of random bytes.
static void GetRandomBytes (ref byte[] byteArray, int numBytes)
Fills the specified byte array with a specified number of cryptographically strong random bytes.
static byte[] GetRandomBytes (int numBytes)
Creates and returns an array of cryptographically strong random bytes of the specified size.
static int GetHashLengthBytes (HashType hashType)
Returns length of the hashRet value, in bytes, for the specified hashRet algorithm.
static int GetHashLengthHex (HashType hashType)
Returns length of the HEXADECIMAL hashRet string for the specified hashRet algorithm.
static HashType[] GetHashTypes ()
Returns all hashing algorithm types contained in the enumeration HashType
static HashType GetHashType (string typeString)
Returns a HashType value corresponding to the specified string representation.
static HashType GetHashType (HashAlgorithm algorithmObject)
Returns the hashing algorithm type, i.e. an enumeration of type HashType, for the specified hashing algorithm object.
static string HashTypeToString (HashType hashType)
Returns standard string representation of the specified hashRet type.
static HashAlgorithm GetHashAlgorithm (HashType hashType)
Returns the appropriate hashRet algorithm according to the specified hashRet type, or null if the type is not recognized or the method is not implemented for that type.
static bool IsCorrectHashAlgorithm (HashAlgorithm algorithm, HashType algorithmType)
Returns true if the specified cryptographic hashRet algorithm corresponds the type specification, false otherwise.
static void ParseHashFile (string filePath, ref List< string[]> hashList)
Parses the file containing hashRet values of one or more files, and adds the parsed pairs {hashRet, inputFilePath} to the specified list.
static void ParseHashFileString (string str, ref List< string[]> hashList)
Parses the string containing hashRet values of one or more files, and adds the parsed pairs {hashRet, inputFilePath} to the specified list.
static byte[] GetHashBytes (byte[] bytesToHash, HashType hashType, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the hashRet (in form of byte array) of the specified kind of the specified byte array.
static string GetHashHex (byte[] bytesToHash, HashType hashType, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the hashRet string of the specified kind of the specified byte array.
static string GetHashMd5Hex (byte[] bytesToHash)
Computes and returns the MD5 hashRet string of the specified array of bytes.
static string GetHashSha1Hex (byte[] bytesToHash)
Computes and returns the SHA1 hashRet string of the specified array of bytes.
static string GetHashSha256Hex (byte[] bytesToHash)
Computes and returns the SHA256 hashRet string of the specified array of bytes.
static string GetHashSha512Hex (byte[] bytesToHash)
Computes and returns the SHA512 hashRet string of the specified array of bytes.
static bool CheckHashHex (byte[] bytesToCheck, string hashValue, HashType hashAlgorithmType)
Chechs the specified type of hashRet value of a byte array.
static HashType CheckHashSupportedTypesHex (byte[] bytesToCheck, string hashValue)
Chechs all supported types of hashRet value of a string.
static byte[] GetStringHashBytes (string stringToHash, HashType hashType=HashType.Default, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the hashRet string of the specified kind of the specified string.
static string GetStringHashHex (string stringToHash, HashType hashType=HashType.Default, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the hashRet string of the specified kind of the specified string.
static string GetStringHashMd5Hex (string stringToHash)
Computes and returns the MD5 hashRet string of the specified string.
static string GetStringHashSha1Hex (string stringToHash)
Computes and returns the SHA1 hashRet string of the specified string.
static string GetStringHashSha256Hex (string stringToHash)
Computes and returns the SHA256 hashRet string of the specified string.
static string GetStringHashSha512Hex (string stringToHash)
Computes and returns the SHA512 hashRet string of the specified string.
static byte[] GetStringSaltedHashBytes (string stringToHash, HashType hashType, string salt, int numIterations=0, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the salted hashRet (in form of byte array) of the specified kind of the specified string, with the specified number of repetitions of the salted hashing algoriithm.
static string GetStringSaltedHash (string stringToHash, HashType hashType, string salt, int numIterations=0, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the salted hashRet of the specified kind of the specified string, with the specified number of repetitions of the salted hashing algoriithm.
static string GetStringSaltedHashMd5Hex (string stringToHash, string salt, int numIterations=0)
Computes and returns the MD5 salted hashRet of the specified string, with the specified number of repetitions of the salted hashing algoriithm.
static string GetStringSaltedHashSha1Hex (string stringToHash, string salt, int numIterations=0)
Computes and returns the SHA1 salted hashRet of the specified string, with the specified number of repetitions of the salted hashing algoriithm.
static string GetStringSaltedHashSha256Hex (string stringToHash, string salt, int numIterations=0)
Computes and returns the SHA-256 salted hashRet of the specified string, with the specified number of repetitions of the salted hashing algoriithm.
static string GetStringSaltedHashSha512Hex (string stringToHash, string salt, int numIterations=0)
Computes and returns the SHA-512 salted hashRet of the specified string, with the specified number of repetitions of the salted hashing algoriithm.
static bool CheckStringHashHex (string stringToCheck, string hashValue, HashType hashAlgorithmType)
Chechs the specified type of hashRet value of a string.
static HashType CheckStringHashSupportedTypesHex (string stringToCheck, string hashValue)
Chechs all supported types of hashRet value of a string.
static bool CheckStringHashMd5Hex (string stringToCheck, string hashValue)
Checks whether the specified MD5 hashRet value matches the actual hashRet value of the specified string.
static bool CheckStringHashSha1Hex (string stringToCheck, string hashValue)
Checks whether the specified SHA-1 hashRet value matches the actual hashRet value of the specified string.
static bool CheckStringHashSha256Hex (string stringToCheck, string hashValue)
Checks whether the specified SHA-256 hashRet value matches the actual hashRet value of the specified string.
static bool CheckStringHashSha512Hex (string stringToCheck, string hashValue)
Checks whether the specified SHA-512 hashRet value matches the actual hashRet value of the specified string.
static byte[] GetFileHashBytes (string filePath, HashType hashType, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the hashRet (in form of byte array) of specified type of the specified stream.
static string GetFileHashHex (string filePath, HashType hashType, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the hashRet string of specified type of the specified stream.
static string GetFileHashMd5Hex (string filePath, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the MD5 hashRet string of the specified stream.
static string GetFileHashSha1Hex (string filePath, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the SHA1 hashRet string of the specified stream.
static string GetFileHashSha256Hex (string filePath, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the SHA256 hashRet string of the specified stream.
static string GetFileHashSha512Hex (string filePath, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the SHA512 hashRet string of the specified stream.
static byte[] GetHashBytes (Stream stream, HashType hashType, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the hashRet (in form of byte array) of specified type of the specified stream.
static string GetHashHex (Stream stream, HashType hashType, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the hexadecimal hashRet string of specified type of the specified stream.
static string GetHashMd5Hex (Stream stream, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the MD5 hashRet string of the specified stream.
static string GetHashSha1Hex (Stream stream, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the SHA1 hashRet string of the specified stream.
static string GetHashSha256Hex (Stream stream, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the SHA256 hashRet string of the specified stream.
static string GetHashSha512Hex (Stream stream, HashAlgorithm cryptoAlgorithm=null)
Computes and returns the SHA512 hashRet string of the specified stream.
static bool CheckFileHashHex (string filePath, string hashValue, HashType hashType, HashAlgorithm cryptoAlgorithm=null)
Chechs the specified type of hashRet value of a file.
static HashType CheckFileHashSupportedTypesHex (string filePath, string hashValue)
Chechs all supported types of hashRet value of a file.
static bool CheckFileHashMd5Hex (string filePath, string hashValue)
Checks whether the specified MD5 hashRet value matches the actual hashRet value of the specified file.
static bool CheckFileHashSha1Hex (string filePath, string hashValue)
Checks whether the specified SHA-1 hashRet value matches the actual hashRet value of the specified file.
static bool CheckFileHashSha256Hex (string filePath, string hashValue)
Checks whether the specified SHA-256 hashRet value matches the actual hashRet value of the specified file.
static bool CheckFileHashSha512Hex (string filePath, string hashValue)
Checks whether the specified SHA-512 hashRet value matches the actual hashRet value of the specified file.
static SymmetricAlgorithmType[] GetSymmetricAlgorithmTypes ()
Returns all symmetric encryption algorithm types contained in the enumeration SymmetricAlgorithmType
static SymmetricAlgorithmType GetSymmetricAlgorithmType (string typeString)
Returns the SymmetricAlgorithmType value corresponding to the specified string.
static SymmetricAlgorithmType GetSymmetricAlgorithmType (SymmetricAlgorithm algorithmObject)
Returns the symmetric encryption algorithm type, i.e. an enumeration of type SymmetricAlgorithmType, for the specified symmetric encryption algorithm object.
static string SymmetricAlgorithmTypeToString (SymmetricAlgorithmType algorithmType)
Returns standard string representation of the specified symmetric encryption algorithm type.
static SymmetricAlgorithm GetSymmetricEncryptionAlgorithm (SymmetricAlgorithmType algorithmType)
Returns the appropriate symmetric encryption algorithm according to the specified hashRet type, or null if the type is not recognized or the method is not implemented for that type.
static bool IsCorrectSymmetricEncryptionAlgorithm (SymmetricAlgorithm algorithm, SymmetricAlgorithmType algorithmType)
Returns true if the specified symmetric encryption algorithm corresponds the type specification, false otherwise.
static byte[] PadToAlgorithmBlocksizeCyclic (byte[] byteArray, int blockSize, bool truncateIfLarger=false)
For the specified symmetric encryption algorithm, this function takes the specified byte array and checks if the array is of valid size. If yes then the unmodified initialization array is returned, otherwise the modified array that fits the required block size is returned (i.e. has integer number of blocks).
static byte[] PadToAlgorithmBlocksizeZero (byte[] byteArray, int blockSize, bool truncateIfLarger=false)
For the specified symmetric encryption algorithm, this function takes the specified byte array and checks if the array is of valid size. If yes then the unmodified initialization array is returned, otherwise the modified array that fits the required block size is returned (i.e. has integer number of blocks).
static byte[] PadToSymmetricAlgorithmBlocksizeCyclic (byte[] byteArray, SymmetricAlgorithm algorithm, bool truncateIfLarger=false)
For the specified symmetric encryption algorithm, this function takes the specified byte array and checks if the array is of valid size. If yes then the unmodified array is returned, otherwise the modified array that fits the required block size is returned. The array size must be mltiple of the block size.
static byte[] PadToSymmetricAlgorithmBlocksizeZero (byte[] byteArray, SymmetricAlgorithm algorithm, bool truncateIfLarger=false)
For the specified symmetric encryption algorithm, this function takes the specified byte array and checks if the array is of valid size. If yes then the unmodified array is returned, otherwise the modified array that fits the required block size is returned. The array size must be mltiple of the block size.
static byte[] GetValidSymmetricAlgorithmKey (byte[] key, SymmetricAlgorithm algorithm)
For the specified symmetric encryption algorithm, this function takes the specified key and checks if the key is of valid size. If yes then the unmodified key is returned, otherwise the modified key that fits the required size is returned.
static byte[] GetValidSymmetricAlgorithmIV (byte[] IV, SymmetricAlgorithm algorithm)
For the specified symmetric encryption algorithm, this function takes the specified initialization vector and checks if the vector is of valid size. If yes then the unmodified IV is returned, otherwise the modified IV that fits the required size is returned.
static int GetLargestSymmetricAlgorithmKeySize (SymmetricAlgorithm algorithm)
Returns the largest possible key siye, in bits, for the spcified symmetric encryption algorithm.
static int GetLargestSymmetricAlgorithmBlockSize (SymmetricAlgorithm algorithm)
Returns the largest possible block siye, in bits, for the spcified symmetric encryption algorithm.
static void PrepareSymmetricAllgorithmBasic (byte[] passwordBytes, byte[] passwordSalt, ref byte[] key, ref byte[] IV, SymmetricAlgorithmType algorithmType, ref SymmetricAlgorithm algorithm, PasswordAlgorithmType pwdType=PasswordAlgorithmType.Default, int pwdNumIterations=1000, bool useLargestKey=false, bool useLargestBlock=false)
Prepares the symmetric algorithm, initialization vector, and key before encryption or decryption takes place.
static byte[] EncryptBasic (byte[] data, byte[] passwordBytes, byte[] passwordSalt, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm=null, byte[] saltBytes=null, PasswordAlgorithmType pwdType=PasswordAlgorithmType.Default, int pwdNumIterations=1000, bool useLargestKey=false, bool useLargestBlock=false)
Encrypts the specified byte array by a symmetric encryption algorithm and returns encrypted bytes.
static byte[] DecryptBasic (byte[] data, byte[] passwordBytes, byte[] passwordSalt, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm=null, int numSaltBytes=0, PasswordAlgorithmType pwdType=PasswordAlgorithmType.Default, int pwdNumIterations=1000, bool useLargestKey=false, bool useLargestBlock=false)
Decrypts the specified byte array by a symmetric algorithm and returns decrypted data.
static string EncryptStringBasic (string stringToEncrypt, byte[] passwordBytes, byte[] passwordSalt, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm=null, byte[] saltBytes=null, PasswordAlgorithmType pwdType=PasswordAlgorithmType.Default, int pwdNumIterations=1000, bool useLargestKey=false, bool useLargestBlock=false)
Encrypts the specified string, using the specified symmetric algorithm, key, and initialization vector, and returns the ToBase64 string representation of the encrypted bytes.
static string DecryptStringBasic (string cipherText, byte[] passwordBytes, byte[] passwordSalt, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm=null, int numSaltBytes=0, PasswordAlgorithmType pwdType=PasswordAlgorithmType.Default, int pwdNumIterations=1000, bool useLargestKey=false, bool useLargestBlock=false)
Derypts the specified string from encryted byte array, using the specified symmetric algorithm, key, and initialization vector.
static void EncryptFileBasic (string inputFilePath, string outputFilePath, byte[] passwordBytes, byte[] passwordSalt, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm=null, byte[] saltBytes=null, int bufferSize=ConstCrypto.FileBufferSize, PasswordAlgorithmType pwdType=PasswordAlgorithmType.Default, int pwdNumIterations=1000, bool useLargestKey=false, bool useLargestBlock=false)
Encrypts the data from the specified input file by a symmetric encryption algorithm and writes encrypted data to the specified output file.
static void DecryptFileBasic (string inputFilePath, string outputFilePath, byte[] passwordBytes, byte[] passwordSalt, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm=null, int numSaltBytes=0, int bufferSize=ConstCrypto.FileBufferSize, PasswordAlgorithmType pwdType=PasswordAlgorithmType.Default, int pwdNumIterations=1000, bool useLargestKey=false, bool useLargestBlock=false)
Decrypts the data from the specified input file by a symmetric encryption algorithm and writes decrypted data to the specified output file.
static void PrepareSymmetricAllgorithmPlain (ref byte[] key, ref byte[] IV, SymmetricAlgorithmType algorithmType, ref SymmetricAlgorithm algorithm, bool useLargestKey=false, bool useLargestBlock=false)
Prepares the symmetric algorithm, initialization vector, and key before encryption or decryption takes place.
static void EncryptPlain (byte[] data, Stream outputStream, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm=null, byte[] saltBytes=null, bool useLargestKey=false, bool useLargestBlock=false)
Encrypts the specified byte array by a symmetric encryption algorithm and writes encrypted data to the specified output stream that must be open for writing.
static void DecryptPlain (byte[] data, Stream outputStream, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm=null, int numSaltBytes=0, bool useLargestKey=false, bool useLargestBlock=false)
Decrypts the specified byte array by a symmetric algorithm and writes decrypted data to the specified output stream.
static byte[] EncryptPlain (byte[] data, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm=null, byte[] saltBytes=null, bool useLargestKey=false, bool useLargestBlock=false)
Encrypts the specified byte array by a symmetric encryption algorithm and returns encrypted bytes.
static byte[] DecryptPlain (byte[] data, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm=null, int numSaltBytes=0, bool useLargestKey=false, bool useLargestBlock=false)
Decrypts the specified byte array by a symmetric algorithm and returns decrypted data.
static string EncryptStringPlain (string stringToEncrypt, byte[] key, byte[] initializationVector, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm=null, byte[] saltBytes=null, bool useLargestKey=false, bool useLargestBlock=false)
Encrypts the specified string, using the specified symmetric algorithm, key, and initialization vector, and returns the Base64 string representation of the encrypted bytes.
static string DecryptStringPlain (string cipherText, byte[] key, byte[] initializationVector, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm=null, int numSaltBytes=0, bool useLargestKey=false, bool useLargestBlock=false)
Derypts the specified string from encryted byte array, using the specified symmetric algorithm, key, and initialization vector.
static byte[] EncryptStringToBytesPlain (string stringToEncrypt, byte[] key, byte[] initializationVector, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm=null, byte[] saltBytes=null, bool useLargestKey=false, bool useLargestBlock=false)
Encrypts the specified string to a byte array, using the specified symmetric algorithm, key, and initialization vector.
static string DecryptStringFromBytesPlain (byte[] cipherText, byte[] key, byte[] initializationVector, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm=null, int numSaltBytes=0, bool useLargestKey=false, bool useLargestBlock=false)
Derypts the specified string from encryted byte array, using the specified symmetric algorithm, key, and initialization vector.
static void EncryptPlain (Stream inputStream, Stream outputStream, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm=null, byte[] saltBytes=null, int bufferSize=ConstCrypto.FileBufferSize, bool useLargestKey=false, bool useLargestBlock=false)
Encrypts the data from the specified input stream by a symmetric encryption algorithm and writes encrypted data to the specified output stream.
static void DecryptPlain (Stream inputStream, Stream outputStream, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm=null, int numSaltBytes=0, int bufferSize=ConstCrypto.FileBufferSize, bool useLargestKey=false, bool useLargestBlock=false)
Decrypts the data from the specified input stream by a symmetric encryption algorithm and writes decrypted data to the specified output stream.
static void EncryptFilePlain (string inputFilePath, string outputFilePath, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm=null, byte[] saltBytes=null, int bufferSize=ConstCrypto.FileBufferSize, bool useLargestKey=false, bool useLargestBlock=false)
Encrypts the data from the specified input file by a symmetric encryption algorithm and writes encrypted data to the specified output file.
static void DecryptFilePlain (string inputFilePath, string outputFilePath, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType=SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm=null, int numSaltBytes=0, int bufferSize=ConstCrypto.FileBufferSize, bool useLargestKey=false, bool useLargestBlock=false)
Decrypts the data from the specified input file by a symmetric encryption algorithm and writes decrypted data to the specified output file.
static AsymmetricAlgorithmType[] GetAsymmetricAlgorithmTypes ()
Returns all asymmetric encryption algorithm types contained in the enumeration AsymmetricAlgorithmType
static AsymmetricAlgorithmType GetAsymmetricAlgorithmType (string typeString)
Returns the AsymmetricAlgorithmType value corresponding to the specified string.
static AsymmetricAlgorithmType GetAsymmetricAlgorithmType (AsymmetricAlgorithm algorithmObject)
Returns the asymmetric encryption algorithm type, i.e. an enumeration of type SymmetricAlgorithmType, for the specified asymmetric encryption algorithm object.
static string AsymmetricAlgorithmTypeToString (AsymmetricAlgorithmType algorithmType)
Returns standard string representation of the specified asymmetric encryption algorithm type.
static AsymmetricAlgorithm GetAsymmetricEncryptionAlgorithm (AsymmetricAlgorithmType algorithmType)
Returns the appropriate asymmetric algorithm according to the specified hashRet type, or null if the type is not recognized or the method is not implemented for that type.
static bool IsCorrectAsymmetricEncryptionAlgorithm (AsymmetricAlgorithm algorithm, AsymmetricAlgorithmType algorithmType)
Returns true if the specified asymmetric encryption algorithm corresponds the type specification, false otherwise.
static int GetLargestAsymmetricAlgorithmKeySize (AsymmetricAlgorithm algorithm)
Returns the largest possible key size, in bits, for the spcified symmetric encryption algorithm.
static byte[] GetValidAsymmetricAlgorithmKey (byte[] key, AsymmetricAlgorithm algorithm, bool useLargestKey=false)
For the specified asymmetric encryption algorithm, this function takes the specified key and checks if the key is of valid size. If yes then the unmodified key is returned, otherwise the modified key that fits the required size is returned.
static CspProviderFlags GetCspProviderFlags (string flagString)
Returns the value of the CspProviderFlags enum corresponding to the specified string.
static string CspProviderFlagsToString (CspProviderFlags flags)
Returns standard string representation of the CspProviderFlags enumeration.
static string ToString (CspKeyContainerInfo keyInfo, int numIndent=0)
Creates and returns a string that presents the key information contained in the argument keyInfo .
static string ToString (RSACryptoServiceProvider alg)
Creates and returns a string containing information about the specified RSA algorithm.
static string ToString (DSACryptoServiceProvider alg)
Creates and returns a string containing information about the specified DSA algorithm.
static string ToString (AsymmetricAlgorithm alg)
Creates and returns a string containing information about the specified RSA algorithm.
static string ToString (X509Certificate certificate)
Returns a readable string representation of the specified certificate.
static string GetSimpleName (X509Certificate2 cert)
Returns simple name of the specified cerrtificate.
static string ToString (X509Certificate2 cert)
Returns a readable string representation of the specified certificate.
static string GetCertificateStoreDescription (int outputLevel=0, string storeName=null, int storeLocation=(int) StoreLocation.CurrentUser|(int) StoreLocation.LocalMachine)
Returns a string that contains human readable description of certificate stores.
static void GetCertificateStores (ref IList< X509Store > stores, bool clearAtBeginning=true, string storeName=null, int storeLocation=(int) StoreLocation.CurrentUser|(int) StoreLocation.LocalMachine)
Adds to the specified list all persistent certificate stores that match the criteria specified by parameters.
static void CloseCertificateStores (IList< X509Store > stores)
Closes all certificate stores on the list.
static X509Certificate2 GetCertificate (string privateKeyPassword=null, string certificateFilePath=null, string certificateName=null, string storeName=null, int storeLocation=(int) StoreLocation.CurrentUser|(int) StoreLocation.LocalMachine)
Obtains and returns the certificate specifid by parameters.
static string AddCertificateToStore (X509Certificate2 certificate, out bool skipped, out bool overwritten, string certificateStoreName, int storeLocation=(int) StoreLocation.CurrentUser, bool isForceOverwrites=false, bool isSkipOverwrites=false)
Adds a certificate to the specified certificate store.
static string DeleteCertificateFromStore (out bool skipped, out bool deleted, string certificateName, string storeName, int storeLocation=(int) StoreLocation.CurrentUser, bool isForceDeletes=false, bool isSkipDeletes=false)
Deletes the specified certificate to the specified certificate store.
static string GetAsymmetricalgorithmHash (AsymmetricAlgorithm algorithm, bool includePrivate=false, bool skipPrivateIfNotExportable=false, HashType hashType=HashType.SHA1)
Returns a hash value for the specified Asymmetric algorithm, which depends on algorithm keys.
static int GetMaximalAsymmetricTextLength (AsymmetricAlgorithm alg)
Returns the maximal size of a byte array that can be encrypted by using the specified asymmetric algoritm.
static bool AsymEncryptionDecryptionTest (string testString, AsymmetricAlgorithm algEnc, AsymmetricAlgorithm algDec=null)
Tests whether the specified asymmetric algorithm(s) correctly encrypts/decrypts the specified string.
static bool AsymEncryptionDecryptionTest (string testString, out string errorString, AsymmetricAlgorithm algEnc, AsymmetricAlgorithm algDec=null)
Tests whether the specified asymmetric algorithm(s) correctly encrypts/decrypts the specified string.
static bool AsymEncryptionDecryptionTest (int length, AsymmetricAlgorithm algEnc, AsymmetricAlgorithm algDec=null)
Tests whether the specified asymmetric algorithm(s) correctly encrypts/decrypts a random byte array of the specified size.
static bool AsymEncryptionDecryptionTest (int length, out string errorString, AsymmetricAlgorithm algEnc, AsymmetricAlgorithm algDec=null)
Tests whether the specified asymmetric algorithm(s) correctly encrypts/decrypts a random byte array of the specified size.
static AsymmetricAlgorithm GetAsymmetricAlgorithm (AsymmetricAlgorithmType algorithmType, string containerName=null, string xmlString=null, CspProviderFlags flags=CspProviderFlags.NoFlags, string certificateFilePath=null, string certificateName=null, string certStore=null)
Creates (if necessary) and returns a new asymmetric algorithm whose keys are either created or obtained through arguments.
static void DeleteKeyInCsp (AsymmetricAlgorithmType algorithmType, string containerName)
Deletes the asymmetric algorithm keys from the specified key container.
static void PrepareAymmetricAllgorithmBasic (AsymmetricAlgorithmType algorithmType, ref AsymmetricAlgorithm algorithm, string containerName=null, string xmlString=null, CspProviderFlags flags=CspProviderFlags.NoFlags, bool useLargestKey=false)
static string EncryptStringAsymShort (string stringToEncrypt, AsymmetricAlgorithm algorithm, AsymmetricAlgorithmType algorithmType=AsymmetricAlgorithmType.None)
static string DecryptStringAsymShort (string cipherText, AsymmetricAlgorithm algorithm, AsymmetricAlgorithmType algorithmType=AsymmetricAlgorithmType.None)
static byte[] EncryptAsymShort (byte[] originalBytes, AsymmetricAlgorithm algorithm, AsymmetricAlgorithmType algorithmType=AsymmetricAlgorithmType.None)
static byte[] DecryptAsymShort (byte[] originalBytes, AsymmetricAlgorithm algorithm, AsymmetricAlgorithmType algorithmType=AsymmetricAlgorithmType.None)
static byte[] EncryptAsymShort (byte[] originalBytes, AsymmetricAlgorithmType algorithmType=AsymmetricAlgorithmType.None, AsymmetricAlgorithm algorithm=null, string containerName=null, string xmlString=null, CspProviderFlags flags=CspProviderFlags.NoFlags, bool useLargestKey=false)
static byte[] DecryptAsymShort (byte[] originalBytes, AsymmetricAlgorithmType algorithmType=AsymmetricAlgorithmType.None, AsymmetricAlgorithm algorithm=null, string containerName=null, string xmlString=null, CspProviderFlags flags=CspProviderFlags.NoFlags, bool useLargestKey=false)
static string IgGetSaltSuffix (int whichSalt)
Returns the specified standard IGLib salt string.
static int IgGetNumSaltSuffices ()
Returns the number of standard IGLib salt strings.
Properties
static int OutputLevel [get]
Output level for static methods of the current utility class.
static object LockStatic [get]
Locking object for static methods and properties of this class.
static Encoding StringEncoding [get]
Gets the character encoding that is used for calculating hashes of strings.
static RNGCryptoServiceProvider Rng [get]
Object used to generate random bytes.
static bool IsUsed_fOAEP [get]
Whether to perform direct RSA encryption using OAEP (optimal asymmetric encryption padding - only available on computers running MS Windows XP or later).
Static Private Member Functions
static PasswordAlgorithmBase GetPasswordAlgorithmNoneSingleton ()
Returns password algorithm that does not change the password provided as initialization parameters.
static int SetLargestSymmetricAlgorithmKeySize (SymmetricAlgorithm algorithm)
On the specified symmetric encryption algorythm, sets the largest possible key size, in bits, for the spcified symmetric encryption algorithm.
static int SetLargestSymmetricAlgorithmBlockSize (SymmetricAlgorithm algorithm)
On the specified symmetric encryption algorithm, sets the largest possible block size, in bits, for the spcified symmetric encryption algorithm.
static int SetLargestAsymmetricAlgorithmKeySize (AsymmetricAlgorithm algorithm)
On the specified asymmetric encryption algorithm, sets the largest possible key size, in bits, for the corresponding asymmetric encryption algorithm.
Static Private Attributes
static int _outputLevel = 1
static object _lockStatic = null
static PasswordAlgorithmType[] _passwordAlgorithmTypes = null
static PasswordAlgorithmBase _passwordAlgorithmNone = null
static RNGCryptoServiceProvider _rng = null
static HashType[] _hashTypes = null
static SymmetricAlgorithmType[] _symmetricTypes = null
static AsymmetricAlgorithmType[] _asymmetricTypes = null
static bool _isUsed_fOAEP1 = false
static string[] _igLibLongSaltSuffices
An array of standard IGLib salt suffices.
Detailed Description
Basic Cryptographic utilities.
Warnings:
- Functions of this class must be fixed (may not change over time) in order not to break any security instruments.
- Functions can only be renamd (always by refactoring tools that change all calls to functions).
- For IGLib functions (IGLib specific supplements of standards), these should only be used through standard shell applications. In such a way security tools can not be broken, as shell functions are more guaranteed to behave constantly over time.
See also:
- Cryptographic hashRet function: http://en.wikipedia.org/wiki/Cryptographic_hash_function
- Password verification: http://en.wikipedia.org/wiki/Cryptographic_hash_function#Password_verification
- Storing passwords: http://www.aspheute.com/english/20040105.asp
- How to encrypt user passwords: http://www.jasypt.org/howtoencryptuserpasswords.html
- Salt: https://en.wikipedia.org/wiki/Salt_(cryptography)
- Key stretching: http://en.wikipedia.org/wiki/Key_stretching
$A Igor Apr10 Jun15;
Member Function Documentation
static PasswordAlgorithmType [] IG.Crypto.UtilCrypto.GetPasswordAlgorithmTypes () inline static
Returns all password algorithm types contained in the enumeration PasswordAlgorithmType
References IG.Lib.Util.LockGlobal.
static PasswordAlgorithmType IG.Crypto.UtilCrypto.GetPasswordAlgorithmType (string typeString) inline static
Returns a PasswordAlgorithmType value corresponding to the specified string representation.
Parameters
typeString String that represents the PasswordAlgorithmType value.
Referenced by IG.Crypto.CryptoManager.AppKeyGenerationAll(), IG.Script.ScriptAppBase.CryptoFunctionTimeKeyGeneration_OLD_TO_DELETE_LATER(), and IG.Crypto.CryptoManager.ParseCommandlineParameters().
static PasswordAlgorithmType IG.Crypto.UtilCrypto.GetPasswordAlgorithmType (PasswordAlgorithmBase algorithmObject) inline static
Returns the password generation algorithm type, i.e. an enumeration of type PasswordAlgorithmType, for the specified password generation algorithm object.
Parameters
algorithmObject Password generaton algorithm object for which type enumeration is returned.
Returns
The type enumeration corresponding to the specified algorithm, or 0 (None) if the algorithm is null or not contained in the enumeration.
static string IG.Crypto.UtilCrypto.PasswordAlgorithmTypeToString (PasswordAlgorithmType passwordAlgorithmType) inline static
Returns standard string representation of the specified password generation algoithm.
Parameters
passwordAlgorithmType Password algorithm type whose string representation is returned.
Referenced by IG.Crypto.UtilCrypto.PrepareSymmetricAllgorithmBasic().
static PasswordAlgorithmBase IG.Crypto.UtilCrypto.GetPasswordAlgorithmNoneSingleton () inline static private
Returns password algorithm that does not change the password provided as initialization parameters.
The same object is returned by each call.
References IG.Lib.Util.LockGlobal.
static IG.Crypto.PasswordAlgorithmBase IG.Crypto.UtilCrypto.GetPasswordAlgorithm (PasswordAlgorithmType algorithmType) inline static
Returns the appropriate password generation algorithm according to the specified algorithm type, or null if the type is not recognized or the method is not implemented for that type.
Parameters
algorithmType Specification of the password generaion algorithm type.
Referenced by IG.Crypto.CryptoManager.AppKeyGenerationAll(), IG.Script.ScriptAppBase.CryptoFunctionTimeKeyGeneration_OLD_TO_DELETE_LATER(), and IG.Crypto.UtilCrypto.PrepareSymmetricAllgorithmBasic().
static bool IG.Crypto.UtilCrypto.IsCorrectPasswordAlgorithm (DeriveBytes algorithm, PasswordAlgorithmType algorithmType) inline static
Returns true if the specified password generation algorithm corresponds the type specification, false otherwise.
If the specified algorithm is null or the specified type is unknown then false is returned.
Parameters
algorithm Algorithm that is checked for type correctness.
algorithmType Specification of the password derivation nalgorithm type.
static string IG.Crypto.UtilCrypto.CreateRandomPassword (int PasswordLength, string allowedChars = null) inline static
Creates and returns a random password consisting of only allowed characters from the specified string.
Cryptographically secure random numbers are used to select characters for the password from the array of allowed characters.
Parameters
PasswordLength Length of the generated password.
allowedChars String containing allowed characters of the password.
By default (if parameter is a null or empty string), these are digits and lower- and upper- case English letters.
Returns
A random password of specified length.
static void IG.Crypto.UtilCrypto.GetRandomBytes (byte[] byteArray) inline static
Fills the specified byte array with a cryptographically strong sequence of random bytes.
Parameters
byteArray Byte array that is filled with random bytes.
Referenced by IG.Script.ScriptAppBase.CryptoFunctionTimeKeyGeneration_OLD_TO_DELETE_LATER(), IG.Crypto.CryptoManager.ResolvePasswordParameters(), IG.Test.TestCrypto.SymmetricEncryptionFilesPlain(), IG.Test.TestCrypto.SymmetricEncryptionStringBase(), IG.Test.TestCrypto.SymmetricEncryptionStringPlain(), and IG.Test.TestCrypto.SymmetricEncryptionStringPlainRandom().
static void IG.Crypto.UtilCrypto.GetRandomBytes (ref byte[] byteArray, int numBytes) inline static
Fills the specified byte array with a specified number of cryptographically strong random bytes.
Byte array is created anew if its size does not equal the specified number of bytes.
Parameters
byteArray Byte array that is filled with random bytes. Reallocated if necessary.
numBytes Number of bytes to be filled into the array.
static byte [] IG.Crypto.UtilCrypto.GetRandomBytes (int numBytes) inline static
Creates and returns an array of cryptographically strong random bytes of the specified size.
Parameters
numBytes Number of bytes to be filled into the array.
static int IG.Crypto.UtilCrypto.GetHashLengthBytes (HashType hashType) inline static
Returns length of the hashRet value, in bytes, for the specified hashRet algorithm.
-1 is returned if the length is not known.
Parameters
hashType Type of the hashing algorithm.
static int IG.Crypto.UtilCrypto.GetHashLengthHex (HashType hashType) inline static
Returns length of the HEXADECIMAL hashRet string for the specified hashRet algorithm.
-1 is returned if the length is not known.
Parameters
hashType Type of the hashing algorithm.
static HashType [] IG.Crypto.UtilCrypto.GetHashTypes () inline static
Returns all hashing algorithm types contained in the enumeration HashType
References IG.Lib.Util.LockGlobal.
Referenced by IG.Test.TestCrypto.HashTypes().
static HashType IG.Crypto.UtilCrypto.GetHashType (string typeString) inline static
Returns a HashType value corresponding to the specified string representation.
Parameters
typeString String that represents the hashRet type.
Referenced by IG.Script.ScriptAppBase.CryptoFunctionCheckSum_OLD_TO_DELETE_LATER(), IG.Test.TestCrypto.HashTypes(), and IG.Crypto.CryptoManager.ParseCommandlineParameters().
static HashType IG.Crypto.UtilCrypto.GetHashType (HashAlgorithm algorithmObject) inline static
Returns the hashing algorithm type, i.e. an enumeration of type HashType, for the specified hashing algorithm object.
Parameters
algorithmObject Hashing algorithm object for which type enumeration is returned.
Returns
The type enumeration corresponding to the specified algorithm, or 0 (None) if the algorithm is null or not contained in the enumeration.
static string IG.Crypto.UtilCrypto.HashTypeToString (HashType hashType) inline static
Returns standard string representation of the specified hashRet type.
Parameters
hashType Hash type whose string representation is returned.
Referenced by IG.Test.TestCrypto.HashTypes().
static HashAlgorithm IG.Crypto.UtilCrypto.GetHashAlgorithm (HashType hashType) inline static
Returns the appropriate hashRet algorithm according to the specified hashRet type, or null if the type is not recognized or the method is not implemented for that type.
Parameters
hashType Specification of the hashRet algorithm type.
static bool IG.Crypto.UtilCrypto.IsCorrectHashAlgorithm (HashAlgorithm algorithm, HashType algorithmType) inline static
Returns true if the specified cryptographic hashRet algorithm corresponds the type specification, false otherwise.
If the specified algorithm is null or the specified type is unknown then false is returned.
Parameters
algorithmType Specification of the cryptographic hashRet algorithm type.
algorithm Algorithm that is checked for type correctness.
static void IG.Crypto.UtilCrypto.ParseHashFile (string filePath, ref List< string[]> hashList) inline static
Parses the file containing hashRet values of one or more files, and adds the parsed pairs {hashRet, inputFilePath} to the specified list.
File must be in the standard format where each line contains a hashRet value and the path to the corresponding file separated from hashRet value by one or more spaces.
List is allocated if necessary. Eventual existent pairs on the list are not affected.
Parameters
filePath Path to the file that is parsed.
hashList List to which which parsed pairs {hashRet, inputFilePath} are added in form of arrays of 2 strings.
Example contents of the file:
595f44fec1e92a71d3e9e77456ba80d1 filetohashA.txt
71f920fa275127a7b60fa4d4d41432a3 filetohashB.txt
43c191bf6d6c3f263a8cd0efd4a058ab filetohashC.txt
/remarks>
Referenced by IG.Crypto.CryptoManager.AppCheckSum(), and IG.Script.ScriptAppBase.CryptoFunctionCheckSum_OLD_TO_DELETE_LATER().
static void IG.Crypto.UtilCrypto.ParseHashFileString (string str, ref List< string[]> hashList) inline static
Parses the string containing hashRet values of one or more files, and adds the parsed pairs {hashRet, inputFilePath} to the specified list.
String must be in the standard format where each line contains a hashRet value and the path to the corresponding file separated from hashRet value by one or more spaces.
List is allocated if necessary. Eventual existent pairs on the list are not affected.
Parameters
str String that is parsed.
hashList List to which which parsed pairs {hashRet, inputFilePath} are added in form of arrays of 2 strings.
Example contents of the string:
595f44fec1e92a71d3e9e77456ba80d1 filetohashA.txt
71f920fa275127a7b60fa4d4d41432a3 filetohashB.txt
43c191bf6d6c3f263a8cd0efd4a058ab filetohashC.txt
/remarks>
static byte [] IG.Crypto.UtilCrypto.GetHashBytes (byte[] bytesToHash, HashType hashType, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the hashRet (in form of byte array) of the specified kind of the specified byte array.
Exception (InvalidOperationException) is thrown if the specified hashRet type is not known or implemented.
Parameters
bytesToHash Byte array whose hashRet string is calculated.
hashType Specifies the type of the hashing algorithm to be used.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by teh method. Its type must correspond the specified type.
static string IG.Crypto.UtilCrypto.GetHashHex (byte[] bytesToHash, HashType hashType, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the hashRet string of the specified kind of the specified byte array.
Exception (InvalidOperationException) is thrown if the specified hashRet type is not known or implemented.
Parameters
bytesToHash Byte array whose hashRet string is calculated.
hashType Specifies the type of the hashing algorithm to be used.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by teh method. Its type must correspond the specified type.
References IG.Lib.Util.ToHexString().
Referenced by IG.Crypto.CryptoManager.AppCheckSum().
static string IG.Crypto.UtilCrypto.GetHashMd5Hex (byte[] bytesToHash) inline static
Computes and returns the MD5 hashRet string of the specified array of bytes.
Parameters
bytesToHash Byte array whose hashRet string is calculated.
Referenced by IG.Test.TestCrypto.HashStringSaltedMd5().
static string IG.Crypto.UtilCrypto.GetHashSha1Hex (byte[] bytesToHash) inline static
Computes and returns the SHA1 hashRet string of the specified array of bytes.
Parameters
bytesToHash Byte array whose hashRet string is calculated.
Referenced by IG.Test.TestCrypto.HashStringSaltedSha1().
static string IG.Crypto.UtilCrypto.GetHashSha256Hex (byte[] bytesToHash) inline static
Computes and returns the SHA256 hashRet string of the specified array of bytes.
Parameters
bytesToHash Byte array whose hashRet string is calculated.
Referenced by IG.Test.TestCrypto.HashStringSaltedSha256().
static string IG.Crypto.UtilCrypto.GetHashSha512Hex (byte[] bytesToHash) inline static
Computes and returns the SHA512 hashRet string of the specified array of bytes.
Parameters
bytesToHash Byte array whose hashRet string is calculated.
Referenced by IG.Test.TestCrypto.HashStringSaltedSHA512().
static bool IG.Crypto.UtilCrypto.CheckHashHex (byte[] bytesToCheck, string hashValue, HashType hashAlgorithmType) inline static
Chechs the specified type of hashRet value of a byte array.
Returns true if the hashRet value matches the hashRet value of the byte array, and false otherwise.
Parameters
bytesToCheck String whose hashRet value is checked.
hashValue Supposed hashRet value whose correctness is checked.
hashAlgorithmType Type of the hashRet value that is checked.
Returns
True if the specified hashRet hashValue actually matches the hashRet value of the type hashAlgorithmType of the verified string bytesToCheck , or false otherwise.
References IG.Lib.Util.AreHexStringsEqual().
Referenced by IG.Crypto.CryptoManager.AppCheckSum().
static HashType IG.Crypto.UtilCrypto.CheckHashSupportedTypesHex (byte[] bytesToCheck, string hashValue) inline static
Chechs all supported types of hashRet value of a string.
Returns the hashRet type if the hashRet value matches the hashRet value of that type of the specified string, or HashType.None if the specified hashRet value doesn't match the hashRet value of any supported type of the string.
Parameters
bytesToCheck String whose hashRet value is checked.
hashValue Supposed hashRet value whose match with the specified string is checked.
Returns
Type of the hashRet value that matches the specified hashRet value of the specified string, or HashType.None if the specified hashRet value doesn't match the hashRet value of any supported type of the specified string.
References IG.Lib.Util.AreHexStringsEqual().
static byte [] IG.Crypto.UtilCrypto.GetStringHashBytes (string stringToHash, HashType hashType = HashType.Default, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the hashRet string of the specified kind of the specified string.
Exception (InvalidOperationException) is thrown if the specified hashRet type is not known or implemented.
Parameters
stringToHash String whose hashRet string is calculated.
hashType Specifies the type of the hashing algorithm to be used.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by the method. Its type must correspond the specified type.
static string IG.Crypto.UtilCrypto.GetStringHashHex (string stringToHash, HashType hashType = HashType.Default, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the hashRet string of the specified kind of the specified string.
Exception (InvalidOperationException) is thrown if the specified hashRet type is not known or implemented.
Parameters
stringToHash String whose hashRet string is calculated.
hashType Specifies the type of the hashing algorithm to be used.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by the method. Its type must correspond the specified type.
References IG.Lib.Util.ToHexString().
Referenced by IG.Crypto.CryptoManager.AppCheckSum(), IG.Script.ScriptAppBase.CryptoFunctionCheckSum_OLD_TO_DELETE_LATER(), and IG.Crypto.UtilCrypto.GetAsymmetricalgorithmHash().
static string IG.Crypto.UtilCrypto.GetStringHashMd5Hex (string stringToHash) inline static
Computes and returns the MD5 hashRet string of the specified string.
Parameters
stringToHash String whose cryptographic hashRet is calculated.
Referenced by IG.Forms.HashControl.CalculateHashes(), and IG.Test.TestCrypto.HashStringMd5().
static string IG.Crypto.UtilCrypto.GetStringHashSha1Hex (string stringToHash) inline static
Computes and returns the SHA1 hashRet string of the specified string.
Parameters
stringToHash String whose cryptographic hashRet is calculated.
Referenced by IG.Forms.HashControl.CalculateHashes(), and IG.Test.TestCrypto.HashStringSha1().
static string IG.Crypto.UtilCrypto.GetStringHashSha256Hex (string stringToHash) inline static
Computes and returns the SHA256 hashRet string of the specified string.
Parameters
stringToHash String whose cryptographic hashRet is calculated.
Referenced by IG.Forms.HashControl.CalculateHashes(), and IG.Test.TestCrypto.HashStringSha256().
static string IG.Crypto.UtilCrypto.GetStringHashSha512Hex (string stringToHash) inline static
Computes and returns the SHA512 hashRet string of the specified string.
Parameters
stringToHash String whose cryptographic hashRet is calculated.
Referenced by IG.Forms.HashControl.CalculateHashes(), and IG.Test.TestCrypto.HashStringSha512().
static byte [] IG.Crypto.UtilCrypto.GetStringSaltedHashBytes (string stringToHash, HashType hashType, string salt, int numIterations = 0, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the salted hashRet (in form of byte array) of the specified kind of the specified string, with the specified number of repetitions of the salted hashing algoriithm.
Exception (InvalidOperationException) is thrown if the specified hashRet type is not known or implemented.
Parameters
stringToHash String whose salted hashRet is to be computed.
hashType Type of hashing algorithm used.
salt Salt string.
numIterations Optional number of iterations. If hreater than 0 then hashing algorithm is reapplied to the salted result of the previous computation for the specified number of time.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by the method. Its type must correspond the specified type.
Returns
The salted hashRet of the specified string, with specified hashRet, and specified number of repetitions of the salted hashRet calculation.
static string IG.Crypto.UtilCrypto.GetStringSaltedHash (string stringToHash, HashType hashType, string salt, int numIterations = 0, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the salted hashRet of the specified kind of the specified string, with the specified number of repetitions of the salted hashing algoriithm.
Exception (InvalidOperationException) is thrown if the specified hashRet type is not known or implemented.
Parameters
stringToHash String whose salted hashRet is to be computed.
hashType Type of hashing algorithm used.
salt Salt string.
numIterations Optional number of iterations. If hreater than 0 then hashing algorithm is reapplied to the salted result of the previous computation for the specified number of time.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by the method. Its type must correspond the specified type.
Returns
The salted hashRet of the specified string, with specified hashRet, and specified number of repetitions of the salted hashRet calculation.
References IG.Lib.Util.ToHexString().
static string IG.Crypto.UtilCrypto.GetStringSaltedHashMd5Hex (string stringToHash, string salt, int numIterations = 0) inline static
Computes and returns the MD5 salted hashRet of the specified string, with the specified number of repetitions of the salted hashing algoriithm.
Exception (InvalidOperationException) is thrown if the specified hashRet type is not known or implemented.
Parameters
stringToHash String whose salted hashRet is to be computed.
salt Salt string.
numIterations Optional number of iterations. If hreater than 0 then hashing algorithm is reapplied to the salted result of the previous computation for the specified number of time.
Returns
The salted hashRet of the specified string, with specified hashRet, and specified number of repetitions of the salted hashRet calculation.
Referenced by IG.Test.TestCrypto.HashStringSaltedMd5().
static string IG.Crypto.UtilCrypto.GetStringSaltedHashSha1Hex (string stringToHash, string salt, int numIterations = 0) inline static
Computes and returns the SHA1 salted hashRet of the specified string, with the specified number of repetitions of the salted hashing algoriithm.
Exception (InvalidOperationException) is thrown if the specified hashRet type is not known or implemented.
Parameters
stringToHash String whose salted hashRet is to be computed.
salt Salt string.
numIterations Optional number of iterations. If hreater than 0 then hashing algorithm is reapplied to the salted result of the previous computation for the specified number of time.
Returns
The salted hashRet of the specified string, with specified hashRet, and specified number of repetitions of the salted hashRet calculation.
Referenced by IG.Test.TestCrypto.HashStringSaltedSha1().
static string IG.Crypto.UtilCrypto.GetStringSaltedHashSha256Hex (string stringToHash, string salt, int numIterations = 0) inline static
Computes and returns the SHA-256 salted hashRet of the specified string, with the specified number of repetitions of the salted hashing algoriithm.
Exception (InvalidOperationException) is thrown if the specified hashRet type is not known or implemented.
Parameters
stringToHash String whose salted hashRet is to be computed.
salt Salt string.
numIterations Optional number of iterations. If hreater than 0 then hashing algorithm is reapplied to the salted result of the previous computation for the specified number of time.
Returns
The salted hashRet of the specified string, with specified hashRet, and specified number of repetitions of the salted hashRet calculation.
Referenced by IG.Test.TestCrypto.HashStringSaltedSha256().
static string IG.Crypto.UtilCrypto.GetStringSaltedHashSha512Hex (string stringToHash, string salt, int numIterations = 0) inline static
Computes and returns the SHA-512 salted hashRet of the specified string, with the specified number of repetitions of the salted hashing algoriithm.
Exception (InvalidOperationException) is thrown if the specified hashRet type is not known or implemented.
Parameters
stringToHash String whose salted hashRet is to be computed.
salt Salt string.
numIterations Optional number of iterations. If hreater than 0 then hashing algorithm is reapplied to the salted result of the previous computation for the specified number of time.
Returns
The salted hashRet of the specified string, with specified hashRet, and specified number of repetitions of the salted hashRet calculation.
Referenced by IG.Test.TestCrypto.HashStringSaltedSHA512().
static bool IG.Crypto.UtilCrypto.CheckStringHashHex (string stringToCheck, string hashValue, HashType hashAlgorithmType) inline static
Chechs the specified type of hashRet value of a string.
Returns true if the hashRet value matches the hashRet value of the string, and false otherwise.
Parameters
stringToCheck String whose hashRet value is checked.
hashValue Supposed hashRet value whose correctness is checked.
hashAlgorithmType Type of the hashRet value that is checked.
Returns
True if the specified hashRet hashValue actually matches the hashRet value of the type hashAlgorithmType of the verified string stringToCheck , or false otherwise.
References IG.Lib.Util.AreHexStringsEqual().
Referenced by IG.Crypto.CryptoManager.AppCheckSum(), and IG.Script.ScriptAppBase.CryptoFunctionCheckSum_OLD_TO_DELETE_LATER().
static HashType IG.Crypto.UtilCrypto.CheckStringHashSupportedTypesHex (string stringToCheck, string hashValue) inline static
Chechs all supported types of hashRet value of a string.
Returns the hashRet type if the hashRet value matches the hashRet value of that type of the specified string, or HashType.None if the specified hashRet value doesn't match the hashRet value of any supported type of the string.
Parameters
stringToCheck String whose hashRet value is checked.
hashValue Supposed hashRet value whose match with the specified string is checked.
Returns
Type of the hashRet value that matches the specified hashRet value of the specified string, or HashType.None if the specified hashRet value doesn't match the hashRet value of any supported type of the specified string.
References IG.Lib.Util.AreHexStringsEqual().
Referenced by IG.Forms.HashControl.VerifyHash().
static bool IG.Crypto.UtilCrypto.CheckStringHashMd5Hex (string stringToCheck, string hashValue) inline static
Checks whether the specified MD5 hashRet value matches the actual hashRet value of the specified string.
Returns true if the specified hashRet value matches the actual hashRet value of the string, and false otherwise.
Parameters
stringToCheck String whose hashRet value is checked.
hashValue Supposed hashRet value whose validity is checked for the specified string.
Returns
True if the specified hashRet value matches the actual value, false otherwise.
static bool IG.Crypto.UtilCrypto.CheckStringHashSha1Hex (string stringToCheck, string hashValue) inline static
Checks whether the specified SHA-1 hashRet value matches the actual hashRet value of the specified string.
Returns true if the specified hashRet value matches the actual hashRet value of the string, and false otherwise.
Parameters
stringToCheck String whose hashRet value is checked.
hashValue Supposed hashRet value whose validity is checked for the specified string.
Returns
True if the specified hashRet value matches the actual value, false otherwise.
static bool IG.Crypto.UtilCrypto.CheckStringHashSha256Hex (string stringToCheck, string hashValue) inline static
Checks whether the specified SHA-256 hashRet value matches the actual hashRet value of the specified string.
Returns true if the specified hashRet value matches the actual hashRet value of the string, and false otherwise.
Parameters
stringToCheck String whose hashRet value is checked.
hashValue Supposed hashRet value whose validity is checked for the specified string.
Returns
True if the specified hashRet value matches the actual value, false otherwise.
static bool IG.Crypto.UtilCrypto.CheckStringHashSha512Hex (string stringToCheck, string hashValue) inline static
Checks whether the specified SHA-512 hashRet value matches the actual hashRet value of the specified string.
Returns true if the specified hashRet value matches the actual hashRet value of the string, and false otherwise.
Parameters
stringToCheck String whose hashRet value is checked.
hashValue Supposed hashRet value whose validity is checked for the specified string.
Returns
True if the specified hashRet value matches the actual value, false otherwise.
static byte [] IG.Crypto.UtilCrypto.GetFileHashBytes (string filePath, HashType hashType, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the hashRet (in form of byte array) of specified type of the specified stream.
Parameters
filePath Path to the file whose contents' cryptographic hashRet is calculated.
hashType Specifies the type of the hashing algorithm to be used.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by teh method. Its type must correspond the specified type.
static string IG.Crypto.UtilCrypto.GetFileHashHex (string filePath, HashType hashType, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the hashRet string of specified type of the specified stream.
Parameters
filePath Path to the file whose contents' cryptographic hashRet is calculated.
hashType Specifies the type of the hashing algorithm to be used.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by teh method. Its type must correspond the specified type.
Referenced by IG.Crypto.CryptoManager.AppCheckSum(), and IG.Script.ScriptAppBase.CryptoFunctionCheckSum_OLD_TO_DELETE_LATER().
static string IG.Crypto.UtilCrypto.GetFileHashMd5Hex (string filePath, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the MD5 hashRet string of the specified stream.
Parameters
filePath Path to the file whose contents' cryptographic hashRet is calculated.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by teh method. Its type must correspond the specified type.
Referenced by IG.Crypto.CryptoManager.AppGetFileHash(), IG.Forms.HashControl.CalculateHashes(), and IG.Script.ScriptAppBase.CryptoFunctionGetFileHash_OLD_TO_DELETE().
static string IG.Crypto.UtilCrypto.GetFileHashSha1Hex (string filePath, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the SHA1 hashRet string of the specified stream.
Parameters
filePath Path to the file whose contents' cryptographic hashRet is calculated.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by teh method. Its type must correspond the specified type.
Referenced by IG.Crypto.CryptoManager.AppGetFileHash(), IG.Forms.HashControl.CalculateHashes(), and IG.Script.ScriptAppBase.CryptoFunctionGetFileHash_OLD_TO_DELETE().
static string IG.Crypto.UtilCrypto.GetFileHashSha256Hex (string filePath, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the SHA256 hashRet string of the specified stream.
Parameters
filePath Path to the file whose contents' cryptographic hashRet is calculated.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by teh method. Its type must correspond the specified type.
Referenced by IG.Crypto.CryptoManager.AppGetFileHash(), IG.Forms.HashControl.CalculateHashes(), and IG.Script.ScriptAppBase.CryptoFunctionGetFileHash_OLD_TO_DELETE().
static string IG.Crypto.UtilCrypto.GetFileHashSha512Hex (string filePath, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the SHA512 hashRet string of the specified stream.
Parameters
filePath Path to the file whose contents' cryptographic hashRet is calculated.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by teh method. Its type must correspond the specified type.
Referenced by IG.Crypto.CryptoManager.AppGetFileHash(), IG.Forms.HashControl.CalculateHashes(), and IG.Script.ScriptAppBase.CryptoFunctionGetFileHash_OLD_TO_DELETE().
static byte [] IG.Crypto.UtilCrypto.GetHashBytes (Stream stream, HashType hashType, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the hashRet (in form of byte array) of specified type of the specified stream.
Parameters
stream Stream whose contents' cryptographic hashRet is calculated.
hashType Type of the hashRet algorithm used.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by the method. Its type must correspond the specified type.
static string IG.Crypto.UtilCrypto.GetHashHex (Stream stream, HashType hashType, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the hexadecimal hashRet string of specified type of the specified stream.
Parameters
stream Stream whose contents' cryptographic hashRet is calculated.
hashType Type of the hashRet algorithm used.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by the method. Its type must correspond the specified type.
References IG.Lib.Util.ToHexString().
static string IG.Crypto.UtilCrypto.GetHashMd5Hex (Stream stream, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the MD5 hashRet string of the specified stream.
Parameters
stream Stream whose contents' cryptographic hashRet is calculated.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by the method. Its type must correspond the specified type.
static string IG.Crypto.UtilCrypto.GetHashSha1Hex (Stream stream, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the SHA1 hashRet string of the specified stream.
Parameters
stream Stream whose contents' cryptographic hashRet is calculated.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by the method. Its type must correspond the specified type.
static string IG.Crypto.UtilCrypto.GetHashSha256Hex (Stream stream, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the SHA256 hashRet string of the specified stream.
Parameters
stream Stream whose contents' cryptographic hashRet is calculated.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by the method. Its type must correspond the specified type.
static string IG.Crypto.UtilCrypto.GetHashSha512Hex (Stream stream, HashAlgorithm cryptoAlgorithm = null) inline static
Computes and returns the SHA512 hashRet string of the specified stream.
Parameters
stream Stream whose contents' cryptographic hashRet is calculated.
cryptoAlgorithm Algorithm objedt used to perform the job. If not specified then it is created by the method. Its type must correspond the specified type.
static bool IG.Crypto.UtilCrypto.CheckFileHashHex (string filePath, string hashValue, HashType hashType, HashAlgorithm cryptoAlgorithm = null) inline static
Chechs the specified type of hashRet value of a file.
Returns true if the specified hashRet value matches the hashRet value of the file, and false otherwise.
Parameters
filePath Path to the file whose hashRet value is checked.
hashValue Supposed hashRet value whose correctness is checked.
hashType Type of the hashRet value that is checked.
cryptoAlgorithm Hasihing algoriithm to be used.
Returns
True if hashType specified hashRet hashValue actually matches the hashRet value of the type hashType of the verified file filePath , or false otherwise.
References IG.Lib.Util.AreHexStringsEqual().
Referenced by IG.Crypto.CryptoManager.AppCheckSum(), and IG.Script.ScriptAppBase.CryptoFunctionCheckSum_OLD_TO_DELETE_LATER().
static HashType IG.Crypto.UtilCrypto.CheckFileHashSupportedTypesHex (string filePath, string hashValue) inline static
Chechs all supported types of hashRet value of a file.
Returns the hashRet type if the hashRet value matches the hashRet value of that type of the specified file, or HashType.None if the specified hashRet value doesn't match the hashRet value of any supported type of the specified file.
Parameters
filePath Path to the file whose hashRet value is checked.
hashValue Supposed hashRet value whose match with the specified file is checked.
Returns
Type of the hashRet value that matches the specified hashRet value of the specified file, or HashType.None if the specified hashRet value doesn't match the hashRet value of any supported type of the specified file.
References IG.Lib.Util.AreHexStringsEqual().
Referenced by IG.Forms.HashControl.VerifyHash().
static bool IG.Crypto.UtilCrypto.CheckFileHashMd5Hex (string filePath, string hashValue) inline static
Checks whether the specified MD5 hashRet value matches the actual hashRet value of the specified file.
Returns true if the specified hashRet value matches the actual hashRet value of the file, and false otherwise.
Parameters
filePath Path to the file whose hashRet value is checked.
hashValue Supposed hashRet value whose validity is checked for the specified file.
Returns
True if the specified file hashRet value matches the actual value, false otherwise.
static bool IG.Crypto.UtilCrypto.CheckFileHashSha1Hex (string filePath, string hashValue) inline static
Checks whether the specified SHA-1 hashRet value matches the actual hashRet value of the specified file.
Returns true if the specified hashRet value matches the actual hashRet value of the file, and false otherwise.
Parameters
filePath Path to the file whose hashRet value is checked.
hashValue Supposed hashRet value whose validity is checked for the specified file.
Returns
True if the specified file hashRet value matches the actual value, false otherwise.
static bool IG.Crypto.UtilCrypto.CheckFileHashSha256Hex (string filePath, string hashValue) inline static
Checks whether the specified SHA-256 hashRet value matches the actual hashRet value of the specified file.
Returns true if the specified hashRet value matches the actual hashRet value of the file, and false otherwise.
Parameters
filePath Path to the file whose hashRet value is checked.
hashValue Supposed hashRet value whose validity is checked for the specified file.
Returns
True if the specified file hashRet value matches the actual value, false otherwise.
static bool IG.Crypto.UtilCrypto.CheckFileHashSha512Hex (string filePath, string hashValue) inline static
Checks whether the specified SHA-512 hashRet value matches the actual hashRet value of the specified file.
Returns true if the specified hashRet value matches the actual hashRet value of the file, and false otherwise.
Parameters
filePath Path to the file whose hashRet value is checked.
hashValue Supposed hashRet value whose validity is checked for the specified file.
Returns
True if the specified file hashRet value matches the actual value, false otherwise.
static SymmetricAlgorithmType [] IG.Crypto.UtilCrypto.GetSymmetricAlgorithmTypes () inline static
Returns all symmetric encryption algorithm types contained in the enumeration SymmetricAlgorithmType
References IG.Lib.Util.LockGlobal.
Referenced by IG.Test.TestCrypto.SymmetricAlgorithmTypes().
static SymmetricAlgorithmType IG.Crypto.UtilCrypto.GetSymmetricAlgorithmType (string typeString) inline static
Returns the SymmetricAlgorithmType value corresponding to the specified string.
This function enables selection of algorithms with strings that can have arbitrary capitalization of their letters, and are thus friendly for user insertion.
Parameters
typeString String that represents the symmetric encryption algorithm type.
Referenced by IG.Crypto.CryptoManager.ParseCommandlineParameters(), and IG.Test.TestCrypto.SymmetricAlgorithmTypes().
static SymmetricAlgorithmType IG.Crypto.UtilCrypto.GetSymmetricAlgorithmType (SymmetricAlgorithm algorithmObject) inline static
Returns the symmetric encryption algorithm type, i.e. an enumeration of type SymmetricAlgorithmType, for the specified symmetric encryption algorithm object.
Parameters
algorithmObject Symmetric algorithm object for which type enumeration is returned.
Returns
The type enumeration corresponding to the specified algorithm, or 0 (None) if the algorithm is null or not contained in the enumeration.
static string IG.Crypto.UtilCrypto.SymmetricAlgorithmTypeToString (SymmetricAlgorithmType algorithmType) inline static
Returns standard string representation of the specified symmetric encryption algorithm type.
Parameters
algorithmType Symmetric encryption algorithm type whose string representation is returned.
Referenced by IG.Crypto.CryptoManager.AppEncryptSymmetricAll(), IG.Test.TestCrypto.SymmetricAlgorithmTypes(), IG.Test.TestCrypto.SymmetricEncryptionFilesPlain(), IG.Test.TestCrypto.SymmetricEncryptionStringBase(), IG.Test.TestCrypto.SymmetricEncryptionStringPlain(), IG.Test.TestCrypto.SymmetricEncryptionStringPlainRandom(), and IG.Test.TestCrypto.SymmetricEncryptionStringToBytesPlain().
static SymmetricAlgorithm IG.Crypto.UtilCrypto.GetSymmetricEncryptionAlgorithm (SymmetricAlgorithmType algorithmType) inline static
Returns the appropriate symmetric encryption algorithm according to the specified hashRet type, or null if the type is not recognized or the method is not implemented for that type.
Parameters
algorithmType Specification of the symmetric encryption algorithm type.
static bool IG.Crypto.UtilCrypto.IsCorrectSymmetricEncryptionAlgorithm (SymmetricAlgorithm algorithm, SymmetricAlgorithmType algorithmType) inline static
Returns true if the specified symmetric encryption algorithm corresponds the type specification, false otherwise.
If the specified algorithm is null or the specified type is unknown then false is returned.
Parameters
algorithmType Specification of the symmetric encryption algorithm type.
algorithm Algorithm that is checked for type correctness.
static byte [] IG.Crypto.UtilCrypto.PadToAlgorithmBlocksizeCyclic (byte[] byteArray, int blockSize, bool truncateIfLarger = false) inline static
For the specified symmetric encryption algorithm, this function takes the specified byte array and checks if the array is of valid size. If yes then the unmodified initialization array is returned, otherwise the modified array that fits the required block size is returned (i.e. has integer number of blocks).
Bytes that are missing to the last full block are filled cyclically with the original bytes from teh beginning.
Parameters
byteArray Original array provided for the algorithm with specified block size.
blockSize Block size of the algorithm for which array is repaired, in bytes.
Warning: Algorithms specify block size in bits, not in bytes.
Parameters
truncateIfLarger If true then the byte array is truncated to the block size if it is larger than it.
Warning: this can only be done with the key and initialization vector, but not with data!!
Returns
An array that is of valid size for the algorithm.
If the original initialization vector size matches the required one, the vector is unmodified.
If the original vector is not a multiple of block size, it is padded by its initial bytes until the desired length.
Referenced by IG.Crypto.PasswordAlgorithmNone.GetBytesInternal().
static byte [] IG.Crypto.UtilCrypto.PadToAlgorithmBlocksizeZero (byte[] byteArray, int blockSize, bool truncateIfLarger = false) inline static
For the specified symmetric encryption algorithm, this function takes the specified byte array and checks if the array is of valid size. If yes then the unmodified initialization array is returned, otherwise the modified array that fits the required block size is returned (i.e. has integer number of blocks).
Bytes that are missing to the last full block are filled cyclically with the original bytes from teh beginning.
Parameters
byteArray Original array provided for the algorithm with specified block size.
blockSize Block size of the algorithm for which array is repaired.
truncateIfLarger If true then the byte array is truncated to the block size if it is larger than it.
Warning: this can only be done with the key and initialization vector, but not with data!!
Returns
An array that is of valid size for the algorithm.
If the original initialization vector size matches the required one, the vector is unmodified.
If the original vector is not a multiple of block size, it is padded by its initial bytes until the desired length.
static byte [] IG.Crypto.UtilCrypto.PadToSymmetricAlgorithmBlocksizeCyclic (byte[] byteArray, SymmetricAlgorithm algorithm, bool truncateIfLarger = false) inline static
For the specified symmetric encryption algorithm, this function takes the specified byte array and checks if the array is of valid size. If yes then the unmodified array is returned, otherwise the modified array that fits the required block size is returned. The array size must be mltiple of the block size.
Bytes that are missing to the last full block are filled cyclically with the original bytes from teh beginning.
Parameters
byteArray Original byte array provided for the algorithm.
algorithm Symmetric algorithm that is used for encryption/decryption. Object is used to query and eventually set the block sizes.
truncateIfLarger If true then the byte array is truncated to the block size if it is larger than it.
Warning: this can only be done with the key and initialization vector, but not with data!!
Returns
An array of bytes that is of valid size for the algorithm.
If the original initialization vector size matches the required one, the array is unmodified.
If the original array is not a multiple of block size, it is padded by its initial bytes until the desired length.
static byte [] IG.Crypto.UtilCrypto.PadToSymmetricAlgorithmBlocksizeZero (byte[] byteArray, SymmetricAlgorithm algorithm, bool truncateIfLarger = false) inline static
For the specified symmetric encryption algorithm, this function takes the specified byte array and checks if the array is of valid size. If yes then the unmodified array is returned, otherwise the modified array that fits the required block size is returned. The array size must be mltiple of the block size.
Bytes that are missing to the last full block are filled cyclically with the original bytes from teh beginning.
Parameters
byteArray Original byte array provided for the algorithm.
algorithm Symmetric algorithm that is used for encryption/decryption. Object is used to query and eventually set the block sizes.
truncateIfLarger If true then the byte array is truncated to the block size if it is larger than it.
Warning: this can only be done with the key and initialization vector, but not with data!!
Returns
An array of bytes that is of valid size for the algorithm.
If the original initialization vector size matches the required one, the array is unmodified.
If the original array is not a multiple of block size, it is padded by its initial bytes until the desired length.
static byte [] IG.Crypto.UtilCrypto.GetValidSymmetricAlgorithmKey (byte[] key, SymmetricAlgorithm algorithm) inline static
For the specified symmetric encryption algorithm, this function takes the specified key and checks if the key is of valid size. If yes then the unmodified key is returned, otherwise the modified key that fits the required size is returned.
Parameters
key Original key provided for the algorithm.
algorithm Symmetric algorithm that is used for encryption/decryption. Object is used to query and eventually set the key sizes.
Returns
A key that is of valid size for the algorithm.
If the original key size matches the required one, the key is unmodified.
If the original key is larger than the required one, the first bytes of the provided key are used in the returned key.
If the provided key is smaller than the erquired key size then bytes in the returned key are cyclically repeated bytes from the original key.
static byte [] IG.Crypto.UtilCrypto.GetValidSymmetricAlgorithmIV (byte[] IV, SymmetricAlgorithm algorithm) inline static
For the specified symmetric encryption algorithm, this function takes the specified initialization vector and checks if the vector is of valid size. If yes then the unmodified IV is returned, otherwise the modified IV that fits the required size is returned.
Parameters
IV Original initialization vector provided for the algorithm.
algorithm Symmetric algorithm that is used for encryption/decryption. Object is used to query and eventually set the initialization vector sizes (i.e., the block sizes).
Returns
An initialization vector that is of valid size for the algorithm (i.e. is of the same size as block size).
If the original key size matches the required one, the IV is unmodified.
If the original IV is larger than the required one, the first bytes of the provided IV are used in the returned IV.
If the provided key is smaller than the erquired IV size (i.e. block size) then bytes in the returned IV are cyclically repeated bytes from the original IV.
static int IG.Crypto.UtilCrypto.GetLargestSymmetricAlgorithmKeySize (SymmetricAlgorithm algorithm) inline static
Returns the largest possible key siye, in bits, for the spcified symmetric encryption algorithm.
Parameters
algorithm Algorithm whose largest possible key size is returned.
static int IG.Crypto.UtilCrypto.SetLargestSymmetricAlgorithmKeySize (SymmetricAlgorithm algorithm) inline static private
On the specified symmetric encryption algorythm, sets the largest possible key size, in bits, for the spcified symmetric encryption algorithm.
Parameters
algorithm Algorithm whose largest possible key size is returned.
Returns
Actual key size on the algorithm after the operation (should be the largest possible key).
static int IG.Crypto.UtilCrypto.GetLargestSymmetricAlgorithmBlockSize (SymmetricAlgorithm algorithm) inline static
Returns the largest possible block siye, in bits, for the spcified symmetric encryption algorithm.
Parameters
algorithm Algorithm whose largest possible block size is returned.
static int IG.Crypto.UtilCrypto.SetLargestSymmetricAlgorithmBlockSize (SymmetricAlgorithm algorithm) inline static private
On the specified symmetric encryption algorithm, sets the largest possible block size, in bits, for the spcified symmetric encryption algorithm.
Parameters
algorithm Algorithm whose largest possible block size is set.
Returns
Actual block size on the algorithm after the operation (should be the largest possible block size).
static void IG.Crypto.UtilCrypto.PrepareSymmetricAllgorithmBasic (byte[] passwordBytes, byte[] passwordSalt, ref byte[] key, ref byte[] IV, SymmetricAlgorithmType algorithmType, ref SymmetricAlgorithm algorithm, PasswordAlgorithmType pwdType = PasswordAlgorithmType.Default, int pwdNumIterations = 1000, bool useLargestKey = false, bool useLargestBlock = false) inline static
Prepares the symmetric algorithm, initialization vector, and key before encryption or decryption takes place.
Creates the algorithm if necessary, changes algorithm parameters (such as key size) when applicable, and checks and corrects the key and initialization vector, if necessary.
Parameters
passwordBytes Password used.
passwordSalt Password salt used.
key Key used. Method checks that the key is of correct size and corrects it when necessary.
IV Initialization vector used. Method checks that it is consistent with the algorithm's block size and corrects it if it is not.
algorithmType Algorithm type. If the algorithm is not specified then it is created anew according to this parameter.
algorithm Algorithm used for encryption. If null it is created. If specified then it is checked that it corresponds to the type specified by algorithmType .
pwdType Type of the password algorrithm.
pwdNumIterations Number of iterations for the password transformation algortgm.
useLargestKey If true then algorithm parameters are set (if necessary) in such a way that the largest hey length supported by the algorithm is used.
useLargestBlock If true then algorithm parameters are set (if necessary) in such a way that the largest hey length supported by the algorithm is used.
References IG.Crypto.PasswordAlgorithmBase.GetBytes(), IG.Crypto.UtilCrypto.GetPasswordAlgorithm(), IG.Crypto.PasswordAlgorithmBase.Init(), IG.Crypto.ConstCrypto.MinPasswordLength, IG.Crypto.ConstCrypto.MinPasswordSaltLength, and IG.Crypto.UtilCrypto.PasswordAlgorithmTypeToString().
static byte [] IG.Crypto.UtilCrypto.EncryptBasic (byte[] data, byte[] passwordBytes, byte[] passwordSalt, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm = null, byte[] saltBytes = null, PasswordAlgorithmType pwdType = PasswordAlgorithmType.Default, int pwdNumIterations = 1000, bool useLargestKey = false, bool useLargestBlock = false) inline static
Encrypts the specified byte array by a symmetric encryption algorithm and returns encrypted bytes.
If the algorithm is not specified then it is provided by the system, but in this case both the key and the initialization vector must be specified.
If algorithm is specified then the key and initialization vector can be generated by the algorithm and retrieved from the algorithm after the call.
Parameters
data Data to be encrypted.
passwordBytes Password used to generate a secred key used to encrypt the data.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
passwordSalt Password salt, added to the password when transformed.
algorithmType Type of the algorithm used.
algorithm Algoritgm used.
If specified then key and IV can be generated and stored by the algorithm. Algorithm type must correspond to the specified type.
If not specified then it is generated anew.
Parameters
saltBytes Salt that is prepended the data before encryption.
pwdType Type of the algorithm used to transform the password.
pwdNumIterations Number of iteration of the password algoriithm.
useLargestKey If true then algorithm is eventually modified in such a way that it uses the largest possible key size.
useLargestBlock If true then algorithm is eventually modified in such a way that it uses the largest possible block size.
Returns
Encrypted data as byte array.
References IG.Crypto.ConstCrypto.MinPasswordSaltLength.
static byte [] IG.Crypto.UtilCrypto.DecryptBasic (byte[] data, byte[] passwordBytes, byte[] passwordSalt, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm = null, int numSaltBytes = 0, PasswordAlgorithmType pwdType = PasswordAlgorithmType.Default, int pwdNumIterations = 1000, bool useLargestKey = false, bool useLargestBlock = false) inline static
Decrypts the specified byte array by a symmetric algorithm and returns decrypted data.
If the algorithm is not specified then it is provided by the system, but in this case both the key and the initialization vector must be specified.
If algorithm is specified then the key and initialization vector can be generated by the algorithm and retrieved from the algorithm after the call.
Parameters
data Data to be decrypted.
passwordBytes Password used to generate a secred key used to encrypt the data.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
passwordSalt Password salt, added to the password when transformed.
algorithmType Type of the algorithm used.
algorithm Algoritgm used.
If specified then key and IV can be generated and stored by the algorithm. Algorithm type must correspond to the specified type.
If not specified then it is generated anew.
Parameters
numSaltBytes Length of salt, which must be accounted for when decrypting.
pwdType Password algorithm type.
pwdNumIterations Number of iterations performed by the password algorithm.
useLargestKey If true then algorithm is eventually modified in such a way that it uses the largest possible key size.
useLargestBlock If true then algorithm is eventually modified in such a way that it uses the largest possible block size.
Returns
Decrypted data as byte array.
static string IG.Crypto.UtilCrypto.EncryptStringBasic (string stringToEncrypt, byte[] passwordBytes, byte[] passwordSalt, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm = null, byte[] saltBytes = null, PasswordAlgorithmType pwdType = PasswordAlgorithmType.Default, int pwdNumIterations = 1000, bool useLargestKey = false, bool useLargestBlock = false) inline static
Encrypts the specified string, using the specified symmetric algorithm, key, and initialization vector, and returns the ToBase64 string representation of the encrypted bytes.
Parameters
stringToEncrypt String that is encrypted.
passwordBytes Password used to generate a secred key used to encrypt the data.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
passwordSalt Password salt, added to the password when transformed.
algorithmType Type of the algorithm used for enxryption.
algorithm Agorithm used for encryption. Must be consistend with algorithmType , or null.
saltBytes Salt that is prepended the data before encryption.
pwdType Password algorithm type.
pwdNumIterations Number of iterations performed by the password algorithm.
useLargestKey If true then the algorithm will be modified in such a way that it uses the largest possible key for this kind of algorithm.
useLargestBlock If true then the algorithm will be modified in such a way that it uses the largest possible block for this kind of algorithm.
Returns
Base64 string representation of the encrypted string bytes.
References IG.Crypto.ConstCrypto.MinPasswordSaltLength.
static string IG.Crypto.UtilCrypto.DecryptStringBasic (string cipherText, byte[] passwordBytes, byte[] passwordSalt, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm = null, int numSaltBytes = 0, PasswordAlgorithmType pwdType = PasswordAlgorithmType.Default, int pwdNumIterations = 1000, bool useLargestKey = false, bool useLargestBlock = false) inline static
Derypts the specified string from encryted byte array, using the specified symmetric algorithm, key, and initialization vector.
Parameters
cipherText Base64 string representation of the byte array containing the encrypted original string.
passwordBytes Password used to generate a secred key used to encrypt the data.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
passwordSalt Password salt, added to the password when transformed.
algorithmType Type of the algorithm used.
algorithm Agorithm used for encryption. Must be consistend with algorithmType , or null.
numSaltBytes Length of salt, which must be accounted for when decrypting.
useLargestKey If true then the algorithm will be modified in such a way that it uses the largest possible key for this kind of algorithm.
pwdType Password algorithm that henerated key from the password.
pwdNumIterations Number fo iteration of the password algorithm.
useLargestBlock If true then the algorithm will be modified in such a way that it uses the largest possible block for this kind of algorithm.
Returns
Original string, provided that input arguments are correct.
static void IG.Crypto.UtilCrypto.EncryptFileBasic (string inputFilePath, string outputFilePath, byte[] passwordBytes, byte[] passwordSalt, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm = null, byte[] saltBytes = null, int bufferSize = ConstCrypto.FileBufferSize, PasswordAlgorithmType pwdType = PasswordAlgorithmType.Default, int pwdNumIterations = 1000, bool useLargestKey = false, bool useLargestBlock = false) inline static
Encrypts the data from the specified input file by a symmetric encryption algorithm and writes encrypted data to the specified output file.
If the algorithm is not specified then it is provided by the system, but in this case both the key and the initialization vector must be specified.
If algorithm is specified then the key and initialization vector can be generated by the algorithm and retrieved from the algorithm after the call.
Parameters
inputFilePath Path to the input file from which data is encrypted. The file must be exist and be readable.
outputFilePath Path to the output file to which encrypted data is written. The file must be writable and will be wasOverwritten if it already exists.
passwordBytes Password, as byte array.
passwordSalt Password salt, as byte array.
algorithmType Type of the algorithm used.
algorithm Algoritgm used.
If specified then key and IV can be generated and stored by the algorithm. Algorithm type must correspond to the specified type.
If not specified then it is generated anew.
Parameters
saltBytes Salt, as byte array.
bufferSize Size of the intermediate buffer through which we read from input and write to output stream. Buffer makes possible to work on very large streams efficiently.
pwdType Password algorithm type.
pwdNumIterations Number of iterations performed by the password algorithm.
useLargestKey If true then algorithm is eventually modified in such a way that it uses the largest possible key size.
useLargestBlock If true then algorithm is eventually modified in such a way that it uses the largest possible block size.
Returns
Encrypted data as byte array.
References IG.Crypto.ConstCrypto.MinPasswordSaltLength.
static void IG.Crypto.UtilCrypto.DecryptFileBasic (string inputFilePath, string outputFilePath, byte[] passwordBytes, byte[] passwordSalt, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm = null, int numSaltBytes = 0, int bufferSize = ConstCrypto.FileBufferSize, PasswordAlgorithmType pwdType = PasswordAlgorithmType.Default, int pwdNumIterations = 1000, bool useLargestKey = false, bool useLargestBlock = false) inline static
Decrypts the data from the specified input file by a symmetric encryption algorithm and writes decrypted data to the specified output file.
If the algorithm is not specified then it is provided by the system, but in this case both the key and the initialization vector must be specified.
If algorithm is specified then the key and initialization vector can be generated by the algorithm and retrieved from the algorithm after the call.
Parameters
inputFilePath Path to the input file from which data is encrypted. The file must be exist and be readable.
outputFilePath Path to the output file to which encrypted data is written. The file must be writable and will be wasOverwritten if it already exists.
passwordBytes Password, as byte array.
passwordSalt Password salt, as byte array.
algorithmType Type of the algorithm used.
algorithm Algoritgm used.
If specified then key and IV can be generated and stored by the algorithm. Algorithm type must correspond to the specified type.
If not specified then it is generated anew.
Parameters
numSaltBytes Length of salt, which must be accounted for when decrypting.
bufferSize Size of the intermediate buffer through which we read from input and write to output stream.
Parameters
pwdType Password algorithm type.
pwdNumIterations Number of iterations performed by the password algorithm.
Buffer makes possible to work on very large streams efficiently.
useLargestKey If true then algorithm is eventually modified in such a way that it uses the largest possible key size.
useLargestBlock If true then algorithm is eventually modified in such a way that it uses the largest possible block size.
Returns
Encrypted data as byte array.
static void IG.Crypto.UtilCrypto.PrepareSymmetricAllgorithmPlain (ref byte[] key, ref byte[] IV, SymmetricAlgorithmType algorithmType, ref SymmetricAlgorithm algorithm, bool useLargestKey = false, bool useLargestBlock = false) inline static
Prepares the symmetric algorithm, initialization vector, and key before encryption or decryption takes place.
Creates the algorithm if necessary, changes algorithm parameters (such as key size) when applicable, and checks and corrects the key and initialization vector, if necessary.
Parameters
key Key used. Method checks that the key is of correct size and corrects it when necessary.
IV Initialization vector used. Method checks that it is consistent with the algorithm's block size and corrects it if it is not.
algorithmType Algorithm type. If the algorithm is not specified then it is created anew according to this parameter.
algorithm Algorithm used for encryption. If null it is created. If specified then it is checked that it corresponds to the type specified by algorithmType .
useLargestKey If true then algorithm parameters are set (if necessary) in such a way that the largest hey length supported by the algorithm is used.
useLargestBlock If true then algorithm parameters are set (if necessary) in such a way that the largest hey length supported by the algorithm is used.
Referenced by IG.Test.EncDec.Decrypt(), IG.Crypto.UtilCrypto.DecryptPlain(), IG.Test.EncDec.Encrypt(), and IG.Crypto.UtilCrypto.EncryptPlain().
static void IG.Crypto.UtilCrypto.EncryptPlain (byte[] data, Stream outputStream, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm = null, byte[] saltBytes = null, bool useLargestKey = false, bool useLargestBlock = false) inline static
Encrypts the specified byte array by a symmetric encryption algorithm and writes encrypted data to the specified output stream that must be open for writing.
If the algorithm is not specified then it is provided by the system, but in this case both the key and the initialization vector must be specified.
If algorithm is specified then the key and initialization vector can be generated by the algorithm and retrieved from the algorithm after the call.
Parameters
data Data to be encrypted.
outputStream Stream to which decrypted data is written. The stream must be open for writing and should be closed by the caller of this method.
key Secret key used to encrypt the data.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
IV Initialization vector. It can be public and stored together with encrypted data, but it is advised that the vecor is randomly generated for each session or each encryption.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
algorithmType Type of the algorithm used.
algorithm Algoritgm used.
If specified then key and IV can be generated and stored by the algorithm. Algorithm type must correspond to the specified type.
If not specified then it is generated anew.
Parameters
saltBytes Salt that is prepended the data before encryption.
useLargestKey If true then algorithm is eventually modified in such a way that it uses the largest possible key size.
useLargestBlock If true then algorithm is eventually modified in such a way that it uses the largest possible block size.
Returns
Encrypted data as byte array.
References IG.Crypto.UtilCrypto.PrepareSymmetricAllgorithmPlain().
Referenced by IG.Crypto.CryptoManager.AppEncryptSymmetricAll().
static void IG.Crypto.UtilCrypto.DecryptPlain (byte[] data, Stream outputStream, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm = null, int numSaltBytes = 0, bool useLargestKey = false, bool useLargestBlock = false) inline static
Decrypts the specified byte array by a symmetric algorithm and writes decrypted data to the specified output stream.
If the algorithm is not specified then it is provided by the system, but in this case both the key and the initialization vector must be specified.
If algorithm is specified then the key and initialization vector can be generated by the algorithm and retrieved from the algorithm after the call.
Parameters
data Data to be decrypted.
outputStream Stream to which decrypted data is written. The stream must be open for writing and should be closed by the caller of this method.
key Secret key used to decrypt the data.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
IV Initialization vector. It can be public and stored together with encrypted data, but it is advised that the vecor is randomly generated for each session or each encryption.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
algorithmType Type of the algorithm used.
algorithm Algoritgm used.
If specified then key and IV can be generated and stored by the algorithm. Algorithm type must correspond to the specified type.
If not specified then it is generated anew.
Parameters
numSaltBytes Length of salt, which must be accounted for when decrypting.
useLargestKey If true then algorithm is eventually modified in such a way that it uses the largest possible key size.
useLargestBlock If true then algorithm is eventually modified in such a way that it uses the largest possible block size.
Returns
Decrypted data as byte array.
References IG.Crypto.UtilCrypto.PrepareSymmetricAllgorithmPlain().
Referenced by IG.Crypto.CryptoManager.AppEncryptSymmetricAll().
static byte [] IG.Crypto.UtilCrypto.EncryptPlain (byte[] data, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm = null, byte[] saltBytes = null, bool useLargestKey = false, bool useLargestBlock = false) inline static
Encrypts the specified byte array by a symmetric encryption algorithm and returns encrypted bytes.
If the algorithm is not specified then it is provided by the system, but in this case both the key and the initialization vector must be specified.
If algorithm is specified then the key and initialization vector can be generated by the algorithm and retrieved from the algorithm after the call.
Parameters
data Data to be encrypted.
key Secret key used to encrypt the data.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
IV Initialization vector. It can be public and stored together with encrypted data, but it is advised that the vecor is randomly generated for each session or each encryption.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
algorithmType Type of the algorithm used.
algorithm Algoritgm used.
If specified then key and IV can be generated and stored by the algorithm. Algorithm type must correspond to the specified type.
If not specified then it is generated anew.
Parameters
saltBytes Salt that is prepended the data before encryption.
useLargestKey If true then algorithm is eventually modified in such a way that it uses the largest possible key size.
useLargestBlock If true then algorithm is eventually modified in such a way that it uses the largest possible block size.
Returns
Encrypted data as byte array.
static byte [] IG.Crypto.UtilCrypto.DecryptPlain (byte[] data, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm = null, int numSaltBytes = 0, bool useLargestKey = false, bool useLargestBlock = false) inline static
Decrypts the specified byte array by a symmetric algorithm and returns decrypted data.
If the algorithm is not specified then it is provided by the system, but in this case both the key and the initialization vector must be specified.
If algorithm is specified then the key and initialization vector can be generated by the algorithm and retrieved from the algorithm after the call.
Parameters
data Data to be decrypted.
key Secret key used to decrypt the data.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
IV Initialization vector. It can be public and stored together with encrypted data, but it is advised that the vecor is randomly generated for each session or each encryption.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
algorithmType Type of the algorithm used.
algorithm Algoritgm used.
If specified then key and IV can be generated and stored by the algorithm. Algorithm type must correspond to the specified type.
If not specified then it is generated anew.
Parameters
useLargestKey If true then algorithm is eventually modified in such a way that it uses the largest possible key size.
numSaltBytes Length of salt, which must be accounted for when decrypting.
useLargestBlock If true then algorithm is eventually modified in such a way that it uses the largest possible block size.
Returns
Decrypted data as byte array.
static string IG.Crypto.UtilCrypto.EncryptStringPlain (string stringToEncrypt, byte[] key, byte[] initializationVector, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm = null, byte[] saltBytes = null, bool useLargestKey = false, bool useLargestBlock = false) inline static
Encrypts the specified string, using the specified symmetric algorithm, key, and initialization vector, and returns the Base64 string representation of the encrypted bytes.
Parameters
stringToEncrypt String that is encrypted.
key Secret key used in encryption.
initializationVector Initialization vector used in encryption. Necessary for stronger encryption (othervise repeating input blocks would cause repeating output blocks).
algorithmType Type of the algorithm used.
algorithm Agorithm used for encryption. Must be consistend with algorithmType , or null.
saltBytes Salt that is prepended the data before encryption.
useLargestKey If true then the algorithm will be modified in such a way that it uses the largest possible key for this kind of algorithm.
useLargestBlock If true then the algorithm will be modified in such a way that it uses the largest possible block for this kind of algorithm.
Returns
Base64 string representation of the encrypted string bytes.
Referenced by IG.Crypto.CryptoManager.AppEncryptSymmetricAll(), IG.Test.TestCrypto.SymmetricEncryptionStringBase(), IG.Test.TestCrypto.SymmetricEncryptionStringPlain(), and IG.Test.TestCrypto.SymmetricEncryptionStringPlainRandom().
static string IG.Crypto.UtilCrypto.DecryptStringPlain (string cipherText, byte[] key, byte[] initializationVector, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm = null, int numSaltBytes = 0, bool useLargestKey = false, bool useLargestBlock = false) inline static
Derypts the specified string from encryted byte array, using the specified symmetric algorithm, key, and initialization vector.
Parameters
cipherText Base64 string representation of the byte array containing the encrypted original string.
key Secret key used in encryption.
initializationVector Initialization vector used in encryption. Necessary for stronger encryption (othervise repeating input blocks would cause repeating output blocks).
algorithmType Type of the algorithm used.
algorithm Agorithm used for encryption. Must be consistend with algorithmType , or null.
numSaltBytes Length of salt, which must be accounted for when decrypting.
useLargestKey If true then the algorithm will be modified in such a way that it uses the largest possible key for this kind of algorithm.
useLargestBlock If true then the algorithm will be modified in such a way that it uses the largest possible block for this kind of algorithm.
Returns
Original string, provided that input arguments are correct.
Referenced by IG.Crypto.CryptoManager.AppEncryptSymmetricAll(), IG.Test.TestCrypto.SymmetricEncryptionStringBase(), IG.Test.TestCrypto.SymmetricEncryptionStringPlain(), and IG.Test.TestCrypto.SymmetricEncryptionStringPlainRandom().
static byte [] IG.Crypto.UtilCrypto.EncryptStringToBytesPlain (string stringToEncrypt, byte[] key, byte[] initializationVector, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm = null, byte[] saltBytes = null, bool useLargestKey = false, bool useLargestBlock = false) inline static
Encrypts the specified string to a byte array, using the specified symmetric algorithm, key, and initialization vector.
Parameters
stringToEncrypt String that is encrypted.
key Secret key used in encryption.
initializationVector Initialization vector used in encryption. Necessary for stronger encryption (othervise repeating input blocks would cause repeating output blocks).
algorithmType Type of the algorithm used.
algorithm Agorithm used for encryption. Must be consistend with algorithmType , or null.
saltBytes Salt that is prepended the data before encryption.
useLargestKey If true then the algorithm will be modified in such a way that it uses the largest possible key for this kind of algorithm.
useLargestBlock If true then the algorithm will be modified in such a way that it uses the largest possible block for this kind of algorithm.
Returns
Array of bytes containing encrypted string.
Referenced by IG.Test.TestCrypto.SymmetricEncryptionStringToBytesPlain().
static string IG.Crypto.UtilCrypto.DecryptStringFromBytesPlain (byte[] cipherText, byte[] key, byte[] initializationVector, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.Default, SymmetricAlgorithm algorithm = null, int numSaltBytes = 0, bool useLargestKey = false, bool useLargestBlock = false) inline static
Derypts the specified string from encryted byte array, using the specified symmetric algorithm, key, and initialization vector.
Parameters
cipherText Byte array containing the encrypted original string.
key Secret key used in encryption.
initializationVector Initialization vector used in encryption. Necessary for stronger encryption (othervise repeating input blocks would cause repeating output blocks).
algorithmType Type of the algorithm used.
algorithm Agorithm used for encryption. Must be consistend with algorithmType , or null.
numSaltBytes Length of salt, which must be accounted for when decrypting.
useLargestKey If true then the algorithm is modified (if necessary) in such a way that the largest possible key size is used.
useLargestBlock If true then the algorithm is modified in such a way that the largest possible block size is used.
Returns
Original string, provided that input arguments are correct.
Referenced by IG.Test.TestCrypto.SymmetricEncryptionStringToBytesPlain().
static void IG.Crypto.UtilCrypto.EncryptPlain (Stream inputStream, Stream outputStream, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm = null, byte[] saltBytes = null, int bufferSize = ConstCrypto.FileBufferSize, bool useLargestKey = false, bool useLargestBlock = false) inline static
Encrypts the data from the specified input stream by a symmetric encryption algorithm and writes encrypted data to the specified output stream.
If the algorithm is not specified then it is provided by the system, but in this case both the key and the initialization vector must be specified.
If algorithm is specified then the key and initialization vector can be generated by the algorithm and retrieved from the algorithm after the call.
Parameters
inputStream Input stream from which data is encrypted. The stream must be open for reading and should be closed by the caller of this method.
outputStream Stream to which encrypted data is written. The stream must be open for writing and should be closed by the caller of this method.
key Secret key used to encrypt the data.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
IV Initialization vector. It can be public and stored together with encrypted data, but it is advised that the vecor is randomly generated for each session or each encryption.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
algorithmType Type of the algorithm used.
algorithm Algoritgm used.
If specified then key and IV can be generated and stored by the algorithm. Algorithm type must correspond to the specified type.
If not specified then it is generated anew.
Parameters
saltBytes Salt added to encrypted data.
bufferSize Size of the intermediate buffer through which we read from input and write to output stream. Buffer makes possible to work on very large streams efficiently.
useLargestKey If true then algorithm is eventually modified in such a way that it uses the largest possible key size.
useLargestBlock If true then algorithm is eventually modified in such a way that it uses the largest possible block size.
Returns
Encrypted data as byte array.
References IG.Crypto.UtilCrypto.PrepareSymmetricAllgorithmPlain().
static void IG.Crypto.UtilCrypto.DecryptPlain (Stream inputStream, Stream outputStream, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm = null, int numSaltBytes = 0, int bufferSize = ConstCrypto.FileBufferSize, bool useLargestKey = false, bool useLargestBlock = false) inline static
Decrypts the data from the specified input stream by a symmetric encryption algorithm and writes decrypted data to the specified output stream.
If the algorithm is not specified then it is provided by the system, but in this case both the key and the initialization vector must be specified.
If algorithm is specified then the key and initialization vector can be generated by the algorithm and retrieved from the algorithm after the call.
Parameters
inputStream Input stream from which data is decrypted. The stream must be open for reading and should be closed by the caller of this method.
outputStream Stream to which decrypted data is written. The stream must be open for writing and should be closed by the caller of this method.
key Secret key used to encrypt the data.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
IV Initialization vector. It can be public and stored together with encrypted data, but it is advised that the vecor is randomly generated for each session or each encryption.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
algorithmType Type of the algorithm used.
algorithm Algorithm used.
If specified then key and IV can be generated and stored by the algorithm. Algorithm type must correspond to the specified type.
If not specified then it is generated anew.
Parameters
numSaltBytes Length of the salt that is added to the encrypted data.
bufferSize Size of the intermediate buffer through which we read from input and write to output stream. Buffer makes possible to work on very large streams efficiently.
useLargestKey If true then algorithm is eventually modified in such a way that it uses the largest possible key size.
useLargestBlock If true then algorithm is eventually modified in such a way that it uses the largest possible block size.
Returns
Encrypted data as byte array.
References IG.Crypto.UtilCrypto.PrepareSymmetricAllgorithmPlain().
static void IG.Crypto.UtilCrypto.EncryptFilePlain (string inputFilePath, string outputFilePath, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm = null, byte[] saltBytes = null, int bufferSize = ConstCrypto.FileBufferSize, bool useLargestKey = false, bool useLargestBlock = false) inline static
Encrypts the data from the specified input file by a symmetric encryption algorithm and writes encrypted data to the specified output file.
If the algorithm is not specified then it is provided by the system, but in this case both the key and the initialization vector must be specified.
If algorithm is specified then the key and initialization vector can be generated by the algorithm and retrieved from the algorithm after the call.
Parameters
inputFilePath Path to the input file from which data is encrypted. The file must be exist and be readable.
outputFilePath Path to the output file to which encrypted data is written. The file must be writable and will be wasOverwritten if it already exists.
key Secret key used to encrypt the data.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
IV Initialization vector. It can be public and stored together with encrypted data, but it is advised that the vecor is randomly generated for each session or each encryption.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
algorithmType Type of the algorithm used.
algorithm Algoritgm used.
If specified then key and IV can be generated and stored by the algorithm. Algorithm type must correspond to the specified type.
If not specified then it is generated anew.
Parameters
saltBytes Salt that is added to data before encryption.
bufferSize Size of the intermediate buffer through which we read from input and write to output stream. Buffer makes possible to work on very large streams efficiently.
useLargestKey If true then algorithm is eventually modified in such a way that it uses the largest possible key size.
useLargestBlock If true then algorithm is eventually modified in such a way that it uses the largest possible block size.
Returns
Encrypted data as byte array.
Referenced by IG.Crypto.CryptoManager.AppEncryptSymmetricAll(), and IG.Test.TestCrypto.SymmetricEncryptionFilesPlain().
static void IG.Crypto.UtilCrypto.DecryptFilePlain (string inputFilePath, string outputFilePath, byte[] key, byte[] IV, SymmetricAlgorithmType algorithmType = SymmetricAlgorithmType.None, SymmetricAlgorithm algorithm = null, int numSaltBytes = 0, int bufferSize = ConstCrypto.FileBufferSize, bool useLargestKey = false, bool useLargestBlock = false) inline static
Decrypts the data from the specified input file by a symmetric encryption algorithm and writes decrypted data to the specified output file.
If the algorithm is not specified then it is provided by the system, but in this case both the key and the initialization vector must be specified.
If algorithm is specified then the key and initialization vector can be generated by the algorithm and retrieved from the algorithm after the call.
Parameters
inputFilePath Path to the input file from which data is encrypted. The file must be exist and be readable.
outputFilePath Path to the output file to which encrypted data is written. The file must be writable and will be wasOverwritten if it already exists.
key Secret key used to encrypt the data.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
IV Initialization vector. It can be public and stored together with encrypted data, but it is advised that the vecor is randomly generated for each session or each encryption.
If not specified but algorithm is specified, it is randomly generated and stored by the algorithm.
Parameters
algorithmType Type of the algorithm used.
algorithm Algoritgm used.
If specified then key and IV can be generated and stored by the algorithm. Algorithm type must correspond to the specified type.
If not specified then it is generated anew.
Parameters
numSaltBytes Length of the salt that is added to the data befoe encryption.
bufferSize Size of the intermediate buffer through which we read from input and write to output stream. Buffer makes possible to work on very large streams efficiently.
useLargestKey If true then algorithm is eventually modified in such a way that it uses the largest possible key size.
useLargestBlock If true then algorithm is eventually modified in such a way that it uses the largest possible block size.
Returns
Encrypted data as byte array.
Referenced by IG.Crypto.CryptoManager.AppEncryptSymmetricAll(), and IG.Test.TestCrypto.SymmetricEncryptionFilesPlain().
static AsymmetricAlgorithmType [] IG.Crypto.UtilCrypto.GetAsymmetricAlgorithmTypes () inline static
Returns all asymmetric encryption algorithm types contained in the enumeration AsymmetricAlgorithmType
References IG.Lib.Util.LockGlobal.
Referenced by IG.Test.TestCrypto.AsymmetricAlgorithmTypes().
static AsymmetricAlgorithmType IG.Crypto.UtilCrypto.GetAsymmetricAlgorithmType (string typeString) inline static
Returns the AsymmetricAlgorithmType value corresponding to the specified string.
Parameters
typeString String that represents the asymmetric encryption algorithm type.
Referenced by IG.Test.TestCrypto.AsymmetricAlgorithmTypes(), IG.Crypto.CryptoManager.ParseCommandlineParameters(), and IG.Crypto.CryptoManager.ResolveAsymParameters().
static AsymmetricAlgorithmType IG.Crypto.UtilCrypto.GetAsymmetricAlgorithmType (AsymmetricAlgorithm algorithmObject) inline static
Returns the asymmetric encryption algorithm type, i.e. an enumeration of type SymmetricAlgorithmType, for the specified asymmetric encryption algorithm object.
Parameters
algorithmObject Asymmetric algorithm object for which type enumeration is returned.
Returns
The type enumeration corresponding to the specified algorithm, or 0 (None) if the algorithm is null or not contained in the enumeration.
static string IG.Crypto.UtilCrypto.AsymmetricAlgorithmTypeToString (AsymmetricAlgorithmType algorithmType) inline static
Returns standard string representation of the specified asymmetric encryption algorithm type.
Parameters
algorithmType Asymmetric encryption algorithm type whose string representation is returned.
Referenced by IG.Test.TestCrypto.AsymmetricAlgorithmTypes(), IG.Crypto.UtilCrypto.DeleteKeyInCsp(), IG.Crypto.UtilCrypto.GetAsymmetricAlgorithm(), and IG.Crypto.UtilCrypto.PrepareAymmetricAllgorithmBasic().
static AsymmetricAlgorithm IG.Crypto.UtilCrypto.GetAsymmetricEncryptionAlgorithm (AsymmetricAlgorithmType algorithmType) inline static
Returns the appropriate asymmetric algorithm according to the specified hashRet type, or null if the type is not recognized or the method is not implemented for that type.
Parameters
algorithmType Specification of the asymmetric encryption algorithm type.
static bool IG.Crypto.UtilCrypto.IsCorrectAsymmetricEncryptionAlgorithm (AsymmetricAlgorithm algorithm, AsymmetricAlgorithmType algorithmType) inline static
Returns true if the specified asymmetric encryption algorithm corresponds the type specification, false otherwise.
If the specified algorithm is null or the specified type is unknown then false is returned.
Parameters
algorithmType Specification of the asymmetric encryption algorithm type.
algorithm Algorithm that is checked for type correctness.
static int IG.Crypto.UtilCrypto.GetLargestAsymmetricAlgorithmKeySize (AsymmetricAlgorithm algorithm) inline static
Returns the largest possible key size, in bits, for the spcified symmetric encryption algorithm.
Parameters
algorithm Algorithm whose largest possible key size is returned.
static int IG.Crypto.UtilCrypto.SetLargestAsymmetricAlgorithmKeySize (AsymmetricAlgorithm algorithm) inline static private
On the specified asymmetric encryption algorithm, sets the largest possible key size, in bits, for the corresponding asymmetric encryption algorithm.
Parameters
algorithm Algorithm whose largest possible key size is returned.
Returns
Actual key size on the algorithm after the operation (should be the largest possible key).
static byte [] IG.Crypto.UtilCrypto.GetValidAsymmetricAlgorithmKey (byte[] key, AsymmetricAlgorithm algorithm, bool useLargestKey = false) inline static
For the specified asymmetric encryption algorithm, this function takes the specified key and checks if the key is of valid size. If yes then the unmodified key is returned, otherwise the modified key that fits the required size is returned.
Parameters
key Original key provided for the algorithm.
algorithm Asymmetric algorithm that is used for encryption/decryption. Object is used to query and eventually set the key sizes.
useLargestKey If true then the specified algorithm is first modified in such a way that it uses the maximal possible key length for the specific kind of algorithm.
Returns
A key that is of valid size for the algorithm.
If the original key size matches the required one, the key is unmodified.
If the original key is larger than the required one, the first bytes of the provided key are used in the returned key.
If the provided key is smaller than the erquired key size then bytes in the returned key are cyclically repeated bytes from the original key.
static CspProviderFlags IG.Crypto.UtilCrypto.GetCspProviderFlags (string flagString) inline static
Returns the value of the CspProviderFlags enum corresponding to the specified string.
Parameters
flagString String representation of the flag value of type CspProviderFlags
Returns
CspProviderFlags value corresponding to string parameter.
Referenced by IG.Crypto.CryptoManager.ParseCommandlineParameters().
static string IG.Crypto.UtilCrypto.CspProviderFlagsToString (CspProviderFlags flags) inline static
Returns standard string representation of the CspProviderFlags enumeration.
Parameters
flags Asymmetric encryption algorithm type whose string representation is returned.
static string IG.Crypto.UtilCrypto.ToString (CspKeyContainerInfo keyInfo, int numIndent = 0) inline static
Creates and returns a string that presents the key information contained in the argument keyInfo .
Parameters
keyInfo Information about the key pair that is returned in string form.
numIndent Indentation.
Referenced by IG.Crypto.CryptoManager.AppAsymExportKey(), IG.Crypto.CryptoManager.AppAsymKeyInfo(), IG.Crypto.CryptoManager.AppAsymTest(), IG.Crypto.CryptoManager.AppCertInfo(), and IG.Crypto.UtilCrypto.ToString().
static string IG.Crypto.UtilCrypto.ToString (RSACryptoServiceProvider alg) inline static
Creates and returns a string containing information about the specified RSA algorithm.
Parameters
alg Algorithm for which information is returned.
References IG.Crypto.UtilCrypto.ToString().
static string IG.Crypto.UtilCrypto.ToString (DSACryptoServiceProvider alg) inline static
Creates and returns a string containing information about the specified DSA algorithm.
Parameters
alg Algorithm for which information is returned.
References IG.Lib.Util.CollectionToString(), and IG.Crypto.UtilCrypto.ToString().
static string IG.Crypto.UtilCrypto.ToString (AsymmetricAlgorithm alg) inline static
Creates and returns a string containing information about the specified RSA algorithm.
Parameters
alg Algorithm for which information is returned.
static string IG.Crypto.UtilCrypto.ToString (X509Certificate certificate) inline static
Returns a readable string representation of the specified certificate.
To obtain a detailed access to certificate data, the object is first used to create a more advanced X509Certificate2 type of object (which has a contructor that takes its base class) and then string representation is created from thi object, which offers better access to internal data.
Parameters
certificate Certificate whose string representaion is returned.
static string IG.Crypto.UtilCrypto.GetSimpleName (X509Certificate2 cert) inline static
Returns simple name of the specified cerrtificate.
Parameters
cert Certificate whose simple name should be returned.
Referenced by IG.Crypto.UtilCrypto.AddCertificateToStore(), IG.Crypto.CryptoManager.AppAddCertificate(), IG.Crypto.UtilCrypto.DeleteCertificateFromStore(), IG.Crypto.UtilCrypto.GetCertificate(), and IG.Crypto.UtilCrypto.GetCertificateStoreDescription().
static string IG.Crypto.UtilCrypto.ToString (X509Certificate2 cert) inline static
Returns a readable string representation of the specified certificate.
Parameters
cert Certificate whose string representaion is returned.
static string IG.Crypto.UtilCrypto.GetCertificateStoreDescription (int outputLevel = 0, string storeName = null, int storeLocation = (int) StoreLocation.CurrentUser | (int) StoreLocation.LocalMachine) inline static
Returns a string that contains human readable description of certificate stores.
See also: https://msdn.microsoft.com/en-us/library/System.Security.Cryptography.X509Certificates.X509Store%28v=vs.110%29.aspx
Parameters
outputLevel Whether certificates contained in stores should also be listed (only by names).
storeName Name of the certificate store whose information is included in the string.
storeLocation Indicates the location of certificte store: 1 - current user, 2 - local machine, 0 or 3 - both.
Enumeration StoreLocation can be conveniently used (eventually combined as flags with the OR operator) to define the location.
References IG.Crypto.UtilCrypto.GetSimpleName().
Referenced by IG.Crypto.CryptoManager.AppCertStoreInfo().
static void IG.Crypto.UtilCrypto.GetCertificateStores (ref IList< X509Store > stores, bool clearAtBeginning = true, string storeName = null, int storeLocation = (int) StoreLocation.CurrentUser | (int) StoreLocation.LocalMachine) inline static
Adds to the specified list all persistent certificate stores that match the criteria specified by parameters.
Parameters
stores A list to which the matching certificate stores are added.
If it references a variable that is null, the list is created.
If the clearAtBeginning parameter is true then the list is cleared before operation.
Parameters
storeName Name of the certificate store whose information is included in the string.
storeLocation Indicates the location of certificte store: 1 - current user, 2 - local machine, 0 or 3 - both.
Enumeration StoreLocation can be conveniently used (eventually combined as flags with the OR operator) to define the location.
Parameters
clearAtBeginning If true (which is default value) then the list is cleared before the operation proceeds.
Referenced by IG.Crypto.UtilCrypto.AddCertificateToStore(), and IG.Crypto.UtilCrypto.DeleteCertificateFromStore().
static void IG.Crypto.UtilCrypto.CloseCertificateStores (IList< X509Store > stores) inline static
Closes all certificate stores on the list.
Parameters
stores List of certificate stores that are closed.
Referenced by IG.Crypto.UtilCrypto.AddCertificateToStore(), and IG.Crypto.UtilCrypto.DeleteCertificateFromStore().
static X509Certificate2 IG.Crypto.UtilCrypto.GetCertificate (string privateKeyPassword = null, string certificateFilePath = null, string certificateName = null, string storeName = null, int storeLocation = (int) StoreLocation.CurrentUser | (int) StoreLocation.LocalMachine) inline static
Obtains and returns the certificate specifid by parameters.
Parameters
privateKeyPassword Password to access the certificate's private key.
certificateFilePath Name of the file containing the certificate.
certificateName Name of the certificate from certificate store.
storeName Certificate store frrom which certificate is to be obtained.
storeLocation Indicates location of the certificate store: 1 for current user, 2 for local machine, 0 or 3 for any location, 4 for none.
Returns
Returns the certificate that corresponds to parameters, or null if such a certificate can not be located.
References IG.Crypto.UtilCrypto.GetSimpleName().
Referenced by IG.Crypto.CryptoManager.AppAddCertificate(), and IG.Crypto.CryptoManager.AppCertInfo().
static string IG.Crypto.UtilCrypto.AddCertificateToStore (X509Certificate2 certificate, out bool skipped, out bool overwritten, string certificateStoreName, int storeLocation = (int) StoreLocation.CurrentUser, bool isForceOverwrites = false, bool isSkipOverwrites = false) inline static
Adds a certificate to the specified certificate store.
Parameters
certificate Certificate to be added to the store.
skipped Output flag informing whether addition has been wasSkipped (to prevent an overwrite).
overwritten Output flag informing whether existing certificate has been wasOverwritten (either due to automatic overwrites specified by parameter isForceOverwrites , or upon user confirmation).
certificateStoreName Name of the certificate store to which the certificate is added.
storeLocation Location where certificate is added: 1 - current user, 2 - local machine.
isForceOverwrites If true then overwrites are forcced without asking for user confirmation. In such a case, parameter overwritten is set to true.
isSkipOverwrites If true then addition is automatically wasSkipped if it would overwrite an existing certificate. In such a case, parameter skipped is set to true.
Returns
Hash value of the public key of the added certificate, or 0 if certificate has not been added.
References IG.Crypto.UtilCrypto.CloseCertificateStores(), IG.Crypto.UtilCrypto.GetAsymmetricalgorithmHash(), IG.Crypto.UtilCrypto.GetCertificateStores(), IG.Crypto.UtilCrypto.GetSimpleName(), and IG.Lib.UtilConsole.Read().
Referenced by IG.Crypto.CryptoManager.AppAddCertificate().
static string IG.Crypto.UtilCrypto.DeleteCertificateFromStore (out bool skipped, out bool deleted, string certificateName, string storeName, int storeLocation = (int) StoreLocation.CurrentUser, bool isForceDeletes = false, bool isSkipDeletes = false) inline static
Deletes the specified certificate to the specified certificate store.
Parameters
skipped Output flag informing whether addition has been skipped (to prevent deletion).
deleted Output flag informing whether existing certificate has been deleeed (either due to automatic deletions specified by parameter isForceDeletes , or upon user confirmation).
certificateName Name of the certificate to be deleted from the store.
storeName Name of the certificate store to which the certificate is added.
storeLocation Location where certificate is added: 1 - current user, 2 - local machine.
isForceDeletes If true then deletes are forcced without asking for user confirmation. In such a case, parameter deleted is set to true.
isSkipDeletes If true then addition is automatically wasSkipped if it would overwrite an existing certificate. In such a case, parameter skipped is set to true.
Returns
Hash value of the public key of the added certificate, or 0 if certificate has not been added.
References IG.Crypto.UtilCrypto.CloseCertificateStores(), IG.Crypto.UtilCrypto.GetAsymmetricalgorithmHash(), IG.Crypto.UtilCrypto.GetCertificateStores(), IG.Crypto.UtilCrypto.GetSimpleName(), and IG.Lib.UtilConsole.Read().
Referenced by IG.Crypto.CryptoManager.AppRemoveCertificate().
static string IG.Crypto.UtilCrypto.GetAsymmetricalgorithmHash (AsymmetricAlgorithm algorithm, bool includePrivate = false, bool skipPrivateIfNotExportable = false, HashType hashType = HashType.SHA1) inline static
Returns a hash value for the specified Asymmetric algorithm, which depends on algorithm keys.
The hash vlaue can be used to verify that two algorithm object used actually have the same keys. This is especially useful when encryption is performed on one machine and decryption is performed on another.
See also: RSAParameters", https://msdn.microsoft.com/en-us/library/system.security.cryptography.rsaparameters%28v=vs.110%29.aspx
Parameters
algorithm Algorithm for which keys' hashRet is returned.
includePrivate Whether private parameters of the asymmetric key contained in the algorithm are taken into account while hassing.
Default is false and it is highly recommended to use only false for this parameter.
Usually using only public parameters should be enough, because it is very unlikely that any key pair would have the same public parameters but different private parameters.
Parameters
skipPrivateIfNotExportable If true then private parameters are not taken into account when they are not exportable to XML, even when includePrivate = true. If false then exception is thrown in the case that includePrivate is true but private parameters of the keys are not exportable to XML.
Default is false.
Parameters
hashType Type of the hashing algorithm. Default is HashType.SHA1 and it is recommended that this is not changed.
References IG.Crypto.UtilCrypto.GetStringHashHex(), IG.Crypto.RSA, and IG.Lib.Util.ToHexString().
Referenced by IG.Crypto.UtilCrypto.AddCertificateToStore(), IG.Crypto.CryptoManager.AppAsymExportKey(), IG.Crypto.CryptoManager.AppAsymKeyInfo(), IG.Crypto.CryptoManager.AppCertInfo(), and IG.Crypto.UtilCrypto.DeleteCertificateFromStore().
static int IG.Crypto.UtilCrypto.GetMaximalAsymmetricTextLength (AsymmetricAlgorithm alg) inline static
Returns the maximal size of a byte array that can be encrypted by using the specified asymmetric algoritm.
Parameters
alg Asymmetric algorithm that would be used for encryption.
Returns
Referenced by IG.Crypto.CryptoManager.AppAsymExportKey(), IG.Crypto.CryptoManager.AppAsymKeyInfo(), and IG.Crypto.CryptoManager.AppCertInfo().
static bool IG.Crypto.UtilCrypto.AsymEncryptionDecryptionTest (string testString, AsymmetricAlgorithm algEnc, AsymmetricAlgorithm algDec = null) inline static
Tests whether the specified asymmetric algorithm(s) correctly encrypts/decrypts the specified string.
Returns true if the test passes and false if not.
The specified string must be short enough.
Parameters
testString String to be encrypted and decrypted.
Must be short enough in order to be suitable for asymmetric encryption / decryption.
If null or empty string then false is returned.
Parameters
algEnc Asymmetric algorithm object used for encryption (and also for decryption if the second algorithm object is not specified).
If null then false is returned.
Parameters
algDec Asymmetric algorithm used for decryption.
If null then the first algorithm object is used for both encryption and decryption.
Possibility of having two algorithm objects makes possible to test situations when one object contains only the public key and a different object contains the private key.
Returns
True if the secified asymmetric algorithms correctly encrypt/decrypt the specified string, false otherwise.
Referenced by IG.Crypto.CryptoManager.AppAsymExportKey(), IG.Crypto.CryptoManager.AppAsymKeyInfo(), IG.Crypto.CryptoManager.AppAsymTest(), and IG.Crypto.CryptoManager.AppCertInfo().
static bool IG.Crypto.UtilCrypto.AsymEncryptionDecryptionTest (string testString, out string errorString, AsymmetricAlgorithm algEnc, AsymmetricAlgorithm algDec = null) inline static
Tests whether the specified asymmetric algorithm(s) correctly encrypts/decrypts the specified string.
Returns true if the test passes and false if not.
The specified string must be short enough.
Parameters
testString String to be encrypted and decrypted.
Must be short enough in order to be suitable for asymmetric encryption / decryption.
If null or empty string then false is returned.
Parameters
errorString String variable where error message is stored, in case that exception is thrown during encryption/decryption. If no exception is thrown then the variable attains value null.
algEnc Asymmetric algorithm object used for encryption (and also for decryption if the second algorithm object is not specified).
If null then false is returned.
Parameters
algDec Asymmetric algorithm used for decryption.
If null then the first algorithm object is used for both encryption and decryption.
Possibility of having two algorithm objects makes possible to test situations when one object contains only the public key and a different object contains the private key.
Returns
True if the secified asymmetric algorithms correctly encrypt/decrypt the specified string, false otherwise.
static bool IG.Crypto.UtilCrypto.AsymEncryptionDecryptionTest (int length, AsymmetricAlgorithm algEnc, AsymmetricAlgorithm algDec = null) inline static
Tests whether the specified asymmetric algorithm(s) correctly encrypts/decrypts a random byte array of the specified size.
Returns true if the test passes (encrypted and then decrypted bytes equal to original) and false if not.
The specified length must me smaller and equal to the value returned by GetMaximalAsymmetricTextLength for the test to pass (beside the encryption/decryption capability and correctness of operaton).
Parameters
length Length of the random byte array that is encrypted / decrypted.
algEnc Asymmetric algorithm object used for encryption (and also for decryption if the second algorithm object is not specified).
If null then false is returned.
Parameters
algDec Asymmetric algorithm used for decryption.
If null then the first algorithm object is used for both encryption and decryption.
Possibility of having two algorithm objects makes possible to test situations when one object contains only the public key and a different object contains the private key.
Returns
True if the secified asymmetric algorithms correctly encrypt/decrypt a random byte array of the specified length, false otherwise.
static bool IG.Crypto.UtilCrypto.AsymEncryptionDecryptionTest (int length, out string errorString, AsymmetricAlgorithm algEnc, AsymmetricAlgorithm algDec = null) inline static
Tests whether the specified asymmetric algorithm(s) correctly encrypts/decrypts a random byte array of the specified size.
Returns true if the test passes (encrypted and then decrypted bytes equal to original) and false if not.
The specified length must me smaller and equal to the value returned by GetMaximalAsymmetricTextLength for the test to pass (beside the encryption/decryption capability and correctness of operaton).
Parameters
length Length of the random byte array to be encrypted and decrypted.
Must be short enough in order to be suitable for asymmetric encryption / decryption. Maximal length can be obtained by the GetMaximalAsymmetricTextLength method.
If null or empty string then false is returned.
Parameters
errorString String variable where error message is stored, in case that exception is thrown during encryption/decryption. If no exception is thrown then the variable attains value null.
algEnc Asymmetric algorithm object used for encryption (and also for decryption if the second algorithm object is not specified).
If null then false is returned.
Parameters
algDec Asymmetric algorithm used for decryption.
If null then the first algorithm object is used for both encryption and decryption.
Possibility of having two algorithm objects makes possible to test situations when one object contains only the public key and a different object contains the private key.
Returns
True if the secified asymmetric algorithms correctly encrypt/decrypt a random byte array of the specified length, false otherwise.
static AsymmetricAlgorithm IG.Crypto.UtilCrypto.GetAsymmetricAlgorithm (AsymmetricAlgorithmType algorithmType, string containerName = null, string xmlString = null, CspProviderFlags flags = CspProviderFlags.NoFlags, string certificateFilePath = null, string certificateName = null, string certStore = null) inline static
Creates (if necessary) and returns a new asymmetric algorithm whose keys are either created or obtained through arguments.
Parameters
algorithmType Type of the asymmetric algorithm that is returned.
containerName Name of the key container where the keys persist. If not specified then keys are not persistent.
xmlString If not null, this string must contain properly formed XML form which the keys are read.
flags Flags of type CspProviderFlags used in crypto service parameters when algorithm object is created. If the value is CspProviderFlags.NoFlags then flags are not used.
certificateFilePath Name of the certificate file from which algorithm keys are obtained.
certificateName Name of the certificate from one of the standard certificate stores from which the algorithm keys are obtained.
certStore Certificate store from which certificate named certificateName is obtained. If null then all standard stores are searched for.
References IG.Crypto.UtilCrypto.AsymmetricAlgorithmTypeToString().
Referenced by IG.Crypto.CryptoManager.AppAsymTest(), and IG.Crypto.CryptoManager.ResolveAsymParameters().
static void IG.Crypto.UtilCrypto.DeleteKeyInCsp (AsymmetricAlgorithmType algorithmType, string containerName) inline static
Deletes the asymmetric algorithm keys from the specified key container.
Parameters
algorithmType Type of the asymmetric algorithm for which the keys are deleted.
containerName Name of the container from which keys are deleted.
References IG.Crypto.UtilCrypto.AsymmetricAlgorithmTypeToString().
Referenced by IG.Crypto.CryptoManager.AppAsymTest().
static void IG.Crypto.UtilCrypto.PrepareAymmetricAllgorithmBasic (AsymmetricAlgorithmType algorithmType, ref AsymmetricAlgorithm algorithm, string containerName = null, string xmlString = null, CspProviderFlags flags = CspProviderFlags.NoFlags, bool useLargestKey = false) inline static
References IG.Crypto.UtilCrypto.AsymmetricAlgorithmTypeToString().
static string IG.Crypto.UtilCrypto.EncryptStringAsymShort (string stringToEncrypt, AsymmetricAlgorithm algorithm, AsymmetricAlgorithmType algorithmType = AsymmetricAlgorithmType.None) inline static
Referenced by IG.Crypto.CryptoManager.AppAsymTest().
static string IG.Crypto.UtilCrypto.DecryptStringAsymShort (string cipherText, AsymmetricAlgorithm algorithm, AsymmetricAlgorithmType algorithmType = AsymmetricAlgorithmType.None) inline static
Referenced by IG.Crypto.CryptoManager.AppAsymTest().
static byte [] IG.Crypto.UtilCrypto.EncryptAsymShort (byte[] originalBytes, AsymmetricAlgorithm algorithm, AsymmetricAlgorithmType algorithmType = AsymmetricAlgorithmType.None) inline static
Referenced by IG.Crypto.CryptoManager.AppAsymTest().
static byte [] IG.Crypto.UtilCrypto.DecryptAsymShort (byte[] originalBytes, AsymmetricAlgorithm algorithm, AsymmetricAlgorithmType algorithmType = AsymmetricAlgorithmType.None) inline static
Referenced by IG.Crypto.CryptoManager.AppAsymTest().
static byte [] IG.Crypto.UtilCrypto.EncryptAsymShort (byte[] originalBytes, AsymmetricAlgorithmType algorithmType = AsymmetricAlgorithmType.None, AsymmetricAlgorithm algorithm = null, string containerName = null, string xmlString = null, CspProviderFlags flags = CspProviderFlags.NoFlags, bool useLargestKey = false) inline static
static byte [] IG.Crypto.UtilCrypto.DecryptAsymShort (byte[] originalBytes, AsymmetricAlgorithmType algorithmType = AsymmetricAlgorithmType.None, AsymmetricAlgorithm algorithm = null, string containerName = null, string xmlString = null, CspProviderFlags flags = CspProviderFlags.NoFlags, bool useLargestKey = false) inline static
static string IG.Crypto.UtilCrypto.IgGetSaltSuffix (int whichSalt) inline static
Returns the specified standard IGLib salt string.
There are several uses of salt strings:
- they are appended or prepended to passwords before hashing.
Parameters
whichSalt Index of the standard IGLib salt string.
Returns
The standard IGLib salt string corresponding to the specified index.
Referenced by IG.Test.TestCryptoIGLib.IGLibSaltOutOfRange1(), IG.Test.TestCryptoIGLib.IGLibSaltOutOfRange2(), and IG.Test.TestCryptoIGLib.IGLibSaltOutOfRange3().
static int IG.Crypto.UtilCrypto.IgGetNumSaltSuffices () inline static
Returns the number of standard IGLib salt strings.
Returns
The number of standard IGLib salt strings.
Referenced by IG.Test.TestCryptoIGLib.IGLibSaltOutOfRange2().
Member Data Documentation
int IG.Crypto.UtilCrypto._outputLevel = 1 static private
object IG.Crypto.UtilCrypto._lockStatic = null static private
PasswordAlgorithmType [] IG.Crypto.UtilCrypto._passwordAlgorithmTypes = null static private
PasswordAlgorithmBase IG.Crypto.UtilCrypto._passwordAlgorithmNone = null static private
RNGCryptoServiceProvider IG.Crypto.UtilCrypto._rng = null static private
HashType [] IG.Crypto.UtilCrypto._hashTypes = null static private
SymmetricAlgorithmType [] IG.Crypto.UtilCrypto._symmetricTypes = null static private
AsymmetricAlgorithmType [] IG.Crypto.UtilCrypto._asymmetricTypes = null static private
bool IG.Crypto.UtilCrypto._isUsed_fOAEP1 = false static private
string [] IG.Crypto.UtilCrypto._igLibLongSaltSuffices static private
Initial value:
= new string[] {
            "0586297593_hc94kglh9kfjhtgk04vnbtheli9f84_IGLib_by_Igor_Gresovnik_k8ktkg9mgrn48vg94f9bkjd8_79384659674",
            "74073659573_l9hfnci85vj7fl58f799aj5kla8s9_IGLib_by_Igor_Gresovnik_b098jdk87jflg274kglmng02_73608109847"
        }
An array of standard IGLib salt suffices.
Warnings:
- Hard coding salts is generally not OK, it is important that salts are random and salts can be stored together with enxrypted data.
- This array should not be modifiable.
- Elements of this array may not change over time. Only new elements can be added.
Property Documentation
int IG.Crypto.UtilCrypto.OutputLevel static get
Output level for static methods of the current utility class.
Warning: This field can be removed at any time.
object IG.Crypto.UtilCrypto.LockStatic static get
Locking object for static methods and properties of this class.
Read-only, safely provided on demand (using Util.LockGlobal when created).
Encoding IG.Crypto.UtilCrypto.StringEncoding static get
Gets the character encoding that is used for calculating hashes of strings.
About thread safety (Enncoding classes should be stateless):
http://stackoverflow.com/questions/3024384/thread-safety-and-system-text-encoding-in-c-sharp
Referenced by IG.Crypto.CryptoManager.AppAsymTest(), IG.Crypto.CryptoManager.AppEncryptSymmetricAll(), IG.Script.ScriptAppBase.CryptoFunctionTimeKeyGeneration_OLD_TO_DELETE_LATER(), IG.Crypto.CryptoManager.ResolvePasswordParameters(), and IG.Test.TestCrypto.SymmetricEncryptionStringBase().
RNGCryptoServiceProvider IG.Crypto.UtilCrypto.Rng static get private
Object used to generate random bytes.
Object is created on demand (layzy evaluation). Ony one object is used through appllication lifetime.
bool IG.Crypto.UtilCrypto.IsUsed_fOAEP static get
Whether to perform direct RSA encryption using OAEP (optimal asymmetric encryption padding - only available on computers running MS Windows XP or later).
To do:
Check whether this works in Mono.
The documentation for this class was generated from the following file:
iglib/igbase/utilities/UtilCrypto.cs