IGLib: _Test Class Reference
_Test Class Reference
Public Member Functions
delegate bool TestDelegate (bool silent)
delegate bool TestDelegate (bool silent)
Static Public Member Functions
static bool call_unittest (int seed, TestDelegate test, ref int sticky)
static int Main (string[] args)
static bool call_unittest (int seed, TestDelegate seq_test, TestDelegate smp_test, bool use_smp, ref int sticky)
static int Main (string[] args)
Member Function Documentation
delegate bool _Test.TestDelegate (bool silent)
Referenced by call_unittest(), and Main().
static bool _Test.call_unittest (int seed, TestDelegate test, ref int sticky) inline static
References alglib.math.rndobject.
Referenced by Main().
static int _Test.Main (string[] args) inline static
References call_unittest(), alglib.testablasunit.testablas(), alglib.testalglibbasicsunit.testalglibbasics(), alglib.testautogkunit.testautogk(), alglib.testbasestatunit.testbasestat(), alglib.testbdssunit.testbdss(), alglib.testbdsvdunit.testbdsvd(), alglib.testblasunit.testblas(), alglib.testchebyshevunit.testchebyshev(), alglib.testconvunit.testconv(), alglib.testcorrunit.testcorr(), alglib.testcqmodelsunit.testcqmodels(), alglib.testcreflectionsunit.testcreflections(), TestDelegate(), alglib.testdensesolverunit.testdensesolver(), alglib.testdforestunit.testdforest(), alglib.testevdunit.testevd(), alglib.testfblsunit.testfbls(), alglib.testfftunit.testfft(), alglib.testfhtunit.testfht(), alglib.testfiltersunit.testfilters(), alglib.testgammafuncunit.testgammafunc(), alglib.testgkqunit.testgkq(), alglib.testgqunit.testgq(), alglib.testhblasunit.testhblas(), alglib.testhermiteunit.testhermite(), alglib.testhqrndunit.testhqrnd(), alglib.testidwintunit.testidwint(), alglib.testinverseupdateunit.testinverseupdate(), alglib.testkmeansunit.testkmeans(), alglib.testlaguerreunit.testlaguerre(), alglib.testldaunit.testlda(), alglib.testlegendreunit.testlegendre(), alglib.testlincgunit.testlincg(), alglib.testlinlsqrunit.testlinlsqr(), alglib.testlinminunit.testlinmin(), alglib.testlinregunit.testlinreg(), alglib.testlsfitunit.testlsfit(), alglib.testmatgenunit.testmatgen(), alglib.testmatinvunit.testmatinv(), alglib.testmcpdunit.testmcpd(), alglib.testminbleicunit.testminbleic(), alglib.testmincgunit.testmincg(), alglib.testminlbfgsunit.testminlbfgs(), alglib.testminlmunit.testminlm(), alglib.testminqpunit.testminqp(), alglib.testmlpeunit.testmlpe(), alglib.testmlptrainunit.testmlptrain(), alglib.testnearestneighborunit.testnearestneighbor(), alglib.testnlequnit.testnleq(), alglib.testnormestimatorunit.testnormestimator(), alglib.testodesolverunit.testodesolver(), alglib.testortfacunit.testortfac(), alglib.testpcaunit.testpca(), alglib.testpolintunit.testpolint(), alglib.testpsplineunit.testpspline(), alglib.testratintunit.testratint(), alglib.testrbfunit.testrbf(), alglib.testrcondunit.testrcond(), alglib.testreflectionsunit.testreflections(), alglib.testsafesolveunit.testsafesolve(), alglib.testsblasunit.testsblas(), alglib.testschurunit.testschur(), alglib.testsparseunit.testsparse(), alglib.testspdgevdunit.testspdgevd(), alglib.testspline1dunit.testspline1d(), alglib.testspline2dunit.testspline2d(), alglib.testspline3dunit.testspline3d(), alglib.testsvdunit.testsvd(), alglib.testtrfacunit.testtrfac(), alglib.testtrlinsolveunit.testtrlinsolve(), alglib.testtsortunit.testtsort(), and alglib.testxblasunit.testxblas().
delegate bool _Test.TestDelegate (bool silent)
static bool _Test.call_unittest (int seed, TestDelegate seq_test, TestDelegate smp_test, bool use_smp, ref int sticky) inline static
References alglib.math.rndobject, and TestDelegate().
static int _Test.Main (string[] args) inline static
References alglib.testablasunit._pexec_testablas(), alglib.testalglibbasicsunit._pexec_testalglibbasics(), alglib.testautogkunit._pexec_testautogk(), alglib.testbasestatunit._pexec_testbasestat(), alglib.testbdssunit._pexec_testbdss(), alglib.testbdsvdunit._pexec_testbdsvd(), alglib.testblasunit._pexec_testblas(), alglib.testchebyshevunit._pexec_testchebyshev(), alglib.testclusteringunit._pexec_testclustering(), alglib.testconvunit._pexec_testconv(), alglib.testcorrunit._pexec_testcorr(), alglib.testcqmodelsunit._pexec_testcqmodels(), alglib.testcreflectionsunit._pexec_testcreflections(), alglib.testdensesolverunit._pexec_testdensesolver(), alglib.testdforestunit._pexec_testdforest(), alglib.testevdunit._pexec_testevd(), alglib.testfblsunit._pexec_testfbls(), alglib.testfftunit._pexec_testfft(), alglib.testfhtunit._pexec_testfht(), alglib.testfiltersunit._pexec_testfilters(), alglib.testgammafuncunit._pexec_testgammafunc(), alglib.testgkqunit._pexec_testgkq(), alglib.testgqunit._pexec_testgq(), alglib.testhblasunit._pexec_testhblas(), alglib.testhermiteunit._pexec_testhermite(), alglib.testhqrndunit._pexec_testhqrnd(), alglib.testidwintunit._pexec_testidwint(), alglib.testinverseupdateunit._pexec_testinverseupdate(), alglib.testlaguerreunit._pexec_testlaguerre(), alglib.testldaunit._pexec_testlda(), alglib.testlegendreunit._pexec_testlegendre(), alglib.testlincgunit._pexec_testlincg(), alglib.testlinlsqrunit._pexec_testlinlsqr(), alglib.testlinminunit._pexec_testlinmin(), alglib.testlinregunit._pexec_testlinreg(), alglib.testlsfitunit._pexec_testlsfit(), alglib.testmatgenunit._pexec_testmatgen(), alglib.testmatinvunit._pexec_testmatinv(), alglib.testmcpdunit._pexec_testmcpd(), alglib.testminbleicunit._pexec_testminbleic(), alglib.testmincgunit._pexec_testmincg(), alglib.testminlbfgsunit._pexec_testminlbfgs(), alglib.testminlmunit._pexec_testminlm(), alglib.testminqpunit._pexec_testminqp(), alglib.testmlpbaseunit._pexec_testmlpbase(), alglib.testmlpeunit._pexec_testmlpe(), alglib.testmlptrainunit._pexec_testmlptrain(), alglib.testnearestneighborunit._pexec_testnearestneighbor(), alglib.testnlequnit._pexec_testnleq(), alglib.testnormestimatorunit._pexec_testnormestimator(), alglib.testodesolverunit._pexec_testodesolver(), alglib.testortfacunit._pexec_testortfac(), alglib.testpcaunit._pexec_testpca(), alglib.testpolintunit._pexec_testpolint(), alglib.testpsplineunit._pexec_testpspline(), alglib.testratintunit._pexec_testratint(), alglib.testrbfunit._pexec_testrbf(), alglib.testrcondunit._pexec_testrcond(), alglib.testreflectionsunit._pexec_testreflections(), alglib.testsactivesetsunit._pexec_testsactivesets(), alglib.testsafesolveunit._pexec_testsafesolve(), alglib.testsblasunit._pexec_testsblas(), alglib.testschurunit._pexec_testschur(), alglib.testsnnlsunit._pexec_testsnnls(), alglib.testsparseunit._pexec_testsparse(), alglib.testspdgevdunit._pexec_testspdgevd(), alglib.testspline1dunit._pexec_testspline1d(), alglib.testspline2dunit._pexec_testspline2d(), alglib.testspline3dunit._pexec_testspline3d(), alglib.teststestunit._pexec_teststest(), alglib.teststudentttestsunit._pexec_teststudentttests(), alglib.testsvdunit._pexec_testsvd(), alglib.testtrfacunit._pexec_testtrfac(), alglib.testtrlinsolveunit._pexec_testtrlinsolve(), alglib.testtsortunit._pexec_testtsort(), alglib.testxblasunit._pexec_testxblas(), call_unittest(), alglib.smp.cores_count, alglib.smpselftests.runtests(), alglib.testablasunit.testablas(), alglib.testalglibbasicsunit.testalglibbasics(), alglib.testautogkunit.testautogk(), alglib.testbasestatunit.testbasestat(), alglib.testbdssunit.testbdss(), alglib.testbdsvdunit.testbdsvd(), alglib.testblasunit.testblas(), alglib.testchebyshevunit.testchebyshev(), alglib.testclusteringunit.testclustering(), alglib.testconvunit.testconv(), alglib.testcorrunit.testcorr(), alglib.testcqmodelsunit.testcqmodels(), alglib.testcreflectionsunit.testcreflections(), TestDelegate(), alglib.testdensesolverunit.testdensesolver(), alglib.testdforestunit.testdforest(), alglib.testevdunit.testevd(), alglib.testfblsunit.testfbls(), alglib.testfftunit.testfft(), alglib.testfhtunit.testfht(), alglib.testfiltersunit.testfilters(), alglib.testgammafuncunit.testgammafunc(), alglib.testgkqunit.testgkq(), alglib.testgqunit.testgq(), alglib.testhblasunit.testhblas(), alglib.testhermiteunit.testhermite(), alglib.testhqrndunit.testhqrnd(), alglib.testidwintunit.testidwint(), alglib.testinverseupdateunit.testinverseupdate(), alglib.testlaguerreunit.testlaguerre(), alglib.testldaunit.testlda(), alglib.testlegendreunit.testlegendre(), alglib.testlincgunit.testlincg(), alglib.testlinlsqrunit.testlinlsqr(), alglib.testlinminunit.testlinmin(), alglib.testlinregunit.testlinreg(), alglib.testlsfitunit.testlsfit(), alglib.testmatgenunit.testmatgen(), alglib.testmatinvunit.testmatinv(), alglib.testmcpdunit.testmcpd(), alglib.testminbleicunit.testminbleic(), alglib.testmincgunit.testmincg(), alglib.testminlbfgsunit.testminlbfgs(), alglib.testminlmunit.testminlm(), alglib.testminqpunit.testminqp(), alglib.testmlpbaseunit.testmlpbase(), alglib.testmlpeunit.testmlpe(), alglib.testmlptrainunit.testmlptrain(), alglib.testnearestneighborunit.testnearestneighbor(), alglib.testnlequnit.testnleq(), alglib.testnormestimatorunit.testnormestimator(), alglib.testodesolverunit.testodesolver(), alglib.testortfacunit.testortfac(), alglib.testpcaunit.testpca(), alglib.testpolintunit.testpolint(), alglib.testpsplineunit.testpspline(), alglib.testratintunit.testratint(), alglib.testrbfunit.testrbf(), alglib.testrcondunit.testrcond(), alglib.testreflectionsunit.testreflections(), alglib.testsactivesetsunit.testsactivesets(), alglib.testsafesolveunit.testsafesolve(), alglib.testsblasunit.testsblas(), alglib.testschurunit.testschur(), alglib.testsnnlsunit.testsnnls(), alglib.testsparseunit.testsparse(), alglib.testspdgevdunit.testspdgevd(), alglib.testspline1dunit.testspline1d(), alglib.testspline2dunit.testspline2d(), alglib.testspline3dunit.testspline3d(), alglib.teststestunit.teststest(), alglib.teststudentttestsunit.teststudentttests(), alglib.testsvdunit.testsvd(), alglib.testtrfacunit.testtrfac(), alglib.testtrlinsolveunit.testtrlinsolve(), alglib.testtsortunit.testtsort(), and alglib.testxblasunit.testxblas().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs