IGLib: IG.Neural.NeuralApproximatorBaseExt Class Reference
IG.Neural.NeuralApproximatorBaseExt Class Reference
Base class for neural network approximators.
Public Member Functions
NeuralApproximatorBaseExt ()
new void SaveTrainingDataJson_To_delete (string filePath)
Saves network's training data to the specified JSON file. File is owerwritten if it exists.
new void LoadTrainingDataJson_To_Delete (string filePath)
Restores training data from the specified file in JSON format.
Public Member Functions inherited from IG.Num.NeuralApproximatorBase
NeuralApproximatorBase ()
virtual int GetNumNeuronsInHiddenLayer (int whichLayer)
Returns the number of neurons in the specified hidden layer. Hidden layers are those not containing input or output neurons.
virtual void SetNumNeuronsInHiddenLayer (int whichLayer, int numNeurons)
Sets the number of neurons in the specified hidden layer. Hidden layers are those not containing input or output neurons.
virtual void SetHiddenLayers (params int[] numNeurons)
Sets the numbers of neurons in each hidden layer. Can be called with table of integers as argument, kor with variable number of integer parameters. Numbers are set by an array of integers in which each element contains the number of neurons in the corresponding hidden layer (indexed from 0). Hidden layers are those not containing input or output neurons.
abstract void PrepareNetwork ()
Prepares neural network for use. If networks have not yet been created accordinfg to internal data, they are created. If networks are already prepared then this method does nothing.
abstract void CreateNetwork ()
Creates the neural network anew. It the network already exists on the current object, it is discarded.
abstract void ResetNetwork ()
Resets the neural network.
abstract void DestroyNetwork ()
Destroys the neural network.
string GetNetworkFilePath (string fileOrDirectoryPath, int whichNetwork)
Returns an absolute path to the file for storing the specified neural network contained on the current object, with respect to suggested file path and index of the network. The returned path is in the same directory as suggested file path and has the same file extension (if any). If the suggested path represents a directory, then some default suggested path is assumed. If there is only one network then the returned file path is the same as the suggested one (or the same as default file name within the suggested directory, if a directory path is proposed).
void SaveNetwork (string filePath)
Saves the state of the neural network to the specified file. If the file already exists, its contents are overwritten.
void LoadNetwork (string filePath)
Restores neural network from a file where it has been stored before.
void SetTrainingAndVerificationData (SampledDataSet trainingData, SampledDataSet verificationData)
void GetTrainingData (ref SampledDataSet trainingData)
void GetVerificationData (ref SampledDataSet veerificationData)
void GetTrainingAndVerificationData (ref SampledDataSet trainingData, ref SampledDataSet verificationData)
void SaveTrainingDataJson (string filePath)
Saves network's training data to the specified JSON file. File is owerwritten if it exists.
void LoadTrainingDataJson (string filePath)
Restores training data from the specified file in JSON format.
void SetNeuronsInputRange (double min, double max)
Sets the neurons input range. Bounds for all input neurons are set equally.
void SetNeuronsOutputRange (double min, double max)
Sets the neurons output range. Bounds for all output neurons are set equally.
void RecalculateInputDataBounds ()
Recalculates input data bounds by taking into account the training data set of the current object.
void RecalculateOutputDataBounds ()
Recalculates output data bounds by taking into account the training data set of the current object.
void RecalculateDataBounds ()
Recalculates input and output data bounds by taking into account the training data set of the current object.
void RecalculateInputDataBounds (SampledDataSet trainingData)
Recalculates input data bounds by taking into account the specified training data set.
void RecalculateOutputDataBounds (SampledDataSet trainingData)
Recalculates output data bounds by taking into account the specified training data set.
void RecalculateDataBounds (SampledDataSet trainingData)
Recalculates input and output data bounds by taking into account the specified training data set.
void GetErrorsTrainingRms (ref IVector errors)
Calculates the RMS (root mean square) of the errors of output values for the training elements of the training set (this excludes verification points).
void GetErrorsVerificationRms (ref IVector errors)
Calculates the RMS (root mean square) of the errors of output values for the verification elements of the training set.
void GetErrorsTrainingMax (ref IVector errors)
Calculates the maximum absolute errors of output values for the training elements of the training set (this excludes verification points).
void GetErrorsVerificationMax (ref IVector errors)
Calculates the maximum absolute errors of output values for the verification elements of the training set.
void GetErrorsTrainingMeanAbs (ref IVector errors)
Calculates the mean absolute errors of output values for the training elements of the training set (this excludes verification points).
void GetErrorsVerificationMeanAbs (ref IVector errors)
Calculates the mean absolute errors of output values for the verification elements of the training set.
virtual void InvalidateTrainingDependencies ()
Invalidates all data that must be recalculated after training of the network is done. This method is called after training or additional training of the network is performed. Invalidation is achieved throughthe the appropriate flags.
virtual void InvalidateTrainingDataDependencies ()
Invalidates all data that must be re-calculated after training data changes. This method is called after training data is modified. Invalidation is achieved throughthe the appropriate flags.
virtual void InvalidateNetworkDependencies ()
Invalidates all data that must be re-calculated after the neural network itself changes. This method must be called after the internal neural network is re-defined (or are re-defined). Invalidation is achieved throughthe the appropriate flags.
void TrainNetwork (int numEpochs)
Trains neural network wiht the specified data, performing the specified number of epochs.
void TrainNetworkMultiple (int numEpochs, int numIterations)
Performs a specified number of training iterations where the specified number of epochs are run in each iteration.
void TrainNetworkMultiple (int numIterations)
Performs a specified number of training iterations where the prescribed number of epochs (contained in the EpochsInBundle property) are run in each iteration.
virtual void TrainNetwork ()
Trains neural network until stopping criteria are met (in terms of errors and number of epochs performed.
virtual bool StopTrainingCriteriaMet ()
Returns true if the stopping criteria for training is met, with respect to current settings, errors and number of epochs already performed, and false otherwise.
override double CalculateOutput (IVector input, int whichElement)
Calculates and returns the specified output by using the neural network.
override void CalculateOutput (IVector input, int[] indices, ref IVector filteredOutput)
Calculates and returns the required output values corresponding to the specified inputs, by using the current neural network(s).
override string ToString ()
Returns string describing the current neural network approximator.
void SaveTrainingDataJson_To_delete (string filePath)
Saves network's training data to the specified JSON file. File is owerwritten if it exists.
void LoadTrainingDataJson_To_Delete (string filePath)
Restores training data from the specified file in JSON format.
void TestMapping ()
Test back and forth mapping (scaling and shifting) from actual data to data prepared for training, and vice versa (checks if transformed data falls withi the prescribed ranges and if backward transformation yields the same result as forward transformation). Testing is performed on all data from the TrainingData property, including verification elements.
Public Member Functions inherited from IG.Num.VectorApproximatorBase
abstract void CalculateOutput (IVector input, ref IVector output)
Calculates and returns the approximated outputs corresponding to the specified inputs, by using the current vector function approximator.
Public Member Functions inherited from IG.Num.IVectorApproximator
void CalculateOutput (IVector input, ref IVector output)
Calculates and returns the approximated outputs corresponding to the specified inputs, by using the current vector function approximator.
Static Public Member Functions
static new void SaveJson (INeuralApproximator approximator, string filePath)
Saves a neural network approximator to a file. If the neural netwoek is trained then internal state is also saved to a file.
static new void SaveJson (INeuralApproximator approximator, string filePath, bool saveInternalState)
Saves a neural network approximator to a file.
static new void LoadJson (string filePath, ref INeuralApproximator approximatorRestored)
Loads network from a file.
Static Public Member Functions inherited from IG.Num.NeuralApproximatorBase
static void CalculateErrorsRms (int dimOutput, IVector[] prescribed, IVector[] calculated, ref IVector errors)
Calculates error measures - RMS (root mean square) of the differences - for the specified arrays of prescribed and calculated output values in a set of sampling points.
static void CalculateErrorsMeanAbs (int dimOutput, IVector[] prescribed, IVector[] calculated, ref IVector errors)
Calculates error measures - mean absolute value of the differences - for the specified arrays of prescribed and calculated output values in a set of sampling points.
static void CalculateErrorsMax (int dimOutput, IVector[] prescribed, IVector[] calculated, ref IVector errors)
Calculates error measures - maximum absolute value of the differences - for the specified arrays of prescribed and calculated output values in a set of sampling points.
static void SaveJson (INeuralApproximator approximator, string filePath)
Saves a neural network approximator to a file. If the neural netwoek is trained then internal state is also saved to a file.
static void SaveJson (INeuralApproximator approximator, string filePath, bool saveInternalState)
Saves a neural network approximator to a file.
static void LoadJson (string filePath, ref INeuralApproximator approximatorRestored)
Loads network from a file.
static void ExampleSaveNetwork (string directoryPath, string fileName, string internalStateFileName)
Example of saving an entire trained neural network to a file, and then restoring it from a file. Network internal state is saved by the SaveNetwork() method that is specific to the type of the network, therefore it is saved to a separate file. The path of this file is savad with the network approximator object itself. Network is saved only once.
static void ExampleSaveNetwork (string directoryPath, string fileName, string internalStateFileName, bool saveRestored)
Example of saving an entire trained neural network to a file, and then restoring it from a file. Network internal state is saved by the SaveNetwork() method that is specific to the type of the network, therefore it is saved to a separate file. The path of this file is savad with the network approximator object itself. If the saveRestored flag parameter is true then the restored file ia saved again for comparison.
static INeuralApproximator ExampleQuadratic ()
Example demonstrating usage of the neural network approximator. A quadratic function with random coefficients is sampled with enough samples to exactly specify function coefficients, a part of samples is randomly designated as verification points, then neural network is created and trained on training samples, and it is verified how close the obtained approximation matches actual function in verification points.
static INeuralApproximator ExampleQuadratic (int inputLength, int outputLength)
Example demonstrating usage of the neural network approximator. A quadratic function with random coefficients is sampled with enough samples to exactly specify function coefficients, a part of samples is randomly designated as verification points, then neural network is created and trained on training samples, and it is verified how close the obtained approximation matches actual function in verification points.
static INeuralApproximator ExampleQuadratic (int inputLength, int outputLength, int outputLevel, int maxEpochs)
Example demonstrating usage of the neural network approximator. A quadratic function with random coefficients is sampled with enough samples to exactly specify function coefficients, a part of samples is randomly designated as verification points, then neural network is created and trained on training samples, and it is verified how close the obtained approximation matches actual function in verification points.
Additional Inherited Members
Protected Member Functions inherited from IG.Num.NeuralApproximatorBase
void SetRmsToleranceRelstiveToRange ()
Updates the tolerances on RMS errors of outputs according to the relative tolerances (defined by ToleranceRmsRelativeToRange) and the ranges in output data (defined by OutputDataBounds), if both are defined.
void SetMaxToleranceRelstiveToRange ()
Updates the tolerances on max. abs. errors of outputs according to the relative tolerances (defined by ToleranceMaxRelativeToRange) and the ranges in output data (defined by OutputDataBounds), if both are defined.
abstract void PrepareNetworksArray ()
Prepares the networks array (allocates it if necessary) for storing all neural networks of the current object.
abstract void SaveNetworkSpecific (string filePath)
Saves the state of the neural network to the specified file. If the file already exists, its contents are overwritten.
abstract void LoadNetworkSpecific (string filePath)
Restores neural network from a file where it has been stored before.
virtual double MapInput (int componentIndex, double value)
Maps (scales and shifts) and returns specific input value to the value prepared for the corresponding input neuron.
virtual double MapFromNeuralInput (int componentIndex, double value)
Inverse maps (scales and shifts) and returns specific input value back from the neural input to the actual input.
virtual void MapInput (IVector values, ref IVector mappedValues)
Maps (scales and shifts) vector of input values to the vector of neuron inputs.
virtual void MapFromNeuralInput (IVector values, ref IVector mappedValues)
Inverse maps (scales and shifts) vector of neural input values back to the vector of actual inputs.
virtual double MapOutput (int componentIndex, double value)
Maps (scales and shifts) and returns specific output value to the output value of the corresponding output neuron.
virtual double MapFromNeuralOutput (int componentIndex, double value)
Inverse maps (scales and shifts) and returns specific output value back from the neural output to the actual output.
virtual void MapOutput (IVector values, ref IVector mappedValues)
Maps (scales and shifts) vector of output values to the vector of neuron outputs.
virtual void MapFromNeuralOutput (IVector values, ref IVector mappedValues)
Inverse maps (scales and shifts) vector of neural output values back to the vector of actual outputs.
void CalculateTrainingVerificationOutputs (bool calculateTrainingOutputs, bool calculateVerificationOutputs)
Calculates outputs in training points contained in training set, either in training points, in verification points, or both.
void CalculateTrainingOutputs ()
Calculates outputs in training points of the training data set (this excludes verification points).
void CalculateVerificationOutputs ()
Calculates outputs in verification points of the training data set.
virtual void PrepareErrorData (ref int dimOutput, ref IVector[] prescribed, ref IVector[] calculated, bool takeTrainingPoints, bool takeVerificationPoints)
Prepares data for calculation of various error measures over training points or in verification points after training of the neural network(s).
abstract void PrepareInternalTrainingData ()
Prepares internal training data that is needed by the native training algorithm. When overridden, this method must set the InternalTrainingDataPrepared flag to true.
abstract void TrainNetworkSpecific (int numEpochs)
Trains neural network wiht the specified data, performing the specified number of epochs. This method must be implemented in derived classes and is specific to specific network type.
Protected Attributes inherited from IG.Num.NeuralApproximatorBase
const string _defaultNetworkFilename = "network.dat"
double _defaultNeuronMinInput = -2
double _defaultNeuronMaxInput = 2
double _defaultNeuronMinOutput = -1.0
double _defaultNeuronMaxOutput = 1.0
List< IVector > _calculatedOutputs = null
List of calculated outputs in points contained in (all) training data.
bool _calculateVerificationErrors = false
Vector _auxErrors = null
Protected Attributes inherited from IG.Num.VectorApproximatorBase
IVector _lastCalculationInputParameters
Properties inherited from IG.Num.NeuralApproximatorBase
int OutputLevel [get, set]
Level of output printed to console when performing actions.
virtual bool MultipleNetworks [get, set]
Flag indicating whether multiple neural networks are used to approximate multiple outputs (one network for each output)
override int InputLength [get, set]
Gets or sets the number of input neurons.
override int OutputLength [get, set]
Gets or sets the number of output neurons.
virtual int[] NumHiddenNeurons [get, set]
Gets or sets the numbers of neurons in each hidden layer. When setting, contents of array are copied, not only a reference. Numbers are set by an array of integers in which each element contains the number of neurons in the corresponding hidden layer (indexed from 0). Hidden layers are those not containing input or output neurons.
virtual int NumHiddenLayers [get, set]
Gets or sets the number of hidden layers of the neural network (these are layers that don't contain input or output neurons).
bool NetworkPrepared [get, protected set]
Gets a flag telling whether the network is prepared for operation (training and calculation of output).
double SigmoidAlphaValue [get, set]
Alpha value specifying the shape of the activation function.
double LearningRate [get, set]
Gets or sets learning rate.
double Momentum [get, set]
Gets or sets momentum.
int EpochCount [get, protected set]
Number of learning epochs performed up to the current moment.
int MaxEpochs [get, set]
Maximal number of epochs in training.
int EpochsInBundle [get, set]
Number of epochs in a single training bundle. This number of epochs is performed at once when training, without checking convergence criteria between. Larger value means slightly more efficient training (because of less checks) but rougher criteria checks.
IVector ToleranceRms [get, set]
Tolerances on RMS errors of outputs over training points. Training will continue until error becomes below tolerance or until maximal number of epochs is reached. If less or equal than 0 then this tolerance is not taken into account.
IVector ToleranceMax [get, set]
Tolerances on maximal errors of outputs over training points. Training will continue until error becomes below tolerance or until maximal number of epochs is reached. If less or equal than 0 then this tolerance is not taken into account.
IVector ToleranceRmsRelativeToRange [get, set]
Relative tolerances on RMS errors of outputs over training points, relative to the correspoinding ranges of output data.
double ToleranceRmsRelativeToRangeScalar [get, set]
Scalar through which all components of the Relative tolerances on RMS errors of outputs can be set to the same value.
IVector ToleranceMaxRelativeToRange [get, set]
Relative tolerances on max. abs. errors of outputs over training points, relative to the correspoinding ranges of output data.
double ToleranceMaxRelativeToRangeScalar [get, set]
Scalar through which all components of the Relative tolerances on max. abs. errors of outputs can be set to the same value.
List< int > EpochNumbers [get, set]
List of epoch numbers at which convergence data was sampled. Saved after every set of epochs.
List< IVector > ConvergenceErrorsTrainingRmsList [get, set]
Convergence List of RMS errors calculated on training data. Saved after every set of epochs.
List< IVector > ConvergenceErrorsTrainingMaxList [get, set]
Convergence List of Maximum errors calculated on training data. Saved after every set of epochs.
List< IVector > ConvergenceErrorsVerificationRmsList [get, set]
Convergence List of Rms errors calculated on verification data. Saved after every set of epochs.
List< IVector > ConvergenceErrorsVerificationMaxList [get, set]
Convergence List of Maximum errors calculated on verification data. Saved after every set of epochs.
bool SaveConvergenceRms [get, set]
Flag to enable RMS error convergence colection.
string NeuralApproximatorType [get]
Gets string representation of type of the current object. This is used e.g. in deserialization in order to prevent that wrong type of internal representation would be read in.
string NetworkStateFilePath [get, set]
Path where the curren network state has been saved, or null if the current state has not been saved yet. The SaveFile methods takes care that the file path is stored when network state is saved. InvalidateTrainingDependencies() takes care that this file path is set to null if network state has changed after last save.
string NetworkStateRelativePath [get, set]
Relative path where the curren network state has been saved. Auxiliary property used in deserialization. When the whole Neural network approximator is saved to a file, tis path is updated in such a way that it points to the fiele where the network state has been saved, but relative to the path where the whole approximator is saved. This enables restore of the saved network state at a later time, even if the containing directory has moved within the file system or has even been copied to another system.
SampledDataSet TrainingData [get, set]
Gets or sets the training data.
virtual IndexList VerificationIndices [get, set]
Gets or sets indices of training data elements that are used for verification of how precise appeoximation is. These elements are excluded from training of neural network.
virtual IBoundingBox InputDataBounds [get, set]
Bounds on input data, used for scaling from actual input to input used by neural network. Scaling is performed because of the bound codomain and image of activation functions.
virtual IBoundingBox OutputDataBounds [get, set]
Bounds on output data, used for scaling from actual output to output produced by neural network. Scaling is performed because of the bound codomain and image of activation functions.
virtual double InputBoundsSafetyFactor [get, set]
Safety factor by which interval lenghts of input data bounds are enlarged after bounds are automatically determined from the range of input data in the training set. Setter re-calculated the input data bounds and therefore invalidates training data dependencies.
virtual double OutputBoundsSafetyFactor [get, set]
Safety factor by which interval lenghts of output data bounds are enlarged after bounds are automatically determined from the range of output data in the training set. Setter re-calculated the output data bounds and therefore invalidates training data dependencies.
virtual IBoundingBox InputNeuronsRange [get, protected set]
Gets the range in which data should be for input neurons, used for scaling from actual input to input used by neural network. This depends on the activation function.
virtual IBoundingBox OutputNeuronsRange [get, protected set]
Gets the range of the data output from output neurons, used for scaling from actual output to output produced by neural network. This will normally depend on the activation function.
int NumAllTrainingPoints [get]
Gets number of all training points, including verification points.
virtual int NumTrainingPoints [get]
Gets number of training points (this excludes verification points).
virtual int NumVerificationPoints [get]
Gets number of verification points.
bool TrainingOutputsCalculated [get, set]
Whether outputs have been calculated, after last training, in the training points (excluding verification points).
bool VerificationOutputsCalculated [get, set]
Whether outputs have been calculated, after last training, in the training points (excluding verification points).
bool InternalTrainingDataPrepared [get, set]
Gets or sets a flag indicating whether internal training data is prepared. This flag is used internally for signalization between methods that deal with training data.
bool NetworkTrained [get, protected set]
Whether network has been trained since the training data was set.
bool BreakTraining [get, set]
Flags that signalizes (if true) that training should be broken on external request.
bool CalculateVerificationErrors [get, set]
Properties inherited from IG.Num.VectorApproximatorBase
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
abstract int InputLength [get, set]
Gets or sets the number of input parameters.
abstract int OutputLength [get, set]
Gets or sets the number of output values.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Properties inherited from IG.Num.INeuralApproximator
int OutputLevel [get, set]
Level of output printed to console when performing actions.
bool MultipleNetworks [get, set]
Flag indicating whether multiple neural networks are used to approximate multiple outputs (one network for each output)
int[] NumHiddenNeurons [get, set]
Sets the numbers of neurons in each hidden layer. Numbers are set by an array of integers in which each element contains the number of neurons in the corresponding hidden layer (indexed from 0). Hidden layers are those not containing input or output neurons.
int NumHiddenLayers [get, set]
Gets or sets the number of hidden layers of the neural network (these are layers that don't contain input or output neurons).
bool NetworkPrepared [get]
Gets a flag telling whether the network is prepared for operation (training and calculation of output).
double SigmoidAlphaValue [get, set]
Alpha value specifying the shape of the activation function.
double LearningRate [get, set]
Gets or sets learning rate.
double Momentum [get, set]
Gets or sets momentum.
int EpochCount [get]
Number of learning epochs performed up to the current moment.
int MaxEpochs [get, set]
Maximal number of epochs in training.
int EpochsInBundle [get, set]
Number of epochs in a single training bundle. This number of epochs is performed at once when training, without checking convergence criteria between. Larger value means slightly more efficient training (because of less checks) but rougher criteria checks.
IVector ToleranceRms [get, set]
Tolerance over RMS error of output over training points. Training will continue until error becomes below tolerance or until maximal number of epochs is reached. If less or equal than 0 then this tolerance is not taken into account.
IVector ToleranceMax [get, set]
Tolerance on maximal error of output over training points. Training will continue until error becomes below tolerance or until maximal number of epochs is reached. If less or equal than 0 then this tolerance is not taken into account.
IVector ToleranceRmsRelativeToRange [get, set]
Relative tolerances on RMS errors of outputs over training points, relative to the correspoinding ranges of output data.
double ToleranceRmsRelativeToRangeScalar [get, set]
Scalar through which all components of the Relative tolerances on RMS errors of outputs can be set to the same value.
IVector ToleranceMaxRelativeToRange [get, set]
Relative tolerances on max. abs. errors of outputs over training points, relative to the correspoinding ranges of output data.
double ToleranceMaxRelativeToRangeScalar [get, set]
Scalar through which all components of the Relative tolerances on max. abs. errors of outputs can be set to the same value.
bool SaveConvergenceRms [get, set]
Flag to enable Rms error convergence colection. Default is false.
List< int > EpochNumbers [get, set]
List of epoch numbers at which convergence data was sampled. Saved after every set of epochs.
List< IVector > ConvergenceErrorsTrainingRmsList [get, set]
Convergence List of Rms errors calculated on training data. Saved after every set of epochs.
List< IVector > ConvergenceErrorsTrainingMaxList [get, set]
Convergence List of Maximum errors calculated on training data. Saved after every set of epochs.
List< IVector > ConvergenceErrorsVerificationRmsList [get, set]
Convergence List of Rms errors calculated on verification data. Saved after every set of epochs.
List< IVector > ConvergenceErrorsVerificationMaxList [get, set]
Convergence List of Maximum errors calculated on verification data. Saved after every set of epochs.
string NeuralApproximatorType [get]
Gets string representation of type of the current object. This is used e.g. in deserialization in order to prevent that wrong type of internal representation would be read in.
string NetworkStateFilePath [get]
Path where the curren network state has been saved, or null if the current state has not been saved yet. The SaveFile methods takes care that the file path is stored when network state is saved. InvalidateTrainingDependencies() takes care that this file path is set to null if network state has changed after last save.
string NetworkStateRelativePath [get, set]
Relative path where the curren network state has been saved. Auxiliary property used in deserialization. When the whole Neural network approximator is saved to a file, tis path is updated in such a way that it points to the fiele where the network state has been saved, but relative to the path where the whole approximator is saved. This enables restore of the saved network state at a later time, even if the containing directory has moved within the file system or has even been copied to another system.
SampledDataSet TrainingData [get, set]
Gets or sets the training data.
IndexList VerificationIndices [get, set]
Gets or sets indices of training data elements that are used for verification of how precise appeoximation is. These elements are excluded from training of neural network.
IBoundingBox InputDataBounds [get, set]
Bounds on input data, used for scaling from actual input to input used by neural network. Scaling is performed because of the bound codomain and image of activation functions.
IBoundingBox OutputDataBounds [get, set]
Bounds on output data, used for scaling from actual output to output produced by neural network. Scaling is performed because of the bound codomain and image of activation functions.
double InputBoundsSafetyFactor [get, set]
Safety factor by which interval lenghts of input data bounds are enlarged after bounds are automatically determined from the range of input data in the training set. Setter re-calculated the input data bounds and therefore invalidates training data dependencies.
double OutputBoundsSafetyFactor [get, set]
Safety factor by which interval lenghts of output data bounds are enlarged after bounds are automatically determined from the range of output data in the training set. Setter re-calculated the output data bounds and therefore invalidates training data dependencies.
IBoundingBox InputNeuronsRange [get]
Gets the range in which data should be for input neurons, used for scaling from actual input to input used by neural network. This depends on the activation function.
IBoundingBox OutputNeuronsRange [get]
Gets the range of the data output from output neurons, used for scaling from actual output to output produced by neural network. This will normally depend on the activation function.
int NumAllTrainingPoints [get]
Gets number of all training points, including verification points.
int NumTrainingPoints [get]
Gets number of training points (this excludes verification points).
int NumVerificationPoints [get]
Gets number of verification points.
bool NetworkTrained [get]
Whether network has been trained since the training data was set.
bool BreakTraining [get, set]
Flags that signalizes (if true) that training should be broken on external request.
Properties inherited from IG.Num.IVectorApproximator
int InputLength [get, set]
Gets or sets the number of input parameters.
int OutputLength [get, set]
Gets or sets the number of output values.
Detailed Description
Base class for neural network approximators.
IMPORTANT:
This type is defined because of the SaveJson and LoadJson methods, because the basic type NeuralApproximatorBase does not see the NeuralApproximatorNeuron type. With this extended class, saving and loading JSON files also works with this class.
$A Igor Mar11 Jan12;
Constructor & Destructor Documentation
IG.Neural.NeuralApproximatorBaseExt.NeuralApproximatorBaseExt () inline
Member Function Documentation
static new void IG.Neural.NeuralApproximatorBaseExt.SaveJson (INeuralApproximator approximator, string filePath) inline static
Saves a neural network approximator to a file. If the neural netwoek is trained then internal state is also saved to a file.
Parameters
approximator Neural network approximator to be saved.
inputFilePath Path to the file where approximator is saved.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.SolveOpt(), IG.Script.LoadableScriptShellNeuralIT.TrainANN(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainANN().
static new void IG.Neural.NeuralApproximatorBaseExt.SaveJson (INeuralApproximator approximator, string filePath, bool saveInternalState) inline static
Saves a neural network approximator to a file.
Parameters
approximator Neural network approximator to be saved.
inputFilePath Path to the file where approximator is saved.
saveInternalState Specifies whether internal state should be saved, too (only in the case that network is trained).
References IG.Lib.UtilSystem.GetRelativePath(), IG.Num.INeuralApproximator.NetworkStateFilePath, IG.Num.INeuralApproximator.NetworkStateRelativePath, IG.Num.INeuralApproximator.NetworkTrained, and IG.Num.INeuralApproximator.SaveNetwork().
static new void IG.Neural.NeuralApproximatorBaseExt.LoadJson (string filePath, ref INeuralApproximator approximatorRestored) inline static
Loads network from a file.
Parameters
inputFilePath Path to the file.
approximatorRestored Neural approximator that is produced by deserialization.
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.LoadANN(), and IG.Neural.Forms.Old.NeuralParametricDemoOld.LoadANN().
new void IG.Neural.NeuralApproximatorBaseExt.SaveTrainingDataJson_To_delete (string filePath) inline
Saves network's training data to the specified JSON file. File is owerwritten if it exists.
Parameters
inputFilePath Path to the file where training data is saved.
new void IG.Neural.NeuralApproximatorBaseExt.LoadTrainingDataJson_To_Delete (string filePath) inline
Restores training data from the specified file in JSON format.
Parameters
inputFilePath File from which training data is restored.
The documentation for this class was generated from the following file:
shelldev/lib/extended/LibNeuralExt/dependencies_neuron_dot_net/neural_approximator_neuron/NeuralApproximatorBaseExt.cs