IGLib: IG.Lib.ParsableXmlObject.AccummulatedReport Class Reference
IG.Lib.ParsableXmlObject.AccummulatedReport Class Reference
Class used for accummulated error and warning reports for task composed of several steps. This is used when we want to perform the whole task even if some errors occur, and treat all errors and messages after the task is completed.
Public Member Functions
AccummulatedReport (IReporter rep, string location, bool throwExceptionOnErrors)
Constructor.
virtual void Reset ()
Resets the report (remove all erorrs, warnings and info messages)
void AddError (string message)
Adds a new error message to the accummulated report.
void AddWarning (string message)
Adds a new warning message to the accummulated report.
void AddInfo (string message)
Adds a new info message to the accummulated report.
virtual void Report ()
Launches the accummulated report.
Public Attributes
bool ThrowExceptionOnErrors = true
If true then exception is thrown in the case of errors when reporting is launched.
string Location = null
Description of location where the accummulated repord is generated.
Properties
int NumErrors [get]
Get number of errors accummulated on the report.
int NumWarnings [get]
Get number of warnings accummulated on the report.
int NumInfos [get]
Get number of infos accummulated on the report.
IReporter R [get, set]
Gets or sets the reporter used for reporting (if any).
virtual string ErrorString [get]
Concatenated string containing all info strings that exist on this class.
virtual string WarningString [get]
Concatenated string containing all warning strings that exist on this class.
virtual string InfoString [get]
Concatenated string containing all error strings that exist on this class.
virtual string ErrorAndWarningString [get]
Private Member Functions
AccummulatedReport ()
Private Attributes
List< string > _errorStrings = null
List< string > _warningStrings = null
List< string > _infoStrings = null
IReporter _rep = new ReporterConsole()
Detailed Description
Class used for accummulated error and warning reports for task composed of several steps. This is used when we want to perform the whole task even if some errors occur, and treat all errors and messages after the task is completed.
Constructor & Destructor Documentation
IG.Lib.ParsableXmlObject.AccummulatedReport.AccummulatedReport () inline private
IG.Lib.ParsableXmlObject.AccummulatedReport.AccummulatedReport (IReporter rep, string location, bool throwExceptionOnErrors) inline
Constructor.
Parameters
rep Reporter object used for launching reports.
throwExceptionOnErrors If true then reporting methods will throw an exception when report contains errors. It is more common practice not to use tehse methods and launch reports & throw exceptions explicitly.
Member Function Documentation
virtual void IG.Lib.ParsableXmlObject.AccummulatedReport.Reset () inline virtual
Resets the report (remove all erorrs, warnings and info messages)
void IG.Lib.ParsableXmlObject.AccummulatedReport.AddError (string message) inline
Adds a new error message to the accummulated report.
Parameters
message Error message.
Referenced by IG.Lib.MsgObservationEvent.CheckConsistency(), IG.Lib.MsgFinancialTransaction.CheckConsistency(), IG.Lib.DocFindings.CheckConsistency(), and IG.Lib.MsgObervationOrder.CheckConsistency().
void IG.Lib.ParsableXmlObject.AccummulatedReport.AddWarning (string message) inline
Adds a new warning message to the accummulated report.
Parameters
message Warning message.
Referenced by IG.Lib.MsgObervationOrder.CheckConsistency().
void IG.Lib.ParsableXmlObject.AccummulatedReport.AddInfo (string message) inline
Adds a new info message to the accummulated report.
Parameters
message Info message.
Referenced by IG.Lib.MsgObservationEvent.CheckConsistency(), IG.Lib.MsgFinancialTransaction.CheckConsistency(), IG.Lib.DocFindings.CheckConsistency(), and IG.Lib.ParsableXmlObject.CheckConsistency().
virtual void IG.Lib.ParsableXmlObject.AccummulatedReport.Report () inline virtual
Launches the accummulated report.
Parameters
place
rep
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), and IG.Lib.MsgObervationOrder.Read().
Member Data Documentation
List<string> IG.Lib.ParsableXmlObject.AccummulatedReport._errorStrings = null private
List<string> IG.Lib.ParsableXmlObject.AccummulatedReport._warningStrings = null private
List<string> IG.Lib.ParsableXmlObject.AccummulatedReport._infoStrings = null private
IReporter IG.Lib.ParsableXmlObject.AccummulatedReport._rep = new ReporterConsole() private
bool IG.Lib.ParsableXmlObject.AccummulatedReport.ThrowExceptionOnErrors = true
If true then exception is thrown in the case of errors when reporting is launched.
string IG.Lib.ParsableXmlObject.AccummulatedReport.Location = null
Description of location where the accummulated repord is generated.
Property Documentation
int IG.Lib.ParsableXmlObject.AccummulatedReport.NumErrors get
Get number of errors accummulated on the report.
int IG.Lib.ParsableXmlObject.AccummulatedReport.NumWarnings get
Get number of warnings accummulated on the report.
int IG.Lib.ParsableXmlObject.AccummulatedReport.NumInfos get
Get number of infos accummulated on the report.
IReporter IG.Lib.ParsableXmlObject.AccummulatedReport.R get set
Gets or sets the reporter used for reporting (if any).
virtual string IG.Lib.ParsableXmlObject.AccummulatedReport.ErrorString get
Concatenated string containing all info strings that exist on this class.
virtual string IG.Lib.ParsableXmlObject.AccummulatedReport.WarningString get
Concatenated string containing all warning strings that exist on this class.
virtual string IG.Lib.ParsableXmlObject.AccummulatedReport.InfoString get
Concatenated string containing all error strings that exist on this class.
virtual string IG.Lib.ParsableXmlObject.AccummulatedReport.ErrorAndWarningString get
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/LabexBis/MessagesBis.cs