IGLib: NUnit.Engine.TestFilterBuilder Class Reference
NUnit.Engine.TestFilterBuilder Class Reference
Public Member Functions
void AddTest (string fullName)
Add a test to be selected
void SelectWhere (string whereClause)
Specify what is to be included by the filter using a where clause.
TestFilter GetFilter ()
Get a TestFilter constructed according to the criteria specified by the other calls.
Static Private Member Functions
static string XmlEscape (string text)
Private Attributes
List< string > _testList = new List<string>()
string _whereClause
Member Function Documentation
void NUnit.Engine.TestFilterBuilder.AddTest (string fullName) inline
Add a test to be selected
Parameters
fullName The full name of the test, as created by NUnit
Implements NUnit.Engine.ITestFilterBuilder.
Referenced by NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestAndWhereClause(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestSelected(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestSelected_XmlEscape(), and NUnit.Engine.Services.Tests.TestFilterBuilderTests.ThreeTestsSelected().
void NUnit.Engine.TestFilterBuilder.SelectWhere (string whereClause) inline
Specify what is to be included by the filter using a where clause.
Parameters
whereClause A where clause that will be parsed by NUnit to create the filter.
Implements NUnit.Engine.ITestFilterBuilder.
Referenced by NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestAndWhereClause(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.WhereClause(), and NUnit.Engine.Services.Tests.TestFilterBuilderTests.WhereClause_XmlEscape().
TestFilter NUnit.Engine.TestFilterBuilder.GetFilter () inline
Get a TestFilter constructed according to the criteria specified by the other calls.
Returns
A TestFilter.
Implements NUnit.Engine.ITestFilterBuilder.
Referenced by NUnit.Engine.Services.Tests.TestFilterBuilderTests.EmptyFilter(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestAndWhereClause(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestSelected(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestSelected_XmlEscape(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.ThreeTestsSelected(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.WhereClause(), and NUnit.Engine.Services.Tests.TestFilterBuilderTests.WhereClause_XmlEscape().
static string NUnit.Engine.TestFilterBuilder.XmlEscape (string text) inline static private
Member Data Documentation
List<string> NUnit.Engine.TestFilterBuilder._testList = new List<string>() private
string NUnit.Engine.TestFilterBuilder._whereClause private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/TestFilterBuilder.cs