IGLib: alglib.mlpbase Class Reference
alglib.mlpbase Class Reference
Classes
class modelerrors
class multilayerperceptron
class smlpgrad
Static Public Member Functions
static void mlpcreate0 (int nin, int nout, multilayerperceptron network)
static void mlpcreate1 (int nin, int nhid, int nout, multilayerperceptron network)
static void mlpcreate2 (int nin, int nhid1, int nhid2, int nout, multilayerperceptron network)
static void mlpcreateb0 (int nin, int nout, double b, double d, multilayerperceptron network)
static void mlpcreateb1 (int nin, int nhid, int nout, double b, double d, multilayerperceptron network)
static void mlpcreateb2 (int nin, int nhid1, int nhid2, int nout, double b, double d, multilayerperceptron network)
static void mlpcreater0 (int nin, int nout, double a, double b, multilayerperceptron network)
static void mlpcreater1 (int nin, int nhid, int nout, double a, double b, multilayerperceptron network)
static void mlpcreater2 (int nin, int nhid1, int nhid2, int nout, double a, double b, multilayerperceptron network)
static void mlpcreatec0 (int nin, int nout, multilayerperceptron network)
static void mlpcreatec1 (int nin, int nhid, int nout, multilayerperceptron network)
static void mlpcreatec2 (int nin, int nhid1, int nhid2, int nout, multilayerperceptron network)
static void mlpcopy (multilayerperceptron network1, multilayerperceptron network2)
static void mlpserializeold (multilayerperceptron network, ref double[] ra, ref int rlen)
static void mlpunserializeold (double[] ra, multilayerperceptron network)
static void mlprandomize (multilayerperceptron network)
static void mlprandomizefull (multilayerperceptron network)
static void mlpinitpreprocessor (multilayerperceptron network, double[,] xy, int ssize)
static void mlpproperties (multilayerperceptron network, ref int nin, ref int nout, ref int wcount)
static int mlpgetinputscount (multilayerperceptron network)
static int mlpgetoutputscount (multilayerperceptron network)
static int mlpgetweightscount (multilayerperceptron network)
static bool mlpissoftmax (multilayerperceptron network)
static int mlpgetlayerscount (multilayerperceptron network)
static int mlpgetlayersize (multilayerperceptron network, int k)
static void mlpgetinputscaling (multilayerperceptron network, int i, ref double mean, ref double sigma)
static void mlpgetoutputscaling (multilayerperceptron network, int i, ref double mean, ref double sigma)
static void mlpgetneuroninfo (multilayerperceptron network, int k, int i, ref int fkind, ref double threshold)
static double mlpgetweight (multilayerperceptron network, int k0, int i0, int k1, int i1)
static void mlpsetinputscaling (multilayerperceptron network, int i, double mean, double sigma)
static void mlpsetoutputscaling (multilayerperceptron network, int i, double mean, double sigma)
static void mlpsetneuroninfo (multilayerperceptron network, int k, int i, int fkind, double threshold)
static void mlpsetweight (multilayerperceptron network, int k0, int i0, int k1, int i1, double w)
static void mlpactivationfunction (double net, int k, ref double f, ref double df, ref double d2f)
static void mlpprocess (multilayerperceptron network, double[] x, ref double[] y)
static void mlpprocessi (multilayerperceptron network, double[] x, ref double[] y)
static double mlperror (multilayerperceptron network, double[,] xy, int ssize)
static double mlperrorn (multilayerperceptron network, double[,] xy, int ssize)
static int mlpclserror (multilayerperceptron network, double[,] xy, int ssize)
static double mlprelclserror (multilayerperceptron network, double[,] xy, int npoints)
static double mlpavgce (multilayerperceptron network, double[,] xy, int npoints)
static double mlprmserror (multilayerperceptron network, double[,] xy, int npoints)
static double mlpavgerror (multilayerperceptron network, double[,] xy, int npoints)
static double mlpavgrelerror (multilayerperceptron network, double[,] xy, int npoints)
static void mlpgrad (multilayerperceptron network, double[] x, double[] desiredy, ref double e, ref double[] grad)
static void mlpgradn (multilayerperceptron network, double[] x, double[] desiredy, ref double e, ref double[] grad)
static void mlpgradbatch (multilayerperceptron network, double[,] xy, int ssize, ref double e, ref double[] grad)
static void mlpgradnbatch (multilayerperceptron network, double[,] xy, int ssize, ref double e, ref double[] grad)
static void mlphessiannbatch (multilayerperceptron network, double[,] xy, int ssize, ref double e, ref double[] grad, ref double[,] h)
static void mlphessianbatch (multilayerperceptron network, double[,] xy, int ssize, ref double e, ref double[] grad, ref double[,] h)
static void mlpinternalprocessvector (int[] structinfo, double[] weights, double[] columnmeans, double[] columnsigmas, ref double[] neurons, ref double[] dfdnet, double[] x, ref double[] y)
static void mlpalloc (alglib.serializer s, multilayerperceptron network)
static void mlpserialize (alglib.serializer s, multilayerperceptron network)
static void mlpunserialize (alglib.serializer s, multilayerperceptron network)
static int mlpgradsplitcost ()
static int mlpgradsplitsize ()
static void mlpcreate0 (int nin, int nout, multilayerperceptron network)
static void mlpcreate1 (int nin, int nhid, int nout, multilayerperceptron network)
static void mlpcreate2 (int nin, int nhid1, int nhid2, int nout, multilayerperceptron network)
static void mlpcreateb0 (int nin, int nout, double b, double d, multilayerperceptron network)
static void mlpcreateb1 (int nin, int nhid, int nout, double b, double d, multilayerperceptron network)
static void mlpcreateb2 (int nin, int nhid1, int nhid2, int nout, double b, double d, multilayerperceptron network)
static void mlpcreater0 (int nin, int nout, double a, double b, multilayerperceptron network)
static void mlpcreater1 (int nin, int nhid, int nout, double a, double b, multilayerperceptron network)
static void mlpcreater2 (int nin, int nhid1, int nhid2, int nout, double a, double b, multilayerperceptron network)
static void mlpcreatec0 (int nin, int nout, multilayerperceptron network)
static void mlpcreatec1 (int nin, int nhid, int nout, multilayerperceptron network)
static void mlpcreatec2 (int nin, int nhid1, int nhid2, int nout, multilayerperceptron network)
static void mlpcopy (multilayerperceptron network1, multilayerperceptron network2)
static void mlpcopyshared (multilayerperceptron network1, multilayerperceptron network2)
static bool mlpsamearchitecture (multilayerperceptron network1, multilayerperceptron network2)
static void mlpcopytunableparameters (multilayerperceptron network1, multilayerperceptron network2)
static void mlpexporttunableparameters (multilayerperceptron network, ref double[] p, ref int pcount)
static void mlpimporttunableparameters (multilayerperceptron network, double[] p)
static void mlpserializeold (multilayerperceptron network, ref double[] ra, ref int rlen)
static void mlpunserializeold (double[] ra, multilayerperceptron network)
static void mlprandomize (multilayerperceptron network)
static void mlprandomizefull (multilayerperceptron network)
static void mlpinitpreprocessor (multilayerperceptron network, double[,] xy, int ssize)
static void mlpinitpreprocessorsparse (multilayerperceptron network, sparse.sparsematrix xy, int ssize)
static void mlpinitpreprocessorsubset (multilayerperceptron network, double[,] xy, int setsize, int[] idx, int subsetsize)
static void mlpinitpreprocessorsparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] idx, int subsetsize)
static void mlpproperties (multilayerperceptron network, ref int nin, ref int nout, ref int wcount)
static int mlpntotal (multilayerperceptron network)
static int mlpgetinputscount (multilayerperceptron network)
static int mlpgetoutputscount (multilayerperceptron network)
static int mlpgetweightscount (multilayerperceptron network)
static bool mlpissoftmax (multilayerperceptron network)
static int mlpgetlayerscount (multilayerperceptron network)
static int mlpgetlayersize (multilayerperceptron network, int k)
static void mlpgetinputscaling (multilayerperceptron network, int i, ref double mean, ref double sigma)
static void mlpgetoutputscaling (multilayerperceptron network, int i, ref double mean, ref double sigma)
static void mlpgetneuroninfo (multilayerperceptron network, int k, int i, ref int fkind, ref double threshold)
static double mlpgetweight (multilayerperceptron network, int k0, int i0, int k1, int i1)
static void mlpsetinputscaling (multilayerperceptron network, int i, double mean, double sigma)
static void mlpsetoutputscaling (multilayerperceptron network, int i, double mean, double sigma)
static void mlpsetneuroninfo (multilayerperceptron network, int k, int i, int fkind, double threshold)
static void mlpsetweight (multilayerperceptron network, int k0, int i0, int k1, int i1, double w)
static void mlpactivationfunction (double net, int k, ref double f, ref double df, ref double d2f)
static void mlpprocess (multilayerperceptron network, double[] x, ref double[] y)
static void mlpprocessi (multilayerperceptron network, double[] x, ref double[] y)
static double mlperror (multilayerperceptron network, double[,] xy, int npoints)
static double _pexec_mlperror (multilayerperceptron network, double[,] xy, int npoints)
static double mlperrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints)
static double _pexec_mlperrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints)
static double mlperrorn (multilayerperceptron network, double[,] xy, int ssize)
static int mlpclserror (multilayerperceptron network, double[,] xy, int npoints)
static int _pexec_mlpclserror (multilayerperceptron network, double[,] xy, int npoints)
static double mlprelclserror (multilayerperceptron network, double[,] xy, int npoints)
static double _pexec_mlprelclserror (multilayerperceptron network, double[,] xy, int npoints)
static double mlprelclserrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints)
static double _pexec_mlprelclserrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints)
static double mlpavgce (multilayerperceptron network, double[,] xy, int npoints)
static double _pexec_mlpavgce (multilayerperceptron network, double[,] xy, int npoints)
static double mlpavgcesparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints)
static double _pexec_mlpavgcesparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints)
static double mlprmserror (multilayerperceptron network, double[,] xy, int npoints)
static double _pexec_mlprmserror (multilayerperceptron network, double[,] xy, int npoints)
static double mlprmserrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints)
static double _pexec_mlprmserrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints)
static double mlpavgerror (multilayerperceptron network, double[,] xy, int npoints)
static double _pexec_mlpavgerror (multilayerperceptron network, double[,] xy, int npoints)
static double mlpavgerrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints)
static double _pexec_mlpavgerrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints)
static double mlpavgrelerror (multilayerperceptron network, double[,] xy, int npoints)
static double _pexec_mlpavgrelerror (multilayerperceptron network, double[,] xy, int npoints)
static double mlpavgrelerrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints)
static double _pexec_mlpavgrelerrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints)
static void mlpgrad (multilayerperceptron network, double[] x, double[] desiredy, ref double e, ref double[] grad)
static void mlpgradn (multilayerperceptron network, double[] x, double[] desiredy, ref double e, ref double[] grad)
static void mlpgradbatch (multilayerperceptron network, double[,] xy, int ssize, ref double e, ref double[] grad)
static void _pexec_mlpgradbatch (multilayerperceptron network, double[,] xy, int ssize, ref double e, ref double[] grad)
static void mlpgradbatchsparse (multilayerperceptron network, sparse.sparsematrix xy, int ssize, ref double e, ref double[] grad)
static void _pexec_mlpgradbatchsparse (multilayerperceptron network, sparse.sparsematrix xy, int ssize, ref double e, ref double[] grad)
static void mlpgradbatchsubset (multilayerperceptron network, double[,] xy, int setsize, int[] idx, int subsetsize, ref double e, ref double[] grad)
static void _pexec_mlpgradbatchsubset (multilayerperceptron network, double[,] xy, int setsize, int[] idx, int subsetsize, ref double e, ref double[] grad)
static void mlpgradbatchsparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] idx, int subsetsize, ref double e, ref double[] grad)
static void _pexec_mlpgradbatchsparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] idx, int subsetsize, ref double e, ref double[] grad)
static void mlpgradbatchx (multilayerperceptron network, double[,] densexy, sparse.sparsematrix sparsexy, int datasetsize, int datasettype, int[] idx, int subset0, int subset1, int subsettype, alglib.smp.shared_pool buf, alglib.smp.shared_pool gradbuf)
static void mlpgradnbatch (multilayerperceptron network, double[,] xy, int ssize, ref double e, ref double[] grad)
static void mlphessiannbatch (multilayerperceptron network, double[,] xy, int ssize, ref double e, ref double[] grad, ref double[,] h)
static void mlphessianbatch (multilayerperceptron network, double[,] xy, int ssize, ref double e, ref double[] grad, ref double[,] h)
static void mlpinternalprocessvector (int[] structinfo, double[] weights, double[] columnmeans, double[] columnsigmas, ref double[] neurons, ref double[] dfdnet, double[] x, ref double[] y)
static void mlpalloc (alglib.serializer s, multilayerperceptron network)
static void mlpserialize (alglib.serializer s, multilayerperceptron network)
static void mlpunserialize (alglib.serializer s, multilayerperceptron network)
static void mlpallerrorssubset (multilayerperceptron network, double[,] xy, int setsize, int[] subset, int subsetsize, modelerrors rep)
static void _pexec_mlpallerrorssubset (multilayerperceptron network, double[,] xy, int setsize, int[] subset, int subsetsize, modelerrors rep)
static void mlpallerrorssparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] subset, int subsetsize, modelerrors rep)
static void _pexec_mlpallerrorssparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] subset, int subsetsize, modelerrors rep)
static double mlperrorsubset (multilayerperceptron network, double[,] xy, int setsize, int[] subset, int subsetsize)
static double _pexec_mlperrorsubset (multilayerperceptron network, double[,] xy, int setsize, int[] subset, int subsetsize)
static double mlperrorsparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] subset, int subsetsize)
static double _pexec_mlperrorsparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] subset, int subsetsize)
static void mlpallerrorsx (multilayerperceptron network, double[,] densexy, sparse.sparsematrix sparsexy, int datasetsize, int datasettype, int[] idx, int subset0, int subset1, int subsettype, alglib.smp.shared_pool buf, modelerrors rep)
Public Attributes
const int mlpvnum = 7
const int mlpfirstversion = 0
const int nfieldwidth = 4
const int hlconnfieldwidth = 5
const int hlnfieldwidth = 4
const int chunksize = 32
const int gradbasecasecost = 50000
const int microbatchsize = 64
Static Private Member Functions
static void addinputlayer (int ncount, ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc)
static void addbiasedsummatorlayer (int ncount, ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc)
static void addactivationlayer (int functype, ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc)
static void addzerolayer (ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc)
static void hladdinputlayer (multilayerperceptron network, ref int connidx, ref int neuroidx, ref int structinfoidx, int nin)
static void hladdoutputlayer (multilayerperceptron network, ref int connidx, ref int neuroidx, ref int structinfoidx, ref int weightsidx, int k, int nprev, int nout, bool iscls, bool islinearout)
static void hladdhiddenlayer (multilayerperceptron network, ref int connidx, ref int neuroidx, ref int structinfoidx, ref int weightsidx, int k, int nprev, int ncur)
static void fillhighlevelinformation (multilayerperceptron network, int nin, int nhid1, int nhid2, int nout, bool iscls, bool islinearout)
static void mlpcreate (int nin, int nout, int[] lsizes, int[] ltypes, int[] lconnfirst, int[] lconnlast, int layerscount, bool isclsnet, multilayerperceptron network)
static void mlphessianbatchinternal (multilayerperceptron network, double[,] xy, int ssize, bool naturalerr, ref double e, ref double[] grad, ref double[,] h)
static void mlpinternalcalculategradient (multilayerperceptron network, double[] neurons, double[] weights, ref double[] derror, ref double[] grad, bool naturalerrorfunc)
static void mlpchunkedgradient (multilayerperceptron network, double[,] xy, int cstart, int csize, ref double e, ref double[] grad, bool naturalerrorfunc)
static double safecrossentropy (double t, double z)
static void addinputlayer (int ncount, ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc)
static void addbiasedsummatorlayer (int ncount, ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc)
static void addactivationlayer (int functype, ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc)
static void addzerolayer (ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc)
static void hladdinputlayer (multilayerperceptron network, ref int connidx, ref int neuroidx, ref int structinfoidx, int nin)
static void hladdoutputlayer (multilayerperceptron network, ref int connidx, ref int neuroidx, ref int structinfoidx, ref int weightsidx, int k, int nprev, int nout, bool iscls, bool islinearout)
static void hladdhiddenlayer (multilayerperceptron network, ref int connidx, ref int neuroidx, ref int structinfoidx, ref int weightsidx, int k, int nprev, int ncur)
static void fillhighlevelinformation (multilayerperceptron network, int nin, int nhid1, int nhid2, int nout, bool iscls, bool islinearout)
static void mlpcreate (int nin, int nout, int[] lsizes, int[] ltypes, int[] lconnfirst, int[] lconnlast, int layerscount, bool isclsnet, multilayerperceptron network)
static void mlphessianbatchinternal (multilayerperceptron network, double[,] xy, int ssize, bool naturalerr, ref double e, ref double[] grad, ref double[,] h)
static void mlpinternalcalculategradient (multilayerperceptron network, double[] neurons, double[] weights, ref double[] derror, ref double[] grad, bool naturalerrorfunc)
static void mlpchunkedgradient (multilayerperceptron network, double[,] xy, int cstart, int csize, double[] batch4buf, double[] hpcbuf, ref double e, bool naturalerrorfunc)
static void mlpchunkedprocess (multilayerperceptron network, double[,] xy, int cstart, int csize, double[] batch4buf, double[] hpcbuf)
static double safecrossentropy (double t, double z)
static void randomizebackwardpass (multilayerperceptron network, int neuronidx, double v)
Member Function Documentation
static void alglib.mlpbase.mlpcreate0 (int nin, int nout, multilayerperceptron network) inline static
References alglib.mlpbase.addactivationlayer(), alglib.mlpbase.addbiasedsummatorlayer(), alglib.mlpbase.addinputlayer(), alglib.mlpbase.fillhighlevelinformation(), and alglib.mlpbase.mlpcreate().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.mlpcreate0(), alglib.mlpbase.mlpunserialize(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlptrainunit.testmlpzeroweights(), alglib.testmlpbaseunit.unsetnetwork(), and alglib.testmlptrainunit.unsetnetwork().
static void alglib.mlpbase.mlpcreate1 (int nin, int nhid, int nout, multilayerperceptron network) inline static
References alglib.mlpbase.addactivationlayer(), alglib.mlpbase.addbiasedsummatorlayer(), alglib.mlpbase.addinputlayer(), alglib.mlpbase.fillhighlevelinformation(), and alglib.mlpbase.mlpcreate().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.mlpcreate1(), alglib.mlpbase.mlpunserialize(), alglib.testmlpbaseunit.spectests(), alglib.testmlptrainunit.testmlprestarts(), alglib.testmlptrainunit.testmlptrain(), alglib.testmlptrainunit.testmlptrainregr(), and alglib.testmlptrainunit.testmlpxorregr().
static void alglib.mlpbase.mlpcreate2 (int nin, int nhid1, int nhid2, int nout, multilayerperceptron network) inline static
References alglib.mlpbase.addactivationlayer(), alglib.mlpbase.addbiasedsummatorlayer(), alglib.mlpbase.addinputlayer(), alglib.mlpbase.fillhighlevelinformation(), and alglib.mlpbase.mlpcreate().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.mlpcreate2(), and alglib.mlpbase.mlpunserialize().
static void alglib.mlpbase.mlpcreateb0 (int nin, int nout, double b, double d, multilayerperceptron network) inline static
References alglib.mlpbase.addactivationlayer(), alglib.mlpbase.addbiasedsummatorlayer(), alglib.mlpbase.addinputlayer(), alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.fillhighlevelinformation(), and alglib.mlpbase.mlpcreate().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), and alglib.mlpcreateb0().
static void alglib.mlpbase.mlpcreateb1 (int nin, int nhid, int nout, double b, double d, multilayerperceptron network) inline static
References alglib.mlpbase.addactivationlayer(), alglib.mlpbase.addbiasedsummatorlayer(), alglib.mlpbase.addinputlayer(), alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.fillhighlevelinformation(), and alglib.mlpbase.mlpcreate().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), and alglib.mlpcreateb1().
static void alglib.mlpbase.mlpcreateb2 (int nin, int nhid1, int nhid2, int nout, double b, double d, multilayerperceptron network) inline static
References alglib.mlpbase.addactivationlayer(), alglib.mlpbase.addbiasedsummatorlayer(), alglib.mlpbase.addinputlayer(), alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.fillhighlevelinformation(), and alglib.mlpbase.mlpcreate().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), and alglib.mlpcreateb2().
static void alglib.mlpbase.mlpcreater0 (int nin, int nout, double a, double b, multilayerperceptron network) inline static
References alglib.mlpbase.addactivationlayer(), alglib.mlpbase.addbiasedsummatorlayer(), alglib.mlpbase.addinputlayer(), alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.fillhighlevelinformation(), and alglib.mlpbase.mlpcreate().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.mlpcreater0(), and alglib.testmlptrainunit.testmlptraines().
static void alglib.mlpbase.mlpcreater1 (int nin, int nhid, int nout, double a, double b, multilayerperceptron network) inline static
References alglib.mlpbase.addactivationlayer(), alglib.mlpbase.addbiasedsummatorlayer(), alglib.mlpbase.addinputlayer(), alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.fillhighlevelinformation(), and alglib.mlpbase.mlpcreate().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), and alglib.mlpcreater1().
static void alglib.mlpbase.mlpcreater2 (int nin, int nhid1, int nhid2, int nout, double a, double b, multilayerperceptron network) inline static
References alglib.mlpbase.addactivationlayer(), alglib.mlpbase.addbiasedsummatorlayer(), alglib.mlpbase.addinputlayer(), alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.fillhighlevelinformation(), and alglib.mlpbase.mlpcreate().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), and alglib.mlpcreater2().
static void alglib.mlpbase.mlpcreatec0 (int nin, int nout, multilayerperceptron network) inline static
References alglib.mlpbase.addbiasedsummatorlayer(), alglib.mlpbase.addinputlayer(), alglib.mlpbase.addzerolayer(), alglib.ap.assert(), alglib.mlpbase.fillhighlevelinformation(), and alglib.mlpbase.mlpcreate().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.mlpcreatec0(), alglib.mlpbase.mlpunserialize(), alglib.logit.mnltrainh(), alglib.testmlptrainunit.testmlptrainclass(), and alglib.testmlptrainunit.testmlpzeroweights().
static void alglib.mlpbase.mlpcreatec1 (int nin, int nhid, int nout, multilayerperceptron network) inline static
References alglib.mlpbase.addactivationlayer(), alglib.mlpbase.addbiasedsummatorlayer(), alglib.mlpbase.addinputlayer(), alglib.mlpbase.addzerolayer(), alglib.ap.assert(), alglib.mlpbase.fillhighlevelinformation(), and alglib.mlpbase.mlpcreate().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.mlpcreatec1(), alglib.mlpbase.mlpunserialize(), alglib.testmlpbaseunit.spectests(), alglib.testmlptrainunit.testmlpcverror(), and alglib.testmlptrainunit.testmlpxorcls().
static void alglib.mlpbase.mlpcreatec2 (int nin, int nhid1, int nhid2, int nout, multilayerperceptron network) inline static
References alglib.mlpbase.addactivationlayer(), alglib.mlpbase.addbiasedsummatorlayer(), alglib.mlpbase.addinputlayer(), alglib.mlpbase.addzerolayer(), alglib.ap.assert(), alglib.mlpbase.fillhighlevelinformation(), and alglib.mlpbase.mlpcreate().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.mlpcreatec2(), and alglib.mlpbase.mlpunserialize().
static void alglib.mlpbase.mlpcopy (multilayerperceptron network1, multilayerperceptron network2) inline static
References alglib.mlpbase.multilayerperceptron.chunks, alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.apserv.copyintegerarray(), alglib.apserv.copyrealarray(), alglib.apserv.copyrealmatrix(), alglib.mlpbase.multilayerperceptron.derror, alglib.mlpbase.multilayerperceptron.dfdnet, alglib.mlpbase.multilayerperceptron.hlconnections, alglib.mlpbase.multilayerperceptron.hllayersizes, alglib.mlpbase.multilayerperceptron.hlnetworktype, alglib.mlpbase.multilayerperceptron.hlneurons, alglib.mlpbase.multilayerperceptron.hlnormtype, alglib.mlpbase.multilayerperceptron.integerbuf, alglib.mlpbase.multilayerperceptron.neurons, alglib.mlpbase.multilayerperceptron.nwbuf, alglib.mlpbase.multilayerperceptron.structinfo, alglib.mlpbase.multilayerperceptron.weights, alglib.mlpbase.multilayerperceptron.x, and alglib.mlpbase.multilayerperceptron.y.
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.testmlpbaseunit.testprocessing(), and alglib.testmlptrainunit.testprocessing().
static void alglib.mlpbase.mlpserializeold (multilayerperceptron network, ref double[] ra, ref int rlen) inline static
References alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpvnum, alglib.mlpbase.multilayerperceptron.structinfo, and alglib.mlpbase.multilayerperceptron.weights.
static void alglib.mlpbase.mlpunserializeold (double[] ra, multilayerperceptron network) inline static
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.chunks, alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.multilayerperceptron.derror, alglib.mlpbase.multilayerperceptron.dfdnet, alglib.mlpbase.mlpvnum, alglib.mlpbase.multilayerperceptron.neurons, alglib.mlpbase.multilayerperceptron.nwbuf, alglib.mlpbase.multilayerperceptron.structinfo, alglib.mlpbase.multilayerperceptron.weights, alglib.mlpbase.multilayerperceptron.x, and alglib.mlpbase.multilayerperceptron.y.
static void alglib.mlpbase.mlprandomize (multilayerperceptron network) inline static
References alglib.mlpbase.mlpproperties(), alglib.math.randomreal(), and alglib.mlpbase.multilayerperceptron.weights.
Referenced by alglib.mlprandomize(), alglib.testmlptrainunit.testmlptraines(), alglib.testmlpbaseunit.testprocessing(), and alglib.testmlptrainunit.testprocessing().
static void alglib.mlpbase.mlprandomizefull (multilayerperceptron network) inline static
References alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpproperties(), alglib.math.randomreal(), alglib.mlpbase.multilayerperceptron.structinfo, and alglib.mlpbase.multilayerperceptron.weights.
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.mlprandomizefull(), alglib.testmlpbaseunit.testerr(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testgradient(), alglib.testmlpbaseunit.testhessian(), alglib.testmlptrainunit.testhessian(), alglib.testmlpbaseunit.testprocessing(), and alglib.testmlptrainunit.testprocessing().
static void alglib.mlpbase.mlpinitpreprocessor (multilayerperceptron network, double xy[,], int ssize) inline static
References alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpproperties(), alglib.math.sqr(), and alglib.mlpbase.multilayerperceptron.structinfo.
Referenced by alglib.logit.mnltrainh(), and alglib.testmlpbaseunit.testprocessing().
static void alglib.mlpbase.mlpproperties (multilayerperceptron network, ref int nin, ref int nout, ref int wcount) inline static
References alglib.mlpbase.multilayerperceptron.structinfo.
Referenced by alglib.mlpbase.mlpavgce(), alglib.mlpbase.mlpavgerror(), alglib.mlpbase.mlpavgrelerror(), alglib.mlpbase.mlpclserror(), alglib.mlpbase.mlperror(), alglib.mlpbase.mlperrorn(), alglib.mlpbase.mlpgradbatch(), alglib.mlpbase.mlpgradnbatch(), alglib.mlpbase.mlphessianbatchinternal(), alglib.mlpbase.mlpinitpreprocessor(), alglib.mlpproperties(), alglib.mlpbase.mlprandomize(), alglib.mlpbase.mlprandomizefull(), alglib.mlpbase.mlprmserror(), alglib.logit.mnltrainh(), alglib.testmlpbaseunit.testerr(), alglib.testmlpeunit.testerr(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testgradient(), alglib.testmlpbaseunit.testhessian(), alglib.testmlptrainunit.testhessian(), alglib.testmlpbaseunit.testinformational(), alglib.testmlptrainunit.testinformational(), alglib.testmlpbaseunit.testmlpgbsubset(), alglib.testmlptrainunit.testmlpgbsubset(), alglib.testmlptrainunit.testmlprestarts(), alglib.testmlptrainunit.testmlpxorcls(), alglib.testmlptrainunit.testmlpzeroweights(), alglib.testmlpbaseunit.testprocessing(), and alglib.testmlptrainunit.testprocessing().
static int alglib.mlpbase.mlpgetinputscount (multilayerperceptron network) inline static
References alglib.mlpbase.multilayerperceptron.structinfo.
Referenced by alglib.mlpgetinputscount(), alglib.testmlpbaseunit.testinformational(), and alglib.testmlptrainunit.testinformational().
static int alglib.mlpbase.mlpgetoutputscount (multilayerperceptron network) inline static
References alglib.mlpbase.multilayerperceptron.structinfo.
Referenced by alglib.mlpgetoutputscount(), alglib.testmlpbaseunit.testinformational(), and alglib.testmlptrainunit.testinformational().
static int alglib.mlpbase.mlpgetweightscount (multilayerperceptron network) inline static
References alglib.mlpbase.multilayerperceptron.structinfo.
Referenced by alglib.mlpgetweightscount(), alglib.testmlpbaseunit.spectests(), alglib.testmlpbaseunit.testinformational(), and alglib.testmlptrainunit.testinformational().
static bool alglib.mlpbase.mlpissoftmax (multilayerperceptron network) inline static
References alglib.mlpbase.multilayerperceptron.structinfo.
Referenced by alglib.mlpbase.mlpavgce(), alglib.mlpbase.mlpavgerror(), alglib.mlpbase.mlpavgrelerror(), alglib.mlpbase.mlpclserror(), alglib.mlpbase.mlperror(), alglib.mlpbase.mlphessianbatchinternal(), alglib.mlpbase.mlpinitpreprocessor(), alglib.mlpissoftmax(), alglib.mlpbase.mlprandomizefull(), alglib.mlpbase.mlpserialize(), alglib.mlpbase.mlpserializeold(), alglib.testmlpbaseunit.testerr(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testgradient(), alglib.testmlpbaseunit.testhessian(), alglib.testmlptrainunit.testhessian(), alglib.testmlpbaseunit.testmlpgbsubset(), alglib.testmlptrainunit.testmlpgbsubset(), and alglib.testmlpbaseunit.testprocessing().
static int alglib.mlpbase.mlpgetlayerscount (multilayerperceptron network) inline static
References alglib.mlpbase.multilayerperceptron.hllayersizes.
Referenced by alglib.mlpgetlayerscount().
static int alglib.mlpbase.mlpgetlayersize (multilayerperceptron network, int k) inline static
References alglib.ap.assert(), and alglib.mlpbase.multilayerperceptron.hllayersizes.
Referenced by alglib.mlpgetlayersize(), alglib.testmlpbaseunit.testinformational(), and alglib.testmlptrainunit.testinformational().
static void alglib.mlpbase.mlpgetinputscaling (multilayerperceptron network, int i, ref double mean, ref double sigma) inline static
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, and alglib.mlpbase.multilayerperceptron.hllayersizes.
Referenced by alglib.mlpbase.mlpalloc(), alglib.mlpgetinputscaling(), alglib.mlpbase.mlpserialize(), alglib.testmlpbaseunit.testinformational(), and alglib.testmlptrainunit.testinformational().
static void alglib.mlpbase.mlpgetoutputscaling (multilayerperceptron network, int i, ref double mean, ref double sigma) inline static
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.multilayerperceptron.hllayersizes, and alglib.mlpbase.multilayerperceptron.structinfo.
Referenced by alglib.mlpbase.mlpalloc(), alglib.mlpgetoutputscaling(), alglib.mlpbase.mlpserialize(), alglib.testmlpbaseunit.testinformational(), and alglib.testmlptrainunit.testinformational().
static void alglib.mlpbase.mlpgetneuroninfo (multilayerperceptron network, int k, int i, ref int fkind, ref double threshold) inline static
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.hlneurons, alglib.mlpbase.hlnfieldwidth, alglib.mlpbase.multilayerperceptron.integerbuf, alglib.mlpbase.nfieldwidth, alglib.apserv.recsearch(), alglib.mlpbase.multilayerperceptron.structinfo, and alglib.mlpbase.multilayerperceptron.weights.
Referenced by alglib.mlpbase.mlpalloc(), alglib.mlpgetneuroninfo(), alglib.mlpbase.mlpserialize(), alglib.testmlpbaseunit.testinformational(), and alglib.testmlptrainunit.testinformational().
static double alglib.mlpbase.mlpgetweight (multilayerperceptron network, int k0, int i0, int k1, int i1) inline static
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.hlconnections, alglib.mlpbase.hlconnfieldwidth, alglib.mlpbase.multilayerperceptron.hllayersizes, alglib.mlpbase.multilayerperceptron.integerbuf, alglib.apserv.recsearch(), and alglib.mlpbase.multilayerperceptron.weights.
Referenced by alglib.mlpgetweight(), alglib.mlpbase.mlpserialize(), alglib.testmlpbaseunit.testinformational(), and alglib.testmlptrainunit.testinformational().
static void alglib.mlpbase.mlpsetinputscaling (multilayerperceptron network, int i, double mean, double sigma) inline static
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.multilayerperceptron.hllayersizes, and alglib.math.isfinite().
Referenced by alglib.mlpsetinputscaling(), and alglib.mlpbase.mlpunserialize().
static void alglib.mlpbase.mlpsetoutputscaling (multilayerperceptron network, int i, double mean, double sigma) inline static
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.multilayerperceptron.hllayersizes, alglib.math.isfinite(), and alglib.mlpbase.multilayerperceptron.structinfo.
Referenced by alglib.mlpsetoutputscaling(), and alglib.mlpbase.mlpunserialize().
static void alglib.mlpbase.mlpsetneuroninfo (multilayerperceptron network, int k, int i, int fkind, double threshold) inline static
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.hlneurons, alglib.mlpbase.hlnfieldwidth, alglib.mlpbase.multilayerperceptron.integerbuf, alglib.math.isfinite(), alglib.mlpbase.nfieldwidth, alglib.apserv.recsearch(), alglib.mlpbase.multilayerperceptron.structinfo, and alglib.mlpbase.multilayerperceptron.weights.
Referenced by alglib.mlpsetneuroninfo(), and alglib.mlpbase.mlpunserialize().
static void alglib.mlpbase.mlpsetweight (multilayerperceptron network, int k0, int i0, int k1, int i1, double w) inline static
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.hlconnections, alglib.mlpbase.hlconnfieldwidth, alglib.mlpbase.multilayerperceptron.hllayersizes, alglib.mlpbase.multilayerperceptron.integerbuf, alglib.math.isfinite(), alglib.apserv.recsearch(), and alglib.mlpbase.multilayerperceptron.weights.
Referenced by alglib.mlpsetweight(), and alglib.mlpbase.mlpunserialize().
static void alglib.mlpbase.mlpactivationfunction (double net, int k, ref double f, ref double df, ref double d2f) inline static
References alglib.math.sqr().
Referenced by alglib.mlpactivationfunction(), alglib.mlpbase.mlpchunkedgradient(), alglib.mlpbase.mlphessianbatchinternal(), alglib.mlpbase.mlpinternalprocessvector(), alglib.testmlpbaseunit.testinformational(), and alglib.testmlptrainunit.testinformational().
static void alglib.mlpbase.mlpprocess (multilayerperceptron network, double[] x, ref double[] y) inline static
References alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.multilayerperceptron.dfdnet, alglib.mlpbase.mlpinternalprocessvector(), alglib.mlpbase.multilayerperceptron.neurons, alglib.mlpbase.multilayerperceptron.structinfo, and alglib.mlpbase.multilayerperceptron.weights.
Referenced by alglib.mlpbase.mlpavgerror(), alglib.mlpbase.mlpavgrelerror(), alglib.mlpbase.mlpclserror(), alglib.mlpbase.mlperror(), alglib.mlpbase.mlperrorn(), alglib.mlpbase.mlpgrad(), alglib.mlpbase.mlpgradn(), alglib.mlpprocess(), alglib.mlpbase.mlpprocessi(), alglib.testmlpbaseunit.testerr(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testgradient(), alglib.testmlpbaseunit.testinformational(), alglib.testmlptrainunit.testinformational(), alglib.testmlptrainunit.testmlptrainclass(), alglib.testmlptrainunit.testmlptraines(), alglib.testmlptrainunit.testmlptrainregr(), alglib.testmlptrainunit.testmlpxorcls(), alglib.testmlptrainunit.testmlpxorregr(), alglib.testmlpbaseunit.testprocessing(), and alglib.testmlptrainunit.testprocessing().
static void alglib.mlpbase.mlpprocessi (multilayerperceptron network, double[] x, ref double[] y) inline static
References alglib.mlpbase.mlpprocess().
Referenced by alglib.mlpprocessi().
static double alglib.mlpbase.mlperror (multilayerperceptron network, double xy[,], int ssize) inline static
References alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlpproperties(), alglib.mlpbase.multilayerperceptron.x, and alglib.mlpbase.multilayerperceptron.y.
Referenced by alglib.mlperror(), alglib.mlpbase.mlprmserror(), alglib.testmlpbaseunit.spectests(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testgradient(), alglib.testmlptrainunit.testmlptraines(), and alglib.testmlptrainunit.testmlpxorcls().
static double alglib.mlpbase.mlperrorn (multilayerperceptron network, double xy[,], int ssize) inline static
References alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlpproperties(), alglib.mlpbase.safecrossentropy(), alglib.mlpbase.multilayerperceptron.structinfo, alglib.mlpbase.multilayerperceptron.x, and alglib.mlpbase.multilayerperceptron.y.
Referenced by alglib.mlpbase.mlpavgce(), alglib.mlperrorn(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testgradient(), and alglib.testmlptrainunit.testmlprestarts().
static int alglib.mlpbase.mlpclserror (multilayerperceptron network, double xy[,], int ssize) inline static
References alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpprocess(), and alglib.mlpbase.mlpproperties().
Referenced by alglib.mlpclserror(), alglib.mlpbase.mlprelclserror(), and alglib.testmlpbaseunit.testerr().
static double alglib.mlpbase.mlprelclserror (multilayerperceptron network, double xy[,], int npoints) inline static
References alglib.mlpbase.mlpclserror().
Referenced by alglib.mlprelclserror(), alglib.testmlpbaseunit.testerr(), and alglib.testmlptrainunit.testmlpcverror().
static double alglib.mlpbase.mlpavgce (multilayerperceptron network, double xy[,], int npoints) inline static
References alglib.mlpbase.mlperrorn(), alglib.mlpbase.mlpissoftmax(), and alglib.mlpbase.mlpproperties().
Referenced by alglib.mlpavgce(), alglib.testmlpbaseunit.testerr(), and alglib.testmlptrainunit.testmlpcverror().
static double alglib.mlpbase.mlprmserror (multilayerperceptron network, double xy[,], int npoints) inline static
References alglib.mlpbase.mlperror(), and alglib.mlpbase.mlpproperties().
Referenced by alglib.mlprmserror(), alglib.testmlpbaseunit.testerr(), alglib.testmlptrainunit.testmlpcverror(), and alglib.testmlptrainunit.testmlptrain().
static double alglib.mlpbase.mlpavgerror (multilayerperceptron network, double xy[,], int npoints) inline static
References alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlpproperties(), alglib.mlpbase.multilayerperceptron.x, and alglib.mlpbase.multilayerperceptron.y.
Referenced by alglib.mlpavgerror(), alglib.testmlpbaseunit.testerr(), and alglib.testmlptrainunit.testmlpcverror().
static double alglib.mlpbase.mlpavgrelerror (multilayerperceptron network, double xy[,], int npoints) inline static
References alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlpproperties(), alglib.mlpbase.multilayerperceptron.x, and alglib.mlpbase.multilayerperceptron.y.
Referenced by alglib.mlpavgrelerror(), alglib.testmlpbaseunit.testerr(), and alglib.testmlptrainunit.testmlpcverror().
static void alglib.mlpbase.mlpgrad (multilayerperceptron network, double[] x, double[] desiredy, ref double e, ref double[] grad) inline static
References alglib.mlpbase.multilayerperceptron.derror, alglib.mlpbase.mlpinternalcalculategradient(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.multilayerperceptron.neurons, alglib.math.sqr(), alglib.mlpbase.multilayerperceptron.structinfo, alglib.mlpbase.multilayerperceptron.weights, and alglib.mlpbase.multilayerperceptron.y.
Referenced by alglib.mlpgrad(), alglib.mlpbase.mlphessianbatchinternal(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testgradient(), alglib.testmlpbaseunit.testhessian(), and alglib.testmlptrainunit.testhessian().
static void alglib.mlpbase.mlpgradn (multilayerperceptron network, double[] x, double[] desiredy, ref double e, ref double[] grad) inline static
References alglib.mlpbase.multilayerperceptron.derror, alglib.mlpbase.mlpinternalcalculategradient(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.multilayerperceptron.neurons, alglib.mlpbase.safecrossentropy(), alglib.math.sqr(), alglib.mlpbase.multilayerperceptron.structinfo, alglib.mlpbase.multilayerperceptron.weights, and alglib.mlpbase.multilayerperceptron.y.
Referenced by alglib.mlpgradn(), alglib.mlpbase.mlphessianbatchinternal(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testgradient(), alglib.testmlpbaseunit.testhessian(), and alglib.testmlptrainunit.testhessian().
static void alglib.mlpbase.mlpgradbatch (multilayerperceptron network, double xy[,], int ssize, ref double e, ref double[] grad) inline static
References alglib.mlpbase.chunksize, alglib.mlpbase.mlpchunkedgradient(), and alglib.mlpbase.mlpproperties().
Referenced by alglib.mlpgradbatch(), alglib.testmlpbaseunit.spectests(), alglib.testmlpbaseunit.testgradient(), alglib.testmlptrainunit.testgradient(), alglib.testmlpbaseunit.testmlpgbsubset(), and alglib.testmlptrainunit.testmlpgbsubset().
static void alglib.mlpbase.mlpgradnbatch (multilayerperceptron network, double xy[,], int ssize, ref double e, ref double[] grad) inline static
References alglib.mlpbase.chunksize, alglib.mlpbase.mlpchunkedgradient(), and alglib.mlpbase.mlpproperties().
Referenced by alglib.mlpgradnbatch(), alglib.logit.mnltrainh(), alglib.testmlpbaseunit.testgradient(), and alglib.testmlptrainunit.testgradient().
static void alglib.mlpbase.mlphessiannbatch (multilayerperceptron network, double xy[,], int ssize, ref double e, ref double[] grad, ref double h[,]) inline static
References alglib.mlpbase.mlphessianbatchinternal().
Referenced by alglib.mlphessiannbatch(), alglib.logit.mnltrainh(), alglib.testmlpbaseunit.testhessian(), and alglib.testmlptrainunit.testhessian().
static void alglib.mlpbase.mlphessianbatch (multilayerperceptron network, double xy[,], int ssize, ref double e, ref double[] grad, ref double h[,]) inline static
References alglib.mlpbase.mlphessianbatchinternal().
Referenced by alglib.mlphessianbatch(), alglib.testmlpbaseunit.testhessian(), and alglib.testmlptrainunit.testhessian().
static void alglib.mlpbase.mlpinternalprocessvector (int[] structinfo, double[] weights, double[] columnmeans, double[] columnsigmas, ref double[] neurons, ref double[] dfdnet, double[] x, ref double[] y) inline static
References alglib.ap.assert(), alglib.mlpbase.mlpactivationfunction(), and alglib.mlpbase.nfieldwidth.
Referenced by alglib.mlpbase.mlpprocess().
static void alglib.mlpbase.mlpalloc (alglib.serializer s, multilayerperceptron network) inline static
References alglib.apserv.allocintegerarray(), alglib.mlpbase.multilayerperceptron.hllayersizes, alglib.mlpbase.mlpgetinputscaling(), alglib.mlpbase.mlpgetneuroninfo(), and alglib.mlpbase.mlpgetoutputscaling().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.mlpserialize(), alglib.testmlpbaseunit.testprocessing(), and alglib.testmlptrainunit.testprocessing().
static void alglib.mlpbase.mlpserialize (alglib.serializer s, multilayerperceptron network) inline static
References alglib.scodes.getmlpserializationcode(), alglib.mlpbase.multilayerperceptron.hllayersizes, alglib.mlpbase.mlpgetinputscaling(), alglib.mlpbase.mlpgetneuroninfo(), alglib.mlpbase.mlpgetoutputscaling(), alglib.mlpbase.mlpgetweight(), alglib.mlpbase.mlpissoftmax(), and alglib.apserv.serializeintegerarray().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.mlpserialize(), alglib.testmlpbaseunit.testprocessing(), and alglib.testmlptrainunit.testprocessing().
static void alglib.mlpbase.mlpunserialize (alglib.serializer s, multilayerperceptron network) inline static
References alglib.ap.assert(), alglib.scodes.getmlpserializationcode(), alglib.mlpbase.mlpcreate0(), alglib.mlpbase.mlpcreate1(), alglib.mlpbase.mlpcreate2(), alglib.mlpbase.mlpcreatec0(), alglib.mlpbase.mlpcreatec1(), alglib.mlpbase.mlpcreatec2(), alglib.mlpbase.mlpsetinputscaling(), alglib.mlpbase.mlpsetneuroninfo(), alglib.mlpbase.mlpsetoutputscaling(), alglib.mlpbase.mlpsetweight(), and alglib.apserv.unserializeintegerarray().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.mlpunserialize(), alglib.testmlpbaseunit.testprocessing(), and alglib.testmlptrainunit.testprocessing().
static void alglib.mlpbase.addinputlayer (int ncount, ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc) inline static private
Referenced by alglib.mlpbase.mlpcreate0(), alglib.mlpbase.mlpcreate1(), alglib.mlpbase.mlpcreate2(), alglib.mlpbase.mlpcreateb0(), alglib.mlpbase.mlpcreateb1(), alglib.mlpbase.mlpcreateb2(), alglib.mlpbase.mlpcreatec0(), alglib.mlpbase.mlpcreatec1(), alglib.mlpbase.mlpcreatec2(), alglib.mlpbase.mlpcreater0(), alglib.mlpbase.mlpcreater1(), and alglib.mlpbase.mlpcreater2().
static void alglib.mlpbase.addbiasedsummatorlayer (int ncount, ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc) inline static private
Referenced by alglib.mlpbase.mlpcreate0(), alglib.mlpbase.mlpcreate1(), alglib.mlpbase.mlpcreate2(), alglib.mlpbase.mlpcreateb0(), alglib.mlpbase.mlpcreateb1(), alglib.mlpbase.mlpcreateb2(), alglib.mlpbase.mlpcreatec0(), alglib.mlpbase.mlpcreatec1(), alglib.mlpbase.mlpcreatec2(), alglib.mlpbase.mlpcreater0(), alglib.mlpbase.mlpcreater1(), and alglib.mlpbase.mlpcreater2().
static void alglib.mlpbase.addactivationlayer (int functype, ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc) inline static private
References alglib.ap.assert().
Referenced by alglib.mlpbase.mlpcreate0(), alglib.mlpbase.mlpcreate1(), alglib.mlpbase.mlpcreate2(), alglib.mlpbase.mlpcreateb0(), alglib.mlpbase.mlpcreateb1(), alglib.mlpbase.mlpcreateb2(), alglib.mlpbase.mlpcreatec1(), alglib.mlpbase.mlpcreatec2(), alglib.mlpbase.mlpcreater0(), alglib.mlpbase.mlpcreater1(), and alglib.mlpbase.mlpcreater2().
static void alglib.mlpbase.addzerolayer (ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc) inline static private
Referenced by alglib.mlpbase.mlpcreatec0(), alglib.mlpbase.mlpcreatec1(), and alglib.mlpbase.mlpcreatec2().
static void alglib.mlpbase.hladdinputlayer (multilayerperceptron network, ref int connidx, ref int neuroidx, ref int structinfoidx, int nin) inline static private
References alglib.mlpbase.multilayerperceptron.hlneurons, and alglib.mlpbase.hlnfieldwidth.
Referenced by alglib.mlpbase.fillhighlevelinformation().
static void alglib.mlpbase.hladdoutputlayer (multilayerperceptron network, ref int connidx, ref int neuroidx, ref int structinfoidx, ref int weightsidx, int k, int nprev, int nout, bool iscls, bool islinearout) inline static private
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.hlconnections, alglib.mlpbase.hlconnfieldwidth, alglib.mlpbase.multilayerperceptron.hlneurons, and alglib.mlpbase.hlnfieldwidth.
Referenced by alglib.mlpbase.fillhighlevelinformation().
static void alglib.mlpbase.hladdhiddenlayer (multilayerperceptron network, ref int connidx, ref int neuroidx, ref int structinfoidx, ref int weightsidx, int k, int nprev, int ncur) inline static private
References alglib.mlpbase.multilayerperceptron.hlconnections, alglib.mlpbase.hlconnfieldwidth, alglib.mlpbase.multilayerperceptron.hlneurons, and alglib.mlpbase.hlnfieldwidth.
Referenced by alglib.mlpbase.fillhighlevelinformation().
static void alglib.mlpbase.fillhighlevelinformation (multilayerperceptron network, int nin, int nhid1, int nhid2, int nout, bool iscls, bool islinearout) inline static private
References alglib.ap.assert(), alglib.mlpbase.hladdhiddenlayer(), alglib.mlpbase.hladdinputlayer(), alglib.mlpbase.hladdoutputlayer(), alglib.mlpbase.multilayerperceptron.hlconnections, alglib.mlpbase.multilayerperceptron.hllayersizes, alglib.mlpbase.multilayerperceptron.hlnetworktype, alglib.mlpbase.multilayerperceptron.hlneurons, and alglib.mlpbase.multilayerperceptron.hlnormtype.
Referenced by alglib.mlpbase.mlpcreate0(), alglib.mlpbase.mlpcreate1(), alglib.mlpbase.mlpcreate2(), alglib.mlpbase.mlpcreateb0(), alglib.mlpbase.mlpcreateb1(), alglib.mlpbase.mlpcreateb2(), alglib.mlpbase.mlpcreatec0(), alglib.mlpbase.mlpcreatec1(), alglib.mlpbase.mlpcreatec2(), alglib.mlpbase.mlpcreater0(), alglib.mlpbase.mlpcreater1(), and alglib.mlpbase.mlpcreater2().
static void alglib.mlpbase.mlpcreate (int nin, int nout, int[] lsizes, int[] ltypes, int[] lconnfirst, int[] lconnlast, int layerscount, bool isclsnet, multilayerperceptron network) inline static private
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.chunks, alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.multilayerperceptron.derror, alglib.mlpbase.multilayerperceptron.dfdnet, alglib.mlpbase.multilayerperceptron.integerbuf, alglib.mlpbase.multilayerperceptron.neurons, alglib.mlpbase.nfieldwidth, alglib.mlpbase.multilayerperceptron.nwbuf, alglib.math.randomreal(), alglib.mlpbase.multilayerperceptron.structinfo, alglib.mlpbase.multilayerperceptron.weights, alglib.mlpbase.multilayerperceptron.x, and alglib.mlpbase.multilayerperceptron.y.
Referenced by alglib.mlpbase.mlpcreate0(), alglib.mlpbase.mlpcreate1(), alglib.mlpbase.mlpcreate2(), alglib.mlpbase.mlpcreateb0(), alglib.mlpbase.mlpcreateb1(), alglib.mlpbase.mlpcreateb2(), alglib.mlpbase.mlpcreatec0(), alglib.mlpbase.mlpcreatec1(), alglib.mlpbase.mlpcreatec2(), alglib.mlpbase.mlpcreater0(), alglib.mlpbase.mlpcreater1(), and alglib.mlpbase.mlpcreater2().
static void alglib.mlpbase.mlphessianbatchinternal (multilayerperceptron network, double xy[,], int ssize, bool naturalerr, ref double e, ref double[] grad, ref double h[,]) inline static private
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.multilayerperceptron.derror, alglib.mlpbase.multilayerperceptron.dfdnet, alglib.mlpbase.mlpactivationfunction(), alglib.mlpbase.mlpgrad(), alglib.mlpbase.mlpgradn(), alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpproperties(), alglib.mlpbase.multilayerperceptron.neurons, alglib.mlpbase.nfieldwidth, alglib.mlpbase.multilayerperceptron.nwbuf, alglib.math.sqr(), alglib.mlpbase.multilayerperceptron.structinfo, alglib.mlpbase.multilayerperceptron.weights, and alglib.mlpbase.multilayerperceptron.y.
Referenced by alglib.mlpbase.mlphessianbatch(), and alglib.mlpbase.mlphessiannbatch().
static void alglib.mlpbase.mlpinternalcalculategradient (multilayerperceptron network, double[] neurons, double[] weights, ref double[] derror, ref double[] grad, bool naturalerrorfunc) inline static private
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.multilayerperceptron.derror, alglib.mlpbase.multilayerperceptron.dfdnet, alglib.mlpbase.multilayerperceptron.neurons, alglib.mlpbase.nfieldwidth, alglib.mlpbase.multilayerperceptron.nwbuf, alglib.math.sqr(), and alglib.mlpbase.multilayerperceptron.structinfo.
Referenced by alglib.mlpbase.mlpgrad(), and alglib.mlpbase.mlpgradn().
static void alglib.mlpbase.mlpchunkedgradient (multilayerperceptron network, double xy[,], int cstart, int csize, ref double e, ref double[] grad, bool naturalerrorfunc) inline static private
References alglib.ap.assert(), alglib.mlpbase.multilayerperceptron.chunks, alglib.mlpbase.multilayerperceptron.columnmeans, alglib.mlpbase.multilayerperceptron.columnsigmas, alglib.mlpbase.mlpactivationfunction(), alglib.mlpbase.nfieldwidth, alglib.mlpbase.multilayerperceptron.nwbuf, alglib.mlpbase.safecrossentropy(), alglib.math.sqr(), alglib.mlpbase.multilayerperceptron.structinfo, and alglib.mlpbase.multilayerperceptron.weights.
Referenced by alglib.mlpbase.mlpgradbatch(), and alglib.mlpbase.mlpgradnbatch().
static double alglib.mlpbase.safecrossentropy (double t, double z) inline static private
References alglib.math.maxrealnumber, and alglib.math.minrealnumber.
Referenced by alglib.mlpbase.mlpchunkedgradient(), alglib.mlpbase.mlperrorn(), and alglib.mlpbase.mlpgradn().
static int alglib.mlpbase.mlpgradsplitcost () inline static
static int alglib.mlpbase.mlpgradsplitsize () inline static
static void alglib.mlpbase.mlpcreate0 (int nin, int nout, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpcreate1 (int nin, int nhid, int nout, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpcreate2 (int nin, int nhid1, int nhid2, int nout, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpcreateb0 (int nin, int nout, double b, double d, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpcreateb1 (int nin, int nhid, int nout, double b, double d, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpcreateb2 (int nin, int nhid1, int nhid2, int nout, double b, double d, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpcreater0 (int nin, int nout, double a, double b, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpcreater1 (int nin, int nhid, int nout, double a, double b, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpcreater2 (int nin, int nhid1, int nhid2, int nout, double a, double b, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpcreatec0 (int nin, int nout, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpcreatec1 (int nin, int nhid, int nout, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpcreatec2 (int nin, int nhid1, int nhid2, int nout, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpcopy (multilayerperceptron network1, multilayerperceptron network2) inline static
static void alglib.mlpbase.mlpcopyshared (multilayerperceptron network1, multilayerperceptron network2) inline static
Referenced by alglib.testmlpbaseunit.testprocessing().
static bool alglib.mlpbase.mlpsamearchitecture (multilayerperceptron network1, multilayerperceptron network2) inline static
static void alglib.mlpbase.mlpcopytunableparameters (multilayerperceptron network1, multilayerperceptron network2) inline static
Referenced by alglib.testmlpbaseunit.testprocessing().
static void alglib.mlpbase.mlpexporttunableparameters (multilayerperceptron network, ref double[] p, ref int pcount) inline static
Referenced by alglib.testmlpbaseunit.testprocessing().
static void alglib.mlpbase.mlpimporttunableparameters (multilayerperceptron network, double[] p) inline static
Referenced by alglib.testmlpbaseunit.testprocessing().
static void alglib.mlpbase.mlpserializeold (multilayerperceptron network, ref double[] ra, ref int rlen) inline static
static void alglib.mlpbase.mlpunserializeold (double[] ra, multilayerperceptron network) inline static
static void alglib.mlpbase.mlprandomize (multilayerperceptron network) inline static
static void alglib.mlpbase.mlprandomizefull (multilayerperceptron network) inline static
static void alglib.mlpbase.mlpinitpreprocessor (multilayerperceptron network, double xy[,], int ssize) inline static
static void alglib.mlpbase.mlpinitpreprocessorsparse (multilayerperceptron network, sparse.sparsematrix xy, int ssize) inline static
Referenced by alglib.testmlpbaseunit.testprocessing().
static void alglib.mlpbase.mlpinitpreprocessorsubset (multilayerperceptron network, double xy[,], int setsize, int[] idx, int subsetsize) inline static
static void alglib.mlpbase.mlpinitpreprocessorsparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] idx, int subsetsize) inline static
static void alglib.mlpbase.mlpproperties (multilayerperceptron network, ref int nin, ref int nout, ref int wcount) inline static
static int alglib.mlpbase.mlpntotal (multilayerperceptron network) inline static
static int alglib.mlpbase.mlpgetinputscount (multilayerperceptron network) inline static
static int alglib.mlpbase.mlpgetoutputscount (multilayerperceptron network) inline static
static int alglib.mlpbase.mlpgetweightscount (multilayerperceptron network) inline static
static bool alglib.mlpbase.mlpissoftmax (multilayerperceptron network) inline static
static int alglib.mlpbase.mlpgetlayerscount (multilayerperceptron network) inline static
static int alglib.mlpbase.mlpgetlayersize (multilayerperceptron network, int k) inline static
static void alglib.mlpbase.mlpgetinputscaling (multilayerperceptron network, int i, ref double mean, ref double sigma) inline static
static void alglib.mlpbase.mlpgetoutputscaling (multilayerperceptron network, int i, ref double mean, ref double sigma) inline static
static void alglib.mlpbase.mlpgetneuroninfo (multilayerperceptron network, int k, int i, ref int fkind, ref double threshold) inline static
static double alglib.mlpbase.mlpgetweight (multilayerperceptron network, int k0, int i0, int k1, int i1) inline static
static void alglib.mlpbase.mlpsetinputscaling (multilayerperceptron network, int i, double mean, double sigma) inline static
static void alglib.mlpbase.mlpsetoutputscaling (multilayerperceptron network, int i, double mean, double sigma) inline static
static void alglib.mlpbase.mlpsetneuroninfo (multilayerperceptron network, int k, int i, int fkind, double threshold) inline static
static void alglib.mlpbase.mlpsetweight (multilayerperceptron network, int k0, int i0, int k1, int i1, double w) inline static
static void alglib.mlpbase.mlpactivationfunction (double net, int k, ref double f, ref double df, ref double d2f) inline static
static void alglib.mlpbase.mlpprocess (multilayerperceptron network, double[] x, ref double[] y) inline static
static void alglib.mlpbase.mlpprocessi (multilayerperceptron network, double[] x, ref double[] y) inline static
static double alglib.mlpbase.mlperror (multilayerperceptron network, double xy[,], int npoints) inline static
static double alglib.mlpbase._pexec_mlperror (multilayerperceptron network, double xy[,], int npoints) inline static
Referenced by alglib.smp_mlperror().
static double alglib.mlpbase.mlperrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints) inline static
Referenced by alglib.mlperrorsparse(), and alglib.testmlpbaseunit.testgradient().
static double alglib.mlpbase._pexec_mlperrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints) inline static
Referenced by alglib.smp_mlperrorsparse().
static double alglib.mlpbase.mlperrorn (multilayerperceptron network, double xy[,], int ssize) inline static
static int alglib.mlpbase.mlpclserror (multilayerperceptron network, double xy[,], int npoints) inline static
static int alglib.mlpbase._pexec_mlpclserror (multilayerperceptron network, double xy[,], int npoints) inline static
Referenced by alglib.smp_mlpclserror().
static double alglib.mlpbase.mlprelclserror (multilayerperceptron network, double xy[,], int npoints) inline static
static double alglib.mlpbase._pexec_mlprelclserror (multilayerperceptron network, double xy[,], int npoints) inline static
Referenced by alglib.smp_mlprelclserror().
static double alglib.mlpbase.mlprelclserrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints) inline static
Referenced by alglib.mlprelclserrorsparse(), and alglib.testmlpbaseunit.testerr().
static double alglib.mlpbase._pexec_mlprelclserrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints) inline static
Referenced by alglib.smp_mlprelclserrorsparse().
static double alglib.mlpbase.mlpavgce (multilayerperceptron network, double xy[,], int npoints) inline static
static double alglib.mlpbase._pexec_mlpavgce (multilayerperceptron network, double xy[,], int npoints) inline static
Referenced by alglib.smp_mlpavgce().
static double alglib.mlpbase.mlpavgcesparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints) inline static
Referenced by alglib.mlpavgcesparse(), and alglib.testmlpbaseunit.testerr().
static double alglib.mlpbase._pexec_mlpavgcesparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints) inline static
Referenced by alglib.smp_mlpavgcesparse().
static double alglib.mlpbase.mlprmserror (multilayerperceptron network, double xy[,], int npoints) inline static
static double alglib.mlpbase._pexec_mlprmserror (multilayerperceptron network, double xy[,], int npoints) inline static
Referenced by alglib.smp_mlprmserror().
static double alglib.mlpbase.mlprmserrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints) inline static
Referenced by alglib.mlprmserrorsparse(), and alglib.testmlpbaseunit.testerr().
static double alglib.mlpbase._pexec_mlprmserrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints) inline static
Referenced by alglib.smp_mlprmserrorsparse().
static double alglib.mlpbase.mlpavgerror (multilayerperceptron network, double xy[,], int npoints) inline static
static double alglib.mlpbase._pexec_mlpavgerror (multilayerperceptron network, double xy[,], int npoints) inline static
Referenced by alglib.smp_mlpavgerror().
static double alglib.mlpbase.mlpavgerrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints) inline static
Referenced by alglib.mlpavgerrorsparse(), and alglib.testmlpbaseunit.testerr().
static double alglib.mlpbase._pexec_mlpavgerrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints) inline static
Referenced by alglib.smp_mlpavgerrorsparse().
static double alglib.mlpbase.mlpavgrelerror (multilayerperceptron network, double xy[,], int npoints) inline static
static double alglib.mlpbase._pexec_mlpavgrelerror (multilayerperceptron network, double xy[,], int npoints) inline static
Referenced by alglib.smp_mlpavgrelerror().
static double alglib.mlpbase.mlpavgrelerrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints) inline static
Referenced by alglib.mlpavgrelerrorsparse(), and alglib.testmlpbaseunit.testerr().
static double alglib.mlpbase._pexec_mlpavgrelerrorsparse (multilayerperceptron network, sparse.sparsematrix xy, int npoints) inline static
Referenced by alglib.smp_mlpavgrelerrorsparse().
static void alglib.mlpbase.mlpgrad (multilayerperceptron network, double[] x, double[] desiredy, ref double e, ref double[] grad) inline static
static void alglib.mlpbase.mlpgradn (multilayerperceptron network, double[] x, double[] desiredy, ref double e, ref double[] grad) inline static
static void alglib.mlpbase.mlpgradbatch (multilayerperceptron network, double xy[,], int ssize, ref double e, ref double[] grad) inline static
static void alglib.mlpbase._pexec_mlpgradbatch (multilayerperceptron network, double xy[,], int ssize, ref double e, ref double[] grad) inline static
Referenced by alglib.smp_mlpgradbatch().
static void alglib.mlpbase.mlpgradbatchsparse (multilayerperceptron network, sparse.sparsematrix xy, int ssize, ref double e, ref double[] grad) inline static
Referenced by alglib.mlpgradbatchsparse(), alglib.testmlpbaseunit.testgradient(), alglib.testmlpbaseunit.testmlpgbsubset(), and alglib.testmlptrainunit.testmlpgbsubset().
static void alglib.mlpbase._pexec_mlpgradbatchsparse (multilayerperceptron network, sparse.sparsematrix xy, int ssize, ref double e, ref double[] grad) inline static
Referenced by alglib.smp_mlpgradbatchsparse().
static void alglib.mlpbase.mlpgradbatchsubset (multilayerperceptron network, double xy[,], int setsize, int[] idx, int subsetsize, ref double e, ref double[] grad) inline static
Referenced by alglib.mlpgradbatchsubset(), alglib.testmlpbaseunit.testgradient(), alglib.testmlpbaseunit.testmlpgbsubset(), and alglib.testmlptrainunit.testmlpgbsubset().
static void alglib.mlpbase._pexec_mlpgradbatchsubset (multilayerperceptron network, double xy[,], int setsize, int[] idx, int subsetsize, ref double e, ref double[] grad) inline static
Referenced by alglib.smp_mlpgradbatchsubset().
static void alglib.mlpbase.mlpgradbatchsparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] idx, int subsetsize, ref double e, ref double[] grad) inline static
Referenced by alglib.mlpgradbatchsparsesubset(), alglib.testmlpbaseunit.testgradient(), alglib.testmlpbaseunit.testmlpgbsubset(), and alglib.testmlptrainunit.testmlpgbsubset().
static void alglib.mlpbase._pexec_mlpgradbatchsparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] idx, int subsetsize, ref double e, ref double[] grad) inline static
Referenced by alglib.smp_mlpgradbatchsparsesubset().
static void alglib.mlpbase.mlpgradbatchx (multilayerperceptron network, double densexy[,], sparse.sparsematrix sparsexy, int datasetsize, int datasettype, int[] idx, int subset0, int subset1, int subsettype, alglib.smp.shared_pool buf, alglib.smp.shared_pool gradbuf) inline static
static void alglib.mlpbase.mlpgradnbatch (multilayerperceptron network, double xy[,], int ssize, ref double e, ref double[] grad) inline static
static void alglib.mlpbase.mlphessiannbatch (multilayerperceptron network, double xy[,], int ssize, ref double e, ref double[] grad, ref double h[,]) inline static
static void alglib.mlpbase.mlphessianbatch (multilayerperceptron network, double xy[,], int ssize, ref double e, ref double[] grad, ref double h[,]) inline static
static void alglib.mlpbase.mlpinternalprocessvector (int[] structinfo, double[] weights, double[] columnmeans, double[] columnsigmas, ref double[] neurons, ref double[] dfdnet, double[] x, ref double[] y) inline static
static void alglib.mlpbase.mlpalloc (alglib.serializer s, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpserialize (alglib.serializer s, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpunserialize (alglib.serializer s, multilayerperceptron network) inline static
static void alglib.mlpbase.mlpallerrorssubset (multilayerperceptron network, double xy[,], int setsize, int[] subset, int subsetsize, modelerrors rep) inline static
Referenced by alglib.mlpallerrorssubset(), and alglib.testmlpbaseunit.testerr().
static void alglib.mlpbase._pexec_mlpallerrorssubset (multilayerperceptron network, double xy[,], int setsize, int[] subset, int subsetsize, modelerrors rep) inline static
Referenced by alglib.smp_mlpallerrorssubset().
static void alglib.mlpbase.mlpallerrorssparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] subset, int subsetsize, modelerrors rep) inline static
Referenced by alglib.mlpallerrorssparsesubset(), and alglib.testmlpbaseunit.testerr().
static void alglib.mlpbase._pexec_mlpallerrorssparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] subset, int subsetsize, modelerrors rep) inline static
Referenced by alglib.smp_mlpallerrorssparsesubset().
static double alglib.mlpbase.mlperrorsubset (multilayerperceptron network, double xy[,], int setsize, int[] subset, int subsetsize) inline static
Referenced by alglib.mlperrorsubset(), and alglib.testmlpbaseunit.testgradient().
static double alglib.mlpbase._pexec_mlperrorsubset (multilayerperceptron network, double xy[,], int setsize, int[] subset, int subsetsize) inline static
Referenced by alglib.smp_mlperrorsubset().
static double alglib.mlpbase.mlperrorsparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] subset, int subsetsize) inline static
Referenced by alglib.mlperrorsparsesubset(), and alglib.testmlpbaseunit.testgradient().
static double alglib.mlpbase._pexec_mlperrorsparsesubset (multilayerperceptron network, sparse.sparsematrix xy, int setsize, int[] subset, int subsetsize) inline static
Referenced by alglib.smp_mlperrorsparsesubset().
static void alglib.mlpbase.mlpallerrorsx (multilayerperceptron network, double densexy[,], sparse.sparsematrix sparsexy, int datasetsize, int datasettype, int[] idx, int subset0, int subset1, int subsettype, alglib.smp.shared_pool buf, modelerrors rep) inline static
static void alglib.mlpbase.addinputlayer (int ncount, ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc) inline static private
static void alglib.mlpbase.addbiasedsummatorlayer (int ncount, ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc) inline static private
static void alglib.mlpbase.addactivationlayer (int functype, ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc) inline static private
static void alglib.mlpbase.addzerolayer (ref int[] lsizes, ref int[] ltypes, ref int[] lconnfirst, ref int[] lconnlast, ref int lastproc) inline static private
static void alglib.mlpbase.hladdinputlayer (multilayerperceptron network, ref int connidx, ref int neuroidx, ref int structinfoidx, int nin) inline static private
static void alglib.mlpbase.hladdoutputlayer (multilayerperceptron network, ref int connidx, ref int neuroidx, ref int structinfoidx, ref int weightsidx, int k, int nprev, int nout, bool iscls, bool islinearout) inline static private
static void alglib.mlpbase.hladdhiddenlayer (multilayerperceptron network, ref int connidx, ref int neuroidx, ref int structinfoidx, ref int weightsidx, int k, int nprev, int ncur) inline static private
static void alglib.mlpbase.fillhighlevelinformation (multilayerperceptron network, int nin, int nhid1, int nhid2, int nout, bool iscls, bool islinearout) inline static private
static void alglib.mlpbase.mlpcreate (int nin, int nout, int[] lsizes, int[] ltypes, int[] lconnfirst, int[] lconnlast, int layerscount, bool isclsnet, multilayerperceptron network) inline static private
static void alglib.mlpbase.mlphessianbatchinternal (multilayerperceptron network, double xy[,], int ssize, bool naturalerr, ref double e, ref double[] grad, ref double h[,]) inline static private
static void alglib.mlpbase.mlpinternalcalculategradient (multilayerperceptron network, double[] neurons, double[] weights, ref double[] derror, ref double[] grad, bool naturalerrorfunc) inline static private
static void alglib.mlpbase.mlpchunkedgradient (multilayerperceptron network, double xy[,], int cstart, int csize, double[] batch4buf, double[] hpcbuf, ref double e, bool naturalerrorfunc) inline static private
static void alglib.mlpbase.mlpchunkedprocess (multilayerperceptron network, double xy[,], int cstart, int csize, double[] batch4buf, double[] hpcbuf) inline static private
static double alglib.mlpbase.safecrossentropy (double t, double z) inline static private
static void alglib.mlpbase.randomizebackwardpass (multilayerperceptron network, int neuronidx, double v) inline static private
Member Data Documentation
const int alglib.mlpbase.mlpvnum = 7
Referenced by alglib.mlpbase.mlpserializeold(), and alglib.mlpbase.mlpunserializeold().
const int alglib.mlpbase.mlpfirstversion = 0
const int alglib.mlpbase.nfieldwidth = 4
Referenced by alglib.mlpbase.mlpchunkedgradient(), alglib.mlpbase.mlpcreate(), alglib.mlpbase.mlpgetneuroninfo(), alglib.mlpbase.mlphessianbatchinternal(), alglib.mlpbase.mlpinternalcalculategradient(), alglib.mlpbase.mlpinternalprocessvector(), and alglib.mlpbase.mlpsetneuroninfo().
const int alglib.mlpbase.hlconnfieldwidth = 5
Referenced by alglib.mlpbase.hladdhiddenlayer(), alglib.mlpbase.hladdoutputlayer(), alglib.mlpbase.mlpgetweight(), and alglib.mlpbase.mlpsetweight().
const int alglib.mlpbase.hlnfieldwidth = 4
Referenced by alglib.mlpbase.hladdhiddenlayer(), alglib.mlpbase.hladdinputlayer(), alglib.mlpbase.hladdoutputlayer(), alglib.mlpbase.mlpgetneuroninfo(), and alglib.mlpbase.mlpsetneuroninfo().
const int alglib.mlpbase.chunksize = 32
Referenced by alglib.mlpbase.mlpgradbatch(), and alglib.mlpbase.mlpgradnbatch().
const int alglib.mlpbase.gradbasecasecost = 50000
const int alglib.mlpbase.microbatchsize = 64
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/dataanalysis.cs