IGLib: IG.MPetekLib.Application.Scripts.NonlinearOscillator._22SingleResCurveManyPhases Class Reference
IG.MPetekLib.Application.Scripts.NonlinearOscillator._22SingleResCurveManyPhases Class Reference
Static Public Member Functions
static void Run (string[] arguments)
Member Function Documentation
static void IG.MPetekLib.Application.Scripts.NonlinearOscillator._22SingleResCurveManyPhases.Run (string[] arguments) inline static
References IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenNonlinearOscillator.bOverJ, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.CalcSteadyStateAmplitudeVsDrivingFrequency(), IG.Lib.ColorScaleBase.Create(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenNonlinearOscillator.DOverJ, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.EndingDrivingAngularFrequency, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.Gamma, IG.Lib.ColorScaleBase.GetColor(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenNonlinearOscillator.M0OverJ, IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.NewCurveFromPlottableData(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.NSamplesForResonanceCurve, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.Solver, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.StartingDrivingAngularFrequency, IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.StepSize, and IG.MPetekLib.Algorithms.Plotting.PlotHQ.Window.
Referenced by IG.Script.AppMarkoPetek.App22SingleResCurveManyPhases().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/application/scripts/NonlinearOscillator/22SingleResCurveManyPhases.cs