IGLib: Meta.Numerics.Statistics.UncertainMeasurementSample< T > Class Template Reference
Meta.Numerics.Statistics.UncertainMeasurementSample< T > Class Template Reference
Represents a set of measurements.
Public Member Functions
UncertainMeasurementSample ()
Initializes a new, empty data set.
void Add (UncertainMeasurement< T > datum)
Adds a new data point to the set.
void Add (T x, double y, double dy)
Adds a new data point to the set.
void Add (IEnumerable< UncertainMeasurement< T >> data)
Adds a series of data points to the set.
bool Remove (UncertainMeasurement< T > datum)
Removes a data point from the set.
bool Contains (UncertainMeasurement< T > datum)
Determines whether the set contains the given data point.
void Clear ()
Removes all data points from the set.
FitResult FitToLinearFunction (Func< T, double >[] functions)
Fits the data to a linear combination of fit functions.
FitResult FitToFunction (Func< double[], T, double > function, double[] start)
Fits the data to an arbitrary parameterized function.
IEnumerator
< UncertainMeasurement< T > > GetEnumerator ()
Gets an enumerator over the measurements.
Properties
int Count [get]
Gets the size of the data set.
bool ICollection
< UncertainMeasurement< T > >. IsReadOnly [get]
Private Member Functions
void ICollection
< UncertainMeasurement< T > >. CopyTo (UncertainMeasurement< T >[] array, int offset)
System.Collections.IEnumerator
System.Collections.IEnumerable. GetEnumerator ()
Private Attributes
List< UncertainMeasurement< T > > data = new List<UncertainMeasurement<T>>()
Detailed Description
Represents a set of measurements.
Template Parameters
T The type of independent variable associated with each measurement.
Constructor & Destructor Documentation
Meta.Numerics.Statistics.UncertainMeasurementSample< T >.UncertainMeasurementSample () inline
Initializes a new, empty data set.
Member Function Documentation
void Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Add (UncertainMeasurement< T > datum) inline
Adds a new data point to the set.
Parameters
datum The data point.
void Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Add (T x, double y, double dy) inline
Adds a new data point to the set.
Parameters
x The value of the ordinate (independent variable).
y The value of the abcissa (dependent variable).
dy The uncertainty of the abcissa (dependent variable).
void Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Add (IEnumerable< UncertainMeasurement< T >> data) inline
Adds a series of data points to the set.
Parameters
data The data points.
bool Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Remove (UncertainMeasurement< T > datum) inline
Removes a data point from the set.
Parameters
datum The data point to remove.
Returns
True if the data point was found and removed; otherwise false.
bool Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Contains (UncertainMeasurement< T > datum) inline
Determines whether the set contains the given data point.
Parameters
datum The data point.
Returns
True if the set contains the given data point, otherwise false.
void Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Clear () inline
Removes all data points from the set.
FitResult Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToLinearFunction (Func< T, double >[] functions) inline
Fits the data to a linear combination of fit functions.
Parameters
functions The component functions.
Returns
A fit result containing the best-fit coefficients of the component functions and a &#x3C7;2 test of the quality of the fit.
Exceptions
ArgumentNullException functions is null.
InsufficientDataException There are fewer data points than fit parameters.
FitResult Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToFunction (Func< double[], T, double > function, double[] start) inline
Fits the data to an arbitrary parameterized function.
Parameters
function The fit function.
start An initial guess at the parameters.
Returns
A fit result containing the best-fitting function parameters and a &#x3C7;2 test of the quality of the fit.
Exceptions
ArgumentNullException function or start are null.
InsufficientDataException There are fewer data points than fit parameters.
References Meta.Numerics.Matrices.SymmetricMatrix.CholeskyDecomposition(), Meta.Numerics.Analysis.FunctionMath.FindMinimum(), and Meta.Numerics.Matrices.CholeskyDecomposition.Inverse().
IEnumerator<UncertainMeasurement<T> > Meta.Numerics.Statistics.UncertainMeasurementSample< T >.GetEnumerator () inline
Gets an enumerator over the measurements.
Returns
An enumerator over the measurements.
void ICollection<UncertainMeasurement<T> >. Meta.Numerics.Statistics.UncertainMeasurementSample< T >.CopyTo (UncertainMeasurement< T >[] array, int offset) inline private
System.Collections.IEnumerator System.Collections.IEnumerable. Meta.Numerics.Statistics.UncertainMeasurementSample< T >.GetEnumerator () inline private
Member Data Documentation
List<UncertainMeasurement<T> > Meta.Numerics.Statistics.UncertainMeasurementSample< T >.data = new List<UncertainMeasurement<T>>() private
Property Documentation
int Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Count get
Gets the size of the data set.
bool ICollection<UncertainMeasurement<T> >. Meta.Numerics.Statistics.UncertainMeasurementSample< T >.IsReadOnly get private
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/UncertainMeasurementSample.cs