IGLib: IG.Old.ComplexVector_OldNumerics Class Reference
IG.Old.ComplexVector_OldNumerics Class Reference
Complex vector.
Public Member Functions
ComplexVector_OldNumerics (int dimension)
ComplexVector_OldNumerics (int dimension, Complex_OldNumerics comp)
ComplexVector_OldNumerics (Complex_OldNumerics[] array)
ComplexVector_OldNumerics (ComplexVector_OldNumerics cv)
Public Member Functions inherited from IG.Old.Vector_OldNumerics< ComponentType >
Vector_OldNumerics (int dim1, ComponentType comp)
Vector_OldNumerics (ComponentType[] array)
void Init (int dim)
Initializes a matrix with dimendions dim1 and dim2.
void Init (int dim, ComponentType comp)
Initializes a vector with dimendion length and sets all vec to comp.
void Init (ComponentType[] array)
Initializes a vector with dimendion length and sets all vec to comp.
void Init (Vector_OldNumerics< ComponentType > v)
Initializes a vector with dimendion length and sets all vec to comp.
override string ToString ()
Redefinition of Tostring(), converts a vector to string representation.
void Add (Vector_OldNumerics< ComponentType > a)
XVector addition.
void Subtract (Vector_OldNumerics< ComponentType > a)
XVector subtraction.
void Multiply (ComponentType scalar)
Multiplication of a vector by a scalar.
ComponentType RightScalarProduct (Vector_OldNumerics< ComponentType > a)
Right scalar product.
ComponentType LeftScalarProduct (Vector_OldNumerics< ComponentType > a)
Right scalar product.
Static Public Member Functions
static ComplexVector_OldNumerics operator+ (ComplexVector_OldNumerics a, ComplexVector_OldNumerics b)
static ComplexVector_OldNumerics operator- (ComplexVector_OldNumerics a, ComplexVector_OldNumerics b)
static ComplexVector_OldNumerics operator* (ComplexVector_OldNumerics a, ComplexVector_OldNumerics b)
static ComplexVector_OldNumerics operator* (ComplexVector_OldNumerics a, Complex_OldNumerics b)
static ComplexVector_OldNumerics operator* (Complex_OldNumerics b, ComplexVector_OldNumerics a)
Static Public Member Functions inherited from IG.Old.Vector_OldNumerics< ComponentType >
static ComponentType[] Copy (Vector_OldNumerics< ComponentType > v)
static void Example ()
Protected Member Functions
ComplexVector_OldNumerics ()
override Complex_OldNumerics Add (Complex_OldNumerics a, Complex_OldNumerics b)
override Complex_OldNumerics Subtract (Complex_OldNumerics a, Complex_OldNumerics b)
override Complex_OldNumerics Multiply (Complex_OldNumerics a, Complex_OldNumerics b)
override Complex_OldNumerics Divide (Complex_OldNumerics a, Complex_OldNumerics b)
override Complex_OldNumerics Negative (Complex_OldNumerics a)
override Complex_OldNumerics Inverse (Complex_OldNumerics a)
override Complex_OldNumerics Conjugate (Complex_OldNumerics a)
Protected Member Functions inherited from IG.Old.Vector_OldNumerics< ComponentType >
Vector_OldNumerics ()
abstract ComponentType Add (ComponentType a, ComponentType b)
abstract ComponentType Subtract (ComponentType a, ComponentType b)
abstract ComponentType Multiply (ComponentType a, ComponentType b)
abstract ComponentType Divide (ComponentType a, ComponentType b)
abstract ComponentType Negative (ComponentType a)
abstract ComponentType Inverse (ComponentType a)
abstract ComponentType Conjugate (ComponentType a)
Properties
override Complex_OldNumerics Zero [get]
Properties inherited from IG.Old.Vector_OldNumerics< ComponentType >
int Dimension [get]
Returns vector dimension.
int Dimension2 [get]
Returns vector dimension.
int d [get]
Synonyme for Dimension, returns vector dimension.
virtual ComponentType this[int ind] [get, set]
Gets or sets a specific vector componene.
abstract ComponentType Zero [get]
Additional Inherited Members
Protected Attributes inherited from IG.Old.Vector_OldNumerics< ComponentType >
int _dim
ComponentType[] _tab
Detailed Description
Complex vector.
Constructor & Destructor Documentation
IG.Old.ComplexVector_OldNumerics.ComplexVector_OldNumerics () inline protected
IG.Old.ComplexVector_OldNumerics.ComplexVector_OldNumerics (int dimension) inline
IG.Old.ComplexVector_OldNumerics.ComplexVector_OldNumerics (int dimension, Complex_OldNumerics comp) inline
IG.Old.ComplexVector_OldNumerics.ComplexVector_OldNumerics (Complex_OldNumerics[] array) inline
IG.Old.ComplexVector_OldNumerics.ComplexVector_OldNumerics (ComplexVector_OldNumerics cv) inline
Member Function Documentation
override Complex_OldNumerics IG.Old.ComplexVector_OldNumerics.Add (Complex_OldNumerics a, Complex_OldNumerics b) inline protected
Referenced by IG.Old.ComplexVector_OldNumerics.operator+().
override Complex_OldNumerics IG.Old.ComplexVector_OldNumerics.Subtract (Complex_OldNumerics a, Complex_OldNumerics b) inline protected
Referenced by IG.Old.ComplexVector_OldNumerics.operator-().
override Complex_OldNumerics IG.Old.ComplexVector_OldNumerics.Multiply (Complex_OldNumerics a, Complex_OldNumerics b) inline protected
Referenced by IG.Old.ComplexVector_OldNumerics.operator*().
override Complex_OldNumerics IG.Old.ComplexVector_OldNumerics.Divide (Complex_OldNumerics a, Complex_OldNumerics b) inline protected
override Complex_OldNumerics IG.Old.ComplexVector_OldNumerics.Negative (Complex_OldNumerics a) inline protected
References IG.Old.Complex_OldNumerics.Zero.
override Complex_OldNumerics IG.Old.ComplexVector_OldNumerics.Inverse (Complex_OldNumerics a) inline protected
References IG.Old.Complex_OldNumerics.One.
override Complex_OldNumerics IG.Old.ComplexVector_OldNumerics.Conjugate (Complex_OldNumerics a) inline protected
References IG.Old.Complex_OldNumerics.Conjugate().
static ComplexVector_OldNumerics IG.Old.ComplexVector_OldNumerics.operator+ (ComplexVector_OldNumerics a, ComplexVector_OldNumerics b) inline static
References IG.Old.ComplexVector_OldNumerics.Add().
static ComplexVector_OldNumerics IG.Old.ComplexVector_OldNumerics.operator- (ComplexVector_OldNumerics a, ComplexVector_OldNumerics b) inline static
References IG.Old.ComplexVector_OldNumerics.Subtract().
static ComplexVector_OldNumerics IG.Old.ComplexVector_OldNumerics.operator* (ComplexVector_OldNumerics a, ComplexVector_OldNumerics b) inline static
References IG.Old.Vector_OldNumerics< ComponentType >.RightScalarProduct().
static ComplexVector_OldNumerics IG.Old.ComplexVector_OldNumerics.operator* (ComplexVector_OldNumerics a, Complex_OldNumerics b) inline static
References IG.Old.ComplexVector_OldNumerics.Multiply().
static ComplexVector_OldNumerics IG.Old.ComplexVector_OldNumerics.operator* (Complex_OldNumerics b, ComplexVector_OldNumerics a) inline static
References IG.Old.ComplexVector_OldNumerics.Multiply().
Property Documentation
override Complex_OldNumerics IG.Old.ComplexVector_OldNumerics.Zero get protected
The documentation for this class was generated from the following file:
igtest/IGLibTestDevExt/z_old/OldNumeric.cs