IGLib: IG.Gr3d.TestVtkGraphic Class Reference
IG.Gr3d.TestVtkGraphic Class Reference
Tests of 3D graphics enabled by ActiViz (VTK wrapper library).
Static Public Member Functions
static void RunBase ()
static void ExampleNeuralTadej (int numXTrainPoints, int numYTrainPoint)
Static Public Member Functions inherited from IG.Gr3d.TestVtkGraphicBase
static void Run ()
static void Test1 ()
static void Test2 ()
static void ColorBar ()
static void Legend ()
static void ExampleParametricCurve (int numT)
Example of plotting parametric curves in 3D space.
static void ExampleStructuredGridVolumeContours ()
Example that demonstrates generaton of contours on a 3D structured grid.
static void ExampleCellsGridContours ()
ExamExample of plotting contours on surfaces in 3D (graphs of functions of 2 variables or parametric surfaces) by using graphic primitives (cells) connected to polydata. Default division numbers of the shown graph are taken.
static void ExampleCellsGridContours (int sizex, int sizey, int numContours)
Example of plotting contours on surfaces in 3D (graphs of functions of 2 variables or parametric surfaces) by using graphic primitives (cells) connected to polydata.
static void ExampleCellsGridEfficient ()
Example of efficient plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces) by using graphic primitives (cells). Default division numbers of the shown graph are taken.
static void ExampleQuadCells ()
Example that demonstrates the ability to use simple primitives for plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces).
static void ExampleQuadCells (int sizex, int sizey)
Example that demonstrates the ability to use simple primitives for plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces).
static void ExampleStructuredGrid ()
Example that demonstrates the ability to use structured grids for plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces).
static void ExampleAxisHendler ()
static void ExampleStructuredGrid (int sizex, int sizey, int sizez)
Example that demonstrates the ability to use structured grids for plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces).
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
Additional Inherited Members
Properties inherited from IG.Gr3d.TestVtkGraphicBase
Examples Modelling Cxx
Delaunay3D.cxx but only outer
contours on body surface.int
int int numContours [set]
Detailed Description
Tests of 3D graphics enabled by ActiViz (VTK wrapper library).
$A Tako78 Sep11; Igor Oct11;
Member Function Documentation
static void IG.Gr3d.TestVtkGraphic.RunBase () inline static
static void IG.Gr3d.TestVtkGraphic.ExampleNeuralTadej (int numXTrainPoints, int numYTrainPoint) inline static
References IG.Num.SampledDataSet.AddElement(), IG.Gr3d.VtkSurfacePlotBase.AddLine(), IG.Gr3d.VtkSurfacePlotBase.AddPoint(), IG.Gr3d.VtkPlotBase.CreateAndShow(), IG.Lib.ColorScaleBase.CreateBlueRedYellow(), IG.Gr3d.VtkSurfacePlotBase.CreateCustomPlot(), IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Neural.NeuralNetworks.Example3D(), IG.Num.Field< TElement >.GetValue(), IG.Num.SampledDataSet.InputLength, IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Num.SampledDataSet.OutputLength, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Gr3d.VtkSurfacePlotBase.PointColor, IG.Gr3d.VtkSurfacePlotBase.PointColorOpacity, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkPlotBase.ShowPlot(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, IG.Gr3d.VtkSurfacePlot.ValueFunctionOfCoordinates, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
The documentation for this class was generated from the following file:
shelldev/lib/extended/LibShellExt/highlevel_and_testing/Testing_Development/VTK/TestVtkGraphicNeural.cs