IGLib: NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture Class Reference
NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture Class Reference
Summary description for ArrayEqualsFailureMessageFixture.
Public Member Functions
void ArraysHaveDifferentRanks ()
void ExpectedArrayIsLonger ()
void ActualArrayIsLonger ()
void FailureOnSingleDimensionedArrays ()
void DoubleDimensionedArrays ()
void TripleDimensionedArrays ()
void FiveDimensionedArrays ()
void JaggedArrays ()
void JaggedArrayComparedToSimpleArray ()
void ArraysWithDifferentRanksAsCollection ()
void ArraysWithDifferentDimensionsAsCollection ()
void SameLengthDifferentContent ()
void ArraysDeclaredAsDifferentTypes ()
void ArrayAndCollection_Failure ()
void DifferentArrayTypesEqualFails ()
Private Attributes
readonly string NL = NUnit.Env.NewLine
Detailed Description
Summary description for ArrayEqualsFailureMessageFixture.
Member Function Documentation
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysHaveDifferentRanks () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ExpectedArrayIsLonger () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ActualArrayIsLonger () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.FailureOnSingleDimensionedArrays () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.DoubleDimensionedArrays () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.TripleDimensionedArrays () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.FiveDimensionedArrays () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.JaggedArrays () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.JaggedArrayComparedToSimpleArray () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysWithDifferentRanksAsCollection () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysWithDifferentDimensionsAsCollection () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.SameLengthDifferentContent () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysDeclaredAsDifferentTypes () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArrayAndCollection_Failure () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.DifferentArrayTypesEqualFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
Member Data Documentation
readonly string NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.NL = NUnit.Env.NewLine private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/ArrayEqualsFailureMessageFixture.cs