IGLib: alglib.linlsqr Class Reference
alglib.linlsqr Class Reference
Classes
class linlsqrreport
class linlsqrstate
Static Public Member Functions
static void linlsqrcreate (int m, int n, linlsqrstate state)
static void linlsqrsetb (linlsqrstate state, double[] b)
static void linlsqrsetlambdai (linlsqrstate state, double lambdai)
static bool linlsqriteration (linlsqrstate state)
static void linlsqrsolvesparse (linlsqrstate state, sparse.sparsematrix a, double[] b)
static void linlsqrsetcond (linlsqrstate state, double epsa, double epsb, int maxits)
static void linlsqrresults (linlsqrstate state, ref double[] x, linlsqrreport rep)
static void linlsqrsetxrep (linlsqrstate state, bool needxrep)
static void linlsqrrestart (linlsqrstate state)
static void linlsqrcreate (int m, int n, linlsqrstate state)
static void linlsqrsetb (linlsqrstate state, double[] b)
static void linlsqrsetprecunit (linlsqrstate state)
static void linlsqrsetprecdiag (linlsqrstate state)
static void linlsqrsetlambdai (linlsqrstate state, double lambdai)
static bool linlsqriteration (linlsqrstate state)
static void linlsqrsolvesparse (linlsqrstate state, sparse.sparsematrix a, double[] b)
static void linlsqrsetcond (linlsqrstate state, double epsa, double epsb, int maxits)
static void linlsqrresults (linlsqrstate state, ref double[] x, linlsqrreport rep)
static void linlsqrsetxrep (linlsqrstate state, bool needxrep)
static void linlsqrrestart (linlsqrstate state)
Public Attributes
const double atol = 1.0E-6
const double btol = 1.0E-6
Static Private Member Functions
static void clearrfields (linlsqrstate state)
static void clearrfields (linlsqrstate state)
Member Function Documentation
static void alglib.linlsqr.linlsqrcreate (int m, int n, linlsqrstate state) inline static
References alglib.ap.assert(), alglib.linlsqr.atol, alglib.linlsqr.linlsqrstate.b, alglib.linlsqr.btol, alglib.linlsqr.linlsqrstate.d, alglib.linlsqr.linlsqrstate.epsa, alglib.linlsqr.linlsqrstate.epsb, alglib.linlsqr.linlsqrstate.epsc, alglib.rcommstate.ia, alglib.linlsqr.linlsqrstate.lambdai, alglib.linlsqr.linlsqrstate.m, alglib.math.machineepsilon, alglib.linlsqr.linlsqrstate.maxits, alglib.linlsqr.linlsqrstate.mtv, alglib.linlsqr.linlsqrstate.mv, alglib.linlsqr.linlsqrstate.n, alglib.linlsqr.linlsqrstate.nes, alglib.normestimator.normestimatorcreate(), alglib.linlsqr.linlsqrstate.omegai, alglib.linlsqr.linlsqrstate.omegaip1, alglib.rcommstate.ra, alglib.linlsqr.linlsqrstate.rstate, alglib.linlsqr.linlsqrstate.running, alglib.linlsqr.linlsqrstate.rx, alglib.rcommstate.stage, alglib.linlsqr.linlsqrstate.ui, alglib.linlsqr.linlsqrstate.uip1, alglib.linlsqr.linlsqrstate.vi, alglib.linlsqr.linlsqrstate.vip1, alglib.linlsqr.linlsqrstate.x, and alglib.linlsqr.linlsqrstate.xrep.
Referenced by alglib.testlinlsqrunit.analytictest(), alglib.testlinlsqrunit.bidiagonaltest(), alglib.linlsqrcreate(), alglib.testlinlsqrunit.mwcranksvdtest(), alglib.testlinlsqrunit.mwicranksvdtest(), alglib.testlinlsqrunit.preconditionertest(), alglib.testlinlsqrunit.reportcorrectnesstest(), alglib.testlinlsqrunit.stoppingcriteriatest(), alglib.testlinlsqrunit.svdtest(), and alglib.testlinlsqrunit.zeromatrixtest().
static void alglib.linlsqr.linlsqrsetb (linlsqrstate state, double[] b) inline static
References alglib.ap.assert(), alglib.linlsqr.linlsqrstate.b, alglib.linlsqr.linlsqrstate.bnorm2, alglib.apserv.isfinitevector(), alglib.linlsqr.linlsqrstate.m, and alglib.linlsqr.linlsqrstate.running.
Referenced by alglib.testlinlsqrunit.analytictest(), alglib.testlinlsqrunit.bidiagonaltest(), alglib.linlsqr.linlsqrsolvesparse(), alglib.testlinlsqrunit.mwcranksvdtest(), alglib.testlinlsqrunit.mwicranksvdtest(), alglib.testlinlsqrunit.reportcorrectnesstest(), alglib.testlinlsqrunit.stoppingcriteriatest(), alglib.testlinlsqrunit.svdtest(), and alglib.testlinlsqrunit.zeromatrixtest().
static void alglib.linlsqr.linlsqrsetlambdai (linlsqrstate state, double lambdai) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.linlsqr.linlsqrstate.lambdai, and alglib.linlsqr.linlsqrstate.running.
Referenced by alglib.linlsqrsetlambdai(), alglib.testlinlsqrunit.mwcranksvdtest(), alglib.testlinlsqrunit.mwicranksvdtest(), alglib.testlinlsqrunit.reportcorrectnesstest(), and alglib.testlinlsqrunit.svdtest().
static bool alglib.linlsqr.linlsqriteration (linlsqrstate state) inline static
References alglib.linlsqr.linlsqrstate.alphai, alglib.linlsqr.linlsqrstate.alphaip1, alglib.linlsqr.linlsqrstate.anorm, alglib.ap.assert(), alglib.linlsqr.linlsqrstate.b, alglib.linlsqr.linlsqrstate.betai, alglib.linlsqr.linlsqrstate.betaip1, alglib.linlsqr.linlsqrstate.bnorm2, alglib.linlsqr.linlsqrstate.ci, alglib.linlsqr.clearrfields(), alglib.linlsqr.linlsqrstate.d, alglib.linlsqr.linlsqrstate.dnorm, alglib.linlsqr.linlsqrstate.epsa, alglib.linlsqr.linlsqrstate.epsb, alglib.linlsqr.linlsqrstate.epsc, alglib.rcommstate.ia, alglib.linlsqr.linlsqrstate.lambdai, alglib.linlsqr.linlsqrstate.m, alglib.linlsqr.linlsqrstate.maxits, alglib.linlsqr.linlsqrstate.mtv, alglib.linlsqr.linlsqrstate.mv, alglib.linlsqr.linlsqrstate.n, alglib.linlsqr.linlsqrstate.needmtv, alglib.linlsqr.linlsqrstate.needmv, alglib.linlsqr.linlsqrstate.nes, alglib.normestimator.normestimatoriteration(), alglib.normestimator.normestimatorrestart(), alglib.normestimator.normestimatorresults(), alglib.linlsqr.linlsqrstate.omegai, alglib.linlsqr.linlsqrstate.omegaip1, alglib.linlsqr.linlsqrstate.phibari, alglib.linlsqr.linlsqrstate.phibarip1, alglib.linlsqr.linlsqrstate.phii, alglib.linlsqr.linlsqrstate.r2, alglib.rcommstate.ra, alglib.linlsqr.linlsqrstate.repiterationscount, alglib.linlsqr.linlsqrstate.repnmv, alglib.linlsqr.linlsqrstate.repterminationtype, alglib.linlsqr.linlsqrstate.rhobari, alglib.linlsqr.linlsqrstate.rhobarip1, alglib.linlsqr.linlsqrstate.rhoi, alglib.linlsqr.linlsqrstate.rstate, alglib.linlsqr.linlsqrstate.running, alglib.linlsqr.linlsqrstate.rx, alglib.apserv.safepythag2(), alglib.linlsqr.linlsqrstate.si, alglib.rcommstate.stage, alglib.linlsqr.linlsqrstate.theta, alglib.linlsqr.linlsqrstate.ui, alglib.linlsqr.linlsqrstate.uip1, alglib.linlsqr.linlsqrstate.vi, alglib.linlsqr.linlsqrstate.vip1, alglib.linlsqr.linlsqrstate.x, alglib.linlsqr.linlsqrstate.xrep, and alglib.linlsqr.linlsqrstate.xupdated.
Referenced by alglib.testlinlsqrunit.analytictest(), alglib.testlinlsqrunit.bidiagonaltest(), alglib.linlsqr.linlsqrsolvesparse(), alglib.testlinlsqrunit.mwcranksvdtest(), alglib.testlinlsqrunit.mwicranksvdtest(), alglib.testlinlsqrunit.reportcorrectnesstest(), alglib.testlinlsqrunit.stoppingcriteriatest(), alglib.testlinlsqrunit.svdtest(), and alglib.testlinlsqrunit.zeromatrixtest().
static void alglib.linlsqr.linlsqrsolvesparse (linlsqrstate state, sparse.sparsematrix a, double[] b) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrrestart(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrstate.m, alglib.linlsqr.linlsqrstate.mtv, alglib.linlsqr.linlsqrstate.mv, alglib.linlsqr.linlsqrstate.needmtv, alglib.linlsqr.linlsqrstate.needmv, alglib.linlsqr.linlsqrstate.running, alglib.sparse.sparsemtv(), alglib.sparse.sparsemv(), and alglib.linlsqr.linlsqrstate.x.
Referenced by alglib.linlsqrsolvesparse(), alglib.testlinlsqrunit.preconditionertest(), and alglib.testlinlsqrunit.svdtest().
static void alglib.linlsqr.linlsqrsetcond (linlsqrstate state, double epsa, double epsb, int maxits) inline static
References alglib.ap.assert(), alglib.linlsqr.atol, alglib.linlsqr.btol, alglib.linlsqr.linlsqrstate.epsa, alglib.linlsqr.linlsqrstate.epsb, alglib.math.isfinite(), alglib.linlsqr.linlsqrstate.maxits, alglib.linlsqr.linlsqrstate.n, and alglib.linlsqr.linlsqrstate.running.
Referenced by alglib.testlinlsqrunit.analytictest(), alglib.testlinlsqrunit.bidiagonaltest(), alglib.linlsqrsetcond(), alglib.testlinlsqrunit.mwcranksvdtest(), alglib.testlinlsqrunit.mwicranksvdtest(), alglib.testlinlsqrunit.preconditionertest(), alglib.testlinlsqrunit.reportcorrectnesstest(), alglib.testlinlsqrunit.stoppingcriteriatest(), and alglib.testlinlsqrunit.zeromatrixtest().
static void alglib.linlsqr.linlsqrresults (linlsqrstate state, ref double[] x, linlsqrreport rep) inline static
References alglib.ap.assert(), alglib.linlsqr.linlsqrreport.iterationscount, alglib.linlsqr.linlsqrstate.n, alglib.linlsqr.linlsqrreport.nmv, alglib.linlsqr.linlsqrstate.repiterationscount, alglib.linlsqr.linlsqrstate.repnmv, alglib.linlsqr.linlsqrstate.repterminationtype, alglib.linlsqr.linlsqrstate.running, alglib.linlsqr.linlsqrstate.rx, and alglib.linlsqr.linlsqrreport.terminationtype.
Referenced by alglib.testlinlsqrunit.bidiagonaltest(), alglib.linlsqrresults(), alglib.testlinlsqrunit.mwcranksvdtest(), alglib.testlinlsqrunit.mwicranksvdtest(), alglib.testlinlsqrunit.preconditionertest(), alglib.testlinlsqrunit.reportcorrectnesstest(), alglib.testlinlsqrunit.stoppingcriteriatest(), alglib.testlinlsqrunit.svdtest(), and alglib.testlinlsqrunit.zeromatrixtest().
static void alglib.linlsqr.linlsqrsetxrep (linlsqrstate state, bool needxrep) inline static
References alglib.linlsqr.linlsqrstate.xrep.
Referenced by alglib.testlinlsqrunit.analytictest(), alglib.linlsqrsetxrep(), and alglib.testlinlsqrunit.reportcorrectnesstest().
static void alglib.linlsqr.linlsqrrestart (linlsqrstate state) inline static
References alglib.linlsqr.clearrfields(), alglib.rcommstate.ia, alglib.rcommstate.ra, alglib.linlsqr.linlsqrstate.rstate, and alglib.rcommstate.stage.
Referenced by alglib.linlsqr.linlsqrsolvesparse(), and alglib.testlinlsqrunit.svdtest().
static void alglib.linlsqr.clearrfields (linlsqrstate state) inline static private
References alglib.linlsqr.linlsqrstate.needmtv, alglib.linlsqr.linlsqrstate.needmv, alglib.linlsqr.linlsqrstate.needmv2, alglib.linlsqr.linlsqrstate.needprec, alglib.linlsqr.linlsqrstate.needvmv, and alglib.linlsqr.linlsqrstate.xupdated.
Referenced by alglib.linlsqr.linlsqriteration(), and alglib.linlsqr.linlsqrrestart().
static void alglib.linlsqr.linlsqrcreate (int m, int n, linlsqrstate state) inline static
References alglib.ap.assert(), alglib.linlsqr.atol, alglib.linlsqr.btol, alglib.math.machineepsilon, and alglib.normestimator.normestimatorcreate().
static void alglib.linlsqr.linlsqrsetb (linlsqrstate state, double[] b) inline static
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
static void alglib.linlsqr.linlsqrsetprecunit (linlsqrstate state) inline static
References alglib.ap.assert().
Referenced by alglib.linlsqrsetprecunit(), alglib.testlinlsqrunit.preconditionertest(), and alglib.testlinlsqrunit.svdtest().
static void alglib.linlsqr.linlsqrsetprecdiag (linlsqrstate state) inline static
References alglib.ap.assert().
Referenced by alglib.linlsqrsetprecdiag(), and alglib.testlinlsqrunit.preconditionertest().
static void alglib.linlsqr.linlsqrsetlambdai (linlsqrstate state, double lambdai) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
static bool alglib.linlsqr.linlsqriteration (linlsqrstate state) inline static
References alglib.ap.assert(), alglib.linlsqr.clearrfields(), alglib.normestimator.normestimatoriteration(), alglib.normestimator.normestimatorrestart(), alglib.normestimator.normestimatorresults(), and alglib.apserv.safepythag2().
static void alglib.linlsqr.linlsqrsolvesparse (linlsqrstate state, sparse.sparsematrix a, double[] b) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrrestart(), alglib.linlsqr.linlsqrsetb(), alglib.apserv.rvectorsetlengthatleast(), alglib.sparse.sparseenumerate(), alglib.sparse.sparsemtv(), alglib.sparse.sparsemv(), and alglib.math.sqr().
static void alglib.linlsqr.linlsqrsetcond (linlsqrstate state, double epsa, double epsb, int maxits) inline static
References alglib.ap.assert(), alglib.linlsqr.atol, alglib.linlsqr.btol, and alglib.math.isfinite().
static void alglib.linlsqr.linlsqrresults (linlsqrstate state, ref double[] x, linlsqrreport rep) inline static
References alglib.ap.assert().
static void alglib.linlsqr.linlsqrsetxrep (linlsqrstate state, bool needxrep) inline static
static void alglib.linlsqr.linlsqrrestart (linlsqrstate state) inline static
References alglib.linlsqr.clearrfields().
static void alglib.linlsqr.clearrfields (linlsqrstate state) inline static private
Member Data Documentation
const double alglib.linlsqr.atol = 1.0E-6
Referenced by alglib.linlsqr.linlsqrcreate(), and alglib.linlsqr.linlsqrsetcond().
const double alglib.linlsqr.btol = 1.0E-6
Referenced by alglib.linlsqr.linlsqrcreate(), and alglib.linlsqr.linlsqrsetcond().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/solvers.cs