IGLib: IG.Crypt.Asym Class Reference
IG.Crypt.Asym Class Reference
Static Public Member Functions
static X509Certificate2 LoadCertificate (string certificateName, StoreName storeName, StoreLocation storeLocation, bool validOnly)
Loads a certificate from a certificate store.
static X509Certificate2 LoadCertificate (string certificateName)
static void CertSetDefault ()
static void CertCreate ()
static void CreateTestCertificate (string CertificateName, string StorageName, bool UserStore, string ContainerName, string CommandPath, bool ReportConsole, bool ReportForm, string OutputFile, string ValidFrom, string ValidTo)
static void CreateTestCertificate (string CertificateName, string StorageName, bool UserStore, string ContainerName, string CommandPath, bool ReportConsole, bool ReportForm, string OutputFile)
static void CreateTestCertificate (string CertificateName, string StorageName, bool UserStore, string ContainerName, string CommandPath)
static void CreateTestCertificate (string CertificateName, string StorageName, bool UserStore, string ContainerName)
static void CreateTestCertificate (string CertificateName)
static void CreateTestCertificate ()
static void LoadKeys (string containername)
static void DeleteKeys (string containername)
static void AssignParameter (string ContainerName)
static void AssignNewKey (string ContainterName, string PrivateKeyFileName, string PublicKeyFileName)
static string EncryptData (string ContainterName, string data2Encrypt, string XMLPublicKeyFileName)
static string DecryptData (string ContainterName, string data2Decrypt, string PrivateKeyFilename)
static void SignXml (XmlDocument Doc, RSA Key)
static Boolean VerifyXml (XmlDocument Doc, RSA Key)
static void TestXML (String[] args)
static void TestEncrypt (string message)
Static Public Attributes
static string TestContainerName = "Test_RSA_container"
static string CertName = "Test_Certificate"
static bool CertUserStore = true
Private Member Functions
RSACryptoServiceProvider CertPrivateKey (X509Certificate2 cert)
RSACryptoServiceProvider CertPublicKey (X509Certificate2 cert)
Static Private Member Functions
static byte[] EncryptMessage (byte[] plaintext, RSAParameters rsaParams)
static byte[] DecryptMessage (byte[] ciphertext, CspParameters cspParams)
Static Private Attributes
static string TestCertificateName = "Test_Certificate"
static string CertStorage = "my"
certificate name in the storage
static string CertContainer = "Test_RSA_container"
storage name
static string CertCommand = "makecert.exe"
key container name
static string CertFile = null
system command to call the certificate maker
static string CertValidFrom = null
output file (should be .cert) to which certificate is exported
static string CertValidTo = null
static bool CertRepConsole = true
static bool CertRepForm = false
static RSACryptoServiceProvider rsaProvider
Member Function Documentation
static X509Certificate2 IG.Crypt.Asym.LoadCertificate (string certificateName, StoreName storeName, StoreLocation storeLocation, bool validOnly) inline static
Loads a certificate from a certificate store.
static X509Certificate2 IG.Crypt.Asym.LoadCertificate (string certificateName) inline static
RSACryptoServiceProvider IG.Crypt.Asym.CertPrivateKey (X509Certificate2 cert) inline private
RSACryptoServiceProvider IG.Crypt.Asym.CertPublicKey (X509Certificate2 cert) inline private
static void IG.Crypt.Asym.CertSetDefault () inline static
Referenced by IG.Crypt.encryption_test.Main().
static void IG.Crypt.Asym.CertCreate () inline static
Referenced by IG.Crypt.encryption_test.Main().
static void IG.Crypt.Asym.CreateTestCertificate (string CertificateName, string StorageName, bool UserStore, string ContainerName, string CommandPath, bool ReportConsole, bool ReportForm, string OutputFile, string ValidFrom, string ValidTo) inline static
Creates a new certificate named CertificateName, with keys stored in the container named ContainerName, and stored in the storage denoted by StorageName. If UserStore==true then the certificate is stored in the current user's store, otherwise it is stored in the machine store. If command path is a string of non-zero length then it specified the path of the makecert system command. If ReportConsole==true then reporting is performed on standard console. If ReportForm is true then reporting is performed to IGForm.Console. OutputFile ia the name of the .cer file where the X.509 certificate will be written.
References IG.Forms.UtilForms.AppConsole, IG.Forms.UtilForms.Reporter, IG.Crypt.Asym.TestCertificateName, IG.Crypt.Asym.TestContainerName, and IG.Forms.ConsoleForm.WriteLine().
static void IG.Crypt.Asym.CreateTestCertificate (string CertificateName, string StorageName, bool UserStore, string ContainerName, string CommandPath, bool ReportConsole, bool ReportForm, string OutputFile) inline static
static void IG.Crypt.Asym.CreateTestCertificate (string CertificateName, string StorageName, bool UserStore, string ContainerName, string CommandPath) inline static
static void IG.Crypt.Asym.CreateTestCertificate (string CertificateName, string StorageName, bool UserStore, string ContainerName) inline static
static void IG.Crypt.Asym.CreateTestCertificate (string CertificateName) inline static
static void IG.Crypt.Asym.CreateTestCertificate () inline static
static void IG.Crypt.Asym.LoadKeys (string containername) inline static
static void IG.Crypt.Asym.DeleteKeys (string containername) inline static
static byte [] IG.Crypt.Asym.EncryptMessage (byte[] plaintext, RSAParameters rsaParams) inline static private
static byte [] IG.Crypt.Asym.DecryptMessage (byte[] ciphertext, CspParameters cspParams) inline static private
static void IG.Crypt.Asym.AssignParameter (string ContainerName) inline static
static void IG.Crypt.Asym.AssignNewKey (string ContainterName, string PrivateKeyFileName, string PublicKeyFileName) inline static
static string IG.Crypt.Asym.EncryptData (string ContainterName, string data2Encrypt, string XMLPublicKeyFileName) inline static
static string IG.Crypt.Asym.DecryptData (string ContainterName, string data2Decrypt, string PrivateKeyFilename) inline static
static void IG.Crypt.Asym.SignXml (XmlDocument Doc, RSA Key) inline static
static Boolean IG.Crypt.Asym.VerifyXml (XmlDocument Doc, RSA Key) inline static
static void IG.Crypt.Asym.TestXML (String[] args) inline static
static void IG.Crypt.Asym.TestEncrypt (string message) inline static
Member Data Documentation
string IG.Crypt.Asym.TestContainerName = "Test_RSA_container" static
Referenced by IG.Crypt.Asym.CreateTestCertificate().
string IG.Crypt.Asym.TestCertificateName = "Test_Certificate" static private
Referenced by IG.Crypt.Asym.CreateTestCertificate().
string IG.Crypt.Asym.CertName = "Test_Certificate" static
string IG.Crypt.Asym.CertStorage = "my" static private
certificate name in the storage
string IG.Crypt.Asym.CertContainer = "Test_RSA_container" static private
storage name
string IG.Crypt.Asym.CertCommand = "makecert.exe" static private
key container name
string IG.Crypt.Asym.CertFile = null static private
system command to call the certificate maker
Referenced by IG.Crypt.encryption_test.Main().
string IG.Crypt.Asym.CertValidFrom = null static private
output file (should be .cert) to which certificate is exported
Referenced by IG.Crypt.encryption_test.Main().
string IG.Crypt.Asym.CertValidTo = null static private
bool IG.Crypt.Asym.CertUserStore = true static
bool IG.Crypt.Asym.CertRepConsole = true static private
bool IG.Crypt.Asym.CertRepForm = false static private
RSACryptoServiceProvider IG.Crypt.Asym.rsaProvider static private
The documentation for this class was generated from the following file:
igtest/iglib_sandbox/encryption/EncryptionLib.cs