IGLib: Meta.Numerics.Statistics.Distributions.FisherDistribution Class Reference
Meta.Numerics.Statistics.Distributions.FisherDistribution Class Reference
Represents the distribution of Fisher's F-statistic.
Public Member Functions
FisherDistribution (double nu1, double nu2)
Initializes a new Fisher distribution.
override double ProbabilityDensity (double x)
Returns the probability density at the given point.
Parameters
x The reference point.
Returns
The probability density p(x).
The probability density function (PDF) gives the relative probability of obtaining different values.
override double LeftProbability (double x)
Returns the cumulative probability to the left of (below) the given point.
Parameters
x The reference point.
Returns
The integrated probability to obtain a result below the reference point.
The left probability function is commonly called the cumulative distribution function (CDF).
override double RightProbability (double x)
Return the cumulative probability to the right of (above) the given point.
Parameters
x The reference point.
Returns
The integrated probability 1-P(x1) to obtain a result above the reference point.
In survival analysis, the right probability function is commonly called the survival function, because it gives the fraction of the population remaining after the given time.
override double Moment (int n)
Computes a raw moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth raw moment of the distribution.
See also
Moment
override double MomentAboutMean (int r)
Computes a central moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth central moment of the distribution.
See also
Moment
override double InverseLeftProbability (double P)
Returns the point at which the cumulative distribution function attains a given value.
Parameters
P The left cumulative probability P, which must lie between 0 and 1.
Returns
The value x at which LeftProbability equals P.
The inverse left probability is commonly called the quantile function. Given a quantile, it tells which variable value is the lower border of that quantile.
override double InverseRightProbability (double Q)
Returns the point at which the right probability function attains the given value.
Parameters
Q The right cumulative probability, which must lie between 0 and 1.
Returns
The value x for which RightProbability equals Q.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double ExpectationValue (Func< double, double > f)
Computes the expectation value of the given function.
virtual double GetRandomValue (Random rng)
Returns a random value.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Cumulant (int r)
Computes a cumulant of the distribution.
Properties
double NumeratorDegreesOfFreedom [get]
Gets the number of degrees of freedom in the numerator.
double DenominatorDegreesOfFreedom [get]
Gets the number of degrees of freedom in the denominator.
override double Mean [get]
override double Variance [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double Median [get]
Gets the median of the distribution.
virtual Interval Support [get]
Gets the interval over which the distribution is nonvanishing.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Private Attributes
double nu1
double nu2
BetaDistribution beta
Detailed Description
Represents the distribution of Fisher's F-statistic.
The ratio of the variances of two sets of normally distributed variables is distributed according to Fisher's F-distribution.
Many test statistics are ratios of variances and are therefore distributed according to the F-distribution. These include the F-test (Sample.FisherFTest), the goodness-of-fit test for a multi-linear regression (MultivariateSample.LinearRegression(int)), and ANOVA tests (Sample.OneWayAnovaTest(IList{Sample})).
The Fisher distribution is related to the Beta distribution (BetaDistribution) by a simple variable transformation.
Constructor & Destructor Documentation
Meta.Numerics.Statistics.Distributions.FisherDistribution.FisherDistribution (double nu1, double nu2) inline
Initializes a new Fisher distribution.
Parameters
nu1 The number of degrees of freedom in the numerator, which must be positive.
nu2 The number of degrees of freedom in the denominator, which must be positive.
See also
Sample.FisherFTest
Member Function Documentation
override double Meta.Numerics.Statistics.Distributions.FisherDistribution.ProbabilityDensity (double x) inline virtual
Returns the probability density at the given point.
Parameters
x The reference point.
Returns
The probability density p(x).
The probability density function (PDF) gives the relative probability of obtaining different values.
Implements Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.BetaDistribution.ProbabilityDensity().
override double Meta.Numerics.Statistics.Distributions.FisherDistribution.LeftProbability (double x) inline virtual
Returns the cumulative probability to the left of (below) the given point.
Parameters
x The reference point.
Returns
The integrated probability to obtain a result below the reference point.
The left probability function is commonly called the cumulative distribution function (CDF).
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.BetaDistribution.LeftProbability().
Referenced by Test.BugTests.Bug5886(), and Test.DistributionTest.FisherInversion().
override double Meta.Numerics.Statistics.Distributions.FisherDistribution.RightProbability (double x) inline virtual
Return the cumulative probability to the right of (above) the given point.
Parameters
x The reference point.
Returns
The integrated probability 1-P(x1) to obtain a result above the reference point.
In survival analysis, the right probability function is commonly called the survival function, because it gives the fraction of the population remaining after the given time.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.BetaDistribution.RightProbability().
Referenced by Test.DistributionTest.FisherInversion().
override double Meta.Numerics.Statistics.Distributions.FisherDistribution.Moment (int n) inline virtual
Computes a raw moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth raw moment of the distribution.
See also
Moment
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
override double Meta.Numerics.Statistics.Distributions.FisherDistribution.MomentAboutMean (int r) inline virtual
Computes a central moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth central moment of the distribution.
See also
Moment
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
override double Meta.Numerics.Statistics.Distributions.FisherDistribution.InverseLeftProbability (double P) inline virtual
Returns the point at which the cumulative distribution function attains a given value.
Parameters
P The left cumulative probability P, which must lie between 0 and 1.
Returns
The value x at which LeftProbability equals P.
The inverse left probability is commonly called the quantile function. Given a quantile, it tells which variable value is the lower border of that quantile.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.BetaDistribution.InverseLeftProbability().
Referenced by Test.BugTests.Bug5886().
override double Meta.Numerics.Statistics.Distributions.FisherDistribution.InverseRightProbability (double Q) inline virtual
Returns the point at which the right probability function attains the given value.
Parameters
Q The right cumulative probability, which must lie between 0 and 1.
Returns
The value x for which RightProbability equals Q.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.BetaDistribution.InverseRightProbability().
Member Data Documentation
double Meta.Numerics.Statistics.Distributions.FisherDistribution.nu1 private
double Meta.Numerics.Statistics.Distributions.FisherDistribution.nu2 private
BetaDistribution Meta.Numerics.Statistics.Distributions.FisherDistribution.beta private
Property Documentation
double Meta.Numerics.Statistics.Distributions.FisherDistribution.NumeratorDegreesOfFreedom get
Gets the number of degrees of freedom in the numerator.
Referenced by Test.DistributionTest.FisherInversion().
double Meta.Numerics.Statistics.Distributions.FisherDistribution.DenominatorDegreesOfFreedom get
Gets the number of degrees of freedom in the denominator.
Referenced by Test.DistributionTest.FisherInversion().
override double Meta.Numerics.Statistics.Distributions.FisherDistribution.Mean get
override double Meta.Numerics.Statistics.Distributions.FisherDistribution.Variance get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/FisherDistribution.cs