IGLib: CShell.Modules.Editors.ViewModels.EditorViewModel Class Reference
CShell.Modules.Editors.ViewModels.EditorViewModel Class Reference
Public Member Functions
override void CanClose (System.Action< bool > callback)
void Open (Uri uri)
override void Save ()
override void SaveAs (string newFile)
string GetSelectionOrCurrentLine ()
override bool Equals (object obj)
void Undo ()
void Redo ()
void Cut ()
void Copy ()
void Paste ()
void SelectAll ()
void Select (int start, int length)
Selects a section in the text.
void Comment ()
void Uncomment ()
override void CanClose (System.Action< bool > callback)
void Open (Uri uri)
override void Save ()
override void SaveAs (string newFile)
string GetSelectionOrCurrentLine ()
override bool Equals (object obj)
void Undo ()
void Redo ()
void Cut ()
void Copy ()
void Paste ()
void SelectAll ()
void Select (int start, int length)
Selects a section in the text.
void Comment ()
void Uncomment ()
Protected Member Functions
override void OnViewLoaded (object view)
override void OnViewLoaded (object view)
Properties
string File [get]
override Uri Uri [get, set]
override bool IsDirty [get, set]
string Text [get, set]
Properties inherited from CShell.Framework.Document
ICommand CloseCommand [get]
virtual Uri Uri [get, set]
virtual bool IsDirty [get, set]
Properties inherited from CShell.Framework.IDocument
ICommand CloseCommand [get]
Uri Uri [get]
bool IsDirty [get]
Properties inherited from CShell.Framework.ITextDocument
string Text [get, set]
Private Member Functions
IHighlightingDefinition GetHighlighting (string fileExtension)
IHighlightingDefinition GetHighlighting (string fileExtension)
Private Attributes
string originalText
string path
string fileName
bool isDirty
CodeTextEditor textEditor
EditorView editorView
Member Function Documentation
override void CShell.Modules.Editors.ViewModels.EditorViewModel.CanClose (System.Action< bool > callback) inline
void CShell.Modules.Editors.ViewModels.EditorViewModel.Open (Uri uri) inline
override void CShell.Modules.Editors.ViewModels.EditorViewModel.OnViewLoaded (object view) inline protected
References CShell.ScriptingEngine.CodeCompletion, CShellCore.CodeCompletion.CodeTextEditor.Completion, CShellCore.CodeCompletion.CodeTextEditor.OpenFile(), CShell.Workspace.ScriptingEngine, and CShell.Shell.Workspace.
override void CShell.Modules.Editors.ViewModels.EditorViewModel.Save () inline virtual
Reimplemented from CShell.Framework.Document.
override void CShell.Modules.Editors.ViewModels.EditorViewModel.SaveAs (string newFile) inline virtual
Reimplemented from CShell.Framework.Document.
string CShell.Modules.Editors.ViewModels.EditorViewModel.GetSelectionOrCurrentLine () inline
Referenced by CShell.Modules.Editors.Module.ExecuteSelection().
override bool CShell.Modules.Editors.ViewModels.EditorViewModel.Equals (object obj) inline
References CShell.Modules.Editors.ViewModels.EditorViewModel.Uri.
IHighlightingDefinition CShell.Modules.Editors.ViewModels.EditorViewModel.GetHighlighting (string fileExtension) inline private
void CShell.Modules.Editors.ViewModels.EditorViewModel.Undo () inline
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.Redo () inline
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.Cut () inline
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.Copy () inline
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.Paste () inline
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.SelectAll () inline
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.Select (int start, int length) inline
Selects a section in the text.
Parameters
start The start index of the selection.
length The length of the selection.
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.Comment () inline
Implements CShell.Framework.ITextDocument.
References CShell.Modules.Editors.Views.EditorView.Comment().
void CShell.Modules.Editors.ViewModels.EditorViewModel.Uncomment () inline
Implements CShell.Framework.ITextDocument.
References CShell.Modules.Editors.Views.EditorView.Uncomment().
override void CShell.Modules.Editors.ViewModels.EditorViewModel.CanClose (System.Action< bool > callback) inline
void CShell.Modules.Editors.ViewModels.EditorViewModel.Open (Uri uri) inline
override void CShell.Modules.Editors.ViewModels.EditorViewModel.OnViewLoaded (object view) inline protected
References CShell.ScriptingEngine.CodeCompletion, CShellCore.CodeCompletion.CodeTextEditor.Completion, CShellCore.CodeCompletion.CodeTextEditor.OpenFile(), CShell.Workspace.ScriptingEngine, and CShell.Shell.Workspace.
override void CShell.Modules.Editors.ViewModels.EditorViewModel.Save () inline virtual
Reimplemented from CShell.Framework.Document.
override void CShell.Modules.Editors.ViewModels.EditorViewModel.SaveAs (string newFile) inline virtual
Reimplemented from CShell.Framework.Document.
string CShell.Modules.Editors.ViewModels.EditorViewModel.GetSelectionOrCurrentLine () inline
override bool CShell.Modules.Editors.ViewModels.EditorViewModel.Equals (object obj) inline
References CShell.Modules.Editors.ViewModels.EditorViewModel.Uri.
IHighlightingDefinition CShell.Modules.Editors.ViewModels.EditorViewModel.GetHighlighting (string fileExtension) inline private
void CShell.Modules.Editors.ViewModels.EditorViewModel.Undo () inline
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.Redo () inline
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.Cut () inline
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.Copy () inline
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.Paste () inline
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.SelectAll () inline
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.Select (int start, int length) inline
Selects a section in the text.
Parameters
start The start index of the selection.
length The length of the selection.
Implements CShell.Framework.ITextDocument.
void CShell.Modules.Editors.ViewModels.EditorViewModel.Comment () inline
Implements CShell.Framework.ITextDocument.
References CShell.Modules.Editors.Views.EditorView.Comment().
void CShell.Modules.Editors.ViewModels.EditorViewModel.Uncomment () inline
Implements CShell.Framework.ITextDocument.
References CShell.Modules.Editors.Views.EditorView.Uncomment().
Member Data Documentation
string CShell.Modules.Editors.ViewModels.EditorViewModel.originalText private
string CShell.Modules.Editors.ViewModels.EditorViewModel.path private
string CShell.Modules.Editors.ViewModels.EditorViewModel.fileName private
bool CShell.Modules.Editors.ViewModels.EditorViewModel.isDirty private
CodeTextEditor CShell.Modules.Editors.ViewModels.EditorViewModel.textEditor private
EditorView CShell.Modules.Editors.ViewModels.EditorViewModel.editorView private
Property Documentation
string CShell.Modules.Editors.ViewModels.EditorViewModel.File get
override Uri CShell.Modules.Editors.ViewModels.EditorViewModel.Uri get set
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.Equals().
override bool CShell.Modules.Editors.ViewModels.EditorViewModel.IsDirty get set
string CShell.Modules.Editors.ViewModels.EditorViewModel.Text get set
Referenced by CShell.Modules.Editors.Module.ExecuteFile().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Editors/ViewModels/EditorViewModel.cs