IGLib: IG.Num.Vector3d Class Reference
IG.Num.Vector3d Class Reference
Vector or point in a 3 dimensional space.
Public Member Functions
Vector3d GetCopyThis ()
Creates and returns a copy of the current 3D vector, which is of the same type as the current vector.
override VectorBase GetCopyBase ()
Creates and returns a copy of the current vector, which is of the same type as the current vector.
Vector3d GetNewThis (int length)
Creates and returns a new vector of the specified dimension in such a way that the type of the returned vector is the same as that of the current vector.
override VectorBase GetNewBase (int length)
Creates and returns a new 3D vector of the specified dimension in such a way that the type of the returned vector is the same as that of the current vector.
Vector3d GetNewThis ()
Creates and returns a new vector with the same dimension and of the same type as the current vector.
override VectorBase GetNewBase ()
Creates and returns a new vector with the same dimension and of the same type as the current vector.
virtual Matrix3d GetNewMatrixThis (int rowCount, int columnCount)
Creates and returns a new 3D matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
override MatrixBase GetNewMatrixBase (int rowCount, int columnCount)
Creates and returns a new 3D matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
Matrix3d GetNewMatrixThis ()
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
override MatrixBase GetNewMatrixBase ()
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
Vector3d (Vector3d v)
Copy constructor. Initializes components of a 3D vector with components of the specified vector.
Vector3d (vec3 v)
Initializes components of a 3D vector with components of the specified vector.
Vector3d (double x, double y, double z)
Initializes components of a 3D vector with the specified values.
Vector3d (double comp)
Initializes all component of a 3D vector with the specified value.
Vector3d (double[] components)
Constructs a vector from a 1-D array.
Vector3d (IVector vec)
Constructs a 3D vector from another vector.
override int GetHashCode ()
Returns the hashRet code (hashRet function) of the current vector.
override bool Equals (Object obj)
Returns a value indicating whether the specified object is equal to the current vector.
new Vector3d Normalized ()
Normalizes this 3D vector.
Vector3d Normalized1 ()
Normalizes this 3D vector in 1 norm.
Vector3d Normalized2 ()
Normalizes this 3D vector in 2 norm.
Vector3d NormalizedInfinity ()
Normalizes this 3D vector in infinity norm.
double ScalarProduct (Vector3d v)
Returns scalar product of the current and the specified vector.
Vector3d VectorProduct (Vector3d v)
Returns vector product of the current and the specified vector.
Vector3d CrossProduct (Vector3d v)
Returns vector product of the current and the specified vector.
Vector3d Cross (Vector3d v)
Returns vector product of the current and the specified vector.
Matrix3d DyadicProduct (Vector3d v)
Returns dyadic product of the current and the specified vector.
double MixedProduct (Vector3d b, Vector3d c)
Returns mixed product of the current and two other specified vectors. This equals the volume of the parallelepiped spanned by these vectors.
Vector3d Multiply (double k)
Returns the current vector multiplied by the specified scalar.
Vector3d Add (Vector3d a)
Returns sum of the current vector and the specified vector.
Vector3d Subtract (Vector3d a)
Returns difference between the current vector and the specified vector.
override string ToString ()
Returns string representation of the 3D vector.
void Read ()
Reads 3D vector components from a console.
void Read (string name)
Reads 3D vector components from a console.
Public Member Functions inherited from IG.Num.VectorBase
virtual double[] ToArray ()
Copies the current vector to an array.
virtual IVector GetCopy ()
Returns a deep copy of the current object.
virtual IVector GetNew (int length)
Creates and returns a new vector with the specified dimension, and of the same type as the current vector.
virtual IVector GetNew ()
Creates and returns a new vector with the same dimension and of the same type as the current vector.
virtual IMatrix GetNewMatrix (int rowCount, int columnCount)
Creates and returns a new matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
virtual IMatrix GetNewMatrix ()
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
virtual void SetZero ()
Sets all components of the current vector to 0.
virtual void SetConstant (double elementValue)
Sets all components of the current vector to the specified value.
virtual void SetUnit (int which)
Sets the current vector to the specific unit vector (one component equals 1, others are 0).
virtual void SetRandom ()
Sets the current vector such that it contains random elements on the interval (0,1].
virtual void SetRandom (IRandomGenerator rnd)
Sets the current vector such that it contains random elements on the interval (0,1].
virtual double NormP (double p)
p-norm, p-th root of sum of absolute values of components raised to the power of p.
IVector Normalized ()
Returns a vector that equals a normalized current vector.
void Normalize ()
Normalizes the current vector.
void Negate ()
Changes the sign of the current vector.
override int GetHashCode ()
Returns the hashRet code (hashRet function) of the current vector.
override bool Equals (Object obj)
Returns a value indicating whether the specified object is equal to the current vector.
int GetHashFunctionInt ()
Returns an integer valued hashRet function of the current vector object.
string GetHashFunctionString ()
Returns a string valued hashRet function of the current vector object.
override string ToString ()
Returns a string representation of this vector in a standard IGLib form.
virtual string ToStringMath ()
Returns a string representation of this vector in a standard IGLib form (Mathematica-like format but with C representation of numbers).
virtual string ToString (string elementFormat)
Returns a string representation of the current vector in a standard IGLib form, with the specified format for elements of the vector.
virtual string ToStringMath (string elementFormat)
Returns a string representation of the current vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified format for elements of the vector.
Static Public Member Functions
static Vector3d Create (double[] components)
Constructs a vector from a 1-D array.
static Vector3d Create (IVector vec)
Constructs a 3D vector as a copy of another IVector object.
static Vector3d Random ()
Generates 3-dimensional vector with random elements uniformly distributed on [0, 1).
static Vector3d Ones ()
Generates an 3-dimensional vector filled with 1s.
static Vector3d Zeros ()
Generates an 3-dimensional vector filled with 0.
static Vector3d BasisVector (int i)
Generates an 3-dimensional unit vector for i-th coordinate.
static Vector3d Copy (Vector3d v)
Returns a copy of the specified 3D vector.
static void Negate (Vector3d v, ref Vector3d res)
Negates the specified vector and stores its copy in the resulting vector.
static Vector3d operator+ (Vector3d v)
Unary plus, returns the operand.
static Vector3d operator- (Vector3d v)
Unary negation, returns the negative operand.
static Vector3d operator+ (Vector3d a, Vector3d b)
Vector addition.
static Vector3d operator- (Vector3d a, Vector3d b)
Vector subtraction.
static double operator* (Vector3d a, Vector3d b)
Scalar product of two 3D vectors.
static Vector3d operator* (Vector3d a, double b)
Product of a 3D vector by a scalar.
static Vector3d operator* (double a, Vector3d b)
Product of a 3D vector by a scalar.
static Vector3d operator/ (Vector3d a, double b)
Vector subtraction.
Static Public Member Functions inherited from IG.Num.VectorBase
static double NormPlain (IVector a)
Returns Euclidean norm of the specified vector.
static double NormStatic (IVector a)
Returns Euclidean norm of the specified vector.
static double Norm2Plain (IVector a)
Returns Euclidean norm of the specified vector.
static double Norm2Static (IVector a)
Returns Euclidean norm of the specified vector.
static double Norm1Plain (Vector a)
Returns the 1-norm (Manhattan or Taxicab norm, sum of element absolute values) of the specified vector.
static double Norm1Static (IVector a)
Returns the 1-norm (Manhattan or Taxicab norm, sum of element absolute values) of the specified vector.
static double NormPPlain (Vector a, double p)
Returns the p-norm (p-th root of sum of absolute values of components raised to the power of p) of the specified vector.
static double NormPStatic (IVector a, double p)
Returns the p-norm (p-th root of sum of absolute values of components raised to the power of p) of the specified vector.
static double NormInfPlain (Vector a)
Returns the Infinity-norm (maximum absolute value of any element) of the specified vector.
static double NormInfStatic (IVector a)
Returns the Infinity-norm (maximum absolute value of any element) of the specified vector.
static double DistancePlain (IVector a, IVector b)
Returns Euqlidean distance between the specified two vectors.
static double Distance (IVector a, IVector b)
Returns Euqlidean distance between the specified two vectors.
static double DistanceWeightedPlain (IVector a, IVector b, IVector characteristicLengths)
Returns distance between the specified two vectors where vector elements are weighted by elements of another vector, which represent intervals of equal importance (thus the weighted sum is divided by their squares).
static double DistanceWeighted (IVector a, IVector b, IVector characteristicLengths)
Returns distance between the specified two vectors where vector elements are weighted by elements of another vector, which represent intervals of equal importance (thus the weighted sum is divided by their squares).
static double NormWeightedPlain (IVector a, IVector characteristicLengths)
Returns weighted Euclidean norm of the specified vector.
static double NormWeighted (IVector a, IVector characteristicLengths)
Returns weighted Euclidean norm of the specified vector.
static void SetZero (IVector vec)
Sets all components of the current vector to 0.
static void SetConstant (IVector vec, double elementValue)
Sets all components of the current vector to the specified value.
static void SetUnit (IVector vec, int which)
Sets the current vector to the specific unit vector (one component equals 1, others are 0).
static void SetRandom (IVector vec)
Sets the current vector such that it contains random elements on the interval (0,1].
static void SetRandom (IVector vec, IRandomGenerator rnd)
Sets the current vector such that it contains random elements on the interval (0,1].
static int Compare (IVector v1, IVector v2)
Compares two vectors and returns -1 if the first vector is smaller than the second one, 0 if vectors are equal, and 1 if the first vector is greater. Vector that is null is considered smaller than a vector that is not null. Two null vectors are considered equal. Vector with smaller dimension is considered smaller than a vector with greater dimension. Vectors with equal dimensions ar compared by elements. The first element that is different decides which vector is considered greater.
static void Resize (ref IVector vec, IVector template, int dimension)
Resizes, if necessary, the specified vector according to the required dimension. If the vector is initially null then a new vector is created. If in this case a template vector is specified then the newly created vector will be of the same type as that template vector, because it is created by the GetNew() method on that vector. If dimension of the initial vector does not match the required dim., then vector is resized. If the specified vector dimension is less or equal to 0 then vector is resized with the same dimension as that of the template vector. If in this case the template vector is null, an exception is thrown. WARNINGS: Components are NOT preserved and have in general undefined values after operation is performed. If vector and template are null then the type of nawly created vector is Vector.
static void Resize (ref IVector vec, int dimension)
Resizes, if necessary, the specified vector according to the required dimension. If the vector is initially null then a new vector is created. If dimension of the initial vector does not match the required dimension, then vector is resized. Components are NOT preserved and have in general undefined values after operation is performed. WARNING: If the vector is initially null then the type of the newly created vector is Vector.
static void Resize (ref IVector vec, IVector template)
Resizes, if necessary, the specified vector according to the dimension of the specified template vector. If the vector is initially null then a new vector is created. In this case the newly created vector will be of the same type as that template vector, because it is created by the GetNew() method on that vector. If dimension of the initial vector does not match the dimension of the template vector, then vector is resized. If the template vector is null, then an exception is thrown. WARNINGS: Components are NOT preserved and have in general undefined values after operation is performed. If vector and template are null then the type of newly created vector is Vector.
static void CopyPlain (IVector a, IVector result)
Copies components of a vector to another vector. This is a plain version that does not perform any dimension checks. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (IVector a, IVector result)
Copies components of a vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (IVector a, ref IVector result)
Copies components of a vectr to another vector. Resulting vector is allocated or reallocated if necessary.
static void CopyPlain (VectorBase_MathNetNumerics a, IVector result)
Copies components of a vector to another vector. This is a plain version that does not perform any dimension checks. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (VectorBase_MathNetNumerics a, IVector result)
Copies components of a vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (VectorBase_MathNetNumerics a, ref IVector result)
Copies components of a vectr to another vector. Resulting vector is allocated or reallocated if necessary.
static void CopyPlain (IVector a, Vector_MathNetNumerics result)
Copies components of a vector to another vector. This is a plain version that does not perform any dimension checks. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (IVector a, Vector_MathNetNumerics result)
Copies components of a vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
static void Copy (IVector a, ref Vector_MathNetNumerics result)
Copies components of a vectr to another vector. Resulting vector is allocated or reallocated if necessary.
static void NegatePlain (IVector a, IVector result)
Stores a negative vector of the specified vector to another vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of the copied vector and result vector must match.
static void Negate (IVector a, IVector result)
Stores a negative vector of the specified vector to another vector. WARNING: dimensions of the copied vector and result vector must match.
static void Negate (IVector a, ref IVector result)
Stores a negative vector of the specified vector to another vector. Resulting vector is allocated or reallocated if necessary.
static void AddPlain (IVector a, IVector b, IVector result)
Sums two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
static void Add (IVector a, IVector b, IVector result)
Sums two vectors and stores the result in the specified result vector. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
static void Add (IVector a, IVector b, ref IVector result)
Sums two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void SubtractPlain (IVector a, IVector b, IVector result)
Subtracts two vectors (a - b) and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
static void Subtract (IVector a, IVector b, IVector result)
Subtracts two vectors (a - b) and stores the result in the specified result vector. WARNING: dimensions of vectors must match, otherwise an exception is thrown.
static void Subtract (IVector a, IVector b, ref IVector result)
Subtracts two vectors (a - b) and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void OrthogonalProjectionPlain (IVector original, IVector onWhich, double onWhichProductSelf, IVector result, double tolerance=0.0)
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result, where the inner project of the vector to which projection is performed is specified.
static void OrthogonalProjectionPlain (IVector original, IVector onWhich, IVector result, double tolerance=0.0)
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result.
static void OrthogonalProjection (IVector original, IVector onWhich, double onWhichProductSelf, ref IVector result, double tolerance=0.0)
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result, where the inner project of the vector to which projection is performed is specified.
static void OrthogonalProjection (IVector original, IVector onWhich, ref IVector result, double tolerance=0.0)
Calculates orthogonal projection of the original vector on the specified vector, and stores the projection in the specified result.
static void ArrayAddPlain (IVector a, double scal, IVector result)
Addition of a scalar to all components of a vector. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void ArrayAdd (IVector a, double scal, IVector result)
Addition of a scalar to all components of a vector. Vector operand must be defined (non-null).
static void ArrayAdd (IVector a, double scal, ref IVector result)
Addition of a scalar to all components of a vector. Vector operand must be defined (non-null).
static void ArraySubtractPlain (IVector a, double scal, IVector result)
Subtraction of a scalar from all components of a vector. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void ArraySubtract (IVector a, double scal, IVector result)
Subtraction of a scalar from all components of a vector. Vector operand must be defined (non-null).
static void ArraySubtract (IVector a, double scal, ref IVector result)
Subtraction of a scalar to all components of a vector. Vector operand must be defined (non-null).
static void MultiplyPlain (IVector a, double scal, IVector result)
Multiplication of a vector by a scalar. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void Multiply (IVector a, double scal, IVector result)
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
static void Multiply (IVector a, double scal, ref IVector result)
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
static void ScalePlain (IVector a, double scal, IVector result)
Multiplication of a vector by a scalar. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void Scale (IVector a, double scal, IVector result)
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
static void Scale (IVector a, double scal, ref IVector result)
Multiplication of a vector by a scalar. Vector operand must be defined (non-null).
static void DividePlain (IVector a, double scal, IVector result)
Division of a vector by a scalar. This is a plain version of the method that does not perform any consistency checks. Vector operand must be defined (non-null).
static void Divide (IVector a, double scal, IVector result)
Division of a vector by a scalar. Vector operand must be defined (non-null).
static void Divide (IVector a, double scal, ref IVector result)
Division of a vector by a scalar. Vector operand must be defined (non-null).
static double ScalarProductPlain (IVector a, IVector b)
Scalar product of teo vectors. This is a plain version of the method that does not perform any consistency checks.
static double ScalarProduct (IVector a, IVector b)
Scalar product of teo vectors.
static void DyadicProductPlain (IVector a, IVector b, IMatrix result)
Calculates dyadic product of two vectors and stores the result in the specified result matrix. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions must match, otherwise an exception is thrown.
static void DyadicProduct (IVector a, IVector b, IMatrix result)
Calculates dyadic product of two vectors and stores the result in the specified result matrix. WARNING: dimensions must match, otherwise an exception is thrown.
static void DyadicProduct (IVector a, IVector b, ref IMatrix result)
Calculates dyadic product of two vectors and stores the result in the specified result matrix. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void CrossProductPlain (IVector a, IVector b, IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void CrossProduct (IVector a, IVector b, IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void CrossProduct (IVector a, IVector b, ref IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void VectorProductPlain (IVector a, IVector b, IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void VectorProduct (IVector a, IVector b, IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void VectorProduct (IVector a, IVector b, ref IVector result)
Calculates a vector product (cross product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void ArrayProductPlain (IVector a, IVector b, IVector result)
Calculates array product (element-by-element product) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void ArrayProduct (IVector a, IVector b, IVector result)
Calculates array product (element-by-element product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void ArrayProduct (IVector a, IVector b, ref IVector result)
Calculates array product (element-by-element product) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static void ArrayQuotientPlain (IVector a, IVector b, IVector result)
Calculates array quotient (element-by-element division) of two vectors and stores the result in the specified result vector. This is a plain version of the method that does not perform any consistency checks. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void ArrayQuotient (IVector a, IVector b, IVector result)
Calculates array quotient (element-by-element division) of two vectors and stores the result in the specified result vector. WARNING: dimensions of all vectors must be 3, otherwise an exception is thrown.
static void ArrayQuotient (IVector a, IVector b, ref IVector result)
Calculates array quotient (element-by-element division) of two vectors and stores the result in the specified result vector. WARNING: dimensions of operands must match, otherwise an exception is thrown. If dimensions of the result do not match then teh result is re-allocated.
static int GetHashCode (IVector vec)
Returns hashRet code of the specified vector.
static bool Equals (IVector v1, IVector v2)
Returns true if the specified vectors are equal, false if not.
static int GetHashFunctionInt (IVector vec)
Returns an integer valued hashRet function of the specified vector object.
static string GetHashFunctionString (IVector vec)
Returns a string valued hashRet function of the specified vector object.
static void OrthoNormalizeGramSchmidt (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolDependent=1e-10, bool normalize=false, int numRequestedVectors=0, IRandomGenerator rand=null, int maxExcessGenerated=5)
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthonormal vectors from the specified set of arbitrary independent vectors.
static int OrthogonalizeGramSchmidt (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolDependent=1e-10, bool normalize=false, int numRequestedVectors=0, IRandomGenerator rand=null, int maxExcessGenerated=5)
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthogonall vectors from the specified set of arbitrary independent vectors.
static void OrthoNormalizeGramSchmidtNonRobust (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolSize=0, bool normalize=false, bool modifiedGrammSchmidt=true)
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthonormal vectors from the specified set of arbitrary independent vectors.
static void OrthogonalizeGramSchmidtNonRobust (IList< IVector > original, ref IList< IVector > resOrthogonal, ref IVector resNorms, ref IVector auxProjection, double tolSize=0, bool normalize=false, bool modifiedGrammSchmidt=true)
Performs the Gramm-Schmidt orthogonalization procedure in order to calculate a set of orthogonall vectors from the specified set of arbitrary independent vectors.
static bool TestGramSchmidtOrthogonalization (int dim, int numRepetitions=1, double tol=1e-8, int outputLevel=0, IRandomGenerator randomGenerator=null, bool normalize=false, bool modifiedGrammSchmidt=true, bool nonRobust=false)
Performs a test of Gramm-Schmidt orthogonalization on a set of random vectors.
static VectorBase operator+ (VectorBase v)
Unary plus, returns the operand.
static VectorBase operator- (VectorBase v)
Unary negation, returns the negative operand.
static VectorBase operator+ (VectorBase a, VectorBase b)
Vector addition.
static VectorBase operator- (VectorBase a, VectorBase b)
Vector subtraction.
static double operator* (VectorBase a, VectorBase b)
Scalar product of two vectors.
static VectorBase operator* (VectorBase a, double b)
Product of a vector by a scalar.
static VectorBase operator* (double a, VectorBase b)
Product of a vector by a scalar.
static VectorBase operator/ (VectorBase a, double b)
Vector subtraction.
static string ToString (IVector vec)
Returns a string representation of the specified vector in a standard IGLib form.
static string ToStringMath (IVector vec)
Returns a string representation of the specified vector in a standard IGLib form (Mathematica-like format but with C representation of numbers).
static string ToString (IVector vec, string elementFormat)
Returns a string representation of the specified vector in a standard IGLib form, with the specified format for elements of the vector.
static string ToStringMath (IVector vec, string elementFormat)
Returns a string representation of the specified vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified format for elements of the vector.
static void SaveJson (IVector vec, string filePath)
Saves (serializes) the specified vector to the specified JSON file. File is owerwritten if it exists.
static void SaveJson (IVector vec, string filePath, bool append)
Saves (serializes) the specified vector to the specified JSON file. If the file already exists, contents either overwrites the file or is appended at the end, dependent on the value of the append flag.
static void LoadJson (string filePath, ref IVector vecRestored)
Restores (deserializes) a vector from the specified file in JSON format.
static void SaveCsv (IVector vec, string filePath)
Saves the specified vector to a CSV file. It the specified file already exists then it is overwritten. Constant UtilCsv.DefaultCsvSeparator is used as separator.
static void SaveCsv (IVector vec, string filePath, string separator)
Saves the specified vector to a CSV file. It the specified file already exists then it is overwritten.
static void SaveCsv (IVector vec, string filePath, bool append)
Saves the specified vector to a CSV file. Constant UtilCsv.DefaultCsvSeparator is used as separator in CSV.
static void SaveCsv (IVector vec, string filePath, string separator, bool append)
Saves the specified vector to a CSV file.
static void LoadCsv (string filePath, ref IVector vecRestored)
Reads a vector from a CSV file. Constant UtilCsv.DefaultCsvSeparator is used as separator in CSV file. If there are no components then a null vector is returned by this method (no exceptions thrown). If there are more than one rows in the CSV file then vector is read from the first row.
static void LoadCsv (string filePath, string separator, ref IVector vecRestored)
Reads a vector written in CSV format from a file. If there are no components then a null vector is returned by this method (no exceptions thrown). If there are more than one rows in the CSV file then vector is read from the first row.
static void LoadCsv (string filePath, int rowNum, ref IVector vecRestored)
Reads a vector from the specified row of a CSV file. Constant UtilCsv.DefaultCsvSeparator is used as CSV separator. If the specified row does not exisist in the file then exception is thrown.
static void LoadCsv (string filePath, int rowNum, string separator, ref IVector vecRestored)
Reads a vector from the specified row of a CSV file. If the specified row does not exisist in the file then exception is thrown.
Properties
override int Length [get]
Gets dimension of the vector.
override double this[int i] [get, set]
Gets or sets the element indexed by i in the 3D Vector.
vec3 Vec [get, set]
Gets the struct representation of this 3D vector.
double X [get, set]
1st component.
double Y [get, set]
2nd component.
double Z [get, set]
3rd component.
override double Norm [get]
Gets a 2 norm of the current 3D vector.
override double Norm2 [get]
Gets a 2 norm of the current 3D vector.
override double Norm1 [get]
Gets an 1 norm of the current 3D vector - sum of absolute values of components.
override double NormInf [get]
Gets an infinity norm of the current 3D vector - maximal absolute component value.
Properties inherited from IG.Num.VectorBase
abstract int Length [get]
Gets dimension of the vector.
abstract double this[int i] [get, set]
Gets or sets the element indexed by i in the Vector.
virtual double Norm [get]
Gets Euclidean norm of the vector.
virtual double Norm2 [get]
Gets Euclidean norm of the vector.
virtual double NormEuclidean [get]
Gets Euclidean norm of the vector.
virtual double SquaredNorm [get]
Squared Euclidean norm, sum of squared components.
virtual double Norm1 [get]
1-norm (Manhattan norm or Taxicab norm), sum of absolute values of components.
virtual double NormInf [get]
Infinity-norm, maximum absolute value of any component.
static VectorStore VectorStore [get]
Gets the matrix store for recycling auxiliary matrices.
Private Member Functions
object ICloneable. Clone ()
Returns a deep copy of a 3D vector.
Private Attributes
vec3 _v
Detailed Description
Vector or point in a 3 dimensional space.
$A Igor Jul08; Oct10; TODO: Consider whether Vector3d should ingerit from VectorBase!
Constructor & Destructor Documentation
IG.Num.Vector3d.Vector3d (Vector3d v) inline
Copy constructor. Initializes components of a 3D vector with components of the specified vector.
Parameters
v Vectr whose components are copied to the initialized vector.
References IG.Num.Vector3d.X, IG.Num.Vector3d.Y, and IG.Num.Vector3d.Z.
IG.Num.Vector3d.Vector3d (vec3 v) inline
Initializes components of a 3D vector with components of the specified vector.
Parameters
v Vector whose components are copied to the initialized vector.
References IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
IG.Num.Vector3d.Vector3d (double x, double y, double z) inline
Initializes components of a 3D vector with the specified values.
Parameters
x Value of the first element of the vector.
y Value of the second element of the vector.
z Value of the third element of the vector.
IG.Num.Vector3d.Vector3d (double comp) inline
Initializes all component of a 3D vector with the specified value.
Parameters
comp Value assigned to all vector components.
IG.Num.Vector3d.Vector3d (double[] components) inline
Constructs a vector from a 1-D array.
Parameters
components One-dimensional array of doubles.
See also
Create(double[])
IG.Num.Vector3d.Vector3d (IVector vec) inline
Constructs a 3D vector from another vector.
Parameters
vec Vector whose copy is created.
Member Function Documentation
Vector3d IG.Num.Vector3d.GetCopyThis () inline
Creates and returns a copy of the current 3D vector, which is of the same type as the current vector.
override VectorBase IG.Num.Vector3d.GetCopyBase () inline virtual
Creates and returns a copy of the current vector, which is of the same type as the current vector.
Implements IG.Num.VectorBase.
Vector3d IG.Num.Vector3d.GetNewThis (int length) inline
Creates and returns a new vector of the specified dimension in such a way that the type of the returned vector is the same as that of the current vector.
Parameters
length Dimension of the returned vector.
override VectorBase IG.Num.Vector3d.GetNewBase (int length) inline virtual
Creates and returns a new 3D vector of the specified dimension in such a way that the type of the returned vector is the same as that of the current vector.
Parameters
length Dimension of the returned vector, must be 3.
Implements IG.Num.VectorBase.
Vector3d IG.Num.Vector3d.GetNewThis () inline
Creates and returns a new vector with the same dimension and of the same type as the current vector.
override VectorBase IG.Num.Vector3d.GetNewBase () inline virtual
Creates and returns a new vector with the same dimension and of the same type as the current vector.
Implements IG.Num.VectorBase.
virtual Matrix3d IG.Num.Vector3d.GetNewMatrixThis (int rowCount, int columnCount) inline virtual
Creates and returns a new 3D matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
Parameters
rowCount Number of rows of the returned matrix.
columnCount Number of rows of the returned matrix.
Returns
A matrix with specified dimensions, whose type is consistent with the type of the current vector.
override MatrixBase IG.Num.Vector3d.GetNewMatrixBase (int rowCount, int columnCount) inline virtual
Creates and returns a new 3D matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
Parameters
rowCount Number of rows of the returned matrix.
columnCount Number of rows of the returned matrix.
Returns
A matrix with specified dimensions, whose type is consistent with the type of the current vector.
Implements IG.Num.VectorBase.
Matrix3d IG.Num.Vector3d.GetNewMatrixThis () inline
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
override MatrixBase IG.Num.Vector3d.GetNewMatrixBase () inline virtual
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
Implements IG.Num.VectorBase.
object ICloneable. IG.Num.Vector3d.Clone () inline private
Returns a deep copy of a 3D vector.
static Vector3d IG.Num.Vector3d.Create (double[] components) inline static
Constructs a vector from a 1-D array.
static Vector3d IG.Num.Vector3d.Create (IVector vec) inline static
Constructs a 3D vector as a copy of another IVector object.
static Vector3d IG.Num.Vector3d.Random () inline static
Generates 3-dimensional vector with random elements uniformly distributed on [0, 1).
References IG.Num.VectorBase.SetRandom().
static Vector3d IG.Num.Vector3d.Ones () inline static
Generates an 3-dimensional vector filled with 1s.
static Vector3d IG.Num.Vector3d.Zeros () inline static
Generates an 3-dimensional vector filled with 0.
static Vector3d IG.Num.Vector3d.BasisVector (int i) inline static
Generates an 3-dimensional unit vector for i-th coordinate.
Parameters
i Coordinate index.
override int IG.Num.Vector3d.GetHashCode () inline
Returns the hashRet code (hashRet function) of the current vector.
This method calls the VectorBase.GetHashCode() to calculate the hashRet code, which is standard for all implementations of the IVector interface.
Two vectors that have the same dimensions and equal elements will produce the same hashRet codes.
Probability that two different vectors will produce the same hashRet code is small but it exists.
Overrides the object.GetHashCode method.
References IG.Num.VectorBase.GetHashCode().
override bool IG.Num.Vector3d.Equals (Object obj) inline
Returns a value indicating whether the specified object is equal to the current vector.
True is returned if the object is a non-null vector (i.e. it implements the IVector interface), has the same dimension and equal elements as the current vector.
This method calls the VectorBase.Equals(IVector, IVector) to obtain the returned value, which is standard for all implementations of the IVector function.
Overrides the object.Equals(object) method.
References IG.Num.VectorBase.Equals().
new Vector3d IG.Num.Vector3d.Normalized () inline
Normalizes this 3D vector.
Implements IG.Num.IVector.
Vector3d IG.Num.Vector3d.Normalized1 () inline
Normalizes this 3D vector in 1 norm.
Vector3d IG.Num.Vector3d.Normalized2 () inline
Normalizes this 3D vector in 2 norm.
Vector3d IG.Num.Vector3d.NormalizedInfinity () inline
Normalizes this 3D vector in infinity norm.
double IG.Num.Vector3d.ScalarProduct (Vector3d v) inline
Returns scalar product of the current and the specified vector.
References IG.Num.Vector3d.Vec.
Referenced by IG.Num.Vector3d.operator*().
Vector3d IG.Num.Vector3d.VectorProduct (Vector3d v) inline
Returns vector product of the current and the specified vector.
References IG.Num.Vector3d.Vec.
Vector3d IG.Num.Vector3d.CrossProduct (Vector3d v) inline
Returns vector product of the current and the specified vector.
Vector3d IG.Num.Vector3d.Cross (Vector3d v) inline
Returns vector product of the current and the specified vector.
Matrix3d IG.Num.Vector3d.DyadicProduct (Vector3d v) inline
Returns dyadic product of the current and the specified vector.
References IG.Num.Vector3d.Vec.
double IG.Num.Vector3d.MixedProduct (Vector3d b, Vector3d c) inline
Returns mixed product of the current and two other specified vectors. This equals the volume of the parallelepiped spanned by these vectors.
References IG.Num.Vector3d.Vec.
Vector3d IG.Num.Vector3d.Multiply (double k) inline
Returns the current vector multiplied by the specified scalar.
Parameters
k Factor by which the current vector is multiplied.
Referenced by IG.Num.Vector3d.operator*().
Vector3d IG.Num.Vector3d.Add (Vector3d a) inline
Returns sum of the current vector and the specified vector.
References IG.Num.Vector3d.Vec.
Referenced by IG.Num.Vector3d.operator+().
Vector3d IG.Num.Vector3d.Subtract (Vector3d a) inline
Returns difference between the current vector and the specified vector.
References IG.Num.Vector3d.Vec.
Referenced by IG.Num.Vector3d.operator-().
static Vector3d IG.Num.Vector3d.Copy (Vector3d v) inline static
Returns a copy of the specified 3D vector.
Parameters
v Vector whose copy is returned.
Referenced by IG.Num.Vector3d.operator+().
static void IG.Num.Vector3d.Negate (Vector3d v, ref Vector3d res) inline static
Negates the specified vector and stores its copy in the resulting vector.
Parameters
v Vectr to be negated.
res Vector where the result is stored.
References IG.Num.Vector3d.X, IG.Num.Vector3d.Y, and IG.Num.Vector3d.Z.
static Vector3d IG.Num.Vector3d.operator+ (Vector3d v) inline static
Unary plus, returns the operand.
References IG.Num.Vector3d.Copy().
static Vector3d IG.Num.Vector3d.operator- (Vector3d v) inline static
Unary negation, returns the negative operand.
References IG.Num.Vector3d.X, IG.Num.Vector3d.Y, and IG.Num.Vector3d.Z.
static Vector3d IG.Num.Vector3d.operator+ (Vector3d a, Vector3d b) inline static
Vector addition.
References IG.Num.Vector3d.Add().
static Vector3d IG.Num.Vector3d.operator- (Vector3d a, Vector3d b) inline static
Vector subtraction.
References IG.Num.Vector3d.Subtract().
static double IG.Num.Vector3d.operator* (Vector3d a, Vector3d b) inline static
Scalar product of two 3D vectors.
References IG.Num.Vector3d.ScalarProduct().
static Vector3d IG.Num.Vector3d.operator* (Vector3d a, double b) inline static
Product of a 3D vector by a scalar.
References IG.Num.Vector3d.Multiply().
static Vector3d IG.Num.Vector3d.operator* (double a, Vector3d b) inline static
Product of a 3D vector by a scalar.
References IG.Num.Vector3d.Multiply().
static Vector3d IG.Num.Vector3d.operator/ (Vector3d a, double b) inline static
Vector subtraction.
References IG.Num.Vector3d.X, IG.Num.Vector3d.Y, and IG.Num.Vector3d.Z.
override string IG.Num.Vector3d.ToString () inline
Returns string representation of the 3D vector.
Implements IG.Num.IVector.
void IG.Num.Vector3d.Read () inline
Reads 3D vector components from a console.
void IG.Num.Vector3d.Read (string name) inline
Reads 3D vector components from a console.
Parameters
name Name of the vector to be read; it is written as orientation to the user and can be null.
Member Data Documentation
vec3 IG.Num.Vector3d._v private
Property Documentation
override int IG.Num.Vector3d.Length get
Gets dimension of the vector.
override double IG.Num.Vector3d.this[int i] get set
Gets or sets the element indexed by i in the 3D Vector.
Parameters
i Element index, 0 - based, must be between 0 and 2.
vec3 IG.Num.Vector3d.Vec get set
Gets the struct representation of this 3D vector.
Referenced by IG.Num.Vector3d.Add(), IG.Num.Vector3d.DyadicProduct(), IG.Gr3d.VtkPlotBase.ExampleSurfacePlotManualScaled(), IG.Num.Vector3d.MixedProduct(), IG.Num.Matrix3d.Multiply(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Num.Vector3d.ScalarProduct(), IG.Num.Matrix3d.Solve(), IG.Num.Vector3d.Subtract(), and IG.Num.Vector3d.VectorProduct().
double IG.Num.Vector3d.X get set
1st component.
Referenced by IG.Num.Matrix3d.Matrix3d(), IG.Num.Vector3d.Negate(), IG.Num.Vector3d.operator-(), IG.Num.Vector3d.operator/(), IG.Num.BoundingBox3d.Update(), and IG.Num.Vector3d.Vector3d().
double IG.Num.Vector3d.Y get set
2nd component.
Referenced by IG.Num.Matrix3d.Matrix3d(), IG.Num.Vector3d.Negate(), IG.Num.Vector3d.operator-(), IG.Num.Vector3d.operator/(), IG.Num.BoundingBox3d.Update(), and IG.Num.Vector3d.Vector3d().
double IG.Num.Vector3d.Z get set
3rd component.
Referenced by IG.Num.Matrix3d.Matrix3d(), IG.Num.Vector3d.Negate(), IG.Num.Vector3d.operator-(), IG.Num.Vector3d.operator/(), IG.Num.BoundingBox3d.Update(), and IG.Num.Vector3d.Vector3d().
override double IG.Num.Vector3d.Norm get
Gets a 2 norm of the current 3D vector.
override double IG.Num.Vector3d.Norm2 get
Gets a 2 norm of the current 3D vector.
override double IG.Num.Vector3d.Norm1 get
Gets an 1 norm of the current 3D vector - sum of absolute values of components.
override double IG.Num.Vector3d.NormInf get
Gets an infinity norm of the current 3D vector - maximal absolute component value.
The documentation for this class was generated from the following file:
igbase/numeric/geometry/Vector3Dclass.cs