IGLib: CShell.Modules.Shell.ViewModels.MainMenuViewModel Class Reference
CShell.Modules.Shell.ViewModels.MainMenuViewModel Class Reference
Public Member Functions
MainMenuViewModel ()
MainMenuViewModel ()
Public Member Functions inherited from CShell.Framework.Menus.MenuModel
void Add (params MenuItemBase[] items)
void Add (params MenuItemBase[] items)
Private Member Functions
IEnumerable< IResult > OpenFile ()
IEnumerable< IResult > Exit ()
IEnumerable< IResult > OpenFile ()
IEnumerable< IResult > Exit ()
Private Attributes
IShell _shell
Additional Inherited Members
Properties inherited from CShell.Framework.Menus.MenuModel
IEnumerable< MenuItemBase > All [get]
Properties inherited from CShell.Framework.Menus.IMenu
IEnumerable< MenuItemBase > All [get]
Constructor & Destructor Documentation
CShell.Modules.Shell.ViewModels.MainMenuViewModel.MainMenuViewModel () inline
CShell.Modules.Shell.ViewModels.MainMenuViewModel.MainMenuViewModel () inline
Member Function Documentation
IEnumerable<IResult> CShell.Modules.Shell.ViewModels.MainMenuViewModel.OpenFile () inline private
References CShell.Framework.Results.Show.Dialog(), and CShell.Framework.Results.Show.Document().
IEnumerable<IResult> CShell.Modules.Shell.ViewModels.MainMenuViewModel.Exit () inline private
References CShell.Framework.Services.IShell.Close().
IEnumerable<IResult> CShell.Modules.Shell.ViewModels.MainMenuViewModel.OpenFile () inline private
References CShell.Framework.Results.Show.Dialog(), and CShell.Framework.Results.Show.Document().
IEnumerable<IResult> CShell.Modules.Shell.ViewModels.MainMenuViewModel.Exit () inline private
Member Data Documentation
IShell CShell.Modules.Shell.ViewModels.MainMenuViewModel._shell private
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Shell/ViewModels/MainMenuViewModel.cs