IGLib: DotNetMatrix.test.TestMatrix Class Reference
DotNetMatrix.test.TestMatrix Class Reference
TestMatrix tests the functionality of the DotNetMatrix GeneralMatrix class and associated decompositions.
Static Public Member Functions
static void Main (System.String[] argv)
Static Private Member Functions
static void check (double x, double y)
private utility routines *
static void check (double[] x, double[] y)
Check norm of difference of "vectors". *
static void check (double[][] x, double[][] y)
Check norm of difference of arrays. *
static void check (GeneralMatrix X, GeneralMatrix Y)
Check norm of difference of Matrices. *
static void print (System.String s)
Shorten spelling of print. *
static void try_success (System.String s, System.String e)
Print appropriate messages for successful outcome try *
static int try_failure (int count, System.String s, System.String e)
Print appropriate messages for unsuccessful outcome try *
static int try_warning (int count, System.String s, System.String e)
Print appropriate messages for unsuccessful outcome try *
Detailed Description
TestMatrix tests the functionality of the DotNetMatrix GeneralMatrix class and associated decompositions.
Run the test from the command line using
DotNetMatrix.test.TestMatrix
Detailed output is provided indicating the functionality being tested and whether the functionality is correctly implemented. Exception handling is also tested.
The test is designed to run to completion and give a summary of any implementation errors encountered. The final output should be:
TestMatrix completed.
Total errors reported: n1
Total warning reported: n2
If the test does not run to completion, this indicates that there is a substantial problem within the implementation that was not anticipated in the test design. The stopping point should give an indication of where the problem exists.
Member Function Documentation
static void DotNetMatrix.test.TestMatrix.Main (System.String[] argv) inline static
Constructors and constructor-like methods: double[], int double[][] int, int int, int, double int, int, double[][] Create(double[][]) Random(int,int) Identity(int)
check that exception is thrown in packed constructor with invalid length *
check that exception is thrown in default constructor if input array is 'ragged' *
check that exception is thrown in Create if input array is 'ragged' *
check that Create behaves properly *
Access Methods: getColumnDimension() getRowDimension() getArray() getArrayCopy() getColumnPackedCopy() getRowPackedCopy() get(int,int) GetMatrix(int,int,int,int) GetMatrix(int,int,int[]) GetMatrix(int[],int,int) GetMatrix(int[],int[]) set(int,int,double) SetMatrix(int,int,int,int,GeneralMatrix) SetMatrix(int,int,int[],GeneralMatrix) SetMatrix(int[],int,int,GeneralMatrix) SetMatrix(int[],int[],GeneralMatrix)
Various get methods:
Various set methods:
Array-like methods: Subtract SubtractEquals Add AddEquals ArrayLeftDivide ArrayLeftDivideEquals ArrayRightDivide ArrayRightDivideEquals arrayTimes ArrayMultiplyEquals uminus
LA methods: Transpose Multiply Condition Rank Determinant trace Norm1 norm2 normF normInf Solve solveTranspose Inverse chol Eigen lu qr svd
References DotNetMatrix.GeneralMatrix.Add(), DotNetMatrix.GeneralMatrix.AddEquals(), DotNetMatrix.GeneralMatrix.Array, DotNetMatrix.GeneralMatrix.ArrayCopy, DotNetMatrix.GeneralMatrix.ArrayLeftDivide(), DotNetMatrix.GeneralMatrix.ArrayLeftDivideEquals(), DotNetMatrix.GeneralMatrix.ArrayMultiply(), DotNetMatrix.GeneralMatrix.ArrayMultiplyEquals(), DotNetMatrix.GeneralMatrix.ArrayRightDivide(), DotNetMatrix.GeneralMatrix.ArrayRightDivideEquals(), DotNetMatrix.GeneralMatrix.chol(), DotNetMatrix.GeneralMatrix.ColumnDimension, DotNetMatrix.GeneralMatrix.ColumnPackedCopy, DotNetMatrix.GeneralMatrix.Condition(), DotNetMatrix.GeneralMatrix.Copy(), DotNetMatrix.GeneralMatrix.Create(), DotNetMatrix.EigenvalueDecomposition.D, DotNetMatrix.GeneralMatrix.Determinant(), DotNetMatrix.GeneralMatrix.Eigen(), DotNetMatrix.GeneralMatrix.GetElement(), DotNetMatrix.CholeskyDecomposition.GetL(), DotNetMatrix.GeneralMatrix.GetMatrix(), DotNetMatrix.SingularValueDecomposition.GetU(), DotNetMatrix.SingularValueDecomposition.GetV(), DotNetMatrix.EigenvalueDecomposition.GetV(), DotNetMatrix.GeneralMatrix.Identity(), DotNetMatrix.GeneralMatrix.Inverse(), DotNetMatrix.LUDecomposition.L, DotNetMatrix.GeneralMatrix.LUD(), DotNetMatrix.GeneralMatrix.Multiply(), DotNetMatrix.GeneralMatrix.Norm1(), DotNetMatrix.GeneralMatrix.NormF(), DotNetMatrix.GeneralMatrix.NormInf(), DotNetMatrix.LUDecomposition.Pivot, DotNetMatrix.QRDecomposition.Q, DotNetMatrix.GeneralMatrix.QRD(), DotNetMatrix.QRDecomposition.R, DotNetMatrix.GeneralMatrix.Random(), DotNetMatrix.GeneralMatrix.Rank(), DotNetMatrix.GeneralMatrix.RowDimension, DotNetMatrix.GeneralMatrix.RowPackedCopy, DotNetMatrix.SingularValueDecomposition.S, DotNetMatrix.GeneralMatrix.SetElement(), DotNetMatrix.GeneralMatrix.SetMatrix(), DotNetMatrix.SingularValueDecomposition.SingularValues, DotNetMatrix.CholeskyDecomposition.Solve(), DotNetMatrix.GeneralMatrix.Solve(), DotNetMatrix.GeneralMatrix.Subtract(), DotNetMatrix.GeneralMatrix.SubtractEquals(), DotNetMatrix.GeneralMatrix.SVD(), DotNetMatrix.GeneralMatrix.Trace(), DotNetMatrix.GeneralMatrix.Transpose(), DotNetMatrix.LUDecomposition.U, and DotNetMatrix.GeneralMatrix.UnaryMinus().
static void DotNetMatrix.test.TestMatrix.check (double x, double y) inline static private
private utility routines *
Check magnitude of difference of scalars. *
static void DotNetMatrix.test.TestMatrix.check (double[] x, double[] y) inline static private
Check norm of difference of "vectors". *
static void DotNetMatrix.test.TestMatrix.check (double x[][], double y[][]) inline static private
Check norm of difference of arrays. *
static void DotNetMatrix.test.TestMatrix.check (GeneralMatrix X, GeneralMatrix Y) inline static private
Check norm of difference of Matrices. *
References DotNetMatrix.GeneralMatrix.Norm1(), and DotNetMatrix.GeneralMatrix.Subtract().
static void DotNetMatrix.test.TestMatrix.print (System.String s) inline static private
Shorten spelling of print. *
static void DotNetMatrix.test.TestMatrix.try_success (System.String s, System.String e) inline static private
Print appropriate messages for successful outcome try *
static int DotNetMatrix.test.TestMatrix.try_failure (int count, System.String s, System.String e) inline static private
Print appropriate messages for unsuccessful outcome try *
static int DotNetMatrix.test.TestMatrix.try_warning (int count, System.String s, System.String e) inline static private
Print appropriate messages for unsuccessful outcome try *
The documentation for this class was generated from the following file:
igtest/numerics/DotMatrix/Test/TestMatrix.cs