IGLib: NUnit.TestUtilities.TestAssert Class Reference
NUnit.TestUtilities.TestAssert Class Reference
Static Public Member Functions
static void IsRunnable (Test test)
static void IsRunnable (Type type)
static void IsRunnable (Type type, string name)
static void IsRunnable (Type type, string name, ResultState resultState)
static void IsNotRunnable (Test test)
static void IsNotRunnable (Type type)
static void IsNotRunnable (Type type, string name)
static void ChildNotRunnable (Type type, string name)
Private Member Functions
TestAssert ()
Constructor & Destructor Documentation
NUnit.TestUtilities.TestAssert.TestAssert () inline private
Member Function Documentation
static void NUnit.TestUtilities.TestAssert.IsRunnable (Test test) inline static
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Internal.Test.RunState.
Referenced by NUnit.Framework.Attributes.TheoryTests.AllValuesMayBeSuppliedByAttributes(), NUnit.Framework.Attributes.TheoryTests.BooleanArgumentsAreSuppliedAutomatically(), NUnit.Framework.Internal.TestFixtureTests.CanRunConstructorWithArgsSupplied(), NUnit.Framework.Internal.TestFixtureTests.CanRunFixtureDerivedFromAbstractDerivedTestFixture(), NUnit.Framework.Internal.TestFixtureTests.CanRunFixtureDerivedFromAbstractTestFixture(), NUnit.Framework.Internal.TestFixtureTests.CanRunMultipleSetUp(), NUnit.Framework.Internal.TestFixtureTests.CanRunMultipleTearDown(), NUnit.Framework.Internal.TestFixtureTests.CanRunMultipleTestFixtureSetUp(), NUnit.Framework.Internal.TestFixtureTests.CanRunMultipleTestFixtureTearDown(), NUnit.Framework.Internal.TestFixtureTests.CanRunProtectedFixtureSetUp(), NUnit.Framework.Internal.TestFixtureTests.CanRunProtectedFixtureTearDown(), NUnit.Framework.Internal.TestFixtureTests.CanRunProtectedSetUp(), NUnit.Framework.Internal.TestFixtureTests.CanRunProtectedTearDown(), NUnit.Framework.Internal.TestFixtureTests.CanRunStaticFixture(), NUnit.Framework.Internal.TestFixtureTests.CanRunStaticFixtureSetUp(), NUnit.Framework.Internal.TestFixtureTests.CanRunStaticFixtureTearDown(), NUnit.Framework.Internal.TestFixtureTests.CanRunStaticSetUp(), NUnit.Framework.Internal.TestFixtureTests.CanRunStaticTearDown(), NUnit.Framework.Internal.TestFixtureTests.CanRunTestFixtureWithNoTests(), NUnit.Framework.Attributes.TheoryTests.DatapointAndAttributeDataMayBeCombined(), NUnit.Framework.Attributes.TheoryTests.EnumArgumentsAreSuppliedAutomatically(), NUnit.Framework.Internal.TestMethodSignatureTests.InstanceTestMethodIsRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.StaticTestMethodIsRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.StaticTestMethodWithArgumentsProvidedIsRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.StaticTestMethodWithWrongArgumentTypesProvidedGivesError(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithArgumentsProvidedIsRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithConvertibleArgumentsIsRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithExpectedReturnTypeIsRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithNonConvertibleArgumentsGivesError(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithWrongArgumentTypesProvidedGivesError(), NUnit.Framework.Attributes.TheoryTests.TheoryWithDatapointsIsRunnable(), and NUnit.Framework.Attributes.TheoryTests.TheoryWithNoArgumentsIsTreatedAsTest().
static void NUnit.TestUtilities.TestAssert.IsRunnable (Type type) inline static
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Assert.NotNull(), NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Internal.Test.RunState, NUnit.TestUtilities.TestBuilder.RunTestSuite(), and NUnit.Framework.Interfaces.ResultState.Success.
static void NUnit.TestUtilities.TestAssert.IsRunnable (Type type, string name) inline static
References NUnit.Framework.Interfaces.ResultState.Success.
static void NUnit.TestUtilities.TestAssert.IsRunnable (Type type, string name, ResultState resultState) inline static
References NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Internal.Reflect.Construct(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ITestResult.HasChildren, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Internal.Test.RunState, NUnit.TestUtilities.TestBuilder.RunTest(), and NUnit.Framework.Assert.That().
static void NUnit.TestUtilities.TestAssert.IsNotRunnable (Test test) inline static
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Internal.Test.RunState.
Referenced by NUnit.Framework.Internal.TestFixtureTests.CannotRunConstructorWithArgsNotSupplied(), NUnit.Framework.Internal.TestFixtureTests.CannotRunFixtureSetupWithParameters(), NUnit.Framework.Internal.TestFixtureTests.CannotRunFixtureSetupWithReturnValue(), NUnit.Framework.Internal.TestFixtureTests.CannotRunFixtureTearDownWithParameters(), NUnit.Framework.Internal.TestFixtureTests.CannotRunFixtureTearDownWithReturnValue(), NUnit.Framework.Internal.TestFixtureTests.CannotRunGenericFixtureDerivedFromAbstractFixtureWithNoArgsProvided(), NUnit.Framework.Internal.TestFixtureTests.CannotRunPrivateFixtureSetUp(), NUnit.Framework.Internal.TestFixtureTests.CannotRunPrivateFixtureTearDown(), NUnit.Framework.Internal.TestFixtureTests.CannotRunPrivateSetUp(), NUnit.Framework.Internal.TestFixtureTests.CannotRunPrivateTearDown(), NUnit.Framework.Internal.TestFixtureTests.CannotRunSetupWithParameters(), NUnit.Framework.Internal.TestFixtureTests.CannotRunSetupWithReturnValue(), NUnit.Framework.Internal.TestFixtureTests.CannotRunTearDownWithParameters(), NUnit.Framework.Internal.TestFixtureTests.CannotRunTearDownWithReturnValue(), NUnit.Framework.Internal.TestMethodSignatureTests.PrivateTestMethodIsNotRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.ProtectedTestMethodIsNotRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.StaticTestMethodWithArgumentsNotProvidedIsNotRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithArgumentsNotProvidedIsNotRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithReturnTypeIsNotRunnable(), and NUnit.Framework.Attributes.TheoryTests.TheoryWithNoDatapointsIsNotRunnable().
static void NUnit.TestUtilities.TestAssert.IsNotRunnable (Type type) inline static
References NUnit.TestUtilities.TestBuilder.MakeFixture(), and NUnit.Framework.Assert.NotNull().
static void NUnit.TestUtilities.TestAssert.IsNotRunnable (Type type, string name) inline static
References NUnit.TestUtilities.TestBuilder.MakeTestCase().
static void NUnit.TestUtilities.TestAssert.ChildNotRunnable (Type type, string name) inline static
References NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), and NUnit.Framework.Internal.TestSuite.Tests.
Referenced by NUnit.Framework.Internal.TestMethodSignatureTests.StaticTestMethodWithWrongNumberOfArgumentsProvidedIsNotRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithoutParametersWithArgumentsProvidedIsNotRunnable(), and NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithWrongNumberOfArgumentsProvidedIsNotRunnable().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/TestUtilities/TestAssert.cs