IGLib: NUnit.Framework.Is Class Reference
NUnit.Framework.Is Class Reference
Helper class with properties and methods that supply a number of constraints used in Asserts.
Static Public Member Functions
static EqualConstraint EqualTo (object expected)
Returns a constraint that tests two items for equality
static SameAsConstraint SameAs (object expected)
Returns a constraint that tests that two references are the same object
static GreaterThanConstraint GreaterThan (object expected)
Returns a constraint that tests whether the actual value is greater than the supplied argument
static GreaterThanOrEqualConstraint GreaterThanOrEqualTo (object expected)
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
static GreaterThanOrEqualConstraint AtLeast (object expected)
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
static LessThanConstraint LessThan (object expected)
Returns a constraint that tests whether the actual value is less than the supplied argument
static LessThanOrEqualConstraint LessThanOrEqualTo (object expected)
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
static LessThanOrEqualConstraint AtMost (object expected)
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
static ExactTypeConstraint TypeOf (Type expectedType)
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
static ExactTypeConstraint TypeOf< TExpected > ()
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
static InstanceOfTypeConstraint InstanceOf (Type expectedType)
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
static InstanceOfTypeConstraint InstanceOf< TExpected > ()
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
static AssignableFromConstraint AssignableFrom (Type expectedType)
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
static AssignableFromConstraint AssignableFrom< TExpected > ()
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
static AssignableToConstraint AssignableTo (Type expectedType)
Returns a constraint that tests whether the actual value is assignable to the type supplied as an argument.
static AssignableToConstraint AssignableTo< TExpected > ()
Returns a constraint that tests whether the actual value is assignable to the type supplied as an argument.
static
CollectionEquivalentConstraint EquivalentTo (IEnumerable expected)
Returns a constraint that tests whether the actual value is a collection containing the same elements as the collection supplied as an argument.
static CollectionSubsetConstraint SubsetOf (IEnumerable expected)
Returns a constraint that tests whether the actual value is a subset of the collection supplied as an argument.
static CollectionSupersetConstraint SupersetOf (IEnumerable expected)
Returns a constraint that tests whether the actual value is a superset of the collection supplied as an argument.
static SubstringConstraint StringContaining (string expected)
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
static StartsWithConstraint StringStarting (string expected)
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
static EndsWithConstraint StringEnding (string expected)
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
static RegexConstraint StringMatching (string pattern)
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
static SamePathConstraint SamePath (string expected)
Returns a constraint that tests whether the path provided is the same as an expected path after canonicalization.
static SubPathConstraint SubPathOf (string expected)
Returns a constraint that tests whether the path provided is a subpath of the expected path after canonicalization.
static SamePathOrUnderConstraint SamePathOrUnder (string expected)
Returns a constraint that tests whether the path provided is the same path or under an expected path after canonicalization.
static RangeConstraint InRange (IComparable from, IComparable to)
Returns a constraint that tests whether the actual value falls inclusively within a specified range.
Properties
static ConstraintExpression Not [get]
Returns a ConstraintExpression that negates any following constraint.
static ConstraintExpression All [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them succeed.
static NullConstraint Null [get]
Returns a constraint that tests for null
static TrueConstraint True [get]
Returns a constraint that tests for True
static FalseConstraint False [get]
Returns a constraint that tests for False
static GreaterThanConstraint Positive [get]
Returns a constraint that tests for a positive value
static LessThanConstraint Negative [get]
Returns a constraint that tests for a negative value
static NaNConstraint NaN [get]
Returns a constraint that tests for NaN
static EmptyConstraint Empty [get]
Returns a constraint that tests for empty
static UniqueItemsConstraint Unique [get]
Returns a constraint that tests whether a collection contains all unique items.
static BinarySerializableConstraint BinarySerializable [get]
Returns a constraint that tests whether an object graph is serializable in binary format.
static XmlSerializableConstraint XmlSerializable [get]
Returns a constraint that tests whether an object graph is serializable in xml format.
static CollectionOrderedConstraint Ordered [get]
Returns a constraint that tests whether a collection is ordered
Detailed Description
Helper class with properties and methods that supply a number of constraints used in Asserts.
Member Function Documentation
static EqualConstraint NUnit.Framework.Is.EqualTo (object expected) inline static
Returns a constraint that tests two items for equality
Referenced by NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ActualArrayIsLonger(), NUnit.Framework.Internal.ResultStateTests.AddSiteToResult(), NUnit.Engine.Internal.Tests.ResultHelperTests.AggregateTestResult(), NUnit.Engine.Internal.Tests.ResultHelperTests.AggregateXmlNodes(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreInRangeFailureMessage(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreInstancesOfTypeFailureMessage(), NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreNotNullFails(), NUnit.Framework.Internal.PropertyBagTests.AllKeysAreListed(), NUnit.Framework.Attributes.TheoryTests.AllValuesMayBeSuppliedByAttributes(), NUnit.Framework.FileAssert.AreEqual(), NUnit.Framework.Assert.AreEqual(), NUnit.Framework.CollectionAssert.AreEqual(), NUnit.Framework.Assertions.CollectionAssertTest.AreEqualFail(), NUnit.Framework.Assertions.CollectionAssertTest.AreEqualFailCount(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWhenOneIsNull(), NUnit.Framework.Assertions.DirectoryAssertTests.AreEqualFailsWithDirectoryInfos(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithFileInfos(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithFiles(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithStreams(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithTextFilesAfterReadingBothFiles(), NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesWithSameStream(), NUnit.Framework.Assertions.CollectionAssertTest.AreNotEqual_Fails(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWhenBothAreNull(), NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualFailsWithDirectoryInfos(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithFileInfos(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithFiles(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithStreams(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualIteratesOverTheEntireFileAndFails(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndArraySegment(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArrayAndCollection_Failure(), NUnit.Framework.Assertions.ListContentsTests.ArrayFails(), NUnit.Framework.Assertions.ListContentsTests.ArrayListFails(), IG.Test.TestUtilities.ArraysAndListToString(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysDeclaredAsDifferentTypes(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraySegmentAndArray(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysHaveDifferentRanks(), NUnit.Framework.Assertions.NotEqualFixture.ArraysNotEqualFails(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysWithDifferentDimensionsAsCollection(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ArraysWithDifferentRanksAsCollection(), NUnit.Framework.Internal.SetUpFixtureTests.AssemblySetupFixtureWrapsExecutionOfTest(), NUnit.Framework.Assert.AssertDoublesAreEqual(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualLambdaAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualLambdaAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_ActualLambdaAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_DelegateAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_DelegateAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.AssertionPasses_DelegateAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.AssertionsAreCountedCorrectly(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualLambdaAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualLambdaAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualLambdaAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_DelegateAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_DelegateAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_DelegateAndConstraintWithMessageAndArgs(), NUnit.Framework.Internal.TestFixtureTests.BadConstructorRunsWithSetUpError(), NUnit.Framework.Internal.TestFixtureTests.FixtureNotNullTestAttribute.BeforeTest(), NUnit.Common.Tests.TokenizerTests.BlankStringReturnsEof(), NUnit.Framework.Attributes.TheoryTests.BooleanArgumentsAreSuppliedAutomatically(), NUnit.Framework.Assertions.EqualsFixture.Bug524CharIntWithoutOverload(), NUnit.Engine.Api.Tests.ServiceLocatorTests.CanAccessService(), NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.CanAccessTestCaseSource(), NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableDecimals(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableDoubles(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableInts(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableMixedNumerics(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareWithTolerance(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertIntToNullableByte(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertIntToNullableSByte(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertIntToNullableShort(), NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomain(), NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified(), NUnit.Engine.Tests.TestEngineResultTests.CanCreateFromXmlNode(), NUnit.Engine.Tests.TestEngineResultTests.CanCreateFromXmlString(), NUnit.Framework.Constraints.ToStringTests.CanDisplayPrefixConstraints_Resolved(), NUnit.Framework.Constraints.ToStringTests.CanDisplaySimpleConstraints_Resolved(), NUnit.Framework.Constraints.ToStringTests.CanDisplaySimpleConstraints_Unresolved(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanExcludePlatform(), NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.CanGenerateDataFromParameter(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnClasses(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnDerivedClasses(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnFields(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnMethods(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnParameters(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnProperties(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetConstructors(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanGetCurrentFramework(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanGetCurrentFramework(), NUnit.Engine.Services.Tests.ExtensionServiceTests.CanGetExtensionPointByPath(), NUnit.Engine.Services.Tests.ExtensionServiceTests.CanGetExtensionPointByType(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetGenericArguments(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetGetMethod(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetMember(), NUnit.Framework.Attributes.TestFixtureSourceTests.CanIgnoreIndividualFixtures(), NUnit.Framework.Attributes.TestCaseSourceTests.CanIgnoreIndividualTestCases(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanIgnoreIndividualTestCases(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanIncludePlatform(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CanLoadEmptyProject(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CanLoadVsProject(), NUnit.Framework.Attributes.TestFixtureSourceTests.CanMarkIndividualFixturesExplicit(), NUnit.Framework.Attributes.TestCaseSourceTests.CanMarkIndividualTestCasesExplicit(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanMarkIndividualTestCasesExplicit(), NUnit.Framework.Constraints.CollectionEqualsTests.CanMatchAnArrayWithACollection(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraint(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintAfterPrefix(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintsUnderAndOperator(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchLambda(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchPredicate(), NUnit.Framework.Constraints.CollectionEqualsTests.CanMatchTwoCollections(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchUsingIsEqualToWithinTimeSpan(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchUsingIsEqualToWithinTimeSpan(), NUnit.Framework.Internal.TestFixtureTests.CannotRunGenericFixtureWithNoArgsProvided(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.CanReadConfigFile(), NUnit.Framework.Internal.TestFixtureTests.CanRunGenericFixtureDerivedFromAbstractFixtureWithArgsProvided(), NUnit.Framework.Internal.TestFixtureTests.CanRunGenericFixtureWithProperArgsProvided(), NUnit.Framework.Attributes.CategoryAttributeTests.CanSpecifyOnMethodAndTestCase(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple_XmlOutput(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_XmlOutput(), NUnit.Framework.Assertions.StringAssertTests.CaseInsensitiveCompareFails(), NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsCategory(), NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsCategoryOnNonRunnableTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_ToXml_Regex(), NUnit.Framework.Attributes.SetUpFixtureAttributeTests.CertainAttributesAreNotAllowed(), NUnit.Framework.Assertions.EqualsFixture.CharCharComparision(), NUnit.Framework.Attributes.TestFixtureSourceTests.CheckArgument(), NUnit.Framework.Internal.Tests.TestNamingTests.CheckNames(), NUnit.Framework.Attributes.TestFixtureSourceTests.CheckNotRunnable(), NUnit.Framework.Attributes.RandomAttributeTests.CheckRandomResult(), NUnit.Framework.Internal.RandomizerTests.CheckScaleIsZero(), NUnit.TestData.TestFixtureSourceData.TestFixtureSourceTest.CheckSource(), NUnit.TestData.TestFixtureSourceData.TestFixtureSourceDivideTest.CheckSource(), NUnit.Framework.Attributes.ValuesAttributeTests.CheckValues(), NUnit.Framework.Attributes.RangeAttributeTests.CheckValues(), NUnit.Framework.Attributes.RangeAttributeTests.CheckValuesWithinTolerance(), NUnit.Framework.Internal.TestXmlTests.CheckXmlForTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_ToXml_Regex(), NUnit.Framework.Internal.TestExecutionContextTests.Cleanup(), NUnit.Framework.Constraints.MsgUtilTests.ClipExpectedAndActual_StringsDoNotFitInLine(), NUnit.Framework.Constraints.MsgUtilTests.ClipExpectedAndActual_StringsFitInLine(), NUnit.Framework.Constraints.MsgUtilTests.ClipExpectedAndActual_StringTailsFitInLine(), NUnit.Framework.Internal.GenericTestMethodTests.Combinatorial_IncompatibleArgsAreNotRunnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.CombinatorialAttribute_NoArgs_NoCases(), NUnit.Framework.Attributes.TestMethodBuilderTests.CombinatorialAttribute_WithArgs_Runnable(), NUnit.Framework.Attributes.ApplyToTestTests.CombinatorialAttributeSetsJoinType(), NUnit.Framework.Attributes.ApplyToTestTests.CombinatorialAttributeSetsJoinTypeOnNonRunnableTest(), NUnit.Framework.Syntax.MixedOperatorOverrides.ComplexTests(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.ConfigFileTests(), NUnit.TestData.AssertCountFixture.ConstraintAssert(), NUnit.Framework.Api.FrameworkControllerTests.ConstructController(), NUnit.Framework.Tests.TestContextTests.ConstructorCanAccessFixtureName(), NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithCombinedArgs(), NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithFixtureArgs(), NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithFixtureArgsAndSetTypeArgs(), NUnit.Framework.Attributes.DerivedPropertyAttributeTests.ConstructWithNoArgs< T >(), NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithNoArgumentsAndSetTypeArgs(), NUnit.Framework.Attributes.DerivedPropertyAttributeTests.ConstructWithOneArg< T >(), NUnit.Framework.Assertions.StringAssertTests.ContainsFails(), NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_EmptyICollection(), NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_EmptyIList(), NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_ICollection(), NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_ILIst(), NUnit.Framework.Assertions.AssertThrowsTests.CorrectExceptionIsReturnedToMethod(), NUnit.Framework.Attributes.Tests.CommandWrapperTests.CorrectExceptionThrown(), NUnit.Framework.Tests.ActionAttributeTests.CorrectNumberOfEventsReceived(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_BadFile_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_FileNotFound_ReturnsZero(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.CountTestCases_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_WithoutLoad_ThrowsInvalidOperation(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_BadFile_ReturnsZero(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_FileNotFound_ReturnsZero(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperation(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeExcludingCurrentCultureSkipsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeExcludingOtherCultureRunsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeIncludingCurrentCultureRunsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeIncludingOtherCultureSkipsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeWithMultipleCulturesIncluded(), NUnit.Framework.Attributes.TheoryTests.DatapointAndAttributeDataMayBeCombined(), NUnit.Framework.Assertions.EqualsFixture.DateTimeNotEqual(), NUnit.Engine.Services.Tests.ServiceDependencyTests.DefaultTestRunnerFactory_ProjectServiceError(), NUnit.Engine.Services.Tests.ServiceDependencyTests.DefaultTestRunnerFactory_ProjectServiceMissing(), NUnit.Framework.Attributes.ApplyToTestTests.DescriptionAttributeSetsDescription(), NUnit.Framework.Attributes.ApplyToTestTests.DescriptionAttributeSetsDescriptionOnNonRunnableTest(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.DifferentArrayTypesEqualFails(), NUnit.Framework.Assertions.EqualsFixture.DirectoryInfoNotEqual(), NUnit.Framework.Constraints.ToStringTests.DisplayBinaryConstraints_Resolved(), NUnit.Framework.Constraints.ToStringTests.DisplayBinaryConstraints_UnResolved(), NUnitLite.Tests.TextUITests.DisplayError(), NUnitLite.Tests.TextUITests.DisplayErrors(), NUnitLite.Tests.TextUITests.DisplayHeader(), NUnit.Framework.Constraints.ToStringTests.DisplayPrefixConstraints_Unresolved(), NUnitLite.Tests.TextUITests.DisplayRequestedOptions(), NUnitLite.Tests.TextUITests.DisplayRuntimeEnvironment(), NUnitLite.Tests.TextUITests.DisplayTestFiles(), NUnitLite.Tests.TextUITests.DisplayWarning(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.DisposeCalledOnceWhenFixtureImplementsIDisposable(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.DisposeCalledOnceWhenFixtureImplementsIDisposableAndHasTestCases(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_FirstChildIsXmlDeclaration(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_FirstChildIsXmlDeclaration(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_HasTestResults(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_HasTestResults(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_HasThreeChildren(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_HasThreeChildren(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_SecondChildIsComment(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_SecondChildIsComment(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_ThirdChildIsTestResults(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_ThirdChildIsTestResults(), NUnit.Framework.Assertions.CollectionAssertTest.DoesNotContain_Fails(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.DoesNotGetAttributesOnDerivedClassesWhenInheritedIsFalse(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetPrivateMemberOnBaseClass(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetStaticMemberOnBaseClass(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.DoubleDimensionedArrays(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.DTimeOffsetCanMatchDatesWithinHours(), NUnit.Common.Tests.XmlHelperTests.ElementContainsElementWithCData(), NUnit.Common.Tests.XmlHelperTests.ElementContainsElementWithInnerText(), NUnit.Framework.Assertions.ListContentsTests.EmptyArrayFails(), NUnit.Engine.Api.Tests.TestFilterTests.EmptyFilter(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.EmptyFilter(), NUnit.Framework.Assertions.StringAssertTests.EndsWithFails(), NUnit.Framework.Attributes.TheoryTests.EnumArgumentsAreSuppliedAutomatically(), NUnit.Framework.Assertions.EqualsFixture.EnumsNotEqual(), NUnit.Framework.Tests.AssertSyntaxTests.EqualIgnoringCaseTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTests(), NUnit.Framework.Syntax.EqualityTests.EqualityTestsUsingDefaultFloatingPointTolerance(), NUnit.Framework.Syntax.EqualityTests.EqualityTestsWithTolerance(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTestsWithTolerance(), NUnit.Framework.Syntax.EqualityTests.EqualityTestsWithTolerance_MixedFloatAndDouble(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTestsWithTolerance_MixedFloatAndDouble(), NUnit.Framework.Syntax.EqualityTests.EqualityTestsWithTolerance_MixingTypesGenerally(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTestsWithTolerance_MixingTypesGenerally(), NUnit.Framework.Assertions.EqualsFixture.EqualsFail(), NUnit.Framework.Assertions.EqualsFixture.EqualsNaNFails(), NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.EqualToTest(), NUnit.Framework.Syntax.AfterSyntaxUsingLambda.EqualToTest(), NUnit.Framework.Assertions.CollectionAssertTest.EquivalentFailOne(), NUnit.Framework.Assertions.CollectionAssertTest.EquivalentFailTwo(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfDaysPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfHoursPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfMillisecondsPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfMinutesPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfPercentPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfSecondsPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfTicksPrecedesWithin(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfUlpsIsUsedOnDecimal(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfUlpsIsUsedOnIntegralType(), NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfUlpsPrecedesWithin(), NUnit.ConsoleRunner.Tests.ResultReporterTests.ErrorsAndFailuresReportTest(), NUnitLite.Tests.TextUITests.ErrorsAndFailuresReportTest(), NUnit.Framework.Constraints.MsgUtilTests.EscapeControlCharsTest(), NUnit.Framework.Constraints.MsgUtilTests.EscapeNullCharInString(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyOneItemMatches(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyOneItemMatchFails(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyTwoItemsMatch(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyTwoItemsMatchFails(), NUnit.Framework.Assertions.TypeAssertTests.ExactTypeFails(), NUnit.Framework.Internal.TestExecutionContextTests.ExecutionStatusIsPromulgatedAcrossBranches(), NUnit.Framework.Internal.TestExecutionContextTests.ExecutionStatusIsPulledFromHigherContext(), NUnit.Framework.Internal.TestExecutionContextTests.ExecutionStatusIsPushedToHigherContext(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.ExpectedArrayIsLonger(), NUnit.Framework.Tests.Attributes.TestExpectedResult.ExpectedResultDoesNotBlockApplyToTestAttributes(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeMakesTestExplicit(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeSetsIgnoreReason(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeWithIgnoreIgnoresTest(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Explore_AfterLoad_ReturnsRunnableSuite(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Explore_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Engine.Services.Tests.ExtensionServiceTests.ExtensionsAreAddedToExtensionPoint(), NUnit.Framework.Constraints.ConstraintTestBase.FailsWithBadValues(), NUnit.Framework.Constraints.CollectionEqualsTests.FailureMatchingArrayAndCollection(), NUnit.Framework.Assertions.GreaterFixture.FailureMessage(), NUnit.Framework.Assertions.LessEqualFixture.FailureMessage(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.FailureOnSingleDimensionedArrays(), NUnit.Framework.Attributes.MaxTimeTests.FailureReportHasPriorityOverMaxTime(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualLambdaAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualLambdaAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_ActualLambdaAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_DelegateAndConstraint(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_DelegateAndConstraintWithMessage(), NUnit.Framework.Assertions.AssertThatTests.FailureThrowsAssertionException_DelegateAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraintWithMessageAndArgs(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraint(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraintWithMessage(), NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraintWithMessageAndArgs(), NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.FileNameIsUsedAsPackageName(), NUnit.Common.Tests.OutputSpecificationTests.FileNameOnly(), NUnit.Common.Tests.OutputSpecificationTests.FileNamePlusFormat(), NUnit.Common.Tests.OutputSpecificationTests.FileNamePlusTransform(), NUnit.Framework.Internal.Tests.StackFilterTests.FilterLongTrace(), NUnit.Framework.Internal.Tests.StackFilterTests.FilterShortTraceWithAssert(), NUnit.Framework.Internal.Tests.StackFilterTests.FilterShortTraceWithAssume_Trace1(), NUnit.Engine.Api.Tests.TestFilterTests.FilterWithOneTest(), NUnit.Engine.Api.Tests.TestFilterTests.FilterWithThreeTests(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.FiveDimensionedArrays(), NUnit.Framework.Internal.TestFixtureTests.FixtureInheritingTwoTestFixtureAttributesIsLoadedOnlyOnce(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureFullName(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureName(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureProperties(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpContextReflectsCurrentPrincipal(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpContextReflectsCurrentUICulture(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpontextReflectsCurrentCulture(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DateTimeTest(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DecimalIsWrittenToTwentyNineDigits(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DecimalIsWrittenWithTrailingM(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DoubleIsWrittenToSeventeenDigits(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DoubleIsWrittenWithTrailingD(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_FloatIsWrittenToNineDigits(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_FloatIsWrittenWithTrailingF(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_IntegerIsWrittenAsIs(), NUnit.Framework.Constraints.MsgUtilTests.FormatValue_StringIsWrittenWithQuotes(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_ToXml_Regex(), NUnit.Common.Tests.AssemblyHelperTests.GetNameForAssembly(), NUnit.Common.Tests.AssemblyHelperTests.GetPathForAssembly(), NUnit.Common.Tests.AssemblyHelperTests.GetPathForType(), NUnit.Framework.Internal.PropertyBagTests.GetReturnsSingleValue(), NUnit.Framework.Internal.GenericMethodHelperTests.GetTypeArgumentsForMethodTests(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureTearDownAfterErrorInTest(), NUnit.Framework.Constraints.AndConstraintTests.HandlesFirstPartFailing(), IG.Test.TestCrypto.HashStringMd5(), IG.Test.TestCrypto.HashStringSaltedMd5(), IG.Test.TestCrypto.HashStringSaltedSha1(), IG.Test.TestCrypto.HashStringSaltedSha256(), IG.Test.TestCrypto.HashStringSaltedSHA512(), IG.Test.TestCrypto.HashStringSha1(), IG.Test.TestCrypto.HashStringSha256(), IG.Test.TestCrypto.HashStringSha512(), NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.HasNoSubPackages(), NUnit.Framework.Constraints.CollectionEqualsTests.HonorsIgnoreCase(), NUnit.Common.Tests.TokenizerTests.IdentifierTokens(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.IdFilter_ToXml(), NUnit.Framework.Assertions.EqualsFixture.IEquatableSuccess_ConstraintSyntax(), NUnit.Framework.Internal.TestResultOutputTests.IfNothingIsWritten_OutputIsEmpty(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeIgnoresTest(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeIgnoresTestUntilDateSpecified(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeIgnoresTestUntilDateTimeSpecified(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeMarksTestAsRunnableAfterUntilDatePasses(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeSetsIgnoreReason(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeUntilSetsTheReason(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithExplicitIgnoresTest(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithUntilAddsIgnoreUntilDateProperty(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithUntilAddsIgnoreUntilDatePropertyPastUntilDate(), NUnit.Framework.Internal.PropertyBagTests.IndexGetsEmptyListIfNameIsNotPresent(), NUnit.Framework.Internal.PropertyBagTests.IndexGetsListOfValues(), NUnit.Framework.Internal.PropertyBagTests.IndexSetsListOfValues(), NUnit.Engine.Services.Tests.ServiceManagerTests.InitializeServices(), NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.InitializeTestEngineResult(), NUnit.Framework.Internal.SetUpFixtureTests.InvalidAssemblySetUpFixtureIsLoadedCorrectly(), NUnit.Framework.Internal.SetUpFixtureTests.InvalidSetUpFixtureTest(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.InvalidTestCase_HasFailedResult(), NUnit.Framework.Assertions.TypeAssertTests.IsAssignableFromFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNonEmptyArray(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNonEmptyIEnumerable(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNullString(), NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnString(), NUnit.Framework.Assertions.ConditionAssertTests.IsFalseFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsFalseFailsForNullable(), NUnit.Framework.Assertions.TypeAssertTests.IsInstanceOfFails(), NUnit.Framework.Assertions.StringAssertTests.IsMatchFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsNaNFails(), NUnit.Framework.Assertions.TypeAssertTests.IsNotAssignableFromFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyArray(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyArrayList(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyHashTable(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyIEnumerable(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyString(), NUnit.Framework.Assertions.TypeAssertTests.IsNotInstanceOfFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsNotNullFails(), NUnit.Framework.Assertions.CollectionAssertTest.IsNotSubsetOf_Fails(), NUnit.Framework.Assertions.ConditionAssertTests.IsNullFails(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_Fails(), NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_Fails(), NUnit.TestUtilities.TestAssert.IsRunnable(), NUnit.Framework.Assertions.CollectionAssertTest.IsSubsetOf_Fails(), NUnit.Framework.Assertions.ConditionAssertTests.IsTrueFails(), NUnit.Framework.Assertions.ConditionAssertTests.IsTrueFailsForNullable(), NUnit.Framework.Assertions.CollectionAssertTest.ItemsNotNullFailure(), NUnit.Framework.Assertions.CollectionAssertTest.ItemsOfTypeFailure(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.JaggedArrayComparedToSimpleArray(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.JaggedArrays(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Load_GoodFile_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_GoodFile_ReturnsRunnableSuite(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Load_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_Assembly_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_GoodFile_ReturnsRunnableSuite(), NUnit.Framework.Attributes.ApplyToTestTests.MaxTimeAttributeSetsMaxTime(), NUnit.Framework.Attributes.ApplyToTestTests.MaxTimeAttributeSetsMaxTimeOnNonRunnableTest(), NUnit.Engine.Internal.Tests.ResultHelperTests.MergeAndAggregateTestResults(), NUnit.Engine.Internal.Tests.ResultHelperTests.MergeTestResults(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_ToXml_Regex(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MethodWithoutParamsIsNamedCorrectly(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MethodWithParamsIsNamedCorrectly(), NUnit.Common.Tests.TokenizerTests.MixedTokens_Complex(), NUnit.Common.Tests.TokenizerTests.MixedTokens_Simple(), NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureReplacesNamespaceNodeInTree(), NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureWrapsExecutionOfSingleTest(), NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureWrapsExecutionOfTwoTests(), NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureWrapsNestedNamespaceSetUpFixture(), NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpMethodsMayBeStatic(), NUnit.Framework.Assertions.EqualsFixture.NanEqualsFails(), NUnit.Framework.Attributes.Tests.CommandWrapperTests.NoExceptionThrown(), NUnit.Framework.Assertions.AssertThrowsTests.NoExceptionThrown(), NUnit.Framework.Assertions.NotEqualFixture.NotEqualFails(), NUnit.Framework.Assertions.CollectionAssertTest.NotEquivalent_Fails(), NUnit.Framework.Assertions.GreaterFixture.NotGreater(), NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterEqualIComparable(), NUnit.Framework.Assertions.GreaterFixture.NotGreaterIComparable(), NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterOrEqual(), NUnit.Framework.Assertions.GreaterFixture.NotGreaterWhenEqual(), NUnit.Framework.Assertions.LessFixture.NotLess(), NUnit.Framework.Assertions.LessEqualFixture.NotLessEqualIComparable(), NUnit.Framework.Assertions.LessFixture.NotLessIComparable(), NUnit.Framework.Assertions.LessEqualFixture.NotLessOrEqual(), NUnit.Framework.Assertions.LessFixture.NotLessWhenEqual(), NUnit.Framework.Assertions.NotSameFixture.NotSameFails(), NUnit.Framework.Assertions.NotEqualFixture.NullEqualsNull(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestAndWhereClause(), NUnitLite.Tests.CreateTestFilterTests.OneTestSelected(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestSelected(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestSelected_XmlEscape(), NUnit.Framework.Internal.TestExecutionContextTests.OneTimeTearDown(), NUnit.Framework.Tests.TestContextOneTimeTearDownTests.OneTimeTearDown(), NUnit.Engine.Api.Tests.TestPackageTests_MultipleAssemblies.PackageContainsThreeSubpackages(), NUnit.Framework.Attributes.TestMethodBuilderTests.PairwiseAttribute_NoArgs_NoCases(), NUnit.Framework.Attributes.TestMethodBuilderTests.PairwiseAttribute_WithArgs_Runnable(), NUnit.Framework.Attributes.ApplyToTestTests.PairwiseAttributeSetsJoinType(), NUnit.Framework.Attributes.ApplyToTestTests.PairwiseAttributeSetsJoinTypeOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToContextTests.ParallelizableAttribute(), NUnit.Framework.Internal.NUnitTestCaseBuilderTests.ParametrizedTestCaseTests(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_ProcessBitNess(), NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeRunsTest(), NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeSkipsTest(), NUnit.Framework.Assertions.EqualsFixture.PosInfinityNotEquals(), NUnit.Framework.Assertions.EqualsFixture.PosInfinityNotEqualsNegInfinity(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.PositiveEqualityTest(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.PositiveEqualityTestWithTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.PositiveEqualityTestWithToleranceAndWithSameOffset(), IG.Test.TestCrypto.Prerequisites(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.PrivateBinPathTests(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.ProperConfigFileIsUsed(), NUnit.Framework.Constraints.PropertyTest.PropertyEqualToValueWithTolerance(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_ToXml_Regex(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Constraints.ConstraintTestBaseNoData.ProvidesProperDescription(), NUnit.Framework.Constraints.ConstraintTestBaseNoData.ProvidesProperStringRepresentation(), NUnit.Framework.Internal.RandomizerTests.RandomByteInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange_MinEqualsMax(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomEnum(), NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.Repeatability.RandomizersWithSameSeedsReturnSameValues(), NUnit.Framework.Internal.RandomizerTests.RandomLongInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomSbyteInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomShortInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomUintInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomULongInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange_MinEqualsMax(), NUnit.Engine.Services.Tests.ServiceDependencyTests.RecentFilesService_SettingsServiceError(), NUnit.Engine.Services.Tests.ServiceDependencyTests.RecentFilesService_SettingsServiceMissing(), NUnit.Framework.Attributes.ApplyToTestTests.RepeatAttributeSetsRepeatCount(), NUnit.Framework.Attributes.ApplyToTestTests.RepeatAttributeSetsRepeatCountOnNonRunnableTest(), NUnit.Framework.Attributes.RepeatAttributeTests.RepeatWorksAsExpected(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresMTAAttributeSetsApartmentState(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresMTAAttributeSetsApartmentStateOnNonRunnableTest(), NUnit.Framework.Attributes.ApartmentAttributeTests.FixtureRequiresMTA.RequiresMTACanBeSetOnTestFixture(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresSTAAttributeSetsApartmentState(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresSTAAttributeSetsApartmentStateOnNonRunnableTest(), NUnit.Framework.Attributes.ApartmentAttributeTests.FixtureRequiresSTA.RequiresSTACanBeSetOnTestFixture(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeMaySetApartmentState(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeSetsRequiresThread(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeSetsRequiresThreadOnNonRunnableTest(), NUnit.Framework.Attributes.RetryAttributeTests.RetryWorksAsExpected(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Run_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_WithoutLoad_ReturnsError(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_WithoutLoad_ReturnsError(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_WithoutLoad_ReturnsError(), NUnit.Framework.Internal.TestMethodSignatureTests.RunningTestsThroughFixtureGivesCorrectResults(), NUnit.Framework.Attributes.DatapointTests.RunTestOnFixture(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_WithoutLoad_ReturnsError(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccessWithDoubleDefaultValue(), NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccessWithIntDefaultValue(), NUnit.Framework.Assertions.SameFixture.SameFails(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.SameLengthDifferentContent(), NUnit.Framework.Assertions.SameFixture.SameValueTypes(), NUnit.Engine.Services.Tests.RuntimeFrameworkServiceTests.SelectRuntimeFramework(), NUnit.Framework.Attributes.TestMethodBuilderTests.SequentialAttribute_NoArgs_NoCases(), NUnit.Framework.Attributes.TestMethodBuilderTests.SequentialAttribute_WithArgs_Runnable(), NUnit.Framework.Attributes.ApplyToTestTests.SequentialAttributeSetsJoinType(), NUnit.Framework.Attributes.ApplyToTestTests.SequentialAttributeSetsJoinTypeOnNonRunnableTest(), NUnit.Engine.Services.Tests.SettingsServiceTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.DomainManagerTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.ProjectServiceTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.TestAgencyTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.ResultServiceTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.DriverServiceTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.RuntimeFrameworkServiceTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.RecentFilesTests.ServiceIsStarted(), NUnit.Framework.Internal.PropertyBagTests.SetAddsNewSingleValue(), NUnit.Framework.Attributes.ApplyToContextTests.SetCultureAttribute(), NUnit.Framework.Attributes.ApplyToTestTests.SetCultureAttributeSetsSetCultureProperty(), NUnit.Framework.Attributes.ApplyToTestTests.SetCultureAttributeSetsSetCulturePropertyOnNonRunnableTest(), NUnit.Framework.Internal.PropertyBagTests.SetReplacesOldValues(), NUnit.Framework.Attributes.ApplyToContextTests.SetUICultureAttribute(), NUnit.Framework.Attributes.ApplyToTestTests.SetUICultureAttributeSetsSetUICultureProperty(), NUnit.Framework.Attributes.ApplyToTestTests.SetUICultureAttributeSetsSetUICulturePropertyOnNonRunnableTest(), NUnit.Framework.Syntax.EqualToTest.SetUp(), NUnit.Framework.Syntax.AfterTest_SimpleConstraint.SetUp(), NUnit.ConsoleRunner.Tests.ColorConsoleTests.SetUp(), NUnit.Framework.Syntax.EqualToTest_IgnoreCase.SetUp(), NUnit.Framework.Tests.ActionAttributeTests.Setup(), NUnit.Framework.Syntax.EqualToTest_WithinTolerance.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforePrecedingOr.SetUp(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestFullName(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestName(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestProperties(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpContextReflectsCurrentCulture(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpContextReflectsCurrentPrincipal(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpContextReflectsCurrentUICulture(), NUnit.Framework.Attributes.TimeoutTests.SetUpTimesOutAndTearDownIsRun(), NUnit.Framework.Syntax.EqualityTests.SimpleEqualityTests(), NUnit.Framework.Attributes.TheoryTests.SimpleTestIgnoresDataPoints(), NUnit.Common.Tests.XmlHelperTests.SingleElement(), NUnit.Common.Tests.XmlHelperTests.SingleElementWithAttributes(), NUnit.Framework.Assertions.EqualsFixture.SinglePosInfinityNotEqualsNegInfinity(), NUnitLite.Tests.CreateTestFilterTests.SixTestsFromTwoTestListFiles(), NUnit.TestData.DatapointFixture.SquareRootTest.SqrtTimesItselfGivesOriginal(), NUnit.Framework.Attributes.TheoryTests.SqrtTests.SqrtTimesItselfGivesOriginal(), NUnit.Framework.Attributes.TheoryTests.SquareRootTest(), NUnit.Framework.Assertions.StringAssertTests.StartsWithFails(), NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest(), NUnit.Common.Tests.TokenizerTests.StringsMayContainEscapedQuoteChar(), NUnit.Common.Tests.TokenizerTests.StringWithDoubleQuotes(), NUnit.Common.Tests.TokenizerTests.StringWithSingleQuotes(), NUnit.Common.Tests.TokenizerTests.StringWithSlashes(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.SuiteHasCorrectNumberOfInstances(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.FailedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultIsFailure(), NUnit.ConsoleRunner.Tests.ResultReporterTests.SummaryReportTest(), NUnitLite.Tests.TextUITests.SummaryReportTest(), NUnit.Framework.Syntax.SyntaxTest.SupportedByConstraintBuilder(), NUnit.Framework.Syntax.SyntaxTest.SupportedByInheritedSyntax(), NUnit.Framework.Syntax.SyntaxTest.SupportedByStaticSyntax(), NUnit.Common.Tests.TokenizerTests.SymbolTokens_DoubleChar(), NUnit.Common.Tests.TokenizerTests.SymbolTokens_SingleChar(), IG.Test.TestCrypto.SymmetricEncryptionStringToBytesPlain(), NUnit.Framework.Tests.TestContextTearDownTests.TearDown(), NUnit.Framework.Attributes.PairwiseTest.Test(), NUnit.Engine.Services.Tests.ServiceDependencyTests.TestAgency_RuntimeFrameworkServiceError(), NUnit.Engine.Services.Tests.ServiceDependencyTests.TestAgency_RuntimeFrameworkServiceMissing(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestAttribute_NoArgs_Runnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestAttribute_WithArgs_NotRunnable(), NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnFullName(), NUnit.Framework.Internal.TestExecutionContextTests.TestCanAccessItsOwnFullName(), NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnMethodName(), NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnName(), NUnit.Framework.Internal.TestExecutionContextTests.TestCanAccessItsOwnName(), NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnProperties(), NUnit.Framework.Internal.TestExecutionContextTests.TestCanAccessItsOwnProperties(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_FailingTest(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_FailureInSetUp(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_IgnoredInSetUp(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_PassingTest(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_CategoryElementsDoNotContainProperties(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_ExecutedIsTrue(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_HasPropertyElement(), NUnit.Framework.Internal.GenericTestMethodTests.TestCase_IncompatibleArgsAreNotRunnable(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_PropertyElementsDoNotContainCategories(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_ResultIsSuccess(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseAttribute_NoArgs_NotRunnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseAttribute_RightArgs_Runnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseAttribute_WrongArgs_NotRunnable(), NUnit.Framework.Tests.TestContextTests.TestCaseCanAccessItsOwnFullName(), NUnit.Framework.Tests.TestContextTests.TestCaseCanAccessItsOwnMethodName(), NUnit.Framework.Tests.TestContextTests.TestCaseCanAccessItsOwnName(), NUnit.Framework.Internal.GenericTestMethodTests.TestCaseSource_IncompatibleArgsAreNotRunnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseSourceAttribute_NoArgs_NotRunnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseSourceAttribute_RightArgs_Runnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseSourceAttribute_WrongArgs_NotRunnable(), NUnit.Framework.Constraints.MsgUtilTests.TestClipString(), NUnit.ConsoleRunner.Tests.ColorConsoleTests.TestConstructor(), NUnit.Framework.Tests.TestContextTests.TestContextOut_WritesToResult(), NUnit.Framework.Internal.TestExecutionContextTests.TestContextReflectsCurrentCulture(), NUnit.Framework.Internal.TestExecutionContextTests.TestContextReflectsCurrentPrincipal(), NUnit.Framework.Internal.TestExecutionContextTests.TestContextReflectsCurrentUICulture(), NUnit.Framework.Tests.TestContextTests.TestContextStoresFailureInfoForOneTimeTearDown(), NUnit.Framework.Tests.TestContextTests.TestContextStoresFailureInfoForTearDown(), NUnit.Framework.Tests.TestContextTests.TestContextWrite_WritesToResult(), NUnit.Framework.Tests.TestContextTests.TestContextWriteLine_WritesToResult(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Failed(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Ignored(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Inconclusive(), NUnitLite.Tests.TextUITests.TestFinished_NoOutput(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Passed(), NUnitLite.Tests.TextUITests.TestFinished_WithOutput(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_ExpectedAttribute(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_HasPropertyElement(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_ResultIsFailure(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_SuccessIsFalse(), NUnit.Core.Tests.PairwiseTest.LiveTest.TestFixtureTearDown(), NUnit.Framework.Attributes.PairwiseTest.LiveTest.TestFixtureTearDown(), NUnit.Framework.Tests.Attributes.ValuesAttributeEnumTests.TestFixtureTeardown(), NUnit.ConsoleRunner.Utilities.Tests.ColorStyleTests.TestGetColor(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestGlobalDefaultTolerance_Success(), NUnitLite.Tests.CreateTestFilterTests.TestListFileMissing(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodHasAttributesAppliedCorrectlyEvenIfNotRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithMultipleTestCasesExecutesMultipleTimes(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithMultipleTestCasesUsesCorrectNames(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_ToXml_Regex(), NUnit.Common.Tests.TestSelectionParserTests.TestParser(), NUnit.Framework.Constraints.EqualTests.TestPropertyWithPrivateSetter(), NUnit.Framework.Internal.MinimumDurationResultTests.TestResultHasMinimumDuration(), NUnit.Framework.Internal.DefaultResultTests.TestResultIsInconclusive(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_AssemblyPathIsCorrect(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestResults_AssemblyPathIsCorrect(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_CounterIsCorrect(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestResults_CounterIsCorrect(), NUnit.Framework.Internal.FailedResultTests.TestResultXmlNodeEscapesInvalidXmlCharacters(), NUnit.ConsoleRunner.Tests.ResultReporterTests.TestsNotRunTest(), NUnitLite.Tests.TextUITests.TestsNotRunTest(), NUnit.Framework.Tests.ActionAttributeTests.TestsRunSuccessfully(), NUnitLite.Tests.TeamCityEventListenerTests.TestStarted(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_ExpectedAttribute(), NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteFinished(), NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteStarted(), NUnit.Framework.Tests.TestContextTearDownTests.TestTheMeaningOfLife(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutElapsed(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutNotElapsed(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutTestCaseWithOutElapsed(), NUnit.Framework.Attributes.TimeoutTests.TestTimesOutAndTearDownIsRun(), NUnit.Framework.Internal.TestXmlTests.TestTypeTests(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestWithinCanOnlyBeUsedOnce(), NUnit.Framework.Attributes.CategoryAttributeTests.TestWithInvalidCategoryNameIsNotRunnable(), NUnit.Framework.Attributes.ApartmentAttributeTests.TestWithRequiresMTARunsInMTA(), NUnit.Framework.Attributes.ApartmentAttributeTests.TestWithRequiresSTARunsInSTA(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadRunsSetUpAndTestOnSameThread(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadWithMTAArgRunsOnSeparateThreadInMTA(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadWithSTAArgRunsOnSeparateThreadInSTA(), NUnit.Framework.Attributes.TimeoutTests.TestWithTimeoutRunsSetUpAndTestOnSameThread(), NUnit.Framework.Attributes.TestMethodBuilderTests.TheoryAttribute_NoArgs_NoCases(), NUnit.Framework.Attributes.TestMethodBuilderTests.TheoryAttribute_WithArgs_Runnable(), NUnit.Framework.Attributes.TheoryTests.TheoryFailsIfAllTestsAreInconclusive(), NUnit.Framework.Attributes.TheoryTests.TheoryWithDatapointsIsRunnable(), NUnit.TestData.AssertCountFixture.ThreeAsserts(), NUnitLite.Tests.CreateTestFilterTests.ThreeTestsFromATestListFile(), NUnitLite.Tests.CreateTestFilterTests.ThreeTestsSelected(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.ThreeTestsSelected(), NUnit.Framework.Attributes.ApplyToContextTests.TimeoutAttribute(), NUnit.Framework.Attributes.TimeoutTests.TimeoutCanBeSetOnTestFixture(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.TopLevelSuiteIsNamedCorrectly(), NUnit.Framework.Assertions.ArrayEqualsFailureMessageFixture.TripleDimensionedArrays(), NUnit.Framework.Assertions.ArrayEqualsFixture.TwoArraySegments(), NUnit.Framework.Assertions.ArrayEqualsFixture.TwoEmptyArraySegments(), NUnitLite.Tests.CreateTestFilterTests.TwoTestsAndWhereClauseSpecified(), NUnit.Framework.Assertions.CollectionAssertTest.UniqueFailure(), NUnit.Common.Tests.OutputSpecificationTests.UserFormatMayBeIndicatedExplicitlyAfterTransform(), NUnit.Common.Tests.OutputSpecificationTests.UserFormatMayBeIndicatedExplicitlyBeforeTransform(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedEqualityComparer(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedGenericComparer(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedGenericComparison(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedGenericEqualityComparer(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedIComparer(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedLambda_IntArgs(), NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedLambda_StringArgs(), NUnit.Engine.Services.Tests.TestFilteringTests.UsingTestFilterBuilderAddTest(), NUnit.Engine.Services.Tests.TestFilteringTests.UsingTestFilterBuilderSelectWhere(), NUnit.Engine.Services.Tests.TestFilteringTests.UsingXml(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayBeGeneric(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayNotBeInstanceField(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayNotBeInstanceMethod(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayNotBeInstanceProperty(), NUnit.ConsoleRunner.Tests.MakeTestPackageTests.WhenDebugging_NumberOfTestWorkersDefaultsToZero(), NUnit.ConsoleRunner.Tests.MakeTestPackageTests.WhenDebugging_NumberOfTestWorkersMayBeOverridden(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.WhereClause(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.WhereClause_XmlEscape(), NUnitLite.Tests.CreateTestFilterTests.WhereClauseSpecified(), NUnit.Framework.Internal.SetUpFixtureTests.WithTwoSetUpFixturesBothAreUsed(), NUnit.Common.Tests.TokenizerTests.WordsInUnicode(), NUnit.Common.Tests.ExtendedTextWrapperTests.Write(), NUnit.Common.Tests.ExtendedTextWrapperTests.Write_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine_ColorStyle(), NUnit.Framework.Attributes.Tests.CommandWrapperTests.WrongExceptionThrown(), NUnit.Framework.Internal.PropertyBagTests.XmlIsProducedCorrectly(), NUnit.Framework.Constraints.ExactCountConstraintTests.ZeroItemsMatch(), and NUnit.Framework.Constraints.ExactCountConstraintTests.ZeroItemsMatchFails().
static SameAsConstraint NUnit.Framework.Is.SameAs (object expected) inline static
Returns a constraint that tests that two references are the same object
Referenced by NUnit.Engine.Services.Tests.ServiceManagerTests.AccessServiceByClass(), NUnit.Engine.Services.Tests.ServiceManagerTests.AccessServiceByInterface(), NUnit.Framework.Assert.AreSame(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayIsEqualToItself(), NUnit.Framework.Api.FrameworkControllerTests.ConstructController(), NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForDifferentParametersOfSameMethod(), NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForSameMethod(), NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForSameParameter(), NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.SameAsTest(), and NUnit.Framework.Syntax.AfterSyntaxUsingLambda.SameAsTest().
static GreaterThanConstraint NUnit.Framework.Is.GreaterThan (object expected) inline static
Returns a constraint that tests whether the actual value is greater than the supplied argument
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AndOperator(), NUnit.Framework.Constraints.GreaterThanConstraintTests.CanCompareIComparables(), NUnit.Framework.Constraints.GreaterThanConstraintTests.CanCompareIComparablesOfT(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableDecimals(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableDoubles(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableInts(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableMixedNumerics(), NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), NUnit.Framework.Syntax.MixedOperatorOverrides.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.ComplexTests(), NUnit.Engine.Tests.RuntimeFrameworkTests.CurrentFrameworkHasBuildSpecified(), NUnit.Framework.Internal.RuntimeFrameworkTests.CurrentFrameworkHasBuildSpecified(), NUnit.Framework.Constraints.ToStringTests.DisplayBinaryConstraints_Resolved(), NUnit.Framework.Constraints.ToStringTests.DisplayBinaryConstraints_UnResolved(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Explore_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Assert.Greater(), NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.GreaterTest(), NUnit.Framework.Syntax.AfterSyntaxUsingLambda.GreaterTest(), NUnit.Framework.Tests.AssertSyntaxTests.OrOperator(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Syntax.GreaterThanTest.SetUp(), NUnit.Framework.Syntax.AndOperatorOverride.SetUp(), NUnit.Framework.Syntax.OrOperatorOverride.SetUp(), NUnit.Framework.Syntax.AfterTest_AndOperator.SetUp(), and NUnit.Framework.Syntax.AndTest.SetUp().
static GreaterThanOrEqualConstraint NUnit.Framework.Is.GreaterThanOrEqualTo (object expected) inline static
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
Referenced by NUnit.Framework.Tests.ActionAttributeTests.ActionsWrappingParameterizedMethodSuite(), NUnit.Framework.Constraints.GreaterThanOrEqualConstraintTests.CanCompareIComparables(), NUnit.Framework.Constraints.GreaterThanOrEqualConstraintTests.CanCompareIComparablesOfT(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableDecimals(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableDoubles(), NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableInts(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnAssemblies(), NUnit.Framework.Tests.ActionAttributeTests.CheckActionsOnTestCase(), NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), NUnit.Framework.Assert.GreaterOrEqual(), NUnit.Framework.Syntax.GreaterThanOrEqualTest.SetUp(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithoutPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithoutPolling_ReturnsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithoutPolling_FailsAfterDelay(), and NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithPolling_FailsAfterDelay().
static GreaterThanOrEqualConstraint NUnit.Framework.Is.AtLeast (object expected) inline static
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), and NUnit.Framework.Syntax.AtLeastTest.SetUp().
static LessThanConstraint NUnit.Framework.Is.LessThan (object expected) inline static
Returns a constraint that tests whether the actual value is less than the supplied argument
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AndOperator(), NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Constraints.LessThanConstraintTests.CanCompareIComparables(), NUnit.Framework.Constraints.LessThanConstraintTests.CanCompareIComparablesOfT(), NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), NUnit.Framework.Syntax.MixedOperatorOverrides.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.ComplexTests(), NUnit.Framework.Assert.Less(), NUnit.Framework.Tests.AssertSyntaxTests.OrOperator(), NUnit.Framework.Syntax.AndOperatorOverride.SetUp(), NUnit.Framework.Syntax.OrOperatorOverride.SetUp(), NUnit.Framework.Syntax.LessThanTest.SetUp(), NUnit.Framework.Syntax.OrTest.SetUp(), NUnit.Framework.Syntax.OrTest_ThreeOrs.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforeFollowingOr.SetUp(), and NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest().
static LessThanOrEqualConstraint NUnit.Framework.Is.LessThanOrEqualTo (object expected) inline static
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
Referenced by NUnit.Framework.Constraints.LessThanOrEqualConstraintTests.CanCompareIComparables(), NUnit.Framework.Constraints.LessThanOrEqualConstraintTests.CanCompareIComparablesOfT(), NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), NUnit.Framework.Assert.LessOrEqual(), and NUnit.Framework.Syntax.LessThanOrEqualTest.SetUp().
static LessThanOrEqualConstraint NUnit.Framework.Is.AtMost (object expected) inline static
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), NUnit.Framework.Syntax.AtMostTest.SetUp(), and NUnit.Framework.Attributes.PairwiseTest.Test().
static ExactTypeConstraint NUnit.Framework.Is.TypeOf (Type expectedType) inline static
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
Referenced by NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.OrFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.NotFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml_TopLevelDefaultsToAnd(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.BuildMethodNameFilter_FromXml_Regex(), NUnit.Framework.Constraints.PredicateConstraintTests.CanUseConstraintExpressionSyntax(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml_Regex(), NUnit.Framework.Api.FrameworkControllerTests.ConstructController(), NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests.CorrectRunnerIsUsed(), NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed(), NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed_InvalidExtension(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Framework.Assertions.TypeAssertTests.ExactType(), NUnit.Framework.Assertions.TypeAssertTests.ExactTypeFails(), NUnit.Framework.Tests.AssertSyntaxTests.ExactTypeTests(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Framework.Internal.TestFixtureTests.FixtureInheritingTwoTestFixtureAttributesIsLoadedOnlyOnce(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.IdFilter_FromXml(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_GoodFile_ReturnsRunnableSuite(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_FromXml(), NUnit.Framework.Attributes.TestCaseSourceTests.MethodTakingTwoStringArrays(), NUnitLite.Tests.CreateTestFilterTests.OneTestSelected(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml_Regex(), NUnit.Framework.Attributes.CombinatorialTests.RandomTest(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Framework.Syntax.ExactTypeTest.SetUp(), NUnit.Framework.Syntax.ExactTypeTest_Generic.SetUp(), NUnitLite.Tests.CreateTestFilterTests.SixTestsFromTwoTestListFiles(), NUnit.Framework.Internal.TypeParameterUsedWithTestMethod< T >.TestMyArgType(), NUnit.Framework.Internal.GenericTestFixture_Numeric< T >.TestMyArgType(), NUnit.Framework.Internal.DeduceTypeArgsFromArgs< T1, T2 >.TestMyArgTypes(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml_Regex(), NUnitLite.Tests.CreateTestFilterTests.ThreeTestsFromATestListFile(), NUnitLite.Tests.CreateTestFilterTests.ThreeTestsSelected(), NUnitLite.Tests.CreateTestFilterTests.TwoTestsAndWhereClauseSpecified(), and NUnitLite.Tests.CreateTestFilterTests.WhereClauseSpecified().
static ExactTypeConstraint NUnit.Framework.Is.TypeOf< TExpected > () inline static
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
static InstanceOfTypeConstraint NUnit.Framework.Is.InstanceOf (Type expectedType) inline static
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
Referenced by NUnit.Framework.Internal.SetUpFixtureTests.AssemblySetUpFixtureReplacesAssemblyNodeInTree(), NUnit.Engine.Api.Tests.ServiceLocatorTests.CanAccessService(), NUnit.Engine.Services.Tests.DriverServiceTests.CorrectDriverIsUsed(), NUnit.Framework.Tests.AssertSyntaxTests.InstanceOfTests(), NUnit.Framework.Assertions.TypeAssertTests.IsInstanceOf(), NUnit.Framework.Assert.IsInstanceOf(), NUnit.Framework.Assert.IsInstanceOf< TExpected >(), NUnit.Framework.Assertions.TypeAssertTests.IsInstanceOfFails(), NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureReplacesNamespaceNodeInTree(), NUnit.Framework.Syntax.InstanceOfTest.SetUp(), and NUnit.Framework.Syntax.InstanceOfTest_Generic.SetUp().
static InstanceOfTypeConstraint NUnit.Framework.Is.InstanceOf< TExpected > () inline static
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
static AssignableFromConstraint NUnit.Framework.Is.AssignableFrom (Type expectedType) inline static
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AssignableFromTypeTests(), NUnit.Framework.Assert.IsAssignableFrom(), NUnit.Framework.Assertions.TypeAssertTests.IsAssignableFrom(), NUnit.Framework.Assert.IsAssignableFrom< TExpected >(), NUnit.Framework.Assertions.TypeAssertTests.IsAssignableFromFails(), NUnit.Framework.Syntax.AssignableFromTest.SetUp(), and NUnit.Framework.Syntax.AssignableFromTest_Generic.SetUp().
static AssignableFromConstraint NUnit.Framework.Is.AssignableFrom< TExpected > () inline static
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
static AssignableToConstraint NUnit.Framework.Is.AssignableTo (Type expectedType) inline static
Returns a constraint that tests whether the actual value is assignable to the type supplied as an argument.
Referenced by NUnit.Framework.Syntax.AssignableToTest.SetUp(), NUnit.Framework.Syntax.AssignableToTest_Generic.SetUp(), and NUnit.Framework.Tests.Compatibility.StopwatchTests.StopwatchIsDotNetStopwatch().
static AssignableToConstraint NUnit.Framework.Is.AssignableTo< TExpected > () inline static
Returns a constraint that tests whether the actual value is assignable to the type supplied as an argument.
static CollectionEquivalentConstraint NUnit.Framework.Is.EquivalentTo (IEnumerable expected) inline static
Returns a constraint that tests whether the actual value is a collection containing the same elements as the collection supplied as an argument.
Referenced by NUnit.Framework.CollectionAssert.AreEquivalent(), NUnit.Engine.Services.Tests.ResultServiceTests.AvailableFormats(), NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsMultipleCategories(), NUnit.Framework.Internal.TestXmlTests.CheckXmlForTest(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionEquivalenceTests(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.FixtureInstancesAreNamedCorrectly(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Syntax.CollectionEquivalentTest.SetUp(), and NUnit.Framework.Internal.PropertyBagTests.XmlIsProducedCorrectly().
static CollectionSubsetConstraint NUnit.Framework.Is.SubsetOf (IEnumerable expected) inline static
Returns a constraint that tests whether the actual value is a subset of the collection supplied as an argument.
Referenced by NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms(), NUnit.Framework.CollectionAssert.IsSubsetOf(), NUnit.Framework.Assertions.CollectionAssertTest.IsSubsetOf(), NUnit.Framework.Assertions.CollectionAssertTest.IsSubsetOfHandlesNull(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Syntax.CollectionSubsetTest.SetUp(), and NUnit.Framework.Tests.AssertSyntaxTests.SubsetTests().
static CollectionSupersetConstraint NUnit.Framework.Is.SupersetOf (IEnumerable expected) inline static
Returns a constraint that tests whether the actual value is a superset of the collection supplied as an argument.
Referenced by NUnit.Framework.CollectionAssert.IsSupersetOf().
static SubstringConstraint NUnit.Framework.Is.StringContaining (string expected) inline static
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.SubstringTests().
static StartsWithConstraint NUnit.Framework.Is.StringStarting (string expected) inline static
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.StartsWithTests().
static EndsWithConstraint NUnit.Framework.Is.StringEnding (string expected) inline static
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.EndsWithTests().
static RegexConstraint NUnit.Framework.Is.StringMatching (string pattern) inline static
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.RegularExpressionTests().
static SamePathConstraint NUnit.Framework.Is.SamePath (string expected) inline static
Returns a constraint that tests whether the path provided is the same as an expected path after canonicalization.
Referenced by NUnit.Engine.Services.Tests.DomainManagerStaticTests.ApplicationBaseTests(), NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomain(), NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CanLoadVsProject(), NUnit.Common.Tests.AssemblyHelperTests.GetAssemblyPathFromCodeBase(), NUnit.Framework.Constraints.SamePathTest_Windows.RootPathEquality(), NUnit.Framework.Constraints.SamePathTest_Linux.RootPathEquality(), NUnit.Framework.Syntax.SamePathTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_IgnoreCase.SetUp(), and NUnit.Framework.Syntax.SamePathTest_RespectCase.SetUp().
static SubPathConstraint NUnit.Framework.Is.SubPathOf (string expected) inline static
Returns a constraint that tests whether the path provided is a subpath of the expected path after canonicalization.
static SamePathOrUnderConstraint NUnit.Framework.Is.SamePathOrUnder (string expected) inline static
Returns a constraint that tests whether the path provided is the same path or under an expected path after canonicalization.
Referenced by NUnit.Framework.Syntax.SamePathOrUnderTest.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_IgnoreCase.SetUp(), and NUnit.Framework.Syntax.SamePathOrUnderTest_RespectCase.SetUp().
static RangeConstraint NUnit.Framework.Is.InRange (IComparable from, IComparable to) inline static
Returns a constraint that tests whether the actual value falls inclusively within a specified range.
from must be less than or equal to true
Parameters
from Inclusive beginning of the range. Must be less than or equal to to.
to Inclusive end of the range. Must be greater than or equal to from.
Returns
Referenced by NUnit.Framework.Constraints.RangeTests.FailingInRangeMethod(), NUnit.Framework.Constraints.RangeTests.InRangeSucceeds(), NUnit.Framework.Constraints.RangeTests.MixedRangeTests< TMin, TMax, TVal >(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomByte(), NUnit.Framework.Internal.RandomizerTests.RandomByte(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomByte_ByteRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomByte_IntRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDecimal(), NUnit.Framework.Internal.RandomizerTests.RandomDecimal(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDecimal_DoubleRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDecimal_IntRange(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalWithMaximum(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDouble(), NUnit.Framework.Internal.RandomizerTests.RandomDouble(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDouble_DoubleRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomFloat(), NUnit.Framework.Internal.RandomizerTests.RandomFloat(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomFloat_FloatRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomInt(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomInt_IntRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomLong(), NUnit.Framework.Internal.RandomizerTests.RandomLong(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomLong_LongRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomSByte(), NUnit.Framework.Internal.RandomizerTests.RandomSByte(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomSByte_IntRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomSByte_SByteRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomShort(), NUnit.Framework.Internal.RandomizerTests.RandomShort(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomShort_IntRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomShort_ShortRange(), NUnit.Framework.Attributes.CombinatorialTests.RandomTest(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUInt(), NUnit.Framework.Internal.RandomizerTests.RandomUInt(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUInt_UIntRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomULong(), NUnit.Framework.Internal.RandomizerTests.RandomULong(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomULong_ULongRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUShort(), NUnit.Framework.Internal.RandomizerTests.RandomUShort(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUShort_IntRange(), NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUShort_UShortRange(), NUnit.Framework.Constraints.RangeTests.RangeBoundaryConditions(), and NUnit.Framework.Constraints.RangeTests.ShouldThrowExceptionIfFromIsLessThanTo().
Property Documentation
ConstraintExpression NUnit.Framework.Is.Not static get
Returns a ConstraintExpression that negates any following constraint.
Referenced by NUnit.Framework.Constraints.AllItemsConstraintTests.AllItemsAreNotNull(), NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Assert.AreNotEqual(), NUnit.Framework.CollectionAssert.AreNotEqual(), NUnit.Framework.CollectionAssert.AreNotEquivalent(), NUnit.Framework.Assert.AreNotSame(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndEmptyArraySegment(), NUnit.Framework.Tests.AssertSyntaxTests.AssignableFromTypeTests(), NUnit.Framework.Internal.TestFixtureTests.FixtureNotNullTestAttribute.BeforeTest(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanCallTypeInfoOnAllPlatforms(), NUnit.Framework.Constraints.ReusableConstraintTests.CanCreateReusableConstraintByImplicitConversion(), NUnit.Framework.Constraints.ToStringTests.CanDisplayPrefixConstraints_Resolved(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnAssemblies(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnClasses(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnDerivedClasses(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnFields(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnMethods(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnParameters(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.CanGetAttributesOnProperties(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetContructorWithParams(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetGenericConstructor(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetGetMethod(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetInterfaces(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetMember(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetProperty(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetPublicField(), NUnit.Framework.Assertions.NullableTypesTests.CanTestForNull(), NUnit.Framework.Constraints.DelayedConstraintTests.CanTestInitiallyNullDelegate(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionEquivalenceTests(), NUnit.Framework.Syntax.MixedOperatorOverrides.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.ComplexTests(), NUnit.Framework.Tests.TestContextTests.ConstructorAccessWorkDirectory(), NUnit.Framework.Tests.TestContextTests.ConstructorCanAccessTestDirectory(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.CultureInfo_HasCultureInfoElement(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.CultureInfo_HasCultureInfoElement(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.CultureInfo_HasRequiredAttribute(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.CultureInfo_HasRequiredAttribute(), NUnit.Framework.Constraints.ToStringTests.DisplayPrefixConstraints_Unresolved(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_HasTestResults(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Document_HasTestResults(), NUnit.Framework.Tests.Compatibility.AttributeHelperTests.DoesNotGetAttributesOnDerivedClassesWhenInheritedIsFalse(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetPrivateMemberOnBaseClass(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetStaticMemberOnBaseClass(), NUnit.Framework.Assertions.AssertThrowsTests.DoesNotThrowFails(), NUnit.Framework.Assertions.ArrayEqualsFixture.EmptyArraySegmentAndArray(), NUnit.Framework.Tests.AssertSyntaxTests.EmptyCollectionTests(), NUnit.Framework.Tests.AssertSyntaxTests.EmptyStringTests(), NUnit.Framework.Tests.AssertSyntaxTests.EndsWithTests(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Environment_HasEnvironmentElement(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.Environment_HasEnvironmentElement(), NUnit.Framework.Tests.AssertSyntaxTests.EqualIgnoringCaseTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTests(), NUnit.Framework.Syntax.EqualityTests.EqualityTestsUsingDefaultFloatingPointTolerance(), NUnit.Framework.Syntax.EqualityTests.EqualityTestsWithTolerance(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTestsWithTolerance(), NUnit.Framework.Tests.AssertSyntaxTests.ExactTypeTests(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Engine.Services.Tests.ExtensionServiceTests.ExtensionsAreAddedToExtensionPoint(), NUnit.Framework.Constraints.RangeTests.FailingNotInRangeMethod(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureId(), NUnit.Framework.Tests.AssertSyntaxTests.InstanceOfTests(), NUnit.Framework.Assert.IsNotAssignableFrom(), NUnit.Framework.Assertions.TypeAssertTests.IsNotAssignableFrom(), NUnit.Framework.Assert.IsNotAssignableFrom< TExpected >(), NUnit.Framework.Assertions.TypeAssertTests.IsNotAssignableFromFails(), NUnit.Framework.Assert.IsNotEmpty(), NUnit.Framework.Assertions.TypeAssertTests.IsNotInstanceOf(), NUnit.Framework.Assert.IsNotInstanceOf(), NUnit.Framework.Assert.IsNotInstanceOf< TExpected >(), NUnit.Framework.Tests.AssertSyntaxTests.IsNotNull(), NUnit.Framework.Assert.IsNotNull(), NUnit.Framework.CollectionAssert.IsNotSubsetOf(), NUnit.Framework.Assertions.CollectionAssertTest.IsNotSubsetOf(), NUnit.Framework.CollectionAssert.IsNotSupersetOf(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_Assembly_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_GoodFile_ReturnsRunnableSuite(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MethodWithoutParamsIsNamedCorrectly(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MethodWithParamsIsNamedCorrectly(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTest(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTestWithinToleranceAndWithSameOffset(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTestWithTolerance(), NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTestWithToleranceAndWithSameOffset(), NUnit.Framework.Constraints.EmptyDirectoryConstraintTest.NotEmptyDirectory(), NUnit.Framework.Constraints.NotConstraintTests.NotHonorsIgnoreCaseUsingPrefixNotation(), NUnit.Framework.Constraints.NotConstraintTests.NotHonorsTolerance(), NUnit.Framework.Constraints.RangeTests.NotInRangeSucceeds(), NUnit.Framework.Assert.NotNull(), NUnit.Framework.Tests.AssertSyntaxTests.NotTests(), NUnit.Framework.Internal.TestExecutionContextTests.OneTimeTearDown(), NUnit.Framework.Tests.TestContextOneTimeTearDownTests.OneTimeTearDown(), NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.PackageIDsAreUnique(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Internal.RandomizerTests.Repeatability.RandomizersWithDifferentSeedsReturnDifferentValues(), NUnit.Framework.Tests.AssertSyntaxTests.RegularExpressionTests(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.RequiredAttribute(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.RequiredAttribute(), NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsDifferentRandomizersForDifferentMethods(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Syntax.NotTest.SetUp(), NUnit.Framework.Assertions.DirectoryAssertTests.SetUp(), NUnit.Framework.Syntax.NotTest_Cascaded.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndTest_ThreeAndsWithNot.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Internal.TextExecutionContextInAppDomain.SetUp(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestId(), NUnit.Framework.Syntax.EqualityTests.SimpleEqualityTests(), NUnit.Framework.Tests.AssertSyntaxTests.StartsWithTests(), NUnit.Framework.Tests.AssertSyntaxTests.SubsetTests(), NUnit.Framework.Tests.AssertSyntaxTests.SubstringTests(), NUnit.Framework.Tests.TestContextTearDownTests.TearDown(), NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnId(), NUnit.Framework.Internal.TestExecutionContextTests.TestCanAccessItsOwnId(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_CategoryElementsDoNotContainProperties(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_HasCategoryElement(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_HasPropertyElement(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestCase_PropertyElementsDoNotContainCategories(), NUnit.ConsoleRunner.Tests.ColorConsoleTests.TestConstructor(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_HasCategoryElement(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestFixture_HasPropertyElement(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestGlobalDefaultTolerance_Failure(), NUnit.Framework.Internal.FailedResultTests.TestResultXmlNodeEscapesInvalidXmlCharacters(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_HasTestSuiteElement(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadRunsInSeparateThread(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadWithMTAArgRunsOnSeparateThreadInMTA(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadWithSTAArgRunsOnSeparateThreadInSTA(), and NUnit.Framework.Attributes.TimeoutTests.TestWithTimeoutRunsOnSeparateThread().
ConstraintExpression NUnit.Framework.Is.All static get
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them succeed.
Referenced by NUnit.Framework.CollectionAssert.AllItemsAreInstancesOfType(), NUnit.Framework.CollectionAssert.AllItemsAreNotNull(), NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintAfterPrefix(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintsUnderAndOperator(), NUnit.Framework.Tests.AssertSyntaxTests.EndsWithTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualIgnoringCaseTests(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Tests.AssertSyntaxTests.RegularExpressionTests(), NUnit.Framework.Syntax.AllTest.SetUp(), NUnit.Framework.Tests.AssertSyntaxTests.StartsWithTests(), NUnit.Framework.Tests.AssertSyntaxTests.SubstringTests(), and NUnit.Framework.Constraints.AllItemsConstraintTests.WorksOnICollection().
NullConstraint NUnit.Framework.Is.Null static get
Returns a constraint that tests for null
Referenced by NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomain(), NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified(), NUnit.Framework.Assertions.NullableTypesTests.CanTestForNull(), NUnit.Framework.Syntax.MixedOperatorOverrides.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.ComplexTests(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetPrivateField(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetStaticPropertyOnBase(), NUnit.Framework.Internal.TestResultOutputTests.IfNothingIsWritten_XmlOutputIsEmpty(), NUnit.Framework.Tests.AssertSyntaxTests.IsNull(), NUnit.Framework.Assert.IsNull(), NUnit.Framework.Tests.AssertSyntaxTests.NotOperator(), NUnit.Framework.Assert.Null(), NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.NullTest(), NUnit.Framework.Syntax.AfterSyntaxUsingLambda.NullTest(), NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccess(), NUnit.Framework.Syntax.NullTest.SetUp(), NUnit.Framework.Syntax.NotOperatorOverride.SetUp(), and NUnit.Framework.Tests.TestContextTests.TestContextStoresFailureInfoForOneTimeTearDown().
TrueConstraint NUnit.Framework.Is.True static get
Returns a constraint that tests for True
Referenced by IG.Test.TestUtilities.ArraysConcatenateAndEquality(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetConstructors(), NUnit.Framework.Constraints.EqualityComparerTests.CanHandleMultipleImplementationsOfIEquatable(), NUnit.Framework.AssertionHelper.Expect(), IG.Test.TestCrypto.HashTypes(), NUnit.Framework.Constraints.EqualityComparerTests.ImplementingIEquatableDirectlyOnTheClass(), NUnit.Framework.Constraints.EqualityComparerTests.ImplementingIEquatableOnABaseClassOrInterface(), NUnit.Framework.Constraints.EqualityComparerTests.ImplementingIEquatableOnABaseClassOrInterfaceThroughInterface(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.IsAssignableFromTest(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.IsInstanceOfTypeTest(), NUnit.Framework.Tests.AssertSyntaxTests.IsTrue(), NUnit.Framework.Assert.IsTrue(), IG.Test.TestCrypto.Prerequisites(), NUnit.Framework.Syntax.TrueTest.SetUp(), NUnit.TestUtilities.TestDirectory.TestDirectory(), NUnit.Framework.Tests.TestContextOneTimeTearDownTests.TestTruth(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithoutPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithoutPolling_ReturnsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithPolling_ReturnsEarly(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithoutPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithPolling_FailsAfterDelay(), NUnit.Framework.Assert.True(), NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.TrueTest(), and NUnit.Framework.Syntax.AfterSyntaxUsingLambda.TrueTest().
FalseConstraint NUnit.Framework.Is.False static get
Returns a constraint that tests for False
Referenced by NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetConstructors(), NUnit.Framework.Constraints.EqualityComparerTests.CanHandleMultipleImplementationsOfIEquatable(), NUnit.Framework.Constraints.EqualityComparerTests.DifferentDirectoriesAreNotEqual(), NUnit.Framework.Assert.False(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.FixtureWithNoTestsShouldNotCallFixtureSetUpOrTearDown(), NUnit.Framework.Constraints.AndConstraintTests.HandlesFirstPartFailing(), NUnit.Framework.Constraints.UniqueItemsTests.HonorsIgnoreCase(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.IsAssignableFromTest(), NUnit.Framework.Tests.AssertSyntaxTests.IsFalse(), NUnit.Framework.Assert.IsFalse(), NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.IsInstanceOfTypeTest(), NUnit.Framework.Syntax.FalseTest.SetUp(), NUnit.Framework.Attributes.TestCaseAttributeTests.SupportsNullableDateTime(), NUnit.Framework.Attributes.TestCaseAttributeTests.SupportsNullableDecimal(), NUnit.Framework.Attributes.TestCaseAttributeTests.SupportsNullableTimeSpan(), NUnit.TestUtilities.TestDirectory.TestDirectory(), and NUnit.Framework.Tests.TestContextOneTimeTearDownTests.TestFalsehood().
GreaterThanConstraint NUnit.Framework.Is.Positive static get
Returns a constraint that tests for a positive value
Referenced by NUnit.Framework.Syntax.PositiveTest.SetUp().
LessThanConstraint NUnit.Framework.Is.Negative static get
Returns a constraint that tests for a negative value
Referenced by NUnit.Framework.Syntax.NegativeTest.SetUp().
NaNConstraint NUnit.Framework.Is.NaN static get
Returns a constraint that tests for NaN
Referenced by NUnit.Framework.Assertions.NullableTypesTests.CanTestForNaN(), NUnit.Framework.Tests.AssertSyntaxTests.IsNaN(), NUnit.Framework.Assert.IsNaN(), and NUnit.Framework.Syntax.NaNTest.SetUp().
EmptyConstraint NUnit.Framework.Is.Empty static get
Returns a constraint that tests for empty
Referenced by NUnitLite.Tests.TextUITests.DisplayRequestedOptions(), NUnitLite.Tests.TextUITests.DisplayRuntimeEnvironment(), NUnit.Framework.Tests.AssertSyntaxTests.EmptyCollectionTests(), NUnit.Framework.Constraints.EmptyDirectoryConstraintTest.EmptyDirectory(), NUnit.Framework.Tests.AssertSyntaxTests.EmptyStringTests(), NUnit.Framework.Internal.SuccessResultTests.SuiteResultIsSuccess(), NUnit.Framework.Internal.DefaultResultTests.TestResultIsInconclusive(), NUnit.Framework.Internal.InconclusiveResultTests.TestResultIsInconclusive(), and NUnit.Framework.Internal.SuccessResultTests.TestResultIsSuccess().
UniqueItemsConstraint NUnit.Framework.Is.Unique static get
Returns a constraint that tests whether a collection contains all unique items.
Referenced by NUnit.Framework.CollectionAssert.AllItemsAreUnique(), NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), and NUnit.Framework.Syntax.UniqueTest.SetUp().
BinarySerializableConstraint NUnit.Framework.Is.BinarySerializable static get
Returns a constraint that tests whether an object graph is serializable in binary format.
Referenced by NUnit.Framework.Syntax.BinarySerializableTest.SetUp().
XmlSerializableConstraint NUnit.Framework.Is.XmlSerializable static get
Returns a constraint that tests whether an object graph is serializable in xml format.
Referenced by NUnit.Framework.Syntax.XmlSerializableTest.SetUp().
CollectionOrderedConstraint NUnit.Framework.Is.Ordered static get
Returns a constraint that tests whether a collection is ordered
Referenced by NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered(), NUnit.Framework.CollectionAssert.IsOrdered(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_2(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_Allows_adjacent_equal_values(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_AtLeastOneArgMustImplementIComparable(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_Fails(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_Handles_custom_comparison(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_Handles_custom_comparison2(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_Handles_null(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrdered_TypesMustBeComparable(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrderedBy(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrderedBy_Comparer(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrderedBy_Handles_heterogeneous_classes_as_long_as_the_property_is_of_same_type(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrderedDescending(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrderedDescending_2(), NUnit.Framework.Syntax.CollectionOrderedTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Descending.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Descending.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer_Descending.SetUp(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.UsesProvidedGenericComparer(), NUnit.Framework.Constraints.CollectionOrderedConstraintTests.UsesProvidedGenericComparison(), and NUnit.Framework.Constraints.CollectionOrderedConstraintTests.UsesProvidedLambda().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Is.cs