IGLib: AP1.Complex Struct Reference
AP1.Complex Struct Reference
Public Member Functions
Complex (double _x)
Complex (double _x, double _y)
Static Public Member Functions
static implicit operator Complex (double _x)
static bool operator== (Complex lhs, Complex rhs)
static bool operator!= (Complex lhs, Complex rhs)
static Complex operator+ (Complex lhs)
static Complex operator- (Complex lhs)
static Complex operator+ (Complex lhs, Complex rhs)
static Complex operator- (Complex lhs, Complex rhs)
static Complex operator* (Complex lhs, Complex rhs)
static Complex operator/ (Complex lhs, Complex rhs)
Public Attributes
double x
double y
Constructor & Destructor Documentation
AP1.Complex.Complex (double _x) inline
Referenced by AP1.Complex.operator Complex(), AP1.Complex.operator*(), AP1.Complex.operator+(), and AP1.Complex.operator-().
AP1.Complex.Complex (double _x, double _y) inline
Member Function Documentation
static implicit AP1.Complex.operator Complex (double _x) inline static
References AP1.Complex.Complex().
static bool AP1.Complex.operator== (Complex lhs, Complex rhs) inline static
References AP1.Complex.x, and AP1.Complex.y.
static bool AP1.Complex.operator!= (Complex lhs, Complex rhs) inline static
References AP1.Complex.x, and AP1.Complex.y.
static Complex AP1.Complex.operator+ (Complex lhs) inline static
static Complex AP1.Complex.operator- (Complex lhs) inline static
References AP1.Complex.Complex(), AP1.Complex.x, and AP1.Complex.y.
static Complex AP1.Complex.operator+ (Complex lhs, Complex rhs) inline static
References AP1.Complex.Complex(), AP1.Complex.x, and AP1.Complex.y.
static Complex AP1.Complex.operator- (Complex lhs, Complex rhs) inline static
References AP1.Complex.Complex(), AP1.Complex.x, and AP1.Complex.y.
static Complex AP1.Complex.operator* (Complex lhs, Complex rhs) inline static
References AP1.Complex.Complex(), AP1.Complex.x, and AP1.Complex.y.
static Complex AP1.Complex.operator/ (Complex lhs, Complex rhs) inline static
References AP1.Complex.x, and AP1.Complex.y.
Member Data Documentation
double AP1.Complex.x
Referenced by AP1.Mathe.AbsComplex(), AP1.Mathe.Conj(), AP1.Mathe.CSqr(), AP1.Complex.operator!=(), AP1.Complex.operator*(), AP1.Complex.operator+(), AP1.Complex.operator-(), AP1.Complex.operator/(), and AP1.Complex.operator==().
double AP1.Complex.y
Referenced by AP1.Mathe.AbsComplex(), AP1.Mathe.Conj(), AP1.Mathe.CSqr(), AP1.Complex.operator!=(), AP1.Complex.operator*(), AP1.Complex.operator+(), AP1.Complex.operator-(), AP1.Complex.operator/(), and AP1.Complex.operator==().
The documentation for this struct was generated from the following file:
igtest/IGLibTestDev/opt/alglib/Alglib_Old_UniMb/AlgLib2008/OriginalCode/ap.cs