IGLib: NUnit.Framework.Constraints.CollectionEqualsTests Class Reference
NUnit.Framework.Constraints.CollectionEqualsTests Class Reference
Public Member Functions
void CanMatchTwoCollections ()
void CanMatchTwoLists ()
void CanMatchAnArrayWithACollection ()
void FailureMatchingArrayAndCollection ()
void HonorsIgnoreCase (IEnumerable expected, IEnumerable actual)
Static Private Attributes
static readonly object[] IgnoreCaseData
Member Function Documentation
void NUnit.Framework.Constraints.CollectionEqualsTests.CanMatchTwoCollections () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.CollectionEqualsTests.CanMatchTwoLists () inline
void NUnit.Framework.Constraints.CollectionEqualsTests.CanMatchAnArrayWithACollection () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.CollectionEqualsTests.FailureMatchingArrayAndCollection () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Constraints.CollectionEqualsTests.HonorsIgnoreCase (IEnumerable expected, IEnumerable actual) inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
Member Data Documentation
readonly object [] NUnit.Framework.Constraints.CollectionEqualsTests.IgnoreCaseData static private
Initial value:
=
        {
            new object[] {new SimpleObjectCollection("x", "y", "z"),new SimpleObjectCollection("x", "Y", "Z")},
            new object[] {new[] {'A', 'B', 'C'}, new object[] {'a', 'b', 'c'}},
            new object[] {new[] {"a", "b", "c"}, new object[] {"A", "B", "C"}},
            new object[] {new Dictionary<int, string> {{ 1, "a" }}, new Dictionary<int, string> {{ 1, "A" }}},
            new object[] {new Dictionary<int, char> {{ 1, 'A' }}, new Dictionary<int, char> {{ 1, 'a' }}},
            new object[] {new List<char> {'A', 'B', 'C'}, new List<char> {'a', 'b', 'c'}},
            new object[] {new List<string> {"a", "b", "c"}, new List<string> {"A", "B", "C"}},
        }
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/CollectionEqualsTests.cs