IGLib: NUnit.Engine.Services.TestAgency Class Reference
NUnit.Engine.Services.TestAgency Class Reference
The TestAgency class provides RemoteTestAgents on request and tracks their status. Agents are wrapped in an instance of the TestAgent class. Multiple agent types are supported but only one, ProcessAgent is implemented at this time.
Classes
class AgentDataBase
A simple class that tracks data about this agencies active and available agents
class AgentRecord
Public Member Functions
TestAgency ()
TestAgency (string uri, int port)
void Register (ITestAgent agent)
Registers an agent with an agency
void ReportStatus (Guid agentId, AgentStatus status)
ITestAgent GetAgent (TestPackage package, int waitTime)
void ReleaseAgent (ITestAgent agent)
void StopService ()
Do any cleanup needed before terminating the service
void StartService ()
Initialize the Service
Properties
IServiceLocator ServiceContext [get, set]
ServiceStatus Status [get, private set]
Properties inherited from NUnit.Engine.IService
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get]
Gets the ServiceStatus of this service
Private Member Functions
Guid LaunchAgentProcess (TestPackage package)
ITestAgent CreateRemoteAgent (TestPackage package, int waitTime)
Static Private Member Functions
static string GetNUnitBinDirectory (Version v)
Return the NUnit Bin Directory for a particular runtime version, or null if it's not installed. For normal installations, there are only 1.1 and 2.0 directories. However, this method accommodates 3.5 and 4.0 directories for the benefit of NUnit developers using those runtimes.
static string GetTestAgentExePath (Version v, bool requires32Bit)
Private Attributes
AgentDataBase _agentData = new AgentDataBase()
IRuntimeFrameworkService _runtimeService
Static Private Attributes
static Logger log = InternalTrace.GetLogger(typeof(TestAgency))
Additional Inherited Members
Protected Member Functions inherited from NUnit.Engine.Internal.ServerBase
ServerBase ()
ServerBase (string uri, int port)
Constructor used to provide
Protected Attributes inherited from NUnit.Engine.Internal.ServerBase
string uri
int port
Detailed Description
The TestAgency class provides RemoteTestAgents on request and tracks their status. Agents are wrapped in an instance of the TestAgent class. Multiple agent types are supported but only one, ProcessAgent is implemented at this time.
Constructor & Destructor Documentation
NUnit.Engine.Services.TestAgency.TestAgency () inline
NUnit.Engine.Services.TestAgency.TestAgency (string uri, int port) inline
Member Function Documentation
void NUnit.Engine.Services.TestAgency.Register (ITestAgent agent) inline
Registers an agent with an agency
Parameters
agent
Implements NUnit.Engine.ITestAgency.
References NUnit.Engine.Services.TestAgency.AgentRecord.Agent, and NUnit.Engine.ITestAgent.Id.
void NUnit.Engine.Services.TestAgency.ReportStatus (Guid agentId, AgentStatus status) inline
References NUnit.Engine.Services.TestAgency.AgentRecord.Status.
ITestAgent NUnit.Engine.Services.TestAgency.GetAgent (TestPackage package, int waitTime) inline
Referenced by NUnit.Engine.Runners.ProcessRunner.LoadPackage().
void NUnit.Engine.Services.TestAgency.ReleaseAgent (ITestAgent agent) inline
References NUnit.Common.Logger.Debug(), NUnit.Common.Logger.Error(), NUnit.Engine.ITestAgent.Id, and NUnit.Engine.Services.TestAgency.AgentRecord.Status.
Guid NUnit.Engine.Services.TestAgency.LaunchAgentProcess (TestPackage package) inline private
References NUnit.Engine.Services.TestAgency.AgentDataBase.Add(), NUnit.Engine.RuntimeFramework.ClrVersion, NUnit.Engine.RuntimeFramework.CurrentFramework, NUnit.Common.Logger.Debug(), NUnit.Common.PackageSettings.DebugAgent, NUnit.Common.PackageSettings.DebugTests, NUnit.Engine.RuntimeFramework.GetBestAvailableFramework(), NUnit.Common.Logger.Info(), NUnit.Engine.RuntimeFramework.IsAvailable, NUnit.Engine.Internal.NUnitConfiguration.MonoExePath, NUnit.Engine.RuntimeFramework.Parse(), NUnit.Common.PackageSettings.RunAsX86, NUnit.Engine.RuntimeFramework.Runtime, NUnit.Common.PackageSettings.RuntimeFramework, and NUnit.Engine.IRuntimeFrameworkService.SelectRuntimeFramework().
ITestAgent NUnit.Engine.Services.TestAgency.CreateRemoteAgent (TestPackage package, int waitTime) inline private
References NUnit.Common.Logger.Debug().
static string NUnit.Engine.Services.TestAgency.GetNUnitBinDirectory (Version v) inline static private
Return the NUnit Bin Directory for a particular runtime version, or null if it's not installed. For normal installations, there are only 1.1 and 2.0 directories. However, this method accommodates 3.5 and 4.0 directories for the benefit of NUnit developers using those runtimes.
References NUnit.Engine.Internal.NUnitConfiguration.NUnitBinDirectory.
static string NUnit.Engine.Services.TestAgency.GetTestAgentExePath (Version v, bool requires32Bit) inline static private
References NUnit.Engine.Internal.NUnitConfiguration.NUnitBinDirectory.
void NUnit.Engine.Services.TestAgency.StopService () inline
Do any cleanup needed before terminating the service
Implements NUnit.Engine.IService.
void NUnit.Engine.Services.TestAgency.StartService () inline
Initialize the Service
Implements NUnit.Engine.IService.
References NUnit.Engine.ServiceContext.GetService().
Member Data Documentation
Logger NUnit.Engine.Services.TestAgency.log = InternalTrace.GetLogger(typeof(TestAgency)) static private
AgentDataBase NUnit.Engine.Services.TestAgency._agentData = new AgentDataBase() private
IRuntimeFrameworkService NUnit.Engine.Services.TestAgency._runtimeService private
Property Documentation
IServiceLocator NUnit.Engine.Services.TestAgency.ServiceContext get set
ServiceStatus NUnit.Engine.Services.TestAgency.Status get private set
Referenced by NUnit.Engine.Services.Tests.TestAgencyTests.ServiceIsStarted().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/TestAgency.cs