IGLib: alglib.ap Class Reference
alglib.ap Class Reference
Static Public Member Functions
static int len< T > (T[] a)
static int rows< T > (T[,] a)
static int cols< T > (T[,] a)
static void swap< T > (ref T a, ref T b)
static void assert (bool cond, string s)
static void assert (bool cond)
static int threshold2dps (double threshold)
static string format (complex a, int _dps)
static string format (bool[] a)
static string format (int[] a)
static string format (double[] a, int _dps)
static string format (complex[] a, int _dps)
static string format (bool[,] a)
static string format (int[,] a)
static string format (double[,] a, int dps)
static string format (complex[,] a, int dps)
static bool issymmetric (double[,] a)
static bool ishermitian (complex[,] a)
static bool forcesymmetric (double[,] a)
static bool forcehermitian (complex[,] a)
static int len< T > (T[] a)
static int rows< T > (T[,] a)
static int cols< T > (T[,] a)
static void swap< T > (ref T a, ref T b)
static void assert (bool cond, string s)
static void assert (bool cond)
static int threshold2dps (double threshold)
static string format (complex a, int _dps)
static string format (bool[] a)
static string format (int[] a)
static string format (double[] a, int _dps)
static string format (complex[] a, int _dps)
static string format (bool[,] a)
static string format (int[,] a)
static string format (double[,] a, int dps)
static string format (complex[,] a, int dps)
static bool issymmetric (double[,] a)
static bool ishermitian (complex[,] a)
static bool forcesymmetric (double[,] a)
static bool forcehermitian (complex[,] a)
Member Function Documentation
static int alglib.ap.len< T > (T[] a) inline static
static int alglib.ap.rows< T > (T a[,]) inline static
static int alglib.ap.cols< T > (T a[,]) inline static
static void alglib.ap.swap< T > (ref T a, ref T b) inline static
static void alglib.ap.assert (bool cond, string s) inline static
Referenced by alglib.mlpbase.addactivationlayer(), alglib.testlinlsqrunit.analytictest(), alglib.apserv.apperiodicmap(), alglib.apserv.apservisfinitecmatrix(), alglib.apserv.apservisfinitectrmatrix(), alglib.apserv.apservisfinitematrix(), alglib.apserv.apservisfiniteornanmatrix(), alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.autogk.autogksingular(), alglib.autogk.autogksmooth(), alglib.autogk.autogksmoothw(), alglib.ratint.barycentricbuildfloaterhormann(), alglib.ratint.barycentricbuildxyw(), alglib.ratint.barycentriccalc(), alglib.ratint.barycentricdiff1(), alglib.ratint.barycentricdiff2(), alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.bessel.besselk0(), alglib.bessel.besselk1(), alglib.bessel.besselkn(), alglib.betaf.beta(), alglib.binomialdistr.binomialcdistribution(), alglib.binomialdistr.binomialdistribution(), alglib.optserv.calculatestepbound(), alglib.chisquaredistr.chisquarecdistribution(), alglib.chisquaredistr.chisquaredistribution(), alglib.clustering.clusterizergetdistances(), alglib.clustering.clusterizergetkclusters(), alglib.clustering.clusterizerrunkmeans(), alglib.clustering.clusterizersetahcalgo(), alglib.clustering.clusterizersetdistances(), alglib.clustering.clusterizersetkmeanslimits(), alglib.clustering.clusterizersetpoints(), alglib.densesolver.cmatrixlusolveinternal(), alglib.safesolve.cmatrixscaledtrsafesolve(), alglib.conv.convc1d(), alglib.conv.convc1dcircular(), alglib.conv.convc1dcircularinv(), alglib.conv.convc1dinv(), alglib.conv.convc1dx(), alglib.conv.convr1d(), alglib.conv.convr1dcircular(), alglib.conv.convr1dcircularinv(), alglib.conv.convr1dinv(), alglib.conv.convr1dx(), alglib.blas.copyandtranspose(), alglib.blas.copymatrix(), alglib.corr.corrc1d(), alglib.corr.corrc1dcircular(), alglib.corr.corrr1d(), alglib.corr.corrr1dcircular(), alglib.basestat.cov2(), alglib.basestat.covm(), alglib.basestat.covm2(), alglib.cqmodels.cqmadx(), alglib.cqmodels.cqmdebugconstrainedevale(), alglib.cqmodels.cqmdebugconstrainedevalt(), alglib.cqmodels.cqmeval(), alglib.cqmodels.cqmevalx(), alglib.cqmodels.cqmgradunconstrained(), alglib.cqmodels.cqmrebuild(), alglib.cqmodels.cqmseta(), alglib.cqmodels.cqmsetactiveset(), alglib.cqmodels.cqmsetb(), alglib.cqmodels.cqmsetd(), alglib.cqmodels.cqmsetq(), alglib.cqmodels.cqmsolveea(), alglib.cqmodels.cqmxtadx2(), alglib.testmlpeunit.createensemble(), alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.testsparseunit.createrandom(), alglib.dforest.dfbuildtree(), alglib.dforest.dfbuildtreerec(), alglib.dforest.dfsplitc(), alglib.dforest.dfsplitr(), alglib.dforest.dfunserialize(), alglib.testclusteringunit.distfunc(), alglib.bdss.dsoptimalsplitk(), alglib.bdss.dssplitk(), alglib.elliptic.ellipticintegrale(), alglib.testspline1dunit.enumerateallsplines(), alglib.fdistr.fcdistribution(), alglib.fdistr.fdistribution(), alglib.fft.fftc1d(), alglib.fft.fftc1dinv(), alglib.ftbase.ffticltrec(), alglib.ftbase.fftirltrec(), alglib.fft.fftr1d(), alglib.fft.fftr1dinternaleven(), alglib.fft.fftr1dinv(), alglib.fft.fftr1dinvinternaleven(), alglib.fht.fhtr1d(), alglib.fht.fhtr1dinv(), alglib.mlpbase.fillhighlevelinformation(), alglib.optserv.filterdirection(), alglib.filters.filterema(), alglib.filters.filterlrma(), alglib.filters.filtersma(), alglib.ntheory.findprimitiverootandinverse(), alglib.lda.fisherldan(), alglib.ftbase.ftapplycomplexcodeletfft(), alglib.ftbase.ftapplycomplexreffft(), alglib.ftbase.ftapplysubplan(), alglib.ftbase.ftbasefindsmoothrec(), alglib.ftbase.ftbasegeneratecomplexfftplan(), alglib.ftbase.ftbasegeneraterealfftplan(), alglib.ftbase.ftbasegeneraterealfhtplan(), alglib.ftbase.ftcomplexfftplan(), alglib.ftbase.ftcomplexfftplanrec(), alglib.testmincgunit.funcderiv(), alglib.testminbleicunit.funcderiv(), alglib.testminlbfgsunit.funcderiv(), alglib.testminlmunit.funcderiv(), alglib.testlsfitunit.funcderiv(), alglib.testldaunit.gendeg1set(), alglib.testldaunit.gensimpleset(), alglib.gkq.gkqlegendretbl(), alglib.mlpbase.hladdoutputlayer(), alglib.densesolver.hpdmatrixcholeskysolveinternal(), alglib.hqrnd.hqrndcontinuous(), alglib.hqrnd.hqrnddiscrete(), alglib.hqrnd.hqrndexponential(), alglib.hqrnd.hqrndintegerbase(), alglib.hqrnd.hqrnduniformi(), alglib.idwint.idwbuildmodifiedshepard(), alglib.idwint.idwbuildmodifiedshepardr(), alglib.idwint.idwbuildnoisy(), alglib.ibetaf.incompletebeta(), alglib.blas.inplacetranspose(), alglib.testortfacunit.internalmatrixmatrixmultiply(), alglib.hsschur.internalschurdecomposition(), alglib.binomialdistr.invbinomialdistribution(), alglib.chisquaredistr.invchisquaredistribution(), alglib.fdistr.invfdistribution(), alglib.ibetaf.invincompletebeta(), alglib.poissondistr.invpoissondistribution(), alglib.studenttdistr.invstudenttdistribution(), alglib.apserv.isfinitecvector(), alglib.apserv.isfinitertrmatrix(), alglib.apserv.isfinitevector(), alglib.testlinlsqrunit.isitgoodsolution(), alglib.testmatgenunit.isspd(), alglib.jacobianelliptic.jacobianellipticfunctions(), alglib.jarquebera.jarqueberastatistic(), alglib.nearestneighbor.kdtreeallocdatasetdependent(), alglib.nearestneighbor.kdtreeallocdatasetindependent(), alglib.nearestneighbor.kdtreealloctemporaries(), alglib.nearestneighbor.kdtreebuild(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.nearestneighbor.kdtreegeneratetreerec(), alglib.nearestneighbor.kdtreeinitbox(), alglib.nearestneighbor.kdtreequeryaknn(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequerynnrec(), alglib.nearestneighbor.kdtreequeryrnn(), alglib.nearestneighbor.kdtreesplit(), alglib.nearestneighbor.kdtreeunserialize(), alglib.lincg.lincgcreate(), alglib.lincg.lincgiteration(), alglib.lincg.lincgresults(), alglib.lincg.lincgsetb(), alglib.lincg.lincgsetcond(), alglib.lincg.lincgsetprecdiag(), alglib.lincg.lincgsetprecunit(), alglib.lincg.lincgsetrestartfreq(), alglib.lincg.lincgsetrupdatefreq(), alglib.lincg.lincgsetstartingpoint(), alglib.lincg.lincgsolvesparse(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetcond(), alglib.linlsqr.linlsqrsetlambdai(), alglib.linlsqr.linlsqrsetprecdiag(), alglib.linlsqr.linlsqrsetprecunit(), alglib.linlsqr.linlsqrsolvesparse(), alglib.linreg.lravgerror(), alglib.linreg.lravgrelerror(), alglib.linreg.lrprocess(), alglib.linreg.lrrmserror(), alglib.linreg.lrunpack(), alglib.testinverseupdateunit.matlu(), alglib.blas.matrixmatrixmultiply(), alglib.blas.matrixvectormultiply(), alglib.mcpd.mcpdcreate(), alglib.mcpd.mcpdcreateentry(), alglib.minbleic.minbleiccreate(), alglib.minbleic.minbleiccreatef(), alglib.minbleic.minbleiciteration(), alglib.minbleic.minbleicrestartfrom(), alglib.minbleic.minbleicsetbc(), alglib.minbleic.minbleicsetgradientcheck(), alglib.minbleic.minbleicsetinnercond(), alglib.minbleic.minbleicsetlc(), alglib.minbleic.minbleicsetmaxits(), alglib.minbleic.minbleicsetoutercond(), alglib.minbleic.minbleicsetprecdiag(), alglib.minbleic.minbleicsetscale(), alglib.minbleic.minbleicsetstpmax(), alglib.mincg.mincgcreate(), alglib.mincg.mincgcreatef(), alglib.mincg.mincgrestartfrom(), alglib.mincg.mincgsetcgtype(), alglib.mincg.mincgsetcond(), alglib.mincg.mincgsetgradientcheck(), alglib.mincg.mincgsetprecdiag(), alglib.mincg.mincgsetscale(), alglib.mincg.mincgsetstpmax(), alglib.mincg.mincgsuggeststep(), alglib.minlbfgs.minlbfgscreate(), alglib.mlpbase.mlpchunkedgradient(), alglib.mlpbase.mlpcreate(), alglib.mlpbase.mlpcreatec0(), alglib.mlpbase.mlpcreatec1(), alglib.mlpbase.mlpcreatec2(), alglib.mlpbase.mlpgetinputscaling(), alglib.mlpbase.mlpgetlayersize(), alglib.mlpbase.mlpgetneuroninfo(), alglib.mlpbase.mlpgetoutputscaling(), alglib.mlpbase.mlpgetweight(), alglib.mlpbase.mlphessianbatchinternal(), alglib.mlpbase.mlpinternalcalculategradient(), alglib.mlpbase.mlpinternalprocessvector(), alglib.mlpbase.mlpsetinputscaling(), alglib.mlpbase.mlpsetneuroninfo(), alglib.mlpbase.mlpsetoutputscaling(), alglib.mlpbase.mlpsetweight(), alglib.mlpbase.mlpunserialize(), alglib.mlpbase.mlpunserializeold(), alglib.logit.mnlallerrors(), alglib.logit.mnlavgce(), alglib.logit.mnlavgerror(), alglib.logit.mnlavgrelerror(), alglib.logit.mnlclserror(), alglib.logit.mnliexp(), alglib.logit.mnlprocess(), alglib.logit.mnlrmserror(), alglib.logit.mnlunpack(), alglib.ntheory.modexp(), alglib.ntheory.modmul(), alglib.testablasunit.naivematrixmatrixmultiply(), alglib.testblasunit.naivematrixmatrixmultiply(), alglib.nleq.nleqcreatelm(), alglib.nleq.nleqrestartfrom(), alglib.nleq.nleqsetcond(), alglib.nleq.nleqsetstpmax(), alglib.odesolver.odesolveriteration(), alglib.odesolver.odesolverrkck(), alglib.basestat.pearsoncorr2(), alglib.basestat.pearsoncorrm(), alglib.basestat.pearsoncorrm2(), alglib.poissondistr.poissoncdistribution(), alglib.poissondistr.poissondistribution(), alglib.polint.polynomialbar2cheb(), alglib.polint.polynomialbar2pow(), alglib.polint.polynomialbuild(), alglib.polint.polynomialbuildcheb1(), alglib.polint.polynomialbuildcheb2(), alglib.polint.polynomialbuildeqdist(), alglib.polint.polynomialcalccheb1(), alglib.polint.polynomialcalccheb2(), alglib.polint.polynomialcalceqdist(), alglib.polint.polynomialcheb2bar(), alglib.lsfit.polynomialfit(), alglib.lsfit.polynomialfitwc(), alglib.polint.polynomialpow2bar(), alglib.optserv.postprocessboundedstep(), alglib.mincg.preconditionedmultiply(), alglib.mincg.preconditionedmultiply2(), alglib.testminqpunit.projectedantigradnorm(), alglib.optserv.projectgradientintobc(), alglib.psif.psi(), alglib.apserv.randomunit(), alglib.basestat.rankdata(), alglib.basestat.rankdatabasecase(), alglib.basestat.rankdatacentered(), alglib.basestat.rankdatarec(), alglib.testfftunit.reffftc1d(), alglib.testfftunit.reffftc1dinv(), alglib.ftbase.reffht(), alglib.testfhtunit.reffhtr1d(), alglib.testfhtunit.reffhtr1dinv(), alglib.ablas.rmatrixgemm(), alglib.ablasf.rmatrixgemmk44v00(), alglib.ablasf.rmatrixgemmk44v01(), alglib.ablasf.rmatrixgemmk44v10(), alglib.ablasf.rmatrixgemmk44v11(), alglib.densesolver.rmatrixlusolveinternal(), alglib.ortfac.rmatrixqrunpackq(), alglib.safesolve.rmatrixscaledtrsafesolve(), alglib.basestat.sampleadev(), alglib.basestat.samplemedian(), alglib.basestat.samplemoments(), alglib.basestat.samplepercentile(), alglib.testrbfunit.searcherr(), alglib.snnls.snnlssetproblem(), alglib.spline1d.solvecubicpolinom(), alglib.densesolver.spdmatrixcholeskysolveinternal(), alglib.basestat.spearmancorr2(), alglib.basestat.spearmancorrm(), alglib.basestat.spearmancorrm2(), alglib.spline1d.spline1dbuildakima(), alglib.spline1d.spline1dbuildcatmullrom(), alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1dbuildhermite(), alglib.spline1d.spline1dbuildlinear(), alglib.spline1d.spline1dbuildmonotone(), alglib.spline1d.spline1dcalc(), alglib.spline1d.spline1dconvcubic(), alglib.spline1d.spline1dconvdiff2cubic(), alglib.spline1d.spline1dconvdiffcubic(), alglib.spline1d.spline1ddiff(), alglib.spline1d.spline1dgriddiff2cubic(), alglib.spline1d.spline1dgriddiffcubic(), alglib.spline1d.spline1dlintransx(), alglib.spline1d.spline1dlintransy(), alglib.spline1d.spline1drootsandextrema(), alglib.apserv.splitlength(), alglib.apserv.splitlengtheven(), alglib.studenttdistr.studenttdistribution(), alglib.apserv.taskgenint1d(), alglib.apserv.taskgenint1dcheb1(), alglib.apserv.taskgenint1dcheb2(), alglib.apserv.taskgenint1dequidist(), alglib.testmcpdunit.testbc(), alglib.testconvunit.testconv(), alglib.testidwintunit.testdegree(), alglib.testmcpdunit.testec(), alglib.testnlequnit.testfunchb1(), alglib.testnlequnit.testfunchbm(), alglib.testnlequnit.testfuncshbm(), alglib.testmlptrainunit.testgradient(), alglib.testmlpbaseunit.testhessian(), alglib.testmlptrainunit.testhessian(), alglib.testnearestneighborunit.testkdtuniform(), alglib.testmcpdunit.testlc(), alglib.testlinregunit.testlinreg(), alglib.testminlmunit.testminlm(), alglib.testodesolverunit.testodesolver(), alglib.testlsfitunit.testpolynomialfitting(), alglib.testmlpbaseunit.testprocessing(), alglib.testmlptrainunit.testprocessing(), alglib.testpsplineunit.testpspline(), alglib.testlsfitunit.testrationalfitting(), alglib.testspline1dunit.testspline1d(), alglib.testlsfitunit.testsplinefitting(), alglib.testxblasunit.testxblas(), alglib.testlinregunit.unsetlr(), alglib.blas.upperhessenberg1norm(), alglib.xdebug.xdebugmaskedbiasedproductsum(), and alglib.xblas.xsum().
static void alglib.ap.assert (bool cond) inline static
References alglib.ap.assert().
static int alglib.ap.threshold2dps (double threshold) inline static
static string alglib.ap.format (complex a, int _dps) inline static
References alglib.complex.x, and alglib.complex.y.
Referenced by alglib.ap.format().
static string alglib.ap.format (bool[] a) inline static
static string alglib.ap.format (int[] a) inline static
static string alglib.ap.format (double[] a, int _dps) inline static
static string alglib.ap.format (complex[] a, int _dps) inline static
References alglib.complex.y.
static string alglib.ap.format (bool a[,]) inline static
References alglib.ap.format().
static string alglib.ap.format (int a[,]) inline static
References alglib.ap.format().
static string alglib.ap.format (double a[,], int dps) inline static
References alglib.ap.format().
static string alglib.ap.format (complex a[,], int dps) inline static
References alglib.ap.format().
static bool alglib.ap.issymmetric (double a[,]) inline static
References alglib.math.isfinite().
Referenced by alglib.minqpsetquadraticterm(), alglib.spdmatrixdet(), and alglib.spdmatrixinverse().
static bool alglib.ap.ishermitian (complex a[,]) inline static
References alglib.math.abscomplex(), alglib.math.isfinite(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.hpdmatrixinverse().
static bool alglib.ap.forcesymmetric (double a[,]) inline static
Referenced by alglib.spdmatrixinverse().
static bool alglib.ap.forcehermitian (complex a[,]) inline static
References alglib.complex.x, and alglib.complex.y.
Referenced by alglib.hpdmatrixinverse().
static int alglib.ap.len< T > (T[] a) inline static
static int alglib.ap.rows< T > (T a[,]) inline static
static int alglib.ap.cols< T > (T a[,]) inline static
static void alglib.ap.swap< T > (ref T a, ref T b) inline static
static void alglib.ap.assert (bool cond, string s) inline static
static void alglib.ap.assert (bool cond) inline static
static int alglib.ap.threshold2dps (double threshold) inline static
static string alglib.ap.format (complex a, int _dps) inline static
static string alglib.ap.format (bool[] a) inline static
static string alglib.ap.format (int[] a) inline static
static string alglib.ap.format (double[] a, int _dps) inline static
static string alglib.ap.format (complex[] a, int _dps) inline static
static string alglib.ap.format (bool a[,]) inline static
static string alglib.ap.format (int a[,]) inline static
static string alglib.ap.format (double a[,], int dps) inline static
static string alglib.ap.format (complex a[,], int dps) inline static
static bool alglib.ap.issymmetric (double a[,]) inline static
References alglib.math.isfinite().
static bool alglib.ap.ishermitian (complex a[,]) inline static
References alglib.math.abscomplex(), and alglib.math.isfinite().
static bool alglib.ap.forcesymmetric (double a[,]) inline static
static bool alglib.ap.forcehermitian (complex a[,]) inline static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/ap.cs