IGLib: NUnit.Engine.Services.DefaultTestRunnerFactory Class Reference
NUnit.Engine.Services.DefaultTestRunnerFactory Class Reference
DefaultTestRunnerFactory handles creation of a suitable test runner for a given package to be loaded and run either in a separate process or within the same process.
Public Member Functions
override void StartService ()
Initialize the Service
override ITestEngineRunner MakeTestRunner (TestPackage package)
Returns a test runner based on the settings in a TestPackage. Any setting that is "consumed" by the factory is removed, so that downstream runners using the factory will not repeatedly create the same type of runner.
override bool CanReuse (ITestEngineRunner runner, TestPackage package)
Return true if the provided runner is suitable for reuse in loading the test package provided. Otherwise, return false. Runners that cannot be reused must always return false.
Public Member Functions inherited from NUnit.Engine.Services.Service
virtual void StopService ()
Do any cleanup needed before terminating the service
void Dispose ()
Private Member Functions
ProcessModel GetTargetProcessModel (TestPackage package)
Private Attributes
IProjectService _projectService
Additional Inherited Members
Protected Member Functions inherited from NUnit.Engine.Services.Service
virtual void Dispose (bool disposing)
Protected Attributes inherited from NUnit.Engine.Services.Service
bool _disposed = false
Properties inherited from NUnit.Engine.Services.Service
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get, protected set]
Gets the ServiceStatus of this service
Properties inherited from NUnit.Engine.IService
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get]
Gets the ServiceStatus of this service
Detailed Description
DefaultTestRunnerFactory handles creation of a suitable test runner for a given package to be loaded and run either in a separate process or within the same process.
Member Function Documentation
override void NUnit.Engine.Services.DefaultTestRunnerFactory.StartService () inline virtual
Initialize the Service
Reimplemented from NUnit.Engine.Services.Service.
References NUnit.Engine.ServiceContext.GetService().
override ITestEngineRunner NUnit.Engine.Services.DefaultTestRunnerFactory.MakeTestRunner (TestPackage package) inline
Returns a test runner based on the settings in a TestPackage. Any setting that is "consumed" by the factory is removed, so that downstream runners using the factory will not repeatedly create the same type of runner.
Parameters
package The TestPackage to be loaded and run
Returns
A TestRunner
Implements NUnit.Engine.ITestRunnerFactory.
References NUnit.Engine.Services.IProjectService.CanLoadFrom(), NUnit.Engine.Services.IProjectService.ExpandProjectPackage(), and NUnit.Engine.Internal.PathUtils.IsAssemblyFileType().
Referenced by NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed(), and NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed_InvalidExtension().
override bool NUnit.Engine.Services.DefaultTestRunnerFactory.CanReuse (ITestEngineRunner runner, TestPackage package) inline
Return true if the provided runner is suitable for reuse in loading the test package provided. Otherwise, return false. Runners that cannot be reused must always return false.
Parameters
runner An ITestRunner to possibly be used.
package The TestPackage to be loaded.
Returns
True if the runner may be reused for the provided package.
Implements NUnit.Engine.ITestRunnerFactory.
ProcessModel NUnit.Engine.Services.DefaultTestRunnerFactory.GetTargetProcessModel (TestPackage package) inline private
References NUnit.Common.PackageSettings.ProcessModel.
Member Data Documentation
IProjectService NUnit.Engine.Services.DefaultTestRunnerFactory._projectService private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/DefaultTestRunnerFactory.cs