IGLib: alglib.testevdunit Class Reference
alglib.testevdunit Class Reference
Static Public Member Functions
static bool testevd (bool silent)
static bool testevd (bool silent)
static bool _pexec_testevd (bool silent)
Static Private Member Functions
static void rmatrixfillsparsea (ref double[,] a, int m, int n, double sparcity)
static void cmatrixfillsparsea (ref complex[,] a, int m, int n, double sparcity)
static void rmatrixsymmetricsplit (double[,] a, int n, ref double[,] al, ref double[,] au)
static void cmatrixhermitiansplit (complex[,] a, int n, ref complex[,] al, ref complex[,] au)
static void unset2d (ref double[,] a)
static void cunset2d (ref complex[,] a)
static void unset1d (ref double[] a)
static void cunset1d (ref complex[] a)
static double tdtestproduct (double[] d, double[] e, int n, double[,] z, double[] lambdav)
static double testproduct (double[,] a, int n, double[,] z, double[] lambdav)
static double testort (double[,] z, int n)
static double testcproduct (complex[,] a, int n, complex[,] z, double[] lambdav)
static double testcort (complex[,] z, int n)
static void testsevdproblem (double[,] a, double[,] al, double[,] au, int n, double threshold, ref bool serrors, ref int failc, ref int runs)
static void testhevdproblem (complex[,] a, complex[,] al, complex[,] au, int n, double threshold, ref bool herrors, ref int failc, ref int runs)
static void testsevdbiproblem (double[,] afull, double[,] al, double[,] au, int n, bool distvals, double threshold, ref bool serrors, ref int failc, ref int runs)
static void testhevdbiproblem (complex[,] afull, complex[,] al, complex[,] au, int n, bool distvals, double threshold, ref bool herrors, ref int failc, ref int runs)
static void testtdevdproblem (double[] d, double[] e, int n, double threshold, ref bool tderrors, ref int failc, ref int runs)
static void testtdevdbiproblem (double[] d, double[] e, int n, bool distvals, double threshold, ref bool serrors, ref int failc, ref int runs)
static void testnsevdproblem (double[,] a, int n, double threshold, ref bool nserrors, ref int failc, ref int runs)
static void testevdset (int n, double threshold, double bithreshold, ref int failc, ref int runs, ref bool nserrors, ref bool serrors, ref bool herrors, ref bool tderrors, ref bool sbierrors, ref bool hbierrors, ref bool tdbierrors)
static void rmatrixfillsparsea (ref double[,] a, int m, int n, double sparcity)
static void cmatrixfillsparsea (ref complex[,] a, int m, int n, double sparcity)
static void rmatrixsymmetricsplit (double[,] a, int n, ref double[,] al, ref double[,] au)
static void cmatrixhermitiansplit (complex[,] a, int n, ref complex[,] al, ref complex[,] au)
static void unset2d (ref double[,] a)
static void cunset2d (ref complex[,] a)
static void unset1d (ref double[] a)
static void cunset1d (ref complex[] a)
static double tdtestproduct (double[] d, double[] e, int n, double[,] z, double[] lambdav)
static double testproduct (double[,] a, int n, double[,] z, double[] lambdav)
static double testort (double[,] z, int n)
static double testcproduct (complex[,] a, int n, complex[,] z, double[] lambdav)
static double testcort (complex[,] z, int n)
static void testsevdproblem (double[,] a, double[,] al, double[,] au, int n, double threshold, ref bool serrors, ref int failc, ref int runs)
static void testhevdproblem (complex[,] a, complex[,] al, complex[,] au, int n, double threshold, ref bool herrors, ref int failc, ref int runs)
static void testsevdbiproblem (double[,] afull, double[,] al, double[,] au, int n, bool distvals, double threshold, ref bool serrors, ref int failc, ref int runs)
static void testhevdbiproblem (complex[,] afull, complex[,] al, complex[,] au, int n, bool distvals, double threshold, ref bool herrors, ref int failc, ref int runs)
static void testtdevdproblem (double[] d, double[] e, int n, double threshold, ref bool tderrors, ref int failc, ref int runs)
static void testtdevdbiproblem (double[] d, double[] e, int n, bool distvals, double threshold, ref bool serrors, ref int failc, ref int runs)
static void testnsevdproblem (double[,] a, int n, double threshold, ref bool nserrors, ref int failc, ref int runs)
static void testevdset (int n, double threshold, double bithreshold, ref int failc, ref int runs, ref bool nserrors, ref bool serrors, ref bool herrors, ref bool tderrors, ref bool sbierrors, ref bool hbierrors, ref bool tdbierrors)
Member Function Documentation
static bool alglib.testevdunit.testevd (bool silent) inline static
References alglib.ablas.ablasblocksize(), alglib.math.machineepsilon, and alglib.testevdunit.testevdset().
Referenced by alglib.testevdunit._pexec_testevd(), and _Test.Main().
static void alglib.testevdunit.rmatrixfillsparsea (ref double a[,], int m, int n, double sparcity) inline static private
References alglib.math.randomreal().
Referenced by alglib.testevdunit.testevdset().
static void alglib.testevdunit.cmatrixfillsparsea (ref complex a[,], int m, int n, double sparcity) inline static private
References alglib.math.randomreal().
Referenced by alglib.testevdunit.testevdset().
static void alglib.testevdunit.rmatrixsymmetricsplit (double a[,], int n, ref double al[,], ref double au[,]) inline static private
References alglib.math.randomreal().
Referenced by alglib.testevdunit.testevdset().
static void alglib.testevdunit.cmatrixhermitiansplit (complex a[,], int n, ref complex al[,], ref complex au[,]) inline static private
References alglib.math.conj(), and alglib.math.randomreal().
Referenced by alglib.testevdunit.testevdset().
static void alglib.testevdunit.unset2d (ref double a[,]) inline static private
References alglib.math.randomreal().
Referenced by alglib.testevdunit.testsevdbiproblem(), and alglib.testevdunit.testsevdproblem().
static void alglib.testevdunit.cunset2d (ref complex a[,]) inline static private
References alglib.math.randomreal().
Referenced by alglib.testevdunit.testhevdbiproblem(), and alglib.testevdunit.testhevdproblem().
static void alglib.testevdunit.unset1d (ref double[] a) inline static private
References alglib.math.randomreal().
Referenced by alglib.testevdunit.testhevdbiproblem(), alglib.testevdunit.testhevdproblem(), alglib.testevdunit.testsevdbiproblem(), and alglib.testevdunit.testsevdproblem().
static void alglib.testevdunit.cunset1d (ref complex[] a) inline static private
References alglib.math.randomreal().
static double alglib.testevdunit.tdtestproduct (double[] d, double[] e, int n, double z[,], double[] lambdav) inline static private
Referenced by alglib.testevdunit.testtdevdproblem().
static double alglib.testevdunit.testproduct (double a[,], int n, double z[,], double[] lambdav) inline static private
Referenced by alglib.testevdunit.testsevdproblem().
static double alglib.testevdunit.testort (double z[,], int n) inline static private
Referenced by alglib.testevdunit.testsevdproblem(), and alglib.testevdunit.testtdevdproblem().
static double alglib.testevdunit.testcproduct (complex a[,], int n, complex z[,], double[] lambdav) inline static private
References alglib.math.abscomplex(), and alglib.math.conj().
Referenced by alglib.testevdunit.testhevdproblem().
static double alglib.testevdunit.testcort (complex z[,], int n) inline static private
References alglib.math.abscomplex(), and alglib.math.conj().
Referenced by alglib.testevdunit.testhevdproblem().
static void alglib.testevdunit.testsevdproblem (double a[,], double al[,], double au[,], int n, double threshold, ref bool serrors, ref int failc, ref int runs) inline static private
References alglib.evd.smatrixevd(), alglib.testevdunit.testort(), alglib.testevdunit.testproduct(), alglib.testevdunit.unset1d(), and alglib.testevdunit.unset2d().
Referenced by alglib.testevdunit.testevdset().
static void alglib.testevdunit.testhevdproblem (complex a[,], complex al[,], complex au[,], int n, double threshold, ref bool herrors, ref int failc, ref int runs) inline static private
References alglib.testevdunit.cunset2d(), alglib.evd.hmatrixevd(), alglib.testevdunit.testcort(), alglib.testevdunit.testcproduct(), and alglib.testevdunit.unset1d().
Referenced by alglib.testevdunit.testevdset().
static void alglib.testevdunit.testsevdbiproblem (double afull[,], double al[,], double au[,], int n, bool distvals, double threshold, ref bool serrors, ref int failc, ref int runs) inline static private
References alglib.math.randominteger(), alglib.evd.smatrixevd(), alglib.evd.smatrixevdi(), alglib.evd.smatrixevdr(), alglib.testevdunit.unset1d(), and alglib.testevdunit.unset2d().
Referenced by alglib.testevdunit.testevdset().
static void alglib.testevdunit.testhevdbiproblem (complex afull[,], complex al[,], complex au[,], int n, bool distvals, double threshold, ref bool herrors, ref int failc, ref int runs) inline static private
References alglib.math.abscomplex(), alglib.math.conj(), alglib.testevdunit.cunset2d(), alglib.evd.hmatrixevd(), alglib.evd.hmatrixevdi(), alglib.evd.hmatrixevdr(), alglib.math.randominteger(), and alglib.testevdunit.unset1d().
Referenced by alglib.testevdunit.testevdset().
static void alglib.testevdunit.testtdevdproblem (double[] d, double[] e, int n, double threshold, ref bool tderrors, ref int failc, ref int runs) inline static private
References alglib.math.randomreal(), alglib.evd.smatrixtdevd(), alglib.testevdunit.tdtestproduct(), and alglib.testevdunit.testort().
Referenced by alglib.testevdunit.testevdset().
static void alglib.testevdunit.testtdevdbiproblem (double[] d, double[] e, int n, bool distvals, double threshold, ref bool serrors, ref int failc, ref int runs) inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.evd.smatrixtdevd(), alglib.evd.smatrixtdevdi(), and alglib.evd.smatrixtdevdr().
Referenced by alglib.testevdunit.testevdset().
static void alglib.testevdunit.testnsevdproblem (double a[,], int n, double threshold, ref bool nserrors, ref int failc, ref int runs) inline static private
References alglib.evd.rmatrixevd().
Referenced by alglib.testevdunit.testevdset().
static void alglib.testevdunit.testevdset (int n, double threshold, double bithreshold, ref int failc, ref int runs, ref bool nserrors, ref bool serrors, ref bool herrors, ref bool tderrors, ref bool sbierrors, ref bool hbierrors, ref bool tdbierrors) inline static private
References alglib.testevdunit.cmatrixfillsparsea(), alglib.testevdunit.cmatrixhermitiansplit(), alglib.math.conj(), alglib.math.randomreal(), alglib.testevdunit.rmatrixfillsparsea(), alglib.testevdunit.rmatrixsymmetricsplit(), alglib.testevdunit.testhevdbiproblem(), alglib.testevdunit.testhevdproblem(), alglib.testevdunit.testnsevdproblem(), alglib.testevdunit.testsevdbiproblem(), alglib.testevdunit.testsevdproblem(), alglib.testevdunit.testtdevdbiproblem(), alglib.testevdunit.testtdevdproblem(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testevdunit.testevd().
static bool alglib.testevdunit.testevd (bool silent) inline static
References alglib.ablas.ablasblocksize(), alglib.math.machineepsilon, and alglib.testevdunit.testevdset().
static bool alglib.testevdunit._pexec_testevd (bool silent) inline static
References alglib.testevdunit.testevd().
Referenced by _Test.Main().
static void alglib.testevdunit.rmatrixfillsparsea (ref double a[,], int m, int n, double sparcity) inline static private
References alglib.math.randomreal().
static void alglib.testevdunit.cmatrixfillsparsea (ref complex a[,], int m, int n, double sparcity) inline static private
References alglib.math.randomreal().
static void alglib.testevdunit.rmatrixsymmetricsplit (double a[,], int n, ref double al[,], ref double au[,]) inline static private
References alglib.math.randomreal().
static void alglib.testevdunit.cmatrixhermitiansplit (complex a[,], int n, ref complex al[,], ref complex au[,]) inline static private
References alglib.math.conj(), and alglib.math.randomreal().
static void alglib.testevdunit.unset2d (ref double a[,]) inline static private
References alglib.math.randomreal().
static void alglib.testevdunit.cunset2d (ref complex a[,]) inline static private
References alglib.math.randomreal().
static void alglib.testevdunit.unset1d (ref double[] a) inline static private
References alglib.math.randomreal().
static void alglib.testevdunit.cunset1d (ref complex[] a) inline static private
References alglib.math.randomreal().
static double alglib.testevdunit.tdtestproduct (double[] d, double[] e, int n, double z[,], double[] lambdav) inline static private
static double alglib.testevdunit.testproduct (double a[,], int n, double z[,], double[] lambdav) inline static private
static double alglib.testevdunit.testort (double z[,], int n) inline static private
static double alglib.testevdunit.testcproduct (complex a[,], int n, complex z[,], double[] lambdav) inline static private
References alglib.math.abscomplex(), and alglib.math.conj().
static double alglib.testevdunit.testcort (complex z[,], int n) inline static private
References alglib.math.abscomplex(), and alglib.math.conj().
static void alglib.testevdunit.testsevdproblem (double a[,], double al[,], double au[,], int n, double threshold, ref bool serrors, ref int failc, ref int runs) inline static private
References alglib.evd.smatrixevd(), alglib.testevdunit.testort(), alglib.testevdunit.testproduct(), alglib.testevdunit.unset1d(), and alglib.testevdunit.unset2d().
static void alglib.testevdunit.testhevdproblem (complex a[,], complex al[,], complex au[,], int n, double threshold, ref bool herrors, ref int failc, ref int runs) inline static private
References alglib.testevdunit.cunset2d(), alglib.evd.hmatrixevd(), alglib.testevdunit.testcort(), alglib.testevdunit.testcproduct(), and alglib.testevdunit.unset1d().
static void alglib.testevdunit.testsevdbiproblem (double afull[,], double al[,], double au[,], int n, bool distvals, double threshold, ref bool serrors, ref int failc, ref int runs) inline static private
References alglib.math.randominteger(), alglib.evd.smatrixevd(), alglib.evd.smatrixevdi(), alglib.evd.smatrixevdr(), alglib.testevdunit.unset1d(), and alglib.testevdunit.unset2d().
static void alglib.testevdunit.testhevdbiproblem (complex afull[,], complex al[,], complex au[,], int n, bool distvals, double threshold, ref bool herrors, ref int failc, ref int runs) inline static private
References alglib.math.abscomplex(), alglib.math.conj(), alglib.testevdunit.cunset2d(), alglib.evd.hmatrixevd(), alglib.evd.hmatrixevdi(), alglib.evd.hmatrixevdr(), alglib.math.randominteger(), and alglib.testevdunit.unset1d().
static void alglib.testevdunit.testtdevdproblem (double[] d, double[] e, int n, double threshold, ref bool tderrors, ref int failc, ref int runs) inline static private
References alglib.math.randomreal(), alglib.evd.smatrixtdevd(), alglib.testevdunit.tdtestproduct(), and alglib.testevdunit.testort().
static void alglib.testevdunit.testtdevdbiproblem (double[] d, double[] e, int n, bool distvals, double threshold, ref bool serrors, ref int failc, ref int runs) inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.evd.smatrixtdevd(), alglib.evd.smatrixtdevdi(), and alglib.evd.smatrixtdevdr().
static void alglib.testevdunit.testnsevdproblem (double a[,], int n, double threshold, ref bool nserrors, ref int failc, ref int runs) inline static private
References alglib.evd.rmatrixevd().
static void alglib.testevdunit.testevdset (int n, double threshold, double bithreshold, ref int failc, ref int runs, ref bool nserrors, ref bool serrors, ref bool herrors, ref bool tderrors, ref bool sbierrors, ref bool hbierrors, ref bool tdbierrors) inline static private
References alglib.testevdunit.cmatrixfillsparsea(), alglib.testevdunit.cmatrixhermitiansplit(), alglib.math.conj(), alglib.math.randomreal(), alglib.testevdunit.rmatrixfillsparsea(), alglib.testevdunit.rmatrixsymmetricsplit(), alglib.testevdunit.testhevdbiproblem(), alglib.testevdunit.testhevdproblem(), alglib.testevdunit.testnsevdproblem(), alglib.testevdunit.testsevdbiproblem(), alglib.testevdunit.testsevdproblem(), alglib.testevdunit.testtdevdbiproblem(), alglib.testevdunit.testtdevdproblem(), alglib.complex.x, and alglib.complex.y.
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs