IGLib: IPLab.ImageDoc Class Reference
IPLab.ImageDoc Class Reference
Summary description for ImageDoc.
Public Member Functions
delegate void SelectionEventHandler (object sender, SelectionEventArgs e)
ImageDoc (string fileName, IDocumentsHost host)
ImageDoc (Bitmap image, IDocumentsHost host)
void ExecuteCommand (ImageDocCommands cmd)
void Reload ()
void Center ()
void mouseWheelMoved (object sender, MouseEventArgs e)
Protected Member Functions
override void OnPaint (PaintEventArgs e)
override void OnClick (EventArgs e)
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
Bitmap Image [get]
int ImageWidth [get]
int ImageHeight [get]
float Zoom [get]
string FileName [get]
Events
EventHandler DocumentChanged
EventHandler ZoomChanged
SelectionEventHandler MouseImagePosition
SelectionEventHandler SelectionChanged
Private Member Functions
ImageDoc (IDocumentsHost host)
void Init ()
Bitmap LoadImageFromFile (string fileName)
void UpdateNewImage ()
void UpdateSize ()
bool CheckIfColor (string filterName)
bool CheckIfGrayscale (string filterName)
bool CheckIfBinary (string filterName)
void ApplyFilter (IFilter filter)
void imageItem_Popup (object sender, System.EventArgs e)
void backImageItem_Click (object sender, System.EventArgs e)
void Clone ()
void cloneImageItem_Click (object sender, System.EventArgs e)
void UpdateZoom ()
void zoomItem_Click (object sender, System.EventArgs e)
void ZoomIn ()
void zoomInImageItem_Click (object sender, System.EventArgs e)
void ZoomOut ()
void zoomOutImageItem_Click (object sender, System.EventArgs e)
void FitToScreen ()
void zoomFitImageItem_Click (object sender, System.EventArgs e)
void flipImageItem_Click (object sender, System.EventArgs e)
void mirrorItem_Click (object sender, System.EventArgs e)
void rotateImageItem_Click (object sender, System.EventArgs e)
void invertColorFiltersItem_Click (object sender, System.EventArgs e)
void rotateColorFiltersItem_Click (object sender, System.EventArgs e)
void sepiaColorFiltersItem_Click (object sender, System.EventArgs e)
void bayerFiltersItem_Click (object sender, EventArgs e)
void Grayscale ()
void grayscaleColorFiltersItem_Click (object sender, System.EventArgs e)
void toRgbColorFiltersItem_Click (object sender, System.EventArgs e)
void redColorFiltersItem_Click (object sender, System.EventArgs e)
void greenColorFiltersItem_Click (object sender, System.EventArgs e)
void blueColorFiltersItem_Click (object sender, System.EventArgs e)
void cyanColorFiltersItem_Click (object sender, System.EventArgs e)
void magentaColorFiltersItem_Click (object sender, System.EventArgs e)
void yellowColorFiltersItem_Click (object sender, System.EventArgs e)
void colorFilteringColorFiltersItem_Click (object sender, System.EventArgs e)
void euclideanFilteringColorFiltersItem_Click (object sender, System.EventArgs e)
void channelsFilteringColorFiltersItem_Click (object sender, System.EventArgs e)
void extractRedColorFiltersItem_Click (object sender, System.EventArgs e)
void extractGreenColorFiltersItem_Click (object sender, System.EventArgs e)
void extractRedBlueFiltersItem_Click (object sender, System.EventArgs e)
void replaceRedColorFiltersItem_Click (object sender, System.EventArgs e)
void replaceGreenColorFiltersItem_Click (object sender, System.EventArgs e)
void replaceBlueColorFiltersItem_Click (object sender, System.EventArgs e)
void extractRedFromNrgbMenuItem_Click (object sender, EventArgs e)
void extractGreenFromNrgbMenuItem_Click (object sender, EventArgs e)
void extractBlueFromNrgbMenuItem_Click (object sender, EventArgs e)
void Brightness ()
void brightnessHslFiltersItem_Click (object sender, System.EventArgs e)
void Contrast ()
void contrastHslFiltersItem_Click (object sender, System.EventArgs e)
void Saturation ()
void saturationHslFiltersItem_Click (object sender, System.EventArgs e)
void linearHslFiltersItem_Click (object sender, System.EventArgs e)
void filteringHslFiltersItem_Click (object sender, System.EventArgs e)
void hueHslFiltersItem_Click (object sender, System.EventArgs e)
void linearYCbCrFiltersItem_Click (object sender, System.EventArgs e)
void filteringYCbCrFiltersItem_Click (object sender, System.EventArgs e)
void extracYFiltersItem_Click (object sender, System.EventArgs e)
void extracCbFiltersItem_Click (object sender, System.EventArgs e)
void extracCrFiltersItem_Click (object sender, System.EventArgs e)
void replaceYFiltersItem_Click (object sender, System.EventArgs e)
void replaceCbFiltersItem_Click (object sender, System.EventArgs e)
void replaceCrFiltersItem_Click (object sender, System.EventArgs e)
void Threshold ()
void thresholdBinaryFiltersItem_Click (object sender, System.EventArgs e)
void thresholdCarryBinaryFiltersItem_Click (object sender, System.EventArgs e)
void orderedDitherBinaryFiltersItem_Click (object sender, System.EventArgs e)
void bayerDitherBinaryFiltersItem_Click (object sender, System.EventArgs e)
void floydBinaryFiltersItem_Click (object sender, System.EventArgs e)
void burkesBinaryFiltersItem_Click (object sender, System.EventArgs e)
void stuckiBinaryFiltersItem_Click (object sender, System.EventArgs e)
void jarvisBinaryFiltersItem_Click (object sender, System.EventArgs e)
void sierraBinaryFiltersItem_Click (object sender, System.EventArgs e)
void sisThresholdBinaryFiltersItem_Click (object sender, System.EventArgs e)
void otsuThresholdMenuItem_Click (object sender, EventArgs e)
void bradleyLocalThresholdingMenuItem_Click (object sender, EventArgs e)
void erosionMorphologyFiltersItem_Click (object sender, System.EventArgs e)
void dilatationMorphologyFiltersItem_Click (object sender, System.EventArgs e)
void openingMorphologyFiltersItem_Click (object sender, System.EventArgs e)
void closingMorphologyFiltersItem_Click (object sender, System.EventArgs e)
void tophatMorphologyFiltersItem_Click (object sender, EventArgs e)
void bottomMorphologyFiltersItem_Click (object sender, EventArgs e)
void Morphology ()
void customMorphologyFiltersItem_Click (object sender, System.EventArgs e)
void hitAndMissFiltersItem_Click (object sender, System.EventArgs e)
void meanConvolutionFiltersItem_Click (object sender, System.EventArgs e)
void blurConvolutionFiltersItem_Click (object sender, System.EventArgs e)
void gaussianConvolutionFiltersItem_Click (object sender, System.EventArgs e)
void sharpenExConvolutionFiltersItem_Click (object sender, System.EventArgs e)
void sharpenConvolutionFiltersItem_Click (object sender, System.EventArgs e)
void edgesConvolutionFiltersItem_Click (object sender, System.EventArgs e)
void Convolution ()
void customConvolutionFiltersItem_Click (object sender, System.EventArgs e)
void mergeTwosrcFiltersItem_Click (object sender, System.EventArgs e)
void intersectTwosrcFiltersItem_Click (object sender, System.EventArgs e)
void addTwosrcFiltersItem_Click (object sender, System.EventArgs e)
void subtractTwosrcFiltersItem_Click (object sender, System.EventArgs e)
void differenceTwosrcFiltersItem_Click (object sender, System.EventArgs e)
void moveTowardsTwosrcFiltersItem_Click (object sender, System.EventArgs e)
void morphTwosrcFiltersItem_Click (object sender, System.EventArgs e)
void maskFilterMenuItem_Click (object sender, EventArgs e)
void homogenityEdgeFiltersItem_Click (object sender, System.EventArgs e)
void differenceEdgeFiltersItem_Click (object sender, System.EventArgs e)
void sobelEdgeFiltersItem_Click (object sender, System.EventArgs e)
void cannyEdgeFiltersItem_Click (object sender, System.EventArgs e)
void susanCornersDetectorMenuItem_Click (object sender, EventArgs e)
void moravecCornersDetectorMenuItem_Click (object sender, EventArgs e)
void additiveNoiseFiltersItem_Click (object sender, EventArgs e)
void saltNoiseFiltersItem_Click (object sender, EventArgs e)
void adaptiveSmoothingFiltersItem_Click (object sender, System.EventArgs e)
void conservativeSmoothingFiltersItem_Click (object sender, System.EventArgs e)
void bilateralSmoothingFiltersItem_Click (object sender, EventArgs e)
void perlinNoiseFiltersItem_Click (object sender, System.EventArgs e)
void oilPaintingFiltersItem_Click (object sender, System.EventArgs e)
void jitterFiltersItem_Click (object sender, System.EventArgs e)
void pixellateFiltersItem_Click (object sender, System.EventArgs e)
void rombozoidMenuItem_Click (object sender, EventArgs e)
void waterWaveMenuItem_Click (object sender, EventArgs e)
void simpleSkeletonizationFiltersItem_Click (object sender, System.EventArgs e)
void shrinkFiltersItem_Click (object sender, System.EventArgs e)
void simplePosterizatonMenuItem_Click (object sender, EventArgs e)
void labelingFiltersItem_Click (object sender, System.EventArgs e)
void blobExtractorFiltersItem_Click (object sender, System.EventArgs e)
void fillHolesMenuItem_Click (object sender, EventArgs e)
void filterBlobsMenuItem_Click (object sender, EventArgs e)
void extractBiggestBlobMenuItem_Click (object sender, EventArgs e)
void quadrilateralFinderMenuItem_Click (object sender, EventArgs e)
void quadrilateralTransformationMenuItem_Click (object sender, EventArgs e)
void ResizeImage ()
void resizeFiltersItem_Click (object sender, System.EventArgs e)
void RotateImage ()
void rotateFiltersItem_Click (object sender, System.EventArgs e)
void Levels ()
void levelsFiltersItem_Click (object sender, System.EventArgs e)
void contrastStretchMenuItem_Click (object sender, EventArgs e)
void histogramEqualizationMenuItem_Click (object sender, EventArgs e)
void medianFiltersItem_Click (object sender, System.EventArgs e)
void gammaFiltersItem_Click (object sender, System.EventArgs e)
void CreateStereoAnaglyph (StereoAnaglyph.Algorithm algorithm)
void trueAnaglyphMenuItem_Click (object sender, EventArgs e)
void grayAnaglyphMenuItem_Click (object sender, EventArgs e)
void colorAnaglyphMenuItem_Click (object sender, EventArgs e)
void halfColorAnaglyphMenuItem_Click (object sender, EventArgs e)
void optimizedAnaglyphMenuItem_Click (object sender, EventArgs e)
void documentAligningMenuItem_Click (object sender, EventArgs e)
void transformToPolarMenuItem_Click (object sender, EventArgs e)
void transformFromPolarMenuItem_Click (object sender, EventArgs e)
void runLengthSmoothingMenuItem_Click (object sender, EventArgs e)
void ForwardFourierTransformation ()
void fourierFiltersItem_Click (object sender, System.EventArgs e)
void GetImageAndScreenPoints (Point point, out Point imgPoint, out Point screenPoint)
void NormalizePoints (ref Point pt1, ref Point pt2)
void DrawSelectionFrame (Graphics g)
void Crop ()
void cropImageItem_Click (object sender, System.EventArgs e)
void ImageDoc_MouseDown (object sender, System.Windows.Forms.MouseEventArgs e)
void ImageDoc_MouseUp (object sender, System.Windows.Forms.MouseEventArgs e)
void ImageDoc_MouseMove (object sender, System.Windows.Forms.MouseEventArgs e)
void ImageDoc_MouseLeave (object sender, System.EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Bitmap backup = null
Bitmap image = null
string fileName = null
int width
int height
float zoom = 1
IDocumentsHost host = null
bool cropping = false
bool dragging = false
Point start
Point end
Point startW
Point endW
System.Windows.Forms.MainMenu mainMenu
System.Windows.Forms.MenuItem imageItem
System.Windows.Forms.MenuItem filtersItem
System.Windows.Forms.MenuItem cloneImageItem
System.Windows.Forms.MenuItem rotateColorFiltersItem
System.Windows.Forms.MenuItem invertColorFiltersItem
System.Windows.Forms.MenuItem sepiaColorFiltersItem
System.Windows.Forms.MenuItem grayscaleColorFiltersItem
System.Windows.Forms.MenuItem menuItem1
System.Windows.Forms.MenuItem menuItem2
System.Windows.Forms.MenuItem backImageItem
System.Windows.Forms.MenuItem menuItem4
System.Windows.Forms.MenuItem menuItem5
System.Windows.Forms.MenuItem menuItem6
System.Windows.Forms.MenuItem menuItem7
System.Windows.Forms.MenuItem z10ImageItem
System.Windows.Forms.MenuItem z25ImageItem
System.Windows.Forms.MenuItem z50ImageItem
System.Windows.Forms.MenuItem z75ImageItem
System.Windows.Forms.MenuItem z100ImageItem
System.Windows.Forms.MenuItem z150ImageItem
System.Windows.Forms.MenuItem z200ImageItem
System.Windows.Forms.MenuItem z400ImageItem
System.Windows.Forms.MenuItem z500ImageItem
System.Windows.Forms.MenuItem menuItem8
System.Windows.Forms.MenuItem zoomInImageItem
System.Windows.Forms.MenuItem zoomOutImageItem
System.Windows.Forms.MenuItem menuItem11
System.Windows.Forms.MenuItem zoomFitImageItem
System.Windows.Forms.MenuItem colorFiltersItem
System.Windows.Forms.MenuItem binaryFiltersItem
System.Windows.Forms.MenuItem thresholdBinaryFiltersItem
System.Windows.Forms.MenuItem thresholdCarryBinaryFiltersItem
System.Windows.Forms.MenuItem floydBinaryFiltersItem
System.Windows.Forms.MenuItem morphologyFiltersItem
System.Windows.Forms.MenuItem dilatationMorphologyFiltersItem
System.Windows.Forms.MenuItem convolutionFiltersItem
System.Windows.Forms.MenuItem meanConvolutionFiltersItem
System.Windows.Forms.MenuItem blurConvolutionFiltersItem
System.Windows.Forms.MenuItem sharpenConvolutionFiltersItem
System.Windows.Forms.MenuItem edgesConvolutionFiltersItem
System.Windows.Forms.MenuItem levelsFiltersItem
System.Windows.Forms.MenuItem flipImageItem
System.Windows.Forms.MenuItem mirrorItem
System.Windows.Forms.MenuItem rotateImageItem
System.Windows.Forms.MenuItem menuItem10
System.Windows.Forms.MenuItem cropImageItem
System.Windows.Forms.MenuItem menuItem3
System.Windows.Forms.MenuItem menuItem9
System.Windows.Forms.MenuItem customMorphologyFiltersItem
System.Windows.Forms.MenuItem menuItem12
System.Windows.Forms.MenuItem customConvolutionFiltersItem
System.Windows.Forms.MenuItem openingMorphologyFiltersItem
System.Windows.Forms.MenuItem medianFiltersItem
System.Windows.Forms.MenuItem closingMorphologyFiltersItem
System.Windows.Forms.MenuItem erosionMorphologyFiltersItem
System.Windows.Forms.MenuItem pixellateFiltersItem
System.Windows.Forms.MenuItem menuItem15
System.Windows.Forms.MenuItem menuItem16
System.Windows.Forms.MenuItem redColorFiltersItem
System.Windows.Forms.MenuItem greenColorFiltersItem
System.Windows.Forms.MenuItem blueColorFiltersItem
System.Windows.Forms.MenuItem menuItem17
System.Windows.Forms.MenuItem cyanColorFiltersItem
System.Windows.Forms.MenuItem magentaColorFiltersItem
System.Windows.Forms.MenuItem yellowColorFiltersItem
System.Windows.Forms.MenuItem channelsFilteringColorFiltersItem
System.Windows.Forms.MenuItem menuItem19
System.Windows.Forms.MenuItem colorFilteringColorFiltersItem
System.Windows.Forms.MenuItem euclideanFilteringColorFiltersItem
System.Windows.Forms.MenuItem extractRedColorFiltersItem
System.Windows.Forms.MenuItem extractGreenColorFiltersItem
System.Windows.Forms.MenuItem extractRedBlueFiltersItem
System.Windows.Forms.MenuItem menuItem18
System.Windows.Forms.MenuItem replaceRedColorFiltersItem
System.Windows.Forms.MenuItem menuItem20
System.Windows.Forms.MenuItem replaceGreenColorFiltersItem
System.Windows.Forms.MenuItem replaceBlueColorFiltersItem
System.Windows.Forms.MenuItem twosrcFiltersItem
System.Windows.Forms.MenuItem mergeTwosrcFiltersItem
System.Windows.Forms.MenuItem intersectTwosrcFiltersItem
System.Windows.Forms.MenuItem menuItem21
System.Windows.Forms.MenuItem addTwosrcFiltersItem
System.Windows.Forms.MenuItem subtractTwosrcFiltersItem
System.Windows.Forms.MenuItem menuItem22
System.Windows.Forms.MenuItem differenceTwosrcFiltersItem
System.Windows.Forms.MenuItem moveTowardsTwosrcFiltersItem
System.Windows.Forms.MenuItem simpleSkeletonizationFiltersItem
System.Windows.Forms.MenuItem menuItem24
System.Windows.Forms.MenuItem orderedDitherBinaryFiltersItem
System.Windows.Forms.MenuItem menuItem14
System.Windows.Forms.MenuItem bayerDitherBinaryFiltersItem
System.Windows.Forms.MenuItem burkesBinaryFiltersItem
System.Windows.Forms.MenuItem stuckiBinaryFiltersItem
System.Windows.Forms.MenuItem jarvisBinaryFiltersItem
System.Windows.Forms.MenuItem sierraBinaryFiltersItem
System.Windows.Forms.MenuItem menuItem23
System.Windows.Forms.MenuItem resizeFiltersItem
System.Windows.Forms.MenuItem menuItem26
System.Windows.Forms.MenuItem shrinkFiltersItem
System.Windows.Forms.MenuItem rotateFiltersItem
System.Windows.Forms.MenuItem jitterFiltersItem
System.Windows.Forms.MenuItem gammaFiltersItem
System.Windows.Forms.MenuItem menuItem27
System.Windows.Forms.MenuItem hitAndMissFiltersItem
System.Windows.Forms.MenuItem hslFiltersItem
System.Windows.Forms.MenuItem brightnessHslFiltersItem
System.Windows.Forms.MenuItem contrastHslFiltersItem
System.Windows.Forms.MenuItem saturationHslFiltersItem
System.Windows.Forms.MenuItem menuItem28
System.Windows.Forms.MenuItem filteringHslFiltersItem
System.Windows.Forms.MenuItem hueHslFiltersItem
System.Windows.Forms.MenuItem menuItem29
System.Windows.Forms.MenuItem linearHslFiltersItem
System.Windows.Forms.MenuItem menuItem25
System.Windows.Forms.MenuItem fourierFiltersItem
System.Windows.Forms.MenuItem edgeFiltersItem
System.Windows.Forms.MenuItem homogenityEdgeFiltersItem
System.Windows.Forms.MenuItem differenceEdgeFiltersItem
System.Windows.Forms.MenuItem labelingFiltersItem
System.Windows.Forms.MenuItem sobelEdgeFiltersItem
System.Windows.Forms.MenuItem gaussianConvolutionFiltersItem
System.Windows.Forms.MenuItem adaptiveSmoothingFiltersItem
System.Windows.Forms.MenuItem blobExtractorFiltersItem
System.Windows.Forms.MenuItem menuItem31
System.Windows.Forms.MenuItem sisThresholdBinaryFiltersItem
System.Windows.Forms.MenuItem conservativeSmoothingFiltersItem
System.Windows.Forms.MenuItem menuItem34
System.Windows.Forms.MenuItem cannyEdgeFiltersItem
System.Windows.Forms.MenuItem menuItem33
System.Windows.Forms.MenuItem sharpenExConvolutionFiltersItem
System.Windows.Forms.MenuItem oilPaintingFiltersItem
System.Windows.Forms.MenuItem ycbcrFiltersItem
System.Windows.Forms.MenuItem extracYFiltersItem
System.Windows.Forms.MenuItem extracCbFiltersItem
System.Windows.Forms.MenuItem extracCrFiltersItem
System.Windows.Forms.MenuItem menuItem37
System.Windows.Forms.MenuItem menuItem38
System.Windows.Forms.MenuItem replaceYFiltersItem
System.Windows.Forms.MenuItem replaceCbFiltersItem
System.Windows.Forms.MenuItem replaceCrFiltersItem
System.Windows.Forms.MenuItem linearYCbCrFiltersItem
System.Windows.Forms.MenuItem filteringYCbCrFiltersItem
System.Windows.Forms.MenuItem toRgbColorFiltersItem
System.Windows.Forms.MenuItem perlinNoiseFiltersItem
System.Windows.Forms.MenuItem morphTwosrcFiltersItem
System.Windows.Forms.MenuItem tophatMorphologyFiltersItem
System.Windows.Forms.MenuItem bottomMorphologyFiltersItem
System.Windows.Forms.MenuItem noiseFiltersItem
System.Windows.Forms.MenuItem additiveNoiseFiltersItem
System.Windows.Forms.MenuItem saltNoiseFiltersItem
System.Windows.Forms.MenuItem menuItem13
System.Windows.Forms.MenuItem extractBiggestBlobMenuItem
System.Windows.Forms.MenuItem menuItem30
System.Windows.Forms.MenuItem contrastStretchMenuItem
System.Windows.Forms.MenuItem histogramEqualizationMenuItem
System.Windows.Forms.MenuItem menuItem32
System.Windows.Forms.MenuItem extractRedFromNrgbMenuItem
System.Windows.Forms.MenuItem extractGreenFromNrgbMenuItem
System.Windows.Forms.MenuItem extractBlueFromNrgbMenuItem
System.Windows.Forms.MenuItem otsuThresholdMenuItem
System.Windows.Forms.MenuItem filterBlobsMenuItem
System.Windows.Forms.MenuItem menuItem35
System.Windows.Forms.MenuItem susanCornersDetectorMenuItem
System.Windows.Forms.MenuItem moravecCornersDetectorMenuItem
System.Windows.Forms.MenuItem simplePosterizatonMenuItem
System.ComponentModel.IContainer components
System.Windows.Forms.MenuItem menuItem36
System.Windows.Forms.MenuItem menuItem39
System.Windows.Forms.MenuItem trueAnaglyphMenuItem
System.Windows.Forms.MenuItem grayAnaglyphMenuItem
System.Windows.Forms.MenuItem colorAnaglyphMenuItem
System.Windows.Forms.MenuItem halfColorAnaglyphMenuItem
System.Windows.Forms.MenuItem optimizedAnaglyphMenuItem
System.Windows.Forms.MenuItem menuItem40
System.Windows.Forms.MenuItem quadrilateralFinderMenuItem
System.Windows.Forms.MenuItem quadrilateralTransformationMenuItem
System.Windows.Forms.MenuItem documentAligningMenuItem
System.Windows.Forms.MenuItem differentEffectsFiltersItem
System.Windows.Forms.MenuItem rombozoidMenuItem
System.Windows.Forms.MenuItem waterWaveMenuItem
System.Windows.Forms.MenuItem bradleyLocalThresholdingMenuItem
System.Windows.Forms.MenuItem fillHolesMenuItem
System.Windows.Forms.MenuItem bilateralSmoothingFiltersItem
System.Windows.Forms.MenuItem bayerFiltersItem
System.Windows.Forms.MenuItem menuItem41
System.Windows.Forms.MenuItem transformToPolarMenuItem
System.Windows.Forms.MenuItem transformFromPolarMenuItem
System.Windows.Forms.MenuItem menuItem42
System.Windows.Forms.MenuItem runLengthSmoothingMenuItem
System.Windows.Forms.MenuItem maskFilterMenuItem
Detailed Description
Summary description for ImageDoc.
Constructor & Destructor Documentation
IPLab.ImageDoc.ImageDoc (IDocumentsHost host) inline private
References IPLab.ImageDoc.host.
IPLab.ImageDoc.ImageDoc (string fileName, IDocumentsHost host) inline
References IPLab.ImageDoc.fileName, IPLab.ImageDoc.Init(), and IPLab.ImageDoc.LoadImageFromFile().
IPLab.ImageDoc.ImageDoc (Bitmap image, IDocumentsHost host) inline
References IPLab.ImageDoc.image, and IPLab.ImageDoc.Init().
Member Function Documentation
delegate void IPLab.ImageDoc.SelectionEventHandler (object sender, SelectionEventArgs e)
Referenced by IPLab.MainForm.SetupDocumentEvents().
void IPLab.ImageDoc.Init () inline private
References IPLab.ImageDoc.InitializeComponent(), IPLab.ImageDoc.mouseWheelMoved(), and IPLab.ImageDoc.UpdateSize().
Referenced by IPLab.ImageDoc.ImageDoc().
Bitmap IPLab.ImageDoc.LoadImageFromFile (string fileName) inline private
Referenced by IPLab.ImageDoc.ImageDoc(), and IPLab.ImageDoc.Reload().
void IPLab.ImageDoc.ExecuteCommand (ImageDocCommands cmd) inline
References IPLab.ImageDoc.Brightness(), IPLab.ImageDoc.Clone(), IPLab.ImageDoc.Contrast(), IPLab.ImageDoc.Convolution(), IPLab.ImageDoc.Crop(), IPLab.ImageDoc.FitToScreen(), IPLab.ImageDoc.ForwardFourierTransformation(), IPLab.ImageDoc.Grayscale(), IPLab.ImageDoc.Levels(), IPLab.ImageDoc.Morphology(), IPLab.ImageDoc.ResizeImage(), IPLab.ImageDoc.RotateImage(), IPLab.ImageDoc.Saturation(), IPLab.ImageDoc.Threshold(), IPLab.ImageDoc.UpdateZoom(), IPLab.ImageDoc.ZoomIn(), and IPLab.ImageDoc.ZoomOut().
void IPLab.ImageDoc.UpdateNewImage () inline private
References IPLab.ImageDoc.DocumentChanged, and IPLab.ImageDoc.UpdateSize().
Referenced by IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.backImageItem_Click(), IPLab.ImageDoc.quadrilateralFinderMenuItem_Click(), IPLab.ImageDoc.Reload(), and IPLab.ImageDoc.rotateImageItem_Click().
void IPLab.ImageDoc.Reload () inline
References IPLab.ImageDoc.LoadImageFromFile(), and IPLab.ImageDoc.UpdateNewImage().
void IPLab.ImageDoc.Center () inline
void IPLab.ImageDoc.UpdateSize () inline private
Referenced by IPLab.ImageDoc.Init(), and IPLab.ImageDoc.UpdateNewImage().
bool IPLab.ImageDoc.CheckIfColor (string filterName) inline private
Referenced by IPLab.ImageDoc.Brightness(), IPLab.ImageDoc.channelsFilteringColorFiltersItem_Click(), IPLab.ImageDoc.colorFilteringColorFiltersItem_Click(), IPLab.ImageDoc.Contrast(), IPLab.ImageDoc.euclideanFilteringColorFiltersItem_Click(), IPLab.ImageDoc.filteringHslFiltersItem_Click(), IPLab.ImageDoc.filteringYCbCrFiltersItem_Click(), IPLab.ImageDoc.hueHslFiltersItem_Click(), IPLab.ImageDoc.linearHslFiltersItem_Click(), IPLab.ImageDoc.linearYCbCrFiltersItem_Click(), and IPLab.ImageDoc.Saturation().
bool IPLab.ImageDoc.CheckIfGrayscale (string filterName) inline private
Referenced by IPLab.ImageDoc.bayerFiltersItem_Click(), IPLab.ImageDoc.ForwardFourierTransformation(), and IPLab.ImageDoc.Threshold().
bool IPLab.ImageDoc.CheckIfBinary (string filterName) inline private
Referenced by IPLab.ImageDoc.fillHolesMenuItem_Click(), IPLab.ImageDoc.hitAndMissFiltersItem_Click(), and IPLab.ImageDoc.runLengthSmoothingMenuItem_Click().
override void IPLab.ImageDoc.OnPaint (PaintEventArgs e) inline protected
References IPLab.ImageDoc.height, and IPLab.ImageDoc.width.
override void IPLab.ImageDoc.OnClick (EventArgs e) inline protected
void IPLab.ImageDoc.ApplyFilter (IFilter filter) inline private
References IPLab.IDocumentsHost.CreateNewDocumentOnChange, IPLab.ImageDoc.image, IPLab.IDocumentsHost.NewDocument(), IPLab.IDocumentsHost.RememberOnChange, and IPLab.ImageDoc.UpdateNewImage().
Referenced by IPLab.ImageDoc.adaptiveSmoothingFiltersItem_Click(), IPLab.ImageDoc.additiveNoiseFiltersItem_Click(), IPLab.ImageDoc.addTwosrcFiltersItem_Click(), IPLab.ImageDoc.bayerDitherBinaryFiltersItem_Click(), IPLab.ImageDoc.bayerFiltersItem_Click(), IPLab.ImageDoc.bilateralSmoothingFiltersItem_Click(), IPLab.ImageDoc.blueColorFiltersItem_Click(), IPLab.ImageDoc.blurConvolutionFiltersItem_Click(), IPLab.ImageDoc.bottomMorphologyFiltersItem_Click(), IPLab.ImageDoc.bradleyLocalThresholdingMenuItem_Click(), IPLab.ImageDoc.Brightness(), IPLab.ImageDoc.burkesBinaryFiltersItem_Click(), IPLab.ImageDoc.cannyEdgeFiltersItem_Click(), IPLab.ImageDoc.channelsFilteringColorFiltersItem_Click(), IPLab.ImageDoc.closingMorphologyFiltersItem_Click(), IPLab.ImageDoc.colorFilteringColorFiltersItem_Click(), IPLab.ImageDoc.conservativeSmoothingFiltersItem_Click(), IPLab.ImageDoc.Contrast(), IPLab.ImageDoc.contrastStretchMenuItem_Click(), IPLab.ImageDoc.Convolution(), IPLab.ImageDoc.CreateStereoAnaglyph(), IPLab.ImageDoc.cyanColorFiltersItem_Click(), IPLab.ImageDoc.differenceEdgeFiltersItem_Click(), IPLab.ImageDoc.differenceTwosrcFiltersItem_Click(), IPLab.ImageDoc.dilatationMorphologyFiltersItem_Click(), IPLab.ImageDoc.documentAligningMenuItem_Click(), IPLab.ImageDoc.edgesConvolutionFiltersItem_Click(), IPLab.ImageDoc.erosionMorphologyFiltersItem_Click(), IPLab.ImageDoc.euclideanFilteringColorFiltersItem_Click(), IPLab.ImageDoc.extracCbFiltersItem_Click(), IPLab.ImageDoc.extracCrFiltersItem_Click(), IPLab.ImageDoc.extractBiggestBlobMenuItem_Click(), IPLab.ImageDoc.extractBlueFromNrgbMenuItem_Click(), IPLab.ImageDoc.extractGreenColorFiltersItem_Click(), IPLab.ImageDoc.extractGreenFromNrgbMenuItem_Click(), IPLab.ImageDoc.extractRedBlueFiltersItem_Click(), IPLab.ImageDoc.extractRedColorFiltersItem_Click(), IPLab.ImageDoc.extractRedFromNrgbMenuItem_Click(), IPLab.ImageDoc.extracYFiltersItem_Click(), IPLab.ImageDoc.fillHolesMenuItem_Click(), IPLab.ImageDoc.filterBlobsMenuItem_Click(), IPLab.ImageDoc.filteringHslFiltersItem_Click(), IPLab.ImageDoc.filteringYCbCrFiltersItem_Click(), IPLab.ImageDoc.floydBinaryFiltersItem_Click(), IPLab.ImageDoc.gammaFiltersItem_Click(), IPLab.ImageDoc.gaussianConvolutionFiltersItem_Click(), IPLab.ImageDoc.Grayscale(), IPLab.ImageDoc.greenColorFiltersItem_Click(), IPLab.ImageDoc.histogramEqualizationMenuItem_Click(), IPLab.ImageDoc.hitAndMissFiltersItem_Click(), IPLab.ImageDoc.homogenityEdgeFiltersItem_Click(), IPLab.ImageDoc.hueHslFiltersItem_Click(), IPLab.ImageDoc.ImageDoc_MouseUp(), IPLab.ImageDoc.intersectTwosrcFiltersItem_Click(), IPLab.ImageDoc.invertColorFiltersItem_Click(), IPLab.ImageDoc.jarvisBinaryFiltersItem_Click(), IPLab.ImageDoc.jitterFiltersItem_Click(), IPLab.ImageDoc.labelingFiltersItem_Click(), IPLab.ImageDoc.Levels(), IPLab.ImageDoc.linearHslFiltersItem_Click(), IPLab.ImageDoc.linearYCbCrFiltersItem_Click(), IPLab.ImageDoc.magentaColorFiltersItem_Click(), IPLab.ImageDoc.maskFilterMenuItem_Click(), IPLab.ImageDoc.meanConvolutionFiltersItem_Click(), IPLab.ImageDoc.medianFiltersItem_Click(), IPLab.ImageDoc.mergeTwosrcFiltersItem_Click(), IPLab.ImageDoc.moravecCornersDetectorMenuItem_Click(), IPLab.ImageDoc.Morphology(), IPLab.ImageDoc.morphTwosrcFiltersItem_Click(), IPLab.ImageDoc.moveTowardsTwosrcFiltersItem_Click(), IPLab.ImageDoc.oilPaintingFiltersItem_Click(), IPLab.ImageDoc.openingMorphologyFiltersItem_Click(), IPLab.ImageDoc.orderedDitherBinaryFiltersItem_Click(), IPLab.ImageDoc.otsuThresholdMenuItem_Click(), IPLab.ImageDoc.perlinNoiseFiltersItem_Click(), IPLab.ImageDoc.pixellateFiltersItem_Click(), IPLab.ImageDoc.quadrilateralTransformationMenuItem_Click(), IPLab.ImageDoc.redColorFiltersItem_Click(), IPLab.ImageDoc.replaceBlueColorFiltersItem_Click(), IPLab.ImageDoc.replaceCbFiltersItem_Click(), IPLab.ImageDoc.replaceCrFiltersItem_Click(), IPLab.ImageDoc.replaceGreenColorFiltersItem_Click(), IPLab.ImageDoc.replaceRedColorFiltersItem_Click(), IPLab.ImageDoc.replaceYFiltersItem_Click(), IPLab.ImageDoc.ResizeImage(), IPLab.ImageDoc.rombozoidMenuItem_Click(), IPLab.ImageDoc.rotateColorFiltersItem_Click(), IPLab.ImageDoc.RotateImage(), IPLab.ImageDoc.runLengthSmoothingMenuItem_Click(), IPLab.ImageDoc.saltNoiseFiltersItem_Click(), IPLab.ImageDoc.Saturation(), IPLab.ImageDoc.sepiaColorFiltersItem_Click(), IPLab.ImageDoc.sharpenConvolutionFiltersItem_Click(), IPLab.ImageDoc.sharpenExConvolutionFiltersItem_Click(), IPLab.ImageDoc.shrinkFiltersItem_Click(), IPLab.ImageDoc.sierraBinaryFiltersItem_Click(), IPLab.ImageDoc.simplePosterizatonMenuItem_Click(), IPLab.ImageDoc.simpleSkeletonizationFiltersItem_Click(), IPLab.ImageDoc.sisThresholdBinaryFiltersItem_Click(), IPLab.ImageDoc.sobelEdgeFiltersItem_Click(), IPLab.ImageDoc.stuckiBinaryFiltersItem_Click(), IPLab.ImageDoc.subtractTwosrcFiltersItem_Click(), IPLab.ImageDoc.susanCornersDetectorMenuItem_Click(), IPLab.ImageDoc.Threshold(), IPLab.ImageDoc.thresholdCarryBinaryFiltersItem_Click(), IPLab.ImageDoc.tophatMorphologyFiltersItem_Click(), IPLab.ImageDoc.toRgbColorFiltersItem_Click(), IPLab.ImageDoc.transformFromPolarMenuItem_Click(), IPLab.ImageDoc.transformToPolarMenuItem_Click(), IPLab.ImageDoc.waterWaveMenuItem_Click(), and IPLab.ImageDoc.yellowColorFiltersItem_Click().
void IPLab.ImageDoc.imageItem_Popup (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.backImageItem, IPLab.ImageDoc.cropImageItem, and IPLab.ImageDoc.cropping.
void IPLab.ImageDoc.backImageItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.backup, and IPLab.ImageDoc.UpdateNewImage().
void IPLab.ImageDoc.Clone () inline private
References IPLab.IDocumentsHost.NewDocument().
Referenced by IPLab.ImageDoc.cloneImageItem_Click(), and IPLab.ImageDoc.ExecuteCommand().
void IPLab.ImageDoc.cloneImageItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.Clone().
void IPLab.ImageDoc.UpdateZoom () inline private
References IPLab.ImageDoc.ZoomChanged.
Referenced by IPLab.ImageDoc.ExecuteCommand(), IPLab.ImageDoc.FitToScreen(), IPLab.ImageDoc.mouseWheelMoved(), IPLab.ImageDoc.ZoomIn(), IPLab.ImageDoc.zoomItem_Click(), and IPLab.ImageDoc.ZoomOut().
void IPLab.ImageDoc.zoomItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.UpdateZoom().
void IPLab.ImageDoc.ZoomIn () inline private
References IPLab.ImageDoc.UpdateZoom().
Referenced by IPLab.ImageDoc.ExecuteCommand(), and IPLab.ImageDoc.zoomInImageItem_Click().
void IPLab.ImageDoc.zoomInImageItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ZoomIn().
void IPLab.ImageDoc.ZoomOut () inline private
References IPLab.ImageDoc.UpdateZoom().
Referenced by IPLab.ImageDoc.ExecuteCommand(), and IPLab.ImageDoc.zoomOutImageItem_Click().
void IPLab.ImageDoc.zoomOutImageItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ZoomOut().
void IPLab.ImageDoc.FitToScreen () inline private
References IPLab.ImageDoc.UpdateZoom().
Referenced by IPLab.ImageDoc.ExecuteCommand(), and IPLab.ImageDoc.zoomFitImageItem_Click().
void IPLab.ImageDoc.zoomFitImageItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.FitToScreen().
void IPLab.ImageDoc.flipImageItem_Click (object sender, System.EventArgs e) inline private
void IPLab.ImageDoc.mirrorItem_Click (object sender, System.EventArgs e) inline private
void IPLab.ImageDoc.rotateImageItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.UpdateNewImage().
void IPLab.ImageDoc.invertColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.rotateColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.sepiaColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.bayerFiltersItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfGrayscale(), and IPLab.BayerFilterForm.Filter.
void IPLab.ImageDoc.Grayscale () inline private
References IPLab.ImageDoc.ApplyFilter().
Referenced by IPLab.ImageDoc.ExecuteCommand(), and IPLab.ImageDoc.grayscaleColorFiltersItem_Click().
void IPLab.ImageDoc.grayscaleColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.Grayscale().
void IPLab.ImageDoc.toRgbColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.redColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.greenColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.blueColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.cyanColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.magentaColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.yellowColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.colorFilteringColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfColor(), IPLab.ColorFilteringForm.Filter, IPLab.ImageDoc.image, and IPLab.ColorFilteringForm.Image.
void IPLab.ImageDoc.euclideanFilteringColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfColor(), IPLab.EuclideanColorFilteringForm.Filter, IPLab.ImageDoc.image, and IPLab.EuclideanColorFilteringForm.Image.
void IPLab.ImageDoc.channelsFilteringColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfColor(), IPLab.ChannelFilteringForm.Filter, IPLab.ImageDoc.image, and IPLab.ChannelFilteringForm.Image.
void IPLab.ImageDoc.extractRedColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.extractGreenColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.extractRedBlueFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.replaceRedColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.IDocumentsHost.GetImage().
void IPLab.ImageDoc.replaceGreenColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.IDocumentsHost.GetImage().
void IPLab.ImageDoc.replaceBlueColorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.IDocumentsHost.GetImage().
void IPLab.ImageDoc.extractRedFromNrgbMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.extractGreenFromNrgbMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.extractBlueFromNrgbMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.Brightness () inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfColor(), IPLab.BrightnessForm.Filter, IPLab.ImageDoc.image, and IPLab.BrightnessForm.Image.
Referenced by IPLab.ImageDoc.brightnessHslFiltersItem_Click(), and IPLab.ImageDoc.ExecuteCommand().
void IPLab.ImageDoc.brightnessHslFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.Brightness().
void IPLab.ImageDoc.Contrast () inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfColor(), IPLab.ContrastForm.Filter, IPLab.ImageDoc.image, and IPLab.ContrastForm.Image.
Referenced by IPLab.ImageDoc.contrastHslFiltersItem_Click(), and IPLab.ImageDoc.ExecuteCommand().
void IPLab.ImageDoc.contrastHslFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.Contrast().
void IPLab.ImageDoc.Saturation () inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfColor(), IPLab.SaturationForm.Filter, IPLab.ImageDoc.image, and IPLab.SaturationForm.Image.
Referenced by IPLab.ImageDoc.ExecuteCommand(), and IPLab.ImageDoc.saturationHslFiltersItem_Click().
void IPLab.ImageDoc.saturationHslFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.Saturation().
void IPLab.ImageDoc.linearHslFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfColor(), IPLab.HSLLinearForm.Filter, IPLab.ImageDoc.image, and IPLab.HSLLinearForm.Image.
void IPLab.ImageDoc.filteringHslFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfColor(), IPLab.HSLFilteringForm.Filter, IPLab.ImageDoc.image, and IPLab.HSLFilteringForm.Image.
void IPLab.ImageDoc.hueHslFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfColor(), IPLab.HueModifierForm.Filter, IPLab.ImageDoc.image, and IPLab.HueModifierForm.Image.
void IPLab.ImageDoc.linearYCbCrFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfColor(), IPLab.YCbCrLinearForm.Filter, IPLab.ImageDoc.image, and IPLab.YCbCrLinearForm.Image.
void IPLab.ImageDoc.filteringYCbCrFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfColor(), IPLab.YCbCrFilteringForm.Filter, IPLab.ImageDoc.image, and IPLab.YCbCrFilteringForm.Image.
void IPLab.ImageDoc.extracYFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.extracCbFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.extracCrFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.replaceYFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.IDocumentsHost.GetImage().
void IPLab.ImageDoc.replaceCbFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.IDocumentsHost.GetImage().
void IPLab.ImageDoc.replaceCrFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.IDocumentsHost.GetImage().
void IPLab.ImageDoc.Threshold () inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfGrayscale(), IPLab.ThresholdForm.Filter, IPLab.ImageDoc.image, and IPLab.ThresholdForm.Image.
Referenced by IPLab.ImageDoc.ExecuteCommand(), and IPLab.ImageDoc.thresholdBinaryFiltersItem_Click().
void IPLab.ImageDoc.thresholdBinaryFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.Threshold().
void IPLab.ImageDoc.thresholdCarryBinaryFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.orderedDitherBinaryFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.bayerDitherBinaryFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.floydBinaryFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.burkesBinaryFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.stuckiBinaryFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.jarvisBinaryFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.sierraBinaryFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.sisThresholdBinaryFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.otsuThresholdMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.bradleyLocalThresholdingMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.erosionMorphologyFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.dilatationMorphologyFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.openingMorphologyFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.closingMorphologyFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.tophatMorphologyFiltersItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.bottomMorphologyFiltersItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.Morphology () inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.MathMorphologyForm.Filter, IPLab.ImageDoc.image, and IPLab.MathMorphologyForm.Image.
Referenced by IPLab.ImageDoc.customMorphologyFiltersItem_Click(), and IPLab.ImageDoc.ExecuteCommand().
void IPLab.ImageDoc.customMorphologyFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.Morphology().
void IPLab.ImageDoc.hitAndMissFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfBinary(), IPLab.MathMorphologyForm.Filter, IPLab.ImageDoc.image, and IPLab.MathMorphologyForm.Image.
void IPLab.ImageDoc.meanConvolutionFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.blurConvolutionFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.gaussianConvolutionFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.GaussianForm.Filter, IPLab.ImageDoc.image, and IPLab.GaussianForm.Image.
void IPLab.ImageDoc.sharpenExConvolutionFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.SharpenExForm.Filter, IPLab.ImageDoc.image, and IPLab.SharpenExForm.Image.
void IPLab.ImageDoc.sharpenConvolutionFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.edgesConvolutionFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.Convolution () inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ConvolutionForm.Filter, IPLab.ImageDoc.image, and IPLab.ConvolutionForm.Image.
Referenced by IPLab.ImageDoc.customConvolutionFiltersItem_Click(), and IPLab.ImageDoc.ExecuteCommand().
void IPLab.ImageDoc.customConvolutionFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.Convolution().
void IPLab.ImageDoc.mergeTwosrcFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.IDocumentsHost.GetImage().
void IPLab.ImageDoc.intersectTwosrcFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.IDocumentsHost.GetImage().
void IPLab.ImageDoc.addTwosrcFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.IDocumentsHost.GetImage().
void IPLab.ImageDoc.subtractTwosrcFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.IDocumentsHost.GetImage().
void IPLab.ImageDoc.differenceTwosrcFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.IDocumentsHost.GetImage().
void IPLab.ImageDoc.moveTowardsTwosrcFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.MoveTowardsFilterForm.Filter, IPLab.IDocumentsHost.GetImage(), IPLab.MoveTowardsFilterForm.Image, and IPLab.ImageDoc.image.
void IPLab.ImageDoc.morphTwosrcFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.MorphForm.Filter, IPLab.IDocumentsHost.GetImage(), IPLab.ImageDoc.image, and IPLab.MorphForm.Image.
void IPLab.ImageDoc.maskFilterMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.IDocumentsHost.GetImage().
void IPLab.ImageDoc.homogenityEdgeFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.differenceEdgeFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.sobelEdgeFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.cannyEdgeFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.CannyDetectorForm.Filter, IPLab.ImageDoc.image, and IPLab.CannyDetectorForm.Image.
void IPLab.ImageDoc.susanCornersDetectorMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.SusanCornersDetectorForm.Filter, IPLab.SusanCornersDetectorForm.Image, and IPLab.ImageDoc.image.
void IPLab.ImageDoc.moravecCornersDetectorMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.MoravecCornersDetectorForm.Filter, IPLab.MoravecCornersDetectorForm.Image, and IPLab.ImageDoc.image.
void IPLab.ImageDoc.additiveNoiseFiltersItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.AdditiveNoiseForm.Filter, IPLab.AdditiveNoiseForm.Image, and IPLab.ImageDoc.image.
void IPLab.ImageDoc.saltNoiseFiltersItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.SaltNoiseForm.Filter, IPLab.SaltNoiseForm.Image, and IPLab.ImageDoc.image.
void IPLab.ImageDoc.adaptiveSmoothingFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.AdaptiveSmoothForm.Filter, IPLab.ImageDoc.image, and IPLab.AdaptiveSmoothForm.Image.
void IPLab.ImageDoc.conservativeSmoothingFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.bilateralSmoothingFiltersItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.BilateralForm.Filter, IPLab.BilateralForm.Image, and IPLab.ImageDoc.image.
void IPLab.ImageDoc.perlinNoiseFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.PerlinNoiseForm.Filter, IPLab.ImageDoc.image, and IPLab.PerlinNoiseForm.Image.
void IPLab.ImageDoc.oilPaintingFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.OilPaintingForm.Filter, IPLab.ImageDoc.image, and IPLab.OilPaintingForm.Image.
void IPLab.ImageDoc.jitterFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.pixellateFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.PixelateForm.Filter, IPLab.ImageDoc.image, and IPLab.PixelateForm.Image.
void IPLab.ImageDoc.rombozoidMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.height, and IPLab.ImageDoc.width.
void IPLab.ImageDoc.waterWaveMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.WaterWaveForm.Filter, IPLab.WaterWaveForm.Image, and IPLab.ImageDoc.image.
void IPLab.ImageDoc.simpleSkeletonizationFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.shrinkFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.ShrinkForm.Filter.
void IPLab.ImageDoc.simplePosterizatonMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.SimplePosterizationForm.Filter, IPLab.SimplePosterizationForm.Image, and IPLab.ImageDoc.image.
void IPLab.ImageDoc.labelingFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.blobExtractorFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.IDocumentsHost.NewDocument().
void IPLab.ImageDoc.fillHolesMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfBinary(), IPLab.HolesFillingForm.Filter, IPLab.HolesFillingForm.Image, and IPLab.ImageDoc.image.
void IPLab.ImageDoc.filterBlobsMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.BlobsFilteringForm.Filter, IPLab.BlobsFilteringForm.Image, and IPLab.ImageDoc.image.
void IPLab.ImageDoc.extractBiggestBlobMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.quadrilateralFinderMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.IDocumentsHost.CreateNewDocumentOnChange, IPLab.ImageDoc.image, IPLab.IDocumentsHost.NewDocument(), IPLab.IDocumentsHost.RememberOnChange, and IPLab.ImageDoc.UpdateNewImage().
void IPLab.ImageDoc.quadrilateralTransformationMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.ResizeImage () inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ResizeForm.Filter, and IPLab.ResizeForm.OriginalSize.
Referenced by IPLab.ImageDoc.ExecuteCommand(), and IPLab.ImageDoc.resizeFiltersItem_Click().
void IPLab.ImageDoc.resizeFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ResizeImage().
void IPLab.ImageDoc.RotateImage () inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.RotateForm.Filter.
Referenced by IPLab.ImageDoc.ExecuteCommand(), and IPLab.ImageDoc.rotateFiltersItem_Click().
void IPLab.ImageDoc.rotateFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.RotateImage().
void IPLab.ImageDoc.Levels () inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.LevelsLinearForm.Filter, IPLab.ImageDoc.image, and IPLab.LevelsLinearForm.Image.
Referenced by IPLab.ImageDoc.ExecuteCommand(), and IPLab.ImageDoc.levelsFiltersItem_Click().
void IPLab.ImageDoc.levelsFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.Levels().
void IPLab.ImageDoc.contrastStretchMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.histogramEqualizationMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.medianFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.gammaFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.GammaForm.Filter, IPLab.ImageDoc.image, and IPLab.GammaForm.Image.
void IPLab.ImageDoc.CreateStereoAnaglyph (StereoAnaglyph.Algorithm algorithm) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.IDocumentsHost.GetImage().
Referenced by IPLab.ImageDoc.colorAnaglyphMenuItem_Click(), IPLab.ImageDoc.grayAnaglyphMenuItem_Click(), IPLab.ImageDoc.halfColorAnaglyphMenuItem_Click(), IPLab.ImageDoc.optimizedAnaglyphMenuItem_Click(), and IPLab.ImageDoc.trueAnaglyphMenuItem_Click().
void IPLab.ImageDoc.trueAnaglyphMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.CreateStereoAnaglyph().
void IPLab.ImageDoc.grayAnaglyphMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.CreateStereoAnaglyph().
void IPLab.ImageDoc.colorAnaglyphMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.CreateStereoAnaglyph().
void IPLab.ImageDoc.halfColorAnaglyphMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.CreateStereoAnaglyph().
void IPLab.ImageDoc.optimizedAnaglyphMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.CreateStereoAnaglyph().
void IPLab.ImageDoc.documentAligningMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter().
void IPLab.ImageDoc.transformToPolarMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.PolarFilterForm.Filter.
void IPLab.ImageDoc.transformFromPolarMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), and IPLab.PolarFilterForm.Filter.
void IPLab.ImageDoc.runLengthSmoothingMenuItem_Click (object sender, EventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.CheckIfBinary(), IPLab.RunLengthSmoothingForm.Filter, IPLab.RunLengthSmoothingForm.Image, and IPLab.ImageDoc.image.
void IPLab.ImageDoc.ForwardFourierTransformation () inline private
References IPLab.ImageDoc.CheckIfGrayscale(), and IPLab.IDocumentsHost.NewDocument().
Referenced by IPLab.ImageDoc.ExecuteCommand(), and IPLab.ImageDoc.fourierFiltersItem_Click().
void IPLab.ImageDoc.fourierFiltersItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.ForwardFourierTransformation().
void IPLab.ImageDoc.GetImageAndScreenPoints (Point point, out Point imgPoint, out Point screenPoint) inline private
References IPLab.ImageDoc.height, IPLab.ImageDoc.width, and IPLab.ImageDoc.zoom.
Referenced by IPLab.ImageDoc.ImageDoc_MouseDown(), and IPLab.ImageDoc.ImageDoc_MouseMove().
void IPLab.ImageDoc.NormalizePoints (ref Point pt1, ref Point pt2) inline private
Referenced by IPLab.ImageDoc.DrawSelectionFrame(), IPLab.ImageDoc.ImageDoc_MouseMove(), and IPLab.ImageDoc.ImageDoc_MouseUp().
void IPLab.ImageDoc.DrawSelectionFrame (Graphics g) inline private
References IPLab.ImageDoc.endW, IPLab.ImageDoc.NormalizePoints(), and IPLab.ImageDoc.startW.
Referenced by IPLab.ImageDoc.ImageDoc_MouseDown(), IPLab.ImageDoc.ImageDoc_MouseMove(), and IPLab.ImageDoc.ImageDoc_MouseUp().
void IPLab.ImageDoc.Crop () inline private
Referenced by IPLab.ImageDoc.cropImageItem_Click(), IPLab.ImageDoc.ExecuteCommand(), and IPLab.ImageDoc.ImageDoc_MouseUp().
void IPLab.ImageDoc.cropImageItem_Click (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.Crop().
void IPLab.ImageDoc.ImageDoc_MouseDown (object sender, System.Windows.Forms.MouseEventArgs e) inline private
References IPLab.ImageDoc.DrawSelectionFrame(), IPLab.ImageDoc.GetImageAndScreenPoints(), IPLab.ImageDoc.start, and IPLab.ImageDoc.startW.
void IPLab.ImageDoc.ImageDoc_MouseUp (object sender, System.Windows.Forms.MouseEventArgs e) inline private
References IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.Crop(), IPLab.ImageDoc.DrawSelectionFrame(), and IPLab.ImageDoc.NormalizePoints().
void IPLab.ImageDoc.ImageDoc_MouseMove (object sender, System.Windows.Forms.MouseEventArgs e) inline private
References IPLab.ImageDoc.DrawSelectionFrame(), IPLab.ImageDoc.end, IPLab.ImageDoc.GetImageAndScreenPoints(), IPLab.ImageDoc.height, IPLab.ImageDoc.MouseImagePosition, IPLab.ImageDoc.NormalizePoints(), IPLab.ImageDoc.SelectionChanged, IPLab.ImageDoc.start, and IPLab.ImageDoc.width.
void IPLab.ImageDoc.ImageDoc_MouseLeave (object sender, System.EventArgs e) inline private
References IPLab.ImageDoc.MouseImagePosition.
void IPLab.ImageDoc.mouseWheelMoved (object sender, MouseEventArgs e) inline
References IPLab.ImageDoc.UpdateZoom().
Referenced by IPLab.ImageDoc.Init().
override void IPLab.ImageDoc.Dispose (bool disposing) inline protected
Clean up any resources being used.
References IPLab.ImageDoc.components, and IPLab.ImageDoc.image.
void IPLab.ImageDoc.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IPLab.ImageDoc.Init().
Member Data Documentation
Bitmap IPLab.ImageDoc.backup = null private
Referenced by IPLab.ImageDoc.backImageItem_Click().
Bitmap IPLab.ImageDoc.image = null private
Referenced by IPLab.ImageDoc.adaptiveSmoothingFiltersItem_Click(), IPLab.ImageDoc.additiveNoiseFiltersItem_Click(), IPLab.ImageDoc.ApplyFilter(), IPLab.ImageDoc.bilateralSmoothingFiltersItem_Click(), IPLab.ImageDoc.Brightness(), IPLab.ImageDoc.cannyEdgeFiltersItem_Click(), IPLab.ImageDoc.channelsFilteringColorFiltersItem_Click(), IPLab.ImageDoc.colorFilteringColorFiltersItem_Click(), IPLab.ImageDoc.Contrast(), IPLab.ImageDoc.Convolution(), IPLab.ImageDoc.Dispose(), IPLab.ImageDoc.euclideanFilteringColorFiltersItem_Click(), IPLab.ImageDoc.fillHolesMenuItem_Click(), IPLab.ImageDoc.filterBlobsMenuItem_Click(), IPLab.ImageDoc.filteringHslFiltersItem_Click(), IPLab.ImageDoc.filteringYCbCrFiltersItem_Click(), IPLab.ImageDoc.gammaFiltersItem_Click(), IPLab.ImageDoc.gaussianConvolutionFiltersItem_Click(), IPLab.ImageDoc.hitAndMissFiltersItem_Click(), IPLab.ImageDoc.hueHslFiltersItem_Click(), IPLab.ImageDoc.ImageDoc(), IPLab.ImageDoc.Levels(), IPLab.ImageDoc.linearHslFiltersItem_Click(), IPLab.ImageDoc.linearYCbCrFiltersItem_Click(), IPLab.ImageDoc.moravecCornersDetectorMenuItem_Click(), IPLab.ImageDoc.Morphology(), IPLab.ImageDoc.morphTwosrcFiltersItem_Click(), IPLab.ImageDoc.moveTowardsTwosrcFiltersItem_Click(), IPLab.ImageDoc.oilPaintingFiltersItem_Click(), IPLab.ImageDoc.perlinNoiseFiltersItem_Click(), IPLab.ImageDoc.pixellateFiltersItem_Click(), IPLab.ImageDoc.quadrilateralFinderMenuItem_Click(), IPLab.ImageDoc.runLengthSmoothingMenuItem_Click(), IPLab.ImageDoc.saltNoiseFiltersItem_Click(), IPLab.ImageDoc.Saturation(), IPLab.ImageDoc.sharpenExConvolutionFiltersItem_Click(), IPLab.ImageDoc.simplePosterizatonMenuItem_Click(), IPLab.ImageDoc.susanCornersDetectorMenuItem_Click(), IPLab.ImageDoc.Threshold(), and IPLab.ImageDoc.waterWaveMenuItem_Click().
string IPLab.ImageDoc.fileName = null private
Referenced by IPLab.ImageDoc.ImageDoc().
int IPLab.ImageDoc.width private
Referenced by IPLab.ImageDoc.GetImageAndScreenPoints(), IPLab.ImageDoc.ImageDoc_MouseMove(), IPLab.ImageDoc.OnPaint(), and IPLab.ImageDoc.rombozoidMenuItem_Click().
int IPLab.ImageDoc.height private
Referenced by IPLab.ImageDoc.GetImageAndScreenPoints(), IPLab.ImageDoc.ImageDoc_MouseMove(), IPLab.ImageDoc.OnPaint(), and IPLab.ImageDoc.rombozoidMenuItem_Click().
float IPLab.ImageDoc.zoom = 1 private
Referenced by IPLab.ImageDoc.GetImageAndScreenPoints().
IDocumentsHost IPLab.ImageDoc.host = null private
Referenced by IPLab.ImageDoc.ImageDoc().
bool IPLab.ImageDoc.cropping = false private
Referenced by IPLab.ImageDoc.imageItem_Popup().
bool IPLab.ImageDoc.dragging = false private
Point IPLab.ImageDoc.start private
Referenced by IPLab.ImageDoc.ImageDoc_MouseDown(), and IPLab.ImageDoc.ImageDoc_MouseMove().
Point IPLab.ImageDoc.end private
Referenced by IPLab.ImageDoc.ImageDoc_MouseMove().
Point IPLab.ImageDoc.startW private
Referenced by IPLab.ImageDoc.DrawSelectionFrame(), and IPLab.ImageDoc.ImageDoc_MouseDown().
Point IPLab.ImageDoc.endW private
Referenced by IPLab.ImageDoc.DrawSelectionFrame().
System.Windows.Forms.MainMenu IPLab.ImageDoc.mainMenu private
System.Windows.Forms.MenuItem IPLab.ImageDoc.imageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.filtersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.cloneImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.rotateColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.invertColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.sepiaColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.grayscaleColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem1 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem2 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.backImageItem private
Referenced by IPLab.ImageDoc.imageItem_Popup().
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem4 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem5 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem6 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem7 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.z10ImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.z25ImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.z50ImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.z75ImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.z100ImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.z150ImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.z200ImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.z400ImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.z500ImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem8 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.zoomInImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.zoomOutImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem11 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.zoomFitImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.colorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.binaryFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.thresholdBinaryFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.thresholdCarryBinaryFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.floydBinaryFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.morphologyFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.dilatationMorphologyFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.convolutionFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.meanConvolutionFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.blurConvolutionFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.sharpenConvolutionFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.edgesConvolutionFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.levelsFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.flipImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.mirrorItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.rotateImageItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem10 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.cropImageItem private
Referenced by IPLab.ImageDoc.imageItem_Popup().
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem3 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem9 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.customMorphologyFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem12 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.customConvolutionFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.openingMorphologyFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.medianFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.closingMorphologyFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.erosionMorphologyFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.pixellateFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem15 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem16 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.redColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.greenColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.blueColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem17 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.cyanColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.magentaColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.yellowColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.channelsFilteringColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem19 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.colorFilteringColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.euclideanFilteringColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.extractRedColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.extractGreenColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.extractRedBlueFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem18 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.replaceRedColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem20 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.replaceGreenColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.replaceBlueColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.twosrcFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.mergeTwosrcFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.intersectTwosrcFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem21 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.addTwosrcFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.subtractTwosrcFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem22 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.differenceTwosrcFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.moveTowardsTwosrcFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.simpleSkeletonizationFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem24 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.orderedDitherBinaryFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem14 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.bayerDitherBinaryFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.burkesBinaryFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.stuckiBinaryFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.jarvisBinaryFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.sierraBinaryFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem23 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.resizeFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem26 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.shrinkFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.rotateFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.jitterFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.gammaFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem27 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.hitAndMissFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.hslFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.brightnessHslFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.contrastHslFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.saturationHslFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem28 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.filteringHslFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.hueHslFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem29 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.linearHslFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem25 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.fourierFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.edgeFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.homogenityEdgeFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.differenceEdgeFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.labelingFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.sobelEdgeFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.gaussianConvolutionFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.adaptiveSmoothingFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.blobExtractorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem31 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.sisThresholdBinaryFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.conservativeSmoothingFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem34 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.cannyEdgeFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem33 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.sharpenExConvolutionFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.oilPaintingFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.ycbcrFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.extracYFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.extracCbFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.extracCrFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem37 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem38 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.replaceYFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.replaceCbFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.replaceCrFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.linearYCbCrFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.filteringYCbCrFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.toRgbColorFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.perlinNoiseFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.morphTwosrcFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.tophatMorphologyFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.bottomMorphologyFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.noiseFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.additiveNoiseFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.saltNoiseFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem13 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.extractBiggestBlobMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem30 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.contrastStretchMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.histogramEqualizationMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem32 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.extractRedFromNrgbMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.extractGreenFromNrgbMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.extractBlueFromNrgbMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.otsuThresholdMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.filterBlobsMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem35 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.susanCornersDetectorMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.moravecCornersDetectorMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.simplePosterizatonMenuItem private
System.ComponentModel.IContainer IPLab.ImageDoc.components private
Referenced by IPLab.ImageDoc.Dispose().
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem36 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem39 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.trueAnaglyphMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.grayAnaglyphMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.colorAnaglyphMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.halfColorAnaglyphMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.optimizedAnaglyphMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem40 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.quadrilateralFinderMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.quadrilateralTransformationMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.documentAligningMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.differentEffectsFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.rombozoidMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.waterWaveMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.bradleyLocalThresholdingMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.fillHolesMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.bilateralSmoothingFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.bayerFiltersItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem41 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.transformToPolarMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.transformFromPolarMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.menuItem42 private
System.Windows.Forms.MenuItem IPLab.ImageDoc.runLengthSmoothingMenuItem private
System.Windows.Forms.MenuItem IPLab.ImageDoc.maskFilterMenuItem private
Property Documentation
Bitmap IPLab.ImageDoc.Image get
Referenced by IPLab.MainForm.SaveFile(), IPLab.MainForm.UpdateHistogram(), and IPLab.MainForm.UpdateStatistics().
int IPLab.ImageDoc.ImageWidth get
int IPLab.ImageDoc.ImageHeight get
float IPLab.ImageDoc.Zoom get
Referenced by IPLab.MainForm.UpdateZoomStatus().
string IPLab.ImageDoc.FileName get
Event Documentation
EventHandler IPLab.ImageDoc.DocumentChanged
Referenced by IPLab.MainForm.SetupDocumentEvents(), and IPLab.ImageDoc.UpdateNewImage().
EventHandler IPLab.ImageDoc.ZoomChanged
Referenced by IPLab.MainForm.SetupDocumentEvents(), and IPLab.ImageDoc.UpdateZoom().
SelectionEventHandler IPLab.ImageDoc.MouseImagePosition
Referenced by IPLab.ImageDoc.ImageDoc_MouseLeave(), IPLab.ImageDoc.ImageDoc_MouseMove(), and IPLab.MainForm.SetupDocumentEvents().
SelectionEventHandler IPLab.ImageDoc.SelectionChanged
Referenced by IPLab.ImageDoc.ImageDoc_MouseMove(), and IPLab.MainForm.SetupDocumentEvents().
The documentation for this class was generated from the following files:
igsandbox/imageprocessing/iplab_new_GPL/Sources/ImageDoc.cs
igsandbox/imageprocessing/iplab_new_GPL/Sources/ImageDoc.Designer.cs