IGLib: PipeServer.Server Class Reference
PipeServer.Server Class Reference
Classes
class Client
Public Member Functions
static SafeFileHandle CreateNamedPipe (String pipeName, uint dwOpenMode, uint dwPipeMode, uint nMaxInstances, uint nOutBufferSize, uint nInBufferSize, uint nDefaultTimeOut, IntPtr lpSecurityAttributes)
static int ConnectNamedPipe (SafeFileHandle hNamedPipe, IntPtr lpOverlapped)
delegate void MessageReceivedHandler (Client client, string message)
Server ()
void Start ()
Starts the pipe server
void SendMessage (string message)
Sends a message to all connected clients
Public Attributes
const uint DUPLEX = (0x00000003)
const uint FILE_FLAG_OVERLAPPED = (0x40000000)
const int BUFFER_SIZE = 4096
Properties
string PipeName [get, set]
bool Running [get]
Events
MessageReceivedHandler MessageReceived
Private Member Functions
void ListenForClients ()
Listens for client connections
void Read (object clientObj)
Reads incoming data from connected clients
Private Attributes
string pipeName
Thread listenThread
bool running
List< Client > clients
Constructor & Destructor Documentation
PipeServer.Server.Server () inline
Member Function Documentation
static SafeFileHandle PipeServer.Server.CreateNamedPipe (String pipeName, uint dwOpenMode, uint dwPipeMode, uint nMaxInstances, uint nOutBufferSize, uint nInBufferSize, uint nDefaultTimeOut, IntPtr lpSecurityAttributes)
Referenced by PipeServer.Server.ListenForClients().
static int PipeServer.Server.ConnectNamedPipe (SafeFileHandle hNamedPipe, IntPtr lpOverlapped)
Referenced by PipeServer.Server.ListenForClients().
delegate void PipeServer.Server.MessageReceivedHandler (Client client, string message)
Referenced by PipeServer.Form1.Form1(), and PipeServer.Form1.pipeServer_MessageReceived().
void PipeServer.Server.Start () inline
Starts the pipe server
References PipeServer.Server.ListenForClients().
Referenced by PipeServer.Form1.btnStart_Click().
void PipeServer.Server.ListenForClients () inline private
Listens for client connections
References client(), PipeServer.Server.ConnectNamedPipe(), PipeServer.Server.CreateNamedPipe(), PipeServer.Server.Client.handle, and PipeServer.Server.Read().
Referenced by PipeServer.Server.Start().
void PipeServer.Server.Read (object clientObj) inline private
Reads incoming data from connected clients
Parameters
clientObj
References PipeServer.Server.BUFFER_SIZE, client(), PipeServer.Server.Client.handle, PipeServer.Server.MessageReceived, and PipeServer.Server.Client.stream.
Referenced by PipeServer.Server.ListenForClients().
void PipeServer.Server.SendMessage (string message) inline
Sends a message to all connected clients
Parameters
message the message to send
References client(), and PipeServer.Server.Client.stream.
Referenced by PipeServer.Form1.btnSend_Click().
Member Data Documentation
const uint PipeServer.Server.DUPLEX = (0x00000003)
const uint PipeServer.Server.FILE_FLAG_OVERLAPPED = (0x40000000)
const int PipeServer.Server.BUFFER_SIZE = 4096
Referenced by PipeServer.Server.Read().
string PipeServer.Server.pipeName private
Thread PipeServer.Server.listenThread private
bool PipeServer.Server.running private
List<Client> PipeServer.Server.clients private
Property Documentation
string PipeServer.Server.PipeName get set
Referenced by PipeServer.Form1.btnStart_Click().
bool PipeServer.Server.Running get
Referenced by PipeServer.Form1.btnStart_Click().
Event Documentation
MessageReceivedHandler PipeServer.Server.MessageReceived
Referenced by PipeServer.Form1.Form1(), and PipeServer.Server.Read().
The documentation for this class was generated from the following file:
igsandbox/InterprocessCommunication/named_pipe_examples_master/C# client & server - named pipe/PipeServer/PipeServer/Server.cs