IGLib: alglib.minlm Class Reference
alglib.minlm Class Reference
Classes
class minlmreport
class minlmstate
Static Public Member Functions
static void minlmcreatevj (int n, int m, double[] x, minlmstate state)
static void minlmcreatev (int n, int m, double[] x, double diffstep, minlmstate state)
static void minlmcreatefgh (int n, double[] x, minlmstate state)
static void minlmsetcond (minlmstate state, double epsg, double epsf, double epsx, int maxits)
static void minlmsetxrep (minlmstate state, bool needxrep)
static void minlmsetstpmax (minlmstate state, double stpmax)
static void minlmsetscale (minlmstate state, double[] s)
static void minlmsetbc (minlmstate state, double[] bndl, double[] bndu)
static void minlmsetacctype (minlmstate state, int acctype)
static bool minlmiteration (minlmstate state)
static void minlmresults (minlmstate state, ref double[] x, minlmreport rep)
static void minlmresultsbuf (minlmstate state, ref double[] x, minlmreport rep)
static void minlmrestartfrom (minlmstate state, double[] x)
static void minlmcreatevgj (int n, int m, double[] x, minlmstate state)
static void minlmcreatefgj (int n, int m, double[] x, minlmstate state)
static void minlmcreatefj (int n, int m, double[] x, minlmstate state)
static void minlmsetgradientcheck (minlmstate state, double teststep)
static void minlmcreatevj (int n, int m, double[] x, minlmstate state)
static void minlmcreatev (int n, int m, double[] x, double diffstep, minlmstate state)
static void minlmcreatefgh (int n, double[] x, minlmstate state)
static void minlmsetcond (minlmstate state, double epsg, double epsf, double epsx, int maxits)
static void minlmsetxrep (minlmstate state, bool needxrep)
static void minlmsetstpmax (minlmstate state, double stpmax)
static void minlmsetscale (minlmstate state, double[] s)
static void minlmsetbc (minlmstate state, double[] bndl, double[] bndu)
static void minlmsetacctype (minlmstate state, int acctype)
static bool minlmiteration (minlmstate state)
static void minlmresults (minlmstate state, ref double[] x, minlmreport rep)
static void minlmresultsbuf (minlmstate state, ref double[] x, minlmreport rep)
static void minlmrestartfrom (minlmstate state, double[] x)
static void minlmcreatevgj (int n, int m, double[] x, minlmstate state)
static void minlmcreatefgj (int n, int m, double[] x, minlmstate state)
static void minlmcreatefj (int n, int m, double[] x, minlmstate state)
static void minlmsetgradientcheck (minlmstate state, double teststep)
Public Attributes
const int lmmodefj = 0
const int lmmodefgj = 1
const int lmmodefgh = 2
const int lmflagnoprelbfgs = 1
const int lmflagnointlbfgs = 2
const int lmprelbfgsm = 5
const int lmintlbfgsits = 5
const int lbfgsnorealloc = 1
const double lambdaup = 2.0
const double lambdadown = 0.33
const double suspiciousnu = 16
const int smallmodelage = 3
const int additers = 5
Static Private Member Functions
static void lmprepare (int n, int m, bool havegrad, minlmstate state)
static void clearrequestfields (minlmstate state)
static bool increaselambda (ref double lambdav, ref double nu)
static void decreaselambda (ref double lambdav, ref double nu)
static double boundedscaledantigradnorm (minlmstate state, double[] x, double[] g)
static void lmprepare (int n, int m, bool havegrad, minlmstate state)
static void clearrequestfields (minlmstate state)
static bool increaselambda (ref double lambdav, ref double nu)
static void decreaselambda (ref double lambdav, ref double nu)
static double boundedscaledantigradnorm (minlmstate state, double[] x, double[] g)
Member Function Documentation
static void alglib.minlm.minlmcreatevj (int n, int m, double[] x, minlmstate state) inline static
Referenced by alglib.testminlmunit.gradientchecktest(), alglib.minlmcreatevj(), and alglib.testminlmunit.testminlm().
static void alglib.minlm.minlmcreatev (int n, int m, double[] x, double diffstep, minlmstate state) inline static
Referenced by alglib.minlmcreatev(), alglib.testminlmunit.testminlm(), and alglib.testminlmunit.tryreproducefixedbugs().
static void alglib.minlm.minlmcreatefgh (int n, double[] x, minlmstate state) inline static
Referenced by alglib.minlmcreatefgh(), and alglib.testminlmunit.testminlm().
static void alglib.minlm.minlmsetcond (minlmstate state, double epsg, double epsf, double epsx, int maxits) inline static
Referenced by alglib.testminlmunit.gradientchecktest(), alglib.minlmsetcond(), and alglib.testminlmunit.testminlm().
static void alglib.minlm.minlmsetxrep (minlmstate state, bool needxrep) inline static
Referenced by alglib.minlmsetxrep(), and alglib.testminlmunit.testminlm().
static void alglib.minlm.minlmsetstpmax (minlmstate state, double stpmax) inline static
Referenced by alglib.minlmsetstpmax(), and alglib.testminlmunit.testminlm().
static void alglib.minlm.minlmsetscale (minlmstate state, double[] s) inline static
Referenced by alglib.minlmsetscale().
static void alglib.minlm.minlmsetbc (minlmstate state, double[] bndl, double[] bndu) inline static
Referenced by alglib.testminlmunit.gradientchecktest(), alglib.minlmsetbc(), alglib.testminlmunit.testminlm(), and alglib.testminlmunit.tryreproducefixedbugs().
static void alglib.minlm.minlmsetacctype (minlmstate state, int acctype) inline static
Referenced by alglib.minlmsetacctype(), and alglib.testminlmunit.testminlm().
static bool alglib.minlm.minlmiteration (minlmstate state) inline static
Referenced by alglib.testminlmunit.gradientchecktest(), alglib.minlmiteration(), alglib.testminlmunit.testminlm(), and alglib.testminlmunit.tryreproducefixedbugs().
static void alglib.minlm.minlmresults (minlmstate state, ref double[] x, minlmreport rep) inline static
Referenced by alglib.testminlmunit.gradientchecktest(), alglib.minlmresults(), alglib.testminlmunit.testminlm(), and alglib.testminlmunit.tryreproducefixedbugs().
static void alglib.minlm.minlmresultsbuf (minlmstate state, ref double[] x, minlmreport rep) inline static
Referenced by alglib.minlmresultsbuf().
static void alglib.minlm.minlmrestartfrom (minlmstate state, double[] x) inline static
Referenced by alglib.testminlmunit.gradientchecktest(), alglib.minlmrestartfrom(), and alglib.testminlmunit.testminlm().
static void alglib.minlm.minlmcreatevgj (int n, int m, double[] x, minlmstate state) inline static
Referenced by alglib.minlmcreatevgj().
static void alglib.minlm.minlmcreatefgj (int n, int m, double[] x, minlmstate state) inline static
Referenced by alglib.minlmcreatefgj(), and alglib.testminlmunit.testminlm().
static void alglib.minlm.minlmcreatefj (int n, int m, double[] x, minlmstate state) inline static
Referenced by alglib.minlmcreatefj(), and alglib.testminlmunit.testminlm().
static void alglib.minlm.minlmsetgradientcheck (minlmstate state, double teststep) inline static
Referenced by alglib.testminlmunit.gradientchecktest(), and alglib.minlmsetgradientcheck().
static void alglib.minlm.lmprepare (int n, int m, bool havegrad, minlmstate state) inline static private
static void alglib.minlm.clearrequestfields (minlmstate state) inline static private
static bool alglib.minlm.increaselambda (ref double lambdav, ref double nu) inline static private
static void alglib.minlm.decreaselambda (ref double lambdav, ref double nu) inline static private
static double alglib.minlm.boundedscaledantigradnorm (minlmstate state, double[] x, double[] g) inline static private
static void alglib.minlm.minlmcreatevj (int n, int m, double[] x, minlmstate state) inline static
static void alglib.minlm.minlmcreatev (int n, int m, double[] x, double diffstep, minlmstate state) inline static
static void alglib.minlm.minlmcreatefgh (int n, double[] x, minlmstate state) inline static
static void alglib.minlm.minlmsetcond (minlmstate state, double epsg, double epsf, double epsx, int maxits) inline static
static void alglib.minlm.minlmsetxrep (minlmstate state, bool needxrep) inline static
static void alglib.minlm.minlmsetstpmax (minlmstate state, double stpmax) inline static
static void alglib.minlm.minlmsetscale (minlmstate state, double[] s) inline static
static void alglib.minlm.minlmsetbc (minlmstate state, double[] bndl, double[] bndu) inline static
static void alglib.minlm.minlmsetacctype (minlmstate state, int acctype) inline static
static bool alglib.minlm.minlmiteration (minlmstate state) inline static
static void alglib.minlm.minlmresults (minlmstate state, ref double[] x, minlmreport rep) inline static
static void alglib.minlm.minlmresultsbuf (minlmstate state, ref double[] x, minlmreport rep) inline static
static void alglib.minlm.minlmrestartfrom (minlmstate state, double[] x) inline static
static void alglib.minlm.minlmcreatevgj (int n, int m, double[] x, minlmstate state) inline static
static void alglib.minlm.minlmcreatefgj (int n, int m, double[] x, minlmstate state) inline static
static void alglib.minlm.minlmcreatefj (int n, int m, double[] x, minlmstate state) inline static
static void alglib.minlm.minlmsetgradientcheck (minlmstate state, double teststep) inline static
static void alglib.minlm.lmprepare (int n, int m, bool havegrad, minlmstate state) inline static private
static void alglib.minlm.clearrequestfields (minlmstate state) inline static private
static bool alglib.minlm.increaselambda (ref double lambdav, ref double nu) inline static private
static void alglib.minlm.decreaselambda (ref double lambdav, ref double nu) inline static private
static double alglib.minlm.boundedscaledantigradnorm (minlmstate state, double[] x, double[] g) inline static private
Member Data Documentation
const int alglib.minlm.lmmodefj = 0
const int alglib.minlm.lmmodefgj = 1
const int alglib.minlm.lmmodefgh = 2
const int alglib.minlm.lmflagnoprelbfgs = 1
const int alglib.minlm.lmflagnointlbfgs = 2
const int alglib.minlm.lmprelbfgsm = 5
const int alglib.minlm.lmintlbfgsits = 5
const int alglib.minlm.lbfgsnorealloc = 1
const double alglib.minlm.lambdaup = 2.0
const double alglib.minlm.lambdadown = 0.33
const double alglib.minlm.suspiciousnu = 16
const int alglib.minlm.smallmodelage = 3
const int alglib.minlm.additers = 5
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/optimization.cs