IGLib: Itaia.ProgramItaia Class Reference
Itaia.ProgramItaia Class Reference
Static Public Member Functions
static void SleepWithNotice (double sleepTime, string location)
Static Public Attributes
static string[] Arguments
Here program arguments are stored.
Static Private Member Functions
static void Main (string[] args)
static void MainThread (string[] args)
static void WorkingThread ()
Thread routine for time consuming tasks.
Member Function Documentation
static void Itaia.ProgramItaia.Main (string[] args) inline static private
References Itaia.AppItaia.Init(), and Itaia.ProgramItaia.MainThread().
static void Itaia.ProgramItaia.MainThread (string[] args) inline static private
References Itaia.ProgramItaia.Arguments, IG.Forms.GraphBase.Example(), Itaia.ProgramItaia.SleepWithNotice(), and Itaia.ProgramItaia.WorkingThread().
Referenced by Itaia.ProgramItaia.Main().
static void Itaia.ProgramItaia.WorkingThread () inline static private
Thread routine for time consuming tasks.
References Itaia.ProgramItaia.SleepWithNotice().
Referenced by Itaia.ProgramItaia.MainThread().
static void Itaia.ProgramItaia.SleepWithNotice (double sleepTime, string location) inline static
Referenced by Itaia.ProgramItaia.MainThread(), and Itaia.ProgramItaia.WorkingThread().
Member Data Documentation
string [] Itaia.ProgramItaia.Arguments static
Here program arguments are stored.
Referenced by Itaia.ProgramItaia.MainThread().
The documentation for this class was generated from the following file:
igapp/itaia/appitaia/ProgramItaia.cs