IGLib: NUnit.Framework.Internal.SetUpFixtureTests Class Reference
NUnit.Framework.Internal.SetUpFixtureTests Class Reference
Public Member Functions
void SetUp ()
void NamespaceSetUpFixtureReplacesNamespaceNodeInTree ()
Tests that the TestSuiteBuilder correctly interperets a SetupFixture class as a 'virtual namespace' into which all it's sibling classes are inserted.
void AssemblySetUpFixtureReplacesAssemblyNodeInTree ()
Tests that the TestSuiteBuilder correctly interperets a SetupFixture class with no parent namespace as a 'virtual assembly' into which all it's sibling fixtures are inserted.
void InvalidAssemblySetUpFixtureIsLoadedCorrectly ()
void NamespaceSetUpFixtureWrapsExecutionOfSingleTest ()
void NamespaceSetUpMethodsMayBeStatic ()
void NamespaceSetUpFixtureWrapsExecutionOfTwoTests ()
void NamespaceSetUpFixtureWrapsNestedNamespaceSetUpFixture ()
void WithTwoSetUpFixturesBothAreUsed ()
void InvalidSetUpFixtureTest ()
void AssemblySetupFixtureWrapsExecutionOfTest ()
Private Member Functions
ITestResult runTests (string nameSpace)
ITestResult runTests (string nameSpace, TestFilter filter)
Private Attributes
ITestAssemblyBuilder builder
ITestAssemblyRunner runner
Static Private Attributes
static readonly string testAssembly = AssemblyHelper.GetAssemblyPath(typeof(NUnit.TestData.SetupFixture.Namespace1.SomeFixture))
Member Function Documentation
void NUnit.Framework.Internal.SetUpFixtureTests.SetUp () inline
ITestResult NUnit.Framework.Internal.SetUpFixtureTests.runTests (string nameSpace) inline private
ITestResult NUnit.Framework.Internal.SetUpFixtureTests.runTests (string nameSpace, TestFilter filter) inline private
References NUnit.Framework.Api.ITestAssemblyRunner.Load(), and NUnit.Framework.Api.ITestAssemblyRunner.Run().
void NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureReplacesNamespaceNodeInTree () inline
Tests that the TestSuiteBuilder correctly interperets a SetupFixture class as a 'virtual namespace' into which all it's sibling classes are inserted.
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Api.ITestAssemblyBuilder.Build(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ITest.FullName, NUnit.Framework.Is.InstanceOf(), NUnit.Framework.Assert.IsNotNull(), NUnit.Framework.Interfaces.ITest.Name, NUnit.Framework.Interfaces.ITest.RunState, NUnit.Framework.Interfaces.ITest.Tests, and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.SetUpFixtureTests.AssemblySetUpFixtureReplacesAssemblyNodeInTree () inline
Tests that the TestSuiteBuilder correctly interperets a SetupFixture class with no parent namespace as a 'virtual assembly' into which all it's sibling fixtures are inserted.
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Api.ITestAssemblyBuilder.Build(), NUnit.Framework.Is.InstanceOf(), NUnit.Framework.Assert.IsNotNull(), NUnit.Framework.Interfaces.ITest.Name, NUnit.Framework.Interfaces.ITest.Tests, and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.SetUpFixtureTests.InvalidAssemblySetUpFixtureIsLoadedCorrectly () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Api.ITestAssemblyBuilder.Build(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ITest.FullName, NUnit.Framework.Assert.IsNotNull(), NUnit.Framework.Interfaces.ITest.Name, NUnit.Framework.Interfaces.ITest.RunState, NUnit.Framework.Interfaces.ITest.Tests, and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureWrapsExecutionOfSingleTest () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Status, and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpMethodsMayBeStatic () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Status, and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureWrapsExecutionOfTwoTests () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Status, and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureWrapsNestedNamespaceSetUpFixture () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Status, and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.SetUpFixtureTests.WithTwoSetUpFixturesBothAreUsed () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Status, and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.SetUpFixtureTests.InvalidSetUpFixtureTest () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Status, and NUnit.Framework.Assert.That().
void NUnit.Framework.Internal.SetUpFixtureTests.AssemblySetupFixtureWrapsExecutionOfTest () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ITestResult.PassCount, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Interfaces.ResultState.Status, and NUnit.Framework.Assert.That().
Member Data Documentation
readonly string NUnit.Framework.Internal.SetUpFixtureTests.testAssembly = AssemblyHelper.GetAssemblyPath(typeof(NUnit.TestData.SetupFixture.Namespace1.SomeFixture)) static private
ITestAssemblyBuilder NUnit.Framework.Internal.SetUpFixtureTests.builder private
ITestAssemblyRunner NUnit.Framework.Internal.SetUpFixtureTests.runner private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/SetUpFixtureTests.cs