IGLib: Meta.Numerics.Statistics.Distributions.LognormalDistribution Class Reference
Meta.Numerics.Statistics.Distributions.LognormalDistribution Class Reference
Represents a log-normal distribution.
Public Member Functions
LognormalDistribution (double mu, double sigma)
Initializes a log-normal distribution.
LognormalDistribution ()
Initializes a standard log-normal distribution.
override double ProbabilityDensity (double x)
Returns the probability density at the given point.
Parameters
x The reference point.
Returns
The probability density p(x).
The probability density function (PDF) gives the relative probability of obtaining different values.
override double LeftProbability (double x)
Returns the cumulative probability to the left of (below) the given point.
Parameters
x The reference point.
Returns
The integrated probability to obtain a result below the reference point.
The left probability function is commonly called the cumulative distribution function (CDF).
override double RightProbability (double x)
Return the cumulative probability to the right of (above) the given point.
Parameters
x The reference point.
Returns
The integrated probability 1-P(x1) to obtain a result above the reference point.
In survival analysis, the right probability function is commonly called the survival function, because it gives the fraction of the population remaining after the given time.
override double InverseLeftProbability (double P)
Returns the point at which the cumulative distribution function attains a given value.
Parameters
P The left cumulative probability P, which must lie between 0 and 1.
Returns
The value x at which LeftProbability equals P.
The inverse left probability is commonly called the quantile function. Given a quantile, it tells which variable value is the lower border of that quantile.
override double InverseRightProbability (double Q)
Returns the point at which the right probability function attains the given value.
Parameters
Q The right cumulative probability, which must lie between 0 and 1.
Returns
The value x for which RightProbability equals Q.
override double GetRandomValue (Random rng)
Returns a random value.
Parameters
rng A random number generator.
Returns
A number distributed according to the distribution.
Note that the random number generator rng will be advanced by this method. The next call to its generator methods will not give the same value as it would had it not been passed to this method.
override double Moment (int n)
Computes a raw moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth raw moment of the distribution.
See also
Moment
override double MomentAboutMean (int n)
Computes a central moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth central moment of the distribution.
See also
Moment
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double ExpectationValue (Func< double, double > f)
Computes the expectation value of the given function.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Cumulant (int r)
Computes a cumulant of the distribution.
Static Public Member Functions
static FitResult FitToSample (Sample sample)
Computes the log-normal distribution that best fits the given sample.
Properties
double Mu [get]
Gets the value of the &#x3BC; parameter.
double Sigma [get]
Gets the value of the &#x3C3; parameter.
override double Mean [get]
override double Median [get]
override double Variance [get]
override double Skewness [get]
override double ExcessKurtosis [get]
override Interval Support [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double Median [get]
Gets the median of the distribution.
virtual Interval Support [get]
Gets the interval over which the distribution is nonvanishing.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Private Member Functions
double[]
IParameterizedDistribution. GetParameters ()
Gets the parameter values of the distribution.
void IParameterizedDistribution. SetParameters (IList< double > parameters)
Sets the parameter values of the distribution.
double IParameterizedDistribution. Likelihood (double x)
Gets the likelihood of a value, given the current parameters.
Private Attributes
double mu = 0.0
double sigma = 1.0
NormalDistribution normal
Detailed Description
Represents a log-normal distribution.
The logrithm of a log-normal distributed variable is distributed normally.
The log-normal distribution is commonly used in financial engineering as a model of stock prices. If the rate of return on an asset is distributed normally, then its price will be distributed log-normally.
See also
NormalDistribution
Constructor & Destructor Documentation
Meta.Numerics.Statistics.Distributions.LognormalDistribution.LognormalDistribution (double mu, double sigma) inline
Initializes a log-normal distribution.
Parameters
mu The mean of the underlying normal distribution.
sigma The standard deviation of the underlying normal distribution.
Note that the values of &#x3BC; and &#x3C3; parameters are not the mean and standard deviation of the log-normal distribution. They are the mean and standard deviation of their logrithms z = ln x. This is the standard method of characterizing a log-normal distribution.
Meta.Numerics.Statistics.Distributions.LognormalDistribution.LognormalDistribution () inline
Initializes a standard log-normal distribution.
A standard log-normal distribution has &#x3BC; = 0 and &#x3C3; = 1. It is the log transform of the standard normal distribution.
Member Function Documentation
override double Meta.Numerics.Statistics.Distributions.LognormalDistribution.ProbabilityDensity (double x) inline virtual
Returns the probability density at the given point.
Parameters
x The reference point.
Returns
The probability density p(x).
The probability density function (PDF) gives the relative probability of obtaining different values.
Implements Meta.Numerics.Statistics.Distributions.Distribution.
override double Meta.Numerics.Statistics.Distributions.LognormalDistribution.LeftProbability (double x) inline virtual
Returns the cumulative probability to the left of (below) the given point.
Parameters
x The reference point.
Returns
The integrated probability to obtain a result below the reference point.
The left probability function is commonly called the cumulative distribution function (CDF).
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.LeftProbability().
override double Meta.Numerics.Statistics.Distributions.LognormalDistribution.RightProbability (double x) inline virtual
Return the cumulative probability to the right of (above) the given point.
Parameters
x The reference point.
Returns
The integrated probability 1-P(x1) to obtain a result above the reference point.
In survival analysis, the right probability function is commonly called the survival function, because it gives the fraction of the population remaining after the given time.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.RightProbability().
override double Meta.Numerics.Statistics.Distributions.LognormalDistribution.InverseLeftProbability (double P) inline virtual
Returns the point at which the cumulative distribution function attains a given value.
Parameters
P The left cumulative probability P, which must lie between 0 and 1.
Returns
The value x at which LeftProbability equals P.
The inverse left probability is commonly called the quantile function. Given a quantile, it tells which variable value is the lower border of that quantile.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.InverseLeftProbability().
override double Meta.Numerics.Statistics.Distributions.LognormalDistribution.InverseRightProbability (double Q) inline virtual
Returns the point at which the right probability function attains the given value.
Parameters
Q The right cumulative probability, which must lie between 0 and 1.
Returns
The value x for which RightProbability equals Q.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.InverseRightProbability().
override double Meta.Numerics.Statistics.Distributions.LognormalDistribution.GetRandomValue (Random rng) inline virtual
Returns a random value.
Parameters
rng A random number generator.
Returns
A number distributed according to the distribution.
Note that the random number generator rng will be advanced by this method. The next call to its generator methods will not give the same value as it would had it not been passed to this method.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.GetRandomValue().
override double Meta.Numerics.Statistics.Distributions.LognormalDistribution.Moment (int n) inline virtual
Computes a raw moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth raw moment of the distribution.
See also
Moment
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.MoreMath.Sqr().
override double Meta.Numerics.Statistics.Distributions.LognormalDistribution.MomentAboutMean (int n) inline virtual
Computes a central moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth central moment of the distribution.
See also
Moment
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient(), and Meta.Numerics.MoreMath.Sqr().
static FitResult Meta.Numerics.Statistics.Distributions.LognormalDistribution.FitToSample (Sample sample) inline static
Computes the log-normal distribution that best fits the given sample.
Parameters
sample The sample to fit.
Returns
The best fit parameters.
The returned fit parameters are the &#x3BC; (Mu) and &#x3C3; (Sigma) parameters, in that order. These are the same parameters, in the same order, that are required by the LognormalDistribution(double,double) constructor to specify a new log-normal distribution.
Exceptions
ArgumentNullException sample is null.
InsufficientDataException sample contains fewer than three values.
InvalidOperationException sample contains non-positive values.
References Meta.Numerics.Statistics.Sample.Count.
Referenced by Test.SampleTest.LognormalFit().
double [] IParameterizedDistribution. Meta.Numerics.Statistics.Distributions.LognormalDistribution.GetParameters () inline private
Gets the parameter values of the distribution.
Returns
The parameter values characterizing the distribution.
Implements Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.
void IParameterizedDistribution. Meta.Numerics.Statistics.Distributions.LognormalDistribution.SetParameters (IList< double > parameters) inline private
Sets the parameter values of the distribution.
Parameters
parameters A list of parameter values.
Implements Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.
double IParameterizedDistribution. Meta.Numerics.Statistics.Distributions.LognormalDistribution.Likelihood (double x) inline private
Gets the likelihood of a value, given the current parameters.
Parameters
x The value.
Returns
The likelihood of the value.
Implements Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.
Member Data Documentation
double Meta.Numerics.Statistics.Distributions.LognormalDistribution.mu = 0.0 private
double Meta.Numerics.Statistics.Distributions.LognormalDistribution.sigma = 1.0 private
NormalDistribution Meta.Numerics.Statistics.Distributions.LognormalDistribution.normal private
Property Documentation
double Meta.Numerics.Statistics.Distributions.LognormalDistribution.Mu get
Gets the value of the &#x3BC; parameter.
Note that the value of this parameter is not the mean of the distribution. It is the value given to the distribution constructor (LognormalDistribution(double,double)), which is the mean of the underlying normal distribution.
Referenced by Test.SampleTest.LognormalFit().
double Meta.Numerics.Statistics.Distributions.LognormalDistribution.Sigma get
Gets the value of the &#x3C3; parameter.
Note that the value of this parameter is not the standard deviation of the distribution. It is the value given to the distribution constructor (LognormalDistribution(double,double)), which is the sandard deviation of the underlying normal distribution.
Referenced by Test.SampleTest.LognormalFit().
override double Meta.Numerics.Statistics.Distributions.LognormalDistribution.Mean get
override double Meta.Numerics.Statistics.Distributions.LognormalDistribution.Median get
override double Meta.Numerics.Statistics.Distributions.LognormalDistribution.Variance get
override double Meta.Numerics.Statistics.Distributions.LognormalDistribution.Skewness get
override double Meta.Numerics.Statistics.Distributions.LognormalDistribution.ExcessKurtosis get
override Interval Meta.Numerics.Statistics.Distributions.LognormalDistribution.Support get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/LognormalDistribution.cs