IGLib: alglib.testmatgenunit Class Reference
alglib.testmatgenunit Class Reference
Static Public Member Functions
static bool testmatgen (bool silent)
static bool testmatgen (bool silent)
static bool _pexec_testmatgen (bool silent)
Public Attributes
const int maxsvditerations = 60
Static Private Member Functions
static void unset2d (ref double[,] a)
static void unset2dc (ref complex[,] a)
static bool isspd (double[,] a, int n, bool isupper)
static bool ishpd (complex[,] a, int n)
static bool testeult ()
static double svdcond (double[,] a, int n)
static bool obsoletesvddecomposition (ref double[,] a, int m, int n, ref double[] w, ref double[,] v)
static double extsign (double a, double b)
static double mymax (double a, double b)
static double pythag (double a, double b)
static void unset2d (ref double[,] a)
static void unset2dc (ref complex[,] a)
static bool isspd (double[,] a, int n, bool isupper)
static bool ishpd (complex[,] a, int n)
static bool testeult ()
static double svdcond (double[,] a, int n)
static bool obsoletesvddecomposition (ref double[,] a, int m, int n, ref double[] w, ref double[,] v)
static double extsign (double a, double b)
static double mymax (double a, double b)
static double pythag (double a, double b)
Member Function Documentation
static bool alglib.testmatgenunit.testmatgen (bool silent) inline static
References alglib.math.abscomplex(), alglib.matgen.cmatrixrndorthogonal(), alglib.matgen.cmatrixrndorthogonalfromtheleft(), alglib.matgen.cmatrixrndorthogonalfromtheright(), alglib.math.conj(), alglib.matgen.hmatrixrndcond(), alglib.matgen.hpdmatrixrndcond(), alglib.testmatgenunit.ishpd(), alglib.testmatgenunit.isspd(), alglib.math.machineepsilon, alglib.testmatgenunit.obsoletesvddecomposition(), alglib.math.randomreal(), alglib.matgen.rmatrixrndcond(), alglib.matgen.rmatrixrndorthogonal(), alglib.matgen.rmatrixrndorthogonalfromtheleft(), alglib.matgen.rmatrixrndorthogonalfromtheright(), alglib.matgen.smatrixrndcond(), alglib.matgen.spdmatrixrndcond(), alglib.testmatgenunit.svdcond(), alglib.testmatgenunit.testeult(), alglib.testmatgenunit.unset2d(), and alglib.testmatgenunit.unset2dc().
Referenced by alglib.testmatgenunit._pexec_testmatgen(), and _Test.Main().
static void alglib.testmatgenunit.unset2d (ref double a[,]) inline static private
References alglib.math.randomreal().
Referenced by alglib.testmatgenunit.testmatgen().
static void alglib.testmatgenunit.unset2dc (ref complex a[,]) inline static private
References alglib.math.randomreal().
Referenced by alglib.testmatgenunit.testmatgen().
static bool alglib.testmatgenunit.isspd (double a[,], int n, bool isupper) inline static private
References alglib.ap.assert().
Referenced by alglib.testmatgenunit.testmatgen().
static bool alglib.testmatgenunit.ishpd (complex a[,], int n) inline static private
References alglib.math.conj().
Referenced by alglib.testmatgenunit.testmatgen().
static bool alglib.testmatgenunit.testeult () inline static private
References alglib.matgen.hmatrixrndcond(), alglib.matgen.hmatrixrndmultiply(), alglib.matgen.hpdmatrixrndcond(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.matgen.smatrixrndcond(), alglib.matgen.smatrixrndmultiply(), and alglib.matgen.spdmatrixrndcond().
Referenced by alglib.testmatgenunit.testmatgen().
static double alglib.testmatgenunit.svdcond (double a[,], int n) inline static private
References alglib.testmatgenunit.obsoletesvddecomposition().
Referenced by alglib.testmatgenunit.testmatgen().
static bool alglib.testmatgenunit.obsoletesvddecomposition (ref double a[,], int m, int n, ref double[] w, ref double v[,]) inline static private
References alglib.testmatgenunit.extsign(), alglib.testmatgenunit.maxsvditerations, alglib.testmatgenunit.mymax(), and alglib.testmatgenunit.pythag().
Referenced by alglib.testmatgenunit.svdcond(), and alglib.testmatgenunit.testmatgen().
static double alglib.testmatgenunit.extsign (double a, double b) inline static private
Referenced by alglib.testmatgenunit.obsoletesvddecomposition().
static double alglib.testmatgenunit.mymax (double a, double b) inline static private
Referenced by alglib.testmatgenunit.obsoletesvddecomposition().
static double alglib.testmatgenunit.pythag (double a, double b) inline static private
References alglib.math.sqr().
Referenced by alglib.testmatgenunit.obsoletesvddecomposition().
static bool alglib.testmatgenunit.testmatgen (bool silent) inline static
References alglib.math.abscomplex(), alglib.matgen.cmatrixrndorthogonal(), alglib.matgen.cmatrixrndorthogonalfromtheleft(), alglib.matgen.cmatrixrndorthogonalfromtheright(), alglib.math.conj(), alglib.matgen.hmatrixrndcond(), alglib.matgen.hpdmatrixrndcond(), alglib.testmatgenunit.ishpd(), alglib.testmatgenunit.isspd(), alglib.math.machineepsilon, alglib.testmatgenunit.obsoletesvddecomposition(), alglib.math.randomreal(), alglib.matgen.rmatrixrndcond(), alglib.matgen.rmatrixrndorthogonal(), alglib.matgen.rmatrixrndorthogonalfromtheleft(), alglib.matgen.rmatrixrndorthogonalfromtheright(), alglib.matgen.smatrixrndcond(), alglib.matgen.spdmatrixrndcond(), alglib.testmatgenunit.svdcond(), alglib.testmatgenunit.testeult(), alglib.testmatgenunit.unset2d(), and alglib.testmatgenunit.unset2dc().
static bool alglib.testmatgenunit._pexec_testmatgen (bool silent) inline static
References alglib.testmatgenunit.testmatgen().
Referenced by _Test.Main().
static void alglib.testmatgenunit.unset2d (ref double a[,]) inline static private
References alglib.math.randomreal().
static void alglib.testmatgenunit.unset2dc (ref complex a[,]) inline static private
References alglib.math.randomreal().
static bool alglib.testmatgenunit.isspd (double a[,], int n, bool isupper) inline static private
References alglib.ap.assert().
static bool alglib.testmatgenunit.ishpd (complex a[,], int n) inline static private
References alglib.math.conj().
static bool alglib.testmatgenunit.testeult () inline static private
References alglib.matgen.hmatrixrndcond(), alglib.matgen.hmatrixrndmultiply(), alglib.matgen.hpdmatrixrndcond(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.matgen.smatrixrndcond(), alglib.matgen.smatrixrndmultiply(), and alglib.matgen.spdmatrixrndcond().
static double alglib.testmatgenunit.svdcond (double a[,], int n) inline static private
References alglib.testmatgenunit.obsoletesvddecomposition().
static bool alglib.testmatgenunit.obsoletesvddecomposition (ref double a[,], int m, int n, ref double[] w, ref double v[,]) inline static private
References alglib.testmatgenunit.extsign(), alglib.testmatgenunit.maxsvditerations, alglib.testmatgenunit.mymax(), and alglib.testmatgenunit.pythag().
static double alglib.testmatgenunit.extsign (double a, double b) inline static private
static double alglib.testmatgenunit.mymax (double a, double b) inline static private
static double alglib.testmatgenunit.pythag (double a, double b) inline static private
References alglib.math.sqr().
Member Data Documentation
const int alglib.testmatgenunit.maxsvditerations = 60
Referenced by alglib.testmatgenunit.obsoletesvddecomposition().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs