IGLib: NUnit.Framework.Internal.Execution.SimpleWorkItem Class Reference
NUnit.Framework.Internal.Execution.SimpleWorkItem Class Reference
A SimpleWorkItem represents a single test case and is marked as completed immediately upon execution. This class is also used for skipped or ignored test suites.
Public Member Functions
SimpleWorkItem (TestMethod test, ITestFilter filter)
Construct a simple work item for a test.
Public Member Functions inherited from NUnit.Framework.Internal.Execution.WorkItem
WorkItem (Test test)
Construct a WorkItem for a particular test.
void InitializeContext (TestExecutionContext context)
Initialize the TestExecutionContext. This must be done before executing the WorkItem.
virtual void Execute ()
Execute the current work item, including any child work items.
Protected Member Functions
override void PerformWork ()
Method that performs actually performs the work.
Protected Member Functions inherited from NUnit.Framework.Internal.Execution.WorkItem
void WorkItemComplete ()
Method called by the derived class when all work is complete
Private Attributes
TestCommand _command
Additional Inherited Members
Static Public Member Functions inherited from NUnit.Framework.Internal.Execution.WorkItem
static WorkItem CreateWorkItem (ITest test, ITestFilter filter)
Creates a work item.
Properties inherited from NUnit.Framework.Internal.Execution.WorkItem
WorkItemState State [get]
Gets the current state of the WorkItem
Test Test [get]
The test being executed by the work item
TestExecutionContext Context [get]
The execution context
List< ITestAction > Actions [get]
The test actions to be performed before and after this test
TestResult Result [get, protected set]
The test result
Events inherited from NUnit.Framework.Internal.Execution.WorkItem
EventHandler Completed
Event triggered when the item is complete
Detailed Description
A SimpleWorkItem represents a single test case and is marked as completed immediately upon execution. This class is also used for skipped or ignored test suites.
Constructor & Destructor Documentation
NUnit.Framework.Internal.Execution.SimpleWorkItem.SimpleWorkItem (TestMethod test, ITestFilter filter) inline
Construct a simple work item for a test.
Parameters
test The test to be executed
filter The filter used to select this test
References NUnit.Framework.Interfaces.ITestFilter.IsExplicitMatch(), NUnit.Framework.Internal.Execution.CommandBuilder.MakeSkipCommand(), NUnit.Framework.Internal.Execution.CommandBuilder.MakeTestCommand(), and NUnit.Framework.Internal.Test.RunState.
Member Function Documentation
override void NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork () inline protected virtual
Method that performs actually performs the work.
Implements NUnit.Framework.Internal.Execution.WorkItem.
References NUnit.Framework.Internal.Commands.TestCommand.Execute().
Member Data Documentation
TestCommand NUnit.Framework.Internal.Execution.SimpleWorkItem._command private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Execution/SimpleWorkItem.cs