IGLib: NUnit.Framework.Attributes.TimeoutTests Class Reference
NUnit.Framework.Attributes.TimeoutTests Class Reference
Public Member Functions
void GetParentThreadInfo ()
void GetSetUpThreadInfo ()
void TestWithTimeoutRunsOnSeparateThread ()
void TestWithTimeoutRunsSetUpAndTestOnSameThread ()
void TestTimesOutAndTearDownIsRun ()
void SetUpTimesOutAndTearDownIsRun ()
void TimeoutCanBeSetOnTestFixture ()
void TestTimeOutNotElapsed ()
void TestTimeOutElapsed ()
void TestTimeOutTestCaseWithOutElapsed ()
Private Attributes
Thread parentThread
Thread setupThread
Member Function Documentation
void NUnit.Framework.Attributes.TimeoutTests.GetParentThreadInfo () inline
void NUnit.Framework.Attributes.TimeoutTests.GetSetUpThreadInfo () inline
void NUnit.Framework.Attributes.TimeoutTests.TestWithTimeoutRunsOnSeparateThread () inline
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.TimeoutTests.TestWithTimeoutRunsSetUpAndTestOnSameThread () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.TimeoutTests.TestTimesOutAndTearDownIsRun () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.TestUtilities.TestFinder.Find(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTest(), NUnit.TestData.TimeoutFixture.TearDownWasRun, and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.TimeoutTests.SetUpTimesOutAndTearDownIsRun () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.TestUtilities.TestFinder.Find(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTest(), NUnit.TestData.TimeoutFixture.TearDownWasRun, and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.TimeoutTests.TimeoutCanBeSetOnTestFixture () inline
References NUnit.Framework.Interfaces.ResultState.ChildFailure, NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.TestUtilities.TestFinder.Find(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.Framework.Interfaces.ResultState.Site, and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.TimeoutTests.TestTimeOutNotElapsed () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestFinder.Find(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTest(), NUnit.Framework.Interfaces.ResultState.Success, and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.TimeoutTests.TestTimeOutElapsed () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.TestUtilities.TestFinder.Find(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTest(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.TimeoutTests.TestTimeOutTestCaseWithOutElapsed () inline
References NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.TestUtilities.TestFinder.Find(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTest(), NUnit.Framework.Interfaces.ResultState.Success, and NUnit.Framework.Assert.That().
Member Data Documentation
Thread NUnit.Framework.Attributes.TimeoutTests.parentThread private
Thread NUnit.Framework.Attributes.TimeoutTests.setupThread private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/TimeoutTests.cs