IGLib: IG.Test.EncDec Class Reference
IG.Test.EncDec Class Reference
Static Public Member Functions
static byte[] Encrypt (byte[] clearData, byte[] key, byte[] IV, SymmetricAlgorithm alg=null)
static byte[] EncryptString (string clearText, byte[] Key, byte[] IV, SymmetricAlgorithm alg=null)
static string DecryptString (byte[] encryptedBytes, byte[] Key, byte[] IV, SymmetricAlgorithm alg=null)
static string Encrypt (string clearText, string Password, SymmetricAlgorithm alg=null)
static byte[] Encrypt (byte[] clearData, string Password, SymmetricAlgorithm alg=null)
static void Encrypt (string fileIn, string fileOut, string Password, SymmetricAlgorithm alg=null)
static byte[] Decrypt (byte[] cipherData, byte[] key, byte[] IV, SymmetricAlgorithm alg)
static string Decrypt (string cipherText, string Password, SymmetricAlgorithm alg=null)
static byte[] Decrypt (byte[] cipherData, string Password, SymmetricAlgorithm alg=null)
static void Decrypt (string fileIn, string fileOut, string Password, SymmetricAlgorithm alg=null)
static byte[] Encrypt (byte[] clearData, byte[] key, byte[] IV, SymmetricAlgorithm alg=null)
static byte[] EncryptString (string clearText, byte[] Key, byte[] IV, SymmetricAlgorithm alg=null)
static string DecryptString (byte[] encryptedBytes, byte[] Key, byte[] IV, SymmetricAlgorithm alg=null)
static string Encrypt (string clearText, string Password, SymmetricAlgorithm alg=null)
static byte[] Encrypt (byte[] clearData, string Password, SymmetricAlgorithm alg=null)
static void Encrypt (string fileIn, string fileOut, string Password, SymmetricAlgorithm alg=null)
static byte[] Decrypt (byte[] cipherData, byte[] key, byte[] IV, SymmetricAlgorithm alg)
static string Decrypt (string cipherText, string Password, SymmetricAlgorithm alg=null)
static byte[] Decrypt (byte[] cipherData, string Password, SymmetricAlgorithm alg=null)
static void Decrypt (string fileIn, string fileOut, string Password, SymmetricAlgorithm alg=null)
Member Function Documentation
static byte [] IG.Test.EncDec.Encrypt (byte[] clearData, byte[] key, byte[] IV, SymmetricAlgorithm alg = null) inline static
References IG.Crypto.UtilCrypto.PrepareSymmetricAllgorithmPlain(), and IG.Crypto.Rijndael.
static byte [] IG.Test.EncDec.EncryptString (string clearText, byte[] Key, byte[] IV, SymmetricAlgorithm alg = null) inline static
Referenced by IG.Test.TestCrypto.Test_EncryptStringTobytes_DecryptStringFromBytes().
static string IG.Test.EncDec.DecryptString (byte[] encryptedBytes, byte[] Key, byte[] IV, SymmetricAlgorithm alg = null) inline static
Referenced by IG.Test.TestCrypto.Test_EncryptStringTobytes_DecryptStringFromBytes().
static string IG.Test.EncDec.Encrypt (string clearText, string Password, SymmetricAlgorithm alg = null) inline static
static byte [] IG.Test.EncDec.Encrypt (byte[] clearData, string Password, SymmetricAlgorithm alg = null) inline static
static void IG.Test.EncDec.Encrypt (string fileIn, string fileOut, string Password, SymmetricAlgorithm alg = null) inline static
References IG.Crypto.Rijndael.
static byte [] IG.Test.EncDec.Decrypt (byte[] cipherData, byte[] key, byte[] IV, SymmetricAlgorithm alg) inline static
References IG.Crypto.UtilCrypto.PrepareSymmetricAllgorithmPlain(), and IG.Crypto.Rijndael.
static string IG.Test.EncDec.Decrypt (string cipherText, string Password, SymmetricAlgorithm alg = null) inline static
static byte [] IG.Test.EncDec.Decrypt (byte[] cipherData, string Password, SymmetricAlgorithm alg = null) inline static
static void IG.Test.EncDec.Decrypt (string fileIn, string fileOut, string Password, SymmetricAlgorithm alg = null) inline static
References IG.Crypto.Rijndael.
static byte [] IG.Test.EncDec.Encrypt (byte[] clearData, byte[] key, byte[] IV, SymmetricAlgorithm alg = null) inline static
References IG.Crypto.UtilCrypto.PrepareSymmetricAllgorithmPlain(), and IG.Crypto.Rijndael.
static byte [] IG.Test.EncDec.EncryptString (string clearText, byte[] Key, byte[] IV, SymmetricAlgorithm alg = null) inline static
static string IG.Test.EncDec.DecryptString (byte[] encryptedBytes, byte[] Key, byte[] IV, SymmetricAlgorithm alg = null) inline static
static string IG.Test.EncDec.Encrypt (string clearText, string Password, SymmetricAlgorithm alg = null) inline static
static byte [] IG.Test.EncDec.Encrypt (byte[] clearData, string Password, SymmetricAlgorithm alg = null) inline static
static void IG.Test.EncDec.Encrypt (string fileIn, string fileOut, string Password, SymmetricAlgorithm alg = null) inline static
References IG.Crypto.Rijndael.
static byte [] IG.Test.EncDec.Decrypt (byte[] cipherData, byte[] key, byte[] IV, SymmetricAlgorithm alg) inline static
References IG.Crypto.UtilCrypto.PrepareSymmetricAllgorithmPlain(), and IG.Crypto.Rijndael.
static string IG.Test.EncDec.Decrypt (string cipherText, string Password, SymmetricAlgorithm alg = null) inline static
static byte [] IG.Test.EncDec.Decrypt (byte[] cipherData, string Password, SymmetricAlgorithm alg = null) inline static
static void IG.Test.EncDec.Decrypt (string fileIn, string fileOut, string Password, SymmetricAlgorithm alg = null) inline static
References IG.Crypto.Rijndael.
The documentation for this class was generated from the following file:
unittests/MSTests/TestUtil/TstCrypto.cs