IGLib: Meta.Numerics.Analysis.MultiFunctionMath Class Reference
Meta.Numerics.Analysis.MultiFunctionMath Class Reference
Contains methods for the analysis of multi-dimensional functions.
Static Public Member Functions
static MultiExtremum FindGlobalMinimum (Func< IList< double >, double > function, IList< Interval > volume)
static MultiExtremum FindGlobalMinimum (Func< IList< double >, double > function, IList< Interval > volume, EvaluationSettings settings)
static MultiExtremum FindGlobalMaximum (Func< IList< double >, double > function, IList< Interval > volume)
static MultiExtremum FindGlobalMaximum (Func< IList< double >, double > function, IList< Interval > volume, EvaluationSettings settings)
static MultiExtremum FindMinimum (Func< IList< double >, double > function, IList< double > start)
Finds a local minimum of a multi-dimensional function in the vincinity of the given starting location.
static MultiExtremum FindMinimum (Func< IList< double >, double > function, IList< double > start, EvaluationSettings settings)
Finds a local minimum of a multi-dimensional function in the vincinity of the given starting location, subject to the given evaluation constraints.
static MultiExtremum FindMaximum (Func< IList< double >, double > function, IList< double > start, EvaluationSettings settings)
Finds a local maximum of a multi-dimensional function in the vincinity of the given starting location, subject to the given evaluation constraints.
static IntegrationResult Integrate (Func< IList< double >, double > function, IList< Interval > volume)
Estimates a multi-dimensional integral.
static IntegrationResult Integrate (Func< IList< double >, double > function, IList< Interval > volume, EvaluationSettings settings)
Estimates a multi-dimensional integral using the given evaluation settings.
Static Private Member Functions
static
DifferentialEvolutionSettings GetDefaultSettings (EvaluationSettings settings, int d)
static MultiExtremum FindGlobalExtremum (MultiFunctor f, IList< Interval > volume, DifferentialEvolutionSettings settings)
static EvaluationSettings GetDefaultOptimizationSettings (int d)
static MultiExtremum FindMinimum_ModelTrust (MultiFunctor f, IList< double > x, double s, EvaluationSettings settings)
static UncertainValue Integrate_Adaptave (MultiFunctor f, CoordinateTransform[] map, IntegrationRegion r, EvaluationSettings settings)
static UncertainValue Integrate_MonteCarlo (MultiFunctor f, CoordinateTransform[] map, IList< Interval > box, EvaluationSettings settings)
static double Integrate_MonteCarlo_Cycle (MultiFunctor f, CoordinateTransform[] map, VectorGenerator g, LePageGrid grid, int n)
Private Attributes
const double mutationFactor = 0.625
Detailed Description
Contains methods for the analysis of multi-dimensional functions.
Member Function Documentation
static MultiExtremum Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMinimum (Func< IList< double >, double > function, IList< Interval > volume) inline static
Referenced by Test.MultiExtremumTest.Ackley(), Test.MultiExtremumTest.Bukin(), Test.MultiExtremumTest.Easom(), Test.MultiExtremumTest.GoldsteinPrice(), Test.MultiExtremumTest.Griewank(), Test.MultiExtremumTest.PackSpheresInCube(), Test.MultiExtremumTest.Schwefel(), FutureTest.FutureTest.STA(), and Test.MultiExtremumTest.ThompsonProblem().
static DifferentialEvolutionSettings Meta.Numerics.Analysis.MultiFunctionMath.GetDefaultSettings (EvaluationSettings settings, int d) inline static private
References Meta.Numerics.Analysis.EvaluationSettings.AbsolutePrecision, Meta.Numerics.Analysis.EvaluationSettings.EvaluationBudget, and Meta.Numerics.Analysis.EvaluationSettings.RelativePrecision.
static MultiExtremum Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMinimum (Func< IList< double >, double > function, IList< Interval > volume, EvaluationSettings settings) inline static
static MultiExtremum Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMaximum (Func< IList< double >, double > function, IList< Interval > volume) inline static
Referenced by Test.MultiExtremumTest.PackCirclesInCircle(), and Test.MultiExtremumTest.PackCirclesInSquare().
static MultiExtremum Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMaximum (Func< IList< double >, double > function, IList< Interval > volume, EvaluationSettings settings) inline static
static MultiExtremum Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalExtremum (MultiFunctor f, IList< Interval > volume, DifferentialEvolutionSettings settings) inline static private
static MultiExtremum Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum (Func< IList< double >, double > function, IList< double > start) inline static
Finds a local minimum of a multi-dimensional function in the vincinity of the given starting location.
Parameters
function The multi-dimensional function to minimize.
start The starting location for the search.
Returns
The local minimum.
Referenced by Test.MultiExtremumTest.Beale(), Test.MultiExtremumTest.GoldsteinPrice(), Meta.Numerics.Statistics.BivariateSample.LinearLogisticRegression(), Test.MultiExtremumTest.LocalThomson(), Test.MultiExtremumTest.Perm(), Test.MultiExtremumTest.PerturbedQuadratic(), Test.MultiExtremumTest.Quadratic(), Test.MultiExtremumTest.Rosenbrock(), Test.MultiExtremumTest.SmoothedEasom(), Test.MultiExtremumTest.StylblinskiTang(), Test.MultiExtremumTest.SumOfPowers(), Test.MultiExtremumTest.ThreeHumpCamel(), and Test.MultiExtremumTest.Vardim().
static EvaluationSettings Meta.Numerics.Analysis.MultiFunctionMath.GetDefaultOptimizationSettings (int d) inline static private
References Meta.Numerics.Analysis.EvaluationSettings.AbsolutePrecision, Meta.Numerics.Analysis.EvaluationSettings.EvaluationBudget, and Meta.Numerics.Analysis.EvaluationSettings.RelativePrecision.
static MultiExtremum Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum (Func< IList< double >, double > function, IList< double > start, EvaluationSettings settings) inline static
Finds a local minimum of a multi-dimensional function in the vincinity of the given starting location, subject to the given evaluation constraints.
Parameters
function The multi-dimensional function to minimize.
start The starting location for the search.
settings The evaluation settings that govern the search for the minimum.
Returns
The local minimum.
static MultiExtremum Meta.Numerics.Analysis.MultiFunctionMath.FindMaximum (Func< IList< double >, double > function, IList< double > start, EvaluationSettings settings) inline static
Finds a local maximum of a multi-dimensional function in the vincinity of the given starting location, subject to the given evaluation constraints.
Parameters
function The multi-dimensional function to maximize.
start The starting location for the search.
settings The evaluation settings that govern the search for the maximum.
Returns
The local maximum.
static MultiExtremum Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum_ModelTrust (MultiFunctor f, IList< double > x, double s, EvaluationSettings settings) inline static private
References Meta.Numerics.Analysis.EvaluationSettings.AbsolutePrecision, Meta.Numerics.Analysis.EvaluationSettings.EvaluationBudget, and Meta.Numerics.Analysis.EvaluationSettings.RelativePrecision.
static IntegrationResult Meta.Numerics.Analysis.MultiFunctionMath.Integrate (Func< IList< double >, double > function, IList< Interval > volume) inline static
Estimates a multi-dimensional integral.
Parameters
function The function to integrate.
volume The volume over which to integrate.
By default, our multidimensional integration system targets a relative accuracy of about 10-7 (close to full single precision) for d=2, falling gradually to about 10-2 (1%) for d=12. To achieve that accuracy, it allows up to about 105 evaluations of the integrand for d=2, rising up to about 108 evaluations for d=12.
You can change the accuracy demands and evaluation budget by passing an EvaluationSettings object to the integration method. By decreasing the accuracy you require or increasing the evaluation budget, you may be able to successfully complete integrals that would fail for the default settings.
Referenced by Test.MultiIntegrateTest.BallVolumeIntegrals(), Test.MultiIntegrateTest.BoxIntegralB(), Test.MultiIntegrateTest.BoxIntegralD(), Test.MultiIntegrateTest.DoubleIntegrals(), Test.MultiIntegrateTest.GaussianIntegrals(), Test.MultiIntegrateTest.IsingIntegrals(), Test.MultiIntegrateTest.RambleIntegral(), Test.MultiIntegrateTest.SeperableIntegrals(), Test.MultiIntegrateTest.SteinmetzVolume(), Test.MultiIntegrateTest.WatsonIntegrals(), and Test.MultiIntegrateTest.ZetaIntegrals().
static IntegrationResult Meta.Numerics.Analysis.MultiFunctionMath.Integrate (Func< IList< double >, double > function, IList< Interval > volume, EvaluationSettings settings) inline static
Estimates a multi-dimensional integral using the given evaluation settings.
Parameters
function The function to be integrated.
volume The volume over which to integrate.
settings The integration settings.
Returns
A numerical estimate of the multi-dimensional integral.
Note that the integration function must not attempt to modify the argument passed to it.
Note that the integration volume must be a hyper-rectangle. You can integrate over regions with more complex boundaries by specifying the integration volume as a bounding hyper-rectangle that encloses your desired integration region, and returing the value 0 for the integrand outside of the desired integration region. For example, to find the volume of a unit d-sphere, you can integrate a function that is 1 inside the unit d-sphere and 0 outside it over the volume [-1,1]d. You can integrate over infinite volumes by specifing volume endpoints of Double.PositiveInfinity and/or Double.NegativeInfinity. Volumes with dimension greater than 12 are not currently supported.
Integrals with hard boundaries (like our hyper-sphere volume problem) typically require more evaluations than integrals of smooth functions to achieve the same accuracy. Integrals with canceling positive and negative contributions also typically require more evaluations than integtrals of purely positive functions.
Numerical multi-dimensional integration is computationally expensive. To make problems more tractable, keep in mind some rules of thumb:
Reduce the required accuracy to the minimum required. Alternatively, if you are willing to wait longer, increase the evaluation budget.
Exploit symmetries of the problem to reduce the integration volume. For example, to compute the volume of the unit d-sphere, it is better to integrate of [0,1]d and multiply the result by 2d than to simply integrate over [-1,1]d.
Apply analytic techniques to reduce the dimension of the integral. For example, when computing the volume of the unit d-sphere, it is better to do a (d-1)-dimesional integral over the function that is the height of the sphere in the dth dimension than to do a d-dimensional integral over the function that is 1 inside the sphere and 0 outside it.
Exceptions
ArgumentException function , volume , or settings are null, or the dimension of volume is larger than 12.
NonconvergenceException The prescribed accuracy could not be achieved with the given evaluation budget.
References Meta.Numerics.Analysis.EvaluationSettings.AbsolutePrecision, Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Interval.LeftEndpoint, Meta.Numerics.Analysis.EvaluationSettings.RelativePrecision, Meta.Numerics.Interval.RightEndpoint, Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
static UncertainValue Meta.Numerics.Analysis.MultiFunctionMath.Integrate_Adaptave (MultiFunctor f, CoordinateTransform[] map, IntegrationRegion r, EvaluationSettings settings) inline static private
References Meta.Numerics.Analysis.EvaluationSettings.AbsolutePrecision, Meta.Numerics.Analysis.EvaluationSettings.EvaluationBudget, and Meta.Numerics.Analysis.EvaluationSettings.RelativePrecision.
static UncertainValue Meta.Numerics.Analysis.MultiFunctionMath.Integrate_MonteCarlo (MultiFunctor f, CoordinateTransform[] map, IList< Interval > box, EvaluationSettings settings) inline static private
References Meta.Numerics.Analysis.EvaluationSettings.AbsolutePrecision, Meta.Numerics.Analysis.EvaluationSettings.EvaluationBudget, and Meta.Numerics.Analysis.EvaluationSettings.RelativePrecision.
static double Meta.Numerics.Analysis.MultiFunctionMath.Integrate_MonteCarlo_Cycle (MultiFunctor f, CoordinateTransform[] map, VectorGenerator g, LePageGrid grid, int n) inline static private
Member Data Documentation
const double Meta.Numerics.Analysis.MultiFunctionMath.mutationFactor = 0.625 private
The documentation for this class was generated from the following files:
igtest/numerics/MetaNumerics/Numerics/Numerics/Analysis/MultiFunctionMath.cs
igtest/numerics/MetaNumerics/Numerics/Numerics/Analysis/MultiFunctionMath_Extrema_DifferentialEvolution.cs
igtest/numerics/MetaNumerics/Numerics/Numerics/Analysis/MultiFunctionMath_Extrema_ModelTrust.cs
igtest/numerics/MetaNumerics/Numerics/Numerics/Analysis/MultiFunctionMath_Integrate.cs
igtest/numerics/MetaNumerics/Numerics/Numerics/Analysis/MultiFunctionMath_Integrate_GenzMalik.cs
igtest/numerics/MetaNumerics/Numerics/Numerics/Analysis/MultiFunctionMath_Integrate_MonteCarlo.cs