IGLib: NUnit.Framework.Assertions.CollectionAssertTest Class Reference
NUnit.Framework.Assertions.CollectionAssertTest Class Reference
Test Library for the NUnit CollectionAssert class.
Public Member Functions
void ItemsOfType ()
void ItemsOfTypeFailure ()
void ItemsNotNull ()
void ItemsNotNullFailure ()
void Unique_WithObjects ()
void Unique_WithStrings ()
void Unique_WithNull ()
void UniqueFailure ()
void UniqueFailure_WithTwoNulls ()
void AreEqual ()
void AreEqualFailCount ()
void AreEqualFail ()
void AreEqual_HandlesNull ()
void EnsureComparerIsUsed ()
void AreEqual_UsingIterator ()
void AreEqual_UsingIterator_Fails ()
void AreEqual_UsingLinqQuery ()
void AreEqual_UsingLinqQuery_Fails ()
void Equivalent ()
void EquivalentFailOne ()
void EquivalentFailTwo ()
void AreEquivalentHandlesNull ()
void AreNotEqual ()
void AreNotEqual_Fails ()
void AreNotEqual_HandlesNull ()
void NotEquivalent ()
void NotEquivalent_Fails ()
void NotEquivalentHandlesNull ()
void Contains_IList ()
void Contains_ICollection ()
void ContainsFails_ILIst ()
void ContainsFails_ICollection ()
void ContainsFails_EmptyIList ()
void ContainsFails_EmptyICollection ()
void ContainsNull_IList ()
void ContainsNull_ICollection ()
void DoesNotContain ()
void DoesNotContain_Empty ()
void DoesNotContain_Fails ()
void IsSubsetOf ()
void IsSubsetOf_Fails ()
void IsSubsetOfHandlesNull ()
void IsNotSubsetOf ()
void IsNotSubsetOf_Fails ()
void IsNotSubsetOfHandlesNull ()
void IsOrdered ()
void IsOrdered_Fails ()
void IsOrdered_Allows_adjacent_equal_values ()
void IsOrdered_Handles_null ()
void IsOrdered_ContainedTypesMustBeCompatible ()
void IsOrdered_TypesMustImplementIComparable ()
void IsOrdered_Handles_custom_comparison ()
void IsOrdered_Handles_custom_comparison2 ()
Private Member Functions
IEnumerable CountToThree ()
Detailed Description
Test Library for the NUnit CollectionAssert class.
Member Function Documentation
void NUnit.Framework.Assertions.CollectionAssertTest.ItemsOfType () inline
References NUnit.Framework.CollectionAssert.AllItemsAreInstancesOfType().
void NUnit.Framework.Assertions.CollectionAssertTest.ItemsOfTypeFailure () inline
References NUnit.Framework.CollectionAssert.AllItemsAreInstancesOfType(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.ItemsNotNull () inline
References NUnit.Framework.CollectionAssert.AllItemsAreNotNull().
void NUnit.Framework.Assertions.CollectionAssertTest.ItemsNotNullFailure () inline
References NUnit.Framework.CollectionAssert.AllItemsAreNotNull(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.Unique_WithObjects () inline
References NUnit.Framework.CollectionAssert.AllItemsAreUnique().
void NUnit.Framework.Assertions.CollectionAssertTest.Unique_WithStrings () inline
References NUnit.Framework.CollectionAssert.AllItemsAreUnique().
void NUnit.Framework.Assertions.CollectionAssertTest.Unique_WithNull () inline
References NUnit.Framework.CollectionAssert.AllItemsAreUnique().
void NUnit.Framework.Assertions.CollectionAssertTest.UniqueFailure () inline
References NUnit.Framework.CollectionAssert.AllItemsAreUnique(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.UniqueFailure_WithTwoNulls () inline
References NUnit.Framework.CollectionAssert.AllItemsAreUnique(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.AreEqual () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.CollectionAssert.AreEqual().
void NUnit.Framework.Assertions.CollectionAssertTest.AreEqualFailCount () inline
References NUnit.Framework.CollectionAssert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.AreEqualFail () inline
References NUnit.Framework.CollectionAssert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.AreEqual_HandlesNull () inline
References NUnit.Framework.CollectionAssert.AreEqual().
void NUnit.Framework.Assertions.CollectionAssertTest.EnsureComparerIsUsed () inline
References NUnit.Framework.CollectionAssert.AreEqual().
void NUnit.Framework.Assertions.CollectionAssertTest.AreEqual_UsingIterator () inline
References NUnit.Framework.CollectionAssert.AreEqual().
IEnumerable NUnit.Framework.Assertions.CollectionAssertTest.CountToThree () inline private
void NUnit.Framework.Assertions.CollectionAssertTest.AreEqual_UsingIterator_Fails () inline
References NUnit.Framework.CollectionAssert.AreEqual(), NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.AreEqual_UsingLinqQuery () inline
References NUnit.Framework.CollectionAssert.AreEqual().
void NUnit.Framework.Assertions.CollectionAssertTest.AreEqual_UsingLinqQuery_Fails () inline
References NUnit.Framework.CollectionAssert.AreEqual(), NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.Equivalent () inline
References NUnit.Framework.CollectionAssert.AreEquivalent().
void NUnit.Framework.Assertions.CollectionAssertTest.EquivalentFailOne () inline
References NUnit.Framework.CollectionAssert.AreEquivalent(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.EquivalentFailTwo () inline
References NUnit.Framework.CollectionAssert.AreEquivalent(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.AreEquivalentHandlesNull () inline
References NUnit.Framework.CollectionAssert.AreEquivalent().
void NUnit.Framework.Assertions.CollectionAssertTest.AreNotEqual () inline
References NUnit.Framework.CollectionAssert.AreNotEqual().
void NUnit.Framework.Assertions.CollectionAssertTest.AreNotEqual_Fails () inline
References NUnit.Framework.CollectionAssert.AreNotEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.AreNotEqual_HandlesNull () inline
References NUnit.Framework.CollectionAssert.AreNotEqual().
void NUnit.Framework.Assertions.CollectionAssertTest.NotEquivalent () inline
References NUnit.Framework.CollectionAssert.AreNotEquivalent().
void NUnit.Framework.Assertions.CollectionAssertTest.NotEquivalent_Fails () inline
References NUnit.Framework.CollectionAssert.AreNotEquivalent(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.NotEquivalentHandlesNull () inline
References NUnit.Framework.CollectionAssert.AreNotEquivalent().
void NUnit.Framework.Assertions.CollectionAssertTest.Contains_IList () inline
References NUnit.Framework.CollectionAssert.Contains().
void NUnit.Framework.Assertions.CollectionAssertTest.Contains_ICollection () inline
References NUnit.Framework.CollectionAssert.Contains().
void NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_ILIst () inline
References NUnit.Framework.CollectionAssert.Contains(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_ICollection () inline
References NUnit.Framework.CollectionAssert.Contains(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_EmptyIList () inline
References NUnit.Framework.CollectionAssert.Contains(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.ContainsFails_EmptyICollection () inline
References NUnit.Framework.CollectionAssert.Contains(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.ContainsNull_IList () inline
References NUnit.Framework.CollectionAssert.Contains().
void NUnit.Framework.Assertions.CollectionAssertTest.ContainsNull_ICollection () inline
References NUnit.Framework.CollectionAssert.Contains().
void NUnit.Framework.Assertions.CollectionAssertTest.DoesNotContain () inline
References NUnit.Framework.CollectionAssert.DoesNotContain().
void NUnit.Framework.Assertions.CollectionAssertTest.DoesNotContain_Empty () inline
References NUnit.Framework.CollectionAssert.DoesNotContain().
void NUnit.Framework.Assertions.CollectionAssertTest.DoesNotContain_Fails () inline
References NUnit.Framework.CollectionAssert.DoesNotContain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.IsSubsetOf () inline
References NUnit.Framework.CollectionAssert.IsSubsetOf(), NUnit.Framework.Is.SubsetOf(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.CollectionAssertTest.IsSubsetOf_Fails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.CollectionAssert.IsSubsetOf(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.IsSubsetOfHandlesNull () inline
References NUnit.Framework.CollectionAssert.IsSubsetOf(), NUnit.Framework.Is.SubsetOf(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.CollectionAssertTest.IsNotSubsetOf () inline
References NUnit.Framework.CollectionAssert.IsNotSubsetOf(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.CollectionAssertTest.IsNotSubsetOf_Fails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.CollectionAssert.IsNotSubsetOf(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.IsNotSubsetOfHandlesNull () inline
References NUnit.Framework.CollectionAssert.IsNotSubsetOf().
void NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered () inline
References NUnit.Framework.CollectionAssert.IsOrdered().
void NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_Fails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.CollectionAssert.IsOrdered(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_Allows_adjacent_equal_values () inline
References NUnit.Framework.CollectionAssert.IsOrdered().
void NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_Handles_null () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.CollectionAssert.IsOrdered(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_ContainedTypesMustBeCompatible () inline
References NUnit.Framework.CollectionAssert.IsOrdered(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_TypesMustImplementIComparable () inline
References NUnit.Framework.CollectionAssert.IsOrdered(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_Handles_custom_comparison () inline
References NUnit.Framework.CollectionAssert.IsOrdered().
void NUnit.Framework.Assertions.CollectionAssertTest.IsOrdered_Handles_custom_comparison2 () inline
References NUnit.Framework.CollectionAssert.IsOrdered().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/CollectionAssertTest.cs