IGLib: alglib.testlinlsqrunit Class Reference
alglib.testlinlsqrunit Class Reference
Static Public Member Functions
static bool testlinlsqr (bool silent)
static bool testlinlsqr (bool silent)
static bool _pexec_testlinlsqr (bool silent)
Public Attributes
const double e0 = 1.0E-6
const double tolort = 1.0E-4
const double e1 = 1.0E+6
const double emergencye0 = 1.0E-12
Static Private Member Functions
static bool svdtest (bool silent)
static bool mwcranksvdtest (bool silent)
static bool mwicranksvdtest (bool silent)
static bool bidiagonaltest (bool silent)
static bool zeromatrixtest (bool silent)
static bool reportcorrectnesstest (bool silent)
static bool stoppingcriteriatest (bool silent)
static bool analytictest (bool silent)
static bool isitgoodsolution (double[,] a, double[] b, int m, int n, double lambdav, double[] x, double epserr, double epsort)
static bool svdtest (bool silent)
static bool mwcranksvdtest (bool silent)
static bool mwicranksvdtest (bool silent)
static bool bidiagonaltest (bool silent)
static bool zeromatrixtest (bool silent)
static bool reportcorrectnesstest (bool silent)
static bool stoppingcriteriatest (bool silent)
static bool analytictest (bool silent)
static bool isitgoodsolution (double[,] a, double[] b, int m, int n, double lambdav, double[] x, double epserr, double epsort)
static bool preconditionertest ()
Member Function Documentation
static bool alglib.testlinlsqrunit.testlinlsqr (bool silent) inline static
References alglib.testlinlsqrunit.analytictest(), alglib.testlinlsqrunit.bidiagonaltest(), alglib.testlinlsqrunit.mwcranksvdtest(), alglib.testlinlsqrunit.mwicranksvdtest(), alglib.testlinlsqrunit.reportcorrectnesstest(), alglib.testlinlsqrunit.stoppingcriteriatest(), alglib.testlinlsqrunit.svdtest(), and alglib.testlinlsqrunit.zeromatrixtest().
Referenced by alglib.testlinlsqrunit._pexec_testlinlsqr(), and _Test.Main().
static bool alglib.testlinlsqrunit.svdtest (bool silent) inline static private
References alglib.testlinlsqrunit.isitgoodsolution(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrrestart(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetlambdai(), alglib.linlsqr.linlsqrsolvesparse(), alglib.math.randomreal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
Referenced by alglib.testlinlsqrunit.testlinlsqr().
static bool alglib.testlinlsqrunit.mwcranksvdtest (bool silent) inline static private
References alglib.testlinlsqrunit.isitgoodsolution(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetcond(), alglib.linlsqr.linlsqrsetlambdai(), alglib.math.randomreal(), and alglib.matgen.rmatrixrndcond().
Referenced by alglib.testlinlsqrunit.testlinlsqr().
static bool alglib.testlinlsqrunit.mwicranksvdtest (bool silent) inline static private
References alglib.testlinlsqrunit.isitgoodsolution(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetcond(), alglib.linlsqr.linlsqrsetlambdai(), alglib.math.randomreal(), alglib.matgen.rmatrixrndorthogonalfromtheleft(), and alglib.matgen.rmatrixrndorthogonalfromtheright().
Referenced by alglib.testlinlsqrunit.testlinlsqr().
static bool alglib.testlinlsqrunit.bidiagonaltest (bool silent) inline static private
References alglib.testlinlsqrunit.isitgoodsolution(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetcond(), and alglib.math.randomreal().
Referenced by alglib.testlinlsqrunit.testlinlsqr().
static bool alglib.testlinlsqrunit.zeromatrixtest (bool silent) inline static private
References alglib.testlinlsqrunit.isitgoodsolution(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), and alglib.linlsqr.linlsqrsetcond().
Referenced by alglib.testlinlsqrunit.testlinlsqr().
static bool alglib.testlinlsqrunit.reportcorrectnesstest (bool silent) inline static private
References alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetcond(), alglib.linlsqr.linlsqrsetlambdai(), alglib.linlsqr.linlsqrsetxrep(), alglib.math.randomreal(), and alglib.matgen.spdmatrixrndcond().
Referenced by alglib.testlinlsqrunit.testlinlsqr().
static bool alglib.testlinlsqrunit.stoppingcriteriatest (bool silent) inline static private
References alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetcond(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.matgen.rmatrixrndorthogonal(), alglib.matgen.spdmatrixrndcond(), and alglib.math.sqr().
Referenced by alglib.testlinlsqrunit.testlinlsqr().
static bool alglib.testlinlsqrunit.analytictest (bool silent) inline static private
References alglib.ap.assert(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetcond(), alglib.linlsqr.linlsqrsetxrep(), and alglib.math.randomreal().
Referenced by alglib.testlinlsqrunit.testlinlsqr().
static bool alglib.testlinlsqrunit.isitgoodsolution (double a[,], double[] b, int m, int n, double lambdav, double[] x, double epserr, double epsort) inline static private
References alglib.ap.assert(), alglib.math.machineepsilon, alglib.svd.rmatrixsvd(), and alglib.math.sqr().
Referenced by alglib.testlinlsqrunit.bidiagonaltest(), alglib.testlinlsqrunit.mwcranksvdtest(), alglib.testlinlsqrunit.mwicranksvdtest(), alglib.testlinlsqrunit.svdtest(), and alglib.testlinlsqrunit.zeromatrixtest().
static bool alglib.testlinlsqrunit.testlinlsqr (bool silent) inline static
References alglib.testlinlsqrunit.analytictest(), alglib.testlinlsqrunit.bidiagonaltest(), alglib.testlinlsqrunit.mwcranksvdtest(), alglib.testlinlsqrunit.mwicranksvdtest(), alglib.testlinlsqrunit.preconditionertest(), alglib.testlinlsqrunit.reportcorrectnesstest(), alglib.testlinlsqrunit.stoppingcriteriatest(), alglib.testlinlsqrunit.svdtest(), and alglib.testlinlsqrunit.zeromatrixtest().
static bool alglib.testlinlsqrunit._pexec_testlinlsqr (bool silent) inline static
References alglib.testlinlsqrunit.testlinlsqr().
Referenced by _Test.Main().
static bool alglib.testlinlsqrunit.svdtest (bool silent) inline static private
References alglib.testlinlsqrunit.isitgoodsolution(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrrestart(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetlambdai(), alglib.linlsqr.linlsqrsetprecunit(), alglib.linlsqr.linlsqrsolvesparse(), alglib.math.randomreal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
static bool alglib.testlinlsqrunit.mwcranksvdtest (bool silent) inline static private
References alglib.testlinlsqrunit.isitgoodsolution(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetcond(), alglib.linlsqr.linlsqrsetlambdai(), alglib.math.randomreal(), and alglib.matgen.rmatrixrndcond().
static bool alglib.testlinlsqrunit.mwicranksvdtest (bool silent) inline static private
References alglib.testlinlsqrunit.isitgoodsolution(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetcond(), alglib.linlsqr.linlsqrsetlambdai(), alglib.math.randomreal(), alglib.matgen.rmatrixrndorthogonalfromtheleft(), and alglib.matgen.rmatrixrndorthogonalfromtheright().
static bool alglib.testlinlsqrunit.bidiagonaltest (bool silent) inline static private
References alglib.testlinlsqrunit.isitgoodsolution(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetcond(), and alglib.math.randomreal().
static bool alglib.testlinlsqrunit.zeromatrixtest (bool silent) inline static private
References alglib.testlinlsqrunit.isitgoodsolution(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), and alglib.linlsqr.linlsqrsetcond().
static bool alglib.testlinlsqrunit.reportcorrectnesstest (bool silent) inline static private
References alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetcond(), alglib.linlsqr.linlsqrsetlambdai(), alglib.linlsqr.linlsqrsetxrep(), alglib.math.randomreal(), and alglib.matgen.spdmatrixrndcond().
static bool alglib.testlinlsqrunit.stoppingcriteriatest (bool silent) inline static private
References alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetcond(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.matgen.rmatrixrndorthogonal(), alglib.matgen.spdmatrixrndcond(), and alglib.math.sqr().
static bool alglib.testlinlsqrunit.analytictest (bool silent) inline static private
References alglib.ap.assert(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqriteration(), alglib.linlsqr.linlsqrsetb(), alglib.linlsqr.linlsqrsetcond(), alglib.linlsqr.linlsqrsetxrep(), and alglib.math.randomreal().
static bool alglib.testlinlsqrunit.isitgoodsolution (double a[,], double[] b, int m, int n, double lambdav, double[] x, double epserr, double epsort) inline static private
References alglib.ap.assert(), alglib.math.machineepsilon, alglib.svd.rmatrixsvd(), and alglib.math.sqr().
static bool alglib.testlinlsqrunit.preconditionertest () inline static private
References alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetcond(), alglib.linlsqr.linlsqrsetprecdiag(), alglib.linlsqr.linlsqrsetprecunit(), alglib.linlsqr.linlsqrsolvesparse(), alglib.apserv.randomnormal(), alglib.math.randomreal(), alglib.matgen.rmatrixrndcond(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
Referenced by alglib.testlinlsqrunit.testlinlsqr().
Member Data Documentation
const double alglib.testlinlsqrunit.e0 = 1.0E-6
const double alglib.testlinlsqrunit.tolort = 1.0E-4
const double alglib.testlinlsqrunit.e1 = 1.0E+6
const double alglib.testlinlsqrunit.emergencye0 = 1.0E-12
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs