IGLib: Test.AdvancedComplexMathTest Class Reference
Test.AdvancedComplexMathTest Class Reference
Public Member Functions
void ComplexErfSpecialCase ()
void ComplexErfSymmetries ()
void ComplexErfFresnel ()
void ComplexErfFaddevaAgreement ()
void ComplexFaddeevaSpecialCase ()
void ComplexFaddeevaConjugation ()
void ComplexFaddeevaDawson ()
void ComplexGammaConjugation ()
void ComplexGammaRecurrance ()
void ComplexGammaInequality ()
void ComplexGammaKnownLines ()
void ComplexLogGammaConjugation ()
void ComplexLogGammaAgreement ()
void ComplexPsiRecurrence ()
void ComplexPsiDuplication ()
void ComplexPsiConjugation ()
void ComplexPsiImaginaryParts ()
void ComplexDiLogSymmetry ()
void ComplexDiLogUnitCircle ()
void ComplexDiLogAgreement ()
void ComplexDiLogConjugation ()
void ComplexDiLogBranchCut ()
void ComplexDiLogClausen ()
void ComplexEinAgreement ()
void ComplexRealRiemannZetaAgreement ()
void ComplexRiemannZetaZeros ()
void ComplexReimannZetaPrimesTest ()
Member Function Documentation
void Test.AdvancedComplexMathTest.ComplexErfSpecialCase () inline
References Meta.Numerics.Functions.AdvancedComplexMath.Erf().
void Test.AdvancedComplexMathTest.ComplexErfSymmetries () inline
References Meta.Numerics.Complex.Conjugate, Meta.Numerics.Functions.AdvancedComplexMath.Erf(), and Meta.Numerics.Complex.Im.
void Test.AdvancedComplexMathTest.ComplexErfFresnel () inline
References Meta.Numerics.Functions.AdvancedComplexMath.Erf(), Meta.Numerics.ComplexMath.I, Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
void Test.AdvancedComplexMathTest.ComplexErfFaddevaAgreement () inline
References Meta.Numerics.Functions.AdvancedComplexMath.Erf(), Meta.Numerics.ComplexMath.Exp(), Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva(), Meta.Numerics.ComplexMath.I, Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
void Test.AdvancedComplexMathTest.ComplexFaddeevaSpecialCase () inline
References Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva().
void Test.AdvancedComplexMathTest.ComplexFaddeevaConjugation () inline
References Meta.Numerics.Complex.Conjugate, Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva(), and Meta.Numerics.Complex.Im.
void Test.AdvancedComplexMathTest.ComplexFaddeevaDawson () inline
References Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva(), Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
void Test.AdvancedComplexMathTest.ComplexGammaConjugation () inline
References Meta.Numerics.Complex.Conjugate, and Meta.Numerics.Functions.AdvancedComplexMath.Gamma().
void Test.AdvancedComplexMathTest.ComplexGammaRecurrance () inline
References Meta.Numerics.Functions.AdvancedComplexMath.Gamma().
void Test.AdvancedComplexMathTest.ComplexGammaInequality () inline
References Meta.Numerics.ComplexMath.Abs(), Meta.Numerics.Functions.AdvancedMath.Gamma(), Meta.Numerics.Functions.AdvancedComplexMath.Gamma(), and Meta.Numerics.Complex.Re.
void Test.AdvancedComplexMathTest.ComplexGammaKnownLines () inline
References Meta.Numerics.Functions.AdvancedComplexMath.Gamma().
void Test.AdvancedComplexMathTest.ComplexLogGammaConjugation () inline
References Meta.Numerics.Complex.Conjugate, Meta.Numerics.Functions.AdvancedComplexMath.LogGamma(), and Meta.Numerics.Complex.Re.
void Test.AdvancedComplexMathTest.ComplexLogGammaAgreement () inline
References Meta.Numerics.Functions.AdvancedMath.LogGamma(), and Meta.Numerics.Functions.AdvancedComplexMath.LogGamma().
void Test.AdvancedComplexMathTest.ComplexPsiRecurrence () inline
References Meta.Numerics.Functions.AdvancedComplexMath.Psi().
void Test.AdvancedComplexMathTest.ComplexPsiDuplication () inline
References Meta.Numerics.Functions.AdvancedComplexMath.Psi().
void Test.AdvancedComplexMathTest.ComplexPsiConjugation () inline
References Meta.Numerics.Complex.Conjugate, and Meta.Numerics.Functions.AdvancedComplexMath.Psi().
void Test.AdvancedComplexMathTest.ComplexPsiImaginaryParts () inline
References Meta.Numerics.Complex.Im, and Meta.Numerics.Functions.AdvancedComplexMath.Psi().
void Test.AdvancedComplexMathTest.ComplexDiLogSymmetry () inline
References Meta.Numerics.Functions.AdvancedComplexMath.DiLog(), and Meta.Numerics.ComplexMath.Log().
void Test.AdvancedComplexMathTest.ComplexDiLogUnitCircle () inline
References Meta.Numerics.Functions.AdvancedMath.Catalan, Meta.Numerics.Functions.AdvancedComplexMath.DiLog(), and Meta.Numerics.ComplexMath.I.
void Test.AdvancedComplexMathTest.ComplexDiLogAgreement () inline
References Meta.Numerics.Functions.AdvancedMath.DiLog(), and Meta.Numerics.Functions.AdvancedComplexMath.DiLog().
void Test.AdvancedComplexMathTest.ComplexDiLogConjugation () inline
References Meta.Numerics.Complex.Conjugate, and Meta.Numerics.Functions.AdvancedComplexMath.DiLog().
void Test.AdvancedComplexMathTest.ComplexDiLogBranchCut () inline
References Meta.Numerics.Functions.AdvancedComplexMath.DiLog(), Meta.Numerics.ComplexMath.I, Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
void Test.AdvancedComplexMathTest.ComplexDiLogClausen () inline
References Meta.Numerics.Functions.AdvancedMath.Clausen(), Meta.Numerics.Functions.AdvancedComplexMath.DiLog(), Meta.Numerics.ComplexMath.Exp(), Meta.Numerics.ComplexMath.I, Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
void Test.AdvancedComplexMathTest.ComplexEinAgreement () inline
References Meta.Numerics.Functions.AdvancedComplexMath.Ein(), Meta.Numerics.Functions.AdvancedMath.EulerGamma, Meta.Numerics.Functions.AdvancedMath.IntegralE(), and Meta.Numerics.Functions.AdvancedMath.IntegralEi().
void Test.AdvancedComplexMathTest.ComplexRealRiemannZetaAgreement () inline
References Meta.Numerics.Functions.AdvancedMath.RiemannZeta(), and Meta.Numerics.Functions.AdvancedComplexMath.RiemannZeta().
void Test.AdvancedComplexMathTest.ComplexRiemannZetaZeros () inline
References Meta.Numerics.Analysis.FunctionMath.FindZero(), Meta.Numerics.Complex.Im, Meta.Numerics.Complex.Re, and Meta.Numerics.Functions.AdvancedComplexMath.RiemannZeta().
void Test.AdvancedComplexMathTest.ComplexReimannZetaPrimesTest () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.IsPrime(), Meta.Numerics.Complex.One, Meta.Numerics.ComplexMath.Pow(), Meta.Numerics.Complex.Re, and Meta.Numerics.Functions.AdvancedComplexMath.RiemannZeta().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/AdvancedComplexMathTest.cs