IGLib: alglib.testmlptrainunit Class Reference
alglib.testmlptrainunit Class Reference
Static Public Member Functions
static bool testmlptrain (bool silent)
static bool testmlptrain (bool silent)
static bool _pexec_testmlptrain (bool silent)
Static Private Member Functions
static void createnetwork (mlpbase.multilayerperceptron network, int nkind, double a1, double a2, int nin, int nhid1, int nhid2, int nout)
static void unsetnetwork (mlpbase.multilayerperceptron network)
static void testinformational (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err)
static void testprocessing (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err)
static void testgradient (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err)
static void testhessian (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err)
static bool testmlptraines ()
static void createnetwork (mlpbase.multilayerperceptron network, int nkind, double a1, double a2, int nin, int nhid1, int nhid2, int nout)
static void unsetnetwork (mlpbase.multilayerperceptron network)
static bool testmlptraines ()
static bool testmlptrainregr ()
static bool testmlpxorregr ()
static bool testmlptrainclass ()
static bool testmlpxorcls ()
static bool testmlpzeroweights ()
static bool testmlprestarts ()
static bool testmlpgbsubset ()
static bool testmlpcverror ()
static bool testmlptrainens ()
static bool testmlptrainensregr ()
static bool testmlptrainenscls ()
Member Function Documentation
static bool alglib.testmlptrainunit.testmlptrain (bool silent) inline static
References alglib.mlpbase.mlpcreate1(), alglib.mlpbase.mlprmserror(), alglib.mlptrain.mlptrainlm(), alglib.testmlptrainunit.testgradient(), alglib.testmlptrainunit.testhessian(), alglib.testmlptrainunit.testinformational(), alglib.testmlptrainunit.testmlptraines(), and alglib.testmlptrainunit.testprocessing().
Referenced by alglib.testmlptrainunit._pexec_testmlptrain(), and _Test.Main().
static void alglib.testmlptrainunit.createnetwork (mlpbase.multilayerperceptron network, int nkind, double a1, double a2, int nin, int nhid1, int nhid2, int nout) inline static private
References alglib.serializer.alloc_start(), alglib.ap.assert(), alglib.serializer.get_string(), alglib.mlpbase.mlpalloc(), alglib.mlpbase.mlpcopy(), alglib.mlpbase.mlpcreate0(), alglib.mlpbase.mlpcreate1(), alglib.mlpbase.mlpcreate2(), alglib.mlpbase.mlpcreateb0(), alglib.mlpbase.mlpcreateb1(), alglib.mlpbase.mlpcreateb2(), alglib.mlpbase.mlpcreatec0(), alglib.mlpbase.mlpcreatec1(), alglib.mlpbase.mlpcreatec2(), alglib.mlpbase.mlpcreater0(), alglib.mlpbase.mlpcreater1(), alglib.mlpbase.mlpcreater2(), alglib.mlpbase.mlprandomizefull(), alglib.mlpbase.mlpserialize(), alglib.mlpbase.mlpunserialize(), alglib.math.randominteger(), alglib.serializer.sstart_str(), alglib.serializer.stop(), and alglib.serializer.ustart_str().
Referenced by alglib.testmlptrainunit.testgradient(), alglib.testmlptrainunit.testhessian(), alglib.testmlptrainunit.testinformational(), alglib.testmlptrainunit.testmlpgbsubset(), and alglib.testmlptrainunit.testprocessing().
static void alglib.testmlptrainunit.unsetnetwork (mlpbase.multilayerperceptron network) inline static private
References alglib.mlpbase.mlpcreate0().
Referenced by alglib.testmlptrainunit.testprocessing().
static void alglib.testmlptrainunit.testinformational (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err) inline static private
References alglib.testmlptrainunit.createnetwork(), alglib.math.machineepsilon, alglib.mlpbase.mlpactivationfunction(), alglib.mlpbase.mlpgetinputscaling(), alglib.mlpbase.mlpgetinputscount(), alglib.mlpbase.mlpgetlayersize(), alglib.mlpbase.mlpgetneuroninfo(), alglib.mlpbase.mlpgetoutputscaling(), alglib.mlpbase.mlpgetoutputscount(), alglib.mlpbase.mlpgetweight(), alglib.mlpbase.mlpgetweightscount(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlpproperties(), and alglib.math.randomreal().
Referenced by alglib.testmlptrainunit.testmlptrain().
static void alglib.testmlptrainunit.testprocessing (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err) inline static private
References alglib.serializer.alloc_start(), alglib.ap.assert(), alglib.testmlptrainunit.createnetwork(), alglib.serializer.get_string(), alglib.math.machineepsilon, alglib.mlpbase.mlpalloc(), alglib.mlpbase.mlpcopy(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlpproperties(), alglib.mlpbase.mlprandomize(), alglib.mlpbase.mlprandomizefull(), alglib.mlpbase.mlpserialize(), alglib.mlpbase.mlpunserialize(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.serializer.sstart_str(), alglib.serializer.stop(), alglib.testmlptrainunit.unsetnetwork(), and alglib.serializer.ustart_str().
Referenced by alglib.testmlptrainunit.testmlptrain().
static void alglib.testmlptrainunit.testgradient (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err) inline static private
References alglib.ap.assert(), alglib.testmlptrainunit.createnetwork(), alglib.math.maxrealnumber, alglib.mlpbase.mlperror(), alglib.mlpbase.mlperrorn(), alglib.mlpbase.mlpgrad(), alglib.mlpbase.mlpgradbatch(), alglib.mlpbase.mlpgradn(), alglib.mlpbase.mlpgradnbatch(), alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlpproperties(), alglib.mlpbase.mlprandomizefull(), alglib.math.randominteger(), alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testmlptrainunit.testmlptrain().
static void alglib.testmlptrainunit.testhessian (int nkind, int nin, int nhid1, int nhid2, int nout, int passcount, ref bool err) inline static private
References alglib.ap.assert(), alglib.testmlptrainunit.createnetwork(), alglib.mlpbase.mlpgrad(), alglib.mlpbase.mlpgradn(), alglib.mlpbase.mlphessianbatch(), alglib.mlpbase.mlphessiannbatch(), alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpproperties(), alglib.mlpbase.mlprandomizefull(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testmlptrainunit.testmlptrain().
static bool alglib.testmlptrainunit.testmlptraines () inline static private
References alglib.mlpbase.mlpcreater0(), alglib.mlpbase.mlperror(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlprandomize(), alglib.mlptrain.mlptraines(), and alglib.math.randomreal().
Referenced by alglib.testmlptrainunit.testmlptrain().
static bool alglib.testmlptrainunit.testmlptrain (bool silent) inline static
References alglib.mlpbase.mlpcreate1(), alglib.mlpbase.mlprmserror(), alglib.mlptrain.mlptrainlm(), alglib.testmlptrainunit.testmlpcverror(), alglib.testmlptrainunit.testmlprestarts(), alglib.testmlptrainunit.testmlptrainclass(), alglib.testmlptrainunit.testmlptrainens(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlptrainensregr(), alglib.testmlptrainunit.testmlptraines(), alglib.testmlptrainunit.testmlptrainregr(), alglib.testmlptrainunit.testmlpxorcls(), alglib.testmlptrainunit.testmlpxorregr(), and alglib.testmlptrainunit.testmlpzeroweights().
static bool alglib.testmlptrainunit._pexec_testmlptrain (bool silent) inline static
References alglib.testmlptrainunit.testmlptrain().
Referenced by _Test.Main().
static void alglib.testmlptrainunit.createnetwork (mlpbase.multilayerperceptron network, int nkind, double a1, double a2, int nin, int nhid1, int nhid2, int nout) inline static private
References alglib.serializer.alloc_start(), alglib.ap.assert(), alglib.serializer.get_string(), alglib.mlpbase.mlpalloc(), alglib.mlpbase.mlpcopy(), alglib.mlpbase.mlpcreate0(), alglib.mlpbase.mlpcreate1(), alglib.mlpbase.mlpcreate2(), alglib.mlpbase.mlpcreateb0(), alglib.mlpbase.mlpcreateb1(), alglib.mlpbase.mlpcreateb2(), alglib.mlpbase.mlpcreatec0(), alglib.mlpbase.mlpcreatec1(), alglib.mlpbase.mlpcreatec2(), alglib.mlpbase.mlpcreater0(), alglib.mlpbase.mlpcreater1(), alglib.mlpbase.mlpcreater2(), alglib.mlpbase.mlprandomizefull(), alglib.mlpbase.mlpserialize(), alglib.mlpbase.mlpunserialize(), alglib.math.randominteger(), alglib.serializer.sstart_str(), alglib.serializer.stop(), and alglib.serializer.ustart_str().
static void alglib.testmlptrainunit.unsetnetwork (mlpbase.multilayerperceptron network) inline static private
References alglib.mlpbase.mlpcreate0().
static bool alglib.testmlptrainunit.testmlptraines () inline static private
References alglib.mlpbase.mlpcreater0(), alglib.mlpbase.mlperror(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlprandomize(), alglib.mlptrain.mlptraines(), and alglib.math.randomreal().
static bool alglib.testmlptrainunit.testmlptrainregr () inline static private
References alglib.mlpbase.mlpcreate1(), alglib.mlptrain.mlpcreatetrainer(), alglib.mlpbase.mlpprocess(), alglib.mlptrain.mlpsetcond(), alglib.mlptrain.mlpsetdataset(), alglib.mlptrain.mlpsetdecay(), alglib.mlptrain.mlpsetsparsedataset(), alglib.mlptrain.mlptrainlbfgs(), alglib.mlptrain.mlptrainlm(), alglib.mlptrain.mlptrainnetwork(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
Referenced by alglib.testmlptrainunit.testmlptrain().
static bool alglib.testmlptrainunit.testmlpxorregr () inline static private
References alglib.mlptrain.mlpcontinuetraining(), alglib.mlpbase.mlpcreate1(), alglib.mlptrain.mlpcreatetrainer(), alglib.mlpbase.mlpprocess(), alglib.mlptrain.mlpsetcond(), alglib.mlptrain.mlpsetdataset(), alglib.mlptrain.mlpsetdecay(), alglib.mlptrain.mlpsetsparsedataset(), alglib.mlptrain.mlpstarttraining(), alglib.mlptrain.mlptrainnetwork(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
Referenced by alglib.testmlptrainunit.testmlptrain().
static bool alglib.testmlptrainunit.testmlptrainclass () inline static private
References alglib.mlpbase.mlpcreatec0(), alglib.mlptrain.mlpcreatetrainercls(), alglib.mlpbase.mlpprocess(), alglib.mlptrain.mlpsetcond(), alglib.mlptrain.mlpsetdataset(), alglib.mlptrain.mlpsetdecay(), alglib.mlptrain.mlpsetsparsedataset(), alglib.mlptrain.mlptrainlbfgs(), alglib.mlptrain.mlptrainlm(), alglib.mlptrain.mlptrainnetwork(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
Referenced by alglib.testmlptrainunit.testmlptrain().
static bool alglib.testmlptrainunit.testmlpxorcls () inline static private
References alglib.math.maxrealnumber, alglib.mlptrain.mlpcontinuetraining(), alglib.mlpbase.mlpcreatec1(), alglib.mlptrain.mlpcreatetrainercls(), alglib.mlpbase.mlperror(), alglib.mlpbase.mlpprocess(), alglib.mlpbase.mlpproperties(), alglib.mlptrain.mlpsetcond(), alglib.mlptrain.mlpsetdataset(), alglib.mlptrain.mlpsetdecay(), alglib.mlptrain.mlpsetsparsedataset(), alglib.mlptrain.mlpstarttraining(), alglib.mlptrain.mlptrainnetwork(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
Referenced by alglib.testmlptrainunit.testmlptrain().
static bool alglib.testmlptrainunit.testmlpzeroweights () inline static private
References alglib.mlptrain.mlpcontinuetraining(), alglib.mlpbase.mlpcreate0(), alglib.mlpbase.mlpcreatec0(), alglib.mlptrain.mlpcreatetrainer(), alglib.mlptrain.mlpcreatetrainercls(), alglib.mlpbase.mlpproperties(), alglib.mlptrain.mlpsetcond(), alglib.mlptrain.mlpsetdataset(), alglib.mlptrain.mlpsetdecay(), alglib.mlptrain.mlpsetsparsedataset(), alglib.mlptrain.mlpstarttraining(), alglib.mlptrain.mlptrainnetwork(), alglib.math.randominteger(), alglib.sparse.sparseconverttocrs(), and alglib.sparse.sparsecreate().
Referenced by alglib.testmlptrainunit.testmlptrain().
static bool alglib.testmlptrainunit.testmlprestarts () inline static private
References alglib.mlpbase.mlpcreate1(), alglib.mlptrain.mlpcreatetrainer(), alglib.mlpbase.mlperrorn(), alglib.mlpbase.mlpproperties(), alglib.mlptrain.mlpsetcond(), alglib.mlptrain.mlpsetdataset(), alglib.mlptrain.mlpsetdecay(), alglib.mlptrain.mlpsetsparsedataset(), alglib.mlptrain.mlptrainlbfgs(), alglib.mlptrain.mlptrainnetwork(), alglib.math.randomreal(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
Referenced by alglib.testmlptrainunit.testmlptrain().
static bool alglib.testmlptrainunit.testmlpgbsubset () inline static private
References alglib.testmlptrainunit.createnetwork(), alglib.mlpbase.mlpgradbatch(), alglib.mlpbase.mlpgradbatchsparse(), alglib.mlpbase.mlpgradbatchsparsesubset(), alglib.mlpbase.mlpgradbatchsubset(), alglib.mlpbase.mlpissoftmax(), alglib.mlpbase.mlpproperties(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
static bool alglib.testmlptrainunit.testmlpcverror () inline static private
References alglib.mlpbase.mlpavgce(), alglib.mlpbase.mlpavgerror(), alglib.mlpbase.mlpavgrelerror(), alglib.mlpbase.mlpcreate0(), alglib.mlpbase.mlpcreatec1(), alglib.mlptrain.mlpcreatetrainer(), alglib.mlptrain.mlpcreatetrainercls(), alglib.mlptrain.mlpkfoldcv(), alglib.mlpbase.mlprelclserror(), alglib.mlpbase.mlprmserror(), alglib.mlptrain.mlpsetcond(), alglib.mlptrain.mlpsetdataset(), alglib.mlptrain.mlpsetdecay(), alglib.mlptrain.mlpsetsparsedataset(), alglib.mlptrain.mlptrainnetwork(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.rmatrixsetlengthatleast(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
Referenced by alglib.testmlptrainunit.testmlptrain().
static bool alglib.testmlptrainunit.testmlptrainens () inline static private
References alglib.mlptrain.mlpebagginglbfgs(), alglib.mlptrain.mlpebagginglm(), alglib.mlpe.mlpecreate1(), alglib.mlpe.mlpecreatec1(), alglib.mlpe.mlpermserror(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testmlptrainunit.testmlptrain().
static bool alglib.testmlptrainunit.testmlptrainensregr () inline static private
References alglib.mlptrain.mlpcreatetrainer(), alglib.mlpe.mlpeallerrorsx(), alglib.mlpe.mlpecreate1(), alglib.mlpe.mlpeprocess(), alglib.mlptrain.mlpetraines(), alglib.mlptrain.mlpsetcond(), alglib.mlptrain.mlpsetdataset(), alglib.mlptrain.mlpsetdecay(), alglib.mlptrain.mlpsetsparsedataset(), alglib.mlptrain.mlptrainensemblees(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.rmatrixsetlengthatleast(), alglib.apserv.rvectorsetlengthatleast(), alglib.apserv.seterrorflag(), alglib.apserv.seterrorflagdiff(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparsegetrow(), and alglib.sparse.sparseset().
Referenced by alglib.testmlptrainunit.testmlptrain().
static bool alglib.testmlptrainunit.testmlptrainenscls () inline static private
References alglib.mlptrain.mlpcreatetrainercls(), alglib.mlpe.mlpecreatec0(), alglib.mlpe.mlpeprocess(), alglib.mlptrain.mlpetraines(), alglib.mlptrain.mlpsetcond(), alglib.mlptrain.mlpsetdataset(), alglib.mlptrain.mlpsetdecay(), alglib.mlptrain.mlpsetsparsedataset(), alglib.mlptrain.mlptrainensemblees(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.rmatrixsetlengthatleast(), alglib.apserv.rvectorsetlengthatleast(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparsegetrow(), and alglib.sparse.sparseset().
Referenced by alglib.testmlptrainunit.testmlptrain().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs