IGLib: NumLib.ExampleAlgLib2008 Class Reference
NumLib.ExampleAlgLib2008 Class Reference
Static Public Member Functions
static void OptimizeQuadraticWithObject ()
Minimization of a quadratic function performed by the MinimizerLbfgs object.
static void OptimizeQuadratic ()
Minimization of a quadratic function.
static void OptimizeRosenbrock (bool useFunctions)
Example: minimization of Rosenbrock function.
static void OptimizeRosenbrockOriginal ()
Original example of minimizing the Rosenbrock function.
Member Function Documentation
static void NumLib.ExampleAlgLib2008.OptimizeQuadraticWithObject () inline static
Minimization of a quadratic function performed by the MinimizerLbfgs object.
References NumLib.MinimizerLbfgs.Minimize(), and NumLib.MinimizerBase.OutputLevel.
Referenced by NumLib.ProgramOptimization.Main().
static void NumLib.ExampleAlgLib2008.OptimizeQuadratic () inline static
Minimization of a quadratic function.
References NumLib.FunctionWithGradient.ArrayToString(), NumLib.FunctionWithGradient.Description, NumLib.FunctionWithGradient.Gradient(), AlgLib.lbfgs.minlbfgs(), AlgLib.lbfgs.minlbfgsiteration(), AlgLib.lbfgs.minlbfgsresults(), NumLib.FunctionWithGradient.Norm(), and NumLib.FunctionWithGradient.Value().
static void NumLib.ExampleAlgLib2008.OptimizeRosenbrock (bool useFunctions) inline static
Example: minimization of Rosenbrock function.
Parameters
useFunctions If true then function object is used for definition of the minimized function. Otherwise, function definition is hard/coded at the place where function value and gradient are calculated.d
References NumLib.RosenbrockFunction.Description, NumLib.RosenbrockFunction.Gradient(), AlgLib.lbfgs.minlbfgs(), AlgLib.lbfgs.minlbfgsiteration(), AlgLib.lbfgs.minlbfgsresults(), NumLib.FunctionWithGradient.Norm(), AP1.Mathe.Sqr(), and NumLib.RosenbrockFunction.Value().
static void NumLib.ExampleAlgLib2008.OptimizeRosenbrockOriginal () inline static
Original example of minimizing the Rosenbrock function.
References AlgLib.lbfgs.minlbfgs(), AlgLib.lbfgs.minlbfgsiteration(), AlgLib.lbfgs.minlbfgsresults(), AP1.Mathe.RandomReal(), and AP1.Mathe.Sqr().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/opt/alglib/Alglib_Old_UniMb/AlgLib2008/ExampleAlgLib2008.cs