IGLib: IPLab.ImageStatisticsWindow Class Reference
IPLab.ImageStatisticsWindow Class Reference
Summary description for ImageStatisticsWindow.
Public Member Functions
ImageStatisticsWindow ()
void GatherStatistics (Bitmap image)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.Windows.Forms.PropertyGrid propertyGrid
System.ComponentModel.Container components = null
Required designer variable.
int currentImageHash = 0
Detailed Description
Summary description for ImageStatisticsWindow.
Constructor & Destructor Documentation
IPLab.ImageStatisticsWindow.ImageStatisticsWindow () inline
References IPLab.ImageStatisticsWindow.InitializeComponent().
Member Function Documentation
override void IPLab.ImageStatisticsWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
References IPLab.ImageStatisticsWindow.components.
void IPLab.ImageStatisticsWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IPLab.ImageStatisticsWindow.ImageStatisticsWindow().
void IPLab.ImageStatisticsWindow.GatherStatistics (Bitmap image) inline
References IPLab.ImageStatisticsWindow.propertyGrid.
Referenced by IPLab.MainForm.statistics_VisibleChanged(), and IPLab.MainForm.UpdateStatistics().
Member Data Documentation
System.Windows.Forms.PropertyGrid IPLab.ImageStatisticsWindow.propertyGrid private
Referenced by IPLab.ImageStatisticsWindow.GatherStatistics().
System.ComponentModel.Container IPLab.ImageStatisticsWindow.components = null private
Required designer variable.
Referenced by IPLab.ImageStatisticsWindow.Dispose().
int IPLab.ImageStatisticsWindow.currentImageHash = 0 private
The documentation for this class was generated from the following file:
igsandbox/imageprocessing/iplab_new_GPL/Sources/ImageStatisticsWindow.cs