IGLib: alglib.minbleic Class Reference
alglib.minbleic Class Reference
Classes
class minbleicreport
class minbleicstate
Static Public Member Functions
static void minbleiccreate (int n, double[] x, minbleicstate state)
static void minbleiccreatef (int n, double[] x, double diffstep, minbleicstate state)
static void minbleicsetbc (minbleicstate state, double[] bndl, double[] bndu)
static void minbleicsetlc (minbleicstate state, double[,] c, int[] ct, int k)
static void minbleicsetinnercond (minbleicstate state, double epsg, double epsf, double epsx)
static void minbleicsetoutercond (minbleicstate state, double epsx, double epsi)
static void minbleicsetscale (minbleicstate state, double[] s)
static void minbleicsetprecdefault (minbleicstate state)
static void minbleicsetprecdiag (minbleicstate state, double[] d)
static void minbleicsetprecscale (minbleicstate state)
static void minbleicsetmaxits (minbleicstate state, int maxits)
static void minbleicsetxrep (minbleicstate state, bool needxrep)
static void minbleicsetstpmax (minbleicstate state, double stpmax)
static bool minbleiciteration (minbleicstate state)
static void minbleicresults (minbleicstate state, ref double[] x, minbleicreport rep)
static void minbleicresultsbuf (minbleicstate state, ref double[] x, minbleicreport rep)
static void minbleicrestartfrom (minbleicstate state, double[] x)
static void minbleicsetgradientcheck (minbleicstate state, double teststep)
static void minbleiccreate (int n, double[] x, minbleicstate state)
static void minbleiccreatef (int n, double[] x, double diffstep, minbleicstate state)
static void minbleicsetbc (minbleicstate state, double[] bndl, double[] bndu)
static void minbleicsetlc (minbleicstate state, double[,] c, int[] ct, int k)
static void minbleicsetcond (minbleicstate state, double epsg, double epsf, double epsx, int maxits)
static void minbleicsetscale (minbleicstate state, double[] s)
static void minbleicsetprecdefault (minbleicstate state)
static void minbleicsetprecdiag (minbleicstate state, double[] d)
static void minbleicsetprecscale (minbleicstate state)
static void minbleicsetxrep (minbleicstate state, bool needxrep)
static void minbleicsetdrep (minbleicstate state, bool needdrep)
static void minbleicsetstpmax (minbleicstate state, double stpmax)
static bool minbleiciteration (minbleicstate state)
static void minbleicresults (minbleicstate state, ref double[] x, minbleicreport rep)
static void minbleicresultsbuf (minbleicstate state, ref double[] x, minbleicreport rep)
static void minbleicrestartfrom (minbleicstate state, double[] x)
static void minbleicemergencytermination (minbleicstate state)
static void minbleicsetgradientcheck (minbleicstate state, double teststep)
Public Attributes
const double svdtol = 100
const double maxouterits = 20
const double maxnonmonotoniclen = 1.0E5
const double gtol = 0.4
const double initialdecay = 0.5
const double mindecay = 0.1
const double decaycorrection = 0.8
const double penaltyfactor = 100
Static Private Member Functions
static void clearrequestfields (minbleicstate state)
static void unscalepoint (minbleicstate state, double[] xscaled, ref double[] xunscaled)
static void projectpointandunscale (minbleicstate state, ref double[] xscaled, ref double[] xunscaled, ref double[] rscaled, ref double rnorm2)
static void scalegradientandexpand (minbleicstate state, double[] gunscaled, ref double[] gscaled)
static void modifytargetfunction (minbleicstate state, double[] x, double[] r, double rnorm2, ref double f, ref double[] g, ref double gnorm, ref double mpgnorm)
static bool additionalcheckforconstraints (minbleicstate state, double[] x)
static void rebuildcexe (minbleicstate state)
static void makegradientprojection (minbleicstate state, ref double[] pg)
static bool prepareconstraintmatrix (minbleicstate state, double[] x, double[] g, ref double[] px, ref double[] pg)
static void minbleicinitinternal (int n, double[] x, double diffstep, minbleicstate state)
static void clearrequestfields (minbleicstate state)
static void minbleicinitinternal (int n, double[] x, double diffstep, minbleicstate state)
static void updateestimateofgoodstep (ref double estimate, double newstep)
Member Function Documentation
static void alglib.minbleic.minbleiccreate (int n, double[] x, minbleicstate state) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.minbleic.minbleicinitinternal().
Referenced by alglib.minbleiccreate(), alglib.testminbleicunit.testconv(), alglib.testminbleicunit.testfeasibility(), alglib.testminbleicunit.testgradientcheck(), alglib.testminbleicunit.testother(), and alglib.testminbleicunit.testpreconditioning().
static void alglib.minbleic.minbleiccreatef (int n, double[] x, double diffstep, minbleicstate state) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.minbleic.minbleicinitinternal().
Referenced by alglib.minbleiccreatef(), alglib.testminbleicunit.testfeasibility(), and alglib.testminbleicunit.testother().
static void alglib.minbleic.minbleicsetbc (minbleicstate state, double[] bndl, double[] bndu) inline static
References alglib.ap.assert(), alglib.minbleic.minbleicstate.bndloriginal, alglib.minbleic.minbleicstate.bnduoriginal, alglib.minbleic.minbleicstate.hasbndl, alglib.minbleic.minbleicstate.hasbndu, alglib.math.isfinite(), and alglib.minbleic.minbleicstate.nmain.
Referenced by alglib.minbleicsetbc(), alglib.testminbleicunit.testconv(), alglib.testminbleicunit.testfeasibility(), alglib.testminbleicunit.testgradientcheck(), alglib.testminbleicunit.testother(), and alglib.testminbleicunit.testpreconditioning().
static void alglib.minbleic.minbleicsetlc (minbleicstate state, double c[,], int[] ct, int k) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), alglib.minbleic.minbleicstate.cecnt, alglib.minbleic.minbleicstate.ceoriginal, alglib.minbleic.minbleicstate.ct, alglib.apserv.ivectorsetlengthatleast(), alglib.minbleic.minbleicstate.nmain, and alglib.apserv.rmatrixsetlengthatleast().
Referenced by alglib.minbleic.minbleicinitinternal(), alglib.minbleicsetlc(), alglib.testminbleicunit.testconv(), alglib.testminbleicunit.testfeasibility(), alglib.testminbleicunit.testother(), and alglib.testminbleicunit.testpreconditioning().
static void alglib.minbleic.minbleicsetinnercond (minbleicstate state, double epsg, double epsf, double epsx) inline static
References alglib.ap.assert(), alglib.minbleic.minbleicstate.innerepsf, alglib.minbleic.minbleicstate.innerepsg, alglib.minbleic.minbleicstate.innerepsx, and alglib.math.isfinite().
Referenced by alglib.minbleic.minbleicinitinternal(), alglib.minbleicsetinnercond(), alglib.testminbleicunit.testconv(), alglib.testminbleicunit.testfeasibility(), and alglib.testminbleicunit.testother().
static void alglib.minbleic.minbleicsetoutercond (minbleicstate state, double epsx, double epsi) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.minbleic.minbleicstate.outerepsi, and alglib.minbleic.minbleicstate.outerepsx.
Referenced by alglib.minbleic.minbleicinitinternal(), alglib.minbleicsetoutercond(), alglib.testminbleicunit.testconv(), alglib.testminbleicunit.testfeasibility(), and alglib.testminbleicunit.testother().
static void alglib.minbleic.minbleicsetscale (minbleicstate state, double[] s) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.minbleic.minbleicstate.nmain, and alglib.minbleic.minbleicstate.soriginal.
Referenced by alglib.minbleicsetscale(), alglib.testminbleicunit.testother(), and alglib.testminbleicunit.testpreconditioning().
static void alglib.minbleic.minbleicsetprecdefault (minbleicstate state) inline static
References alglib.minbleic.minbleicstate.prectype.
Referenced by alglib.minbleic.minbleicinitinternal(), alglib.minbleicsetprecdefault(), alglib.testminbleicunit.setrandompreconditioner(), and alglib.testminbleicunit.testpreconditioning().
static void alglib.minbleic.minbleicsetprecdiag (minbleicstate state, double[] d) inline static
References alglib.ap.assert(), alglib.minbleic.minbleicstate.diaghoriginal, alglib.math.isfinite(), alglib.minbleic.minbleicstate.nmain, alglib.minbleic.minbleicstate.prectype, and alglib.apserv.rvectorsetlengthatleast().
Referenced by alglib.minbleicsetprecdiag(), alglib.testminbleicunit.setrandompreconditioner(), alglib.testminbleicunit.testother(), and alglib.testminbleicunit.testpreconditioning().
static void alglib.minbleic.minbleicsetprecscale (minbleicstate state) inline static
References alglib.minbleic.minbleicstate.prectype.
Referenced by alglib.minbleicsetprecscale(), alglib.testminbleicunit.testother(), and alglib.testminbleicunit.testpreconditioning().
static void alglib.minbleic.minbleicsetmaxits (minbleicstate state, int maxits) inline static
References alglib.ap.assert(), and alglib.minbleic.minbleicstate.maxits.
Referenced by alglib.minbleic.minbleicinitinternal(), alglib.minbleicsetmaxits(), and alglib.testminbleicunit.testother().
static void alglib.minbleic.minbleicsetxrep (minbleicstate state, bool needxrep) inline static
References alglib.minbleic.minbleicstate.xrep.
Referenced by alglib.minbleic.minbleicinitinternal(), alglib.minbleicsetxrep(), and alglib.testminbleicunit.testother().
static void alglib.minbleic.minbleicsetstpmax (minbleicstate state, double stpmax) inline static
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.minbleic.minbleicstate.stpmax.
Referenced by alglib.minbleic.minbleicinitinternal(), alglib.minbleicsetstpmax(), and alglib.testminbleicunit.testother().
static bool alglib.minbleic.minbleiciteration (minbleicstate state) inline static
References alglib.minbleic.minbleicstate.activeconstraints, alglib.minbleic.additionalcheckforconstraints(), alglib.ap.assert(), alglib.rcommstate.ba, alglib.minbleic.minbleicstate.bndleffective, alglib.minbleic.minbleicstate.bndloriginal, alglib.minbleic.minbleicstate.bndueffective, alglib.minbleic.minbleicstate.bnduoriginal, alglib.apserv.bvectorsetlengthatleast(), alglib.minbleic.minbleicstate.cecnt, alglib.minbleic.minbleicstate.cecurrent, alglib.minbleic.minbleicstate.ceeffective, alglib.minbleic.minbleicstate.ceoriginal, alglib.minbleic.minbleicstate.cgrep, alglib.minbleic.minbleicstate.cgstate, alglib.minbleic.clearrequestfields(), alglib.minbleic.minbleicstate.constrainedvalues, alglib.minbleic.minbleicstate.ct, alglib.optserv.derivativecheck(), alglib.minbleic.minbleicstate.diagh, alglib.minbleic.minbleicstate.diaghoriginal, alglib.minbleic.minbleicstate.diffstep, alglib.minbleic.minbleicstate.f, alglib.minbleic.minbleicstate.fbase, alglib.optserv.findfeasiblepoint(), alglib.minbleic.minbleicstate.fm1, alglib.minbleic.minbleicstate.fm2, alglib.minbleic.minbleicstate.fp1, alglib.minbleic.minbleicstate.fp2, alglib.minbleic.minbleicstate.g, alglib.minbleic.minbleicstate.gnorm, alglib.minbleic.minbleicstate.hasbndl, alglib.minbleic.minbleicstate.hasbndu, alglib.rcommstate.ia, alglib.minbleic.minbleicstate.innerepsf, alglib.minbleic.minbleicstate.innerepsg, alglib.minbleic.minbleicstate.innerepsx, alglib.minbleic.minbleicstate.itsleft, alglib.minbleic.minbleicstate.lastg, alglib.math.machineepsilon, alglib.minbleic.makegradientprojection(), alglib.minbleic.minbleicstate.maxits, alglib.mincg.mincgcreate(), alglib.mincg.mincgiteration(), alglib.mincg.mincgrestartfrom(), alglib.mincg.mincgresults(), alglib.mincg.mincgsetcond(), alglib.mincg.mincgsetdrep(), alglib.mincg.mincgsetscale(), alglib.mincg.mincgsetstpmax(), alglib.mincg.mincgsetxrep(), alglib.minbleic.modifytargetfunction(), alglib.minbleic.minbleicstate.mpgnorm, alglib.minbleic.minbleicstate.needf, alglib.minbleic.minbleicstate.needfg, alglib.minbleic.minbleicstate.nmain, alglib.minbleic.minbleicstate.nslack, alglib.minbleic.minbleicstate.optdim, alglib.minbleic.minbleicstate.outerepsi, alglib.minbleic.minbleicstate.outerepsx, alglib.minbleic.minbleicstate.prectype, alglib.minbleic.prepareconstraintmatrix(), alglib.minbleic.projectpointandunscale(), alglib.minbleic.minbleicstate.r, alglib.rcommstate.ra, alglib.minbleic.rebuildcexe(), alglib.minbleic.minbleicstate.repdebugdx, alglib.minbleic.minbleicstate.repdebugeqerr, alglib.minbleic.minbleicstate.repdebugfeasgpaits, alglib.minbleic.minbleicstate.repdebugfeasqpits, alglib.minbleic.minbleicstate.repdebugff, alglib.minbleic.minbleicstate.repdebugfs, alglib.minbleic.minbleicstate.repinneriterationscount, alglib.minbleic.minbleicstate.repnfev, alglib.minbleic.minbleicstate.repouteriterationscount, alglib.minbleic.minbleicstate.repterminationtype, alglib.minbleic.minbleicstate.repvaridx, alglib.apserv.rmatrixsetlengthatleast(), alglib.minbleic.minbleicstate.rstate, alglib.apserv.rvectorsetlengthatleast(), alglib.apserv.safeminposrv(), alglib.minbleic.scalegradientandexpand(), alglib.minbleic.minbleicstate.seffective, alglib.minbleic.minbleicstate.soriginal, alglib.math.sqr(), alglib.rcommstate.stage, alglib.minbleic.minbleicstate.stpmax, alglib.minbleic.minbleicstate.teststep, alglib.minbleic.minbleicstate.tmp0, alglib.minbleic.minbleicstate.tmp1, alglib.minbleic.minbleicstate.tmp2, alglib.minbleic.minbleicstate.transforms, alglib.optserv.trimprepare(), alglib.minbleic.minbleicstate.trimthreshold, alglib.minbleic.unscalepoint(), alglib.minbleic.minbleicstate.valuetofreeze, alglib.minbleic.minbleicstate.variabletofreeze, alglib.minbleic.minbleicstate.x, alglib.minbleic.minbleicstate.xcur, alglib.minbleic.minbleicstate.xe, alglib.minbleic.minbleicstate.xend, alglib.minbleic.minbleicstate.xm1, alglib.minbleic.minbleicstate.xp1, alglib.minbleic.minbleicstate.xprev, alglib.minbleic.minbleicstate.xrep, alglib.minbleic.minbleicstate.xstart, and alglib.minbleic.minbleicstate.xupdated.
Referenced by alglib.minbleiciteration(), alglib.testminbleicunit.testconv(), alglib.testminbleicunit.testfeasibility(), alglib.testminbleicunit.testgradientcheck(), alglib.testminbleicunit.testother(), and alglib.testminbleicunit.testpreconditioning().
static void alglib.minbleic.minbleicresults (minbleicstate state, ref double[] x, minbleicreport rep) inline static
References alglib.minbleic.minbleicresultsbuf().
Referenced by alglib.minbleicresults(), alglib.testminbleicunit.testconv(), alglib.testminbleicunit.testfeasibility(), alglib.testminbleicunit.testgradientcheck(), alglib.testminbleicunit.testother(), and alglib.testminbleicunit.testpreconditioning().
static void alglib.minbleic.minbleicresultsbuf (minbleicstate state, ref double[] x, minbleicreport rep) inline static
References alglib.minbleic.minbleicreport.debugdx, alglib.minbleic.minbleicreport.debugeqerr, alglib.minbleic.minbleicreport.debugfeasgpaits, alglib.minbleic.minbleicreport.debugfeasqpits, alglib.minbleic.minbleicreport.debugff, alglib.minbleic.minbleicreport.debugfs, alglib.minbleic.minbleicreport.inneriterationscount, alglib.minbleic.minbleicreport.nfev, alglib.minbleic.minbleicstate.nmain, alglib.minbleic.minbleicreport.outeriterationscount, alglib.minbleic.minbleicstate.repdebugdx, alglib.minbleic.minbleicstate.repdebugeqerr, alglib.minbleic.minbleicstate.repdebugfeasgpaits, alglib.minbleic.minbleicstate.repdebugfeasqpits, alglib.minbleic.minbleicstate.repdebugff, alglib.minbleic.minbleicstate.repdebugfs, alglib.minbleic.minbleicstate.repinneriterationscount, alglib.minbleic.minbleicstate.repnfev, alglib.minbleic.minbleicstate.repouteriterationscount, alglib.minbleic.minbleicstate.repterminationtype, alglib.minbleic.minbleicstate.repvaridx, alglib.minbleic.minbleicreport.terminationtype, alglib.minbleic.minbleicreport.varidx, and alglib.minbleic.minbleicstate.xend.
Referenced by alglib.minbleic.minbleicresults(), and alglib.minbleicresultsbuf().
static void alglib.minbleic.minbleicrestartfrom (minbleicstate state, double[] x) inline static
References alglib.ap.assert(), alglib.rcommstate.ba, alglib.minbleic.clearrequestfields(), alglib.rcommstate.ia, alglib.apserv.isfinitevector(), alglib.minbleic.minbleicstate.nmain, alglib.rcommstate.ra, alglib.minbleic.minbleicstate.rstate, alglib.rcommstate.stage, and alglib.minbleic.minbleicstate.xstart.
Referenced by alglib.minbleic.minbleicinitinternal(), alglib.minbleicrestartfrom(), alglib.testminbleicunit.testconv(), alglib.testminbleicunit.testgradientcheck(), and alglib.testminbleicunit.testpreconditioning().
static void alglib.minbleic.minbleicsetgradientcheck (minbleicstate state, double teststep) inline static
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.minbleic.minbleicstate.teststep.
Referenced by alglib.minbleicsetgradientcheck(), and alglib.testminbleicunit.testgradientcheck().
static void alglib.minbleic.clearrequestfields (minbleicstate state) inline static private
References alglib.minbleic.minbleicstate.needf, alglib.minbleic.minbleicstate.needfg, and alglib.minbleic.minbleicstate.xupdated.
Referenced by alglib.minbleic.minbleiciteration(), and alglib.minbleic.minbleicrestartfrom().
static void alglib.minbleic.unscalepoint (minbleicstate state, double[] xscaled, ref double[] xunscaled) inline static private
References alglib.minbleic.minbleicstate.bndloriginal, alglib.minbleic.minbleicstate.bnduoriginal, alglib.minbleic.minbleicstate.hasbndl, alglib.minbleic.minbleicstate.hasbndu, alglib.minbleic.minbleicstate.nmain, and alglib.minbleic.minbleicstate.transforms.
Referenced by alglib.minbleic.minbleiciteration(), and alglib.minbleic.projectpointandunscale().
static void alglib.minbleic.projectpointandunscale (minbleicstate state, ref double[] xscaled, ref double[] xunscaled, ref double[] rscaled, ref double rnorm2) inline static private
References alglib.minbleic.minbleicstate.activeconstraints, alglib.minbleic.minbleicstate.cecnt, alglib.minbleic.minbleicstate.cecurrent, alglib.minbleic.minbleicstate.nmain, alglib.minbleic.minbleicstate.nslack, alglib.math.sqr(), alglib.minbleic.unscalepoint(), and alglib.minbleic.minbleicstate.xe.
Referenced by alglib.minbleic.minbleiciteration().
static void alglib.minbleic.scalegradientandexpand (minbleicstate state, double[] gunscaled, ref double[] gscaled) inline static private
References alglib.minbleic.minbleicstate.nmain, alglib.minbleic.minbleicstate.nslack, and alglib.minbleic.minbleicstate.transforms.
Referenced by alglib.minbleic.minbleiciteration().
static void alglib.minbleic.modifytargetfunction (minbleicstate state, double[] x, double[] r, double rnorm2, ref double f, ref double[] g, ref double gnorm, ref double mpgnorm) inline static private
References alglib.minbleic.minbleicstate.activeconstraints, alglib.minbleic.minbleicstate.cecnt, alglib.minbleic.minbleicstate.cecurrent, alglib.minbleic.minbleicstate.nmain, and alglib.minbleic.minbleicstate.nslack.
Referenced by alglib.minbleic.minbleiciteration().
static bool alglib.minbleic.additionalcheckforconstraints (minbleicstate state, double[] x) inline static private
References alglib.minbleic.minbleicstate.activeconstraints, alglib.minbleic.minbleicstate.bndleffective, alglib.minbleic.minbleicstate.bndueffective, alglib.minbleic.minbleicstate.constrainedvalues, alglib.minbleic.minbleicstate.hasbndl, alglib.minbleic.minbleicstate.hasbndu, alglib.minbleic.minbleicstate.nmain, and alglib.minbleic.minbleicstate.nslack.
Referenced by alglib.minbleic.minbleiciteration(), and alglib.minbleic.prepareconstraintmatrix().
static void alglib.minbleic.rebuildcexe (minbleicstate state) inline static private
References alglib.minbleic.minbleicstate.activeconstraints, alglib.minbleic.minbleicstate.cecnt, alglib.minbleic.minbleicstate.cecurrent, alglib.minbleic.minbleicstate.ceeffective, alglib.minbleic.minbleicstate.constrainedvalues, alglib.math.machineepsilon, alglib.minbleic.minbleicstate.nmain, alglib.minbleic.minbleicstate.nslack, alglib.ablas.rmatrixcopy(), and alglib.minbleic.minbleicstate.xe.
Referenced by alglib.minbleic.minbleiciteration(), and alglib.minbleic.prepareconstraintmatrix().
static void alglib.minbleic.makegradientprojection (minbleicstate state, ref double[] pg) inline static private
References alglib.minbleic.minbleicstate.activeconstraints, alglib.minbleic.minbleicstate.cecnt, alglib.minbleic.minbleicstate.cecurrent, alglib.minbleic.minbleicstate.nmain, and alglib.minbleic.minbleicstate.nslack.
Referenced by alglib.minbleic.minbleiciteration().
static bool alglib.minbleic.prepareconstraintmatrix (minbleicstate state, double[] x, double[] g, ref double[] px, ref double[] pg) inline static private
References alglib.minbleic.minbleicstate.activeconstraints, alglib.minbleic.additionalcheckforconstraints(), alglib.minbleic.minbleicstate.cecnt, alglib.minbleic.minbleicstate.cecurrent, alglib.minbleic.minbleicstate.ceeffective, alglib.minbleic.minbleicstate.nmain, alglib.minbleic.minbleicstate.nslack, alglib.minbleic.minbleicstate.outerepsi, alglib.minbleic.rebuildcexe(), and alglib.minbleic.minbleicstate.xe.
Referenced by alglib.minbleic.minbleiciteration().
static void alglib.minbleic.minbleicinitinternal (int n, double[] x, double diffstep, minbleicstate state) inline static private
References alglib.minbleic.minbleicstate.bndleffective, alglib.minbleic.minbleicstate.bndloriginal, alglib.minbleic.minbleicstate.bndueffective, alglib.minbleic.minbleicstate.bnduoriginal, alglib.minbleic.minbleicstate.diffstep, alglib.minbleic.minbleicstate.g, alglib.minbleic.minbleicstate.hasbndl, alglib.minbleic.minbleicstate.hasbndu, alglib.minbleic.minbleicrestartfrom(), alglib.minbleic.minbleicsetinnercond(), alglib.minbleic.minbleicsetlc(), alglib.minbleic.minbleicsetmaxits(), alglib.minbleic.minbleicsetoutercond(), alglib.minbleic.minbleicsetprecdefault(), alglib.minbleic.minbleicsetstpmax(), alglib.minbleic.minbleicsetxrep(), alglib.minbleic.minbleicstate.nmain, alglib.minbleic.minbleicstate.optdim, alglib.minbleic.minbleicstate.soriginal, alglib.minbleic.minbleicstate.teststep, alglib.minbleic.minbleicstate.x, and alglib.minbleic.minbleicstate.xstart.
Referenced by alglib.minbleic.minbleiccreate(), and alglib.minbleic.minbleiccreatef().
static void alglib.minbleic.minbleiccreate (int n, double[] x, minbleicstate state) inline static
static void alglib.minbleic.minbleiccreatef (int n, double[] x, double diffstep, minbleicstate state) inline static
static void alglib.minbleic.minbleicsetbc (minbleicstate state, double[] bndl, double[] bndu) inline static
static void alglib.minbleic.minbleicsetlc (minbleicstate state, double c[,], int[] ct, int k) inline static
static void alglib.minbleic.minbleicsetcond (minbleicstate state, double epsg, double epsf, double epsx, int maxits) inline static
Referenced by alglib.minbleicsetcond(), alglib.testminbleicunit.testconv(), alglib.testminbleicunit.testfeasibility(), alglib.testminbleicunit.testother(), and alglib.testminbleicunit.testpreconditioning().
static void alglib.minbleic.minbleicsetscale (minbleicstate state, double[] s) inline static
static void alglib.minbleic.minbleicsetprecdefault (minbleicstate state) inline static
static void alglib.minbleic.minbleicsetprecdiag (minbleicstate state, double[] d) inline static
static void alglib.minbleic.minbleicsetprecscale (minbleicstate state) inline static
static void alglib.minbleic.minbleicsetxrep (minbleicstate state, bool needxrep) inline static
static void alglib.minbleic.minbleicsetdrep (minbleicstate state, bool needdrep) inline static
static void alglib.minbleic.minbleicsetstpmax (minbleicstate state, double stpmax) inline static
static bool alglib.minbleic.minbleiciteration (minbleicstate state) inline static
static void alglib.minbleic.minbleicresults (minbleicstate state, ref double[] x, minbleicreport rep) inline static
static void alglib.minbleic.minbleicresultsbuf (minbleicstate state, ref double[] x, minbleicreport rep) inline static
static void alglib.minbleic.minbleicrestartfrom (minbleicstate state, double[] x) inline static
static void alglib.minbleic.minbleicemergencytermination (minbleicstate state) inline static
static void alglib.minbleic.minbleicsetgradientcheck (minbleicstate state, double teststep) inline static
static void alglib.minbleic.clearrequestfields (minbleicstate state) inline static private
static void alglib.minbleic.minbleicinitinternal (int n, double[] x, double diffstep, minbleicstate state) inline static private
static void alglib.minbleic.updateestimateofgoodstep (ref double estimate, double newstep) inline static private
Member Data Documentation
const double alglib.minbleic.svdtol = 100
const double alglib.minbleic.maxouterits = 20
const double alglib.minbleic.maxnonmonotoniclen = 1.0E5
const double alglib.minbleic.gtol = 0.4
const double alglib.minbleic.initialdecay = 0.5
const double alglib.minbleic.mindecay = 0.1
const double alglib.minbleic.decaycorrection = 0.8
const double alglib.minbleic.penaltyfactor = 100
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/optimization.cs