IGLib: IG.Num.NeuralTrainingTable Class Reference
IG.Num.NeuralTrainingTable Class Reference
Contains Parameters that define neural network architecture and trainig limits, together with achieved results after training such as various error norms.
Public Member Functions
void UpdateTrainingTableDimensionns ()
Updates the list of dimensions of the table of training results (contained in the list TrainingParameters).
int GetIndex (int[] indices)
Returns the index of the element in the onedimensional list that corresponds to the specified indices of the multidimensional table of elements.
void GetIndices (int oneDimensionalIndex, ref int[] tableIndices)
Calculates and stores the multidimensional indices of an element of the multidimensional table of training parameters amd results.
Static Public Member Functions
static void SaveJson (NeuralTrainingTable trainingResults, string filePath)
Saves (serializes) the specified training results object to the specified JSON file. File is owerwritten if it exists.
static void SaveJson (NeuralTrainingTable trainingResults, string filePath, bool append)
Saves (serializes) the specified training results object to the specified JSON file.
static void LoadJson (string filePath, ref NeuralTrainingTable trainingResultsRestored)
Restores (deserializes) a training results object from the specified file in JSON format.
Public Attributes
NeuralTrainingLimits _trainingLimits = null
List< NeuralTrainingParameters > _trainingParameters = null
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
NeuralTrainingLimits TrainingLimits [get, set]
Contains Parameters that define neural network architecture limits and trainig parameter limits.
List< NeuralTrainingParameters > TrainingParameters [get, set]
Contains Parameters that define neural network architecture and trainig procedure, together with achieved results after training such as various error norms.
List< int > TrainingTableDimensions [get, private set]
List of dimensions of the table of training results.
NeuralTrainingParameters this[params
int[] indices [get]
Gets the element of the training table specified by the indices.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
object _mainLock = new object()
List< int > _trainingTableDimensions
Detailed Description
Contains Parameters that define neural network architecture and trainig limits, together with achieved results after training such as various error norms.
Not thread safe!
This class is used for storing parameters and limits of neural networks and restoring them at a later time, in order to repeat training under similar condition or simply to analyse performance of neural networks.
$A Igor Jul10 Aug12; Tako78 Aug12;
Member Function Documentation
void IG.Num.NeuralTrainingTable.UpdateTrainingTableDimensionns () inline
Updates the list of dimensions of the table of training results (contained in the list TrainingParameters).
References IG.Num.NeuralTrainingLimits.IterateThroughMultidimensionalTable().
int IG.Num.NeuralTrainingTable.GetIndex (int[] indices) inline
Returns the index of the element in the onedimensional list that corresponds to the specified indices of the multidimensional table of elements.
Parameters
indices Indices of the element in the multidimensional table of training results.
Returns
One dimensional index that corresponds to the specified multidimensional indices of the element of the multidimensional table of training results.
References IG.Lib.Util.GetIndex().
void IG.Num.NeuralTrainingTable.GetIndices (int oneDimensionalIndex, ref int[] tableIndices) inline
Calculates and stores the multidimensional indices of an element of the multidimensional table of training parameters amd results.
Parameters
oneDimensionalIndex One dimensional index that defines the position of the element in the list of elements.
tableIndices Variable where multidimensional indices of the element are stored.
References IG.Lib.Util.GetIndices().
static void IG.Num.NeuralTrainingTable.SaveJson (NeuralTrainingTable trainingResults, string filePath) inline static
Saves (serializes) the specified training results object to the specified JSON file. File is owerwritten if it exists.
Parameters
trainingResults Object that is saved to a file.
filePath Path to the file into which object is is saved.
static void IG.Num.NeuralTrainingTable.SaveJson (NeuralTrainingTable trainingResults, string filePath, bool append) inline static
Saves (serializes) the specified training results object to the specified JSON file.
Parameters
trainingResults Object that is saved to a file.
filePath Path to the file into which object is is saved.
append Specifies whether serialized data is appended at the end of the file in the case that the file already exists.
static void IG.Num.NeuralTrainingTable.LoadJson (string filePath, ref NeuralTrainingTable trainingResultsRestored) inline static
Restores (deserializes) a training results object from the specified file in JSON format.
Parameters
filePath File from which object data is restored.
trainingResultsRestored Object that is restored by deserialization.
Member Data Documentation
object IG.Num.NeuralTrainingTable._mainLock = new object() private
NeuralTrainingLimits IG.Num.NeuralTrainingTable._trainingLimits = null
List<NeuralTrainingParameters> IG.Num.NeuralTrainingTable._trainingParameters = null
List<int> IG.Num.NeuralTrainingTable._trainingTableDimensions private
Property Documentation
object IG.Num.NeuralTrainingTable.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
NeuralTrainingLimits IG.Num.NeuralTrainingTable.TrainingLimits get set
Contains Parameters that define neural network architecture limits and trainig parameter limits.
Referenced by IG.Num.NeuralTrainingTableDto.CopyFromPlain().
List<NeuralTrainingParameters> IG.Num.NeuralTrainingTable.TrainingParameters get set
Contains Parameters that define neural network architecture and trainig procedure, together with achieved results after training such as various error norms.
Referenced by IG.Num.NeuralTrainingTableDto.CopyFromPlain(), and IG.Num.TestTrainingParametersComparers.Test().
List<int> IG.Num.NeuralTrainingTable.TrainingTableDimensions get private set
List of dimensions of the table of training results.
NeuralTrainingParameters this[params int[] IG.Num.NeuralTrainingTable.indices get
Gets the element of the training table specified by the indices.
Parameters
indices Indices of the element in the table of training parameters.
The documentation for this class was generated from the following file:
igbase/numeric/approximation/neural/NeuralTrainingParameters.cs