IGLib: IG.Script.ScriptGraphics2dBase Class Reference
IG.Script.ScriptGraphics2dBase Class Reference
Base class for script classes with 2D graphics examples.
Public Member Functions
ScriptGraphics2dBase ()
override void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds commands to the internal interpreter.
string TestMyTest (string[] arguments)
Test action.
virtual string TestCustom (string[] arguments)
Custom test.
virtual string TestGraph (string[] arguments)
Demonstration of various 3D plots.
Public Member Functions inherited from IG.Lib.LoadableScriptBase
LoadableScriptBase ()
Argument-less constructor. If argument-less constructor is called then initialization is not performed and will be performed later.
string Run (string[] arguments)
Performs the action of this object. Override this in derived classes!
void Initialize (string[] arguments)
Initializes the object. If not called explicitly, this method is automatically called at the first call to the Run method.
virtual string Script_DefaultInitialize (string[] arguments)
Default initialization method for scripts.
virtual string Script_DefaultRun (string[] arguments)
Default run method for the script. Can be used when only installed commands are run by hte script.
virtual
ICommandLineApplicationInterpreter Script_CreateInterpreterWithoutCommands ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
delegate string Script_CommandDelegate (string[] args)
Delegate for commands that are installed on script's internal interpreter (property Script_Interpreter).
void Script_AddCommand (string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
virtual void Script_AddCommand (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings, string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
string Script_GetHelpString (string scriptCommandName)
Returns help string for internal script command with specified name, or null if help string is not installed for such a command.
void Script_PrintCommandsHelp ()
Prits help for the installed internal commands of the script.
virtual bool Script_ContainsCommand (string commandName)
Returns true if the internal script's interpreter contains a command with specified name, false otherwise.
virtual bool Script_ContainsScriptCommand (string commandName)
Returns true if the specified command is script command (i.e. its first argument is command-name and it is run through the Script_CommandAdapter object).
virtual void Script_RemoveCommand (string commandName)
Removes the specified internal script command from the internal interpreter of the current scripting object.
virtual void Script_RemoveAllCommands ()
Removes ALL internal script commands from the internal interpreter of the current scripting object.
string Script_Run (string[] arguments)
Runs internal script command.
string Script_Run (string commandName, params string[] otherArguments)
Runs internal script command.
virtual void Script_PrintArguments (string messageString, string[] arguments)
Prints the specified array of string arguments (usually passed as command-line arguments).
Public Attributes
const string ConstMyTest = "MyTest"
Name of the command that performs my custom test.
const string ConstHelpMyTest = "Custom test function."
const string ConstCustom = "Custom"
Name of the command for custom test.
const string ConstHelpCustom = "Custom test."
const string ConstGraph = "Graph"
Name of the 2d graphs tests.
const string ConstHelpGraph = "Various 2D graphs. Run with ? argument to see which tests are available."
Public Attributes inherited from IG.Lib.LoadableScriptBase
const string ConstDefaultHelp = "Help"
Default command name for help.
const string ConstHelpDefaultUniversal = "?"
Universal name of the help command.
const string ConstDefaultTestScrip = "TestScript"
Default command name for test method.
Protected Member Functions
override void InitializeThis (string[] arguments)
Initializes the current object.
override string RunThis (string[] arguments)
Runs action of the current object.
void AddGraphCommand (string testName, CommandMethod surfaceMethod, string surfaceHelp)
Adds a new command for a 2D graph test.
virtual void InitTestGraph ()
Initializes commands for 3d graphic tests.
virtual string RunTestGraph (string[] args)
Runs demonstration of surface plots according to arguments.
Protected Member Functions inherited from IG.Lib.LoadableScriptBase
delegate string CommandMethod (string commandName, string[] args)
Delegate for internal command methods.
ICommandLineApplicationInterpreter Script_CreateInterpreter ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
virtual string Script_CommandHelp (string[] arguments)
Prints help.
virtual string Script_CommandTestScript (string[] arguments)
Prints help.
Protected Attributes
List< string > TestGraphNames = new List<string>()
List of installed 2D graph test names.
List< string > TestGraphHelpStrings = new List<string>()
List of help strings corresponding to installed 2D graph tests.
List< CommandMethod > TestGraphMethods = new List<CommandMethod>()
List of methods used to perform 2D graph tests.
Protected Attributes inherited from IG.Lib.LoadableScriptBase
string _embeddedCommandName = null
int _outputLevel = DefaultOutputLevel
ICommandLineApplicationInterpreter _script_interpreter
Private Member Functions
string GraphFunctionSinePlots (string surfaceName, string[] args)
Demonstration of plotting sine curves with different phases.
string GraphFunctionCurvePlotLissajous (string surfaceName, string[] args)
Demonstration of plotting 2d parametric curves (Lissajous curves).
string GraphFunctionDecorations (string surfaceName, string[] args)
Demonstration of different decoration styles for 2D graphs.
string GraphFunctionCurveStylesWithSave (string surfaceName, string[] args)
Demonstration of different curve styles and saving of 2D graphs.
Private Attributes
const string GraphSinePlots = "SinePlots"
const string GraphHelpSinePlots = GraphSinePlots + " <nCurves> <nPoints> : Plot of sine curves with different phases."
const string GraphCurvePlotLissajous = "CurvePlotLissajous"
const string GraphHelpCurvePlotLissajous = GraphCurvePlotLissajous + " <nX> <nY> : Plot of Lissajous curves in 2D."
const string GraphDecorations = "Decorations"
const string GraphHelpDecorations = GraphDecorations + " : Decoration styles on 2D graphs."
const string GraphCurveStylesWithSave = "CurveStylesWithSave"
const string GraphHelpCurveStylesWithSave = GraphCurveStylesWithSave + " <filePath.bmp> : Curve styles and saving of 2D graphs."
bool _graphCommandsInitialized = false
Additional Inherited Members
Properties inherited from IG.Lib.LoadableScriptBase
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
string[] InitializationArguments [get, set]
Arguments used by the initialization method. WARNING: arguments can only be set before initialization is performed. Initialization is performed either implicitly at the first call to the Run method or explicitly by calling the Initialize method.
virtual bool IsInitialized [get, protected set]
Whether the object has been initialized or not.
static int DefaultOutputLevel [get, set]
int OutputLevel [get, set]
Level of output to console produced by some operations of the current object.
virtual
ICommandLineApplicationInterpreter Script_Interpreter [get, protected set]
Script's internal interpreter that takes care for execution of installed internal commands.
SortedList< string, string > Script_CommandHelpStrings [get]
Contains help strings associated with script commands installed on interpreter.
Properties inherited from IG.Lib.ILoadableScript
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
string[] InitializationArguments [get, set]
Arguments used by the initialization method.
bool IsInitialized [get]
Whether the object has been initialized or not.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Detailed Description
Base class for script classes with 2D graphics examples.
$A Igor xx Jul12;
Constructor & Destructor Documentation
IG.Script.ScriptGraphics2dBase.ScriptGraphics2dBase () inline
Member Function Documentation
override void IG.Script.ScriptGraphics2dBase.InitializeThis (string[] arguments) inline protected virtual
Initializes the current object.
Implements IG.Lib.LoadableScriptBase.
override string IG.Script.ScriptGraphics2dBase.RunThis (string[] arguments) inline protected virtual
Runs action of the current object.
Parameters
arguments Command-line arguments of the action.
Implements IG.Lib.LoadableScriptBase.
override void IG.Script.ScriptGraphics2dBase.Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings) inline virtual
Adds commands to the internal interpreter.
Parameters
interpreter Interpreter where commands are executed.
helpStrings List containg help strings.
Reimplemented from IG.Lib.LoadableScriptBase.
string IG.Script.ScriptGraphics2dBase.TestMyTest (string[] arguments) inline
Test action.
Parameters
arguments Array of command-line arguments.
virtual string IG.Script.ScriptGraphics2dBase.TestCustom (string[] arguments) inline virtual
Custom test.
void IG.Script.ScriptGraphics2dBase.AddGraphCommand (string testName, CommandMethod surfaceMethod, string surfaceHelp) inline protected
Adds a new command for a 2D graph test.
Parameters
testName Test name.
surfaceMethod Method used to perform the test.
surfaceHelp Eventual help string for the test.
string IG.Script.ScriptGraphics2dBase.GraphFunctionSinePlots (string surfaceName, string[] args) inline private
Demonstration of plotting sine curves with different phases.
References IG.Gr.PlotterZedGraph.ExempleSinePlots().
string IG.Script.ScriptGraphics2dBase.GraphFunctionCurvePlotLissajous (string surfaceName, string[] args) inline private
Demonstration of plotting 2d parametric curves (Lissajous curves).
References IG.Gr.PlotterZedGraph.ExampleLissajous().
string IG.Script.ScriptGraphics2dBase.GraphFunctionDecorations (string surfaceName, string[] args) inline private
Demonstration of different decoration styles for 2D graphs.
References IG.Gr.PlotterZedGraph.ExampleDecorations().
string IG.Script.ScriptGraphics2dBase.GraphFunctionCurveStylesWithSave (string surfaceName, string[] args) inline private
Demonstration of different curve styles and saving of 2D graphs.
References IG.Gr.PlotterZedGraph.ExampleCurveStylesWithSave().
virtual void IG.Script.ScriptGraphics2dBase.InitTestGraph () inline protected virtual
Initializes commands for 3d graphic tests.
virtual string IG.Script.ScriptGraphics2dBase.RunTestGraph (string[] args) inline protected virtual
Runs demonstration of surface plots according to arguments.
virtual string IG.Script.ScriptGraphics2dBase.TestGraph (string[] arguments) inline virtual
Demonstration of various 3D plots.
Member Data Documentation
const string IG.Script.ScriptGraphics2dBase.ConstMyTest = "MyTest"
Name of the command that performs my custom test.
const string IG.Script.ScriptGraphics2dBase.ConstHelpMyTest = "Custom test function."
const string IG.Script.ScriptGraphics2dBase.ConstCustom = "Custom"
Name of the command for custom test.
const string IG.Script.ScriptGraphics2dBase.ConstHelpCustom = "Custom test."
const string IG.Script.ScriptGraphics2dBase.ConstGraph = "Graph"
Name of the 2d graphs tests.
const string IG.Script.ScriptGraphics2dBase.ConstHelpGraph = "Various 2D graphs. Run with ? argument to see which tests are available."
List<string> IG.Script.ScriptGraphics2dBase.TestGraphNames = new List<string>() protected
List of installed 2D graph test names.
List<string> IG.Script.ScriptGraphics2dBase.TestGraphHelpStrings = new List<string>() protected
List of help strings corresponding to installed 2D graph tests.
List<CommandMethod> IG.Script.ScriptGraphics2dBase.TestGraphMethods = new List<CommandMethod>() protected
List of methods used to perform 2D graph tests.
const string IG.Script.ScriptGraphics2dBase.GraphSinePlots = "SinePlots" private
const string IG.Script.ScriptGraphics2dBase.GraphHelpSinePlots = GraphSinePlots + " <nCurves> <nPoints> : Plot of sine curves with different phases." private
const string IG.Script.ScriptGraphics2dBase.GraphCurvePlotLissajous = "CurvePlotLissajous" private
const string IG.Script.ScriptGraphics2dBase.GraphHelpCurvePlotLissajous = GraphCurvePlotLissajous + " <nX> <nY> : Plot of Lissajous curves in 2D." private
const string IG.Script.ScriptGraphics2dBase.GraphDecorations = "Decorations" private
const string IG.Script.ScriptGraphics2dBase.GraphHelpDecorations = GraphDecorations + " : Decoration styles on 2D graphs." private
const string IG.Script.ScriptGraphics2dBase.GraphCurveStylesWithSave = "CurveStylesWithSave" private
const string IG.Script.ScriptGraphics2dBase.GraphHelpCurveStylesWithSave = GraphCurveStylesWithSave + " <filePath.bmp> : Curve styles and saving of 2D graphs." private
bool IG.Script.ScriptGraphics2dBase._graphCommandsInitialized = false private
The documentation for this class was generated from the following file:
iglib/extensions/iglibext/00testscriptsext/examples/ScriptGraphics2dBase.cs