IGLib: Test.SquareMatrixTest Class Reference
Test.SquareMatrixTest Class Reference
Public Member Functions
void SquareMatrixInvalidDimensionTest ()
void SquareMatrixAccess ()
void SquareMatrixArithmetic ()
void SquareVandermondeMatrixInverse ()
void SquareRandomMatrixInverse ()
void SquareRandomMatrixQRDecomposition ()
void SquareRandomMatrixLUDecomposition ()
void SquareVandermondeMatrixLUDecomposition ()
void SquareVandermondeMatrixEigenvalues ()
void SquareRandomMatrixEigenvalues ()
void SquareUnitMatrixLUDecomposition ()
void SquareUnitMatrixEigensystem ()
void SquareMatrixDifficultEigensystem ()
void KnownEigenvalues ()
void DegenerateEigenvalues ()
void SquareMatrixStochasticEigensystem ()
void TimedEigenvalues ()
void SquareMatrixNorms ()
void HilbertMatrixSVD ()
void CompanionMatrixEigenvalues ()
void MatrixPeriodTest ()
void SvdOfRankOneMatrix ()
Static Public Member Functions
static void PrintMatrix (AnyRectangularMatrix M)
static void PrintMatrix (double[,] A)
Static Private Member Functions
static SquareMatrix CreateSquareRandomMatrix (int n)
static SquareMatrix CreateSquareRandomMatrix (int n, int seed)
static SquareMatrix CreateVandermondeMatrix (int n)
static SquareMatrix CreateVandermondeMatrix (double[] x)
Member Function Documentation
static void Test.SquareMatrixTest.PrintMatrix (AnyRectangularMatrix M) inline static
References Meta.Numerics.Matrices.AnyMatrix< T >.ColumnCount, and Meta.Numerics.Matrices.AnyMatrix< T >.RowCount.
Referenced by Test.SquareMatrixTest.SquareVandermondeMatrixInverse().
static SquareMatrix Test.SquareMatrixTest.CreateSquareRandomMatrix (int n) inline static private
Referenced by Test.SquareMatrixTest.SquareMatrixArithmetic(), Test.SquareMatrixTest.SquareMatrixNorms(), Test.SquareMatrixTest.SquareRandomMatrixEigenvalues(), Test.SquareMatrixTest.SquareRandomMatrixInverse(), Test.SquareMatrixTest.SquareRandomMatrixLUDecomposition(), and Test.SquareMatrixTest.SquareRandomMatrixQRDecomposition().
static SquareMatrix Test.SquareMatrixTest.CreateSquareRandomMatrix (int n, int seed) inline static private
static SquareMatrix Test.SquareMatrixTest.CreateVandermondeMatrix (int n) inline static private
Referenced by Test.SquareMatrixTest.SquareMatrixAccess(), Test.SquareMatrixTest.SquareMatrixNorms(), Test.SquareMatrixTest.SquareVandermondeMatrixEigenvalues(), Test.SquareMatrixTest.SquareVandermondeMatrixInverse(), and Test.SquareMatrixTest.SquareVandermondeMatrixLUDecomposition().
static SquareMatrix Test.SquareMatrixTest.CreateVandermondeMatrix (double[] x) inline static private
void Test.SquareMatrixTest.SquareMatrixInvalidDimensionTest () inline
void Test.SquareMatrixTest.SquareMatrixAccess () inline
References Meta.Numerics.Matrices.SquareMatrix.Column(), Meta.Numerics.Matrices.SquareMatrix.Copy(), Test.SquareMatrixTest.CreateVandermondeMatrix(), Meta.Numerics.Matrices.SquareMatrix.Dimension, Meta.Numerics.Matrices.VectorBase.Dimension, and Meta.Numerics.Matrices.SquareMatrix.Row().
void Test.SquareMatrixTest.SquareMatrixArithmetic () inline
References Test.SquareMatrixTest.CreateSquareRandomMatrix(), and Meta.Numerics.Matrices.SquareMatrix.Transpose().
void Test.SquareMatrixTest.SquareVandermondeMatrixInverse () inline
References Test.SquareMatrixTest.CreateVandermondeMatrix(), Meta.Numerics.Matrices.SquareMatrix.Inverse(), and Test.SquareMatrixTest.PrintMatrix().
void Test.SquareMatrixTest.SquareRandomMatrixInverse () inline
References Test.SquareMatrixTest.CreateSquareRandomMatrix(), and Meta.Numerics.Matrices.SquareMatrix.Inverse().
void Test.SquareMatrixTest.SquareRandomMatrixQRDecomposition () inline
References Test.SquareMatrixTest.CreateSquareRandomMatrix(), Meta.Numerics.Matrices.SquareMatrix.Dimension, Meta.Numerics.Matrices.SquareQRDecomposition.Dimension, Meta.Numerics.Matrices.SquareQRDecomposition.Inverse(), Meta.Numerics.Matrices.SquareQRDecomposition.QMatrix(), Meta.Numerics.Matrices.SquareMatrix.QRDecomposition(), Meta.Numerics.Matrices.SquareQRDecomposition.RMatrix(), and Meta.Numerics.Matrices.SquareQRDecomposition.Solve().
void Test.SquareMatrixTest.SquareRandomMatrixLUDecomposition () inline
References Test.SquareMatrixTest.CreateSquareRandomMatrix(), Meta.Numerics.Matrices.LUDecomposition.Dimension, Meta.Numerics.Matrices.LUDecomposition.Inverse(), Meta.Numerics.Matrices.LUDecomposition.LMatrix(), Meta.Numerics.Matrices.SquareMatrix.LUDecomposition(), Meta.Numerics.Matrices.LUDecomposition.PMatrix(), Meta.Numerics.Matrices.LUDecomposition.Solve(), and Meta.Numerics.Matrices.LUDecomposition.UMatrix().
void Test.SquareMatrixTest.SquareVandermondeMatrixLUDecomposition () inline
References Test.SquareMatrixTest.CreateVandermondeMatrix(), Meta.Numerics.Matrices.LUDecomposition.Determinant(), Meta.Numerics.Matrices.LUDecomposition.Inverse(), Meta.Numerics.Matrices.LUDecomposition.LMatrix(), Meta.Numerics.Matrices.SquareMatrix.LUDecomposition(), Meta.Numerics.Matrices.LUDecomposition.PMatrix(), Meta.Numerics.Matrices.LUDecomposition.Solve(), and Meta.Numerics.Matrices.LUDecomposition.UMatrix().
void Test.SquareMatrixTest.SquareVandermondeMatrixEigenvalues () inline
References Test.SquareMatrixTest.CreateVandermondeMatrix(), Meta.Numerics.Matrices.SquareMatrix.Eigensystem(), Meta.Numerics.Matrices.ComplexEigensystem.Eigenvalue(), Meta.Numerics.Matrices.ComplexEigensystem.Eigenvector(), Meta.Numerics.Complex.Re, and Meta.Numerics.Matrices.AnySquareMatrix.Trace().
void Test.SquareMatrixTest.SquareRandomMatrixEigenvalues () inline
References Test.SquareMatrixTest.CreateSquareRandomMatrix(), Meta.Numerics.Matrices.ComplexEigensystem.Dimension, Meta.Numerics.Matrices.SquareMatrix.Eigensystem(), Meta.Numerics.Matrices.ComplexEigensystem.Eigenvalue(), Meta.Numerics.Matrices.ComplexEigensystem.Eigenvector(), and Meta.Numerics.Matrices.AnySquareMatrix.Trace().
void Test.SquareMatrixTest.SquareUnitMatrixLUDecomposition () inline
References Meta.Numerics.Matrices.LUDecomposition.Determinant(), Meta.Numerics.Matrices.LUDecomposition.Inverse(), Meta.Numerics.Matrices.SquareMatrix.LUDecomposition(), and Meta.Numerics.Matrices.AnySquareMatrix.Trace().
void Test.SquareMatrixTest.SquareUnitMatrixEigensystem () inline
References Meta.Numerics.Matrices.ComplexEigensystem.Dimension, Meta.Numerics.Matrices.SquareMatrix.Eigensystem(), Meta.Numerics.Matrices.ComplexEigensystem.Eigenvalue(), and Meta.Numerics.Matrices.ComplexEigensystem.Eigenvector().
void Test.SquareMatrixTest.SquareMatrixDifficultEigensystem () inline
References Meta.Numerics.Matrices.ComplexEigensystem.Dimension, Meta.Numerics.Matrices.SquareMatrix.Eigensystem(), Meta.Numerics.Matrices.ComplexEigensystem.Eigenvalue(), and Meta.Numerics.Matrices.ComplexEigensystem.Eigenvector().
void Test.SquareMatrixTest.KnownEigenvalues () inline
References Meta.Numerics.Matrices.SquareMatrix.Eigenvalues().
void Test.SquareMatrixTest.DegenerateEigenvalues () inline
References Meta.Numerics.Matrices.SquareMatrix.Eigensystem().
void Test.SquareMatrixTest.SquareMatrixStochasticEigensystem () inline
References Meta.Numerics.Matrices.ComplexEigensystem.Dimension, Meta.Numerics.Matrices.SquareMatrix.Eigensystem(), Meta.Numerics.Matrices.ComplexEigensystem.Eigenvalue(), and Meta.Numerics.Matrices.ComplexEigensystem.Eigenvector().
static void Test.SquareMatrixTest.PrintMatrix (double A[,]) inline static
void Test.SquareMatrixTest.TimedEigenvalues () inline
References Meta.Numerics.Matrices.SquareMatrix.Eigenvalues().
void Test.SquareMatrixTest.SquareMatrixNorms () inline
References Test.SquareMatrixTest.CreateSquareRandomMatrix(), Test.SquareMatrixTest.CreateVandermondeMatrix(), Meta.Numerics.Matrices.AnyRectangularMatrix.FrobeniusNorm(), Meta.Numerics.Matrices.SquareMatrix.InfinityNorm(), and Meta.Numerics.Matrices.SquareMatrix.OneNorm().
void Test.SquareMatrixTest.HilbertMatrixSVD () inline
References Meta.Numerics.Matrices.SingularValueDecomposition.Dimension, Meta.Numerics.Matrices.SingularValueDecomposition.LeftTransformMatrix(), Meta.Numerics.Matrices.SingularValueDecomposition.RightTransformMatrix(), Meta.Numerics.Matrices.SingularValueDecomposition.SingularValue(), Meta.Numerics.Matrices.SquareMatrix.SingularValueDecomposition(), and Meta.Numerics.Matrices.SquareMatrix.Transpose().
void Test.SquareMatrixTest.CompanionMatrixEigenvalues () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient(), Meta.Numerics.Matrices.ComplexEigensystem.Dimension, Meta.Numerics.Matrices.SquareMatrix.Eigensystem(), and Meta.Numerics.Matrices.ComplexEigensystem.Eigenvalue().
void Test.SquareMatrixTest.MatrixPeriodTest () inline
References Meta.Numerics.Matrices.SquareMatrix.Power().
void Test.SquareMatrixTest.SvdOfRankOneMatrix () inline
References Meta.Numerics.Matrices.SingularValueDecomposition.Dimension, Meta.Numerics.Matrices.SingularValueDecomposition.SingularValue(), Meta.Numerics.Matrices.RectangularMatrix.SingularValueDecomposition(), and Meta.Numerics.Matrices.ColumnVector.Transpose().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/SquareMatrixTest.cs