IGLib: NUnit.Framework.Tests.ActionAttributeTests Class Reference
NUnit.Framework.Tests.ActionAttributeTests Class Reference
Public Member Functions
void Setup ()
void TestsRunSuccessfully ()
void ExpectedOutput_InCorrectOrder ()
void ActionsWrappingAssembly ()
void ActionsWrappingSetUpFixture ()
void ActionsWrappingTestFixture ()
void ActionsWrappingParameterizedMethodSuite ()
void CorrectNumberOfEventsReceived ()
void ActionsWrappingTestMethod (string testName)
Private Member Functions
void CheckActionsOnSuite (string suiteName, int firstEvent, int lastEvent, params string[] tags)
void CheckActionsOnTestCase (string testName)
void CheckBeforeAfterActionPair (int index1, int index2, string testName, string tag)
Private Attributes
ITestResult _result = null
int _numEvents = -1
Static Private Attributes
static readonly string ASSEMBLY_PATH = AssemblyHelper.GetAssemblyPath(typeof(ActionAttributeFixture))
static readonly string ASSEMBLY_NAME = System.IO.Path.GetFileName(ASSEMBLY_PATH)
static readonly string[] ExpectedAssemblyActions
static readonly string[] ExpectedSetUpFixtureActions
static readonly string[] ExpectedTestFixtureActions
static readonly string[] ExpectedParameterizedTestActions
static readonly string[] ExpectedTestCaseActions
static readonly List< string > ExpectedEvents
static readonly int NumTestCaseActions = ExpectedTestCaseActions.Length
static readonly int EventsPerTestCase = 2 * NumTestCaseActions + 1
static readonly int NumTestCaseEvents = 3 * EventsPerTestCase
static readonly int NumParameterizedTestActions = ExpectedParameterizedTestActions.Length
static readonly int NumTestFixtureActions = ExpectedTestFixtureActions.Length
static readonly int NumSetUpFixtureActions = ExpectedSetUpFixtureActions.Length
static readonly int NumAssemblyActions = ExpectedAssemblyActions.Length
Member Function Documentation
void NUnit.Framework.Tests.ActionAttributeTests.Setup () inline
References NUnit.TestData.ActionAttributeTests.ActionAttributeFixture.ClearResults(), NUnit.Framework.Is.EqualTo(), NUnit.TestData.ActionAttributeTests.ActionAttributeFixture.Events, NUnit.Framework.Assert.NotNull(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Tests.ActionAttributeTests.TestsRunSuccessfully () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Interfaces.ResultState.Success, and NUnit.Framework.Assert.That().
void NUnit.Framework.Tests.ActionAttributeTests.ExpectedOutput_InCorrectOrder () inline
References NUnit.TestData.ActionAttributeTests.ActionAttributeFixture.Events, and NUnit.Framework.Assert.Fail().
void NUnit.Framework.Tests.ActionAttributeTests.ActionsWrappingAssembly () inline
void NUnit.Framework.Tests.ActionAttributeTests.ActionsWrappingSetUpFixture () inline
void NUnit.Framework.Tests.ActionAttributeTests.ActionsWrappingTestFixture () inline
void NUnit.Framework.Tests.ActionAttributeTests.ActionsWrappingParameterizedMethodSuite () inline
References NUnit.TestData.ActionAttributeTests.ActionAttributeFixture.Events, NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assume.That().
void NUnit.Framework.Tests.ActionAttributeTests.CorrectNumberOfEventsReceived () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestData.ActionAttributeTests.ActionAttributeFixture.Events, and NUnit.Framework.Assert.That().
void NUnit.Framework.Tests.ActionAttributeTests.ActionsWrappingTestMethod (string testName) inline
void NUnit.Framework.Tests.ActionAttributeTests.CheckActionsOnSuite (string suiteName, int firstEvent, int lastEvent, params string[] tags) inline private
References NUnit.TestData.ActionAttributeTests.ActionAttributeFixture.Events, NUnit.Framework.Does.Not, and NUnit.Framework.Assert.That().
void NUnit.Framework.Tests.ActionAttributeTests.CheckActionsOnTestCase (string testName) inline private
References NUnit.TestData.ActionAttributeTests.ActionAttributeFixture.Events, NUnit.Framework.Is.GreaterThanOrEqualTo(), NUnit.Framework.Does.Not, and NUnit.Framework.Assert.That().
void NUnit.Framework.Tests.ActionAttributeTests.CheckBeforeAfterActionPair (int index1, int index2, string testName, string tag) inline private
References NUnit.Framework.Does.EndWith(), NUnit.TestData.ActionAttributeTests.ActionAttributeFixture.Events, NUnit.Framework.Does.StartWith(), and NUnit.Framework.Assert.That().
Member Data Documentation
readonly string NUnit.Framework.Tests.ActionAttributeTests.ASSEMBLY_PATH = AssemblyHelper.GetAssemblyPath(typeof(ActionAttributeFixture)) static private
readonly string NUnit.Framework.Tests.ActionAttributeTests.ASSEMBLY_NAME = System.IO.Path.GetFileName(ASSEMBLY_PATH) static private
ITestResult NUnit.Framework.Tests.ActionAttributeTests._result = null private
int NUnit.Framework.Tests.ActionAttributeTests._numEvents = -1 private
readonly string [] NUnit.Framework.Tests.ActionAttributeTests.ExpectedAssemblyActions static private
Initial value:
= new string[] {
                        "OnAssembly", "OnAssembly", "OnAssembly" }
readonly string [] NUnit.Framework.Tests.ActionAttributeTests.ExpectedSetUpFixtureActions static private
Initial value:
= new string[] {
                        "OnBaseSetupFixture", "OnBaseSetupFixture", "OnBaseSetupFixture",
                        "OnSetupFixture", "OnSetupFixture", "OnSetupFixture"
        }
readonly string [] NUnit.Framework.Tests.ActionAttributeTests.ExpectedTestFixtureActions static private
Initial value:
= new string[] {
                        "OnBaseInterface", "OnBaseInterface", "OnBaseInterface",
                        "OnBaseFixture", "OnBaseFixture", "OnBaseFixture",
                        "OnInterface", "OnInterface", "OnInterface",
                        "OnFixture", "OnFixture", "OnFixture"
        }
readonly string [] NUnit.Framework.Tests.ActionAttributeTests.ExpectedParameterizedTestActions static private
Initial value:
= new string[] {
                        "OnMethod", "OnMethod"
        }
readonly string [] NUnit.Framework.Tests.ActionAttributeTests.ExpectedTestCaseActions static private
Initial value:
= new string[] {
                        "OnMethod", "OnMethod", "OnMethod",
                        "OnFixture", "OnFixture",
                        "OnInterface", "OnInterface",
                        "OnBaseFixture", "OnBaseFixture",
                        "OnBaseInterface", "OnBaseInterface",
                        "OnSetupFixture", "OnSetupFixture",
                        "OnBaseSetupFixture", "OnBaseSetupFixture",
                        "OnAssembly", "OnAssembly"
        }
readonly List<string> NUnit.Framework.Tests.ActionAttributeTests.ExpectedEvents static private
readonly int NUnit.Framework.Tests.ActionAttributeTests.NumTestCaseActions = ExpectedTestCaseActions.Length static private
readonly int NUnit.Framework.Tests.ActionAttributeTests.EventsPerTestCase = 2 * NumTestCaseActions + 1 static private
readonly int NUnit.Framework.Tests.ActionAttributeTests.NumTestCaseEvents = 3 * EventsPerTestCase static private
readonly int NUnit.Framework.Tests.ActionAttributeTests.NumParameterizedTestActions = ExpectedParameterizedTestActions.Length static private
readonly int NUnit.Framework.Tests.ActionAttributeTests.NumTestFixtureActions = ExpectedTestFixtureActions.Length static private
readonly int NUnit.Framework.Tests.ActionAttributeTests.NumSetUpFixtureActions = ExpectedSetUpFixtureActions.Length static private
readonly int NUnit.Framework.Tests.ActionAttributeTests.NumAssemblyActions = ExpectedAssemblyActions.Length static private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/ActionAttributeTests.cs