IGLib: Meta.Numerics.Statistics.Distributions.GumbelDistribution Class Reference
Meta.Numerics.Statistics.Distributions.GumbelDistribution Class Reference
Represents a Gumbel distribution.
Public Member Functions
GumbelDistribution ()
Initializes a new standard Gumbel distribution.
GumbelDistribution (double location, double scale)
Initializes a new Gumbel distribution with the given parameters.
override double ProbabilityDensity (double x)
Returns the probability density at the given point.
Parameters
x The reference point.
Returns
The probability density p(x).
The probability density function (PDF) gives the relative probability of obtaining different values.
override double LeftProbability (double x)
Returns the cumulative probability to the left of (below) the given point.
Parameters
x The reference point.
Returns
The integrated probability to obtain a result below the reference point.
The left probability function is commonly called the cumulative distribution function (CDF).
override double RightProbability (double x)
Return the cumulative probability to the right of (above) the given point.
Parameters
x The reference point.
Returns
The integrated probability 1-P(x1) to obtain a result above the reference point.
In survival analysis, the right probability function is commonly called the survival function, because it gives the fraction of the population remaining after the given time.
override double InverseLeftProbability (double P)
Returns the point at which the cumulative distribution function attains a given value.
Parameters
P The left cumulative probability P, which must lie between 0 and 1.
Returns
The value x at which LeftProbability equals P.
The inverse left probability is commonly called the quantile function. Given a quantile, it tells which variable value is the lower border of that quantile.
override double MomentAboutMean (int r)
Computes a central moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth central moment of the distribution.
See also
Moment
override double Moment (int r)
Computes a raw moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth raw moment of the distribution.
See also
Moment
override double Cumulant (int r)
Computes a cumulant of the distribution.
Parameters
r The index of the cumulant to compute.
Returns
The rth cumulant of the distribution.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double InverseRightProbability (double Q)
Returns the point at which the right probability function attains the given value.
virtual double ExpectationValue (Func< double, double > f)
Computes the expectation value of the given function.
virtual double GetRandomValue (Random rng)
Returns a random value.
Properties
override Interval Support [get]
double LocationParameter [get]
Gets the location parameter of the distribution.
double ScaleParameter [get]
Gets the scale parameter of the distribution.
override double Median [get]
override double Mean [get]
override double Variance [get]
override double StandardDeviation [get]
override double Skewness [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double Median [get]
Gets the median of the distribution.
virtual Interval Support [get]
Gets the interval over which the distribution is nonvanishing.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Private Attributes
readonly double m
readonly double s
Detailed Description
Represents a Gumbel distribution.
Constructor & Destructor Documentation
Meta.Numerics.Statistics.Distributions.GumbelDistribution.GumbelDistribution () inline
Initializes a new standard Gumbel distribution.
Meta.Numerics.Statistics.Distributions.GumbelDistribution.GumbelDistribution (double location, double scale) inline
Initializes a new Gumbel distribution with the given parameters.
Parameters
location The location parameter.
scale The scale parameter, which must be positive.
Exceptions
ArgumentOutOfRangeException scale is negative or zero.
Member Function Documentation
override double Meta.Numerics.Statistics.Distributions.GumbelDistribution.ProbabilityDensity (double x) inline virtual
Returns the probability density at the given point.
Parameters
x The reference point.
Returns
The probability density p(x).
The probability density function (PDF) gives the relative probability of obtaining different values.
Implements Meta.Numerics.Statistics.Distributions.Distribution.
override double Meta.Numerics.Statistics.Distributions.GumbelDistribution.LeftProbability (double x) inline virtual
Returns the cumulative probability to the left of (below) the given point.
Parameters
x The reference point.
Returns
The integrated probability to obtain a result below the reference point.
The left probability function is commonly called the cumulative distribution function (CDF).
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
override double Meta.Numerics.Statistics.Distributions.GumbelDistribution.RightProbability (double x) inline virtual
Return the cumulative probability to the right of (above) the given point.
Parameters
x The reference point.
Returns
The integrated probability 1-P(x1) to obtain a result above the reference point.
In survival analysis, the right probability function is commonly called the survival function, because it gives the fraction of the population remaining after the given time.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.MoreMath.ExpMinusOne().
override double Meta.Numerics.Statistics.Distributions.GumbelDistribution.InverseLeftProbability (double P) inline virtual
Returns the point at which the cumulative distribution function attains a given value.
Parameters
P The left cumulative probability P, which must lie between 0 and 1.
Returns
The value x at which LeftProbability equals P.
The inverse left probability is commonly called the quantile function. Given a quantile, it tells which variable value is the lower border of that quantile.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
override double Meta.Numerics.Statistics.Distributions.GumbelDistribution.MomentAboutMean (int r) inline virtual
Computes a central moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth central moment of the distribution.
See also
Moment
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
override double Meta.Numerics.Statistics.Distributions.GumbelDistribution.Moment (int r) inline virtual
Computes a raw moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth raw moment of the distribution.
See also
Moment
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
override double Meta.Numerics.Statistics.Distributions.GumbelDistribution.Cumulant (int r) inline virtual
Computes a cumulant of the distribution.
Parameters
r The index of the cumulant to compute.
Returns
The rth cumulant of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.UnivariateDistribution.
References Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Functions.AdvancedMath.RiemannZeta().
Member Data Documentation
readonly double Meta.Numerics.Statistics.Distributions.GumbelDistribution.m private
readonly double Meta.Numerics.Statistics.Distributions.GumbelDistribution.s private
Property Documentation
override Interval Meta.Numerics.Statistics.Distributions.GumbelDistribution.Support get
double Meta.Numerics.Statistics.Distributions.GumbelDistribution.LocationParameter get
Gets the location parameter of the distribution.
double Meta.Numerics.Statistics.Distributions.GumbelDistribution.ScaleParameter get
Gets the scale parameter of the distribution.
override double Meta.Numerics.Statistics.Distributions.GumbelDistribution.Median get
override double Meta.Numerics.Statistics.Distributions.GumbelDistribution.Mean get
override double Meta.Numerics.Statistics.Distributions.GumbelDistribution.Variance get
override double Meta.Numerics.Statistics.Distributions.GumbelDistribution.StandardDeviation get
override double Meta.Numerics.Statistics.Distributions.GumbelDistribution.Skewness get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/GumbelDistribution.cs