IGLib: alglib.snnls Class Reference
alglib.snnls Class Reference
Classes
class snnlssolver
Static Public Member Functions
static void snnlsinit (int nsmax, int ndmax, int nrmax, snnlssolver s)
static void snnlssetproblem (snnlssolver s, double[,] a, double[] b, int ns, int nd, int nr)
static void snnlsdropnnc (snnlssolver s, int idx)
static void snnlssolve (snnlssolver s, ref double[] x)
Public Attributes
const int iterativerefinementits = 3
Static Private Member Functions
static bool boundedstepandactivation (double[] xc, double[] xn, bool[] nnc, int n)
Member Function Documentation
static void alglib.snnls.snnlsinit (int nsmax, int ndmax, int nrmax, snnlssolver s) inline static
References alglib.snnls.snnlssolver.b, alglib.apserv.bvectorsetlengthatleast(), alglib.snnls.snnlssolver.debugflops, alglib.snnls.snnlssolver.debugmaxnewton, alglib.snnls.snnlssolver.densea, alglib.snnls.iterativerefinementits, alglib.snnls.snnlssolver.nd, alglib.snnls.snnlssolver.nnc, alglib.snnls.snnlssolver.nr, alglib.snnls.snnlssolver.ns, alglib.snnls.snnlssolver.refinementits, alglib.apserv.rmatrixsetlengthatleast(), alglib.apserv.rvectorsetlengthatleast(), alglib.snnls.snnlssolver.tmpca, and alglib.snnls.snnlssolver.tmpz.
Referenced by alglib.testsnnlsunit.testsnnls().
static void alglib.snnls.snnlssetproblem (snnlssolver s, double a[,], double[] b, int ns, int nd, int nr) inline static
References alglib.ap.assert().
Referenced by alglib.testsnnlsunit.testsnnls().
static void alglib.snnls.snnlsdropnnc (snnlssolver s, int idx) inline static
Referenced by alglib.testsnnlsunit.testsnnls().
static void alglib.snnls.snnlssolve (snnlssolver s, ref double[] x) inline static
Referenced by alglib.testsnnlsunit.testsnnls().
static bool alglib.snnls.boundedstepandactivation (double[] xc, double[] xn, bool[] nnc, int n) inline static private
Member Data Documentation
const int alglib.snnls.iterativerefinementits = 3
Referenced by alglib.snnls.snnlsinit().
The documentation for this class was generated from the following file:
igtest/numerics/alglib_0.8.2/src/optimization.cs