IGLib: NUnit.Common.ExtendedTextWrapper Class Reference
NUnit.Common.ExtendedTextWrapper Class Reference
ExtendedTextWrapper wraps a TextWriter and makes it look like an ExtendedTextWriter. All style indications are ignored. It's used when text is being written to a file.
Public Member Functions
ExtendedTextWrapper (TextWriter writer)
override void Write (char value)
Write a single char value
override void Write (string value)
Write a string value
override void WriteLine (string value)
Write a string value followed by a NewLine
override void Close ()
Close the ExtendedTextWriter
override void Write (ColorStyle style, string value)
Writes the value with the specified style.
override void WriteLine (ColorStyle style, string value)
Writes the value with the specified style
override void WriteLabel (string label, object option)
Writes the label and the option that goes with it.
override void WriteLabel (string label, object option, ColorStyle valueStyle)
Writes the label and the option that goes with it.
override void WriteLabelLine (string label, object option)
Writes the label and the option that goes with it followed by a new line.
override void WriteLabelLine (string label, object option, ColorStyle valueStyle)
Writes the label and the option that goes with it followed by a new line.
Protected Member Functions
override void Dispose (bool disposing)
Dispose the Extended TextWriter
Properties
override Encoding Encoding [get]
Gets the encoding for this ExtendedTextWriter
Private Attributes
TextWriter _writer
Detailed Description
ExtendedTextWrapper wraps a TextWriter and makes it look like an ExtendedTextWriter. All style indications are ignored. It's used when text is being written to a file.
Constructor & Destructor Documentation
NUnit.Common.ExtendedTextWrapper.ExtendedTextWrapper (TextWriter writer) inline
Member Function Documentation
override void NUnit.Common.ExtendedTextWrapper.Write (char value) inline
Write a single char value
Referenced by NUnit.Common.Tests.ExtendedTextWrapperTests.Write(), and NUnit.Common.Tests.ExtendedTextWrapperTests.Write_ColorStyle().
override void NUnit.Common.ExtendedTextWrapper.Write (string value) inline
Write a string value
override void NUnit.Common.ExtendedTextWrapper.WriteLine (string value) inline
Write a string value followed by a NewLine
Referenced by NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine(), and NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine_ColorStyle().
override void NUnit.Common.ExtendedTextWrapper.Close () inline
Close the ExtendedTextWriter
override void NUnit.Common.ExtendedTextWrapper.Dispose (bool disposing) inline protected
Dispose the Extended TextWriter
override void NUnit.Common.ExtendedTextWrapper.Write (ColorStyle style, string value) inline virtual
Writes the value with the specified style.
Parameters
style The style.
value The value.
Implements NUnit.Common.ExtendedTextWriter.
override void NUnit.Common.ExtendedTextWrapper.WriteLine (ColorStyle style, string value) inline virtual
Writes the value with the specified style
Parameters
style The style.
value The value.
Implements NUnit.Common.ExtendedTextWriter.
override void NUnit.Common.ExtendedTextWrapper.WriteLabel (string label, object option) inline virtual
Writes the label and the option that goes with it.
Parameters
label The label.
option The option.
Implements NUnit.Common.ExtendedTextWriter.
Referenced by NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel(), and NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel_ColorStyle().
override void NUnit.Common.ExtendedTextWrapper.WriteLabel (string label, object option, ColorStyle valueStyle) inline virtual
Writes the label and the option that goes with it.
Parameters
label The label.
option The option.
valueStyle The color to display the value with
Implements NUnit.Common.ExtendedTextWriter.
override void NUnit.Common.ExtendedTextWrapper.WriteLabelLine (string label, object option) inline virtual
Writes the label and the option that goes with it followed by a new line.
Parameters
label The label.
option The option.
Implements NUnit.Common.ExtendedTextWriter.
Referenced by NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine(), and NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine_ColorStyle().
override void NUnit.Common.ExtendedTextWrapper.WriteLabelLine (string label, object option, ColorStyle valueStyle) inline virtual
Writes the label and the option that goes with it followed by a new line.
Parameters
label The label.
option The option.
valueStyle The color to display the value with
Implements NUnit.Common.ExtendedTextWriter.
Member Data Documentation
TextWriter NUnit.Common.ExtendedTextWrapper._writer private
Property Documentation
override Encoding NUnit.Common.ExtendedTextWrapper.Encoding get
Gets the encoding for this ExtendedTextWriter
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/ExtendedTextWrapper.cs