IGLib: NUnit.Framework.Internal.Randomizer Class Reference
NUnit.Framework.Internal.Randomizer Class Reference
Randomizer returns a set of random _values in a repeatable way, to allow re-running of tests if necessary. It extends the .NET Random class, providing random values for a much wider range of types.
Public Member Functions
Randomizer ()
Default constructor
Randomizer (int seed)
Construct based on seed value
uint NextUInt ()
Returns a random unsigned int.
uint NextUInt (uint max)
Returns a random unsigned int less than the specified maximum.
uint NextUInt (uint min, uint max)
Returns a random unsigned int within a specified range.
short NextShort ()
Returns a non-negative random short.
short NextShort (short max)
Returns a non-negative random short less than the specified maximum.
short NextShort (short min, short max)
Returns a non-negative random short within a specified range.
ushort NextUShort ()
Returns a random unsigned short.
ushort NextUShort (ushort max)
Returns a random unsigned short less than the specified maximum.
ushort NextUShort (ushort min, ushort max)
Returns a random unsigned short within a specified range.
long NextLong ()
Returns a random long.
long NextLong (long max)
Returns a random long less than the specified maximum.
long NextLong (long min, long max)
Returns a non-negative random long within a specified range.
ulong NextULong ()
Returns a random ulong.
ulong NextULong (ulong max)
Returns a random ulong less than the specified maximum.
ulong NextULong (ulong min, ulong max)
Returns a non-negative random long within a specified range.
byte NextByte ()
Returns a random Byte
byte NextByte (byte max)
Returns a random Byte less than the specified maximum.
byte NextByte (byte min, byte max)
Returns a random Byte within a specified range
sbyte NextSByte ()
Returns a random SByte
sbyte NextSByte (sbyte max)
Returns a random sbyte less than the specified maximum.
sbyte NextSByte (sbyte min, sbyte max)
Returns a random sbyte within a specified range
bool NextBool ()
Returns a random bool
bool NextBool (double probability)
Returns a random bool based on the probablility a true result
double NextDouble (double max)
Returns a random double between 0.0 and the specified maximum.
double NextDouble (double min, double max)
Returns a random double within a specified range.
float NextFloat ()
Returns a random float.
float NextFloat (float max)
Returns a random float between 0.0 and the specified maximum.
float NextFloat (float min, float max)
Returns a random float within a specified range.
object NextEnum (Type type)
Returns a random enum value of the specified Type as an object.
T NextEnum< T > ()
Returns a random enum value of the specified Type.
string GetString (int outputLength, string allowedChars)
Generate a random string based on the characters from the input string.
string GetString (int outputLength)
Generate a random string based on the characters from the input string.
string GetString ()
Generate a random string based on the characters from the input string.
decimal NextDecimal ()
Returns a random decimal.
decimal NextDecimal (decimal max)
Returns a random decimal between positive zero and the specified maximum.
decimal NextDecimal (decimal min, decimal max)
Returns a random decimal within a specified range, which is not permitted to exceed decimal.MaxVal in the current implementation.
Static Public Member Functions
static Randomizer GetRandomizer (MemberInfo member)
Get a Randomizer for a particular member, returning one that has already been created if it exists. This ensures that the same _values are generated each time the tests are reloaded.
static Randomizer GetRandomizer (ParameterInfo parameter)
Get a randomizer for a particular parameter, returning one that has already been created if it exists. This ensures that the same values are generated each time the tests are reloaded.
static Randomizer CreateRandomizer ()
Create a new Randomizer using the next seed available to ensure that each randomizer gives a unique sequence of values.
Public Attributes
const string DefaultStringChars = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ0123456789_"
Default characters for random functions.
Properties
static int InitialSeed [get, set]
Initial seed used to create randomizers for this run
static Random SeedGenerator [get]
Private Member Functions
uint RawUInt ()
uint RawUShort ()
ulong RawULong ()
long RawLong ()
decimal RawDecimal ()
Private Attributes
const int DefaultStringLength = 25
Static Private Attributes
static Random _seedGenerator
static Dictionary< MemberInfo,
Randomizer > Randomizers = new Dictionary<MemberInfo, Randomizer>()
Detailed Description
Randomizer returns a set of random _values in a repeatable way, to allow re-running of tests if necessary. It extends the .NET Random class, providing random values for a much wider range of types.
The class is used internally by the framework to generate test case data and is also exposed for use by users through the TestContext.Random property.
For consistency with the underlying Random Type, methods returning a single value use the prefix "Next..." Those without an argument return a non-negative value up to the full positive range of the Type. Overloads are provided for specifying a maximum or a range. Methods that return arrays or strings use the prefix "Get..." to avoid confusion with the single-value methods.
Constructor & Destructor Documentation
NUnit.Framework.Internal.Randomizer.Randomizer () inline
Default constructor
NUnit.Framework.Internal.Randomizer.Randomizer (int seed) inline
Construct based on seed value
Parameters
seed
Member Function Documentation
static Randomizer NUnit.Framework.Internal.Randomizer.GetRandomizer (MemberInfo member) inline static
Get a Randomizer for a particular member, returning one that has already been created if it exists. This ensures that the same _values are generated each time the tests are reloaded.
Referenced by NUnit.Framework.RandomAttribute.RandomDataSource< T >.GetData(), NUnit.Framework.RandomAttribute.EnumDataSource.GetData(), NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsDifferentRandomizersForDifferentMethods(), NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForDifferentParametersOfSameMethod(), NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForSameMethod(), and NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForSameParameter().
static Randomizer NUnit.Framework.Internal.Randomizer.GetRandomizer (ParameterInfo parameter) inline static
Get a randomizer for a particular parameter, returning one that has already been created if it exists. This ensures that the same values are generated each time the tests are reloaded.
static Randomizer NUnit.Framework.Internal.Randomizer.CreateRandomizer () inline static
Create a new Randomizer using the next seed available to ensure that each randomizer gives a unique sequence of values.
Returns
uint NUnit.Framework.Internal.Randomizer.NextUInt () inline
Returns a random unsigned int.
Referenced by NUnit.Framework.Internal.RandomizerTests.RandomUInt(), NUnit.Framework.Internal.RandomizerTests.RandomUIntInRange(), NUnit.Framework.Internal.RandomizerTests.RandomUintInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomUintInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomUIntsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomUIntsInRangeAreUnique(), and NUnit.Framework.Internal.RandomizerTests.RandomUIntWithMaximum().
uint NUnit.Framework.Internal.Randomizer.NextUInt (uint max) inline
Returns a random unsigned int less than the specified maximum.
uint NUnit.Framework.Internal.Randomizer.NextUInt (uint min, uint max) inline
Returns a random unsigned int within a specified range.
short NUnit.Framework.Internal.Randomizer.NextShort () inline
Returns a non-negative random short.
Referenced by NUnit.Framework.Internal.RandomizerTests.RandomShort(), NUnit.Framework.Internal.RandomizerTests.RandomShortInRange(), NUnit.Framework.Internal.RandomizerTests.RandomShortInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomShortInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomShortsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomShortsInRangeAreUnique(), and NUnit.Framework.Internal.RandomizerTests.RandomShortWithMaximum().
short NUnit.Framework.Internal.Randomizer.NextShort (short max) inline
Returns a non-negative random short less than the specified maximum.
short NUnit.Framework.Internal.Randomizer.NextShort (short min, short max) inline
Returns a non-negative random short within a specified range.
ushort NUnit.Framework.Internal.Randomizer.NextUShort () inline
Returns a random unsigned short.
Referenced by NUnit.Framework.Internal.RandomizerTests.RandomUShort(), NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange(), NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomUShortsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomUShortsInRangeAreUnique(), and NUnit.Framework.Internal.RandomizerTests.RandomUShortWithMaximum().
ushort NUnit.Framework.Internal.Randomizer.NextUShort (ushort max) inline
Returns a random unsigned short less than the specified maximum.
ushort NUnit.Framework.Internal.Randomizer.NextUShort (ushort min, ushort max) inline
Returns a random unsigned short within a specified range.
long NUnit.Framework.Internal.Randomizer.NextLong () inline
Returns a random long.
Referenced by NUnit.Framework.Internal.RandomizerTests.RandomLong(), NUnit.Framework.Internal.RandomizerTests.RandomLongInRange(), NUnit.Framework.Internal.RandomizerTests.RandomLongInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomLongInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomLongsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomLongsInRangeAreUnique(), and NUnit.Framework.Internal.RandomizerTests.RandomLongWithMaximum().
long NUnit.Framework.Internal.Randomizer.NextLong (long max) inline
Returns a random long less than the specified maximum.
long NUnit.Framework.Internal.Randomizer.NextLong (long min, long max) inline
Returns a non-negative random long within a specified range.
ulong NUnit.Framework.Internal.Randomizer.NextULong () inline
Returns a random ulong.
Referenced by NUnit.Framework.Internal.RandomizerTests.RandomULong(), NUnit.Framework.Internal.RandomizerTests.RandomULongInRange(), NUnit.Framework.Internal.RandomizerTests.RandomULongInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomULongInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomULongsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomULongsInRangeAreUnique(), and NUnit.Framework.Internal.RandomizerTests.RandomULongWithMaximum().
ulong NUnit.Framework.Internal.Randomizer.NextULong (ulong max) inline
Returns a random ulong less than the specified maximum.
ulong NUnit.Framework.Internal.Randomizer.NextULong (ulong min, ulong max) inline
Returns a non-negative random long within a specified range.
byte NUnit.Framework.Internal.Randomizer.NextByte () inline
Returns a random Byte
Referenced by NUnit.Framework.Internal.RandomizerTests.RandomByte(), NUnit.Framework.Internal.RandomizerTests.RandomByteInRange(), NUnit.Framework.Internal.RandomizerTests.RandomByteInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomByteInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomBytesAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomBytesInRangeAreUnique(), and NUnit.Framework.Internal.RandomizerTests.RandomByteWithMaximum().
byte NUnit.Framework.Internal.Randomizer.NextByte (byte max) inline
Returns a random Byte less than the specified maximum.
byte NUnit.Framework.Internal.Randomizer.NextByte (byte min, byte max) inline
Returns a random Byte within a specified range
sbyte NUnit.Framework.Internal.Randomizer.NextSByte () inline
Returns a random SByte
Referenced by NUnit.Framework.Internal.RandomizerTests.RandomSByte(), NUnit.Framework.Internal.RandomizerTests.RandomSByteInRange(), NUnit.Framework.Internal.RandomizerTests.RandomSbyteInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomSByteInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomSBytesAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomSBytesInRangeAreUnique(), and NUnit.Framework.Internal.RandomizerTests.RandomSByteWithMaximum().
sbyte NUnit.Framework.Internal.Randomizer.NextSByte (sbyte max) inline
Returns a random sbyte less than the specified maximum.
sbyte NUnit.Framework.Internal.Randomizer.NextSByte (sbyte min, sbyte max) inline
Returns a random sbyte within a specified range
bool NUnit.Framework.Internal.Randomizer.NextBool () inline
Returns a random bool
Referenced by NUnit.Framework.Internal.RandomizerTests.RandomBool(), NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbability(), NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbabilityOneIsAlwaysTrue(), NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbabilityOutOfRange(), and NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbabilityZeroIsAlwaysFalse().
bool NUnit.Framework.Internal.Randomizer.NextBool (double probability) inline
Returns a random bool based on the probablility a true result
double NUnit.Framework.Internal.Randomizer.NextDouble (double max) inline
Returns a random double between 0.0 and the specified maximum.
Referenced by NUnit.Framework.Internal.RandomizerTests.RandomDouble(), NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange(), NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomDoublesAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomDoublesInRangeAreUnique(), and NUnit.Framework.Internal.RandomizerTests.RandomDoubleWithMaximum().
double NUnit.Framework.Internal.Randomizer.NextDouble (double min, double max) inline
Returns a random double within a specified range.
float NUnit.Framework.Internal.Randomizer.NextFloat () inline
Returns a random float.
Referenced by NUnit.Framework.Internal.RandomizerTests.GetFloats(), NUnit.Framework.Internal.RandomizerTests.RandomFloat(), NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange(), NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomFloatsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomFloatsInRangeAreUnique(), and NUnit.Framework.Internal.RandomizerTests.RandomFloatWithMaximum().
float NUnit.Framework.Internal.Randomizer.NextFloat (float max) inline
Returns a random float between 0.0 and the specified maximum.
float NUnit.Framework.Internal.Randomizer.NextFloat (float min, float max) inline
Returns a random float within a specified range.
object NUnit.Framework.Internal.Randomizer.NextEnum (Type type) inline
Returns a random enum value of the specified Type as an object.
References NUnit.Framework.Internal.TypeHelper.GetEnumValues().
Referenced by NUnit.Framework.RandomAttribute.EnumDataSource.GetData(), NUnit.Framework.Internal.RandomizerTests.RandomEnum(), and NUnit.Framework.Internal.RandomizerTests.RandomEnum_Generic().
T NUnit.Framework.Internal.Randomizer.NextEnum< T > () inline
Returns a random enum value of the specified Type.
string NUnit.Framework.Internal.Randomizer.GetString (int outputLength, string allowedChars) inline
Generate a random string based on the characters from the input string.
Parameters
outputLength desired length of output string.
allowedChars string representing the set of characters from which to construct the resulting string
Returns
A random string of arbitrary length
Referenced by NUnit.Framework.Internal.RandomizerTests.RandomStringsAreUnique().
string NUnit.Framework.Internal.Randomizer.GetString (int outputLength) inline
Generate a random string based on the characters from the input string.
Parameters
outputLength desired length of output string.
Returns
A random string of arbitrary length
Uses DefaultStringChars as the input character set
string NUnit.Framework.Internal.Randomizer.GetString () inline
Generate a random string based on the characters from the input string.
Returns
A random string of the default length
Uses DefaultStringChars as the input character set
decimal NUnit.Framework.Internal.Randomizer.NextDecimal () inline
Returns a random decimal.
Referenced by NUnit.Framework.Internal.RandomizerTests.RandomDecimal(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalRangeTooGreat(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalsInRangeAreUnique(), and NUnit.Framework.Internal.RandomizerTests.RandomDecimalWithMaximum().
decimal NUnit.Framework.Internal.Randomizer.NextDecimal (decimal max) inline
Returns a random decimal between positive zero and the specified maximum.
decimal NUnit.Framework.Internal.Randomizer.NextDecimal (decimal min, decimal max) inline
Returns a random decimal within a specified range, which is not permitted to exceed decimal.MaxVal in the current implementation.
A limitation of this implementation is that the range from min to max must not exceed decimal.MaxVal.
uint NUnit.Framework.Internal.Randomizer.RawUInt () inline private
uint NUnit.Framework.Internal.Randomizer.RawUShort () inline private
ulong NUnit.Framework.Internal.Randomizer.RawULong () inline private
long NUnit.Framework.Internal.Randomizer.RawLong () inline private
decimal NUnit.Framework.Internal.Randomizer.RawDecimal () inline private
Member Data Documentation
Random NUnit.Framework.Internal.Randomizer._seedGenerator static private
Dictionary<MemberInfo, Randomizer> NUnit.Framework.Internal.Randomizer.Randomizers = new Dictionary<MemberInfo, Randomizer>() static private
const string NUnit.Framework.Internal.Randomizer.DefaultStringChars = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ0123456789_"
Default characters for random functions.
Default characters are the English alphabet (uppercase & lowercase), arabic numerals, and underscore
const int NUnit.Framework.Internal.Randomizer.DefaultStringLength = 25 private
Property Documentation
int NUnit.Framework.Internal.Randomizer.InitialSeed static get set
Initial seed used to create randomizers for this run
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.Load(), and NUnitLite.NUnit3XmlOutputWriter.MakeTestRunElement().
Random NUnit.Framework.Internal.Randomizer.SeedGenerator static get private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Randomizer.cs