IGLib: Test.DataSetTest Class Reference
Test.DataSetTest Class Reference
This is a test class for DataSetTest and is intended to contain all DataSetTest Unit Tests /summary>
Public Member Functions
void DataSetManipulationsTest ()
void FitDataToProportionalityTest ()
void FitDataToLineTest ()
void FitDataToLineChiSquaredTest ()
void FitDataToPolynomialTest ()
void FitDataToPolynomialChiSquaredTest ()
void FitDataToPolynomialUncertaintiesTest ()
void FitDataToLinearFunctionTest ()
void FitDataToFunctionTest ()
void FitToFunctionLinearCompatibilityTest ()
void FitToFunctionPolynomialCompatibilityTest ()
void FitDataToLineUncertaintyTest ()
Properties
TestContext TestContext [get, set]
Gets or sets the test context which provides information about and functionality for the current test run. /summary>
Private Member Functions
UncertainMeasurementSample CreateDataSet (Interval r, Func< double, double > fv, Func< double, double > fu, int n)
UncertainMeasurementSample CreateDataSet (Interval r, Func< double, double > fv, Func< double, double > fu, int n, int seed)
UncertainMeasurementSample CreateDataSet (double[] xs, Func< double, double > fv, Func< double, double > fu, int seed)
Private Attributes
TestContext testContextInstance
Detailed Description
This is a test class for DataSetTest and is intended to contain all DataSetTest Unit Tests /summary>
Member Function Documentation
void Test.DataSetTest.DataSetManipulationsTest () inline
UncertainMeasurementSample Test.DataSetTest.CreateDataSet (Interval r, Func< double, double > fv, Func< double, double > fu, int n) inline private
Referenced by Test.DataSetTest.FitDataToLinearFunctionTest(), Test.DataSetTest.FitDataToLineChiSquaredTest(), Test.DataSetTest.FitDataToLineTest(), Test.DataSetTest.FitDataToLineUncertaintyTest(), Test.DataSetTest.FitDataToPolynomialChiSquaredTest(), Test.DataSetTest.FitDataToPolynomialTest(), Test.DataSetTest.FitDataToPolynomialUncertaintiesTest(), Test.DataSetTest.FitDataToProportionalityTest(), Test.DataSetTest.FitToFunctionLinearCompatibilityTest(), and Test.DataSetTest.FitToFunctionPolynomialCompatibilityTest().
UncertainMeasurementSample Test.DataSetTest.CreateDataSet (Interval r, Func< double, double > fv, Func< double, double > fu, int n, int seed) inline private
References Meta.Numerics.Statistics.Distributions.UniformDistribution.InverseLeftProbability(), and Meta.Numerics.Statistics.Distributions.NormalDistribution.InverseLeftProbability().
UncertainMeasurementSample Test.DataSetTest.CreateDataSet (double[] xs, Func< double, double > fv, Func< double, double > fu, int seed) inline private
References Meta.Numerics.Statistics.Distributions.NormalDistribution.InverseLeftProbability().
void Test.DataSetTest.FitDataToProportionalityTest () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.DataSetTest.CreateDataSet(), Meta.Numerics.Statistics.FitResult.Dimension, Meta.Numerics.Statistics.UncertainMeasurementSample.FitToLine(), Meta.Numerics.Statistics.UncertainMeasurementSample.FitToProportionality(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.TestResult.Statistic, and Meta.Numerics.UncertainValue.Value.
void Test.DataSetTest.FitDataToLineTest () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.FitResult.CorrelationCoefficient(), Meta.Numerics.Statistics.FitResult.Covariance(), Meta.Numerics.Statistics.FitResult.CovarianceMatrix(), Test.DataSetTest.CreateDataSet(), Meta.Numerics.Statistics.FitResult.Dimension, Meta.Numerics.Statistics.UncertainMeasurementSample.FitToConstant(), Meta.Numerics.Statistics.UncertainMeasurementSample.FitToLine(), Meta.Numerics.Statistics.UncertainMeasurementSample.FitToPolynomial(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.FitResult.Parameters(), Meta.Numerics.Statistics.TestResult.RightProbability, Meta.Numerics.Statistics.TestResult.Statistic, and Meta.Numerics.UncertainValue.Uncertainty.
void Test.DataSetTest.FitDataToLineChiSquaredTest () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Sample.Count, Test.DataSetTest.CreateDataSet(), Meta.Numerics.Statistics.UncertainMeasurementSample.FitToLine(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.DataSetTest.FitDataToPolynomialTest () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.DataSetTest.CreateDataSet(), Meta.Numerics.Statistics.FitResult.Dimension, Meta.Numerics.Statistics.UncertainMeasurementSample.FitToPolynomial(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.FitResult.Parameter(), and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.DataSetTest.FitDataToPolynomialChiSquaredTest () inline
References Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Sample.Count, Test.DataSetTest.CreateDataSet(), Meta.Numerics.Statistics.UncertainMeasurementSample.FitToPolynomial(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.DataSetTest.FitDataToPolynomialUncertaintiesTest () inline
References Meta.Numerics.Statistics.MultivariateSample.Add(), Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.Statistics.MultivariateSample.Column(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Test.DataSetTest.CreateDataSet(), Meta.Numerics.Statistics.FitResult.Dimension, Meta.Numerics.Statistics.UncertainMeasurementSample.FitToPolynomial(), Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, Meta.Numerics.Statistics.Sample.StandardDeviation, Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
void Test.DataSetTest.FitDataToLinearFunctionTest () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.FitResult.Covariance(), Test.DataSetTest.CreateDataSet(), Meta.Numerics.Statistics.FitResult.Dimension, Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Statistics.FitResult.Parameter(), and Meta.Numerics.UncertainValue.Uncertainty.
void Test.DataSetTest.FitDataToFunctionTest () inline
References Meta.Numerics.Statistics.FitResult.Parameter().
void Test.DataSetTest.FitToFunctionLinearCompatibilityTest () inline
References Meta.Numerics.Statistics.FitResult.CovarianceMatrix(), Test.DataSetTest.CreateDataSet(), Meta.Numerics.Statistics.FitResult.Dimension, Meta.Numerics.Statistics.UncertainMeasurementSample.FitToLine(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.FitResult.Parameters(), and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.DataSetTest.FitToFunctionPolynomialCompatibilityTest () inline
References Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.FitResult.CovarianceMatrix(), Test.DataSetTest.CreateDataSet(), Meta.Numerics.Statistics.FitResult.Dimension, Meta.Numerics.Statistics.UncertainMeasurementSample.FitToPolynomial(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.FitResult.Parameters(), Meta.Numerics.Statistics.TestResult.Statistic, and Meta.Numerics.UncertainValue.Value.
void Test.DataSetTest.FitDataToLineUncertaintyTest () inline
References Meta.Numerics.Statistics.MultivariateSample.Add(), Meta.Numerics.Statistics.FitResult.CovarianceMatrix(), Test.DataSetTest.CreateDataSet(), Meta.Numerics.Statistics.UncertainMeasurementSample.FitToLine(), and Meta.Numerics.Statistics.FitResult.Parameters().
Member Data Documentation
TestContext Test.DataSetTest.testContextInstance private
Property Documentation
TestContext Test.DataSetTest.TestContext get set
Gets or sets the test context which provides information about and functionality for the current test run. /summary>
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/DataSetTest.cs