IGLib: NUnit.Framework.Constraints.EqualConstraintResult Class Reference
NUnit.Framework.Constraints.EqualConstraintResult Class Reference
The EqualConstraintResult class is tailored for formatting and displaying the result of an EqualConstraint.
Public Member Functions
EqualConstraintResult (EqualConstraint constraint, object actual, bool hasSucceeded)
Construct an EqualConstraintResult
override void WriteMessageTo (MessageWriter writer)
Write a failure message. Overridden to provide custom failure messages for EqualConstraint.
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintResult
ConstraintResult (IConstraint constraint, object actualValue)
Constructs a ConstraintResult for a particular Constraint.
ConstraintResult (IConstraint constraint, object actualValue, ConstraintStatus status)
Constructs a ConstraintResult for a particular Constraint.
ConstraintResult (IConstraint constraint, object actualValue, bool isSuccess)
Constructs a ConstraintResult for a particular Constraint.
virtual void WriteActualValueTo (MessageWriter writer)
Write the actual value for a failing constraint test to a MessageWriter. The default implementation simply writes the raw value of actual, leaving it to the writer to perform any formatting.
Private Member Functions
void DisplayDifferences (MessageWriter writer, object expected, object actual, int depth)
void DisplayStringDifferences (MessageWriter writer, string expected, string actual)
void DisplayStreamDifferences (MessageWriter writer, Stream expected, Stream actual, int depth)
void DisplayCollectionDifferences (MessageWriter writer, ICollection expected, ICollection actual, int depth)
Display the failure information for two collections that did not match.
void DisplayTypesAndSizes (MessageWriter writer, IEnumerable expected, IEnumerable actual, int indent)
Displays a single line showing the types and sizes of the expected and actual collections or arrays. If both are identical, the value is only shown once.
void DisplayFailurePoint (MessageWriter writer, IEnumerable expected, IEnumerable actual, NUnitEqualityComparer.FailurePoint failurePoint, int indent)
Displays a single line showing the point in the expected and actual arrays at which the comparison failed. If the arrays have different structures or dimensions, both _values are shown.
void DisplayEnumerableDifferences (MessageWriter writer, IEnumerable expected, IEnumerable actual, int depth)
Display the failure information for two IEnumerables that did not match.
Static Private Member Functions
static object GetValueFromCollection (ICollection collection, int index)
Private Attributes
object expectedValue
Tolerance tolerance
bool caseInsensitive
bool clipStrings
IList
< NUnitEqualityComparer.FailurePoint > failurePoints
Static Private Attributes
static readonly string StringsDiffer_1
static readonly string StringsDiffer_2
static readonly string StreamsDiffer_1
static readonly string StreamsDiffer_2
static readonly string CollectionType_1
static readonly string CollectionType_2
static readonly string ValuesDiffer_1
static readonly string ValuesDiffer_2
Additional Inherited Members
Properties inherited from NUnit.Framework.Constraints.ConstraintResult
object ActualValue [get, private set]
The actual value that was passed to the Constraint.ApplyTo{TActual}(TActual) method.
ConstraintStatus Status [get, set]
Gets and sets the ResultStatus for this result.
virtual bool IsSuccess [get]
True if actual value meets the Constraint criteria otherwise false.
string Name [get, private set]
Display friendly name of the constraint.
string Description [get, private set]
Description of the constraint may be affected by the state the constraint had when Constraint.ApplyTo{TActual}(TActual) was performed against the actual value.
Detailed Description
The EqualConstraintResult class is tailored for formatting and displaying the result of an EqualConstraint.
Constructor & Destructor Documentation
NUnit.Framework.Constraints.EqualConstraintResult.EqualConstraintResult (EqualConstraint constraint, object actual, bool hasSucceeded) inline
Construct an EqualConstraintResult
References NUnit.Framework.Constraints.Constraint.Arguments, NUnit.Framework.Constraints.EqualConstraint.CaseInsensitive, NUnit.Framework.Constraints.EqualConstraint.ClipStrings, NUnit.Framework.Constraints.EqualConstraint.FailurePoints, and NUnit.Framework.Constraints.EqualConstraint.Tolerance.
Member Function Documentation
override void NUnit.Framework.Constraints.EqualConstraintResult.WriteMessageTo (MessageWriter writer) inline virtual
Write a failure message. Overridden to provide custom failure messages for EqualConstraint.
Parameters
writer The MessageWriter to write to
Reimplemented from NUnit.Framework.Constraints.ConstraintResult.
void NUnit.Framework.Constraints.EqualConstraintResult.DisplayDifferences (MessageWriter writer, object expected, object actual, int depth) inline private
References NUnit.Framework.Constraints.MessageWriter.DisplayDifferences().
void NUnit.Framework.Constraints.EqualConstraintResult.DisplayStringDifferences (MessageWriter writer, string expected, string actual) inline private
References NUnit.Framework.Constraints.MessageWriter.DisplayStringDifferences(), and NUnit.Framework.Constraints.MessageWriter.WriteMessageLine().
void NUnit.Framework.Constraints.EqualConstraintResult.DisplayStreamDifferences (MessageWriter writer, Stream expected, Stream actual, int depth) inline private
References NUnit.Framework.Constraints.MessageWriter.WriteMessageLine().
void NUnit.Framework.Constraints.EqualConstraintResult.DisplayCollectionDifferences (MessageWriter writer, ICollection expected, ICollection actual, int depth) inline private
Display the failure information for two collections that did not match.
Parameters
writer The MessageWriter on which to display
expected The expected collection.
actual The actual collection
depth The depth of this failure in a set of nested collections
void NUnit.Framework.Constraints.EqualConstraintResult.DisplayTypesAndSizes (MessageWriter writer, IEnumerable expected, IEnumerable actual, int indent) inline private
Displays a single line showing the types and sizes of the expected and actual collections or arrays. If both are identical, the value is only shown once.
Parameters
writer The MessageWriter on which to display
expected The expected collection or array
actual The actual collection or array
indent The indentation level for the message line
References NUnit.Framework.Constraints.MessageWriter.WriteMessageLine().
void NUnit.Framework.Constraints.EqualConstraintResult.DisplayFailurePoint (MessageWriter writer, IEnumerable expected, IEnumerable actual, NUnitEqualityComparer.FailurePoint failurePoint, int indent) inline private
Displays a single line showing the point in the expected and actual arrays at which the comparison failed. If the arrays have different structures or dimensions, both _values are shown.
Parameters
writer The MessageWriter on which to display
expected The expected array
actual The actual array
failurePoint Index of the failure point in the underlying collections
indent The indentation level for the message line
References NUnit.Framework.Constraints.MessageWriter.WriteMessageLine().
static object NUnit.Framework.Constraints.EqualConstraintResult.GetValueFromCollection (ICollection collection, int index) inline static private
void NUnit.Framework.Constraints.EqualConstraintResult.DisplayEnumerableDifferences (MessageWriter writer, IEnumerable expected, IEnumerable actual, int depth) inline private
Display the failure information for two IEnumerables that did not match.
Parameters
writer The MessageWriter on which to display
expected The expected enumeration.
actual The actual enumeration
depth The depth of this failure in a set of nested collections
Member Data Documentation
object NUnit.Framework.Constraints.EqualConstraintResult.expectedValue private
Tolerance NUnit.Framework.Constraints.EqualConstraintResult.tolerance private
bool NUnit.Framework.Constraints.EqualConstraintResult.caseInsensitive private
bool NUnit.Framework.Constraints.EqualConstraintResult.clipStrings private
IList<NUnitEqualityComparer.FailurePoint> NUnit.Framework.Constraints.EqualConstraintResult.failurePoints private
readonly string NUnit.Framework.Constraints.EqualConstraintResult.StringsDiffer_1 static private
Initial value:
=
            "String lengths are both {0}. Strings differ at index {1}."
readonly string NUnit.Framework.Constraints.EqualConstraintResult.StringsDiffer_2 static private
Initial value:
=
            "Expected string length {0} but was {1}. Strings differ at index {2}."
readonly string NUnit.Framework.Constraints.EqualConstraintResult.StreamsDiffer_1 static private
Initial value:
=
            "Stream lengths are both {0}. Streams differ at offset {1}."
readonly string NUnit.Framework.Constraints.EqualConstraintResult.StreamsDiffer_2 static private
Initial value:
=
            "Expected Stream length {0} but was {1}."
readonly string NUnit.Framework.Constraints.EqualConstraintResult.CollectionType_1 static private
Initial value:
=
            "Expected and actual are both {0}"
readonly string NUnit.Framework.Constraints.EqualConstraintResult.CollectionType_2 static private
Initial value:
=
            "Expected is {0}, actual is {1}"
readonly string NUnit.Framework.Constraints.EqualConstraintResult.ValuesDiffer_1 static private
Initial value:
=
            "Values differ at index {0}"
readonly string NUnit.Framework.Constraints.EqualConstraintResult.ValuesDiffer_2 static private
Initial value:
=
            "Values differ at expected index {0}, actual index {1}"
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/EqualConstraintResult.cs