IGLib: NUnit.Framework.PlatformAttribute Class Reference
NUnit.Framework.PlatformAttribute Class Reference
PlatformAttribute is used to mark a test fixture or an individual method as applying to a particular platform only.
Public Member Functions
PlatformAttribute ()
Constructor with no platforms specified, for use with named property syntax.
PlatformAttribute (string platforms)
Constructor taking one or more platforms
void ApplyToTest (Test test)
Causes a test to be skipped if this PlatformAttribute is not satisfied.
Public Member Functions inherited from NUnit.Framework.IncludeExcludeAttribute
IncludeExcludeAttribute ()
Constructor with no included items specified, for use with named property syntax.
IncludeExcludeAttribute (string include)
Constructor taking one or more included items
Public Member Functions inherited from NUnit.Framework.NUnitAttribute
NUnitAttribute ()
Default constructor
Private Attributes
PlatformHelper platformHelper = new PlatformHelper()
Additional Inherited Members
Properties inherited from NUnit.Framework.IncludeExcludeAttribute
string Include [get, set]
Name of the item that is needed in order for a test to run. Multiple items may be given, separated by a comma.
string Exclude [get, set]
Name of the item to be excluded. Multiple items may be given, separated by a comma.
string Reason [get, set]
The reason for including or excluding the test
Detailed Description
PlatformAttribute is used to mark a test fixture or an individual method as applying to a particular platform only.
Constructor & Destructor Documentation
NUnit.Framework.PlatformAttribute.PlatformAttribute () inline
Constructor with no platforms specified, for use with named property syntax.
NUnit.Framework.PlatformAttribute.PlatformAttribute (string platforms) inline
Constructor taking one or more platforms
Parameters
platforms Comma-delimited list of platforms
Member Function Documentation
void NUnit.Framework.PlatformAttribute.ApplyToTest (Test test) inline
Causes a test to be skipped if this PlatformAttribute is not satisfied.
Parameters
test The test to modify
Implements NUnit.Framework.Interfaces.IApplyToTest.
References NUnit.Framework.Interfaces.IPropertyBag.Add(), NUnit.Framework.Internal.PlatformHelper.IsPlatformSupported(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.PlatformHelper.Reason, NUnit.Framework.Internal.Test.RunState, and NUnit.Framework.Internal.PropertyNames.SkipReason.
Referenced by NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeRunsTest(), and NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeSkipsTest().
Member Data Documentation
PlatformHelper NUnit.Framework.PlatformAttribute.platformHelper = new PlatformHelper() private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Attributes/PlatformAttribute.cs