IGLib: NUnit.Samples.Money.MoneyTest Class Reference
NUnit.Samples.Money.MoneyTest Class Reference
Public Member Functions
void BagMultiply ()
void BagNegate ()
void BagSimpleAdd ()
void BagSubtract ()
void BagSumAdd ()
void IsZero ()
void MixedSimpleAdd ()
void MoneyBagEquals ()
void MoneyBagHash ()
void MoneyEquals ()
void MoneyHash ()
void Normalize ()
void Normalize2 ()
void Normalize3 ()
void Normalize4 ()
void Print ()
void SimpleAdd ()
void SimpleBagAdd ()
void SimpleMultiply ()
void SimpleNegate ()
void SimpleSubtract ()
Protected Member Functions
void SetUp ()
Private Attributes
Money f12CHF
Money f14CHF
Money f7USD
Money f21USD
MoneyBag fMB1
MoneyBag fMB2
Detailed Description
Member Function Documentation
void NUnit.Samples.Money.MoneyTest.SetUp () inline protected
void NUnit.Samples.Money.MoneyTest.BagMultiply () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.IsTrue(), NUnit.Samples.Money.IMoney.IsZero, and NUnit.Samples.Money.MoneyBag.Multiply().
void NUnit.Samples.Money.MoneyTest.BagNegate () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Samples.Money.MoneyBag.Negate().
void NUnit.Samples.Money.MoneyTest.BagSimpleAdd () inline
References NUnit.Samples.Money.MoneyBag.Add(), and NUnit.Framework.Assert.AreEqual().
void NUnit.Samples.Money.MoneyTest.BagSubtract () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Samples.Money.MoneyBag.Subtract().
void NUnit.Samples.Money.MoneyTest.BagSumAdd () inline
References NUnit.Samples.Money.MoneyBag.Add(), and NUnit.Framework.Assert.AreEqual().
void NUnit.Samples.Money.MoneyTest.IsZero () inline
References NUnit.Framework.Assert.IsTrue(), NUnit.Samples.Money.IMoney.IsZero, and NUnit.Samples.Money.MoneyBag.Subtract().
void NUnit.Samples.Money.MoneyTest.MixedSimpleAdd () inline
References NUnit.Samples.Money.Money.Add(), and NUnit.Framework.Assert.AreEqual().
void NUnit.Samples.Money.MoneyTest.MoneyBagEquals () inline
References NUnit.Samples.Money.Money.Equals(), NUnit.Samples.Money.MoneyBag.Equals(), NUnit.Framework.Assert.IsFalse(), and NUnit.Framework.Assert.IsTrue().
void NUnit.Samples.Money.MoneyTest.MoneyBagHash () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Samples.Money.MoneyBag.GetHashCode().
void NUnit.Samples.Money.MoneyTest.MoneyEquals () inline
References NUnit.Samples.Money.Money.Equals(), NUnit.Framework.Assert.IsFalse(), and NUnit.Framework.Assert.IsTrue().
void NUnit.Samples.Money.MoneyTest.MoneyHash () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Samples.Money.Money.Equals(), NUnit.Samples.Money.Money.GetHashCode(), and NUnit.Framework.Assert.IsFalse().
void NUnit.Samples.Money.MoneyTest.Normalize () inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Samples.Money.MoneyTest.Normalize2 () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Samples.Money.MoneyBag.Subtract().
void NUnit.Samples.Money.MoneyTest.Normalize3 () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Samples.Money.MoneyBag.Subtract().
void NUnit.Samples.Money.MoneyTest.Normalize4 () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Samples.Money.Money.Subtract().
void NUnit.Samples.Money.MoneyTest.Print () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Samples.Money.Money.ToString().
void NUnit.Samples.Money.MoneyTest.SimpleAdd () inline
References NUnit.Samples.Money.Money.Add(), and NUnit.Framework.Assert.AreEqual().
void NUnit.Samples.Money.MoneyTest.SimpleBagAdd () inline
References NUnit.Samples.Money.Money.Add(), and NUnit.Framework.Assert.AreEqual().
void NUnit.Samples.Money.MoneyTest.SimpleMultiply () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Samples.Money.Money.Multiply().
void NUnit.Samples.Money.MoneyTest.SimpleNegate () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Samples.Money.Money.Negate().
void NUnit.Samples.Money.MoneyTest.SimpleSubtract () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Samples.Money.Money.Subtract().
Member Data Documentation
Money NUnit.Samples.Money.MoneyTest.f12CHF private
Money NUnit.Samples.Money.MoneyTest.f14CHF private
Money NUnit.Samples.Money.MoneyTest.f7USD private
Money NUnit.Samples.Money.MoneyTest.f21USD private
MoneyBag NUnit.Samples.Money.MoneyTest.fMB1 private
MoneyBag NUnit.Samples.Money.MoneyTest.fMB2 private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1/samples/csharp/money/MoneyTest.cs