IGLib: alglib.matgen Class Reference
alglib.matgen Class Reference
Static Public Member Functions
static void rmatrixrndorthogonal (int n, ref double[,] a)
static void rmatrixrndcond (int n, double c, ref double[,] a)
static void cmatrixrndorthogonal (int n, ref complex[,] a)
static void cmatrixrndcond (int n, double c, ref complex[,] a)
static void smatrixrndcond (int n, double c, ref double[,] a)
static void spdmatrixrndcond (int n, double c, ref double[,] a)
static void hmatrixrndcond (int n, double c, ref complex[,] a)
static void hpdmatrixrndcond (int n, double c, ref complex[,] a)
static void rmatrixrndorthogonalfromtheright (ref double[,] a, int m, int n)
static void rmatrixrndorthogonalfromtheleft (ref double[,] a, int m, int n)
static void cmatrixrndorthogonalfromtheright (ref complex[,] a, int m, int n)
static void cmatrixrndorthogonalfromtheleft (ref complex[,] a, int m, int n)
static void smatrixrndmultiply (ref double[,] a, int n)
static void hmatrixrndmultiply (ref complex[,] a, int n)
static void rmatrixrndorthogonal (int n, ref double[,] a)
static void rmatrixrndcond (int n, double c, ref double[,] a)
static void cmatrixrndorthogonal (int n, ref complex[,] a)
static void cmatrixrndcond (int n, double c, ref complex[,] a)
static void smatrixrndcond (int n, double c, ref double[,] a)
static void spdmatrixrndcond (int n, double c, ref double[,] a)
static void hmatrixrndcond (int n, double c, ref complex[,] a)
static void hpdmatrixrndcond (int n, double c, ref complex[,] a)
static void rmatrixrndorthogonalfromtheright (ref double[,] a, int m, int n)
static void rmatrixrndorthogonalfromtheleft (ref double[,] a, int m, int n)
static void cmatrixrndorthogonalfromtheright (ref complex[,] a, int m, int n)
static void cmatrixrndorthogonalfromtheleft (ref complex[,] a, int m, int n)
static void smatrixrndmultiply (ref double[,] a, int n)
static void hmatrixrndmultiply (ref complex[,] a, int n)
Member Function Documentation
static void alglib.matgen.rmatrixrndorthogonal (int n, ref double a[,]) inline static
Referenced by alglib.testminqpunit.ecqptest(), alglib.testminqpunit.icqptest(), alglib.rmatrixrndorthogonal(), alglib.testrbfunit.sqrdegmatrixrbftest(), alglib.testlinlsqrunit.stoppingcriteriatest(), alglib.testmatgenunit.testmatgen(), and alglib.testnormestimatorunit.testnormestimator().
static void alglib.matgen.rmatrixrndcond (int n, double c, ref double a[,]) inline static
Referenced by alglib.testminqpunit.icqptest(), alglib.testlinlsqrunit.mwcranksvdtest(), alglib.testlinlsqrunit.preconditionertest(), alglib.rmatrixrndcond(), alglib.testmatgenunit.testmatgen(), alglib.testminlmunit.testminlm(), alglib.testnormestimatorunit.testnormestimator(), alglib.testmatinvunit.testrinv(), alglib.testrcondunit.testrmatrixrcond(), and alglib.testdensesolverunit.testrsolver().
static void alglib.matgen.cmatrixrndorthogonal (int n, ref complex a[,]) inline static
Referenced by alglib.cmatrixrndorthogonal(), and alglib.testmatgenunit.testmatgen().
static void alglib.matgen.cmatrixrndcond (int n, double c, ref complex a[,]) inline static
Referenced by alglib.cmatrixrndcond(), alglib.testmatinvunit.testcinv(), alglib.testrcondunit.testcmatrixrcond(), and alglib.testdensesolverunit.testcsolver().
static void alglib.matgen.smatrixrndcond (int n, double c, ref double a[,]) inline static
Referenced by alglib.smatrixrndcond(), alglib.testmatgenunit.testeult(), and alglib.testmatgenunit.testmatgen().
static void alglib.matgen.spdmatrixrndcond (int n, double c, ref double a[,]) inline static
Referenced by alglib.testlincgunit.basictestiters(), alglib.testlincgunit.basictestx(), alglib.testminqpunit.bleictests(), alglib.testlincgunit.complexres(), alglib.testlincgunit.complextest(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.functest1(), alglib.testminqpunit.functest2(), alglib.testminqpunit.icqptest(), alglib.testlincgunit.krylovsubspacetest(), alglib.testlincgunit.precondtest(), alglib.testlinlsqrunit.reportcorrectnesstest(), alglib.testlincgunit.sparsetest(), alglib.spdmatrixrndcond(), alglib.testlinlsqrunit.stoppingcriteriatest(), alglib.testmatgenunit.testeult(), alglib.testmatgenunit.testmatgen(), alglib.testlincgunit.testrcorrectness(), alglib.testmatinvunit.testspdinv(), alglib.testrcondunit.testspdmatrixrcond(), alglib.testdensesolverunit.testspdsolver(), and alglib.testtrfacunit.testtrfac().
static void alglib.matgen.hmatrixrndcond (int n, double c, ref complex a[,]) inline static
Referenced by alglib.hmatrixrndcond(), alglib.testmatgenunit.testeult(), and alglib.testmatgenunit.testmatgen().
static void alglib.matgen.hpdmatrixrndcond (int n, double c, ref complex a[,]) inline static
Referenced by alglib.hpdmatrixrndcond(), alglib.testmatgenunit.testeult(), alglib.testmatinvunit.testhpdinv(), alglib.testrcondunit.testhpdmatrixrcond(), alglib.testdensesolverunit.testhpdsolver(), alglib.testmatgenunit.testmatgen(), and alglib.testtrfacunit.testtrfac().
static void alglib.matgen.rmatrixrndorthogonalfromtheright (ref double a[,], int m, int n) inline static
Referenced by alglib.testlinlsqrunit.mwicranksvdtest(), alglib.rmatrixrndorthogonalfromtheright(), alglib.testmatgenunit.testmatgen(), and alglib.testtrfacunit.testtrfac().
static void alglib.matgen.rmatrixrndorthogonalfromtheleft (ref double a[,], int m, int n) inline static
Referenced by alglib.testlinlsqrunit.mwicranksvdtest(), alglib.rmatrixrndorthogonalfromtheleft(), alglib.testmatgenunit.testmatgen(), and alglib.testtrfacunit.testtrfac().
static void alglib.matgen.cmatrixrndorthogonalfromtheright (ref complex a[,], int m, int n) inline static
Referenced by alglib.cmatrixrndorthogonalfromtheright(), alglib.testmatgenunit.testmatgen(), and alglib.testtrfacunit.testtrfac().
static void alglib.matgen.cmatrixrndorthogonalfromtheleft (ref complex a[,], int m, int n) inline static
Referenced by alglib.cmatrixrndorthogonalfromtheleft(), alglib.testmatgenunit.testmatgen(), and alglib.testtrfacunit.testtrfac().
static void alglib.matgen.smatrixrndmultiply (ref double a[,], int n) inline static
Referenced by alglib.smatrixrndmultiply(), and alglib.testmatgenunit.testeult().
static void alglib.matgen.hmatrixrndmultiply (ref complex a[,], int n) inline static
Referenced by alglib.hmatrixrndmultiply(), and alglib.testmatgenunit.testeult().
static void alglib.matgen.rmatrixrndorthogonal (int n, ref double a[,]) inline static
static void alglib.matgen.rmatrixrndcond (int n, double c, ref double a[,]) inline static
static void alglib.matgen.cmatrixrndorthogonal (int n, ref complex a[,]) inline static
static void alglib.matgen.cmatrixrndcond (int n, double c, ref complex a[,]) inline static
static void alglib.matgen.smatrixrndcond (int n, double c, ref double a[,]) inline static
static void alglib.matgen.spdmatrixrndcond (int n, double c, ref double a[,]) inline static
static void alglib.matgen.hmatrixrndcond (int n, double c, ref complex a[,]) inline static
static void alglib.matgen.hpdmatrixrndcond (int n, double c, ref complex a[,]) inline static
static void alglib.matgen.rmatrixrndorthogonalfromtheright (ref double a[,], int m, int n) inline static
static void alglib.matgen.rmatrixrndorthogonalfromtheleft (ref double a[,], int m, int n) inline static
static void alglib.matgen.cmatrixrndorthogonalfromtheright (ref complex a[,], int m, int n) inline static
static void alglib.matgen.cmatrixrndorthogonalfromtheleft (ref complex a[,], int m, int n) inline static
static void alglib.matgen.smatrixrndmultiply (ref double a[,], int n) inline static
static void alglib.matgen.hmatrixrndmultiply (ref complex a[,], int n) inline static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/linalg.cs