IGLib: alglib.smp Class Reference
alglib.smp Class Reference
Classes
class ae_lock
class shared_pool
class sharedpoolentry
Static Public Member Functions
static void ae_spin_wait (int cnt)
static void ae_yield ()
static void ae_init_lock (ref ae_lock obj)
static void ae_acquire_lock (ae_lock obj)
static void ae_release_lock (ae_lock obj)
static void ae_free_lock (ref ae_lock obj)
static bool ae_shared_pool_is_initialized (shared_pool dst)
static void ae_shared_pool_set_seed (shared_pool dst, alglib.apobject seed_object)
static void ae_shared_pool_retrieve< T > (shared_pool pool, ref T obj)
static void ae_shared_pool_recycle< T > (shared_pool pool, ref T obj)
static void ae_shared_pool_clear_recycled (shared_pool pool)
static void ae_shared_pool_first_recycled< T > (shared_pool pool, ref T obj)
static void ae_shared_pool_next_recycled< T > (shared_pool pool, ref T obj)
static void ae_shared_pool_reset (shared_pool pool)
Public Attributes
const int AE_LOCK_CYCLES = 512
const int AE_LOCK_TESTS_BEFORE_YIELD = 16
Static Public Attributes
static volatile int never_change_it = 0
static int cores_count = 1
static volatile int cores_to_use = 0
Member Function Documentation
static void alglib.smp.ae_spin_wait (int cnt) inline static
static void alglib.smp.ae_yield () inline static
static void alglib.smp.ae_init_lock (ref ae_lock obj) inline static
static void alglib.smp.ae_acquire_lock (ae_lock obj) inline static
References alglib.smp.ae_lock.is_locked.
static void alglib.smp.ae_release_lock (ae_lock obj) inline static
References alglib.smp.ae_lock.is_locked.
static void alglib.smp.ae_free_lock (ref ae_lock obj) inline static
static bool alglib.smp.ae_shared_pool_is_initialized (shared_pool dst) inline static
References alglib.smp.shared_pool.seed_object.
Referenced by alglib.testalglibbasicsunit.sharedpoolerrors().
static void alglib.smp.ae_shared_pool_set_seed (shared_pool dst, alglib.apobject seed_object) inline static
References alglib.smp.shared_pool.enumeration_counter, alglib.apobject.make_copy(), alglib.smp.shared_pool.recycled_objects, and alglib.smp.shared_pool.seed_object.
Referenced by alglib.testalglibbasicsunit.createpoolandrecords(), alglib.ftbase.ftcomplexfftplan(), alglib.testalglibbasicsunit.performtestpoolsum(), alglib.basestat.rankdata(), alglib.basestat.rankdatacentered(), and alglib.testalglibbasicsunit.sharedpoolerrors().
static void alglib.smp.ae_shared_pool_retrieve< T > (shared_pool pool, ref T obj) inline static
Type Constraints
T : alglib.apobject
static void alglib.smp.ae_shared_pool_recycle< T > (shared_pool pool, ref T obj) inline static
Type Constraints
T : alglib.apobject
static void alglib.smp.ae_shared_pool_clear_recycled (shared_pool pool) inline static
References alglib.smp.shared_pool.recycled_objects.
Referenced by alglib.testalglibbasicsunit.sharedpoolerrors().
static void alglib.smp.ae_shared_pool_first_recycled< T > (shared_pool pool, ref T obj) inline static
Type Constraints
T : alglib.apobject
static void alglib.smp.ae_shared_pool_next_recycled< T > (shared_pool pool, ref T obj) inline static
Type Constraints
T : alglib.apobject
static void alglib.smp.ae_shared_pool_reset (shared_pool pool) inline static
References alglib.smp.shared_pool.enumeration_counter, alglib.smp.shared_pool.recycled_objects, and alglib.smp.shared_pool.seed_object.
Referenced by alglib.testalglibbasicsunit.sharedpoolerrors().
Member Data Documentation
const int alglib.smp.AE_LOCK_CYCLES = 512
const int alglib.smp.AE_LOCK_TESTS_BEFORE_YIELD = 16
volatile int alglib.smp.never_change_it = 0 static
int alglib.smp.cores_count = 1 static
Referenced by _Test.Main().
volatile int alglib.smp.cores_to_use = 0 static
Referenced by alglib.setnworkers().
The documentation for this class was generated from the following file:
igtest/numerics/alglib_0.8.2/src/ap.cs