IGLib: alglib.trfac Class Reference
alglib.trfac Class Reference
Static Public Member Functions
static void rmatrixlu (ref double[,] a, int m, int n, ref int[] pivots)
static void cmatrixlu (ref complex[,] a, int m, int n, ref int[] pivots)
static bool hpdmatrixcholesky (ref complex[,] a, int n, bool isupper)
static bool spdmatrixcholesky (ref double[,] a, int n, bool isupper)
static void rmatrixlup (ref double[,] a, int m, int n, ref int[] pivots)
static void cmatrixlup (ref complex[,] a, int m, int n, ref int[] pivots)
static void rmatrixplu (ref double[,] a, int m, int n, ref int[] pivots)
static void cmatrixplu (ref complex[,] a, int m, int n, ref int[] pivots)
static bool spdmatrixcholeskyrec (ref double[,] a, int offs, int n, bool isupper, ref double[] tmp)
static void rmatrixlu (ref double[,] a, int m, int n, ref int[] pivots)
static void cmatrixlu (ref complex[,] a, int m, int n, ref int[] pivots)
static bool hpdmatrixcholesky (ref complex[,] a, int n, bool isupper)
static bool spdmatrixcholesky (ref double[,] a, int n, bool isupper)
static void rmatrixlup (ref double[,] a, int m, int n, ref int[] pivots)
static void cmatrixlup (ref complex[,] a, int m, int n, ref int[] pivots)
static void rmatrixplu (ref double[,] a, int m, int n, ref int[] pivots)
static void cmatrixplu (ref complex[,] a, int m, int n, ref int[] pivots)
static bool spdmatrixcholeskyrec (ref double[,] a, int offs, int n, bool isupper, ref double[] tmp)
Static Private Member Functions
static void cmatrixluprec (ref complex[,] a, int offs, int m, int n, ref int[] pivots, ref complex[] tmp)
static void rmatrixluprec (ref double[,] a, int offs, int m, int n, ref int[] pivots, ref double[] tmp)
static void cmatrixplurec (ref complex[,] a, int offs, int m, int n, ref int[] pivots, ref complex[] tmp)
static void rmatrixplurec (ref double[,] a, int offs, int m, int n, ref int[] pivots, ref double[] tmp)
static void cmatrixlup2 (ref complex[,] a, int offs, int m, int n, ref int[] pivots, ref complex[] tmp)
static void rmatrixlup2 (ref double[,] a, int offs, int m, int n, ref int[] pivots, ref double[] tmp)
static void cmatrixplu2 (ref complex[,] a, int offs, int m, int n, ref int[] pivots, ref complex[] tmp)
static void rmatrixplu2 (ref double[,] a, int offs, int m, int n, ref int[] pivots, ref double[] tmp)
static bool hpdmatrixcholeskyrec (ref complex[,] a, int offs, int n, bool isupper, ref complex[] tmp)
static bool hpdmatrixcholesky2 (ref complex[,] aaa, int offs, int n, bool isupper, ref complex[] tmp)
static bool spdmatrixcholesky2 (ref double[,] aaa, int offs, int n, bool isupper, ref double[] tmp)
static void cmatrixluprec (ref complex[,] a, int offs, int m, int n, ref int[] pivots, ref complex[] tmp)
static void rmatrixluprec (ref double[,] a, int offs, int m, int n, ref int[] pivots, ref double[] tmp)
static void cmatrixplurec (ref complex[,] a, int offs, int m, int n, ref int[] pivots, ref complex[] tmp)
static void rmatrixplurec (ref double[,] a, int offs, int m, int n, ref int[] pivots, ref double[] tmp)
static void cmatrixlup2 (ref complex[,] a, int offs, int m, int n, ref int[] pivots, ref complex[] tmp)
static void rmatrixlup2 (ref double[,] a, int offs, int m, int n, ref int[] pivots, ref double[] tmp)
static void cmatrixplu2 (ref complex[,] a, int offs, int m, int n, ref int[] pivots, ref complex[] tmp)
static void rmatrixplu2 (ref double[,] a, int offs, int m, int n, ref int[] pivots, ref double[] tmp)
static bool hpdmatrixcholeskyrec (ref complex[,] a, int offs, int n, bool isupper, ref complex[] tmp)
static bool hpdmatrixcholesky2 (ref complex[,] aaa, int offs, int n, bool isupper, ref complex[] tmp)
static bool spdmatrixcholesky2 (ref double[,] aaa, int offs, int n, bool isupper, ref double[] tmp)
Member Function Documentation
static void alglib.trfac.rmatrixlu (ref double a[,], int m, int n, ref int[] pivots) inline static
Referenced by alglib.testrcondunit.rmatrixinvmat(), alglib.rmatrixlu(), alglib.densesolver.rmatrixsolvem(), alglib.testmatinvunit.testrinv(), alglib.testrcondunit.testrmatrixrcond(), and alglib.testdensesolverunit.testrsolver().
static void alglib.trfac.cmatrixlu (ref complex a[,], int m, int n, ref int[] pivots) inline static
Referenced by alglib.testrcondunit.cmatrixinvmat(), alglib.cmatrixlu(), alglib.densesolver.cmatrixsolvem(), alglib.testmatinvunit.testcinv(), alglib.testrcondunit.testcmatrixrcond(), and alglib.testdensesolverunit.testcsolver().
static bool alglib.trfac.hpdmatrixcholesky (ref complex a[,], int n, bool isupper) inline static
Referenced by alglib.hpdmatrixcholesky(), alglib.densesolver.hpdmatrixsolvem(), alglib.testmatinvunit.testhpdinv(), alglib.testrcondunit.testhpdmatrixrcond(), alglib.testdensesolverunit.testhpdsolver(), and alglib.testtrfacunit.testtrfac().
static bool alglib.trfac.spdmatrixcholesky (ref double a[,], int n, bool isupper) inline static
Referenced by alglib.logit.mnltrainh(), alglib.spdmatrixcholesky(), alglib.densesolver.spdmatrixsolvem(), alglib.testmatinvunit.testspdinv(), alglib.testrcondunit.testspdmatrixrcond(), alglib.testdensesolverunit.testspdsolver(), and alglib.testtrfacunit.testtrfac().
static void alglib.trfac.rmatrixlup (ref double a[,], int m, int n, ref int[] pivots) inline static
Referenced by alglib.testtrfacunit.testrluproblem().
static void alglib.trfac.cmatrixlup (ref complex a[,], int m, int n, ref int[] pivots) inline static
Referenced by alglib.testtrfacunit.testcluproblem().
static void alglib.trfac.rmatrixplu (ref double a[,], int m, int n, ref int[] pivots) inline static
Referenced by alglib.testtrfacunit.testrluproblem().
static void alglib.trfac.cmatrixplu (ref complex a[,], int m, int n, ref int[] pivots) inline static
Referenced by alglib.testtrfacunit.testcluproblem().
static bool alglib.trfac.spdmatrixcholeskyrec (ref double a[,], int offs, int n, bool isupper, ref double[] tmp) inline static
Referenced by alglib.cqmodels.cqmrebuild(), and alglib.mincg.mincgsetpreclowrankfast().
static void alglib.trfac.cmatrixluprec (ref complex a[,], int offs, int m, int n, ref int[] pivots, ref complex[] tmp) inline static private
static void alglib.trfac.rmatrixluprec (ref double a[,], int offs, int m, int n, ref int[] pivots, ref double[] tmp) inline static private
static void alglib.trfac.cmatrixplurec (ref complex a[,], int offs, int m, int n, ref int[] pivots, ref complex[] tmp) inline static private
static void alglib.trfac.rmatrixplurec (ref double a[,], int offs, int m, int n, ref int[] pivots, ref double[] tmp) inline static private
static void alglib.trfac.cmatrixlup2 (ref complex a[,], int offs, int m, int n, ref int[] pivots, ref complex[] tmp) inline static private
static void alglib.trfac.rmatrixlup2 (ref double a[,], int offs, int m, int n, ref int[] pivots, ref double[] tmp) inline static private
static void alglib.trfac.cmatrixplu2 (ref complex a[,], int offs, int m, int n, ref int[] pivots, ref complex[] tmp) inline static private
static void alglib.trfac.rmatrixplu2 (ref double a[,], int offs, int m, int n, ref int[] pivots, ref double[] tmp) inline static private
static bool alglib.trfac.hpdmatrixcholeskyrec (ref complex a[,], int offs, int n, bool isupper, ref complex[] tmp) inline static private
static bool alglib.trfac.hpdmatrixcholesky2 (ref complex aaa[,], int offs, int n, bool isupper, ref complex[] tmp) inline static private
static bool alglib.trfac.spdmatrixcholesky2 (ref double aaa[,], int offs, int n, bool isupper, ref double[] tmp) inline static private
static void alglib.trfac.rmatrixlu (ref double a[,], int m, int n, ref int[] pivots) inline static
static void alglib.trfac.cmatrixlu (ref complex a[,], int m, int n, ref int[] pivots) inline static
static bool alglib.trfac.hpdmatrixcholesky (ref complex a[,], int n, bool isupper) inline static
static bool alglib.trfac.spdmatrixcholesky (ref double a[,], int n, bool isupper) inline static
static void alglib.trfac.rmatrixlup (ref double a[,], int m, int n, ref int[] pivots) inline static
static void alglib.trfac.cmatrixlup (ref complex a[,], int m, int n, ref int[] pivots) inline static
static void alglib.trfac.rmatrixplu (ref double a[,], int m, int n, ref int[] pivots) inline static
static void alglib.trfac.cmatrixplu (ref complex a[,], int m, int n, ref int[] pivots) inline static
static bool alglib.trfac.spdmatrixcholeskyrec (ref double a[,], int offs, int n, bool isupper, ref double[] tmp) inline static
static void alglib.trfac.cmatrixluprec (ref complex a[,], int offs, int m, int n, ref int[] pivots, ref complex[] tmp) inline static private
static void alglib.trfac.rmatrixluprec (ref double a[,], int offs, int m, int n, ref int[] pivots, ref double[] tmp) inline static private
static void alglib.trfac.cmatrixplurec (ref complex a[,], int offs, int m, int n, ref int[] pivots, ref complex[] tmp) inline static private
static void alglib.trfac.rmatrixplurec (ref double a[,], int offs, int m, int n, ref int[] pivots, ref double[] tmp) inline static private
static void alglib.trfac.cmatrixlup2 (ref complex a[,], int offs, int m, int n, ref int[] pivots, ref complex[] tmp) inline static private
static void alglib.trfac.rmatrixlup2 (ref double a[,], int offs, int m, int n, ref int[] pivots, ref double[] tmp) inline static private
static void alglib.trfac.cmatrixplu2 (ref complex a[,], int offs, int m, int n, ref int[] pivots, ref complex[] tmp) inline static private
static void alglib.trfac.rmatrixplu2 (ref double a[,], int offs, int m, int n, ref int[] pivots, ref double[] tmp) inline static private
static bool alglib.trfac.hpdmatrixcholeskyrec (ref complex a[,], int offs, int n, bool isupper, ref complex[] tmp) inline static private
static bool alglib.trfac.hpdmatrixcholesky2 (ref complex aaa[,], int offs, int n, bool isupper, ref complex[] tmp) inline static private
static bool alglib.trfac.spdmatrixcholesky2 (ref double aaa[,], int offs, int n, bool isupper, ref double[] tmp) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/linalg.cs