IGLib: IG.Sendigence.FormWriterBase Class Reference
IG.Sendigence.FormWriterBase Class Reference abstract
Public Member Functions
void InitStyles (TextStyle source)
void InitStyles (Control source)
void InitStyles (RichTextBox source)
abstract void SetStyle (TextStyle style)
abstract void Write (string str)
void WriteLine (string str)
void WriteProgramdata (IG.Lib.ProgramBase prog)
void InitStyles (TextStyle source)
void InitStyles (Control source)
void InitStyles (RichTextBox source)
abstract void SetStyle (TextStyle style)
abstract void Write (string str)
void WriteLine (string str)
void WriteProgramdata (IG.Lib.ModuleBase prog)
Public Attributes
TextStyle Heading1 = new TextStyle(null, Color.White, Color.Red)
Private Member Functions
void InitStylesAfter ()
void InitStylesAfter ()
Private Attributes
TextStyle _currentstyle = null
Dictionary< string, TextStyle > styles = new Dictionary<string,TextStyle>()
TextStyle Heading2 = new TextStyle(null, Color.White, Color.Red)
TextStyle Heading3 = new TextStyle(null, Color.White, Color.Red)
TextStyle Text = new TextStyle(null, Color.White, Color.Black)
TextStyle Bold = new TextStyle(null, Color.White, Color.Black)
TextStyle Italic = new TextStyle(null, Color.White, Color.Black)
TextStyle BoldItalic =new TextStyle(null, Color.White, Color.Black)
TextStyle Small = new TextStyle(null, Color.White, Color.Black)
Member Function Documentation
void IG.Sendigence.FormWriterBase.InitStylesAfter () inline private
References IG.Sendigence.TextStyle.SizeInPoints.
void IG.Sendigence.FormWriterBase.InitStyles (TextStyle source) inline
References IG.Sendigence.TextStyle.Copy().
void IG.Sendigence.FormWriterBase.InitStyles (Control source) inline
References IG.Sendigence.TextStyle.Copy().
void IG.Sendigence.FormWriterBase.InitStyles (RichTextBox source) inline
References IG.Sendigence.TextStyle.Copy().
abstract void IG.Sendigence.FormWriterBase.SetStyle (TextStyle style) pure virtual
abstract void IG.Sendigence.FormWriterBase.Write (string str) pure virtual
void IG.Sendigence.FormWriterBase.WriteLine (string str) inline
void IG.Sendigence.FormWriterBase.WriteProgramdata (IG.Lib.ProgramBase prog) inline
void IG.Sendigence.FormWriterBase.InitStylesAfter () inline private
void IG.Sendigence.FormWriterBase.InitStyles (TextStyle source) inline
References IG.Sendigence.TextStyle.Copy().
void IG.Sendigence.FormWriterBase.InitStyles (Control source) inline
References IG.Sendigence.TextStyle.Copy().
void IG.Sendigence.FormWriterBase.InitStyles (RichTextBox source) inline
References IG.Sendigence.TextStyle.Copy().
abstract void IG.Sendigence.FormWriterBase.SetStyle (TextStyle style) pure virtual
abstract void IG.Sendigence.FormWriterBase.Write (string str) pure virtual
void IG.Sendigence.FormWriterBase.WriteLine (string str) inline
void IG.Sendigence.FormWriterBase.WriteProgramdata (IG.Lib.ModuleBase prog) inline
Member Data Documentation
TextStyle IG.Sendigence.FormWriterBase._currentstyle = null private
Dictionary< string, TextStyle > IG.Sendigence.FormWriterBase.styles = new Dictionary<string,TextStyle>() private
TextStyle IG.Sendigence.FormWriterBase.Heading1 = new TextStyle(null, Color.White, Color.Red)
TextStyle IG.Sendigence.FormWriterBase.Heading2 = new TextStyle(null, Color.White, Color.Red) private
TextStyle IG.Sendigence.FormWriterBase.Heading3 = new TextStyle(null, Color.White, Color.Red) private
TextStyle IG.Sendigence.FormWriterBase.Text = new TextStyle(null, Color.White, Color.Black) private
TextStyle IG.Sendigence.FormWriterBase.Bold = new TextStyle(null, Color.White, Color.Black) private
TextStyle IG.Sendigence.FormWriterBase.Italic = new TextStyle(null, Color.White, Color.Black) private
TextStyle IG.Sendigence.FormWriterBase.BoldItalic =new TextStyle(null, Color.White, Color.Black) private
TextStyle IG.Sendigence.FormWriterBase.Small = new TextStyle(null, Color.White, Color.Black) private
The documentation for this class was generated from the following file:
igapp/copy/sendigence/sendigence_main_form.cs