IGLib: IPLab.MainForm Class Reference
IPLab.MainForm Class Reference
Summary description for Form1.
Public Member Functions
bool NewDocument (Bitmap image)
bool NewDocument (ComplexImage image)
Bitmap GetImage (object sender, String text, Size size, PixelFormat format)
Protected Types
enum AutoOpenMode { AutoOpenMode.None, AutoOpenMode.Clipboard, AutoOpenMode.File }
Specifies the action the application performs upon starting.
Protected Member Functions
MainForm (AutoOpenMode autoOpenMode, string autoOpenParam)
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
bool CreateNewDocumentOnChange [get]
bool RememberOnChange [get]
Properties inherited from IPLab.IDocumentsHost
bool CreateNewDocumentOnChange [get]
bool RememberOnChange [get]
Private Member Functions
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void MainForm_Load (object sender, System.EventArgs e)
Content GetContentFromPersistString (string persistString)
void mainToolBar_ButtonClick (object sender, System.Windows.Forms.ToolBarButtonClickEventArgs e)
void dockManager_ActiveDocumentChanged (object sender, System.EventArgs e)
void About ()
void aboutHelpItem_Click (object sender, System.EventArgs e)
void fileItem_Popup (object sender, System.EventArgs e)
void exitFileItem_Click (object sender, System.EventArgs e)
void SetupDocumentEvents (ImageDoc doc)
void OpenFile ()
void OpenFile (string fileName)
void ShowHistogram (bool show)
void ShowStatistics (bool show)
void OpenItem_Click (object sender, System.EventArgs e)
void reloadFileItem_Click (object sender, System.EventArgs e)
void SaveFile ()
string CreateCppImageClass (Bitmap image, string className)
void saveFileItem_Click (object sender, System.EventArgs e)
void CopyToClipboard ()
void copyFileItem_Click (object sender, System.EventArgs e)
void PasteFromClipboard ()
void pasteFileItem_Click (object sender, System.EventArgs e)
void closeFileItem_Click (object sender, System.EventArgs e)
void closeAllFileItem_Click (object sender, System.EventArgs e)
void pageSetupFileItem_Click (object sender, System.EventArgs e)
void printFileItem_Click (object sender, System.EventArgs e)
void printPreviewFileItem_Click (object sender, System.EventArgs e)
void optionsItem_Popup (object sender, System.EventArgs e)
void openInNewOptionsItem_Click (object sender, System.EventArgs e)
void rememberOptionsItem_Click (object sender, System.EventArgs e)
void viewItem_Popup (object sender, System.EventArgs e)
void histogramViewItem_Click (object sender, System.EventArgs e)
void statisticsViewItem_Click (object sender, System.EventArgs e)
void histogram_VisibleChanged (object sender, System.EventArgs e)
void statistics_VisibleChanged (object sender, System.EventArgs e)
void centerViewItem_Click (object sender, System.EventArgs e)
void redHistogramViewItem_Click (object sender, System.EventArgs e)
void greenHistogramViewItem_Click (object sender, System.EventArgs e)
void blueHistogramViewItem_Click (object sender, System.EventArgs e)
void document_DocumentChanged (object sender, System.EventArgs e)
void document_ZoomChanged (object sender, System.EventArgs e)
void document_MouseImagePosition (object sender, SelectionEventArgs e)
void document_SelectionChanged (object sender, SelectionEventArgs e)
void UpdateHistogram (ImageDoc imgDoc)
void UpdateStatistics (ImageDoc imgDoc)
void UpdateSizeStatus (Content doc)
void UpdateZoomStatus (ImageDoc imgDoc)
void imageToolBar_ButtonClick (object sender, System.Windows.Forms.ToolBarButtonClickEventArgs e)
void mainBarViewItem_Click (object sender, System.EventArgs e)
void imageBarViewItem_Click (object sender, System.EventArgs e)
void histogram_DockStateChanged (object sender, System.EventArgs e)
void statistics_DockStateChanged (object sender, System.EventArgs e)
void printDocument_PrintPage (object sender, System.Drawing.Printing.PrintPageEventArgs e)
void dockManager_DragEnter (object sender, DragEventArgs e)
void dockManager_DragDrop (object sender, DragEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Static Private Member Functions
static void Main (string[] args)
The main entry point for the application.
Private Attributes
int unNamedNumber = 0
Configuration config = new Configuration()
HistogramWindow histogramWin = new HistogramWindow()
ImageStatisticsWindow statisticsWin = new ImageStatisticsWindow()
ToolBarManager toolBarManager
AutoOpenMode autoOpenMode
string autoOpenParam
System.ComponentModel.IContainer components
WeifenLuo.WinFormsUI.DockManager dockManager
System.Windows.Forms.MainMenu mainMenu
System.Windows.Forms.MenuItem fileItem
System.Windows.Forms.MenuItem exitFileItem
System.Windows.Forms.MenuItem OpenItem
System.Windows.Forms.MenuItem menuItem2
System.Windows.Forms.MenuItem closeFileItem
System.Windows.Forms.MenuItem closeAllFileItem
System.Windows.Forms.MenuItem optionsItem
System.Windows.Forms.MenuItem openInNewOptionsItem
System.Windows.Forms.MenuItem viewItem
System.Windows.Forms.MenuItem windowItem
System.Windows.Forms.MenuItem helpItem
System.Windows.Forms.MenuItem histogramViewItem
System.Windows.Forms.MenuItem redHistogramViewItem
System.Windows.Forms.MenuItem greenHistogramViewItem
System.Windows.Forms.MenuItem blueHistogramViewItem
System.Windows.Forms.StatusBarPanel zoomPanel
System.Windows.Forms.StatusBarPanel sizePanel
System.Windows.Forms.StatusBarPanel infoPanel
System.Windows.Forms.Panel panel1
System.Windows.Forms.StatusBar statusBar
System.Windows.Forms.MenuItem rememberOptionsItem
System.Windows.Forms.MenuItem menuItem1
System.Windows.Forms.MenuItem reloadFileItem
System.Windows.Forms.MenuItem menuItem3
System.Windows.Forms.MenuItem centerViewItem
System.Windows.Forms.StatusBarPanel selectionPanel
System.Windows.Forms.OpenFileDialog ofd
System.Windows.Forms.StatusBarPanel colorPanel
System.Windows.Forms.ImageList imageList
System.Windows.Forms.ToolBar mainToolBar
System.Windows.Forms.ToolBarButton openButton
System.Windows.Forms.ToolBarButton sep1
System.Windows.Forms.ToolBarButton histogramButton
System.Windows.Forms.ToolBar imageToolBar
System.Windows.Forms.ImageList imageList2
System.Windows.Forms.ToolBarButton cloneButton
System.Windows.Forms.ToolBarButton cropButton
System.Windows.Forms.ToolBarButton toolBarButton1
System.Windows.Forms.ToolBarButton toolBarButton2
System.Windows.Forms.ToolBarButton zoomInButton
System.Windows.Forms.ToolBarButton zoomOutButton
System.Windows.Forms.ToolBarButton toolBarButton3
System.Windows.Forms.ToolBarButton fitToScreenButton
System.Windows.Forms.ToolBarButton toolBarButton4
System.Windows.Forms.ToolBarButton aboutButton
System.Windows.Forms.ToolBarButton toolBarButton5
System.Windows.Forms.ToolBarButton levelsButton
System.Windows.Forms.ToolBarButton grayscaleButton
System.Windows.Forms.ToolBarButton thresholdButton
System.Windows.Forms.ToolBarButton toolBarButton6
System.Windows.Forms.ToolBarButton morphologyButton
System.Windows.Forms.ToolBarButton convolutionButton
System.Windows.Forms.MenuItem mainBarViewItem
System.Windows.Forms.MenuItem imageBarViewItem
System.Windows.Forms.MenuItem menuItem7
System.Windows.Forms.ToolBarButton resizeButton
System.Windows.Forms.ToolBarButton toolBarButton7
System.Windows.Forms.ToolBarButton rotateButton
System.Windows.Forms.StatusBarPanel hslPanel
System.Windows.Forms.ToolBarButton toolBarButton8
System.Windows.Forms.ToolBarButton saturationButton
System.Windows.Forms.ToolBarButton fourierButton
System.Windows.Forms.MenuItem copyFileItem
System.Windows.Forms.MenuItem pasteFileItem
System.Windows.Forms.MenuItem menuItem5
System.Windows.Forms.MenuItem saveFileItem
System.Windows.Forms.MenuItem aboutHelpItem
System.Windows.Forms.SaveFileDialog sfd
System.Windows.Forms.ToolBarButton pasteButton
System.Windows.Forms.ToolBarButton saveButton
System.Windows.Forms.ToolBarButton copyButton
System.Windows.Forms.ToolBarButton toolBarButton9
System.Drawing.Printing.PrintDocument printDocument
System.Windows.Forms.PrintPreviewDialog printPreviewDialog
System.Windows.Forms.MenuItem printPreviewFileItem
System.Windows.Forms.MenuItem pageSetupFileItem
System.Windows.Forms.MenuItem printFileItem
System.Windows.Forms.MenuItem menuItem8
System.Windows.Forms.PageSetupDialog pageSetupDialog
System.Windows.Forms.PrintDialog printDialog
System.Windows.Forms.StatusBarPanel ycbcrPanel
System.Windows.Forms.MenuItem statisticsViewItem
Static Private Attributes
static string configFile = Path.Combine(System.Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), @"IPLab\settings.config")
static string dockManagerConfigFile = Path.Combine(System.Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), @"IPLab\DockManager.config")
Detailed Description
Summary description for Form1.
Member Enumeration Documentation
enum IPLab.MainForm.AutoOpenMode protected
Specifies the action the application performs upon starting.
Enumerator
None
Clipboard
File
Constructor & Destructor Documentation
IPLab.MainForm.MainForm (AutoOpenMode autoOpenMode, string autoOpenParam) inline protected
References IPLab.MainForm.autoOpenMode, IPLab.MainForm.autoOpenParam, IPLab.MainForm.dockManager, IPLab.MainForm.dockManager_DragDrop(), IPLab.MainForm.dockManager_DragEnter(), IPLab.MainForm.histogram_DockStateChanged(), IPLab.MainForm.histogram_VisibleChanged(), IPLab.MainForm.imageToolBar, IPLab.MainForm.InitializeComponent(), IPLab.MainForm.mainToolBar, IPLab.MainForm.statistics_DockStateChanged(), and IPLab.MainForm.statistics_VisibleChanged().
Referenced by IPLab.MainForm.Main().
Member Function Documentation
static void IPLab.MainForm.Main (string[] args) inline static private
The main entry point for the application.
References IPLab.MainForm.File, and IPLab.MainForm.MainForm().
bool IPLab.MainForm.NewDocument (Bitmap image) inline
Implements IPLab.IDocumentsHost.
References IPLab.MainForm.dockManager, and IPLab.MainForm.SetupDocumentEvents().
bool IPLab.MainForm.NewDocument (ComplexImage image) inline
Implements IPLab.IDocumentsHost.
References IPLab.MainForm.dockManager.
Bitmap IPLab.MainForm.GetImage (object sender, String text, Size size, PixelFormat format) inline
Implements IPLab.IDocumentsHost.
References IPLab.SelectImageForm.Description, IPLab.MainForm.dockManager, IPLab.SelectImageForm.ImageNames, and IPLab.SelectImageForm.SelectedItem.
void IPLab.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References IPLab.MainForm.dockManager, IPLab.Configuration.mainWindowLocation, IPLab.Configuration.mainWindowSize, and IPLab.Configuration.Save().
void IPLab.MainForm.MainForm_Load (object sender, System.EventArgs e) inline private
References IPLab.MainForm.dockManager, IPLab.MainForm.File, IPLab.MainForm.GetContentFromPersistString(), IPLab.Configuration.histogramVisible, IPLab.Configuration.Load(), IPLab.Configuration.mainWindowLocation, IPLab.Configuration.mainWindowSize, IPLab.MainForm.OpenFile(), IPLab.MainForm.PasteFromClipboard(), and IPLab.MainForm.ShowHistogram().
Content IPLab.MainForm.GetContentFromPersistString (string persistString) inline private
References IPLab.MainForm.histogramWin, and IPLab.MainForm.statisticsWin.
Referenced by IPLab.MainForm.MainForm_Load().
void IPLab.MainForm.mainToolBar_ButtonClick (object sender, System.Windows.Forms.ToolBarButtonClickEventArgs e) inline private
References IPLab.MainForm.About(), IPLab.MainForm.CopyToClipboard(), IPLab.Configuration.histogramVisible, IPLab.MainForm.OpenFile(), IPLab.MainForm.PasteFromClipboard(), IPLab.MainForm.SaveFile(), and IPLab.MainForm.ShowHistogram().
void IPLab.MainForm.dockManager_ActiveDocumentChanged (object sender, System.EventArgs e) inline private
References IPLab.MainForm.dockManager, IPLab.MainForm.UpdateHistogram(), IPLab.MainForm.UpdateSizeStatus(), IPLab.MainForm.UpdateStatistics(), and IPLab.MainForm.UpdateZoomStatus().
void IPLab.MainForm.About () inline private
Referenced by IPLab.MainForm.aboutHelpItem_Click(), and IPLab.MainForm.mainToolBar_ButtonClick().
void IPLab.MainForm.aboutHelpItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.About().
void IPLab.MainForm.fileItem_Popup (object sender, System.EventArgs e) inline private
References IPLab.MainForm.Clipboard, IPLab.MainForm.closeAllFileItem, IPLab.MainForm.closeFileItem, IPLab.MainForm.copyFileItem, IPLab.MainForm.dockManager, IPLab.MainForm.pasteFileItem, IPLab.MainForm.printFileItem, IPLab.MainForm.printPreviewFileItem, IPLab.MainForm.reloadFileItem, and IPLab.MainForm.saveFileItem.
void IPLab.MainForm.exitFileItem_Click (object sender, System.EventArgs e) inline private
void IPLab.MainForm.SetupDocumentEvents (ImageDoc doc) inline private
References IPLab.MainForm.document_DocumentChanged(), IPLab.MainForm.document_MouseImagePosition(), IPLab.MainForm.document_SelectionChanged(), IPLab.MainForm.document_ZoomChanged(), IPLab.ImageDoc.DocumentChanged, IPLab.ImageDoc.MouseImagePosition, IPLab.ImageDoc.SelectionChanged, IPLab.ImageDoc.SelectionEventHandler(), and IPLab.ImageDoc.ZoomChanged.
Referenced by IPLab.MainForm.NewDocument(), IPLab.MainForm.OpenFile(), and IPLab.MainForm.PasteFromClipboard().
void IPLab.MainForm.OpenFile () inline private
References IPLab.MainForm.ofd.
Referenced by IPLab.MainForm.dockManager_DragDrop(), IPLab.MainForm.MainForm_Load(), IPLab.MainForm.mainToolBar_ButtonClick(), and IPLab.MainForm.OpenItem_Click().
void IPLab.MainForm.OpenFile (string fileName) inline private
References IPLab.MainForm.dockManager, IG.Lib.ImageBuilderBase.LoadCsv(), IPLab.MainForm.SetupDocumentEvents(), and IG.Lib.ImageBuilderBase.ToBitmap().
void IPLab.MainForm.ShowHistogram (bool show) inline private
References IPLab.MainForm.dockManager, IPLab.MainForm.histogramButton, IPLab.MainForm.histogramViewItem, and IPLab.Configuration.histogramVisible.
Referenced by IPLab.MainForm.histogramViewItem_Click(), IPLab.MainForm.MainForm_Load(), and IPLab.MainForm.mainToolBar_ButtonClick().
void IPLab.MainForm.ShowStatistics (bool show) inline private
References IPLab.MainForm.dockManager, IPLab.MainForm.statisticsViewItem, and IPLab.Configuration.statisticsVisible.
Referenced by IPLab.MainForm.statisticsViewItem_Click().
void IPLab.MainForm.OpenItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.OpenFile().
void IPLab.MainForm.reloadFileItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.dockManager.
void IPLab.MainForm.SaveFile () inline private
References IPLab.MainForm.CreateCppImageClass(), IPLab.MainForm.dockManager, IPLab.ImageDoc.Image, IG.Lib.ImageBuilderBase.SaveCsv(), IPLab.MainForm.sfd, and IG.Lib.ImageBuilderBase.ToBitmap().
Referenced by IPLab.MainForm.mainToolBar_ButtonClick(), and IPLab.MainForm.saveFileItem_Click().
string IPLab.MainForm.CreateCppImageClass (Bitmap image, string className) inline private
Referenced by IPLab.MainForm.SaveFile().
void IPLab.MainForm.saveFileItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.SaveFile().
void IPLab.MainForm.CopyToClipboard () inline private
References IPLab.MainForm.Clipboard, and IPLab.MainForm.dockManager.
Referenced by IPLab.MainForm.copyFileItem_Click(), and IPLab.MainForm.mainToolBar_ButtonClick().
void IPLab.MainForm.copyFileItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.CopyToClipboard().
void IPLab.MainForm.PasteFromClipboard () inline private
References IPLab.MainForm.Clipboard, IPLab.MainForm.dockManager, and IPLab.MainForm.SetupDocumentEvents().
Referenced by IPLab.MainForm.MainForm_Load(), IPLab.MainForm.mainToolBar_ButtonClick(), and IPLab.MainForm.pasteFileItem_Click().
void IPLab.MainForm.pasteFileItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.PasteFromClipboard().
void IPLab.MainForm.closeFileItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.dockManager.
void IPLab.MainForm.closeAllFileItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.dockManager.
void IPLab.MainForm.pageSetupFileItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.pageSetupDialog, and IPLab.MainForm.printDocument.
void IPLab.MainForm.printFileItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.dockManager, IPLab.MainForm.printDialog, and IPLab.MainForm.printDocument.
void IPLab.MainForm.printPreviewFileItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.dockManager, IPLab.MainForm.printDocument, and IPLab.MainForm.printPreviewDialog.
void IPLab.MainForm.optionsItem_Popup (object sender, System.EventArgs e) inline private
References IPLab.Configuration.openInNewDoc, IPLab.MainForm.openInNewOptionsItem, IPLab.Configuration.rememberOnChange, and IPLab.MainForm.rememberOptionsItem.
void IPLab.MainForm.openInNewOptionsItem_Click (object sender, System.EventArgs e) inline private
References IPLab.Configuration.openInNewDoc.
void IPLab.MainForm.rememberOptionsItem_Click (object sender, System.EventArgs e) inline private
References IPLab.Configuration.rememberOnChange.
void IPLab.MainForm.viewItem_Popup (object sender, System.EventArgs e) inline private
References IPLab.MainForm.centerViewItem, IPLab.MainForm.dockManager, IPLab.MainForm.imageBarViewItem, IPLab.MainForm.imageToolBar, IPLab.MainForm.mainBarViewItem, and IPLab.MainForm.mainToolBar.
void IPLab.MainForm.histogramViewItem_Click (object sender, System.EventArgs e) inline private
References IPLab.Configuration.histogramVisible, and IPLab.MainForm.ShowHistogram().
void IPLab.MainForm.statisticsViewItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.ShowStatistics(), and IPLab.Configuration.statisticsVisible.
void IPLab.MainForm.histogram_VisibleChanged (object sender, System.EventArgs e) inline private
References IPLab.MainForm.dockManager, and IPLab.HistogramWindow.GatherStatistics().
Referenced by IPLab.MainForm.MainForm().
void IPLab.MainForm.statistics_VisibleChanged (object sender, System.EventArgs e) inline private
References IPLab.MainForm.dockManager, and IPLab.ImageStatisticsWindow.GatherStatistics().
Referenced by IPLab.MainForm.MainForm().
void IPLab.MainForm.centerViewItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.dockManager.
void IPLab.MainForm.redHistogramViewItem_Click (object sender, System.EventArgs e) inline private
References IPLab.HistogramWindow.SwitchChannel().
void IPLab.MainForm.greenHistogramViewItem_Click (object sender, System.EventArgs e) inline private
References IPLab.HistogramWindow.SwitchChannel().
void IPLab.MainForm.blueHistogramViewItem_Click (object sender, System.EventArgs e) inline private
References IPLab.HistogramWindow.SwitchChannel().
void IPLab.MainForm.document_DocumentChanged (object sender, System.EventArgs e) inline private
References IPLab.MainForm.UpdateHistogram(), IPLab.MainForm.UpdateSizeStatus(), and IPLab.MainForm.UpdateStatistics().
Referenced by IPLab.MainForm.SetupDocumentEvents().
void IPLab.MainForm.document_ZoomChanged (object sender, System.EventArgs e) inline private
References IPLab.MainForm.UpdateZoomStatus().
Referenced by IPLab.MainForm.SetupDocumentEvents().
void IPLab.MainForm.document_MouseImagePosition (object sender, SelectionEventArgs e) inline private
References IPLab.MainForm.colorPanel, IPLab.MainForm.hslPanel, IPLab.SelectionEventArgs.Location, IPLab.MainForm.selectionPanel, and IPLab.MainForm.ycbcrPanel.
Referenced by IPLab.MainForm.SetupDocumentEvents().
void IPLab.MainForm.document_SelectionChanged (object sender, SelectionEventArgs e) inline private
References IPLab.SelectionEventArgs.Location, IPLab.MainForm.selectionPanel, and IPLab.SelectionEventArgs.Size.
Referenced by IPLab.MainForm.SetupDocumentEvents().
void IPLab.MainForm.UpdateHistogram (ImageDoc imgDoc) inline private
References IPLab.HistogramWindow.GatherStatistics(), IPLab.Configuration.histogramVisible, and IPLab.ImageDoc.Image.
Referenced by IPLab.MainForm.dockManager_ActiveDocumentChanged(), and IPLab.MainForm.document_DocumentChanged().
void IPLab.MainForm.UpdateStatistics (ImageDoc imgDoc) inline private
References IPLab.ImageStatisticsWindow.GatherStatistics(), IPLab.ImageDoc.Image, and IPLab.Configuration.statisticsVisible.
Referenced by IPLab.MainForm.dockManager_ActiveDocumentChanged(), and IPLab.MainForm.document_DocumentChanged().
void IPLab.MainForm.UpdateSizeStatus (Content doc) inline private
References IPLab.MainForm.sizePanel.
Referenced by IPLab.MainForm.dockManager_ActiveDocumentChanged(), and IPLab.MainForm.document_DocumentChanged().
void IPLab.MainForm.UpdateZoomStatus (ImageDoc imgDoc) inline private
References IPLab.ImageDoc.Zoom, and IPLab.MainForm.zoomPanel.
Referenced by IPLab.MainForm.dockManager_ActiveDocumentChanged(), and IPLab.MainForm.document_ZoomChanged().
void IPLab.MainForm.imageToolBar_ButtonClick (object sender, System.Windows.Forms.ToolBarButtonClickEventArgs e) inline private
References IPLab.MainForm.dockManager.
void IPLab.MainForm.mainBarViewItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.mainToolBar.
void IPLab.MainForm.imageBarViewItem_Click (object sender, System.EventArgs e) inline private
References IPLab.MainForm.imageToolBar.
void IPLab.MainForm.histogram_DockStateChanged (object sender, System.EventArgs e) inline private
References IPLab.MainForm.histogramButton, IPLab.MainForm.histogramViewItem, and IPLab.Configuration.histogramVisible.
Referenced by IPLab.MainForm.MainForm().
void IPLab.MainForm.statistics_DockStateChanged (object sender, System.EventArgs e) inline private
References IPLab.MainForm.statisticsViewItem, and IPLab.Configuration.statisticsVisible.
Referenced by IPLab.MainForm.MainForm().
void IPLab.MainForm.printDocument_PrintPage (object sender, System.Drawing.Printing.PrintPageEventArgs e) inline private
References IPLab.MainForm.dockManager.
void IPLab.MainForm.dockManager_DragEnter (object sender, DragEventArgs e) inline private
Referenced by IPLab.MainForm.MainForm().
void IPLab.MainForm.dockManager_DragDrop (object sender, DragEventArgs e) inline private
References IPLab.MainForm.OpenFile().
Referenced by IPLab.MainForm.MainForm().
override void IPLab.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References IPLab.MainForm.components.
void IPLab.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IPLab.MainForm.MainForm().
Member Data Documentation
string IPLab.MainForm.configFile = Path.Combine(System.Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), @"IPLab\settings.config") static private
string IPLab.MainForm.dockManagerConfigFile = Path.Combine(System.Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), @"IPLab\DockManager.config") static private
int IPLab.MainForm.unNamedNumber = 0 private
Configuration IPLab.MainForm.config = new Configuration() private
HistogramWindow IPLab.MainForm.histogramWin = new HistogramWindow() private
Referenced by IPLab.MainForm.GetContentFromPersistString().
ImageStatisticsWindow IPLab.MainForm.statisticsWin = new ImageStatisticsWindow() private
Referenced by IPLab.MainForm.GetContentFromPersistString().
ToolBarManager IPLab.MainForm.toolBarManager private
AutoOpenMode IPLab.MainForm.autoOpenMode private
Referenced by IPLab.MainForm.MainForm().
string IPLab.MainForm.autoOpenParam private
Referenced by IPLab.MainForm.MainForm().
System.ComponentModel.IContainer IPLab.MainForm.components private
Referenced by IPLab.MainForm.Dispose().
WeifenLuo.WinFormsUI.DockManager IPLab.MainForm.dockManager private
Referenced by IPLab.MainForm.centerViewItem_Click(), IPLab.MainForm.closeAllFileItem_Click(), IPLab.MainForm.closeFileItem_Click(), IPLab.MainForm.CopyToClipboard(), IPLab.MainForm.dockManager_ActiveDocumentChanged(), IPLab.MainForm.fileItem_Popup(), IPLab.MainForm.GetImage(), IPLab.MainForm.histogram_VisibleChanged(), IPLab.MainForm.imageToolBar_ButtonClick(), IPLab.MainForm.MainForm(), IPLab.MainForm.MainForm_Closing(), IPLab.MainForm.MainForm_Load(), IPLab.MainForm.NewDocument(), IPLab.MainForm.OpenFile(), IPLab.MainForm.PasteFromClipboard(), IPLab.MainForm.printDocument_PrintPage(), IPLab.MainForm.printFileItem_Click(), IPLab.MainForm.printPreviewFileItem_Click(), IPLab.MainForm.reloadFileItem_Click(), IPLab.MainForm.SaveFile(), IPLab.MainForm.ShowHistogram(), IPLab.MainForm.ShowStatistics(), IPLab.MainForm.statistics_VisibleChanged(), and IPLab.MainForm.viewItem_Popup().
System.Windows.Forms.MainMenu IPLab.MainForm.mainMenu private
System.Windows.Forms.MenuItem IPLab.MainForm.fileItem private
System.Windows.Forms.MenuItem IPLab.MainForm.exitFileItem private
System.Windows.Forms.MenuItem IPLab.MainForm.OpenItem private
System.Windows.Forms.MenuItem IPLab.MainForm.menuItem2 private
System.Windows.Forms.MenuItem IPLab.MainForm.closeFileItem private
Referenced by IPLab.MainForm.fileItem_Popup().
System.Windows.Forms.MenuItem IPLab.MainForm.closeAllFileItem private
Referenced by IPLab.MainForm.fileItem_Popup().
System.Windows.Forms.MenuItem IPLab.MainForm.optionsItem private
System.Windows.Forms.MenuItem IPLab.MainForm.openInNewOptionsItem private
Referenced by IPLab.MainForm.optionsItem_Popup().
System.Windows.Forms.MenuItem IPLab.MainForm.viewItem private
System.Windows.Forms.MenuItem IPLab.MainForm.windowItem private
System.Windows.Forms.MenuItem IPLab.MainForm.helpItem private
System.Windows.Forms.MenuItem IPLab.MainForm.histogramViewItem private
Referenced by IPLab.MainForm.histogram_DockStateChanged(), and IPLab.MainForm.ShowHistogram().
System.Windows.Forms.MenuItem IPLab.MainForm.redHistogramViewItem private
System.Windows.Forms.MenuItem IPLab.MainForm.greenHistogramViewItem private
System.Windows.Forms.MenuItem IPLab.MainForm.blueHistogramViewItem private
System.Windows.Forms.StatusBarPanel IPLab.MainForm.zoomPanel private
Referenced by IPLab.MainForm.UpdateZoomStatus().
System.Windows.Forms.StatusBarPanel IPLab.MainForm.sizePanel private
Referenced by IPLab.MainForm.UpdateSizeStatus().
System.Windows.Forms.StatusBarPanel IPLab.MainForm.infoPanel private
System.Windows.Forms.Panel IPLab.MainForm.panel1 private
System.Windows.Forms.StatusBar IPLab.MainForm.statusBar private
System.Windows.Forms.MenuItem IPLab.MainForm.rememberOptionsItem private
Referenced by IPLab.MainForm.optionsItem_Popup().
System.Windows.Forms.MenuItem IPLab.MainForm.menuItem1 private
System.Windows.Forms.MenuItem IPLab.MainForm.reloadFileItem private
Referenced by IPLab.MainForm.fileItem_Popup().
System.Windows.Forms.MenuItem IPLab.MainForm.menuItem3 private
System.Windows.Forms.MenuItem IPLab.MainForm.centerViewItem private
Referenced by IPLab.MainForm.viewItem_Popup().
System.Windows.Forms.StatusBarPanel IPLab.MainForm.selectionPanel private
Referenced by IPLab.MainForm.document_MouseImagePosition(), and IPLab.MainForm.document_SelectionChanged().
System.Windows.Forms.OpenFileDialog IPLab.MainForm.ofd private
Referenced by IPLab.MainForm.OpenFile().
System.Windows.Forms.StatusBarPanel IPLab.MainForm.colorPanel private
Referenced by IPLab.MainForm.document_MouseImagePosition().
System.Windows.Forms.ImageList IPLab.MainForm.imageList private
System.Windows.Forms.ToolBar IPLab.MainForm.mainToolBar private
Referenced by IPLab.MainForm.mainBarViewItem_Click(), IPLab.MainForm.MainForm(), and IPLab.MainForm.viewItem_Popup().
System.Windows.Forms.ToolBarButton IPLab.MainForm.openButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.sep1 private
System.Windows.Forms.ToolBarButton IPLab.MainForm.histogramButton private
Referenced by IPLab.MainForm.histogram_DockStateChanged(), and IPLab.MainForm.ShowHistogram().
System.Windows.Forms.ToolBar IPLab.MainForm.imageToolBar private
Referenced by IPLab.MainForm.imageBarViewItem_Click(), IPLab.MainForm.MainForm(), and IPLab.MainForm.viewItem_Popup().
System.Windows.Forms.ImageList IPLab.MainForm.imageList2 private
System.Windows.Forms.ToolBarButton IPLab.MainForm.cloneButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.cropButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.toolBarButton1 private
System.Windows.Forms.ToolBarButton IPLab.MainForm.toolBarButton2 private
System.Windows.Forms.ToolBarButton IPLab.MainForm.zoomInButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.zoomOutButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.toolBarButton3 private
System.Windows.Forms.ToolBarButton IPLab.MainForm.fitToScreenButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.toolBarButton4 private
System.Windows.Forms.ToolBarButton IPLab.MainForm.aboutButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.toolBarButton5 private
System.Windows.Forms.ToolBarButton IPLab.MainForm.levelsButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.grayscaleButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.thresholdButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.toolBarButton6 private
System.Windows.Forms.ToolBarButton IPLab.MainForm.morphologyButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.convolutionButton private
System.Windows.Forms.MenuItem IPLab.MainForm.mainBarViewItem private
Referenced by IPLab.MainForm.viewItem_Popup().
System.Windows.Forms.MenuItem IPLab.MainForm.imageBarViewItem private
Referenced by IPLab.MainForm.viewItem_Popup().
System.Windows.Forms.MenuItem IPLab.MainForm.menuItem7 private
System.Windows.Forms.ToolBarButton IPLab.MainForm.resizeButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.toolBarButton7 private
System.Windows.Forms.ToolBarButton IPLab.MainForm.rotateButton private
System.Windows.Forms.StatusBarPanel IPLab.MainForm.hslPanel private
Referenced by IPLab.MainForm.document_MouseImagePosition().
System.Windows.Forms.ToolBarButton IPLab.MainForm.toolBarButton8 private
System.Windows.Forms.ToolBarButton IPLab.MainForm.saturationButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.fourierButton private
System.Windows.Forms.MenuItem IPLab.MainForm.copyFileItem private
Referenced by IPLab.MainForm.fileItem_Popup().
System.Windows.Forms.MenuItem IPLab.MainForm.pasteFileItem private
Referenced by IPLab.MainForm.fileItem_Popup().
System.Windows.Forms.MenuItem IPLab.MainForm.menuItem5 private
System.Windows.Forms.MenuItem IPLab.MainForm.saveFileItem private
Referenced by IPLab.MainForm.fileItem_Popup().
System.Windows.Forms.MenuItem IPLab.MainForm.aboutHelpItem private
System.Windows.Forms.SaveFileDialog IPLab.MainForm.sfd private
Referenced by IPLab.MainForm.SaveFile().
System.Windows.Forms.ToolBarButton IPLab.MainForm.pasteButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.saveButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.copyButton private
System.Windows.Forms.ToolBarButton IPLab.MainForm.toolBarButton9 private
System.Drawing.Printing.PrintDocument IPLab.MainForm.printDocument private
Referenced by IPLab.MainForm.pageSetupFileItem_Click(), IPLab.MainForm.printFileItem_Click(), and IPLab.MainForm.printPreviewFileItem_Click().
System.Windows.Forms.PrintPreviewDialog IPLab.MainForm.printPreviewDialog private
Referenced by IPLab.MainForm.printPreviewFileItem_Click().
System.Windows.Forms.MenuItem IPLab.MainForm.printPreviewFileItem private
Referenced by IPLab.MainForm.fileItem_Popup().
System.Windows.Forms.MenuItem IPLab.MainForm.pageSetupFileItem private
System.Windows.Forms.MenuItem IPLab.MainForm.printFileItem private
Referenced by IPLab.MainForm.fileItem_Popup().
System.Windows.Forms.MenuItem IPLab.MainForm.menuItem8 private
System.Windows.Forms.PageSetupDialog IPLab.MainForm.pageSetupDialog private
Referenced by IPLab.MainForm.pageSetupFileItem_Click().
System.Windows.Forms.PrintDialog IPLab.MainForm.printDialog private
Referenced by IPLab.MainForm.printFileItem_Click().
System.Windows.Forms.StatusBarPanel IPLab.MainForm.ycbcrPanel private
Referenced by IPLab.MainForm.document_MouseImagePosition().
System.Windows.Forms.MenuItem IPLab.MainForm.statisticsViewItem private
Referenced by IPLab.MainForm.ShowStatistics(), and IPLab.MainForm.statistics_DockStateChanged().
Property Documentation
bool IPLab.MainForm.CreateNewDocumentOnChange get
bool IPLab.MainForm.RememberOnChange get
The documentation for this class was generated from the following files:
igsandbox/imageprocessing/iplab_new_GPL/Sources/MainForm.cs
igsandbox/imageprocessing/iplab_new_GPL/Sources/MainForm.Designer.cs