IGLib: Meta.Numerics.UncertainValue Struct Reference
Meta.Numerics.UncertainValue Struct Reference
Represents a value with an associated uncertainty.
Public Member Functions
Interval ConfidenceInterval (double P)
Returns a confidence interval.
UncertainValue (double value, double uncertainty)
Initializes a new uncertain value.
override string ToString ()
Creates a string representation of the uncertain value.
override bool Equals (object obj)
Determines whether the given object represents the same uncertain value.
override int GetHashCode ()
Computes a hash code for the uncertain value.
Static Public Member Functions
static bool operator== (UncertainValue v1, UncertainValue v2)
Determines whether two uncertain values are equal.
static bool operator!= (UncertainValue v1, UncertainValue v2)
Determines whether two uncertain values are not equal.
static UncertainValue operator- (UncertainValue x)
Negates an uncertain value.
static UncertainValue operator+ (UncertainValue v1, UncertainValue v2)
Adds two uncertain values.
static UncertainValue operator- (UncertainValue v1, UncertainValue v2)
Subtracts two uncertain values.
static UncertainValue operator* (UncertainValue v1, UncertainValue v2)
Multiplies two uncertain values.
static UncertainValue operator/ (UncertainValue v1, UncertainValue v2)
Divides two uncertain values.
static UncertainValue operator+ (double v1, UncertainValue u2)
Adds an uncertain value to an certain value.
static UncertainValue operator+ (UncertainValue u1, double v2)
Adds a certain value to an uncertain value.
static UncertainValue operator- (UncertainValue u1, double v2)
Subtracts a certain value from an uncertain value.
static UncertainValue operator- (double v1, UncertainValue u2)
Subtracts an uncertain value from a certain value.
static UncertainValue operator* (double v1, UncertainValue u2)
Multiplies a certain value by an uncertain value.
static UncertainValue operator* (UncertainValue u1, double v2)
Multiplies an uncertain value by a certain value.
static UncertainValue operator/ (UncertainValue u1, double v2)
Divides an uncertain value by a certain value.
Properties
double Value [get, set]
Gets the best estimate.
double Uncertainty [get, set]
Gets the uncertainty.
double RelativeUncertainty [get]
Gets the relative uncertainty.
Private Attributes
double v
double u
Detailed Description
Represents a value with an associated uncertainty.
Constructor & Destructor Documentation
Meta.Numerics.UncertainValue.UncertainValue (double value, double uncertainty) inline
Initializes a new uncertain value.
Parameters
value The best estimate of the value.
uncertainty The uncertainty in the value.
Member Function Documentation
Interval Meta.Numerics.UncertainValue.ConfidenceInterval (double P) inline
Returns a confidence interval.
Parameters
P The required confidence level.
Returns
The associated confidence interval.
This method assumes
References Meta.Numerics.Interval.FromMidpointAndWidth(), and Meta.Numerics.Functions.AdvancedMath.InverseErf().
Referenced by Test.MultiIntegrateTest.BallVolumeIntegrals(), Test.SampleTest.BetaFit(), Test.SampleTest.BetaFitUncertainty(), Test.BinaryContingencyTableTest.BinaryContingencyNullTest(), Test.BinaryContingencyTableTest.BinaryContingencyTest(), Test.BivariateSampleTest.BivariateLinearRegression(), Test.BivariateSampleTest.BivariatePolynomialRegression(), Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties(), Test.MultiIntegrateTest.DoubleIntegrals(), Test.SampleTest.ExponentialFit(), Test.SampleTest.ExponentialFitUncertainty(), Test.DataSetTest.FitDataToLinearFunctionTest(), Test.DataSetTest.FitDataToLineTest(), Test.DataSetTest.FitDataToPolynomialTest(), Test.DataSetTest.FitDataToPolynomialUncertaintiesTest(), Test.DataSetTest.FitDataToProportionalityTest(), Test.DataSetTest.FitToFunctionPolynomialCompatibilityTest(), Test.SampleTest.GammaFit(), Test.SampleTest.GammaFitUncertainty(), Test.MultiIntegrateTest.GaussianIntegrals(), Test.NullDistributionTests.KendallNullDistributionTest(), Test.NullDistributionTests.KolmogorovNullDistributionTest(), Test.NullDistributionTests.KuiperNullDistributionTest(), Test.BivariateSampleTest.LinearLogisticRegression(), Test.SampleTest.LognormalFit(), Test.MultivariateSampleTest.MultivariateLinearRegressionTest(), Test.MultivariateSampleTest.MultivariateNormalSummaryStatistics(), Test.SampleTest.NormalFit(), Test.SampleTest.NormalFitUncertainties(), Test.SampleTest.SampleKuiperTest(), Test.SampleTest.SampleMaximumLikelihoodFit(), Test.SampleTest.SampleMoments(), Test.SampleTest.SamplePopulationMomentEstimateVariances(), Test.MultiIntegrateTest.SeperableIntegrals(), Test.SampleTest.SignTestDistribution(), Test.NullDistributionTests.SpearmanNullDistributionTest(), Test.MultiIntegrateTest.SteinmetzVolume(), Test.SampleTest.TTestDistribution(), Test.NullDistributionTests.TwoSampleKolmogorovNullDistributionTest(), Test.SampleTest.WaldFitUncertainties(), Test.MultiIntegrateTest.WatsonIntegrals(), Test.SampleTest.WeibullFit(), Test.SampleTest.WeibullFitUncertainties(), and Test.MultiIntegrateTest.ZetaIntegrals().
override string Meta.Numerics.UncertainValue.ToString () inline
Creates a string representation of the uncertain value.
Returns
A string of the format value &#x00B1; uncertainty.
static bool Meta.Numerics.UncertainValue.operator== (UncertainValue v1, UncertainValue v2) inline static
Determines whether two uncertain values are equal.
Parameters
v1 The first uncertain value.
v2 The second uncertain value.
Returns
True if the two uncertain values are equal, otherwise false.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
static bool Meta.Numerics.UncertainValue.operator!= (UncertainValue v1, UncertainValue v2) inline static
Determines whether two uncertain values are not equal.
Parameters
v1 The first uncertain value.
v2 The second uncertain value.
Returns
True if the two uncertain values not are equal, otherwise false.
override bool Meta.Numerics.UncertainValue.Equals (object obj) inline
Determines whether the given object represents the same uncertain value.
Parameters
obj The object.
Returns
True if the object represents the same reference point, otherwise false.
override int Meta.Numerics.UncertainValue.GetHashCode () inline
Computes a hash code for the uncertain value.
Returns
A hash code.
Referenced by Meta.Numerics.Statistics.UncertainMeasurement< T >.GetHashCode().
static UncertainValue Meta.Numerics.UncertainValue.operator- (UncertainValue x) inline static
Negates an uncertain value.
Parameters
x The uncertain value.
Returns
The negative of the uncertain value.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
static UncertainValue Meta.Numerics.UncertainValue.operator+ (UncertainValue v1, UncertainValue v2) inline static
Adds two uncertain values.
Parameters
v1 The first uncertain value.
v2 The second uncertain value.
Returns
The sum of the two uncertain values.
References Meta.Numerics.MoreMath.Hypot(), Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
static UncertainValue Meta.Numerics.UncertainValue.operator- (UncertainValue v1, UncertainValue v2) inline static
Subtracts two uncertain values.
Parameters
v1 The first uncertain value.
v2 The second uncertain value.
Returns
The difference of the two uncertain values.
References Meta.Numerics.MoreMath.Hypot(), Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
static UncertainValue Meta.Numerics.UncertainValue.operator* (UncertainValue v1, UncertainValue v2) inline static
Multiplies two uncertain values.
Parameters
v1 The first uncertain value.
v2 The second uncertain value.
Returns
The product of the two uncertain values.
References Meta.Numerics.MoreMath.Hypot(), Meta.Numerics.UncertainValue.RelativeUncertainty, Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
static UncertainValue Meta.Numerics.UncertainValue.operator/ (UncertainValue v1, UncertainValue v2) inline static
Divides two uncertain values.
Parameters
v1 The first uncertain value.
v2 The second uncertain value.
Returns
The quotient of the two uncertain values.
References Meta.Numerics.MoreMath.Hypot(), Meta.Numerics.UncertainValue.RelativeUncertainty, Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
static UncertainValue Meta.Numerics.UncertainValue.operator+ (double v1, UncertainValue u2) inline static
Adds an uncertain value to an certain value.
Parameters
v1 The certain value.
u2 The uncertain value.
Returns
The sum of the two values.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
static UncertainValue Meta.Numerics.UncertainValue.operator+ (UncertainValue u1, double v2) inline static
Adds a certain value to an uncertain value.
Parameters
u1 The uncertain value.
v2 The certain value.
Returns
The sum of the two values.
static UncertainValue Meta.Numerics.UncertainValue.operator- (UncertainValue u1, double v2) inline static
Subtracts a certain value from an uncertain value.
Parameters
u1 The uncertain value.
v2 The certain value.
Returns
The difference between the two values.
static UncertainValue Meta.Numerics.UncertainValue.operator- (double v1, UncertainValue u2) inline static
Subtracts an uncertain value from a certain value.
Parameters
v1 The certain value.
u2 The uncertain vlaue.
Returns
The difference between the two values.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
static UncertainValue Meta.Numerics.UncertainValue.operator* (double v1, UncertainValue u2) inline static
Multiplies a certain value by an uncertain value.
Parameters
v1 The certain value.
u2 The uncertain value.
Returns
The product of the two values.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
static UncertainValue Meta.Numerics.UncertainValue.operator* (UncertainValue u1, double v2) inline static
Multiplies an uncertain value by a certain value.
Parameters
u1 The uncertain value.
v2 The certain value.
Returns
The product of the two values.
static UncertainValue Meta.Numerics.UncertainValue.operator/ (UncertainValue u1, double v2) inline static
Divides an uncertain value by a certain value.
Parameters
u1 The uncertain value.
v2 The certain value.
Returns
The quotient of the two values.
References Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Member Data Documentation
double Meta.Numerics.UncertainValue.v private
double Meta.Numerics.UncertainValue.u private
Property Documentation
double Meta.Numerics.UncertainValue.Value get set
Gets the best estimate.
Referenced by Meta.Numerics.UncertainMath.Acos(), Meta.Numerics.UncertainMath.Asin(), Meta.Numerics.UncertainMath.Atan(), Meta.Numerics.UncertainMath.Atan2(), Test.MultiIntegrateTest.BallVolumeIntegrals(), Test.SampleTest.BetaFitUncertainty(), Test.BivariateSampleTest.BivariateLinearRegression(), Test.BugTests.Bug6162(), Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties(), Meta.Numerics.UncertainMath.Cos(), Meta.Numerics.UncertainMath.Cosh(), Meta.Numerics.UncertainMath.Exp(), Test.SampleTest.ExponentialFitUncertainty(), Test.DataSetTest.FitDataToPolynomialUncertaintiesTest(), Test.DataSetTest.FitDataToProportionalityTest(), Test.DataSetTest.FitToFunctionPolynomialCompatibilityTest(), Meta.Numerics.Statistics.Distributions.NormalDistribution.FitToSample(), Test.SampleTest.GammaFitUncertainty(), Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), Meta.Numerics.Analysis.FunctionMath.Integrate_Adaptive(), Test.BivariateSampleTest.LinearLogisticRegression(), Meta.Numerics.UncertainMath.Log(), Test.SampleTest.NormalFitUncertainties(), Meta.Numerics.UncertainValue.operator*(), Meta.Numerics.UncertainValue.operator+(), Meta.Numerics.UncertainValue.operator-(), Meta.Numerics.UncertainValue.operator/(), Meta.Numerics.UncertainValue.operator==(), Meta.Numerics.UncertainMath.Pow(), Test.SampleTest.SampleMaximumLikelihoodFit(), Test.SampleTest.SamplePopulationMomentEstimateVariances(), Meta.Numerics.UncertainMath.Sin(), Meta.Numerics.UncertainMath.Sinh(), Meta.Numerics.UncertainMath.Sqrt(), Test.DistributionTest.StudentTest(), Meta.Numerics.UncertainMath.Tan(), Meta.Numerics.UncertainMath.Tanh(), Test.UncertainMathTest.UncertainMathCosACos(), Test.UncertainMathTest.UncertainMathSqrtSquare(), Test.UncertainMathTest.UncertainMathValueAgreement(), Test.UncertainValueTest.UncertainValueArithmeticValuesTest(), Test.UncertainValueTest.UncertainValueMixedArithmeticTest(), Test.UncertainValueTest.UncertainValueZeroUncertaintiesTest(), Test.SampleTest.WaldFitUncertainties(), Test.SampleTest.WeibullFitUncertainties(), and Test.MultiIntegrateTest.ZetaIntegrals().
double Meta.Numerics.UncertainValue.Uncertainty get set
Gets the uncertainty.
Referenced by Meta.Numerics.UncertainMath.Acos(), Meta.Numerics.UncertainMath.Asin(), Meta.Numerics.UncertainMath.Atan(), Meta.Numerics.UncertainMath.Atan2(), Test.SampleTest.BetaFitUncertainty(), Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties(), Meta.Numerics.UncertainMath.Cos(), Meta.Numerics.UncertainMath.Cosh(), Meta.Numerics.UncertainMath.Exp(), Test.SampleTest.ExponentialFitUncertainty(), Test.DataSetTest.FitDataToLinearFunctionTest(), Test.DataSetTest.FitDataToLineTest(), Test.DataSetTest.FitDataToPolynomialUncertaintiesTest(), Meta.Numerics.Statistics.Distributions.NormalDistribution.FitToSample(), Test.SampleTest.GammaFitUncertainty(), Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), Meta.Numerics.Analysis.FunctionMath.Integrate_Adaptive(), Meta.Numerics.UncertainMath.Log(), Meta.Numerics.UncertainValue.operator*(), Meta.Numerics.UncertainValue.operator+(), Meta.Numerics.UncertainValue.operator-(), Meta.Numerics.UncertainValue.operator/(), Meta.Numerics.UncertainValue.operator==(), Meta.Numerics.UncertainMath.Pow(), Test.SampleTest.SampleMaximumLikelihoodFit(), Test.SampleTest.SamplePopulationMomentEstimateVariances(), Meta.Numerics.UncertainMath.Sin(), Meta.Numerics.UncertainMath.Sinh(), Meta.Numerics.UncertainMath.Sqrt(), Meta.Numerics.UncertainMath.Tan(), Meta.Numerics.UncertainMath.Tanh(), Test.UncertainMathTest.UncertainMathCosACos(), Test.UncertainMathTest.UncertainMathLogExp(), Test.UncertainMathTest.UncertainMathSqrtSquare(), Test.UncertainValueTest.UncertainValueAdditionTriangleTest(), Test.UncertainValueTest.UncertainValueMixedArithmeticTest(), Test.UncertainValueTest.UncertainValueSubtractionTriangleTest(), Test.UncertainValueTest.UncertainValueZeroUncertaintiesTest(), and Test.SampleTest.WeibullFitUncertainties().
double Meta.Numerics.UncertainValue.RelativeUncertainty get
Gets the relative uncertainty.
Referenced by Meta.Numerics.UncertainMath.Log(), Meta.Numerics.UncertainValue.operator*(), Meta.Numerics.UncertainValue.operator/(), Meta.Numerics.UncertainMath.Pow(), Test.UncertainMathTest.UncertainMathLogExp(), and Test.UncertainMathTest.UncertainMathSqrtSquare().
The documentation for this struct was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Core/UncertainValue.cs