IGLib: CShell.Shell Class Reference
CShell.Shell Class Reference
Hosts all general utility methods to access and modify the shell. Use this static class to manage the workspace, open documents, evaluate code and manage or dump to the sinks.
Static Public Member Functions
static void UpdateProgress (int progress)
Update the progress in the staus bar.
static EvaluatorResult Evaluate (string input)
Evaluates a piece of code.
static EvaluatorResult EvaluateFile (string filePath)
Evaluates all the code in a file.
static bool TryEvaluateFile (string filePath)
Evaluates all the code in a file.
static IEnumerable< IDocument > GetDocuments ()
Gets all available documents including sinks.
static IDocument GetDocument (Uri uri)
Gets or creates specific document and opens it.
static IDocument GetDocument (Uri uri, bool suppressOpen)
Gets or creates specific document and opens it.
static IEnumerable< ITextDocument > GetTextDocuments ()
Gets all available text documents.
static ITextDocument GetTextDocument (string filePath)
Gets or creates specific text document and opens it.
static bool TryOpen (string filePath)
Tries to open a file as a document.
static void Open (string filePath)
Opens a file as a document.
static IEnumerable< ISink > GetSinks ()
Gets all available sinks.
static ISink GetSink (Uri uri)
Gets a specific sink based on the URI. If the sink URI exists or can be created the sink is opened.
static ISink GetSink (Uri uri, bool suppressOpen)
Gets a specific sink based on the uri.
static ISink GetSink (string sinkName)
Gets the first sink with a certain title.
static void Dump (this object o, Uri sink=null)
Dumps an object to the specified sink.
static void Dump (this object o, string description, Uri sink=null)
Dumps an object to the specified sink.
static void DumpGrid (this IEnumerable data, string sinkName=null)
Dumps data to a table.
static void DumpXhtml (this object o, string description=null, int depth=3, string sinkName=null)
Dumps the object to a XHTML sink.
static ITool GetTool (Uri uri)
Gets a specific tool based on the URI. If the tool URI exists or can be created the tool is opened.
static ITool GetTool (Uri uri, bool suppressOpen)
Gets a specific tool based on the uri.
static void OpenWorkspace ()
Opens a default workspace.
static Task OpenWorkspace (string cshellFile)
Opens a workspace based on a .cshell file.
static Task CloseWorkspace ()
Closes the current workspace.
static void UpdateProgress (int progress)
Update the progress in the staus bar.
static EvaluatorResult Evaluate (string input)
Evaluates a piece of code.
static EvaluatorResult EvaluateFile (string filePath)
Evaluates all the code in a file.
static bool TryEvaluateFile (string filePath)
Evaluates all the code in a file.
static IEnumerable< IDocument > GetDocuments ()
Gets all available documents including sinks.
static IDocument GetDocument (Uri uri)
Gets or creates specific document and opens it.
static IDocument GetDocument (Uri uri, bool suppressOpen)
Gets or creates specific document and opens it.
static IEnumerable< ITextDocument > GetTextDocuments ()
Gets all available text documents.
static ITextDocument GetTextDocument (string filePath)
Gets or creates specific text document and opens it.
static bool TryOpen (string filePath)
Tries to open a file as a document.
static void Open (string filePath)
Opens a file as a document.
static IEnumerable< ISink > GetSinks ()
Gets all available sinks.
static ISink GetSink (Uri uri)
Gets a specific sink based on the URI. If the sink URI exists or can be created the sink is opened.
static ISink GetSink (Uri uri, bool suppressOpen)
Gets a specific sink based on the uri.
static ISink GetSink (string sinkName)
Gets the first sink with a certain title.
static void Dump (this object o, Uri sink=null)
Dumps an object to the specified sink.
static void Dump (this object o, string description, Uri sink=null)
Dumps an object to the specified sink.
static void DumpGrid (this IEnumerable data, string sinkName=null)
Dumps data to a table.
static void DumpXhtml (this object o, string description=null, int depth=3, string sinkName=null)
Dumps the object to a XHTML sink.
static ITool GetTool (Uri uri)
Gets a specific tool based on the URI. If the tool URI exists or can be created the tool is opened.
static ITool GetTool (Uri uri, bool suppressOpen)
Gets a specific tool based on the uri.
static void OpenWorkspace ()
Opens a default workspace.
static Task OpenWorkspace (string cshellFile)
Opens a workspace based on a .cshell file.
static Task CloseWorkspace ()
Closes the current workspace.
Properties
static IRepl Repl [get]
Gets the interface to modify the REPL window.
static IOutput Output [get]
Gets the interface to modify the console output window.
static ITextDocument TextDocument [get]
Gets the current text document.
static Uri DefaultSinkUri [get, set]
Gets or sets the URI of the default sink.
static Workspace Workspace [get]
Gets the instance of the currently open workspace, if no workspace is open returns null.
Static Private Member Functions
static ISink GetGridSink (string sinkName, bool suppressOpen=false)
Gets a grid sink based on the sink name.
static IXhtmlSink GetXhtmlSink (string sinkName, bool suppressOpen=false)
Gets a XHTML sink.
static ISink GetGridSink (string sinkName, bool suppressOpen=false)
Gets a grid sink based on the sink name.
static IXhtmlSink GetXhtmlSink (string sinkName, bool suppressOpen=false)
Gets a XHTML sink.
Static Private Attributes
static readonly Lazy< IShell > shellLazy = new Lazy<IShell>(() => IoC.Get<IShell>(), true)
static readonly Lazy< IRepl > replLazy = new Lazy<IRepl>(() => IoC.Get<IRepl>(), true)
static readonly Lazy< IOutput > outputLazy = new Lazy<IOutput>(()=>IoC.Get<IOutput>(), true)
static Uri defaultSinkUri = new Uri(Constants.SinkXhtml)
static Workspace workspace = null
static readonly object instanceLock = new object()
Detailed Description
Hosts all general utility methods to access and modify the shell. Use this static class to manage the workspace, open documents, evaluate code and manage or dump to the sinks.
Member Function Documentation
static void CShell.Shell.UpdateProgress (int progress) inline static
Update the progress in the staus bar.
Parameters
progress The progress between 0 and 100.
static EvaluatorResult CShell.Shell.Evaluate (string input) inline static
Evaluates a piece of code.
Parameters
input The code to evaluate.
Returns
The results of the evaluation.
Referenced by IG.Lib.Ig.Eval().
static EvaluatorResult CShell.Shell.EvaluateFile (string filePath) inline static
Evaluates all the code in a file.
Parameters
filePath The path to the file. Can be relative to the root path of the workspace, e.g. "subfolder/file.csx"
Returns
The results of the evaluation.
References CShell.ScriptingEngine.Evaluate(), and CShell.Workspace.ScriptingEngine.
Referenced by CShell.Shell.TryEvaluateFile().
static bool CShell.Shell.TryEvaluateFile (string filePath) inline static
Evaluates all the code in a file.
Parameters
filePath The path to the file. Can be relative to the root path of the workspace, e.g. "subfolder/file.csx"
Returns
true if the evaluation succeeded, otherwise false.
References CShell.Shell.EvaluateFile(), and CShell.EvaluatorResult.HasErrors.
Referenced by IG.Lib.Ig.TryEvalFile().
static IEnumerable<IDocument> CShell.Shell.GetDocuments () inline static
Gets all available documents including sinks.
References CShell.Shell.shellLazy.
Referenced by CShell.Shell.GetDocument().
static IDocument CShell.Shell.GetDocument (Uri uri) inline static
Gets or creates specific document and opens it.
Parameters
uri The URI of the document. Can be a file path URI.
Referenced by CShell.Framework.Results.OpenDocumentResult.Execute(), CShell.Shell.GetDocument(), CShell.Shell.GetTextDocument(), and CShell.Modules.Shell.ViewModels.ShellViewModel.LoadLayout().
static IDocument CShell.Shell.GetDocument (Uri uri, bool suppressOpen) inline static
Gets or creates specific document and opens it.
Parameters
uri The URI of the document. Can be a file path URI.
suppressOpen true if the document should not be opened.
References CShell.Shell.GetDocuments(), and CShell.Shell.shellLazy.
static IEnumerable<ITextDocument> CShell.Shell.GetTextDocuments () inline static
Gets all available text documents.
References CShell.Shell.shellLazy.
static ITextDocument CShell.Shell.GetTextDocument (string filePath) inline static
Gets or creates specific text document and opens it.
Parameters
filePath The path to the file. Can be relative to the root path of the workspace, e.g. "subfolder/file.csx"
References CShell.Shell.GetDocument().
static bool CShell.Shell.TryOpen (string filePath) inline static
Tries to open a file as a document.
Parameters
filePath The path to the file. Can be relative to the root path of the workspace, e.g. "subfolder/file.csx"
Returns
true if the file was found, otherwise false.
static void CShell.Shell.Open (string filePath) inline static
Opens a file as a document.
Parameters
filePath The path to the file. Can be relative to the root path of the workspace, e.g. "subfolder/file.csx"
Exceptions
ArgumentNullException If the file path is null or empty.
FileNotFoundException If the file doesn't exist.
References CShell.Framework.Results.Show.Document().
static IEnumerable<ISink> CShell.Shell.GetSinks () inline static
Gets all available sinks.
Returns
References CShell.Shell.shellLazy.
Referenced by CShell.Shell.GetSink().
static ISink CShell.Shell.GetSink (Uri uri) inline static
Gets a specific sink based on the URI. If the sink URI exists or can be created the sink is opened.
Parameters
uri The sink URI.
Referenced by CShell.Shell.Dump(), CShell.Shell.GetGridSink(), CShell.Sinks.Plotting.GetPlotSink(), CShell.Shell.GetSink(), CShell.Shell.GetXhtmlSink(), and CShell.Modules.Shell.ViewModels.ShellViewModel.LoadLayout().
static ISink CShell.Shell.GetSink (Uri uri, bool suppressOpen) inline static
Gets a specific sink based on the uri.
Parameters
uri The sink URI.
suppressOpen If set to true sink will not be opened, but just created.
Returns
References CShell.Shell.GetSinks(), and CShell.Shell.shellLazy.
static ISink CShell.Shell.GetSink (string sinkName) inline static
Gets the first sink with a certain title.
Parameters
sinkName Name of the sink.
Returns
If the sink name cannot be found returns null.
References CShell.Shell.GetSinks().
static void CShell.Shell.Dump (this object o, Uri sink = null) inline static
Dumps an object to the specified sink.
Parameters
o The object to dump.
sink The sink URI. If no sink URI is specified the default sink is used.
Referenced by CShell.Shell.Dump().
static void CShell.Shell.Dump (this object o, string description, Uri sink = null) inline static
Dumps an object to the specified sink.
Parameters
o The object to dump.
description A description of the object. Can be null.
sink The sink URI. If no sink URI is specified the default sink is used.
References CShell.Shell.DefaultSinkUri, and CShell.Shell.GetSink().
static ISink CShell.Shell.GetGridSink (string sinkName, bool suppressOpen = false) inline static private
Gets a grid sink based on the sink name.
Parameters
sinkName Name of the sink.
suppressOpen If set to true the grid is not opened.
References CShell.Shell.GetSink(), and CShell.Constants.SinkGrid.
Referenced by CShell.Shell.DumpGrid().
static void CShell.Shell.DumpGrid (this IEnumerable data, string sinkName = null) inline static
Dumps data to a table.
Parameters
data The data.
sinkName Name of the sink.
References CShell.Shell.GetGridSink().
static IXhtmlSink CShell.Shell.GetXhtmlSink (string sinkName, bool suppressOpen = false) inline static private
Gets a XHTML sink.
Parameters
sinkName Name of the sink.
suppressOpen If set to true the sink is not opened.
Returns
References CShell.Shell.GetSink(), and CShell.Constants.SinkXhtml.
Referenced by CShell.Shell.DumpXhtml().
static void CShell.Shell.DumpXhtml (this object o, string description = null, int depth = 3, string sinkName = null) inline static
Dumps the object to a XHTML sink.
Parameters
o The object to dump.
description A description of the object.
depth If it's a nested type how many sub-types should be printed.
sinkName Name of the sink.
References CShell.Shell.GetXhtmlSink().
static ITool CShell.Shell.GetTool (Uri uri) inline static
Gets a specific tool based on the URI. If the tool URI exists or can be created the tool is opened.
Parameters
uri The tool URI.
Referenced by CShell.Shell.GetTool(), and CShell.Modules.Shell.ViewModels.ShellViewModel.LoadLayout().
static ITool CShell.Shell.GetTool (Uri uri, bool suppressOpen) inline static
Gets a specific tool based on the uri.
Parameters
uri The tool URI.
suppressOpen If set to true tool will not be opened, but just created.
Returns
References CShell.Shell.shellLazy.
static void CShell.Shell.OpenWorkspace () inline static
Opens a default workspace.
References CShell.Constants.CShellDefaultFilePath.
Referenced by CShell.Framework.Results.OpenWorkspaceResult.Execute(), and CShell.Shell.OpenWorkspace().
static Task CShell.Shell.OpenWorkspace (string cshellFile) inline static
Opens a workspace based on a .cshell file.
Parameters
cshellFile The file path to the .cshell file.
Returns
A task that completes once the workspace is opened.
References CShell.Shell.Workspace.
static Task CShell.Shell.CloseWorkspace () inline static
Closes the current workspace.
Returns
A task that completes once the workspace is closed.
Referenced by CShell.Framework.Results.CloseWorkspaceResult.Execute().
static void CShell.Shell.UpdateProgress (int progress) inline static
Update the progress in the staus bar.
Parameters
progress The progress between 0 and 100.
static EvaluatorResult CShell.Shell.Evaluate (string input) inline static
Evaluates a piece of code.
Parameters
input The code to evaluate.
Returns
The results of the evaluation.
static EvaluatorResult CShell.Shell.EvaluateFile (string filePath) inline static
Evaluates all the code in a file.
Parameters
filePath The path to the file. Can be relative to the root path of the workspace, e.g. "subfolder/file.csx"
Returns
The results of the evaluation.
References CShell.ScriptingEngine.Evaluate(), and CShell.Workspace.ScriptingEngine.
static bool CShell.Shell.TryEvaluateFile (string filePath) inline static
Evaluates all the code in a file.
Parameters
filePath The path to the file. Can be relative to the root path of the workspace, e.g. "subfolder/file.csx"
Returns
true if the evaluation succeeded, otherwise false.
References CShell.Shell.EvaluateFile(), and CShell.EvaluatorResult.HasErrors.
static IEnumerable<IDocument> CShell.Shell.GetDocuments () inline static
Gets all available documents including sinks.
References CShell.Shell.shellLazy.
static IDocument CShell.Shell.GetDocument (Uri uri) inline static
Gets or creates specific document and opens it.
Parameters
uri The URI of the document. Can be a file path URI.
References CShell.Shell.GetDocument().
static IDocument CShell.Shell.GetDocument (Uri uri, bool suppressOpen) inline static
Gets or creates specific document and opens it.
Parameters
uri The URI of the document. Can be a file path URI.
suppressOpen true if the document should not be opened.
References CShell.Shell.GetDocuments(), and CShell.Shell.shellLazy.
static IEnumerable<ITextDocument> CShell.Shell.GetTextDocuments () inline static
Gets all available text documents.
References CShell.Shell.shellLazy.
static ITextDocument CShell.Shell.GetTextDocument (string filePath) inline static
Gets or creates specific text document and opens it.
Parameters
filePath The path to the file. Can be relative to the root path of the workspace, e.g. "subfolder/file.csx"
References CShell.Shell.GetDocument().
static bool CShell.Shell.TryOpen (string filePath) inline static
Tries to open a file as a document.
Parameters
filePath The path to the file. Can be relative to the root path of the workspace, e.g. "subfolder/file.csx"
Returns
true if the file was found, otherwise false.
static void CShell.Shell.Open (string filePath) inline static
Opens a file as a document.
Parameters
filePath The path to the file. Can be relative to the root path of the workspace, e.g. "subfolder/file.csx"
Exceptions
ArgumentNullException If the file path is null or empty.
FileNotFoundException If the file doesn't exist.
References CShell.Framework.Results.Show.Document().
static IEnumerable<ISink> CShell.Shell.GetSinks () inline static
Gets all available sinks.
Returns
References CShell.Shell.shellLazy.
static ISink CShell.Shell.GetSink (Uri uri) inline static
Gets a specific sink based on the URI. If the sink URI exists or can be created the sink is opened.
Parameters
uri The sink URI.
References CShell.Shell.GetSink().
static ISink CShell.Shell.GetSink (Uri uri, bool suppressOpen) inline static
Gets a specific sink based on the uri.
Parameters
uri The sink URI.
suppressOpen If set to true sink will not be opened, but just created.
Returns
References CShell.Shell.GetSinks(), and CShell.Shell.shellLazy.
static ISink CShell.Shell.GetSink (string sinkName) inline static
Gets the first sink with a certain title.
Parameters
sinkName Name of the sink.
Returns
If the sink name cannot be found returns null.
References CShell.Shell.GetSinks().
static void CShell.Shell.Dump (this object o, Uri sink = null) inline static
Dumps an object to the specified sink.
Parameters
o The object to dump.
sink The sink URI. If no sink URI is specified the default sink is used.
References CShell.Shell.Dump().
static void CShell.Shell.Dump (this object o, string description, Uri sink = null) inline static
Dumps an object to the specified sink.
Parameters
o The object to dump.
description A description of the object. Can be null.
sink The sink URI. If no sink URI is specified the default sink is used.
References CShell.Shell.DefaultSinkUri, and CShell.Shell.GetSink().
static ISink CShell.Shell.GetGridSink (string sinkName, bool suppressOpen = false) inline static private
Gets a grid sink based on the sink name.
Parameters
sinkName Name of the sink.
suppressOpen If set to true the grid is not opened.
References CShell.Shell.GetSink(), and CShell.Constants.SinkGrid.
static void CShell.Shell.DumpGrid (this IEnumerable data, string sinkName = null) inline static
Dumps data to a table.
Parameters
data The data.
sinkName Name of the sink.
References CShell.Shell.GetGridSink().
static IXhtmlSink CShell.Shell.GetXhtmlSink (string sinkName, bool suppressOpen = false) inline static private
Gets a XHTML sink.
Parameters
sinkName Name of the sink.
suppressOpen If set to true the sink is not opened.
Returns
References CShell.Shell.GetSink(), and CShell.Constants.SinkXhtml.
static void CShell.Shell.DumpXhtml (this object o, string description = null, int depth = 3, string sinkName = null) inline static
Dumps the object to a XHTML sink.
Parameters
o The object to dump.
description A description of the object.
depth If it's a nested type how many sub-types should be printed.
sinkName Name of the sink.
References CShell.Shell.GetXhtmlSink().
static ITool CShell.Shell.GetTool (Uri uri) inline static
Gets a specific tool based on the URI. If the tool URI exists or can be created the tool is opened.
Parameters
uri The tool URI.
References CShell.Shell.GetTool().
static ITool CShell.Shell.GetTool (Uri uri, bool suppressOpen) inline static
Gets a specific tool based on the uri.
Parameters
uri The tool URI.
suppressOpen If set to true tool will not be opened, but just created.
Returns
References CShell.Shell.shellLazy.
static void CShell.Shell.OpenWorkspace () inline static
Opens a default workspace.
References CShell.Constants.CShellDefaultFilePath, and CShell.Shell.OpenWorkspace().
static Task CShell.Shell.OpenWorkspace (string cshellFile) inline static
Opens a workspace based on a .cshell file.
Parameters
cshellFile The file path to the .cshell file.
Returns
A task that completes once the workspace is opened.
References CShell.Shell.Workspace.
static Task CShell.Shell.CloseWorkspace () inline static
Closes the current workspace.
Returns
A task that completes once the workspace is closed.
Member Data Documentation
static readonly Lazy< IShell > CShell.Shell.shellLazy = new Lazy<IShell>(() => IoC.Get<IShell>(), true) static private
Referenced by CShell.Shell.GetDocument(), CShell.Shell.GetDocuments(), CShell.Shell.GetSink(), CShell.Shell.GetSinks(), CShell.Shell.GetTextDocuments(), and CShell.Shell.GetTool().
static readonly Lazy< IRepl > CShell.Shell.replLazy = new Lazy<IRepl>(() => IoC.Get<IRepl>(), true) static private
static readonly Lazy< IOutput > CShell.Shell.outputLazy = new Lazy<IOutput>(()=>IoC.Get<IOutput>(), true) static private
static Uri CShell.Shell.defaultSinkUri = new Uri(Constants.SinkXhtml) static private
static Workspace CShell.Shell.workspace = null static private
static readonly object CShell.Shell.instanceLock = new object() static private
Property Documentation
static IRepl CShell.Shell.Repl static get
Gets the interface to modify the REPL window.
Referenced by IG.Lib.Ig.Clear().
static IOutput CShell.Shell.Output static get
Gets the interface to modify the console output window.
static ITextDocument CShell.Shell.TextDocument static get
Gets the current text document.
static Uri CShell.Shell.DefaultSinkUri static get set
Gets or sets the URI of the default sink.
Referenced by CShell.Shell.Dump().
static Workspace CShell.Shell.Workspace static get
Gets the instance of the currently open workspace, if no workspace is open returns null.
Referenced by CShell.Modules.Workspace.Module.AddReferenceFromFile(), CShell.Modules.Workspace.Module.AddReferenceFromGac(), CShell.Modules.Shell.ViewModels.ShellViewModel.Closing(), CShell.Framework.Results.RunCodeResult.Execute(), CShell.Modules.Workspace.ViewModels.RootFolderSettingsViewModel.Ok(), CShell.Modules.Editors.ViewModels.EditorViewModel.OnViewLoaded(), CShell.Shell.OpenWorkspace(), CShell.Modules.Repl.ViewModels.OutputViewModel.OutputViewModel(), CShell.Modules.Workspace.ViewModels.RootFolderSettingsViewModel.RootFolderSettingsViewModel(), and CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.WorkspaceViewModel().
The documentation for this class was generated from the following files:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Shell.cs
shelldev/repl/CShell-0.1.2/Src/CShellCore/Shell.Documents.cs
shelldev/repl/CShell-0.1.2/Src/CShellCore/Shell.Sinks.cs
shelldev/repl/CShell-0.1.2/Src/CShellCore/Shell.Workspace.cs
shelldev/repl/CShell-0.1.2/Src/CShellCore/Shell.Sinks.Grid.cs
shelldev/repl/CShell-0.1.2/Src/CShellCore/Shell.Sinks.Xhtml.cs
shelldev/repl/CShell-0.1.2/Src/CShellCore/Shell.Tools.cs