IGLib: alglib.autogk Class Reference
alglib.autogk Class Reference
Classes
class autogkinternalstate
class autogkreport
class autogkstate
Static Public Member Functions
static void autogksmooth (double a, double b, autogkstate state)
static void autogksmoothw (double a, double b, double xwidth, autogkstate state)
static void autogksingular (double a, double b, double alpha, double beta, autogkstate state)
static bool autogkiteration (autogkstate state)
static void autogkresults (autogkstate state, ref double v, autogkreport rep)
static void autogksmooth (double a, double b, autogkstate state)
static void autogksmoothw (double a, double b, double xwidth, autogkstate state)
static void autogksingular (double a, double b, double alpha, double beta, autogkstate state)
static bool autogkiteration (autogkstate state)
static void autogkresults (autogkstate state, ref double v, autogkreport rep)
Public Attributes
const int maxsubintervals = 10000
Static Private Member Functions
static void autogkinternalprepare (double a, double b, double eps, double xwidth, autogkinternalstate state)
static bool autogkinternaliteration (autogkinternalstate state)
static void mheappop (ref double[,] heap, int heapsize, int heapwidth)
static void mheappush (ref double[,] heap, int heapsize, int heapwidth)
static void mheapresize (ref double[,] heap, ref int heapsize, int newheapsize, int heapwidth)
static void autogkinternalprepare (double a, double b, double eps, double xwidth, autogkinternalstate state)
static bool autogkinternaliteration (autogkinternalstate state)
static void mheappop (ref double[,] heap, int heapsize, int heapwidth)
static void mheappush (ref double[,] heap, int heapsize, int heapwidth)
static void mheapresize (ref double[,] heap, ref int heapsize, int newheapsize, int heapwidth)
Member Function Documentation
static void alglib.autogk.autogksmooth (double a, double b, autogkstate state) inline static
References alglib.ap.assert(), alglib.autogk.autogksmoothw(), and alglib.math.isfinite().
Referenced by alglib.autogksmooth(), and alglib.testautogkunit.testautogk().
static void alglib.autogk.autogksmoothw (double a, double b, double xwidth, autogkstate state) inline static
References alglib.autogk.autogkstate.a, alglib.ap.assert(), alglib.autogk.autogkstate.b, alglib.math.isfinite(), alglib.autogk.autogkstate.needf, alglib.rcommstate.ra, alglib.autogk.autogkstate.rstate, alglib.rcommstate.stage, alglib.autogk.autogkstate.wrappermode, and alglib.autogk.autogkstate.xwidth.
Referenced by alglib.autogk.autogksmooth(), alglib.autogksmoothw(), and alglib.testautogkunit.testautogk().
static void alglib.autogk.autogksingular (double a, double b, double alpha, double beta, autogkstate state) inline static
References alglib.autogk.autogkstate.a, alglib.autogk.autogkstate.alpha, alglib.ap.assert(), alglib.autogk.autogkstate.b, alglib.beta(), alglib.autogk.autogkstate.beta, alglib.math.isfinite(), alglib.autogk.autogkstate.needf, alglib.rcommstate.ra, alglib.autogk.autogkstate.rstate, alglib.rcommstate.stage, alglib.autogk.autogkstate.wrappermode, and alglib.autogk.autogkstate.xwidth.
Referenced by alglib.autogksingular(), and alglib.testautogkunit.testautogk().
static bool alglib.autogk.autogkiteration (autogkstate state) inline static
References alglib.autogk.autogkstate.a, alglib.autogk.autogkstate.alpha, alglib.autogk.autogkinternaliteration(), alglib.autogk.autogkinternalprepare(), alglib.autogk.autogkstate.b, alglib.beta(), alglib.autogk.autogkstate.beta, alglib.autogk.autogkstate.bminusx, alglib.autogk.autogkinternalstate.f, alglib.autogk.autogkstate.f, alglib.autogk.autogkinternalstate.heapused, alglib.autogk.autogkinternalstate.info, alglib.autogk.autogkstate.internalstate, alglib.autogk.autogkstate.needf, alglib.autogk.autogkstate.nfev, alglib.autogk.autogkstate.nintervals, alglib.autogk.autogkinternalstate.r, alglib.rcommstate.ra, alglib.autogk.autogkstate.rstate, alglib.rcommstate.stage, alglib.autogk.autogkstate.terminationtype, alglib.autogk.autogkstate.v, alglib.autogk.autogkstate.wrappermode, alglib.autogk.autogkinternalstate.x, alglib.autogk.autogkstate.x, alglib.autogk.autogkstate.xminusa, and alglib.autogk.autogkstate.xwidth.
Referenced by alglib.autogkiteration(), and alglib.testautogkunit.testautogk().
static void alglib.autogk.autogkresults (autogkstate state, ref double v, autogkreport rep) inline static
References alglib.autogk.autogkreport.nfev, alglib.autogk.autogkstate.nfev, alglib.autogk.autogkreport.nintervals, alglib.autogk.autogkstate.nintervals, alglib.autogk.autogkreport.terminationtype, alglib.autogk.autogkstate.terminationtype, and alglib.autogk.autogkstate.v.
Referenced by alglib.autogkresults(), and alglib.testautogkunit.testautogk().
static void alglib.autogk.autogkinternalprepare (double a, double b, double eps, double xwidth, autogkinternalstate state) inline static private
References alglib.autogk.autogkinternalstate.a, alglib.autogk.autogkinternalstate.b, alglib.autogk.autogkinternalstate.eps, alglib.rcommstate.ia, alglib.rcommstate.ra, alglib.autogk.autogkinternalstate.rstate, alglib.rcommstate.stage, and alglib.autogk.autogkinternalstate.xwidth.
Referenced by alglib.autogk.autogkiteration().
static bool alglib.autogk.autogkinternaliteration (autogkinternalstate state) inline static private
References alglib.autogk.autogkinternalstate.a, alglib.autogk.autogkinternalstate.b, alglib.autogk.autogkinternalstate.eps, alglib.autogk.autogkinternalstate.f, alglib.gkq.gkqgenerategausslegendre(), alglib.autogk.autogkinternalstate.heap, alglib.autogk.autogkinternalstate.heapsize, alglib.autogk.autogkinternalstate.heapused, alglib.autogk.autogkinternalstate.heapwidth, alglib.rcommstate.ia, alglib.autogk.autogkinternalstate.info, alglib.math.machineepsilon, alglib.autogk.mheappop(), alglib.autogk.mheappush(), alglib.autogk.mheapresize(), alglib.autogk.autogkinternalstate.n, alglib.autogk.autogkinternalstate.qn, alglib.autogk.autogkinternalstate.r, alglib.rcommstate.ra, alglib.autogk.autogkinternalstate.rstate, alglib.rcommstate.stage, alglib.autogk.autogkinternalstate.sumabs, alglib.autogk.autogkinternalstate.sumerr, alglib.autogk.autogkinternalstate.wg, alglib.autogk.autogkinternalstate.wk, alglib.autogk.autogkinternalstate.wr, alglib.autogk.autogkinternalstate.x, and alglib.autogk.autogkinternalstate.xwidth.
Referenced by alglib.autogk.autogkiteration().
static void alglib.autogk.mheappop (ref double heap[,], int heapsize, int heapwidth) inline static private
Referenced by alglib.autogk.autogkinternaliteration().
static void alglib.autogk.mheappush (ref double heap[,], int heapsize, int heapwidth) inline static private
Referenced by alglib.autogk.autogkinternaliteration().
static void alglib.autogk.mheapresize (ref double heap[,], ref int heapsize, int newheapsize, int heapwidth) inline static private
Referenced by alglib.autogk.autogkinternaliteration().
static void alglib.autogk.autogksmooth (double a, double b, autogkstate state) inline static
References alglib.ap.assert(), alglib.autogk.autogksmoothw(), and alglib.math.isfinite().
static void alglib.autogk.autogksmoothw (double a, double b, double xwidth, autogkstate state) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
static void alglib.autogk.autogksingular (double a, double b, double alpha, double beta, autogkstate state) inline static
References alglib.ap.assert(), alglib.beta(), and alglib.math.isfinite().
static bool alglib.autogk.autogkiteration (autogkstate state) inline static
References alglib.autogk.autogkinternaliteration(), alglib.autogk.autogkinternalprepare(), and alglib.beta().
static void alglib.autogk.autogkresults (autogkstate state, ref double v, autogkreport rep) inline static
static void alglib.autogk.autogkinternalprepare (double a, double b, double eps, double xwidth, autogkinternalstate state) inline static private
static bool alglib.autogk.autogkinternaliteration (autogkinternalstate state) inline static private
References alglib.gkq.gkqgenerategausslegendre(), alglib.math.machineepsilon, alglib.autogk.mheappop(), alglib.autogk.mheappush(), and alglib.autogk.mheapresize().
static void alglib.autogk.mheappop (ref double heap[,], int heapsize, int heapwidth) inline static private
static void alglib.autogk.mheappush (ref double heap[,], int heapsize, int heapwidth) inline static private
static void alglib.autogk.mheapresize (ref double heap[,], ref int heapsize, int newheapsize, int heapwidth) inline static private
Member Data Documentation
const int alglib.autogk.maxsubintervals = 10000
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/integration.cs