IGLib: IG.Crypto.CryptoManager Class Reference
IG.Crypto.CryptoManager Class Reference
Performs high level cryptographic opereratins, such ass reading command-line parameters and performing high-level tasks that can be directly used in application commands (i.e. those commands that are installed on applicaition interpreters).
Public Member Functions
CryptoManager ()
CryptoManager (int outputLevel)
string GetFreeParameter (int whichParameter)
Returns the specified free parameter (obtained from commans-line arguments).
virtual void ParseCommandlineParameters (string appName, string[] args)
Reads parameters for cryptographic operations to be performed from the specified command line.
virtual void GetInputFilePaths (ref List< string > inputFilePaths, bool enableWildcards=true, bool addRecursive=true, bool clearBefore=true)
Gets a list of input files specified by command-line arguments that had been previously parsed by the ParseCommandlineParameters method.
virtual string AppEncryptSymmetricBasic (string appName, string[] args)
Executes command-line action - symmetric encryption of files or text by using BASIC class of methods.
virtual string AppDecryptSymmetricBasic (string appName, string[] args)
Executes command-line action - symmetric decryption of files or text by using BASIC class of methods.
virtual string AppEncryptSymmetricPlain (string appName, string[] args)
Executes command-line action - symmetric encryption of files or text by using PLAIN class of methods.
virtual string AppDecryptSymmetricPlain (string appName, string[] args)
Executes command-line action - symmetric decryption of files or text by using PLAIN class of methods.
virtual string AppGetFileHash (string appName, string[] args)
Executes command-line action - calculation of various hashRet values of a file.
virtual string AppCheckSum (string appName, string[] args)
Executes command-line action - calculation of various hashRet values of files or text.
virtual string AppConvert (string appName, string[] args)
Executes command-line action - conversion between different representations of data.
virtual string AppCleanFiles (string appName, string[] args)
Executes command-line action - deletion of eventual redundant files that remained in the file system after cryptographic operations..
virtual string AppTimeKeyGeneration (string appName, string[] args)
Executes command-line action - measuring time of password generaton algorithms.
virtual string AppGetKey (string appName, string[] args)
Executes command-line action - generates a random initialization vector for symmetric encryption.
virtual string AppGetInitializationVector (string appName, string[] args)
Executes command-line action - generates a random initialization vector for symmetric encryption.
virtual string AppGetSalt (string appName, string[] args)
Executes command-line action - generates a random salt bytes.
virtual int ResolvePasswordParameters (int whichFreeParameterkeyLength=0, int whichFreeParameterNumIterations=1)
Resolves password related parameters such as password, salt, and generated key length.
virtual void ResolveAsymParameters ()
Resolves asymmetric algorithm parameters from the information that has been previously obtained through command-line parameters.
virtual string AppAsymKeyInfo (string appName, string[] args)
Executes command-line action - prints information about asymmetric keys specified by command-line parameters.
virtual string AppAsymExportKey (string appName, string[] args)
Executes command-line action - exports asymmetric keys specified by command-line parameters.
virtual string AppCertStoreInfo (string appName, string[] args)
Executes command-line action - prints information about the certificate stores specified by command-line parameters.
virtual string AppAddCertificate (string appName, string[] args)
Executes command-line action - prints information about the certificate stores specified by command-line parameters.
virtual string AppRemoveCertificate (string appName, string[] args)
Executes command-line action - removes certificate with the specified name from the specified certificate store.
virtual string AppCertInfo (string appName, string[] args)
Executes command-line action - prints information about the certificate specified by command-line parameters.
virtual string AppAsymTest (string appName, string[] args)
Executes command-line action - a couple of custom asymmetric encryption-related tests.
Public Member Functions inherited from IG.Crypto.CryptoParameters
CryptoParameters ()
void Reset ()
Resets the state.
bool IsFlagsSet (params CryptoFlags[] whichFlags)
Returns true if ALL the specified flags are set, or false if some of them are unset.
bool IsAnyFlagSet (params CryptoFlags[] whichFlags)
Returns true if any of the specified flags is set, or false if none of them is set.
void SetFlags (params CryptoFlags[] whichFlags)
Sets the specified flags.
void ClearFlags (CryptoFlags firstFlags, params CryptoFlags[] whichFlags)
Clears the specified flags.
void ClearAllFlags ()
Clears all flags.
Protected Member Functions
virtual void ReportError (string errorString)
Used in the current class to report an error.
virtual void ReportWarning (string errorString)
Used in the current class to launch a warning message.
virtual void ReportInfo (string errorString)
Used in the current class to launch an informative message.
virtual void WarnAboutPlainEncryption ()
Writes a notification informing that a cryptographic task has been delegated to the CryptoParameters class.
virtual void WarnExportPrivateKey ()
Writes a notification informing that a private key may be exported.
virtual string AppEncryptSymmetricAll (string appName, string[] args, bool isDecrypt=false, bool isPlain=false, bool isBasic=false)
Executes command-line action - symmetric encryption of files or text.
virtual string AppKeyGenerationAll (string appName, string[] args, bool measureTimes, int numGenerations)
Executes command-line action - one of the actions related to key generation.
Protected Attributes
bool _isDecrypt = false
bool _isLargestKey = false
Properties
int OutputLevel [get, set]
Level of output during operation.
string AppName [get, protected set]
string[] AppArguments [get, set]
Last (or currently) read command-line arguments.
int NumAppArguments [get]
Number of command-line arguments.
PasswordAlgorithmType PasswordAlgorithmType [get, set]
Type of the algorithm used for password hashing.
string PasswordAlgorithmTypeString [get, set]
Name of the algorithm used in password hashing.
PasswordAlgorithmBase PasswordAlgorithm [get, set]
Password hashing algorithm.
string AlgorithmTypeString [get, set]
String representation of algorithm type.
HashType HashAlgorithmType [get, set]
Hashing algorithm type.
SymmetricAlgorithmType SymmetricAlgorithmType [get, set]
Symmetric algorithm type.
bool IsDecrypt [get, protected set]
Whether decryption is perrformed, rather than encryption.
bool IsEncrypt [get, protected set]
Whether decryption is perrformed, rather than encryption.
bool IsExportPrivateKey [get, protected set]
Whether private key is also exported or printed.
AsymmetricAlgorithmType AsymAlgorithmType [get, protected set]
AsymmetricAlgorithm AsymAlgorithm [get, set]
Asymmetric algorithm, equipped with keys, that will perform asymmetric cryptographic tasks.
CspProviderFlags AsymFlags [get, set]
Asymmetric CSP (crypto service provider) flags.
string AsymAlgorithmTypeString [get, protected set]
String that represents asymmetric algorithm type.
string AsymKeyContainerName [get, protected set]
Asymmetric key container name.
string AsymKeyFileXml [get, protected set]
Asymmetric key file path in XML format.
string CertificatePath [get, protected set]
Path to the certificate file (e.g. for obtaining asymmetric keys).
string CertificateName [get, protected set]
Certificate name (usually specified to locate the certificate in a certificate store).
string CertificateStoreName [get, protected set]
Name of the certificate store (usually, to locate the specified certificate).
int CertificateStoreLocation [get, protected set]
Location of the certificate store (usually used to filter certificate stores).
bool IsCertificatePasswordThroughUi [get, protected set]
Indicates that pasword for private key should obtained from the user through GUI (usually through console).
string CertificatePassword [get, set]
Password for accessing private keys (e.g. for private keys associated with certificate).
string HashValue [get, set]
Hash value, usually used for checking consistency.
bool IsStringInput [get, set]
Flag indicating that input are strings or encoded byte arrays, rather than files.
int PasswordLength [get, set]
Length of the (generated) password.
string PasswordString [get, set]
byte[] PasswordBytes [get, set]
Password as byte array.
int SaltLength [get, set]
Length of salt.
string SaltString [get, set]
Salt string.
byte[] SaltBytes [get, set]
Salt as byte array.
int IvLength [get, set]
Length of the initialization vector.
string IvString [get, set]
Initialization vector in string form.
byte[] IvBytes [get, set]
Initialization vector as byte array.
int KeyLength [get, set]
Length of the key.
byte[] KeyBytes [get, set]
Secret key as byte array.
bool IsLargestKey [get, set]
Whether the largest available key size for the algorithm in use is taken.
int NumPasswordIterations [get, set]
Number of iterations in passworg hashing algorithms, aimed at increasing processing effort to break the password.
List< string > FreeParameters [get]
List of free parameters from the parsed command-line.
int NumFreeParameters [get]
Number of free parameters (obtained from commans-line arguments).
string ReturnedString [get, set]
Returned value of command-line application methods.
bool IsChecked [get, set]
Indicates that something is verified, not calculated (or checked in addition, after calculation).
double TargetedTotalTime [get, set]
Total time targeted in multi-pass algorithms (e.g. in password hashing).
bool IsInputFormatString [get, set]
Whether input format is ordinary string. Returns true if there is no binary format specified, false if there is.
bool IsInputFormatLongInt [get, protected set]
bool IsInputFormat64 [get, protected set]
Whether input is in form of base-64 encoded byte array.
bool IsInputFormatHex [get, protected set]
Whether input is in form of hexadecimal encoded byte array.
bool IsOutputFormatString [get, set]
Whether output format is ordinary string. Returns true if there is no binary format specified, false if there is.
bool IsOutputFormatLongInt [get, protected set]
Whether output is in form of long integer.
bool IsOutputFormat64 [get, protected set]
Whether output is in form of base-64 encoded byte array.
bool IsOutputFormatHex [get, protected set]
Whether output is in form of hexadecimal encoded byte array.
Properties inherited from IG.Crypto.CryptoParameters
CryptoFlags Flags [get, private set]
Flags for cryptographic operations performed.
Private Attributes
int _outputLevel = 2
string _appName = null
string[] _appArguments = null
PasswordAlgorithmType _passwordAlgorithmType = PasswordAlgorithmType.Default
string _passwordAlgorithmTypeString = null
PasswordAlgorithmBase _passwordAlgorithm = null
string _algorithmTypeString = null
HashType _hashAlgorithmType = HashType.Default
SymmetricAlgorithmType _symmetricAlgorithmType = SymmetricAlgorithmType.Default
bool _isExportPrivateKey = false
AsymmetricAlgorithmType _asymAlgorithmType = AsymmetricAlgorithmType.Default
AsymmetricAlgorithm _asymAlgorithm = null
CspProviderFlags _asymFlags = CspProviderFlags.NoFlags
string _asymAlgorithmTypeString = null
string _asymKeyContainerName = null
string _asymKeyFileXml = null
string _certificatePath = null
string _certificateName = null
string _certificateStoreName = null
int _certificateStoreLocation = 0
bool _certificatePasswordThroughUi = false
string _certificatePassword = null
string _hashValue = null
bool _isStringInput = false
int _passwordLength = 0
string _passwordString = null
byte[] _passwordBytes = null
int _saltLength = 0
string _saltString = null
byte[] _saltBytes = null
int _ivLength = 0
string _ivString = null
byte[] _ivBytes = null
int _keyLength = 0
byte[] _keyBytes = null
int _numPasswordIterations = 0
List< string > _freeParameters = new List<string>()
string _returnedString = null
bool _isChecked = false
double _targetedTotalTime = 0.1
string OutputPath = null
List< string > RecursivePathList = new List<string>()
List< string > RecursivePathListByLevels = new List<string>()
List< string > RecursiveFilePatterns = new List<string>()
int RecursiveDirectoryLevels = -1
bool IsRelativePaths = false
bool IsAbsolutePaths = false
bool IsDeleteOriginal = false
Specifies whether the original files should be deleted.
bool IsDeleteEncrypted = false
Specifies whether the encrypted files should be deleted.
bool IsDeleteDecrypted = false
Specifies whether the encrypted files should be deleted.
bool IsDeleteAllVersions = false
Specifies whether all versions of a file (e.g. original, encrypted, and decrypted) are allowed to be deleted (e.g. in a file clean-up operation).
bool IsForceOverwrites = false
If true then eventual file overwtires are automatically performed by the relevant operation without asking for user's approval.
bool IsSkipOverwrites = false
If true then eventual file overwrites are automatically wasSkipped by the relevant operation.
bool IsForceDeletes = false
bool IsSkipDeletes = false
bool IsInputFormatEqualOutputFormat = false
If true then options for input formats and output format are treated interchangeably in the currentt context (e.g. in the current command-line application).
bool _isInputFormatLongInt = false
bool _isInputFormat64 = false
bool _isInputFormatHex = false
bool _isOutputFormatLongInt = false
bool _isOutputFormat64 = false
bool _isOutputFormatHex = false
Static Private Attributes
static int _numNotifyPlainEncryption = 0
static int _numNotifyExportPrivateKey = 0
Detailed Description
Performs high level cryptographic opereratins, such ass reading command-line parameters and performing high-level tasks that can be directly used in application commands (i.e. those commands that are installed on applicaition interpreters).
Constructor & Destructor Documentation
IG.Crypto.CryptoManager.CryptoManager () inline
IG.Crypto.CryptoManager.CryptoManager (int outputLevel) inline
Member Function Documentation
virtual void IG.Crypto.CryptoManager.ReportError (string errorString) inline protected virtual
Used in the current class to report an error.
Parameters
errorString Error message that is a part of the output generated by this function.
virtual void IG.Crypto.CryptoManager.ReportWarning (string errorString) inline protected virtual
Used in the current class to launch a warning message.
Parameters
errorString Warning message that is a part of the output generated by this function.
virtual void IG.Crypto.CryptoManager.ReportInfo (string errorString) inline protected virtual
Used in the current class to launch an informative message.
Parameters
errorString Warning message that is a part of the output generated by this function.
virtual void IG.Crypto.CryptoManager.WarnAboutPlainEncryption () inline protected virtual
Writes a notification informing that a cryptographic task has been delegated to the CryptoParameters class.
virtual void IG.Crypto.CryptoManager.WarnExportPrivateKey () inline protected virtual
Writes a notification informing that a private key may be exported.
string IG.Crypto.CryptoManager.GetFreeParameter (int whichParameter) inline
Returns the specified free parameter (obtained from commans-line arguments).
Parameters
whichParameter Index of the free parameter to be returned.
virtual void IG.Crypto.CryptoManager.ParseCommandlineParameters (string appName, string[] args) inline virtual
Reads parameters for cryptographic operations to be performed from the specified command line.
Parameters read from this function can be used by any high level function that actually performs cryptographic operations.
Parameters
appName Name of the embedded application for which parameters are read.
args Arguments of the embedded application's command.
References IG.Lib.Util.FromHexString(), IG.Crypto.UtilCrypto.GetAsymmetricAlgorithmType(), IG.Crypto.UtilCrypto.GetCspProviderFlags(), IG.Crypto.UtilCrypto.GetHashType(), IG.Crypto.UtilCrypto.GetPasswordAlgorithmType(), and IG.Crypto.UtilCrypto.GetSymmetricAlgorithmType().
virtual void IG.Crypto.CryptoManager.GetInputFilePaths (ref List< string > inputFilePaths, bool enableWildcards = true, bool addRecursive = true, bool clearBefore = true) inline virtual
Gets a list of input files specified by command-line arguments that had been previously parsed by the ParseCommandlineParameters method.
Parameters
inputFilePaths List where the obtained input file paths are stored.
enableWildcards If true (which is default) then file paths listed as free parameters will be resolved by expanding wildcard characters.
addRecursive If true (which is default) then files obtained by recursive directory listings are also included.
clearBefore If true (which is default) then the list inputFilePaths is cleared before operation. If false then extracted file paths are added to the eventual existing items already on the list. This is an untypical situation and there will rarely bee any need for this.
References IG.Lib.UtilSystem.GetAbsolutePath(), IG.Lib.UtilSystem.GetRelativePath(), IG.Lib.UtilSystem.ListFilesByLevels(), and IG.Lib.UtilSystem.ListFilesRecursively().
virtual string IG.Crypto.CryptoManager.AppEncryptSymmetricBasic (string appName, string[] args) inline virtual
Executes command-line action - symmetric encryption of files or text by using BASIC class of methods.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
Referenced by IG.Script.ScriptAppBase.CryptoFunctionEncryptBasic().
virtual string IG.Crypto.CryptoManager.AppDecryptSymmetricBasic (string appName, string[] args) inline virtual
Executes command-line action - symmetric decryption of files or text by using BASIC class of methods.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
Referenced by IG.Script.ScriptAppBase.CryptoFunctionDecryptBasic().
virtual string IG.Crypto.CryptoManager.AppEncryptSymmetricPlain (string appName, string[] args) inline virtual
Executes command-line action - symmetric encryption of files or text by using PLAIN class of methods.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
Referenced by IG.Script.ScriptAppBase.CryptoFunctionEncryptPlain().
virtual string IG.Crypto.CryptoManager.AppDecryptSymmetricPlain (string appName, string[] args) inline virtual
Executes command-line action - symmetric decryption of files or text by using PLAIN class of methods.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
Referenced by IG.Script.ScriptAppBase.CryptoFunctionDecryptPlain().
virtual string IG.Crypto.CryptoManager.AppEncryptSymmetricAll (string appName, string[] args, bool isDecrypt = false, bool isPlain = false, bool isBasic = false) inline protected virtual
Executes command-line action - symmetric encryption of files or text.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
isDecrypt If true then decryption is performed, otherwise encryption is performed.
isPlain If true then PLAIN class of encryption/decrypton methods is used.
isBasic If true then BASIC class of encryption/decryption metthods is used.
References IG.Lib.StopWatch1.CpuTime, IG.Crypto.UtilCrypto.DecryptFilePlain(), IG.Crypto.UtilCrypto.DecryptPlain(), IG.Crypto.UtilCrypto.DecryptStringPlain(), IG.Crypto.UtilCrypto.EncryptFilePlain(), IG.Crypto.UtilCrypto.EncryptPlain(), IG.Crypto.UtilCrypto.EncryptStringPlain(), IG.Lib.Util.FromHexString(), IG.Lib.UtilConsole.Read(), IG.Lib.UtilConsole.ReadPwd(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Crypto.UtilCrypto.StringEncoding, IG.Crypto.UtilCrypto.SymmetricAlgorithmTypeToString(), IG.Lib.StopWatch1.Time, IG.Lib.Util.ToHexString(), IG.Lib.StopWatch1.TotalCpuTime, and IG.Lib.StopWatch1.TotalTime.
virtual string IG.Crypto.CryptoManager.AppGetFileHash (string appName, string[] args) inline virtual
Executes command-line action - calculation of various hashRet values of a file.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
References IG.Crypto.UtilCrypto.GetFileHashMd5Hex(), IG.Crypto.UtilCrypto.GetFileHashSha1Hex(), IG.Crypto.UtilCrypto.GetFileHashSha256Hex(), IG.Crypto.UtilCrypto.GetFileHashSha512Hex(), IG.Lib.UtilConsole.Read(), and IG.Lib.UtilStr.ToBoolean().
Referenced by IG.Script.ScriptAppBase.CryptoFunctionGetFileHash().
virtual string IG.Crypto.CryptoManager.AppCheckSum (string appName, string[] args) inline virtual
Executes command-line action - calculation of various hashRet values of files or text.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
References IG.Crypto.UtilCrypto.CheckFileHashHex(), IG.Crypto.UtilCrypto.CheckHashHex(), IG.Crypto.UtilCrypto.CheckStringHashHex(), IG.Lib.Util.FromHexString(), IG.Crypto.UtilCrypto.GetFileHashHex(), IG.Crypto.UtilCrypto.GetHashHex(), IG.Crypto.UtilCrypto.GetStringHashHex(), IG.Crypto.UtilCrypto.ParseHashFile(), IG.Lib.UtilConsole.Read(), and IG.Lib.Util.ToByteArray().
Referenced by IG.Script.ScriptAppBase.CryptoFunctionCheckSum().
virtual string IG.Crypto.CryptoManager.AppConvert (string appName, string[] args) inline virtual
Executes command-line action - conversion between different representations of data.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
References IG.Lib.Util.FromHexString(), IG.Lib.Util.ToByteArray(), and IG.Lib.Util.ToHexString().
Referenced by IG.Script.ScriptAppBase.CryptoFunctionConvert().
virtual string IG.Crypto.CryptoManager.AppCleanFiles (string appName, string[] args) inline virtual
Executes command-line action - deletion of eventual redundant files that remained in the file system after cryptographic operations..
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
References IG.Lib.UtilConsole.Read().
Referenced by IG.Script.ScriptAppBase.CryptoFunctionCleanFiles().
virtual string IG.Crypto.CryptoManager.AppTimeKeyGeneration (string appName, string[] args) inline virtual
Executes command-line action - measuring time of password generaton algorithms.
Key generation algorithm type and other parameters such as password and salt are determined by command-line options.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
Referenced by IG.Script.ScriptAppBase.CryptoFunctionTimeKeyGeneration().
virtual string IG.Crypto.CryptoManager.AppGetKey (string appName, string[] args) inline virtual
Executes command-line action - generates a random initialization vector for symmetric encryption.
Key generation algorithm type and other parameters such as password and salt are determined by command-line options.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
Referenced by IG.Script.ScriptAppBase.CryptoFunctionGetKey().
virtual string IG.Crypto.CryptoManager.AppGetInitializationVector (string appName, string[] args) inline virtual
Executes command-line action - generates a random initialization vector for symmetric encryption.
Key generation algorithm type and other parameters such as password and salt are determined by command-line options.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
Referenced by IG.Script.ScriptAppBase.CryptoFunctionGetInitializationVector().
virtual string IG.Crypto.CryptoManager.AppGetSalt (string appName, string[] args) inline virtual
Executes command-line action - generates a random salt bytes.
Key generation algorithm type and other parameters such as password and salt are determined by command-line options.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
Referenced by IG.Script.ScriptAppBase.CryptoFunctionGetSalt().
virtual int IG.Crypto.CryptoManager.ResolvePasswordParameters (int whichFreeParameterkeyLength = 0, int whichFreeParameterNumIterations = 1) inline virtual
Resolves password related parameters such as password, salt, and generated key length.
Paremeters that determine which free paremeters map to password-related parameters such as key length and number of iterations of key generation algorithm, must fill free parameters up to the specified index.
Parameters
whichFreeParameterkeyLength Index of free parameter that can eventually represent the key length. If less than 0 then key length can not be specified by free parameters.
whichFreeParameterNumIterations Index of free parameter that can eventually represent the number of iterations in password generating algorithm. If less than 0 then number of key generation iterations can not be specified by free parameters.
Returns
Number of free parameters that were eventually used for resolving password-related parameters.
References IG.Crypto.UtilCrypto.GetRandomBytes(), and IG.Crypto.UtilCrypto.StringEncoding.
virtual string IG.Crypto.CryptoManager.AppKeyGenerationAll (string appName, string[] args, bool measureTimes, int numGenerations) inline protected virtual
Executes command-line action - one of the actions related to key generation.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
measureTimes If true then time necessary for key generation with given parameters is measured. Otherwise, the key is actually created. The key can also be used as initialization vector.
numGenerations Number of repetirions of key algorithm before return. This makes possible to to generate different outputs e.g. for key, for initialization vector, or for salt.
References IG.Crypto.UtilCrypto.GetPasswordAlgorithm(), IG.Crypto.UtilCrypto.GetPasswordAlgorithmType(), IG.Crypto.PasswordAlgorithmBase.Init(), IG.Lib.StopWatch1.TestExecutionTime(), and IG.Lib.Util.ToHexString().
virtual void IG.Crypto.CryptoManager.ResolveAsymParameters () inline virtual
Resolves asymmetric algorithm parameters from the information that has been previously obtained through command-line parameters.
References IG.Crypto.UtilCrypto.GetAsymmetricAlgorithm(), and IG.Crypto.UtilCrypto.GetAsymmetricAlgorithmType().
virtual string IG.Crypto.CryptoManager.AppAsymKeyInfo (string appName, string[] args) inline virtual
Executes command-line action - prints information about asymmetric keys specified by command-line parameters.
Information necessary to access the asymmetric keys is extracted from command-line parameters.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
References IG.Crypto.UtilCrypto.AsymEncryptionDecryptionTest(), IG.Crypto.DSA, IG.Crypto.UtilCrypto.GetAsymmetricalgorithmHash(), IG.Crypto.UtilCrypto.GetMaximalAsymmetricTextLength(), IG.Crypto.UtilCrypto.ToString(), and IG.Lib.Util.XmlToString().
Referenced by IG.Script.ScriptAppBase.CryptoFunctionAsymKeyInfo().
virtual string IG.Crypto.CryptoManager.AppAsymExportKey (string appName, string[] args) inline virtual
Executes command-line action - exports asymmetric keys specified by command-line parameters.
Information necessary to access the asymmetric keys is extracted from command-line parameters.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
References IG.Crypto.UtilCrypto.AsymEncryptionDecryptionTest(), IG.Crypto.UtilCrypto.GetAsymmetricalgorithmHash(), IG.Crypto.UtilCrypto.GetMaximalAsymmetricTextLength(), IG.Lib.UtilConsole.Read(), IG.Crypto.UtilCrypto.ToString(), and IG.Lib.Util.XmlToString().
virtual string IG.Crypto.CryptoManager.AppCertStoreInfo (string appName, string[] args) inline virtual
Executes command-line action - prints information about the certificate stores specified by command-line parameters.
Information necessary to access the stores is extracted from command-line parameters.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
References IG.Crypto.UtilCrypto.GetCertificateStoreDescription().
Referenced by IG.Script.ScriptAppBase.CryptoFunctionCertStoreInfo().
virtual string IG.Crypto.CryptoManager.AppAddCertificate (string appName, string[] args) inline virtual
Executes command-line action - prints information about the certificate stores specified by command-line parameters.
Information necessary to access the stores is extracted from command-line parameters.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
References IG.Crypto.UtilCrypto.AddCertificateToStore(), IG.Crypto.UtilCrypto.GetCertificate(), IG.Crypto.UtilCrypto.GetSimpleName(), and IG.Lib.UtilConsole.ReadPwd().
Referenced by IG.Script.ScriptAppBase.CryptoFunctionAddCertificate().
virtual string IG.Crypto.CryptoManager.AppRemoveCertificate (string appName, string[] args) inline virtual
Executes command-line action - removes certificate with the specified name from the specified certificate store.
Information about the certificate name and the store is extracted from command-line parameters.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
References IG.Crypto.UtilCrypto.DeleteCertificateFromStore().
Referenced by IG.Script.ScriptAppBase.CryptoFunctionRemoveCertificate().
virtual string IG.Crypto.CryptoManager.AppCertInfo (string appName, string[] args) inline virtual
Executes command-line action - prints information about the certificate specified by command-line parameters.
Information necessary to access the certificate is extracted from command-line parameters.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
References IG.Crypto.UtilCrypto.AsymEncryptionDecryptionTest(), IG.Crypto.DSA, IG.Crypto.UtilCrypto.GetAsymmetricalgorithmHash(), IG.Crypto.UtilCrypto.GetCertificate(), IG.Crypto.UtilCrypto.GetMaximalAsymmetricTextLength(), IG.Lib.UtilConsole.ReadPwd(), and IG.Crypto.UtilCrypto.ToString().
Referenced by IG.Script.ScriptAppBase.CryptoFunctionCertInfo().
virtual string IG.Crypto.CryptoManager.AppAsymTest (string appName, string[] args) inline virtual
Executes command-line action - a couple of custom asymmetric encryption-related tests.
Parameters
appName Name of the embedded application.
args Arguments of the embedded application's command.
References IG.Crypto.UtilCrypto.AsymEncryptionDecryptionTest(), IG.Crypto.UtilCrypto.DecryptAsymShort(), IG.Crypto.UtilCrypto.DecryptStringAsymShort(), IG.Crypto.UtilCrypto.DeleteKeyInCsp(), IG.Crypto.UtilCrypto.EncryptAsymShort(), IG.Crypto.UtilCrypto.EncryptStringAsymShort(), IG.Crypto.UtilCrypto.GetAsymmetricAlgorithm(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Crypto.UtilCrypto.StringEncoding, IG.Lib.StopWatch1.Time, IG.Crypto.UtilCrypto.ToString(), and IG.Lib.Util.XmlToString().
Referenced by IG.Script.ScriptAppBase.CryptoFunctionAsymTest().
Member Data Documentation
int IG.Crypto.CryptoManager._numNotifyPlainEncryption = 0 static private
int IG.Crypto.CryptoManager._numNotifyExportPrivateKey = 0 static private
int IG.Crypto.CryptoManager._outputLevel = 2 private
string IG.Crypto.CryptoManager._appName = null private
string [] IG.Crypto.CryptoManager._appArguments = null private
PasswordAlgorithmType IG.Crypto.CryptoManager._passwordAlgorithmType = PasswordAlgorithmType.Default private
string IG.Crypto.CryptoManager._passwordAlgorithmTypeString = null private
PasswordAlgorithmBase IG.Crypto.CryptoManager._passwordAlgorithm = null private
string IG.Crypto.CryptoManager._algorithmTypeString = null private
HashType IG.Crypto.CryptoManager._hashAlgorithmType = HashType.Default private
SymmetricAlgorithmType IG.Crypto.CryptoManager._symmetricAlgorithmType = SymmetricAlgorithmType.Default private
bool IG.Crypto.CryptoManager._isDecrypt = false protected
bool IG.Crypto.CryptoManager._isExportPrivateKey = false private
AsymmetricAlgorithmType IG.Crypto.CryptoManager._asymAlgorithmType = AsymmetricAlgorithmType.Default private
AsymmetricAlgorithm IG.Crypto.CryptoManager._asymAlgorithm = null private
CspProviderFlags IG.Crypto.CryptoManager._asymFlags = CspProviderFlags.NoFlags private
string IG.Crypto.CryptoManager._asymAlgorithmTypeString = null private
string IG.Crypto.CryptoManager._asymKeyContainerName = null private
string IG.Crypto.CryptoManager._asymKeyFileXml = null private
string IG.Crypto.CryptoManager._certificatePath = null private
string IG.Crypto.CryptoManager._certificateName = null private
string IG.Crypto.CryptoManager._certificateStoreName = null private
int IG.Crypto.CryptoManager._certificateStoreLocation = 0 private
bool IG.Crypto.CryptoManager._certificatePasswordThroughUi = false private
string IG.Crypto.CryptoManager._certificatePassword = null private
string IG.Crypto.CryptoManager._hashValue = null private
bool IG.Crypto.CryptoManager._isStringInput = false private
int IG.Crypto.CryptoManager._passwordLength = 0 private
string IG.Crypto.CryptoManager._passwordString = null private
byte [] IG.Crypto.CryptoManager._passwordBytes = null private
int IG.Crypto.CryptoManager._saltLength = 0 private
string IG.Crypto.CryptoManager._saltString = null private
byte [] IG.Crypto.CryptoManager._saltBytes = null private
int IG.Crypto.CryptoManager._ivLength = 0 private
string IG.Crypto.CryptoManager._ivString = null private
byte [] IG.Crypto.CryptoManager._ivBytes = null private
int IG.Crypto.CryptoManager._keyLength = 0 private
byte [] IG.Crypto.CryptoManager._keyBytes = null private
bool IG.Crypto.CryptoManager._isLargestKey = false protected
int IG.Crypto.CryptoManager._numPasswordIterations = 0 private
List<string> IG.Crypto.CryptoManager._freeParameters = new List<string>() private
string IG.Crypto.CryptoManager._returnedString = null private
bool IG.Crypto.CryptoManager._isChecked = false private
double IG.Crypto.CryptoManager._targetedTotalTime = 0.1 private
string IG.Crypto.CryptoManager.OutputPath = null private
List<string> IG.Crypto.CryptoManager.RecursivePathList = new List<string>() private
List<string> IG.Crypto.CryptoManager.RecursivePathListByLevels = new List<string>() private
List<string> IG.Crypto.CryptoManager.RecursiveFilePatterns = new List<string>() private
int IG.Crypto.CryptoManager.RecursiveDirectoryLevels = -1 private
bool IG.Crypto.CryptoManager.IsRelativePaths = false private
bool IG.Crypto.CryptoManager.IsAbsolutePaths = false private
bool IG.Crypto.CryptoManager.IsDeleteOriginal = false private
Specifies whether the original files should be deleted.
This can refer to deletion of the original file(s) after encryption or decryption, or to deletion of the original file in a group(s) of associated files (original, encrypted, decrypted).
bool IG.Crypto.CryptoManager.IsDeleteEncrypted = false private
Specifies whether the encrypted files should be deleted.
This can refer to deletion of the encrypted file(s) in a group(s) of associated files (original, encrypted, decrypted) during a separate clean-up operation.
bool IG.Crypto.CryptoManager.IsDeleteDecrypted = false private
Specifies whether the encrypted files should be deleted.
This can refer to deletion of the decrypted file(s) in a group(s) of associated files (original, encrypted, decrypted) during a separate clean-up operation.
bool IG.Crypto.CryptoManager.IsDeleteAllVersions = false private
Specifies whether all versions of a file (e.g. original, encrypted, and decrypted) are allowed to be deleted (e.g. in a file clean-up operation).
bool IG.Crypto.CryptoManager.IsForceOverwrites = false private
If true then eventual file overwtires are automatically performed by the relevant operation without asking for user's approval.
bool IG.Crypto.CryptoManager.IsSkipOverwrites = false private
If true then eventual file overwrites are automatically wasSkipped by the relevant operation.
This means that whenever the operation in question would normally have to overwrite an existent file, this is wasSkipped, without even asking ro user's approval. For example, if decryption is performed but some of the original files already exist then these files will not be dcrypted as the operation would heve to overrwrite the original files.
bool IG.Crypto.CryptoManager.IsForceDeletes = false private
bool IG.Crypto.CryptoManager.IsSkipDeletes = false private
bool IG.Crypto.CryptoManager.IsInputFormatEqualOutputFormat = false private
If true then options for input formats and output format are treated interchangeably in the currentt context (e.g. in the current command-line application).
bool IG.Crypto.CryptoManager._isInputFormatLongInt = false private
bool IG.Crypto.CryptoManager._isInputFormat64 = false private
bool IG.Crypto.CryptoManager._isInputFormatHex = false private
bool IG.Crypto.CryptoManager._isOutputFormatLongInt = false private
bool IG.Crypto.CryptoManager._isOutputFormat64 = false private
bool IG.Crypto.CryptoManager._isOutputFormatHex = false private
Property Documentation
int IG.Crypto.CryptoManager.OutputLevel get set private
Level of output during operation.
string IG.Crypto.CryptoManager.AppName get protected set
string [] IG.Crypto.CryptoManager.AppArguments get set
Last (or currently) read command-line arguments.
int IG.Crypto.CryptoManager.NumAppArguments get private
Number of command-line arguments.
PasswordAlgorithmType IG.Crypto.CryptoManager.PasswordAlgorithmType get set private
Type of the algorithm used for password hashing.
string IG.Crypto.CryptoManager.PasswordAlgorithmTypeString get set private
Name of the algorithm used in password hashing.
PasswordAlgorithmBase IG.Crypto.CryptoManager.PasswordAlgorithm get set private
Password hashing algorithm.
string IG.Crypto.CryptoManager.AlgorithmTypeString get set private
String representation of algorithm type.
HashType IG.Crypto.CryptoManager.HashAlgorithmType get set private
Hashing algorithm type.
SymmetricAlgorithmType IG.Crypto.CryptoManager.SymmetricAlgorithmType get set private
Symmetric algorithm type.
bool IG.Crypto.CryptoManager.IsDecrypt get protected set
Whether decryption is perrformed, rather than encryption.
bool IG.Crypto.CryptoManager.IsEncrypt get protected set
Whether decryption is perrformed, rather than encryption.
bool IG.Crypto.CryptoManager.IsExportPrivateKey get protected set
Whether private key is also exported or printed.
AsymmetricAlgorithmType IG.Crypto.CryptoManager.AsymAlgorithmType get protected set
AsymmetricAlgorithm IG.Crypto.CryptoManager.AsymAlgorithm get set protected
Asymmetric algorithm, equipped with keys, that will perform asymmetric cryptographic tasks.
CspProviderFlags IG.Crypto.CryptoManager.AsymFlags get set
Asymmetric CSP (crypto service provider) flags.
string IG.Crypto.CryptoManager.AsymAlgorithmTypeString get protected set
String that represents asymmetric algorithm type.
string IG.Crypto.CryptoManager.AsymKeyContainerName get protected set
Asymmetric key container name.
string IG.Crypto.CryptoManager.AsymKeyFileXml get protected set
Asymmetric key file path in XML format.
string IG.Crypto.CryptoManager.CertificatePath get protected set
Path to the certificate file (e.g. for obtaining asymmetric keys).
string IG.Crypto.CryptoManager.CertificateName get protected set
Certificate name (usually specified to locate the certificate in a certificate store).
string IG.Crypto.CryptoManager.CertificateStoreName get protected set
Name of the certificate store (usually, to locate the specified certificate).
int IG.Crypto.CryptoManager.CertificateStoreLocation get protected set
Location of the certificate store (usually used to filter certificate stores).
bool IG.Crypto.CryptoManager.IsCertificatePasswordThroughUi get protected set
Indicates that pasword for private key should obtained from the user through GUI (usually through console).
string IG.Crypto.CryptoManager.CertificatePassword get set protected
Password for accessing private keys (e.g. for private keys associated with certificate).
string IG.Crypto.CryptoManager.HashValue get set private
Hash value, usually used for checking consistency.
bool IG.Crypto.CryptoManager.IsStringInput get set private
Flag indicating that input are strings or encoded byte arrays, rather than files.
int IG.Crypto.CryptoManager.PasswordLength get set private
Length of the (generated) password.
string IG.Crypto.CryptoManager.PasswordString get set private
byte [] IG.Crypto.CryptoManager.PasswordBytes get set private
Password as byte array.
int IG.Crypto.CryptoManager.SaltLength get set private
Length of salt.
string IG.Crypto.CryptoManager.SaltString get set private
Salt string.
byte [] IG.Crypto.CryptoManager.SaltBytes get set private
Salt as byte array.
int IG.Crypto.CryptoManager.IvLength get set private
Length of the initialization vector.
string IG.Crypto.CryptoManager.IvString get set private
Initialization vector in string form.
byte [] IG.Crypto.CryptoManager.IvBytes get set private
Initialization vector as byte array.
int IG.Crypto.CryptoManager.KeyLength get set private
Length of the key.
byte [] IG.Crypto.CryptoManager.KeyBytes get set private
Secret key as byte array.
bool IG.Crypto.CryptoManager.IsLargestKey get set private
Whether the largest available key size for the algorithm in use is taken.
int IG.Crypto.CryptoManager.NumPasswordIterations get set private
Number of iterations in passworg hashing algorithms, aimed at increasing processing effort to break the password.
List<string> IG.Crypto.CryptoManager.FreeParameters get protected
List of free parameters from the parsed command-line.
int IG.Crypto.CryptoManager.NumFreeParameters get
Number of free parameters (obtained from commans-line arguments).
string IG.Crypto.CryptoManager.ReturnedString get set private
Returned value of command-line application methods.
bool IG.Crypto.CryptoManager.IsChecked get set private
Indicates that something is verified, not calculated (or checked in addition, after calculation).
double IG.Crypto.CryptoManager.TargetedTotalTime get set protected
Total time targeted in multi-pass algorithms (e.g. in password hashing).
bool IG.Crypto.CryptoManager.IsInputFormatString get set private
Whether input format is ordinary string. Returns true if there is no binary format specified, false if there is.
bool IG.Crypto.CryptoManager.IsInputFormatLongInt get protected set
bool IG.Crypto.CryptoManager.IsInputFormat64 get protected set
Whether input is in form of base-64 encoded byte array.
bool IG.Crypto.CryptoManager.IsInputFormatHex get protected set
Whether input is in form of hexadecimal encoded byte array.
bool IG.Crypto.CryptoManager.IsOutputFormatString get set private
Whether output format is ordinary string. Returns true if there is no binary format specified, false if there is.
bool IG.Crypto.CryptoManager.IsOutputFormatLongInt get protected set
Whether output is in form of long integer.
bool IG.Crypto.CryptoManager.IsOutputFormat64 get protected set
Whether output is in form of base-64 encoded byte array.
bool IG.Crypto.CryptoManager.IsOutputFormatHex get protected set
Whether output is in form of hexadecimal encoded byte array.
The documentation for this class was generated from the following file:
iglib/igbase/utilities/UilCryptoAux1.cs