IGLib: IG.Num.IVector Interface Reference
IG.Num.IVector Interface Reference
Real vector intrface.
Public Member Functions
IVector GetCopy ()
Returns a deep copy of the current object.
IVector GetNew (int length)
Creates and returns a new vector with the specified dimension, and of the same type as the current vector.
IVector GetNew ()
Creates and returns a new vector with the same dimension and of the same type as the current vector.
IMatrix GetNewMatrix (int rowCount, int columnCount)
Creates and returns a new matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
IMatrix GetNewMatrix ()
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
void SetConstant (double elementValue)
Sets all components of the current vector to the specified value.
void SetUnit (int which)
Sets the current vector to the specific unit vector (one component equals 1, others are 0).
void SetRandom ()
Sets the current vector such that it contains random elements on the interval (0,1].
void SetRandom (IRandomGenerator rnd)
Sets the current vector such that it contains random elements on the interval (0,1].
void SetZero ()
Sets all components of the current vector to 0.
IVector Normalized ()
Returns a vector that equals a normalized current vector.
string ToString ()
Returns a string representation of this vector in a standard IGLib form (Mathematica-like format but with C representation of numbers).
string ToStringMath ()
Returns a string representation of this vector in a standard IGLib form (Mathematica-like format but with C representation of numbers).
string ToString (string elementFormat)
Returns a string representation of the current vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified format for elements of the vector.
string ToStringMath (string elementFormat)
Returns a string representation of the current vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified format for elements of the vector.
int GetHashFunctionInt ()
Returns an integer valued hashRet function of the current vector object.
string GetHashFunctionString ()
Returns a string valued hashRet function of the current vector object.
Detailed Description
Real vector intrface.
$A Igor Sep08;
Member Function Documentation
IVector IG.Num.IVector.GetCopy ()
Returns a deep copy of the current object.
Implemented in IG.Num.VectorBase.
Referenced by IG.Num.ApproximatorWlsLinearBase.AddValue(), IG.Num.SampledDataSet.ComparerInputDistance.ComparerInputDistance(), IG.Num.SampledDataSet.ComparerOutputDistance.ComparerOutputDistance(), IG.Num.ResponseEvaluatorWithStorageVector.CreateRequestThis(), IG.NumExperimental.ResponseEvaluatorWithStorageVector.CreateRequestThis(), IG.Num.ResponseEvaluatorWithStorageAnalysis.CreateRequestThis(), IG.NumExperimental.ResponseEvaluatorWithStorageAnalysis.CreateRequestThis(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtRobustD7(), IG.Neural.Forms.Old.NeuralParametricDemoOld.PlotRandTrainingAndVerificationPointsResponse(), IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.PlotTrainingAndVerificationPointsResponse(), IG.Neural.Forms.Old.NeuralParametricDemoOld.PlotTrainingAndVerificationPointsResponse(), IG.Script.LoadableScriptShellNeuralIT.PlotTrainingAndVerificationPointsResponse(), IG.Script.S_13_5_Convection.RunRandomSimulationsLog(), IG.Num.AnalysisResults.SetConstraintGradient(), IG.Num.VectorFunctionResults.SetGradient(), IG.Num.ScalarFunctionUntransformedBase.TestGradient(), and IG.Num.ScalarFunctionUntransformedBase.TestHessian().
IVector IG.Num.IVector.GetNew (int length)
Creates and returns a new vector with the specified dimension, and of the same type as the current vector.
Parameters
length Dimension of the newly created vector.
Returns
A newly created vector of the specified dimension and of the same type as the current vector.
Implemented in IG.Num.VectorBase.
Referenced by IG.Num.VectorBase.Add(), IG.Num.VectorBase.ArrayAdd(), IG.Num.VectorBase.ArrayProduct(), IG.Num.VectorBase.ArrayQuotient(), IG.Num.VectorBase.ArraySubtract(), IG.Num.MatrixBase.CholeskySolve(), IG.Num.VectorBase.Copy(), IG.Num.VectorBase.CrossProduct(), IG.Num.VectorBase.Divide(), IG.Num.ScalarFunctionUntransformedBase.Evaluate(), IG.Num.ScalarFunctionUntransformedBase.Gradient(), IG.Num.ScalarFunctionBase.GradientPlain(), IG.Num.ScalarFunctionRadialUntransformed.GradientPlain(), IG.Num.MatrixBase.LdltSolve(), IG.Num.VectorBase.Multiply(), IG.Num.VectorBase.Negate(), IG.Num.ScalarFunctionUntransformedBase.NumericalGradientCentral(), IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForward(), IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentral(), IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForward(), IG.Num.VectorBase.OrthogonalizeGramSchmidt(), IG.Num.VectorBase.OrthogonalProjection(), IG.Num.MatrixBase.QrSolve(), IG.Num.ScalarFunctionRadial.ReferenceGradientPlain(), IG.Num.VectorBase.Scale(), IG.Num.RealFunctionParametricBase.SetParameters(), IG.Num.ScalarFunctionParametricBase.SetParameters(), IG.Num.ScalarFunctionRadialParametric.SetParameters(), IG.Num.VectorBase.Subtract(), IG.Num.ScalarFunctionUntransformedBase.Test(), IG.Num.AffineTransformationSquare.TransformBackCoordinates(), IG.Num.AffineTransformationSquare.TransformBackGradient(), IG.Num.AffineTransformationSquare.TransformCoordinates(), and IG.Num.AffineTransformationSquare.TransformGradient().
IVector IG.Num.IVector.GetNew ()
Creates and returns a new vector with the same dimension and of the same type as the current vector.
Implemented in IG.Num.VectorBase.
IMatrix IG.Num.IVector.GetNewMatrix (int rowCount, int columnCount)
Creates and returns a new matrix with the specified dimensona, and of a type that is consistent with the type of the current vector.
Parameters
rowCount Number of rows of the returned matrix.
columnCount Number of rows of the returned matrix.
Returns
A matrix with specified dimensions, whose type is consistent with the type of the current vector.
Implemented in IG.Num.VectorBase.
Referenced by IG.Num.VectorBase.DyadicProduct(), IG.Num.ScalarFunctionUntransformedBase.Evaluate(), IG.Num.ScalarFunctionUntransformedBase.Hessian(), IG.Num.ScalarFunctionBase.HessianPlain(), IG.Num.ScalarFunctionUntransformedBase.NumericalHessianCentral(), and IG.Num.ScalarFunctionUntransformedBase.NumericalHessianForward().
IMatrix IG.Num.IVector.GetNewMatrix ()
Creates and returns a new matrix of a type that is consistent with the type of the current vector, and with both dimensions equal to the dimension of the current vector.
Implemented in IG.Num.VectorBase.
void IG.Num.IVector.SetConstant (double elementValue)
Sets all components of the current vector to the specified value.
Parameters
elementValue Value to which vector elements are set.
Implemented in IG.Num.VectorBase.
Referenced by IG.Num.ScalarFunctionUntransformedBase.TestGradient(), IG.Num.TestAlglibOld2008.TestLbfgsAlglibOld(), and IG.Script.ScriptExtNumeric.TestScalarFunctions().
void IG.Num.IVector.SetUnit (int which)
Sets the current vector to the specific unit vector (one component equals 1, others are 0).
Parameters
which Specifies which unit vector is set (i.e., which component equals 1).
Implemented in IG.Num.VectorBase.
void IG.Num.IVector.SetRandom ()
Sets the current vector such that it contains random elements on the interval (0,1].
Implemented in IG.Num.VectorBase.
Referenced by IG.Num.SampledDataSet.CreateExampleLinear(), IG.Num.SampledDataSet.CreateExampleQuadratic(), IG.Test.TestMatrixDecomposition.Qr_MatrixBase(), IG.Test.TestMatrixDecomposition.QrGrammSchmidt_MatrixBase(), IG.Num.ApproximationLeastSquaresBase.TestMlsQuadratic(), and IG.Num.MatrixBaseDev.TestSolveLLT().
void IG.Num.IVector.SetRandom (IRandomGenerator rnd)
Sets the current vector such that it contains random elements on the interval (0,1].
Parameters
rnd Random generator used to generate vector elements.
Implemented in IG.Num.VectorBase.
void IG.Num.IVector.SetZero ()
Sets all components of the current vector to 0.
Implemented in IG.Num.VectorBase.
Referenced by IG.Num.ScalarFunctionConstant.GradientPlain(), IG.Num.ScalarFunctionLinear.GradientPlain(), IG.Num.ScalarFunctionQuadratic.GradientPlain(), IG.Num.ScalarFunctionExamples.RosenbrockGeneralizedAdjacent.ReferenceGradientPlain(), and IG.Num.ScalarFunctionExamples.RosenbrockGeneralizedExhaustive.ReferenceGradientPlain().
IVector IG.Num.IVector.Normalized ()
Returns a vector that equals a normalized current vector.
Implemented in IG.Num.VectorBase, IG.Num.Vector3d, and IG.Num.Vector2d.
string IG.Num.IVector.ToString ()
Returns a string representation of this vector in a standard IGLib form (Mathematica-like format but with C representation of numbers).
Implemented in IG.Num.VectorBase, IG.Num.Vector3d, and IG.Num.Vector2d.
Referenced by IG.Lib.InterfaceInverse.AppendValue(), IG.Lib.TemporaryInterfaceInvAn_Temp_For_Testing.AppendValue(), IG.Lib.ScalarFunctionLoader.Example(), IG.Neural.NeuralNetworks.Example3D(), IG.Neural.NeuralTadej.ExampleCasting(), IG.Neural.NeuralTadej.ExampleQuadratic(), IG.Num.NeuralApproximatorBase.ExampleQuadratic(), IG.Neural.NeuralTadej.ExampleStore(), IG.Script.AppExtBase.FormDemoFunctionTestDevelop(), IG.Num.SampledDataCsv.RestoreData(), IG.Script.LoadableScriptShellNeuralBase.SaveSensitivityCSV(), IG.Script.LoadableScriptShellNeuralITOriginalBase.SaveSensitivityCSV(), IG.Script.S_13_5_Convection.SimRun(), IG.Script.LoadableScriptShellNeuralITOriginalBase.StochasticInfluence(), IG.Num.SampledDataCsv.StoreData(), IG.Script.LoadableScriptShellNeuralITOriginalBase.TestAnalysis(), IG.Script.LoadableScriptShellNeuralBase.TestAnalysis(), IG.Script.LoadableScriptShellNeuralITOriginalBase.TestApproximation(), IG.Script.LoadableScriptShellNeuralBase.TestApproximation(), IG.Num.PointCloud< PointLinkType, PointContainerType, PointType >.TestClosestPoints(), IG.Script.Script_11_10_clanek_neural_01.TestClosestPoints(), IG.Script.LoadableScriptShellNeuralITOriginalBase.TestClosestPoints(), IG.Script.LoadableScriptShellNeuralBase.TestClosestPoints(), IG.Num.PointCloud< PointLinkType, PointContainerType, PointType >.TestClosestPointsWithOutputs(), IG.Num.ScalarFunctionUntransformedBase.TestGradient(), IG.Num.ScalarFunctionUntransformedBase.TestHessian(), IG.Num.TestAlglibOld2008.TestLbfgsAlglibOld(), IG.Neural.Applications.ProgramTestTadejApp.TestPrediction(), IG.Script.S_12_03_paper_gk.TestSimulator(), IG.Num.ScalarFunctionUntransformedBase.TestSpeed(), IG.Num.ApproximatorWlsLinearBase.TestWeightedLeastSquaresMultiplePolynomialBasis(), IG.Num.ApproximatorWlsLinearBase.TestWeightedLeastSquaresPolynomialBasis(), IG.Num.ApproximatorWlsLinearBase.ToString(), IG.Num.SampledDataSet.ToString(), IG.Num.VectorBase.ToStringMath(), IG.Script.LoadableScriptShellNeuralIT.TrainANN(), IG.Script.LoadableScriptShellNeuralITOriginalBase.TrainANN(), IG.Script.LoadableScriptShellNeuralBase.TrainANN(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainANN(), IG.Neural.NeuralTadej.TrainNetwork(), IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.WriteParametersToGridPrediction(), IG.Neural.Forms.Old.NeuralParametricDemoOld.WriteParametersToGridPrediction(), and IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.WriteValesToGrid().
string IG.Num.IVector.ToStringMath ()
Returns a string representation of this vector in a standard IGLib form (Mathematica-like format but with C representation of numbers).
Implemented in IG.Num.VectorBase.
Referenced by IG.Num.SimCastingRobertFileManager.CalculateVectorResponse(), IG.Num.SimKosecFileManagerBase.CalculateVectorResponse(), IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.CalculateVectorResponseJson(), IG.Num.MatrixBase.TestCholeskyDecompositionDemo(), and IG.Num.MatrixBase.TestLuDecompositionDemo().
string IG.Num.IVector.ToString (string elementFormat)
Returns a string representation of the current vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified format for elements of the vector.
Parameters
elementFormat Format specification for printing individual element.
Implemented in IG.Num.VectorBase.
string IG.Num.IVector.ToStringMath (string elementFormat)
Returns a string representation of the current vector in a standard IGLib form (Mathematica-like format but with C representation of numbers), with the specified format for elements of the vector.
Parameters
elementFormat Format specification for printing individual element.
Implemented in IG.Num.VectorBase.
int IG.Num.IVector.GetHashFunctionInt ()
Returns an integer valued hashRet function of the current vector object.
The returned value is calculated by the Util.GetHashFunctionInt method.
See also
Util.GetHashFunctionInt
Implemented in IG.Num.VectorBase.
string IG.Num.IVector.GetHashFunctionString ()
Returns a string valued hashRet function of the current vector object.
The returned value is calculated by the Util.GetHashFunctionString method.
The returned string is always on the same length, and is based on the ToString() method. Therefore it is convenient for use in file or directory names that have one part related to a specific vector.
See also
Util.GetHashFunctionString
Implemented in IG.Num.VectorBase.
The documentation for this interface was generated from the following file:
iglib/igbase/numeric/VectorBase.cs