IGLib: NUnit.Engine.Services.ProjectLoaders.NUnitProject Class Reference
NUnit.Engine.Services.ProjectLoaders.NUnitProject Class Reference
Public Member Functions
TestPackage GetTestPackage ()
Gets a test package for the primary or active configuration within the project. The package includes all the assemblies and any settings specified in the project format.
TestPackage GetTestPackage (string configName)
Gets a TestPackage for a specific configuration within the project. The package includes all the assemblies and any settings specified in the project format.
void Load (string filename)
void LoadXml (string xmlText)
string GetSetting (string name)
string GetSetting (string name, string defaultValue)
string GetProjectBasePath ()
GetProjectBasePath uses the BasePath if present and otherwise defaults to the directory part of the ProjectPath.
Properties
string ProjectPath [get, private set]
Gets the path to the file storing this project, if any. If the project has not been saved, this is null.
string ActiveConfigName [get]
Gets the active configuration, as defined by the particular project. For an NUnit project, we use the activeConfig attribute if present and otherwise return the first config found.
IList< string > ConfigNames [get]
Properties inherited from NUnit.Engine.Extensibility.IProject
string ProjectPath [get]
Gets the path to the file storing this project, if any. If the project has not been saved, this is null.
string ActiveConfigName [get]
Gets the active configuration, as defined by the particular project.
IList< string > ConfigNames [get]
Gets a list of the configs for this project
Private Member Functions
XmlNode GetConfigNode (string name)
string GetBasePathForConfig (XmlNode configNode)
IDictionary< string, object > GetSettingsForConfig (XmlNode configNode)
string NormalizePath (string path)
Private Attributes
XmlDocument xmlDoc = new XmlDocument()
The XmlDocument representing the loaded doc. It is generated from the text when the doc is loaded unless an exception is thrown. It is modified as the user makes changes.
Static Private Attributes
static readonly char[] PATH_SEPARATORS = new char[] { '/', '\\' }
Member Function Documentation
TestPackage NUnit.Engine.Services.ProjectLoaders.NUnitProject.GetTestPackage () inline
Gets a test package for the primary or active configuration within the project. The package includes all the assemblies and any settings specified in the project format.
Returns
A TestPackage
Implements NUnit.Engine.Extensibility.IProject.
Referenced by NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.GetTestPackage().
TestPackage NUnit.Engine.Services.ProjectLoaders.NUnitProject.GetTestPackage (string configName) inline
Gets a TestPackage for a specific configuration within the project. The package includes all the assemblies and any settings specified in the project format.
Parameters
configName The name of the config to use
Returns
A TestPackage for the named configuration.
Implements NUnit.Engine.Extensibility.IProject.
void NUnit.Engine.Services.ProjectLoaders.NUnitProject.Load (string filename) inline
Referenced by NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.GetTestPackage(), and NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.LoadFrom().
void NUnit.Engine.Services.ProjectLoaders.NUnitProject.LoadXml (string xmlText) inline
string NUnit.Engine.Services.ProjectLoaders.NUnitProject.GetSetting (string name) inline
string NUnit.Engine.Services.ProjectLoaders.NUnitProject.GetSetting (string name, string defaultValue) inline
XmlNode NUnit.Engine.Services.ProjectLoaders.NUnitProject.GetConfigNode (string name) inline private
string NUnit.Engine.Services.ProjectLoaders.NUnitProject.GetProjectBasePath () inline
GetProjectBasePath uses the BasePath if present and otherwise defaults to the directory part of the ProjectPath.
string NUnit.Engine.Services.ProjectLoaders.NUnitProject.GetBasePathForConfig (XmlNode configNode) inline private
IDictionary<string, object> NUnit.Engine.Services.ProjectLoaders.NUnitProject.GetSettingsForConfig (XmlNode configNode) inline private
References NUnit.Engine.RunnerSettings.AutoBinPath, NUnit.Engine.RunnerSettings.BasePath, NUnit.Engine.RunnerSettings.ConfigurationFile, NUnit.Engine.RunnerSettings.DomainUsage, NUnit.Engine.RunnerSettings.PrivateBinPath, NUnit.Engine.RunnerSettings.ProcessModel, and NUnit.Engine.RunnerSettings.RuntimeFramework.
string NUnit.Engine.Services.ProjectLoaders.NUnitProject.NormalizePath (string path) inline private
Member Data Documentation
XmlDocument NUnit.Engine.Services.ProjectLoaders.NUnitProject.xmlDoc = new XmlDocument() private
The XmlDocument representing the loaded doc. It is generated from the text when the doc is loaded unless an exception is thrown. It is modified as the user makes changes.
readonly char [] NUnit.Engine.Services.ProjectLoaders.NUnitProject.PATH_SEPARATORS = new char[] { '/', '\\' } static private
Property Documentation
string NUnit.Engine.Services.ProjectLoaders.NUnitProject.ProjectPath get private set
Gets the path to the file storing this project, if any. If the project has not been saved, this is null.
string NUnit.Engine.Services.ProjectLoaders.NUnitProject.ActiveConfigName get
Gets the active configuration, as defined by the particular project. For an NUnit project, we use the activeConfig attribute if present and otherwise return the first config found.
IList<string> NUnit.Engine.Services.ProjectLoaders.NUnitProject.ConfigNames get
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/Addins/nunit-project-loader/NUnitProject.cs