IGLib: alglib.testminlmunit Class Reference
alglib.testminlmunit Class Reference
Static Public Member Functions
static bool testminlm (bool silent)
static bool testminlm (bool silent)
static bool _pexec_testminlm (bool silent)
Static Private Member Functions
static bool rkindvsstatecheck (int rkind, minlm.minlmstate state)
static void axmb (minlm.minlmstate state, double[,] a, double[] b, int n)
static void tryreproducefixedbugs (ref bool err)
static bool gradientchecktest ()
static void funcderiv (double[] a, double[] x0, double[] x, int m, int n, double anyconst, int functype, ref double[] f, ref double[,] j)
static bool rkindvsstatecheck (int rkind, minlm.minlmstate state)
static void axmb (minlm.minlmstate state, double[,] a, double[] b, int n)
static void tryreproducefixedbugs (ref bool err)
static bool gradientchecktest ()
static void funcderiv (double[] a, double[] x0, double[] x, int m, int n, double anyconst, int functype, ref double[] f, ref double[,] j)
Member Function Documentation
static bool alglib.testminlmunit.testminlm (bool silent) inline static
References alglib.ap.assert(), alglib.testminlmunit.axmb(), alglib.apserv.boundval(), alglib.testminlmunit.gradientchecktest(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.minlm.minlmcreatefgh(), alglib.minlm.minlmcreatefgj(), alglib.minlm.minlmcreatefj(), alglib.minlm.minlmcreatev(), alglib.minlm.minlmcreatevj(), alglib.minlm.minlmiteration(), alglib.minlm.minlmrestartfrom(), alglib.minlm.minlmresults(), alglib.minlm.minlmsetacctype(), alglib.minlm.minlmsetbc(), alglib.minlm.minlmsetcond(), alglib.minlm.minlmsetstpmax(), alglib.minlm.minlmsetxrep(), alglib.math.randomreal(), alglib.testminlmunit.rkindvsstatecheck(), alglib.matgen.rmatrixrndcond(), alglib.math.sqr(), and alglib.testminlmunit.tryreproducefixedbugs().
Referenced by alglib.testminlmunit._pexec_testminlm(), and _Test.Main().
static bool alglib.testminlmunit.rkindvsstatecheck (int rkind, minlm.minlmstate state) inline static private
Referenced by alglib.testminlmunit.testminlm().
static void alglib.testminlmunit.axmb (minlm.minlmstate state, double a[,], double[] b, int n) inline static private
References alglib.math.sqr().
Referenced by alglib.testminlmunit.testminlm().
static void alglib.testminlmunit.tryreproducefixedbugs (ref bool err) inline static private
References alglib.minlm.minlmcreatev(), alglib.minlm.minlmiteration(), alglib.minlm.minlmresults(), alglib.minlm.minlmsetbc(), and alglib.math.sqr().
Referenced by alglib.testminlmunit.testminlm().
static bool alglib.testminlmunit.gradientchecktest () inline static private
References alglib.testminlmunit.funcderiv(), alglib.math.isfinite(), alglib.minlm.minlmcreatevj(), alglib.minlm.minlmiteration(), alglib.minlm.minlmrestartfrom(), alglib.minlm.minlmresults(), alglib.minlm.minlmsetbc(), alglib.minlm.minlmsetcond(), alglib.minlm.minlmsetgradientcheck(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testminlmunit.testminlm().
static void alglib.testminlmunit.funcderiv (double[] a, double[] x0, double[] x, int m, int n, double anyconst, int functype, ref double[] f, ref double j[,]) inline static private
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
Referenced by alglib.testminlmunit.gradientchecktest().
static bool alglib.testminlmunit.testminlm (bool silent) inline static
References alglib.ap.assert(), alglib.testminlmunit.axmb(), alglib.apserv.boundval(), alglib.testminlmunit.gradientchecktest(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.minlm.minlmcreatefgh(), alglib.minlm.minlmcreatefgj(), alglib.minlm.minlmcreatefj(), alglib.minlm.minlmcreatev(), alglib.minlm.minlmcreatevj(), alglib.minlm.minlmiteration(), alglib.minlm.minlmrestartfrom(), alglib.minlm.minlmresults(), alglib.minlm.minlmsetacctype(), alglib.minlm.minlmsetbc(), alglib.minlm.minlmsetcond(), alglib.minlm.minlmsetstpmax(), alglib.minlm.minlmsetxrep(), alglib.math.randomreal(), alglib.testminlmunit.rkindvsstatecheck(), alglib.matgen.rmatrixrndcond(), alglib.math.sqr(), and alglib.testminlmunit.tryreproducefixedbugs().
static bool alglib.testminlmunit._pexec_testminlm (bool silent) inline static
References alglib.testminlmunit.testminlm().
Referenced by _Test.Main().
static bool alglib.testminlmunit.rkindvsstatecheck (int rkind, minlm.minlmstate state) inline static private
static void alglib.testminlmunit.axmb (minlm.minlmstate state, double a[,], double[] b, int n) inline static private
References alglib.math.sqr().
static void alglib.testminlmunit.tryreproducefixedbugs (ref bool err) inline static private
References alglib.minlm.minlmcreatev(), alglib.minlm.minlmiteration(), alglib.minlm.minlmresults(), alglib.minlm.minlmsetbc(), and alglib.math.sqr().
static bool alglib.testminlmunit.gradientchecktest () inline static private
References alglib.testminlmunit.funcderiv(), alglib.math.isfinite(), alglib.minlm.minlmcreatevj(), alglib.minlm.minlmiteration(), alglib.minlm.minlmrestartfrom(), alglib.minlm.minlmresults(), alglib.minlm.minlmsetbc(), alglib.minlm.minlmsetcond(), alglib.minlm.minlmsetgradientcheck(), alglib.math.randominteger(), alglib.apserv.randomnormal(), and alglib.math.randomreal().
static void alglib.testminlmunit.funcderiv (double[] a, double[] x0, double[] x, int m, int n, double anyconst, int functype, ref double[] f, ref double j[,]) inline static private
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs