IGLib: alglib.spline1d Class Reference
alglib.spline1d Class Reference
Classes
class spline1dinterpolant
Static Public Member Functions
static void spline1dbuildlinear (double[] x, double[] y, int n, spline1dinterpolant c)
static void spline1dbuildcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, spline1dinterpolant c)
static void spline1dgriddiffcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, ref double[] d)
static void spline1dgriddiff2cubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, ref double[] d1, ref double[] d2)
static void spline1dconvcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, double[] x2, int n2, ref double[] y2)
static void spline1dconvdiffcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, double[] x2, int n2, ref double[] y2, ref double[] d2)
static void spline1dconvdiff2cubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, double[] x2, int n2, ref double[] y2, ref double[] d2, ref double[] dd2)
static void spline1dbuildcatmullrom (double[] x, double[] y, int n, int boundtype, double tension, spline1dinterpolant c)
static void spline1dbuildhermite (double[] x, double[] y, double[] d, int n, spline1dinterpolant c)
static void spline1dbuildakima (double[] x, double[] y, int n, spline1dinterpolant c)
static double spline1dcalc (spline1dinterpolant c, double x)
static void spline1ddiff (spline1dinterpolant c, double x, ref double s, ref double ds, ref double d2s)
static void spline1dcopy (spline1dinterpolant c, spline1dinterpolant cc)
static void spline1dunpack (spline1dinterpolant c, ref int n, ref double[,] tbl)
static void spline1dlintransx (spline1dinterpolant c, double a, double b)
static void spline1dlintransy (spline1dinterpolant c, double a, double b)
static double spline1dintegrate (spline1dinterpolant c, double x)
static void spline1dconvdiffinternal (double[] xold, double[] yold, double[] dold, int n, double[] x2, int n2, ref double[] y, bool needy, ref double[] d1, bool needd1, ref double[] d2, bool needd2)
static void spline1drootsandextrema (spline1dinterpolant c, ref double[] r, ref int nr, ref bool dr, ref double[] e, ref int[] et, ref int ne, ref bool de)
static void heapsortdpoints (ref double[] x, ref double[] y, ref double[] d, int n)
static void solvepolinom2 (double p0, double m0, double p1, double m1, ref double x0, ref double x1, ref int nr)
static void solvecubicpolinom (double pa, double ma, double pb, double mb, double a, double b, ref double x0, ref double x1, ref double x2, ref double ex0, ref double ex1, ref int nr, ref int ne, ref double[] tempdata)
static int bisectmethod (double pa, double ma, double pb, double mb, double a, double b, ref double x)
static void spline1dbuildmonotone (double[] x, double[] y, int n, spline1dinterpolant c)
static void spline1dbuildlinear (double[] x, double[] y, int n, spline1dinterpolant c)
static void spline1dbuildcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, spline1dinterpolant c)
static void spline1dgriddiffcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, ref double[] d)
static void spline1dgriddiff2cubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, ref double[] d1, ref double[] d2)
static void spline1dconvcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, double[] x2, int n2, ref double[] y2)
static void spline1dconvdiffcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, double[] x2, int n2, ref double[] y2, ref double[] d2)
static void spline1dconvdiff2cubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, double[] x2, int n2, ref double[] y2, ref double[] d2, ref double[] dd2)
static void spline1dbuildcatmullrom (double[] x, double[] y, int n, int boundtype, double tension, spline1dinterpolant c)
static void spline1dbuildhermite (double[] x, double[] y, double[] d, int n, spline1dinterpolant c)
static void spline1dbuildakima (double[] x, double[] y, int n, spline1dinterpolant c)
static double spline1dcalc (spline1dinterpolant c, double x)
static void spline1ddiff (spline1dinterpolant c, double x, ref double s, ref double ds, ref double d2s)
static void spline1dcopy (spline1dinterpolant c, spline1dinterpolant cc)
static void spline1dunpack (spline1dinterpolant c, ref int n, ref double[,] tbl)
static void spline1dlintransx (spline1dinterpolant c, double a, double b)
static void spline1dlintransy (spline1dinterpolant c, double a, double b)
static double spline1dintegrate (spline1dinterpolant c, double x)
static void spline1dconvdiffinternal (double[] xold, double[] yold, double[] dold, int n, double[] x2, int n2, ref double[] y, bool needy, ref double[] d1, bool needd1, ref double[] d2, bool needd2)
static void spline1drootsandextrema (spline1dinterpolant c, ref double[] r, ref int nr, ref bool dr, ref double[] e, ref int[] et, ref int ne, ref bool de)
static void heapsortdpoints (ref double[] x, ref double[] y, ref double[] d, int n)
static void solvepolinom2 (double p0, double m0, double p1, double m1, ref double x0, ref double x1, ref int nr)
static void solvecubicpolinom (double pa, double ma, double pb, double mb, double a, double b, ref double x0, ref double x1, ref double x2, ref double ex0, ref double ex1, ref int nr, ref int ne, ref double[] tempdata)
static int bisectmethod (double pa, double ma, double pb, double mb, double a, double b, ref double x)
static void spline1dbuildmonotone (double[] x, double[] y, int n, spline1dinterpolant c)
Static Private Member Functions
static void spline1dgriddiffcubicinternal (double[] x, ref double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, ref double[] d, ref double[] a1, ref double[] a2, ref double[] a3, ref double[] b, ref double[] dt)
static void heapsortpoints (ref double[] x, ref double[] y, int n)
static void heapsortppoints (ref double[] x, ref double[] y, ref int[] p, int n)
static void solvetridiagonal (double[] a, double[] b, double[] c, double[] d, int n, ref double[] x)
static void solvecyclictridiagonal (double[] a, double[] b, double[] c, double[] d, int n, ref double[] x)
static double diffthreepoint (double t, double x0, double f0, double x1, double f1, double x2, double f2)
static void hermitecalc (double p0, double m0, double p1, double m1, double t, ref double s, ref double ds)
static double rescaleval (double a0, double b0, double a1, double b1, double t)
static void spline1dgriddiffcubicinternal (double[] x, ref double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, ref double[] d, ref double[] a1, ref double[] a2, ref double[] a3, ref double[] b, ref double[] dt)
static void heapsortpoints (ref double[] x, ref double[] y, int n)
static void heapsortppoints (ref double[] x, ref double[] y, ref int[] p, int n)
static void solvetridiagonal (double[] a, double[] b, double[] c, double[] d, int n, ref double[] x)
static void solvecyclictridiagonal (double[] a, double[] b, double[] c, double[] d, int n, ref double[] x)
static double diffthreepoint (double t, double x0, double f0, double x1, double f1, double x2, double f2)
static void hermitecalc (double p0, double m0, double p1, double m1, double t, ref double s, ref double ds)
static double rescaleval (double a0, double b0, double a1, double b1, double t)
Member Function Documentation
static void alglib.spline1d.spline1dbuildlinear (double[] x, double[] y, int n, spline1dinterpolant c) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.spline1dinterpolant.c, alglib.spline1d.spline1dinterpolant.continuity, alglib.spline1d.heapsortpoints(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dinterpolant.k, alglib.spline1d.spline1dinterpolant.n, alglib.spline1d.spline1dinterpolant.periodic, and alglib.spline1d.spline1dinterpolant.x.
Referenced by alglib.testspline1dunit.enumerateallsplines(), alglib.spline1d.spline1dbuildcatmullrom(), alglib.spline1dbuildlinear(), alglib.spline1d.spline1dlintransx(), and alglib.testspline1dunit.testspline1d().
static void alglib.spline1d.spline1dbuildcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, spline1dinterpolant c) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.spline1dinterpolant.continuity, alglib.spline1d.heapsortppoints(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dinterpolant.periodic, alglib.spline1d.spline1dbuildhermite(), and alglib.spline1d.spline1dgriddiffcubicinternal().
Referenced by alglib.testspline1dunit.enumerateallsplines(), alglib.spline1d.spline1dbuildakima(), alglib.spline1d.spline1dbuildcatmullrom(), alglib.spline1dbuildcubic(), alglib.testpsplineunit.testpspline(), alglib.testspline1dunit.testspline1d(), and alglib.testlsfitunit.testsplinefitting().
static void alglib.spline1d.spline1dgriddiffcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, ref double[] d) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortppoints(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.spline1d.spline1dgriddiffcubicinternal().
Referenced by alglib.spline1dgriddiffcubic(), and alglib.testspline1dunit.testspline1d().
static void alglib.spline1d.spline1dgriddiff2cubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, ref double[] d1, ref double[] d2) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortppoints(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dgriddiffcubicinternal(), and alglib.math.sqr().
Referenced by alglib.spline1dgriddiff2cubic(), and alglib.testspline1dunit.testspline1d().
static void alglib.spline1d.spline1dconvcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, double[] x2, int n2, ref double[] y2) inline static
References alglib.apserv.apperiodicmap(), alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortppoints(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dconvdiffinternal(), and alglib.spline1d.spline1dgriddiffcubicinternal().
Referenced by alglib.spline1dconvcubic(), and alglib.testspline1dunit.testspline1d().
static void alglib.spline1d.spline1dconvdiffcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, double[] x2, int n2, ref double[] y2, ref double[] d2) inline static
References alglib.apserv.apperiodicmap(), alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortppoints(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dconvdiffinternal(), and alglib.spline1d.spline1dgriddiffcubicinternal().
Referenced by alglib.spline1dconvdiffcubic(), and alglib.testspline1dunit.testspline1d().
static void alglib.spline1d.spline1dconvdiff2cubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, double[] x2, int n2, ref double[] y2, ref double[] d2, ref double[] dd2) inline static
References alglib.apserv.apperiodicmap(), alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortppoints(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dconvdiffinternal(), and alglib.spline1d.spline1dgriddiffcubicinternal().
Referenced by alglib.spline1dconvdiff2cubic(), and alglib.testspline1dunit.testspline1d().
static void alglib.spline1d.spline1dbuildcatmullrom (double[] x, double[] y, int n, int boundtype, double tension, spline1dinterpolant c) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortpoints(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dinterpolant.periodic, alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1dbuildhermite(), and alglib.spline1d.spline1dbuildlinear().
Referenced by alglib.spline1dbuildcatmullrom(), and alglib.testspline1dunit.testspline1d().
static void alglib.spline1d.spline1dbuildhermite (double[] x, double[] y, double[] d, int n, spline1dinterpolant c) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.spline1dinterpolant.c, alglib.spline1d.spline1dinterpolant.continuity, alglib.spline1d.heapsortdpoints(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dinterpolant.k, alglib.spline1d.spline1dinterpolant.n, alglib.spline1d.spline1dinterpolant.periodic, alglib.math.sqr(), and alglib.spline1d.spline1dinterpolant.x.
Referenced by alglib.spline1d.spline1dbuildakima(), alglib.spline1d.spline1dbuildcatmullrom(), alglib.spline1d.spline1dbuildcubic(), alglib.spline1dbuildhermite(), alglib.spline1d.spline1dbuildmonotone(), alglib.spline1d.spline1dlintransx(), alglib.testspline1dunit.testmonotonespline(), alglib.testspline1dunit.testspline1d(), alglib.testlsfitunit.testsplinefitting(), and alglib.testspline1dunit.unsetspline1d().
static void alglib.spline1d.spline1dbuildakima (double[] x, double[] y, int n, spline1dinterpolant c) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.diffthreepoint(), alglib.spline1d.heapsortpoints(), alglib.apserv.isfinitevector(), and alglib.spline1d.spline1dbuildhermite().
Referenced by alglib.spline1dbuildakima(), and alglib.testspline1dunit.testspline1d().
static double alglib.spline1d.spline1dcalc (spline1dinterpolant c, double x) inline static
References alglib.apserv.apperiodicmap(), alglib.ap.assert(), alglib.spline1d.spline1dinterpolant.c, alglib.spline1d.spline1dinterpolant.k, alglib.spline1d.spline1dinterpolant.n, alglib.spline1d.spline1dinterpolant.periodic, and alglib.spline1d.spline1dinterpolant.x.
Referenced by alglib.testspline1dunit.lconst(), alglib.spline1dcalc(), alglib.spline1d.spline1dlintransx(), alglib.testspline1dunit.testmonotonespline(), alglib.testspline1dunit.testspline1d(), alglib.testlsfitunit.testsplinefitting(), and alglib.testspline1dunit.testunpack().
static void alglib.spline1d.spline1ddiff (spline1dinterpolant c, double x, ref double s, ref double ds, ref double d2s) inline static
References alglib.apserv.apperiodicmap(), alglib.ap.assert(), alglib.spline1d.spline1dinterpolant.c, alglib.spline1d.spline1dinterpolant.k, alglib.spline1d.spline1dinterpolant.n, alglib.spline1d.spline1dinterpolant.periodic, alglib.math.sqr(), and alglib.spline1d.spline1dinterpolant.x.
Referenced by alglib.spline1ddiff(), alglib.spline1d.spline1dlintransx(), alglib.testspline1dunit.testmonotonespline(), alglib.testpsplineunit.testpspline(), alglib.testspline1dunit.testspline1d(), and alglib.testlsfitunit.testsplinefitting().
static void alglib.spline1d.spline1dcopy (spline1dinterpolant c, spline1dinterpolant cc) inline static
References alglib.spline1d.spline1dinterpolant.c, alglib.spline1d.spline1dinterpolant.continuity, alglib.spline1d.spline1dinterpolant.k, alglib.spline1d.spline1dinterpolant.n, alglib.spline1d.spline1dinterpolant.periodic, and alglib.spline1d.spline1dinterpolant.x.
Referenced by alglib.testspline1dunit.testspline1d().
static void alglib.spline1d.spline1dunpack (spline1dinterpolant c, ref int n, ref double tbl[,]) inline static
References alglib.spline1d.spline1dinterpolant.c, alglib.spline1d.spline1dinterpolant.k, alglib.spline1d.spline1dinterpolant.n, and alglib.spline1d.spline1dinterpolant.x.
Referenced by alglib.spline1dunpack(), and alglib.testspline1dunit.testunpack().
static void alglib.spline1d.spline1dlintransx (spline1dinterpolant c, double a, double b) inline static
References alglib.ap.assert(), alglib.spline1d.spline1dinterpolant.continuity, alglib.spline1d.spline1dinterpolant.k, alglib.spline1d.spline1dinterpolant.n, alglib.spline1d.spline1dinterpolant.periodic, alglib.spline1d.spline1dbuildhermite(), alglib.spline1d.spline1dbuildlinear(), alglib.spline1d.spline1dcalc(), alglib.spline1d.spline1ddiff(), and alglib.spline1d.spline1dinterpolant.x.
Referenced by alglib.spline1dlintransx(), and alglib.testspline1dunit.testspline1d().
static void alglib.spline1d.spline1dlintransy (spline1dinterpolant c, double a, double b) inline static
References alglib.ap.assert(), alglib.spline1d.spline1dinterpolant.c, alglib.spline1d.spline1dinterpolant.k, and alglib.spline1d.spline1dinterpolant.n.
Referenced by alglib.spline1dlintransy(), and alglib.testspline1dunit.testspline1d().
static double alglib.spline1d.spline1dintegrate (spline1dinterpolant c, double x) inline static
References alglib.apserv.apperiodicmap(), alglib.spline1d.spline1dinterpolant.c, alglib.spline1d.spline1dinterpolant.k, alglib.spline1d.spline1dinterpolant.n, alglib.spline1d.spline1dinterpolant.periodic, and alglib.spline1d.spline1dinterpolant.x.
Referenced by alglib.spline1dintegrate(), and alglib.testspline1dunit.testspline1d().
static void alglib.spline1d.spline1dconvdiffinternal (double[] xold, double[] yold, double[] dold, int n, double[] x2, int n2, ref double[] y, bool needy, ref double[] d1, bool needd1, ref double[] d2, bool needd2) inline static
Referenced by alglib.spline1d.spline1dconvcubic(), alglib.spline1d.spline1dconvdiff2cubic(), and alglib.spline1d.spline1dconvdiffcubic().
static void alglib.spline1d.spline1drootsandextrema (spline1dinterpolant c, ref double[] r, ref int nr, ref bool dr, ref double[] e, ref int[] et, ref int ne, ref bool de) inline static
References alglib.ap.assert(), alglib.spline1d.spline1dinterpolant.c, alglib.spline1d.spline1dinterpolant.continuity, alglib.apserv.ivectorsetlengthatleast(), alglib.spline1d.spline1dinterpolant.k, alglib.spline1d.spline1dinterpolant.n, alglib.apserv.rvectorsetlengthatleast(), alglib.spline1d.solvecubicpolinom(), and alglib.spline1d.spline1dinterpolant.x.
static void alglib.spline1d.heapsortdpoints (ref double[] x, ref double[] y, ref double[] d, int n) inline static
References alglib.tsort.tagsortfasti().
Referenced by alglib.spline1d.spline1dbuildhermite().
static void alglib.spline1d.solvepolinom2 (double p0, double m0, double p1, double m1, ref double x0, ref double x1, ref int nr) inline static
Referenced by alglib.spline1d.solvecubicpolinom().
static void alglib.spline1d.solvecubicpolinom (double pa, double ma, double pb, double mb, double a, double b, ref double x0, ref double x1, ref double x2, ref double ex0, ref double ex1, ref int nr, ref int ne, ref double[] tempdata) inline static
References alglib.ap.assert(), alglib.spline1d.bisectmethod(), alglib.spline1d.rescaleval(), alglib.apserv.rvectorsetlengthatleast(), and alglib.spline1d.solvepolinom2().
Referenced by alglib.spline1d.spline1drootsandextrema().
static int alglib.spline1d.bisectmethod (double pa, double ma, double pb, double mb, double a, double b, ref double x) inline static
References alglib.spline1d.hermitecalc(), and alglib.math.machineepsilon.
Referenced by alglib.spline1d.solvecubicpolinom().
static void alglib.spline1d.spline1dbuildmonotone (double[] x, double[] y, int n, spline1dinterpolant c) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.beta(), alglib.spline1d.spline1dinterpolant.continuity, alglib.spline1d.heapsortppoints(), alglib.apserv.isfinitevector(), alglib.math.machineepsilon, alglib.spline1d.spline1dbuildhermite(), and alglib.math.sqr().
Referenced by alglib.spline1dbuildmonotone(), and alglib.testspline1dunit.testmonotonespline().
static void alglib.spline1d.spline1dgriddiffcubicinternal (double[] x, ref double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, ref double[] d, ref double[] a1, ref double[] a2, ref double[] a3, ref double[] b, ref double[] dt) inline static private
References alglib.spline1d.solvecyclictridiagonal(), and alglib.spline1d.solvetridiagonal().
Referenced by alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1dconvcubic(), alglib.spline1d.spline1dconvdiff2cubic(), alglib.spline1d.spline1dconvdiffcubic(), alglib.spline1d.spline1dgriddiff2cubic(), and alglib.spline1d.spline1dgriddiffcubic().
static void alglib.spline1d.heapsortpoints (ref double[] x, ref double[] y, int n) inline static private
References alglib.tsort.tagsortfastr().
Referenced by alglib.spline1d.spline1dbuildakima(), alglib.spline1d.spline1dbuildcatmullrom(), and alglib.spline1d.spline1dbuildlinear().
static void alglib.spline1d.heapsortppoints (ref double[] x, ref double[] y, ref int[] p, int n) inline static private
References alglib.tsort.tagsortfasti().
Referenced by alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1dbuildmonotone(), alglib.spline1d.spline1dconvcubic(), alglib.spline1d.spline1dconvdiff2cubic(), alglib.spline1d.spline1dconvdiffcubic(), alglib.spline1d.spline1dgriddiff2cubic(), and alglib.spline1d.spline1dgriddiffcubic().
static void alglib.spline1d.solvetridiagonal (double[] a, double[] b, double[] c, double[] d, int n, ref double[] x) inline static private
Referenced by alglib.spline1d.solvecyclictridiagonal(), and alglib.spline1d.spline1dgriddiffcubicinternal().
static void alglib.spline1d.solvecyclictridiagonal (double[] a, double[] b, double[] c, double[] d, int n, ref double[] x) inline static private
References alglib.beta(), and alglib.spline1d.solvetridiagonal().
Referenced by alglib.spline1d.spline1dgriddiffcubicinternal().
static double alglib.spline1d.diffthreepoint (double t, double x0, double f0, double x1, double f1, double x2, double f2) inline static private
References alglib.math.sqr().
Referenced by alglib.spline1d.spline1dbuildakima().
static void alglib.spline1d.hermitecalc (double p0, double m0, double p1, double m1, double t, ref double s, ref double ds) inline static private
Referenced by alglib.spline1d.bisectmethod().
static double alglib.spline1d.rescaleval (double a0, double b0, double a1, double b1, double t) inline static private
Referenced by alglib.spline1d.solvecubicpolinom().
static void alglib.spline1d.spline1dbuildlinear (double[] x, double[] y, int n, spline1dinterpolant c) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortpoints(), and alglib.apserv.isfinitevector().
static void alglib.spline1d.spline1dbuildcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, spline1dinterpolant c) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortppoints(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dbuildhermite(), and alglib.spline1d.spline1dgriddiffcubicinternal().
static void alglib.spline1d.spline1dgriddiffcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, ref double[] d) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortppoints(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.spline1d.spline1dgriddiffcubicinternal().
static void alglib.spline1d.spline1dgriddiff2cubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, ref double[] d1, ref double[] d2) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortppoints(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dgriddiffcubicinternal(), and alglib.math.sqr().
static void alglib.spline1d.spline1dconvcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, double[] x2, int n2, ref double[] y2) inline static
References alglib.apserv.apperiodicmap(), alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortppoints(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dconvdiffinternal(), and alglib.spline1d.spline1dgriddiffcubicinternal().
static void alglib.spline1d.spline1dconvdiffcubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, double[] x2, int n2, ref double[] y2, ref double[] d2) inline static
References alglib.apserv.apperiodicmap(), alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortppoints(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dconvdiffinternal(), and alglib.spline1d.spline1dgriddiffcubicinternal().
static void alglib.spline1d.spline1dconvdiff2cubic (double[] x, double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, double[] x2, int n2, ref double[] y2, ref double[] d2, ref double[] dd2) inline static
References alglib.apserv.apperiodicmap(), alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortppoints(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dconvdiffinternal(), and alglib.spline1d.spline1dgriddiffcubicinternal().
static void alglib.spline1d.spline1dbuildcatmullrom (double[] x, double[] y, int n, int boundtype, double tension, spline1dinterpolant c) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortpoints(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1dbuildhermite(), and alglib.spline1d.spline1dbuildlinear().
static void alglib.spline1d.spline1dbuildhermite (double[] x, double[] y, double[] d, int n, spline1dinterpolant c) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.heapsortdpoints(), alglib.apserv.isfinitevector(), and alglib.math.sqr().
static void alglib.spline1d.spline1dbuildakima (double[] x, double[] y, int n, spline1dinterpolant c) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.diffthreepoint(), alglib.spline1d.heapsortpoints(), alglib.apserv.isfinitevector(), alglib.spline1d.spline1dbuildcubic(), and alglib.spline1d.spline1dbuildhermite().
static double alglib.spline1d.spline1dcalc (spline1dinterpolant c, double x) inline static
References alglib.apserv.apperiodicmap(), and alglib.ap.assert().
static void alglib.spline1d.spline1ddiff (spline1dinterpolant c, double x, ref double s, ref double ds, ref double d2s) inline static
References alglib.apserv.apperiodicmap(), alglib.ap.assert(), and alglib.math.sqr().
static void alglib.spline1d.spline1dcopy (spline1dinterpolant c, spline1dinterpolant cc) inline static
static void alglib.spline1d.spline1dunpack (spline1dinterpolant c, ref int n, ref double tbl[,]) inline static
static void alglib.spline1d.spline1dlintransx (spline1dinterpolant c, double a, double b) inline static
References alglib.ap.assert(), alglib.spline1d.spline1dbuildhermite(), alglib.spline1d.spline1dbuildlinear(), alglib.spline1d.spline1dcalc(), and alglib.spline1d.spline1ddiff().
static void alglib.spline1d.spline1dlintransy (spline1dinterpolant c, double a, double b) inline static
References alglib.ap.assert().
static double alglib.spline1d.spline1dintegrate (spline1dinterpolant c, double x) inline static
References alglib.apserv.apperiodicmap().
static void alglib.spline1d.spline1dconvdiffinternal (double[] xold, double[] yold, double[] dold, int n, double[] x2, int n2, ref double[] y, bool needy, ref double[] d1, bool needd1, ref double[] d2, bool needd2) inline static
static void alglib.spline1d.spline1drootsandextrema (spline1dinterpolant c, ref double[] r, ref int nr, ref bool dr, ref double[] e, ref int[] et, ref int ne, ref bool de) inline static
References alglib.ap.assert(), alglib.apserv.ivectorsetlengthatleast(), alglib.apserv.rvectorsetlengthatleast(), and alglib.spline1d.solvecubicpolinom().
static void alglib.spline1d.heapsortdpoints (ref double[] x, ref double[] y, ref double[] d, int n) inline static
References alglib.tsort.tagsortfasti().
static void alglib.spline1d.solvepolinom2 (double p0, double m0, double p1, double m1, ref double x0, ref double x1, ref int nr) inline static
static void alglib.spline1d.solvecubicpolinom (double pa, double ma, double pb, double mb, double a, double b, ref double x0, ref double x1, ref double x2, ref double ex0, ref double ex1, ref int nr, ref int ne, ref double[] tempdata) inline static
References alglib.ap.assert(), alglib.spline1d.bisectmethod(), alglib.spline1d.rescaleval(), alglib.apserv.rvectorsetlengthatleast(), and alglib.spline1d.solvepolinom2().
static int alglib.spline1d.bisectmethod (double pa, double ma, double pb, double mb, double a, double b, ref double x) inline static
References alglib.spline1d.hermitecalc(), and alglib.math.machineepsilon.
static void alglib.spline1d.spline1dbuildmonotone (double[] x, double[] y, int n, spline1dinterpolant c) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.beta(), alglib.spline1d.heapsortppoints(), alglib.apserv.isfinitevector(), alglib.math.machineepsilon, alglib.spline1d.spline1dbuildhermite(), and alglib.math.sqr().
static void alglib.spline1d.spline1dgriddiffcubicinternal (double[] x, ref double[] y, int n, int boundltype, double boundl, int boundrtype, double boundr, ref double[] d, ref double[] a1, ref double[] a2, ref double[] a3, ref double[] b, ref double[] dt) inline static private
References alglib.spline1d.solvecyclictridiagonal(), and alglib.spline1d.solvetridiagonal().
static void alglib.spline1d.heapsortpoints (ref double[] x, ref double[] y, int n) inline static private
References alglib.tsort.tagsortfastr().
static void alglib.spline1d.heapsortppoints (ref double[] x, ref double[] y, ref int[] p, int n) inline static private
References alglib.tsort.tagsortfasti().
static void alglib.spline1d.solvetridiagonal (double[] a, double[] b, double[] c, double[] d, int n, ref double[] x) inline static private
static void alglib.spline1d.solvecyclictridiagonal (double[] a, double[] b, double[] c, double[] d, int n, ref double[] x) inline static private
References alglib.beta(), and alglib.spline1d.solvetridiagonal().
static double alglib.spline1d.diffthreepoint (double t, double x0, double f0, double x1, double f1, double x2, double f2) inline static private
References alglib.math.sqr().
static void alglib.spline1d.hermitecalc (double p0, double m0, double p1, double m1, double t, ref double s, ref double ds) inline static private
static double alglib.spline1d.rescaleval (double a0, double b0, double a1, double b1, double t) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/interpolation.cs