IGLib: NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests Class Reference
NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests Class Reference
Public Member Functions
void SetUp ()
void TearDown ()
void PassesWhenFileInfoExists ()
void PassesWhenDirectoryInfoExists ()
void PassesWhenFileStringExists ()
void PassesWhenDirectoryStringExists ()
void FailsWhenIgnoreFilesIsTrueWithFileString ()
void FailsWhenIgnoreFilesIsTrueWithFileInfo ()
void FailsWhenIgnoreDirectoriesIsTrueWithDirectoryString ()
void FailsWhenIgnoreDirectoriesIsTrueWithDirectoryInfo ()
void FailsWhenDirectoryInfoDoesNotExist ()
void FailsWhenFileInfoDoesNotExist ()
void FailsWhenFileStringDoesNotExist ()
void FailsWhenDirectoryStringDoesNotExist ()
void FailsWhenNotStringOrDirectoryInfo ()
void FailsWhenFileInfoIsNull ()
void FailsWhenDirectoryInfoIsNull ()
void FailsWhenStringIsNull ()
void FailsWhenStringIsEmpty ()
Private Attributes
FileOrDirectoryExistsConstraint _constraint
TestDirectory _goodDir
const string TEST_FILE = "Test1.txt"
const string RESOURCE_FILE = "TestText1.txt"
Static Private Attributes
static readonly string BAD_DIRECTORY = Path.Combine(Path.GetTempPath(), @"\I\hope\this\is\garbage")
static readonly string BAD_FILE = Path.Combine(Path.GetTempPath(), "garbage.txt")
Member Function Documentation
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.SetUp () inline
References NUnit.Framework.Constraints.ConstraintExpression.Exist, NUnit.Framework.Does.Not, and NUnit.Framework.Assume.That().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.TearDown () inline
References NUnit.TestUtilities.TestDirectory.Dispose().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.PassesWhenFileInfoExists () inline
References NUnit.Framework.Does.Exist, and NUnit.Framework.Assert.That().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.PassesWhenDirectoryInfoExists () inline
References NUnit.TestUtilities.TestDirectory.Directory, NUnit.Framework.Does.Exist, and NUnit.Framework.Assert.That().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.PassesWhenFileStringExists () inline
References NUnit.Framework.Does.Exist, and NUnit.Framework.Assert.That().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.PassesWhenDirectoryStringExists () inline
References NUnit.Framework.Does.Exist, NUnit.Framework.Assert.That(), and NUnit.TestUtilities.TestDirectory.ToString().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenIgnoreFilesIsTrueWithFileString () inline
References NUnit.Framework.Constraints.FileOrDirectoryExistsConstraint.IgnoreFiles, and NUnit.Framework.Assert.That().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenIgnoreFilesIsTrueWithFileInfo () inline
References NUnit.Framework.Constraints.FileOrDirectoryExistsConstraint.IgnoreFiles, NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenIgnoreDirectoriesIsTrueWithDirectoryString () inline
References NUnit.Framework.Constraints.FileOrDirectoryExistsConstraint.IgnoreDirectories, NUnit.Framework.Assert.That(), and NUnit.TestUtilities.TestDirectory.ToString().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenIgnoreDirectoriesIsTrueWithDirectoryInfo () inline
References NUnit.TestUtilities.TestDirectory.Directory, NUnit.Framework.Constraints.FileOrDirectoryExistsConstraint.IgnoreDirectories, NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenDirectoryInfoDoesNotExist () inline
References NUnit.Framework.Constraints.ConstraintExpression.Exist, NUnit.Framework.Does.Not, and NUnit.Framework.Assert.That().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenFileInfoDoesNotExist () inline
References NUnit.Framework.Constraints.ConstraintExpression.Exist, NUnit.Framework.Does.Not, and NUnit.Framework.Assert.That().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenFileStringDoesNotExist () inline
References NUnit.Framework.Constraints.ConstraintExpression.Exist, NUnit.Framework.Does.Not, and NUnit.Framework.Assert.That().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenDirectoryStringDoesNotExist () inline
References NUnit.Framework.Constraints.ConstraintExpression.Exist, NUnit.Framework.Does.Not, and NUnit.Framework.Assert.That().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenNotStringOrDirectoryInfo () inline
References NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenFileInfoIsNull () inline
References NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenDirectoryInfoIsNull () inline
References NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenStringIsNull () inline
References NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenStringIsEmpty () inline
References NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
Member Data Documentation
FileOrDirectoryExistsConstraint NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests._constraint private
TestDirectory NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests._goodDir private
readonly string NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.BAD_DIRECTORY = Path.Combine(Path.GetTempPath(), @"\I\hope\this\is\garbage") static private
readonly string NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.BAD_FILE = Path.Combine(Path.GetTempPath(), "garbage.txt") static private
const string NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.TEST_FILE = "Test1.txt" private
const string NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.RESOURCE_FILE = "TestText1.txt" private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/FileOrDirectoryExistsConstraintTests.cs