IGLib: alglib.spdgevd Class Reference
alglib.spdgevd Class Reference
Static Public Member Functions
static bool smatrixgevd (double[,] a, int n, bool isuppera, double[,] b, bool isupperb, int zneeded, int problemtype, ref double[] d, ref double[,] z)
static bool smatrixgevdreduce (ref double[,] a, int n, bool isuppera, double[,] b, bool isupperb, int problemtype, ref double[,] r, ref bool isupperr)
static bool smatrixgevd (double[,] a, int n, bool isuppera, double[,] b, bool isupperb, int zneeded, int problemtype, ref double[] d, ref double[,] z)
static bool smatrixgevdreduce (ref double[,] a, int n, bool isuppera, double[,] b, bool isupperb, int problemtype, ref double[,] r, ref bool isupperr)
Member Function Documentation
static bool alglib.spdgevd.smatrixgevd (double a[,], int n, bool isuppera, double b[,], bool isupperb, int zneeded, int problemtype, ref double[] d, ref double z[,]) inline static
Referenced by alglib.smatrixgevd(), and alglib.testspdgevdunit.testspdgevd().
static bool alglib.spdgevd.smatrixgevdreduce (ref double a[,], int n, bool isuppera, double b[,], bool isupperb, int problemtype, ref double r[,], ref bool isupperr) inline static
Referenced by alglib.smatrixgevdreduce().
static bool alglib.spdgevd.smatrixgevd (double a[,], int n, bool isuppera, double b[,], bool isupperb, int zneeded, int problemtype, ref double[] d, ref double z[,]) inline static
static bool alglib.spdgevd.smatrixgevdreduce (ref double a[,], int n, bool isuppera, double b[,], bool isupperb, int problemtype, ref double r[,], ref bool isupperr) inline static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/linalg.cs