IGLib: NUnit.Framework.Attributes.RangeAttributeTests Class Reference
NUnit.Framework.Attributes.RangeAttributeTests Class Reference
Public Member Functions
void IntRange ()
void IntRange_Reversed ()
void IntRange_FromEqualsTo ()
void IntRangeAndStep ()
void IntRangeAndZeroStep ()
void IntRangeAndStep_Reversed ()
void IntRangeAndNegativeStep ()
void IntRangeAndNegativeStep_Reversed ()
void UintRange ()
void UintRange_Reversed ()
void UintRange_FromEqualsTo ()
void UintRangeAndStep ()
void UintRangeAndZeroStep ()
void UintRangeAndStep_Reversed ()
void LongRange ()
void LongRange_Reversed ()
void LongRange_FromEqualsTo ()
void LongRangeAndStep ()
void LongRangeAndZeroStep ()
void LongRangeAndStep_Reversed ()
void LongRangeAndNegativeStep ()
void LongRangeAndNegativeStep_Reversed ()
void UlongRange ()
void UlongRange_Reversed ()
void UlongRange_FromEqualsTo ()
void UlongRangeAndStep ()
void UlongRangeAndZeroStep ()
void UlongRangeAndStep_Reversed ()
void DoubleRangeAndStep ()
void DoubleRangeAndZeroStep ()
void DoubleRangeAndStep_Reversed ()
void DoubleRangeAndNegativeStep ()
void DoubleRangeAndNegativeStep_Reversed ()
void FloatRangeAndStep ()
void FloatRangeAndZeroStep ()
void FloatRangeAndStep_Reversed ()
void FloatRangeAndNegativeStep ()
void FloatRangeAndNegativeStep_Reversed ()
void CanConvertIntRangeToShort ()
void CanConvertIntRangeToByte ()
void CanConvertIntRangeToSByte ()
void CanConvertIntRangeToDecimal ()
void CanConvertDoubleRangeToDecimal ()
Private Member Functions
void MethodWithIntRange ([Range(11, 15)] int x)
void MethodWithIntRange_Reversed ([Range(15, 11)] int x)
void MethodWithIntRange_FromEqualsTo ([Range(11, 11)] int x)
void MethodWithIntRangeAndStep ([Range(11, 15, 2)] int x)
void MethodWithIntRangeAndZeroStep ([Range(11, 15, 0)] int x)
void MethodWithIntRangeAndStep_Reversed ([Range(15, 11, 2)] int x)
void MethodWithIntRangeAndNegativeStep ([Range(11, 15,-2)] int x)
void MethodWithIntRangeAndNegativeStep_Reversed ([Range(15, 11,-2)] int x)
void MethodWithUintRange ([Range(11u, 15u)] uint x)
void MethodWithUintRange_Reversed ([Range(15u, 11u)] uint x)
void MethodWithUintRange_FromEqualsTo ([Range(11u, 11u)] uint x)
void MethodWithUintRangeAndStep ([Range(11u, 15u, 2u)] uint x)
void MethodWithUintRangeAndZeroStep ([Range(11u, 15u, 0u)] uint x)
void MethodWithUintRangeAndStep_Reversed ([Range(15u, 11u, 2u)] uint x)
void MethodWithLongRange ([Range(11L, 15L)] long x)
void MethodWithLongRange_Reversed ([Range(15L, 11L)] long x)
void MethodWithLongRange_FromEqualsTo ([Range(11L, 11L)] long x)
void MethodWithLongRangeAndStep ([Range(11L, 15L, 2)] long x)
void MethodWithLongRangeAndZeroStep ([Range(11L, 15L, 0L)] long x)
void MethodWithLongRangeAndStep_Reversed ([Range(15L, 11L, 2L)] long x)
void MethodWithLongRangeAndNegativeStep ([Range(11L, 15L,-2L)] long x)
void MethodWithLongRangeAndNegativeStep_Reversed ([Range(15L, 11L,-2L)] long x)
void MethodWithUlongRange ([Range(11ul, 15ul)] ulong x)
void MethodWithUlongRange_Reversed ([Range(15ul, 11ul)] ulong x)
void MethodWithUlongRange_FromEqualsTo ([Range(11ul, 11ul)] ulong x)
void MethodWithUlongRangeAndStep ([Range(11ul, 15ul, 2ul)] ulong x)
void MethodWithUlongRangeAndZeroStep ([Range(11ul, 15ul, 0ul)] ulong x)
void MethodWithUlongRangeAndStep_Reversed ([Range(15ul, 11ul, 2ul)] ulong x)
void MethodWithDoubleRangeAndStep ([Range(0.7, 1.2, 0.2)] double x)
void MethodWithDoubleRangeAndZeroStep ([Range(0.7, 1.2, 0.0)] double x)
void MethodWithDoubleRangeAndStep_Reversed ([Range(1.2, 0.7, 0.2)] double x)
void MethodWithDoubleRangeAndNegativeStep ([Range(0.7, 1.2,-0.2)] double x)
void MethodWithDoubleRangeAndNegativeStep_Reversed ([Range(1.2, 0.7,-0.2)] double x)
void MethodWithFloatRangeAndStep ([Range(0.7f, 1.2f, 0.2f)] float x)
void MethodWithFloatRangeAndZeroStep ([Range(0.7f, 1.2f, 0.0f)] float x)
void MethodWithFloatRangeAndStep_Reversed ([Range(1.2f, 0.7, 0.2f)] float x)
void MethodWithFloatRangeAndNegativeStep ([Range(0.7f, 1.2f,-0.2f)] float x)
void MethodWithFloatRangeAndNegativeStep_Reversed ([Range(1.2f, 0.7,-0.2f)] float x)
void MethodWithIntRangeAndShortArgument ([Range(1, 3)] short x)
void MethodWithIntRangeAndByteArgument ([Range(1, 3)] byte x)
void MethodWithIntRangeAndSByteArgument ([Range(1, 3)] sbyte x)
void MethodWithIntRangeAndDecimalArgument ([Range(1, 3)] decimal x)
void MethodWithDoubleRangeAndDecimalArgument ([Range(1.0, 1.21, 0.1)] decimal x)
void CheckValues (string methodName, params object[] expected)
void CheckValuesWithinTolerance (string methodName, params object[] expected)
Member Function Documentation
void NUnit.Framework.Attributes.RangeAttributeTests.IntRange () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithIntRange ([Range(11, 15)] int x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.IntRange_Reversed () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithIntRange_Reversed ([Range(15, 11)] int x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.IntRange_FromEqualsTo () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithIntRange_FromEqualsTo ([Range(11, 11)] int x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.IntRangeAndStep () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithIntRangeAndStep ([Range(11, 15, 2)] int x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.IntRangeAndZeroStep () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithIntRangeAndZeroStep ([Range(11, 15, 0)] int x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.IntRangeAndStep_Reversed () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithIntRangeAndStep_Reversed ([Range(15, 11, 2)] int x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.IntRangeAndNegativeStep () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithIntRangeAndNegativeStep ([Range(11, 15, -2)] int x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.IntRangeAndNegativeStep_Reversed () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithIntRangeAndNegativeStep_Reversed ([Range(15, 11, -2)] int x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.UintRange () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithUintRange ([Range(11u, 15u)] uint x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.UintRange_Reversed () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithUintRange_Reversed ([Range(15u, 11u)] uint x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.UintRange_FromEqualsTo () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithUintRange_FromEqualsTo ([Range(11u, 11u)] uint x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.UintRangeAndStep () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithUintRangeAndStep ([Range(11u, 15u, 2u)] uint x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.UintRangeAndZeroStep () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithUintRangeAndZeroStep ([Range(11u, 15u, 0u)] uint x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.UintRangeAndStep_Reversed () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithUintRangeAndStep_Reversed ([Range(15u, 11u, 2u)] uint x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.LongRange () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithLongRange ([Range(11L, 15L)] long x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.LongRange_Reversed () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithLongRange_Reversed ([Range(15L, 11L)] long x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.LongRange_FromEqualsTo () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithLongRange_FromEqualsTo ([Range(11L, 11L)] long x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.LongRangeAndStep () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithLongRangeAndStep ([Range(11L, 15L, 2)] long x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.LongRangeAndZeroStep () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithLongRangeAndZeroStep ([Range(11L, 15L, 0L)] long x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.LongRangeAndStep_Reversed () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithLongRangeAndStep_Reversed ([Range(15L, 11L, 2L)] long x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.LongRangeAndNegativeStep () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithLongRangeAndNegativeStep ([Range(11L, 15L, -2L)] long x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.LongRangeAndNegativeStep_Reversed () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithLongRangeAndNegativeStep_Reversed ([Range(15L, 11L, -2L)] long x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.UlongRange () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithUlongRange ([Range(11ul, 15ul)] ulong x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.UlongRange_Reversed () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithUlongRange_Reversed ([Range(15ul, 11ul)] ulong x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.UlongRange_FromEqualsTo () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithUlongRange_FromEqualsTo ([Range(11ul, 11ul)] ulong x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.UlongRangeAndStep () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithUlongRangeAndStep ([Range(11ul, 15ul, 2ul)] ulong x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.UlongRangeAndZeroStep () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithUlongRangeAndZeroStep ([Range(11ul, 15ul, 0ul)] ulong x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.UlongRangeAndStep_Reversed () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithUlongRangeAndStep_Reversed ([Range(15ul, 11ul, 2ul)] ulong x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.DoubleRangeAndStep () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithDoubleRangeAndStep ([Range(0.7, 1.2, 0.2)] double x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.DoubleRangeAndZeroStep () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithDoubleRangeAndZeroStep ([Range(0.7, 1.2, 0.0)] double x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.DoubleRangeAndStep_Reversed () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithDoubleRangeAndStep_Reversed ([Range(1.2, 0.7, 0.2)] double x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.DoubleRangeAndNegativeStep () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithDoubleRangeAndNegativeStep ([Range(0.7, 1.2, -0.2)] double x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.DoubleRangeAndNegativeStep_Reversed () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithDoubleRangeAndNegativeStep_Reversed ([Range(1.2, 0.7, -0.2)] double x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.FloatRangeAndStep () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithFloatRangeAndStep ([Range(0.7f, 1.2f, 0.2f)] float x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.FloatRangeAndZeroStep () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithFloatRangeAndZeroStep ([Range(0.7f, 1.2f, 0.0f)] float x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.FloatRangeAndStep_Reversed () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithFloatRangeAndStep_Reversed ([Range(1.2f, 0.7, 0.2f)] float x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.FloatRangeAndNegativeStep () inline
References NUnit.Framework.Assert.Throws().
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithFloatRangeAndNegativeStep ([Range(0.7f, 1.2f, -0.2f)] float x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.FloatRangeAndNegativeStep_Reversed () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithFloatRangeAndNegativeStep_Reversed ([Range(1.2f, 0.7, -0.2f)] float x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.CanConvertIntRangeToShort () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithIntRangeAndShortArgument ([Range(1, 3)] short x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.CanConvertIntRangeToByte () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithIntRangeAndByteArgument ([Range(1, 3)] byte x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.CanConvertIntRangeToSByte () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithIntRangeAndSByteArgument ([Range(1, 3)] sbyte x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.CanConvertIntRangeToDecimal () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithIntRangeAndDecimalArgument ([Range(1, 3)] decimal x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.CanConvertDoubleRangeToDecimal () inline
void NUnit.Framework.Attributes.RangeAttributeTests.MethodWithDoubleRangeAndDecimalArgument ([Range(1.0, 1.21, 0.1)] decimal x) inline private
void NUnit.Framework.Attributes.RangeAttributeTests.CheckValues (string methodName, params object[] expected) inline private
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.RangeAttributeTests.CheckValuesWithinTolerance (string methodName, params object[] expected) inline private
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/RangeAttributeTests.cs