IGLib: NUnit.Framework.Assertions.EqualsFixture Class Reference
NUnit.Framework.Assertions.EqualsFixture Class Reference
Public Member Functions
void Equals ()
void EqualsNull ()
void Bug575936Int32Int64Comparison ()
void Bug524CharIntComparision ()
void Bug524CharIntWithoutOverload ()
void CharCharComparision ()
void IntegerLongComparison ()
void IntegerEquals ()
void EqualsFail ()
void EqualsNaNFails ()
void NanEqualsFails ()
void NanEqualsNaNSucceeds ()
void NegInfinityEqualsInfinity ()
void PosInfinityEqualsInfinity ()
void PosInfinityNotEquals ()
void PosInfinityNotEqualsNegInfinity ()
void SinglePosInfinityNotEqualsNegInfinity ()
void EqualsThrowsException ()
void ReferenceEqualsThrowsException ()
void Float ()
void Byte ()
void String ()
void Short ()
void Int ()
void UInt ()
void Decimal ()
void EqualsSameTypes ()
Checks to see that a value comparison works with all types. Current version has problems when value is the same but the types are different...C# is not like Java, and doesn't automatically perform value type conversion to simplify this type of comparison.
void EnumsEqual ()
void EnumsNotEqual ()
void DateTimeEqual ()
void DateTimeNotEqual ()
void DirectoryInfoEqual ()
void DirectoryInfoNotEqual ()
void DoubleNotEqualMessageDisplaysAllDigits ()
void FloatNotEqualMessageDisplaysAllDigits ()
void DoubleNotEqualMessageDisplaysTolerance ()
void FloatNotEqualMessageDisplaysTolerance ()
void DoubleNotEqualMessageDisplaysDefaultTolerance ()
void DoubleNotEqualWithNanDoesNotDisplayDefaultTolerance ()
void IEquatableSuccess_OldSyntax ()
void IEquatableSuccess_ConstraintSyntax ()
Private Types
enum MyEnum { MyEnum.a, MyEnum.b, MyEnum.c }
Member Enumeration Documentation
enum NUnit.Framework.Assertions.EqualsFixture.MyEnum private
Enumerator
a
b
c
Member Function Documentation
void NUnit.Framework.Assertions.EqualsFixture.Equals () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.IsTrue().
void NUnit.Framework.Assertions.EqualsFixture.EqualsNull () inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Assertions.EqualsFixture.Bug575936Int32Int64Comparison () inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Assertions.EqualsFixture.Bug524CharIntComparision () inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Assertions.EqualsFixture.Bug524CharIntWithoutOverload () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.EqualsFixture.CharCharComparision () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.EqualsFixture.IntegerLongComparison () inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Assertions.EqualsFixture.IntegerEquals () inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Assertions.EqualsFixture.EqualsFail () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.EqualsFixture.EqualsNaNFails () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.EqualsFixture.NanEqualsFails () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.EqualsFixture.NanEqualsNaNSucceeds () inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Assertions.EqualsFixture.NegInfinityEqualsInfinity () inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Assertions.EqualsFixture.PosInfinityEqualsInfinity () inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Assertions.EqualsFixture.PosInfinityNotEquals () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.EqualsFixture.PosInfinityNotEqualsNegInfinity () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.EqualsFixture.SinglePosInfinityNotEqualsNegInfinity () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.EqualsFixture.EqualsThrowsException () inline
References NUnit.Framework.Assert.Equals(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.EqualsFixture.ReferenceEqualsThrowsException () inline
References NUnit.Framework.Assert.ReferenceEquals(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.EqualsFixture.Float () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.IsTrue().
void NUnit.Framework.Assertions.EqualsFixture.Byte () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.IsTrue().
void NUnit.Framework.Assertions.EqualsFixture.String () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.IsTrue().
void NUnit.Framework.Assertions.EqualsFixture.Short () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.IsTrue().
void NUnit.Framework.Assertions.EqualsFixture.Int () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.IsTrue().
void NUnit.Framework.Assertions.EqualsFixture.UInt () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.IsTrue().
void NUnit.Framework.Assertions.EqualsFixture.Decimal () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.IsTrue().
void NUnit.Framework.Assertions.EqualsFixture.EqualsSameTypes () inline
Checks to see that a value comparison works with all types. Current version has problems when value is the same but the types are different...C# is not like Java, and doesn't automatically perform value type conversion to simplify this type of comparison.
Related to Bug575936Int32Int64Comparison, but covers all numeric types.
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Assertions.EqualsFixture.EnumsEqual () inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Assertions.EqualsFixture.EnumsNotEqual () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.EqualsFixture.DateTimeEqual () inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Assertions.EqualsFixture.DateTimeNotEqual () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.EqualsFixture.DirectoryInfoEqual () inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Assertions.EqualsFixture.DirectoryInfoNotEqual () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualMessageDisplaysAllDigits () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.AreNotEqual(), and NUnit.Framework.Assert.Fail().
void NUnit.Framework.Assertions.EqualsFixture.FloatNotEqualMessageDisplaysAllDigits () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.AreNotEqual(), and NUnit.Framework.Assert.Fail().
void NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualMessageDisplaysTolerance () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.Fail(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.EqualsFixture.FloatNotEqualMessageDisplaysTolerance () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.Fail(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualMessageDisplaysDefaultTolerance () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Does.Contain(), NUnit.Framework.GlobalSettings.DefaultFloatingPointTolerance, NUnit.Framework.Assert.Fail(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.EqualsFixture.DoubleNotEqualWithNanDoesNotDisplayDefaultTolerance () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.GlobalSettings.DefaultFloatingPointTolerance, NUnit.Framework.Assert.Fail(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Assertions.EqualsFixture.IEquatableSuccess_OldSyntax () inline
References NUnit.Framework.Assert.AreEqual().
void NUnit.Framework.Assertions.EqualsFixture.IEquatableSuccess_ConstraintSyntax () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/AssertEqualsTests.cs