IGLib: IPLab.FilterPreview Class Reference
IPLab.FilterPreview Class Reference
FilterPreview window
Public Member Functions
FilterPreview ()
void RefreshFilter ()
Protected Member Functions
override void Dispose (bool disposing)
override void OnPaint (PaintEventArgs pe)
Properties
Bitmap Image [get, set]
AForge.Imaging.Filters.IFilter Filter [set]
Private Member Functions
void InitializeComponent ()
void FilterPreview_MouseMove (object sender, System.Windows.Forms.MouseEventArgs e)
void FilterPreview_MouseDown (object sender, System.Windows.Forms.MouseEventArgs e)
void FilterPreview_MouseUp (object sender, System.Windows.Forms.MouseEventArgs e)
Private Attributes
Bitmap previewImage
Bitmap image
IFilter filter
Pen blackPen = new Pen(Color.Black, 1)
Cursor cursorHand
Cursor cursorHandMove
int areaWidth
int areaHeight
int imageX
int imageY
bool tracking = false
int startTrackingX
int startTrackingY
int oldImageX
int oldImageY
Detailed Description
FilterPreview window
Constructor & Destructor Documentation
IPLab.FilterPreview.FilterPreview () inline
References IPLab.FilterPreview.InitializeComponent().
Member Function Documentation
override void IPLab.FilterPreview.Dispose (bool disposing) inline protected
void IPLab.FilterPreview.InitializeComponent () inline private
References IPLab.FilterPreview.FilterPreview_MouseDown(), IPLab.FilterPreview.FilterPreview_MouseMove(), and IPLab.FilterPreview.FilterPreview_MouseUp().
Referenced by IPLab.FilterPreview.FilterPreview().
override void IPLab.FilterPreview.OnPaint (PaintEventArgs pe) inline protected
void IPLab.FilterPreview.RefreshFilter () inline
Referenced by IPLab.ChannelFilteringForm.blueFillTypeCombo_SelectedIndexChanged(), IPLab.BrightnessForm.brightnessBox_TextChanged(), IPLab.BilateralForm.colorFactorUpDown_ValueChanged(), IPLab.BilateralForm.colorPowerUpDown_ValueChanged(), IPLab.ContrastForm.contrastBox_TextChanged(), IPLab.SusanCornersDetectorForm.diffThresholdTrackBar_ValueChanged(), IPLab.AdaptiveSmoothForm.factorBox_TextChanged(), IPLab.ChannelFilteringForm.fillBBox_TextChanged(), IPLab.EuclideanColorFilteringForm.fillBox_TextChanged(), IPLab.ChannelFilteringForm.fillGBox_TextChanged(), IPLab.ChannelFilteringForm.fillRBox_TextChanged(), IPLab.SimplePosterizationForm.fillTypeCombo_SelectedIndexChanged(), IPLab.EuclideanColorFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.YCbCrFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.ColorFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.HSLFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.FilterPreview.FilterPreview_MouseUp(), IPLab.GammaForm.gammaBox_TextChanged(), IPLab.SusanCornersDetectorForm.geometricalThresholdTrackBar_ValueChanged(), IPLab.ChannelFilteringForm.greenFillTypeCombo_SelectedIndexChanged(), IPLab.PixelateForm.heightBox_TextChanged(), IPLab.CannyDetectorForm.highThresholdBox_TextChanged(), IPLab.WaterWaveForm.horAmplitudeTrackBar_ValueChanged(), IPLab.WaterWaveForm.horCountTrackBar_ValueChanged(), IPLab.HueModifierForm.hueBox_TextChanged(), IPLab.BilateralForm.kernelSizeUpDown_ValueChanged(), IPLab.CannyDetectorForm.lowThresholdBox_TextChanged(), IPLab.RunLengthSmoothingForm.maxGapUpDown_ValueChanged(), IPLab.HolesFillingForm.maxHeightBox_TextChanged(), IPLab.HolesFillingForm.maxWidthBox_TextChanged(), IPLab.ThresholdForm.minBox_TextChanged(), IPLab.BlobsFilteringForm.minHeightBox_TextChanged(), IPLab.BlobsFilteringForm.minWidthBox_TextChanged(), IPLab.BlobsFilteringForm.modeCombo_SelectedIndexChanged(), IPLab.HolesFillingForm.modeCombo_SelectedIndexChanged(), IPLab.SaltNoiseForm.noiseAmountBox_TextChanged(), IPLab.AdditiveNoiseForm.noiseAmplitudeBox_TextChanged(), IPLab.MorphForm.percentageBar_ValueChanged(), IPLab.SimplePosterizationForm.posterizationIntervalBox_TextChanged(), IPLab.RunLengthSmoothingForm.processBordersCheck_CheckedChanged(), IPLab.EuclideanColorFilteringForm.radiusBox_TextChanged(), IPLab.ChannelFilteringForm.redFillTypeCombo_SelectedIndexChanged(), IPLab.SaturationForm.saturationBox_TextChanged(), IPLab.SharpenExForm.sigmaBox_TextChanged(), IPLab.GaussianForm.sigmaBox_TextChanged(), IPLab.CannyDetectorForm.sigmaBox_TextChanged(), IPLab.OilPaintingForm.sizeBox_TextChanged(), IPLab.PixelateForm.sizeBox_TextChanged(), IPLab.GaussianForm.sizeBox_TextChanged(), IPLab.SharpenExForm.sizeBox_TextChanged(), IPLab.BilateralForm.spatialFactorUpDown_ValueChanged(), IPLab.BilateralForm.spatialPowerUpDown_ValueChanged(), IPLab.MoveTowardsFilterForm.stepSizeBar_Scroll(), IPLab.MoravecCornersDetectorForm.thresholdTrackBar_ValueChanged(), IPLab.RunLengthSmoothingForm.typeCombo_SelectedIndexChanged(), IPLab.EuclideanColorFilteringForm.UpdateCenterColor(), IPLab.YCbCrFilteringForm.UpdateFillColor(), IPLab.ColorFilteringForm.UpdateFillColor(), IPLab.HSLFilteringForm.UpdateFillColor(), IPLab.HSLLinearForm.UpdateFilter(), IPLab.YCbCrFilteringForm.UpdateFilter(), IPLab.ColorFilteringForm.UpdateFilter(), IPLab.YCbCrLinearForm.UpdateFilter(), IPLab.HSLFilteringForm.UpdateFilter(), IPLab.ChannelFilteringForm.UpdateFilter(), IPLab.LevelsLinearForm.UpdateFilter(), IPLab.HSLFilteringForm.updateHCheck_CheckedChanged(), IPLab.HSLFilteringForm.updateLCheck_CheckedChanged(), IPLab.HSLFilteringForm.updateSCheck_CheckedChanged(), IPLab.WaterWaveForm.vertAmplitudeTrackBar_ValueChanged(), IPLab.WaterWaveForm.vertCountTrackBar_ValueChanged(), and IPLab.MoravecCornersDetectorForm.windowSizeCombo_SelectedIndexChanged().
void IPLab.FilterPreview.FilterPreview_MouseMove (object sender, System.Windows.Forms.MouseEventArgs e) inline private
References IPLab.FilterPreview.areaHeight, IPLab.FilterPreview.cursorHand, IPLab.FilterPreview.cursorHandMove, IPLab.FilterPreview.startTrackingX, and IPLab.FilterPreview.startTrackingY.
Referenced by IPLab.FilterPreview.InitializeComponent().
void IPLab.FilterPreview.FilterPreview_MouseDown (object sender, System.Windows.Forms.MouseEventArgs e) inline private
References IPLab.FilterPreview.cursorHandMove, IPLab.FilterPreview.imageX, and IPLab.FilterPreview.imageY.
Referenced by IPLab.FilterPreview.InitializeComponent().
void IPLab.FilterPreview.FilterPreview_MouseUp (object sender, System.Windows.Forms.MouseEventArgs e) inline private
References IPLab.FilterPreview.cursorHand, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.FilterPreview.InitializeComponent().
Member Data Documentation
Bitmap IPLab.FilterPreview.previewImage private
Bitmap IPLab.FilterPreview.image private
IFilter IPLab.FilterPreview.filter private
Pen IPLab.FilterPreview.blackPen = new Pen(Color.Black, 1) private
Cursor IPLab.FilterPreview.cursorHand private
Referenced by IPLab.FilterPreview.FilterPreview_MouseMove(), and IPLab.FilterPreview.FilterPreview_MouseUp().
Cursor IPLab.FilterPreview.cursorHandMove private
Referenced by IPLab.FilterPreview.FilterPreview_MouseDown(), and IPLab.FilterPreview.FilterPreview_MouseMove().
int IPLab.FilterPreview.areaWidth private
int IPLab.FilterPreview.areaHeight private
Referenced by IPLab.FilterPreview.FilterPreview_MouseMove().
int IPLab.FilterPreview.imageX private
Referenced by IPLab.FilterPreview.FilterPreview_MouseDown().
int IPLab.FilterPreview.imageY private
Referenced by IPLab.FilterPreview.FilterPreview_MouseDown().
bool IPLab.FilterPreview.tracking = false private
int IPLab.FilterPreview.startTrackingX private
Referenced by IPLab.FilterPreview.FilterPreview_MouseMove().
int IPLab.FilterPreview.startTrackingY private
Referenced by IPLab.FilterPreview.FilterPreview_MouseMove().
int IPLab.FilterPreview.oldImageX private
int IPLab.FilterPreview.oldImageY private
Property Documentation
Bitmap IPLab.FilterPreview.Image get set
Referenced by IPLab.AdditiveNoiseForm.InitializeComponent(), IPLab.WaterWaveForm.InitializeComponent(), IPLab.SusanCornersDetectorForm.InitializeComponent(), IPLab.SimplePosterizationForm.InitializeComponent(), IPLab.SaltNoiseForm.InitializeComponent(), IPLab.RunLengthSmoothingForm.InitializeComponent(), IPLab.MoveTowardsFilterForm.InitializeComponent(), IPLab.MoravecCornersDetectorForm.InitializeComponent(), IPLab.HolesFillingForm.InitializeComponent(), IPLab.BlobsFilteringForm.InitializeComponent(), and IPLab.BilateralForm.InitializeComponent().
AForge.Imaging.Filters.IFilter IPLab.FilterPreview.Filter set
Referenced by IPLab.AdaptiveSmoothForm.AdaptiveSmoothForm(), IPLab.AdditiveNoiseForm.AdditiveNoiseForm(), IPLab.BilateralForm.BilateralForm(), IPLab.BlobsFilteringForm.BlobsFilteringForm(), IPLab.BrightnessForm.BrightnessForm(), IPLab.CannyDetectorForm.CannyDetectorForm(), IPLab.ChannelFilteringForm.ChannelFilteringForm(), IPLab.ColorFilteringForm.ColorFilteringForm(), IPLab.ContrastForm.ContrastForm(), IPLab.PerlinNoiseForm.effectComboBox_SelectedIndexChanged(), IPLab.EuclideanColorFilteringForm.EuclideanColorFilteringForm(), IPLab.GammaForm.GammaForm(), IPLab.GaussianForm.GaussianForm(), IPLab.HolesFillingForm.HolesFillingForm(), IPLab.HSLFilteringForm.HSLFilteringForm(), IPLab.HSLLinearForm.HSLLinearForm(), IPLab.HueModifierForm.HueModifierForm(), IPLab.LevelsLinearForm.LevelsLinearForm(), IPLab.MoravecCornersDetectorForm.MoravecCornersDetectorForm(), IPLab.MorphForm.MorphForm(), IPLab.MoveTowardsFilterForm.MoveTowardsFilterForm(), IPLab.OilPaintingForm.OilPaintingForm(), IPLab.PixelateForm.PixelateForm(), IPLab.SaltNoiseForm.SaltNoiseForm(), IPLab.SaturationForm.SaturationForm(), IPLab.SharpenExForm.SharpenExForm(), IPLab.SimplePosterizationForm.SimplePosterizationForm(), IPLab.SusanCornersDetectorForm.SusanCornersDetectorForm(), IPLab.ThresholdForm.ThresholdForm(), IPLab.RunLengthSmoothingForm.typeCombo_SelectedIndexChanged(), IPLab.ConvolutionForm.UpdateFilter(), IPLab.MathMorphologyForm.UpdateFilter(), IPLab.WaterWaveForm.WaterWaveForm(), IPLab.YCbCrFilteringForm.YCbCrFilteringForm(), and IPLab.YCbCrLinearForm.YCbCrLinearForm().
The documentation for this class was generated from the following file:
igsandbox/imageprocessing/iplab_new_GPL/Sources/Controls/FilterPreview.cs