IGLib: NUnit.Framework.Internal.SuccessResultTests Class Reference
NUnit.Framework.Internal.SuccessResultTests Class Reference
Public Member Functions
void TestResultIsSuccess ()
void SuiteResultIsSuccess ()
void TestResultXmlNodeIsSuccess ()
void SuiteResultXmlNodeIsSuccess ()
void SuiteResultXmlNodeHasOneChildTest ()
Public Member Functions inherited from NUnit.Framework.Internal.TestResultTests
void SetUp ()
void TestResultBasicInfo ()
void SuiteResultBasicInfo ()
void TestResultXmlNodeBasicInfo ()
void SuiteResultXmlNodeBasicInfo ()
Protected Member Functions
override void SimulateTestRun ()
Properties
override ResultState ResultState [get]
Properties inherited from NUnit.Framework.Internal.TestResultTests
virtual ResultState ResultState [get]
virtual string ReasonNodeName [get]
Additional Inherited Members
Protected Attributes inherited from NUnit.Framework.Internal.TestResultTests
TestResult testResult
TestResult suiteResult
TestMethod test
double expectedDuration
DateTime expectedStart
DateTime expectedEnd
Member Function Documentation
override void NUnit.Framework.Internal.SuccessResultTests.SimulateTestRun () inline protected virtual
Implements NUnit.Framework.Internal.TestResultTests.
References NUnit.Framework.Interfaces.ResultState.Success.
void NUnit.Framework.Internal.SuccessResultTests.TestResultIsSuccess () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.Empty, NUnit.Framework.Interfaces.ResultState.Success, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.True().
void NUnit.Framework.Internal.SuccessResultTests.SuiteResultIsSuccess () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.Empty, NUnit.Framework.Interfaces.ResultState.Success, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.True().
void NUnit.Framework.Internal.SuccessResultTests.TestResultXmlNodeIsSuccess () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.TNode.Attributes, NUnit.Framework.Assert.NotNull(), NUnit.Framework.Assert.Null(), NUnit.Framework.Interfaces.TNode.SelectSingleNode(), and NUnit.Framework.Interfaces.TNode.Value.
void NUnit.Framework.Internal.SuccessResultTests.SuiteResultXmlNodeIsSuccess () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.TNode.Attributes.
void NUnit.Framework.Internal.SuccessResultTests.SuiteResultXmlNodeHasOneChildTest () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.TNode.SelectNodes().
Property Documentation
override ResultState NUnit.Framework.Internal.SuccessResultTests.ResultState get protected
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/TestResultTests.cs