IGLib: IG.Num.IScalarFunctionUntransformed Interface Reference
IG.Num.IScalarFunctionUntransformed Interface Reference
Scalar functions of vector arguments.
Public Member Functions
void Evaluate (IScalarFunctionResults data)
Evaluates whatever needs to be evaluated and stores the results on the specified storage object.
double Value (IVector x)
Returns the value of this function at the specified parameter.
void GradientPlain (IVector parameters, IVector gradient)
Calculates first order derivatives (gradient) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
void Gradient (IVector parameters, ref IVector gradient)
Calculates first order derivatives (gradient) of this function at the specified parameters.
void HessianPlain (IVector parameters, IMatrix hessian)
Calculates the second derivative (Hessian matrix) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
void Hessian (IVector parameters, ref IMatrix hessian)
Calculates the second derivative (Hessian matrix) of this function at the specified parameters.
Properties
string Name [get]
Returns a short name of the function.
string Description [get]
Returns a short description of the function.
bool ValueDefined [get]
Tells whether value of the function is defined by implementation.
bool GradientDefined [get]
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
bool HessianDefined [get]
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
Detailed Description
Scalar functions of vector arguments.
$A Igor xx May10;
Member Function Documentation
void IG.Num.IScalarFunctionUntransformed.Evaluate (IScalarFunctionResults data)
Evaluates whatever needs to be evaluated and stores the results on the specified storage object.
Parameters
data Evaluation data object where results of calculation are stored. It also contains flags taht specify what needs to be calculated, and resulting flags specifying what has been calculated.
Implemented in IG.Num.ScalarFunctionUntransformedBase.
double IG.Num.IScalarFunctionUntransformed.Value (IVector x)
Returns the value of this function at the specified parameter.
Implemented in IG.Num.ScalarFunctionQuadratic, IG.Num.Func3dBase, IG.Num.ScalarFunctionLinear, IG.Num.Func2dBase, IG.Num.ScalarFunctionUntransformedBase, IG.Num.ScalarFunctionRadialUntransformed, IG.Num.ScalarFunctionBase, and IG.Num.ScalarFunctionConstant.
Referenced by IG.Num.VectorFunctionExamples.RosenrockAndCircle.Evaluate(), IG.Script.AppExtBase.FormDemoFunctionTestDevelop(), IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D(), IG.Neural.Forms.NeuralTrainingControl.GenerateDefaultPoints2D(), IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), IG.Num.TestAlglibOld2008.TestLbfgsAlglibOld(), and IG.Num.Func2dFromScalarFunction.Value().
void IG.Num.IScalarFunctionUntransformed.GradientPlain (IVector parameters, IVector gradient)
Calculates first order derivatives (gradient) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
Parameters
parameters Vector of parameters where derivatives are evaluated.
gradient Vector where first order derivatives (the gradient) are stored.
Implemented in IG.Num.ScalarFunctionQuadratic, IG.Num.Func3dBase, IG.Num.ScalarFunctionLinear, IG.Num.Func2dBase, IG.Num.ScalarFunctionUntransformedBase, IG.Num.ScalarFunctionRadialUntransformed, IG.Num.ScalarFunctionBase, and IG.Num.ScalarFunctionConstant.
void IG.Num.IScalarFunctionUntransformed.Gradient (IVector parameters, ref IVector gradient)
Calculates first order derivatives (gradient) of this function at the specified parameters.
Parameters
parameters Vector of parameters where derivatives are evaluated.
gradient Vector where first order derivatives (gradient) are stored. Passed by reference.
Implemented in IG.Num.ScalarFunctionUntransformedBase.
Referenced by IG.Num.VectorFunctionExamples.RosenrockAndCircle.Evaluate(), and IG.Num.TestAlglibOld2008.TestLbfgsAlglibOld().
void IG.Num.IScalarFunctionUntransformed.HessianPlain (IVector parameters, IMatrix hessian)
Calculates the second derivative (Hessian matrix) of this function at the specified parameters. WARNING: Plain function, does not check consistency of arguments.
Parameters
parameters Vector of parameters where derivatives are evaluated.
hessian Matrix where second derivatives (Hessian matrix) are stored.
Implemented in IG.Num.ScalarFunctionQuadratic, IG.Num.Func3dBase, IG.Num.ScalarFunctionLinear, IG.Num.Func2dBase, IG.Num.ScalarFunctionUntransformedBase, IG.Num.ScalarFunctionRadialUntransformed, IG.Num.ScalarFunctionBase, and IG.Num.ScalarFunctionConstant.
void IG.Num.IScalarFunctionUntransformed.Hessian (IVector parameters, ref IMatrix hessian)
Calculates the second derivative (Hessian matrix) of this function at the specified parameters.
Parameters
parameters Vector of parameters where derivatives are evaluated.
hessian Matrix where second derivatives (Hessian matrix) are stored. Passed by reference.
Implemented in IG.Num.ScalarFunctionUntransformedBase.
Referenced by IG.Num.VectorFunctionExamples.RosenrockAndCircle.Evaluate().
Property Documentation
string IG.Num.IScalarFunctionUntransformed.Name get
Returns a short name of the function.
string IG.Num.IScalarFunctionUntransformed.Description get
Returns a short description of the function.
bool IG.Num.IScalarFunctionUntransformed.ValueDefined get
Tells whether value of the function is defined by implementation.
bool IG.Num.IScalarFunctionUntransformed.GradientDefined get
Tells whether the first derivative is defined for this function (by implementation, not mathematically)
bool IG.Num.IScalarFunctionUntransformed.HessianDefined get
Tells whether the second derivative is defined for this function (by implementation, not mathematically)
The documentation for this interface was generated from the following file:
iglib/igbase/numeric/FunctionScalarInt.cs