IGLib: IG.Crypt.HashUtilities Class Reference
IG.Crypt.HashUtilities Class Reference
Public Types
enum HashAlgorithms {
HashAlgorithms.MD5, HashAlgorithms.SHA, HashAlgorithms.SHA1, HashAlgorithms.SHA256,
HashAlgorithms.SHA384
}
Static Public Member Functions
static byte[] ToASCIIByteArray (string characters)
Converts string to an AscII Byte array.
static byte[] ToUnicodeByteArray (string characters)
Converts string to an Unicode Byte array.
static string FromASCIIByteArray (byte[] characters)
static string FromUnicodeByteArray (byte[] characters)
static bool ValidateHashCode (string p_hash_algorithm, string p_hash_string, byte[] p_data)
static void Test ()
Static Private Member Functions
static byte[] ComputeHash (string HashAlgorithmName, string Str)
static string ComputeHashHexString (string HashAlgorithmName, string Str)
static string HashToHexString (byte[] xHashCode)
static byte[] ParseHashCodeString (string p_hash_code_string)
static bool CompareHashCodes (byte[] x_hash_code1, byte[] x_hash_code2)
Member Enumeration Documentation
enum IG.Crypt.HashUtilities.HashAlgorithms
Enumerator
MD5
SHA
SHA1
SHA256
SHA384
Member Function Documentation
static byte [] IG.Crypt.HashUtilities.ComputeHash (string HashAlgorithmName, string Str) inline static private
static string IG.Crypt.HashUtilities.ComputeHashHexString (string HashAlgorithmName, string Str) inline static private
Referenced by IG.Crypt.HashUtilities.Test().
static string IG.Crypt.HashUtilities.HashToHexString (byte[] xHashCode) inline static private
static byte [] IG.Crypt.HashUtilities.ToASCIIByteArray (string characters) inline static
Converts string to an AscII Byte array.
static byte [] IG.Crypt.HashUtilities.ToUnicodeByteArray (string characters) inline static
Converts string to an Unicode Byte array.
static string IG.Crypt.HashUtilities.FromASCIIByteArray (byte[] characters) inline static
static string IG.Crypt.HashUtilities.FromUnicodeByteArray (byte[] characters) inline static
Referenced by IG.Crypt.HashUtilities.Test().
static byte [] IG.Crypt.HashUtilities.ParseHashCodeString (string p_hash_code_string) inline static private
Referenced by IG.Crypt.HashUtilities.Test().
static bool IG.Crypt.HashUtilities.CompareHashCodes (byte[] x_hash_code1, byte[] x_hash_code2) inline static private
static bool IG.Crypt.HashUtilities.ValidateHashCode (string p_hash_algorithm, string p_hash_string, byte[] p_data) inline static
static void IG.Crypt.HashUtilities.Test () inline static
References IG.Crypt.HashUtilities.ComputeHashHexString(), IG.Crypt.HashUtilities.FromUnicodeByteArray(), and IG.Crypt.HashUtilities.ParseHashCodeString().
The documentation for this class was generated from the following file:
igtest/iglib_sandbox/encryption/EncryptionLib.cs