IGLib: alglib.conv Class Reference
alglib.conv Class Reference
Static Public Member Functions
static void convc1d (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void convc1dinv (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void convc1dcircular (complex[] s, int m, complex[] r, int n, ref complex[] c)
static void convc1dcircularinv (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void convr1d (double[] a, int m, double[] b, int n, ref double[] r)
static void convr1dinv (double[] a, int m, double[] b, int n, ref double[] r)
static void convr1dcircular (double[] s, int m, double[] r, int n, ref double[] c)
static void convr1dcircularinv (double[] a, int m, double[] b, int n, ref double[] r)
static void convc1dx (complex[] a, int m, complex[] b, int n, bool circular, int alg, int q, ref complex[] r)
static void convr1dx (double[] a, int m, double[] b, int n, bool circular, int alg, int q, ref double[] r)
static void convc1d (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void convc1dinv (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void convc1dcircular (complex[] s, int m, complex[] r, int n, ref complex[] c)
static void convc1dcircularinv (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void convr1d (double[] a, int m, double[] b, int n, ref double[] r)
static void convr1dinv (double[] a, int m, double[] b, int n, ref double[] r)
static void convr1dcircular (double[] s, int m, double[] r, int n, ref double[] c)
static void convr1dcircularinv (double[] a, int m, double[] b, int n, ref double[] r)
static void convc1dx (complex[] a, int m, complex[] b, int n, bool circular, int alg, int q, ref complex[] r)
static void convr1dx (double[] a, int m, double[] b, int n, bool circular, int alg, int q, ref double[] r)
Member Function Documentation
static void alglib.conv.convc1d (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static
References alglib.ap.assert(), and alglib.conv.convc1dx().
Referenced by alglib.convc1d(), alglib.conv.convc1d(), alglib.corr.corrc1d(), and alglib.testconvunit.testconv().
static void alglib.conv.convc1dinv (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static
References alglib.ap.assert(), alglib.ftbase.ftbaseexecuteplan(), alglib.ftbase.ftbasefindsmooth(), alglib.ftbase.ftbasegeneratecomplexfftplan(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.convc1dinv(), and alglib.testconvunit.testconv().
static void alglib.conv.convc1dcircular (complex[] s, int m, complex[] r, int n, ref complex[] c) inline static
References alglib.ap.assert(), and alglib.conv.convc1dx().
Referenced by alglib.convc1dcircular(), alglib.conv.convc1dcircular(), alglib.corr.corrc1dcircular(), and alglib.testconvunit.testconv().
static void alglib.conv.convc1dcircularinv (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static
References alglib.ap.assert(), alglib.ftbase.ftbaseexecuteplan(), alglib.ftbase.ftbasegeneratecomplexfftplan(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.convc1dcircularinv(), alglib.conv.convc1dcircularinv(), and alglib.testconvunit.testconv().
static void alglib.conv.convr1d (double[] a, int m, double[] b, int n, ref double[] r) inline static
References alglib.ap.assert(), and alglib.conv.convr1dx().
Referenced by alglib.convr1d(), alglib.conv.convr1d(), alglib.corr.corrr1d(), and alglib.testconvunit.testconv().
static void alglib.conv.convr1dinv (double[] a, int m, double[] b, int n, ref double[] r) inline static
References alglib.ap.assert(), alglib.fft.fftr1dinternaleven(), alglib.fft.fftr1dinvinternaleven(), alglib.ftbase.ftbasefindsmootheven(), alglib.ftbase.ftbasegeneratecomplexfftplan(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.convr1dinv(), and alglib.testconvunit.testconv().
static void alglib.conv.convr1dcircular (double[] s, int m, double[] r, int n, ref double[] c) inline static
References alglib.ap.assert(), and alglib.conv.convr1dx().
Referenced by alglib.convr1dcircular(), alglib.conv.convr1dcircular(), alglib.corr.corrr1dcircular(), and alglib.testconvunit.testconv().
static void alglib.conv.convr1dcircularinv (double[] a, int m, double[] b, int n, ref double[] r) inline static
References alglib.ap.assert(), alglib.fft.fftr1d(), alglib.fft.fftr1dinternaleven(), alglib.fft.fftr1dinv(), alglib.fft.fftr1dinvinternaleven(), alglib.ftbase.ftbasegeneratecomplexfftplan(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.convr1dcircularinv(), alglib.conv.convr1dcircularinv(), and alglib.testconvunit.testconv().
static void alglib.conv.convc1dx (complex[] a, int m, complex[] b, int n, bool circular, int alg, int q, ref complex[] r) inline static
References alglib.ap.assert(), alglib.fft.fftc1d(), alglib.ftbase.ftbaseexecuteplan(), alglib.ftbase.ftbasefindsmooth(), alglib.ftbase.ftbasegeneratecomplexfftplan(), alglib.ftbase.ftbasegetflopestimate(), alglib.ftbase.ftbaseissmooth(), alglib.math.maxrealnumber, alglib.complex.x, and alglib.complex.y.
Referenced by alglib.conv.convc1d(), alglib.conv.convc1dcircular(), alglib.conv.convc1dx(), and alglib.testconvunit.testconv().
static void alglib.conv.convr1dx (double[] a, int m, double[] b, int n, bool circular, int alg, int q, ref double[] r) inline static
References alglib.ap.assert(), alglib.fft.fftr1dinternaleven(), alglib.fft.fftr1dinvinternaleven(), alglib.ftbase.ftbasefindsmootheven(), alglib.ftbase.ftbasegeneratecomplexfftplan(), alglib.ftbase.ftbasegetflopestimate(), alglib.ftbase.ftbaseissmooth(), and alglib.math.maxrealnumber.
Referenced by alglib.conv.convr1d(), alglib.conv.convr1dcircular(), alglib.conv.convr1dx(), and alglib.testconvunit.testconv().
static void alglib.conv.convc1d (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static
References alglib.ap.assert(), alglib.conv.convc1d(), and alglib.conv.convc1dx().
static void alglib.conv.convc1dinv (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static
References alglib.ap.assert(), alglib.ftbase.ftapplyplan(), alglib.ftbase.ftbasefindsmooth(), alglib.ftbase.ftcomplexfftplan(), alglib.complex.x, and alglib.complex.y.
static void alglib.conv.convc1dcircular (complex[] s, int m, complex[] r, int n, ref complex[] c) inline static
References alglib.ap.assert(), alglib.conv.convc1dcircular(), and alglib.conv.convc1dx().
static void alglib.conv.convc1dcircularinv (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static
References alglib.ap.assert(), alglib.conv.convc1dcircularinv(), alglib.ftbase.ftapplyplan(), alglib.ftbase.ftcomplexfftplan(), alglib.complex.x, and alglib.complex.y.
static void alglib.conv.convr1d (double[] a, int m, double[] b, int n, ref double[] r) inline static
References alglib.ap.assert(), alglib.conv.convr1d(), and alglib.conv.convr1dx().
static void alglib.conv.convr1dinv (double[] a, int m, double[] b, int n, ref double[] r) inline static
References alglib.ap.assert(), alglib.fft.fftr1dinternaleven(), alglib.fft.fftr1dinvinternaleven(), alglib.ftbase.ftbasefindsmootheven(), alglib.ftbase.ftcomplexfftplan(), alglib.complex.x, and alglib.complex.y.
static void alglib.conv.convr1dcircular (double[] s, int m, double[] r, int n, ref double[] c) inline static
References alglib.ap.assert(), alglib.conv.convr1dcircular(), and alglib.conv.convr1dx().
static void alglib.conv.convr1dcircularinv (double[] a, int m, double[] b, int n, ref double[] r) inline static
References alglib.ap.assert(), alglib.conv.convr1dcircularinv(), alglib.fft.fftr1d(), alglib.fft.fftr1dinternaleven(), alglib.fft.fftr1dinv(), alglib.fft.fftr1dinvinternaleven(), alglib.ftbase.ftcomplexfftplan(), alglib.complex.x, and alglib.complex.y.
static void alglib.conv.convc1dx (complex[] a, int m, complex[] b, int n, bool circular, int alg, int q, ref complex[] r) inline static
References alglib.ap.assert(), alglib.conv.convc1dx(), alglib.fft.fftc1d(), alglib.ftbase.ftapplyplan(), alglib.ftbase.ftbasefindsmooth(), alglib.ftbase.ftbasegetflopestimate(), alglib.ftbase.ftbaseissmooth(), alglib.ftbase.ftcomplexfftplan(), alglib.math.maxrealnumber, alglib.complex.x, and alglib.complex.y.
static void alglib.conv.convr1dx (double[] a, int m, double[] b, int n, bool circular, int alg, int q, ref double[] r) inline static
References alglib.ap.assert(), alglib.conv.convr1dx(), alglib.fft.fftr1dinternaleven(), alglib.fft.fftr1dinvinternaleven(), alglib.ftbase.ftbasefindsmootheven(), alglib.ftbase.ftbasegetflopestimate(), alglib.ftbase.ftbaseissmooth(), alglib.ftbase.ftcomplexfftplan(), and alglib.math.maxrealnumber.
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/fasttransforms.cs