IGLib: IG.Test.TestMatrixOperations Class Reference
IG.Test.TestMatrixOperations Class Reference
Unit tests for matrix operations.
Public Member Functions
void AccessOutOfRangeMatrix1 ()
void AccessOutOfRangeMatrix2 ()
void AccessOutOfRangeMatrix3 ()
void AccessOutOfRangeMatrix4 ()
void AccessOutOfRangeVector1 ()
void AccessOutOfRangeVector2 ()
void ByHand_Transpose ()
Test of matrix transpose - comparison with known result.
void ByHand_MultiplyMatrix ()
Test of matrix product - comparison of product with known result.
void ByHand_MultiplyMatrixVector ()
Test of matrix - vector product (comparison of product with known result).
void ByHand_ScalarProduct ()
Test of scalar product (comparison of product with knnown result).
void MultiplyMatMatTransp ()
Tests matrix product A*B*C^T.
void MultiplyVectorMatrixVector ()
Tests vector - matrix - vector product a^T*B*c.
void AccessOutOfRangeMatrix1 ()
void AccessOutOfRangeMatrix2 ()
void AccessOutOfRangeMatrix3 ()
void AccessOutOfRangeMatrix4 ()
void AccessOutOfRangeVector1 ()
void AccessOutOfRangeVector2 ()
void ByHand_Transpose ()
Test of matrix transpose - comparison with known result.
void ByHand_MultiplyMatrix ()
Test of matrix product - comparison of product with known result.
void ByHand_MultiplyMatrixVector ()
Test of matrix - vector product (comparison of product with known result).
void ByHand_ScalarProduct ()
Test of scalar product (comparison of product with knnown result).
void MultiplyMatMatTransp ()
Tests matrix product A*B*C^T.
void MultiplyVectorMatrixVector ()
Tests vector - matrix - vector product a^T*B*c.
Detailed Description
Unit tests for matrix operations.
$A Igor May09 Dec14;
Member Function Documentation
void IG.Test.TestMatrixOperations.AccessOutOfRangeMatrix1 () inline
References IG.Num.A.
void IG.Test.TestMatrixOperations.AccessOutOfRangeMatrix2 () inline
References IG.Num.A.
void IG.Test.TestMatrixOperations.AccessOutOfRangeMatrix3 () inline
References IG.Num.A.
void IG.Test.TestMatrixOperations.AccessOutOfRangeMatrix4 () inline
References IG.Num.A.
void IG.Test.TestMatrixOperations.AccessOutOfRangeVector1 () inline
void IG.Test.TestMatrixOperations.AccessOutOfRangeVector2 () inline
void IG.Test.TestMatrixOperations.ByHand_Transpose () inline
Test of matrix transpose - comparison with known result.
References IG.Num.A, IG.Num.MatrixBase.SetZero(), IG.Num.MatrixBase.Subtract(), IG.Num.IMatrix.ToStringReadable(), IG.Num.MatrixBase.Transpose(), and IG.Num.MatrixBase.TransposePlain().
void IG.Test.TestMatrixOperations.ByHand_MultiplyMatrix () inline
Test of matrix product - comparison of product with known result.
References IG.Num.A, IG.Num.MatrixBase.Multiply(), IG.Num.MatrixBase.MultiplyPlain(), IG.Num.MatrixBase.SetZero(), IG.Num.MatrixBase.Subtract(), and IG.Num.IMatrix.ToStringReadable().
void IG.Test.TestMatrixOperations.ByHand_MultiplyMatrixVector () inline
Test of matrix - vector product (comparison of product with known result).
References IG.Num.A, IG.Num.MatrixBase.Multiply(), IG.Num.MatrixBase.MultiplyPlain(), IG.Num.VectorBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.IMatrix.ToStringReadable().
void IG.Test.TestMatrixOperations.ByHand_ScalarProduct () inline
Test of scalar product (comparison of product with knnown result).
References IG.Num.VectorBase.ScalarProduct().
void IG.Test.TestMatrixOperations.MultiplyMatMatTransp () inline
Tests matrix product A*B*C^T.
References IG.Num.A, IG.Num.MatrixBase.Multiply(), IG.Num.MatrixBase.MultiplyMatMatTransp(), IG.Num.MatrixBase.MultiplyMatMatTranspPlain(), IG.Num.MatrixBase.SetRandom(), IG.Num.MatrixBase.SetZero(), IG.Num.MatrixBase.Subtract(), and IG.Num.MatrixBase.Transpose().
void IG.Test.TestMatrixOperations.MultiplyVectorMatrixVector () inline
Tests vector - matrix - vector product a^T*B*c.
References IG.Num.MatrixBase.Multiply(), IG.Num.VectorBase.ScalarProduct(), IG.Num.VectorBase.SetRandom(), and IG.Num.MatrixBase.SetRandom().
void IG.Test.TestMatrixOperations.AccessOutOfRangeMatrix1 () inline
References IG.Num.A, and NUnit.Framework.Assert.Throws().
void IG.Test.TestMatrixOperations.AccessOutOfRangeMatrix2 () inline
References IG.Num.A, and NUnit.Framework.Assert.Throws().
void IG.Test.TestMatrixOperations.AccessOutOfRangeMatrix3 () inline
References IG.Num.A, and NUnit.Framework.Assert.Throws().
void IG.Test.TestMatrixOperations.AccessOutOfRangeMatrix4 () inline
References IG.Num.A, and NUnit.Framework.Assert.Throws().
void IG.Test.TestMatrixOperations.AccessOutOfRangeVector1 () inline
References NUnit.Framework.Assert.Throws().
void IG.Test.TestMatrixOperations.AccessOutOfRangeVector2 () inline
References NUnit.Framework.Assert.Throws().
void IG.Test.TestMatrixOperations.ByHand_Transpose () inline
Test of matrix transpose - comparison with known result.
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), IG.Num.MatrixBase.SetZero(), IG.Num.MatrixBase.Subtract(), IG.Num.IMatrix.ToStringReadable(), IG.Num.MatrixBase.Transpose(), and IG.Num.MatrixBase.TransposePlain().
void IG.Test.TestMatrixOperations.ByHand_MultiplyMatrix () inline
Test of matrix product - comparison of product with known result.
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), IG.Num.MatrixBase.Multiply(), IG.Num.MatrixBase.MultiplyPlain(), IG.Num.MatrixBase.SetZero(), IG.Num.MatrixBase.Subtract(), and IG.Num.IMatrix.ToStringReadable().
void IG.Test.TestMatrixOperations.ByHand_MultiplyMatrixVector () inline
Test of matrix - vector product (comparison of product with known result).
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), IG.Num.MatrixBase.Multiply(), IG.Num.MatrixBase.MultiplyPlain(), IG.Num.VectorBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.IMatrix.ToStringReadable().
void IG.Test.TestMatrixOperations.ByHand_ScalarProduct () inline
Test of scalar product (comparison of product with knnown result).
References NUnit.Framework.Assert.AreEqual(), and IG.Num.VectorBase.ScalarProduct().
void IG.Test.TestMatrixOperations.MultiplyMatMatTransp () inline
Tests matrix product A*B*C^T.
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), IG.Num.MatrixBase.Multiply(), IG.Num.MatrixBase.MultiplyMatMatTransp(), IG.Num.MatrixBase.MultiplyMatMatTranspPlain(), IG.Num.MatrixBase.SetRandom(), IG.Num.MatrixBase.SetZero(), IG.Num.MatrixBase.Subtract(), and IG.Num.MatrixBase.Transpose().
void IG.Test.TestMatrixOperations.MultiplyVectorMatrixVector () inline
Tests vector - matrix - vector product a^T*B*c.
References NUnit.Framework.Assert.AreEqual(), IG.Num.MatrixBase.Multiply(), IG.Num.VectorBase.ScalarProduct(), IG.Num.VectorBase.SetRandom(), and IG.Num.MatrixBase.SetRandom().
The documentation for this class was generated from the following file:
unittests/MSTests/TestNumeric/TstMatrixOperations.cs