IGLib: Meta.Numerics.ComplexMath Class Reference
Meta.Numerics.ComplexMath Class Reference
Provides simple functions of complex arguments.
Static Public Member Functions
static double Abs (Complex z)
Computes the absolute value of a complex number.
static double Arg (Complex z)
Computes the phase of a complex number.
static Complex Exp (Complex z)
Computes e raised to the power of a complex number.
static Complex Log (Complex z)
Computes the natrual logarithm of a complex number.
static Complex Sqr (Complex z)
Computes the square of a complex number.
static Complex Sqrt (Complex z)
Computes the square root of a complex number.
static Complex Sin (Complex z)
Computes the sine of a complex number.
static Complex Sinh (Complex z)
Computes the hyperbolic sine of a complex number.
static Complex Cos (Complex z)
Computes the cosine of a complex number.
static Complex Cosh (Complex z)
Computes the hyperbolic cosine of a complex number.
static Complex Tan (Complex z)
Computes the tangent of a complex number.
static Complex Tanh (Complex z)
Computes the hyperbolic tangent of a complex number.
static Complex Pow (Complex z, double p)
Raises a complex number to an arbitrary real power.
static Complex Pow (double x, Complex z)
Raises a real number to an arbitrary complex power.
static Complex Pow (Complex z, int n)
Raises a complex number to an integer power.
Properties
static Complex I [get]
Gets the unit imaginary number I.
Detailed Description
Provides simple functions of complex arguments.
Member Function Documentation
static double Meta.Numerics.ComplexMath.Abs (Complex z) inline static
Computes the absolute value of a complex number.
Parameters
z The argument.
Returns
The value of |z|.
The absolute value of a complex number is the distance of the number from the origin in the complex plane. This is a compatible generalization of the definition of the absolute value of a real number.
See also
Math.Abs(Double)
References Meta.Numerics.MoreMath.Hypot(), Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
Referenced by Test.BugTests.Bug5504(), Test.AdvancedComplexMathTest.ComplexGammaInequality(), Test.ComplexMathTest.ComplexMagnitude(), Test.ComplexMathTest.ComplexSqrt(), Test.BugTests.DifficultEigenvalue(), Meta.Numerics.Functions.AdvancedComplexMath.DiLog(), Meta.Numerics.Functions.AdvancedComplexMath.Erf(), Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva(), Test.FourierTest.FourierSpecialCases(), Meta.Numerics.Functions.AdvancedComplexMath.LogGamma(), Test.MultiIntegrateTest.RambleIntegral(), and Meta.Numerics.Functions.AdvancedComplexMath.RiemannZeta().
static double Meta.Numerics.ComplexMath.Arg (Complex z) inline static
Computes the phase of a complex number.
Parameters
z The argument.
Returns
The value of arg(z).
The phase of a complex number is the angle between the line joining it to the origin and the real axis of the complex plane.
The phase of complex numbers in the upper complex plane lies between 0 and &#x3C0;. The phase of complex numbers in the lower complex plane lies between 0 and -&#x3C0;. The phase of a real number is zero.
References Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
Referenced by Test.BugTests.Bug5504(), Test.ComplexMathTest.ComplexLogSum(), Test.ComplexMathTest.ComplexSqrt(), and Test.BugTests.DifficultEigenvalue().
static Complex Meta.Numerics.ComplexMath.Exp (Complex z) inline static
Computes e raised to the power of a complex number.
Parameters
z The argument.
Returns
The value of ez.
References Meta.Numerics.MoreMath.Cos(), Meta.Numerics.Complex.Im, Meta.Numerics.Complex.Re, and Meta.Numerics.MoreMath.Sin().
Referenced by Test.AdvancedComplexMathTest.ComplexDiLogClausen(), Test.AdvancedComplexMathTest.ComplexErfFaddevaAgreement(), Test.ComplexMathTest.ComplexExpReflection(), Test.ComplexMathTest.ComplexExpSpecialCase(), Test.ComplexMathTest.ComplexExpSumTest(), Test.ComplexMathTest.ComplexLogExp(), Test.ComplexMathTest.ComplexPowExponent(), Test.ComplexMathTest.ComplexRealAgreement(), Meta.Numerics.Functions.AdvancedComplexMath.Erf(), Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva(), Meta.Numerics.Functions.AdvancedComplexMath.Gamma(), Meta.Numerics.Functions.AdvancedComplexMath.IntegeralE1_ContinuedFraction(), and Meta.Numerics.Functions.AdvancedComplexMath.IntegralEi_AsymptoticSeries().
static Complex Meta.Numerics.ComplexMath.Log (Complex z) inline static
Computes the natrual logarithm of a complex number.
Parameters
z The argument.
Returns
The value of ln(z).
Referenced by Test.AdvancedComplexMathTest.ComplexDiLogSymmetry(), Test.ComplexMathTest.ComplexLogExp(), Test.ComplexMathTest.ComplexLogSpecialCase(), Test.ComplexMathTest.ComplexLogSum(), Test.ComplexMathTest.ComplexRealAgreement(), Meta.Numerics.Functions.AdvancedComplexMath.DiLog(), Meta.Numerics.Functions.AdvancedComplexMath.DiLog_Log_Series(), Meta.Numerics.Functions.AdvancedComplexMath.DiLog_Series_1(), Meta.Numerics.Functions.AdvancedComplexMath.Ein(), and Meta.Numerics.Functions.AdvancedComplexMath.LogGamma_Stirling().
static Complex Meta.Numerics.ComplexMath.Sqr (Complex z) inline static
Computes the square of a complex number.
Parameters
z The argument.
Returns
The value of z2.
Referenced by Test.ComplexMathTest.ComplexSqrt().
static Complex Meta.Numerics.ComplexMath.Sqrt (Complex z) inline static
Computes the square root of a complex number.
Parameters
z The argument.
Returns
The square root of the argument.
References Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
Referenced by Test.ComplexMathTest.ComplexIDefinition(), Test.ComplexMathTest.ComplexPowOneHalf(), Test.ComplexMathTest.ComplexRealAgreement(), and Test.ComplexMathTest.ComplexSqrt().
static Complex Meta.Numerics.ComplexMath.Sin (Complex z) inline static
Computes the sine of a complex number.
Parameters
z The argument.
Returns
The value of sin(z).
References Meta.Numerics.MoreMath.Cos(), Meta.Numerics.Complex.Im, Meta.Numerics.Complex.Re, and Meta.Numerics.MoreMath.Sin().
Referenced by Test.ComplexMathTest.ComplexAngleAdditionTest(), Test.ComplexMathTest.ComplexDoubleAngle(), Test.ComplexMathTest.ComplexNegativeAngles(), Test.ComplexMathTest.ComplexPythagorean(), Test.ComplexMathTest.ComplexSinSinh(), Test.ComplexMathTest.ComplexTrigPeriodicity(), and Meta.Numerics.Functions.AdvancedComplexMath.Gamma().
static Complex Meta.Numerics.ComplexMath.Sinh (Complex z) inline static
Computes the hyperbolic sine of a complex number.
Parameters
z The argument.
Returns
The value of sinh(z).
References Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
Referenced by Test.ComplexMathTest.ComplexSinhCoshRelation(), and Test.ComplexMathTest.ComplexSinSinh().
static Complex Meta.Numerics.ComplexMath.Cos (Complex z) inline static
Computes the cosine of a complex number.
Parameters
z The argument.
Returns
The value of cos(z).
References Meta.Numerics.MoreMath.Cos(), Meta.Numerics.Complex.Im, Meta.Numerics.Complex.Re, and Meta.Numerics.MoreMath.Sin().
Referenced by Test.ComplexMathTest.ComplexAngleAdditionTest(), Test.ComplexMathTest.ComplexCosCosh(), Test.ComplexMathTest.ComplexDoubleAngle(), Test.ComplexMathTest.ComplexNegativeAngles(), Test.ComplexMathTest.ComplexPythagorean(), Test.ComplexMathTest.ComplexSecTanTest(), Test.ComplexMathTest.ComplexTrigPeriodicity(), and Meta.Numerics.Functions.AdvancedComplexMath.RiemannZeta().
static Complex Meta.Numerics.ComplexMath.Cosh (Complex z) inline static
Computes the hyperbolic cosine of a complex number.
Parameters
z The argument.
Returns
The value of cosh(z).
References Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
Referenced by Test.ComplexMathTest.ComplexCosCosh(), and Test.ComplexMathTest.ComplexSinhCoshRelation().
static Complex Meta.Numerics.ComplexMath.Tan (Complex z) inline static
Computes the tangent of a complex number.
Parameters
z The argument.
Returns
The value of tan(z).
References Meta.Numerics.MoreMath.Cos(), Meta.Numerics.Complex.Im, Meta.Numerics.Complex.Re, and Meta.Numerics.MoreMath.Sin().
Referenced by Test.ComplexMathTest.ComplexNegativeAngles(), Test.ComplexMathTest.ComplexSecTanTest(), Test.ComplexMathTest.ComplexTanTanh(), and Meta.Numerics.Functions.AdvancedComplexMath.Psi().
static Complex Meta.Numerics.ComplexMath.Tanh (Complex z) inline static
Computes the hyperbolic tangent of a complex number.
Parameters
z The argument.
Returns
The value of tanh(z).
References Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
Referenced by Test.ComplexMathTest.ComplexTanTanh().
static Complex Meta.Numerics.ComplexMath.Pow (Complex z, double p) inline static
Raises a complex number to an arbitrary real power.
Parameters
z The argument.
p The power.
Returns
The value of zp.
References Meta.Numerics.MoreMath.Cos(), and Meta.Numerics.MoreMath.Sin().
Referenced by Test.ComplexMathTest.ComplexPowExponent(), Test.ComplexMathTest.ComplexPowMultiplication(), Test.ComplexMathTest.ComplexPowOneHalf(), Test.ComplexMathTest.ComplexPowSpecialCases(), Test.AdvancedComplexMathTest.ComplexReimannZetaPrimesTest(), Meta.Numerics.ComplexMath.Pow(), Meta.Numerics.Functions.AdvancedComplexMath.RiemannZeta(), and Meta.Numerics.Functions.AdvancedComplexMath.RiemannZeta_EulerMaclaurin().
static Complex Meta.Numerics.ComplexMath.Pow (double x, Complex z) inline static
Raises a real number to an arbitrary complex power.
Parameters
x The real base, which must be non-negative.
z The complex exponent.
Returns
The value of xz.
References Meta.Numerics.MoreMath.Cos(), Meta.Numerics.Complex.Im, Meta.Numerics.Complex.One, Meta.Numerics.Complex.Re, Meta.Numerics.MoreMath.Sin(), and Meta.Numerics.Complex.Zero.
static Complex Meta.Numerics.ComplexMath.Pow (Complex z, int n) inline static
Raises a complex number to an integer power.
Parameters
z The argument.
n The power.
Returns
The value of zn.
References Meta.Numerics.ComplexMath.Pow().
Property Documentation
Complex Meta.Numerics.ComplexMath.I static get
Gets the unit imaginary number I.
Referenced by Meta.Numerics.Functions.AdvancedMath.Bessel_CF2(), Test.ComplexMathTest.ComplexCosCosh(), Test.AdvancedComplexMathTest.ComplexDiLogBranchCut(), Test.AdvancedComplexMathTest.ComplexDiLogClausen(), Test.AdvancedComplexMathTest.ComplexDiLogUnitCircle(), Test.AdvancedComplexMathTest.ComplexErfFaddevaAgreement(), Test.AdvancedComplexMathTest.ComplexErfFresnel(), Test.ComplexMathTest.ComplexLogSpecialCase(), Test.ComplexMathTest.ComplexSinSinh(), Test.ComplexMathTest.ComplexTanTanh(), Meta.Numerics.Functions.AdvancedMath.Coulomb_CF2(), Meta.Numerics.Functions.AdvancedComplexMath.Erf(), Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva(), Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva_ContinuedFraction(), Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva_Taylor(), and Meta.Numerics.Functions.AdvancedComplexMath.Faddeeva_Weideman().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Core/ComplexMath.cs