IGLib: alglib.apserv.sreal Class Reference
alglib.apserv.sreal Class Reference
Public Member Functions
sreal ()
override void init ()
override alglib.apobject make_copy ()
Public Attributes
double val
Constructor & Destructor Documentation
alglib.apserv.sreal.sreal () inline
References alglib.apserv.sreal.init().
Referenced by alglib.apserv.sreal.make_copy().
Member Function Documentation
override void alglib.apserv.sreal.init () inline virtual
Implements alglib.apobject.
Referenced by alglib.apserv.sreal.sreal().
override alglib.apobject alglib.apserv.sreal.make_copy () inline virtual
Implements alglib.apobject.
References alglib.apserv.sreal.sreal(), and alglib.apserv.sreal.val.
Member Data Documentation
double alglib.apserv.sreal.val
Referenced by alglib.apserv.sreal.make_copy().
The documentation for this class was generated from the following file:
igtest/numerics/alglib_0.8.2/src/alglibinternal.cs