IGLib: alglib.testminbleicunit Class Reference
alglib.testminbleicunit Class Reference
Static Public Member Functions
static bool testminbleic (bool silent)
static bool testminbleic (bool silent)
static bool _pexec_testminbleic (bool silent)
Static Private Member Functions
static void checkbounds (double[] x, double[] bndl, double[] bndu, int n, ref bool err)
static void calciip2 (minbleic.minbleicstate state, int n, int fk)
static void testfeasibility (ref bool feaserr, ref bool converr, ref bool interr)
static void testother (ref bool err)
static void testconv (ref bool err)
static void testpreconditioning (ref bool err)
static void setrandompreconditioner (minbleic.minbleicstate state, int n, int preckind)
static void testgradientcheck (ref bool testg)
static void funcderiv (double a, double b, double c, double d, double x0, double x1, double x2, double[] x, int functype, ref double f, ref double[] g)
static void checkbounds (double[] x, double[] bndl, double[] bndu, int n, ref bool err)
static void calciip2 (minbleic.minbleicstate state, int n, int fk)
static void testfeasibility (ref bool feaserr, ref bool converr, ref bool interr)
static void testother (ref bool err)
static void testconv (ref bool err)
static void testpreconditioning (ref bool err)
static void setrandompreconditioner (minbleic.minbleicstate state, int n, int preckind)
static void testgradientcheck (ref bool testg)
static void funcderiv (double a, double b, double c, double d, double x0, double x1, double x2, double[] x, int functype, ref double f, ref double[] g)
Member Function Documentation
static bool alglib.testminbleicunit.testminbleic (bool silent) inline static
References alglib.testminbleicunit.testconv(), alglib.testminbleicunit.testfeasibility(), alglib.testminbleicunit.testgradientcheck(), alglib.testminbleicunit.testother(), and alglib.testminbleicunit.testpreconditioning().
Referenced by alglib.testminbleicunit._pexec_testminbleic(), and _Test.Main().
static void alglib.testminbleicunit.checkbounds (double[] x, double[] bndl, double[] bndu, int n, ref bool err) inline static private
static void alglib.testminbleicunit.calciip2 (minbleic.minbleicstate state, int n, int fk) inline static private
References alglib.math.sqr().
Referenced by alglib.testminbleicunit.testpreconditioning().
static void alglib.testminbleicunit.testfeasibility (ref bool feaserr, ref bool converr, ref bool interr) inline static private
References alglib.apserv.boundval(), alglib.minbleic.minbleiccreate(), alglib.minbleic.minbleiccreatef(), alglib.minbleic.minbleiciteration(), alglib.minbleic.minbleicresults(), alglib.minbleic.minbleicsetbc(), alglib.minbleic.minbleicsetinnercond(), alglib.minbleic.minbleicsetlc(), alglib.minbleic.minbleicsetoutercond(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.testminbleicunit.setrandompreconditioner(), and alglib.math.sqr().
Referenced by alglib.testminbleicunit.testminbleic().
static void alglib.testminbleicunit.testother (ref bool err) inline static private
References alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.minbleic.minbleiccreate(), alglib.minbleic.minbleiccreatef(), alglib.minbleic.minbleiciteration(), alglib.minbleic.minbleicresults(), alglib.minbleic.minbleicsetbc(), alglib.minbleic.minbleicsetinnercond(), alglib.minbleic.minbleicsetlc(), alglib.minbleic.minbleicsetmaxits(), alglib.minbleic.minbleicsetoutercond(), alglib.minbleic.minbleicsetprecdiag(), alglib.minbleic.minbleicsetprecscale(), alglib.minbleic.minbleicsetscale(), alglib.minbleic.minbleicsetstpmax(), alglib.minbleic.minbleicsetxrep(), alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testminbleicunit.testminbleic().
static void alglib.testminbleicunit.testconv (ref bool err) inline static private
References alglib.minbleic.minbleiccreate(), alglib.minbleic.minbleiciteration(), alglib.minbleic.minbleicresults(), alglib.minbleic.minbleicsetbc(), alglib.minbleic.minbleicsetinnercond(), alglib.minbleic.minbleicsetlc(), alglib.minbleic.minbleicsetoutercond(), alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testminbleicunit.testminbleic().
static void alglib.testminbleicunit.testpreconditioning (ref bool err) inline static private
References alglib.testminbleicunit.calciip2(), alglib.minbleic.minbleiccreate(), alglib.minbleic.minbleiciteration(), alglib.minbleic.minbleicrestartfrom(), alglib.minbleic.minbleicresults(), alglib.minbleic.minbleicsetbc(), alglib.minbleic.minbleicsetlc(), alglib.minbleic.minbleicsetprecdefault(), alglib.minbleic.minbleicsetprecdiag(), alglib.minbleic.minbleicsetprecscale(), alglib.minbleic.minbleicsetscale(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testminbleicunit.testminbleic().
static void alglib.testminbleicunit.setrandompreconditioner (minbleic.minbleicstate state, int n, int preckind) inline static private
References alglib.minbleic.minbleicsetprecdefault(), alglib.minbleic.minbleicsetprecdiag(), and alglib.math.randomreal().
Referenced by alglib.testminbleicunit.testconv(), and alglib.testminbleicunit.testfeasibility().
static void alglib.testminbleicunit.testgradientcheck (ref bool testg) inline static private
References alglib.testminbleicunit.funcderiv(), alglib.math.isfinite(), alglib.minbleic.minbleiccreate(), alglib.minbleic.minbleiciteration(), alglib.minbleic.minbleicrestartfrom(), alglib.minbleic.minbleicresults(), alglib.minbleic.minbleicsetbc(), alglib.minbleic.minbleicsetgradientcheck(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testminbleicunit.testminbleic().
static void alglib.testminbleicunit.funcderiv (double a, double b, double c, double d, double x0, double x1, double x2, double[] x, int functype, ref double f, ref double[] g) inline static private
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.math.sqr().
Referenced by alglib.testminbleicunit.testgradientcheck().
static bool alglib.testminbleicunit.testminbleic (bool silent) inline static
References alglib.testminbleicunit.testconv(), alglib.testminbleicunit.testfeasibility(), alglib.testminbleicunit.testgradientcheck(), alglib.testminbleicunit.testother(), and alglib.testminbleicunit.testpreconditioning().
static bool alglib.testminbleicunit._pexec_testminbleic (bool silent) inline static
References alglib.testminbleicunit.testminbleic().
Referenced by _Test.Main().
static void alglib.testminbleicunit.checkbounds (double[] x, double[] bndl, double[] bndu, int n, ref bool err) inline static private
static void alglib.testminbleicunit.calciip2 (minbleic.minbleicstate state, int n, int fk) inline static private
References alglib.math.sqr().
static void alglib.testminbleicunit.testfeasibility (ref bool feaserr, ref bool converr, ref bool interr) inline static private
References alglib.minbleic.minbleiccreate(), alglib.minbleic.minbleiccreatef(), alglib.minbleic.minbleiciteration(), alglib.minbleic.minbleicresults(), alglib.minbleic.minbleicsetbc(), alglib.minbleic.minbleicsetcond(), alglib.minbleic.minbleicsetlc(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.testminbleicunit.setrandompreconditioner(), and alglib.math.sqr().
static void alglib.testminbleicunit.testother (ref bool err) inline static private
References alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.minbleic.minbleiccreate(), alglib.minbleic.minbleiccreatef(), alglib.minbleic.minbleiciteration(), alglib.minbleic.minbleicresults(), alglib.minbleic.minbleicsetbc(), alglib.minbleic.minbleicsetcond(), alglib.minbleic.minbleicsetlc(), alglib.minbleic.minbleicsetprecdiag(), alglib.minbleic.minbleicsetprecscale(), alglib.minbleic.minbleicsetscale(), alglib.minbleic.minbleicsetstpmax(), alglib.minbleic.minbleicsetxrep(), alglib.math.randomreal(), alglib.apserv.seterrorflag(), and alglib.math.sqr().
static void alglib.testminbleicunit.testconv (ref bool err) inline static private
References alglib.minbleic.minbleiccreate(), alglib.minbleic.minbleiciteration(), alglib.minbleic.minbleicrestartfrom(), alglib.minbleic.minbleicresults(), alglib.minbleic.minbleicsetbc(), alglib.minbleic.minbleicsetcond(), alglib.minbleic.minbleicsetlc(), alglib.apserv.randomnormal(), alglib.math.randomreal(), alglib.testminbleicunit.setrandompreconditioner(), and alglib.math.sqr().
static void alglib.testminbleicunit.testpreconditioning (ref bool err) inline static private
References alglib.testminbleicunit.calciip2(), alglib.minbleic.minbleiccreate(), alglib.minbleic.minbleiciteration(), alglib.minbleic.minbleicrestartfrom(), alglib.minbleic.minbleicresults(), alglib.minbleic.minbleicsetbc(), alglib.minbleic.minbleicsetcond(), alglib.minbleic.minbleicsetlc(), alglib.minbleic.minbleicsetprecdefault(), alglib.minbleic.minbleicsetprecdiag(), alglib.minbleic.minbleicsetprecscale(), alglib.minbleic.minbleicsetscale(), alglib.math.randominteger(), and alglib.math.randomreal().
static void alglib.testminbleicunit.setrandompreconditioner (minbleic.minbleicstate state, int n, int preckind) inline static private
References alglib.minbleic.minbleicsetprecdefault(), alglib.minbleic.minbleicsetprecdiag(), and alglib.math.randomreal().
static void alglib.testminbleicunit.testgradientcheck (ref bool testg) inline static private
References alglib.testminbleicunit.funcderiv(), alglib.math.isfinite(), alglib.minbleic.minbleiccreate(), alglib.minbleic.minbleiciteration(), alglib.minbleic.minbleicrestartfrom(), alglib.minbleic.minbleicresults(), alglib.minbleic.minbleicsetbc(), alglib.minbleic.minbleicsetgradientcheck(), alglib.math.randominteger(), alglib.apserv.randomnormal(), and alglib.math.randomreal().
static void alglib.testminbleicunit.funcderiv (double a, double b, double c, double d, double x0, double x1, double x2, double[] x, int functype, ref double f, ref double[] g) inline static private
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.math.sqr().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs