IGLib: IPLab.YCbCrFilteringForm Class Reference
IPLab.YCbCrFilteringForm Class Reference
Summary description for YCbCrFilteringForm.
Public Member Functions
YCbCrFilteringForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
Bitmap Image [set]
IFilter Filter [get]
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void UpdateFilter ()
void minYBox_TextChanged (object sender, System.EventArgs e)
void maxYBox_TextChanged (object sender, System.EventArgs e)
void minCbBox_TextChanged (object sender, System.EventArgs e)
void maxCbBox_TextChanged (object sender, System.EventArgs e)
void minCrBox_TextChanged (object sender, System.EventArgs e)
void maxCrBox_TextChanged (object sender, System.EventArgs e)
void ySlider_ValuesChanged (object sender, System.EventArgs e)
void cbSlider_ValuesChanged (object sender, System.EventArgs e)
void crSlider_ValuesChanged (object sender, System.EventArgs e)
void fillYBox_TextChanged (object sender, System.EventArgs e)
void fillCbBox_TextChanged (object sender, System.EventArgs e)
void fillCrBox_TextChanged (object sender, System.EventArgs e)
void UpdateFillColor ()
void fillTypeCombo_SelectedIndexChanged (object sender, System.EventArgs e)
Private Attributes
YCbCrFiltering filter = new YCbCrFiltering()
Range yRange = new Range(0, 1)
Range cbRange = new Range(-0.5f, 0.5f)
Range crRange = new Range(-0.5f, 0.5f)
float fillY = 0
float fillCb = 0
float fillCr = 0
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Label label1
System.Windows.Forms.TextBox minYBox
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox maxYBox
AForge.Controls.ColorSlider ySlider
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Label label3
System.Windows.Forms.TextBox minCbBox
System.Windows.Forms.Label label4
System.Windows.Forms.TextBox maxCbBox
AForge.Controls.ColorSlider cbSlider
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.Label label5
System.Windows.Forms.Label label6
AForge.Controls.ColorSlider crSlider
System.Windows.Forms.TextBox maxCrBox
System.Windows.Forms.TextBox minCrBox
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.Label label7
System.Windows.Forms.TextBox fillYBox
System.Windows.Forms.Label label8
System.Windows.Forms.TextBox fillCbBox
System.Windows.Forms.Label label9
System.Windows.Forms.TextBox fillCrBox
System.Windows.Forms.GroupBox groupBox5
IPLab.FilterPreview filterPreview
System.Windows.Forms.Label label10
System.Windows.Forms.ComboBox fillTypeCombo
System.Windows.Forms.Button okButton
System.Windows.Forms.Button cancelButton
System.ComponentModel.Container components = null
Required designer variable.
Detailed Description
Summary description for YCbCrFilteringForm.
Constructor & Destructor Documentation
IPLab.YCbCrFilteringForm.YCbCrFilteringForm () inline
References IPLab.YCbCrFilteringForm.fillCb, IPLab.YCbCrFilteringForm.fillCbBox, IPLab.YCbCrFilteringForm.fillCr, IPLab.YCbCrFilteringForm.fillCrBox, IPLab.YCbCrFilteringForm.fillTypeCombo, IPLab.YCbCrFilteringForm.fillYBox, IPLab.YCbCrFilteringForm.filter, IPLab.FilterPreview.Filter, IPLab.YCbCrFilteringForm.filterPreview, IPLab.YCbCrFilteringForm.InitializeComponent(), IPLab.YCbCrFilteringForm.maxCbBox, IPLab.YCbCrFilteringForm.maxCrBox, IPLab.YCbCrFilteringForm.maxYBox, IPLab.YCbCrFilteringForm.minCbBox, IPLab.YCbCrFilteringForm.minCrBox, and IPLab.YCbCrFilteringForm.minYBox.
Member Function Documentation
override void IPLab.YCbCrFilteringForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References IPLab.YCbCrFilteringForm.components.
void IPLab.YCbCrFilteringForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IPLab.YCbCrFilteringForm.YCbCrFilteringForm().
void IPLab.YCbCrFilteringForm.UpdateFilter () inline private
References IPLab.YCbCrFilteringForm.cbRange, IPLab.YCbCrFilteringForm.crRange, IPLab.YCbCrFilteringForm.filterPreview, IPLab.FilterPreview.RefreshFilter(), and IPLab.YCbCrFilteringForm.yRange.
Referenced by IPLab.YCbCrFilteringForm.maxCbBox_TextChanged(), IPLab.YCbCrFilteringForm.maxCrBox_TextChanged(), IPLab.YCbCrFilteringForm.maxYBox_TextChanged(), IPLab.YCbCrFilteringForm.minCbBox_TextChanged(), IPLab.YCbCrFilteringForm.minCrBox_TextChanged(), and IPLab.YCbCrFilteringForm.minYBox_TextChanged().
void IPLab.YCbCrFilteringForm.minYBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrFilteringForm.minYBox, IPLab.YCbCrFilteringForm.UpdateFilter(), and IPLab.YCbCrFilteringForm.ySlider.
void IPLab.YCbCrFilteringForm.maxYBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrFilteringForm.maxYBox, IPLab.YCbCrFilteringForm.UpdateFilter(), and IPLab.YCbCrFilteringForm.ySlider.
void IPLab.YCbCrFilteringForm.minCbBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrFilteringForm.cbSlider, IPLab.YCbCrFilteringForm.minCbBox, and IPLab.YCbCrFilteringForm.UpdateFilter().
void IPLab.YCbCrFilteringForm.maxCbBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrFilteringForm.cbSlider, IPLab.YCbCrFilteringForm.maxCbBox, and IPLab.YCbCrFilteringForm.UpdateFilter().
void IPLab.YCbCrFilteringForm.minCrBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrFilteringForm.crSlider, IPLab.YCbCrFilteringForm.minCrBox, and IPLab.YCbCrFilteringForm.UpdateFilter().
void IPLab.YCbCrFilteringForm.maxCrBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrFilteringForm.crSlider, IPLab.YCbCrFilteringForm.maxCrBox, and IPLab.YCbCrFilteringForm.UpdateFilter().
void IPLab.YCbCrFilteringForm.ySlider_ValuesChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrFilteringForm.maxYBox, IPLab.YCbCrFilteringForm.minYBox, and IPLab.YCbCrFilteringForm.ySlider.
void IPLab.YCbCrFilteringForm.cbSlider_ValuesChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrFilteringForm.cbSlider, IPLab.YCbCrFilteringForm.maxCbBox, and IPLab.YCbCrFilteringForm.minCbBox.
void IPLab.YCbCrFilteringForm.crSlider_ValuesChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrFilteringForm.crSlider, IPLab.YCbCrFilteringForm.maxCrBox, and IPLab.YCbCrFilteringForm.minCrBox.
void IPLab.YCbCrFilteringForm.fillYBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrFilteringForm.fillYBox, and IPLab.YCbCrFilteringForm.UpdateFillColor().
void IPLab.YCbCrFilteringForm.fillCbBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrFilteringForm.fillCb, IPLab.YCbCrFilteringForm.fillCbBox, and IPLab.YCbCrFilteringForm.UpdateFillColor().
void IPLab.YCbCrFilteringForm.fillCrBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrFilteringForm.fillCr, IPLab.YCbCrFilteringForm.fillCrBox, and IPLab.YCbCrFilteringForm.UpdateFillColor().
void IPLab.YCbCrFilteringForm.UpdateFillColor () inline private
References IPLab.YCbCrFilteringForm.fillCb, IPLab.YCbCrFilteringForm.fillCr, IPLab.YCbCrFilteringForm.filterPreview, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.YCbCrFilteringForm.fillCbBox_TextChanged(), IPLab.YCbCrFilteringForm.fillCrBox_TextChanged(), and IPLab.YCbCrFilteringForm.fillYBox_TextChanged().
void IPLab.YCbCrFilteringForm.fillTypeCombo_SelectedIndexChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrFilteringForm.cbSlider, IPLab.YCbCrFilteringForm.crSlider, IPLab.YCbCrFilteringForm.fillTypeCombo, IPLab.YCbCrFilteringForm.filterPreview, IPLab.FilterPreview.RefreshFilter(), and IPLab.YCbCrFilteringForm.ySlider.
Member Data Documentation
YCbCrFiltering IPLab.YCbCrFilteringForm.filter = new YCbCrFiltering() private
Referenced by IPLab.YCbCrFilteringForm.YCbCrFilteringForm().
Range IPLab.YCbCrFilteringForm.yRange = new Range(0, 1) private
Referenced by IPLab.YCbCrFilteringForm.UpdateFilter().
Range IPLab.YCbCrFilteringForm.cbRange = new Range(-0.5f, 0.5f) private
Referenced by IPLab.YCbCrFilteringForm.UpdateFilter().
Range IPLab.YCbCrFilteringForm.crRange = new Range(-0.5f, 0.5f) private
Referenced by IPLab.YCbCrFilteringForm.UpdateFilter().
float IPLab.YCbCrFilteringForm.fillY = 0 private
float IPLab.YCbCrFilteringForm.fillCb = 0 private
Referenced by IPLab.YCbCrFilteringForm.fillCbBox_TextChanged(), IPLab.YCbCrFilteringForm.UpdateFillColor(), and IPLab.YCbCrFilteringForm.YCbCrFilteringForm().
float IPLab.YCbCrFilteringForm.fillCr = 0 private
Referenced by IPLab.YCbCrFilteringForm.fillCrBox_TextChanged(), IPLab.YCbCrFilteringForm.UpdateFillColor(), and IPLab.YCbCrFilteringForm.YCbCrFilteringForm().
System.Windows.Forms.GroupBox IPLab.YCbCrFilteringForm.groupBox1 private
System.Windows.Forms.Label IPLab.YCbCrFilteringForm.label1 private
System.Windows.Forms.TextBox IPLab.YCbCrFilteringForm.minYBox private
Referenced by IPLab.YCbCrFilteringForm.minYBox_TextChanged(), IPLab.YCbCrFilteringForm.YCbCrFilteringForm(), and IPLab.YCbCrFilteringForm.ySlider_ValuesChanged().
System.Windows.Forms.Label IPLab.YCbCrFilteringForm.label2 private
System.Windows.Forms.TextBox IPLab.YCbCrFilteringForm.maxYBox private
Referenced by IPLab.YCbCrFilteringForm.maxYBox_TextChanged(), IPLab.YCbCrFilteringForm.YCbCrFilteringForm(), and IPLab.YCbCrFilteringForm.ySlider_ValuesChanged().
AForge.Controls.ColorSlider IPLab.YCbCrFilteringForm.ySlider private
Referenced by IPLab.YCbCrFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.YCbCrFilteringForm.maxYBox_TextChanged(), IPLab.YCbCrFilteringForm.minYBox_TextChanged(), and IPLab.YCbCrFilteringForm.ySlider_ValuesChanged().
System.Windows.Forms.GroupBox IPLab.YCbCrFilteringForm.groupBox2 private
System.Windows.Forms.Label IPLab.YCbCrFilteringForm.label3 private
System.Windows.Forms.TextBox IPLab.YCbCrFilteringForm.minCbBox private
Referenced by IPLab.YCbCrFilteringForm.cbSlider_ValuesChanged(), IPLab.YCbCrFilteringForm.minCbBox_TextChanged(), and IPLab.YCbCrFilteringForm.YCbCrFilteringForm().
System.Windows.Forms.Label IPLab.YCbCrFilteringForm.label4 private
System.Windows.Forms.TextBox IPLab.YCbCrFilteringForm.maxCbBox private
Referenced by IPLab.YCbCrFilteringForm.cbSlider_ValuesChanged(), IPLab.YCbCrFilteringForm.maxCbBox_TextChanged(), and IPLab.YCbCrFilteringForm.YCbCrFilteringForm().
AForge.Controls.ColorSlider IPLab.YCbCrFilteringForm.cbSlider private
Referenced by IPLab.YCbCrFilteringForm.cbSlider_ValuesChanged(), IPLab.YCbCrFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.YCbCrFilteringForm.maxCbBox_TextChanged(), and IPLab.YCbCrFilteringForm.minCbBox_TextChanged().
System.Windows.Forms.GroupBox IPLab.YCbCrFilteringForm.groupBox3 private
System.Windows.Forms.Label IPLab.YCbCrFilteringForm.label5 private
System.Windows.Forms.Label IPLab.YCbCrFilteringForm.label6 private
AForge.Controls.ColorSlider IPLab.YCbCrFilteringForm.crSlider private
Referenced by IPLab.YCbCrFilteringForm.crSlider_ValuesChanged(), IPLab.YCbCrFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.YCbCrFilteringForm.maxCrBox_TextChanged(), and IPLab.YCbCrFilteringForm.minCrBox_TextChanged().
System.Windows.Forms.TextBox IPLab.YCbCrFilteringForm.maxCrBox private
Referenced by IPLab.YCbCrFilteringForm.crSlider_ValuesChanged(), IPLab.YCbCrFilteringForm.maxCrBox_TextChanged(), and IPLab.YCbCrFilteringForm.YCbCrFilteringForm().
System.Windows.Forms.TextBox IPLab.YCbCrFilteringForm.minCrBox private
Referenced by IPLab.YCbCrFilteringForm.crSlider_ValuesChanged(), IPLab.YCbCrFilteringForm.minCrBox_TextChanged(), and IPLab.YCbCrFilteringForm.YCbCrFilteringForm().
System.Windows.Forms.GroupBox IPLab.YCbCrFilteringForm.groupBox4 private
System.Windows.Forms.Label IPLab.YCbCrFilteringForm.label7 private
System.Windows.Forms.TextBox IPLab.YCbCrFilteringForm.fillYBox private
Referenced by IPLab.YCbCrFilteringForm.fillYBox_TextChanged(), and IPLab.YCbCrFilteringForm.YCbCrFilteringForm().
System.Windows.Forms.Label IPLab.YCbCrFilteringForm.label8 private
System.Windows.Forms.TextBox IPLab.YCbCrFilteringForm.fillCbBox private
Referenced by IPLab.YCbCrFilteringForm.fillCbBox_TextChanged(), and IPLab.YCbCrFilteringForm.YCbCrFilteringForm().
System.Windows.Forms.Label IPLab.YCbCrFilteringForm.label9 private
System.Windows.Forms.TextBox IPLab.YCbCrFilteringForm.fillCrBox private
Referenced by IPLab.YCbCrFilteringForm.fillCrBox_TextChanged(), and IPLab.YCbCrFilteringForm.YCbCrFilteringForm().
System.Windows.Forms.GroupBox IPLab.YCbCrFilteringForm.groupBox5 private
IPLab.FilterPreview IPLab.YCbCrFilteringForm.filterPreview private
Referenced by IPLab.YCbCrFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.YCbCrFilteringForm.UpdateFillColor(), IPLab.YCbCrFilteringForm.UpdateFilter(), and IPLab.YCbCrFilteringForm.YCbCrFilteringForm().
System.Windows.Forms.Label IPLab.YCbCrFilteringForm.label10 private
System.Windows.Forms.ComboBox IPLab.YCbCrFilteringForm.fillTypeCombo private
Referenced by IPLab.YCbCrFilteringForm.fillTypeCombo_SelectedIndexChanged(), and IPLab.YCbCrFilteringForm.YCbCrFilteringForm().
System.Windows.Forms.Button IPLab.YCbCrFilteringForm.okButton private
System.Windows.Forms.Button IPLab.YCbCrFilteringForm.cancelButton private
System.ComponentModel.Container IPLab.YCbCrFilteringForm.components = null private
Required designer variable.
Referenced by IPLab.YCbCrFilteringForm.Dispose().
Property Documentation
Bitmap IPLab.YCbCrFilteringForm.Image set
Referenced by IPLab.ImageDoc.filteringYCbCrFiltersItem_Click().
IFilter IPLab.YCbCrFilteringForm.Filter get
Referenced by IPLab.ImageDoc.filteringYCbCrFiltersItem_Click().
The documentation for this class was generated from the following file:
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/YCbCrFilteringForm.cs