IGLib: alglib.mcpd Class Reference
alglib.mcpd Class Reference
Classes
class mcpdreport
class mcpdstate
Static Public Member Functions
static void mcpdcreate (int n, mcpdstate s)
static void mcpdcreateentry (int n, int entrystate, mcpdstate s)
static void mcpdcreateexit (int n, int exitstate, mcpdstate s)
static void mcpdcreateentryexit (int n, int entrystate, int exitstate, mcpdstate s)
static void mcpdaddtrack (mcpdstate s, double[,] xy, int k)
static void mcpdsetec (mcpdstate s, double[,] ec)
static void mcpdaddec (mcpdstate s, int i, int j, double c)
static void mcpdsetbc (mcpdstate s, double[,] bndl, double[,] bndu)
static void mcpdaddbc (mcpdstate s, int i, int j, double bndl, double bndu)
static void mcpdsetlc (mcpdstate s, double[,] c, int[] ct, int k)
static void mcpdsettikhonovregularizer (mcpdstate s, double v)
static void mcpdsetprior (mcpdstate s, double[,] pp)
static void mcpdsetpredictionweights (mcpdstate s, double[] pw)
static void mcpdsolve (mcpdstate s)
static void mcpdresults (mcpdstate s, ref double[,] p, mcpdreport rep)
static void mcpdcreate (int n, mcpdstate s)
static void mcpdcreateentry (int n, int entrystate, mcpdstate s)
static void mcpdcreateexit (int n, int exitstate, mcpdstate s)
static void mcpdcreateentryexit (int n, int entrystate, int exitstate, mcpdstate s)
static void mcpdaddtrack (mcpdstate s, double[,] xy, int k)
static void mcpdsetec (mcpdstate s, double[,] ec)
static void mcpdaddec (mcpdstate s, int i, int j, double c)
static void mcpdsetbc (mcpdstate s, double[,] bndl, double[,] bndu)
static void mcpdaddbc (mcpdstate s, int i, int j, double bndl, double bndu)
static void mcpdsetlc (mcpdstate s, double[,] c, int[] ct, int k)
static void mcpdsettikhonovregularizer (mcpdstate s, double v)
static void mcpdsetprior (mcpdstate s, double[,] pp)
static void mcpdsetpredictionweights (mcpdstate s, double[] pw)
static void mcpdsolve (mcpdstate s)
static void mcpdresults (mcpdstate s, ref double[,] p, mcpdreport rep)
Public Attributes
const double xtol = 1.0E-8
Static Private Member Functions
static void mcpdinit (int n, int entrystate, int exitstate, mcpdstate s)
static void mcpdinit (int n, int entrystate, int exitstate, mcpdstate s)
Member Function Documentation
static void alglib.mcpd.mcpdcreate (int n, mcpdstate s) inline static
References alglib.ap.assert(), and alglib.mcpd.mcpdinit().
Referenced by alglib.testmcpdunit.createee(), alglib.mcpdcreate(), alglib.testmcpdunit.testentryexit(), and alglib.testmcpdunit.testsimple().
static void alglib.mcpd.mcpdcreateentry (int n, int entrystate, mcpdstate s) inline static
References alglib.ap.assert().
Referenced by alglib.testmcpdunit.createee(), alglib.mcpdcreateentry(), and alglib.testmcpdunit.testentryexit().
static void alglib.mcpd.mcpdcreateexit (int n, int exitstate, mcpdstate s) inline static
Referenced by alglib.testmcpdunit.createee(), alglib.mcpdcreateexit(), and alglib.testmcpdunit.testentryexit().
static void alglib.mcpd.mcpdcreateentryexit (int n, int entrystate, int exitstate, mcpdstate s) inline static
Referenced by alglib.testmcpdunit.createee(), alglib.mcpdcreateentryexit(), and alglib.testmcpdunit.testentryexit().
static void alglib.mcpd.mcpdaddtrack (mcpdstate s, double xy[,], int k) inline static
Referenced by alglib.mcpdaddtrack(), alglib.testmcpdunit.testbc(), alglib.testmcpdunit.testec(), alglib.testmcpdunit.testentryexit(), alglib.testmcpdunit.testlc(), and alglib.testmcpdunit.testsimple().
static void alglib.mcpd.mcpdsetec (mcpdstate s, double ec[,]) inline static
Referenced by alglib.mcpdsetec(), and alglib.testmcpdunit.testec().
static void alglib.mcpd.mcpdaddec (mcpdstate s, int i, int j, double c) inline static
Referenced by alglib.mcpdaddec(), and alglib.testmcpdunit.testec().
static void alglib.mcpd.mcpdsetbc (mcpdstate s, double bndl[,], double bndu[,]) inline static
Referenced by alglib.mcpdsetbc(), and alglib.testmcpdunit.testbc().
static void alglib.mcpd.mcpdaddbc (mcpdstate s, int i, int j, double bndl, double bndu) inline static
Referenced by alglib.mcpdaddbc(), and alglib.testmcpdunit.testbc().
static void alglib.mcpd.mcpdsetlc (mcpdstate s, double c[,], int[] ct, int k) inline static
Referenced by alglib.mcpdsetlc(), and alglib.testmcpdunit.testlc().
static void alglib.mcpd.mcpdsettikhonovregularizer (mcpdstate s, double v) inline static
Referenced by alglib.mcpdsettikhonovregularizer().
static void alglib.mcpd.mcpdsetprior (mcpdstate s, double pp[,]) inline static
Referenced by alglib.mcpdsetprior().
static void alglib.mcpd.mcpdsetpredictionweights (mcpdstate s, double[] pw) inline static
Referenced by alglib.mcpdsetpredictionweights().
static void alglib.mcpd.mcpdsolve (mcpdstate s) inline static
Referenced by alglib.mcpdsolve(), alglib.testmcpdunit.testbc(), alglib.testmcpdunit.testec(), alglib.testmcpdunit.testentryexit(), alglib.testmcpdunit.testlc(), and alglib.testmcpdunit.testsimple().
static void alglib.mcpd.mcpdresults (mcpdstate s, ref double p[,], mcpdreport rep) inline static
Referenced by alglib.mcpdresults(), alglib.testmcpdunit.testbc(), alglib.testmcpdunit.testec(), alglib.testmcpdunit.testentryexit(), alglib.testmcpdunit.testlc(), and alglib.testmcpdunit.testsimple().
static void alglib.mcpd.mcpdinit (int n, int entrystate, int exitstate, mcpdstate s) inline static private
Referenced by alglib.mcpd.mcpdcreate().
static void alglib.mcpd.mcpdcreate (int n, mcpdstate s) inline static
static void alglib.mcpd.mcpdcreateentry (int n, int entrystate, mcpdstate s) inline static
static void alglib.mcpd.mcpdcreateexit (int n, int exitstate, mcpdstate s) inline static
static void alglib.mcpd.mcpdcreateentryexit (int n, int entrystate, int exitstate, mcpdstate s) inline static
static void alglib.mcpd.mcpdaddtrack (mcpdstate s, double xy[,], int k) inline static
static void alglib.mcpd.mcpdsetec (mcpdstate s, double ec[,]) inline static
static void alglib.mcpd.mcpdaddec (mcpdstate s, int i, int j, double c) inline static
static void alglib.mcpd.mcpdsetbc (mcpdstate s, double bndl[,], double bndu[,]) inline static
static void alglib.mcpd.mcpdaddbc (mcpdstate s, int i, int j, double bndl, double bndu) inline static
static void alglib.mcpd.mcpdsetlc (mcpdstate s, double c[,], int[] ct, int k) inline static
static void alglib.mcpd.mcpdsettikhonovregularizer (mcpdstate s, double v) inline static
static void alglib.mcpd.mcpdsetprior (mcpdstate s, double pp[,]) inline static
static void alglib.mcpd.mcpdsetpredictionweights (mcpdstate s, double[] pw) inline static
static void alglib.mcpd.mcpdsolve (mcpdstate s) inline static
static void alglib.mcpd.mcpdresults (mcpdstate s, ref double p[,], mcpdreport rep) inline static
static void alglib.mcpd.mcpdinit (int n, int entrystate, int exitstate, mcpdstate s) inline static private
Member Data Documentation
const double alglib.mcpd.xtol = 1.0E-8
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/dataanalysis.cs