IGLib: IG.Old.XVector Class Reference
IG.Old.XVector Class Reference
Class that is directly derived from MathNet.Numerics.LinearAlgebra.Vector
Public Member Functions
XVector (int n)
Constructs an d2-dimensional vector of zeros.
XVector (int n, int i)
Constructs an d2-dimensional unit vector for i'th coordinate.
XVector (int n, double value)
Constructs an d2-dimensional constant vector.
XVector (double[] components)
Constructs a vector from a 1-D array, directly using the provided array as internal data structure.
override string ToString ()
Returns a string representation of this vector in a standard IGLib form.
void Resize (int newsize)
void AddInplace (XVector v2)
In-place vector addition.
XVector Add (XVector v2)
In-place vector addition.
IVector_OldNumerics< double > GetCopy ()
double FirstComponent ()
Public Member Functions inherited from IG.Old.IVector_OldNumerics< T >
T[] CopyToArray ()
Copy all elements of this vector to an array.
Static Public Member Functions
static new XVector Create (double[] components)
Constructs a vector from a copy of a 1-D array.
static new XVector Random (int n, IContinuousGenerator randomDistribution)
Generates vector with random elements.
static new XVector Random (int n)
Generates vector with random elements uniformly distributed on [0, 1).
static new XVector Ones (int n)
Generates an d2-dimensional vector filled with 1.
static new XVector Zeros (int n)
Generates an d2-dimensional vector filled with 0.
static new XVector BasisVector (int n, int i)
Generates an d2-dimensional unit vector for i-th coordinate.
static void Examples ()
Static Protected Member Functions
static void AddRaw (MathNet.Numerics.LinearAlgebra.Vector v1, MathNet.Numerics.LinearAlgebra.Vector v2, MathNet.Numerics.LinearAlgebra.Vector result)
Raw vector addition.
Additional Inherited Members
Properties inherited from IG.Old.IVector_OldNumerics< T >
int Length [get]
Gets the number of rows.
T this[int i] [get, set]
Gets or set the element indexed by i in the Vector.
Detailed Description
Class that is directly derived from MathNet.Numerics.LinearAlgebra.Vector
Constructor & Destructor Documentation
IG.Old.XVector.XVector (int n) inline
Constructs an d2-dimensional vector of zeros.
Parameters
d2 Dimensionality of vector.
IG.Old.XVector.XVector (int n, int i) inline
Constructs an d2-dimensional unit vector for i'th coordinate.
Parameters
d2 Dimensionality of vector.
i Coordinate index.
IG.Old.XVector.XVector (int n, double value) inline
Constructs an d2-dimensional constant vector.
Parameters
d2 Dimensionality of vector.
value Fill the vector with this scalar value.
IG.Old.XVector.XVector (double[] components) inline
Constructs a vector from a 1-D array, directly using the provided array as internal data structure.
Parameters
vec One-dimensional array of doubles.
See also
Create
Member Function Documentation
static new XVector IG.Old.XVector.Create (double[] components) inline static
Constructs a vector from a copy of a 1-D array.
static new XVector IG.Old.XVector.Random (int n, IContinuousGenerator randomDistribution) inline static
Generates vector with random elements.
Parameters
d2 Dimensionality of vector.
randomDistribution Continuous Random Distribution or Source
Returns
An d2-dimensional vector with random elements distributed according to the specified random distribution.
static new XVector IG.Old.XVector.Random (int n) inline static
Generates vector with random elements uniformly distributed on [0, 1).
Parameters
d2 Dimensionality of vector.
Returns
An d2-dimensional vector with uniformly distributedrandom elements in [0, 1) interval.
static new XVector IG.Old.XVector.Ones (int n) inline static
Generates an d2-dimensional vector filled with 1.
Parameters
d2 Dimensionality of vector.
Referenced by IG.Old.XVector.Examples().
static new XVector IG.Old.XVector.Zeros (int n) inline static
Generates an d2-dimensional vector filled with 0.
Parameters
d2 Dimensionality of vector.
static new XVector IG.Old.XVector.BasisVector (int n, int i) inline static
Generates an d2-dimensional unit vector for i-th coordinate.
Parameters
d2 Dimensionality of vector.
i Coordinate index.
override string IG.Old.XVector.ToString () inline
Returns a string representation of this vector in a standard IGLib form.
Referenced by IG.Old.XVector.Examples().
void IG.Old.XVector.Resize (int newsize) inline
static void IG.Old.XVector.AddRaw (MathNet.Numerics.LinearAlgebra.Vector v1, MathNet.Numerics.LinearAlgebra.Vector v2, MathNet.Numerics.LinearAlgebra.Vector result) inline static protected
Raw vector addition.
Parameters
v1 Left summand.
v2 Right Summand.
result Result.
void IG.Old.XVector.AddInplace (XVector v2) inline
In-place vector addition.
XVector IG.Old.XVector.Add (XVector v2) inline
In-place vector addition.
IVector_OldNumerics<double> IG.Old.XVector.GetCopy () inline
double IG.Old.XVector.FirstComponent () inline
Referenced by IG.Old.XVector.Examples().
static void IG.Old.XVector.Examples () inline static
References IG.Old.XVector.FirstComponent(), IG.Old.XVector.Ones(), and IG.Old.XVector.ToString().
The documentation for this class was generated from the following file:
igtest/IGLibTestDevExt/z_old/matrix_old/MatrixExtMathNet.cs