IGLib: Test.RectangularMatrixTest Class Reference
Test.RectangularMatrixTest Class Reference
Public Member Functions
void RectangularMatrixAccess ()
void RectangularMatrixEquality ()
void RectangularMatrixArithmetic ()
void RectangularQRDecomposition ()
void RectangularMatrixNorms ()
void RandomRectangularSVD ()
void PC ()
void SmallSVD ()
void MatrixSelfMultiplication ()
void MatrixArrayConversion ()
Properties
TestContext TestContext [get, set]
Private Member Functions
RectangularMatrix GenerateRandomMatrix (int rd, int cd)
void WriteMatrix (AnyRectangularMatrix A)
Private Attributes
TestContext testContextInstance
Member Function Documentation
RectangularMatrix Test.RectangularMatrixTest.GenerateRandomMatrix (int rd, int cd) inline private
Referenced by Test.RectangularMatrixTest.MatrixSelfMultiplication(), Test.RectangularMatrixTest.RandomRectangularSVD(), Test.RectangularMatrixTest.RectangularMatrixArithmetic(), Test.RectangularMatrixTest.RectangularMatrixNorms(), and Test.RectangularMatrixTest.RectangularQRDecomposition().
void Test.RectangularMatrixTest.RectangularMatrixAccess () inline
References Meta.Numerics.Matrices.AnyRectangularMatrix.Column(), Meta.Numerics.Matrices.RectangularMatrix.ColumnCount, Meta.Numerics.Matrices.RectangularMatrix.Copy(), Meta.Numerics.Matrices.VectorBase.Dimension, Meta.Numerics.Matrices.AnyRectangularMatrix.Row(), and Meta.Numerics.Matrices.RectangularMatrix.RowCount.
void Test.RectangularMatrixTest.RectangularMatrixEquality () inline
References Meta.Numerics.Matrices.RectangularMatrix.Copy(), and Meta.Numerics.Matrices.AnyRectangularMatrix.Equals().
void Test.RectangularMatrixTest.RectangularMatrixArithmetic () inline
References Meta.Numerics.Matrices.RectangularMatrix.ColumnCount, Test.RectangularMatrixTest.GenerateRandomMatrix(), Meta.Numerics.Matrices.RectangularMatrix.RowCount, and Meta.Numerics.Matrices.RectangularMatrix.Transpose().
void Test.RectangularMatrixTest.RectangularQRDecomposition () inline
References Meta.Numerics.Matrices.RectangularMatrix.ColumnCount, Meta.Numerics.Matrices.QRDecomposition.ColumnCount, Meta.Numerics.Matrices.SquareMatrix.Dimension, Test.RectangularMatrixTest.GenerateRandomMatrix(), Meta.Numerics.Matrices.QRDecomposition.QMatrix(), Meta.Numerics.Matrices.RectangularMatrix.QRDecomposition(), Meta.Numerics.Matrices.QRDecomposition.RMatrix(), Meta.Numerics.Matrices.RectangularMatrix.RowCount, Meta.Numerics.Matrices.QRDecomposition.RowCount, and Meta.Numerics.Matrices.SquareMatrix.Transpose().
void Test.RectangularMatrixTest.WriteMatrix (AnyRectangularMatrix A) inline private
References Meta.Numerics.Matrices.AnyMatrix< T >.ColumnCount, and Meta.Numerics.Matrices.AnyMatrix< T >.RowCount.
void Test.RectangularMatrixTest.RectangularMatrixNorms () inline
References Meta.Numerics.Matrices.AnyRectangularMatrix.FrobeniusNorm(), Test.RectangularMatrixTest.GenerateRandomMatrix(), Meta.Numerics.Matrices.RectangularMatrix.InfinityNorm(), and Meta.Numerics.Matrices.RectangularMatrix.OneNorm().
void Test.RectangularMatrixTest.RandomRectangularSVD () inline
References Meta.Numerics.Matrices.SingularValueDecomposition.ColumnCount, Meta.Numerics.Matrices.RectangularMatrix.ColumnCount, Meta.Numerics.Matrices.SquareMatrix.Dimension, Meta.Numerics.Matrices.SingularValueDecomposition.Dimension, Test.RectangularMatrixTest.GenerateRandomMatrix(), Meta.Numerics.Matrices.SingularValueDecomposition.LeftSingularVector(), Meta.Numerics.Matrices.SingularValueDecomposition.LeftTransformMatrix(), Meta.Numerics.Matrices.SingularValueDecomposition.RightSingularVector(), Meta.Numerics.Matrices.SingularValueDecomposition.RightTransformMatrix(), Meta.Numerics.Matrices.SingularValueDecomposition.RowCount, Meta.Numerics.Matrices.RectangularMatrix.RowCount, Meta.Numerics.Matrices.SingularValueDecomposition.SingularValue(), Meta.Numerics.Matrices.RectangularMatrix.SingularValueDecomposition(), and Meta.Numerics.Matrices.SquareMatrix.Transpose().
void Test.RectangularMatrixTest.PC () inline
References Meta.Numerics.Statistics.MultivariateSample.Add(), Meta.Numerics.Statistics.MultivariateSample.Column(), Meta.Numerics.Statistics.PrincipalComponentAnalysis.Component(), Meta.Numerics.Statistics.PrincipalComponentAnalysis.Count, Meta.Numerics.Statistics.PrincipalComponent.CumulativeVarianceFraction, Meta.Numerics.Statistics.PrincipalComponentAnalysis.Dimension, Meta.Numerics.Matrices.SingularValueDecomposition.Dimension, Meta.Numerics.Statistics.MultivariateSample.GetEnumerator(), Meta.Numerics.Statistics.PrincipalComponent.Index, Meta.Numerics.Matrices.SingularValueDecomposition.LeftTransformMatrix(), Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.PrincipalComponent.NormalizedVector(), Meta.Numerics.Statistics.MultivariateSample.PrincipalComponentAnalysis(), Meta.Numerics.Matrices.SingularValueDecomposition.RightSingularVector(), Meta.Numerics.Matrices.SingularValueDecomposition.RightTransformMatrix(), Meta.Numerics.Matrices.SingularValueDecomposition.SingularValue(), Meta.Numerics.Matrices.RectangularMatrix.SingularValueDecomposition(), Meta.Numerics.Statistics.PrincipalComponentAnalysis.TransformedSample(), Meta.Numerics.Statistics.Sample.Variance, Meta.Numerics.Statistics.PrincipalComponent.VarianceFraction, and Meta.Numerics.Statistics.PrincipalComponent.Weight.
void Test.RectangularMatrixTest.SmallSVD () inline
References Meta.Numerics.Matrices.SingularValueDecomposition.Dimension, Meta.Numerics.Matrices.SingularValueDecomposition.LeftTransformMatrix(), Meta.Numerics.Matrices.SingularValueDecomposition.RightTransformMatrix(), Meta.Numerics.Matrices.SingularValueDecomposition.SingularValue(), Meta.Numerics.Matrices.SquareMatrix.SingularValueDecomposition(), and Meta.Numerics.Matrices.SquareMatrix.Transpose().
void Test.RectangularMatrixTest.MatrixSelfMultiplication () inline
References Test.RectangularMatrixTest.GenerateRandomMatrix(), Meta.Numerics.Matrices.AnyRectangularMatrix.MultiplySelfByTranspose(), Meta.Numerics.Matrices.AnyRectangularMatrix.MultiplyTransposeBySelf(), and Meta.Numerics.Matrices.RectangularMatrix.Transpose().
void Test.RectangularMatrixTest.MatrixArrayConversion () inline
References Meta.Numerics.Matrices.RectangularMatrix.ColumnCount, Meta.Numerics.Matrices.RectangularMatrix.RowCount, and Meta.Numerics.Matrices.AnyMatrix< T >.ToArray().
Member Data Documentation
TestContext Test.RectangularMatrixTest.testContextInstance private
Property Documentation
TestContext Test.RectangularMatrixTest.TestContext get set
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/RectangularMatrixTest.cs