IGLib: IG.Old.SpeedTestCpuOld Class Reference
IG.Old.SpeedTestCpuOld Class Reference
Various utilities for testing computational speed of the current system - Old version!
Static Public Member Functions
static double TestComputationalTimesLU_MathNet (int numEq, int outLevel)
Test of LU decomposition.
static double TestComputationalTimesLU_MathNet (int numEq, int outLevel, bool testProduct)
Test of LU decomposition.
static double TestComputationalTimesQR_MathNet (int numEq, int outLevel)
Test of QR decomposition. Writes times necessary for all steps.
static double TestComputationalTimesQR_MathNet (int numEq, int outLevel, bool testProduct)
Test of QR decomposition. Writes times necessary for all steps.
Detailed Description
Various utilities for testing computational speed of the current system - Old version!
$A Igor xx Feb08;
Member Function Documentation
static double IG.Old.SpeedTestCpuOld.TestComputationalTimesLU_MathNet (int numEq, int outLevel) inline static
Test of LU decomposition.
Parameters
outLevel Level of output.
numEq Number of equations to be solved with decomposition.
Returns
Total wallclock time (in seconds) spent for the test.
Referenced by IG.Script.Script_Numeric.TestMatrixOperations().
static double IG.Old.SpeedTestCpuOld.TestComputationalTimesLU_MathNet (int numEq, int outLevel, bool testProduct) inline static
Test of LU decomposition.
Parameters
outLevel Level of output.
numEq Number of equations to be solved with decomposition.
testProduct If true then it is tested if the product of factors gives the original matrix. Otherwise, this test is skipped.
Returns
Total wallclock time (in seconds) spent for the test.
References IG.Lib.StopWatch1.CpuTime, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Lib.StopWatch1.TotalCpuTime, and IG.Lib.StopWatch1.TotalTime.
static double IG.Old.SpeedTestCpuOld.TestComputationalTimesQR_MathNet (int numEq, int outLevel) inline static
Test of QR decomposition. Writes times necessary for all steps.
This method does not perform test of decomposition (comparison of product of factors with the original matrix).
Parameters
numEq Number of equations to be solved with decomposition.
outLevel Level of output.
Returns
Total time spent for all operations.
Referenced by IG.Script.Script_Numeric.TestMatrixOperations().
static double IG.Old.SpeedTestCpuOld.TestComputationalTimesQR_MathNet (int numEq, int outLevel, bool testProduct) inline static
Test of QR decomposition. Writes times necessary for all steps.
Parameters
numEq Number of equations to be solved with decomposition.
outLevel Level of output.
testProduct If true then it is tested if the product of factors gives the original matrix. Otherwise, this test is skipped.
Returns
Total time spent for all operations.
References IG.Lib.StopWatch1.CpuTime, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Lib.StopWatch1.TotalCpuTime, and IG.Lib.StopWatch1.TotalTime.
The documentation for this class was generated from the following file:
igtest/IGLibTestDevExt/z_old/matrix_old/TestSpeedOld.cs