IGLib: IG.Neural.NeuralTrainingResultsPlotter Class Reference
IG.Neural.NeuralTrainingResultsPlotter Class Reference
Plotter class for neural training results.
Public Member Functions
NeuralTrainingResultsPlotter (NeuralTrainingParameters results)
Constructs a new training results plotter for plotting the specified training results.
virtual void ApplyPlotSettingsCurveRGB (PlotterZedGraph plotter, PlotZedgraphCurve plot, double r, double g, double b)
Applies basic plot settings for basic kinds of curve plots where groups of curves are plotted.
virtual void ApplyPlotSettingsConvergence (PlotterZedGraph plotter, PlotZedgraphCurve plot, int whichOutput, int numOutputs)
Applies basic plot settings for basic kinds of curve plots.
Static Public Member Functions
static void PlotCompleteConvergence (NeuralTrainingParameters results)
static void PlotCompleteConvergenceMax (NeuralTrainingParameters results)
static void PlotCompleteConvergenceRms (NeuralTrainingParameters results)
static void ExampleConvergence (NeuralTrainingParameters results)
Protected Member Functions
virtual void PlotConvergenceTrainingRms (int whichOutput)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceTrainingRms (int whichOutput, string errorsName, string outputName)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceTrainingMax (int whichOutput)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceTrainingMax (int whichOutput, string errorsName, string outputName)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceVerificationRms (int whichOutput)
Plots a convergence plot for the specified list of errors of the current verification results.
virtual void PlotConvergenceVerificationRms (int whichOutput, string errorsName, string outputName)
Plots a convergence plot for the specified list of errors of the current verification results.
virtual void PlotConvergenceVerificationMax (int whichOutput)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceVerificationMax (int whichOutput, string errorsName, string outputName)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergence (List< IVector > errors, int whichOutput, string errorName, string outputName)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceMax (int whichOutput)
Plots a convergence plot for all maximum lists of errors of the current training results.
virtual void PlotConvergenceMax (int whichOutput, string outputName)
Plots a convergence plot all maximum lists of errors of the current training results.
virtual void PlotConvergenceRms (int whichOutput)
Plots a convergence plot for Rms lists of errors of the current training results.
virtual void PlotConvergenceRms (int whichOutput, string outputName)
Plots a convergence plot for the Rms lists of errors of the current training results.
Protected Attributes
NeuralTrainingParameters _results
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
static InputOutputDataDefiniton DataDefinition [get, set]
Definitions of input and output data.
virtual NeuralTrainingParameters Results [get, protected set]
Training results that are used for plotting.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Member Functions
NeuralTrainingResultsPlotter ()
Prevent argumentless constructor.
Private Attributes
object _mainLock = new object()
Static Private Attributes
static InputOutputDataDefiniton _dataDefinition = null
Detailed Description
Plotter class for neural training results.
$A Igor Sep12; Tako78 Sep12;
Constructor & Destructor Documentation
IG.Neural.NeuralTrainingResultsPlotter.NeuralTrainingResultsPlotter () inline private
Prevent argumentless constructor.
IG.Neural.NeuralTrainingResultsPlotter.NeuralTrainingResultsPlotter (NeuralTrainingParameters results) inline
Constructs a new training results plotter for plotting the specified training results.
Parameters
results Parameters and results of the training procedure.
Member Function Documentation
virtual void IG.Neural.NeuralTrainingResultsPlotter.ApplyPlotSettingsCurveRGB (PlotterZedGraph plotter, PlotZedgraphCurve plot, double r, double g, double b) inline virtual
Applies basic plot settings for basic kinds of curve plots where groups of curves are plotted.
Parameters
plotter Plotter used for plotting graphs for which settings are set.
plot Plot that contains graphic objects.
r Index for red collor.
g Index for green collor.
b Index for blue collor.
$A Tako78 Sep12;
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointColor, IG.Gr.PlotZedgraphCurve.PointSize, and IG.Gr.PlotZedgraphCurve.PointTypeSymbol.
virtual void IG.Neural.NeuralTrainingResultsPlotter.ApplyPlotSettingsConvergence (PlotterZedGraph plotter, PlotZedgraphCurve plot, int whichOutput, int numOutputs) inline virtual
Applies basic plot settings for basic kinds of curve plots.
Parameters
plotter Plotter used for plotting graphs for which settings are set.
plot Curve plot that contains graphic objects.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointColor, IG.Gr.PlotZedgraphCurve.PointSize, and IG.Gr.PlotZedgraphCurve.PointTypeSymbol.
virtual void IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceTrainingRms (int whichOutput) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
Referenced by IG.Neural.NeuralTrainingResultsPlotter.ExampleConvergence(), and IG.Neural.NeuralTrainingResultsPlotter.PlotCompleteConvergence().
virtual void IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceTrainingRms (int whichOutput, string errorsName, string outputName) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
errorsName Name of errors used as label on the graph's vertical axis. If not specified then a default name is used./param>
References IG.Num.NeuralTrainingParameters.ErrorsTrainingRmsList.
virtual void IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceTrainingMax (int whichOutput) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
Referenced by IG.Neural.NeuralTrainingResultsPlotter.PlotCompleteConvergence().
virtual void IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceTrainingMax (int whichOutput, string errorsName, string outputName) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
errorsName Name of errors used as label on the graph's vertical axis. If not specified then a default name is used.
References IG.Num.NeuralTrainingParameters.ErrorsTrainingMaxList.
virtual void IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceVerificationRms (int whichOutput) inline protected virtual
Plots a convergence plot for the specified list of errors of the current verification results.
Parameters
whichOutput Specifies for which output errors are plotted.
Referenced by IG.Neural.NeuralTrainingResultsPlotter.PlotCompleteConvergence().
virtual void IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceVerificationRms (int whichOutput, string errorsName, string outputName) inline protected virtual
Plots a convergence plot for the specified list of errors of the current verification results.
Parameters
whichOutput Specifies for which output errors are plotted.
errorsName Name of errors used as label on the graph's vertical axis. If not specified then a default name is used./param> $A Tako78 Sep12;
References IG.Num.NeuralTrainingParameters.ErrorsVerificationMaxList.
virtual void IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceVerificationMax (int whichOutput) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
Referenced by IG.Neural.NeuralTrainingResultsPlotter.PlotCompleteConvergence().
virtual void IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceVerificationMax (int whichOutput, string errorsName, string outputName) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
errorsName Name of errors used as label on the graph's vertical axis. If not specified then a default name is used.
References IG.Num.NeuralTrainingParameters.ErrorsTrainingMaxList.
virtual void IG.Neural.NeuralTrainingResultsPlotter.PlotConvergence (List< IVector > errors, int whichOutput, string errorName, string outputName) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
errors List of errors that are plotter, must be consistent with Results.
whichOutput Specifies for which output errors are plotted.
errorName Name of errors used as label on the graph's vertical axis. If not specified then a default name is used.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Gr.PlotterZedGraph.CreateDefault(), IG.Num.NeuralTrainingParameters.EpochNumbers, IG.Gr.ZedGraphWindow.GraphControl, IG.Num.NeuralTrainingParameters.IsNetworkTrained, IG.Num.NeuralTrainingParameters.OutputLength, IG.Gr.PlotterZedGraph.Title, IG.Gr.PlotterZedGraph.Update(), IG.Gr.PlotterZedGraph.XAxisLabel, IG.Gr.PlotterZedGraph.YAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabelFont.
virtual void IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceMax (int whichOutput) inline protected virtual
Plots a convergence plot for all maximum lists of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
$A Tako78 Sep12;
Referenced by IG.Neural.NeuralTrainingResultsPlotter.PlotCompleteConvergenceMax().
virtual void IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceMax (int whichOutput, string outputName) inline protected virtual
Plots a convergence plot all maximum lists of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
outputName Name of errors used as label on the graph's vertical axis. If not specified then a default name is used.
$A Tako78 Sep12;
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Gr.PlotterZedGraph.CreateDefault(), IG.Num.NeuralTrainingParameters.EpochNumbers, IG.Num.NeuralTrainingParameters.ErrorsTrainingMaxList, IG.Num.NeuralTrainingParameters.ErrorsVerificationMaxList, IG.Gr.ZedGraphWindow.GraphControl, IG.Num.NeuralTrainingParameters.IsNetworkTrained, IG.Gr.PlotZedGraphBase.LegendString, IG.Num.NeuralTrainingParameters.OutputLength, IG.Gr.PlotZedgraphCurve.PointTypeSymbol, IG.Gr.PlotterZedGraph.Title, IG.Gr.PlotterZedGraph.Update(), IG.Gr.PlotterZedGraph.XAxisLabel, IG.Gr.PlotterZedGraph.YAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabelFont.
virtual void IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceRms (int whichOutput) inline protected virtual
Plots a convergence plot for Rms lists of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
$A Tako78 Sep12;
Referenced by IG.Neural.NeuralTrainingResultsPlotter.PlotCompleteConvergenceRms().
virtual void IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceRms (int whichOutput, string outputName) inline protected virtual
Plots a convergence plot for the Rms lists of errors of the current training results.
<
Parameters
whichOutput Specifies for which output errors are plotted.
errorName Name of errors used as label on the graph's vertical axis.
outputName Name of errors used as label on the graph's vertical axis.
If not specified then a default name is used.
$A Tako78 Sep12;
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Gr.PlotterZedGraph.CreateDefault(), IG.Num.NeuralTrainingParameters.EpochNumbers, IG.Num.NeuralTrainingParameters.ErrorsTrainingRmsList, IG.Num.NeuralTrainingParameters.ErrorsVerificationRmsList, IG.Gr.ZedGraphWindow.GraphControl, IG.Num.NeuralTrainingParameters.IsNetworkTrained, IG.Gr.PlotZedGraphBase.LegendString, IG.Num.NeuralTrainingParameters.OutputLength, IG.Gr.PlotZedgraphCurve.PointTypeSymbol, IG.Gr.PlotterZedGraph.Title, IG.Gr.PlotterZedGraph.Update(), IG.Gr.PlotterZedGraph.XAxisLabel, IG.Gr.PlotterZedGraph.YAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabelFont.
static void IG.Neural.NeuralTrainingResultsPlotter.PlotCompleteConvergence (NeuralTrainingParameters results) inline static
References IG.Num.NeuralTrainingParameters.OutputLength, IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceTrainingMax(), IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceTrainingRms(), IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceVerificationMax(), and IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceVerificationRms().
static void IG.Neural.NeuralTrainingResultsPlotter.PlotCompleteConvergenceMax (NeuralTrainingParameters results) inline static
References IG.Num.NeuralTrainingParameters.OutputLength, and IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceMax().
static void IG.Neural.NeuralTrainingResultsPlotter.PlotCompleteConvergenceRms (NeuralTrainingParameters results) inline static
References IG.Num.NeuralTrainingParameters.OutputLength, and IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceRms().
static void IG.Neural.NeuralTrainingResultsPlotter.ExampleConvergence (NeuralTrainingParameters results) inline static
References IG.Num.NeuralTrainingParameters.OutputLength, and IG.Neural.NeuralTrainingResultsPlotter.PlotConvergenceTrainingRms().
Member Data Documentation
object IG.Neural.NeuralTrainingResultsPlotter._mainLock = new object() private
InputOutputDataDefiniton IG.Neural.NeuralTrainingResultsPlotter._dataDefinition = null static private
NeuralTrainingParameters IG.Neural.NeuralTrainingResultsPlotter._results protected
Property Documentation
object IG.Neural.NeuralTrainingResultsPlotter.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
InputOutputDataDefiniton IG.Neural.NeuralTrainingResultsPlotter.DataDefinition static get set
Definitions of input and output data.
$A Tako78 Sep12;
Referenced by IG.Script.LoadableScriptShellNeuralIT.PlotTrainingTime().
virtual NeuralTrainingParameters IG.Neural.NeuralTrainingResultsPlotter.Results get protected set
Training results that are used for plotting.
The documentation for this class was generated from the following file:
shelldev/lib/extended/LibNeuralExt/scripts_presentation/NeuralTrainingResultsPlotter.cs