IGLib: NUnit.Framework.Constraints.ReusableConstraintTests Class Reference
NUnit.Framework.Constraints.ReusableConstraintTests Class Reference
Public Member Functions
void CanReuseReusableConstraintMultipleTimes (ReusableConstraint c)
void CanCreateReusableConstraintByImplicitConversion ()
Static Private Attributes
static readonly
ReusableConstraint[] constraints
Member Function Documentation
void NUnit.Framework.Constraints.ReusableConstraintTests.CanReuseReusableConstraintMultipleTimes (ReusableConstraint c) inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
void NUnit.Framework.Constraints.ReusableConstraintTests.CanCreateReusableConstraintByImplicitConversion () inline
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
Member Data Documentation
readonly ReusableConstraint [] NUnit.Framework.Constraints.ReusableConstraintTests.constraints static private
Initial value:
= new ReusableConstraint[] {
            Is.Not.Empty,
            Is.Not.Null,
            Has.Length.GreaterThan(3),
            Has.Property("Length").EqualTo(4).And.StartsWith("te")
        }
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/ReusableConstraintTests.cs