IGLib: IPLab.FourierDoc Class Reference
IPLab.FourierDoc Class Reference
Summary description for FourierDoc.
Public Member Functions
FourierDoc (ComplexImage image, IDocumentsHost host)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void OnPaint (PaintEventArgs e)
Properties
Bitmap Image [get]
int ImageWidth [get]
int ImageHeight [get]
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void UpdateNewImage ()
void backwardFourierItem_Click (object sender, System.EventArgs e)
void frequencyFilterFourierItem_Click (object sender, System.EventArgs e)
void undoFourierItem_Click (object sender, System.EventArgs e)
void fourierItem_Popup (object sender, System.EventArgs e)
Private Attributes
ComplexImage image = null
ComplexImage backup = null
System.Drawing.Bitmap bitmap = null
int width
int height
IDocumentsHost host = null
System.Windows.Forms.MainMenu mainMenu
System.Windows.Forms.MenuItem fourierItem
System.Windows.Forms.MenuItem backwardFourierItem
System.Windows.Forms.MenuItem menuItem1
System.Windows.Forms.MenuItem frequencyFilterFourierItem
System.Windows.Forms.MenuItem undoFourierItem
System.ComponentModel.Container components = null
Required designer variable.
Detailed Description
Summary description for FourierDoc.
Constructor & Destructor Documentation
IPLab.FourierDoc.FourierDoc (ComplexImage image, IDocumentsHost host) inline
References IPLab.FourierDoc.host, IPLab.FourierDoc.image, IPLab.FourierDoc.InitializeComponent(), and IPLab.FourierDoc.UpdateNewImage().
Member Function Documentation
override void IPLab.FourierDoc.Dispose (bool disposing) inline protected
Clean up any resources being used.
References IPLab.FourierDoc.bitmap, and IPLab.FourierDoc.components.
void IPLab.FourierDoc.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IPLab.FourierDoc.FourierDoc().
void IPLab.FourierDoc.UpdateNewImage () inline private
References IPLab.FourierDoc.bitmap.
Referenced by IPLab.FourierDoc.FourierDoc(), IPLab.FourierDoc.frequencyFilterFourierItem_Click(), and IPLab.FourierDoc.undoFourierItem_Click().
override void IPLab.FourierDoc.OnPaint (PaintEventArgs e) inline protected
References IPLab.FourierDoc.bitmap, IPLab.FourierDoc.height, and IPLab.FourierDoc.width.
void IPLab.FourierDoc.backwardFourierItem_Click (object sender, System.EventArgs e) inline private
References IPLab.IDocumentsHost.NewDocument().
void IPLab.FourierDoc.frequencyFilterFourierItem_Click (object sender, System.EventArgs e) inline private
References IPLab.FrequencyFilterForm.InputRange, IPLab.FrequencyFilterForm.OutputRange, and IPLab.FourierDoc.UpdateNewImage().
void IPLab.FourierDoc.undoFourierItem_Click (object sender, System.EventArgs e) inline private
References IPLab.FourierDoc.backup, and IPLab.FourierDoc.UpdateNewImage().
void IPLab.FourierDoc.fourierItem_Popup (object sender, System.EventArgs e) inline private
References IPLab.FourierDoc.undoFourierItem.
Member Data Documentation
ComplexImage IPLab.FourierDoc.image = null private
Referenced by IPLab.FourierDoc.FourierDoc().
ComplexImage IPLab.FourierDoc.backup = null private
Referenced by IPLab.FourierDoc.undoFourierItem_Click().
System.Drawing.Bitmap IPLab.FourierDoc.bitmap = null private
Referenced by IPLab.FourierDoc.Dispose(), IPLab.FourierDoc.OnPaint(), and IPLab.FourierDoc.UpdateNewImage().
int IPLab.FourierDoc.width private
Referenced by IPLab.FourierDoc.OnPaint().
int IPLab.FourierDoc.height private
Referenced by IPLab.FourierDoc.OnPaint().
IDocumentsHost IPLab.FourierDoc.host = null private
Referenced by IPLab.FourierDoc.FourierDoc().
System.Windows.Forms.MainMenu IPLab.FourierDoc.mainMenu private
System.Windows.Forms.MenuItem IPLab.FourierDoc.fourierItem private
System.Windows.Forms.MenuItem IPLab.FourierDoc.backwardFourierItem private
System.Windows.Forms.MenuItem IPLab.FourierDoc.menuItem1 private
System.Windows.Forms.MenuItem IPLab.FourierDoc.frequencyFilterFourierItem private
System.Windows.Forms.MenuItem IPLab.FourierDoc.undoFourierItem private
Referenced by IPLab.FourierDoc.fourierItem_Popup().
System.ComponentModel.Container IPLab.FourierDoc.components = null private
Required designer variable.
Referenced by IPLab.FourierDoc.Dispose().
Property Documentation
Bitmap IPLab.FourierDoc.Image get
int IPLab.FourierDoc.ImageWidth get
int IPLab.FourierDoc.ImageHeight get
The documentation for this class was generated from the following file:
igsandbox/imageprocessing/iplab_new_GPL/Sources/FourierDoc.cs