IGLib: IG.Lib.StringVariableSystem Class Reference
IG.Lib.StringVariableSystem Class Reference
A lightweight system of string-valued variables, with some support to type conversion.
Public Member Functions
StringVariableSystem ()
Constructs a new system of string variables.
virtual string GetVariable (string varName)
Returns value of the specified variable, or null if it is not defined.
virtual void SetVariable (string varName, string varValue)
Sets the specified variable to the specified value.
virtual void AddNewVariable (string varName, string varValue)
Adds a new variable of the specified name and with the specified value (which can be null).
virtual bool RemoveVariable (string varName)
Removes a variable with the specified name from the current variable system, and returns a flag indicating whether variable was actually removed.
virtual int RemoveVariables (params string[] varNames)
Removes all variables whose names are specified by the argument, and returns the number of variables that were actully been removed.
virtual bool UnSetVariable (string varName)
Unsets the variable with the specified name on the current variable system, and returns a flag indicating whether variable was defined.
virtual bool IsVariableDefined (string varName)
Returns true if the specified variable is defined, false otherwise.
virtual string[][] ToArray ()
Returns array representation of variables that are currently defined on the system.
virtual void ImportVariables (string[][] variables)
Imports variables defined in form of two dimensional array.
virtual void SetVariable (string varName, object varValue)
Sets the specified variable to the specified value.
bool TryGetIntegerVariable (string varName, out int varTypedValue)
Obtains a value of an integer-typed variable of the specified name, if such a variable is defined and its value can be interpreted as an integer.
int GetIntegerVariable (string varName)
Returns the value of an integer-valued variable of the specified name.
bool TryGetDoubleVariable (string varName, out double varTypedValue)
Obtains a value of a double-typed variable of the specified name, if such a variable is defined and its value can be interpreted as a number of type double.
double GetDoubleVariable (string varName)
Returns the value of a double-valued variable of the specified name.
bool TryGetBooleanVariable (string varName, out bool varTypedValue)
Obtains a value of a boolean-typed variable of the specified name, if such a variable is defined and its value can be interpreted as a boolean value.
bool GetBooleanVariable (string varName)
Returns the value of a boolean-valued variable of the specified name.
bool GetFlag (string flagName)
Returns value of the flag with the specified name.
void SetFlag (string flagName, bool flagValue)
Sets the flag of the specified name to the specified value.
virtual void Export (string filePath)
Saves (serializes) the specified variable system to the specified JSON file.
virtual void Export (string filePath, bool append)
Saves (serializes) the specified variable system to the specified JSON file.
virtual void Import (string filePath)
Imports variables from the specified variable system in JSON format.
void PrintVariables ()
Prints all variables (with their values) defined on the current object.
Static Public Member Functions
static void SaveJson (StringVariableSystem variableSystem, string filePath)
Saves (serializes) the specified variable system to the specified JSON file. File is owerwritten if it exists.
static void SaveJson (StringVariableSystem variableSystem, string filePath, bool append)
Saves (serializes) the specified variable system to the specified JSON file. If the file already exists, contents either overwrites the file or is appended at the end, dependent on the value of the append flag.
static void LoadJson (string filePath, ref StringVariableSystem variableSystemRestored)
Restores (deserializes) a vector from the specified file in JSON format.
static void ExportDto (StringVariableSystemDto settings, string filePath)
Saves (serializes) the specified variable system DTO to the specified JSON file.
static void ExportDto (StringVariableSystemDto variables, string filePath, bool append)
Saves (serializes) the specified variable system DTO to the specified JSON file.
static void ImportDto (string filePath, ref StringVariableSystemDto settings)
Restores (deserializes) variable system DTO from the specified file in JSON format.
static void TestMisc ()
Miscellaneous tests.
Protected Attributes
SortedList< string, string > _variables = new SortedList<string, string>()
Properties
object Lock [get]
This object's central lock object to be used by other object.
bool SetNullOnImport [get, set]
Flag indicating whether null variable values are also set when importing variable values. If false then, if some imported variable has null value, this variable will not be set on the current system of variables. This means that the value of eventually existent variable will remain unchanged if variables are imported from another system where this variable is defined but has null value.
virtual SortedList< string,
string > Variables [get]
virtual string this[string varName] [get, set]
Gets or sets value of the specified variable.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
object _mainLock = new object()
bool _setNullOnImport = false
Detailed Description
A lightweight system of string-valued variables, with some support to type conversion.
Constructor & Destructor Documentation
IG.Lib.StringVariableSystem.StringVariableSystem () inline
Constructs a new system of string variables.
Member Function Documentation
virtual string IG.Lib.StringVariableSystem.GetVariable (string varName) inline virtual
Returns value of the specified variable, or null if it is not defined.
Parameters
varName Name of the variable whose value is queried. Must not be null or empty string.
Exceptions
ArgumentException When the specified variable name is null or empty string.
virtual void IG.Lib.StringVariableSystem.SetVariable (string varName, string varValue) inline virtual
Sets the specified variable to the specified value.
If variable does not exist then it is created, otherwise its value is overwritten.
Parameters
varName Name of the variable to be set. Must not be null or empty string.
varValue Value that is assigned to the variable.
Exceptions
ArgumentException When the specified variable name is null or empty string.
Referenced by IG.Lib.StringVariableSystem.TestMisc().
virtual void IG.Lib.StringVariableSystem.AddNewVariable (string varName, string varValue) inline virtual
Adds a new variable of the specified name and with the specified value (which can be null).
If the variable with the specified name already exists then ArgumentException exception is thrown.
Parameters
varName Name of the variable to be added. Must not be null or empty string.
varValue Value that is assigned to the variable.
Exceptions
ArgumentException When the specified variable name is null or empty string, or when the variable with the specified name already exists.
virtual bool IG.Lib.StringVariableSystem.RemoveVariable (string varName) inline virtual
Removes a variable with the specified name from the current variable system, and returns a flag indicating whether variable was actually removed.
False is returned but no exception is thrown if the specified variable is not defined.
Parameters
varName Name of the variable to be removed. Must not be null or empty string.
Returns
True if a variable has been removed, false it the specified variable was not defined.
Exceptions
ArgumentException When the specified variable name is null or empty string.
virtual int IG.Lib.StringVariableSystem.RemoveVariables (params string[] varNames) inline virtual
Removes all variables whose names are specified by the argument, and returns the number of variables that were actully been removed.
Parameters
varNames Names of variables to be removed.
Returns
Number of variables that were actually removed.
virtual bool IG.Lib.StringVariableSystem.UnSetVariable (string varName) inline virtual
Unsets the variable with the specified name on the current variable system, and returns a flag indicating whether variable was defined.
If the variable is defined then it is jus tset to null and true is returned.
False is returned but no exception is thrown if the specified variable is not defined.
Parameters
varName Name of the variable to be removed. Must not be null or empty string.
Returns
True if a variable is defined (in which case it is set to null), false it the specified variable was not defined.
Exceptions
ArgumentException When the specified variable name is null or empty string.
virtual bool IG.Lib.StringVariableSystem.IsVariableDefined (string varName) inline virtual
Returns true if the specified variable is defined, false otherwise.
Parameters
varName Name of the variable whose existence is queried. Must not be null or empty string.
Exceptions
ArgumentException When the specified variable name is null or empty string.
virtual string [][] IG.Lib.StringVariableSystem.ToArray () inline virtual
Returns array representation of variables that are currently defined on the system.
Returns
Array whose elements are arrays of two strings, of which the 0-th element is variable name and the 1st element is its value.
Referenced by IG.Lib.StringVariableSystemDtoBase< VariableSystemType >.CopyFromPlain().
virtual void IG.Lib.StringVariableSystem.ImportVariables (string variables[][]) inline virtual
Imports variables defined in form of two dimensional array.
Parameters
variables
virtual void IG.Lib.StringVariableSystem.SetVariable (string varName, object varValue) inline virtual
Sets the specified variable to the specified value.
If value is null then variable value is set to null, otherwise it is set to object's string representation that is obtained by calling its ToString() method.
If variable does not exist then it is created, otherwise its value is overwritten.
Parameters
varName Name of the variable to be set. Must not be null or empty string.
varValue Value that is assigned to the variable. If the object is null then null is assigned, otherwise string representation of the object obtained by the ToString() method is assigned.
Exceptions
ArgumentException When the specified variable name is null or empty string.
bool IG.Lib.StringVariableSystem.TryGetIntegerVariable (string varName, out int varTypedValue) inline
Obtains a value of an integer-typed variable of the specified name, if such a variable is defined and its value can be interpreted as an integer.
Returns a flag indicating whether the value has been successfully obtained.
Parameters
varName Name of the variable whose value is queried. Must not be null or empty string.
Returns
True if the value has been successfully obtained, false if not.
Exceptions
ArgumentException When the specified variable name is null or empty string.
int IG.Lib.StringVariableSystem.GetIntegerVariable (string varName) inline
Returns the value of an integer-valued variable of the specified name.
Exception is thrown if the specified variable does not exist or its string value can not be interpreted as integer.
Parameters
varName Name of the variable whose value is queried. Must not be null or empty string.
Returns
Integar value of the specified variable.
Exceptions
ArgumentException When the specified variable name is null or empty string or when a variable with the specified name does not exist or its string value does not represent an integer.
bool IG.Lib.StringVariableSystem.TryGetDoubleVariable (string varName, out double varTypedValue) inline
Obtains a value of a double-typed variable of the specified name, if such a variable is defined and its value can be interpreted as a number of type double.
Returns a flag indicating whether the value has been successfully obtained.
Parameters
varName Name of the variable whose value is queried. Must not be null or empty string.
Returns
True if the value has been successfully obtained, false if not.
Exceptions
ArgumentException When the specified variable name is null or empty string.
double IG.Lib.StringVariableSystem.GetDoubleVariable (string varName) inline
Returns the value of a double-valued variable of the specified name.
Exception is thrown if the specified variable does not exist or its string value can not be interpreted as a number of type double.
Parameters
varName Name of the variable whose value is queried. Must not be null or empty string.
Returns
Double value of the specified variable.
Exceptions
ArgumentException When the specified variable name is null or empty string or when a variable with the specified name does not exist or its string value does not represent a number of type double.
bool IG.Lib.StringVariableSystem.TryGetBooleanVariable (string varName, out bool varTypedValue) inline
Obtains a value of a boolean-typed variable of the specified name, if such a variable is defined and its value can be interpreted as a boolean value.
Returns a flag indicating whether the value has been successfully obtained.
Parameters
varName Name of the variable whose value is queried. Must not be null or empty string.
Returns
True if the value has been successfully obtained, false if not.
Exceptions
ArgumentException When the specified variable name is null or empty string.
References IG.Lib.Util.TryParseBoolean().
bool IG.Lib.StringVariableSystem.GetBooleanVariable (string varName) inline
Returns the value of a boolean-valued variable of the specified name.
Exception is thrown if the specified variable does not exist or its string value can not be interpreted as a boolean value.
Parameters
varName Name of the variable whose value is queried. Must not be null or empty string.
Returns
Boolean value of the specified variable.
Exceptions
ArgumentException When the specified variable name is null or empty string or when a variable with the specified name does not exist or its string value does not represent a boolean value.
References IG.Lib.Util.TryParseBoolean().
bool IG.Lib.StringVariableSystem.GetFlag (string flagName) inline
Returns value of the flag with the specified name.
Flag is considered to be false if the variable of the specified flag name is not defined or its string name does not represent a boolean value, or it is the value of the specified variable interpreted as boolean.
Parameters
flagName Name of the flag to be returned.
Returns
Value of the specified flag, i.e. value of the variable named flagName interpreted as boolean, or false if there is no such variable or its value can not be interpreted as boolean.
Exceptions
ArgumentException When the specified flag name is null or empty string.
void IG.Lib.StringVariableSystem.SetFlag (string flagName, bool flagValue) inline
Sets the flag of the specified name to the specified value.
Variable of the specified name is assigned string representation of the specified boolean value.
Parameters
flagName Name of the flag to be set.
flagValue Value to be assigned to the flag of the specified name.
virtual void IG.Lib.StringVariableSystem.Export (string filePath) inline virtual
Saves (serializes) the specified variable system to the specified JSON file.
If the file already exists, contents overwrite the file.
Parameters
filePath Path to the file in variables and properties of the system are saved.
Reimplemented in IG.Lib.StringSettings.
virtual void IG.Lib.StringVariableSystem.Export (string filePath, bool append) inline virtual
Saves (serializes) the specified variable system to the specified JSON file.
If the file already exists, contents either overwrite the file or are appended at the end, dependent on the value of the append flag.
Parameters
filePath Path to the file in variables and properties of the system are saved.
append Specifies whether serialized data is appended at the end of the file in the case that the file already exists.
Reimplemented in IG.Lib.StringSettings.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom().
virtual void IG.Lib.StringVariableSystem.Import (string filePath) inline virtual
Imports variables from the specified variable system in JSON format.
Parameters
filePath File from which object is restored.
Reimplemented in IG.Lib.StringSettings.
static void IG.Lib.StringVariableSystem.SaveJson (StringVariableSystem variableSystem, string filePath) inline static
Saves (serializes) the specified variable system to the specified JSON file. File is owerwritten if it exists.
Parameters
variableSystem Object that is saved to a file.
filePath Path to the file in which object is is saved.
static void IG.Lib.StringVariableSystem.SaveJson (StringVariableSystem variableSystem, string filePath, bool append) inline static
Saves (serializes) the specified variable system to the specified JSON file. If the file already exists, contents either overwrites the file or is appended at the end, dependent on the value of the append flag.
Parameters
variableSystem Object that is saved to a file.
filePath Path to the file into which object is saved.
append Specifies whether serialized data is appended at the end of the file in the case that the file already exists.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom().
static void IG.Lib.StringVariableSystem.LoadJson (string filePath, ref StringVariableSystem variableSystemRestored) inline static
Restores (deserializes) a vector from the specified file in JSON format.
Parameters
filePath File from which object is restored.
variableSystemRestored Object that is restored by deserialization.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyTo().
static void IG.Lib.StringVariableSystem.ExportDto (StringVariableSystemDto settings, string filePath) inline static
Saves (serializes) the specified variable system DTO to the specified JSON file.
If the file already exists, contents overwrite the file.
Parameters
settings Variable system DTO that is saved to a file.
filePath Path to the file into which variables (and settings and other stuff) are saved.
static void IG.Lib.StringVariableSystem.ExportDto (StringVariableSystemDto variables, string filePath, bool append) inline static
Saves (serializes) the specified variable system DTO to the specified JSON file.
If the file already exists, contents either overwrite the file or are appended at the end, dependent on the value of the append flag.
Parameters
variables Variable system DTO that is saved to a file.
filePath Path to the file into which variables (and settings and other stuff) are saved.
append Specifies whether serialized data is appended at the end of the file in the case that the file already exists.
static void IG.Lib.StringVariableSystem.ImportDto (string filePath, ref StringVariableSystemDto settings) inline static
Restores (deserializes) variable system DTO from the specified file in JSON format.
The restored DTO can be used e.g. to import variables to a variable system.
Parameters
filePath File from which object is restored.
settings Variable system DTO that is restored by deserialization.
void IG.Lib.StringVariableSystem.PrintVariables () inline
Prints all variables (with their values) defined on the current object.
Referenced by IG.Lib.StringVariableSystem.TestMisc().
static void IG.Lib.StringVariableSystem.TestMisc () inline static
Miscellaneous tests.
References IG.Lib.StringVariableSystem.PrintVariables(), and IG.Lib.StringVariableSystem.SetVariable().
Member Data Documentation
object IG.Lib.StringVariableSystem._mainLock = new object() private
bool IG.Lib.StringVariableSystem._setNullOnImport = false private
SortedList<string, string> IG.Lib.StringVariableSystem._variables = new SortedList<string, string>() protected
Property Documentation
object IG.Lib.StringVariableSystem.Lock get
This object's central lock object to be used by other object.
bool IG.Lib.StringVariableSystem.SetNullOnImport get set
Flag indicating whether null variable values are also set when importing variable values. If false then, if some imported variable has null value, this variable will not be set on the current system of variables. This means that the value of eventually existent variable will remain unchanged if variables are imported from another system where this variable is defined but has null value.
Default value is false. This behavior can be useful e.g. when importing settings from a file. Many times we don't want to import variables with null value because somebody might have set values to null instead of completely removing those variables he or she didn't want to change. This might not be the preferred behavior when null-valued variables actually serve some purpose and it is important that we have possibility of defining null values for variables e.g. in a setting file.
Referenced by IG.Lib.StringVariableSystemDtoBase< VariableSystemType >.CopyFromPlain().
virtual SortedList<string, string> IG.Lib.StringVariableSystem.Variables get protected
virtual string IG.Lib.StringVariableSystem.this[string varName] get set
Gets or sets value of the specified variable.
Getter returnd value of the variable or null if it is not defined.
Setter overwrites existing value or creates a variable if it is not yet defined.
Parameters
varName Name of the variable whose value is queried. Must not be null or empty string.
Exceptions
ArgumentException When the specified variable name is null or empty string.
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/varstring/VarSystemString.cs