IGLib: NUnit.Framework.Attributes.OneTimeSetupTearDownTest Class Reference
NUnit.Framework.Attributes.OneTimeSetupTearDownTest Class Reference
Public Member Functions
void MakeSureSetUpAndTearDownAreCalled ()
void MakeSureSetUpAndTearDownAreCalledOnFixtureWithTestCases ()
void MakeSureSetUpAndTearDownAreCalledOnFixtureWithTheories ()
void MakeSureSetUpAndTearDownAreNotCalledOnExplicitFixture ()
void CheckInheritedSetUpAndTearDownAreCalled ()
void OverriddenSetUpAndTearDownAreNotCalled ()
void BaseSetUpCalledFirstAndTearDownCalledLast ()
void FailedBaseSetUpCausesDerivedSetUpAndTeardownToBeSkipped ()
void StaticBaseSetUpCalledFirstAndTearDownCalledLast ()
void HandleErrorInFixtureSetup ()
void RerunFixtureAfterSetUpFixed ()
void HandleIgnoreInFixtureSetup ()
void HandleErrorInFixtureTearDown ()
void HandleErrorInFixtureTearDownAfterErrorInTest ()
void HandleErrorInFixtureTearDownAfterErrorInFixtureSetUp ()
void HandleExceptionInFixtureConstructor ()
void RerunFixtureAfterTearDownFixed ()
void HandleSetUpAndTearDownWithTestInName ()
void IgnoredFixtureShouldNotCallFixtureSetUpOrTearDown ()
void FixtureWithNoTestsShouldNotCallFixtureSetUpOrTearDown ()
void DisposeCalledOnceWhenFixtureImplementsIDisposable ()
void DisposeCalledOnceWhenFixtureImplementsIDisposableAndHasTestCases ()
Static Public Member Functions
static void StaticSetUpAndTearDownAreCalled ()
static void StaticClassSetUpAndTearDownAreCalled ()
Member Function Documentation
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.MakeSureSetUpAndTearDownAreCalled () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownFixture.setUpCount, and NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownFixture.tearDownCount.
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.MakeSureSetUpAndTearDownAreCalledOnFixtureWithTestCases () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.TestUtilities.TestBuilder.RunTestFixture().
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.MakeSureSetUpAndTearDownAreCalledOnFixtureWithTheories () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.TestUtilities.TestBuilder.RunTestFixture().
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.MakeSureSetUpAndTearDownAreNotCalledOnExplicitFixture () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.ExplicitSetUpAndTearDownFixture.setUpCount, and NUnit.TestData.OneTimeSetUpTearDownData.ExplicitSetUpAndTearDownFixture.tearDownCount.
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.CheckInheritedSetUpAndTearDownAreCalled () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownFixture.setUpCount, and NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownFixture.tearDownCount.
static void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.StaticSetUpAndTearDownAreCalled () inline static
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.StaticSetUpAndTearDownFixture.setUpCount, and NUnit.TestData.OneTimeSetUpTearDownData.StaticSetUpAndTearDownFixture.tearDownCount.
static void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.StaticClassSetUpAndTearDownAreCalled () inline static
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.StaticClassSetUpAndTearDownFixture.setUpCount, and NUnit.TestData.OneTimeSetUpTearDownData.StaticClassSetUpAndTearDownFixture.tearDownCount.
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.OverriddenSetUpAndTearDownAreNotCalled () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestData.OneTimeSetUpTearDownData.OverrideSetUpAndTearDown.derivedSetUpCount, NUnit.TestData.OneTimeSetUpTearDownData.OverrideSetUpAndTearDown.derivedTearDownCount, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownFixture.setUpCount, and NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownFixture.tearDownCount.
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.BaseSetUpCalledFirstAndTearDownCalledLast () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestData.OneTimeSetUpTearDownData.DerivedSetUpAndTearDownFixture.baseSetUpCalledFirst, NUnit.TestData.OneTimeSetUpTearDownData.DerivedSetUpAndTearDownFixture.baseTearDownCalledLast, NUnit.TestData.OneTimeSetUpTearDownData.DerivedSetUpAndTearDownFixture.derivedSetUpCount, NUnit.TestData.OneTimeSetUpTearDownData.DerivedSetUpAndTearDownFixture.derivedTearDownCount, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownFixture.setUpCount, NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownFixture.tearDownCount, and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.FailedBaseSetUpCausesDerivedSetUpAndTeardownToBeSkipped () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestData.OneTimeSetUpTearDownData.DerivedSetUpAndTearDownFixture.derivedSetUpCount, NUnit.TestData.OneTimeSetUpTearDownData.DerivedSetUpAndTearDownFixture.derivedTearDownCount, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownFixture.setUpCount, NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownFixture.tearDownCount, and NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownFixture.throwInBaseSetUp.
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.StaticBaseSetUpCalledFirstAndTearDownCalledLast () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestData.OneTimeSetUpTearDownData.DerivedStaticSetUpAndTearDownFixture.baseSetUpCalledFirst, NUnit.TestData.OneTimeSetUpTearDownData.DerivedStaticSetUpAndTearDownFixture.baseTearDownCalledLast, NUnit.TestData.OneTimeSetUpTearDownData.DerivedStaticSetUpAndTearDownFixture.derivedSetUpCount, NUnit.TestData.OneTimeSetUpTearDownData.DerivedStaticSetUpAndTearDownFixture.derivedTearDownCount, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.StaticSetUpAndTearDownFixture.setUpCount, NUnit.TestData.OneTimeSetUpTearDownData.StaticSetUpAndTearDownFixture.tearDownCount, and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureSetup () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.blowUpInSetUp, NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Interfaces.ITestResult.FailCount, NUnit.Framework.Assert.IsNotNull(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.setUpCount, NUnit.Framework.Interfaces.ResultState.SetUpError, NUnit.Framework.Interfaces.ITestResult.StackTrace, and NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.tearDownCount.
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.RerunFixtureAfterSetUpFixed () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.blowUpInSetUp, NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.Reinitialize(), NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.setUpCount, NUnit.Framework.Interfaces.ResultState.SetUpError, NUnit.Framework.Interfaces.ResultState.Success, and NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.tearDownCount.
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleIgnoreInFixtureSetup () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Interfaces.ResultState.Ignored, NUnit.Framework.Assert.IsNotNull(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.Framework.Interfaces.ITestResult.SkipCount, NUnit.Framework.Interfaces.ITestResult.StackTrace, and NUnit.Framework.Interfaces.ResultState.WithSite().
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureTearDown () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.blowUpInTearDown, NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Does.Contain(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.setUpCount, NUnit.Framework.Interfaces.ITestResult.StackTrace, NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.tearDownCount, NUnit.Framework.Interfaces.ResultState.TearDownError, and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureTearDownAfterErrorInTest () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.blowUpInTearDown, NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.blowUpInTest, NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.setUpCount, NUnit.Framework.Interfaces.ResultState.Site, NUnit.Framework.Interfaces.ITestResult.StackTrace, NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.tearDownCount, NUnit.Framework.Interfaces.ResultState.TearDownError, and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureTearDownAfterErrorInFixtureSetUp () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.blowUpInSetUp, NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.blowUpInTearDown, NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Does.Contain(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.setUpCount, NUnit.Framework.Interfaces.ITestResult.StackTrace, NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.tearDownCount, NUnit.Framework.Interfaces.ResultState.TearDownError, and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleExceptionInFixtureConstructor () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Interfaces.ITestResult.FailCount, NUnit.Framework.Assert.IsNotNull(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.Framework.Interfaces.ResultState.SetUpError, and NUnit.Framework.Interfaces.ITestResult.StackTrace.
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.RerunFixtureAfterTearDownFixed () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.blowUpInTearDown, NUnit.Framework.Interfaces.ITestResult.Children, NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.Reinitialize(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.setUpCount, and NUnit.TestData.OneTimeSetUpTearDownData.MisbehavingFixture.tearDownCount.
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleSetUpAndTearDownWithTestInName () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownWithTestInName.setUpCount, and NUnit.TestData.OneTimeSetUpTearDownData.SetUpAndTearDownWithTestInName.tearDownCount.
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.IgnoredFixtureShouldNotCallFixtureSetUpOrTearDown () inline
References NUnit.Framework.Internal.TestSuite.Add(), NUnit.Framework.Assert.IsFalse(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.TestUtilities.TestBuilder.RunTest(), NUnit.TestUtilities.TestBuilder.RunTestSuite(), NUnit.TestData.OneTimeSetUpTearDownData.IgnoredFixture.setupCalled, NUnit.TestData.OneTimeSetUpTearDownData.IgnoredFixture.teardownCalled, and NUnit.Framework.Internal.TestSuite.Tests.
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.FixtureWithNoTestsShouldNotCallFixtureSetUpOrTearDown () inline
References NUnit.Framework.Is.False, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.OneTimeSetUpTearDownData.FixtureWithNoTests.setupCalled, NUnit.TestData.OneTimeSetUpTearDownData.FixtureWithNoTests.teardownCalled, and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.DisposeCalledOnceWhenFixtureImplementsIDisposable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Attributes.OneTimeSetupTearDownTest.DisposeCalledOnceWhenFixtureImplementsIDisposableAndHasTestCases () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/OneTimeSetUpTearDownTests.cs