IGLib: NUnit.Framework.Internal.Execution.CommandBuilder Class Reference
NUnit.Framework.Internal.Execution.CommandBuilder Class Reference
A utility class to create TestCommands
Static Public Member Functions
static TestCommand MakeOneTimeSetUpCommand (TestSuite suite, List< SetUpTearDownItem > setUpTearDown, List< TestActionItem > actions)
Gets the command to be executed before any of the child tests are run.
static TestCommand MakeOneTimeTearDownCommand (TestSuite suite, List< SetUpTearDownItem > setUpTearDownItems, List< TestActionItem > actions)
Gets the command to be executed after all of the child tests are run.
static TestCommand MakeTestCommand (TestMethod test)
Creates a test command for use in running this test.
static SkipCommand MakeSkipCommand (Test test)
Creates a command for skipping a test. The result returned will depend on the test RunState.
static List< SetUpTearDownItem > BuildSetUpTearDownList (Type fixtureType, Type setUpType, Type tearDownType)
Builds the set up tear down list.
Static Private Member Functions
static SetUpTearDownItem BuildNode (Type fixtureType, IList< MethodInfo > setUpMethods, IList< MethodInfo > tearDownMethods)
static List< MethodInfo > SelectMethodsByDeclaringType (Type type, IList< MethodInfo > methods)
Detailed Description
A utility class to create TestCommands
Member Function Documentation
static TestCommand NUnit.Framework.Internal.Execution.CommandBuilder.MakeOneTimeSetUpCommand (TestSuite suite, List< SetUpTearDownItem > setUpTearDown, List< TestActionItem > actions) inline static
Gets the command to be executed before any of the child tests are run.
Returns
A TestCommand
References NUnit.Framework.Internal.Test.Method, NUnit.Framework.Internal.Test.RunState, and NUnit.Framework.Internal.Test.TypeInfo.
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.InitializeSetUpAndTearDownCommands().
static TestCommand NUnit.Framework.Internal.Execution.CommandBuilder.MakeOneTimeTearDownCommand (TestSuite suite, List< SetUpTearDownItem > setUpTearDownItems, List< TestActionItem > actions) inline static
Gets the command to be executed after all of the child tests are run.
Returns
A TestCommand
References NUnit.Framework.Internal.Test.TestType.
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.InitializeSetUpAndTearDownCommands().
static TestCommand NUnit.Framework.Internal.Execution.CommandBuilder.MakeTestCommand (TestMethod test) inline static
Creates a test command for use in running this test.
Returns
References NUnit.Framework.Interfaces.ICommandWrapper.Wrap().
Referenced by NUnit.Framework.Internal.Execution.SimpleWorkItem.SimpleWorkItem().
static SkipCommand NUnit.Framework.Internal.Execution.CommandBuilder.MakeSkipCommand (Test test) inline static
Creates a command for skipping a test. The result returned will depend on the test RunState.
Referenced by NUnit.Framework.Internal.Execution.SimpleWorkItem.SimpleWorkItem().
static List<SetUpTearDownItem> NUnit.Framework.Internal.Execution.CommandBuilder.BuildSetUpTearDownList (Type fixtureType, Type setUpType, Type tearDownType) inline static
Builds the set up tear down list.
Parameters
fixtureType Type of the fixture.
setUpType Type of the set up attribute.
tearDownType Type of the tear down attribute.
Returns
A list of SetUpTearDownItems
References NUnit.Framework.Internal.Reflect.GetMethodsWithAttribute().
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.InitializeSetUpAndTearDownCommands(), and NUnit.Framework.Internal.Commands.SetUpTearDownCommand.SetUpTearDownCommand().
static SetUpTearDownItem NUnit.Framework.Internal.Execution.CommandBuilder.BuildNode (Type fixtureType, IList< MethodInfo > setUpMethods, IList< MethodInfo > tearDownMethods) inline static private
static List<MethodInfo> NUnit.Framework.Internal.Execution.CommandBuilder.SelectMethodsByDeclaringType (Type type, IList< MethodInfo > methods) inline static private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Execution/CommandBuilder.cs