IGLib: IPLab.HSLFilteringForm Class Reference
IPLab.HSLFilteringForm Class Reference
Summary description for HSLFilteringForm.
Public Member Functions
HSLFilteringForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
Bitmap Image [set]
IFilter Filter [get]
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void UpdateFilter ()
void minHBox_TextChanged (object sender, System.EventArgs e)
void maxHBox_TextChanged (object sender, System.EventArgs e)
void minSBox_TextChanged (object sender, System.EventArgs e)
void maxSBox_TextChanged (object sender, System.EventArgs e)
void minLBox_TextChanged (object sender, System.EventArgs e)
void maxLBox_TextChanged (object sender, System.EventArgs e)
void huePicker_ValuesChanged (object sender, System.EventArgs e)
void saturationSlider_ValuesChanged (object sender, System.EventArgs e)
void luminanceSlider_ValuesChanged (object sender, System.EventArgs e)
void fillHBox_TextChanged (object sender, System.EventArgs e)
void fillSBox_TextChanged (object sender, System.EventArgs e)
void fillLBox_TextChanged (object sender, System.EventArgs e)
void UpdateFillColor ()
void updateHCheck_CheckedChanged (object sender, System.EventArgs e)
void updateSCheck_CheckedChanged (object sender, System.EventArgs e)
void updateLCheck_CheckedChanged (object sender, System.EventArgs e)
void fillTypeCombo_SelectedIndexChanged (object sender, System.EventArgs e)
Private Attributes
HSLFiltering filter = new HSLFiltering()
IntRange hue = new IntRange(0, 359)
Range saturation = new Range(0, 1)
Range luminance = new Range(0, 1)
int fillH = 0
float fillS = 0
float fillL = 0
AForge.Controls.HuePicker huePicker
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox maxHBox
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Label label3
System.Windows.Forms.Label label4
System.Windows.Forms.TextBox minSBox
System.Windows.Forms.TextBox maxSBox
AForge.Controls.ColorSlider saturationSlider
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.Label label5
System.Windows.Forms.Label label6
System.Windows.Forms.TextBox minLBox
System.Windows.Forms.TextBox maxLBox
System.Windows.Forms.GroupBox groupBox5
IPLab.FilterPreview filterPreview
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.Label label7
System.Windows.Forms.TextBox fillHBox
System.Windows.Forms.CheckBox updateHCheck
System.Windows.Forms.Label label8
System.Windows.Forms.TextBox fillSBox
System.Windows.Forms.CheckBox updateSCheck
System.Windows.Forms.Label label9
System.Windows.Forms.TextBox fillLBox
System.Windows.Forms.CheckBox updateLCheck
System.Windows.Forms.ComboBox fillTypeCombo
System.Windows.Forms.Label label10
System.Windows.Forms.Button cancelButton
System.Windows.Forms.Button okButton
System.Windows.Forms.TextBox minHBox
AForge.Controls.ColorSlider luminanceSlider
System.ComponentModel.Container components = null
Required designer variable.
Detailed Description
Summary description for HSLFilteringForm.
Constructor & Destructor Documentation
IPLab.HSLFilteringForm.HSLFilteringForm () inline
References IPLab.HSLFilteringForm.fillHBox, IPLab.HSLFilteringForm.fillL, IPLab.HSLFilteringForm.fillLBox, IPLab.HSLFilteringForm.fillSBox, IPLab.HSLFilteringForm.fillTypeCombo, IPLab.HSLFilteringForm.filter, IPLab.FilterPreview.Filter, IPLab.HSLFilteringForm.filterPreview, IPLab.HSLFilteringForm.InitializeComponent(), IPLab.HSLFilteringForm.maxHBox, IPLab.HSLFilteringForm.maxLBox, IPLab.HSLFilteringForm.maxSBox, IPLab.HSLFilteringForm.minHBox, IPLab.HSLFilteringForm.minLBox, and IPLab.HSLFilteringForm.minSBox.
Member Function Documentation
override void IPLab.HSLFilteringForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References IPLab.HSLFilteringForm.components.
void IPLab.HSLFilteringForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IPLab.HSLFilteringForm.HSLFilteringForm().
void IPLab.HSLFilteringForm.UpdateFilter () inline private
References IPLab.HSLFilteringForm.filterPreview, IPLab.HSLFilteringForm.hue, IPLab.HSLFilteringForm.luminance, IPLab.FilterPreview.RefreshFilter(), and IPLab.HSLFilteringForm.saturation.
Referenced by IPLab.HSLFilteringForm.maxHBox_TextChanged(), IPLab.HSLFilteringForm.maxLBox_TextChanged(), IPLab.HSLFilteringForm.maxSBox_TextChanged(), IPLab.HSLFilteringForm.minHBox_TextChanged(), IPLab.HSLFilteringForm.minLBox_TextChanged(), and IPLab.HSLFilteringForm.minSBox_TextChanged().
void IPLab.HSLFilteringForm.minHBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.huePicker, IPLab.HSLFilteringForm.minHBox, and IPLab.HSLFilteringForm.UpdateFilter().
void IPLab.HSLFilteringForm.maxHBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.huePicker, IPLab.HSLFilteringForm.maxHBox, and IPLab.HSLFilteringForm.UpdateFilter().
void IPLab.HSLFilteringForm.minSBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.minSBox, IPLab.HSLFilteringForm.saturationSlider, and IPLab.HSLFilteringForm.UpdateFilter().
void IPLab.HSLFilteringForm.maxSBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.maxSBox, IPLab.HSLFilteringForm.saturationSlider, and IPLab.HSLFilteringForm.UpdateFilter().
void IPLab.HSLFilteringForm.minLBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.luminanceSlider, IPLab.HSLFilteringForm.minLBox, and IPLab.HSLFilteringForm.UpdateFilter().
void IPLab.HSLFilteringForm.maxLBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.luminanceSlider, IPLab.HSLFilteringForm.maxLBox, and IPLab.HSLFilteringForm.UpdateFilter().
void IPLab.HSLFilteringForm.huePicker_ValuesChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.huePicker, IPLab.HSLFilteringForm.maxHBox, and IPLab.HSLFilteringForm.minHBox.
void IPLab.HSLFilteringForm.saturationSlider_ValuesChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.maxSBox, IPLab.HSLFilteringForm.minSBox, and IPLab.HSLFilteringForm.saturationSlider.
void IPLab.HSLFilteringForm.luminanceSlider_ValuesChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.luminanceSlider, IPLab.HSLFilteringForm.maxLBox, and IPLab.HSLFilteringForm.minLBox.
void IPLab.HSLFilteringForm.fillHBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.fillHBox, and IPLab.HSLFilteringForm.UpdateFillColor().
void IPLab.HSLFilteringForm.fillSBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.fillSBox, and IPLab.HSLFilteringForm.UpdateFillColor().
void IPLab.HSLFilteringForm.fillLBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.fillL, IPLab.HSLFilteringForm.fillLBox, and IPLab.HSLFilteringForm.UpdateFillColor().
void IPLab.HSLFilteringForm.UpdateFillColor () inline private
References IPLab.HSLFilteringForm.fillL, IPLab.HSLFilteringForm.filterPreview, IPLab.HSLFilteringForm.luminanceSlider, IPLab.FilterPreview.RefreshFilter(), and IPLab.HSLFilteringForm.saturationSlider.
Referenced by IPLab.HSLFilteringForm.fillHBox_TextChanged(), IPLab.HSLFilteringForm.fillLBox_TextChanged(), and IPLab.HSLFilteringForm.fillSBox_TextChanged().
void IPLab.HSLFilteringForm.updateHCheck_CheckedChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.filterPreview, IPLab.FilterPreview.RefreshFilter(), and IPLab.HSLFilteringForm.updateHCheck.
void IPLab.HSLFilteringForm.updateSCheck_CheckedChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.filterPreview, IPLab.FilterPreview.RefreshFilter(), and IPLab.HSLFilteringForm.updateSCheck.
void IPLab.HSLFilteringForm.updateLCheck_CheckedChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.filterPreview, IPLab.FilterPreview.RefreshFilter(), and IPLab.HSLFilteringForm.updateLCheck.
void IPLab.HSLFilteringForm.fillTypeCombo_SelectedIndexChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLFilteringForm.fillTypeCombo, IPLab.HSLFilteringForm.filterPreview, IPLab.HSLFilteringForm.luminanceSlider, IPLab.FilterPreview.RefreshFilter(), and IPLab.HSLFilteringForm.saturationSlider.
Member Data Documentation
HSLFiltering IPLab.HSLFilteringForm.filter = new HSLFiltering() private
Referenced by IPLab.HSLFilteringForm.HSLFilteringForm().
IntRange IPLab.HSLFilteringForm.hue = new IntRange(0, 359) private
Referenced by IPLab.HSLFilteringForm.UpdateFilter().
Range IPLab.HSLFilteringForm.saturation = new Range(0, 1) private
Referenced by IPLab.HSLFilteringForm.UpdateFilter().
Range IPLab.HSLFilteringForm.luminance = new Range(0, 1) private
Referenced by IPLab.HSLFilteringForm.UpdateFilter().
int IPLab.HSLFilteringForm.fillH = 0 private
float IPLab.HSLFilteringForm.fillS = 0 private
float IPLab.HSLFilteringForm.fillL = 0 private
Referenced by IPLab.HSLFilteringForm.fillLBox_TextChanged(), IPLab.HSLFilteringForm.HSLFilteringForm(), and IPLab.HSLFilteringForm.UpdateFillColor().
AForge.Controls.HuePicker IPLab.HSLFilteringForm.huePicker private
Referenced by IPLab.HSLFilteringForm.huePicker_ValuesChanged(), IPLab.HSLFilteringForm.maxHBox_TextChanged(), and IPLab.HSLFilteringForm.minHBox_TextChanged().
System.Windows.Forms.GroupBox IPLab.HSLFilteringForm.groupBox1 private
System.Windows.Forms.Label IPLab.HSLFilteringForm.label1 private
System.Windows.Forms.Label IPLab.HSLFilteringForm.label2 private
System.Windows.Forms.TextBox IPLab.HSLFilteringForm.maxHBox private
Referenced by IPLab.HSLFilteringForm.HSLFilteringForm(), IPLab.HSLFilteringForm.huePicker_ValuesChanged(), and IPLab.HSLFilteringForm.maxHBox_TextChanged().
System.Windows.Forms.GroupBox IPLab.HSLFilteringForm.groupBox2 private
System.Windows.Forms.Label IPLab.HSLFilteringForm.label3 private
System.Windows.Forms.Label IPLab.HSLFilteringForm.label4 private
System.Windows.Forms.TextBox IPLab.HSLFilteringForm.minSBox private
Referenced by IPLab.HSLFilteringForm.HSLFilteringForm(), IPLab.HSLFilteringForm.minSBox_TextChanged(), and IPLab.HSLFilteringForm.saturationSlider_ValuesChanged().
System.Windows.Forms.TextBox IPLab.HSLFilteringForm.maxSBox private
Referenced by IPLab.HSLFilteringForm.HSLFilteringForm(), IPLab.HSLFilteringForm.maxSBox_TextChanged(), and IPLab.HSLFilteringForm.saturationSlider_ValuesChanged().
AForge.Controls.ColorSlider IPLab.HSLFilteringForm.saturationSlider private
Referenced by IPLab.HSLFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.HSLFilteringForm.maxSBox_TextChanged(), IPLab.HSLFilteringForm.minSBox_TextChanged(), IPLab.HSLFilteringForm.saturationSlider_ValuesChanged(), and IPLab.HSLFilteringForm.UpdateFillColor().
System.Windows.Forms.GroupBox IPLab.HSLFilteringForm.groupBox3 private
System.Windows.Forms.Label IPLab.HSLFilteringForm.label5 private
System.Windows.Forms.Label IPLab.HSLFilteringForm.label6 private
System.Windows.Forms.TextBox IPLab.HSLFilteringForm.minLBox private
Referenced by IPLab.HSLFilteringForm.HSLFilteringForm(), IPLab.HSLFilteringForm.luminanceSlider_ValuesChanged(), and IPLab.HSLFilteringForm.minLBox_TextChanged().
System.Windows.Forms.TextBox IPLab.HSLFilteringForm.maxLBox private
Referenced by IPLab.HSLFilteringForm.HSLFilteringForm(), IPLab.HSLFilteringForm.luminanceSlider_ValuesChanged(), and IPLab.HSLFilteringForm.maxLBox_TextChanged().
System.Windows.Forms.GroupBox IPLab.HSLFilteringForm.groupBox5 private
IPLab.FilterPreview IPLab.HSLFilteringForm.filterPreview private
Referenced by IPLab.HSLFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.HSLFilteringForm.HSLFilteringForm(), IPLab.HSLFilteringForm.UpdateFillColor(), IPLab.HSLFilteringForm.UpdateFilter(), IPLab.HSLFilteringForm.updateHCheck_CheckedChanged(), IPLab.HSLFilteringForm.updateLCheck_CheckedChanged(), and IPLab.HSLFilteringForm.updateSCheck_CheckedChanged().
System.Windows.Forms.GroupBox IPLab.HSLFilteringForm.groupBox4 private
System.Windows.Forms.Label IPLab.HSLFilteringForm.label7 private
System.Windows.Forms.TextBox IPLab.HSLFilteringForm.fillHBox private
Referenced by IPLab.HSLFilteringForm.fillHBox_TextChanged(), and IPLab.HSLFilteringForm.HSLFilteringForm().
System.Windows.Forms.CheckBox IPLab.HSLFilteringForm.updateHCheck private
Referenced by IPLab.HSLFilteringForm.updateHCheck_CheckedChanged().
System.Windows.Forms.Label IPLab.HSLFilteringForm.label8 private
System.Windows.Forms.TextBox IPLab.HSLFilteringForm.fillSBox private
Referenced by IPLab.HSLFilteringForm.fillSBox_TextChanged(), and IPLab.HSLFilteringForm.HSLFilteringForm().
System.Windows.Forms.CheckBox IPLab.HSLFilteringForm.updateSCheck private
Referenced by IPLab.HSLFilteringForm.updateSCheck_CheckedChanged().
System.Windows.Forms.Label IPLab.HSLFilteringForm.label9 private
System.Windows.Forms.TextBox IPLab.HSLFilteringForm.fillLBox private
Referenced by IPLab.HSLFilteringForm.fillLBox_TextChanged(), and IPLab.HSLFilteringForm.HSLFilteringForm().
System.Windows.Forms.CheckBox IPLab.HSLFilteringForm.updateLCheck private
Referenced by IPLab.HSLFilteringForm.updateLCheck_CheckedChanged().
System.Windows.Forms.ComboBox IPLab.HSLFilteringForm.fillTypeCombo private
Referenced by IPLab.HSLFilteringForm.fillTypeCombo_SelectedIndexChanged(), and IPLab.HSLFilteringForm.HSLFilteringForm().
System.Windows.Forms.Label IPLab.HSLFilteringForm.label10 private
System.Windows.Forms.Button IPLab.HSLFilteringForm.cancelButton private
System.Windows.Forms.Button IPLab.HSLFilteringForm.okButton private
System.Windows.Forms.TextBox IPLab.HSLFilteringForm.minHBox private
Referenced by IPLab.HSLFilteringForm.HSLFilteringForm(), IPLab.HSLFilteringForm.huePicker_ValuesChanged(), and IPLab.HSLFilteringForm.minHBox_TextChanged().
AForge.Controls.ColorSlider IPLab.HSLFilteringForm.luminanceSlider private
Referenced by IPLab.HSLFilteringForm.fillTypeCombo_SelectedIndexChanged(), IPLab.HSLFilteringForm.luminanceSlider_ValuesChanged(), IPLab.HSLFilteringForm.maxLBox_TextChanged(), IPLab.HSLFilteringForm.minLBox_TextChanged(), and IPLab.HSLFilteringForm.UpdateFillColor().
System.ComponentModel.Container IPLab.HSLFilteringForm.components = null private
Required designer variable.
Referenced by IPLab.HSLFilteringForm.Dispose().
Property Documentation
Bitmap IPLab.HSLFilteringForm.Image set
Referenced by IPLab.ImageDoc.filteringHslFiltersItem_Click().
IFilter IPLab.HSLFilteringForm.Filter get
Referenced by IPLab.ImageDoc.filteringHslFiltersItem_Click().
The documentation for this class was generated from the following file:
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/HSLFilteringForm.cs