IGLib: IG.Lib.MsgBase Class Reference
IG.Lib.MsgBase Class Reference
Base class for all messages.
Public Member Functions
void SetSenderLabex ()
Sets msg data such that sender is Labex and receiver is Bis.
void SetSenderBis ()
Sets msg data such that sender is Bis and receiver is Labex.
Public Member Functions inherited from IG.Lib.ParsableXmlObject
virtual void Save (string filename)
Saves contents of the msg to an xml file.
virtual void CreateXml ()
Creates msg Xml from the current msg data and stores it in this object.
virtual void Load (string filename)
Loads msg data from a file containing the XML msg.
virtual void LoadXml (string doc)
Loads msg data from a string containing the XML msg.
virtual void LoadXml (XmlDocument doc)
Loads msg data from an XmlDocument containing XML msg.
abstract void Read ()
Reads msg data from the internal XML document containing the msg.
abstract void Read (XmlParser data)
Read msg data from an XML document containing the msg.
virtual void CheckConsistency (AccummulatedReport rep)
Empty data consistency check, intended to be overridden in derived classes.
virtual void WriteToConsole ()
Writes cntents of the msg in a human readable form to the system console.
virtual void Write (string filename, bool append)
Writes cntents of the msg in a human readable form to a file.
abstract XmlDocument ToXml ()
Converts a msg to Xml and returns it.
Static Public Member Functions
static void SetMessageReceiverOld (ref XmlDocument msg, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false. WARNING: searching for receiver element is done through an XPath expression, which may fail due to default namespaces that were not detected.
static void SetMessageReceiver (ref string message, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageReceiver (ref XmlDocument msg, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageReceiver (ref XmlBuilder data, string receiver, out bool changed)
Sets the receiver of the communication msg stored in an Xml builder to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageSender (ref XmlBuilder data, string sender, out bool changed)
Sets the sender of the communication msg stored in an Xml builder to the specified sender, and indicates through an output argument whether the sender has been changed in msg. If the Sender stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageResponder (ref XmlBuilder data, string responder, out bool changed)
Sets the responder of the communication msg stored in an Xml builder to the specified responder, and indicates through an output argument whether the responder has been changed in msg. If the responder stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static MessageType GetMessageType (string msgstring)
Infers the msg type from the XML string containing the msg, and returns it.
static MessageType GetMessageType (XmlDocument msg)
Infers the msg type from the XML document containing the msg, and returns it.
static MessageType GetMessageType (XmlParser data)
Infers the msg type from the XML parser containing the msg, and returns it.
Public Attributes
MessageType Type = MessageType.Unknown
Message type. Helps with general methods that operate on any datatype of msg.
string MessageId = null
Message ID, obtained form the web service.
string MessageFile = null
Specifies the file where message has been backed up. Warning: this file may be deleted at any time!
string MessageNumber = null
Public Attributes inherited from IG.Lib.ParsableXmlObject
string XmlString = null
Static Protected Attributes
static string LabexIdLowercase = null
Properties
static MsgConst Const [get]
Gets objects that contains all constants related to communication messages.
string MessageXml [get, set]
Complete msg as obtained from the web service.
Properties inherited from IG.Lib.ParsableXmlObject
virtual IReporter R [get]
Reporter for this class.
XmlDocument Doc [get]
Returns the XML document representing the msg.
Static Private Member Functions
static bool IsSpecimenObservationOrder (XmlParser data)
Returns true if data contains a msg of type MessageType.SpecimenObservationOrder.
static bool IsSpecimenObservationEvent (XmlParser data)
Returns true if data contains a msg of type MessageType.SpecimenObservationEvent.
static bool IsDetailedFinancialTransaction (XmlParser data)
Returns true if data contains a msg of type MessageType.DetailedFinancialTransaction.
Private Attributes
string MessageNumberOid = null
string MessageReceiver = null
string MessageReceiverOid = null
string MessageResponder = null
string MessageResponderOid = null
string MessageSender = null
string MessageSenderOid = null
Static Private Attributes
static string BisIdLowercase = null
Additional Inherited Members
Protected Attributes inherited from IG.Lib.ParsableXmlObject
XmlBuilder Data = new XmlBuilder()
Detailed Description
Base class for all messages.
Member Function Documentation
void IG.Lib.MsgBase.SetSenderLabex () inline
Sets msg data such that sender is Labex and receiver is Bis.
References IG.Lib.MsgConst.Const, and IG.Lib.MsgConstCommon.LabexId.
Referenced by IGTest.ProgramIGTest.TestMsgFinancialTransaction(), and IGTest.ProgramIGTest.TestMsgObservationEvent().
void IG.Lib.MsgBase.SetSenderBis () inline
Sets msg data such that sender is Bis and receiver is Labex.
References IG.Lib.MsgConst.Const, and IG.Lib.MsgConstCommon.LabexId.
static void IG.Lib.MsgBase.SetMessageReceiverOld (ref XmlDocument msg, string receiver, out bool changed) inline static
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false. WARNING: searching for receiver element is done through an XPath expression, which may fail due to default namespaces that were not detected.
Parameters
msg Message in which receiver should be set.
receiver The new receiver of the msg.
changed Indicates whether the msg has been changed (i.e., whether the new receiver has been written to the msg).
static void IG.Lib.MsgBase.SetMessageReceiver (ref string message, string receiver, out bool changed) inline static
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
Parameters
msg Message document in which receiver should be set.
receiver The new receiver of the msg.
changed Indicates whether the msg has been changed (i.e., whether the new receiver has been written to the msg).
Referenced by LabexBis.Calypso.SendMessage().
static void IG.Lib.MsgBase.SetMessageReceiver (ref XmlDocument msg, string receiver, out bool changed) inline static
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
Parameters
msg Message in which receiver should be set.
receiver The new receiver of the msg.
changed Indicates whether the msg has been changed (i.e., whether the new receiver has been written to the msg).
References IG.Lib.XmlUtilityBase.LoadXml().
static void IG.Lib.MsgBase.SetMessageReceiver (ref XmlBuilder data, string receiver, out bool changed) inline static
Sets the receiver of the communication msg stored in an Xml builder to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
Parameters
data XML builder containing the msg where receiver is to be set.
receiver The new receiver of the msg.
changed Indicates whether the msg has been changed (i.e., whether the new receiver has been written to the msg).
static void IG.Lib.MsgBase.SetMessageSender (ref XmlBuilder data, string sender, out bool changed) inline static
Sets the sender of the communication msg stored in an Xml builder to the specified sender, and indicates through an output argument whether the sender has been changed in msg. If the Sender stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
Parameters
data XML builder containing the msg where Sender is to be set.
sender The new Sender of the msg.
changed Indicates whether the msg has been changed (i.e., whether the new Sender has been written to the msg).
static void IG.Lib.MsgBase.SetMessageResponder (ref XmlBuilder data, string responder, out bool changed) inline static
Sets the responder of the communication msg stored in an Xml builder to the specified responder, and indicates through an output argument whether the responder has been changed in msg. If the responder stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
Parameters
data XML builder containing the msg where responder is to be set.
responder The new responder of the msg.
changed Indicates whether the msg has been changed (i.e., whether the new responder has been written to the msg).
static bool IG.Lib.MsgBase.IsSpecimenObservationOrder (XmlParser data) inline static private
Returns true if data contains a msg of type MessageType.SpecimenObservationOrder.
Parameters
data XmlParser containing the msg.
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.GoToRoot(), IG.Lib.XmlParser.Name, IG.Lib.XmlParser.NextOrCurrentElement(), and IG.Lib.XmlParser.StepIn().
static bool IG.Lib.MsgBase.IsSpecimenObservationEvent (XmlParser data) inline static private
Returns true if data contains a msg of type MessageType.SpecimenObservationEvent.
Parameters
data XmlParser containing the msg.
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.GoToRoot(), IG.Lib.XmlParser.Name, IG.Lib.XmlParser.NextOrCurrentElement(), and IG.Lib.XmlParser.StepIn().
static bool IG.Lib.MsgBase.IsDetailedFinancialTransaction (XmlParser data) inline static private
Returns true if data contains a msg of type MessageType.DetailedFinancialTransaction.
Parameters
data XmlParser containing the msg.
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.GoToRoot(), IG.Lib.XmlParser.Name, IG.Lib.XmlParser.NextOrCurrentElement(), and IG.Lib.XmlParser.StepIn().
static MessageType IG.Lib.MsgBase.GetMessageType (string msgstring) inline static
Infers the msg type from the XML string containing the msg, and returns it.
Parameters
msgstring Message string.
Returns
The type of the msg.
Referenced by LabexBis.Calypso.GetMessage().
static MessageType IG.Lib.MsgBase.GetMessageType (XmlDocument msg) inline static
Infers the msg type from the XML document containing the msg, and returns it.
Parameters
msg Xml document containing the msg.
Returns
Message type (null if the type could not be inferred).
References IG.Lib.XmlUtilityBase.LoadXml().
static MessageType IG.Lib.MsgBase.GetMessageType (XmlParser data) inline static
Infers the msg type from the XML parser containing the msg, and returns it.
Parameters
msg Xml parser containing the msg.
Returns
Message type (null if the type could not be inferred).
Member Data Documentation
MessageType IG.Lib.MsgBase.Type = MessageType.Unknown
Message type. Helps with general methods that operate on any datatype of msg.
Referenced by IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), LabexBis.Calypso.SendOoNullifyToBis(), and IGTest.ProgramIGTest.TestCalypsoWs().
string IG.Lib.MsgBase.MessageId = null
Message ID, obtained form the web service.
Referenced by LabexBis.Calypso.GetMessage(), IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), LabexBis.Calypso.SaveIncomingMessage(), LabexBis.Calypso.SendOoNullifyToBis(), and IGTest.ProgramIGTest.TestMsgObservationOrderNullifySend().
string IG.Lib.MsgBase.MessageFile = null
Specifies the file where message has been backed up. Warning: this file may be deleted at any time!
Referenced by LabexBis.Calypso.GetMessage().
string IG.Lib.MsgBase.MessageNumber = null
Referenced by LabexBis.Calypso.SendOoNullifyToBis(), IGTest.ProgramIGTest.TestMsgFinancialTransaction(), and IGTest.ProgramIGTest.TestMsgObservationEvent().
string IG.Lib.MsgBase.MessageNumberOid = null private
string IG.Lib.MsgBase.MessageReceiver = null private
string IG.Lib.MsgBase.MessageReceiverOid = null private
string IG.Lib.MsgBase.MessageResponder = null private
string IG.Lib.MsgBase.MessageResponderOid = null private
string IG.Lib.MsgBase.MessageSender = null private
string IG.Lib.MsgBase.MessageSenderOid = null private
string IG.Lib.MsgBase.LabexIdLowercase = null static protected
string IG.Lib.MsgBase.BisIdLowercase = null static private
Property Documentation
MsgConst IG.Lib.MsgBase.Const static get protected
Gets objects that contains all constants related to communication messages.
string IG.Lib.MsgBase.MessageXml get set
Complete msg as obtained from the web service.
Referenced by LabexBis.Calypso.GetMessage(), IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), and LabexBis.Calypso.SaveIncomingMessage().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/LabexBis/MessagesBis.cs