IGLib: Meta.Numerics.Statistics.UncertainMeasurementSample Class Reference
Meta.Numerics.Statistics.UncertainMeasurementSample Class Reference
Represents a set of UncertainMeasurement{Double} measurements.
Public Member Functions
UncertainMeasurementSample ()
Initializes a new, empty data set.
UncertainMeasurementSample (IEnumerable< UncertainMeasurement< double >> data)
Initializes a new data set with the specified data.
FitResult FitToConstant ()
Fits the data to a constant value.
FitResult FitToProportionality ()
Fit the data to a proportionality relationship.
FitResult FitToLine ()
Fits the data to a line.
FitResult FitToPolynomial (int order)
Fits the data to a polynomial.
Detailed Description
Represents a set of UncertainMeasurement{Double} measurements.
This class adds functionality to the UncertainMeasurementSample class which applies when the independent variable (X variable) is a single real number. This includes fitting to a constant, line, or polynomial.
Constructor & Destructor Documentation
Meta.Numerics.Statistics.UncertainMeasurementSample.UncertainMeasurementSample () inline
Initializes a new, empty data set.
Meta.Numerics.Statistics.UncertainMeasurementSample.UncertainMeasurementSample (IEnumerable< UncertainMeasurement< double >> data) inline
Initializes a new data set with the specified data.
Parameters
data An enumerator over the UncertainMeasurement{Double}s to place in the set.
Member Function Documentation
FitResult Meta.Numerics.Statistics.UncertainMeasurementSample.FitToConstant () inline
Fits the data to a constant value.
Returns
A fit result containing the best combined value and a &#x3C7;2 test of the quality of the fit.
This method provides a simple way to
Referenced by Test.DataSetTest.FitDataToLineTest().
FitResult Meta.Numerics.Statistics.UncertainMeasurementSample.FitToProportionality () inline
Fit the data to a proportionality relationship.
Returns
A fit result containing the best-fit proportionality constant parameter and a &#x3C7;2 test of the quality of the fit.
Referenced by Test.DataSetTest.FitDataToProportionalityTest().
FitResult Meta.Numerics.Statistics.UncertainMeasurementSample.FitToLine () inline
Fits the data to a line.
Returns
A fit result containing the best-fit intercept and slope parameters and a &#x3C7;2 test of the quality of the fit.
Referenced by Test.DataSetTest.FitDataToLineChiSquaredTest(), Test.DataSetTest.FitDataToLineTest(), Test.DataSetTest.FitDataToLineUncertaintyTest(), Test.DataSetTest.FitDataToProportionalityTest(), and Test.DataSetTest.FitToFunctionLinearCompatibilityTest().
FitResult Meta.Numerics.Statistics.UncertainMeasurementSample.FitToPolynomial (int order) inline
Fits the data to a polynomial.
Parameters
order The order of the polynomial to fit.
Returns
A fit result containg the best-fit polynomial coefficients, in order of ascending power from 0 to order , and a &#x3C7;2 test of the quality of the fit.
Exceptions
InvalidOperationException There are more polynomial coefficients than data points.
References Meta.Numerics.MoreMath.Pow().
Referenced by Test.BugTests.Bug6162(), Test.DataSetTest.FitDataToLineTest(), Test.DataSetTest.FitDataToPolynomialChiSquaredTest(), Test.DataSetTest.FitDataToPolynomialTest(), Test.DataSetTest.FitDataToPolynomialUncertaintiesTest(), and Test.DataSetTest.FitToFunctionPolynomialCompatibilityTest().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/UncertainMeasurementSample.cs