IGLib: PipeClient.Form1 Class Reference
PipeClient.Form1 Class Reference
Public Member Functions
Form1 ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void pipeClient_MessageReceived (string message)
void DisplayReceivedMessage (string message)
void btnStart_Click (object sender, EventArgs e)
void btnSend_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Client pipeClient
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblReceived
System.Windows.Forms.TextBox tbReceived
System.Windows.Forms.Button btnSend
System.Windows.Forms.Label lblSend
System.Windows.Forms.TextBox tbSend
System.Windows.Forms.Button btnStart
System.Windows.Forms.Label lblPipeName
System.Windows.Forms.TextBox tbPipeName
Constructor & Destructor Documentation
PipeClient.Form1.Form1 () inline
References PipeClient.Form1.InitializeComponent(), PipeClient.Client.MessageReceived, PipeClient.Client.MessageReceivedHandler(), and PipeClient.Form1.pipeClient_MessageReceived().
Member Function Documentation
void PipeClient.Form1.pipeClient_MessageReceived (string message) inline private
References PipeClient.Form1.DisplayReceivedMessage(), and PipeClient.Client.MessageReceivedHandler().
Referenced by PipeClient.Form1.Form1().
void PipeClient.Form1.DisplayReceivedMessage (string message) inline private
References PipeClient.Form1.tbReceived.
Referenced by PipeClient.Form1.pipeClient_MessageReceived().
void PipeClient.Form1.btnStart_Click (object sender, EventArgs e) inline private
References PipeClient.Form1.btnStart, PipeClient.Client.Connect(), PipeClient.Client.Connected, PipeClient.Client.PipeName, and PipeClient.Form1.tbPipeName.
Referenced by PipeClient.Form1.InitializeComponent().
void PipeClient.Form1.btnSend_Click (object sender, EventArgs e) inline private
References PipeClient.Client.SendMessage(), and PipeClient.Form1.tbSend.
Referenced by PipeClient.Form1.InitializeComponent().
override void PipeClient.Form1.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References PipeClient.Form1.components.
void PipeClient.Form1.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References PipeClient.Form1.btnSend, PipeClient.Form1.btnSend_Click(), PipeClient.Form1.btnStart, PipeClient.Form1.btnStart_Click(), PipeClient.Form1.lblPipeName, PipeClient.Form1.lblReceived, PipeClient.Form1.lblSend, PipeClient.Form1.tbPipeName, PipeClient.Form1.tbReceived, and PipeClient.Form1.tbSend.
Referenced by PipeClient.Form1.Form1().
Member Data Documentation
Client PipeClient.Form1.pipeClient private
System.ComponentModel.IContainer PipeClient.Form1.components = null private
Required designer variable.
Referenced by PipeClient.Form1.Dispose().
System.Windows.Forms.Label PipeClient.Form1.lblReceived private
Referenced by PipeClient.Form1.InitializeComponent().
System.Windows.Forms.TextBox PipeClient.Form1.tbReceived private
Referenced by PipeClient.Form1.DisplayReceivedMessage(), and PipeClient.Form1.InitializeComponent().
System.Windows.Forms.Button PipeClient.Form1.btnSend private
Referenced by PipeClient.Form1.InitializeComponent().
System.Windows.Forms.Label PipeClient.Form1.lblSend private
Referenced by PipeClient.Form1.InitializeComponent().
System.Windows.Forms.TextBox PipeClient.Form1.tbSend private
Referenced by PipeClient.Form1.btnSend_Click(), and PipeClient.Form1.InitializeComponent().
System.Windows.Forms.Button PipeClient.Form1.btnStart private
Referenced by PipeClient.Form1.btnStart_Click(), and PipeClient.Form1.InitializeComponent().
System.Windows.Forms.Label PipeClient.Form1.lblPipeName private
Referenced by PipeClient.Form1.InitializeComponent().
System.Windows.Forms.TextBox PipeClient.Form1.tbPipeName private
Referenced by PipeClient.Form1.btnStart_Click(), and PipeClient.Form1.InitializeComponent().
The documentation for this class was generated from the following files:
igsandbox/InterprocessCommunication/named_pipe_examples_master/C# client & server - named pipe/PipeClient/PipeClient/Form1.cs
igsandbox/InterprocessCommunication/named_pipe_examples_master/C# client & server - named pipe/PipeClient/PipeClient/Form1.Designer.cs