IGLib: NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier Class Reference
NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier Class Reference
Classes
class IntArrayEqualComparer
class IntListEqualComparer
Public Member Functions
void UsesProvidedIComparer ()
void UsesProvidedEqualityComparer ()
void UsesProvidedGenericEqualityComparer ()
void UsesProvidedGenericComparer ()
void UsesProvidedGenericComparison ()
void UsesProvidedLambda_IntArgs ()
void UsesProvidedLambda_StringArgs ()
void UsesProvidedListComparer ()
void UsesProvidedArrayComparer ()
Member Function Documentation
void NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedIComparer () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedEqualityComparer () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedGenericEqualityComparer () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedGenericComparer () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedGenericComparison () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedLambda_IntArgs () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedLambda_StringArgs () inline
References NUnit.Framework.Internal.StringUtil.Compare(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedListComparer () inline
References NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.EqualConstraintTests.UsingModifier.UsesProvidedArrayComparer () inline
References NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs