IGLib: alglib.testmatinvunit Class Reference
alglib.testmatinvunit Class Reference
Static Public Member Functions
static bool testmatinv (bool silent)
static bool testmatinv (bool silent)
static bool _pexec_testmatinv (bool silent)
Static Private Member Functions
static void rmatrixmakeacopy (double[,] a, int m, int n, ref double[,] b)
static void cmatrixmakeacopy (complex[,] a, int m, int n, ref complex[,] b)
static bool rmatrixcheckinverse (double[,] a, double[,] inva, int n, double threshold, int info, matinv.matinvreport rep)
static bool spdmatrixcheckinverse (double[,] a, double[,] inva, bool isupper, int n, double threshold, int info, matinv.matinvreport rep)
static bool hpdmatrixcheckinverse (complex[,] a, complex[,] inva, bool isupper, int n, double threshold, int info, matinv.matinvreport rep)
static bool rmatrixcheckinversesingular (double[,] inva, int n, double threshold, int info, matinv.matinvreport rep)
static bool cmatrixcheckinverse (complex[,] a, complex[,] inva, int n, double threshold, int info, matinv.matinvreport rep)
static bool cmatrixcheckinversesingular (complex[,] inva, int n, double threshold, int info, matinv.matinvreport rep)
static void rmatrixdrophalf (ref double[,] a, int n, bool droplower)
static void cmatrixdrophalf (ref complex[,] a, int n, bool droplower)
static void testrtrinv (int maxn, int passcount, double threshold, ref bool rtrerrors)
static void testctrinv (int maxn, int passcount, double threshold, ref bool ctrerrors)
static void testrinv (int maxn, int passcount, double threshold, ref bool rerrors)
static void testcinv (int maxn, int passcount, double threshold, ref bool cerrors)
static void testspdinv (int maxn, int passcount, double threshold, ref bool spderrors)
static void testhpdinv (int maxn, int passcount, double threshold, ref bool hpderrors)
static void unset2d (ref double[,] x)
static void unset1d (ref double[] x)
static void cunset2d (ref complex[,] x)
static void cunset1d (ref complex[] x)
static void unsetrep (matinv.matinvreport r)
static void rmatrixmakeacopy (double[,] a, int m, int n, ref double[,] b)
static void cmatrixmakeacopy (complex[,] a, int m, int n, ref complex[,] b)
static bool rmatrixcheckinverse (double[,] a, double[,] inva, int n, double threshold, int info, matinv.matinvreport rep)
static bool spdmatrixcheckinverse (double[,] a, double[,] inva, bool isupper, int n, double threshold, int info, matinv.matinvreport rep)
static bool hpdmatrixcheckinverse (complex[,] a, complex[,] inva, bool isupper, int n, double threshold, int info, matinv.matinvreport rep)
static bool rmatrixcheckinversesingular (double[,] inva, int n, double threshold, int info, matinv.matinvreport rep)
static bool cmatrixcheckinverse (complex[,] a, complex[,] inva, int n, double threshold, int info, matinv.matinvreport rep)
static bool cmatrixcheckinversesingular (complex[,] inva, int n, double threshold, int info, matinv.matinvreport rep)
static void rmatrixdrophalf (ref double[,] a, int n, bool droplower)
static void cmatrixdrophalf (ref complex[,] a, int n, bool droplower)
static void testrtrinv (int maxn, int passcount, double threshold, ref bool rtrerrors)
static void testctrinv (int maxn, int passcount, double threshold, ref bool ctrerrors)
static void testrinv (int maxn, int passcount, double threshold, ref bool rerrors)
static void testcinv (int maxn, int passcount, double threshold, ref bool cerrors)
static void testspdinv (int maxn, int passcount, double threshold, ref bool spderrors)
static void testhpdinv (int maxn, int passcount, double threshold, ref bool hpderrors)
static void unset2d (ref double[,] x)
static void unset1d (ref double[] x)
static void cunset2d (ref complex[,] x)
static void cunset1d (ref complex[] x)
static void unsetrep (matinv.matinvreport r)
Member Function Documentation
static bool alglib.testmatinvunit.testmatinv (bool silent) inline static
References alglib.ablas.ablasblocksize(), alglib.math.machineepsilon, alglib.testmatinvunit.testcinv(), alglib.testmatinvunit.testctrinv(), alglib.testmatinvunit.testhpdinv(), alglib.testmatinvunit.testrinv(), alglib.testmatinvunit.testrtrinv(), and alglib.testmatinvunit.testspdinv().
Referenced by alglib.testmatinvunit._pexec_testmatinv(), and _Test.Main().
static void alglib.testmatinvunit.rmatrixmakeacopy (double a[,], int m, int n, ref double b[,]) inline static private
Referenced by alglib.testmatinvunit.testrinv(), and alglib.testmatinvunit.testspdinv().
static void alglib.testmatinvunit.cmatrixmakeacopy (complex a[,], int m, int n, ref complex b[,]) inline static private
Referenced by alglib.testmatinvunit.testcinv(), and alglib.testmatinvunit.testhpdinv().
static bool alglib.testmatinvunit.rmatrixcheckinverse (double a[,], double inva[,], int n, double threshold, int info, matinv.matinvreport rep) inline static private
References alglib.math.machineepsilon.
Referenced by alglib.testmatinvunit.testrinv().
static bool alglib.testmatinvunit.spdmatrixcheckinverse (double a[,], double inva[,], bool isupper, int n, double threshold, int info, matinv.matinvreport rep) inline static private
References alglib.math.machineepsilon.
Referenced by alglib.testmatinvunit.testspdinv().
static bool alglib.testmatinvunit.hpdmatrixcheckinverse (complex a[,], complex inva[,], bool isupper, int n, double threshold, int info, matinv.matinvreport rep) inline static private
References alglib.math.abscomplex(), alglib.math.conj(), and alglib.math.machineepsilon.
Referenced by alglib.testmatinvunit.testhpdinv().
static bool alglib.testmatinvunit.rmatrixcheckinversesingular (double inva[,], int n, double threshold, int info, matinv.matinvreport rep) inline static private
References alglib.math.machineepsilon.
Referenced by alglib.testmatinvunit.testrinv().
static bool alglib.testmatinvunit.cmatrixcheckinverse (complex a[,], complex inva[,], int n, double threshold, int info, matinv.matinvreport rep) inline static private
References alglib.math.abscomplex(), and alglib.math.machineepsilon.
Referenced by alglib.testmatinvunit.testcinv().
static bool alglib.testmatinvunit.cmatrixcheckinversesingular (complex inva[,], int n, double threshold, int info, matinv.matinvreport rep) inline static private
References alglib.math.machineepsilon.
Referenced by alglib.testmatinvunit.testcinv().
static void alglib.testmatinvunit.rmatrixdrophalf (ref double a[,], int n, bool droplower) inline static private
Referenced by alglib.testmatinvunit.testspdinv().
static void alglib.testmatinvunit.cmatrixdrophalf (ref complex a[,], int n, bool droplower) inline static private
Referenced by alglib.testmatinvunit.testhpdinv().
static void alglib.testmatinvunit.testrtrinv (int maxn, int passcount, double threshold, ref bool rtrerrors) inline static private
References alglib.math.randomreal(), and alglib.matinv.rmatrixtrinverse().
Referenced by alglib.testmatinvunit.testmatinv().
static void alglib.testmatinvunit.testctrinv (int maxn, int passcount, double threshold, ref bool ctrerrors) inline static private
References alglib.math.abscomplex(), alglib.matinv.cmatrixtrinverse(), alglib.math.randomreal(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testmatinvunit.testmatinv().
static void alglib.testmatinvunit.testrinv (int maxn, int passcount, double threshold, ref bool rerrors) inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.testmatinvunit.rmatrixcheckinverse(), alglib.testmatinvunit.rmatrixcheckinversesingular(), alglib.matinv.rmatrixinverse(), alglib.trfac.rmatrixlu(), alglib.matinv.rmatrixluinverse(), alglib.testmatinvunit.rmatrixmakeacopy(), alglib.matgen.rmatrixrndcond(), alglib.testmatinvunit.unset2d(), and alglib.testmatinvunit.unsetrep().
Referenced by alglib.testmatinvunit.testmatinv().
static void alglib.testmatinvunit.testcinv (int maxn, int passcount, double threshold, ref bool cerrors) inline static private
References alglib.testmatinvunit.cmatrixcheckinverse(), alglib.testmatinvunit.cmatrixcheckinversesingular(), alglib.matinv.cmatrixinverse(), alglib.trfac.cmatrixlu(), alglib.matinv.cmatrixluinverse(), alglib.testmatinvunit.cmatrixmakeacopy(), alglib.matgen.cmatrixrndcond(), alglib.testmatinvunit.cunset2d(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.testmatinvunit.unsetrep(), and alglib.complex.x.
Referenced by alglib.testmatinvunit.testmatinv().
static void alglib.testmatinvunit.testspdinv (int maxn, int passcount, double threshold, ref bool spderrors) inline static private
References alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testmatinvunit.rmatrixdrophalf(), alglib.testmatinvunit.rmatrixmakeacopy(), alglib.testmatinvunit.spdmatrixcheckinverse(), alglib.trfac.spdmatrixcholesky(), alglib.matinv.spdmatrixcholeskyinverse(), alglib.matinv.spdmatrixinverse(), alglib.matgen.spdmatrixrndcond(), alglib.testmatinvunit.unset2d(), and alglib.testmatinvunit.unsetrep().
Referenced by alglib.testmatinvunit.testmatinv().
static void alglib.testmatinvunit.testhpdinv (int maxn, int passcount, double threshold, ref bool hpderrors) inline static private
References alglib.testmatinvunit.cmatrixdrophalf(), alglib.testmatinvunit.cmatrixmakeacopy(), alglib.testmatinvunit.cunset2d(), alglib.testmatinvunit.hpdmatrixcheckinverse(), alglib.trfac.hpdmatrixcholesky(), alglib.matinv.hpdmatrixcholeskyinverse(), alglib.matinv.hpdmatrixinverse(), alglib.matgen.hpdmatrixrndcond(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testmatinvunit.unsetrep(), and alglib.complex.x.
Referenced by alglib.testmatinvunit.testmatinv().
static void alglib.testmatinvunit.unset2d (ref double x[,]) inline static private
References alglib.math.randomreal().
Referenced by alglib.testmatinvunit.testrinv(), and alglib.testmatinvunit.testspdinv().
static void alglib.testmatinvunit.unset1d (ref double[] x) inline static private
References alglib.math.randomreal().
static void alglib.testmatinvunit.cunset2d (ref complex x[,]) inline static private
References alglib.math.randomreal().
Referenced by alglib.testmatinvunit.testcinv(), and alglib.testmatinvunit.testhpdinv().
static void alglib.testmatinvunit.cunset1d (ref complex[] x) inline static private
References alglib.math.randomreal().
static void alglib.testmatinvunit.unsetrep (matinv.matinvreport r) inline static private
Referenced by alglib.testmatinvunit.testcinv(), alglib.testmatinvunit.testhpdinv(), alglib.testmatinvunit.testrinv(), and alglib.testmatinvunit.testspdinv().
static bool alglib.testmatinvunit.testmatinv (bool silent) inline static
References alglib.ablas.ablasblocksize(), alglib.math.machineepsilon, alglib.testmatinvunit.testcinv(), alglib.testmatinvunit.testctrinv(), alglib.testmatinvunit.testhpdinv(), alglib.testmatinvunit.testrinv(), alglib.testmatinvunit.testrtrinv(), and alglib.testmatinvunit.testspdinv().
static bool alglib.testmatinvunit._pexec_testmatinv (bool silent) inline static
References alglib.testmatinvunit.testmatinv().
Referenced by _Test.Main().
static void alglib.testmatinvunit.rmatrixmakeacopy (double a[,], int m, int n, ref double b[,]) inline static private
static void alglib.testmatinvunit.cmatrixmakeacopy (complex a[,], int m, int n, ref complex b[,]) inline static private
static bool alglib.testmatinvunit.rmatrixcheckinverse (double a[,], double inva[,], int n, double threshold, int info, matinv.matinvreport rep) inline static private
References alglib.math.machineepsilon.
static bool alglib.testmatinvunit.spdmatrixcheckinverse (double a[,], double inva[,], bool isupper, int n, double threshold, int info, matinv.matinvreport rep) inline static private
References alglib.math.machineepsilon.
static bool alglib.testmatinvunit.hpdmatrixcheckinverse (complex a[,], complex inva[,], bool isupper, int n, double threshold, int info, matinv.matinvreport rep) inline static private
References alglib.math.abscomplex(), alglib.math.conj(), and alglib.math.machineepsilon.
static bool alglib.testmatinvunit.rmatrixcheckinversesingular (double inva[,], int n, double threshold, int info, matinv.matinvreport rep) inline static private
References alglib.math.machineepsilon.
static bool alglib.testmatinvunit.cmatrixcheckinverse (complex a[,], complex inva[,], int n, double threshold, int info, matinv.matinvreport rep) inline static private
References alglib.math.abscomplex(), and alglib.math.machineepsilon.
static bool alglib.testmatinvunit.cmatrixcheckinversesingular (complex inva[,], int n, double threshold, int info, matinv.matinvreport rep) inline static private
References alglib.math.machineepsilon.
static void alglib.testmatinvunit.rmatrixdrophalf (ref double a[,], int n, bool droplower) inline static private
static void alglib.testmatinvunit.cmatrixdrophalf (ref complex a[,], int n, bool droplower) inline static private
static void alglib.testmatinvunit.testrtrinv (int maxn, int passcount, double threshold, ref bool rtrerrors) inline static private
References alglib.math.randomreal(), and alglib.matinv.rmatrixtrinverse().
static void alglib.testmatinvunit.testctrinv (int maxn, int passcount, double threshold, ref bool ctrerrors) inline static private
References alglib.math.abscomplex(), alglib.matinv.cmatrixtrinverse(), alglib.math.randomreal(), alglib.complex.x, and alglib.complex.y.
static void alglib.testmatinvunit.testrinv (int maxn, int passcount, double threshold, ref bool rerrors) inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.testmatinvunit.rmatrixcheckinverse(), alglib.testmatinvunit.rmatrixcheckinversesingular(), alglib.matinv.rmatrixinverse(), alglib.trfac.rmatrixlu(), alglib.matinv.rmatrixluinverse(), alglib.testmatinvunit.rmatrixmakeacopy(), alglib.matgen.rmatrixrndcond(), alglib.testmatinvunit.unset2d(), and alglib.testmatinvunit.unsetrep().
static void alglib.testmatinvunit.testcinv (int maxn, int passcount, double threshold, ref bool cerrors) inline static private
References alglib.testmatinvunit.cmatrixcheckinverse(), alglib.testmatinvunit.cmatrixcheckinversesingular(), alglib.matinv.cmatrixinverse(), alglib.trfac.cmatrixlu(), alglib.matinv.cmatrixluinverse(), alglib.testmatinvunit.cmatrixmakeacopy(), alglib.matgen.cmatrixrndcond(), alglib.testmatinvunit.cunset2d(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.testmatinvunit.unsetrep(), and alglib.complex.x.
static void alglib.testmatinvunit.testspdinv (int maxn, int passcount, double threshold, ref bool spderrors) inline static private
References alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testmatinvunit.rmatrixdrophalf(), alglib.testmatinvunit.rmatrixmakeacopy(), alglib.testmatinvunit.spdmatrixcheckinverse(), alglib.trfac.spdmatrixcholesky(), alglib.matinv.spdmatrixcholeskyinverse(), alglib.matinv.spdmatrixinverse(), alglib.matgen.spdmatrixrndcond(), alglib.testmatinvunit.unset2d(), and alglib.testmatinvunit.unsetrep().
static void alglib.testmatinvunit.testhpdinv (int maxn, int passcount, double threshold, ref bool hpderrors) inline static private
References alglib.testmatinvunit.cmatrixdrophalf(), alglib.testmatinvunit.cmatrixmakeacopy(), alglib.testmatinvunit.cunset2d(), alglib.testmatinvunit.hpdmatrixcheckinverse(), alglib.trfac.hpdmatrixcholesky(), alglib.matinv.hpdmatrixcholeskyinverse(), alglib.matinv.hpdmatrixinverse(), alglib.matgen.hpdmatrixrndcond(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testmatinvunit.unsetrep(), and alglib.complex.x.
static void alglib.testmatinvunit.unset2d (ref double x[,]) inline static private
References alglib.math.randomreal().
static void alglib.testmatinvunit.unset1d (ref double[] x) inline static private
References alglib.math.randomreal().
static void alglib.testmatinvunit.cunset2d (ref complex x[,]) inline static private
References alglib.math.randomreal().
static void alglib.testmatinvunit.cunset1d (ref complex[] x) inline static private
References alglib.math.randomreal().
static void alglib.testmatinvunit.unsetrep (matinv.matinvreport r) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs