IGLib: NUnit.Framework.Throws Class Reference
NUnit.Framework.Throws Class Reference
Helper class with properties and methods that supply constraints that operate on exceptions.
Static Public Member Functions
static ExactTypeConstraint TypeOf (Type expectedType)
Creates a constraint specifying the exact type of exception expected
static ExactTypeConstraint TypeOf< TExpected > ()
Creates a constraint specifying the exact type of exception expected
static InstanceOfTypeConstraint InstanceOf (Type expectedType)
Creates a constraint specifying the type of exception expected
static InstanceOfTypeConstraint InstanceOf< TExpected > ()
Creates a constraint specifying the type of exception expected
Properties
static
ResolvableConstraintExpression Exception [get]
Creates a constraint specifying an expected exception
static
ResolvableConstraintExpression InnerException [get]
Creates a constraint specifying an exception with a given InnerException
static ExactTypeConstraint TargetInvocationException [get]
Creates a constraint specifying an expected TargetInvocationException
static ExactTypeConstraint ArgumentException [get]
Creates a constraint specifying an expected ArgumentException
static ExactTypeConstraint ArgumentNullException [get]
Creates a constraint specifying an expected ArgumentNUllException
static ExactTypeConstraint InvalidOperationException [get]
Creates a constraint specifying an expected InvalidOperationException
static ThrowsNothingConstraint Nothing [get]
Creates a constraint specifying that no exception is thrown
Detailed Description
Helper class with properties and methods that supply constraints that operate on exceptions.
Member Function Documentation
static ExactTypeConstraint NUnit.Framework.Throws.TypeOf (Type expectedType) inline static
Creates a constraint specifying the exact type of exception expected
Referenced by NUnit.Framework.Attributes.MaxTimeTests.FailureReport(), NUnit.Framework.Constraints.RangeTests.InRangeFails(), NUnit.Common.Tests.OutputSpecificationTests.MultipleFormatSpecifiersNotAllowed(), NUnit.Common.Tests.OutputSpecificationTests.MultipleTransformSpecifiersNotAllowed(), NUnit.Framework.Constraints.RangeTests.NotInRangeFails(), NUnit.Engine.Services.Tests.ResultServiceTests.NUnit3Format_NullArgument_ThrowsArgumentNullException(), NUnit.Common.Tests.OutputSpecificationTests.SpecMayNotBeNull(), NUnit.Common.Tests.OutputSpecificationTests.SpecOptionMustContainEqualSign(), NUnit.Common.Tests.OutputSpecificationTests.SpecOptionMustContainJustOneEqualSign(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestModeMustFollowTolerance(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestModesCanOnlyBeUsedOnce(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestNumericToleranceRequired(), NUnit.Common.Tests.TestSelectionParserTests.TestParser_InvalidInput(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestWithinCanOnlyBeUsedOnce(), NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionException(), NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionException_MessageSpecified(), NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionExceptionWithMessage(), NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionExceptionWithMessageAndArgs(), NUnit.Framework.Assertions.AssertIgnoreTests.ThrowsIgnoreException(), NUnit.Framework.Assertions.AssertIgnoreTests.ThrowsIgnoreExceptionWithMessage(), NUnit.Framework.Assertions.AssertIgnoreTests.ThrowsIgnoreExceptionWithMessageAndArgs(), NUnit.Framework.Assertions.AssertInconclusiveTests.ThrowsInconclusiveException(), NUnit.Framework.Assertions.AssertInconclusiveTests.ThrowsInconclusiveExceptionWithMessage(), NUnit.Framework.Assertions.AssertInconclusiveTests.ThrowsInconclusiveExceptionWithMessageAndArgs(), NUnit.Framework.Assertions.AssertPassTests.ThrowsSuccessException(), NUnit.Framework.Assertions.AssertPassTests.ThrowsSuccessExceptionWithMessage(), NUnit.Framework.Assertions.AssertPassTests.ThrowsSuccessExceptionWithMessageAndArgs(), NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOf(), NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOfAndConstraint(), NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOfWithConstraint(), and NUnit.Common.Tests.OutputSpecificationTests.TransformWithNonUserFormatNotAllowed().
static ExactTypeConstraint NUnit.Framework.Throws.TypeOf< TExpected > () inline static
Creates a constraint specifying the exact type of exception expected
static InstanceOfTypeConstraint NUnit.Framework.Throws.InstanceOf (Type expectedType) inline static
Creates a constraint specifying the type of exception expected
Referenced by NUnit.Engine.Services.Tests.ServiceManagerTests.InitializationFailure(), NUnit.Framework.Syntax.ThrowsTests.LambdaThrowsException(), NUnit.Framework.Syntax.ThrowsTests.LambdaThrowsExceptionWithMessage(), NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbabilityOutOfRange(), NUnit.Framework.Internal.RandomizerTests.RandomByteInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalRangeTooGreat(), NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomLongInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomSByteInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomShortInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomUintInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomULongInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange_Reversed(), and NUnit.Framework.Syntax.ThrowsTests.ThrowsInstanceOf().
static InstanceOfTypeConstraint NUnit.Framework.Throws.InstanceOf< TExpected > () inline static
Creates a constraint specifying the type of exception expected
Property Documentation
ResolvableConstraintExpression NUnit.Framework.Throws.Exception static get
Creates a constraint specifying an expected exception
Referenced by NUnit.Framework.Assertions.AssertThrowsTests.CorrectExceptionThrown(), NUnit.Framework.Syntax.ThrowsTests.DelegateThrowsException(), NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.FailsWhenKeyIsMissing(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.FailsWhenValueIsMissing(), NUnit.Framework.Syntax.ThrowsTests.ThrowsException(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionInstanceOf(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionTypeOf(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionTypeOfAndConstraint(), and NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionWithConstraint().
ResolvableConstraintExpression NUnit.Framework.Throws.InnerException static get
Creates a constraint specifying an exception with a given InnerException
ExactTypeConstraint NUnit.Framework.Throws.TargetInvocationException static get
Creates a constraint specifying an expected TargetInvocationException
ExactTypeConstraint NUnit.Framework.Throws.ArgumentException static get
Creates a constraint specifying an expected ArgumentException
Referenced by NUnit.Framework.Attributes.ApartmentAttributeTests.ApartmentStateUnknownThrowsException(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.ConstructController_MissingFile_ThrowsArgumentInvalid(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.FailsWhenNotUsedAgainstADictionary(), NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.FailsWhenNotUsedAgainstADictionary(), NUnit.Engine.Services.Tests.ResultServiceTests.NUnit3Format_NonExistentTransform_ThrowsArgumentException(), and NUnit.Framework.Constraints.RangeTests.ShouldThrowExceptionIfFromIsLessThanTo().
ExactTypeConstraint NUnit.Framework.Throws.ArgumentNullException static get
Creates a constraint specifying an expected ArgumentNUllException
Referenced by NUnit.Framework.Tests.ThrowsTests.ArgumentNullException_ConstraintMatchesThrownArgumentNullException(), and NUnit.Common.Tests.TokenizerTests.NullInputThrowsException().
ExactTypeConstraint NUnit.Framework.Throws.InvalidOperationException static get
Creates a constraint specifying an expected InvalidOperationException
ThrowsNothingConstraint NUnit.Framework.Throws.Nothing static get
Creates a constraint specifying that no exception is thrown
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Throws.cs