IGLib: alglib.lsfit Class Reference
alglib.lsfit Class Reference
Classes
class barycentricfitreport
class lsfitreport
class lsfitstate
class polynomialfitreport
class spline1dfitreport
Static Public Member Functions
static void polynomialfit (double[] x, double[] y, int n, int m, ref int info, ratint.barycentricinterpolant p, polynomialfitreport rep)
static void polynomialfitwc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, ratint.barycentricinterpolant p, polynomialfitreport rep)
static void barycentricfitfloaterhormannwc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, ratint.barycentricinterpolant b, barycentricfitreport rep)
static void barycentricfitfloaterhormann (double[] x, double[] y, int n, int m, ref int info, ratint.barycentricinterpolant b, barycentricfitreport rep)
static void spline1dfitpenalized (double[] x, double[] y, int n, int m, double rho, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void spline1dfitpenalizedw (double[] x, double[] y, double[] w, int n, int m, double rho, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void spline1dfitcubicwc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void spline1dfithermitewc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void spline1dfitcubic (double[] x, double[] y, int n, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void spline1dfithermite (double[] x, double[] y, int n, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void lsfitlinearw (double[] y, double[] w, double[,] fmatrix, int n, int m, ref int info, ref double[] c, lsfitreport rep)
static void lsfitlinearwc (double[] y, double[] w, double[,] fmatrix, double[,] cmatrix, int n, int m, int k, ref int info, ref double[] c, lsfitreport rep)
static void lsfitlinear (double[] y, double[,] fmatrix, int n, int m, ref int info, ref double[] c, lsfitreport rep)
static void lsfitlinearc (double[] y, double[,] fmatrix, double[,] cmatrix, int n, int m, int k, ref int info, ref double[] c, lsfitreport rep)
static void lsfitcreatewf (double[,] x, double[] y, double[] w, double[] c, int n, int m, int k, double diffstep, lsfitstate state)
static void lsfitcreatef (double[,] x, double[] y, double[] c, int n, int m, int k, double diffstep, lsfitstate state)
static void lsfitcreatewfg (double[,] x, double[] y, double[] w, double[] c, int n, int m, int k, bool cheapfg, lsfitstate state)
static void lsfitcreatefg (double[,] x, double[] y, double[] c, int n, int m, int k, bool cheapfg, lsfitstate state)
static void lsfitcreatewfgh (double[,] x, double[] y, double[] w, double[] c, int n, int m, int k, lsfitstate state)
static void lsfitcreatefgh (double[,] x, double[] y, double[] c, int n, int m, int k, lsfitstate state)
static void lsfitsetcond (lsfitstate state, double epsf, double epsx, int maxits)
static void lsfitsetstpmax (lsfitstate state, double stpmax)
static void lsfitsetxrep (lsfitstate state, bool needxrep)
static void lsfitsetscale (lsfitstate state, double[] s)
static void lsfitsetbc (lsfitstate state, double[] bndl, double[] bndu)
static bool lsfititeration (lsfitstate state)
static void lsfitresults (lsfitstate state, ref int info, ref double[] c, lsfitreport rep)
static void lsfitsetgradientcheck (lsfitstate state, double teststep)
static void lsfitscalexy (ref double[] x, ref double[] y, ref double[] w, int n, ref double[] xc, ref double[] yc, int[] dc, int k, ref double xa, ref double xb, ref double sa, ref double sb, ref double[] xoriginal, ref double[] yoriginal)
static void polynomialfit (double[] x, double[] y, int n, int m, ref int info, ratint.barycentricinterpolant p, polynomialfitreport rep)
static void polynomialfitwc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, ratint.barycentricinterpolant p, polynomialfitreport rep)
static void barycentricfitfloaterhormannwc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, ratint.barycentricinterpolant b, barycentricfitreport rep)
static void barycentricfitfloaterhormann (double[] x, double[] y, int n, int m, ref int info, ratint.barycentricinterpolant b, barycentricfitreport rep)
static void spline1dfitpenalized (double[] x, double[] y, int n, int m, double rho, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void spline1dfitpenalizedw (double[] x, double[] y, double[] w, int n, int m, double rho, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void spline1dfitcubicwc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void spline1dfithermitewc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void spline1dfitcubic (double[] x, double[] y, int n, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void spline1dfithermite (double[] x, double[] y, int n, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void lsfitlinearw (double[] y, double[] w, double[,] fmatrix, int n, int m, ref int info, ref double[] c, lsfitreport rep)
static void lsfitlinearwc (double[] y, double[] w, double[,] fmatrix, double[,] cmatrix, int n, int m, int k, ref int info, ref double[] c, lsfitreport rep)
static void lsfitlinear (double[] y, double[,] fmatrix, int n, int m, ref int info, ref double[] c, lsfitreport rep)
static void lsfitlinearc (double[] y, double[,] fmatrix, double[,] cmatrix, int n, int m, int k, ref int info, ref double[] c, lsfitreport rep)
static void lsfitcreatewf (double[,] x, double[] y, double[] w, double[] c, int n, int m, int k, double diffstep, lsfitstate state)
static void lsfitcreatef (double[,] x, double[] y, double[] c, int n, int m, int k, double diffstep, lsfitstate state)
static void lsfitcreatewfg (double[,] x, double[] y, double[] w, double[] c, int n, int m, int k, bool cheapfg, lsfitstate state)
static void lsfitcreatefg (double[,] x, double[] y, double[] c, int n, int m, int k, bool cheapfg, lsfitstate state)
static void lsfitcreatewfgh (double[,] x, double[] y, double[] w, double[] c, int n, int m, int k, lsfitstate state)
static void lsfitcreatefgh (double[,] x, double[] y, double[] c, int n, int m, int k, lsfitstate state)
static void lsfitsetcond (lsfitstate state, double epsf, double epsx, int maxits)
static void lsfitsetstpmax (lsfitstate state, double stpmax)
static void lsfitsetxrep (lsfitstate state, bool needxrep)
static void lsfitsetscale (lsfitstate state, double[] s)
static void lsfitsetbc (lsfitstate state, double[] bndl, double[] bndu)
static bool lsfititeration (lsfitstate state)
static void lsfitresults (lsfitstate state, ref int info, ref double[] c, lsfitreport rep)
static void lsfitsetgradientcheck (lsfitstate state, double teststep)
static void lsfitscalexy (ref double[] x, ref double[] y, ref double[] w, int n, ref double[] xc, ref double[] yc, int[] dc, int k, ref double xa, ref double xb, ref double sa, ref double sb, ref double[] xoriginal, ref double[] yoriginal)
Public Attributes
const int rfsmax = 10
Static Private Member Functions
static void spline1dfitinternal (int st, double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void lsfitlinearinternal (double[] y, double[] w, double[,] fmatrix, int n, int m, ref int info, ref double[] c, lsfitreport rep)
static void lsfitclearrequestfields (lsfitstate state)
static void barycentriccalcbasis (ratint.barycentricinterpolant b, double t, ref double[] y)
static void internalchebyshevfit (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, ref double[] c, lsfitreport rep)
static void barycentricfitwcfixedd (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, int d, ref int info, ratint.barycentricinterpolant b, barycentricfitreport rep)
static void spline1dfitinternal (int st, double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep)
static void lsfitlinearinternal (double[] y, double[] w, double[,] fmatrix, int n, int m, ref int info, ref double[] c, lsfitreport rep)
static void lsfitclearrequestfields (lsfitstate state)
static void barycentriccalcbasis (ratint.barycentricinterpolant b, double t, ref double[] y)
static void internalchebyshevfit (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, ref double[] c, lsfitreport rep)
static void barycentricfitwcfixedd (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, int d, ref int info, ratint.barycentricinterpolant b, barycentricfitreport rep)
static void clearreport (lsfitreport rep)
static void estimateerrors (double[,] f1, double[] f0, double[] y, double[] w, double[] x, double[] s, int n, int k, lsfitreport rep, ref double[,] z, int zkind)
Member Function Documentation
static void alglib.lsfit.polynomialfit (double[] x, double[] y, int n, int m, ref int info, ratint.barycentricinterpolant p, polynomialfitreport rep) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.lsfit.polynomialfitwc().
Referenced by alglib.polynomialfit(), and alglib.testlsfitunit.testpolynomialfitting().
static void alglib.lsfit.polynomialfitwc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, ratint.barycentricinterpolant p, polynomialfitreport rep) inline static
References alglib.ap.assert().
Referenced by alglib.lsfit.polynomialfit(), alglib.polynomialfitwc(), and alglib.testlsfitunit.testpolynomialfitting().
static void alglib.lsfit.barycentricfitfloaterhormannwc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, ratint.barycentricinterpolant b, barycentricfitreport rep) inline static
Referenced by alglib.barycentricfitfloaterhormannwc(), and alglib.testlsfitunit.testrationalfitting().
static void alglib.lsfit.barycentricfitfloaterhormann (double[] x, double[] y, int n, int m, ref int info, ratint.barycentricinterpolant b, barycentricfitreport rep) inline static
Referenced by alglib.barycentricfitfloaterhormann(), and alglib.testlsfitunit.testrationalfitting().
static void alglib.lsfit.spline1dfitpenalized (double[] x, double[] y, int n, int m, double rho, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static
Referenced by alglib.spline1dfitpenalized(), and alglib.testlsfitunit.testsplinefitting().
static void alglib.lsfit.spline1dfitpenalizedw (double[] x, double[] y, double[] w, int n, int m, double rho, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static
Referenced by alglib.spline1dfitpenalizedw(), and alglib.testlsfitunit.testsplinefitting().
static void alglib.lsfit.spline1dfitcubicwc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static
Referenced by alglib.spline1dfitcubicwc(), and alglib.testlsfitunit.testsplinefitting().
static void alglib.lsfit.spline1dfithermitewc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static
Referenced by alglib.spline1dfithermitewc(), and alglib.testlsfitunit.testsplinefitting().
static void alglib.lsfit.spline1dfitcubic (double[] x, double[] y, int n, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static
Referenced by alglib.spline1dfitcubic(), and alglib.testlsfitunit.testsplinefitting().
static void alglib.lsfit.spline1dfithermite (double[] x, double[] y, int n, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static
Referenced by alglib.spline1dfithermite(), and alglib.testlsfitunit.testsplinefitting().
static void alglib.lsfit.lsfitlinearw (double[] y, double[] w, double fmatrix[,], int n, int m, ref int info, ref double[] c, lsfitreport rep) inline static
Referenced by alglib.lsfitlinearw(), and alglib.testlsfitunit.testgeneralfitting().
static void alglib.lsfit.lsfitlinearwc (double[] y, double[] w, double fmatrix[,], double cmatrix[,], int n, int m, int k, ref int info, ref double[] c, lsfitreport rep) inline static
Referenced by alglib.lsfitlinearwc(), and alglib.testlsfitunit.testgeneralfitting().
static void alglib.lsfit.lsfitlinear (double[] y, double fmatrix[,], int n, int m, ref int info, ref double[] c, lsfitreport rep) inline static
Referenced by alglib.lsfitlinear(), and alglib.testlsfitunit.testgeneralfitting().
static void alglib.lsfit.lsfitlinearc (double[] y, double fmatrix[,], double cmatrix[,], int n, int m, int k, ref int info, ref double[] c, lsfitreport rep) inline static
Referenced by alglib.lsfitlinearc(), and alglib.testlsfitunit.testgeneralfitting().
static void alglib.lsfit.lsfitcreatewf (double x[,], double[] y, double[] w, double[] c, int n, int m, int k, double diffstep, lsfitstate state) inline static
Referenced by alglib.lsfitcreatewf(), and alglib.testlsfitunit.testgeneralfitting().
static void alglib.lsfit.lsfitcreatef (double x[,], double[] y, double[] c, int n, int m, int k, double diffstep, lsfitstate state) inline static
Referenced by alglib.lsfitcreatef(), and alglib.testlsfitunit.testgeneralfitting().
static void alglib.lsfit.lsfitcreatewfg (double x[,], double[] y, double[] w, double[] c, int n, int m, int k, bool cheapfg, lsfitstate state) inline static
Referenced by alglib.lsfitcreatewfg(), and alglib.testlsfitunit.testgeneralfitting().
static void alglib.lsfit.lsfitcreatefg (double x[,], double[] y, double[] c, int n, int m, int k, bool cheapfg, lsfitstate state) inline static
Referenced by alglib.lsfitcreatefg(), alglib.testlsfitunit.testgeneralfitting(), and alglib.testlsfitunit.testgradientcheck().
static void alglib.lsfit.lsfitcreatewfgh (double x[,], double[] y, double[] w, double[] c, int n, int m, int k, lsfitstate state) inline static
Referenced by alglib.lsfitcreatewfgh(), and alglib.testlsfitunit.testgeneralfitting().
static void alglib.lsfit.lsfitcreatefgh (double x[,], double[] y, double[] c, int n, int m, int k, lsfitstate state) inline static
Referenced by alglib.lsfitcreatefgh(), and alglib.testlsfitunit.testgeneralfitting().
static void alglib.lsfit.lsfitsetcond (lsfitstate state, double epsf, double epsx, int maxits) inline static
Referenced by alglib.lsfitsetcond(), alglib.testlsfitunit.testgeneralfitting(), and alglib.testlsfitunit.testgradientcheck().
static void alglib.lsfit.lsfitsetstpmax (lsfitstate state, double stpmax) inline static
Referenced by alglib.lsfitsetstpmax().
static void alglib.lsfit.lsfitsetxrep (lsfitstate state, bool needxrep) inline static
Referenced by alglib.lsfitsetxrep().
static void alglib.lsfit.lsfitsetscale (lsfitstate state, double[] s) inline static
Referenced by alglib.lsfitsetscale().
static void alglib.lsfit.lsfitsetbc (lsfitstate state, double[] bndl, double[] bndu) inline static
Referenced by alglib.lsfitsetbc(), and alglib.testlsfitunit.testgradientcheck().
static bool alglib.lsfit.lsfititeration (lsfitstate state) inline static
Referenced by alglib.testlsfitunit.fitlinearnonlinear(), alglib.lsfititeration(), alglib.testlsfitunit.testgeneralfitting(), and alglib.testlsfitunit.testgradientcheck().
static void alglib.lsfit.lsfitresults (lsfitstate state, ref int info, ref double[] c, lsfitreport rep) inline static
Referenced by alglib.lsfitresults(), alglib.testlsfitunit.testgeneralfitting(), and alglib.testlsfitunit.testgradientcheck().
static void alglib.lsfit.lsfitsetgradientcheck (lsfitstate state, double teststep) inline static
Referenced by alglib.lsfitsetgradientcheck(), and alglib.testlsfitunit.testgradientcheck().
static void alglib.lsfit.lsfitscalexy (ref double[] x, ref double[] y, ref double[] w, int n, ref double[] xc, ref double[] yc, int[] dc, int k, ref double xa, ref double xb, ref double sa, ref double sb, ref double[] xoriginal, ref double[] yoriginal) inline static
static void alglib.lsfit.spline1dfitinternal (int st, double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static private
static void alglib.lsfit.lsfitlinearinternal (double[] y, double[] w, double fmatrix[,], int n, int m, ref int info, ref double[] c, lsfitreport rep) inline static private
static void alglib.lsfit.lsfitclearrequestfields (lsfitstate state) inline static private
static void alglib.lsfit.barycentriccalcbasis (ratint.barycentricinterpolant b, double t, ref double[] y) inline static private
static void alglib.lsfit.internalchebyshevfit (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, ref double[] c, lsfitreport rep) inline static private
static void alglib.lsfit.barycentricfitwcfixedd (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, int d, ref int info, ratint.barycentricinterpolant b, barycentricfitreport rep) inline static private
static void alglib.lsfit.polynomialfit (double[] x, double[] y, int n, int m, ref int info, ratint.barycentricinterpolant p, polynomialfitreport rep) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.lsfit.polynomialfitwc().
static void alglib.lsfit.polynomialfitwc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, ratint.barycentricinterpolant p, polynomialfitreport rep) inline static
References alglib.ap.assert().
static void alglib.lsfit.barycentricfitfloaterhormannwc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, ratint.barycentricinterpolant b, barycentricfitreport rep) inline static
static void alglib.lsfit.barycentricfitfloaterhormann (double[] x, double[] y, int n, int m, ref int info, ratint.barycentricinterpolant b, barycentricfitreport rep) inline static
static void alglib.lsfit.spline1dfitpenalized (double[] x, double[] y, int n, int m, double rho, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static
static void alglib.lsfit.spline1dfitpenalizedw (double[] x, double[] y, double[] w, int n, int m, double rho, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static
static void alglib.lsfit.spline1dfitcubicwc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static
static void alglib.lsfit.spline1dfithermitewc (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static
static void alglib.lsfit.spline1dfitcubic (double[] x, double[] y, int n, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static
static void alglib.lsfit.spline1dfithermite (double[] x, double[] y, int n, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static
static void alglib.lsfit.lsfitlinearw (double[] y, double[] w, double fmatrix[,], int n, int m, ref int info, ref double[] c, lsfitreport rep) inline static
static void alglib.lsfit.lsfitlinearwc (double[] y, double[] w, double fmatrix[,], double cmatrix[,], int n, int m, int k, ref int info, ref double[] c, lsfitreport rep) inline static
static void alglib.lsfit.lsfitlinear (double[] y, double fmatrix[,], int n, int m, ref int info, ref double[] c, lsfitreport rep) inline static
static void alglib.lsfit.lsfitlinearc (double[] y, double fmatrix[,], double cmatrix[,], int n, int m, int k, ref int info, ref double[] c, lsfitreport rep) inline static
static void alglib.lsfit.lsfitcreatewf (double x[,], double[] y, double[] w, double[] c, int n, int m, int k, double diffstep, lsfitstate state) inline static
static void alglib.lsfit.lsfitcreatef (double x[,], double[] y, double[] c, int n, int m, int k, double diffstep, lsfitstate state) inline static
static void alglib.lsfit.lsfitcreatewfg (double x[,], double[] y, double[] w, double[] c, int n, int m, int k, bool cheapfg, lsfitstate state) inline static
static void alglib.lsfit.lsfitcreatefg (double x[,], double[] y, double[] c, int n, int m, int k, bool cheapfg, lsfitstate state) inline static
static void alglib.lsfit.lsfitcreatewfgh (double x[,], double[] y, double[] w, double[] c, int n, int m, int k, lsfitstate state) inline static
static void alglib.lsfit.lsfitcreatefgh (double x[,], double[] y, double[] c, int n, int m, int k, lsfitstate state) inline static
static void alglib.lsfit.lsfitsetcond (lsfitstate state, double epsf, double epsx, int maxits) inline static
static void alglib.lsfit.lsfitsetstpmax (lsfitstate state, double stpmax) inline static
static void alglib.lsfit.lsfitsetxrep (lsfitstate state, bool needxrep) inline static
static void alglib.lsfit.lsfitsetscale (lsfitstate state, double[] s) inline static
static void alglib.lsfit.lsfitsetbc (lsfitstate state, double[] bndl, double[] bndu) inline static
static bool alglib.lsfit.lsfititeration (lsfitstate state) inline static
static void alglib.lsfit.lsfitresults (lsfitstate state, ref int info, ref double[] c, lsfitreport rep) inline static
static void alglib.lsfit.lsfitsetgradientcheck (lsfitstate state, double teststep) inline static
static void alglib.lsfit.lsfitscalexy (ref double[] x, ref double[] y, ref double[] w, int n, ref double[] xc, ref double[] yc, int[] dc, int k, ref double xa, ref double xb, ref double sa, ref double sb, ref double[] xoriginal, ref double[] yoriginal) inline static
static void alglib.lsfit.spline1dfitinternal (int st, double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, spline1d.spline1dinterpolant s, spline1dfitreport rep) inline static private
static void alglib.lsfit.lsfitlinearinternal (double[] y, double[] w, double fmatrix[,], int n, int m, ref int info, ref double[] c, lsfitreport rep) inline static private
static void alglib.lsfit.lsfitclearrequestfields (lsfitstate state) inline static private
static void alglib.lsfit.barycentriccalcbasis (ratint.barycentricinterpolant b, double t, ref double[] y) inline static private
static void alglib.lsfit.internalchebyshevfit (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, ref int info, ref double[] c, lsfitreport rep) inline static private
static void alglib.lsfit.barycentricfitwcfixedd (double[] x, double[] y, double[] w, int n, double[] xc, double[] yc, int[] dc, int k, int m, int d, ref int info, ratint.barycentricinterpolant b, barycentricfitreport rep) inline static private
static void alglib.lsfit.clearreport (lsfitreport rep) inline static private
static void alglib.lsfit.estimateerrors (double f1[,], double[] f0, double[] y, double[] w, double[] x, double[] s, int n, int k, lsfitreport rep, ref double z[,], int zkind) inline static private
Member Data Documentation
const int alglib.lsfit.rfsmax = 10
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/interpolation.cs