IGLib: Meta.Numerics.Statistics.Distributions.GeometricDistribution Class Reference
Meta.Numerics.Statistics.Distributions.GeometricDistribution Class Reference
Represents a geometric distribution.
Public Member Functions
GeometricDistribution (double p)
Initializes a new geometric distribution.
override double ProbabilityMass (int k)
Returns the probability of the obtaining the given value.
Parameters
k The value.
Returns
The probability of obtaining the value.
override double LeftExclusiveProbability (int k)
Computes the probability of obtaining a value less than the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value strictly less than k .
See also
RightExclusiveProbability
override double RightExclusiveProbability (int k)
Computes the probability of obtaining a value greater than the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value strictly greater than k .
See also
LeftExclusiveProbability
override int InverseLeftProbability (double P)
Computes the value corresponding to the given percentile.
Parameters
P The percentile.
Returns
The value.
override double Moment (int r)
Gets a raw moment of the distribution.
Parameters
r The order of the moment.
Returns
The raw moment Mr.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.DiscreteDistribution
virtual double LeftInclusiveProbability (int k)
Computes the probability of obtaining a value less than or equal to the given value.
virtual double ExpectationValue (Func< int, double > f)
Computes the expectation value of an artibrary function.
override double MomentAboutMean (int r)
Gets a central moment of the distribution.
virtual int GetRandomValue (Random rng)
Produces a random integer drawn from the distribution.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Cumulant (int r)
Computes a cumulant of the distribution.
Properties
override int Minimum [get]
override int Maximum [get]
override double Mean [get]
override double Variance [get]
override double StandardDeviation [get]
override double Skewness [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.DiscreteDistribution
abstract int Minimum [get]
Gets the smallest value in the distribution.
abstract int Maximum [get]
Gets the largest value in the distribution.
override double Mean [get]
Gets the mean of the distribution.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Static Private Member Functions
static double EulerianPolynomial (int n, double x)
Private Attributes
readonly double p
readonly double q
Detailed Description
Represents a geometric distribution.
The probability of obtaining each integer value in a geometric distribution is lower than the probability of obtaining the previous value by a constant factor. The probability thus decreases geometricly with the value, giving the distribution its name.
Constructor & Destructor Documentation
Meta.Numerics.Statistics.Distributions.GeometricDistribution.GeometricDistribution (double p) inline
Initializes a new geometric distribution.
Parameters
p The probabability of the value zero.
Member Function Documentation
override double Meta.Numerics.Statistics.Distributions.GeometricDistribution.ProbabilityMass (int k) inline virtual
Returns the probability of the obtaining the given value.
Parameters
k The value.
Returns
The probability of obtaining the value.
Implements Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
References Meta.Numerics.MoreMath.Pow().
override double Meta.Numerics.Statistics.Distributions.GeometricDistribution.LeftExclusiveProbability (int k) inline virtual
Computes the probability of obtaining a value less than the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value strictly less than k .
See also
RightExclusiveProbability
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
References Meta.Numerics.MoreMath.Pow().
override double Meta.Numerics.Statistics.Distributions.GeometricDistribution.RightExclusiveProbability (int k) inline virtual
Computes the probability of obtaining a value greater than the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value strictly greater than k .
See also
LeftExclusiveProbability
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
References Meta.Numerics.MoreMath.Pow().
override int Meta.Numerics.Statistics.Distributions.GeometricDistribution.InverseLeftProbability (double P) inline virtual
Computes the value corresponding to the given percentile.
Parameters
P The percentile.
Returns
The value.
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
override double Meta.Numerics.Statistics.Distributions.GeometricDistribution.Moment (int r) inline virtual
Gets a raw moment of the distribution.
Parameters
r The order of the moment.
Returns
The raw moment Mr.
Reimplemented from Meta.Numerics.Statistics.Distributions.DiscreteDistribution.
References Meta.Numerics.MoreMath.Pow().
static double Meta.Numerics.Statistics.Distributions.GeometricDistribution.EulerianPolynomial (int n, double x) inline static private
Member Data Documentation
readonly double Meta.Numerics.Statistics.Distributions.GeometricDistribution.p private
readonly double Meta.Numerics.Statistics.Distributions.GeometricDistribution.q private
Property Documentation
override int Meta.Numerics.Statistics.Distributions.GeometricDistribution.Minimum get
override int Meta.Numerics.Statistics.Distributions.GeometricDistribution.Maximum get
override double Meta.Numerics.Statistics.Distributions.GeometricDistribution.Mean get
override double Meta.Numerics.Statistics.Distributions.GeometricDistribution.Variance get
override double Meta.Numerics.Statistics.Distributions.GeometricDistribution.StandardDeviation get
override double Meta.Numerics.Statistics.Distributions.GeometricDistribution.Skewness get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/GeometricDistribution.cs