IGLib: alglib.testspline2dunit Class Reference
alglib.testspline2dunit Class Reference
Static Public Member Functions
static bool testspline2d (bool silent)
static bool testspline2d (bool silent)
static bool _pexec_testspline2d (bool silent)
Static Private Member Functions
static void lconst (spline2d.spline2dinterpolant c, double[] lx, double[] ly, int m, int n, double lstep, ref double lc, ref double lcx, ref double lcy, ref double lcxy)
static void twodnumder (spline2d.spline2dinterpolant c, double x, double y, double h, ref double f, ref double fx, ref double fy, ref double fxy)
static bool testunpack (spline2d.spline2dinterpolant c, double[] lx, double[] ly)
static bool testlintrans (spline2d.spline2dinterpolant c, int d, double ax, double bx, double ay, double by)
static void unsetspline2d (spline2d.spline2dinterpolant c)
static bool testspline2dvf (bool silent)
static void lconst (spline2d.spline2dinterpolant c, double[] lx, double[] ly, int m, int n, double lstep, ref double lc, ref double lcx, ref double lcy, ref double lcxy)
static void twodnumder (spline2d.spline2dinterpolant c, double x, double y, double h, ref double f, ref double fx, ref double fy, ref double fxy)
static bool testunpack (spline2d.spline2dinterpolant c, double[] lx, double[] ly)
static bool testlintrans (spline2d.spline2dinterpolant c, int d, double ax, double bx, double ay, double by)
static void unsetspline2d (spline2d.spline2dinterpolant c)
static bool testspline2dvf (bool silent)
Member Function Documentation
static bool alglib.testspline2dunit.testspline2d (bool silent) inline static
References alglib.testspline2dunit.lconst(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.spline2d.spline2dbuildbicubic(), alglib.spline2d.spline2dbuildbicubicv(), alglib.spline2d.spline2dbuildbilinear(), alglib.spline2d.spline2dbuildbilinearv(), alglib.spline2d.spline2dcalc(), alglib.spline2d.spline2dcopy(), alglib.spline2d.spline2ddiff(), alglib.spline2d.spline2dresamplebicubic(), alglib.spline2d.spline2dresamplebilinear(), alglib.testspline2dunit.testlintrans(), alglib.testspline2dunit.testspline2dvf(), alglib.testspline2dunit.testunpack(), alglib.testspline2dunit.twodnumder(), and alglib.testspline2dunit.unsetspline2d().
Referenced by alglib.testspline2dunit._pexec_testspline2d(), and _Test.Main().
static void alglib.testspline2dunit.lconst (spline2d.spline2dinterpolant c, double[] lx, double[] ly, int m, int n, double lstep, ref double lc, ref double lcx, ref double lcy, ref double lcxy) inline static private
References alglib.testspline2dunit.twodnumder().
Referenced by alglib.testspline2dunit.testspline2d().
static void alglib.testspline2dunit.twodnumder (spline2d.spline2dinterpolant c, double x, double y, double h, ref double f, ref double fx, ref double fy, ref double fxy) inline static private
References alglib.spline2d.spline2dcalc(), and alglib.math.sqr().
Referenced by alglib.testspline2dunit.lconst(), and alglib.testspline2dunit.testspline2d().
static bool alglib.testspline2dunit.testunpack (spline2d.spline2dinterpolant c, double[] lx, double[] ly) inline static private
References alglib.math.machineepsilon, alglib.math.randomreal(), alglib.spline2d.spline2dcalc(), and alglib.spline2d.spline2dunpack().
Referenced by alglib.testspline2dunit.testspline2d().
static bool alglib.testspline2dunit.testlintrans (spline2d.spline2dinterpolant c, int d, double ax, double bx, double ay, double by) inline static private
References alglib.math.machineepsilon, alglib.math.randomreal(), alglib.spline2d.spline2dcalcv(), alglib.spline2d.spline2dcopy(), alglib.spline2d.spline2dlintransf(), and alglib.spline2d.spline2dlintransxy().
Referenced by alglib.testspline2dunit.testspline2d().
static void alglib.testspline2dunit.unsetspline2d (spline2d.spline2dinterpolant c) inline static private
References alglib.spline2d.spline2dbuildbilinear().
Referenced by alglib.testspline2dunit.testspline2d().
static bool alglib.testspline2dunit.testspline2dvf (bool silent) inline static private
References alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.rmatrixsetlengthatleast(), alglib.apserv.rvectorsetlengthatleast(), alglib.spline2d.spline2dbuildbicubic(), alglib.spline2d.spline2dbuildbicubicv(), alglib.spline2d.spline2dbuildbilinear(), alglib.spline2d.spline2dbuildbilinearv(), alglib.spline2d.spline2dcalc(), alglib.spline2d.spline2dcalcv(), alglib.spline2d.spline2dunpack(), and alglib.spline2d.spline2dunpackv().
Referenced by alglib.testspline2dunit.testspline2d().
static bool alglib.testspline2dunit.testspline2d (bool silent) inline static
References alglib.testspline2dunit.lconst(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.spline2d.spline2dbuildbicubic(), alglib.spline2d.spline2dbuildbicubicv(), alglib.spline2d.spline2dbuildbilinear(), alglib.spline2d.spline2dbuildbilinearv(), alglib.spline2d.spline2dcalc(), alglib.spline2d.spline2dcopy(), alglib.spline2d.spline2ddiff(), alglib.spline2d.spline2dresamplebicubic(), alglib.spline2d.spline2dresamplebilinear(), alglib.testspline2dunit.testlintrans(), alglib.testspline2dunit.testspline2dvf(), alglib.testspline2dunit.testunpack(), alglib.testspline2dunit.twodnumder(), and alglib.testspline2dunit.unsetspline2d().
static bool alglib.testspline2dunit._pexec_testspline2d (bool silent) inline static
References alglib.testspline2dunit.testspline2d().
Referenced by _Test.Main().
static void alglib.testspline2dunit.lconst (spline2d.spline2dinterpolant c, double[] lx, double[] ly, int m, int n, double lstep, ref double lc, ref double lcx, ref double lcy, ref double lcxy) inline static private
References alglib.testspline2dunit.twodnumder().
static void alglib.testspline2dunit.twodnumder (spline2d.spline2dinterpolant c, double x, double y, double h, ref double f, ref double fx, ref double fy, ref double fxy) inline static private
References alglib.spline2d.spline2dcalc(), and alglib.math.sqr().
static bool alglib.testspline2dunit.testunpack (spline2d.spline2dinterpolant c, double[] lx, double[] ly) inline static private
References alglib.math.machineepsilon, alglib.math.randomreal(), alglib.spline2d.spline2dcalc(), and alglib.spline2d.spline2dunpack().
static bool alglib.testspline2dunit.testlintrans (spline2d.spline2dinterpolant c, int d, double ax, double bx, double ay, double by) inline static private
References alglib.math.machineepsilon, alglib.math.randomreal(), alglib.spline2d.spline2dcalcv(), alglib.spline2d.spline2dcopy(), alglib.spline2d.spline2dlintransf(), and alglib.spline2d.spline2dlintransxy().
static void alglib.testspline2dunit.unsetspline2d (spline2d.spline2dinterpolant c) inline static private
References alglib.spline2d.spline2dbuildbilinear().
static bool alglib.testspline2dunit.testspline2dvf (bool silent) inline static private
References alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.rmatrixsetlengthatleast(), alglib.apserv.rvectorsetlengthatleast(), alglib.spline2d.spline2dbuildbicubic(), alglib.spline2d.spline2dbuildbicubicv(), alglib.spline2d.spline2dbuildbilinear(), alglib.spline2d.spline2dbuildbilinearv(), alglib.spline2d.spline2dcalc(), alglib.spline2d.spline2dcalcv(), alglib.spline2d.spline2dunpack(), and alglib.spline2d.spline2dunpackv().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs