IGLib: IG.Forms.CompilerFormOld Class Reference
IG.Forms.CompilerFormOld Class Reference
Public Member Functions
CompilerFormOld ()
Initializes form components and internal variables.
CompilerFormOld ()
Initializes form components and internal variables.
Public Attributes
ReporterConsoleMsgbox Reporter = new ReporterConsoleMsgbox()
Protected Member Functions
void ReportError (string message, Exception ex)
Launches error report.
void CheckReadyToRun ()
Checks whether the compiled code is ready to run, and enables the Run button accordingly.
override void Dispose (bool disposing)
Clean up any resources being used.
void ReportError (string message, Exception ex)
Launches error report.
void CheckReadyToRun ()
Checks whether the compiled code is ready to run, and enables the Run button accordingly.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
RuntimeCompilerOld Compiler = new RuntimeCompilerOld()
Properties
Logger Logger [get]
Gets compiler's logger.
Private Member Functions
void btnQuit_Click (object sender, System.EventArgs e)
void btnLoad_Click (object sender, System.EventArgs e)
Loads code template into the rich textbox.
void btnCompile_Click (object sender, System.EventArgs e)
Compilation of code.
void btnExecute_Click (object sender, System.EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnQuit_Click (object sender, System.EventArgs e)
void btnLoad_Click (object sender, System.EventArgs e)
Loads code template into the rich textbox.
void btnCompile_Click (object sender, System.EventArgs e)
Compilation of code.
void btnExecute_Click (object sender, System.EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Logger _logger = null
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.RichTextBox rtfCode
System.Windows.Forms.Button btnLoad
System.Windows.Forms.Button btnCompile
System.Windows.Forms.Button btnExecute
System.Windows.Forms.Button btnQuit
Constructor & Destructor Documentation
IG.Forms.CompilerFormOld.CompilerFormOld () inline
Initializes form components and internal variables.
IG.Forms.CompilerFormOld.CompilerFormOld () inline
Initializes form components and internal variables.
Member Function Documentation
void IG.Forms.CompilerFormOld.btnQuit_Click (object sender, System.EventArgs e) inline private
void IG.Forms.CompilerFormOld.btnLoad_Click (object sender, System.EventArgs e) inline private
Loads code template into the rich textbox.
References IG.Lib.RuntimeCompilerOld.CodeBase.
void IG.Forms.CompilerFormOld.ReportError (string message, Exception ex) inline protected
Launches error report.
Parameters
message Custom part of the message shown in report.
ex Exception that was thrown.
void IG.Forms.CompilerFormOld.CheckReadyToRun () inline protected
Checks whether the compiled code is ready to run, and enables the Run button accordingly.
References IG.Lib.RuntimeCompilerOld.ReadyToRun.
void IG.Forms.CompilerFormOld.btnCompile_Click (object sender, System.EventArgs e) inline private
Compilation of code.
References IG.Lib.Logger.Clear(), IG.Lib.RuntimeCompilerOld.Code, IG.Lib.RuntimeCompilerOld.Compile(), IG.Lib.Logger.GetErrorsReport(), IG.Lib.Logger.GetReport(), IG.Lib.Logger.GetWarningsReport(), IG.Lib.Logger.HasErrors(), IG.Lib.Logger.HasWarnings(), IG.Lib.RuntimeCompilerOld.ReadyToRun, IG.Lib.Logger.Report(), IG.Lib.ReporterBase.ReportError(), and IG.Forms.ReporterConsoleMsgbox_Base.UseMessageBox.
void IG.Forms.CompilerFormOld.btnExecute_Click (object sender, System.EventArgs e) inline private
References IG.Lib.RuntimeCompilerOld.LibraryPath, IG.Lib.RuntimeCompilerOld.LoadFile(), IG.Lib.IRunnableOld.Run(), and IG.Lib.RuntimeCompilerOld.RunnableFullClass.
override void IG.Forms.CompilerFormOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
void IG.Forms.CompilerFormOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
void IG.Forms.CompilerFormOld.btnQuit_Click (object sender, System.EventArgs e) inline private
void IG.Forms.CompilerFormOld.btnLoad_Click (object sender, System.EventArgs e) inline private
Loads code template into the rich textbox.
References IG.Lib.RuntimeCompilerOld.CodeBase.
void IG.Forms.CompilerFormOld.ReportError (string message, Exception ex) inline protected
Launches error report.
Parameters
message Custom part of the message shown in report.
ex Exception that was thrown.
void IG.Forms.CompilerFormOld.CheckReadyToRun () inline protected
Checks whether the compiled code is ready to run, and enables the Run button accordingly.
References IG.Lib.RuntimeCompilerOld.ReadyToRun.
void IG.Forms.CompilerFormOld.btnCompile_Click (object sender, System.EventArgs e) inline private
Compilation of code.
References IG.Lib.Logger.Clear(), IG.Lib.RuntimeCompilerOld.Code, IG.Lib.RuntimeCompilerOld.Compile(), IG.Lib.Logger.GetErrorsReport(), IG.Lib.Logger.GetReport(), IG.Lib.Logger.GetWarningsReport(), IG.Lib.Logger.HasErrors(), IG.Lib.Logger.HasWarnings(), IG.Lib.RuntimeCompilerOld.ReadyToRun, IG.Lib.Logger.Report(), IG.Lib.ReporterBase.ReportError(), and IG.Forms.ReporterConsoleMsgbox_Base.UseMessageBox.
void IG.Forms.CompilerFormOld.btnExecute_Click (object sender, System.EventArgs e) inline private
References IG.Lib.RuntimeCompilerOld.LibraryPath, IG.Lib.RuntimeCompilerOld.LoadFile(), IG.Lib.IRunnableOld.Run(), and IG.Lib.RuntimeCompilerOld.RunnableFullClass.
override void IG.Forms.CompilerFormOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
void IG.Forms.CompilerFormOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Member Data Documentation
RuntimeCompilerOld IG.Forms.CompilerFormOld.Compiler = new RuntimeCompilerOld() protected
ReporterConsoleMsgbox IG.Forms.CompilerFormOld.Reporter = new ReporterConsoleMsgbox()
Referenced by IG.Test.RuntimeCompilerMain.Main().
Logger IG.Forms.CompilerFormOld._logger = null private
System ComponentModel IContainer IG.Forms.CompilerFormOld.components = null private
Required designer variable.
System Windows Forms RichTextBox IG.Forms.CompilerFormOld.rtfCode private
System Windows Forms Button IG.Forms.CompilerFormOld.btnLoad private
System Windows Forms Button IG.Forms.CompilerFormOld.btnCompile private
System Windows Forms Button IG.Forms.CompilerFormOld.btnExecute private
System Windows Forms Button IG.Forms.CompilerFormOld.btnQuit private
Property Documentation
Logger IG.Forms.CompilerFormOld.Logger get protected
Gets compiler's logger.
The documentation for this class was generated from the following files:
igtest/test_iglib_tmp_CSharpScripter/old_csharpscripter/OldCompilerForm.cs
igtest/test_iglib_tmp_CSharpScripter/old_csharpscripter/OldCompilerForm.Designer.cs