IGLib: NUnitLite.TextUI Class Reference
NUnitLite.TextUI Class Reference
Public Member Functions
TextUI (TextWriter writer, TextReader reader, CommandLineOptions options)
void DisplayHeader ()
Writes the header.
void DisplayTestFiles (IEnumerable< string > testFiles)
void DisplayTestFilters ()
void DisplayHelp ()
void DisplayRunSettings ()
void TestFinished (ITestResult result)
void WaitForUser (string message)
void DisplaySummaryReport (ResultSummary summary)
void DisplayErrorsAndFailuresReport (ITestResult result)
void DisplayNotRunReport (ITestResult result)
void WriteLine (string message)
void DisplayError (string message)
void DisplayErrors (IList< string > messages)
TextUI (NUnitLiteOptions options)
TextUI (ExtendedTextWriter writer, NUnitLiteOptions options)
void DisplayHeader ()
Writes the header.
void DisplayTestFiles (string[] testFiles)
void DisplayHelp ()
void DisplayRequestedOptions ()
void DisplayRuntimeEnvironment ()
Displays info about the runtime environment.
void DisplayTestFilters ()
void DisplayRunSettings ()
void TestFinished (ITestResult result)
void WaitForUser (string message)
void DisplaySummaryReport (ResultSummary summary)
void DisplayErrorsAndFailuresReport (ITestResult result)
void DisplayNotRunReport (ITestResult result)
void DisplayWarning (string text)
void DisplayError (string text)
void DisplayErrors (IList< string > messages)
Private Member Functions
void WriteSummaryCount (string label, int count)
void DisplayErrorsAndFailures (ITestResult result)
void DisplayNotRunResults (ITestResult result)
void DisplayTestResult (ITestResult result)
void WriteLabel (string label, object option)
void WriteLabelLine (string label, object option)
void WriteSummaryCount (string label, int count)
void WriteSummaryCount (string label, int count, ColorStyle color)
void DisplayErrorsAndFailures (ITestResult result)
void DisplayNotRunResults (ITestResult result)
void DisplayTestResult (ITestResult result)
void WriteLine (ColorStyle style, string text)
void WriteHeader (string text)
void WriteSubHeader (string text)
void WriteSectionHeader (string text)
void WriteHelpLine (string text)
void WriteLabel (string label, object option)
void WriteLabelLine (string label, object option)
void WriteLabelLine (string label, object option, ColorStyle valueStyle)
void SkipLine ()
Private Attributes
TextWriter _writer
TextReader _reader
CommandLineOptions _options
int _reportIndex
ExtendedTextWriter _outWriter
NUnitLiteOptions _options
bool _testCreatedOutput = false
Static Private Attributes
static readonly char[] TRIM_CHARS = { '\r', '\n' }
Constructor & Destructor Documentation
NUnitLite.TextUI.TextUI (TextWriter writer, TextReader reader, CommandLineOptions options) inline
NUnitLite.TextUI.TextUI (NUnitLiteOptions options) inline
NUnitLite.TextUI.TextUI (ExtendedTextWriter writer, NUnitLiteOptions options) inline
References NUnit.Common.CommandLineOptions.NoColor.
Member Function Documentation
void NUnitLite.TextUI.DisplayHeader () inline
Writes the header.
References NUnit.Common.AssemblyHelper.GetAssemblyName(), and NUnit.Common.String.
Referenced by NUnitLite.Tests.TextUITests.DisplayHeader().
void NUnitLite.TextUI.DisplayTestFiles (IEnumerable< string > testFiles) inline
Referenced by NUnitLite.Tests.TextUITests.DisplayTestFiles().
void NUnitLite.TextUI.DisplayTestFilters () inline
References NUnit.Common.CommandLineOptions.TestList, NUnit.Common.CommandLineOptions.WhereClause, and NUnit.Common.CommandLineOptions.WhereClauseSpecified.
Referenced by NUnitLite.TextRunner.Execute().
void NUnitLite.TextUI.DisplayHelp () inline
Referenced by NUnitLite.Tests.TextUITests.DisplayHelp().
void NUnitLite.TextUI.DisplayRunSettings () inline
References NUnit.Common.CommandLineOptions.DefaultTimeout, NUnit.Common.CommandLineOptions.TeamCity, NUnitLite.TextUI.WriteLabelLine(), and NUnitLite.TextUI.WriteLine().
Referenced by NUnitLite.TextRunner.ReportResults().
void NUnitLite.TextUI.TestFinished (ITestResult result) inline
References NUnit.Common.CommandLineOptions.DisplayTestLabels, NUnit.Framework.Interfaces.ITest.IsSuite, NUnit.Framework.Interfaces.ITest.Name, NUnit.Framework.Interfaces.ITestResult.Output, and NUnit.Framework.Interfaces.ITestResult.Test.
Referenced by NUnitLite.TextRunner.RunTests(), NUnitLite.TextRunner.TestFinished(), NUnitLite.Tests.TextUITests.TestFinished_NoOutput(), and NUnitLite.Tests.TextUITests.TestFinished_WithOutput().
void NUnitLite.TextUI.WaitForUser (string message) inline
void NUnitLite.TextUI.DisplaySummaryReport (ResultSummary summary) inline
References NUnitLite.ResultSummary.Duration, NUnitLite.ResultSummary.EndTime, NUnitLite.ResultSummary.ErrorCount, NUnitLite.ResultSummary.ExplicitCount, NUnitLite.ResultSummary.FailureCount, NUnitLite.ResultSummary.IgnoreCount, NUnitLite.ResultSummary.InconclusiveCount, NUnitLite.ResultSummary.InvalidCount, NUnitLite.ResultSummary.NotRunCount, NUnitLite.ResultSummary.PassCount, NUnitLite.ResultSummary.ResultState, NUnitLite.ResultSummary.RunCount, NUnitLite.ResultSummary.SkipCount, NUnitLite.ResultSummary.StartTime, NUnit.Framework.Interfaces.ResultState.Status, NUnitLite.TextUI.WriteLabelLine(), and NUnitLite.TextUI.WriteSummaryCount().
Referenced by NUnitLite.TextRunner.ReportResults(), and NUnitLite.Tests.TextUITests.SummaryReportTest().
void NUnitLite.TextUI.WriteSummaryCount (string label, int count) inline private
References NUnitLite.TextUI.WriteLabel().
Referenced by NUnitLite.TextUI.DisplaySummaryReport().
void NUnitLite.TextUI.DisplayErrorsAndFailuresReport (ITestResult result) inline
References NUnitLite.TextUI._reportIndex, NUnitLite.TextUI.DisplayErrorsAndFailures(), and NUnit.Common.CommandLineOptions.StopOnError.
Referenced by NUnitLite.Tests.TextUITests.ErrorsAndFailuresReportTest(), and NUnitLite.TextRunner.ReportResults().
void NUnitLite.TextUI.DisplayNotRunReport (ITestResult result) inline
References NUnitLite.TextUI._reportIndex, and NUnitLite.TextUI.DisplayNotRunResults().
Referenced by NUnitLite.TextRunner.ReportResults(), and NUnitLite.Tests.TextUITests.TestsNotRunTest().
void NUnitLite.TextUI.WriteLine (string message) inline
Referenced by NUnitLite.TextUI.DisplayError(), NUnitLite.TextUI.DisplayErrorsAndFailuresReport(), NUnitLite.TextUI.DisplayRunSettings(), NUnitLite.TextUI.DisplayTestFiles(), NUnitLite.TextUI.DisplayTestResult(), NUnitLite.TextUI.DisplayWarning(), NUnitLite.TextUI.WriteHeader(), NUnitLite.TextUI.WriteHelpLine(), NUnitLite.TextUI.WriteSectionHeader(), and NUnitLite.TextUI.WriteSubHeader().
void NUnitLite.TextUI.DisplayError (string message) inline
Referenced by NUnitLite.Tests.TextUITests.DisplayError(), NUnitLite.TextUI.DisplayErrors(), and NUnitLite.TextRunner.Execute().
void NUnitLite.TextUI.DisplayErrors (IList< string > messages) inline
Referenced by NUnitLite.Tests.TextUITests.DisplayErrors().
void NUnitLite.TextUI.DisplayErrorsAndFailures (ITestResult result) inline private
References NUnit.Framework.Interfaces.ITestResult.Children, NUnitLite.TextUI.DisplayTestResult(), NUnit.Framework.Interfaces.ITest.IsSuite, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Interfaces.ResultState.Site, NUnit.Framework.Interfaces.ResultState.Status, and NUnit.Framework.Interfaces.ITestResult.Test.
Referenced by NUnitLite.TextUI.DisplayErrorsAndFailures(), and NUnitLite.TextUI.DisplayErrorsAndFailuresReport().
void NUnitLite.TextUI.DisplayNotRunResults (ITestResult result) inline private
References NUnit.Framework.Interfaces.ITestResult.Children, NUnitLite.TextUI.DisplayTestResult(), and NUnit.Framework.Interfaces.ITestResult.HasChildren.
Referenced by NUnitLite.TextUI.DisplayNotRunReport(), and NUnitLite.TextUI.DisplayNotRunResults().
void NUnitLite.TextUI.DisplayTestResult (ITestResult result) inline private
References NUnit.Framework.Interfaces.ITestResult.FullName, NUnit.Framework.Interfaces.ResultState.Label, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Interfaces.ResultState.Site, NUnit.Framework.Interfaces.ITestResult.StackTrace, and NUnit.Framework.Interfaces.ResultState.Status.
Referenced by NUnitLite.TextUI.DisplayErrorsAndFailures(), and NUnitLite.TextUI.DisplayNotRunResults().
void NUnitLite.TextUI.WriteLabel (string label, object option) inline private
Referenced by NUnitLite.TextUI.WriteLabelLine(), and NUnitLite.TextUI.WriteSummaryCount().
void NUnitLite.TextUI.WriteLabelLine (string label, object option) inline private
References NUnitLite.TextUI.WriteLabel().
Referenced by NUnitLite.TextUI.DisplayRequestedOptions(), NUnitLite.TextUI.DisplayRunSettings(), NUnitLite.TextUI.DisplayRuntimeEnvironment(), and NUnitLite.TextUI.DisplaySummaryReport().
void NUnitLite.TextUI.DisplayHeader () inline
Writes the header.
References NUnit.Common.AssemblyHelper.GetAssemblyName(), NUnitLite.TextUI.SkipLine(), NUnit.Common.String, NUnitLite.TextUI.WriteHeader(), and NUnitLite.TextUI.WriteSubHeader().
void NUnitLite.TextUI.DisplayTestFiles (string[] testFiles) inline
References NUnitLite.TextUI.SkipLine(), NUnitLite.TextUI.WriteLine(), and NUnitLite.TextUI.WriteSectionHeader().
void NUnitLite.TextUI.DisplayHelp () inline
References NUnitLite.TextUI.SkipLine(), NUnit.Common.ExtendedTextWriter.Write(), NUnitLite.TextUI.WriteHeader(), NUnitLite.TextUI.WriteHelpLine(), and NUnitLite.TextUI.WriteSectionHeader().
void NUnitLite.TextUI.DisplayRequestedOptions () inline
References NUnit.Common.CommandLineOptions.DefaultTimeout, NUnit.Env.DefaultWorkDirectory, NUnit.Common.CommandLineOptions.InternalTraceLevel, NUnitLite.TextUI.SkipLine(), NUnit.Common.CommandLineOptions.TeamCity, NUnit.Common.CommandLineOptions.TestList, NUnit.Common.CommandLineOptions.WorkDirectory, NUnitLite.TextUI.WriteLabelLine(), NUnit.Common.ExtendedTextWriter.WriteLine(), and NUnitLite.TextUI.WriteSectionHeader().
Referenced by NUnitLite.Tests.TextUITests.DisplayRequestedOptions().
void NUnitLite.TextUI.DisplayRuntimeEnvironment () inline
Displays info about the runtime environment.
References NUnitLite.TextUI.SkipLine(), NUnitLite.TextUI.WriteLabelLine(), and NUnitLite.TextUI.WriteSectionHeader().
Referenced by NUnitLite.Tests.TextUITests.DisplayRuntimeEnvironment().
void NUnitLite.TextUI.DisplayTestFilters () inline
References NUnit.Common.CommandLineOptions.TestList, NUnit.Common.CommandLineOptions.WhereClause, NUnit.Common.CommandLineOptions.WhereClauseSpecified, NUnit.Common.ExtendedTextWriter.WriteLabelLine(), and NUnit.Common.ExtendedTextWriter.WriteLine().
void NUnitLite.TextUI.DisplayRunSettings () inline
References NUnit.Common.CommandLineOptions.DefaultTimeout, NUnit.Env.DefaultWorkDirectory, NUnit.Common.CommandLineOptions.InternalTraceLevel, NUnit.Common.CommandLineOptions.NumberOfTestWorkers, NUnitLite.TextUI.SkipLine(), NUnit.Common.CommandLineOptions.TeamCity, NUnit.Common.CommandLineOptions.WorkDirectory, NUnitLite.TextUI.WriteLabelLine(), NUnit.Common.ExtendedTextWriter.WriteLine(), and NUnitLite.TextUI.WriteSectionHeader().
void NUnitLite.TextUI.TestFinished (ITestResult result) inline
References NUnit.Common.CommandLineOptions.DisplayTestLabels, NUnit.Framework.Interfaces.ITest.IsSuite, NUnit.Framework.Interfaces.ITest.Name, NUnit.Framework.Interfaces.ITestResult.Output, NUnitLite.TextUI.SkipLine(), NUnit.Framework.Interfaces.ITestResult.Test, NUnit.Common.ExtendedTextWriter.Write(), and NUnit.Common.ExtendedTextWriter.WriteLine().
void NUnitLite.TextUI.WaitForUser (string message) inline
References NUnit.Common.ExtendedTextWriter.WriteLine().
void NUnitLite.TextUI.DisplaySummaryReport (ResultSummary summary) inline
References NUnitLite.ResultSummary.Duration, NUnitLite.ResultSummary.EndTime, NUnitLite.ResultSummary.ErrorCount, NUnitLite.ResultSummary.ExplicitCount, NUnitLite.ResultSummary.FailureCount, NUnitLite.ResultSummary.IgnoreCount, NUnitLite.ResultSummary.InconclusiveCount, NUnitLite.ResultSummary.InvalidCount, NUnitLite.ResultSummary.NotRunCount, NUnitLite.ResultSummary.PassCount, NUnitLite.ResultSummary.ResultState, NUnitLite.ResultSummary.RunCount, NUnitLite.ResultSummary.SkipCount, NUnitLite.TextUI.SkipLine(), NUnitLite.ResultSummary.StartTime, NUnit.Framework.Interfaces.ResultState.Status, NUnitLite.TextUI.WriteLabelLine(), NUnit.Common.ExtendedTextWriter.WriteLine(), NUnitLite.TextUI.WriteSectionHeader(), and NUnitLite.TextUI.WriteSummaryCount().
void NUnitLite.TextUI.WriteSummaryCount (string label, int count) inline private
References NUnit.Common.ExtendedTextWriter.WriteLabel().
void NUnitLite.TextUI.WriteSummaryCount (string label, int count, ColorStyle color) inline private
References NUnit.Common.ExtendedTextWriter.WriteLabel().
void NUnitLite.TextUI.DisplayErrorsAndFailuresReport (ITestResult result) inline
References NUnitLite.TextUI._reportIndex, NUnitLite.TextUI.DisplayErrorsAndFailures(), NUnitLite.TextUI.SkipLine(), NUnit.Common.CommandLineOptions.StopOnError, NUnitLite.TextUI.WriteLine(), and NUnitLite.TextUI.WriteSectionHeader().
void NUnitLite.TextUI.DisplayNotRunReport (ITestResult result) inline
References NUnitLite.TextUI._reportIndex, NUnitLite.TextUI.DisplayNotRunResults(), NUnitLite.TextUI.SkipLine(), and NUnitLite.TextUI.WriteSectionHeader().
void NUnitLite.TextUI.DisplayWarning (string text) inline
References NUnitLite.TextUI.WriteLine().
Referenced by NUnitLite.Tests.TextUITests.DisplayWarning().
void NUnitLite.TextUI.DisplayError (string text) inline
References NUnitLite.TextUI.WriteLine().
void NUnitLite.TextUI.DisplayErrors (IList< string > messages) inline
References NUnitLite.TextUI.DisplayError().
void NUnitLite.TextUI.DisplayErrorsAndFailures (ITestResult result) inline private
References NUnit.Framework.Interfaces.ITestResult.Children, NUnitLite.TextUI.DisplayErrorsAndFailures(), NUnitLite.TextUI.DisplayTestResult(), NUnit.Framework.Interfaces.ITest.IsSuite, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Interfaces.ResultState.Site, NUnit.Framework.Interfaces.ResultState.Status, and NUnit.Framework.Interfaces.ITestResult.Test.
void NUnitLite.TextUI.DisplayNotRunResults (ITestResult result) inline private
References NUnit.Framework.Interfaces.ITestResult.Children, NUnitLite.TextUI.DisplayNotRunResults(), NUnitLite.TextUI.DisplayTestResult(), and NUnit.Framework.Interfaces.ITestResult.HasChildren.
void NUnitLite.TextUI.DisplayTestResult (ITestResult result) inline private
References NUnit.Framework.Interfaces.ITestResult.FullName, NUnit.Framework.Interfaces.ResultState.Label, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Interfaces.ResultState.Site, NUnitLite.TextUI.SkipLine(), NUnit.Framework.Interfaces.ITestResult.StackTrace, NUnit.Framework.Interfaces.ResultState.Status, and NUnitLite.TextUI.WriteLine().
void NUnitLite.TextUI.WriteLine (ColorStyle style, string text) inline private
References NUnit.Common.ExtendedTextWriter.WriteLine().
void NUnitLite.TextUI.WriteHeader (string text) inline private
References NUnitLite.TextUI.WriteLine().
Referenced by NUnitLite.TextUI.DisplayHeader(), and NUnitLite.TextUI.DisplayHelp().
void NUnitLite.TextUI.WriteSubHeader (string text) inline private
References NUnitLite.TextUI.WriteLine().
Referenced by NUnitLite.TextUI.DisplayHeader().
void NUnitLite.TextUI.WriteSectionHeader (string text) inline private
References NUnitLite.TextUI.WriteLine().
Referenced by NUnitLite.TextUI.DisplayErrorsAndFailuresReport(), NUnitLite.TextUI.DisplayHelp(), NUnitLite.TextUI.DisplayNotRunReport(), NUnitLite.TextUI.DisplayRequestedOptions(), NUnitLite.TextUI.DisplayRunSettings(), NUnitLite.TextUI.DisplayRuntimeEnvironment(), NUnitLite.TextUI.DisplaySummaryReport(), and NUnitLite.TextUI.DisplayTestFiles().
void NUnitLite.TextUI.WriteHelpLine (string text) inline private
References NUnitLite.TextUI.WriteLine().
Referenced by NUnitLite.TextUI.DisplayHelp().
void NUnitLite.TextUI.WriteLabel (string label, object option) inline private
References NUnit.Common.ExtendedTextWriter.WriteLabel().
void NUnitLite.TextUI.WriteLabelLine (string label, object option) inline private
References NUnit.Common.ExtendedTextWriter.WriteLabelLine().
void NUnitLite.TextUI.WriteLabelLine (string label, object option, ColorStyle valueStyle) inline private
References NUnit.Common.ExtendedTextWriter.WriteLabelLine().
void NUnitLite.TextUI.SkipLine () inline private
References NUnit.Common.ExtendedTextWriter.WriteLine().
Referenced by NUnitLite.TextUI.DisplayErrorsAndFailuresReport(), NUnitLite.TextUI.DisplayHeader(), NUnitLite.TextUI.DisplayHelp(), NUnitLite.TextUI.DisplayNotRunReport(), NUnitLite.TextUI.DisplayRequestedOptions(), NUnitLite.TextUI.DisplayRunSettings(), NUnitLite.TextUI.DisplayRuntimeEnvironment(), NUnitLite.TextUI.DisplaySummaryReport(), NUnitLite.TextUI.DisplayTestFiles(), NUnitLite.TextUI.DisplayTestResult(), and NUnitLite.TextUI.TestFinished().
Member Data Documentation
TextWriter NUnitLite.TextUI._writer private
TextReader NUnitLite.TextUI._reader private
CommandLineOptions NUnitLite.TextUI._options private
readonly char [] NUnitLite.TextUI.TRIM_CHARS = { '\r', '\n' } static private
int NUnitLite.TextUI._reportIndex private
Referenced by NUnitLite.TextUI.DisplayErrorsAndFailuresReport(), and NUnitLite.TextUI.DisplayNotRunReport().
ExtendedTextWriter NUnitLite.TextUI._outWriter private
NUnitLiteOptions NUnitLite.TextUI._options private
bool NUnitLite.TextUI._testCreatedOutput = false private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/nunitlite.runner/Portable/TextUI.cs