IGLib: NUnit.Framework.Assertions.DirectoryAssertTests Class Reference
NUnit.Framework.Assertions.DirectoryAssertTests Class Reference
Public Member Functions
void SetUp ()
void TearDown ()
void AreEqualPassesWithDirectoryInfos ()
void AreEqualFailsWithDirectoryInfos ()
void AreNotEqualPassesIfExpectedIsNull ()
void AreNotEqualPassesIfActualIsNull ()
void AreNotEqualPassesWithDirectoryInfos ()
void AreNotEqualFailsWithDirectoryInfos ()
void ExistsPassesWhenDirectoryInfoExists ()
void ExistsPassesWhenStringExists ()
void ExistsFailsWhenDirectoryInfoDoesNotExist ()
void ExistsFailsWhenStringDoesNotExist ()
void ExistsFailsWhenDirectoryInfoIsNull ()
void ExistsFailsWhenStringIsNull ()
void ExistsFailsWhenStringIsEmpty ()
void DoesNotExistFailsWhenDirectoryInfoExists ()
void DoesNotExistFailsWhenStringExists ()
void DoesNotExistPassesWhenDirectoryInfoDoesNotExist ()
void DoesNotExistPassesWhenStringDoesNotExist ()
void DoesNotExistFailsWhenDirectoryInfoIsNull ()
void DoesNotExistFailsWhenStringIsNull ()
void DoesNotExistFailsWhenStringIsEmpty ()
Private Attributes
TestDirectory _goodDir1
TestDirectory _goodDir2
const string BAD_DIRECTORY = @"\I\hope\this\is\garbage"
Member Function Documentation
void NUnit.Framework.Assertions.DirectoryAssertTests.SetUp () inline
References NUnit.TestUtilities.TestDirectory.Directory, NUnit.Framework.Does.Not, NUnit.Framework.Is.Not, and NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.DirectoryAssertTests.TearDown () inline
References NUnit.TestUtilities.TestDirectory.Dispose().
void NUnit.Framework.Assertions.DirectoryAssertTests.AreEqualPassesWithDirectoryInfos () inline
References NUnit.Framework.DirectoryAssert.AreEqual(), and NUnit.TestUtilities.TestDirectory.ToString().
void NUnit.Framework.Assertions.DirectoryAssertTests.AreEqualFailsWithDirectoryInfos () inline
References NUnit.Framework.DirectoryAssert.AreEqual(), NUnit.TestUtilities.TestDirectory.Directory, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualPassesIfExpectedIsNull () inline
References NUnit.Framework.DirectoryAssert.AreNotEqual(), and NUnit.TestUtilities.TestDirectory.Directory.
void NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualPassesIfActualIsNull () inline
References NUnit.Framework.DirectoryAssert.AreNotEqual(), and NUnit.TestUtilities.TestDirectory.Directory.
void NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualPassesWithDirectoryInfos () inline
References NUnit.Framework.DirectoryAssert.AreNotEqual(), and NUnit.TestUtilities.TestDirectory.Directory.
void NUnit.Framework.Assertions.DirectoryAssertTests.AreNotEqualFailsWithDirectoryInfos () inline
References NUnit.Framework.DirectoryAssert.AreNotEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.TestUtilities.TestDirectory.ToString().
void NUnit.Framework.Assertions.DirectoryAssertTests.ExistsPassesWhenDirectoryInfoExists () inline
References NUnit.TestUtilities.TestDirectory.Directory, and NUnit.Framework.DirectoryAssert.Exists().
void NUnit.Framework.Assertions.DirectoryAssertTests.ExistsPassesWhenStringExists () inline
References NUnit.Framework.DirectoryAssert.Exists(), and NUnit.TestUtilities.TestDirectory.ToString().
void NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenDirectoryInfoDoesNotExist () inline
References NUnit.Framework.DirectoryAssert.Exists(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenStringDoesNotExist () inline
References NUnit.Framework.DirectoryAssert.Exists(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenDirectoryInfoIsNull () inline
References NUnit.Framework.DirectoryAssert.Exists(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenStringIsNull () inline
References NUnit.Framework.DirectoryAssert.Exists(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.DirectoryAssertTests.ExistsFailsWhenStringIsEmpty () inline
References NUnit.Framework.DirectoryAssert.Exists(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenDirectoryInfoExists () inline
References NUnit.TestUtilities.TestDirectory.Directory, NUnit.Framework.DirectoryAssert.DoesNotExist(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenStringExists () inline
References NUnit.Framework.DirectoryAssert.DoesNotExist(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.TestUtilities.TestDirectory.ToString().
void NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistPassesWhenDirectoryInfoDoesNotExist () inline
References NUnit.Framework.DirectoryAssert.DoesNotExist().
void NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistPassesWhenStringDoesNotExist () inline
References NUnit.Framework.DirectoryAssert.DoesNotExist().
void NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenDirectoryInfoIsNull () inline
References NUnit.Framework.DirectoryAssert.DoesNotExist(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenStringIsNull () inline
References NUnit.Framework.DirectoryAssert.DoesNotExist(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.DirectoryAssertTests.DoesNotExistFailsWhenStringIsEmpty () inline
References NUnit.Framework.DirectoryAssert.DoesNotExist(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
Member Data Documentation
TestDirectory NUnit.Framework.Assertions.DirectoryAssertTests._goodDir1 private
TestDirectory NUnit.Framework.Assertions.DirectoryAssertTests._goodDir2 private
const string NUnit.Framework.Assertions.DirectoryAssertTests.BAD_DIRECTORY = @"\I\hope\this\is\garbage" private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/DirectoryAssertTests.cs