IGLib: IG.Neural.Forms.NeuralTrainingControl Class Reference
IG.Neural.Forms.NeuralTrainingControl Class Reference
A 2D neural network approximation demo control.
Public Member Functions
NeuralTrainingControl ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
void GenerateDefaultPoints2D ()
Generates the set of default points according to settings.
void RemoveApprovimationActors ()
void Bounds2D ()
void ResetAll2D ()
Reset all to default.
void PrepareDefaultPlots ()
Prepare default plots of.
Static Public Member Functions
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
Public Attributes
System.ComponentModel.BackgroundWorker backgroundWorker2D
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
INeuralModelContainer _neuralModelContainerControl
INeuralApproximator _neuralApproximator
Properties
INeuralModel NeuralModel [get, protected set]
Neural network - based model.
INeuralApproximator TrainedNetwork [get]
Traint artificial neural network.
InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
INeuralApproximator network2D [get]
Traint artificial neural network.
virtual INeuralApproximator NeuralApproximator [get, set]
Neural approximator.
BoundingBox3d ScaledBounds [get]
Properties inherited from IG.Neural.INeuralModelContainer
INeuralModel NeuralModel [get]
Artificial neural network - based model.
Private Member Functions
void LoadForm (object sender, EventArgs e)
void InitializeApproximator2D ()
Clean and initialize the approximator.
void InitializeTrainingData2D ()
Clean and initialize the training data set.
void InitializeVerificationData2D ()
Clean and initialize the verification data set.
void InitializeDefaultData2D ()
Clean and initialize the default data set.
void WriteErrors2D ()
Write training and verification errors in text box.
void ClearErrorGraph2D ()
Clear Graph with error convergence for 2 dimension.
void btReset2D_Click (object sender, EventArgs e)
Reset button.
void btStart2D_Click (object sender, EventArgs e)
Start training button.
void btStop2D_Click (object sender, EventArgs e)
Stop training button.
void TrainNetworkThread2D ()
void btnGenerateOptData2D_Click (object sender, EventArgs e)
Generate training data button.
void btnShowDefault_Click (object sender, EventArgs e)
Show default graph button.
void rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void numMaxEpoch2D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle2D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS2D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate2D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum2D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron2D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety2D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety2D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
INeuralModel _neuralModel
GraphPane pane2DError
Error graph.
SampledDataSet trainingData2D = null
Training data set.
SampledDataSet verificationData2D = null
Verification data set.
SampledDataSet defaultFunctionData2D = null
Default data set.
int hiddenNeuronL12D = 5
int hiddenNeuronL22D = 0
int maxEpoch2D = 5000
int epochInBundle2D = 500
double rmsError2D = 0.001
double learningRate2D = 0.3
double momentum2D = 0.6
int samplesX2D = 5
int samplesY2D = 5
double lowHorizontalLimit2D = -1.0
double highHorizontalLimit2D = 1.0
double lowVerticalLimit2D = -1.0
double highVerticalLimit2D = 1.0
double lowVerificationHorizontalLimit2D = -5.0
double highVerificationHorizontalLimit2D = 5.0
double inputSafetyFactor2D = 1.3
double outputSafetyFactor2D = 1.3
string equation2D = "x*x + y*y"
string[] variableNames2D = { "x", "y" }
bool maxTrainErrorEnabled2D = true
bool rmsTrainErrorEnabled2D = false
bool maxVerErrorEnabled2D = false
bool rmsVerErrorEnabled2D = false
bool defaultSurfaceonGraph = false
bool defaultGreedonGraph = true
bool trainingPointsonGraph = true
bool approximationSurfaceonGraph = true
bool approximationGreedonGraph = false
bool contureDefaultonGraph = false
bool contureApproximationonGraph = false
bool stopTraining2D = false
bool stopTraining1D = false
double opacityDefaultGraph2D = 0.5
double opacityApproxGraph2D = 0.7
double opacityContourGraph2D = 1.0
int numAllXPoints2D = 100
int numAllYPoints2D = 100
LineItem errorConvergenceFunction2D
Func2dFromScalarFunction iFunctionDefault2D
Scalar function that is approximated.
IScalarFunction scalarFunctionDefault2D
Scalar function that is approximated.
StructuredMesh2d3d Default2DMesh
Maeh of default points used for plotting.
VtkSurfacePlot plotDefault2D
Plot from default points.
VtkContourPlot plotApproximationConture2D
Conture Plot from approximated points.
VtkSurfacePlot plotTrainingPoints2D
Plot from training points.
Func2dFromApproximator iFunctionApproximator2D
Scalar function that is approximated.
ExampleValueFunctionDiff3D iFunctionDifference2D
Scalar function that is a difference default and approximated function.
VtkSurfacePlot plotApproximation2D
Plot from approximated points.
VtkContourPlot plotDefaultConture2D
Conture Plot from default points.
BoundingBox2d paramBounds2D
Bounding box for function limits. </summary
BoundingBox3d _scaledBounds
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.TextBox tbEquationError2D
System.Windows.Forms.RadioButton rbRmsTrainError2D
System.Windows.Forms.RadioButton rbMaxTrainError2D
System.Windows.Forms.RadioButton rbRmsVerError2D
System.Windows.Forms.RadioButton rbMaxVerError2D
System.Windows.Forms.TextBox tbRmsTrainError2D
System.Windows.Forms.Label label26
System.Windows.Forms.Label label27
System.Windows.Forms.TextBox tbMaxTrainError2D
System.Windows.Forms.TextBox tbRmsVerError2D
System.Windows.Forms.TextBox tbMaxVerError2D
System.Windows.Forms.Label label28
System.Windows.Forms.Label label29
ZedGraph.ZedGraphControl errorConvergence2D
System.Windows.Forms.NumericUpDown numHiddenNeuronL22D
System.Windows.Forms.NumericUpDown numHiddenNeuron2D
System.Windows.Forms.Button btLoadANN2D
System.Windows.Forms.Button btSaveANN2D
System.Windows.Forms.Button btReset2D
System.Windows.Forms.Button btStart2D
System.Windows.Forms.NumericUpDown numOutputSafety2D
System.Windows.Forms.Label label17
System.Windows.Forms.NumericUpDown numInputSafety2D
System.Windows.Forms.Label label18
System.Windows.Forms.Label label20
System.Windows.Forms.NumericUpDown numMomentum2D
System.Windows.Forms.NumericUpDown numLearningRate2D
System.Windows.Forms.NumericUpDown numRMS2D
System.Windows.Forms.NumericUpDown numEpochBundle2D
System.Windows.Forms.NumericUpDown numMaxEpoch2D
System.Windows.Forms.Label label21
System.Windows.Forms.Label label22
System.Windows.Forms.Label label23
System.Windows.Forms.Label label24
System.Windows.Forms.Label label25
System.Windows.Forms.Button btLoad2D
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.Button btStop2D
Detailed Description
A 2D neural network approximation demo control.
$A Tadej xx; Igor Feb13;
Constructor & Destructor Documentation
IG.Neural.Forms.NeuralTrainingControl.NeuralTrainingControl () inline
Member Function Documentation
void IG.Neural.Forms.NeuralTrainingControl.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
void IG.Neural.Forms.NeuralTrainingControl.LoadForm (object sender, EventArgs e) inline private
static ColorScale IG.Neural.Forms.NeuralTrainingControl.CreateGreenRedYellow (double minValue, double maxValue) inline static
void IG.Neural.Forms.NeuralTrainingControl.InitializeApproximator2D () inline private
Clean and initialize the approximator.
void IG.Neural.Forms.NeuralTrainingControl.InitializeTrainingData2D () inline private
Clean and initialize the training data set.
void IG.Neural.Forms.NeuralTrainingControl.InitializeVerificationData2D () inline private
Clean and initialize the verification data set.
void IG.Neural.Forms.NeuralTrainingControl.InitializeDefaultData2D () inline private
Clean and initialize the default data set.
void IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D () inline private
Write training and verification errors in text box.
void IG.Neural.Forms.NeuralTrainingControl.ClearErrorGraph2D () inline private
Clear Graph with error convergence for 2 dimension.
void IG.Neural.Forms.NeuralTrainingControl.GenerateDefaultPoints2D () inline
Generates the set of default points according to settings.
References IG.Num.StructuredMeshGeometry2d< TCoord >.Coordinates, IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Num.StructuredMesh2d3d.GenerateCoordinates(), and IG.Num.IScalarFunctionUntransformed.Value().
void IG.Neural.Forms.NeuralTrainingControl.RemoveApprovimationActors () inline
void IG.Neural.Forms.NeuralTrainingControl.Bounds2D () inline
void IG.Neural.Forms.NeuralTrainingControl.ResetAll2D () inline
Reset all to default.
void IG.Neural.Forms.NeuralTrainingControl.btReset2D_Click (object sender, EventArgs e) inline private
Reset button.
void IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Num.SampledDataSet.AddElement(), IG.Num.Field< TElement >.GetValue(), IG.Num.SampledDataSet.InputLength, IG.Gr3d.VtkSurfacePlot.Mesh, and IG.Num.SampledDataSet.OutputLength.
void IG.Neural.Forms.NeuralTrainingControl.btStop2D_Click (object sender, EventArgs e) inline private
Stop training button.
void IG.Neural.Forms.NeuralTrainingControl.TrainNetworkThread2D () inline private
void IG.Neural.Forms.NeuralTrainingControl.btnGenerateOptData2D_Click (object sender, EventArgs e) inline private
Generate training data button.
void IG.Neural.Forms.NeuralTrainingControl.btnShowDefault_Click (object sender, EventArgs e) inline private
Show default graph button.
void IG.Neural.Forms.NeuralTrainingControl.PrepareDefaultPlots () inline
Prepare default plots of.
void IG.Neural.Forms.NeuralTrainingControl.rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
void IG.Neural.Forms.NeuralTrainingControl.rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
void IG.Neural.Forms.NeuralTrainingControl.rbMaxVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
void IG.Neural.Forms.NeuralTrainingControl.rbRmsVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
void IG.Neural.Forms.NeuralTrainingControl.numMaxEpoch2D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
void IG.Neural.Forms.NeuralTrainingControl.numEpochBundle2D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
void IG.Neural.Forms.NeuralTrainingControl.numRMS2D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
void IG.Neural.Forms.NeuralTrainingControl.numLearningRate2D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
void IG.Neural.Forms.NeuralTrainingControl.numMomentum2D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
void IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuron2D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
void IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
void IG.Neural.Forms.NeuralTrainingControl.numInputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
void IG.Neural.Forms.NeuralTrainingControl.numOutputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
void IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e) inline private
References IG.Lib.StopWatch1.Start(), and IG.Lib.StopWatch1.Stop().
void IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
override void IG.Neural.Forms.NeuralTrainingControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
void IG.Neural.Forms.NeuralTrainingControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Member Data Documentation
INeuralModelContainer IG.Neural.Forms.NeuralTrainingControl._neuralModelContainerControl protected
INeuralModel IG.Neural.Forms.NeuralTrainingControl._neuralModel private
GraphPane IG.Neural.Forms.NeuralTrainingControl.pane2DError private
Error graph.
INeuralApproximator IG.Neural.Forms.NeuralTrainingControl._neuralApproximator protected
SampledDataSet IG.Neural.Forms.NeuralTrainingControl.trainingData2D = null private
Training data set.
SampledDataSet IG.Neural.Forms.NeuralTrainingControl.verificationData2D = null private
Verification data set.
SampledDataSet IG.Neural.Forms.NeuralTrainingControl.defaultFunctionData2D = null private
Default data set.
int IG.Neural.Forms.NeuralTrainingControl.hiddenNeuronL12D = 5 private
int IG.Neural.Forms.NeuralTrainingControl.hiddenNeuronL22D = 0 private
int IG.Neural.Forms.NeuralTrainingControl.maxEpoch2D = 5000 private
int IG.Neural.Forms.NeuralTrainingControl.epochInBundle2D = 500 private
double IG.Neural.Forms.NeuralTrainingControl.rmsError2D = 0.001 private
double IG.Neural.Forms.NeuralTrainingControl.learningRate2D = 0.3 private
double IG.Neural.Forms.NeuralTrainingControl.momentum2D = 0.6 private
int IG.Neural.Forms.NeuralTrainingControl.samplesX2D = 5 private
int IG.Neural.Forms.NeuralTrainingControl.samplesY2D = 5 private
double IG.Neural.Forms.NeuralTrainingControl.lowHorizontalLimit2D = -1.0 private
double IG.Neural.Forms.NeuralTrainingControl.highHorizontalLimit2D = 1.0 private
double IG.Neural.Forms.NeuralTrainingControl.lowVerticalLimit2D = -1.0 private
double IG.Neural.Forms.NeuralTrainingControl.highVerticalLimit2D = 1.0 private
double IG.Neural.Forms.NeuralTrainingControl.lowVerificationHorizontalLimit2D = -5.0 private
double IG.Neural.Forms.NeuralTrainingControl.highVerificationHorizontalLimit2D = 5.0 private
double IG.Neural.Forms.NeuralTrainingControl.inputSafetyFactor2D = 1.3 private
double IG.Neural.Forms.NeuralTrainingControl.outputSafetyFactor2D = 1.3 private
string IG.Neural.Forms.NeuralTrainingControl.equation2D = "x*x + y*y" private
string [] IG.Neural.Forms.NeuralTrainingControl.variableNames2D = { "x", "y" } private
bool IG.Neural.Forms.NeuralTrainingControl.maxTrainErrorEnabled2D = true private
bool IG.Neural.Forms.NeuralTrainingControl.rmsTrainErrorEnabled2D = false private
bool IG.Neural.Forms.NeuralTrainingControl.maxVerErrorEnabled2D = false private
bool IG.Neural.Forms.NeuralTrainingControl.rmsVerErrorEnabled2D = false private
bool IG.Neural.Forms.NeuralTrainingControl.defaultSurfaceonGraph = false private
bool IG.Neural.Forms.NeuralTrainingControl.defaultGreedonGraph = true private
bool IG.Neural.Forms.NeuralTrainingControl.trainingPointsonGraph = true private
bool IG.Neural.Forms.NeuralTrainingControl.approximationSurfaceonGraph = true private
bool IG.Neural.Forms.NeuralTrainingControl.approximationGreedonGraph = false private
bool IG.Neural.Forms.NeuralTrainingControl.contureDefaultonGraph = false private
bool IG.Neural.Forms.NeuralTrainingControl.contureApproximationonGraph = false private
bool IG.Neural.Forms.NeuralTrainingControl.stopTraining2D = false private
bool IG.Neural.Forms.NeuralTrainingControl.stopTraining1D = false private
double IG.Neural.Forms.NeuralTrainingControl.opacityDefaultGraph2D = 0.5 private
double IG.Neural.Forms.NeuralTrainingControl.opacityApproxGraph2D = 0.7 private
double IG.Neural.Forms.NeuralTrainingControl.opacityContourGraph2D = 1.0 private
int IG.Neural.Forms.NeuralTrainingControl.numAllXPoints2D = 100 private
int IG.Neural.Forms.NeuralTrainingControl.numAllYPoints2D = 100 private
LineItem IG.Neural.Forms.NeuralTrainingControl.errorConvergenceFunction2D private
Func2dFromScalarFunction IG.Neural.Forms.NeuralTrainingControl.iFunctionDefault2D private
Scalar function that is approximated.
IScalarFunction IG.Neural.Forms.NeuralTrainingControl.scalarFunctionDefault2D private
Scalar function that is approximated.
StructuredMesh2d3d IG.Neural.Forms.NeuralTrainingControl.Default2DMesh private
Maeh of default points used for plotting.
VtkSurfacePlot IG.Neural.Forms.NeuralTrainingControl.plotDefault2D private
Plot from default points.
VtkContourPlot IG.Neural.Forms.NeuralTrainingControl.plotApproximationConture2D private
Conture Plot from approximated points.
VtkSurfacePlot IG.Neural.Forms.NeuralTrainingControl.plotTrainingPoints2D private
Plot from training points.
Func2dFromApproximator IG.Neural.Forms.NeuralTrainingControl.iFunctionApproximator2D private
Scalar function that is approximated.
ExampleValueFunctionDiff3D IG.Neural.Forms.NeuralTrainingControl.iFunctionDifference2D private
Scalar function that is a difference default and approximated function.
VtkSurfacePlot IG.Neural.Forms.NeuralTrainingControl.plotApproximation2D private
Plot from approximated points.
VtkContourPlot IG.Neural.Forms.NeuralTrainingControl.plotDefaultConture2D private
Conture Plot from default points.
BoundingBox2d IG.Neural.Forms.NeuralTrainingControl.paramBounds2D private
Bounding box for function limits. </summary
BoundingBox3d IG.Neural.Forms.NeuralTrainingControl._scaledBounds private
System.ComponentModel.IContainer IG.Neural.Forms.NeuralTrainingControl.components = null private
Required designer variable.
System.Windows.Forms.TextBox IG.Neural.Forms.NeuralTrainingControl.tbEquationError2D private
System.Windows.Forms.RadioButton IG.Neural.Forms.NeuralTrainingControl.rbRmsTrainError2D private
System.Windows.Forms.RadioButton IG.Neural.Forms.NeuralTrainingControl.rbMaxTrainError2D private
System.Windows.Forms.RadioButton IG.Neural.Forms.NeuralTrainingControl.rbRmsVerError2D private
System.Windows.Forms.RadioButton IG.Neural.Forms.NeuralTrainingControl.rbMaxVerError2D private
System.Windows.Forms.TextBox IG.Neural.Forms.NeuralTrainingControl.tbRmsTrainError2D private
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label26 private
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label27 private
System.Windows.Forms.TextBox IG.Neural.Forms.NeuralTrainingControl.tbMaxTrainError2D private
System.Windows.Forms.TextBox IG.Neural.Forms.NeuralTrainingControl.tbRmsVerError2D private
System.Windows.Forms.TextBox IG.Neural.Forms.NeuralTrainingControl.tbMaxVerError2D private
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label28 private
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label29 private
ZedGraph.ZedGraphControl IG.Neural.Forms.NeuralTrainingControl.errorConvergence2D private
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuronL22D private
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuron2D private
System.Windows.Forms.Button IG.Neural.Forms.NeuralTrainingControl.btLoadANN2D private
System.Windows.Forms.Button IG.Neural.Forms.NeuralTrainingControl.btSaveANN2D private
System.Windows.Forms.Button IG.Neural.Forms.NeuralTrainingControl.btReset2D private
System.Windows.Forms.Button IG.Neural.Forms.NeuralTrainingControl.btStart2D private
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numOutputSafety2D private
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label17 private
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numInputSafety2D private
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label18 private
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label20 private
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numMomentum2D private
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numLearningRate2D private
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numRMS2D private
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numEpochBundle2D private
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numMaxEpoch2D private
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label21 private
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label22 private
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label23 private
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label24 private
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label25 private
System.Windows.Forms.Button IG.Neural.Forms.NeuralTrainingControl.btLoad2D private
System.Windows.Forms.GroupBox IG.Neural.Forms.NeuralTrainingControl.groupBox1 private
System.Windows.Forms.GroupBox IG.Neural.Forms.NeuralTrainingControl.groupBox2 private
System.Windows.Forms.GroupBox IG.Neural.Forms.NeuralTrainingControl.groupBox4 private
System.Windows.Forms.Button IG.Neural.Forms.NeuralTrainingControl.btStop2D private
System.ComponentModel.BackgroundWorker IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D
Property Documentation
INeuralModel IG.Neural.Forms.NeuralTrainingControl.NeuralModel get protected set
Neural network - based model.
Contains data definition and trained neural network approximator.
INeuralApproximator IG.Neural.Forms.NeuralTrainingControl.TrainedNetwork get
Traint artificial neural network.
InputOutputDataDefiniton IG.Neural.Forms.NeuralTrainingControl.NeuralDataDefinition get
Neural data definition.
INeuralApproximator IG.Neural.Forms.NeuralTrainingControl.network2D get
Traint artificial neural network.
virtual INeuralApproximator IG.Neural.Forms.NeuralTrainingControl.NeuralApproximator get set
Neural approximator.
BoundingBox3d IG.Neural.Forms.NeuralTrainingControl.ScaledBounds get protected
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/ResponseForms/TestingStage/Training/NeuralTrainingControl.cs
shelldev/extensions/ExtAppAnnApp/ResponseForms/TestingStage/Training/NeuralTrainingControl.Designer.cs