IGLib: alglib.odesolver.odesolverreport Class Reference
alglib.odesolver.odesolverreport Class Reference
Public Member Functions
odesolverreport ()
override void init ()
override alglib.apobject make_copy ()
Public Attributes
int nfev
int terminationtype
Constructor & Destructor Documentation
alglib.odesolver.odesolverreport.odesolverreport () inline
References alglib.odesolver.odesolverreport.init().
Referenced by alglib.odesolver.odesolverreport.make_copy().
Member Function Documentation
override void alglib.odesolver.odesolverreport.init () inline virtual
Implements alglib.apobject.
Referenced by alglib.odesolver.odesolverreport.odesolverreport().
override alglib.apobject alglib.odesolver.odesolverreport.make_copy () inline virtual
Implements alglib.apobject.
References alglib.odesolver.odesolverreport.nfev, alglib.odesolver.odesolverreport.odesolverreport(), and alglib.odesolver.odesolverreport.terminationtype.
Member Data Documentation
int alglib.odesolver.odesolverreport.nfev
Referenced by alglib.odesolver.odesolverreport.make_copy(), and alglib.odesolver.odesolverresults().
int alglib.odesolver.odesolverreport.terminationtype
Referenced by alglib.odesolver.odesolverreport.make_copy(), and alglib.odesolver.odesolverresults().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/diffequations.cs