IGLib: HelloVTKForm.Form1 Class Reference
HelloVTKForm.Form1 Class Reference
Public Member Functions
Form1 ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void renderWindowControl1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
Kitware.VTK.RenderWindowControl renderWindowControl1
Constructor & Destructor Documentation
HelloVTKForm.Form1.Form1 () inline
References HelloVTKForm.Form1.InitializeComponent().
Member Function Documentation
void HelloVTKForm.Form1.renderWindowControl1_Load (object sender, EventArgs e) inline private
References HelloVTKForm.Form1.renderWindowControl1.
Referenced by HelloVTKForm.Form1.InitializeComponent().
override void HelloVTKForm.Form1.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References HelloVTKForm.Form1.components.
void HelloVTKForm.Form1.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References HelloVTKForm.Form1.renderWindowControl1, and HelloVTKForm.Form1.renderWindowControl1_Load().
Referenced by HelloVTKForm.Form1.Form1().
Member Data Documentation
System.ComponentModel.IContainer HelloVTKForm.Form1.components = null private
Required designer variable.
Referenced by HelloVTKForm.Form1.Dispose().
Kitware.VTK.RenderWindowControl HelloVTKForm.Form1.renderWindowControl1 private
Referenced by HelloVTKForm.Form1.InitializeComponent(), and HelloVTKForm.Form1.renderWindowControl1_Load().
The documentation for this class was generated from the following files:
iglib/extensions/igplot3d/plot3d/vtkbased/Forms/testforms/VtkExample/Form1.cs
iglib/extensions/igplot3d/plot3d/vtkbased/Forms/testforms/VtkExample/Form1.Designer.cs