IGLib: IG.Lib.RuntimeCompilerOld Class Reference
IG.Lib.RuntimeCompilerOld Class Reference
Public Member Functions
string GetExecutableDirectory ()
Returns the directory containing the executable that started the current application.
byte[] LoadFile (string filePath)
Copies the specified file to byte array and returns it.
void Compile ()
string GetExecutableDirectory ()
Returns the directory containing the executable that started the current application.
byte[] LoadFile (string filePath)
Copies the specified file to byte array and returns it.
void Compile ()
Protected Member Functions
void GenerateNewLibraryName ()
Generates a new library file name.
void GenerateNewLibraryName ()
Generates a new library file name.
Protected Attributes
string _code = null
string _runnableNamespace = "IG.Lib"
string _runnableClass = "TestClass"
string _runnableInterface = "IRunnableOld"
string _runnableFunction = "Run"
string _libraryOriginalName = "TestClass"
int _idLibraryName = 0
string _libraryFileName = "TestClass.dll"
bool _readyToRun = false
Properties
Logger Logger [get]
virtual string CodeBase [get]
Gets code base (a template code for compiling) where names of classes, methods etc. are properly set.
string Code [get, set]
Gets or sets code to be compiled. Get: If not assigned explicitly then CodeBase is taken.
string RunnableNamespace [get, protected set]
string RunnableInterface [get, protected set]
string RunnableClass [get, protected set]
string RunnableFullClass [get]
string RunnableFunction [get, protected set]
virtual string LibraryDirectory [get]
Returns directory where library will be compiled, which will be the directory of the executable that started the application.
virtual string LibraryPath [get]
Path to the dll where code is compiled. We take the directory where executable is located.
virtual bool ReadyToRun [get, set]
Wheather the compiled class' method is ready to run.
Private Attributes
Logger _logger = new Logger()
string _executableDirectory = null
Member Function Documentation
void IG.Lib.RuntimeCompilerOld.GenerateNewLibraryName () inline protected
Generates a new library file name.
string IG.Lib.RuntimeCompilerOld.GetExecutableDirectory () inline
Returns the directory containing the executable that started the current application.
byte [] IG.Lib.RuntimeCompilerOld.LoadFile (string filePath) inline
Copies the specified file to byte array and returns it.
TODO: move this to utils or something like that!
Referenced by IG.Forms.CompilerFormOld.btnExecute_Click().
void IG.Lib.RuntimeCompilerOld.Compile () inline
References IG.Lib.Logger.LogError(), IG.Lib.Logger.LogInfo(), and IG.Lib.Logger.LogWarning().
Referenced by IG.Forms.CompilerFormOld.btnCompile_Click().
void IG.Lib.RuntimeCompilerOld.GenerateNewLibraryName () inline protected
Generates a new library file name.
string IG.Lib.RuntimeCompilerOld.GetExecutableDirectory () inline
Returns the directory containing the executable that started the current application.
byte [] IG.Lib.RuntimeCompilerOld.LoadFile (string filePath) inline
Copies the specified file to byte array and returns it.
TODO: move this to utils or something like that!
void IG.Lib.RuntimeCompilerOld.Compile () inline
References IG.Lib.Logger.LogError(), IG.Lib.Logger.LogInfo(), and IG.Lib.Logger.LogWarning().
Member Data Documentation
Logger IG.Lib.RuntimeCompilerOld._logger = new Logger() private
string IG.Lib.RuntimeCompilerOld._code = null protected
string IG.Lib.RuntimeCompilerOld._runnableNamespace = "IG.Lib" protected
string IG.Lib.RuntimeCompilerOld._runnableClass = "TestClass" protected
string IG.Lib.RuntimeCompilerOld._runnableInterface = "IRunnableOld" protected
string IG.Lib.RuntimeCompilerOld._runnableFunction = "Run" protected
string IG.Lib.RuntimeCompilerOld._libraryOriginalName = "TestClass" protected
int IG.Lib.RuntimeCompilerOld._idLibraryName = 0 protected
string IG.Lib.RuntimeCompilerOld._libraryFileName = "TestClass.dll" protected
string IG.Lib.RuntimeCompilerOld._executableDirectory = null private
bool IG.Lib.RuntimeCompilerOld._readyToRun = false protected
Property Documentation
Logger IG.Lib.RuntimeCompilerOld.Logger get
string IG.Lib.RuntimeCompilerOld.CodeBase get
Gets code base (a template code for compiling) where names of classes, methods etc. are properly set.
Referenced by IG.Forms.CompilerFormOld.btnLoad_Click().
string IG.Lib.RuntimeCompilerOld.Code get set
Gets or sets code to be compiled. Get: If not assigned explicitly then CodeBase is taken.
Referenced by IG.Forms.CompilerFormOld.btnCompile_Click().
string IG.Lib.RuntimeCompilerOld.RunnableNamespace get protected set
string IG.Lib.RuntimeCompilerOld.RunnableInterface get protected set
string IG.Lib.RuntimeCompilerOld.RunnableClass get protected set
string IG.Lib.RuntimeCompilerOld.RunnableFullClass get
Referenced by IG.Forms.CompilerFormOld.btnExecute_Click().
string IG.Lib.RuntimeCompilerOld.RunnableFunction get protected set
string IG.Lib.RuntimeCompilerOld.LibraryDirectory get
Returns directory where library will be compiled, which will be the directory of the executable that started the application.
string IG.Lib.RuntimeCompilerOld.LibraryPath get
Path to the dll where code is compiled. We take the directory where executable is located.
Referenced by IG.Forms.CompilerFormOld.btnExecute_Click().
bool IG.Lib.RuntimeCompilerOld.ReadyToRun get set
Wheather the compiled class' method is ready to run.
Referenced by IG.Forms.CompilerFormOld.btnCompile_Click(), and IG.Forms.CompilerFormOld.CheckReadyToRun().
The documentation for this class was generated from the following file:
igtest/test_iglib_tmp_CSharpScripter/old_csharpscripter/OldRuntimeCompiler.cs