IGLib: Test.SymmetricMatrixTest Class Reference
Test.SymmetricMatrixTest Class Reference
Public Member Functions
void SymmetricMatrixAccess ()
void SymmetricMatrixArithmetic ()
void SymmetricHilbertMatrixInverse ()
void SymmetricRandomMatrixInverse ()
void SymmetricRandomMatrixEigenvectors ()
void SymmetricHilbertMatrixEigenvalues ()
void SymmetricMatrixDecomposition ()
void SymmetricRandomMatrixCholeskyDecomposition ()
void CatalanHankelMatrixDeterminant ()
void SymmetricMatrixNorms ()
Properties
TestContext TestContext [get, set]
Static Private Member Functions
static SymmetricMatrix CreateSymmetricRandomMatrix (int n, int seed)
Private Attributes
TestContext testContextInstance
Member Function Documentation
static SymmetricMatrix Test.SymmetricMatrixTest.CreateSymmetricRandomMatrix (int n, int seed) inline static private
Referenced by Test.SymmetricMatrixTest.SymmetricMatrixAccess(), Test.SymmetricMatrixTest.SymmetricMatrixArithmetic(), Test.SymmetricMatrixTest.SymmetricMatrixNorms(), and Test.SymmetricMatrixTest.SymmetricRandomMatrixEigenvectors().
void Test.SymmetricMatrixTest.SymmetricMatrixAccess () inline
References Meta.Numerics.Matrices.AnyRectangularMatrix.Column(), Meta.Numerics.Matrices.SymmetricMatrix.Copy(), Test.SymmetricMatrixTest.CreateSymmetricRandomMatrix(), Meta.Numerics.Matrices.SymmetricMatrix.Dimension, Meta.Numerics.Matrices.VectorBase.Dimension, and Meta.Numerics.Matrices.AnyRectangularMatrix.Row().
void Test.SymmetricMatrixTest.SymmetricMatrixArithmetic () inline
References Test.SymmetricMatrixTest.CreateSymmetricRandomMatrix().
void Test.SymmetricMatrixTest.SymmetricHilbertMatrixInverse () inline
References Meta.Numerics.Matrices.SymmetricMatrix.Inverse().
void Test.SymmetricMatrixTest.SymmetricRandomMatrixInverse () inline
References Meta.Numerics.Matrices.SymmetricMatrix.Inverse().
void Test.SymmetricMatrixTest.SymmetricRandomMatrixEigenvectors () inline
References Test.SymmetricMatrixTest.CreateSymmetricRandomMatrix(), Meta.Numerics.Matrices.RealEigensystem.Dimension, Meta.Numerics.Matrices.SymmetricMatrix.Dimension, Meta.Numerics.Matrices.SymmetricMatrix.Eigensystem(), Meta.Numerics.Matrices.RealEigensystem.Eigenvalue(), Meta.Numerics.Matrices.RealEigensystem.Eigenvector(), Meta.Numerics.Matrices.SymmetricMatrix.Trace(), Meta.Numerics.Matrices.RealEigensystem.TransformMatrix(), and Meta.Numerics.Matrices.SquareMatrix.Transpose().
void Test.SymmetricMatrixTest.SymmetricHilbertMatrixEigenvalues () inline
References Meta.Numerics.Matrices.SymmetricMatrix.Eigenvalues(), and Meta.Numerics.Matrices.SymmetricMatrix.Trace().
void Test.SymmetricMatrixTest.SymmetricMatrixDecomposition () inline
References Meta.Numerics.Matrices.SymmetricMatrix.CholeskyDecomposition(), Meta.Numerics.Matrices.CholeskyDecomposition.Dimension, and Meta.Numerics.Matrices.CholeskyDecomposition.Inverse().
void Test.SymmetricMatrixTest.SymmetricRandomMatrixCholeskyDecomposition () inline
References Meta.Numerics.Matrices.SymmetricMatrix.CholeskyDecomposition(), and Meta.Numerics.Matrices.ColumnVector.Transpose().
void Test.SymmetricMatrixTest.CatalanHankelMatrixDeterminant () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient(), Meta.Numerics.Matrices.SymmetricMatrix.CholeskyDecomposition(), and Meta.Numerics.Matrices.CholeskyDecomposition.Determinant().
void Test.SymmetricMatrixTest.SymmetricMatrixNorms () inline
References Test.SymmetricMatrixTest.CreateSymmetricRandomMatrix(), Meta.Numerics.Matrices.AnyRectangularMatrix.FrobeniusNorm(), Meta.Numerics.Matrices.AnyRectangularMatrix.InfinityNorm(), and Meta.Numerics.Matrices.AnyRectangularMatrix.OneNorm().
Member Data Documentation
TestContext Test.SymmetricMatrixTest.testContextInstance private
Property Documentation
TestContext Test.SymmetricMatrixTest.TestContext get set
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/SymmetricMatrixTest.cs