IGLib: alglib.clustering Class Reference
alglib.clustering Class Reference
Classes
class ahcreport
class clusterizerstate
class kmeansreport
Static Public Member Functions
static void clusterizercreate (clusterizerstate s)
static void clusterizersetpoints (clusterizerstate s, double[,] xy, int npoints, int nfeatures, int disttype)
static void clusterizersetdistances (clusterizerstate s, double[,] d, int npoints, bool isupper)
static void clusterizersetahcalgo (clusterizerstate s, int algo)
static void clusterizersetkmeanslimits (clusterizerstate s, int restarts, int maxits)
static void clusterizerrunahc (clusterizerstate s, ahcreport rep)
static void _pexec_clusterizerrunahc (clusterizerstate s, ahcreport rep)
static void clusterizerrunkmeans (clusterizerstate s, int k, kmeansreport rep)
static void clusterizergetdistances (double[,] xy, int npoints, int nfeatures, int disttype, ref double[,] d)
static void _pexec_clusterizergetdistances (double[,] xy, int npoints, int nfeatures, int disttype, ref double[,] d)
static void clusterizergetkclusters (ahcreport rep, int k, ref int[] cidx, ref int[] cz)
static void clusterizerseparatedbydist (ahcreport rep, double r, ref int k, ref int[] cidx, ref int[] cz)
static void clusterizerseparatedbycorr (ahcreport rep, double r, ref int k, ref int[] cidx, ref int[] cz)
static void kmeansgenerateinternal (double[,] xy, int npoints, int nvars, int k, int maxits, int restarts, ref int info, ref double[,] ccol, bool needccol, ref double[,] crow, bool needcrow, ref int[] xyc)
Public Attributes
const int parallelcomplexity = 200000
Static Private Member Functions
static bool selectcenterpp (double[,] xy, int npoints, int nvars, ref double[,] centers, ref bool[] busycenters, int ccnt, ref double[] d2, ref double[] p, ref double[] tmp)
static void clusterizerrunahcinternal (clusterizerstate s, ref double[,] d, ahcreport rep)
static void evaluatedistancematrixrec (double[,] xy, int nfeatures, int disttype, double[,] d, int i0, int i1, int j0, int j1)
Member Function Documentation
static void alglib.clustering.clusterizercreate (clusterizerstate s) inline static
References alglib.clustering.clusterizerstate.ahcalgo, alglib.clustering.clusterizerstate.disttype, alglib.clustering.clusterizerstate.kmeansmaxits, alglib.clustering.clusterizerstate.kmeansrestarts, alglib.clustering.clusterizerstate.nfeatures, and alglib.clustering.clusterizerstate.npoints.
Referenced by alglib.testclusteringunit.advancedahctests(), alglib.testclusteringunit.basicahctests(), alglib.clusterizercreate(), alglib.testclusteringunit.kmeansinfinitelooptest(), alglib.testclusteringunit.kmeansrestartstest(), and alglib.testclusteringunit.kmeanssimpletest1().
static void alglib.clustering.clusterizersetpoints (clusterizerstate s, double xy[,], int npoints, int nfeatures, int disttype) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), alglib.clustering.clusterizerstate.disttype, alglib.clustering.clusterizerstate.nfeatures, alglib.clustering.clusterizerstate.npoints, alglib.apserv.rmatrixsetlengthatleast(), and alglib.clustering.clusterizerstate.xy.
Referenced by alglib.testclusteringunit.advancedahctests(), alglib.testclusteringunit.basicahctests(), alglib.clusterizersetpoints(), alglib.testclusteringunit.kmeansinfinitelooptest(), alglib.testclusteringunit.kmeansrestartstest(), and alglib.testclusteringunit.kmeanssimpletest1().
static void alglib.clustering.clusterizersetdistances (clusterizerstate s, double d[,], int npoints, bool isupper) inline static
References alglib.ap.assert(), alglib.clustering.clusterizerstate.d, alglib.clustering.clusterizerstate.disttype, alglib.math.isfinite(), alglib.clustering.clusterizerstate.nfeatures, alglib.clustering.clusterizerstate.npoints, and alglib.apserv.rmatrixsetlengthatleast().
Referenced by alglib.testclusteringunit.advancedahctests(), alglib.testclusteringunit.basicahctests(), and alglib.clusterizersetdistances().
static void alglib.clustering.clusterizersetahcalgo (clusterizerstate s, int algo) inline static
References alglib.clustering.clusterizerstate.ahcalgo, and alglib.ap.assert().
Referenced by alglib.testclusteringunit.advancedahctests(), alglib.testclusteringunit.basicahctests(), and alglib.clusterizersetahcalgo().
static void alglib.clustering.clusterizersetkmeanslimits (clusterizerstate s, int restarts, int maxits) inline static
References alglib.ap.assert(), alglib.clustering.clusterizerstate.kmeansmaxits, and alglib.clustering.clusterizerstate.kmeansrestarts.
Referenced by alglib.clusterizersetkmeanslimits(), alglib.testclusteringunit.kmeansinfinitelooptest(), alglib.testclusteringunit.kmeansrestartstest(), and alglib.testclusteringunit.kmeanssimpletest1().
static void alglib.clustering.clusterizerrunahc (clusterizerstate s, ahcreport rep) inline static
References alglib.clustering.clusterizergetdistances(), alglib.clustering.clusterizerrunahcinternal(), alglib.clustering.clusterizerstate.d, alglib.clustering.clusterizerstate.disttype, alglib.clustering.ahcreport.mergedist, alglib.clustering.clusterizerstate.nfeatures, alglib.clustering.clusterizerstate.npoints, alglib.clustering.ahcreport.npoints, alglib.clustering.ahcreport.p, alglib.clustering.ahcreport.pm, alglib.clustering.ahcreport.pz, alglib.clustering.clusterizerstate.xy, and alglib.clustering.ahcreport.z.
Referenced by alglib.clustering._pexec_clusterizerrunahc(), alglib.testclusteringunit.advancedahctests(), alglib.testclusteringunit.basicahctests(), and alglib.clusterizerrunahc().
static void alglib.clustering._pexec_clusterizerrunahc (clusterizerstate s, ahcreport rep) inline static
References alglib.clustering.clusterizerrunahc().
Referenced by alglib.smp_clusterizerrunahc().
static void alglib.clustering.clusterizerrunkmeans (clusterizerstate s, int k, kmeansreport rep) inline static
References alglib.ap.assert(), alglib.clustering.kmeansreport.c, alglib.clustering.kmeansreport.cidx, alglib.clustering.clusterizerstate.disttype, alglib.clustering.kmeansreport.k, alglib.clustering.kmeansgenerateinternal(), alglib.clustering.clusterizerstate.kmeansmaxits, alglib.clustering.clusterizerstate.kmeansrestarts, alglib.clustering.clusterizerstate.nfeatures, alglib.clustering.kmeansreport.nfeatures, alglib.clustering.clusterizerstate.npoints, alglib.clustering.kmeansreport.npoints, alglib.clustering.kmeansreport.terminationtype, and alglib.clustering.clusterizerstate.xy.
Referenced by alglib.clusterizerrunkmeans(), alglib.testclusteringunit.kmeansinfinitelooptest(), alglib.testclusteringunit.kmeansrestartstest(), and alglib.testclusteringunit.kmeanssimpletest1().
static void alglib.clustering.clusterizergetdistances (double xy[,], int npoints, int nfeatures, int disttype, ref double d[,]) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), alglib.clustering.evaluatedistancematrixrec(), alglib.basestat.rankdatacentered(), alglib.ablas.rmatrixcopy(), alglib.ablas.rmatrixenforcesymmetricity(), and alglib.ablas.rmatrixsyrk().
Referenced by alglib.clustering._pexec_clusterizergetdistances(), alglib.testclusteringunit.advancedahctests(), alglib.clusterizergetdistances(), and alglib.clustering.clusterizerrunahc().
static void alglib.clustering._pexec_clusterizergetdistances (double xy[,], int npoints, int nfeatures, int disttype, ref double d[,]) inline static
References alglib.clustering.clusterizergetdistances().
Referenced by alglib.smp_clusterizergetdistances().
static void alglib.clustering.clusterizergetkclusters (ahcreport rep, int k, ref int[] cidx, ref int[] cz) inline static
References alglib.ap.assert(), and alglib.clustering.ahcreport.npoints.
Referenced by alglib.testclusteringunit.basicahctests(), alglib.clusterizergetkclusters(), and alglib.testclusteringunit.errorsinmerges().
static void alglib.clustering.clusterizerseparatedbydist (ahcreport rep, double r, ref int k, ref int[] cidx, ref int[] cz) inline static
Referenced by alglib.testclusteringunit.basicahctests(), and alglib.clusterizerseparatedbydist().
static void alglib.clustering.clusterizerseparatedbycorr (ahcreport rep, double r, ref int k, ref int[] cidx, ref int[] cz) inline static
Referenced by alglib.testclusteringunit.basicahctests(), and alglib.clusterizerseparatedbycorr().
static void alglib.clustering.kmeansgenerateinternal (double xy[,], int npoints, int nvars, int k, int maxits, int restarts, ref int info, ref double ccol[,], bool needccol, ref double crow[,], bool needcrow, ref int[] xyc) inline static
Referenced by alglib.clustering.clusterizerrunkmeans().
static bool alglib.clustering.selectcenterpp (double xy[,], int npoints, int nvars, ref double centers[,], ref bool[] busycenters, int ccnt, ref double[] d2, ref double[] p, ref double[] tmp) inline static private
static void alglib.clustering.clusterizerrunahcinternal (clusterizerstate s, ref double d[,], ahcreport rep) inline static private
Referenced by alglib.clustering.clusterizerrunahc().
static void alglib.clustering.evaluatedistancematrixrec (double xy[,], int nfeatures, int disttype, double d[,], int i0, int i1, int j0, int j1) inline static private
Referenced by alglib.clustering.clusterizergetdistances().
Member Data Documentation
const int alglib.clustering.parallelcomplexity = 200000
The documentation for this class was generated from the following file:
igtest/numerics/alglib_0.8.2/src/dataanalysis.cs