IGLib: Meta.Numerics.Statistics.ContingencyTable Class Reference
Meta.Numerics.Statistics.ContingencyTable Class Reference
Represents a contingency table.
Public Member Functions
ContingencyTable (int rows, int columns)
Initializes a new contingency table.
ContingencyTable (int[,] data)
Initializes a new contingency table with the given data set.
void Increment (int r, int c)
Increments the count in the specifed cel.
virtual int RowTotal (int r)
Gets the total counts in the specified row.
virtual int ColumnTotal (int c)
Gets the total counts in the specified column.
virtual UncertainValue Probability (int r, int c)
Estimates the probability of the given cell in the underlying population.
virtual UncertainValue ProbabilityOfRow (int r)
Estimates the marginal probility of the given row in the underlying population.
virtual UncertainValue ProbabilityOfColumn (int c)
Estimates the marginal probility of the given column in the underlying population.
virtual UncertainValue ProbabilityOfRowConditionalOnColumn (int r, int c)
Estimates the probability of the given row, conditional on the given column.
virtual UncertainValue ProbabilityOfColumnConditionalOnRow (int c, int r)
Estimates the probability of the given row, conditional on the given column.
virtual TestResult PearsonChiSquaredTest ()
Performs a Pearson &#x3C7;2 test for correlation in the table.
Properties
string Name [get, set]
Gets or sets the name of the table.
int this[int r, int c] [get, set]
Gets or sets the count in the specified cell.
virtual int RowCount [get]
Gets the number of rows in the table.
virtual int ColumnCount [get]
Gets the number of columns in the table.
virtual int Total [get]
Gets the total counts in the table.
Private Attributes
string name
int rows
int cols
int[,] counts
int[] rCounts
int[] cCounts
int tCounts
Detailed Description
Represents a contingency table.
Imagine a controlled experiment in which each data point consists of two category values. For example, a measurement of a driver's car and his nationality, or a person's sex and employment status. Such experiments are typically undertaken to determine what correlation exists between the categories.
See also
BinaryContingencyTable
Constructor & Destructor Documentation
Meta.Numerics.Statistics.ContingencyTable.ContingencyTable (int rows, int columns) inline
Initializes a new contingency table.
Parameters
rows The number of rows, which must be positive.
columns The number of columns, which must be positive.
Meta.Numerics.Statistics.ContingencyTable.ContingencyTable (int data[,]) inline
Initializes a new contingency table with the given data set.
Parameters
data A (zero-based) matrix of contingency table entries.
Member Function Documentation
void Meta.Numerics.Statistics.ContingencyTable.Increment (int r, int c) inline
Increments the count in the specifed cel.
Parameters
r The (zero-based) row index.
c The (zero-based) column index.
Referenced by Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties().
virtual int Meta.Numerics.Statistics.ContingencyTable.RowTotal (int r) inline virtual
Gets the total counts in the specified row.
Parameters
r The (zero-based) row index.
Returns
The sum of all counts in the specified row.
Referenced by Test.BinaryContingencyTableTest.BinaryContingencyNullTest(), Test.BinaryContingencyTableTest.BinaryContingencyTest(), and Test.ContingencyTableTest.ContingencyTableOperations().
virtual int Meta.Numerics.Statistics.ContingencyTable.ColumnTotal (int c) inline virtual
Gets the total counts in the specified column.
Parameters
c The (zero-based) column index.
Returns
The sum of all counts in the specified column.
Referenced by Test.BinaryContingencyTableTest.BinaryContingencyNullTest(), Test.BinaryContingencyTableTest.BinaryContingencyTest(), and Test.ContingencyTableTest.ContingencyTableOperations().
virtual UncertainValue Meta.Numerics.Statistics.ContingencyTable.Probability (int r, int c) inline virtual
Estimates the probability of the given cell in the underlying population.
Parameters
r The (zero-based) row index.
c The (zero-based) column index.
Returns
The probability for a random event to occur inthe given cell.
Referenced by Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties().
virtual UncertainValue Meta.Numerics.Statistics.ContingencyTable.ProbabilityOfRow (int r) inline virtual
Estimates the marginal probility of the given row in the underlying population.
Parameters
r The (zero-based) row index.
Returns
The probability for a random event to occur in the given row.
Referenced by Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties().
virtual UncertainValue Meta.Numerics.Statistics.ContingencyTable.ProbabilityOfColumn (int c) inline virtual
Estimates the marginal probility of the given column in the underlying population.
Parameters
c The (zero-based) column index.
Returns
The probability for a random envent to occur in the given column.
Referenced by Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties().
virtual UncertainValue Meta.Numerics.Statistics.ContingencyTable.ProbabilityOfRowConditionalOnColumn (int r, int c) inline virtual
Estimates the probability of the given row, conditional on the given column.
Parameters
r The (zero-based) row index.
c The (zero-based) column index.
Returns
The probability for a random event to occur in the given row, if it appears in the given column.
Referenced by Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties().
virtual UncertainValue Meta.Numerics.Statistics.ContingencyTable.ProbabilityOfColumnConditionalOnRow (int c, int r) inline virtual
Estimates the probability of the given row, conditional on the given column.
Parameters
r The (zero-based) row index.
c The (zero-based) column index.
Returns
The probability for a random event to occur in the given row, if it appears in the given column.
Referenced by Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties().
virtual TestResult Meta.Numerics.Statistics.ContingencyTable.PearsonChiSquaredTest () inline virtual
Performs a Pearson &#x3C7;2 test for correlation in the table.
Returns
The result of the test. The test statistic is &#x3C7;2 and its likelyhood under the null hypothesis is the (right) probability to obtain a value as large or larger.
The Pearson Pearson &#x3C7;2 test tests for correlation between the row and column values. If row and column values are uncorrelated, then the expected number of counts in a table entry is simply proportional to the totals for its row and column. If that number is large for all entries, then the central limit theorem suggests that the actual number of counts will be distributed normally with mean equal to the expected value and standard deviation equal to its square root. The &#x3C7;2 statistic measures the departure of the actual table from this expectation in the uncorrelated case, and under this null hypothesis its distribution is known. Having calculated &#x3C7;2, then, we can compute just how unlikely it was to obtain a value as large or larger than the one obtained.
In cases where either the actual or expected counts for some entries are small or zero, the assumptions of the Pearson &#x3C7;2 test are violated and it should not be used. For 2 X 2 experiments, the BinaryContingencyTable.FisherExactTest is a viable alternative in these cases.
See also
ChiSquaredDistribution
Referenced by Test.BinaryContingencyTableTest.BinaryContingencyTest().
Member Data Documentation
string Meta.Numerics.Statistics.ContingencyTable.name private
int Meta.Numerics.Statistics.ContingencyTable.rows private
int Meta.Numerics.Statistics.ContingencyTable.cols private
int [,] Meta.Numerics.Statistics.ContingencyTable.counts private
int [] Meta.Numerics.Statistics.ContingencyTable.rCounts private
int [] Meta.Numerics.Statistics.ContingencyTable.cCounts private
int Meta.Numerics.Statistics.ContingencyTable.tCounts private
Property Documentation
string Meta.Numerics.Statistics.ContingencyTable.Name get set
Gets or sets the name of the table.
int Meta.Numerics.Statistics.ContingencyTable.this[int r, int c] get set
Gets or sets the count in the specified cell.
Parameters
r The (zero-based) row index.
c The (zero-based) column index.
Returns
The count in the specified cell.
virtual int Meta.Numerics.Statistics.ContingencyTable.RowCount get
Gets the number of rows in the table.
Referenced by Test.ContingencyTableTest.ContingencyTableOperations().
virtual int Meta.Numerics.Statistics.ContingencyTable.ColumnCount get
Gets the number of columns in the table.
Referenced by Test.ContingencyTableTest.ContingencyTableOperations().
virtual int Meta.Numerics.Statistics.ContingencyTable.Total get
Gets the total counts in the table.
Referenced by Test.BinaryContingencyTableTest.BinaryContingencyNullTest(), Test.BinaryContingencyTableTest.BinaryContingencyTest(), Test.ContingencyTableTest.ContingencyTableOperations(), and Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/ContingencyTable.cs