IGLib: alglib.igammaf Class Reference
alglib.igammaf Class Reference
Static Public Member Functions
static double incompletegamma (double a, double x)
static double incompletegammac (double a, double x)
static double invincompletegammac (double a, double y0)
static double incompletegamma (double a, double x)
static double incompletegammac (double a, double x)
static double invincompletegammac (double a, double y0)
Member Function Documentation
static double alglib.igammaf.incompletegamma (double a, double x) inline static
References alglib.igammaf.incompletegammac(), and alglib.gammafunc.lngamma().
Referenced by alglib.chisquaredistr.chisquaredistribution(), alglib.incompletegamma(), alglib.igammaf.incompletegammac(), and alglib.poissondistr.poissoncdistribution().
static double alglib.igammaf.incompletegammac (double a, double x) inline static
References alglib.igammaf.incompletegamma(), and alglib.gammafunc.lngamma().
Referenced by alglib.chisquaredistr.chisquarecdistribution(), alglib.igammaf.incompletegamma(), alglib.incompletegammac(), alglib.igammaf.invincompletegammac(), alglib.linreg.lrlines(), and alglib.poissondistr.poissondistribution().
static double alglib.igammaf.invincompletegammac (double a, double y0) inline static
References alglib.igammaf.incompletegammac(), alglib.normaldistr.invnormaldistribution(), and alglib.gammafunc.lngamma().
Referenced by alglib.chisquaredistr.invchisquaredistribution(), alglib.invincompletegammac(), and alglib.poissondistr.invpoissondistribution().
static double alglib.igammaf.incompletegamma (double a, double x) inline static
References alglib.igammaf.incompletegammac(), and alglib.gammafunc.lngamma().
static double alglib.igammaf.incompletegammac (double a, double x) inline static
References alglib.igammaf.incompletegamma(), and alglib.gammafunc.lngamma().
static double alglib.igammaf.invincompletegammac (double a, double y0) inline static
References alglib.igammaf.incompletegammac(), alglib.normaldistr.invnormaldistribution(), and alglib.gammafunc.lngamma().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/specialfunctions.cs