IGLib: alglib.testnearestneighborunit Class Reference
alglib.testnearestneighborunit Class Reference
Static Public Member Functions
static bool testnearestneighbor (bool silent)
static bool testnearestneighbor (bool silent)
static bool _pexec_testnearestneighbor (bool silent)
Static Private Member Functions
static void unset2d (ref complex[,] a)
static void unset1d (ref double[] a)
static bool kdtresultsdifferent (double[,] refxy, int ntotal, double[,] qx, double[,] qxy, int[] qt, int n, int nx, int ny)
static double vnorm (double[] x, int n, int normtype)
static void testkdtuniform (double[,] xy, int n, int nx, int ny, int normtype, ref bool kdterrors)
static void testkdtreeserialization (ref bool err)
static bool testspecialcases ()
static void unset2d (ref complex[,] a)
static void unset1d (ref double[] a)
static bool kdtresultsdifferent (double[,] refxy, int ntotal, double[,] qx, double[,] qxy, int[] qt, int n, int nx, int ny)
static double vnorm (double[] x, int n, int normtype)
static void testkdtuniform (double[,] xy, int n, int nx, int ny, int normtype, ref bool kdterrors)
static void testkdtreeserialization (ref bool err)
static bool testspecialcases ()
Member Function Documentation
static bool alglib.testnearestneighborunit.testnearestneighbor (bool silent) inline static
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.testnearestneighborunit.testkdtreeserialization(), alglib.testnearestneighborunit.testkdtuniform(), and alglib.testnearestneighborunit.testspecialcases().
Referenced by alglib.testnearestneighborunit._pexec_testnearestneighbor(), and _Test.Main().
static void alglib.testnearestneighborunit.unset2d (ref complex a[,]) inline static private
References alglib.math.randomreal().
static void alglib.testnearestneighborunit.unset1d (ref double[] a) inline static private
References alglib.math.randomreal().
static bool alglib.testnearestneighborunit.kdtresultsdifferent (double refxy[,], int ntotal, double qx[,], double qxy[,], int[] qt, int n, int nx, int ny) inline static private
Referenced by alglib.testnearestneighborunit.testkdtuniform().
static double alglib.testnearestneighborunit.vnorm (double[] x, int n, int normtype) inline static private
References alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testnearestneighborunit.testkdtuniform().
static void alglib.testnearestneighborunit.testkdtuniform (double xy[,], int n, int nx, int ny, int normtype, ref bool kdterrors) inline static private
References alglib.ap.assert(), alglib.nearestneighbor.kdtreebuild(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.nearestneighbor.kdtreequeryaknn(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryresultsdistances(), alglib.nearestneighbor.kdtreequeryresultsdistancesi(), alglib.nearestneighbor.kdtreequeryresultstags(), alglib.nearestneighbor.kdtreequeryresultstagsi(), alglib.nearestneighbor.kdtreequeryresultsx(), alglib.nearestneighbor.kdtreequeryresultsxi(), alglib.nearestneighbor.kdtreequeryresultsxy(), alglib.nearestneighbor.kdtreequeryresultsxyi(), alglib.nearestneighbor.kdtreequeryrnn(), alglib.testnearestneighborunit.kdtresultsdifferent(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), and alglib.testnearestneighborunit.vnorm().
Referenced by alglib.testnearestneighborunit.testnearestneighbor().
static void alglib.testnearestneighborunit.testkdtreeserialization (ref bool err) inline static private
References alglib.serializer.alloc_start(), alglib.serializer.get_string(), alglib.nearestneighbor.kdtreealloc(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryresultstags(), alglib.nearestneighbor.kdtreequeryresultsxy(), alglib.nearestneighbor.kdtreeserialize(), alglib.nearestneighbor.kdtreeunserialize(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.serializer.sstart_str(), alglib.serializer.stop(), and alglib.serializer.ustart_str().
Referenced by alglib.testnearestneighborunit.testnearestneighbor().
static bool alglib.testnearestneighborunit.testspecialcases () inline static private
References alglib.nearestneighbor.kdtreebuild(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.nearestneighbor.kdtreequeryaknn(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryrnn(), and alglib.math.randomreal().
Referenced by alglib.testnearestneighborunit.testnearestneighbor().
static bool alglib.testnearestneighborunit.testnearestneighbor (bool silent) inline static
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.testnearestneighborunit.testkdtreeserialization(), alglib.testnearestneighborunit.testkdtuniform(), and alglib.testnearestneighborunit.testspecialcases().
static bool alglib.testnearestneighborunit._pexec_testnearestneighbor (bool silent) inline static
References alglib.testnearestneighborunit.testnearestneighbor().
Referenced by _Test.Main().
static void alglib.testnearestneighborunit.unset2d (ref complex a[,]) inline static private
References alglib.math.randomreal().
static void alglib.testnearestneighborunit.unset1d (ref double[] a) inline static private
References alglib.math.randomreal().
static bool alglib.testnearestneighborunit.kdtresultsdifferent (double refxy[,], int ntotal, double qx[,], double qxy[,], int[] qt, int n, int nx, int ny) inline static private
static double alglib.testnearestneighborunit.vnorm (double[] x, int n, int normtype) inline static private
References alglib.math.randomreal(), and alglib.math.sqr().
static void alglib.testnearestneighborunit.testkdtuniform (double xy[,], int n, int nx, int ny, int normtype, ref bool kdterrors) inline static private
References alglib.ap.assert(), alglib.nearestneighbor.kdtreebuild(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.nearestneighbor.kdtreequeryaknn(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryresultsdistances(), alglib.nearestneighbor.kdtreequeryresultsdistancesi(), alglib.nearestneighbor.kdtreequeryresultstags(), alglib.nearestneighbor.kdtreequeryresultstagsi(), alglib.nearestneighbor.kdtreequeryresultsx(), alglib.nearestneighbor.kdtreequeryresultsxi(), alglib.nearestneighbor.kdtreequeryresultsxy(), alglib.nearestneighbor.kdtreequeryresultsxyi(), alglib.nearestneighbor.kdtreequeryrnn(), alglib.testnearestneighborunit.kdtresultsdifferent(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), and alglib.testnearestneighborunit.vnorm().
static void alglib.testnearestneighborunit.testkdtreeserialization (ref bool err) inline static private
References alglib.serializer.alloc_start(), alglib.serializer.get_string(), alglib.nearestneighbor.kdtreealloc(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryresultstags(), alglib.nearestneighbor.kdtreequeryresultsxy(), alglib.nearestneighbor.kdtreeserialize(), alglib.nearestneighbor.kdtreeunserialize(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.serializer.sstart_str(), alglib.serializer.stop(), and alglib.serializer.ustart_str().
static bool alglib.testnearestneighborunit.testspecialcases () inline static private
References alglib.nearestneighbor.kdtreebuild(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.nearestneighbor.kdtreequeryaknn(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryrnn(), and alglib.math.randomreal().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs