IGLib: CShell.Framework.Services.IShell Interface Reference
CShell.Framework.Services.IShell Interface Reference
Public Member Functions
void ShowTool (ITool model)
void OpenDocument (IDocument model)
void CloseDocument (IDocument document)
void ActivateDocument (IDocument document)
void Opened (string[] args)
void Close ()
void SaveLayout (XmlWriter xmlWriter)
void LoadLayout (XmlReader xmlReader)
void ShowTool (ITool model)
void OpenDocument (IDocument model)
void CloseDocument (IDocument document)
void ActivateDocument (IDocument document)
void Opened (string[] args)
void Close ()
void SaveLayout (XmlWriter xmlWriter)
void LoadLayout (XmlReader xmlReader)
Properties
string Title [get, set]
ImageSource Icon [get, set]
IMenu MainMenu [get]
IToolBar ToolBar [get]
IStatusBar StatusBar [get]
IScreen ActiveItem [get]
IEnumerable< IDocument > Documents [get]
IEnumerable< ITool > Tools [get]
Member Function Documentation
void CShell.Framework.Services.IShell.ShowTool (ITool model)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
Referenced by CShell.Framework.Results.ShowToolResult< TTool >.Execute().
void CShell.Framework.Services.IShell.OpenDocument (IDocument model)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
Referenced by CShell.Framework.Results.OpenDocumentResult.Execute().
void CShell.Framework.Services.IShell.CloseDocument (IDocument document)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
void CShell.Framework.Services.IShell.ActivateDocument (IDocument document)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
void CShell.Framework.Services.IShell.Opened (string[] args)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
Referenced by CShell.AppBootstrapper.OnStartup().
void CShell.Framework.Services.IShell.Close ()
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
Referenced by CShell.Modules.Shell.ViewModels.MainMenuViewModel.Exit().
void CShell.Framework.Services.IShell.SaveLayout (XmlWriter xmlWriter)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
Referenced by CShell.Workspace.Save().
void CShell.Framework.Services.IShell.LoadLayout (XmlReader xmlReader)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
Referenced by CShell.Workspace.Load().
void CShell.Framework.Services.IShell.ShowTool (ITool model)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
void CShell.Framework.Services.IShell.OpenDocument (IDocument model)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
void CShell.Framework.Services.IShell.CloseDocument (IDocument document)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
void CShell.Framework.Services.IShell.ActivateDocument (IDocument document)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
void CShell.Framework.Services.IShell.Opened (string[] args)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
void CShell.Framework.Services.IShell.Close ()
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
void CShell.Framework.Services.IShell.SaveLayout (XmlWriter xmlWriter)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
void CShell.Framework.Services.IShell.LoadLayout (XmlReader xmlReader)
Implemented in CShell.Modules.Shell.ViewModels.ShellViewModel, and CShell.Modules.Shell.ViewModels.ShellViewModel.
Property Documentation
string CShell.Framework.Services.IShell.Title get set
ImageSource CShell.Framework.Services.IShell.Icon get set
IMenu CShell.Framework.Services.IShell.MainMenu get
IToolBar CShell.Framework.Services.IShell.ToolBar get
IStatusBar CShell.Framework.Services.IShell.StatusBar get
IScreen CShell.Framework.Services.IShell.ActiveItem get
IEnumerable< IDocument > CShell.Framework.Services.IShell.Documents get
IEnumerable< ITool > CShell.Framework.Services.IShell.Tools get
The documentation for this interface was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Services/IShell.cs