IGLib: NUnit.Framework.Internal.TestResultTests Class Reference
NUnit.Framework.Internal.TestResultTests Class Reference abstract
Summary description for TestResultTests.
Classes
class DummySuite
Public Member Functions
void SetUp ()
void TestResultBasicInfo ()
void SuiteResultBasicInfo ()
void TestResultXmlNodeBasicInfo ()
void SuiteResultXmlNodeBasicInfo ()
Protected Member Functions
abstract void SimulateTestRun ()
Protected Attributes
TestResult testResult
TestResult suiteResult
TestMethod test
double expectedDuration
DateTime expectedStart
DateTime expectedEnd
Properties
virtual ResultState ResultState [get]
virtual string ReasonNodeName [get]
Detailed Description
Summary description for TestResultTests.
Member Function Documentation
void NUnit.Framework.Internal.TestResultTests.SetUp () inline
References NUnit.Framework.Interfaces.IPropertyBag.Add(), NUnit.Framework.Internal.PropertyNames.Category, NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Internal.TestMethod.MakeTestResult(), NUnit.Framework.Internal.TestSuite.MakeTestResult(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Interfaces.IPropertyBag.Set().
void NUnit.Framework.Internal.TestResultTests.TestResultBasicInfo () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.TestResult.FullName, and NUnit.Framework.Internal.TestResult.Name.
void NUnit.Framework.Internal.TestResultTests.SuiteResultBasicInfo () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.TestResult.FullName, and NUnit.Framework.Internal.TestResult.Name.
void NUnit.Framework.Internal.TestResultTests.TestResultXmlNodeBasicInfo () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.TNode.Attributes, NUnit.Framework.Interfaces.TNode.Name, NUnit.Framework.Assert.NotNull(), NUnit.Framework.Interfaces.TNode.SelectNodes(), NUnit.Framework.Interfaces.TNode.SelectSingleNode(), and NUnit.Framework.Internal.TestResult.ToXml().
void NUnit.Framework.Internal.TestResultTests.SuiteResultXmlNodeBasicInfo () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.TNode.Attributes, NUnit.Framework.Interfaces.TNode.Name, NUnit.Framework.Assert.NotNull(), NUnit.Framework.Interfaces.TNode.SelectSingleNode(), and NUnit.Framework.Internal.TestResult.ToXml().
abstract void NUnit.Framework.Internal.TestResultTests.SimulateTestRun () protected pure virtual
Implemented in NUnit.Framework.Internal.MinimumDurationResultTests, NUnit.Framework.Internal.MixedResultTests, NUnit.Framework.Internal.InconclusiveResultTests, NUnit.Framework.Internal.FailedResultTests, NUnit.Framework.Internal.NotRunnableResultTests, NUnit.Framework.Internal.IgnoredResultTests, NUnit.Framework.Internal.SuccessResultTests, and NUnit.Framework.Internal.DefaultResultTests.
Member Data Documentation
TestResult NUnit.Framework.Internal.TestResultTests.testResult protected
TestResult NUnit.Framework.Internal.TestResultTests.suiteResult protected
TestMethod NUnit.Framework.Internal.TestResultTests.test protected
double NUnit.Framework.Internal.TestResultTests.expectedDuration protected
DateTime NUnit.Framework.Internal.TestResultTests.expectedStart protected
DateTime NUnit.Framework.Internal.TestResultTests.expectedEnd protected
Property Documentation
virtual ResultState NUnit.Framework.Internal.TestResultTests.ResultState get protected
virtual string NUnit.Framework.Internal.TestResultTests.ReasonNodeName get protected
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/TestResultTests.cs