IGLib: NUnit.TestData.DatapointFixture.SquareRootTest Class Reference
NUnit.TestData.DatapointFixture.SquareRootTest Class Reference
Public Member Functions
void SqrtTimesItselfGivesOriginal (double num)
Member Function Documentation
void NUnit.TestData.DatapointFixture.SquareRootTest.SqrtTimesItselfGivesOriginal (double num) inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/testdata/DatapointFixture.cs