IGLib: Program Class Reference
Program Class Reference
Static Public Member Functions
static void AcceptCallback (IAsyncResult ar)
Asynchronously accepts an incoming connection attempt and creates a new Socket to handle remote host communication.
static void ReceiveCallback (IAsyncResult ar)
Asynchronously receive data from a connected Socket.
static void SendCallback (IAsyncResult ar)
Sends data asynchronously to a connected Socket.
Static Private Member Functions
static void listenToSNMP ()
static void answerSNMP ()
static void Main (string[] args)
static void PInvokeNativePipeServer ()
Named pipe server through P/Invoke-ing the native APIs
static void Main (string[] args)
static void Main (string[] args)
static void Main (string[] args)
static bool WriteMailslot (IntPtr hMailslot, String strMessage)
Write a message to the specified mailslot
static void Main (string[] args)
static bool ReadMailslot (IntPtr hMailslot)
Read the messages from a mailslot by using the mailslot handle in a call to the ReadFile function.
static void Main (string[] args)
Main
static void PInvokeNativePipeClient ()
static void BCLSystemIOPipeClient ()
static void Main (string[] args)
Main
static string GetResponse (NamedPipeClientStream pipeClient, string requestString)
static void BCLSystemIOPipeClient ()
static void Main (string[] args)
static void PInvokeNativePipeServer ()
Named pipe server through P/Invoke-ing the native APIs
static void BCLSystemIOPipeServer ()
Named pipe server through BCL System.IO.Pipes
static void Main (string[] args)
static void BCLSystemIOPipeServer (bool openNewServersSequentially)
static void BCLSystemIOPipeServer ()
Named pipe server through BCL System.IO.Pipes
static void Main (string[] args)
Main
static void PInvokeNativePipeClient ()
static void BCLSystemIOPipeClient ()
static void Main (string[] args)
Main
static string GetResponse (NamedPipeClientStream pipeClient, string requestString)
static void BCLSystemIOPipeClient ()
static void Main (string[] args)
static void PInvokeNativePipeServer ()
Named pipe server through P/Invoke-ing the native APIs
static void BCLSystemIOPipeServer ()
Named pipe server through BCL System.IO.Pipes
static void Main (string[] args)
static void BCLSystemIOPipeServer (bool openNewServersSequentially)
static void BCLSystemIOPipeServer ()
Named pipe server through BCL System.IO.Pipes
static void Main (string[] args)
static void RemotingClientByConfig ()
Access the .NET Remoting server using configuration file.
static void RemotingClientByCode ()
Access the .NET Remoting server using code.
static void Main (string[] args)
static void RemotingServerByConfig ()
Create the .NET Remoting server using configuration file.
static void RemotingServerByCode ()
Create the .NET Remoting server using code.
static void Main (string[] args)
static void Main (string[] args)
Private Attributes
const int BUFFER_SIZE = 4096
const uint BUFFER_SIZE = 256
const string STOP_REQUEST = "STOP"
const bool multiThreaded = true
Member Function Documentation
static void Program.listenToSNMP () inline static private
References SECURITY_ATTRIBUTES.bInheritHandle, BUFFER_SIZE, PipeNative.CloseHandle(), PipeNative.ConnectNamedPipe(), PipeNative.CreateNamedPipe(), PipeNative.DisconnectNamedPipe(), PipeNative.ERROR_PIPE_CONNECTED, PipeNative.FlushFileBuffers(), PipeNative.GetLastError(), SecurityNative.InitializeSecurityDescriptor(), PipeNative.INVALID_HANDLE_VALUE, SECURITY_ATTRIBUTES.lpSecurityDescriptor, SECURITY_ATTRIBUTES.nLength, PipeNative.NMPWAIT_USE_DEFAULT_WAIT, PipeNative.PIPE_UNLIMITED_INSTANCES, PipeNative.ReadFile(), and SecurityNative.SetSecurityDescriptorDacl().
Referenced by PInvokeNativePipeServer().
static void Program.answerSNMP () inline static private
References SECURITY_ATTRIBUTES.bInheritHandle, BUFFER_SIZE, PipeNative.CloseHandle(), PipeNative.ConnectNamedPipe(), PipeNative.CreateNamedPipe(), PipeNative.DisconnectNamedPipe(), PipeNative.ERROR_PIPE_CONNECTED, PipeNative.FlushFileBuffers(), PipeNative.GetLastError(), SecurityNative.InitializeSecurityDescriptor(), PipeNative.INVALID_HANDLE_VALUE, SECURITY_ATTRIBUTES.lpSecurityDescriptor, SECURITY_ATTRIBUTES.nLength, PipeNative.NMPWAIT_USE_DEFAULT_WAIT, PipeNative.PIPE_UNLIMITED_INSTANCES, PipeNative.ReadFile(), SecurityNative.SetSecurityDescriptorDacl(), and PipeNative.WriteFile().
Referenced by PInvokeNativePipeServer().
static void Program.Main (string[] args) inline static private
References PInvokeNativePipeServer().
static void Program.PInvokeNativePipeServer () inline static private
Named pipe server through P/Invoke-ing the native APIs
References answerSNMP(), and listenToSNMP().
Referenced by Main().
static void Program.Main (string[] args) inline static private
References FileMappingNative.CloseHandle(), FileMappingNative.GetLastError(), FileMappingNative.MapViewOfFile(), FileMappingNative.OpenFileMapping(), and FileMappingNative.UnmapViewOfFile().
static void Program.Main (string[] args) inline static private
References FileMappingNative.CloseHandle(), FileMappingNative.CreateFileMapping(), FileMappingNative.GetLastError(), FileMappingNative.INVALID_HANDLE_VALUE, FileMappingNative.MapViewOfFile(), and FileMappingNative.UnmapViewOfFile().
static void Program.Main (string[] args) inline static private
References MailslotNative.CloseHandle(), MailslotNative.CreateFile(), MailslotNative.INVALID_HANDLE_VALUE, and WriteMailslot().
static bool Program.WriteMailslot (IntPtr hMailslot, String strMessage) inline static private
Write a message to the specified mailslot
Parameters
hMailslot Handle to the mailslot
lpszMessage The message to be written to the slot
Returns
If the function succeeds, the return value is true
References MailslotNative.WriteFile().
Referenced by Main().
static void Program.Main (string[] args) inline static private
References SECURITY_ATTRIBUTES.bInheritHandle, MailslotNative.CloseHandle(), MailslotNative.CreateMailslot(), SecurityNative.InitializeSecurityDescriptor(), MailslotNative.INVALID_HANDLE_VALUE, SECURITY_ATTRIBUTES.lpSecurityDescriptor, MailslotNative.MAILSLOT_WAIT_FOREVER, SECURITY_ATTRIBUTES.nLength, ReadMailslot(), and SecurityNative.SetSecurityDescriptorDacl().
static bool Program.ReadMailslot (IntPtr hMailslot) inline static private
Read the messages from a mailslot by using the mailslot handle in a call to the ReadFile function.
Parameters
hMailslot The handle of the mailslot
Returns
If the function succeeds, the return value is true
References MailslotNative.GetMailslotInfo(), MailslotNative.MAILSLOT_NO_MESSAGE, and MailslotNative.ReadFile().
Referenced by Main().
static void Program.Main (string[] args) inline static private
Main
References BCLSystemIOPipeClient().
static void Program.PInvokeNativePipeClient () inline static private
References BUFFER_SIZE, PipeNative.CloseHandle(), PipeNative.CreateFile(), PipeNative.ERROR_MORE_DATA, PipeNative.ERROR_PIPE_BUSY, PipeNative.GetLastError(), PipeNative.INVALID_HANDLE_VALUE, PipeNative.ReadFile(), PipeNative.SetNamedPipeHandleState(), PipeNative.WaitNamedPipe(), and PipeNative.WriteFile().
static void Program.BCLSystemIOPipeClient () inline static private
References BUFFER_SIZE.
Referenced by Main().
static void Program.Main (string[] args) inline static private
Main
References BCLSystemIOPipeClient().
static string Program.GetResponse (NamedPipeClientStream pipeClient, string requestString) inline static private
References BUFFER_SIZE.
Referenced by BCLSystemIOPipeClient().
static void Program.BCLSystemIOPipeClient () inline static private
References BUFFER_SIZE, and GetResponse().
static void Program.Main (string[] args) inline static private
References PInvokeNativePipeServer().
static void Program.PInvokeNativePipeServer () inline static private
Named pipe server through P/Invoke-ing the native APIs
References SECURITY_ATTRIBUTES.bInheritHandle, BUFFER_SIZE, PipeNative.CloseHandle(), PipeNative.ConnectNamedPipe(), PipeNative.CreateNamedPipe(), PipeNative.DisconnectNamedPipe(), PipeNative.ERROR_PIPE_CONNECTED, PipeNative.FlushFileBuffers(), PipeNative.GetLastError(), SecurityNative.InitializeSecurityDescriptor(), PipeNative.INVALID_HANDLE_VALUE, SECURITY_ATTRIBUTES.lpSecurityDescriptor, SECURITY_ATTRIBUTES.nLength, PipeNative.NMPWAIT_USE_DEFAULT_WAIT, PipeNative.PIPE_UNLIMITED_INSTANCES, PipeNative.ReadFile(), SecurityNative.SetSecurityDescriptorDacl(), and PipeNative.WriteFile().
static void Program.BCLSystemIOPipeServer () inline static private
Named pipe server through BCL System.IO.Pipes
References BUFFER_SIZE.
Referenced by BCLSystemIOPipeServer(), and Main().
static void Program.Main (string[] args) inline static private
References BCLSystemIOPipeServer().
static void Program.BCLSystemIOPipeServer (bool openNewServersSequentially) inline static private
References BCLSystemIOPipeServer().
static void Program.BCLSystemIOPipeServer () inline static private
Named pipe server through BCL System.IO.Pipes
References BUFFER_SIZE.
static void Program.Main (string[] args) inline static private
Main
References BCLSystemIOPipeClient().
static void Program.PInvokeNativePipeClient () inline static private
References BUFFER_SIZE, PipeNative.CloseHandle(), PipeNative.CreateFile(), PipeNative.ERROR_MORE_DATA, PipeNative.ERROR_PIPE_BUSY, PipeNative.GetLastError(), PipeNative.INVALID_HANDLE_VALUE, PipeNative.ReadFile(), PipeNative.SetNamedPipeHandleState(), PipeNative.WaitNamedPipe(), and PipeNative.WriteFile().
static void Program.BCLSystemIOPipeClient () inline static private
References BUFFER_SIZE.
static void Program.Main (string[] args) inline static private
Main
References BCLSystemIOPipeClient().
static string Program.GetResponse (NamedPipeClientStream pipeClient, string requestString) inline static private
References BUFFER_SIZE.
static void Program.BCLSystemIOPipeClient () inline static private
References BUFFER_SIZE, and GetResponse().
static void Program.Main (string[] args) inline static private
References PInvokeNativePipeServer().
static void Program.PInvokeNativePipeServer () inline static private
Named pipe server through P/Invoke-ing the native APIs
References SECURITY_ATTRIBUTES.bInheritHandle, BUFFER_SIZE, PipeNative.CloseHandle(), PipeNative.ConnectNamedPipe(), PipeNative.CreateNamedPipe(), PipeNative.DisconnectNamedPipe(), PipeNative.ERROR_PIPE_CONNECTED, PipeNative.FlushFileBuffers(), PipeNative.GetLastError(), SecurityNative.InitializeSecurityDescriptor(), PipeNative.INVALID_HANDLE_VALUE, SECURITY_ATTRIBUTES.lpSecurityDescriptor, SECURITY_ATTRIBUTES.nLength, PipeNative.NMPWAIT_USE_DEFAULT_WAIT, PipeNative.PIPE_UNLIMITED_INSTANCES, PipeNative.ReadFile(), SecurityNative.SetSecurityDescriptorDacl(), and PipeNative.WriteFile().
static void Program.BCLSystemIOPipeServer () inline static private
Named pipe server through BCL System.IO.Pipes
References BUFFER_SIZE.
static void Program.Main (string[] args) inline static private
References BCLSystemIOPipeServer().
static void Program.BCLSystemIOPipeServer (bool openNewServersSequentially) inline static private
References BCLSystemIOPipeServer().
static void Program.BCLSystemIOPipeServer () inline static private
Named pipe server through BCL System.IO.Pipes
References BUFFER_SIZE.
static void Program.Main (string[] args) inline static private
References RemotingClientByCode().
static void Program.RemotingClientByConfig () inline static private
Access the .NET Remoting server using configuration file.
static void Program.RemotingClientByCode () inline static private
Access the .NET Remoting server using code.
Referenced by Main().
static void Program.Main (string[] args) inline static private
References RemotingServerByConfig().
static void Program.RemotingServerByConfig () inline static private
Create the .NET Remoting server using configuration file.
Referenced by Main().
static void Program.RemotingServerByCode () inline static private
Create the .NET Remoting server using code.
static void Program.Main (string[] args) inline static private
static void Program.Main (string[] args) inline static private
References AcceptCallback().
static void Program.AcceptCallback (IAsyncResult ar) inline static
Asynchronously accepts an incoming connection attempt and creates a new Socket to handle remote host communication.
Parameters
ar the status of an asynchronous operation
References ReceiveCallback().
Referenced by Main().
static void Program.ReceiveCallback (IAsyncResult ar) inline static
Asynchronously receive data from a connected Socket.
Parameters
ar the status of an asynchronous operation
References SendCallback().
Referenced by AcceptCallback().
static void Program.SendCallback (IAsyncResult ar) inline static
Sends data asynchronously to a connected Socket.
Parameters
ar The status of an asynchronous operation
Referenced by ReceiveCallback().
Member Data Documentation
const int Program.BUFFER_SIZE = 4096 private
Referenced by answerSNMP(), BCLSystemIOPipeClient(), BCLSystemIOPipeServer(), GetResponse(), listenToSNMP(), PInvokeNativePipeClient(), and PInvokeNativePipeServer().
const uint Program.BUFFER_SIZE = 256 private
const string Program.STOP_REQUEST = "STOP" private
const bool Program.multiThreaded = true private
The documentation for this class was generated from the following files:
igsandbox/InterprocessCommunication/named_pipe_examples_master/C++ client & C# server FULL-DUPLEX/CSPipeServer/CSPipeServer/Program.cs
igsandbox/InterprocessCommunication/named_pipe_examples_master/Inter-Process Communication (IPC)/CSNamedPipeClient/ProgramClientPipe.cs
igsandbox/InterprocessCommunication/named_pipe_examples_master/Inter-Process Communication (IPC)/CSNamedPipeServer/ProgramServerPipe.cs
igsandbox/InterprocessCommunication/named_pipe_examples_master/Inter-Process Communication (IPC)/CSNamedPipeTextClient/ProgramTextClientPipe.cs
igsandbox/InterprocessCommunication/named_pipe_examples_master/Inter-Process Communication (IPC)/CSNamedPipeTextServer/ProgramTextServerPipe.cs