IGLib: NUnit.TestUtilities.TestBuilder Class Reference
NUnit.TestUtilities.TestBuilder Class Reference
Utility Class used to build and run NUnit tests used as test data
Static Public Member Functions
static TestSuite MakeFixture (Type type)
static TestSuite MakeFixture (object fixture)
static TestSuite MakeParameterizedMethodSuite (Type type, string methodName)
static TestSuite MakeParameterizedMethodSuite (object fixture, string methodName)
static TestMethod MakeTestCase (Type type, string methodName)
static ITestResult RunTestFixture (Type type)
static ITestResult RunTestFixture (object fixture)
static ITestResult RunParameterizedMethodSuite (Type type, string methodName)
static ITestResult RunTestSuite (TestSuite suite, object testObject)
static ITestResult RunTestCase (Type type, string methodName)
static ITestResult RunTestCase (object fixture, string methodName)
static ITestResult RunTest (Test test, object testObject)
static TestSuite MakeFixture (Type type)
static TestSuite MakeFixture (object fixture)
static TestSuite MakeParameterizedMethodSuite (Type type, string methodName)
static TestSuite MakeParameterizedMethodSuite (object fixture, string methodName)
static TestMethod MakeTestCase (Type type, string methodName)
static ITestResult RunTestFixture (Type type)
static ITestResult RunTestFixture (object fixture)
static ITestResult RunParameterizedMethodSuite (Type type, string methodName)
static ITestResult RunTestSuite (TestSuite suite, object testObject)
static ITestResult RunTestCase (Type type, string methodName)
static ITestResult RunTestCase (object fixture, string methodName)
static ITestResult RunTest (Test test, object testObject)
Private Member Functions
TestBuilder ()
TestBuilder ()
Static Private Member Functions
static bool IsStaticClass (Type type)
static bool IsStaticClass (Type type)
Detailed Description
Utility Class used to build and run NUnit tests used as test data
Constructor & Destructor Documentation
NUnit.TestUtilities.TestBuilder.TestBuilder () inline private
NUnit.TestUtilities.TestBuilder.TestBuilder () inline private
Member Function Documentation
static TestSuite NUnit.TestUtilities.TestBuilder.MakeFixture (Type type) inline static
References NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom().
Referenced by NUnit.Framework.Internal.TestFixtureTests.CanConstructFrom(), NUnit.Framework.Attributes.TestFixtureSourceTests.CanIgnoreIndividualFixtures(), NUnit.Framework.Attributes.TestFixtureSourceTests.CanMarkIndividualFixturesExplicit(), NUnit.Framework.Internal.TestFixtureTests.CannotRunGenericFixtureDerivedFromAbstractFixtureWithNoArgsProvided(), NUnit.Framework.Internal.TestFixtureTests.CannotRunGenericFixtureWithNoArgsProvided(), NUnit.Framework.Internal.TestFixtureTests.CanRunGenericFixtureDerivedFromAbstractFixtureWithArgsProvided(), NUnit.Framework.Internal.TestFixtureTests.CanRunGenericFixtureWithProperArgsProvided(), NUnit.Framework.Attributes.ParameterizedTestFixtureTests.CanSpecifyCategory(), NUnit.Framework.Attributes.ParameterizedTestFixtureTests.CanSpecifyMultipleCategories(), NUnit.Framework.Attributes.RepeatAttributeTests.CategoryWorksWithRepeatedTest(), NUnit.Framework.Attributes.RetryAttributeTests.CategoryWorksWithRetry(), NUnit.Framework.Attributes.TestFixtureSourceTests.CheckNotRunnable(), NUnit.Framework.Attributes.PropertyAttributeTests.CreateFixture(), NUnit.Framework.Attributes.CategoryAttributeTests.CreateFixture(), NUnit.Framework.Tests.Attributes.AuthorTests.FixtureAuthor(), NUnit.Framework.Attributes.DescriptionTests.FixtureDescription(), NUnit.Framework.Internal.TestFixtureTests.FixtureInheritingTwoTestFixtureAttributesIsLoadedOnlyOnce(), NUnit.Framework.Tests.Attributes.TestOfTests.FixtureTestOf(), NUnit.Framework.Internal.TestFixtureTests.FixtureUsingIgnoreAttributeIsIgnored(), NUnit.Framework.Internal.TestFixtureTests.FixtureUsingIgnorePropertyIsIgnored(), NUnit.Framework.Internal.TestFixtureTests.FixtureUsingIgnoreReasonPropertyIsIgnored(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.IgnoredFixtureShouldNotCallFixtureSetUpOrTearDown(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWorksForTestSuite(), NUnit.Framework.Attributes.AttributeInheritanceTests.InheritedFixtureAttributeIsRecognized(), NUnit.Framework.Attributes.AttributeInheritanceTests.InheritedTestAttributeIsRecognized(), NUnit.TestUtilities.TestAssert.IsNotRunnable(), NUnit.TestUtilities.TestAssert.IsRunnable(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.LoadWithFrenchCanadianCulture(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.LoadWithFrenchCulture(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.LoadWithRussianCulture(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MakeFixture(), NUnit.Framework.Attributes.TimeoutTests.SetUpTimesOutAndTearDownIsRun(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutElapsed(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutNotElapsed(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutTestCaseWithOutElapsed(), and NUnit.Framework.Attributes.TimeoutTests.TestTimesOutAndTearDownIsRun().
static TestSuite NUnit.TestUtilities.TestBuilder.MakeFixture (object fixture) inline static
References NUnit.Framework.Internal.Test.Fixture.
static TestSuite NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite (Type type, string methodName) inline static
Referenced by NUnit.Framework.Attributes.TheoryTests.AllValuesMayBeSuppliedByAttributes(), NUnit.Framework.Tests.Attributes.AuthorTests.AuthorOnTestCase(), NUnit.Framework.Attributes.TheoryTests.BooleanArgumentsAreSuppliedAutomatically(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanExcludePlatform(), NUnit.Framework.Attributes.TestCaseSourceTests.CanIgnoreIndividualTestCases(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanIgnoreIndividualTestCases(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanIncludePlatform(), NUnit.Framework.Attributes.TestCaseSourceTests.CanMarkIndividualTestCasesExplicit(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanMarkIndividualTestCasesExplicit(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyCategory(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyDescription(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyMultipleCategories(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyTestName_FixedText(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyTestName_WithMethodName(), NUnit.TestUtilities.TestAssert.ChildNotRunnable(), NUnit.Framework.Attributes.TheoryTests.DatapointAndAttributeDataMayBeCombined(), NUnit.Framework.Attributes.DescriptionTests.DescriptionOnTestCase(), NUnit.Framework.Attributes.TheoryTests.EnumArgumentsAreSuppliedAutomatically(), NUnit.Framework.Attributes.TestCaseSourceTests.HandlesExceptionInTestCaseSource(), NUnit.Framework.Internal.NUnitTestCaseBuilderTests.ParametrizedTestCaseTests(), NUnit.Framework.Attributes.TheoryTests.SimpleTestIgnoresDataPoints(), NUnit.Framework.Attributes.TestCaseAttributeTests.TestCaseRunnableState(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithMultipleTestCasesUsesCorrectNames(), NUnit.Framework.Tests.Attributes.TestOfTests.TestOfOnTestCase(), and NUnit.Framework.Attributes.TheoryTests.TheoryWithDatapointsIsRunnable().
static TestSuite NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite (object fixture, string methodName) inline static
References NUnit.Framework.Internal.Test.Fixture, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
static TestMethod NUnit.TestUtilities.TestBuilder.MakeTestCase (Type type, string methodName) inline static
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
Referenced by NUnit.Framework.Tests.Attributes.AuthorTests.Author(), NUnit.Framework.Attributes.DescriptionTests.Description(), NUnit.TestUtilities.TestAssert.IsNotRunnable(), NUnit.Framework.Tests.Attributes.AuthorTests.NoAuthor(), NUnit.Framework.Attributes.DescriptionTests.NoDescription(), NUnit.Framework.Tests.Attributes.TestOfTests.NoTestOf(), NUnit.Framework.Attributes.DescriptionTests.ReflectionTest(), NUnit.Framework.Tests.Attributes.AuthorTests.ReflectionTest(), NUnit.Framework.Tests.Attributes.TestOfTests.ReflectionTest(), NUnit.Framework.Tests.Attributes.AuthorTests.SeparateAuthorAttribute(), NUnit.Framework.Tests.Attributes.AuthorTests.SeparateAuthorWithEmailAttribute(), NUnit.Framework.Attributes.DescriptionTests.SeparateDescriptionAttribute(), NUnit.Framework.Tests.Attributes.TestOfTests.SeparateTestOfAttribute(), NUnit.Framework.Tests.Attributes.TestOfTests.SeparateTestOfStringMethod(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodHasAttributesAppliedCorrectlyEvenIfNotRunnable(), and NUnit.Framework.Tests.Attributes.TestOfTests.TestOf().
static ITestResult NUnit.TestUtilities.TestBuilder.RunTestFixture (Type type) inline static
Referenced by NUnit.Framework.Assertions.AssertThatTests.AssertionsAreCountedCorrectly(), NUnit.Framework.Internal.TestFixtureTests.BadConstructorRunsWithSetUpError(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.BaseSetUpCalledFirstAndTearDownCalledLast(), NUnit.Framework.Internal.SetUpTearDownTests.BaseSetUpIsCalledFirstTearDownLast(), NUnit.Framework.Attributes.TestFixtureSourceTests.CheckArgument(), NUnit.Framework.Internal.SetUpTearDownTests.CheckInheritedSetUpAndTearDownAreCalled(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.CheckInheritedSetUpAndTearDownAreCalled(), NUnit.Framework.Internal.SetUpTearDownTests.CheckOverriddenSetUpAndTearDownAreNotCalled(), NUnit.Framework.Internal.GenericTestMethodTests.Combinatorial_IncompatibleArgsAreNotRunnable(), NUnitLite.Tests.TextUITests.CreateResult(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.DisposeCalledOnceWhenFixtureImplementsIDisposable(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.DisposeCalledOnceWhenFixtureImplementsIDisposableAndHasTestCases(), NUnit.Framework.Attributes.MaxTimeTests.ErrorReportHasPriorityOverMaxTime(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.FailedBaseSetUpCausesDerivedSetUpAndTeardownToBeSkipped(), NUnit.Framework.Internal.SetUpTearDownTests.FailureInBaseSetUpCausesDerivedSetUpAndTearDownToBeSkipped(), NUnit.Framework.Attributes.MaxTimeTests.FailureReportHasPriorityOverMaxTime(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.FixtureWithNoTestsShouldNotCallFixtureSetUpOrTearDown(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureSetup(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureTearDown(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureTearDownAfterErrorInFixtureSetUp(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleErrorInFixtureTearDownAfterErrorInTest(), NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInBothSetUpAndTearDown(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleExceptionInFixtureConstructor(), NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInSetUp(), NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInTearDown(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleIgnoreInFixtureSetup(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.HandleSetUpAndTearDownWithTestInName(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWorksFromSetUp(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.MakeSureSetUpAndTearDownAreCalled(), NUnit.Framework.Internal.SetUpTearDownTests.MakeSureSetUpAndTearDownAreCalled(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.MakeSureSetUpAndTearDownAreCalledOnFixtureWithTestCases(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.MakeSureSetUpAndTearDownAreCalledOnFixtureWithTheories(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.MakeSureSetUpAndTearDownAreNotCalledOnExplicitFixture(), NUnit.Framework.Attributes.MaxTimeTests.MaxTimeExceeded(), NUnit.Framework.Attributes.MaxTimeTests.MaxTimeExceededOnTestCase(), NUnit.Framework.Internal.SetUpTearDownTests.MultipleSetUpAndTearDownMethodsAreCalled(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.OverriddenSetUpAndTearDownAreNotCalled(), NUnit.Framework.Attributes.RepeatAttributeTests.RepeatWorksAsExpected(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.RerunFixtureAfterSetUpFixed(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.RerunFixtureAfterTearDownFixed(), NUnit.Framework.Attributes.RetryAttributeTests.RetryWorksAsExpected(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.RunMockAssemblyTests(), NUnit.Framework.Internal.TestMethodSignatureTests.RunningTestsThroughFixtureGivesCorrectResults(), NUnit.Framework.Attributes.DatapointTests.RunTestOnFixture(), NUnit.Framework.Internal.SetUpTearDownTests.SetUpAndTearDownCounter(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.StaticBaseSetUpCalledFirstAndTearDownCalledLast(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.StaticClassSetUpAndTearDownAreCalled(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.StaticSetUpAndTearDownAreCalled(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_FailingTest(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_FailureInSetUp(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_IgnoredInSetUp(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_PassingTest(), NUnit.Framework.Internal.GenericTestMethodTests.TestCase_IncompatibleArgsAreNotRunnable(), NUnit.Framework.Internal.GenericTestMethodTests.TestCaseSource_IncompatibleArgsAreNotRunnable(), NUnit.Framework.Tests.TestContextTests.TestContextStoresFailureInfoForOneTimeTearDown(), NUnit.Framework.Tests.TestContextTests.TestContextStoresFailureInfoForTearDown(), and NUnit.Framework.Attributes.TimeoutTests.TimeoutCanBeSetOnTestFixture().
static ITestResult NUnit.TestUtilities.TestBuilder.RunTestFixture (object fixture) inline static
static ITestResult NUnit.TestUtilities.TestBuilder.RunParameterizedMethodSuite (Type type, string methodName) inline static
References NUnit.Framework.Internal.Reflect.Construct().
Referenced by NUnit.Framework.Attributes.RandomAttributeTests.CheckRandomResult(), NUnit.Framework.Attributes.TestCaseSourceTests.IgnoreTakesPrecedenceOverExpectedException(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceUsingInstanceFieldIsNotRunnable(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceUsingInstanceMethodIsNotRunnable(), NUnit.Framework.Attributes.TestCaseSourceTests.SourceUsingInstancePropertyIsNotRunnable(), NUnit.Framework.Internal.TestMethodSignatureTests.TestMethodWithMultipleTestCasesExecutesMultipleTimes(), NUnit.Framework.Attributes.TheoryTests.TheoryFailsIfAllTestsAreInconclusive(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayNotBeInstanceField(), NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayNotBeInstanceMethod(), and NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayNotBeInstanceProperty().
static ITestResult NUnit.TestUtilities.TestBuilder.RunTestSuite (TestSuite suite, object testObject) inline static
References NUnit.Framework.Internal.Execution.WorkItem.CreateWorkItem(), NUnit.Framework.Internal.Execution.WorkItem.Execute(), NUnit.Framework.Internal.Execution.WorkItem.InitializeContext(), NUnit.Framework.Internal.Execution.WorkItem.Result, NUnit.Framework.Internal.Execution.WorkItem.State, and NUnit.Framework.Internal.TestExecutionContext.TestObject.
Referenced by NUnit.Framework.Attributes.OneTimeSetupTearDownTest.IgnoredFixtureShouldNotCallFixtureSetUpOrTearDown(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWorksForTestSuite(), and NUnit.TestUtilities.TestAssert.IsRunnable().
static ITestResult NUnit.TestUtilities.TestBuilder.RunTestCase (Type type, string methodName) inline static
References NUnit.Framework.Internal.Reflect.Construct().
Referenced by NUnit.Framework.Assertions.AssertFailTests.AssertFailWorks(), NUnit.Framework.Assertions.AssertFailTests.AssertFailWorksWithMessage(), NUnit.Framework.Assertions.AssertFailTests.AssertFailWorksWithMessageAndArgs(), NUnit.Framework.Internal.UnexpectedExceptionTests.BadStackTraceIsHandled(), NUnit.Framework.Attributes.Tests.CommandWrapperTests.CorrectExceptionThrown(), NUnit.Framework.Internal.UnexpectedExceptionTests.CustomExceptionIsHandled(), NUnit.Framework.Internal.UnexpectedExceptionTests.FailRecordsInnerException(), NUnit.Framework.Internal.UnexpectedExceptionTests.FailRecordsNestedInnerException(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWorksForTestCase(), NUnit.Framework.Attributes.Tests.CommandWrapperTests.NoExceptionThrown(), and NUnit.Framework.Attributes.Tests.CommandWrapperTests.WrongExceptionThrown().
static ITestResult NUnit.TestUtilities.TestBuilder.RunTestCase (object fixture, string methodName) inline static
static ITestResult NUnit.TestUtilities.TestBuilder.RunTest (Test test, object testObject) inline static
References NUnit.Framework.Internal.Execution.WorkItem.CreateWorkItem(), NUnit.Framework.Internal.Execution.WorkItem.Execute(), NUnit.Framework.Internal.Execution.WorkItem.InitializeContext(), NUnit.Framework.Internal.Execution.WorkItem.Result, NUnit.Framework.Internal.Execution.WorkItem.State, and NUnit.Framework.Internal.TestExecutionContext.TestObject.
Referenced by NUnit.Framework.Attributes.TestCaseSourceTests.HandlesExceptionInTestCaseSource(), NUnit.Framework.Attributes.OneTimeSetupTearDownTest.IgnoredFixtureShouldNotCallFixtureSetUpOrTearDown(), NUnit.TestUtilities.TestAssert.IsRunnable(), NUnit.Framework.Attributes.TimeoutTests.SetUpTimesOutAndTearDownIsRun(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutElapsed(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutNotElapsed(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutTestCaseWithOutElapsed(), and NUnit.Framework.Attributes.TimeoutTests.TestTimesOutAndTearDownIsRun().
static bool NUnit.TestUtilities.TestBuilder.IsStaticClass (Type type) inline static private
static TestSuite NUnit.TestUtilities.TestBuilder.MakeFixture (Type type) inline static
References NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom().
static TestSuite NUnit.TestUtilities.TestBuilder.MakeFixture (object fixture) inline static
References NUnit.Framework.Internal.Test.Fixture.
static TestSuite NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite (Type type, string methodName) inline static
References NUnit.Framework.Assert.NotNull().
static TestSuite NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite (object fixture, string methodName) inline static
References NUnit.Framework.Internal.Test.Fixture, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
static TestMethod NUnit.TestUtilities.TestBuilder.MakeTestCase (Type type, string methodName) inline static
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
static ITestResult NUnit.TestUtilities.TestBuilder.RunTestFixture (Type type) inline static
static ITestResult NUnit.TestUtilities.TestBuilder.RunTestFixture (object fixture) inline static
static ITestResult NUnit.TestUtilities.TestBuilder.RunParameterizedMethodSuite (Type type, string methodName) inline static
References NUnit.Framework.Internal.Reflect.Construct().
static ITestResult NUnit.TestUtilities.TestBuilder.RunTestSuite (TestSuite suite, object testObject) inline static
References NUnit.Framework.Internal.Execution.WorkItem.CreateWorkItem(), NUnit.Framework.Internal.Execution.WorkItem.Execute(), NUnit.Framework.Internal.Execution.WorkItem.InitializeContext(), NUnit.Framework.Internal.Execution.WorkItem.Result, NUnit.Framework.Internal.Execution.WorkItem.State, and NUnit.Framework.Internal.TestExecutionContext.TestObject.
static ITestResult NUnit.TestUtilities.TestBuilder.RunTestCase (Type type, string methodName) inline static
References NUnit.Framework.Internal.Reflect.Construct().
static ITestResult NUnit.TestUtilities.TestBuilder.RunTestCase (object fixture, string methodName) inline static
static ITestResult NUnit.TestUtilities.TestBuilder.RunTest (Test test, object testObject) inline static
References NUnit.Framework.Internal.Execution.WorkItem.CreateWorkItem(), NUnit.Framework.Internal.Execution.WorkItem.Execute(), NUnit.Framework.Internal.Execution.WorkItem.InitializeContext(), NUnit.Framework.Internal.Execution.WorkItem.Result, NUnit.Framework.Internal.Execution.WorkItem.State, and NUnit.Framework.Internal.TestExecutionContext.TestObject.
static bool NUnit.TestUtilities.TestBuilder.IsStaticClass (Type type) inline static private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/nunitlite.tests/TestUtilities/TestBuilder.cs