IGLib: Meta.Numerics.Matrices.ComplexEigensystem Class Reference
Meta.Numerics.Matrices.ComplexEigensystem Class Reference
Represents a collection of complex eigenvalues and eigenvectors.
Public Member Functions
Complex Eigenvalue (int n)
Gets the specified eigenvalue.
Complex[] Eigenvector (int n)
Gets the specified eigenvector.
Properties
int Dimension [get]
Gets the dimension of the eigensystem.
Private Attributes
int dimension
Complex[] eigenvalues
Complex[][] eigenvectors
Detailed Description
Represents a collection of complex eigenvalues and eigenvectors.
Member Function Documentation
Complex Meta.Numerics.Matrices.ComplexEigensystem.Eigenvalue (int n) inline
Gets the specified eigenvalue.
Parameters
n The number of the eigenvalue.
Returns
The n th eigenvalue.
Referenced by Test.BugTests.Bug7208(), Test.SquareMatrixTest.CompanionMatrixEigenvalues(), Test.SquareMatrixTest.SquareMatrixDifficultEigensystem(), Test.SquareMatrixTest.SquareMatrixStochasticEigensystem(), Test.SquareMatrixTest.SquareRandomMatrixEigenvalues(), Test.SquareMatrixTest.SquareUnitMatrixEigensystem(), and Test.SquareMatrixTest.SquareVandermondeMatrixEigenvalues().
Complex [] Meta.Numerics.Matrices.ComplexEigensystem.Eigenvector (int n) inline
Gets the specified eigenvector.
Parameters
n The number of the eigenvector.
Returns
The n th eigenvector.
Referenced by Test.BugTests.Bug7208(), Test.SquareMatrixTest.SquareMatrixDifficultEigensystem(), Test.SquareMatrixTest.SquareMatrixStochasticEigensystem(), Test.SquareMatrixTest.SquareRandomMatrixEigenvalues(), Test.SquareMatrixTest.SquareUnitMatrixEigensystem(), and Test.SquareMatrixTest.SquareVandermondeMatrixEigenvalues().
Member Data Documentation
int Meta.Numerics.Matrices.ComplexEigensystem.dimension private
Complex [] Meta.Numerics.Matrices.ComplexEigensystem.eigenvalues private
Complex [][] Meta.Numerics.Matrices.ComplexEigensystem.eigenvectors private
Property Documentation
int Meta.Numerics.Matrices.ComplexEigensystem.Dimension get
Gets the dimension of the eigensystem.
Referenced by Test.SquareMatrixTest.CompanionMatrixEigenvalues(), Test.SquareMatrixTest.SquareMatrixDifficultEigensystem(), Test.SquareMatrixTest.SquareMatrixStochasticEigensystem(), Test.SquareMatrixTest.SquareRandomMatrixEigenvalues(), and Test.SquareMatrixTest.SquareUnitMatrixEigensystem().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Matrices/ComplexEigensystem.cs