IGLib: CShell.ScriptingEngine Class Reference
CShell.ScriptingEngine Class Reference
Public Member Functions
ScriptingEngine ()
void Dispose ()
Task< EvaluatorResult > EvaluateAsync (string input)
Task< EvaluatorResult > EvaluateAsync (string input, string sourceFile)
Task< EvaluatorResult > EvaluateAsync (string input, string sourceFile, CancellationToken cancellationToken)
EvaluatorResult Evaluate (string input)
EvaluatorResult Evaluate (string input, string sourceFile)
void Interrupt ()
void ReferenceAssembly (Assembly assembly)
void ReferenceAssembly (string file)
string GetUsing ()
string GetVars ()
ScriptingEngine ()
void Dispose ()
Task< EvaluatorResult > EvaluateAsync (string input)
Task< EvaluatorResult > EvaluateAsync (string input, string sourceFile)
Task< EvaluatorResult > EvaluateAsync (string input, string sourceFile, CancellationToken cancellationToken)
EvaluatorResult Evaluate (string input)
EvaluatorResult Evaluate (string input, string sourceFile)
void Interrupt ()
void ReferenceAssembly (Assembly assembly)
void ReferenceAssembly (string file)
string GetUsing ()
string GetVars ()
Properties
CSharpCompletion CodeCompletion [get]
Events
EventHandler< ConsoleEventArgs > ConsoleOutput
EventHandler
< EvaluateStartedEventArgs > EvaluateStarted
EventHandler
< EvaluateCompletedEventArgs > EvaluateCompleted
Private Member Functions
void OnConsoleOutput (string text, TextType textType)
void OnConsoleOutput (ConsoleEventArgs e)
void OnEvaluateStarted (string input, string sourceFile)
void OnEvaluateCompleted (EvaluateCompletedEventArgs e)
void OnConsoleOutput (string text, TextType textType)
void OnConsoleOutput (ConsoleEventArgs e)
void OnEvaluateStarted (string input, string sourceFile)
void OnEvaluateCompleted (EvaluateCompletedEventArgs e)
Static Private Member Functions
static bool IsMessage (string message, string messageType)
static bool IsMessage (string message, string messageType)
Private Attributes
readonly Evaluator evaluator
readonly CompilerContext context
readonly TaskFactory taskFactory
readonly CancellationTokenSource tokenSource
readonly CSharpCompletion codeCompletion
Constructor & Destructor Documentation
CShell.ScriptingEngine.ScriptingEngine () inline
References CShell.Code.ScriptingInteractiveBase.Error, CShell.ScriptingEngine.Evaluate(), CShell.Code.ScriptingInteractiveBase.Evaluator, CShell.ScriptingEngine.evaluator, CShell.ScriptingEngine.OnConsoleOutput(), and CShell.Code.ScriptingInteractiveBase.Output.
CShell.ScriptingEngine.ScriptingEngine () inline
References CShell.Code.ScriptingInteractiveBase.Error, CShell.ScriptingEngine.Evaluate(), CShell.Code.ScriptingInteractiveBase.Evaluator, CShell.ScriptingEngine.evaluator, CShell.ScriptingEngine.OnConsoleOutput(), and CShell.Code.ScriptingInteractiveBase.Output.
Member Function Documentation
void CShell.ScriptingEngine.Dispose () inline
void CShell.ScriptingEngine.OnConsoleOutput (string text, TextType textType) inline private
Referenced by CShell.ScriptingEngine.OnConsoleOutput(), and CShell.ScriptingEngine.ScriptingEngine().
void CShell.ScriptingEngine.OnConsoleOutput (ConsoleEventArgs e) inline private
References CShell.ScriptingEngine.ConsoleOutput.
void CShell.ScriptingEngine.OnEvaluateStarted (string input, string sourceFile) inline private
References CShell.ScriptingEngine.EvaluateStarted.
Referenced by CShell.ScriptingEngine.Evaluate().
void CShell.ScriptingEngine.OnEvaluateCompleted (EvaluateCompletedEventArgs e) inline private
References CShell.ScriptingEngine.EvaluateCompleted.
Referenced by CShell.ScriptingEngine.Evaluate().
Task<EvaluatorResult> CShell.ScriptingEngine.EvaluateAsync (string input) inline
Referenced by CShell.Modules.Repl.Controls.CSRepl.CommandEntered(), CShell.ScriptingEngine.EvaluateAsync(), and CShell.Framework.Results.RunCodeResult.Execute().
Task<EvaluatorResult> CShell.ScriptingEngine.EvaluateAsync (string input, string sourceFile) inline
References CShell.ScriptingEngine.EvaluateAsync().
Task<EvaluatorResult> CShell.ScriptingEngine.EvaluateAsync (string input, string sourceFile, CancellationToken cancellationToken) inline
References CShell.ScriptingEngine.Evaluate().
EvaluatorResult CShell.ScriptingEngine.Evaluate (string input) inline
Referenced by CShell.ScriptingEngine.Evaluate(), CShell.ScriptingEngine.EvaluateAsync(), CShell.Shell.EvaluateFile(), and CShell.ScriptingEngine.ScriptingEngine().
EvaluatorResult CShell.ScriptingEngine.Evaluate (string input, string sourceFile) inline
References CShell.ScriptingEngine.IsMessage(), CShell.ScriptingEngine.OnEvaluateCompleted(), and CShell.ScriptingEngine.OnEvaluateStarted().
static bool CShell.ScriptingEngine.IsMessage (string message, string messageType) inline static private
Referenced by CShell.ScriptingEngine.Evaluate().
void CShell.ScriptingEngine.Interrupt () inline
Referenced by CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown().
void CShell.ScriptingEngine.ReferenceAssembly (Assembly assembly) inline
void CShell.ScriptingEngine.ReferenceAssembly (string file) inline
string CShell.ScriptingEngine.GetUsing () inline
Implements CShellCore.CodeCompletion.ICSharpScriptProvider.
string CShell.ScriptingEngine.GetVars () inline
Implements CShellCore.CodeCompletion.ICSharpScriptProvider.
void CShell.ScriptingEngine.Dispose () inline
void CShell.ScriptingEngine.OnConsoleOutput (string text, TextType textType) inline private
References CShell.ScriptingEngine.OnConsoleOutput().
void CShell.ScriptingEngine.OnConsoleOutput (ConsoleEventArgs e) inline private
References CShell.ScriptingEngine.ConsoleOutput.
void CShell.ScriptingEngine.OnEvaluateStarted (string input, string sourceFile) inline private
References CShell.ScriptingEngine.EvaluateStarted.
void CShell.ScriptingEngine.OnEvaluateCompleted (EvaluateCompletedEventArgs e) inline private
References CShell.ScriptingEngine.EvaluateCompleted.
Task<EvaluatorResult> CShell.ScriptingEngine.EvaluateAsync (string input) inline
References CShell.ScriptingEngine.EvaluateAsync().
Task<EvaluatorResult> CShell.ScriptingEngine.EvaluateAsync (string input, string sourceFile) inline
References CShell.ScriptingEngine.EvaluateAsync().
Task<EvaluatorResult> CShell.ScriptingEngine.EvaluateAsync (string input, string sourceFile, CancellationToken cancellationToken) inline
References CShell.ScriptingEngine.Evaluate().
EvaluatorResult CShell.ScriptingEngine.Evaluate (string input) inline
References CShell.ScriptingEngine.Evaluate().
EvaluatorResult CShell.ScriptingEngine.Evaluate (string input, string sourceFile) inline
References CShell.ScriptingEngine.IsMessage(), CShell.ScriptingEngine.OnEvaluateCompleted(), and CShell.ScriptingEngine.OnEvaluateStarted().
static bool CShell.ScriptingEngine.IsMessage (string message, string messageType) inline static private
void CShell.ScriptingEngine.Interrupt () inline
void CShell.ScriptingEngine.ReferenceAssembly (Assembly assembly) inline
void CShell.ScriptingEngine.ReferenceAssembly (string file) inline
string CShell.ScriptingEngine.GetUsing () inline
Implements CShellCore.CodeCompletion.ICSharpScriptProvider.
string CShell.ScriptingEngine.GetVars () inline
Implements CShellCore.CodeCompletion.ICSharpScriptProvider.
Member Data Documentation
readonly Evaluator CShell.ScriptingEngine.evaluator private
Referenced by CShell.ScriptingEngine.ScriptingEngine().
readonly CompilerContext CShell.ScriptingEngine.context private
readonly TaskFactory CShell.ScriptingEngine.taskFactory private
readonly CancellationTokenSource CShell.ScriptingEngine.tokenSource private
readonly CSharpCompletion CShell.ScriptingEngine.codeCompletion private
Property Documentation
CSharpCompletion CShell.ScriptingEngine.CodeCompletion get
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.OnViewLoaded().
Event Documentation
EventHandler< ConsoleEventArgs > CShell.ScriptingEngine.ConsoleOutput
Referenced by CShell.ScriptingEngine.OnConsoleOutput(), and CShell.Modules.Repl.ViewModels.OutputViewModel.OutputViewModel().
EventHandler< EvaluateStartedEventArgs > CShell.ScriptingEngine.EvaluateStarted
Referenced by CShell.ScriptingEngine.OnEvaluateStarted().
EventHandler< EvaluateCompletedEventArgs > CShell.ScriptingEngine.EvaluateCompleted
Referenced by CShell.ScriptingEngine.OnEvaluateCompleted().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/ScriptingEngine.cs