IGLib: alglib.serializer Class Reference
alglib.serializer Class Reference
Public Member Functions
serializer ()
void alloc_start ()
void alloc_entry ()
void sstart_str ()
void ustart_str (string s)
void serialize_bool (bool v)
void serialize_int (int v)
void serialize_double (double v)
bool unserialize_bool ()
int unserialize_int ()
double unserialize_double ()
void stop ()
string get_string ()
serializer ()
void alloc_start ()
void alloc_entry ()
void sstart_str ()
void ustart_str (string s)
void serialize_bool (bool v)
void serialize_int (int v)
void serialize_double (double v)
bool unserialize_bool ()
int unserialize_int ()
double unserialize_double ()
void stop ()
string get_string ()
Private Types
enum SMODE {
SMODE.DEFAULT, SMODE.ALLOC, SMODE.TO_STRING, SMODE.FROM_STRING,
SMODE.DEFAULT, SMODE.ALLOC, SMODE.TO_STRING, SMODE.FROM_STRING
}
enum SMODE {
SMODE.DEFAULT, SMODE.ALLOC, SMODE.TO_STRING, SMODE.FROM_STRING,
SMODE.DEFAULT, SMODE.ALLOC, SMODE.TO_STRING, SMODE.FROM_STRING
}
Private Member Functions
int get_alloc_size ()
int get_alloc_size ()
Static Private Member Functions
static char sixbits2char (int v)
static int char2sixbits (char c)
static void threebytes2foursixbits (byte[] src, int src_offs, int[] dst, int dst_offs)
static void foursixbits2threebytes (int[] src, int src_offs, byte[] dst, int dst_offs)
static void bool2str (bool v, char[] buf, ref int offs)
static bool str2bool (char[] buf, ref int offs)
static void int2str (int v, char[] buf, ref int offs)
static int str2int (char[] buf, ref int offs)
static void double2str (double v, char[] buf, ref int offs)
static double str2double (char[] buf, ref int offs)
static char sixbits2char (int v)
static int char2sixbits (char c)
static void threebytes2foursixbits (byte[] src, int src_offs, int[] dst, int dst_offs)
static void foursixbits2threebytes (int[] src, int src_offs, byte[] dst, int dst_offs)
static void bool2str (bool v, char[] buf, ref int offs)
static bool str2bool (char[] buf, ref int offs)
static void int2str (int v, char[] buf, ref int offs)
static int str2int (char[] buf, ref int offs)
static void double2str (double v, char[] buf, ref int offs)
static double str2double (char[] buf, ref int offs)
Private Attributes
const int SER_ENTRIES_PER_ROW = 5
const int SER_ENTRY_LENGTH = 11
SMODE mode
int entries_needed
int entries_saved
int bytes_asked
int bytes_written
int bytes_read
char[] out_str
char[] in_str
Static Private Attributes
static char[] _sixbits2char_tbl
static int[] _char2sixbits_tbl
Member Enumeration Documentation
enum alglib.serializer.SMODE private
Enumerator
DEFAULT
ALLOC
TO_STRING
FROM_STRING
DEFAULT
ALLOC
TO_STRING
FROM_STRING
enum alglib.serializer.SMODE private
Enumerator
DEFAULT
ALLOC
TO_STRING
FROM_STRING
DEFAULT
ALLOC
TO_STRING
FROM_STRING
Constructor & Destructor Documentation
alglib.serializer.serializer () inline
alglib.serializer.serializer () inline
Member Function Documentation
void alglib.serializer.alloc_start () inline
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.testrbfunit.serializationtest(), alglib.testnearestneighborunit.testkdtreeserialization(), alglib.testdforestunit.testprocessing(), alglib.testmlpbaseunit.testprocessing(), alglib.testmlptrainunit.testprocessing(), alglib.testmlpeunit.testprocessing(), and alglib.testalglibbasicsunit.testserializationfunctions().
void alglib.serializer.alloc_entry () inline
int alglib.serializer.get_alloc_size () inline private
References alglib.serializer.bytes_asked, alglib.serializer.SER_ENTRIES_PER_ROW, and alglib.serializer.SER_ENTRY_LENGTH.
Referenced by alglib.serializer.sstart_str().
void alglib.serializer.sstart_str () inline
References alglib.serializer.get_alloc_size().
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.testrbfunit.serializationtest(), alglib.testnearestneighborunit.testkdtreeserialization(), alglib.testdforestunit.testprocessing(), alglib.testmlpbaseunit.testprocessing(), alglib.testmlptrainunit.testprocessing(), alglib.testmlpeunit.testprocessing(), and alglib.testalglibbasicsunit.testserializationfunctions().
void alglib.serializer.ustart_str (string s) inline
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.testrbfunit.serializationtest(), alglib.testnearestneighborunit.testkdtreeserialization(), alglib.testdforestunit.testprocessing(), alglib.testmlpbaseunit.testprocessing(), alglib.testmlptrainunit.testprocessing(), alglib.testmlpeunit.testprocessing(), and alglib.testalglibbasicsunit.testserializationfunctions().
void alglib.serializer.serialize_bool (bool v) inline
References alglib.serializer.bool2str(), and alglib.serializer.bytes_written.
void alglib.serializer.serialize_int (int v) inline
References alglib.serializer.bytes_written, and alglib.serializer.int2str().
void alglib.serializer.serialize_double (double v) inline
References alglib.serializer.bytes_written, and alglib.serializer.double2str().
bool alglib.serializer.unserialize_bool () inline
References alglib.serializer.str2bool().
int alglib.serializer.unserialize_int () inline
References alglib.serializer.str2int().
double alglib.serializer.unserialize_double () inline
References alglib.serializer.str2double().
void alglib.serializer.stop () inline
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.testrbfunit.serializationtest(), alglib.testnearestneighborunit.testkdtreeserialization(), alglib.testdforestunit.testprocessing(), alglib.testmlpbaseunit.testprocessing(), alglib.testmlptrainunit.testprocessing(), alglib.testmlpeunit.testprocessing(), and alglib.testalglibbasicsunit.testserializationfunctions().
string alglib.serializer.get_string () inline
Referenced by alglib.testmlpbaseunit.createnetwork(), alglib.testmlptrainunit.createnetwork(), alglib.testrbfunit.serializationtest(), alglib.testnearestneighborunit.testkdtreeserialization(), alglib.testdforestunit.testprocessing(), alglib.testmlpbaseunit.testprocessing(), alglib.testmlptrainunit.testprocessing(), alglib.testmlpeunit.testprocessing(), and alglib.testalglibbasicsunit.testserializationfunctions().
static char alglib.serializer.sixbits2char (int v) inline static private
Referenced by alglib.serializer.double2str(), and alglib.serializer.int2str().
static int alglib.serializer.char2sixbits (char c) inline static private
Referenced by alglib.serializer.str2double(), and alglib.serializer.str2int().
static void alglib.serializer.threebytes2foursixbits (byte[] src, int src_offs, int[] dst, int dst_offs) inline static private
Referenced by alglib.serializer.double2str(), and alglib.serializer.int2str().
static void alglib.serializer.foursixbits2threebytes (int[] src, int src_offs, byte[] dst, int dst_offs) inline static private
Referenced by alglib.serializer.str2double(), and alglib.serializer.str2int().
static void alglib.serializer.bool2str (bool v, char[] buf, ref int offs) inline static private
References alglib.serializer.SER_ENTRY_LENGTH.
Referenced by alglib.serializer.serialize_bool().
static bool alglib.serializer.str2bool (char[] buf, ref int offs) inline static private
Referenced by alglib.serializer.unserialize_bool().
static void alglib.serializer.int2str (int v, char[] buf, ref int offs) inline static private
References alglib.serializer.SER_ENTRY_LENGTH, alglib.serializer.sixbits2char(), and alglib.serializer.threebytes2foursixbits().
Referenced by alglib.serializer.serialize_int().
static int alglib.serializer.str2int (char[] buf, ref int offs) inline static private
References alglib.serializer.char2sixbits(), and alglib.serializer.foursixbits2threebytes().
Referenced by alglib.serializer.unserialize_int().
static void alglib.serializer.double2str (double v, char[] buf, ref int offs) inline static private
References alglib.serializer.SER_ENTRY_LENGTH, alglib.serializer.sixbits2char(), and alglib.serializer.threebytes2foursixbits().
Referenced by alglib.serializer.serialize_double().
static double alglib.serializer.str2double (char[] buf, ref int offs) inline static private
References alglib.serializer.char2sixbits(), alglib.serializer.foursixbits2threebytes(), and alglib.serializer.SER_ENTRY_LENGTH.
Referenced by alglib.serializer.unserialize_double().
void alglib.serializer.alloc_start () inline
void alglib.serializer.alloc_entry () inline
int alglib.serializer.get_alloc_size () inline private
void alglib.serializer.sstart_str () inline
void alglib.serializer.ustart_str (string s) inline
void alglib.serializer.serialize_bool (bool v) inline
void alglib.serializer.serialize_int (int v) inline
void alglib.serializer.serialize_double (double v) inline
bool alglib.serializer.unserialize_bool () inline
int alglib.serializer.unserialize_int () inline
double alglib.serializer.unserialize_double () inline
void alglib.serializer.stop () inline
string alglib.serializer.get_string () inline
static char alglib.serializer.sixbits2char (int v) inline static private
static int alglib.serializer.char2sixbits (char c) inline static private
static void alglib.serializer.threebytes2foursixbits (byte[] src, int src_offs, int[] dst, int dst_offs) inline static private
static void alglib.serializer.foursixbits2threebytes (int[] src, int src_offs, byte[] dst, int dst_offs) inline static private
static void alglib.serializer.bool2str (bool v, char[] buf, ref int offs) inline static private
static bool alglib.serializer.str2bool (char[] buf, ref int offs) inline static private
static void alglib.serializer.int2str (int v, char[] buf, ref int offs) inline static private
static int alglib.serializer.str2int (char[] buf, ref int offs) inline static private
static void alglib.serializer.double2str (double v, char[] buf, ref int offs) inline static private
static double alglib.serializer.str2double (char[] buf, ref int offs) inline static private
Member Data Documentation
const int alglib.serializer.SER_ENTRIES_PER_ROW = 5 private
Referenced by alglib.serializer.get_alloc_size().
const int alglib.serializer.SER_ENTRY_LENGTH = 11 private
Referenced by alglib.serializer.bool2str(), alglib.serializer.double2str(), alglib.serializer.get_alloc_size(), alglib.serializer.int2str(), and alglib.serializer.str2double().
SMODE alglib.serializer.mode private
int alglib.serializer.entries_needed private
int alglib.serializer.entries_saved private
int alglib.serializer.bytes_asked private
Referenced by alglib.serializer.get_alloc_size().
int alglib.serializer.bytes_written private
Referenced by alglib.serializer.serialize_bool(), alglib.serializer.serialize_double(), and alglib.serializer.serialize_int().
int alglib.serializer.bytes_read private
char [] alglib.serializer.out_str private
char [] alglib.serializer.in_str private
char [] alglib.serializer._sixbits2char_tbl static private
Initial value:
= new char[64]{
                '0', '1', '2', '3', '4', '5', '6', '7',
                '8', '9', 'A', 'B', 'C', 'D', 'E', 'F',
                'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
                'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V',
                'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd',
                'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
                'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
                'u', 'v', 'w', 'x', 'y', 'z', '-', '_' }
int [] alglib.serializer._char2sixbits_tbl static private
Initial value:
= new int[128] {
            -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, -1, -1, -1,
            -1, -1, -1, -1, -1, 62, -1, -1,
             0,  1,  2,  3,  4,  5,  6,  7,
             8,  9, -1, -1, -1, -1, -1, -1,
            -1, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24,
            25, 26, 27, 28, 29, 30, 31, 32,
            33, 34, 35, -1, -1, -1, -1, 63,
            -1, 36, 37, 38, 39, 40, 41, 42,
            43, 44, 45, 46, 47, 48, 49, 50,
            51, 52, 53, 54, 55, 56, 57, 58,
            59, 60, 61, -1, -1, -1, -1, -1 }
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/ap.cs