IGLib: IG.Forms.GraphBase Class Reference
IG.Forms.GraphBase Class Reference
Graph data & control class.
Public Member Functions
GraphBase (string description, string title)
GraphAxisItem AddXAxis ()
Adds a new X axis to the graph and returns it.
GraphAxisItem AddYAxis ()
Adds a new Y axis to the graph and returns it.
void RemoveAxis (GraphAxisItem axis)
Removes the specified axis from the graph.
GraphAxisItem getXAxis ()
Returns the first axis for which IsXAxis evaluates to true.
GraphAxisItem getYAxis ()
Returns the first axis for which IsYAxis evaluates to true.
GraphAxisItem getX2Axis ()
Returns the first axis for which IsX2Axis evaluates to true.
GraphAxisItem getY2Axis ()
Returns the first axis for which IsY2Axis evaluates to true.
void OpenModalWindow ()
Opens a new modal window containing the graph control that renders the current graph.
void OpenWindow ()
Creates and shows in a new thread a window containing the graph control that renders the current graph.
void DetachGraphWindow ()
Removes the top-level graph window.
Static Public Member Functions
static void Example ()
Protected Member Functions
void OpenWindowCurrentThread ()
Opens a new modal window containing the graph control that renders the current graph.
Protected Attributes
string _title
string _description
ZedGraphControl _graphControl
Thread _windowThread
Properties
object Lock [get]
PaneBase Pane [get]
The graph pane the chart is show in.
MasterPane MasterPane [get]
The graph pane the chart is show in.
GraphPane GraphPane [get]
The graph pane the chart is show in (same as .Pane).
virtual string Title [get, set]
Graph title.
virtual string Description [get, set]
Graph description.
ZedGraphControl GraphControl [get, protected set]
The control the graph pane is in.
List< GraphAxisItem > Axes [get]
Gets a list of axes maintained in the graph.
List< GraphPlotItem > PlotItems [get]
Gets a list of plot items (such as lines or bar charts) contained in the graph.
Form ContainingForm [get, set]
Control ContainingControl [get, set]
Thread WindowThread [get, protected set]
Thread in which new window is opened.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Member Functions
void Init (string description, string title)
Private Attributes
object _lock = new object()
List< GraphAxisItem > _axes = new List<GraphAxisItem>()
List< GraphPlotItem > _plotItems = new List<GraphPlotItem>()
Form _containingForm = null
Control _containingControl
Detailed Description
Graph data & control class.
Constructor & Destructor Documentation
IG.Forms.GraphBase.GraphBase (string description, string title) inline
Member Function Documentation
void IG.Forms.GraphBase.Init (string description, string title) inline private
GraphAxisItem IG.Forms.GraphBase.AddXAxis () inline
Adds a new X axis to the graph and returns it.
References IG.Forms.GraphAxisItem.IsX2Axis, and IG.Forms.GraphAxisItem.IsXAxis.
GraphAxisItem IG.Forms.GraphBase.AddYAxis () inline
Adds a new Y axis to the graph and returns it.
References IG.Forms.GraphAxisItem.IsY2Axis, and IG.Forms.GraphAxisItem.IsYAxis.
void IG.Forms.GraphBase.RemoveAxis (GraphAxisItem axis) inline
Removes the specified axis from the graph.
Parameters
axis
References IG.Forms.GraphAxisItem.DetachFromGraph().
GraphAxisItem IG.Forms.GraphBase.getXAxis () inline
Returns the first axis for which IsXAxis evaluates to true.
References IG.Forms.GraphAxisItem.IsXAxis.
GraphAxisItem IG.Forms.GraphBase.getYAxis () inline
Returns the first axis for which IsYAxis evaluates to true.
References IG.Forms.GraphAxisItem.IsYAxis.
GraphAxisItem IG.Forms.GraphBase.getX2Axis () inline
Returns the first axis for which IsX2Axis evaluates to true.
References IG.Forms.GraphAxisItem.IsX2Axis.
GraphAxisItem IG.Forms.GraphBase.getY2Axis () inline
Returns the first axis for which IsY2Axis evaluates to true.
References IG.Forms.GraphAxisItem.IsY2Axis.
void IG.Forms.GraphBase.OpenModalWindow () inline
Opens a new modal window containing the graph control that renders the current graph.
void IG.Forms.GraphBase.OpenWindow () inline
Creates and shows in a new thread a window containing the graph control that renders the current graph.
void IG.Forms.GraphBase.OpenWindowCurrentThread () inline protected
Opens a new modal window containing the graph control that renders the current graph.
References IG.Forms.GraphWindow.GraphControl, IG.Lib.App.Rep, and IG.Lib.IReporterBase.ReportError().
void IG.Forms.GraphBase.DetachGraphWindow () inline
Removes the top-level graph window.
static void IG.Forms.GraphBase.Example () inline static
Referenced by Itaia.ProgramItaia.MainThread().
Member Data Documentation
string IG.Forms.GraphBase._title protected
string IG.Forms.GraphBase._description protected
object IG.Forms.GraphBase._lock = new object() private
ZedGraphControl IG.Forms.GraphBase._graphControl protected
List<GraphAxisItem> IG.Forms.GraphBase._axes = new List<GraphAxisItem>() private
List<GraphPlotItem> IG.Forms.GraphBase._plotItems = new List<GraphPlotItem>() private
Form IG.Forms.GraphBase._containingForm = null private
Control IG.Forms.GraphBase._containingControl private
Thread IG.Forms.GraphBase._windowThread protected
Property Documentation
object IG.Forms.GraphBase.Lock get
Referenced by IG.Forms.GraphLineItem.GraphLineItem().
PaneBase IG.Forms.GraphBase.Pane get
The graph pane the chart is show in.
MasterPane IG.Forms.GraphBase.MasterPane get
The graph pane the chart is show in.
GraphPane IG.Forms.GraphBase.GraphPane get
The graph pane the chart is show in (same as .Pane).
virtual string IG.Forms.GraphBase.Title get set
Graph title.
virtual string IG.Forms.GraphBase.Description get set
Graph description.
ZedGraphControl IG.Forms.GraphBase.GraphControl get protected set
The control the graph pane is in.
List<GraphAxisItem> IG.Forms.GraphBase.Axes get
Gets a list of axes maintained in the graph.
List<GraphPlotItem> IG.Forms.GraphBase.PlotItems get
Gets a list of plot items (such as lines or bar charts) contained in the graph.
Referenced by IG.Forms.GraphLineItem.GraphLineItem().
Form IG.Forms.GraphBase.ContainingForm get set
Control IG.Forms.GraphBase.ContainingControl get set
Thread IG.Forms.GraphBase.WindowThread get protected set
Thread in which new window is opened.
The documentation for this class was generated from the following file:
igapp/itaia/appitaialib/graph/GraphBase.cs