IGLib: alglib.mincg Class Reference
alglib.mincg Class Reference
Classes
class mincgreport
class mincgstate
Static Public Member Functions
static void mincgcreate (int n, double[] x, mincgstate state)
static void mincgcreatef (int n, double[] x, double diffstep, mincgstate state)
static void mincgsetcond (mincgstate state, double epsg, double epsf, double epsx, int maxits)
static void mincgsetscale (mincgstate state, double[] s)
static void mincgsetxrep (mincgstate state, bool needxrep)
static void mincgsetdrep (mincgstate state, bool needdrep)
static void mincgsetcgtype (mincgstate state, int cgtype)
static void mincgsetstpmax (mincgstate state, double stpmax)
static void mincgsuggeststep (mincgstate state, double stp)
static void mincgsetprecdefault (mincgstate state)
static void mincgsetprecdiag (mincgstate state, double[] d)
static void mincgsetprecscale (mincgstate state)
static bool mincgiteration (mincgstate state)
static void mincgresults (mincgstate state, ref double[] x, mincgreport rep)
static void mincgresultsbuf (mincgstate state, ref double[] x, mincgreport rep)
static void mincgrestartfrom (mincgstate state, double[] x)
static void mincgsetprecdiagfast (mincgstate state, double[] d)
static void mincgsetpreclowrankfast (mincgstate state, double[] d1, double[] c, double[,] v, int vcnt)
static void mincgsetprecvarpart (mincgstate state, double[] d2)
static void mincgsetgradientcheck (mincgstate state, double teststep)
static void mincgcreate (int n, double[] x, mincgstate state)
static void mincgcreatef (int n, double[] x, double diffstep, mincgstate state)
static void mincgsetcond (mincgstate state, double epsg, double epsf, double epsx, int maxits)
static void mincgsetscale (mincgstate state, double[] s)
static void mincgsetxrep (mincgstate state, bool needxrep)
static void mincgsetdrep (mincgstate state, bool needdrep)
static void mincgsetcgtype (mincgstate state, int cgtype)
static void mincgsetstpmax (mincgstate state, double stpmax)
static void mincgsuggeststep (mincgstate state, double stp)
static void mincgsetprecdefault (mincgstate state)
static void mincgsetprecdiag (mincgstate state, double[] d)
static void mincgsetprecscale (mincgstate state)
static bool mincgiteration (mincgstate state)
static void mincgresults (mincgstate state, ref double[] x, mincgreport rep)
static void mincgresultsbuf (mincgstate state, ref double[] x, mincgreport rep)
static void mincgrestartfrom (mincgstate state, double[] x)
static void mincgsetprecdiagfast (mincgstate state, double[] d)
static void mincgsetpreclowrankfast (mincgstate state, double[] d1, double[] c, double[,] v, int vcnt)
static void mincgsetprecvarpart (mincgstate state, double[] d2)
static void mincgsetgradientcheck (mincgstate state, double teststep)
Public Attributes
const int rscountdownlen = 10
const double gtol = 0.3
Static Private Member Functions
static void clearrequestfields (mincgstate state)
static void preconditionedmultiply (mincgstate state, ref double[] x, ref double[] work0, ref double[] work1)
static double preconditionedmultiply2 (mincgstate state, ref double[] x, ref double[] y, ref double[] work0, ref double[] work1)
static void mincginitinternal (int n, double diffstep, mincgstate state)
static void clearrequestfields (mincgstate state)
static void preconditionedmultiply (mincgstate state, ref double[] x, ref double[] work0, ref double[] work1)
static double preconditionedmultiply2 (mincgstate state, ref double[] x, ref double[] y, ref double[] work0, ref double[] work1)
static void mincginitinternal (int n, double diffstep, mincgstate state)
Member Function Documentation
static void alglib.mincg.mincgcreate (int n, double[] x, mincgstate state) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.mincg.mincginitinternal(), and alglib.mincg.mincgrestartfrom().
Referenced by alglib.testmincgunit.gradientchecktest(), alglib.minbleic.minbleiciteration(), alglib.mincgcreate(), alglib.testmincgunit.testmincg(), alglib.testmincgunit.testother(), and alglib.testmincgunit.testpreconditioning().
static void alglib.mincg.mincgcreatef (int n, double[] x, double diffstep, mincgstate state) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.mincg.mincginitinternal(), and alglib.mincg.mincgrestartfrom().
Referenced by alglib.mincgcreatef(), alglib.testmincgunit.testmincg(), and alglib.testmincgunit.testother().
static void alglib.mincg.mincgsetcond (mincgstate state, double epsg, double epsf, double epsx, int maxits) inline static
References alglib.ap.assert(), alglib.mincg.mincgstate.epsf, alglib.mincg.mincgstate.epsg, alglib.mincg.mincgstate.epsx, alglib.math.isfinite(), and alglib.mincg.mincgstate.maxits.
Referenced by alglib.testmincgunit.gradientchecktest(), alglib.minbleic.minbleiciteration(), alglib.mincg.mincginitinternal(), alglib.mincgsetcond(), alglib.testmincgunit.testmincg(), and alglib.testmincgunit.testother().
static void alglib.mincg.mincgsetscale (mincgstate state, double[] s) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.mincg.mincgstate.n, and alglib.mincg.mincgstate.s.
Referenced by alglib.minbleic.minbleiciteration(), alglib.mincgsetscale(), alglib.testmincgunit.testother(), and alglib.testmincgunit.testpreconditioning().
static void alglib.mincg.mincgsetxrep (mincgstate state, bool needxrep) inline static
References alglib.mincg.mincgstate.xrep.
Referenced by alglib.minbleic.minbleiciteration(), alglib.mincg.mincginitinternal(), alglib.mincgsetxrep(), and alglib.testmincgunit.testother().
static void alglib.mincg.mincgsetdrep (mincgstate state, bool needdrep) inline static
References alglib.mincg.mincgstate.drep.
Referenced by alglib.minbleic.minbleiciteration(), and alglib.mincg.mincginitinternal().
static void alglib.mincg.mincgsetcgtype (mincgstate state, int cgtype) inline static
References alglib.ap.assert(), and alglib.mincg.mincgstate.cgtype.
Referenced by alglib.mincg.mincginitinternal(), alglib.mincgsetcgtype(), alglib.testmincgunit.testmincg(), alglib.testmincgunit.testother(), and alglib.testmincgunit.testpreconditioning().
static void alglib.mincg.mincgsetstpmax (mincgstate state, double stpmax) inline static
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.mincg.mincgstate.stpmax.
Referenced by alglib.minbleic.minbleiciteration(), alglib.mincg.mincginitinternal(), alglib.mincgsetstpmax(), alglib.testmincgunit.testmincg(), and alglib.testmincgunit.testother().
static void alglib.mincg.mincgsuggeststep (mincgstate state, double stp) inline static
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.mincg.mincgstate.suggestedstep.
Referenced by alglib.mincg.mincgrestartfrom(), and alglib.mincgsuggeststep().
static void alglib.mincg.mincgsetprecdefault (mincgstate state) inline static
References alglib.mincg.mincgstate.innerresetneeded, and alglib.mincg.mincgstate.prectype.
Referenced by alglib.mincg.mincginitinternal(), alglib.mincgsetprecdefault(), and alglib.testmincgunit.testpreconditioning().
static void alglib.mincg.mincgsetprecdiag (mincgstate state, double[] d) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.mincg.mincgsetprecdiagfast(), and alglib.mincg.mincgstate.n.
Referenced by alglib.mincgsetprecdiag(), alglib.testmincgunit.testother(), and alglib.testmincgunit.testpreconditioning().
static void alglib.mincg.mincgsetprecscale (mincgstate state) inline static
References alglib.mincg.mincgstate.innerresetneeded, and alglib.mincg.mincgstate.prectype.
Referenced by alglib.mincgsetprecscale(), alglib.testmincgunit.testother(), and alglib.testmincgunit.testpreconditioning().
static bool alglib.mincg.mincgiteration (mincgstate state) inline static
References alglib.mincg.mincgstate.algpowerup, alglib.mincg.mincgstate.betady, alglib.mincg.mincgstate.betahs, alglib.mincg.mincgstate.cgtype, alglib.mincg.clearrequestfields(), alglib.mincg.mincgstate.curstpmax, alglib.mincg.mincgstate.d, alglib.mincg.mincgstate.debugrestartscount, alglib.optserv.derivativecheck(), alglib.mincg.mincgstate.diffstep, alglib.mincg.mincgstate.dk, alglib.mincg.mincgstate.dn, alglib.mincg.mincgstate.drep, alglib.mincg.mincgstate.epsf, alglib.mincg.mincgstate.epsg, alglib.mincg.mincgstate.epsx, alglib.mincg.mincgstate.f, alglib.mincg.mincgstate.fbase, alglib.mincg.mincgstate.fm1, alglib.mincg.mincgstate.fm2, alglib.mincg.mincgstate.fold, alglib.mincg.mincgstate.fp1, alglib.mincg.mincgstate.fp2, alglib.mincg.mincgstate.g, alglib.rcommstate.ia, alglib.mincg.mincgstate.innerresetneeded, alglib.mincg.mincgstate.k, alglib.mincg.mincgstate.lastgoodstep, alglib.mincg.mincgstate.lastscaledstep, alglib.linmin.linminnormalized(), alglib.mincg.mincgstate.lsend, alglib.mincg.mincgstate.lsstart, alglib.mincg.mincgstate.lstate, alglib.mincg.mincgstate.maxits, alglib.mincg.mincgstate.mcinfo, alglib.linmin.mcsrch(), alglib.mincg.mincgstate.mcstage, alglib.mincg.mincgstate.n, alglib.mincg.mincgstate.needf, alglib.mincg.mincgstate.needfg, alglib.mincg.mincgstate.nfev, alglib.mincg.preconditionedmultiply(), alglib.mincg.preconditionedmultiply2(), alglib.mincg.mincgstate.prectype, alglib.rcommstate.ra, alglib.mincg.mincgstate.repiterationscount, alglib.mincg.mincgstate.repnfev, alglib.mincg.mincgstate.repterminationtype, alglib.mincg.mincgstate.repvaridx, alglib.mincg.rscountdownlen, alglib.mincg.mincgstate.rstate, alglib.mincg.mincgstate.rstimer, alglib.mincg.mincgstate.s, alglib.math.sqr(), alglib.rcommstate.stage, alglib.mincg.mincgstate.stp, alglib.mincg.mincgstate.stpmax, alglib.mincg.mincgstate.suggestedstep, alglib.mincg.mincgstate.terminationneeded, alglib.mincg.mincgstate.teststep, alglib.optserv.trimfunction(), alglib.optserv.trimprepare(), alglib.mincg.mincgstate.trimthreshold, alglib.mincg.mincgstate.work0, alglib.mincg.mincgstate.work1, alglib.mincg.mincgstate.x, alglib.mincg.mincgstate.xk, alglib.mincg.mincgstate.xn, alglib.mincg.mincgstate.xrep, alglib.mincg.mincgstate.xupdated, and alglib.mincg.mincgstate.yk.
Referenced by alglib.testmincgunit.gradientchecktest(), alglib.minbleic.minbleiciteration(), alglib.mincgiteration(), alglib.testmincgunit.testmincg(), alglib.testmincgunit.testother(), and alglib.testmincgunit.testpreconditioning().
static void alglib.mincg.mincgresults (mincgstate state, ref double[] x, mincgreport rep) inline static
References alglib.mincg.mincgresultsbuf().
Referenced by alglib.testmincgunit.gradientchecktest(), alglib.minbleic.minbleiciteration(), alglib.mincgresults(), alglib.testmincgunit.testmincg(), alglib.testmincgunit.testother(), and alglib.testmincgunit.testpreconditioning().
static void alglib.mincg.mincgresultsbuf (mincgstate state, ref double[] x, mincgreport rep) inline static
References alglib.mincg.mincgreport.iterationscount, alglib.mincg.mincgstate.n, alglib.mincg.mincgreport.nfev, alglib.mincg.mincgstate.repiterationscount, alglib.mincg.mincgstate.repnfev, alglib.mincg.mincgstate.repterminationtype, alglib.mincg.mincgstate.repvaridx, alglib.mincg.mincgreport.terminationtype, alglib.mincg.mincgreport.varidx, and alglib.mincg.mincgstate.xn.
Referenced by alglib.mincg.mincgresults(), and alglib.mincgresultsbuf().
static void alglib.mincg.mincgrestartfrom (mincgstate state, double[] x) inline static
References alglib.ap.assert(), alglib.mincg.clearrequestfields(), alglib.rcommstate.ia, alglib.apserv.isfinitevector(), alglib.mincg.mincgsuggeststep(), alglib.mincg.mincgstate.n, alglib.rcommstate.ra, alglib.mincg.mincgstate.rstate, alglib.rcommstate.stage, and alglib.mincg.mincgstate.x.
Referenced by alglib.testmincgunit.gradientchecktest(), alglib.minbleic.minbleiciteration(), alglib.mincg.mincgcreate(), alglib.mincg.mincgcreatef(), alglib.mincgrestartfrom(), alglib.testmincgunit.testmincg(), alglib.testmincgunit.testother(), and alglib.testmincgunit.testpreconditioning().
static void alglib.mincg.mincgsetprecdiagfast (mincgstate state, double[] d) inline static
References alglib.mincg.mincgstate.diagh, alglib.mincg.mincgstate.diaghl2, alglib.mincg.mincgstate.innerresetneeded, alglib.mincg.mincgstate.n, alglib.mincg.mincgstate.prectype, alglib.apserv.rvectorsetlengthatleast(), and alglib.mincg.mincgstate.vcnt.
Referenced by alglib.mincg.mincgsetprecdiag(), and alglib.mincg.mincgsetpreclowrankfast().
static void alglib.mincg.mincgsetpreclowrankfast (mincgstate state, double[] d1, double[] c, double v[,], int vcnt) inline static
References alglib.mincg.mincgstate.diagh, alglib.mincg.mincgstate.diaghl2, alglib.mincg.mincgstate.innerresetneeded, alglib.mincg.mincgsetprecdiagfast(), alglib.mincg.mincgstate.n, alglib.mincg.mincgstate.prectype, alglib.apserv.rmatrixsetlengthatleast(), alglib.apserv.rvectorsetlengthatleast(), alglib.trfac.spdmatrixcholeskyrec(), alglib.mincg.mincgstate.vcnt, alglib.mincg.mincgstate.vcorr, and alglib.mincg.mincgstate.work0.
Referenced by alglib.testmincgunit.testpreconditioning().
static void alglib.mincg.mincgsetprecvarpart (mincgstate state, double[] d2) inline static
References alglib.mincg.mincgstate.diaghl2, and alglib.mincg.mincgstate.n.
static void alglib.mincg.mincgsetgradientcheck (mincgstate state, double teststep) inline static
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.mincg.mincgstate.teststep.
Referenced by alglib.testmincgunit.gradientchecktest(), and alglib.mincgsetgradientcheck().
static void alglib.mincg.clearrequestfields (mincgstate state) inline static private
References alglib.mincg.mincgstate.algpowerup, alglib.mincg.mincgstate.lsend, alglib.mincg.mincgstate.lsstart, alglib.mincg.mincgstate.needf, alglib.mincg.mincgstate.needfg, and alglib.mincg.mincgstate.xupdated.
Referenced by alglib.mincg.mincgiteration(), and alglib.mincg.mincgrestartfrom().
static void alglib.mincg.preconditionedmultiply (mincgstate state, ref double[] x, ref double[] work0, ref double[] work1) inline static private
References alglib.ap.assert(), alglib.mincg.mincgstate.diagh, alglib.mincg.mincgstate.diaghl2, alglib.mincg.mincgstate.n, alglib.mincg.mincgstate.prectype, alglib.mincg.mincgstate.s, alglib.mincg.mincgstate.vcnt, alglib.mincg.mincgstate.vcorr, and alglib.mincg.mincgstate.work1.
Referenced by alglib.mincg.mincgiteration().
static double alglib.mincg.preconditionedmultiply2 (mincgstate state, ref double[] x, ref double[] y, ref double[] work0, ref double[] work1) inline static private
References alglib.ap.assert(), alglib.mincg.mincgstate.diagh, alglib.mincg.mincgstate.diaghl2, alglib.mincg.mincgstate.n, alglib.mincg.mincgstate.prectype, alglib.mincg.mincgstate.s, alglib.mincg.mincgstate.vcnt, and alglib.mincg.mincgstate.vcorr.
Referenced by alglib.mincg.mincgiteration().
static void alglib.mincg.mincginitinternal (int n, double diffstep, mincgstate state) inline static private
References alglib.mincg.mincgstate.d, alglib.mincg.mincgstate.diffstep, alglib.mincg.mincgstate.dk, alglib.mincg.mincgstate.dn, alglib.mincg.mincgstate.g, alglib.mincg.mincgsetcgtype(), alglib.mincg.mincgsetcond(), alglib.mincg.mincgsetdrep(), alglib.mincg.mincgsetprecdefault(), alglib.mincg.mincgsetstpmax(), alglib.mincg.mincgsetxrep(), alglib.mincg.mincgstate.n, alglib.mincg.mincgstate.s, alglib.mincg.mincgstate.teststep, alglib.mincg.mincgstate.work0, alglib.mincg.mincgstate.work1, alglib.mincg.mincgstate.x, alglib.mincg.mincgstate.xk, alglib.mincg.mincgstate.xn, and alglib.mincg.mincgstate.yk.
Referenced by alglib.mincg.mincgcreate(), and alglib.mincg.mincgcreatef().
static void alglib.mincg.mincgcreate (int n, double[] x, mincgstate state) inline static
static void alglib.mincg.mincgcreatef (int n, double[] x, double diffstep, mincgstate state) inline static
static void alglib.mincg.mincgsetcond (mincgstate state, double epsg, double epsf, double epsx, int maxits) inline static
static void alglib.mincg.mincgsetscale (mincgstate state, double[] s) inline static
static void alglib.mincg.mincgsetxrep (mincgstate state, bool needxrep) inline static
static void alglib.mincg.mincgsetdrep (mincgstate state, bool needdrep) inline static
static void alglib.mincg.mincgsetcgtype (mincgstate state, int cgtype) inline static
static void alglib.mincg.mincgsetstpmax (mincgstate state, double stpmax) inline static
static void alglib.mincg.mincgsuggeststep (mincgstate state, double stp) inline static
static void alglib.mincg.mincgsetprecdefault (mincgstate state) inline static
static void alglib.mincg.mincgsetprecdiag (mincgstate state, double[] d) inline static
static void alglib.mincg.mincgsetprecscale (mincgstate state) inline static
static bool alglib.mincg.mincgiteration (mincgstate state) inline static
static void alglib.mincg.mincgresults (mincgstate state, ref double[] x, mincgreport rep) inline static
static void alglib.mincg.mincgresultsbuf (mincgstate state, ref double[] x, mincgreport rep) inline static
static void alglib.mincg.mincgrestartfrom (mincgstate state, double[] x) inline static
static void alglib.mincg.mincgsetprecdiagfast (mincgstate state, double[] d) inline static
static void alglib.mincg.mincgsetpreclowrankfast (mincgstate state, double[] d1, double[] c, double v[,], int vcnt) inline static
static void alglib.mincg.mincgsetprecvarpart (mincgstate state, double[] d2) inline static
static void alglib.mincg.mincgsetgradientcheck (mincgstate state, double teststep) inline static
static void alglib.mincg.clearrequestfields (mincgstate state) inline static private
static void alglib.mincg.preconditionedmultiply (mincgstate state, ref double[] x, ref double[] work0, ref double[] work1) inline static private
static double alglib.mincg.preconditionedmultiply2 (mincgstate state, ref double[] x, ref double[] y, ref double[] work0, ref double[] work1) inline static private
static void alglib.mincg.mincginitinternal (int n, double diffstep, mincgstate state) inline static private
Member Data Documentation
const int alglib.mincg.rscountdownlen = 10
Referenced by alglib.mincg.mincgiteration().
const double alglib.mincg.gtol = 0.3
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/optimization.cs