IGLib: NUnit.Framework.Constraints.GreaterThanOrEqualConstraintTests Class Reference
NUnit.Framework.Constraints.GreaterThanOrEqualConstraintTests Class Reference
Public Member Functions
void SetUp ()
void CanCompareIComparables ()
void CanCompareIComparablesOfT ()
Public Member Functions inherited from NUnit.Framework.Constraints.ComparisonConstraintTestBase
void InvalidDataThrowsArgumentException (object data)
void UsesProvidedIComparer ()
void UsesProvidedGenericComparer ()
void UsesProvidedGenericComparison ()
void UsesProvidedLambda ()
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintTestBase
void SucceedsWithGoodValues (object value)
void FailsWithBadValues (object badValue, string message)
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintTestBaseNoData
void ProvidesProperDescription ()
void ProvidesProperStringRepresentation ()
Static Private Attributes
static object[] SuccessData = new object[] { 6, 5 }
static object[] FailureData = new object[] { new object[] { 4, "4" } }
Additional Inherited Members
Protected Attributes inherited from NUnit.Framework.Constraints.ComparisonConstraintTestBase
ComparisonConstraint comparisonConstraint
Protected Attributes inherited from NUnit.Framework.Constraints.ConstraintTestBaseNoData
Constraint theConstraint
string expectedDescription = "<NOT SET>"
string stringRepresentation = "<NOT SET>"
Member Function Documentation
void NUnit.Framework.Constraints.GreaterThanOrEqualConstraintTests.SetUp () inline
void NUnit.Framework.Constraints.GreaterThanOrEqualConstraintTests.CanCompareIComparables () inline
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.GreaterThanOrEqualConstraintTests.CanCompareIComparablesOfT () inline
References NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
Member Data Documentation
object [] NUnit.Framework.Constraints.GreaterThanOrEqualConstraintTests.SuccessData = new object[] { 6, 5 } static private
object [] NUnit.Framework.Constraints.GreaterThanOrEqualConstraintTests.FailureData = new object[] { new object[] { 4, "4" } } static private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/GreaterThanOrEqualConstraintTests.cs