IGLib: AP.Complex Struct Reference
AP.Complex Struct Reference
Public Member Functions
Complex (double _x)
Complex (double _x, double _y)
Static Public Member Functions
static implicit operator Complex (double _x)
static bool operator== (Complex lhs, Complex rhs)
static bool operator!= (Complex lhs, Complex rhs)
static Complex operator+ (Complex lhs)
static Complex operator- (Complex lhs)
static Complex operator+ (Complex lhs, Complex rhs)
static Complex operator- (Complex lhs, Complex rhs)
static Complex operator* (Complex lhs, Complex rhs)
static Complex operator/ (Complex lhs, Complex rhs)
Public Attributes
double x
double y
Constructor & Destructor Documentation
AP.Complex.Complex (double _x) inline
Referenced by AP.Complex.operator Complex(), AP.Complex.operator*(), AP.Complex.operator+(), and AP.Complex.operator-().
AP.Complex.Complex (double _x, double _y) inline
Member Function Documentation
static implicit AP.Complex.operator Complex (double _x) inline static
References AP.Complex.Complex().
static bool AP.Complex.operator== (Complex lhs, Complex rhs) inline static
References AP.Complex.x, and AP.Complex.y.
static bool AP.Complex.operator!= (Complex lhs, Complex rhs) inline static
References AP.Complex.x, and AP.Complex.y.
static Complex AP.Complex.operator+ (Complex lhs) inline static
static Complex AP.Complex.operator- (Complex lhs) inline static
References AP.Complex.Complex(), AP.Complex.x, and AP.Complex.y.
static Complex AP.Complex.operator+ (Complex lhs, Complex rhs) inline static
References AP.Complex.Complex(), AP.Complex.x, and AP.Complex.y.
static Complex AP.Complex.operator- (Complex lhs, Complex rhs) inline static
References AP.Complex.Complex(), AP.Complex.x, and AP.Complex.y.
static Complex AP.Complex.operator* (Complex lhs, Complex rhs) inline static
References AP.Complex.Complex(), AP.Complex.x, and AP.Complex.y.
static Complex AP.Complex.operator/ (Complex lhs, Complex rhs) inline static
References AP.Complex.x, and AP.Complex.y.
Member Data Documentation
double AP.Complex.x
Referenced by AP.Math.AbsComplex(), AP.Math.Conj(), AP.Math.CSqr(), AP.Complex.operator!=(), AP.Complex.operator*(), AP.Complex.operator+(), AP.Complex.operator-(), AP.Complex.operator/(), and AP.Complex.operator==().
double AP.Complex.y
Referenced by AP.Math.AbsComplex(), AP.Math.Conj(), AP.Math.CSqr(), AP.Complex.operator!=(), AP.Complex.operator*(), AP.Complex.operator+(), AP.Complex.operator-(), AP.Complex.operator/(), and AP.Complex.operator==().
The documentation for this struct was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/ap.cs