IGLib: MathEval.MathExpressionParser Class Reference
MathEval.MathExpressionParser Class Reference
Public Member Functions
MathExpressionParser ()
bool init (string expr)
double eval (double x, double y)
Private Attributes
MyClassBase myobj = null
Constructor & Destructor Documentation
MathEval.MathExpressionParser.MathExpressionParser () inline
Member Function Documentation
bool MathEval.MathExpressionParser.init (string expr) inline
Referenced by MathEval.Program.Main().
double MathEval.MathExpressionParser.eval (double x, double y) inline
References MathEval.MyClassBase.eval().
Referenced by MathEval.Program.Main().
Member Data Documentation
MyClassBase MathEval.MathExpressionParser.myobj = null private
The documentation for this class was generated from the following file:
igtest/test_iglib_tmp_CSharpScripter1_OLD_TO_DELETE/0000another_project/ConsoleApplication1/Mathcode.cs