IGLib: Meta.Numerics.Polynomial Class Reference
Meta.Numerics.Polynomial Class Reference
Represents a polynomial with real coefficients.
Public Member Functions
virtual double Coefficient (int n)
Gets the specificed coefficient.
virtual double Evaluate (double x)
Evaluates the polynomial for the given input value.
virtual Polynomial Differentiate ()
Differentiates the polynomial.
virtual Polynomial Integrate (double C)
Integrates the polynomail.
override string ToString ()
Generates a string representation of the polynomial.
Static Public Member Functions
static Polynomial FromCoefficients (params double[] coefficients)
Initializes a new polynomial with the given coefficients.
static Polynomial FromPoints (double[,] points)
Initializes a new polynomial that passes through the given points.
static Polynomial FromPoints (ICollection< XY > points)
Initializes a new polynomial that passes through the given points.
static Polynomial operator- (Polynomial p)
Negates a polynomial.
static Polynomial operator+ (Polynomial p1, Polynomial p2)
Computes the sum of two polynomials.
static Polynomial operator- (Polynomial p1, Polynomial p2)
Computes the difference of two polynomials.
static Polynomial operator* (Polynomial p1, Polynomial p2)
Computes the product of two polynomials.
static Polynomial Divide (Polynomial p1, Polynomial p2, out Polynomial remainder)
Computes the quotient of two polynomials.
Properties
virtual int Degree [get]
Gets the degree of the polynomial.
Private Attributes
double[] coefficients
int order
Detailed Description
Represents a polynomial with real coefficients.
Member Function Documentation
static Polynomial Meta.Numerics.Polynomial.FromCoefficients (params double[] coefficients) inline static
Initializes a new polynomial with the given coefficients.
Parameters
coefficients The coefficients of the polynomial.
Returns
The specified polynomial.
Coefficients should be arranged from low to high order, so that the kth entry is the coefficient of xk. For example, to specify the polynomial 5 - 6 x + 7 x2, give the values 5, -6, 7.
Referenced by Test.PolynomialTest.PolynomialArithmetic(), Test.PolynomialTest.PolynomialCalculus(), Test.PolynomialTest.PolynomialDivisionIdentity(), Test.PolynomialTest.PolynomialFit(), Test.PolynomialTest.PolynomialNegation(), Test.PolynomialTest.PolynomialProperties(), and Test.PolynomialTest.PolynomialRemainderTheorem().
static Polynomial Meta.Numerics.Polynomial.FromPoints (double points[,]) inline static
Initializes a new polynomial that passes through the given points.
Parameters
points An N X 2 array whose first column contains the x values of points and whose second column contains the corresponding y values.
Returns
A polynomial of degree N-1 that passes through all the given points.
Referenced by Test.PolynomialTest.PolynomialFit().
static Polynomial Meta.Numerics.Polynomial.FromPoints (ICollection< XY > points) inline static
Initializes a new polynomial that passes through the given points.
Parameters
points A collection of points.
Returns
A polynomial that passes through all the given points.
References Meta.Numerics.XY.X, and Meta.Numerics.XY.Y.
virtual double Meta.Numerics.Polynomial.Coefficient (int n) inline virtual
Gets the specificed coefficient.
Parameters
n The power of the variable for which the coefficient is desired.
Returns
The coefficient of xn.
Exceptions
ArgumentOutOfRangeException n is negative.
Referenced by Meta.Numerics.Polynomial.Divide(), Meta.Numerics.Polynomial.operator*(), Meta.Numerics.Polynomial.operator+(), Meta.Numerics.Polynomial.operator-(), Test.PolynomialTest.PolynomialDivisionIdentity(), Test.PolynomialTest.PolynomialFit(), Test.PolynomialTest.PolynomialProperties(), and Test.PolynomialTest.PolynomialRemainderTheorem().
virtual double Meta.Numerics.Polynomial.Evaluate (double x) inline virtual
Evaluates the polynomial for the given input value.
Parameters
x The value of the variable.
Returns
The value of the polynomial.
Referenced by Test.PolynomialTest.PolynomialArithmetic(), Test.PolynomialTest.PolynomialCalculus(), Test.PolynomialTest.PolynomialFit(), and Test.PolynomialTest.PolynomialNegation().
virtual Polynomial Meta.Numerics.Polynomial.Differentiate () inline virtual
Differentiates the polynomial.
Returns
The derivative of the polynomail.
Referenced by Test.PolynomialTest.PolynomialCalculus().
virtual Polynomial Meta.Numerics.Polynomial.Integrate (double C) inline virtual
Integrates the polynomail.
Parameters
C The integration constant.
Returns
The integral of the polynomial.
Referenced by Test.PolynomialTest.PolynomialCalculus().
override string Meta.Numerics.Polynomial.ToString () inline
Generates a string representation of the polynomial.
Returns
A string representation of the polynomial.
static Polynomial Meta.Numerics.Polynomial.operator- (Polynomial p) inline static
Negates a polynomial.
Parameters
p The polynomial.
Returns
The addative inverse of the polynomial.
Exceptions
ArgumentNullException p is null.
References Meta.Numerics.Polynomial.Coefficient(), and Meta.Numerics.Polynomial.Degree.
static Polynomial Meta.Numerics.Polynomial.operator+ (Polynomial p1, Polynomial p2) inline static
Computes the sum of two polynomials.
Parameters
p1 The first polynomial.
p2 The second polynomial.
Returns
The sum polynomial.
Exceptions
ArgumentNullException p1 or p2 is null.
References Meta.Numerics.Polynomial.Coefficient(), and Meta.Numerics.Polynomial.Degree.
static Polynomial Meta.Numerics.Polynomial.operator- (Polynomial p1, Polynomial p2) inline static
Computes the difference of two polynomials.
Parameters
p1 The first polynomial.
p2 The second polynomial.
Returns
The difference polynomial.
Exceptions
ArgumentNullException p1 or p2 is null.
References Meta.Numerics.Polynomial.Coefficient(), and Meta.Numerics.Polynomial.Degree.
static Polynomial Meta.Numerics.Polynomial.operator* (Polynomial p1, Polynomial p2) inline static
Computes the product of two polynomials.
Parameters
p1 The first polynomial.
p2 The second polynomial.
Returns
The product polynomial.
Exceptions
ArgumentNullException p1 or p2 is null.
References Meta.Numerics.Polynomial.Coefficient(), and Meta.Numerics.Polynomial.Degree.
static Polynomial Meta.Numerics.Polynomial.Divide (Polynomial p1, Polynomial p2, out Polynomial remainder) inline static
Computes the quotient of two polynomials.
Parameters
p1 The dividend polynomial.
p2 The divisor polynomial.
remainder The remainder polynomial.
Returns
The quotient polynomial.
p1 = q p2 + r
References Meta.Numerics.Polynomial.Coefficient(), and Meta.Numerics.Polynomial.Degree.
Referenced by Test.PolynomialTest.PolynomialDivisionIdentity(), and Test.PolynomialTest.PolynomialRemainderTheorem().
Member Data Documentation
double [] Meta.Numerics.Polynomial.coefficients private
int Meta.Numerics.Polynomial.order private
Property Documentation
virtual int Meta.Numerics.Polynomial.Degree get
Gets the degree of the polynomial.
The degree of a polynomial is the highest power of the variable that appears. For example, the degree of 5 + 6 x + 7 x2 is 2.
Referenced by Meta.Numerics.Polynomial.Divide(), Meta.Numerics.Polynomial.operator*(), Meta.Numerics.Polynomial.operator+(), Meta.Numerics.Polynomial.operator-(), Test.PolynomialTest.PolynomialArithmetic(), Test.PolynomialTest.PolynomialDivisionIdentity(), Test.PolynomialTest.PolynomialFit(), Test.PolynomialTest.PolynomialNegation(), Test.PolynomialTest.PolynomialProperties(), and Test.PolynomialTest.PolynomialRemainderTheorem().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Core/Polynomial.cs