IGLib: Test.ComplexMathTest Class Reference
Test.ComplexMathTest Class Reference
Public Member Functions
void ComplexIParts ()
void ComplexIDefinition ()
void ComplexSqrt ()
void ComplexPythagorean ()
void ComplexDoubleAngle ()
void ComplexSecTanTest ()
void ComplexTrigPeriodicity ()
void ComplexNegativeAngles ()
void ComplexAngleAdditionTest ()
void ComplexSinSinh ()
void ComplexCosCosh ()
void ComplexTanTanh ()
void ComplexSinhCoshRelation ()
void ComplexPowMultiplication ()
void ComplexPowOneHalf ()
void ComplexLogSpecialCase ()
void ComplexLogExp ()
void ComplexLogSum ()
void ComplexExpSpecialCase ()
void ComplexExpReflection ()
void ComplexExpSumTest ()
void ComplexMagnitude ()
void ComplexPowExponent ()
void ComplexPowSpecialCases ()
void ComplexRealAgreement ()
Private Attributes
Complex a = new Complex(3.0, 4.0)
Complex b = new Complex(1.5, -2.3)
Member Function Documentation
void Test.ComplexMathTest.ComplexIParts () inline
References Meta.Numerics.Complex.I, Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
void Test.ComplexMathTest.ComplexIDefinition () inline
References Meta.Numerics.Complex.I, and Meta.Numerics.ComplexMath.Sqrt().
void Test.ComplexMathTest.ComplexSqrt () inline
References Meta.Numerics.ComplexMath.Abs(), Meta.Numerics.ComplexMath.Arg(), Meta.Numerics.ComplexMath.Sqr(), and Meta.Numerics.ComplexMath.Sqrt().
void Test.ComplexMathTest.ComplexPythagorean () inline
References Meta.Numerics.ComplexMath.Cos(), Meta.Numerics.Complex.Im, and Meta.Numerics.ComplexMath.Sin().
void Test.ComplexMathTest.ComplexDoubleAngle () inline
References Meta.Numerics.ComplexMath.Cos(), Meta.Numerics.Complex.Im, and Meta.Numerics.ComplexMath.Sin().
void Test.ComplexMathTest.ComplexSecTanTest () inline
References Meta.Numerics.ComplexMath.Cos(), Meta.Numerics.Complex.Im, and Meta.Numerics.ComplexMath.Tan().
void Test.ComplexMathTest.ComplexTrigPeriodicity () inline
References Meta.Numerics.ComplexMath.Cos(), and Meta.Numerics.ComplexMath.Sin().
void Test.ComplexMathTest.ComplexNegativeAngles () inline
References Meta.Numerics.ComplexMath.Cos(), Meta.Numerics.Complex.Im, Meta.Numerics.ComplexMath.Sin(), and Meta.Numerics.ComplexMath.Tan().
void Test.ComplexMathTest.ComplexAngleAdditionTest () inline
References Meta.Numerics.ComplexMath.Cos(), and Meta.Numerics.ComplexMath.Sin().
void Test.ComplexMathTest.ComplexSinSinh () inline
References Meta.Numerics.ComplexMath.I, Meta.Numerics.ComplexMath.Sin(), and Meta.Numerics.ComplexMath.Sinh().
void Test.ComplexMathTest.ComplexCosCosh () inline
References Meta.Numerics.ComplexMath.Cos(), Meta.Numerics.ComplexMath.Cosh(), and Meta.Numerics.ComplexMath.I.
void Test.ComplexMathTest.ComplexTanTanh () inline
References Meta.Numerics.ComplexMath.I, Meta.Numerics.ComplexMath.Tan(), and Meta.Numerics.ComplexMath.Tanh().
void Test.ComplexMathTest.ComplexSinhCoshRelation () inline
References Meta.Numerics.ComplexMath.Cosh(), and Meta.Numerics.ComplexMath.Sinh().
void Test.ComplexMathTest.ComplexPowMultiplication () inline
References Meta.Numerics.ComplexMath.Pow().
void Test.ComplexMathTest.ComplexPowOneHalf () inline
References Meta.Numerics.ComplexMath.Pow(), and Meta.Numerics.ComplexMath.Sqrt().
void Test.ComplexMathTest.ComplexLogSpecialCase () inline
References Meta.Numerics.ComplexMath.I, and Meta.Numerics.ComplexMath.Log().
void Test.ComplexMathTest.ComplexLogExp () inline
References Meta.Numerics.ComplexMath.Exp(), and Meta.Numerics.ComplexMath.Log().
void Test.ComplexMathTest.ComplexLogSum () inline
References Meta.Numerics.ComplexMath.Arg(), and Meta.Numerics.ComplexMath.Log().
void Test.ComplexMathTest.ComplexExpSpecialCase () inline
References Meta.Numerics.ComplexMath.Exp().
void Test.ComplexMathTest.ComplexExpReflection () inline
References Meta.Numerics.ComplexMath.Exp().
void Test.ComplexMathTest.ComplexExpSumTest () inline
References Meta.Numerics.ComplexMath.Exp(), Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
void Test.ComplexMathTest.ComplexMagnitude () inline
References Meta.Numerics.ComplexMath.Abs(), and Meta.Numerics.Complex.Conjugate.
void Test.ComplexMathTest.ComplexPowExponent () inline
References Meta.Numerics.ComplexMath.Exp(), and Meta.Numerics.ComplexMath.Pow().
void Test.ComplexMathTest.ComplexPowSpecialCases () inline
References Meta.Numerics.ComplexMath.Pow().
void Test.ComplexMathTest.ComplexRealAgreement () inline
References Meta.Numerics.ComplexMath.Exp(), Meta.Numerics.ComplexMath.Log(), and Meta.Numerics.ComplexMath.Sqrt().
Member Data Documentation
Complex Test.ComplexMathTest.a = new Complex(3.0, 4.0) private
Complex Test.ComplexMathTest.b = new Complex(1.5, -2.3) private
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/ComplexMathTest.cs