IGLib: alglib.logit Class Reference
alglib.logit Class Reference
Classes
class logitmcstate
class logitmodel
class mnlreport
Static Public Member Functions
static void mnltrainh (double[,] xy, int npoints, int nvars, int nclasses, ref int info, logitmodel lm, mnlreport rep)
static void mnlprocess (logitmodel lm, double[] x, ref double[] y)
static void mnlprocessi (logitmodel lm, double[] x, ref double[] y)
static void mnlunpack (logitmodel lm, ref double[,] a, ref int nvars, ref int nclasses)
static void mnlpack (double[,] a, int nvars, int nclasses, logitmodel lm)
static void mnlcopy (logitmodel lm1, logitmodel lm2)
static double mnlavgce (logitmodel lm, double[,] xy, int npoints)
static double mnlrelclserror (logitmodel lm, double[,] xy, int npoints)
static double mnlrmserror (logitmodel lm, double[,] xy, int npoints)
static double mnlavgerror (logitmodel lm, double[,] xy, int npoints)
static double mnlavgrelerror (logitmodel lm, double[,] xy, int ssize)
static int mnlclserror (logitmodel lm, double[,] xy, int npoints)
static void mnltrainh (double[,] xy, int npoints, int nvars, int nclasses, ref int info, logitmodel lm, mnlreport rep)
static void mnlprocess (logitmodel lm, double[] x, ref double[] y)
static void mnlprocessi (logitmodel lm, double[] x, ref double[] y)
static void mnlunpack (logitmodel lm, ref double[,] a, ref int nvars, ref int nclasses)
static void mnlpack (double[,] a, int nvars, int nclasses, logitmodel lm)
static void mnlcopy (logitmodel lm1, logitmodel lm2)
static double mnlavgce (logitmodel lm, double[,] xy, int npoints)
static double mnlrelclserror (logitmodel lm, double[,] xy, int npoints)
static double mnlrmserror (logitmodel lm, double[,] xy, int npoints)
static double mnlavgerror (logitmodel lm, double[,] xy, int npoints)
static double mnlavgrelerror (logitmodel lm, double[,] xy, int ssize)
static int mnlclserror (logitmodel lm, double[,] xy, int npoints)
Public Attributes
const double xtol = 100*math.machineepsilon
const double ftol = 0.0001
const double gtol = 0.3
const int maxfev = 20
const double stpmin = 1.0E-2
const double stpmax = 1.0E5
const int logitvnum = 6
Static Private Member Functions
static void mnliexp (ref double[] w, double[] x)
static void mnlallerrors (logitmodel lm, double[,] xy, int npoints, ref double relcls, ref double avgce, ref double rms, ref double avg, ref double avgrel)
static void mnlmcsrch (int n, ref double[] x, ref double f, ref double[] g, double[] s, ref double stp, ref int info, ref int nfev, ref double[] wa, logitmcstate state, ref int stage)
static void mnlmcstep (ref double stx, ref double fx, ref double dx, ref double sty, ref double fy, ref double dy, ref double stp, double fp, double dp, ref bool brackt, double stmin, double stmax, ref int info)
static void mnliexp (ref double[] w, double[] x)
static void mnlallerrors (logitmodel lm, double[,] xy, int npoints, ref double relcls, ref double avgce, ref double rms, ref double avg, ref double avgrel)
static void mnlmcsrch (int n, ref double[] x, ref double f, ref double[] g, double[] s, ref double stp, ref int info, ref int nfev, ref double[] wa, logitmcstate state, ref int stage)
static void mnlmcstep (ref double stx, ref double fx, ref double dx, ref double sty, ref double fy, ref double dy, ref double stp, double fp, double dp, ref bool brackt, double stmin, double stmax, ref int info)
Member Function Documentation
static void alglib.logit.mnltrainh (double xy[,], int npoints, int nvars, int nclasses, ref int info, logitmodel lm, mnlreport rep) inline static
References alglib.logit.logitvnum, alglib.math.machineepsilon, alglib.math.minrealnumber, alglib.mlpbase.mlpcreatec0(), alglib.mlpbase.mlpgradnbatch(), alglib.mlpbase.mlphessiannbatch(), alglib.mlpbase.mlpinitpreprocessor(), alglib.mlpbase.mlpproperties(), alglib.logit.mnlmcsrch(), alglib.logit.mnlreport.ngrad, alglib.logit.mnlreport.nhess, alglib.math.randomreal(), alglib.trfac.spdmatrixcholesky(), alglib.densesolver.spdmatrixcholeskysolve(), and alglib.logit.logitmodel.w.
Referenced by alglib.mnltrainh().
static void alglib.logit.mnlprocess (logitmodel lm, double[] x, ref double[] y) inline static
References alglib.ap.assert(), alglib.logit.mnliexp(), and alglib.logit.logitmodel.w.
Referenced by alglib.logit.mnlallerrors(), alglib.logit.mnlavgce(), alglib.logit.mnlclserror(), alglib.mnlprocess(), and alglib.logit.mnlprocessi().
static void alglib.logit.mnlprocessi (logitmodel lm, double[] x, ref double[] y) inline static
References alglib.logit.mnlprocess().
Referenced by alglib.mnlprocessi().
static void alglib.logit.mnlunpack (logitmodel lm, ref double a[,], ref int nvars, ref int nclasses) inline static
References alglib.ap.assert(), and alglib.logit.logitmodel.w.
Referenced by alglib.mnlunpack().
static void alglib.logit.mnlpack (double a[,], int nvars, int nclasses, logitmodel lm) inline static
References alglib.logit.logitvnum, and alglib.logit.logitmodel.w.
Referenced by alglib.mnlpack().
static void alglib.logit.mnlcopy (logitmodel lm1, logitmodel lm2) inline static
References alglib.logit.logitmodel.w.
static double alglib.logit.mnlavgce (logitmodel lm, double xy[,], int npoints) inline static
References alglib.ap.assert(), alglib.math.minrealnumber, alglib.logit.mnlprocess(), and alglib.logit.logitmodel.w.
Referenced by alglib.mnlavgce().
static double alglib.logit.mnlrelclserror (logitmodel lm, double xy[,], int npoints) inline static
References alglib.logit.mnlclserror().
Referenced by alglib.mnlrelclserror().
static double alglib.logit.mnlrmserror (logitmodel lm, double xy[,], int npoints) inline static
References alglib.ap.assert(), alglib.logit.logitvnum, alglib.logit.mnlallerrors(), and alglib.logit.logitmodel.w.
Referenced by alglib.mnlrmserror().
static double alglib.logit.mnlavgerror (logitmodel lm, double xy[,], int npoints) inline static
References alglib.ap.assert(), alglib.logit.logitvnum, alglib.logit.mnlallerrors(), and alglib.logit.logitmodel.w.
Referenced by alglib.mnlavgerror().
static double alglib.logit.mnlavgrelerror (logitmodel lm, double xy[,], int ssize) inline static
References alglib.ap.assert(), alglib.logit.logitvnum, alglib.logit.mnlallerrors(), and alglib.logit.logitmodel.w.
Referenced by alglib.mnlavgrelerror().
static int alglib.logit.mnlclserror (logitmodel lm, double xy[,], int npoints) inline static
References alglib.ap.assert(), alglib.logit.mnlprocess(), and alglib.logit.logitmodel.w.
Referenced by alglib.mnlclserror(), and alglib.logit.mnlrelclserror().
static void alglib.logit.mnliexp (ref double[] w, double[] x) inline static private
References alglib.ap.assert().
Referenced by alglib.logit.mnlprocess().
static void alglib.logit.mnlallerrors (logitmodel lm, double xy[,], int npoints, ref double relcls, ref double avgce, ref double rms, ref double avg, ref double avgrel) inline static private
References alglib.ap.assert(), alglib.bdss.dserraccumulate(), alglib.bdss.dserrallocate(), alglib.bdss.dserrfinish(), alglib.logit.logitvnum, alglib.logit.mnlprocess(), and alglib.logit.logitmodel.w.
Referenced by alglib.logit.mnlavgerror(), alglib.logit.mnlavgrelerror(), and alglib.logit.mnlrmserror().
static void alglib.logit.mnlmcsrch (int n, ref double[] x, ref double f, ref double[] g, double[] s, ref double stp, ref int info, ref int nfev, ref double[] wa, logitmcstate state, ref int stage) inline static private
References alglib.logit.logitmcstate.brackt, alglib.logit.logitmcstate.dg, alglib.logit.logitmcstate.dginit, alglib.logit.logitmcstate.dgm, alglib.logit.logitmcstate.dgtest, alglib.logit.logitmcstate.dgx, alglib.logit.logitmcstate.dgxm, alglib.logit.logitmcstate.dgy, alglib.logit.logitmcstate.dgym, alglib.logit.logitmcstate.finit, alglib.logit.logitmcstate.fm, alglib.logit.logitmcstate.ftest1, alglib.logit.logitmcstate.fx, alglib.logit.logitmcstate.fxm, alglib.logit.logitmcstate.fy, alglib.logit.logitmcstate.fym, alglib.logit.logitmcstate.infoc, alglib.logit.mnlmcstep(), alglib.logit.logitmcstate.stage1, alglib.logit.logitmcstate.stmax, alglib.logit.logitmcstate.stmin, alglib.logit.stpmax, alglib.logit.stpmin, alglib.logit.logitmcstate.stx, alglib.logit.logitmcstate.sty, alglib.logit.logitmcstate.width, alglib.logit.logitmcstate.width1, and alglib.logit.logitmcstate.xtrapf.
Referenced by alglib.logit.mnltrainh().
static void alglib.logit.mnlmcstep (ref double stx, ref double fx, ref double dx, ref double sty, ref double fy, ref double dy, ref double stp, double fp, double dp, ref bool brackt, double stmin, double stmax, ref int info) inline static private
References alglib.math.sqr().
Referenced by alglib.logit.mnlmcsrch().
static void alglib.logit.mnltrainh (double xy[,], int npoints, int nvars, int nclasses, ref int info, logitmodel lm, mnlreport rep) inline static
static void alglib.logit.mnlprocess (logitmodel lm, double[] x, ref double[] y) inline static
static void alglib.logit.mnlprocessi (logitmodel lm, double[] x, ref double[] y) inline static
static void alglib.logit.mnlunpack (logitmodel lm, ref double a[,], ref int nvars, ref int nclasses) inline static
static void alglib.logit.mnlpack (double a[,], int nvars, int nclasses, logitmodel lm) inline static
static void alglib.logit.mnlcopy (logitmodel lm1, logitmodel lm2) inline static
static double alglib.logit.mnlavgce (logitmodel lm, double xy[,], int npoints) inline static
static double alglib.logit.mnlrelclserror (logitmodel lm, double xy[,], int npoints) inline static
static double alglib.logit.mnlrmserror (logitmodel lm, double xy[,], int npoints) inline static
static double alglib.logit.mnlavgerror (logitmodel lm, double xy[,], int npoints) inline static
static double alglib.logit.mnlavgrelerror (logitmodel lm, double xy[,], int ssize) inline static
static int alglib.logit.mnlclserror (logitmodel lm, double xy[,], int npoints) inline static
static void alglib.logit.mnliexp (ref double[] w, double[] x) inline static private
static void alglib.logit.mnlallerrors (logitmodel lm, double xy[,], int npoints, ref double relcls, ref double avgce, ref double rms, ref double avg, ref double avgrel) inline static private
static void alglib.logit.mnlmcsrch (int n, ref double[] x, ref double f, ref double[] g, double[] s, ref double stp, ref int info, ref int nfev, ref double[] wa, logitmcstate state, ref int stage) inline static private
static void alglib.logit.mnlmcstep (ref double stx, ref double fx, ref double dx, ref double sty, ref double fy, ref double dy, ref double stp, double fp, double dp, ref bool brackt, double stmin, double stmax, ref int info) inline static private
Member Data Documentation
const double alglib.logit.xtol = 100*math.machineepsilon
const double alglib.logit.ftol = 0.0001
const double alglib.logit.gtol = 0.3
const int alglib.logit.maxfev = 20
const double alglib.logit.stpmin = 1.0E-2
Referenced by alglib.logit.mnlmcsrch().
const double alglib.logit.stpmax = 1.0E5
Referenced by alglib.logit.mnlmcsrch().
const int alglib.logit.logitvnum = 6
Referenced by alglib.logit.mnlallerrors(), alglib.logit.mnlavgerror(), alglib.logit.mnlavgrelerror(), alglib.logit.mnlpack(), alglib.logit.mnlrmserror(), and alglib.logit.mnltrainh().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/dataanalysis.cs