IGLib: NUnit.Engine.Services.RuntimeFrameworkService Class Reference
NUnit.Engine.Services.RuntimeFrameworkService Class Reference
Public Member Functions
bool IsAvailable (string name)
Returns true if the runtime framework represented by the string passed as an argument is available.
string SelectRuntimeFramework (TestPackage package)
Selects a target runtime framework for a TestPackage based on the settings in the package and the assemblies themselves. The package RuntimeFramework setting may be updated as a result and a string representing the selected runtime is returned.
Public Member Functions inherited from NUnit.Engine.Services.Service
virtual void StartService ()
Initialize the Service
virtual void StopService ()
Do any cleanup needed before terminating the service
void Dispose ()
Static Private Member Functions
static bool FrameworksMatch (RuntimeFramework f1, RuntimeFramework f2)
Static Private Attributes
static Logger log = InternalTrace.GetLogger(typeof(RuntimeFrameworkService))
static readonly Version AnyVersion = new Version(0, 0)
Additional Inherited Members
Protected Member Functions inherited from NUnit.Engine.Services.Service
virtual void Dispose (bool disposing)
Protected Attributes inherited from NUnit.Engine.Services.Service
bool _disposed = false
Properties inherited from NUnit.Engine.Services.Service
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get, protected set]
Gets the ServiceStatus of this service
Properties inherited from NUnit.Engine.IService
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get]
Gets the ServiceStatus of this service
Member Function Documentation
bool NUnit.Engine.Services.RuntimeFrameworkService.IsAvailable (string name) inline
Returns true if the runtime framework represented by the string passed as an argument is available.
Parameters
name A string representing a framework, like 'net-4.0'
Returns
True if the framework is available, false if unavailable or nonexistent
Implements NUnit.Engine.IRuntimeFrameworkService.
References NUnit.Engine.RuntimeFramework.AvailableFrameworks, and NUnit.Engine.RuntimeFramework.Parse().
static bool NUnit.Engine.Services.RuntimeFrameworkService.FrameworksMatch (RuntimeFramework f1, RuntimeFramework f2) inline static private
References NUnit.Engine.RuntimeFramework.ClrVersion, NUnit.Engine.RuntimeFramework.FrameworkVersion, and NUnit.Engine.RuntimeFramework.Runtime.
string NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework (TestPackage package) inline
Selects a target runtime framework for a TestPackage based on the settings in the package and the assemblies themselves. The package RuntimeFramework setting may be updated as a result and a string representing the selected runtime is returned.
Parameters
package A TestPackage
Returns
A string representing the selected RuntimeFramework
Implements NUnit.Engine.IRuntimeFrameworkService.
References NUnit.Engine.RuntimeFramework.CurrentFramework, NUnit.Common.Logger.Debug(), NUnit.Engine.RuntimeFramework.DefaultVersion, NUnit.Engine.RuntimeFramework.FrameworkVersion, NUnit.Engine.Internal.PathUtils.IsAssemblyFileType(), NUnit.Engine.RuntimeFramework.IsAvailable, NUnit.Engine.RuntimeFramework.Parse(), NUnit.Common.PackageSettings.RunAsX86, NUnit.Engine.RuntimeFramework.Runtime, NUnit.Common.PackageSettings.RuntimeFramework, NUnit.Engine.TestPackage.Settings, NUnit.Engine.TestPackage.SubPackages, and NUnit.Engine.RuntimeFramework.ToString().
Referenced by NUnit.Engine.Services.Tests.RuntimeFrameworkServiceTests.SelectRuntimeFramework().
Member Data Documentation
Logger NUnit.Engine.Services.RuntimeFrameworkService.log = InternalTrace.GetLogger(typeof(RuntimeFrameworkService)) static private
readonly Version NUnit.Engine.Services.RuntimeFrameworkService.AnyVersion = new Version(0, 0) static private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/RuntimeFrameworkService.cs