IGLib: IG.Neural.Forms.Old.NeuralParametricDemoOld Class Reference
IG.Neural.Forms.Old.NeuralParametricDemoOld Class Reference
Class for testing Layout designs.
Public Member Functions
NeuralParametricDemoOld (string workingDirectoryPath)
Constructs a new form for parametric studies, with the specified working directory.
NeuralParametricDemoOld ()
Constructs a new form for parametric studies, with default working directory (specified internally as relative path to location of executable when run from Visual Studio).
string FormatNumber (double number)
Format number to fixed width.
void PlotTrainingAndVerificationPointsResponse (List< IVector > ParmTestSelectedPoints, int whichOutput, int whichParameter, double minParameterLimit, double maxParameterLimit)
void PlotRandTrainingAndVerificationPointsResponse (List< IVector > ParmTestSelectedPoints, int whichOutput, int whichParameter, double minParameterLimit, double maxParameterLimit)
virtual void ApplyPlotSettingsCurveBlueRed (LineItem Line, int i, int max)
virtual void ApplyPlotSettingsCurve (LineItem Line)
Public Attributes
string _workingDirectoryPath = "../../../../../../../workspaceprojects/12_01_paper_neuralcasting/train/opt"
string _neuralNetworkFilename = "neuralnetwork.json"
string _neuralNetworkPath
Protected Member Functions
override void InitLayout ()
Sets the default layout when the form is opened.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string _dataDefinitionFilename = "neuraldatadefinition.json"
string _dataDefinitionPath
NeuralParametricDemoAboutWindowOld _aboutWindow
Properties
bool IsTabPageVisibleParametric [get, set]
Whether the "Parametric Test" tab is visible or not.
bool IsTabPageVisibleParametricRand [get, set]
Whether the "Parametric Test Random" tab is visible or not.
bool IsTabPageVisibleSensitivityTest [get, set]
Whether the "Sensitivity Test" tab is visible or not.
bool IsTabPageVisibleErrorEstimation [get, set]
Whether the "Error Estimation" tab is visible or not.
string WorkingDirectoryPath [get, set]
Working directory where files are found.
string NeuralNetworkFilename [get, set]
Name of the file where neural network is stored.
string NeuralNetworkPath [get]
Path to the file where neural network is stored.
string DataDefinitionFilename [get, set]
Name of the file where data definitions are stored.
string DataDefinitionPath [get]
Path to the file where data definitions are stored.
NeuralParametricDemoAboutWindowOld AboutWindow [get]
Private Member Functions
void InitializeParmTestFGraph ()
void InitializeParmTestFGraphRand ()
void GenerateANNPredictionInputGid ()
void GenerateANNPredictionOutputGrid ()
void GenerateANNPredictionInfoGrid ()
void GenerateANNParamTestInputGridRand ()
void GenerateANNParamTestInputGrid ()
void LoadANN ()
void PrepareTrainingAndVerificationData ()
void LoadDataDefinition ()
void toolStripStoreSW_ItemClicked (object sender, ToolStripItemClickedEventArgs e)
void btnParmTest_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void btnPredict_Click (object sender, EventArgs e)
Button ANN predict output.
void ReadValuesFromGrid (ref IVector Values)
void WriteValesToGrid (IVector Values)
void ReadParametersFromGridPrediction (ref IVector Parameters)
void WriteParametersToGridPrediction (IVector Parameters)
void ReadParametersFromGridParmTest (ref List< IVector > ParameterLimits)
void ReadValuesFromGridarmTest (ref List< IVector > ParameterValues)
void btnResttDefault_Click (object sender, EventArgs e)
void combBoxANN_SelectedIndexChanged (object sender, EventArgs e)
void btnParmTestSelectAll_Click (object sender, EventArgs e)
Button select-all check boxes in parametric test data grid.
void btnParmTestClearAll_Click (object sender, EventArgs e)
Button clear-all check boxes in parametric test data grid.
void btnParmTestResetToDefault_Click (object sender, EventArgs e)
Button Reset to default parameters in parametric test data grid.
void btnParmTestStart_Click (object sender, EventArgs e)
Button Start parametric test.
void ParmTestAddRandomGraphs (int parTestRandomGraphNumber)
void ParmTestAddGraphs (int parTestGraphNumber)
void ParmTestPrepareGraphs (List< IVector > ParamTestParameterLimits, List< IVector > ParmTestSelectedPoints)
void ParmTestRandPrepareGraphs (List< IVector > ParamTestParameterLimits, List< IVector > ParmTestSelectedPoints)
void ParmTestInitializeGraphPane (GraphPane Pane, int whichOutput, int whichParameter)
void ParmTestPrepareSelectedPoint (ref List< IVector > VerificationPoints)
void ParmTestPrepareRandomPoints (ref List< IVector > VerificationPoints)
Prepare points for parametric test.
void dGridParmTestInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
Check for values in parametric test data grid.
void cBoxParmTestType_SelectedIndexChanged (object sender, EventArgs e)
void numNumPointsParmTest_ValueChanged (object sender, EventArgs e)
void btnParmTestFwd_Click (object sender, EventArgs e)
void btnParmTestFwdEnd_Click (object sender, EventArgs e)
void btnParmTestBck_Click (object sender, EventArgs e)
void btnParmTestBckEnd_Click (object sender, EventArgs e)
void cBParmTestManualPoints_CheckedChanged (object sender, EventArgs e)
void NeuralParametricDemo_HelpEventHandlers (object sender, KeyEventArgs e)
void NeuralParametricDemo_KeyUp (object sender, KeyEventArgs e)
void tabControl_KeyUp (object sender, KeyEventArgs e)
void aboutStoreSW_Click (object sender, EventArgs e)
void showManualToolStripMenuItem_Click (object sender, EventArgs e)
void closeStoreSW_Click (object sender, EventArgs e)
void btnParmTestStartRand_Click (object sender, EventArgs e)
void btnParmTestResetToDefaultRand_Click (object sender, EventArgs e)
void btnParmTestSelectAllRand_Click (object sender, EventArgs e)
void btnParmTestClearAllRand_Click (object sender, EventArgs e)
void btnParmTestBckEndRand_Click (object sender, EventArgs e)
void btnParmTestBckRand_Click (object sender, EventArgs e)
void btnParmTestFwdRand_Click (object sender, EventArgs e)
void btnParmTestFwdEndRand_Click (object sender, EventArgs e)
void numNumPointsParmTestRand_ValueChanged (object sender, EventArgs e)
void toolStripMenuItemAbout_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
INeuralApproximator approximator
InputOutputDataDefiniton NeuralDataDefinition
SampledDataSet verificationData
SampledDataSet trainingData
List< PlotterZedGraph > plotter
string nameANN = "neuralnetwork.json"
string definitionANN = "neuraldatadefinition.json"
List< GraphPane > parmTestGraphPane
List< GraphPane > parmTestRandGraphPene
Chart ParmTestGraphChart
Chart ParmTestGraphChartRand
string parTestType = "Verification Points"
int parTestNumPoints = 5
int parTestGraphNumber = 0
int parTestRandGraphNumber = 0
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.ToolStrip toolOarametricDemo
System.Windows.Forms.ToolStripDropDownButton fileStoreSW
System.Windows.Forms.ToolStripMenuItem closeStoreSW
System.Windows.Forms.ToolStripDropDownButton helpStoreSW
System.Windows.Forms.ToolStripMenuItem aboutStoreSW
System.Windows.Forms.ToolStripDropDownButton aNNStoreSW
System.Windows.Forms.ToolStripMenuItem saveANNStoreSW
System.Windows.Forms.ToolStripMenuItem loadANNStoreSW
System.Windows.Forms.ToolStripMenuItem importTDJson
System.Windows.Forms.ToolStripMenuItem jsonFile
System.Windows.Forms.ToolStripMenuItem csvFile
System.Windows.Forms.ToolStripMenuItem saveTrainingDataToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem jSONToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem cSVToolStripMenuItem
System.Windows.Forms.ToolStripSeparator toolStripSeparator1
System.Windows.Forms.ComboBox combBoxANN
System.Windows.Forms.TextBox tbInfoLine
System.Windows.Forms.TabControl tabControl
System.Windows.Forms.TabPage tpPrediction
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.DataGridView dGridInfoValues
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn4
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn6
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.DataGridView dGridOutputValues
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.DataGridView dGridInputParam
System.Windows.Forms.TabPage tpParmTest
System.Windows.Forms.TabPage tpSensTest
System.Windows.Forms.TabPage tpErrorEst
System.Windows.Forms.Button btnResttDefault
System.Windows.Forms.Button btnPredict
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.DataGridView dGridParmTestInputParam
ZedGraph.ZedGraphControl ParmTestFGraph
System.Windows.Forms.Button btnParmTestFwdEnd
System.Windows.Forms.Button btnParmTestBckEnd
System.Windows.Forms.Button btnParmTestFwd
System.Windows.Forms.Button btnParmTestBck
System.Windows.Forms.Button btnParmTestSelectAll
System.Windows.Forms.Button btnParmTestClearAll
System.Windows.Forms.Button btnParmTestResetToDefault
System.Windows.Forms.Button btnParmTestStart
System.Windows.Forms.NumericUpDown numNumPointsParmTest
System.Windows.Forms.Label label1
System.Windows.Forms.ComboBox cBoxParmTestType
System.Windows.Forms.Button btnParmTestEditPoints
System.Windows.Forms.Button button1
System.Windows.Forms.Button button2
System.Windows.Forms.Button btnSensTestFwdEnd
System.Windows.Forms.Button btnSensTestBckEnd
System.Windows.Forms.Button btnSensTestFwd
System.Windows.Forms.Button btnSensTestBck
System.Windows.Forms.GroupBox groupBox5
System.Windows.Forms.DataGridView dGreedSensTestInputParam
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn9
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn10
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn11
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn12
System.Windows.Forms.CheckBox cBParmTestManualPoints
System.Windows.Forms.Label label2
System.Windows.Forms.GroupBox groupBox6
System.Windows.Forms.DataGridView dataGridView1
System.Windows.Forms.TextBox textBox1
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn13
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn14
System.Windows.Forms.DataGridViewTextBoxColumn Change
System.Windows.Forms.DataGridViewTextBoxColumn Share
System.Windows.Forms.ToolStripMenuItem showManualToolStripMenuItem
System.Windows.Forms.TabPage tpParmTestRand
System.Windows.Forms.CheckBox cBParmTestManualPointsRand
System.Windows.Forms.Label lblManualPointsRand
System.Windows.Forms.Button btnParmTestEditPointsRand
System.Windows.Forms.NumericUpDown numNumPointsParmTestRand
System.Windows.Forms.Label lblNumPointsRand
System.Windows.Forms.ComboBox cBoxParmTestTypeRand
System.Windows.Forms.Button btnParmTestResetToDefaultRand
System.Windows.Forms.Button btnParmTestStartRand
System.Windows.Forms.Button btnParmTestFwdEndRand
System.Windows.Forms.Button btnParmTestBckEndRand
System.Windows.Forms.Button btnParmTestFwdRand
System.Windows.Forms.Button btnParmTestBckRand
ZedGraph.ZedGraphControl ParmTestFGraphRand
System.Windows.Forms.GroupBox groupBox7
System.Windows.Forms.DataGridView dGridParmTestInputParamRand
System.Windows.Forms.Button btnParmTestClearAllRand
System.Windows.Forms.Button btnParmTestSelectAllRand
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn15
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn16
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn17
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn18
System.Windows.Forms.DataGridViewCheckBoxColumn dataGridViewCheckBoxColumn1
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn1
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn2
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn3
System.Windows.Forms.DataGridViewTextBoxColumn columnID
System.Windows.Forms.DataGridViewTextBoxColumn columnName
System.Windows.Forms.DataGridViewTextBoxColumn columnValue
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn5
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn7
System.Windows.Forms.DataGridViewTextBoxColumn Value
System.Windows.Forms.DataGridViewTextBoxColumn dataGridViewTextBoxColumn8
System.Windows.Forms.DataGridViewTextBoxColumn MaxValue
System.Windows.Forms.DataGridViewCheckBoxColumn Column1
System.Windows.Forms.TextBox txtModel
System.Windows.Forms.Label lblModel
System.Windows.Forms.ToolStripMenuItem toolStripMenuItemAbout
Detailed Description
Class for testing Layout designs.
$A Tako78 Apr13; Igor Apr13;
Constructor & Destructor Documentation
IG.Neural.Forms.Old.NeuralParametricDemoOld.NeuralParametricDemoOld (string workingDirectoryPath) inline
Constructs a new form for parametric studies, with the specified working directory.
Parameters
workingDirectoryPath Path of the working directory. If null or empty string then default value (within the "workspaceprojects" directory, relative to executable directory in Visual Studio) will be set.
IG.Neural.Forms.Old.NeuralParametricDemoOld.NeuralParametricDemoOld () inline
Constructs a new form for parametric studies, with default working directory (specified internally as relative path to location of executable when run from Visual Studio).
Member Function Documentation
override void IG.Neural.Forms.Old.NeuralParametricDemoOld.InitLayout () inline protected
Sets the default layout when the form is opened.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.InitializeParmTestFGraph () inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.InitializeParmTestFGraphRand () inline private
string IG.Neural.Forms.Old.NeuralParametricDemoOld.FormatNumber (double number) inline
Format number to fixed width.
Parameters
number Desired number.
Returns
void IG.Neural.Forms.Old.NeuralParametricDemoOld.GenerateANNPredictionInputGid () inline private
References IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.InputLength, and IG.Num.InputOutputElementDefinition.Title.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.GenerateANNPredictionOutputGrid () inline private
References IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.InputOutputDataDefiniton.OutputLength, and IG.Num.InputOutputElementDefinition.Title.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.GenerateANNPredictionInfoGrid () inline private
References IG.Num.InputOutputDataDefiniton.Description, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.IVectorApproximator.InputLength, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.SampledDataSet.Length, IG.Num.InputOutputElementDefinition.Name, IG.Num.InputOutputDataDefiniton.Name, IG.Num.INeuralApproximator.NumVerificationPoints, IG.Num.IVectorApproximator.OutputLength, IG.Num.SampledDataSet.OutputLength, and IG.Num.INeuralApproximator.TrainingData.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.GenerateANNParamTestInputGridRand () inline private
References IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Num.InputOutputElementDefinition.Title.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.GenerateANNParamTestInputGrid () inline private
References IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Num.InputOutputElementDefinition.Title.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.LoadANN () inline private
References IG.Neural.NeuralApproximatorBaseExt.LoadJson().
void IG.Neural.Forms.Old.NeuralParametricDemoOld.PrepareTrainingAndVerificationData () inline private
References IG.Num.SampledDataSet.Add(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.IVectorApproximator.InputLength, IG.Num.SampledDataSet.Length, IG.Num.IVectorApproximator.OutputLength, IG.Num.INeuralApproximator.TrainingData, and IG.Num.INeuralApproximator.VerificationIndices.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.LoadDataDefinition () inline private
References IG.Num.InputOutputDataDefiniton.LoadJson().
void IG.Neural.Forms.Old.NeuralParametricDemoOld.toolStripStoreSW_ItemClicked (object sender, ToolStripItemClickedEventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTest_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.IVectorApproximator.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Num.InputOutputElementDefinition.Name.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnPredict_Click (object sender, EventArgs e) inline private
Button ANN predict output.
Parameters
sender
e
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Num.SampledDataSet.InputLength, IG.Num.SampledDataSet.OutputLength, and IG.Num.INeuralApproximator.TrainingData.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.ReadValuesFromGrid (ref IVector Values) inline private
References IG.Num.SampledDataSet.OutputLength, and IG.Num.INeuralApproximator.TrainingData.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.WriteValesToGrid (IVector Values) inline private
References IG.Num.SampledDataSet.OutputLength, and IG.Num.INeuralApproximator.TrainingData.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.ReadParametersFromGridPrediction (ref IVector Parameters) inline private
References IG.Num.SampledDataSet.InputLength, and IG.Num.INeuralApproximator.TrainingData.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.WriteParametersToGridPrediction (IVector Parameters) inline private
References IG.Num.SampledDataSet.InputLength, IG.Num.IVector.ToString(), and IG.Num.INeuralApproximator.TrainingData.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.ReadParametersFromGridParmTest (ref List< IVector > ParameterLimits) inline private
References IG.Num.SampledDataSet.InputLength, IG.Gr.Line, and IG.Num.INeuralApproximator.TrainingData.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.ReadValuesFromGridarmTest (ref List< IVector > ParameterValues) inline private
References IG.Num.SampledDataSet.InputLength, and IG.Num.INeuralApproximator.TrainingData.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnResttDefault_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.combBoxANN_SelectedIndexChanged (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestSelectAll_Click (object sender, EventArgs e) inline private
Button select-all check boxes in parametric test data grid.
Parameters
sender
e
References IG.Num.IVectorApproximator.InputLength.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestClearAll_Click (object sender, EventArgs e) inline private
Button clear-all check boxes in parametric test data grid.
Parameters
sender
e
References IG.Num.IVectorApproximator.InputLength.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestResetToDefault_Click (object sender, EventArgs e) inline private
Button Reset to default parameters in parametric test data grid.
Parameters
sender
e
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestStart_Click (object sender, EventArgs e) inline private
Button Start parametric test.
Parameters
sender
e
void IG.Neural.Forms.Old.NeuralParametricDemoOld.ParmTestAddRandomGraphs (int parTestRandomGraphNumber) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.ParmTestAddGraphs (int parTestGraphNumber) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.ParmTestPrepareGraphs (List< IVector > ParamTestParameterLimits, List< IVector > ParmTestSelectedPoints) inline private
References IG.Num.IVectorApproximator.OutputLength.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.ParmTestRandPrepareGraphs (List< IVector > ParamTestParameterLimits, List< IVector > ParmTestSelectedPoints) inline private
References IG.Num.IVectorApproximator.OutputLength.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.PlotTrainingAndVerificationPointsResponse (List< IVector > ParmTestSelectedPoints, int whichOutput, int whichParameter, double minParameterLimit, double maxParameterLimit) inline
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Num.InputOutputElementDefinition.Description, IG.Num.IVector.GetCopy(), IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Gr.Line, IG.Num.InputOutputElementDefinition.Name, and IG.Num.InputOutputElementDefinition.Title.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.PlotRandTrainingAndVerificationPointsResponse (List< IVector > ParmTestSelectedPoints, int whichOutput, int whichParameter, double minParameterLimit, double maxParameterLimit) inline
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Num.InputOutputElementDefinition.Description, IG.Num.IVector.GetCopy(), IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Gr.Line, IG.Num.InputOutputElementDefinition.Name, and IG.Num.InputOutputElementDefinition.Title.
virtual void IG.Neural.Forms.Old.NeuralParametricDemoOld.ApplyPlotSettingsCurveBlueRed (LineItem Line, int i, int max) inline virtual
References IG.Lib.ColorScaleBase.Create(), and IG.Lib.ColorScaleBase.GetColor().
virtual void IG.Neural.Forms.Old.NeuralParametricDemoOld.ApplyPlotSettingsCurve (LineItem Line) inline virtual
void IG.Neural.Forms.Old.NeuralParametricDemoOld.ParmTestInitializeGraphPane (GraphPane Pane, int whichOutput, int whichParameter) inline private
References IG.Num.InputOutputElementDefinition.Description, IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.InputOutputElementDefinition.Name, and IG.Num.InputOutputElementDefinition.Title.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.ParmTestPrepareSelectedPoint (ref List< IVector > VerificationPoints) inline private
References IG.Num.SampledDataSet.InputLength.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.ParmTestPrepareRandomPoints (ref List< IVector > VerificationPoints) inline private
Prepare points for parametric test.
Parameters
VerificationPoints
References IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.InputLength, and IG.Num.SampledDataSet.Length.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.dGridParmTestInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
Check for values in parametric test data grid.
Parameters
sender
e
References IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.IVectorApproximator.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Num.InputOutputElementDefinition.Name.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.cBoxParmTestType_SelectedIndexChanged (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.numNumPointsParmTest_ValueChanged (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestFwd_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestFwdEnd_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestBck_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestBckEnd_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.cBParmTestManualPoints_CheckedChanged (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.NeuralParametricDemo_HelpEventHandlers (object sender, KeyEventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.NeuralParametricDemo_KeyUp (object sender, KeyEventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.tabControl_KeyUp (object sender, KeyEventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.aboutStoreSW_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.showManualToolStripMenuItem_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.closeStoreSW_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestStartRand_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestResetToDefaultRand_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestSelectAllRand_Click (object sender, EventArgs e) inline private
References IG.Num.IVectorApproximator.InputLength.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestClearAllRand_Click (object sender, EventArgs e) inline private
References IG.Num.IVectorApproximator.InputLength.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestBckEndRand_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestBckRand_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestFwdRand_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestFwdEndRand_Click (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.numNumPointsParmTestRand_ValueChanged (object sender, EventArgs e) inline private
void IG.Neural.Forms.Old.NeuralParametricDemoOld.toolStripMenuItemAbout_Click (object sender, EventArgs e) inline private
override void IG.Neural.Forms.Old.NeuralParametricDemoOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
void IG.Neural.Forms.Old.NeuralParametricDemoOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Member Data Documentation
string IG.Neural.Forms.Old.NeuralParametricDemoOld._workingDirectoryPath = "../../../../../../../workspaceprojects/12_01_paper_neuralcasting/train/opt"
string IG.Neural.Forms.Old.NeuralParametricDemoOld._neuralNetworkFilename = "neuralnetwork.json"
string IG.Neural.Forms.Old.NeuralParametricDemoOld._neuralNetworkPath
string IG.Neural.Forms.Old.NeuralParametricDemoOld._dataDefinitionFilename = "neuraldatadefinition.json" protected
string IG.Neural.Forms.Old.NeuralParametricDemoOld._dataDefinitionPath protected
INeuralApproximator IG.Neural.Forms.Old.NeuralParametricDemoOld.approximator private
InputOutputDataDefiniton IG.Neural.Forms.Old.NeuralParametricDemoOld.NeuralDataDefinition private
SampledDataSet IG.Neural.Forms.Old.NeuralParametricDemoOld.verificationData private
SampledDataSet IG.Neural.Forms.Old.NeuralParametricDemoOld.trainingData private
List<PlotterZedGraph> IG.Neural.Forms.Old.NeuralParametricDemoOld.plotter private
string IG.Neural.Forms.Old.NeuralParametricDemoOld.nameANN = "neuralnetwork.json" private
string IG.Neural.Forms.Old.NeuralParametricDemoOld.definitionANN = "neuraldatadefinition.json" private
List<GraphPane> IG.Neural.Forms.Old.NeuralParametricDemoOld.parmTestGraphPane private
List<GraphPane> IG.Neural.Forms.Old.NeuralParametricDemoOld.parmTestRandGraphPene private
Chart IG.Neural.Forms.Old.NeuralParametricDemoOld.ParmTestGraphChart private
Chart IG.Neural.Forms.Old.NeuralParametricDemoOld.ParmTestGraphChartRand private
string IG.Neural.Forms.Old.NeuralParametricDemoOld.parTestType = "Verification Points" private
int IG.Neural.Forms.Old.NeuralParametricDemoOld.parTestNumPoints = 5 private
int IG.Neural.Forms.Old.NeuralParametricDemoOld.parTestGraphNumber = 0 private
int IG.Neural.Forms.Old.NeuralParametricDemoOld.parTestRandGraphNumber = 0 private
NeuralParametricDemoAboutWindowOld IG.Neural.Forms.Old.NeuralParametricDemoOld._aboutWindow protected
System.ComponentModel.IContainer IG.Neural.Forms.Old.NeuralParametricDemoOld.components = null private
Required designer variable.
System.Windows.Forms.ToolStrip IG.Neural.Forms.Old.NeuralParametricDemoOld.toolOarametricDemo private
System.Windows.Forms.ToolStripDropDownButton IG.Neural.Forms.Old.NeuralParametricDemoOld.fileStoreSW private
System.Windows.Forms.ToolStripMenuItem IG.Neural.Forms.Old.NeuralParametricDemoOld.closeStoreSW private
System.Windows.Forms.ToolStripDropDownButton IG.Neural.Forms.Old.NeuralParametricDemoOld.helpStoreSW private
System.Windows.Forms.ToolStripMenuItem IG.Neural.Forms.Old.NeuralParametricDemoOld.aboutStoreSW private
System.Windows.Forms.ToolStripDropDownButton IG.Neural.Forms.Old.NeuralParametricDemoOld.aNNStoreSW private
System.Windows.Forms.ToolStripMenuItem IG.Neural.Forms.Old.NeuralParametricDemoOld.saveANNStoreSW private
System.Windows.Forms.ToolStripMenuItem IG.Neural.Forms.Old.NeuralParametricDemoOld.loadANNStoreSW private
System.Windows.Forms.ToolStripMenuItem IG.Neural.Forms.Old.NeuralParametricDemoOld.importTDJson private
System.Windows.Forms.ToolStripMenuItem IG.Neural.Forms.Old.NeuralParametricDemoOld.jsonFile private
System.Windows.Forms.ToolStripMenuItem IG.Neural.Forms.Old.NeuralParametricDemoOld.csvFile private
System.Windows.Forms.ToolStripMenuItem IG.Neural.Forms.Old.NeuralParametricDemoOld.saveTrainingDataToolStripMenuItem private
System.Windows.Forms.ToolStripMenuItem IG.Neural.Forms.Old.NeuralParametricDemoOld.jSONToolStripMenuItem private
System.Windows.Forms.ToolStripMenuItem IG.Neural.Forms.Old.NeuralParametricDemoOld.cSVToolStripMenuItem private
System.Windows.Forms.ToolStripSeparator IG.Neural.Forms.Old.NeuralParametricDemoOld.toolStripSeparator1 private
System.Windows.Forms.ComboBox IG.Neural.Forms.Old.NeuralParametricDemoOld.combBoxANN private
System.Windows.Forms.TextBox IG.Neural.Forms.Old.NeuralParametricDemoOld.tbInfoLine private
System.Windows.Forms.TabControl IG.Neural.Forms.Old.NeuralParametricDemoOld.tabControl private
System.Windows.Forms.TabPage IG.Neural.Forms.Old.NeuralParametricDemoOld.tpPrediction private
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.NeuralParametricDemoOld.groupBox4 private
System.Windows.Forms.DataGridView IG.Neural.Forms.Old.NeuralParametricDemoOld.dGridInfoValues private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn4 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn6 private
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.NeuralParametricDemoOld.groupBox2 private
System.Windows.Forms.DataGridView IG.Neural.Forms.Old.NeuralParametricDemoOld.dGridOutputValues private
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.NeuralParametricDemoOld.groupBox1 private
System.Windows.Forms.DataGridView IG.Neural.Forms.Old.NeuralParametricDemoOld.dGridInputParam private
System.Windows.Forms.TabPage IG.Neural.Forms.Old.NeuralParametricDemoOld.tpParmTest private
System.Windows.Forms.TabPage IG.Neural.Forms.Old.NeuralParametricDemoOld.tpSensTest private
System.Windows.Forms.TabPage IG.Neural.Forms.Old.NeuralParametricDemoOld.tpErrorEst private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnResttDefault private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnPredict private
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.NeuralParametricDemoOld.groupBox3 private
System.Windows.Forms.DataGridView IG.Neural.Forms.Old.NeuralParametricDemoOld.dGridParmTestInputParam private
ZedGraph.ZedGraphControl IG.Neural.Forms.Old.NeuralParametricDemoOld.ParmTestFGraph private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestFwdEnd private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestBckEnd private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestFwd private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestBck private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestSelectAll private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestClearAll private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestResetToDefault private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestStart private
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.NeuralParametricDemoOld.numNumPointsParmTest private
System.Windows.Forms.Label IG.Neural.Forms.Old.NeuralParametricDemoOld.label1 private
System.Windows.Forms.ComboBox IG.Neural.Forms.Old.NeuralParametricDemoOld.cBoxParmTestType private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestEditPoints private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.button1 private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.button2 private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnSensTestFwdEnd private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnSensTestBckEnd private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnSensTestFwd private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnSensTestBck private
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.NeuralParametricDemoOld.groupBox5 private
System.Windows.Forms.DataGridView IG.Neural.Forms.Old.NeuralParametricDemoOld.dGreedSensTestInputParam private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn9 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn10 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn11 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn12 private
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.NeuralParametricDemoOld.cBParmTestManualPoints private
System.Windows.Forms.Label IG.Neural.Forms.Old.NeuralParametricDemoOld.label2 private
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.NeuralParametricDemoOld.groupBox6 private
System.Windows.Forms.DataGridView IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridView1 private
System.Windows.Forms.TextBox IG.Neural.Forms.Old.NeuralParametricDemoOld.textBox1 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn13 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn14 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.Change private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.Share private
System.Windows.Forms.ToolStripMenuItem IG.Neural.Forms.Old.NeuralParametricDemoOld.showManualToolStripMenuItem private
System.Windows.Forms.TabPage IG.Neural.Forms.Old.NeuralParametricDemoOld.tpParmTestRand private
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.NeuralParametricDemoOld.cBParmTestManualPointsRand private
System.Windows.Forms.Label IG.Neural.Forms.Old.NeuralParametricDemoOld.lblManualPointsRand private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestEditPointsRand private
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.NeuralParametricDemoOld.numNumPointsParmTestRand private
System.Windows.Forms.Label IG.Neural.Forms.Old.NeuralParametricDemoOld.lblNumPointsRand private
System.Windows.Forms.ComboBox IG.Neural.Forms.Old.NeuralParametricDemoOld.cBoxParmTestTypeRand private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestResetToDefaultRand private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestStartRand private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestFwdEndRand private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestBckEndRand private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestFwdRand private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestBckRand private
ZedGraph.ZedGraphControl IG.Neural.Forms.Old.NeuralParametricDemoOld.ParmTestFGraphRand private
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.NeuralParametricDemoOld.groupBox7 private
System.Windows.Forms.DataGridView IG.Neural.Forms.Old.NeuralParametricDemoOld.dGridParmTestInputParamRand private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestClearAllRand private
System.Windows.Forms.Button IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestSelectAllRand private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn15 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn16 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn17 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn18 private
System.Windows.Forms.DataGridViewCheckBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewCheckBoxColumn1 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn1 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn2 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn3 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.columnID private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.columnName private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.columnValue private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn5 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn7 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.Value private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.dataGridViewTextBoxColumn8 private
System.Windows.Forms.DataGridViewTextBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.MaxValue private
System.Windows.Forms.DataGridViewCheckBoxColumn IG.Neural.Forms.Old.NeuralParametricDemoOld.Column1 private
System.Windows.Forms.TextBox IG.Neural.Forms.Old.NeuralParametricDemoOld.txtModel private
System.Windows.Forms.Label IG.Neural.Forms.Old.NeuralParametricDemoOld.lblModel private
System.Windows.Forms.ToolStripMenuItem IG.Neural.Forms.Old.NeuralParametricDemoOld.toolStripMenuItemAbout private
Property Documentation
bool IG.Neural.Forms.Old.NeuralParametricDemoOld.IsTabPageVisibleParametric get set
Whether the "Parametric Test" tab is visible or not.
bool IG.Neural.Forms.Old.NeuralParametricDemoOld.IsTabPageVisibleParametricRand get set
Whether the "Parametric Test Random" tab is visible or not.
bool IG.Neural.Forms.Old.NeuralParametricDemoOld.IsTabPageVisibleSensitivityTest get set
Whether the "Sensitivity Test" tab is visible or not.
bool IG.Neural.Forms.Old.NeuralParametricDemoOld.IsTabPageVisibleErrorEstimation get set
Whether the "Error Estimation" tab is visible or not.
string IG.Neural.Forms.Old.NeuralParametricDemoOld.WorkingDirectoryPath get set
Working directory where files are found.
string IG.Neural.Forms.Old.NeuralParametricDemoOld.NeuralNetworkFilename get set
Name of the file where neural network is stored.
string IG.Neural.Forms.Old.NeuralParametricDemoOld.NeuralNetworkPath get
Path to the file where neural network is stored.
string IG.Neural.Forms.Old.NeuralParametricDemoOld.DataDefinitionFilename get set
Name of the file where data definitions are stored.
string IG.Neural.Forms.Old.NeuralParametricDemoOld.DataDefinitionPath get
Path to the file where data definitions are stored.
NeuralParametricDemoAboutWindowOld IG.Neural.Forms.Old.NeuralParametricDemoOld.AboutWindow get
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/FormsOld/NeuralParametricDemoOld.cs
shelldev/lib/extended/LibNeuralExtForms/FormsOld/NeuralParametricDemoOld.Designer.cs