IGLib: IG.Test.TestUtilities Class Reference
IG.Test.TestUtilities Class Reference
Unit tests for various utilities.
Public Member Functions
void ArraysConcatenateAndEquality ()
Tests array concatenation and equality checking.
void ArraysAndListToString ()
Tests array concatenation and equality checking.
void ArraysConcatenateAndEquality ()
Tests array concatenation and equality checking.
void ArraysAndListToString ()
Tests array concatenation and equality checking.
Protected Attributes
int OutputLevel = 1
Detailed Description
Unit tests for various utilities.
$A Igor May09;
Member Function Documentation
void IG.Test.TestUtilities.ArraysConcatenateAndEquality () inline
Tests array concatenation and equality checking.
void IG.Test.TestUtilities.ArraysAndListToString () inline
Tests array concatenation and equality checking.
void IG.Test.TestUtilities.ArraysConcatenateAndEquality () inline
Tests array concatenation and equality checking.
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
void IG.Test.TestUtilities.ArraysAndListToString () inline
Tests array concatenation and equality checking.
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
Member Data Documentation
int IG.Test.TestUtilities.OutputLevel = 1 protected
The documentation for this class was generated from the following file:
unittests/MSTests/TestUtil/TstUtil.cs