IGLib: alglib.testdforestunit Class Reference
alglib.testdforestunit Class Reference
Static Public Member Functions
static bool testdforest (bool silent)
static bool testdforest (bool silent)
static bool _pexec_testdforest (bool silent)
Static Private Member Functions
static void testprocessing (ref bool err)
static void basictest1 (int nvars, int nclasses, int passcount, ref bool err)
static void basictest2 (ref bool err)
static void basictest3 (ref bool err)
static void basictest4 (ref bool err)
static void basictest5 (ref bool err)
static double rnormal ()
static void rsphere (ref double[,] xy, int n, int i)
static void unsetdf (dforest.decisionforest df)
static void testprocessing (ref bool err)
static void basictest1 (int nvars, int nclasses, int passcount, ref bool err)
static void basictest2 (ref bool err)
static void basictest3 (ref bool err)
static void basictest4 (ref bool err)
static void basictest5 (ref bool err)
static double rnormal ()
static void rsphere (ref double[,] xy, int n, int i)
static void unsetdf (dforest.decisionforest df)
Member Function Documentation
static bool alglib.testdforestunit.testdforest (bool silent) inline static
References alglib.testdforestunit.basictest1(), alglib.testdforestunit.basictest2(), alglib.testdforestunit.basictest3(), alglib.testdforestunit.basictest4(), alglib.testdforestunit.basictest5(), and alglib.testdforestunit.testprocessing().
Referenced by alglib.testdforestunit._pexec_testdforest(), and _Test.Main().
static void alglib.testdforestunit.testprocessing (ref bool err) inline static private
References alglib.serializer.alloc_start(), alglib.dforest.dfalloc(), alglib.dforest.dfbuildinternal(), alglib.dforest.dfcopy(), alglib.dforest.dfprocess(), alglib.dforest.dfserialize(), alglib.dforest.dfunserialize(), alglib.serializer.get_string(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.serializer.sstart_str(), alglib.serializer.stop(), alglib.testdforestunit.unsetdf(), and alglib.serializer.ustart_str().
Referenced by alglib.testdforestunit.testdforest().
static void alglib.testdforestunit.basictest1 (int nvars, int nclasses, int passcount, ref bool err) inline static private
References alglib.dforest.dfbuildinternal(), alglib.dforest.dfprocess(), alglib.math.machineepsilon, alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testdforestunit.testdforest().
static void alglib.testdforestunit.basictest2 (ref bool err) inline static private
References alglib.dforest.dfbuildinternal(), alglib.dforest.dfprocess(), alglib.math.machineepsilon, and alglib.math.randomreal().
Referenced by alglib.testdforestunit.testdforest().
static void alglib.testdforestunit.basictest3 (ref bool err) inline static private
References alglib.dforest.dfbuildinternal(), alglib.dforest.dfprocess(), alglib.math.machineepsilon, alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testdforestunit.testdforest().
static void alglib.testdforestunit.basictest4 (ref bool err) inline static private
References alglib.dforest.dfbuildinternal(), alglib.dforest.dfprocess(), alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testdforestunit.testdforest().
static void alglib.testdforestunit.basictest5 (ref bool err) inline static private
References alglib.dforest.dfbuildinternal(), alglib.dforest.dfprocess(), and alglib.math.machineepsilon.
Referenced by alglib.testdforestunit.testdforest().
static double alglib.testdforestunit.rnormal () inline static private
References alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testdforestunit.rsphere().
static void alglib.testdforestunit.rsphere (ref double xy[,], int n, int i) inline static private
References alglib.math.randomreal(), and alglib.testdforestunit.rnormal().
static void alglib.testdforestunit.unsetdf (dforest.decisionforest df) inline static private
References alglib.dforest.dfbuildinternal().
Referenced by alglib.testdforestunit.testprocessing().
static bool alglib.testdforestunit.testdforest (bool silent) inline static
References alglib.testdforestunit.basictest1(), alglib.testdforestunit.basictest2(), alglib.testdforestunit.basictest3(), alglib.testdforestunit.basictest4(), alglib.testdforestunit.basictest5(), and alglib.testdforestunit.testprocessing().
static bool alglib.testdforestunit._pexec_testdforest (bool silent) inline static
References alglib.testdforestunit.testdforest().
Referenced by _Test.Main().
static void alglib.testdforestunit.testprocessing (ref bool err) inline static private
References alglib.serializer.alloc_start(), alglib.dforest.dfalloc(), alglib.dforest.dfbuildinternal(), alglib.dforest.dfcopy(), alglib.dforest.dfprocess(), alglib.dforest.dfserialize(), alglib.dforest.dfunserialize(), alglib.serializer.get_string(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.serializer.sstart_str(), alglib.serializer.stop(), alglib.testdforestunit.unsetdf(), and alglib.serializer.ustart_str().
static void alglib.testdforestunit.basictest1 (int nvars, int nclasses, int passcount, ref bool err) inline static private
References alglib.dforest.dfbuildinternal(), alglib.dforest.dfprocess(), alglib.math.machineepsilon, alglib.math.randominteger(), and alglib.math.randomreal().
static void alglib.testdforestunit.basictest2 (ref bool err) inline static private
References alglib.dforest.dfbuildinternal(), alglib.dforest.dfprocess(), alglib.math.machineepsilon, and alglib.math.randomreal().
static void alglib.testdforestunit.basictest3 (ref bool err) inline static private
References alglib.dforest.dfbuildinternal(), alglib.dforest.dfprocess(), alglib.math.machineepsilon, alglib.math.randomreal(), and alglib.math.sqr().
static void alglib.testdforestunit.basictest4 (ref bool err) inline static private
References alglib.dforest.dfbuildinternal(), alglib.dforest.dfprocess(), alglib.math.randomreal(), and alglib.math.sqr().
static void alglib.testdforestunit.basictest5 (ref bool err) inline static private
References alglib.dforest.dfbuildinternal(), alglib.dforest.dfprocess(), and alglib.math.machineepsilon.
static double alglib.testdforestunit.rnormal () inline static private
References alglib.math.randomreal(), and alglib.math.sqr().
static void alglib.testdforestunit.rsphere (ref double xy[,], int n, int i) inline static private
References alglib.math.randomreal(), and alglib.testdforestunit.rnormal().
static void alglib.testdforestunit.unsetdf (dforest.decisionforest df) inline static private
References alglib.dforest.dfbuildinternal().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs