IGLib: NUnit.Engine.Services.ExtensionService Class Reference
NUnit.Engine.Services.ExtensionService Class Reference
The ExtensionService discovers ExtensionPoints and Extensions and maintains them in a database. It can return extension nodes or actual extension objects on request.
Public Member Functions
ExtensionPoint GetExtensionPoint (string path)
Get an ExtensionPoint based on it's unique identifying path.
ExtensionPoint GetExtensionPoint (Type type)
Get an ExtensionPoint based on the required Type for extensions.
ExtensionPoint GetExtensionPoint (TypeReference type)
Get an ExtensionPoint based on a Cecil TypeReference.
IEnumerable< ExtensionNode > GetExtensionNodes (string path)
ExtensionNode GetExtensionNode (string path)
IEnumerable< ExtensionNode > GetExtensionNodes< T > ()
IEnumerable< T > GetExtensions< T > ()
override void StartService ()
Initialize the Service
Public Member Functions inherited from NUnit.Engine.Services.Service
virtual void StopService ()
Do any cleanup needed before terminating the service
void Dispose ()
Properties
IEnumerable< ExtensionPoint > ExtensionPoints [get]
IEnumerable< ExtensionNode > Extensions [get]
Properties inherited from NUnit.Engine.Services.Service
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get, protected set]
Gets the ServiceStatus of this service
Properties inherited from NUnit.Engine.IService
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get]
Gets the ServiceStatus of this service
Private Member Functions
void FindExtensionPoints (Assembly assembly)
Find the extension points in a loaded assembly
ExtensionPoint DeduceExtensionPointFromType (TypeReference typeRef)
Deduce the extension point based on the Type of an extension. Returns null if no extension point can be found that would be satisfied by the provided Type.
void FindExtensionsInDirectory (DirectoryInfo startDir)
Scans a directory for addins. Note that assemblies in the directory are only scanned if no file of type .addins is found. If such a file is found, then those assemblies it references are scanned.
void ProcessAddinsFile (DirectoryInfo baseDir, string fileName)
Process a .addins type file. The file contains one entry per line. Each entry may be a directory to scan, an assembly path or a wildcard pattern used to find assemblies. Blank lines and comments started by # are ignored.
void FindExtensionsInAssembly (string assemblyName)
Scan a single assembly for extensions marked by ExtensionAttribute. For each extension, create an ExtensionNode and link it to the correct ExtensionPoint.
Private Attributes
List< ExtensionPoint > _extensionPoints = new List<ExtensionPoint>()
Dictionary< string,
ExtensionPoint > _pathIndex = new Dictionary<string, ExtensionPoint>()
List< ExtensionNode > _extensions = new List<ExtensionNode>()
Additional Inherited Members
Protected Member Functions inherited from NUnit.Engine.Services.Service
virtual void Dispose (bool disposing)
Protected Attributes inherited from NUnit.Engine.Services.Service
bool _disposed = false
Detailed Description
The ExtensionService discovers ExtensionPoints and Extensions and maintains them in a database. It can return extension nodes or actual extension objects on request.
Member Function Documentation
ExtensionPoint NUnit.Engine.Services.ExtensionService.GetExtensionPoint (string path) inline
Get an ExtensionPoint based on it's unique identifying path.
Referenced by NUnit.Engine.Services.Tests.ExtensionServiceTests.CanGetExtensionPointByPath(), NUnit.Engine.Services.Tests.ExtensionServiceTests.CanGetExtensionPointByType(), and NUnit.Engine.Services.Tests.ExtensionServiceTests.ExtensionsAreAddedToExtensionPoint().
ExtensionPoint NUnit.Engine.Services.ExtensionService.GetExtensionPoint (Type type) inline
Get an ExtensionPoint based on the required Type for extensions.
ExtensionPoint NUnit.Engine.Services.ExtensionService.GetExtensionPoint (TypeReference type) inline
Get an ExtensionPoint based on a Cecil TypeReference.
IEnumerable<ExtensionNode> NUnit.Engine.Services.ExtensionService.GetExtensionNodes (string path) inline
Referenced by NUnit.Engine.Services.ResultService.StartService().
ExtensionNode NUnit.Engine.Services.ExtensionService.GetExtensionNode (string path) inline
Referenced by NUnit.Engine.Services.DriverService.StartService().
IEnumerable<ExtensionNode> NUnit.Engine.Services.ExtensionService.GetExtensionNodes< T > () inline
IEnumerable<T> NUnit.Engine.Services.ExtensionService.GetExtensions< T > () inline
override void NUnit.Engine.Services.ExtensionService.StartService () inline virtual
Initialize the Service
Reimplemented from NUnit.Engine.Services.Service.
Referenced by NUnit.Engine.Services.Tests.ExtensionServiceTests.CreateService().
void NUnit.Engine.Services.ExtensionService.FindExtensionPoints (Assembly assembly) inline private
Find the extension points in a loaded assembly
References NUnit.Engine.Extensibility.ExtensionPointAttribute.Description, NUnit.Engine.Extensibility.TypeExtensionPointAttribute.Description, NUnit.Engine.Extensibility.ExtensionPointAttribute.Path, NUnit.Engine.Extensibility.TypeExtensionPointAttribute.Path, and NUnit.Engine.Extensibility.ExtensionPointAttribute.Type.
ExtensionPoint NUnit.Engine.Services.ExtensionService.DeduceExtensionPointFromType (TypeReference typeRef) inline private
Deduce the extension point based on the Type of an extension. Returns null if no extension point can be found that would be satisfied by the provided Type.
void NUnit.Engine.Services.ExtensionService.FindExtensionsInDirectory (DirectoryInfo startDir) inline private
Scans a directory for addins. Note that assemblies in the directory are only scanned if no file of type .addins is found. If such a file is found, then those assemblies it references are scanned.
void NUnit.Engine.Services.ExtensionService.ProcessAddinsFile (DirectoryInfo baseDir, string fileName) inline private
Process a .addins type file. The file contains one entry per line. Each entry may be a directory to scan, an assembly path or a wildcard pattern used to find assemblies. Blank lines and comments started by # are ignored.
void NUnit.Engine.Services.ExtensionService.FindExtensionsInAssembly (string assemblyName) inline private
Scan a single assembly for extensions marked by ExtensionAttribute. For each extension, create an ExtensionNode and link it to the correct ExtensionPoint.
References NUnit.Engine.Extensibility.ExtensionPoint.Install(), and NUnit.Engine.Extensibility.ExtensionPoint.Path.
Member Data Documentation
List<ExtensionPoint> NUnit.Engine.Services.ExtensionService._extensionPoints = new List<ExtensionPoint>() private
Dictionary<string, ExtensionPoint> NUnit.Engine.Services.ExtensionService._pathIndex = new Dictionary<string, ExtensionPoint>() private
List<ExtensionNode> NUnit.Engine.Services.ExtensionService._extensions = new List<ExtensionNode>() private
Property Documentation
IEnumerable<ExtensionPoint> NUnit.Engine.Services.ExtensionService.ExtensionPoints get
Referenced by NUnit.Engine.Services.Tests.ExtensionServiceTests.CanListExtensionPoints().
IEnumerable<ExtensionNode> NUnit.Engine.Services.ExtensionService.Extensions get
Referenced by NUnit.Engine.Services.Tests.ExtensionServiceTests.CanListExtensions().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/ExtensionService.cs