IGLib: NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality Class Reference
NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality Class Reference
Public Member Functions
void CanMatchSpecialFloatingPointValues (object value)
void CanMatchDoublesWithUlpTolerance (object value)
void FailsOnDoublesOutsideOfUlpTolerance (object value)
void CanMatchSinglesWithUlpTolerance (object value)
void FailsOnSinglesOutsideOfUlpTolerance (object value)
void CanMatchDoublesWithRelativeTolerance (object value)
void FailsOnDoublesOutsideOfRelativeTolerance (object value)
void CanMatchSinglesWithRelativeTolerance (object value)
void FailsOnSinglesOutsideOfRelativeTolerance (object value)
void ErrorWithPercentAndUlpsToleranceModes ()
Applies both the Percent and Ulps modifiers to cause an exception
void ErrorWithUlpsAndPercentToleranceModes ()
Applies both the Ulps and Percent modifiers to cause an exception
void ErrorIfPercentPrecedesWithin ()
void ErrorIfUlpsPrecedesWithin ()
void ErrorIfUlpsIsUsedOnIntegralType (object x, object y)
void ErrorIfUlpsIsUsedOnDecimal ()
Member Function Documentation
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.CanMatchSpecialFloatingPointValues (object value) inline
References NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.CanMatchDoublesWithUlpTolerance (object value) inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.Ulps.
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.FailsOnDoublesOutsideOfUlpTolerance (object value) inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.Framework.Constraints.Ulps.
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.CanMatchSinglesWithUlpTolerance (object value) inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.Ulps.
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.FailsOnSinglesOutsideOfUlpTolerance (object value) inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.Framework.Constraints.Ulps.
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.CanMatchDoublesWithRelativeTolerance (object value) inline
References NUnit.Framework.Constraints.Percent, and NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.FailsOnDoublesOutsideOfRelativeTolerance (object value) inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Constraints.Percent, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.CanMatchSinglesWithRelativeTolerance (object value) inline
References NUnit.Framework.Constraints.Percent, and NUnit.Framework.Assert.That().
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.FailsOnSinglesOutsideOfRelativeTolerance (object value) inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Constraints.Percent, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorWithPercentAndUlpsToleranceModes () inline
Applies both the Percent and Ulps modifiers to cause an exception
References NUnit.Framework.Constraints.EqualConstraint.Percent, NUnit.Framework.Assert.Throws(), NUnit.Framework.Constraints.EqualConstraint.Ulps, and NUnit.Framework.Constraints.EqualConstraint.Within().
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorWithUlpsAndPercentToleranceModes () inline
Applies both the Ulps and Percent modifiers to cause an exception
References NUnit.Framework.Constraints.EqualConstraint.Percent, NUnit.Framework.Assert.Throws(), NUnit.Framework.Constraints.EqualConstraint.Ulps, and NUnit.Framework.Constraints.EqualConstraint.Within().
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfPercentPrecedesWithin () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfUlpsPrecedesWithin () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfUlpsIsUsedOnIntegralType (object x, object y) inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Constraints.EqualConstraintTests.FloatingPointEquality.ErrorIfUlpsIsUsedOnDecimal () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs