IGLib: alglib.evd Class Reference
alglib.evd Class Reference
Static Public Member Functions
static bool smatrixevd (double[,] a, int n, int zneeded, bool isupper, ref double[] d, ref double[,] z)
static bool smatrixevdr (double[,] a, int n, int zneeded, bool isupper, double b1, double b2, ref int m, ref double[] w, ref double[,] z)
static bool smatrixevdi (double[,] a, int n, int zneeded, bool isupper, int i1, int i2, ref double[] w, ref double[,] z)
static bool hmatrixevd (complex[,] a, int n, int zneeded, bool isupper, ref double[] d, ref complex[,] z)
static bool hmatrixevdr (complex[,] a, int n, int zneeded, bool isupper, double b1, double b2, ref int m, ref double[] w, ref complex[,] z)
static bool hmatrixevdi (complex[,] a, int n, int zneeded, bool isupper, int i1, int i2, ref double[] w, ref complex[,] z)
static bool smatrixtdevd (ref double[] d, double[] e, int n, int zneeded, ref double[,] z)
static bool smatrixtdevdr (ref double[] d, double[] e, int n, int zneeded, double a, double b, ref int m, ref double[,] z)
static bool smatrixtdevdi (ref double[] d, double[] e, int n, int zneeded, int i1, int i2, ref double[,] z)
static bool rmatrixevd (double[,] a, int n, int vneeded, ref double[] wr, ref double[] wi, ref double[,] vl, ref double[,] vr)
static bool smatrixevd (double[,] a, int n, int zneeded, bool isupper, ref double[] d, ref double[,] z)
static bool smatrixevdr (double[,] a, int n, int zneeded, bool isupper, double b1, double b2, ref int m, ref double[] w, ref double[,] z)
static bool smatrixevdi (double[,] a, int n, int zneeded, bool isupper, int i1, int i2, ref double[] w, ref double[,] z)
static bool hmatrixevd (complex[,] a, int n, int zneeded, bool isupper, ref double[] d, ref complex[,] z)
static bool hmatrixevdr (complex[,] a, int n, int zneeded, bool isupper, double b1, double b2, ref int m, ref double[] w, ref complex[,] z)
static bool hmatrixevdi (complex[,] a, int n, int zneeded, bool isupper, int i1, int i2, ref double[] w, ref complex[,] z)
static bool smatrixtdevd (ref double[] d, double[] e, int n, int zneeded, ref double[,] z)
static bool smatrixtdevdr (ref double[] d, double[] e, int n, int zneeded, double a, double b, ref int m, ref double[,] z)
static bool smatrixtdevdi (ref double[] d, double[] e, int n, int zneeded, int i1, int i2, ref double[,] z)
static bool rmatrixevd (double[,] a, int n, int vneeded, ref double[] wr, ref double[] wi, ref double[,] vl, ref double[,] vr)
Static Private Member Functions
static bool tridiagonalevd (ref double[] d, double[] e, int n, int zneeded, ref double[,] z)
static void tdevde2 (double a, double b, double c, ref double rt1, ref double rt2)
static void tdevdev2 (double a, double b, double c, ref double rt1, ref double rt2, ref double cs1, ref double sn1)
static double tdevdpythag (double a, double b)
static double tdevdextsign (double a, double b)
static bool internalbisectioneigenvalues (double[] d, double[] e, int n, int irange, int iorder, double vl, double vu, int il, int iu, double abstol, ref double[] w, ref int m, ref int nsplit, ref int[] iblock, ref int[] isplit, ref int errorcode)
static void internaldstein (int n, double[] d, double[] e, int m, double[] w, int[] iblock, int[] isplit, ref double[,] z, ref int[] ifail, ref int info)
static void tdininternaldlagtf (int n, ref double[] a, double lambdav, ref double[] b, ref double[] c, double tol, ref double[] d, ref int[] iin, ref int info)
static void tdininternaldlagts (int n, double[] a, double[] b, double[] c, double[] d, int[] iin, ref double[] y, ref double tol, ref int info)
static void internaldlaebz (int ijob, int nitmax, int n, int mmax, int minp, double abstol, double reltol, double pivmin, double[] d, double[] e, double[] e2, ref int[] nval, ref double[,] ab, ref double[] c, ref int mout, ref int[,] nab, ref double[] work, ref int[] iwork, ref int info)
static void internaltrevc (double[,] t, int n, int side, int howmny, bool[] vselect, ref double[,] vl, ref double[,] vr, ref int m, ref int info)
static void internalhsevdlaln2 (bool ltrans, int na, int nw, double smin, double ca, double[,] a, double d1, double d2, double[,] b, double wr, double wi, ref bool[] rswap4, ref bool[] zswap4, ref int[,] ipivot44, ref double[] civ4, ref double[] crv4, ref double[,] x, ref double scl, ref double xnorm, ref int info)
static void internalhsevdladiv (double a, double b, double c, double d, ref double p, ref double q)
static bool nonsymmetricevd (double[,] a, int n, int vneeded, ref double[] wr, ref double[] wi, ref double[,] vl, ref double[,] vr)
static void toupperhessenberg (ref double[,] a, int n, ref double[] tau)
static void unpackqfromupperhessenberg (double[,] a, int n, double[] tau, ref double[,] q)
static bool tridiagonalevd (ref double[] d, double[] e, int n, int zneeded, ref double[,] z)
static void tdevde2 (double a, double b, double c, ref double rt1, ref double rt2)
static void tdevdev2 (double a, double b, double c, ref double rt1, ref double rt2, ref double cs1, ref double sn1)
static double tdevdpythag (double a, double b)
static double tdevdextsign (double a, double b)
static bool internalbisectioneigenvalues (double[] d, double[] e, int n, int irange, int iorder, double vl, double vu, int il, int iu, double abstol, ref double[] w, ref int m, ref int nsplit, ref int[] iblock, ref int[] isplit, ref int errorcode)
static void internaldstein (int n, double[] d, double[] e, int m, double[] w, int[] iblock, int[] isplit, ref double[,] z, ref int[] ifail, ref int info)
static void tdininternaldlagtf (int n, ref double[] a, double lambdav, ref double[] b, ref double[] c, double tol, ref double[] d, ref int[] iin, ref int info)
static void tdininternaldlagts (int n, double[] a, double[] b, double[] c, double[] d, int[] iin, ref double[] y, ref double tol, ref int info)
static void internaldlaebz (int ijob, int nitmax, int n, int mmax, int minp, double abstol, double reltol, double pivmin, double[] d, double[] e, double[] e2, ref int[] nval, ref double[,] ab, ref double[] c, ref int mout, ref int[,] nab, ref double[] work, ref int[] iwork, ref int info)
static void internaltrevc (double[,] t, int n, int side, int howmny, bool[] vselect, ref double[,] vl, ref double[,] vr, ref int m, ref int info)
static void internalhsevdlaln2 (bool ltrans, int na, int nw, double smin, double ca, double[,] a, double d1, double d2, double[,] b, double wr, double wi, ref bool[] rswap4, ref bool[] zswap4, ref int[,] ipivot44, ref double[] civ4, ref double[] crv4, ref double[,] x, ref double scl, ref double xnorm, ref int info)
static void internalhsevdladiv (double a, double b, double c, double d, ref double p, ref double q)
static bool nonsymmetricevd (double[,] a, int n, int vneeded, ref double[] wr, ref double[] wi, ref double[,] vl, ref double[,] vr)
static void toupperhessenberg (ref double[,] a, int n, ref double[] tau)
static void unpackqfromupperhessenberg (double[,] a, int n, double[] tau, ref double[,] q)
Member Function Documentation
static bool alglib.evd.smatrixevd (double a[,], int n, int zneeded, bool isupper, ref double[] d, ref double z[,]) inline static
Referenced by alglib.lda.fisherldan(), alglib.smatrixevd(), alglib.testevdunit.testsevdbiproblem(), alglib.testevdunit.testsevdproblem(), and alglib.testldaunit.testwn().
static bool alglib.evd.smatrixevdr (double a[,], int n, int zneeded, bool isupper, double b1, double b2, ref int m, ref double[] w, ref double z[,]) inline static
Referenced by alglib.smatrixevdr(), and alglib.testevdunit.testsevdbiproblem().
static bool alglib.evd.smatrixevdi (double a[,], int n, int zneeded, bool isupper, int i1, int i2, ref double[] w, ref double z[,]) inline static
Referenced by alglib.smatrixevdi(), and alglib.testevdunit.testsevdbiproblem().
static bool alglib.evd.hmatrixevd (complex a[,], int n, int zneeded, bool isupper, ref double[] d, ref complex z[,]) inline static
Referenced by alglib.hmatrixevd(), alglib.testevdunit.testhevdbiproblem(), and alglib.testevdunit.testhevdproblem().
static bool alglib.evd.hmatrixevdr (complex a[,], int n, int zneeded, bool isupper, double b1, double b2, ref int m, ref double[] w, ref complex z[,]) inline static
Referenced by alglib.hmatrixevdr(), and alglib.testevdunit.testhevdbiproblem().
static bool alglib.evd.hmatrixevdi (complex a[,], int n, int zneeded, bool isupper, int i1, int i2, ref double[] w, ref complex z[,]) inline static
Referenced by alglib.hmatrixevdi(), and alglib.testevdunit.testhevdbiproblem().
static bool alglib.evd.smatrixtdevd (ref double[] d, double[] e, int n, int zneeded, ref double z[,]) inline static
Referenced by alglib.gq.gqgenerategausslobattorec(), alglib.gq.gqgenerategaussradaurec(), alglib.gq.gqgeneraterec(), alglib.smatrixtdevd(), alglib.testevdunit.testtdevdbiproblem(), and alglib.testevdunit.testtdevdproblem().
static bool alglib.evd.smatrixtdevdr (ref double[] d, double[] e, int n, int zneeded, double a, double b, ref int m, ref double z[,]) inline static
Referenced by alglib.smatrixtdevdr(), and alglib.testevdunit.testtdevdbiproblem().
static bool alglib.evd.smatrixtdevdi (ref double[] d, double[] e, int n, int zneeded, int i1, int i2, ref double z[,]) inline static
Referenced by alglib.smatrixtdevdi(), and alglib.testevdunit.testtdevdbiproblem().
static bool alglib.evd.rmatrixevd (double a[,], int n, int vneeded, ref double[] wr, ref double[] wi, ref double vl[,], ref double vr[,]) inline static
Referenced by alglib.rmatrixevd(), and alglib.testevdunit.testnsevdproblem().
static bool alglib.evd.tridiagonalevd (ref double[] d, double[] e, int n, int zneeded, ref double z[,]) inline static private
static void alglib.evd.tdevde2 (double a, double b, double c, ref double rt1, ref double rt2) inline static private
static void alglib.evd.tdevdev2 (double a, double b, double c, ref double rt1, ref double rt2, ref double cs1, ref double sn1) inline static private
static double alglib.evd.tdevdpythag (double a, double b) inline static private
static double alglib.evd.tdevdextsign (double a, double b) inline static private
static bool alglib.evd.internalbisectioneigenvalues (double[] d, double[] e, int n, int irange, int iorder, double vl, double vu, int il, int iu, double abstol, ref double[] w, ref int m, ref int nsplit, ref int[] iblock, ref int[] isplit, ref int errorcode) inline static private
static void alglib.evd.internaldstein (int n, double[] d, double[] e, int m, double[] w, int[] iblock, int[] isplit, ref double z[,], ref int[] ifail, ref int info) inline static private
static void alglib.evd.tdininternaldlagtf (int n, ref double[] a, double lambdav, ref double[] b, ref double[] c, double tol, ref double[] d, ref int[] iin, ref int info) inline static private
static void alglib.evd.tdininternaldlagts (int n, double[] a, double[] b, double[] c, double[] d, int[] iin, ref double[] y, ref double tol, ref int info) inline static private
static void alglib.evd.internaldlaebz (int ijob, int nitmax, int n, int mmax, int minp, double abstol, double reltol, double pivmin, double[] d, double[] e, double[] e2, ref int[] nval, ref double ab[,], ref double[] c, ref int mout, ref int nab[,], ref double[] work, ref int[] iwork, ref int info) inline static private
static void alglib.evd.internaltrevc (double t[,], int n, int side, int howmny, bool[] vselect, ref double vl[,], ref double vr[,], ref int m, ref int info) inline static private
static void alglib.evd.internalhsevdlaln2 (bool ltrans, int na, int nw, double smin, double ca, double a[,], double d1, double d2, double b[,], double wr, double wi, ref bool[] rswap4, ref bool[] zswap4, ref int ipivot44[,], ref double[] civ4, ref double[] crv4, ref double x[,], ref double scl, ref double xnorm, ref int info) inline static private
static void alglib.evd.internalhsevdladiv (double a, double b, double c, double d, ref double p, ref double q) inline static private
static bool alglib.evd.nonsymmetricevd (double a[,], int n, int vneeded, ref double[] wr, ref double[] wi, ref double vl[,], ref double vr[,]) inline static private
static void alglib.evd.toupperhessenberg (ref double a[,], int n, ref double[] tau) inline static private
static void alglib.evd.unpackqfromupperhessenberg (double a[,], int n, double[] tau, ref double q[,]) inline static private
static bool alglib.evd.smatrixevd (double a[,], int n, int zneeded, bool isupper, ref double[] d, ref double z[,]) inline static
static bool alglib.evd.smatrixevdr (double a[,], int n, int zneeded, bool isupper, double b1, double b2, ref int m, ref double[] w, ref double z[,]) inline static
static bool alglib.evd.smatrixevdi (double a[,], int n, int zneeded, bool isupper, int i1, int i2, ref double[] w, ref double z[,]) inline static
static bool alglib.evd.hmatrixevd (complex a[,], int n, int zneeded, bool isupper, ref double[] d, ref complex z[,]) inline static
static bool alglib.evd.hmatrixevdr (complex a[,], int n, int zneeded, bool isupper, double b1, double b2, ref int m, ref double[] w, ref complex z[,]) inline static
static bool alglib.evd.hmatrixevdi (complex a[,], int n, int zneeded, bool isupper, int i1, int i2, ref double[] w, ref complex z[,]) inline static
static bool alglib.evd.smatrixtdevd (ref double[] d, double[] e, int n, int zneeded, ref double z[,]) inline static
static bool alglib.evd.smatrixtdevdr (ref double[] d, double[] e, int n, int zneeded, double a, double b, ref int m, ref double z[,]) inline static
static bool alglib.evd.smatrixtdevdi (ref double[] d, double[] e, int n, int zneeded, int i1, int i2, ref double z[,]) inline static
static bool alglib.evd.rmatrixevd (double a[,], int n, int vneeded, ref double[] wr, ref double[] wi, ref double vl[,], ref double vr[,]) inline static
static bool alglib.evd.tridiagonalevd (ref double[] d, double[] e, int n, int zneeded, ref double z[,]) inline static private
static void alglib.evd.tdevde2 (double a, double b, double c, ref double rt1, ref double rt2) inline static private
static void alglib.evd.tdevdev2 (double a, double b, double c, ref double rt1, ref double rt2, ref double cs1, ref double sn1) inline static private
static double alglib.evd.tdevdpythag (double a, double b) inline static private
static double alglib.evd.tdevdextsign (double a, double b) inline static private
static bool alglib.evd.internalbisectioneigenvalues (double[] d, double[] e, int n, int irange, int iorder, double vl, double vu, int il, int iu, double abstol, ref double[] w, ref int m, ref int nsplit, ref int[] iblock, ref int[] isplit, ref int errorcode) inline static private
static void alglib.evd.internaldstein (int n, double[] d, double[] e, int m, double[] w, int[] iblock, int[] isplit, ref double z[,], ref int[] ifail, ref int info) inline static private
static void alglib.evd.tdininternaldlagtf (int n, ref double[] a, double lambdav, ref double[] b, ref double[] c, double tol, ref double[] d, ref int[] iin, ref int info) inline static private
static void alglib.evd.tdininternaldlagts (int n, double[] a, double[] b, double[] c, double[] d, int[] iin, ref double[] y, ref double tol, ref int info) inline static private
static void alglib.evd.internaldlaebz (int ijob, int nitmax, int n, int mmax, int minp, double abstol, double reltol, double pivmin, double[] d, double[] e, double[] e2, ref int[] nval, ref double ab[,], ref double[] c, ref int mout, ref int nab[,], ref double[] work, ref int[] iwork, ref int info) inline static private
static void alglib.evd.internaltrevc (double t[,], int n, int side, int howmny, bool[] vselect, ref double vl[,], ref double vr[,], ref int m, ref int info) inline static private
static void alglib.evd.internalhsevdlaln2 (bool ltrans, int na, int nw, double smin, double ca, double a[,], double d1, double d2, double b[,], double wr, double wi, ref bool[] rswap4, ref bool[] zswap4, ref int ipivot44[,], ref double[] civ4, ref double[] crv4, ref double x[,], ref double scl, ref double xnorm, ref int info) inline static private
static void alglib.evd.internalhsevdladiv (double a, double b, double c, double d, ref double p, ref double q) inline static private
static bool alglib.evd.nonsymmetricevd (double a[,], int n, int vneeded, ref double[] wr, ref double[] wi, ref double vl[,], ref double vr[,]) inline static private
static void alglib.evd.toupperhessenberg (ref double a[,], int n, ref double[] tau) inline static private
static void alglib.evd.unpackqfromupperhessenberg (double a[,], int n, double[] tau, ref double q[,]) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/linalg.cs