IGLib: alglib.bessel Class Reference
alglib.bessel Class Reference
Static Public Member Functions
static double besselj0 (double x)
static double besselj1 (double x)
static double besseljn (int n, double x)
static double bessely0 (double x)
static double bessely1 (double x)
static double besselyn (int n, double x)
static double besseli0 (double x)
static double besseli1 (double x)
static double besselk0 (double x)
static double besselk1 (double x)
static double besselkn (int nn, double x)
static double besselj0 (double x)
static double besselj1 (double x)
static double besseljn (int n, double x)
static double bessely0 (double x)
static double bessely1 (double x)
static double besselyn (int n, double x)
static double besseli0 (double x)
static double besseli1 (double x)
static double besselk0 (double x)
static double besselk1 (double x)
static double besselkn (int nn, double x)
Static Private Member Functions
static void besselmfirstcheb (double c, ref double b0, ref double b1, ref double b2)
static void besselmnextcheb (double x, double c, ref double b0, ref double b1, ref double b2)
static void besselm1firstcheb (double c, ref double b0, ref double b1, ref double b2)
static void besselm1nextcheb (double x, double c, ref double b0, ref double b1, ref double b2)
static void besselasympt0 (double x, ref double pzero, ref double qzero)
static void besselasympt1 (double x, ref double pzero, ref double qzero)
static void besselmfirstcheb (double c, ref double b0, ref double b1, ref double b2)
static void besselmnextcheb (double x, double c, ref double b0, ref double b1, ref double b2)
static void besselm1firstcheb (double c, ref double b0, ref double b1, ref double b2)
static void besselm1nextcheb (double x, double c, ref double b0, ref double b1, ref double b2)
static void besselasympt0 (double x, ref double pzero, ref double qzero)
static void besselasympt1 (double x, ref double pzero, ref double qzero)
Member Function Documentation
static double alglib.bessel.besselj0 (double x) inline static
References alglib.bessel.besselasympt0(), and alglib.math.sqr().
Referenced by alglib.besselj0(), alglib.bessel.besseljn(), and alglib.bessel.bessely0().
static double alglib.bessel.besselj1 (double x) inline static
References alglib.bessel.besselasympt1(), and alglib.math.sqr().
Referenced by alglib.besselj1(), alglib.bessel.besseljn(), and alglib.bessel.bessely1().
static double alglib.bessel.besseljn (int n, double x) inline static
References alglib.bessel.besselj0(), alglib.bessel.besselj1(), and alglib.math.machineepsilon.
Referenced by alglib.besseljn().
static double alglib.bessel.bessely0 (double x) inline static
References alglib.bessel.besselasympt0(), alglib.bessel.besselj0(), and alglib.math.sqr().
Referenced by alglib.bessely0(), and alglib.bessel.besselyn().
static double alglib.bessel.bessely1 (double x) inline static
References alglib.bessel.besselasympt1(), alglib.bessel.besselj1(), and alglib.math.sqr().
Referenced by alglib.bessely1(), and alglib.bessel.besselyn().
static double alglib.bessel.besselyn (int n, double x) inline static
References alglib.bessel.bessely0(), and alglib.bessel.bessely1().
Referenced by alglib.besselyn().
static double alglib.bessel.besseli0 (double x) inline static
References alglib.bessel.besselmfirstcheb(), and alglib.bessel.besselmnextcheb().
Referenced by alglib.besseli0(), and alglib.bessel.besselk0().
static double alglib.bessel.besseli1 (double x) inline static
References alglib.bessel.besselm1firstcheb(), and alglib.bessel.besselm1nextcheb().
Referenced by alglib.besseli1(), and alglib.bessel.besselk1().
static double alglib.bessel.besselk0 (double x) inline static
References alglib.ap.assert(), alglib.bessel.besseli0(), alglib.bessel.besselmfirstcheb(), and alglib.bessel.besselmnextcheb().
Referenced by alglib.besselk0().
static double alglib.bessel.besselk1 (double x) inline static
References alglib.ap.assert(), alglib.bessel.besseli1(), alglib.bessel.besselm1firstcheb(), and alglib.bessel.besselm1nextcheb().
Referenced by alglib.besselk1().
static double alglib.bessel.besselkn (int nn, double x) inline static
References alglib.ap.assert(), alglib.math.machineepsilon, and alglib.math.maxrealnumber.
Referenced by alglib.besselkn().
static void alglib.bessel.besselmfirstcheb (double c, ref double b0, ref double b1, ref double b2) inline static private
Referenced by alglib.bessel.besseli0(), and alglib.bessel.besselk0().
static void alglib.bessel.besselmnextcheb (double x, double c, ref double b0, ref double b1, ref double b2) inline static private
Referenced by alglib.bessel.besseli0(), and alglib.bessel.besselk0().
static void alglib.bessel.besselm1firstcheb (double c, ref double b0, ref double b1, ref double b2) inline static private
Referenced by alglib.bessel.besseli1(), and alglib.bessel.besselk1().
static void alglib.bessel.besselm1nextcheb (double x, double c, ref double b0, ref double b1, ref double b2) inline static private
Referenced by alglib.bessel.besseli1(), and alglib.bessel.besselk1().
static void alglib.bessel.besselasympt0 (double x, ref double pzero, ref double qzero) inline static private
Referenced by alglib.bessel.besselj0(), and alglib.bessel.bessely0().
static void alglib.bessel.besselasympt1 (double x, ref double pzero, ref double qzero) inline static private
Referenced by alglib.bessel.besselj1(), and alglib.bessel.bessely1().
static double alglib.bessel.besselj0 (double x) inline static
References alglib.bessel.besselasympt0(), and alglib.math.sqr().
static double alglib.bessel.besselj1 (double x) inline static
References alglib.bessel.besselasympt1(), and alglib.math.sqr().
static double alglib.bessel.besseljn (int n, double x) inline static
References alglib.bessel.besselj0(), alglib.bessel.besselj1(), and alglib.math.machineepsilon.
static double alglib.bessel.bessely0 (double x) inline static
References alglib.bessel.besselasympt0(), alglib.bessel.besselj0(), and alglib.math.sqr().
static double alglib.bessel.bessely1 (double x) inline static
References alglib.bessel.besselasympt1(), alglib.bessel.besselj1(), and alglib.math.sqr().
static double alglib.bessel.besselyn (int n, double x) inline static
References alglib.bessel.bessely0(), and alglib.bessel.bessely1().
static double alglib.bessel.besseli0 (double x) inline static
References alglib.bessel.besselmfirstcheb(), and alglib.bessel.besselmnextcheb().
static double alglib.bessel.besseli1 (double x) inline static
References alglib.bessel.besselm1firstcheb(), and alglib.bessel.besselm1nextcheb().
static double alglib.bessel.besselk0 (double x) inline static
References alglib.ap.assert(), alglib.bessel.besseli0(), alglib.bessel.besselmfirstcheb(), and alglib.bessel.besselmnextcheb().
static double alglib.bessel.besselk1 (double x) inline static
References alglib.ap.assert(), alglib.bessel.besseli1(), alglib.bessel.besselm1firstcheb(), and alglib.bessel.besselm1nextcheb().
static double alglib.bessel.besselkn (int nn, double x) inline static
References alglib.ap.assert(), alglib.math.machineepsilon, and alglib.math.maxrealnumber.
static void alglib.bessel.besselmfirstcheb (double c, ref double b0, ref double b1, ref double b2) inline static private
static void alglib.bessel.besselmnextcheb (double x, double c, ref double b0, ref double b1, ref double b2) inline static private
static void alglib.bessel.besselm1firstcheb (double c, ref double b0, ref double b1, ref double b2) inline static private
static void alglib.bessel.besselm1nextcheb (double x, double c, ref double b0, ref double b1, ref double b2) inline static private
static void alglib.bessel.besselasympt0 (double x, ref double pzero, ref double qzero) inline static private
static void alglib.bessel.besselasympt1 (double x, ref double pzero, ref double qzero) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/specialfunctions.cs