IGLib: NUnit.Engine.Services.RecentFilesService Class Reference
NUnit.Engine.Services.RecentFilesService Class Reference
Summary description for RecentFilesService.
Public Member Functions
void Remove (string fileName)
Remove a file from the list
void SetMostRecent (string filePath)
Set the most recent file name, reordering the saved names as needed and removing the oldest if the max number of files would be exceeded. The current CLR version is used to create the entry.
override void StopService ()
Do any cleanup needed before terminating the service
override void StartService ()
Initialize the Service
Public Member Functions inherited from NUnit.Engine.Services.Service
void Dispose ()
Properties
int MaxFiles [get, set]
IList< string > Entries [get]
Properties inherited from NUnit.Engine.Services.Service
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get, protected set]
Gets the ServiceStatus of this service
Properties inherited from NUnit.Engine.IService
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get]
Gets the ServiceStatus of this service
Properties inherited from NUnit.Engine.IRecentFiles
int MaxFiles [get, set]
The max number of files saved
IList< string > Entries [get]
Get a list of all the file entries
Private Member Functions
void LoadEntriesFromSettings ()
void AddEntriesForPrefix (string prefix)
void SaveEntriesToSettings ()
string GetRecentFileKey (string prefix, int index)
Private Attributes
IList< string > _fileEntries = new List<string>()
ISettings _userSettings
const int MinSize = 0
const int MaxSize = 24
const int DefaultSize = 5
Additional Inherited Members
Protected Member Functions inherited from NUnit.Engine.Services.Service
virtual void Dispose (bool disposing)
Protected Attributes inherited from NUnit.Engine.Services.Service
bool _disposed = false
Detailed Description
Summary description for RecentFilesService.
Member Function Documentation
void NUnit.Engine.Services.RecentFilesService.Remove (string fileName) inline
Remove a file from the list
Parameters
fileName The name of the file to remove
Implements NUnit.Engine.IRecentFiles.
Referenced by NUnit.Engine.Services.Tests.RecentFilesTests.RemoveFirstProject(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveLastProject(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveMultipleProjects(), and NUnit.Engine.Services.Tests.RecentFilesTests.RemoveOneProject().
void NUnit.Engine.Services.RecentFilesService.SetMostRecent (string fileName) inline
Set the most recent file name, reordering the saved names as needed and removing the oldest if the max number of files would be exceeded. The current CLR version is used to create the entry.
Implements NUnit.Engine.IRecentFiles.
Referenced by NUnit.Engine.Services.Tests.RecentFilesTests.IncreaseSizeAfterAdd(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderLastProject(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderMultipleProjects(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderSameProject(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderSingleProject(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderWithListNotFull(), and NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues().
void NUnit.Engine.Services.RecentFilesService.LoadEntriesFromSettings () inline private
void NUnit.Engine.Services.RecentFilesService.AddEntriesForPrefix (string prefix) inline private
References NUnit.Engine.ISettings.GetSetting().
void NUnit.Engine.Services.RecentFilesService.SaveEntriesToSettings () inline private
References NUnit.Engine.ISettings.RemoveGroup(), NUnit.Engine.ISettings.RemoveSetting(), and NUnit.Engine.ISettings.SaveSetting().
string NUnit.Engine.Services.RecentFilesService.GetRecentFileKey (string prefix, int index) inline private
override void NUnit.Engine.Services.RecentFilesService.StopService () inline virtual
Do any cleanup needed before terminating the service
Reimplemented from NUnit.Engine.Services.Service.
override void NUnit.Engine.Services.RecentFilesService.StartService () inline virtual
Initialize the Service
Reimplemented from NUnit.Engine.Services.Service.
References NUnit.Engine.ServiceContext.GetService().
Member Data Documentation
IList<string> NUnit.Engine.Services.RecentFilesService._fileEntries = new List<string>() private
ISettings NUnit.Engine.Services.RecentFilesService._userSettings private
const int NUnit.Engine.Services.RecentFilesService.MinSize = 0 private
const int NUnit.Engine.Services.RecentFilesService.MaxSize = 24 private
const int NUnit.Engine.Services.RecentFilesService.DefaultSize = 5 private
Property Documentation
int NUnit.Engine.Services.RecentFilesService.MaxFiles get set
Referenced by NUnit.Engine.Services.Tests.RecentFilesTests.CheckAddItems(), NUnit.Engine.Services.Tests.RecentFilesTests.CountAtMax(), NUnit.Engine.Services.Tests.RecentFilesTests.CountAtMin(), NUnit.Engine.Services.Tests.RecentFilesTests.CountDefault(), NUnit.Engine.Services.Tests.RecentFilesTests.CountOverMax(), NUnit.Engine.Services.Tests.RecentFilesTests.CountUnderMin(), NUnit.Engine.Services.Tests.RecentFilesTests.IncreaseSize(), NUnit.Engine.Services.Tests.RecentFilesTests.IncreaseSizeAfterAdd(), NUnit.Engine.Services.Tests.RecentFilesTests.ReduceSize(), and NUnit.Engine.Services.Tests.RecentFilesTests.ReduceSizeAfterAdd().
IList<string> NUnit.Engine.Services.RecentFilesService.Entries get
Referenced by NUnit.Engine.Services.Tests.RecentFilesTests.CheckAddItems(), NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains(), NUnit.Engine.Services.Tests.RecentFilesTests.CheckMockValues(), and NUnit.Engine.Services.Tests.RecentFilesTests.EmptyList().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/RecentFilesService.cs