IGLib: alglib.ablasf Class Reference
alglib.ablasf Class Reference
Static Public Member Functions
static bool cmatrixrank1f (int m, int n, ref complex[,] a, int ia, int ja, ref complex[] u, int iu, ref complex[] v, int iv)
static bool rmatrixrank1f (int m, int n, ref double[,] a, int ia, int ja, ref double[] u, int iu, ref double[] v, int iv)
static bool cmatrixmvf (int m, int n, complex[,] a, int ia, int ja, int opa, complex[] x, int ix, ref complex[] y, int iy)
static bool rmatrixmvf (int m, int n, double[,] a, int ia, int ja, int opa, double[] x, int ix, ref double[] y, int iy)
static bool cmatrixrighttrsmf (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref complex[,] x, int i2, int j2)
static bool cmatrixlefttrsmf (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref complex[,] x, int i2, int j2)
static bool rmatrixrighttrsmf (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref double[,] x, int i2, int j2)
static bool rmatrixlefttrsmf (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref double[,] x, int i2, int j2)
static bool cmatrixsyrkf (int n, int k, double alpha, complex[,] a, int ia, int ja, int optypea, double beta, ref complex[,] c, int ic, int jc, bool isupper)
static bool rmatrixsyrkf (int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double beta, ref double[,] c, int ic, int jc, bool isupper)
static bool rmatrixgemmf (int m, int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double[,] b, int ib, int jb, int optypeb, double beta, ref double[,] c, int ic, int jc)
static bool cmatrixgemmf (int m, int n, int k, complex alpha, complex[,] a, int ia, int ja, int optypea, complex[,] b, int ib, int jb, int optypeb, complex beta, ref complex[,] c, int ic, int jc)
static bool cmatrixrank1f (int m, int n, ref complex[,] a, int ia, int ja, ref complex[] u, int iu, ref complex[] v, int iv)
static bool rmatrixrank1f (int m, int n, ref double[,] a, int ia, int ja, ref double[] u, int iu, ref double[] v, int iv)
static bool cmatrixmvf (int m, int n, complex[,] a, int ia, int ja, int opa, complex[] x, int ix, ref complex[] y, int iy)
static bool rmatrixmvf (int m, int n, double[,] a, int ia, int ja, int opa, double[] x, int ix, ref double[] y, int iy)
static bool cmatrixrighttrsmf (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, complex[,] x, int i2, int j2)
static bool cmatrixlefttrsmf (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, complex[,] x, int i2, int j2)
static bool rmatrixrighttrsmf (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, double[,] x, int i2, int j2)
static bool rmatrixlefttrsmf (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, double[,] x, int i2, int j2)
static bool cmatrixsyrkf (int n, int k, double alpha, complex[,] a, int ia, int ja, int optypea, double beta, complex[,] c, int ic, int jc, bool isupper)
static bool rmatrixsyrkf (int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double beta, double[,] c, int ic, int jc, bool isupper)
static bool rmatrixgemmf (int m, int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double[,] b, int ib, int jb, int optypeb, double beta, double[,] c, int ic, int jc)
static bool cmatrixgemmf (int m, int n, int k, complex alpha, complex[,] a, int ia, int ja, int optypea, complex[,] b, int ib, int jb, int optypeb, complex beta, complex[,] c, int ic, int jc)
static void cmatrixgemmk (int m, int n, int k, complex alpha, complex[,] a, int ia, int ja, int optypea, complex[,] b, int ib, int jb, int optypeb, complex beta, complex[,] c, int ic, int jc)
static void rmatrixgemmk (int m, int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double[,] b, int ib, int jb, int optypeb, double beta, double[,] c, int ic, int jc)
static void rmatrixgemmk44v00 (int m, int n, int k, double alpha, double[,] a, int ia, int ja, double[,] b, int ib, int jb, double beta, double[,] c, int ic, int jc)
static void rmatrixgemmk44v01 (int m, int n, int k, double alpha, double[,] a, int ia, int ja, double[,] b, int ib, int jb, double beta, double[,] c, int ic, int jc)
static void rmatrixgemmk44v10 (int m, int n, int k, double alpha, double[,] a, int ia, int ja, double[,] b, int ib, int jb, double beta, double[,] c, int ic, int jc)
static void rmatrixgemmk44v11 (int m, int n, int k, double alpha, double[,] a, int ia, int ja, double[,] b, int ib, int jb, double beta, double[,] c, int ic, int jc)
Member Function Documentation
static bool alglib.ablasf.cmatrixrank1f (int m, int n, ref complex a[,], int ia, int ja, ref complex[] u, int iu, ref complex[] v, int iv) inline static
Referenced by alglib.ablas.cmatrixrank1().
static bool alglib.ablasf.rmatrixrank1f (int m, int n, ref double a[,], int ia, int ja, ref double[] u, int iu, ref double[] v, int iv) inline static
Referenced by alglib.ablas.rmatrixrank1().
static bool alglib.ablasf.cmatrixmvf (int m, int n, complex a[,], int ia, int ja, int opa, complex[] x, int ix, ref complex[] y, int iy) inline static
Referenced by alglib.ablas.cmatrixmv().
static bool alglib.ablasf.rmatrixmvf (int m, int n, double a[,], int ia, int ja, int opa, double[] x, int ix, ref double[] y, int iy) inline static
Referenced by alglib.ablas.rmatrixmv().
static bool alglib.ablasf.cmatrixrighttrsmf (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref complex x[,], int i2, int j2) inline static
Referenced by alglib.ablas.cmatrixrighttrsm2().
static bool alglib.ablasf.cmatrixlefttrsmf (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref complex x[,], int i2, int j2) inline static
Referenced by alglib.ablas.cmatrixlefttrsm2().
static bool alglib.ablasf.rmatrixrighttrsmf (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref double x[,], int i2, int j2) inline static
Referenced by alglib.ablas.rmatrixrighttrsm2().
static bool alglib.ablasf.rmatrixlefttrsmf (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref double x[,], int i2, int j2) inline static
Referenced by alglib.ablas.rmatrixlefttrsm2().
static bool alglib.ablasf.cmatrixsyrkf (int n, int k, double alpha, complex a[,], int ia, int ja, int optypea, double beta, ref complex c[,], int ic, int jc, bool isupper) inline static
Referenced by alglib.ablas.cmatrixsyrk2().
static bool alglib.ablasf.rmatrixsyrkf (int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double beta, ref double c[,], int ic, int jc, bool isupper) inline static
Referenced by alglib.ablas.rmatrixsyrk2().
static bool alglib.ablasf.rmatrixgemmf (int m, int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double b[,], int ib, int jb, int optypeb, double beta, ref double c[,], int ic, int jc) inline static
Referenced by alglib.ablasf.rmatrixgemmk(), and alglib.ablas.rmatrixgemmk().
static bool alglib.ablasf.cmatrixgemmf (int m, int n, int k, complex alpha, complex a[,], int ia, int ja, int optypea, complex b[,], int ib, int jb, int optypeb, complex beta, ref complex c[,], int ic, int jc) inline static
Referenced by alglib.ablasf.cmatrixgemmk(), and alglib.ablas.cmatrixgemmk().
static bool alglib.ablasf.cmatrixrank1f (int m, int n, ref complex a[,], int ia, int ja, ref complex[] u, int iu, ref complex[] v, int iv) inline static
static bool alglib.ablasf.rmatrixrank1f (int m, int n, ref double a[,], int ia, int ja, ref double[] u, int iu, ref double[] v, int iv) inline static
static bool alglib.ablasf.cmatrixmvf (int m, int n, complex a[,], int ia, int ja, int opa, complex[] x, int ix, ref complex[] y, int iy) inline static
static bool alglib.ablasf.rmatrixmvf (int m, int n, double a[,], int ia, int ja, int opa, double[] x, int ix, ref double[] y, int iy) inline static
static bool alglib.ablasf.cmatrixrighttrsmf (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, complex x[,], int i2, int j2) inline static
static bool alglib.ablasf.cmatrixlefttrsmf (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, complex x[,], int i2, int j2) inline static
static bool alglib.ablasf.rmatrixrighttrsmf (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, double x[,], int i2, int j2) inline static
static bool alglib.ablasf.rmatrixlefttrsmf (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, double x[,], int i2, int j2) inline static
static bool alglib.ablasf.cmatrixsyrkf (int n, int k, double alpha, complex a[,], int ia, int ja, int optypea, double beta, complex c[,], int ic, int jc, bool isupper) inline static
static bool alglib.ablasf.rmatrixsyrkf (int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double beta, double c[,], int ic, int jc, bool isupper) inline static
static bool alglib.ablasf.rmatrixgemmf (int m, int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double b[,], int ib, int jb, int optypeb, double beta, double c[,], int ic, int jc) inline static
static bool alglib.ablasf.cmatrixgemmf (int m, int n, int k, complex alpha, complex a[,], int ia, int ja, int optypea, complex b[,], int ib, int jb, int optypeb, complex beta, complex c[,], int ic, int jc) inline static
static void alglib.ablasf.cmatrixgemmk (int m, int n, int k, complex alpha, complex a[,], int ia, int ja, int optypea, complex b[,], int ib, int jb, int optypeb, complex beta, complex c[,], int ic, int jc) inline static
References alglib.ablasf.cmatrixgemmf(), alglib.math.conj(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.ablas.cmatrixgemm().
static void alglib.ablasf.rmatrixgemmk (int m, int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double b[,], int ib, int jb, int optypeb, double beta, double c[,], int ic, int jc) inline static
References alglib.ablasf.rmatrixgemmf(), alglib.ablasf.rmatrixgemmk44v00(), alglib.ablasf.rmatrixgemmk44v01(), alglib.ablasf.rmatrixgemmk44v10(), and alglib.ablasf.rmatrixgemmk44v11().
Referenced by alglib.ablas.rmatrixgemm().
static void alglib.ablasf.rmatrixgemmk44v00 (int m, int n, int k, double alpha, double a[,], int ia, int ja, double b[,], int ib, int jb, double beta, double c[,], int ic, int jc) inline static
References alglib.ap.assert(), and alglib.beta().
Referenced by alglib.ablasf.rmatrixgemmk().
static void alglib.ablasf.rmatrixgemmk44v01 (int m, int n, int k, double alpha, double a[,], int ia, int ja, double b[,], int ib, int jb, double beta, double c[,], int ic, int jc) inline static
References alglib.ap.assert(), and alglib.beta().
Referenced by alglib.ablasf.rmatrixgemmk().
static void alglib.ablasf.rmatrixgemmk44v10 (int m, int n, int k, double alpha, double a[,], int ia, int ja, double b[,], int ib, int jb, double beta, double c[,], int ic, int jc) inline static
References alglib.ap.assert(), and alglib.beta().
Referenced by alglib.ablasf.rmatrixgemmk().
static void alglib.ablasf.rmatrixgemmk44v11 (int m, int n, int k, double alpha, double a[,], int ia, int ja, double b[,], int ib, int jb, double beta, double c[,], int ic, int jc) inline static
References alglib.ap.assert(), and alglib.beta().
Referenced by alglib.ablasf.rmatrixgemmk().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/alglibinternal.cs