IGLib: NUnit.TestUtilities.TestDelegates Class Reference
NUnit.TestUtilities.TestDelegates Class Reference
Classes
class BaseException
class DerivedException
Static Public Member Functions
static void ThrowsArgumentException ()
static void ThrowsArgumentNullException ()
static void ThrowsNullReferenceException ()
static void ThrowsSystemException ()
static void ThrowsNothing ()
static void ThrowsBaseException ()
static void ThrowsDerivedException ()
Member Function Documentation
static void NUnit.TestUtilities.TestDelegates.ThrowsArgumentException () inline static
Referenced by NUnit.Framework.Assertions.AssertThrowsTests.CorrectExceptionIsReturnedToMethod(), NUnit.Framework.Assertions.AssertThrowsTests.CorrectExceptionThrown(), NUnit.Framework.Assertions.AssertThrowsTests.DerivedExceptionThrown(), and NUnit.Framework.Assertions.AssertThrowsTests.DoesNotThrowFails().
static void NUnit.TestUtilities.TestDelegates.ThrowsArgumentNullException () inline static
Referenced by NUnit.Framework.Tests.ThrowsTests.ArgumentNullException_ConstraintMatchesThrownArgumentNullException().
static void NUnit.TestUtilities.TestDelegates.ThrowsNullReferenceException () inline static
Referenced by NUnit.Framework.Assertions.AssertThrowsTests.UnrelatedExceptionThrown().
static void NUnit.TestUtilities.TestDelegates.ThrowsSystemException () inline static
Referenced by NUnit.Framework.Assertions.AssertThrowsTests.BaseExceptionThrown().
static void NUnit.TestUtilities.TestDelegates.ThrowsNothing () inline static
Referenced by NUnit.Framework.Assertions.AssertThrowsTests.DoesNotThrowSuceeds(), and NUnit.Framework.Assertions.AssertThrowsTests.NoExceptionThrown().
static void NUnit.TestUtilities.TestDelegates.ThrowsBaseException () inline static
static void NUnit.TestUtilities.TestDelegates.ThrowsDerivedException () inline static
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/TestUtilities/TestDelegates.cs