IGLib: alglib.hsschur Class Reference
alglib.hsschur Class Reference
Static Public Member Functions
static bool upperhessenbergschurdecomposition (ref double[,] h, int n, ref double[,] s)
static void internalschurdecomposition (ref double[,] h, int n, int tneeded, int zneeded, ref double[] wr, ref double[] wi, ref double[,] z, ref int info)
static bool upperhessenbergschurdecomposition (ref double[,] h, int n, ref double[,] s)
static void internalschurdecomposition (ref double[,] h, int n, int tneeded, int zneeded, ref double[] wr, ref double[] wi, ref double[,] z, ref int info)
Static Private Member Functions
static void internalauxschur (bool wantt, bool wantz, int n, int ilo, int ihi, ref double[,] h, ref double[] wr, ref double[] wi, int iloz, int ihiz, ref double[,] z, ref double[] work, ref double[] workv3, ref double[] workc1, ref double[] works1, ref int info)
static void aux2x2schur (ref double a, ref double b, ref double c, ref double d, ref double rt1r, ref double rt1i, ref double rt2r, ref double rt2i, ref double cs, ref double sn)
static double extschursign (double a, double b)
static int extschursigntoone (double b)
static void internalauxschur (bool wantt, bool wantz, int n, int ilo, int ihi, ref double[,] h, ref double[] wr, ref double[] wi, int iloz, int ihiz, ref double[,] z, ref double[] work, ref double[] workv3, ref double[] workc1, ref double[] works1, ref int info)
static void aux2x2schur (ref double a, ref double b, ref double c, ref double d, ref double rt1r, ref double rt1i, ref double rt2r, ref double rt2i, ref double cs, ref double sn)
static double extschursign (double a, double b)
static int extschursigntoone (double b)
Member Function Documentation
static bool alglib.hsschur.upperhessenbergschurdecomposition (ref double h[,], int n, ref double s[,]) inline static
References alglib.hsschur.internalschurdecomposition().
static void alglib.hsschur.internalschurdecomposition (ref double h[,], int n, int tneeded, int zneeded, ref double[] wr, ref double[] wi, ref double z[,], ref int info) inline static
References alglib.reflections.applyreflectionfromtheleft(), alglib.reflections.applyreflectionfromtheright(), alglib.ap.assert(), alglib.blas.copymatrix(), alglib.reflections.generatereflection(), alglib.hsschur.internalauxschur(), alglib.math.machineepsilon, alglib.blas.matrixvectormultiply(), alglib.math.minrealnumber, alglib.blas.pythag2(), alglib.blas.upperhessenberg1norm(), and alglib.blas.vectoridxabsmax().
Referenced by alglib.hsschur.upperhessenbergschurdecomposition().
static void alglib.hsschur.internalauxschur (bool wantt, bool wantz, int n, int ilo, int ihi, ref double h[,], ref double[] wr, ref double[] wi, int iloz, int ihiz, ref double z[,], ref double[] work, ref double[] workv3, ref double[] workc1, ref double[] works1, ref int info) inline static private
References alglib.rotations.applyrotationsfromtheleft(), alglib.rotations.applyrotationsfromtheright(), alglib.hsschur.aux2x2schur(), alglib.hsschur.extschursign(), alglib.reflections.generatereflection(), alglib.math.machineepsilon, alglib.math.minrealnumber, and alglib.blas.upperhessenberg1norm().
Referenced by alglib.hsschur.internalschurdecomposition().
static void alglib.hsschur.aux2x2schur (ref double a, ref double b, ref double c, ref double d, ref double rt1r, ref double rt1i, ref double rt2r, ref double rt2i, ref double cs, ref double sn) inline static private
References alglib.hsschur.extschursign(), alglib.hsschur.extschursigntoone(), alglib.math.machineepsilon, and alglib.blas.pythag2().
Referenced by alglib.hsschur.internalauxschur().
static double alglib.hsschur.extschursign (double a, double b) inline static private
Referenced by alglib.hsschur.aux2x2schur(), and alglib.hsschur.internalauxschur().
static int alglib.hsschur.extschursigntoone (double b) inline static private
Referenced by alglib.hsschur.aux2x2schur().
static bool alglib.hsschur.upperhessenbergschurdecomposition (ref double h[,], int n, ref double s[,]) inline static
References alglib.hsschur.internalschurdecomposition().
static void alglib.hsschur.internalschurdecomposition (ref double h[,], int n, int tneeded, int zneeded, ref double[] wr, ref double[] wi, ref double z[,], ref int info) inline static
References alglib.reflections.applyreflectionfromtheleft(), alglib.reflections.applyreflectionfromtheright(), alglib.ap.assert(), alglib.blas.copymatrix(), alglib.reflections.generatereflection(), alglib.hsschur.internalauxschur(), alglib.math.machineepsilon, alglib.blas.matrixvectormultiply(), alglib.math.minrealnumber, alglib.blas.pythag2(), alglib.apserv.touchint(), alglib.blas.upperhessenberg1norm(), and alglib.blas.vectoridxabsmax().
static void alglib.hsschur.internalauxschur (bool wantt, bool wantz, int n, int ilo, int ihi, ref double h[,], ref double[] wr, ref double[] wi, int iloz, int ihiz, ref double z[,], ref double[] work, ref double[] workv3, ref double[] workc1, ref double[] works1, ref int info) inline static private
References alglib.rotations.applyrotationsfromtheleft(), alglib.rotations.applyrotationsfromtheright(), alglib.hsschur.aux2x2schur(), alglib.hsschur.extschursign(), alglib.reflections.generatereflection(), alglib.math.machineepsilon, alglib.math.minrealnumber, and alglib.blas.upperhessenberg1norm().
static void alglib.hsschur.aux2x2schur (ref double a, ref double b, ref double c, ref double d, ref double rt1r, ref double rt1i, ref double rt2r, ref double rt2i, ref double cs, ref double sn) inline static private
References alglib.hsschur.extschursign(), alglib.hsschur.extschursigntoone(), alglib.math.machineepsilon, and alglib.blas.pythag2().
static double alglib.hsschur.extschursign (double a, double b) inline static private
static int alglib.hsschur.extschursigntoone (double b) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/alglibinternal.cs