IGLib: Meta.Numerics.Statistics.Distributions.StudentDistribution Class Reference
Meta.Numerics.Statistics.Distributions.StudentDistribution Class Reference
Represents the distribution of Student't t statistic.
Public Member Functions
StudentDistribution (double nu)
Initializes a new Student distribution.
override double ProbabilityDensity (double x)
Returns the probability density at the given point.
Parameters
x The reference point.
Returns
The probability density p(x).
The probability density function (PDF) gives the relative probability of obtaining different values.
override double LeftProbability (double x)
Returns the cumulative probability to the left of (below) the given point.
Parameters
x The reference point.
Returns
The integrated probability to obtain a result below the reference point.
The left probability function is commonly called the cumulative distribution function (CDF).
override double RightProbability (double x)
Return the cumulative probability to the right of (above) the given point.
Parameters
x The reference point.
Returns
The integrated probability 1-P(x1) to obtain a result above the reference point.
In survival analysis, the right probability function is commonly called the survival function, because it gives the fraction of the population remaining after the given time.
override double InverseLeftProbability (double P)
Returns the point at which the cumulative distribution function attains a given value.
Parameters
P The left cumulative probability P, which must lie between 0 and 1.
Returns
The value x at which LeftProbability equals P.
The inverse left probability is commonly called the quantile function. Given a quantile, it tells which variable value is the lower border of that quantile.
override double GetRandomValue (Random rng)
Returns a random value.
Parameters
rng A random number generator.
Returns
A number distributed according to the distribution.
Note that the random number generator rng will be advanced by this method. The next call to its generator methods will not give the same value as it would had it not been passed to this method.
override double Moment (int r)
Computes a raw moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth raw moment of the distribution.
See also
Moment
override double MomentAboutMean (int r)
Computes a central moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth central moment of the distribution.
See also
Moment
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double InverseRightProbability (double Q)
Returns the point at which the right probability function attains the given value.
virtual double ExpectationValue (Func< double, double > f)
Computes the expectation value of the given function.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Cumulant (int r)
Computes a cumulant of the distribution.
Properties
double DegreesOfFreedom [get]
Gets the number of degrees of freedom.
override double Mean [get]
override double Variance [get]
override double Skewness [get]
override double Median [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double Median [get]
Gets the median of the distribution.
virtual Interval Support [get]
Gets the interval over which the distribution is nonvanishing.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Private Attributes
double nu
Detailed Description
Represents the distribution of Student't t statistic.
The mean of n independent standard-normal distributed variables, divided by their root mean square, is distributed according a Student distribution with n degrees of freedom. Since this is the form of the expression for the mean of a sample divided by its standard deviation, the Student distribution expresses the distribution of sample means arround the population mean, for a normally distributed population.
See also
Sample.StudentTTest(Double)
Constructor & Destructor Documentation
Meta.Numerics.Statistics.Distributions.StudentDistribution.StudentDistribution (double nu) inline
Initializes a new Student distribution.
Parameters
nu The number of degrees of freedom, which must be positive.
Member Function Documentation
override double Meta.Numerics.Statistics.Distributions.StudentDistribution.ProbabilityDensity (double x) inline virtual
Returns the probability density at the given point.
Parameters
x The reference point.
Returns
The probability density p(x).
The probability density function (PDF) gives the relative probability of obtaining different values.
Implements Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Functions.AdvancedMath.Beta().
override double Meta.Numerics.Statistics.Distributions.StudentDistribution.LeftProbability (double x) inline virtual
Returns the cumulative probability to the left of (below) the given point.
Parameters
x The reference point.
Returns
The integrated probability to obtain a result below the reference point.
The left probability function is commonly called the cumulative distribution function (CDF).
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Functions.AdvancedMath.Beta().
override double Meta.Numerics.Statistics.Distributions.StudentDistribution.RightProbability (double x) inline virtual
Return the cumulative probability to the right of (above) the given point.
Parameters
x The reference point.
Returns
The integrated probability 1-P(x1) to obtain a result above the reference point.
In survival analysis, the right probability function is commonly called the survival function, because it gives the fraction of the population remaining after the given time.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Functions.AdvancedMath.LeftRegularizedBeta().
override double Meta.Numerics.Statistics.Distributions.StudentDistribution.InverseLeftProbability (double P) inline virtual
Returns the point at which the cumulative distribution function attains a given value.
Parameters
P The left cumulative probability P, which must lie between 0 and 1.
Returns
The value x at which LeftProbability equals P.
The inverse left probability is commonly called the quantile function. Given a quantile, it tells which variable value is the lower border of that quantile.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.BetaDistribution.InverseLeftProbability().
override double Meta.Numerics.Statistics.Distributions.StudentDistribution.GetRandomValue (Random rng) inline virtual
Returns a random value.
Parameters
rng A random number generator.
Returns
A number distributed according to the distribution.
Note that the random number generator rng will be advanced by this method. The next call to its generator methods will not give the same value as it would had it not been passed to this method.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
override double Meta.Numerics.Statistics.Distributions.StudentDistribution.Moment (int r) inline virtual
Computes a raw moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth raw moment of the distribution.
See also
Moment
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
override double Meta.Numerics.Statistics.Distributions.StudentDistribution.MomentAboutMean (int r) inline virtual
Computes a central moment of the distribution.
Parameters
r The order of the moment to compute.
Returns
The rth central moment of the distribution.
See also
Moment
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
Member Data Documentation
double Meta.Numerics.Statistics.Distributions.StudentDistribution.nu private
Property Documentation
double Meta.Numerics.Statistics.Distributions.StudentDistribution.DegreesOfFreedom get
Gets the number of degrees of freedom.
Referenced by Test.SampleTest.AnovaStudentAgreement().
override double Meta.Numerics.Statistics.Distributions.StudentDistribution.Mean get
override double Meta.Numerics.Statistics.Distributions.StudentDistribution.Variance get
override double Meta.Numerics.Statistics.Distributions.StudentDistribution.Skewness get
override double Meta.Numerics.Statistics.Distributions.StudentDistribution.Median get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/StudentDistribution.cs