IGLib: IPLab.HSLLinearForm Class Reference
IPLab.HSLLinearForm Class Reference
Summary description for HSLLinearForm.
Public Member Functions
HSLLinearForm (AForge.Imaging.ImageStatisticsHSL imgStat)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
Bitmap Image [set]
IFilter Filter [get]
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void componentCombo_SelectedIndexChanged (object sender, System.EventArgs e)
void inMinBox_TextChanged (object sender, System.EventArgs e)
void inMaxBox_TextChanged (object sender, System.EventArgs e)
void outMinBox_TextChanged (object sender, System.EventArgs e)
void outMaxBox_TextChanged (object sender, System.EventArgs e)
void inSlider_ValuesChanged (object sender, System.EventArgs e)
void outSlider_ValuesChanged (object sender, System.EventArgs e)
void UpdateFilter ()
Private Attributes
HSLLinear filter = new HSLLinear()
Range inSaturation = new Range(0, 1)
Range inLuminance = new Range(0, 1)
Range outSaturation = new Range(0, 1)
Range outLuminance = new Range(0, 1)
AForge.Imaging.ImageStatisticsHSL imgStat
System.Windows.Forms.Label label1
System.Windows.Forms.ComboBox componentCombo
System.Windows.Forms.PictureBox pictureBox1
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox inMaxBox
System.Windows.Forms.TextBox inMinBox
AForge.Controls.Histogram histogram
AForge.Controls.ColorSlider inSlider
System.Windows.Forms.PictureBox pictureBox2
AForge.Controls.ColorSlider outSlider
System.Windows.Forms.PictureBox pictureBox3
System.Windows.Forms.TextBox outMaxBox
System.Windows.Forms.TextBox outMinBox
System.Windows.Forms.Label label3
System.Windows.Forms.GroupBox groupBox4
IPLab.FilterPreview filterPreview
System.Windows.Forms.Button cancelButton
System.Windows.Forms.Button okButton
System.ComponentModel.Container components = null
Required designer variable.
Detailed Description
Summary description for HSLLinearForm.
Constructor & Destructor Documentation
IPLab.HSLLinearForm.HSLLinearForm (AForge.Imaging.ImageStatisticsHSL imgStat) inline
References IPLab.HSLLinearForm.componentCombo, IPLab.HSLLinearForm.filter, IPLab.FilterPreview.Filter, IPLab.HSLLinearForm.filterPreview, IPLab.HSLLinearForm.imgStat, and IPLab.HSLLinearForm.InitializeComponent().
Member Function Documentation
override void IPLab.HSLLinearForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References IPLab.HSLLinearForm.components.
void IPLab.HSLLinearForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IPLab.HSLLinearForm.HSLLinearForm().
void IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLLinearForm.componentCombo, IPLab.HSLLinearForm.histogram, IPLab.HSLLinearForm.imgStat, IPLab.HSLLinearForm.inLuminance, IPLab.HSLLinearForm.inMaxBox, IPLab.HSLLinearForm.inMinBox, IPLab.HSLLinearForm.inSaturation, IPLab.HSLLinearForm.inSlider, IPLab.HSLLinearForm.outLuminance, IPLab.HSLLinearForm.outMaxBox, IPLab.HSLLinearForm.outMinBox, IPLab.HSLLinearForm.outSaturation, and IPLab.HSLLinearForm.outSlider.
void IPLab.HSLLinearForm.inMinBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLLinearForm.componentCombo, IPLab.HSLLinearForm.inMinBox, IPLab.HSLLinearForm.inSlider, and IPLab.HSLLinearForm.UpdateFilter().
void IPLab.HSLLinearForm.inMaxBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLLinearForm.componentCombo, IPLab.HSLLinearForm.inMaxBox, IPLab.HSLLinearForm.inSlider, and IPLab.HSLLinearForm.UpdateFilter().
void IPLab.HSLLinearForm.outMinBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLLinearForm.componentCombo, IPLab.HSLLinearForm.outMinBox, IPLab.HSLLinearForm.outSlider, and IPLab.HSLLinearForm.UpdateFilter().
void IPLab.HSLLinearForm.outMaxBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLLinearForm.componentCombo, IPLab.HSLLinearForm.outMaxBox, IPLab.HSLLinearForm.outSlider, and IPLab.HSLLinearForm.UpdateFilter().
void IPLab.HSLLinearForm.inSlider_ValuesChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLLinearForm.inMaxBox, IPLab.HSLLinearForm.inMinBox, and IPLab.HSLLinearForm.inSlider.
void IPLab.HSLLinearForm.outSlider_ValuesChanged (object sender, System.EventArgs e) inline private
References IPLab.HSLLinearForm.outMaxBox, IPLab.HSLLinearForm.outMinBox, and IPLab.HSLLinearForm.outSlider.
void IPLab.HSLLinearForm.UpdateFilter () inline private
References IPLab.HSLLinearForm.filterPreview, IPLab.HSLLinearForm.inLuminance, IPLab.HSLLinearForm.inSaturation, IPLab.HSLLinearForm.outLuminance, IPLab.HSLLinearForm.outSaturation, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.HSLLinearForm.inMaxBox_TextChanged(), IPLab.HSLLinearForm.inMinBox_TextChanged(), IPLab.HSLLinearForm.outMaxBox_TextChanged(), and IPLab.HSLLinearForm.outMinBox_TextChanged().
Member Data Documentation
HSLLinear IPLab.HSLLinearForm.filter = new HSLLinear() private
Referenced by IPLab.HSLLinearForm.HSLLinearForm().
Range IPLab.HSLLinearForm.inSaturation = new Range(0, 1) private
Referenced by IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged(), and IPLab.HSLLinearForm.UpdateFilter().
Range IPLab.HSLLinearForm.inLuminance = new Range(0, 1) private
Referenced by IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged(), and IPLab.HSLLinearForm.UpdateFilter().
Range IPLab.HSLLinearForm.outSaturation = new Range(0, 1) private
Referenced by IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged(), and IPLab.HSLLinearForm.UpdateFilter().
Range IPLab.HSLLinearForm.outLuminance = new Range(0, 1) private
Referenced by IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged(), and IPLab.HSLLinearForm.UpdateFilter().
AForge.Imaging.ImageStatisticsHSL IPLab.HSLLinearForm.imgStat private
Referenced by IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged(), and IPLab.HSLLinearForm.HSLLinearForm().
System.Windows.Forms.Label IPLab.HSLLinearForm.label1 private
System.Windows.Forms.ComboBox IPLab.HSLLinearForm.componentCombo private
Referenced by IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged(), IPLab.HSLLinearForm.HSLLinearForm(), IPLab.HSLLinearForm.inMaxBox_TextChanged(), IPLab.HSLLinearForm.inMinBox_TextChanged(), IPLab.HSLLinearForm.outMaxBox_TextChanged(), and IPLab.HSLLinearForm.outMinBox_TextChanged().
System.Windows.Forms.PictureBox IPLab.HSLLinearForm.pictureBox1 private
System.Windows.Forms.Label IPLab.HSLLinearForm.label2 private
System.Windows.Forms.TextBox IPLab.HSLLinearForm.inMaxBox private
Referenced by IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged(), IPLab.HSLLinearForm.inMaxBox_TextChanged(), and IPLab.HSLLinearForm.inSlider_ValuesChanged().
System.Windows.Forms.TextBox IPLab.HSLLinearForm.inMinBox private
Referenced by IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged(), IPLab.HSLLinearForm.inMinBox_TextChanged(), and IPLab.HSLLinearForm.inSlider_ValuesChanged().
AForge.Controls.Histogram IPLab.HSLLinearForm.histogram private
Referenced by IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged().
AForge.Controls.ColorSlider IPLab.HSLLinearForm.inSlider private
Referenced by IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged(), IPLab.HSLLinearForm.inMaxBox_TextChanged(), IPLab.HSLLinearForm.inMinBox_TextChanged(), and IPLab.HSLLinearForm.inSlider_ValuesChanged().
System.Windows.Forms.PictureBox IPLab.HSLLinearForm.pictureBox2 private
AForge.Controls.ColorSlider IPLab.HSLLinearForm.outSlider private
Referenced by IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged(), IPLab.HSLLinearForm.outMaxBox_TextChanged(), IPLab.HSLLinearForm.outMinBox_TextChanged(), and IPLab.HSLLinearForm.outSlider_ValuesChanged().
System.Windows.Forms.PictureBox IPLab.HSLLinearForm.pictureBox3 private
System.Windows.Forms.TextBox IPLab.HSLLinearForm.outMaxBox private
Referenced by IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged(), IPLab.HSLLinearForm.outMaxBox_TextChanged(), and IPLab.HSLLinearForm.outSlider_ValuesChanged().
System.Windows.Forms.TextBox IPLab.HSLLinearForm.outMinBox private
Referenced by IPLab.HSLLinearForm.componentCombo_SelectedIndexChanged(), IPLab.HSLLinearForm.outMinBox_TextChanged(), and IPLab.HSLLinearForm.outSlider_ValuesChanged().
System.Windows.Forms.Label IPLab.HSLLinearForm.label3 private
System.Windows.Forms.GroupBox IPLab.HSLLinearForm.groupBox4 private
IPLab.FilterPreview IPLab.HSLLinearForm.filterPreview private
Referenced by IPLab.HSLLinearForm.HSLLinearForm(), and IPLab.HSLLinearForm.UpdateFilter().
System.Windows.Forms.Button IPLab.HSLLinearForm.cancelButton private
System.Windows.Forms.Button IPLab.HSLLinearForm.okButton private
System.ComponentModel.Container IPLab.HSLLinearForm.components = null private
Required designer variable.
Referenced by IPLab.HSLLinearForm.Dispose().
Property Documentation
Bitmap IPLab.HSLLinearForm.Image set
Referenced by IPLab.ImageDoc.linearHslFiltersItem_Click().
IFilter IPLab.HSLLinearForm.Filter get
Referenced by IPLab.ImageDoc.linearHslFiltersItem_Click().
The documentation for this class was generated from the following file:
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/HSLLinearForm.cs