IGLib: IG.MPetekLib.Application.Scripts.LinearOscillator._11MultipleResCurvesPlot3D Class Reference
IG.MPetekLib.Application.Scripts.LinearOscillator._11MultipleResCurvesPlot3D Class Reference
Static Public Member Functions
static void ApplySurfacePlotSettingsDefault (VtkSurfacePlotBase plot)
Applies default settings to surface plots.
static void ApplySurfacePlottterSettingsDefault (VtkPlotter plotter)
Applies default settings to plotter used to render 3D graphs.
static void Run (string[] arguments)
Gets the plotting arguments: damping interval size, N curves, N points/curve. Then calls another method
static void Run (double dampingMin, double dampingMax, int numCurves, int numPoints)
Plots a family of resonance curves in 3D.
Static Private Member Functions
static void ResonanceCurveHarmonicFamily3dWithManualScaling (double dampingMin, double dampingMax, int numCurves, int numPoints)
Plots a family of resonance curves in 3D.
Static Private Attributes
static BoundingBox3d OriginalBounds
static ColorScale SurfaceColorScale
Member Function Documentation
static void IG.MPetekLib.Application.Scripts.LinearOscillator._11MultipleResCurvesPlot3D.ApplySurfacePlotSettingsDefault (VtkSurfacePlotBase plot) inline static
Applies default settings to surface plots.
Parameters
plot Surface plot to which settings are applied.
References IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
static void IG.MPetekLib.Application.Scripts.LinearOscillator._11MultipleResCurvesPlot3D.ApplySurfacePlottterSettingsDefault (VtkPlotter plotter) inline static
Applies default settings to plotter used to render 3D graphs.
Parameters
plotter 3D Plotter to which settings are applied.
References IG.Gr3d.VtkPlotter.BackGround, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Gr3d.VtkDecorationHandler.LookUpTableColorScale, IG.Gr3d.VtkDecorationHandler.LookUpTableMaxRange, IG.Gr3d.VtkDecorationHandler.LookUpTableMinRange, IG.Num.BoundingBox3d.MaxZ, IG.Num.BoundingBox3d.MinZ, IG.Gr3d.VtkDecorationHandler.ScalarBarNumberOfLabels, IG.Gr3d.VtkDecorationHandler.ScalarBarTitle, IG.Gr3d.VtkDecorationHandler.ShowCubeAxes, IG.Gr3d.VtkDecorationHandler.ShowScalarBar, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
static void IG.MPetekLib.Application.Scripts.LinearOscillator._11MultipleResCurvesPlot3D.Run (string[] arguments) inline static
Gets the plotting arguments: damping interval size, N curves, N points/curve. Then calls another method
that does the plotting.
Plotting is performed in the main thread.
Referenced by IG.Script.AppMarkoPetek.App11MultipleResCurvesPlot3D().
static void IG.MPetekLib.Application.Scripts.LinearOscillator._11MultipleResCurvesPlot3D.Run (double dampingMin, double dampingMax, int numCurves, int numPoints) inline static
Plots a family of resonance curves in 3D.
This method performs MANUAL scaling of graphics to the [0, 1] range and is obsolete. Use the ResonanceCurveHarmonicFamily3d instead.
Parameters
dampingMin Minimal damping coefficient.
dampingMax Maximal damping coefficient.
numCurves Number of points in the coordinate direction of damping coefficient.
numPoints Number of points in the coordinate direction of frequency.
Plotting is performed in the main thread.
References IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase._solutionODE, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.CalcSteadyStateAmplitudeVsDrivingFrequency(), IG.Gr3d.VtkSurfacePlot.ClearSurfaceDefinition(), IG.Num.StructuredMeshGeometry2d< TCoord >.Coordinates, IG.Gr3d.VtkSurfacePlot.Create(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.DampingCoefficient, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.EndingDrivingAngularFrequency, IG.Gr3d.VtkPlotter.IsScaled, IG.Num.BoundingBoxBase.Max, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Num.BoundingBoxBase.Min, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.NSamplesForResonanceCurve, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Gr3d.VtkPlotter.ResetCamera(), IG.Gr3d.VtkPlotter.SetBoundsScaled(), IG.Gr3d.VtkPlotBase.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.Solver, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.StartingDrivingAngularFrequency, IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.StepSize, and IG.Num.BoundingBox3d.Update().
static void IG.MPetekLib.Application.Scripts.LinearOscillator._11MultipleResCurvesPlot3D.ResonanceCurveHarmonicFamily3dWithManualScaling (double dampingMin, double dampingMax, int numCurves, int numPoints) inline static private
Plots a family of resonance curves in 3D.
This method performs MANUAL scaling of graphics to the [0, 1] range and is obsolete. Use the ResonanceCurveHarmonicFamily3d instead.
Parameters
dampingMin Minimal damping coefficient.
dampingMax Maximal damping coefficient.
numCurves Number of points in the coordinate direction of damping coefficient.
numPoints Number of points in the coordinate direction of frequency.
Plotting is performed in the main thread.
References IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase._solutionODE, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.CalcSteadyStateAmplitudeVsDrivingFrequency(), IG.Gr3d.VtkSurfacePlot.ClearSurfaceDefinition(), IG.Num.StructuredMeshGeometry2d< TCoord >.Coordinates, IG.Gr3d.VtkSurfacePlot.Create(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.DampingCoefficient, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.EndingDrivingAngularFrequency, IG.Num.Field< TElement >.Length, IG.Num.BoundingBoxBase.Map(), IG.Num.BoundingBoxBase.Max, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Num.BoundingBoxBase.Min, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.NSamplesForResonanceCurve, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Gr3d.VtkPlotter.ResetCamera(), IG.Gr3d.VtkPlotBase.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.Solver, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.StartingDrivingAngularFrequency, IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.StepSize, IG.Num.BoundingBoxBase.ToString(), IG.Num.BoundingBox3d.Update(), and IG.Num.Vector3d.Vec.
Member Data Documentation
BoundingBox3d IG.MPetekLib.Application.Scripts.LinearOscillator._11MultipleResCurvesPlot3D.OriginalBounds static private
ColorScale IG.MPetekLib.Application.Scripts.LinearOscillator._11MultipleResCurvesPlot3D.SurfaceColorScale static private
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/application/scripts/LinearOscillator/11MultipleResCurvesPlot3D.cs