IGLib: alglib.nearestneighbor Class Reference
alglib.nearestneighbor Class Reference
Classes
class kdtree
Static Public Member Functions
static void kdtreebuild (double[,] xy, int n, int nx, int ny, int normtype, kdtree kdt)
static void kdtreebuildtagged (double[,] xy, int[] tags, int n, int nx, int ny, int normtype, kdtree kdt)
static int kdtreequeryknn (kdtree kdt, double[] x, int k, bool selfmatch)
static int kdtreequeryrnn (kdtree kdt, double[] x, double r, bool selfmatch)
static int kdtreequeryaknn (kdtree kdt, double[] x, int k, bool selfmatch, double eps)
static void kdtreequeryresultsx (kdtree kdt, ref double[,] x)
static void kdtreequeryresultsxy (kdtree kdt, ref double[,] xy)
static void kdtreequeryresultstags (kdtree kdt, ref int[] tags)
static void kdtreequeryresultsdistances (kdtree kdt, ref double[] r)
static void kdtreequeryresultsxi (kdtree kdt, ref double[,] x)
static void kdtreequeryresultsxyi (kdtree kdt, ref double[,] xy)
static void kdtreequeryresultstagsi (kdtree kdt, ref int[] tags)
static void kdtreequeryresultsdistancesi (kdtree kdt, ref double[] r)
static void kdtreealloc (alglib.serializer s, kdtree tree)
static void kdtreeserialize (alglib.serializer s, kdtree tree)
static void kdtreeunserialize (alglib.serializer s, kdtree tree)
static void kdtreebuild (double[,] xy, int n, int nx, int ny, int normtype, kdtree kdt)
static void kdtreebuildtagged (double[,] xy, int[] tags, int n, int nx, int ny, int normtype, kdtree kdt)
static int kdtreequeryknn (kdtree kdt, double[] x, int k, bool selfmatch)
static int kdtreequeryrnn (kdtree kdt, double[] x, double r, bool selfmatch)
static int kdtreequeryaknn (kdtree kdt, double[] x, int k, bool selfmatch, double eps)
static void kdtreequeryresultsx (kdtree kdt, ref double[,] x)
static void kdtreequeryresultsxy (kdtree kdt, ref double[,] xy)
static void kdtreequeryresultstags (kdtree kdt, ref int[] tags)
static void kdtreequeryresultsdistances (kdtree kdt, ref double[] r)
static void kdtreequeryresultsxi (kdtree kdt, ref double[,] x)
static void kdtreequeryresultsxyi (kdtree kdt, ref double[,] xy)
static void kdtreequeryresultstagsi (kdtree kdt, ref int[] tags)
static void kdtreequeryresultsdistancesi (kdtree kdt, ref double[] r)
static void kdtreealloc (alglib.serializer s, kdtree tree)
static void kdtreeserialize (alglib.serializer s, kdtree tree)
static void kdtreeunserialize (alglib.serializer s, kdtree tree)
Public Attributes
const int splitnodesize = 6
const int kdtreefirstversion = 0
Static Private Member Functions
static void kdtreesplit (kdtree kdt, int i1, int i2, int d, double s, ref int i3)
static void kdtreegeneratetreerec (kdtree kdt, ref int nodesoffs, ref int splitsoffs, int i1, int i2, int maxleafsize)
static void kdtreequerynnrec (kdtree kdt, int offs)
static void kdtreeinitbox (kdtree kdt, double[] x)
static void kdtreeallocdatasetindependent (kdtree kdt, int nx, int ny)
static void kdtreeallocdatasetdependent (kdtree kdt, int n, int nx, int ny)
static void kdtreealloctemporaries (kdtree kdt, int n, int nx, int ny)
static void kdtreesplit (kdtree kdt, int i1, int i2, int d, double s, ref int i3)
static void kdtreegeneratetreerec (kdtree kdt, ref int nodesoffs, ref int splitsoffs, int i1, int i2, int maxleafsize)
static void kdtreequerynnrec (kdtree kdt, int offs)
static void kdtreeinitbox (kdtree kdt, double[] x)
static void kdtreeallocdatasetindependent (kdtree kdt, int nx, int ny)
static void kdtreeallocdatasetdependent (kdtree kdt, int n, int nx, int ny)
static void kdtreealloctemporaries (kdtree kdt, int n, int nx, int ny)
Member Function Documentation
static void alglib.nearestneighbor.kdtreebuild (double xy[,], int n, int nx, int ny, int normtype, kdtree kdt) inline static
Referenced by alglib.kdtreebuild(), alglib.testnearestneighborunit.testkdtuniform(), and alglib.testnearestneighborunit.testspecialcases().
static void alglib.nearestneighbor.kdtreebuildtagged (double xy[,], int[] tags, int n, int nx, int ny, int normtype, kdtree kdt) inline static
Referenced by alglib.idwint.idwbuildmodifiedshepard(), alglib.idwint.idwbuildmodifiedshepardr(), alglib.idwint.idwbuildnoisy(), alglib.nearestneighbor.kdtreebuild(), alglib.kdtreebuildtagged(), alglib.testnearestneighborunit.testkdtreeserialization(), alglib.testnearestneighborunit.testkdtuniform(), and alglib.testnearestneighborunit.testspecialcases().
static int alglib.nearestneighbor.kdtreequeryknn (kdtree kdt, double[] x, int k, bool selfmatch) inline static
Referenced by alglib.idwint.idwbuildmodifiedshepard(), alglib.idwint.idwbuildnoisy(), alglib.idwint.idwcalc(), alglib.kdtreequeryknn(), alglib.testnearestneighborunit.testkdtreeserialization(), alglib.testnearestneighborunit.testkdtuniform(), and alglib.testnearestneighborunit.testspecialcases().
static int alglib.nearestneighbor.kdtreequeryrnn (kdtree kdt, double[] x, double r, bool selfmatch) inline static
Referenced by alglib.idwint.idwcalc(), alglib.kdtreequeryrnn(), alglib.testnearestneighborunit.testkdtuniform(), and alglib.testnearestneighborunit.testspecialcases().
static int alglib.nearestneighbor.kdtreequeryaknn (kdtree kdt, double[] x, int k, bool selfmatch, double eps) inline static
Referenced by alglib.kdtreequeryaknn(), alglib.nearestneighbor.kdtreequeryknn(), alglib.testnearestneighborunit.testkdtuniform(), and alglib.testnearestneighborunit.testspecialcases().
static void alglib.nearestneighbor.kdtreequeryresultsx (kdtree kdt, ref double x[,]) inline static
Referenced by alglib.kdtreequeryresultsx(), alglib.nearestneighbor.kdtreequeryresultsxi(), and alglib.testnearestneighborunit.testkdtuniform().
static void alglib.nearestneighbor.kdtreequeryresultsxy (kdtree kdt, ref double xy[,]) inline static
Referenced by alglib.idwint.idwbuildmodifiedshepard(), alglib.idwint.idwbuildnoisy(), alglib.kdtreequeryresultsxy(), alglib.nearestneighbor.kdtreequeryresultsxyi(), alglib.testnearestneighborunit.testkdtreeserialization(), and alglib.testnearestneighborunit.testkdtuniform().
static void alglib.nearestneighbor.kdtreequeryresultstags (kdtree kdt, ref int[] tags) inline static
Referenced by alglib.idwint.idwcalc(), alglib.kdtreequeryresultstags(), alglib.nearestneighbor.kdtreequeryresultstagsi(), alglib.testnearestneighborunit.testkdtreeserialization(), and alglib.testnearestneighborunit.testkdtuniform().
static void alglib.nearestneighbor.kdtreequeryresultsdistances (kdtree kdt, ref double[] r) inline static
Referenced by alglib.idwint.idwbuildmodifiedshepard(), alglib.idwint.idwbuildnoisy(), alglib.idwint.idwcalc(), alglib.kdtreequeryresultsdistances(), alglib.nearestneighbor.kdtreequeryresultsdistancesi(), and alglib.testnearestneighborunit.testkdtuniform().
static void alglib.nearestneighbor.kdtreequeryresultsxi (kdtree kdt, ref double x[,]) inline static
Referenced by alglib.kdtreequeryresultsxi(), and alglib.testnearestneighborunit.testkdtuniform().
static void alglib.nearestneighbor.kdtreequeryresultsxyi (kdtree kdt, ref double xy[,]) inline static
Referenced by alglib.kdtreequeryresultsxyi(), and alglib.testnearestneighborunit.testkdtuniform().
static void alglib.nearestneighbor.kdtreequeryresultstagsi (kdtree kdt, ref int[] tags) inline static
Referenced by alglib.kdtreequeryresultstagsi(), and alglib.testnearestneighborunit.testkdtuniform().
static void alglib.nearestneighbor.kdtreequeryresultsdistancesi (kdtree kdt, ref double[] r) inline static
Referenced by alglib.kdtreequeryresultsdistancesi(), and alglib.testnearestneighborunit.testkdtuniform().
static void alglib.nearestneighbor.kdtreealloc (alglib.serializer s, kdtree tree) inline static
Referenced by alglib.kdtreeserialize(), and alglib.testnearestneighborunit.testkdtreeserialization().
static void alglib.nearestneighbor.kdtreeserialize (alglib.serializer s, kdtree tree) inline static
Referenced by alglib.kdtreeserialize(), and alglib.testnearestneighborunit.testkdtreeserialization().
static void alglib.nearestneighbor.kdtreeunserialize (alglib.serializer s, kdtree tree) inline static
Referenced by alglib.kdtreeunserialize(), and alglib.testnearestneighborunit.testkdtreeserialization().
static void alglib.nearestneighbor.kdtreesplit (kdtree kdt, int i1, int i2, int d, double s, ref int i3) inline static private
Referenced by alglib.nearestneighbor.kdtreegeneratetreerec().
static void alglib.nearestneighbor.kdtreegeneratetreerec (kdtree kdt, ref int nodesoffs, ref int splitsoffs, int i1, int i2, int maxleafsize) inline static private
Referenced by alglib.nearestneighbor.kdtreebuildtagged(), and alglib.nearestneighbor.kdtreegeneratetreerec().
static void alglib.nearestneighbor.kdtreequerynnrec (kdtree kdt, int offs) inline static private
Referenced by alglib.nearestneighbor.kdtreequeryaknn(), alglib.nearestneighbor.kdtreequerynnrec(), and alglib.nearestneighbor.kdtreequeryrnn().
static void alglib.nearestneighbor.kdtreeinitbox (kdtree kdt, double[] x) inline static private
Referenced by alglib.nearestneighbor.kdtreequeryaknn(), and alglib.nearestneighbor.kdtreequeryrnn().
static void alglib.nearestneighbor.kdtreeallocdatasetindependent (kdtree kdt, int nx, int ny) inline static private
Referenced by alglib.nearestneighbor.kdtreebuildtagged().
static void alglib.nearestneighbor.kdtreeallocdatasetdependent (kdtree kdt, int n, int nx, int ny) inline static private
Referenced by alglib.nearestneighbor.kdtreebuildtagged().
static void alglib.nearestneighbor.kdtreealloctemporaries (kdtree kdt, int n, int nx, int ny) inline static private
Referenced by alglib.nearestneighbor.kdtreeunserialize().
static void alglib.nearestneighbor.kdtreebuild (double xy[,], int n, int nx, int ny, int normtype, kdtree kdt) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), and alglib.nearestneighbor.kdtreebuildtagged().
static void alglib.nearestneighbor.kdtreebuildtagged (double xy[,], int[] tags, int n, int nx, int ny, int normtype, kdtree kdt) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), alglib.nearestneighbor.kdtreeallocdatasetdependent(), alglib.nearestneighbor.kdtreeallocdatasetindependent(), and alglib.nearestneighbor.kdtreegeneratetreerec().
static int alglib.nearestneighbor.kdtreequeryknn (kdtree kdt, double[] x, int k, bool selfmatch) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.nearestneighbor.kdtreequeryaknn().
static int alglib.nearestneighbor.kdtreequeryrnn (kdtree kdt, double[] x, double r, bool selfmatch) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.nearestneighbor.kdtreeinitbox(), alglib.nearestneighbor.kdtreequerynnrec(), alglib.math.sqr(), and alglib.tsort.tagheappopi().
static int alglib.nearestneighbor.kdtreequeryaknn (kdtree kdt, double[] x, int k, bool selfmatch, double eps) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.nearestneighbor.kdtreeinitbox(), alglib.nearestneighbor.kdtreequerynnrec(), alglib.math.sqr(), and alglib.tsort.tagheappopi().
static void alglib.nearestneighbor.kdtreequeryresultsx (kdtree kdt, ref double x[,]) inline static
static void alglib.nearestneighbor.kdtreequeryresultsxy (kdtree kdt, ref double xy[,]) inline static
static void alglib.nearestneighbor.kdtreequeryresultstags (kdtree kdt, ref int[] tags) inline static
static void alglib.nearestneighbor.kdtreequeryresultsdistances (kdtree kdt, ref double[] r) inline static
static void alglib.nearestneighbor.kdtreequeryresultsxi (kdtree kdt, ref double x[,]) inline static
References alglib.nearestneighbor.kdtreequeryresultsx().
static void alglib.nearestneighbor.kdtreequeryresultsxyi (kdtree kdt, ref double xy[,]) inline static
References alglib.nearestneighbor.kdtreequeryresultsxy().
static void alglib.nearestneighbor.kdtreequeryresultstagsi (kdtree kdt, ref int[] tags) inline static
References alglib.nearestneighbor.kdtreequeryresultstags().
static void alglib.nearestneighbor.kdtreequeryresultsdistancesi (kdtree kdt, ref double[] r) inline static
References alglib.nearestneighbor.kdtreequeryresultsdistances().
static void alglib.nearestneighbor.kdtreealloc (alglib.serializer s, kdtree tree) inline static
References alglib.apserv.allocintegerarray(), alglib.apserv.allocrealarray(), and alglib.apserv.allocrealmatrix().
static void alglib.nearestneighbor.kdtreeserialize (alglib.serializer s, kdtree tree) inline static
References alglib.scodes.getkdtreeserializationcode(), alglib.apserv.serializeintegerarray(), alglib.apserv.serializerealarray(), and alglib.apserv.serializerealmatrix().
static void alglib.nearestneighbor.kdtreeunserialize (alglib.serializer s, kdtree tree) inline static
References alglib.ap.assert(), alglib.scodes.getkdtreeserializationcode(), alglib.nearestneighbor.kdtreealloctemporaries(), alglib.apserv.unserializeintegerarray(), alglib.apserv.unserializerealarray(), and alglib.apserv.unserializerealmatrix().
static void alglib.nearestneighbor.kdtreesplit (kdtree kdt, int i1, int i2, int d, double s, ref int i3) inline static private
References alglib.ap.assert().
static void alglib.nearestneighbor.kdtreegeneratetreerec (kdtree kdt, ref int nodesoffs, ref int splitsoffs, int i1, int i2, int maxleafsize) inline static private
References alglib.ap.assert(), alglib.nearestneighbor.kdtreegeneratetreerec(), alglib.nearestneighbor.kdtreesplit(), and alglib.nearestneighbor.splitnodesize.
static void alglib.nearestneighbor.kdtreequerynnrec (kdtree kdt, int offs) inline static private
References alglib.ap.assert(), alglib.nearestneighbor.kdtreequerynnrec(), alglib.math.sqr(), alglib.tsort.tagheappushi(), and alglib.tsort.tagheapreplacetopi().
static void alglib.nearestneighbor.kdtreeinitbox (kdtree kdt, double[] x) inline static private
References alglib.ap.assert(), and alglib.math.sqr().
static void alglib.nearestneighbor.kdtreeallocdatasetindependent (kdtree kdt, int nx, int ny) inline static private
References alglib.ap.assert().
static void alglib.nearestneighbor.kdtreeallocdatasetdependent (kdtree kdt, int n, int nx, int ny) inline static private
References alglib.ap.assert().
static void alglib.nearestneighbor.kdtreealloctemporaries (kdtree kdt, int n, int nx, int ny) inline static private
References alglib.ap.assert().
Member Data Documentation
const int alglib.nearestneighbor.splitnodesize = 6
Referenced by alglib.nearestneighbor.kdtreegeneratetreerec().
const int alglib.nearestneighbor.kdtreefirstversion = 0
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/alglibmisc.cs