IGLib: NUnit.Framework.Assertions.AssumeThatTests Class Reference
NUnit.Framework.Assertions.AssumeThatTests Class Reference
Public Member Functions
void AssumptionPasses_Boolean ()
void AssumptionPasses_BooleanWithMessage ()
void AssumptionPasses_BooleanWithMessageAndArgs ()
void AssumptionPasses_BooleanLambda ()
void AssumptionPasses_BooleanLambdaWithMessage ()
void AssumptionPasses_BooleanLambdaWithMessageAndArgs ()
void AssumptionPasses_ActualAndConstraint ()
void AssumptionPasses_ActualAndConstraintWithMessage ()
void AssumptionPasses_ActualAndConstraintWithMessageAndArgs ()
void AssumptionPasses_ActualLambdaAndConstraint ()
void AssumptionPasses_ActualLambdaAndConstraintWithMessage ()
void AssumptionPasses_ActualLambdaAndConstraintWithMessageAndArgs ()
void AssumptionPasses_DelegateAndConstraint ()
void AssumptionPasses_DelegateAndConstraintWithMessage ()
void AssumptionPasses_DelegateAndConstraintWithMessageAndArgs ()
void FailureThrowsInconclusiveException_Boolean ()
void FailureThrowsInconclusiveException_BooleanWithMessage ()
void FailureThrowsInconclusiveException_BooleanWithMessageAndArgs ()
void FailureThrowsInconclusiveException_BooleanLambda ()
void FailureThrowsInconclusiveException_BooleanLambdaWithMessage ()
void FailureThrowsInconclusiveException_BooleanLambdaWithMessageAndArgs ()
void FailureThrowsInconclusiveException_ActualAndConstraint ()
void FailureThrowsInconclusiveException_ActualAndConstraintWithMessage ()
void FailureThrowsInconclusiveException_ActualAndConstraintWithMessageAndArgs ()
void FailureThrowsInconclusiveException_ActualLambdaAndConstraint ()
void FailureThrowsInconclusiveException_ActualLambdaAndConstraintWithMessage ()
void FailureThrowsInconclusiveException_ActualLambdaAndConstraintWithMessageAndArgs ()
void FailureThrowsInconclusiveException_DelegateAndConstraint ()
void FailureThrowsInconclusiveException_DelegateAndConstraintWithMessage ()
void FailureThrowsInconclusiveException_DelegateAndConstraintWithMessageAndArgs ()
Private Member Functions
int ReturnsFour ()
int ReturnsFive ()
Member Function Documentation
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_Boolean () inline
References NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_BooleanWithMessage () inline
References NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_BooleanWithMessageAndArgs () inline
References NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_BooleanLambda () inline
References NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_BooleanLambdaWithMessage () inline
References NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_BooleanLambdaWithMessageAndArgs () inline
References NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualAndConstraint () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualAndConstraintWithMessage () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualAndConstraintWithMessageAndArgs () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualLambdaAndConstraint () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualLambdaAndConstraintWithMessage () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_ActualLambdaAndConstraintWithMessageAndArgs () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_DelegateAndConstraint () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_DelegateAndConstraintWithMessage () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assume.That().
void NUnit.Framework.Assertions.AssumeThatTests.AssumptionPasses_DelegateAndConstraintWithMessageAndArgs () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assume.That().
int NUnit.Framework.Assertions.AssumeThatTests.ReturnsFour () inline private
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_Boolean () inline
References NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanWithMessage () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanWithMessageAndArgs () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanLambda () inline
References NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanLambdaWithMessage () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_BooleanLambdaWithMessageAndArgs () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraint () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraintWithMessage () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualAndConstraintWithMessageAndArgs () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraint () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraintWithMessage () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_ActualLambdaAndConstraintWithMessageAndArgs () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraint () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraintWithMessage () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
void NUnit.Framework.Assertions.AssumeThatTests.FailureThrowsInconclusiveException_DelegateAndConstraintWithMessageAndArgs () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assert.Throws().
int NUnit.Framework.Assertions.AssumeThatTests.ReturnsFive () inline private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/AssumeThatTests.cs