IGLib: CShell.AssemblyLoader Class Reference
CShell.AssemblyLoader Class Reference
Static Helper classes to manage the assemblies. The instance is subscribed to the workpsace events and the AssemblyReferences to load it's modules to the container.
Public Member Functions
AssemblyLoader (CompositionContainer container, IEventAggregator eventAggregator)
void Handle (WorkspaceOpeningEventArgs message)
void Handle (WorkspaceClosingEventArgs message)
AssemblyLoader (CompositionContainer container, IEventAggregator eventAggregator)
void Handle (WorkspaceOpeningEventArgs message)
void Handle (WorkspaceClosingEventArgs message)
Static Public Member Functions
static string GetAssemblyName (string fullName)
static string[] GetAssemblySearchFiles (IEnumerable< AssemblyReference > references)
static string[] GetAssemblySearchPaths (IEnumerable< AssemblyReference > references)
static Assembly LoadAssembly (AssemblyReference reference)
static AssemblyName[] GetGacAssemblyNames ()
static Assembly[] GetGacAssemblies ()
Gets the assemblies in the GAC, the assemblies are loaded reflection only.
static string GetGacAssemblyPath (AssemblyName assemblyName)
static string GetAssemblyName (string fullName)
static string[] GetAssemblySearchFiles (IEnumerable< AssemblyReference > references)
static string[] GetAssemblySearchPaths (IEnumerable< AssemblyReference > references)
static Assembly LoadAssembly (AssemblyReference reference)
static AssemblyName[] GetGacAssemblyNames ()
static Assembly[] GetGacAssemblies ()
Gets the assemblies in the GAC, the assemblies are loaded reflection only.
static string GetGacAssemblyPath (AssemblyName assemblyName)
Private Member Functions
void AssembliesOnCollectionChanged (object sender, NotifyCollectionChangedEventArgs args)
void AssemblyAdded (AssemblyReference assemblyReference)
void AssemblyRemoved (AssemblyReference assemblyReference)
void AssembliesOnCollectionChanged (object sender, NotifyCollectionChangedEventArgs args)
void AssemblyAdded (AssemblyReference assemblyReference)
void AssemblyRemoved (AssemblyReference assemblyReference)
Private Attributes
readonly CompositionContainer container
readonly AggregateCatalog catalog
readonly ILog log = LogManager.GetLog(typeof (AssemblyLoader))
readonly List< IModule > loadedModules = new List<IModule>()
readonly List< AssemblyReference > loadedAssemblies = new List<AssemblyReference>()
Static Private Attributes
static readonly Lazy
< AssemblyName[]> gacAssembyNames = new Lazy<AssemblyName[]>(() => Util.GlobalAssemblyCache.GetAssemblyList().ToArray(), true)
static readonly Lazy< Assembly[]> gacAssemblies
Detailed Description
Static Helper classes to manage the assemblies. The instance is subscribed to the workpsace events and the AssemblyReferences to load it's modules to the container.
Constructor & Destructor Documentation
CShell.AssemblyLoader.AssemblyLoader (CompositionContainer container, IEventAggregator eventAggregator) inline
References CShell.AssemblyLoader.container.
CShell.AssemblyLoader.AssemblyLoader (CompositionContainer container, IEventAggregator eventAggregator) inline
References CShell.AssemblyLoader.container.
Member Function Documentation
void CShell.AssemblyLoader.Handle (WorkspaceOpeningEventArgs message) inline
References CShell.Workspace.Assemblies, CShell.AssemblyLoader.AssembliesOnCollectionChanged(), and CShell.WorkspaceOpeningEventArgs.Workspace.
void CShell.AssemblyLoader.Handle (WorkspaceClosingEventArgs message) inline
References CShell.Workspace.Assemblies, CShell.AssemblyLoader.AssembliesOnCollectionChanged(), CShell.AssemblyLoader.AssemblyRemoved(), and CShell.WorkspaceClosingEventArgs.Workspace.
void CShell.AssemblyLoader.AssembliesOnCollectionChanged (object sender, NotifyCollectionChangedEventArgs args) inline private
References CShell.AssemblyLoader.AssemblyAdded(), and CShell.AssemblyLoader.AssemblyRemoved().
Referenced by CShell.AssemblyLoader.Handle().
void CShell.AssemblyLoader.AssemblyAdded (AssemblyReference assemblyReference) inline private
References CShell.AssemblyReference.Assembly, CShell.AssemblyReference.AssemblyCatalog, CShell.AssemblyReference.AssemblyName, CShell.AssemblyReference.HasParts, and CShell.Framework.IModule.Initialize().
Referenced by CShell.AssemblyLoader.AssembliesOnCollectionChanged().
void CShell.AssemblyLoader.AssemblyRemoved (AssemblyReference assemblyReference) inline private
References CShell.AssemblyReference.Assembly, and CShell.AssemblyReference.AssemblyCatalog.
Referenced by CShell.AssemblyLoader.AssembliesOnCollectionChanged(), and CShell.AssemblyLoader.Handle().
static string CShell.AssemblyLoader.GetAssemblyName (string fullName) inline static
Referenced by CShell.AssemblyReferences.ResolveAssembly().
static string [] CShell.AssemblyLoader.GetAssemblySearchFiles (IEnumerable< AssemblyReference > references) inline static
References CShell.AssemblyLoader.GetAssemblySearchPaths().
Referenced by CShell.AssemblyReferences.ResolveAssembly().
static string [] CShell.AssemblyLoader.GetAssemblySearchPaths (IEnumerable< AssemblyReference > references) inline static
Referenced by CShell.AssemblyLoader.GetAssemblySearchFiles().
static Assembly CShell.AssemblyLoader.LoadAssembly (AssemblyReference reference) inline static
References CShell.AssemblyReference.AssemblyName, and CShell.AssemblyReference.FullPath.
static AssemblyName [] CShell.AssemblyLoader.GetGacAssemblyNames () inline static
static Assembly [] CShell.AssemblyLoader.GetGacAssemblies () inline static
Gets the assemblies in the GAC, the assemblies are loaded reflection only.
Returns
static string CShell.AssemblyLoader.GetGacAssemblyPath (AssemblyName assemblyName) inline static
void CShell.AssemblyLoader.Handle (WorkspaceOpeningEventArgs message) inline
References CShell.Workspace.Assemblies, CShell.AssemblyLoader.AssembliesOnCollectionChanged(), and CShell.WorkspaceOpeningEventArgs.Workspace.
void CShell.AssemblyLoader.Handle (WorkspaceClosingEventArgs message) inline
References CShell.Workspace.Assemblies, CShell.AssemblyLoader.AssembliesOnCollectionChanged(), CShell.AssemblyLoader.AssemblyRemoved(), and CShell.WorkspaceClosingEventArgs.Workspace.
void CShell.AssemblyLoader.AssembliesOnCollectionChanged (object sender, NotifyCollectionChangedEventArgs args) inline private
References CShell.AssemblyLoader.AssemblyAdded(), and CShell.AssemblyLoader.AssemblyRemoved().
void CShell.AssemblyLoader.AssemblyAdded (AssemblyReference assemblyReference) inline private
References CShell.AssemblyReference.Assembly, CShell.AssemblyReference.AssemblyCatalog, CShell.AssemblyReference.AssemblyName, CShell.AssemblyReference.HasParts, and CShell.Framework.IModule.Initialize().
void CShell.AssemblyLoader.AssemblyRemoved (AssemblyReference assemblyReference) inline private
References CShell.AssemblyReference.Assembly, and CShell.AssemblyReference.AssemblyCatalog.
static string CShell.AssemblyLoader.GetAssemblyName (string fullName) inline static
static string [] CShell.AssemblyLoader.GetAssemblySearchFiles (IEnumerable< AssemblyReference > references) inline static
References CShell.AssemblyLoader.GetAssemblySearchPaths().
static string [] CShell.AssemblyLoader.GetAssemblySearchPaths (IEnumerable< AssemblyReference > references) inline static
static Assembly CShell.AssemblyLoader.LoadAssembly (AssemblyReference reference) inline static
References CShell.AssemblyReference.AssemblyName, and CShell.AssemblyReference.FullPath.
static AssemblyName [] CShell.AssemblyLoader.GetGacAssemblyNames () inline static
static Assembly [] CShell.AssemblyLoader.GetGacAssemblies () inline static
Gets the assemblies in the GAC, the assemblies are loaded reflection only.
Returns
static string CShell.AssemblyLoader.GetGacAssemblyPath (AssemblyName assemblyName) inline static
Member Data Documentation
readonly CompositionContainer CShell.AssemblyLoader.container private
Referenced by CShell.AssemblyLoader.AssemblyLoader().
readonly AggregateCatalog CShell.AssemblyLoader.catalog private
readonly ILog CShell.AssemblyLoader.log = LogManager.GetLog(typeof (AssemblyLoader)) private
readonly List< IModule > CShell.AssemblyLoader.loadedModules = new List<IModule>() private
readonly List< AssemblyReference > CShell.AssemblyLoader.loadedAssemblies = new List<AssemblyReference>() private
static readonly Lazy< AssemblyName[]> CShell.AssemblyLoader.gacAssembyNames = new Lazy<AssemblyName[]>(() => Util.GlobalAssemblyCache.GetAssemblyList().ToArray(), true) static private
static readonly Lazy< Assembly[]> CShell.AssemblyLoader.gacAssemblies static private
Initial value:
= new Lazy<Assembly[]>(() =>
        {
            var assemblies = new List<Assembly>();
            var errorCount = 0;
            foreach (var assemblyName in gacAssembyNames.Value)
            {
                try
                {
                    var assembly = Assembly.ReflectionOnlyLoad(assemblyName.FullName);
                    assemblies.Add(assembly);
                }
                catch (Exception ex)
                {
                    errorCount++;
                    Debug.Print("Could not load GAC assembly '{0}': {1}",assemblyName.FullName, ex);
                }
            }
            Debug.Print("GAC error count: "+errorCount);
            return assemblies.ToArray();
        }, true)
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/AssemblyLoader.cs