IGLib: alglib.ortfac Class Reference
alglib.ortfac Class Reference
Static Public Member Functions
static void rmatrixqr (ref double[,] a, int m, int n, ref double[] tau)
static void rmatrixlq (ref double[,] a, int m, int n, ref double[] tau)
static void cmatrixqr (ref complex[,] a, int m, int n, ref complex[] tau)
static void cmatrixlq (ref complex[,] a, int m, int n, ref complex[] tau)
static void rmatrixqrunpackq (double[,] a, int m, int n, double[] tau, int qcolumns, ref double[,] q)
static void rmatrixqrunpackr (double[,] a, int m, int n, ref double[,] r)
static void rmatrixlqunpackq (double[,] a, int m, int n, double[] tau, int qrows, ref double[,] q)
static void rmatrixlqunpackl (double[,] a, int m, int n, ref double[,] l)
static void cmatrixqrunpackq (complex[,] a, int m, int n, complex[] tau, int qcolumns, ref complex[,] q)
static void cmatrixqrunpackr (complex[,] a, int m, int n, ref complex[,] r)
static void cmatrixlqunpackq (complex[,] a, int m, int n, complex[] tau, int qrows, ref complex[,] q)
static void cmatrixlqunpackl (complex[,] a, int m, int n, ref complex[,] l)
static void rmatrixqrbasecase (ref double[,] a, int m, int n, ref double[] work, ref double[] t, ref double[] tau)
static void rmatrixlqbasecase (ref double[,] a, int m, int n, ref double[] work, ref double[] t, ref double[] tau)
static void rmatrixbd (ref double[,] a, int m, int n, ref double[] tauq, ref double[] taup)
static void rmatrixbdunpackq (double[,] qp, int m, int n, double[] tauq, int qcolumns, ref double[,] q)
static void rmatrixbdmultiplybyq (double[,] qp, int m, int n, double[] tauq, ref double[,] z, int zrows, int zcolumns, bool fromtheright, bool dotranspose)
static void rmatrixbdunpackpt (double[,] qp, int m, int n, double[] taup, int ptrows, ref double[,] pt)
static void rmatrixbdmultiplybyp (double[,] qp, int m, int n, double[] taup, ref double[,] z, int zrows, int zcolumns, bool fromtheright, bool dotranspose)
static void rmatrixbdunpackdiagonals (double[,] b, int m, int n, ref bool isupper, ref double[] d, ref double[] e)
static void rmatrixhessenberg (ref double[,] a, int n, ref double[] tau)
static void rmatrixhessenbergunpackq (double[,] a, int n, double[] tau, ref double[,] q)
static void rmatrixhessenbergunpackh (double[,] a, int n, ref double[,] h)
static void smatrixtd (ref double[,] a, int n, bool isupper, ref double[] tau, ref double[] d, ref double[] e)
static void smatrixtdunpackq (double[,] a, int n, bool isupper, double[] tau, ref double[,] q)
static void hmatrixtd (ref complex[,] a, int n, bool isupper, ref complex[] tau, ref double[] d, ref double[] e)
static void hmatrixtdunpackq (complex[,] a, int n, bool isupper, complex[] tau, ref complex[,] q)
static void rmatrixqr (ref double[,] a, int m, int n, ref double[] tau)
static void rmatrixlq (ref double[,] a, int m, int n, ref double[] tau)
static void cmatrixqr (ref complex[,] a, int m, int n, ref complex[] tau)
static void cmatrixlq (ref complex[,] a, int m, int n, ref complex[] tau)
static void rmatrixqrunpackq (double[,] a, int m, int n, double[] tau, int qcolumns, ref double[,] q)
static void rmatrixqrunpackr (double[,] a, int m, int n, ref double[,] r)
static void rmatrixlqunpackq (double[,] a, int m, int n, double[] tau, int qrows, ref double[,] q)
static void rmatrixlqunpackl (double[,] a, int m, int n, ref double[,] l)
static void cmatrixqrunpackq (complex[,] a, int m, int n, complex[] tau, int qcolumns, ref complex[,] q)
static void cmatrixqrunpackr (complex[,] a, int m, int n, ref complex[,] r)
static void cmatrixlqunpackq (complex[,] a, int m, int n, complex[] tau, int qrows, ref complex[,] q)
static void cmatrixlqunpackl (complex[,] a, int m, int n, ref complex[,] l)
static void rmatrixqrbasecase (ref double[,] a, int m, int n, ref double[] work, ref double[] t, ref double[] tau)
static void rmatrixlqbasecase (ref double[,] a, int m, int n, ref double[] work, ref double[] t, ref double[] tau)
static void rmatrixbd (ref double[,] a, int m, int n, ref double[] tauq, ref double[] taup)
static void rmatrixbdunpackq (double[,] qp, int m, int n, double[] tauq, int qcolumns, ref double[,] q)
static void rmatrixbdmultiplybyq (double[,] qp, int m, int n, double[] tauq, ref double[,] z, int zrows, int zcolumns, bool fromtheright, bool dotranspose)
static void rmatrixbdunpackpt (double[,] qp, int m, int n, double[] taup, int ptrows, ref double[,] pt)
static void rmatrixbdmultiplybyp (double[,] qp, int m, int n, double[] taup, ref double[,] z, int zrows, int zcolumns, bool fromtheright, bool dotranspose)
static void rmatrixbdunpackdiagonals (double[,] b, int m, int n, ref bool isupper, ref double[] d, ref double[] e)
static void rmatrixhessenberg (ref double[,] a, int n, ref double[] tau)
static void rmatrixhessenbergunpackq (double[,] a, int n, double[] tau, ref double[,] q)
static void rmatrixhessenbergunpackh (double[,] a, int n, ref double[,] h)
static void smatrixtd (ref double[,] a, int n, bool isupper, ref double[] tau, ref double[] d, ref double[] e)
static void smatrixtdunpackq (double[,] a, int n, bool isupper, double[] tau, ref double[,] q)
static void hmatrixtd (ref complex[,] a, int n, bool isupper, ref complex[] tau, ref double[] d, ref double[] e)
static void hmatrixtdunpackq (complex[,] a, int n, bool isupper, complex[] tau, ref complex[,] q)
Static Private Member Functions
static void cmatrixqrbasecase (ref complex[,] a, int m, int n, ref complex[] work, ref complex[] t, ref complex[] tau)
static void cmatrixlqbasecase (ref complex[,] a, int m, int n, ref complex[] work, ref complex[] t, ref complex[] tau)
static void rmatrixblockreflector (ref double[,] a, ref double[] tau, bool columnwisea, int lengtha, int blocksize, ref double[,] t, ref double[] work)
static void cmatrixblockreflector (ref complex[,] a, ref complex[] tau, bool columnwisea, int lengtha, int blocksize, ref complex[,] t, ref complex[] work)
static void cmatrixqrbasecase (ref complex[,] a, int m, int n, ref complex[] work, ref complex[] t, ref complex[] tau)
static void cmatrixlqbasecase (ref complex[,] a, int m, int n, ref complex[] work, ref complex[] t, ref complex[] tau)
static void rmatrixblockreflector (ref double[,] a, ref double[] tau, bool columnwisea, int lengtha, int blocksize, ref double[,] t, ref double[] work)
static void cmatrixblockreflector (ref complex[,] a, ref complex[] tau, bool columnwisea, int lengtha, int blocksize, ref complex[,] t, ref complex[] work)
Member Function Documentation
static void alglib.ortfac.rmatrixqr (ref double a[,], int m, int n, ref double[] tau) inline static
References alglib.ablas.ablasblocksize(), alglib.reflections.applyreflectionfromtheleft(), alglib.ortfac.rmatrixblockreflector(), alglib.ablas.rmatrixcopy(), alglib.ablas.rmatrixgemm(), and alglib.ortfac.rmatrixqrbasecase().
Referenced by alglib.rmatrixqr(), and alglib.testortfacunit.testrqrproblem().
static void alglib.ortfac.rmatrixlq (ref double a[,], int m, int n, ref double[] tau) inline static
References alglib.ablas.ablasblocksize(), alglib.reflections.applyreflectionfromtheright(), alglib.ortfac.rmatrixblockreflector(), alglib.ablas.rmatrixcopy(), alglib.ablas.rmatrixgemm(), and alglib.ortfac.rmatrixlqbasecase().
Referenced by alglib.rmatrixlq(), and alglib.testortfacunit.testrlqproblem().
static void alglib.ortfac.cmatrixqr (ref complex a[,], int m, int n, ref complex[] tau) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ortfac.cmatrixblockreflector(), alglib.ablas.cmatrixcopy(), alglib.ablas.cmatrixgemm(), alglib.ortfac.cmatrixqrbasecase(), alglib.creflections.complexapplyreflectionfromtheleft(), and alglib.math.conj().
Referenced by alglib.cmatrixqr(), and alglib.testortfacunit.testcqrproblem().
static void alglib.ortfac.cmatrixlq (ref complex a[,], int m, int n, ref complex[] tau) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ortfac.cmatrixblockreflector(), alglib.ablas.cmatrixcopy(), alglib.ablas.cmatrixgemm(), alglib.ortfac.cmatrixlqbasecase(), alglib.creflections.complexapplyreflectionfromtheright(), and alglib.math.conj().
Referenced by alglib.cmatrixlq(), and alglib.testortfacunit.testclqproblem().
static void alglib.ortfac.rmatrixqrunpackq (double a[,], int m, int n, double[] tau, int qcolumns, ref double q[,]) inline static
References alglib.ap.assert().
Referenced by alglib.rmatrixqrunpackq(), and alglib.testortfacunit.testrqrproblem().
static void alglib.ortfac.rmatrixqrunpackr (double a[,], int m, int n, ref double r[,]) inline static
Referenced by alglib.rmatrixqrunpackr(), and alglib.testortfacunit.testrqrproblem().
static void alglib.ortfac.rmatrixlqunpackq (double a[,], int m, int n, double[] tau, int qrows, ref double q[,]) inline static
Referenced by alglib.rmatrixlqunpackq(), and alglib.testortfacunit.testrlqproblem().
static void alglib.ortfac.rmatrixlqunpackl (double a[,], int m, int n, ref double l[,]) inline static
Referenced by alglib.rmatrixlqunpackl(), and alglib.testortfacunit.testrlqproblem().
static void alglib.ortfac.cmatrixqrunpackq (complex a[,], int m, int n, complex[] tau, int qcolumns, ref complex q[,]) inline static
Referenced by alglib.cmatrixqrunpackq(), and alglib.testortfacunit.testcqrproblem().
static void alglib.ortfac.cmatrixqrunpackr (complex a[,], int m, int n, ref complex r[,]) inline static
Referenced by alglib.cmatrixqrunpackr(), and alglib.testortfacunit.testcqrproblem().
static void alglib.ortfac.cmatrixlqunpackq (complex a[,], int m, int n, complex[] tau, int qrows, ref complex q[,]) inline static
Referenced by alglib.cmatrixlqunpackq(), and alglib.testortfacunit.testclqproblem().
static void alglib.ortfac.cmatrixlqunpackl (complex a[,], int m, int n, ref complex l[,]) inline static
Referenced by alglib.cmatrixlqunpackl(), and alglib.testortfacunit.testclqproblem().
static void alglib.ortfac.rmatrixqrbasecase (ref double a[,], int m, int n, ref double[] work, ref double[] t, ref double[] tau) inline static
Referenced by alglib.ortfac.rmatrixqr().
static void alglib.ortfac.rmatrixlqbasecase (ref double a[,], int m, int n, ref double[] work, ref double[] t, ref double[] tau) inline static
Referenced by alglib.ortfac.rmatrixlq().
static void alglib.ortfac.rmatrixbd (ref double a[,], int m, int n, ref double[] tauq, ref double[] taup) inline static
Referenced by alglib.rmatrixbd(), and alglib.testortfacunit.testrbdproblem().
static void alglib.ortfac.rmatrixbdunpackq (double qp[,], int m, int n, double[] tauq, int qcolumns, ref double q[,]) inline static
Referenced by alglib.rmatrixbdunpackq(), and alglib.testortfacunit.testrbdproblem().
static void alglib.ortfac.rmatrixbdmultiplybyq (double qp[,], int m, int n, double[] tauq, ref double z[,], int zrows, int zcolumns, bool fromtheright, bool dotranspose) inline static
Referenced by alglib.rmatrixbdmultiplybyq(), and alglib.testortfacunit.testrbdproblem().
static void alglib.ortfac.rmatrixbdunpackpt (double qp[,], int m, int n, double[] taup, int ptrows, ref double pt[,]) inline static
Referenced by alglib.rmatrixbdunpackpt(), and alglib.testortfacunit.testrbdproblem().
static void alglib.ortfac.rmatrixbdmultiplybyp (double qp[,], int m, int n, double[] taup, ref double z[,], int zrows, int zcolumns, bool fromtheright, bool dotranspose) inline static
Referenced by alglib.rmatrixbdmultiplybyp(), and alglib.testortfacunit.testrbdproblem().
static void alglib.ortfac.rmatrixbdunpackdiagonals (double b[,], int m, int n, ref bool isupper, ref double[] d, ref double[] e) inline static
Referenced by alglib.rmatrixbdunpackdiagonals(), and alglib.testortfacunit.testrbdproblem().
static void alglib.ortfac.rmatrixhessenberg (ref double a[,], int n, ref double[] tau) inline static
Referenced by alglib.rmatrixhessenberg(), and alglib.testortfacunit.testrhessproblem().
static void alglib.ortfac.rmatrixhessenbergunpackq (double a[,], int n, double[] tau, ref double q[,]) inline static
Referenced by alglib.rmatrixhessenbergunpackq(), and alglib.testortfacunit.testrhessproblem().
static void alglib.ortfac.rmatrixhessenbergunpackh (double a[,], int n, ref double h[,]) inline static
Referenced by alglib.rmatrixhessenbergunpackh(), and alglib.testortfacunit.testrhessproblem().
static void alglib.ortfac.smatrixtd (ref double a[,], int n, bool isupper, ref double[] tau, ref double[] d, ref double[] e) inline static
Referenced by alglib.smatrixtd(), and alglib.testortfacunit.testrtdproblem().
static void alglib.ortfac.smatrixtdunpackq (double a[,], int n, bool isupper, double[] tau, ref double q[,]) inline static
Referenced by alglib.smatrixtdunpackq(), and alglib.testortfacunit.testrtdproblem().
static void alglib.ortfac.hmatrixtd (ref complex a[,], int n, bool isupper, ref complex[] tau, ref double[] d, ref double[] e) inline static
Referenced by alglib.hmatrixtd(), and alglib.testortfacunit.testctdproblem().
static void alglib.ortfac.hmatrixtdunpackq (complex a[,], int n, bool isupper, complex[] tau, ref complex q[,]) inline static
Referenced by alglib.hmatrixtdunpackq(), and alglib.testortfacunit.testctdproblem().
static void alglib.ortfac.cmatrixqrbasecase (ref complex a[,], int m, int n, ref complex[] work, ref complex[] t, ref complex[] tau) inline static private
Referenced by alglib.ortfac.cmatrixqr().
static void alglib.ortfac.cmatrixlqbasecase (ref complex a[,], int m, int n, ref complex[] work, ref complex[] t, ref complex[] tau) inline static private
Referenced by alglib.ortfac.cmatrixlq().
static void alglib.ortfac.rmatrixblockreflector (ref double a[,], ref double[] tau, bool columnwisea, int lengtha, int blocksize, ref double t[,], ref double[] work) inline static private
Referenced by alglib.ortfac.rmatrixlq(), and alglib.ortfac.rmatrixqr().
static void alglib.ortfac.cmatrixblockreflector (ref complex a[,], ref complex[] tau, bool columnwisea, int lengtha, int blocksize, ref complex t[,], ref complex[] work) inline static private
Referenced by alglib.ortfac.cmatrixlq(), and alglib.ortfac.cmatrixqr().
static void alglib.ortfac.rmatrixqr (ref double a[,], int m, int n, ref double[] tau) inline static
References alglib.ablas.ablasblocksize(), alglib.reflections.applyreflectionfromtheleft(), alglib.ortfac.rmatrixblockreflector(), alglib.ablas.rmatrixcopy(), alglib.ablas.rmatrixgemm(), and alglib.ortfac.rmatrixqrbasecase().
static void alglib.ortfac.rmatrixlq (ref double a[,], int m, int n, ref double[] tau) inline static
References alglib.ablas.ablasblocksize(), alglib.reflections.applyreflectionfromtheright(), alglib.ortfac.rmatrixblockreflector(), alglib.ablas.rmatrixcopy(), alglib.ablas.rmatrixgemm(), and alglib.ortfac.rmatrixlqbasecase().
static void alglib.ortfac.cmatrixqr (ref complex a[,], int m, int n, ref complex[] tau) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ortfac.cmatrixblockreflector(), alglib.ablas.cmatrixcopy(), alglib.ablas.cmatrixgemm(), alglib.ortfac.cmatrixqrbasecase(), alglib.creflections.complexapplyreflectionfromtheleft(), and alglib.math.conj().
static void alglib.ortfac.cmatrixlq (ref complex a[,], int m, int n, ref complex[] tau) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ortfac.cmatrixblockreflector(), alglib.ablas.cmatrixcopy(), alglib.ablas.cmatrixgemm(), alglib.ortfac.cmatrixlqbasecase(), alglib.creflections.complexapplyreflectionfromtheright(), and alglib.math.conj().
static void alglib.ortfac.rmatrixqrunpackq (double a[,], int m, int n, double[] tau, int qcolumns, ref double q[,]) inline static
References alglib.ap.assert().
static void alglib.ortfac.rmatrixqrunpackr (double a[,], int m, int n, ref double r[,]) inline static
static void alglib.ortfac.rmatrixlqunpackq (double a[,], int m, int n, double[] tau, int qrows, ref double q[,]) inline static
static void alglib.ortfac.rmatrixlqunpackl (double a[,], int m, int n, ref double l[,]) inline static
static void alglib.ortfac.cmatrixqrunpackq (complex a[,], int m, int n, complex[] tau, int qcolumns, ref complex q[,]) inline static
static void alglib.ortfac.cmatrixqrunpackr (complex a[,], int m, int n, ref complex r[,]) inline static
static void alglib.ortfac.cmatrixlqunpackq (complex a[,], int m, int n, complex[] tau, int qrows, ref complex q[,]) inline static
static void alglib.ortfac.cmatrixlqunpackl (complex a[,], int m, int n, ref complex l[,]) inline static
static void alglib.ortfac.rmatrixqrbasecase (ref double a[,], int m, int n, ref double[] work, ref double[] t, ref double[] tau) inline static
static void alglib.ortfac.rmatrixlqbasecase (ref double a[,], int m, int n, ref double[] work, ref double[] t, ref double[] tau) inline static
static void alglib.ortfac.rmatrixbd (ref double a[,], int m, int n, ref double[] tauq, ref double[] taup) inline static
static void alglib.ortfac.rmatrixbdunpackq (double qp[,], int m, int n, double[] tauq, int qcolumns, ref double q[,]) inline static
static void alglib.ortfac.rmatrixbdmultiplybyq (double qp[,], int m, int n, double[] tauq, ref double z[,], int zrows, int zcolumns, bool fromtheright, bool dotranspose) inline static
static void alglib.ortfac.rmatrixbdunpackpt (double qp[,], int m, int n, double[] taup, int ptrows, ref double pt[,]) inline static
static void alglib.ortfac.rmatrixbdmultiplybyp (double qp[,], int m, int n, double[] taup, ref double z[,], int zrows, int zcolumns, bool fromtheright, bool dotranspose) inline static
static void alglib.ortfac.rmatrixbdunpackdiagonals (double b[,], int m, int n, ref bool isupper, ref double[] d, ref double[] e) inline static
static void alglib.ortfac.rmatrixhessenberg (ref double a[,], int n, ref double[] tau) inline static
static void alglib.ortfac.rmatrixhessenbergunpackq (double a[,], int n, double[] tau, ref double q[,]) inline static
static void alglib.ortfac.rmatrixhessenbergunpackh (double a[,], int n, ref double h[,]) inline static
static void alglib.ortfac.smatrixtd (ref double a[,], int n, bool isupper, ref double[] tau, ref double[] d, ref double[] e) inline static
static void alglib.ortfac.smatrixtdunpackq (double a[,], int n, bool isupper, double[] tau, ref double q[,]) inline static
static void alglib.ortfac.hmatrixtd (ref complex a[,], int n, bool isupper, ref complex[] tau, ref double[] d, ref double[] e) inline static
static void alglib.ortfac.hmatrixtdunpackq (complex a[,], int n, bool isupper, complex[] tau, ref complex q[,]) inline static
static void alglib.ortfac.cmatrixqrbasecase (ref complex a[,], int m, int n, ref complex[] work, ref complex[] t, ref complex[] tau) inline static private
static void alglib.ortfac.cmatrixlqbasecase (ref complex a[,], int m, int n, ref complex[] work, ref complex[] t, ref complex[] tau) inline static private
static void alglib.ortfac.rmatrixblockreflector (ref double a[,], ref double[] tau, bool columnwisea, int lengtha, int blocksize, ref double t[,], ref double[] work) inline static private
static void alglib.ortfac.cmatrixblockreflector (ref complex a[,], ref complex[] tau, bool columnwisea, int lengtha, int blocksize, ref complex t[,], ref complex[] work) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/linalg.cs