IGLib: Test.BivariateSampleTest Class Reference
Test.BivariateSampleTest Class Reference
Public Member Functions
void BivariateSampleManipulations ()
void BivariateSampleEnumerations ()
void BivariateSampleCopy ()
void PearsonRDistribution ()
void LinearLogisticRegression ()
void BivariateLinearRegression ()
void BivariateLinearRegressionGoodnessOfFitDistribution ()
void BivariatePolynomialRegression ()
void BivariateLinearPolynomialRegressionAgreement ()
Member Function Documentation
void Test.BivariateSampleTest.BivariateSampleManipulations () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.BivariateSample.Clear(), Meta.Numerics.Statistics.BivariateSample.Contains(), Meta.Numerics.Statistics.BivariateSample.Count, and Meta.Numerics.Statistics.BivariateSample.Remove().
void Test.BivariateSampleTest.BivariateSampleEnumerations () inline
void Test.BivariateSampleTest.BivariateSampleCopy () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.BivariateSample.Copy(), and Meta.Numerics.Statistics.BivariateSample.Count.
void Test.BivariateSampleTest.PearsonRDistribution () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.BivariateSample.PearsonRTest(), and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.BivariateSampleTest.LinearLogisticRegression () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.Statistics.FitResult.Covariance(), Meta.Numerics.Statistics.BivariateSample.LinearLogisticRegression(), Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.BivariateSample.PopulationCovariance, Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationVariance, Meta.Numerics.UncertainValue.Value, Meta.Numerics.Statistics.BivariateSample.X, and Meta.Numerics.Statistics.BivariateSample.Y.
void Test.BivariateSampleTest.BivariateLinearRegression () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.Statistics.FitResult.Covariance(), Meta.Numerics.Statistics.Distributions.Distribution.GetRandomValue(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.BivariateSample.LinearRegression(), Meta.Numerics.Statistics.FitResult.Parameter(), Meta.Numerics.Statistics.BivariateSample.PopulationCovariance, Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationVariance, Meta.Numerics.Statistics.TestResult.Statistic, Meta.Numerics.UncertainValue.Value, Meta.Numerics.Statistics.BivariateSample.X, and Meta.Numerics.Statistics.BivariateSample.Y.
void Test.BivariateSampleTest.BivariateLinearRegressionGoodnessOfFitDistribution () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Statistics.Distributions.NormalDistribution.GetRandomValue(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.TestResult.LeftProbability, Meta.Numerics.Statistics.BivariateSample.LinearRegression(), Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Sample.PopulationMean, and Meta.Numerics.Statistics.TestResult.Statistic.
void Test.BivariateSampleTest.BivariatePolynomialRegression () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.MultivariateSample.Add(), Meta.Numerics.Statistics.Sample.Add(), Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.Statistics.MultivariateSample.Column(), Meta.Numerics.UncertainValue.ConfidenceInterval(), Meta.Numerics.Statistics.MultivariateSample.Count, Meta.Numerics.Statistics.FitResult.CovarianceMatrix(), Meta.Numerics.Statistics.MultivariateSample.Dimension, Meta.Numerics.Statistics.Distributions.Distribution.GetRandomValue(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.FitResult.Parameters(), Meta.Numerics.Statistics.BivariateSample.PolynomialRegression(), Meta.Numerics.Statistics.BivariateSample.PopulationCovariance, Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.MoreMath.Pow(), Meta.Numerics.Statistics.TestResult.Statistic, and Meta.Numerics.Statistics.MultivariateSample.TwoColumns().
void Test.BivariateSampleTest.BivariateLinearPolynomialRegressionAgreement () inline
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.FitResult.CovarianceMatrix(), Meta.Numerics.Statistics.FitResult.GoodnessOfFit, Meta.Numerics.Statistics.BivariateSample.LinearRegression(), Meta.Numerics.Statistics.FitResult.Parameters(), Meta.Numerics.Statistics.BivariateSample.PolynomialRegression(), and Meta.Numerics.Statistics.TestResult.Statistic.
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/BivariateSampleTest.cs