IGLib: alglib.spline3d Class Reference
alglib.spline3d Class Reference
Classes
class spline3dinterpolant
Static Public Member Functions
static double spline3dcalc (spline3dinterpolant c, double x, double y, double z)
static void spline3dlintransxyz (spline3dinterpolant c, double ax, double bx, double ay, double by, double az, double bz)
static void spline3dlintransf (spline3dinterpolant c, double a, double b)
static void spline3dcopy (spline3dinterpolant c, spline3dinterpolant cc)
static void spline3dresampletrilinear (double[] a, int oldzcount, int oldycount, int oldxcount, int newzcount, int newycount, int newxcount, ref double[] b)
static void spline3dbuildtrilinearv (double[] x, int n, double[] y, int m, double[] z, int l, double[] f, int d, spline3dinterpolant c)
static void spline3dcalcvbuf (spline3dinterpolant c, double x, double y, double z, ref double[] f)
static void spline3dcalcv (spline3dinterpolant c, double x, double y, double z, ref double[] f)
static void spline3dunpackv (spline3dinterpolant c, ref int n, ref int m, ref int l, ref int d, ref int stype, ref double[,] tbl)
static double spline3dcalc (spline3dinterpolant c, double x, double y, double z)
static void spline3dlintransxyz (spline3dinterpolant c, double ax, double bx, double ay, double by, double az, double bz)
static void spline3dlintransf (spline3dinterpolant c, double a, double b)
static void spline3dcopy (spline3dinterpolant c, spline3dinterpolant cc)
static void spline3dresampletrilinear (double[] a, int oldzcount, int oldycount, int oldxcount, int newzcount, int newycount, int newxcount, ref double[] b)
static void spline3dbuildtrilinearv (double[] x, int n, double[] y, int m, double[] z, int l, double[] f, int d, spline3dinterpolant c)
static void spline3dcalcvbuf (spline3dinterpolant c, double x, double y, double z, ref double[] f)
static void spline3dcalcv (spline3dinterpolant c, double x, double y, double z, ref double[] f)
static void spline3dunpackv (spline3dinterpolant c, ref int n, ref int m, ref int l, ref int d, ref int stype, ref double[,] tbl)
Static Private Member Functions
static void spline3ddiff (spline3dinterpolant c, double x, double y, double z, ref double f, ref double fx, ref double fy, ref double fxy)
static void spline3ddiff (spline3dinterpolant c, double x, double y, double z, ref double f, ref double fx, ref double fy, ref double fxy)
Member Function Documentation
static double alglib.spline3d.spline3dcalc (spline3dinterpolant c, double x, double y, double z) inline static
Referenced by alglib.testspline3dunit.basictest(), alglib.spline3dcalc(), alglib.testspline3dunit.testtrilinearresample(), and alglib.testspline3dunit.testunpack().
static void alglib.spline3d.spline3dlintransxyz (spline3dinterpolant c, double ax, double bx, double ay, double by, double az, double bz) inline static
Referenced by alglib.spline3dlintransxyz(), and alglib.testspline3dunit.testlintrans().
static void alglib.spline3d.spline3dlintransf (spline3dinterpolant c, double a, double b) inline static
Referenced by alglib.spline3dlintransf(), and alglib.testspline3dunit.testlintrans().
static void alglib.spline3d.spline3dcopy (spline3dinterpolant c, spline3dinterpolant cc) inline static
Referenced by alglib.testspline3dunit.testlintrans().
static void alglib.spline3d.spline3dresampletrilinear (double[] a, int oldzcount, int oldycount, int oldxcount, int newzcount, int newycount, int newxcount, ref double[] b) inline static
Referenced by alglib.spline3dresampletrilinear(), and alglib.testspline3dunit.testtrilinearresample().
static void alglib.spline3d.spline3dbuildtrilinearv (double[] x, int n, double[] y, int m, double[] z, int l, double[] f, int d, spline3dinterpolant c) inline static
Referenced by alglib.testspline3dunit.basictest(), alglib.spline3dbuildtrilinearv(), alglib.testspline3dunit.testlintrans(), alglib.testspline3dunit.testtrilinearresample(), and alglib.testspline3dunit.testunpack().
static void alglib.spline3d.spline3dcalcvbuf (spline3dinterpolant c, double x, double y, double z, ref double[] f) inline static
Referenced by alglib.spline3dcalcvbuf().
static void alglib.spline3d.spline3dcalcv (spline3dinterpolant c, double x, double y, double z, ref double[] f) inline static
Referenced by alglib.testspline3dunit.basictest(), alglib.spline3dcalcv(), and alglib.testspline3dunit.testlintrans().
static void alglib.spline3d.spline3dunpackv (spline3dinterpolant c, ref int n, ref int m, ref int l, ref int d, ref int stype, ref double tbl[,]) inline static
Referenced by alglib.spline3dunpackv(), and alglib.testspline3dunit.testunpack().
static void alglib.spline3d.spline3ddiff (spline3dinterpolant c, double x, double y, double z, ref double f, ref double fx, ref double fy, ref double fxy) inline static private
static double alglib.spline3d.spline3dcalc (spline3dinterpolant c, double x, double y, double z) inline static
static void alglib.spline3d.spline3dlintransxyz (spline3dinterpolant c, double ax, double bx, double ay, double by, double az, double bz) inline static
static void alglib.spline3d.spline3dlintransf (spline3dinterpolant c, double a, double b) inline static
static void alglib.spline3d.spline3dcopy (spline3dinterpolant c, spline3dinterpolant cc) inline static
static void alglib.spline3d.spline3dresampletrilinear (double[] a, int oldzcount, int oldycount, int oldxcount, int newzcount, int newycount, int newxcount, ref double[] b) inline static
static void alglib.spline3d.spline3dbuildtrilinearv (double[] x, int n, double[] y, int m, double[] z, int l, double[] f, int d, spline3dinterpolant c) inline static
static void alglib.spline3d.spline3dcalcvbuf (spline3dinterpolant c, double x, double y, double z, ref double[] f) inline static
static void alglib.spline3d.spline3dcalcv (spline3dinterpolant c, double x, double y, double z, ref double[] f) inline static
static void alglib.spline3d.spline3dunpackv (spline3dinterpolant c, ref int n, ref int m, ref int l, ref int d, ref int stype, ref double tbl[,]) inline static
static void alglib.spline3d.spline3ddiff (spline3dinterpolant c, double x, double y, double z, ref double f, ref double fx, ref double fy, ref double fxy) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/interpolation.cs