IGLib: IG.Neural.Applications.TadejFormOld Class Reference
IG.Neural.Applications.TadejFormOld Class Reference
GUI Form for training neural networks.
Public Member Functions
TadejFormOld ()
void testSmooth ()
Public Attributes
SampledDataSet trainingData = null
InputOutputDataDefiniton definitionData = null
System.Windows.Forms.TextBox tbLoad
System.Windows.Forms.Button btStartTrain
System.ComponentModel.BackgroundWorker backgroundWorker1
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string filePathSave = @"../../testdata/LoadTrainingFile/"
string savedNetwNameJson = "Network"
string savedNetwNameDat = "Network"
bool multipleNetwork = true
bool uniqueOutput = false
bool uniqueInput = false
bool zrtoData = false
int numHiddenLayers = 0
int hiddenLayer1 = 40
int hiddenLayer2 = 0
int hiddenLayer3 = 0
int maxEpoch = 5000
int epochInBoundle = 500
double toleranceRMS = 0.1
double learningRate = 0.03
double alphaValue = 2.0
double momentum = 0.6
double verifPointsPercent = 0.2
double standDeviation = 0.0
bool breakTrainingFlag = false
Properties
Boolean btStartVisible [get, set]
Private Member Functions
void backgroundWorker1_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker1_ProgressChanged (object sender, ProgressChangedEventArgs e)
string MakeTheTimeString (double time)
void backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void cBxSmoothData_CheckedChanged (object sender, EventArgs e)
void cBxMultipleNetwork_CheckedChanged (object sender, EventArgs e)
void cBxSaveNet_CheckedChanged (object sender, EventArgs e)
void cbxVerifPoints_CheckedChanged (object sender, EventArgs e)
void cbNeuralNetworkType_SelectedIndexChanged (object sender, EventArgs e)
void numHiddenLayer1_ValueChanged (object sender, EventArgs e)
void numHiddenLayer2_ValueChanged (object sender, EventArgs e)
void numHiddenLayer3_ValueChanged (object sender, EventArgs e)
void numMaxEpoch_ValueChanged (object sender, EventArgs e)
void numEpochinBoundle_ValueChanged (object sender, EventArgs e)
void numTolerance_ValueChanged (object sender, EventArgs e)
void numLearningRate_ValueChanged (object sender, EventArgs e)
void numAlphaValue_ValueChanged (object sender, EventArgs e)
void numMomentum_ValueChanged (object sender, EventArgs e)
void numStandardDev_ValueChanged (object sender, EventArgs e)
void numVerifPoints_ValueChanged (object sender, EventArgs e)
void button2_Click (object sender, EventArgs e)
void btnPredictSave_Click (object sender, EventArgs e)
void btnLoadTrainJSON_Click (object sender, EventArgs e)
void btnLoadTrainCSV_Click (object sender, EventArgs e)
void btResetTrainingData_Click (object sender, EventArgs e)
void btSelectSaveNetworkPath_Click (object sender, EventArgs e)
void TranscribeDataToNetwork ()
void btStartTrain_Click (object sender, EventArgs e)
void btStopTraining_Click (object sender, EventArgs e)
void btTestSmooth_Click (object sender, EventArgs e)
void cbxUniqueInput_CheckedChanged (object sender, EventArgs e)
void cbxUniqueOutput_CheckedChanged (object sender, EventArgs e)
void cbxZeroData_CheckedChanged (object sender, EventArgs e)
void tBxSavedNameJson_TextChanged (object sender, EventArgs e)
void tBxSavedNameDat_TextChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.OpenFileDialog openFD
System.Windows.Forms.Button btnPredictSave
System.Windows.Forms.NumericUpDown numLearningRate
System.Windows.Forms.NumericUpDown numTolerance
System.Windows.Forms.Label labLearningRate
System.Windows.Forms.NumericUpDown numEpochinBoundle
System.Windows.Forms.NumericUpDown numAlphaValue
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Label labMultipleNetwork
System.Windows.Forms.CheckBox cBxMultipleNetwork
System.Windows.Forms.NumericUpDown numHiddenLayer3
System.Windows.Forms.NumericUpDown numMomentum
System.Windows.Forms.NumericUpDown numHiddenLayer2
System.Windows.Forms.NumericUpDown numMaxEpoch
System.Windows.Forms.NumericUpDown numHiddenLayer1
System.Windows.Forms.Label labMaxEpoch
System.Windows.Forms.Label labAlphaValue
System.Windows.Forms.Label labHiddenLayer
System.Windows.Forms.Label labEpoch
System.Windows.Forms.Label labTollerance
System.Windows.Forms.Label labMomentum
System.Windows.Forms.FolderBrowserDialog folderBrouseSaveNetwork
System.Windows.Forms.GroupBox groupBox5
System.Windows.Forms.Button btnLoadTrainJSON
System.Windows.Forms.Button btnLoadTrainCSV
System.Windows.Forms.Button btResetTrainingData
System.Windows.Forms.GroupBox gbLoad
System.Windows.Forms.GroupBox gbSmooth
System.Windows.Forms.NumericUpDown numStandardDev
System.Windows.Forms.Label labStandardDev
System.Windows.Forms.Label label1
System.Windows.Forms.CheckBox cBxSmoothData
System.Windows.Forms.Label label4
System.Windows.Forms.Button btStopTraining
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.ComboBox cbNeuralNetworkType
System.Windows.Forms.Label label5
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Label labNumVerifPoints_
System.Windows.Forms.NumericUpDown numVerifPoints
System.Windows.Forms.Label labNumVerifPoints
System.Windows.Forms.CheckBox cbxVerifPoints
System.Windows.Forms.Label label14
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.GroupBox gbSaveNet
System.Windows.Forms.TextBox tbSavePath
System.Windows.Forms.Label labSaveNet2
System.Windows.Forms.TextBox tBxSavedNameJson
System.Windows.Forms.TextBox tBxSavedNameDat
System.Windows.Forms.Label labSaveNet1
System.Windows.Forms.GroupBox gbTrainSave
System.Windows.Forms.CheckBox cBxSaveNet
System.Windows.Forms.Label label3
System.Windows.Forms.Button btSelectSaveNetworkPath
System.Windows.Forms.Button btnExit
System.Windows.Forms.Button btTestSmooth
System.Windows.Forms.TextBox tbTrainPairs
System.Windows.Forms.TextBox tbOutputVal
System.Windows.Forms.TextBox tbInputPar
System.Windows.Forms.Label labInputParamSmooth
System.Windows.Forms.Label labOutputValSmooth
System.Windows.Forms.Label labTrainPairsSmooth
System.Windows.Forms.CheckBox cbxUniqueOutput
System.Windows.Forms.CheckBox cbxUniqueInput
System.Windows.Forms.Label labUniqueOutput
System.Windows.Forms.Label labUniqueInbput
System.Windows.Forms.CheckBox cbxZeroData
System.Windows.Forms.Label labZeroData
System.Windows.Forms.Label labAfter
System.Windows.Forms.Label labBefore
System.Windows.Forms.TextBox tbTrainPairsSmooth
System.Windows.Forms.TextBox tbOutputValSmooth
System.Windows.Forms.TextBox tbInputParSmooth
System.Windows.Forms.TextBox tbTrainingTime
System.Windows.Forms.ProgressBar progressBarTraining
System.Windows.Forms.Label label2
Detailed Description
GUI Form for training neural networks.
$A Tako78 May11;
Constructor & Destructor Documentation
IG.Neural.Applications.TadejFormOld.TadejFormOld () inline
Member Function Documentation
void IG.Neural.Applications.TadejFormOld.backgroundWorker1_DoWork (object sender, DoWorkEventArgs e) inline private
References IG.Num.INeuralApproximator.EpochsInBundle, IG.Num.INeuralApproximator.MaxEpochs, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.INeuralApproximator.StopTrainingCriteriaMet(), IG.Lib.StopWatch1.TotalTime, and IG.Num.INeuralApproximator.TrainNetwork().
void IG.Neural.Applications.TadejFormOld.backgroundWorker1_ProgressChanged (object sender, ProgressChangedEventArgs e) inline private
string IG.Neural.Applications.TadejFormOld.MakeTheTimeString (double time) inline private
void IG.Neural.Applications.TadejFormOld.backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork_CheckedChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.cbxVerifPoints_CheckedChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.numHiddenLayer1_ValueChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.numHiddenLayer2_ValueChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.numHiddenLayer3_ValueChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.numMaxEpoch_ValueChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.numEpochinBoundle_ValueChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.numTolerance_ValueChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.numLearningRate_ValueChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.numAlphaValue_ValueChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.numMomentum_ValueChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.numStandardDev_ValueChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.numVerifPoints_ValueChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.button2_Click (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.btnPredictSave_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.ProgramTestTadejApp.TestPrediction().
void IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON_Click (object sender, EventArgs e) inline private
References IG.Neural.NeuralTadej.LoadSampledDataJson().
void IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.formLoadCSV.tadejForm.
void IG.Neural.Applications.TadejFormOld.btResetTrainingData_Click (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath_Click (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork () inline private
References IG.Lib.IndexList.CreateRandom(), IG.Num.INeuralApproximator.EpochsInBundle, IG.Num.INeuralApproximator.InputBoundsSafetyFactor, IG.Num.IVectorApproximator.InputLength, IG.Num.SampledDataSet.InputLength, IG.Num.INeuralApproximator.InputNeuronsRange, IG.Num.INeuralApproximator.LearningRate, IG.Num.SampledDataSet.Length, IG.Num.INeuralApproximator.MaxEpochs, IG.Num.INeuralApproximator.Momentum, IG.Num.INeuralApproximator.MultipleNetworks, IG.Num.INeuralApproximator.OutputBoundsSafetyFactor, IG.Num.IVectorApproximator.OutputLength, IG.Num.SampledDataSet.OutputLength, IG.Num.INeuralApproximator.OutputLevel, IG.Num.INeuralApproximator.OutputNeuronsRange, IG.Num.IBoundingBox.Reset(), IG.Num.INeuralApproximator.SetHiddenLayers(), IG.Num.INeuralApproximator.SigmoidAlphaValue, IG.Neural.NeuralTadej.SmoothingTrainingData(), IG.Num.INeuralApproximator.ToleranceRms, IG.Num.INeuralApproximator.TrainingData, IG.Num.IBoundingBox.UpdateAll(), and IG.Num.INeuralApproximator.VerificationIndices.
void IG.Neural.Applications.TadejFormOld.btStartTrain_Click (object sender, EventArgs e) inline private
References IG.Num.INeuralApproximator.BreakTraining.
void IG.Neural.Applications.TadejFormOld.btStopTraining_Click (object sender, EventArgs e) inline private
References IG.Num.INeuralApproximator.BreakTraining.
void IG.Neural.Applications.TadejFormOld.btTestSmooth_Click (object sender, EventArgs e) inline private
References IG.Neural.NeuralTadej.SmoothingTrainingData().
void IG.Neural.Applications.TadejFormOld.cbxUniqueInput_CheckedChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.cbxUniqueOutput_CheckedChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.cbxZeroData_CheckedChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.tBxSavedNameJson_TextChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.tBxSavedNameDat_TextChanged (object sender, EventArgs e) inline private
void IG.Neural.Applications.TadejFormOld.testSmooth () inline
References IG.Num.SampledDataSet.InputLength, IG.Num.SampledDataSet.Length, and IG.Num.SampledDataSet.OutputLength.
override void IG.Neural.Applications.TadejFormOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
void IG.Neural.Applications.TadejFormOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Member Data Documentation
SampledDataSet IG.Neural.Applications.TadejFormOld.trainingData = null
Referenced by IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click().
InputOutputDataDefiniton IG.Neural.Applications.TadejFormOld.definitionData = null
Referenced by IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click().
string IG.Neural.Applications.TadejFormOld.filePathSave = @"../../testdata/LoadTrainingFile/" protected
string IG.Neural.Applications.TadejFormOld.savedNetwNameJson = "Network" protected
string IG.Neural.Applications.TadejFormOld.savedNetwNameDat = "Network" protected
bool IG.Neural.Applications.TadejFormOld.multipleNetwork = true protected
bool IG.Neural.Applications.TadejFormOld.uniqueOutput = false protected
bool IG.Neural.Applications.TadejFormOld.uniqueInput = false protected
bool IG.Neural.Applications.TadejFormOld.zrtoData = false protected
int IG.Neural.Applications.TadejFormOld.numHiddenLayers = 0 protected
int IG.Neural.Applications.TadejFormOld.hiddenLayer1 = 40 protected
int IG.Neural.Applications.TadejFormOld.hiddenLayer2 = 0 protected
int IG.Neural.Applications.TadejFormOld.hiddenLayer3 = 0 protected
int IG.Neural.Applications.TadejFormOld.maxEpoch = 5000 protected
int IG.Neural.Applications.TadejFormOld.epochInBoundle = 500 protected
double IG.Neural.Applications.TadejFormOld.toleranceRMS = 0.1 protected
double IG.Neural.Applications.TadejFormOld.learningRate = 0.03 protected
double IG.Neural.Applications.TadejFormOld.alphaValue = 2.0 protected
double IG.Neural.Applications.TadejFormOld.momentum = 0.6 protected
double IG.Neural.Applications.TadejFormOld.verifPointsPercent = 0.2 protected
double IG.Neural.Applications.TadejFormOld.standDeviation = 0.0 protected
bool IG.Neural.Applications.TadejFormOld.breakTrainingFlag = false protected
System.ComponentModel.IContainer IG.Neural.Applications.TadejFormOld.components = null private
Required designer variable.
System.Windows.Forms.OpenFileDialog IG.Neural.Applications.TadejFormOld.openFD private
System.Windows.Forms.Button IG.Neural.Applications.TadejFormOld.btnPredictSave private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.TadejFormOld.numLearningRate private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.TadejFormOld.numTolerance private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labLearningRate private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.TadejFormOld.numEpochinBoundle private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.TadejFormOld.numAlphaValue private
System.Windows.Forms.GroupBox IG.Neural.Applications.TadejFormOld.groupBox2 private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labMultipleNetwork private
System.Windows.Forms.CheckBox IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.TadejFormOld.numHiddenLayer3 private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.TadejFormOld.numMomentum private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.TadejFormOld.numHiddenLayer2 private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.TadejFormOld.numMaxEpoch private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.TadejFormOld.numHiddenLayer1 private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labMaxEpoch private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labAlphaValue private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labHiddenLayer private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labEpoch private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labTollerance private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labMomentum private
System.Windows.Forms.FolderBrowserDialog IG.Neural.Applications.TadejFormOld.folderBrouseSaveNetwork private
System.Windows.Forms.GroupBox IG.Neural.Applications.TadejFormOld.groupBox5 private
System.Windows.Forms.TextBox IG.Neural.Applications.TadejFormOld.tbLoad
System.Windows.Forms.Button IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON private
System.Windows.Forms.Button IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV private
System.Windows.Forms.Button IG.Neural.Applications.TadejFormOld.btResetTrainingData private
System.Windows.Forms.GroupBox IG.Neural.Applications.TadejFormOld.gbLoad private
System.Windows.Forms.GroupBox IG.Neural.Applications.TadejFormOld.gbSmooth private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.TadejFormOld.numStandardDev private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labStandardDev private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.label1 private
System.Windows.Forms.CheckBox IG.Neural.Applications.TadejFormOld.cBxSmoothData private
System.Windows.Forms.Button IG.Neural.Applications.TadejFormOld.btStartTrain
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.label4 private
System.Windows.Forms.Button IG.Neural.Applications.TadejFormOld.btStopTraining private
System.Windows.Forms.GroupBox IG.Neural.Applications.TadejFormOld.groupBox4 private
System.Windows.Forms.ComboBox IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.label5 private
System.Windows.Forms.GroupBox IG.Neural.Applications.TadejFormOld.groupBox1 private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labNumVerifPoints_ private
System.Windows.Forms.NumericUpDown IG.Neural.Applications.TadejFormOld.numVerifPoints private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labNumVerifPoints private
System.Windows.Forms.CheckBox IG.Neural.Applications.TadejFormOld.cbxVerifPoints private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.label14 private
System.Windows.Forms.GroupBox IG.Neural.Applications.TadejFormOld.groupBox3 private
System.Windows.Forms.GroupBox IG.Neural.Applications.TadejFormOld.gbSaveNet private
System.Windows.Forms.TextBox IG.Neural.Applications.TadejFormOld.tbSavePath private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labSaveNet2 private
System.Windows.Forms.TextBox IG.Neural.Applications.TadejFormOld.tBxSavedNameJson private
System.Windows.Forms.TextBox IG.Neural.Applications.TadejFormOld.tBxSavedNameDat private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labSaveNet1 private
System.Windows.Forms.GroupBox IG.Neural.Applications.TadejFormOld.gbTrainSave private
System.Windows.Forms.CheckBox IG.Neural.Applications.TadejFormOld.cBxSaveNet private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.label3 private
System.Windows.Forms.Button IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath private
System.Windows.Forms.Button IG.Neural.Applications.TadejFormOld.btnExit private
System.Windows.Forms.Button IG.Neural.Applications.TadejFormOld.btTestSmooth private
System.Windows.Forms.TextBox IG.Neural.Applications.TadejFormOld.tbTrainPairs private
System.Windows.Forms.TextBox IG.Neural.Applications.TadejFormOld.tbOutputVal private
System.Windows.Forms.TextBox IG.Neural.Applications.TadejFormOld.tbInputPar private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labInputParamSmooth private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labOutputValSmooth private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labTrainPairsSmooth private
System.Windows.Forms.CheckBox IG.Neural.Applications.TadejFormOld.cbxUniqueOutput private
System.Windows.Forms.CheckBox IG.Neural.Applications.TadejFormOld.cbxUniqueInput private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labUniqueOutput private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labUniqueInbput private
System.Windows.Forms.CheckBox IG.Neural.Applications.TadejFormOld.cbxZeroData private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labZeroData private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labAfter private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.labBefore private
System.Windows.Forms.TextBox IG.Neural.Applications.TadejFormOld.tbTrainPairsSmooth private
System.Windows.Forms.TextBox IG.Neural.Applications.TadejFormOld.tbOutputValSmooth private
System.Windows.Forms.TextBox IG.Neural.Applications.TadejFormOld.tbInputParSmooth private
System.ComponentModel.BackgroundWorker IG.Neural.Applications.TadejFormOld.backgroundWorker1
System.Windows.Forms.TextBox IG.Neural.Applications.TadejFormOld.tbTrainingTime private
System.Windows.Forms.ProgressBar IG.Neural.Applications.TadejFormOld.progressBarTraining private
System.Windows.Forms.Label IG.Neural.Applications.TadejFormOld.label2 private
Property Documentation
Boolean IG.Neural.Applications.TadejFormOld.btStartVisible get set
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralApplications/TadejFormOld/TadejForm.cs
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralApplications/TadejFormOld/TadejForm.designer.cs