IGLib: CShell.AssemblyReferences Class Reference
CShell.AssemblyReferences Class Reference
Public Member Functions
AssemblyReferences (ScriptingEngine engine)
void Dispose ()
void Add (AssemblyName assemblyName)
void Add (string file)
void AddReferences (string path)
void AddReferences (string path, string searchPattern)
Assembly ResolveAssembly (string assemblyFullName)
Assembly ResolveAssembly (string assemblyFullName, Assembly requestingAssembly)
AssemblyReferences (ScriptingEngine engine)
void Dispose ()
void Add (AssemblyName assemblyName)
void Add (string file)
void AddReferences (string path)
void AddReferences (string path, string searchPattern)
Assembly ResolveAssembly (string assemblyFullName)
Assembly ResolveAssembly (string assemblyFullName, Assembly requestingAssembly)
Protected Member Functions
override string GetKeyForItem (AssemblyReference item)
override void InsertItem (int index, AssemblyReference item)
override void SetItem (int index, AssemblyReference item)
override string GetKeyForItem (AssemblyReference item)
override void InsertItem (int index, AssemblyReference item)
override void SetItem (int index, AssemblyReference item)
Private Member Functions
Assembly CurrentDomainOnAssemblyResolve (object sender, ResolveEventArgs args)
Assembly CurrentDomainOnAssemblyResolve (object sender, ResolveEventArgs args)
Private Attributes
readonly ScriptingEngine engine
Constructor & Destructor Documentation
CShell.AssemblyReferences.AssemblyReferences (ScriptingEngine engine) inline
References CShell.AssemblyReferences.CurrentDomainOnAssemblyResolve(), and CShell.AssemblyReferences.engine.
CShell.AssemblyReferences.AssemblyReferences (ScriptingEngine engine) inline
References CShell.AssemblyReferences.CurrentDomainOnAssemblyResolve(), and CShell.AssemblyReferences.engine.
Member Function Documentation
void CShell.AssemblyReferences.Dispose () inline
References CShell.AssemblyReferences.CurrentDomainOnAssemblyResolve().
override string CShell.AssemblyReferences.GetKeyForItem (AssemblyReference item) inline protected
References CShell.AssemblyReference.AssemblyName.
override void CShell.AssemblyReferences.InsertItem (int index, AssemblyReference item) inline protected
References CShell.AssemblyReference.Assembly, and CShell.AssemblyReference.Available.
override void CShell.AssemblyReferences.SetItem (int index, AssemblyReference item) inline protected
References CShell.AssemblyReference.Assembly, and CShell.AssemblyReference.Available.
void CShell.AssemblyReferences.Add (AssemblyName assemblyName) inline
Referenced by CShell.AssemblyReferences.Add(), CShell.AssemblyReferences.AddReferences(), and CShell.Workspace.Load().
void CShell.AssemblyReferences.Add (string file) inline
References CShell.AssemblyReferences.Add().
void CShell.AssemblyReferences.AddReferences (string path) inline
Referenced by CShell.AssemblyReferences.AddReferences().
void CShell.AssemblyReferences.AddReferences (string path, string searchPattern) inline
References CShell.AssemblyReferences.Add().
Assembly CShell.AssemblyReferences.CurrentDomainOnAssemblyResolve (object sender, ResolveEventArgs args) inline private
References CShell.AssemblyReferences.ResolveAssembly().
Referenced by CShell.AssemblyReferences.AssemblyReferences(), and CShell.AssemblyReferences.Dispose().
Assembly CShell.AssemblyReferences.ResolveAssembly (string assemblyFullName) inline
Referenced by CShell.AssemblyReferences.CurrentDomainOnAssemblyResolve(), and CShell.AssemblyReferences.ResolveAssembly().
Assembly CShell.AssemblyReferences.ResolveAssembly (string assemblyFullName, Assembly requestingAssembly) inline
References CShell.AssemblyLoader.GetAssemblyName(), and CShell.AssemblyLoader.GetAssemblySearchFiles().
void CShell.AssemblyReferences.Dispose () inline
References CShell.AssemblyReferences.CurrentDomainOnAssemblyResolve().
override string CShell.AssemblyReferences.GetKeyForItem (AssemblyReference item) inline protected
References CShell.AssemblyReference.AssemblyName.
override void CShell.AssemblyReferences.InsertItem (int index, AssemblyReference item) inline protected
References CShell.AssemblyReference.Assembly, and CShell.AssemblyReference.Available.
override void CShell.AssemblyReferences.SetItem (int index, AssemblyReference item) inline protected
References CShell.AssemblyReference.Assembly, and CShell.AssemblyReference.Available.
void CShell.AssemblyReferences.Add (AssemblyName assemblyName) inline
References CShell.AssemblyReferences.Add().
void CShell.AssemblyReferences.Add (string file) inline
References CShell.AssemblyReferences.Add().
void CShell.AssemblyReferences.AddReferences (string path) inline
References CShell.AssemblyReferences.AddReferences().
void CShell.AssemblyReferences.AddReferences (string path, string searchPattern) inline
References CShell.AssemblyReferences.Add().
Assembly CShell.AssemblyReferences.CurrentDomainOnAssemblyResolve (object sender, ResolveEventArgs args) inline private
References CShell.AssemblyReferences.ResolveAssembly().
Assembly CShell.AssemblyReferences.ResolveAssembly (string assemblyFullName) inline
References CShell.AssemblyReferences.ResolveAssembly().
Assembly CShell.AssemblyReferences.ResolveAssembly (string assemblyFullName, Assembly requestingAssembly) inline
References CShell.AssemblyLoader.GetAssemblyName(), and CShell.AssemblyLoader.GetAssemblySearchFiles().
Member Data Documentation
readonly ScriptingEngine CShell.AssemblyReferences.engine private
Referenced by CShell.AssemblyReferences.AssemblyReferences().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/AssemblyReferences.cs