IGLib: CShell.Workspace Class Reference
CShell.Workspace Class Reference
Classes
class WorkspaceContainer
Public Member Functions
void Save (string path)
void Save (string path, bool saveShellLayout)
bool Load (string path)
bool Load (string path, bool loadShellLayout)
void Save (string path)
void Save (string path, bool saveShellLayout)
bool Load (string path)
bool Load (string path, bool loadShellLayout)
Static Public Member Functions
static void CreateEmptyFile (string filePath)
static void CreateEmptyFile (string filePath)
Properties
string CShellFileName [get, private set]
Gets CShell file name without extension.
string CShellFile [get, private set]
ScriptingEngine ScriptingEngine [get]
AssemblyReferences Assemblies [get]
string RootFolder [get, set]
string Filter [get, set]
Events
PropertyChangedEventHandler PropertyChanged
Private Member Functions
void OnPropertyChanged (string propertyName)
void OnPropertyChanged (string propertyName)
Private Attributes
readonly ILog log = LogManager.GetLog(typeof (Workspace))
readonly ScriptingEngine engine
readonly AssemblyReferences assemblies
string rootFolder
string filter = Constants.WorkspaceFilter
Static Private Attributes
static readonly string startupDirectory = Environment.CurrentDirectory
Member Function Documentation
void CShell.Workspace.OnPropertyChanged (string propertyName) inline private
References CShell.Workspace.PropertyChanged.
static void CShell.Workspace.CreateEmptyFile (string filePath) inline static
References CShell.Constants.CShellTemplatesPath.
Referenced by CShell.Modules.Workspace.Results.AddFilesResult.Execute().
void CShell.Workspace.Save (string path) inline
Referenced by CShell.Workspace.Save().
void CShell.Workspace.Save (string path, bool saveShellLayout) inline
References CShell.Workspace.Assemblies, CShell.Workspace.Filter, CShell.Workspace.RootFolder, and CShell.Framework.Services.IShell.SaveLayout().
bool CShell.Workspace.Load (string path) inline
Referenced by CShell.Workspace.Load().
bool CShell.Workspace.Load (string path, bool loadShellLayout) inline
References CShell.AssemblyReferences.Add(), CShell.Workspace.Assemblies, CShell.Workspace.WorkspaceContainer.AssemblyFileReferences, CShell.Workspace.WorkspaceContainer.AssemblyNameReferences, CShell.Workspace.Filter, CShell.Workspace.WorkspaceContainer.Filter, CShell.Framework.Services.IShell.LoadLayout(), CShell.Workspace.RootFolder, and CShell.Workspace.WorkspaceContainer.RootFolder.
void CShell.Workspace.OnPropertyChanged (string propertyName) inline private
References CShell.Workspace.PropertyChanged.
static void CShell.Workspace.CreateEmptyFile (string filePath) inline static
References CShell.Constants.CShellTemplatesPath.
void CShell.Workspace.Save (string path) inline
References CShell.Workspace.Save().
void CShell.Workspace.Save (string path, bool saveShellLayout) inline
References CShell.Workspace.Assemblies, CShell.Workspace.Filter, CShell.Workspace.RootFolder, and CShell.Framework.Services.IShell.SaveLayout().
bool CShell.Workspace.Load (string path) inline
References CShell.Workspace.Load().
bool CShell.Workspace.Load (string path, bool loadShellLayout) inline
References CShell.AssemblyReferences.Add(), CShell.Workspace.Assemblies, CShell.Workspace.WorkspaceContainer.AssemblyFileReferences, CShell.Workspace.WorkspaceContainer.AssemblyNameReferences, CShell.Workspace.Filter, CShell.Workspace.WorkspaceContainer.Filter, CShell.Framework.Services.IShell.LoadLayout(), CShell.Workspace.RootFolder, and CShell.Workspace.WorkspaceContainer.RootFolder.
Member Data Documentation
readonly ILog CShell.Workspace.log = LogManager.GetLog(typeof (Workspace)) private
readonly ScriptingEngine CShell.Workspace.engine private
static readonly string CShell.Workspace.startupDirectory = Environment.CurrentDirectory static private
readonly AssemblyReferences CShell.Workspace.assemblies private
string CShell.Workspace.rootFolder private
string CShell.Workspace.filter = Constants.WorkspaceFilter private
Property Documentation
string CShell.Workspace.CShellFileName get private set
Gets CShell file name without extension.
string CShell.Workspace.CShellFile get private set
ScriptingEngine CShell.Workspace.ScriptingEngine get
Referenced by CShell.Shell.EvaluateFile(), CShell.Framework.Results.RunCodeResult.Execute(), CShell.Modules.Editors.ViewModels.EditorViewModel.OnViewLoaded(), and CShell.Modules.Repl.ViewModels.OutputViewModel.OutputViewModel().
AssemblyReferences CShell.Workspace.Assemblies get
Referenced by CShell.Modules.Workspace.Module.AddReferenceFromFile(), CShell.Modules.Workspace.Module.AddReferenceFromGac(), CShell.AssemblyLoader.Handle(), CShell.Workspace.Load(), and CShell.Workspace.Save().
string CShell.Workspace.RootFolder get set
Referenced by CShell.Workspace.Load(), CShell.Modules.Workspace.ViewModels.RootFolderSettingsViewModel.Ok(), CShell.Modules.Workspace.ViewModels.RootFolderSettingsViewModel.RootFolderSettingsViewModel(), and CShell.Workspace.Save().
string CShell.Workspace.Filter get set
Referenced by CShell.Workspace.Load(), and CShell.Workspace.Save().
Event Documentation
PropertyChangedEventHandler CShell.Workspace.PropertyChanged
Referenced by CShell.Workspace.OnPropertyChanged().
The documentation for this class was generated from the following files:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Workspace.cs
shelldev/repl/CShell-0.1.2/Src/CShellCore/Workspace.Serialization.cs