IGLib: alglib.bdss Class Reference
alglib.bdss Class Reference
Classes
class cvreport
Static Public Member Functions
static void dserrallocate (int nclasses, ref double[] buf)
static void dserraccumulate (ref double[] buf, double[] y, double[] desiredy)
static void dserrfinish (ref double[] buf)
static void dsnormalize (ref double[,] xy, int npoints, int nvars, ref int info, ref double[] means, ref double[] sigmas)
static void dsnormalizec (double[,] xy, int npoints, int nvars, ref int info, ref double[] means, ref double[] sigmas)
static double dsgetmeanmindistance (double[,] xy, int npoints, int nvars)
static void dstie (ref double[] a, int n, ref int[] ties, ref int tiecount, ref int[] p1, ref int[] p2)
static void dstiefasti (ref double[] a, ref int[] b, int n, ref int[] ties, ref int tiecount, ref double[] bufr, ref int[] bufi)
static void dsoptimalsplit2 (double[] a, int[] c, int n, ref int info, ref double threshold, ref double pal, ref double pbl, ref double par, ref double pbr, ref double cve)
static void dsoptimalsplit2fast (ref double[] a, ref int[] c, ref int[] tiesbuf, ref int[] cntbuf, ref double[] bufr, ref int[] bufi, int n, int nc, double alpha, ref int info, ref double threshold, ref double rms, ref double cvrms)
static void dssplitk (double[] a, int[] c, int n, int nc, int kmax, ref int info, ref double[] thresholds, ref int ni, ref double cve)
static void dsoptimalsplitk (double[] a, int[] c, int n, int nc, int kmax, ref int info, ref double[] thresholds, ref int ni, ref double cve)
static void dserrallocate (int nclasses, ref double[] buf)
static void dserraccumulate (ref double[] buf, double[] y, double[] desiredy)
static void dserrfinish (ref double[] buf)
static void dsnormalize (ref double[,] xy, int npoints, int nvars, ref int info, ref double[] means, ref double[] sigmas)
static void dsnormalizec (double[,] xy, int npoints, int nvars, ref int info, ref double[] means, ref double[] sigmas)
static double dsgetmeanmindistance (double[,] xy, int npoints, int nvars)
static void dstie (ref double[] a, int n, ref int[] ties, ref int tiecount, ref int[] p1, ref int[] p2)
static void dstiefasti (ref double[] a, ref int[] b, int n, ref int[] ties, ref int tiecount, ref double[] bufr, ref int[] bufi)
static void dsoptimalsplit2 (double[] a, int[] c, int n, ref int info, ref double threshold, ref double pal, ref double pbl, ref double par, ref double pbr, ref double cve)
static void dsoptimalsplit2fast (ref double[] a, ref int[] c, ref int[] tiesbuf, ref int[] cntbuf, ref double[] bufr, ref int[] bufi, int n, int nc, double alpha, ref int info, ref double threshold, ref double rms, ref double cvrms)
static void dssplitk (double[] a, int[] c, int n, int nc, int kmax, ref int info, ref double[] thresholds, ref int ni, ref double cve)
static void dsoptimalsplitk (double[] a, int[] c, int n, int nc, int kmax, ref int info, ref double[] thresholds, ref int ni, ref double cve)
Static Private Member Functions
static double xlny (double x, double y)
static double getcv (int[] cnt, int nc)
static void tieaddc (int[] c, int[] ties, int ntie, int nc, ref int[] cnt)
static void tiesubc (int[] c, int[] ties, int ntie, int nc, ref int[] cnt)
static double xlny (double x, double y)
static double getcv (int[] cnt, int nc)
static void tieaddc (int[] c, int[] ties, int ntie, int nc, ref int[] cnt)
static void tiesubc (int[] c, int[] ties, int ntie, int nc, ref int[] cnt)
Member Function Documentation
static void alglib.bdss.dserrallocate (int nclasses, ref double[] buf) inline static
Referenced by alglib.logit.mnlallerrors().
static void alglib.bdss.dserraccumulate (ref double[] buf, double[] y, double[] desiredy) inline static
References alglib.math.maxrealnumber, and alglib.math.sqr().
Referenced by alglib.logit.mnlallerrors().
static void alglib.bdss.dserrfinish (ref double[] buf) inline static
Referenced by alglib.logit.mnlallerrors().
static void alglib.bdss.dsnormalize (ref double xy[,], int npoints, int nvars, ref int info, ref double[] means, ref double[] sigmas) inline static
References alglib.basestat.samplemoments().
static void alglib.bdss.dsnormalizec (double xy[,], int npoints, int nvars, ref int info, ref double[] means, ref double[] sigmas) inline static
References alglib.basestat.samplemoments().
static double alglib.bdss.dsgetmeanmindistance (double xy[,], int npoints, int nvars) inline static
References alglib.math.maxrealnumber.
static void alglib.bdss.dstie (ref double[] a, int n, ref int[] ties, ref int tiecount, ref int[] p1, ref int[] p2) inline static
References alglib.tsort.tagsort().
Referenced by alglib.bdss.dsoptimalsplit2(), alglib.bdss.dsoptimalsplitk(), alglib.bdss.dssplitk(), and alglib.testbdssunit.testbdss().
static void alglib.bdss.dstiefasti (ref double[] a, ref int[] b, int n, ref int[] ties, ref int tiecount, ref double[] bufr, ref int[] bufi) inline static
References alglib.tsort.tagsortfasti().
Referenced by alglib.bdss.dsoptimalsplit2fast().
static void alglib.bdss.dsoptimalsplit2 (double[] a, int[] c, int n, ref int info, ref double threshold, ref double pal, ref double pbl, ref double par, ref double pbr, ref double cve) inline static
References alglib.bdss.dstie(), alglib.math.maxrealnumber, and alglib.bdss.xlny().
Referenced by alglib.dsoptimalsplit2(), and alglib.testbdssunit.testbdss().
static void alglib.bdss.dsoptimalsplit2fast (ref double[] a, ref int[] c, ref int[] tiesbuf, ref int[] cntbuf, ref double[] bufr, ref int[] bufi, int n, int nc, double alpha, ref int info, ref double threshold, ref double rms, ref double cvrms) inline static
References alglib.bdss.dstiefasti(), alglib.math.maxrealnumber, and alglib.math.sqr().
Referenced by alglib.dsoptimalsplit2fast(), and alglib.testbdssunit.testbdss().
static void alglib.bdss.dssplitk (double[] a, int[] c, int n, int nc, int kmax, ref int info, ref double[] thresholds, ref int ni, ref double cve) inline static
References alglib.ap.assert(), alglib.bdss.dstie(), alglib.bdss.getcv(), alglib.math.maxrealnumber, and alglib.bdss.tieaddc().
Referenced by alglib.testbdssunit.testbdss().
static void alglib.bdss.dsoptimalsplitk (double[] a, int[] c, int n, int nc, int kmax, ref int info, ref double[] thresholds, ref int ni, ref double cve) inline static
References alglib.ap.assert(), alglib.bdss.dstie(), alglib.bdss.getcv(), alglib.math.maxrealnumber, alglib.bdss.tieaddc(), and alglib.bdss.tiesubc().
Referenced by alglib.testbdssunit.testbdss().
static double alglib.bdss.xlny (double x, double y) inline static private
Referenced by alglib.bdss.dsoptimalsplit2(), and alglib.bdss.getcv().
static double alglib.bdss.getcv (int[] cnt, int nc) inline static private
References alglib.bdss.xlny().
Referenced by alglib.bdss.dsoptimalsplitk(), and alglib.bdss.dssplitk().
static void alglib.bdss.tieaddc (int[] c, int[] ties, int ntie, int nc, ref int[] cnt) inline static private
Referenced by alglib.bdss.dsoptimalsplitk(), and alglib.bdss.dssplitk().
static void alglib.bdss.tiesubc (int[] c, int[] ties, int ntie, int nc, ref int[] cnt) inline static private
Referenced by alglib.bdss.dsoptimalsplitk().
static void alglib.bdss.dserrallocate (int nclasses, ref double[] buf) inline static
static void alglib.bdss.dserraccumulate (ref double[] buf, double[] y, double[] desiredy) inline static
References alglib.math.maxrealnumber, and alglib.math.sqr().
static void alglib.bdss.dserrfinish (ref double[] buf) inline static
static void alglib.bdss.dsnormalize (ref double xy[,], int npoints, int nvars, ref int info, ref double[] means, ref double[] sigmas) inline static
References alglib.basestat.samplemoments().
static void alglib.bdss.dsnormalizec (double xy[,], int npoints, int nvars, ref int info, ref double[] means, ref double[] sigmas) inline static
References alglib.basestat.samplemoments().
static double alglib.bdss.dsgetmeanmindistance (double xy[,], int npoints, int nvars) inline static
References alglib.math.maxrealnumber.
static void alglib.bdss.dstie (ref double[] a, int n, ref int[] ties, ref int tiecount, ref int[] p1, ref int[] p2) inline static
References alglib.tsort.tagsort().
static void alglib.bdss.dstiefasti (ref double[] a, ref int[] b, int n, ref int[] ties, ref int tiecount, ref double[] bufr, ref int[] bufi) inline static
References alglib.tsort.tagsortfasti().
static void alglib.bdss.dsoptimalsplit2 (double[] a, int[] c, int n, ref int info, ref double threshold, ref double pal, ref double pbl, ref double par, ref double pbr, ref double cve) inline static
References alglib.bdss.dstie(), alglib.math.maxrealnumber, and alglib.bdss.xlny().
static void alglib.bdss.dsoptimalsplit2fast (ref double[] a, ref int[] c, ref int[] tiesbuf, ref int[] cntbuf, ref double[] bufr, ref int[] bufi, int n, int nc, double alpha, ref int info, ref double threshold, ref double rms, ref double cvrms) inline static
References alglib.bdss.dstiefasti(), alglib.math.maxrealnumber, and alglib.math.sqr().
static void alglib.bdss.dssplitk (double[] a, int[] c, int n, int nc, int kmax, ref int info, ref double[] thresholds, ref int ni, ref double cve) inline static
References alglib.ap.assert(), alglib.bdss.dstie(), alglib.bdss.getcv(), alglib.math.maxrealnumber, and alglib.bdss.tieaddc().
static void alglib.bdss.dsoptimalsplitk (double[] a, int[] c, int n, int nc, int kmax, ref int info, ref double[] thresholds, ref int ni, ref double cve) inline static
References alglib.ap.assert(), alglib.bdss.dstie(), alglib.bdss.getcv(), alglib.math.maxrealnumber, alglib.bdss.tieaddc(), alglib.bdss.tiesubc(), and alglib.apserv.touchint().
static double alglib.bdss.xlny (double x, double y) inline static private
static double alglib.bdss.getcv (int[] cnt, int nc) inline static private
References alglib.bdss.xlny().
static void alglib.bdss.tieaddc (int[] c, int[] ties, int ntie, int nc, ref int[] cnt) inline static private
static void alglib.bdss.tiesubc (int[] c, int[] ties, int ntie, int nc, ref int[] cnt) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/dataanalysis.cs