IGLib: Package NUnit.Framework
Package NUnit.Framework
Namespaces
package Api
package Assertions
package Attributes
package Compatibility
package Constraints
package Interfaces
package Internal
package Syntax
package Tests
Classes
class ApartmentAttribute
Marks a test that must run in a particular threading apartment state, causing it to run in a separate thread if necessary.
class Assert
The Assert class contains a collection of static methods that implement the most common assertions used in NUnit.
class AssertionException
Thrown when an assertion failed.
class AssertionHelper
AssertionHelper is an optional base class for user tests, allowing the use of shorter ids for constraints and asserts and avoiding conflict with the definition of Is, from which it inherits much of its behavior, in certain mock object frameworks.
class Assume
Provides static methods to express the assumptions that must be met for a test to give a meaningful result. If an assumption is not met, the test should produce an inconclusive result.
class AuthorAttribute
Provides the Author of a test or test fixture.
class CategoryAttribute
Attribute used to apply a category to a test
class CollectionAssert
A set of Assert methods operating on one or more collections
class CombinatorialAttribute
Marks a test to use a combinatorial join of any argument data provided. Since this is the default, the attribute is optional.
class CombiningStrategyAttribute
Marks a test to use a particular CombiningStrategy to join any parameter data provided. Since this is the default, the attribute is optional.
class Contains
Helper class with properties and methods that supply a number of constraints used in Asserts.
class CultureAttribute
CultureAttribute is used to mark a test fixture or an individual method as applying to a particular Culture only.
class DataAttribute
The abstract base class for all data-providing attributes defined by NUnit. Used to select all data sources for a method, class or parameter.
class DatapointAttribute
Used to mark a field for use as a datapoint when executing a theory within the same fixture that requires an argument of the field's Type.
class DatapointsAttribute
Used to mark a field, property or method providing a set of datapoints to be used in executing any theories within the same fixture that require an argument of the Type provided. The data source may provide an array of the required Type or an IEnumerable{T}. Synonymous with DatapointSourceAttribute.
class DatapointSourceAttribute
Used to mark a field, property or method providing a set of datapoints to be used in executing any theories within the same fixture that require an argument of the Type provided. The data source may provide an array of the required Type or an IEnumerable{T}. Synonymous with DatapointsAttribute.
class DescriptionAttribute
Attribute used to provide descriptive text about a test case or fixture.
class DirectoryAssert
Asserts on Directories
class Does
Helper class with properties and methods that supply a number of constraints used in Asserts.
class ExplicitAttribute
ExplicitAttribute marks a test or test fixture so that it will only be run if explicitly executed from the gui or command line or if it is included by use of a filter. The test will not be run simply because an enclosing suite is run.
class FileAssert
Asserts on Files
class GlobalSettings
GlobalSettings is a place for setting default _values used by the framework in performing asserts.
class Has
Helper class with properties and methods that supply a number of constraints used in Asserts.
class IgnoreAttribute
Attribute used to mark a test that is to be ignored. Ignored tests result in a warning message when the tests are run.
class IgnoreException
Thrown when an assertion failed.
class IncludeExcludeAttribute
Abstract base for Attributes that are used to include tests in the test run based on environmental settings.
class InconclusiveException
Thrown when a test executes inconclusively.
class Is
Helper class with properties and methods that supply a number of constraints used in Asserts.
interface ITestAction
When implemented by an attribute, this interface implemented to provide actions to execute before and after tests.
class Iz
The Iz class is a synonym for Is intended for use in VB, which regards Is as a keyword.
class LevelOfParallelismAttribute
LevelOfParallelismAttribute is used to set the number of worker threads that may be allocated by the framework for running tests.
class List
The List class is a helper class with properties and methods that supply a number of constraints used with lists and collections.
class ListMapper
ListMapper is used to transform a collection used as an actual argument producing another collection to be used in the assertion.
class MaxTimeAttribute
Summary description for MaxTimeAttribute.
class NUnitAttribute
The abstract base class for all custom attributes defined by NUnit.
class OneTimeSetUpAttribute
Attribute used to identify a method that is called once to perform setup before any child tests are run.
class OneTimeTearDownAttribute
Attribute used to identify a method that is called once after all the child tests have run. The method is guaranteed to be called, even if an exception is thrown.
class PairwiseAttribute
Marks a test to use a pairwise join of any argument data provided. Arguments will be combined in such a way that all possible pairs of arguments are used.
class ParallelizableAttribute
ParallelizableAttribute is used to mark tests that may be run in parallel.
class PlatformAttribute
PlatformAttribute is used to mark a test fixture or an individual method as applying to a particular platform only.
class PostTestAttribute
Attribute used to mark a class that contains one-time SetUp and/or TearDown methods that apply to all the tests in a namespace or an assembly.
class PreTestAttribute
Attribute used to mark a class that contains one-time SetUp and/or TearDown methods that apply to all the tests in a namespace or an assembly.
class PropertyAttribute
PropertyAttribute is used to attach information to a test as a name/value pair..
class RandomAttribute
RandomAttribute is used to supply a set of random _values to a single parameter of a parameterized test.
class RangeAttribute
RangeAttribute is used to supply a range of _values to an individual parameter of a parameterized test.
class RepeatAttribute
RepeatAttribute may be applied to test case in order to run it multiple times.
class RequiresMTAAttribute
Marks a test that must run in the MTA, causing it to run in a separate thread if necessary.
class RequiresSTAAttribute
Marks a test that must run in the STA, causing it to run in a separate thread if necessary.
class RequiresThreadAttribute
Marks a test that must run on a separate thread.
class ResultStateException
Abstract base for Exceptions that terminate a test and provide a ResultState.
class RetryAttribute
RepeatAttribute may be applied to test case in order to run it multiple times.
class SequentialAttribute
Marks a test to use a Sequential join of any argument data provided. Arguments will be combined into test cases, taking the next value of each argument until all are used.
class SetCultureAttribute
Summary description for SetCultureAttribute.
class SetUICultureAttribute
Summary description for SetUICultureAttribute.
class SetUpAttribute
Attribute used to mark a class that contains one-time SetUp and/or TearDown methods that apply to all the tests in a namespace or an assembly.
class SetUpFixtureAttribute
SetUpFixtureAttribute is used to identify a SetUpFixture
class StringAssert
Basic Asserts on strings.
class SuccessException
Thrown when an assertion failed.
class TearDownAttribute
Attribute used to identify a method that is called immediately after each test is run. The method is guaranteed to be called, even if an exception is thrown.
class TestActionAttribute
Provide actions to execute before and after tests.
class TestAttribute
Adding this attribute to a method within a
See also
TestFixtureAttribute
class makes the method callable from the NUnit test runner. There is a property called Description which is optional which you can provide a more detailed test description. This class cannot be inherited.
class TestCaseAttribute
TestCaseAttribute is used to mark parameterized test cases and provide them with their arguments.
class TestCaseData
The TestCaseData class represents a set of arguments and other parameter info to be used for a parameterized test case. It is derived from TestCaseParameters and adds a fluent syntax for use in initializing the test case.
class TestCaseSourceAttribute
TestCaseSourceAttribute indicates the source to be used to provide test cases for a test method.
class TestContext
Provide the context information of the current test. This is an adapter for the internal ExecutionContext class, hiding the internals from the user test.
class TestFixtureAttribute
TestFixtureAttribute is used to mark a class that represents a TestFixture.
class TestFixtureData
The TestFixtureData class represents a set of arguments and other parameter info to be used for a parameterized fixture. It is derived from TestFixtureParameters and adds a fluent syntax for use in initializing the fixture.
class TestFixtureSetUpAttribute
Attribute used to identify a method that is called before any tests in a fixture are run.
class TestFixtureSourceAttribute
TestCaseSourceAttribute indicates the source to be used to provide test fixture instances for a test class.
class TestFixtureTearDownAttribute
Attribute used to identify a method that is called after all the tests in a fixture have run. The method is guaranteed to be called, even if an exception is thrown.
class TestOfAttribute
Indicates which class the test or test fixture is testing
class TheoryAttribute
Adding this attribute to a method within a
See also
TestFixtureAttribute
class makes the method callable from the NUnit test runner. There is a property called Description which is optional which you can provide a more detailed test description. This class cannot be inherited.
class Throws
Helper class with properties and methods that supply constraints that operate on exceptions.
class TimeoutAttribute
Used on a method, marks the test with a timeout value in milliseconds. The test will be run in a separate thread and is cancelled if the timeout is exceeded. Used on a class or assembly, sets the default timeout for all contained test methods.
class ValuesAttribute
ValuesAttribute is used to provide literal arguments for an individual parameter of a test.
class ValueSourceAttribute
ValueSourceAttribute indicates the source to be used to provide data for one parameter of a test method.
Enumerations
enum ActionTargets { ActionTargets.Default = 0, ActionTargets.Test = 1, ActionTargets.Suite = 2 }
The different targets a test action attribute can be applied to
enum ParallelScope { ParallelScope.None = 0, ParallelScope.Self = 1, ParallelScope.Children = 2, ParallelScope.Fixtures = 4 }
The ParallelScope enumeration permits specifying the degree to which a test and its descendants may be run in parallel.
enum SpecialValue { SpecialValue.Null }
The SpecialValue enum is used to represent TestCase arguments that cannot be used as arguments to an Attribute.
Functions
delegate void TestDelegate ()
Delegate used by tests that execute code and capture any thrown exception.
Enumeration Type Documentation
enum NUnit.Framework.ActionTargets
The different targets a test action attribute can be applied to
Enumerator
Default
Default target, which is determined by where the action attribute is attached
Test
Target a individual test case
Suite
Target a suite of test cases
enum NUnit.Framework.ParallelScope
The ParallelScope enumeration permits specifying the degree to which a test and its descendants may be run in parallel.
Enumerator
None
No Parallelism is permitted
Self
The test itself may be run in parallel with others at the same level
Children
Descendants of the test may be run in parallel with one another
Fixtures
Descendants of the test down to the level of TestFixtures may be run in parallel
enum NUnit.Framework.SpecialValue
The SpecialValue enum is used to represent TestCase arguments that cannot be used as arguments to an Attribute.
Enumerator
Null
Null represents a null value, which cannot be used as an argument to an attriute under .NET 1.x
Function Documentation
delegate void NUnit.Framework.TestDelegate ()
Delegate used by tests that execute code and capture any thrown exception.
Referenced by NUnit.Framework.Constraints.ThrowsExceptionConstraint.ApplyTo< TActual >(), NUnit.Framework.Assertions.AssertThrowsTests.CorrectExceptionIsReturnedToMethod(), NUnit.Framework.Assertions.AssertThrowsTests.CorrectExceptionThrown(), NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.FailsWhenKeyIsMissing(), NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.FailsWhenNotUsedAgainstADictionary(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.FailsWhenNotUsedAgainstADictionary(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.FailsWhenValueIsMissing(), NUnit.Framework.Constraints.RangeTests.InRangeFails(), and NUnit.Framework.Constraints.RangeTests.NotInRangeFails().