IGLib: IPLab.YCbCrLinearForm Class Reference
IPLab.YCbCrLinearForm Class Reference
Summary description for YCbCrLinearForm.
Public Member Functions
YCbCrLinearForm (AForge.Imaging.ImageStatisticsYCbCr imgStat)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
Bitmap Image [set]
IFilter Filter [get]
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void componentCombo_SelectedIndexChanged (object sender, System.EventArgs e)
void inMinBox_TextChanged (object sender, System.EventArgs e)
void inMaxBox_TextChanged (object sender, System.EventArgs e)
void outMinBox_TextChanged (object sender, System.EventArgs e)
void outMaxBox_TextChanged (object sender, System.EventArgs e)
void inSlider_ValuesChanged (object sender, System.EventArgs e)
void outSlider_ValuesChanged (object sender, System.EventArgs e)
void UpdateFilter ()
Private Attributes
YCbCrLinear filter = new YCbCrLinear()
Range inY = new Range(0, 1)
Range inCb = new Range(-0.5f, 0.5f)
Range inCr = new Range(-0.5f, 0.5f)
Range outY = new Range(0, 1)
Range outCb = new Range(-0.5f, 0.5f)
Range outCr = new Range(-0.5f, 0.5f)
AForge.Imaging.ImageStatisticsYCbCr imgStat
System.Windows.Forms.Button cancelButton
System.Windows.Forms.Button okButton
System.Windows.Forms.GroupBox groupBox4
IPLab.FilterPreview filterPreview
AForge.Controls.ColorSlider outSlider
System.Windows.Forms.PictureBox pictureBox3
System.Windows.Forms.TextBox outMaxBox
System.Windows.Forms.TextBox outMinBox
System.Windows.Forms.Label label3
AForge.Controls.ColorSlider inSlider
System.Windows.Forms.PictureBox pictureBox2
AForge.Controls.Histogram histogram
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox inMinBox
System.Windows.Forms.PictureBox pictureBox1
System.Windows.Forms.Label label1
System.Windows.Forms.TextBox inMaxBox
System.Windows.Forms.ComboBox componentCombo
System.ComponentModel.Container components = null
Required designer variable.
Detailed Description
Summary description for YCbCrLinearForm.
Constructor & Destructor Documentation
IPLab.YCbCrLinearForm.YCbCrLinearForm (AForge.Imaging.ImageStatisticsYCbCr imgStat) inline
References IPLab.YCbCrLinearForm.componentCombo, IPLab.YCbCrLinearForm.filter, IPLab.FilterPreview.Filter, IPLab.YCbCrLinearForm.filterPreview, IPLab.YCbCrLinearForm.imgStat, and IPLab.YCbCrLinearForm.InitializeComponent().
Member Function Documentation
override void IPLab.YCbCrLinearForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References IPLab.YCbCrLinearForm.components.
void IPLab.YCbCrLinearForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IPLab.YCbCrLinearForm.YCbCrLinearForm().
void IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrLinearForm.componentCombo, IPLab.YCbCrLinearForm.histogram, IPLab.YCbCrLinearForm.imgStat, IPLab.YCbCrLinearForm.inCb, IPLab.YCbCrLinearForm.inCr, IPLab.YCbCrLinearForm.inMaxBox, IPLab.YCbCrLinearForm.inMinBox, IPLab.YCbCrLinearForm.inSlider, IPLab.YCbCrLinearForm.inY, IPLab.YCbCrLinearForm.outCb, IPLab.YCbCrLinearForm.outCr, IPLab.YCbCrLinearForm.outMaxBox, IPLab.YCbCrLinearForm.outMinBox, IPLab.YCbCrLinearForm.outSlider, and IPLab.YCbCrLinearForm.outY.
void IPLab.YCbCrLinearForm.inMinBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrLinearForm.componentCombo, IPLab.YCbCrLinearForm.inMinBox, IPLab.YCbCrLinearForm.inSlider, and IPLab.YCbCrLinearForm.UpdateFilter().
void IPLab.YCbCrLinearForm.inMaxBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrLinearForm.componentCombo, IPLab.YCbCrLinearForm.inMaxBox, IPLab.YCbCrLinearForm.inSlider, and IPLab.YCbCrLinearForm.UpdateFilter().
void IPLab.YCbCrLinearForm.outMinBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrLinearForm.componentCombo, IPLab.YCbCrLinearForm.outMinBox, IPLab.YCbCrLinearForm.outSlider, and IPLab.YCbCrLinearForm.UpdateFilter().
void IPLab.YCbCrLinearForm.outMaxBox_TextChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrLinearForm.componentCombo, IPLab.YCbCrLinearForm.outMaxBox, IPLab.YCbCrLinearForm.outSlider, and IPLab.YCbCrLinearForm.UpdateFilter().
void IPLab.YCbCrLinearForm.inSlider_ValuesChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrLinearForm.componentCombo, IPLab.YCbCrLinearForm.inMaxBox, IPLab.YCbCrLinearForm.inMinBox, and IPLab.YCbCrLinearForm.inSlider.
void IPLab.YCbCrLinearForm.outSlider_ValuesChanged (object sender, System.EventArgs e) inline private
References IPLab.YCbCrLinearForm.componentCombo, IPLab.YCbCrLinearForm.outMaxBox, IPLab.YCbCrLinearForm.outMinBox, and IPLab.YCbCrLinearForm.outSlider.
void IPLab.YCbCrLinearForm.UpdateFilter () inline private
References IPLab.YCbCrLinearForm.filterPreview, IPLab.YCbCrLinearForm.inCb, IPLab.YCbCrLinearForm.inCr, IPLab.YCbCrLinearForm.inY, IPLab.YCbCrLinearForm.outCb, IPLab.YCbCrLinearForm.outCr, IPLab.YCbCrLinearForm.outY, and IPLab.FilterPreview.RefreshFilter().
Referenced by IPLab.YCbCrLinearForm.inMaxBox_TextChanged(), IPLab.YCbCrLinearForm.inMinBox_TextChanged(), IPLab.YCbCrLinearForm.outMaxBox_TextChanged(), and IPLab.YCbCrLinearForm.outMinBox_TextChanged().
Member Data Documentation
YCbCrLinear IPLab.YCbCrLinearForm.filter = new YCbCrLinear() private
Referenced by IPLab.YCbCrLinearForm.YCbCrLinearForm().
Range IPLab.YCbCrLinearForm.inY = new Range(0, 1) private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), and IPLab.YCbCrLinearForm.UpdateFilter().
Range IPLab.YCbCrLinearForm.inCb = new Range(-0.5f, 0.5f) private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), and IPLab.YCbCrLinearForm.UpdateFilter().
Range IPLab.YCbCrLinearForm.inCr = new Range(-0.5f, 0.5f) private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), and IPLab.YCbCrLinearForm.UpdateFilter().
Range IPLab.YCbCrLinearForm.outY = new Range(0, 1) private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), and IPLab.YCbCrLinearForm.UpdateFilter().
Range IPLab.YCbCrLinearForm.outCb = new Range(-0.5f, 0.5f) private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), and IPLab.YCbCrLinearForm.UpdateFilter().
Range IPLab.YCbCrLinearForm.outCr = new Range(-0.5f, 0.5f) private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), and IPLab.YCbCrLinearForm.UpdateFilter().
AForge.Imaging.ImageStatisticsYCbCr IPLab.YCbCrLinearForm.imgStat private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), and IPLab.YCbCrLinearForm.YCbCrLinearForm().
System.Windows.Forms.Button IPLab.YCbCrLinearForm.cancelButton private
System.Windows.Forms.Button IPLab.YCbCrLinearForm.okButton private
System.Windows.Forms.GroupBox IPLab.YCbCrLinearForm.groupBox4 private
IPLab.FilterPreview IPLab.YCbCrLinearForm.filterPreview private
Referenced by IPLab.YCbCrLinearForm.UpdateFilter(), and IPLab.YCbCrLinearForm.YCbCrLinearForm().
AForge.Controls.ColorSlider IPLab.YCbCrLinearForm.outSlider private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), IPLab.YCbCrLinearForm.outMaxBox_TextChanged(), IPLab.YCbCrLinearForm.outMinBox_TextChanged(), and IPLab.YCbCrLinearForm.outSlider_ValuesChanged().
System.Windows.Forms.PictureBox IPLab.YCbCrLinearForm.pictureBox3 private
System.Windows.Forms.TextBox IPLab.YCbCrLinearForm.outMaxBox private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), IPLab.YCbCrLinearForm.outMaxBox_TextChanged(), and IPLab.YCbCrLinearForm.outSlider_ValuesChanged().
System.Windows.Forms.TextBox IPLab.YCbCrLinearForm.outMinBox private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), IPLab.YCbCrLinearForm.outMinBox_TextChanged(), and IPLab.YCbCrLinearForm.outSlider_ValuesChanged().
System.Windows.Forms.Label IPLab.YCbCrLinearForm.label3 private
AForge.Controls.ColorSlider IPLab.YCbCrLinearForm.inSlider private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), IPLab.YCbCrLinearForm.inMaxBox_TextChanged(), IPLab.YCbCrLinearForm.inMinBox_TextChanged(), and IPLab.YCbCrLinearForm.inSlider_ValuesChanged().
System.Windows.Forms.PictureBox IPLab.YCbCrLinearForm.pictureBox2 private
AForge.Controls.Histogram IPLab.YCbCrLinearForm.histogram private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged().
System.Windows.Forms.Label IPLab.YCbCrLinearForm.label2 private
System.Windows.Forms.TextBox IPLab.YCbCrLinearForm.inMinBox private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), IPLab.YCbCrLinearForm.inMinBox_TextChanged(), and IPLab.YCbCrLinearForm.inSlider_ValuesChanged().
System.Windows.Forms.PictureBox IPLab.YCbCrLinearForm.pictureBox1 private
System.Windows.Forms.Label IPLab.YCbCrLinearForm.label1 private
System.Windows.Forms.TextBox IPLab.YCbCrLinearForm.inMaxBox private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), IPLab.YCbCrLinearForm.inMaxBox_TextChanged(), and IPLab.YCbCrLinearForm.inSlider_ValuesChanged().
System.Windows.Forms.ComboBox IPLab.YCbCrLinearForm.componentCombo private
Referenced by IPLab.YCbCrLinearForm.componentCombo_SelectedIndexChanged(), IPLab.YCbCrLinearForm.inMaxBox_TextChanged(), IPLab.YCbCrLinearForm.inMinBox_TextChanged(), IPLab.YCbCrLinearForm.inSlider_ValuesChanged(), IPLab.YCbCrLinearForm.outMaxBox_TextChanged(), IPLab.YCbCrLinearForm.outMinBox_TextChanged(), IPLab.YCbCrLinearForm.outSlider_ValuesChanged(), and IPLab.YCbCrLinearForm.YCbCrLinearForm().
System.ComponentModel.Container IPLab.YCbCrLinearForm.components = null private
Required designer variable.
Referenced by IPLab.YCbCrLinearForm.Dispose().
Property Documentation
Bitmap IPLab.YCbCrLinearForm.Image set
Referenced by IPLab.ImageDoc.linearYCbCrFiltersItem_Click().
IFilter IPLab.YCbCrLinearForm.Filter get
Referenced by IPLab.ImageDoc.linearYCbCrFiltersItem_Click().
The documentation for this class was generated from the following file:
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/YCbCrLinearForm.cs