IGLib: NUnit.Common.ExtendedTextWriter Class Reference
NUnit.Common.ExtendedTextWriter Class Reference abstract
ExtendedTextWriter extends the TextWriter abstract class to support displaying text in color. $
Public Member Functions
abstract void Write (ColorStyle style, string value)
Writes the value with the specified style.
abstract void WriteLine (ColorStyle style, string value)
Writes the value with the specified style
abstract void WriteLabel (string label, object option)
Writes the label and the option that goes with it.
abstract void WriteLabel (string label, object option, ColorStyle valueStyle)
Writes the label and the option that goes with it.
abstract void WriteLabelLine (string label, object option)
Writes the label and the option that goes with it followed by a new line.
abstract void WriteLabelLine (string label, object option, ColorStyle valueStyle)
Writes the label and the option that goes with it followed by a new line.
Detailed Description
ExtendedTextWriter extends the TextWriter abstract class to support displaying text in color. $
Member Function Documentation
abstract void NUnit.Common.ExtendedTextWriter.Write (ColorStyle style, string value) pure virtual
Writes the value with the specified style.
Parameters
style The style.
value The value.
Implemented in NUnit.Common.ExtendedTextWrapper, and NUnit.Common.ColorConsoleWriter.
Referenced by NUnitLite.TextUI.DisplayHelp(), and NUnitLite.TextUI.TestFinished().
abstract void NUnit.Common.ExtendedTextWriter.WriteLine (ColorStyle style, string value) pure virtual
Writes the value with the specified style
Parameters
style The style.
value The value.
Implemented in NUnit.Common.ExtendedTextWrapper, and NUnit.Common.ColorConsoleWriter.
Referenced by NUnitLite.TextUI.DisplayRequestedOptions(), NUnitLite.TextUI.DisplayRunSettings(), NUnit.ConsoleRunner.ConsoleRunner.DisplayRuntimeEnvironment(), NUnitLite.TextUI.DisplaySummaryReport(), NUnit.ConsoleRunner.ConsoleRunner.DisplayTestFiles(), NUnitLite.TextUI.DisplayTestFilters(), NUnit.ConsoleRunner.ConsoleRunner.DisplayTestFilters(), NUnit.ConsoleRunner.ConsoleRunner.ExploreTests(), NUnit.ConsoleRunner.ResultReporter.ReportResults(), NUnit.ConsoleRunner.ConsoleRunner.RunTests(), NUnitLite.TextUI.SkipLine(), NUnitLite.TextUI.TestFinished(), NUnitLite.TextUI.WaitForUser(), NUnit.ConsoleRunner.ResultReporter.WriteErrorsAndFailuresReport(), NUnitLite.TextUI.WriteLine(), NUnit.ConsoleRunner.ResultReporter.WriteNotRunReport(), NUnit.ConsoleRunner.ResultReporter.WriteRunSettingsReport(), NUnit.ConsoleRunner.ResultReporter.WriteSingleResult(), and NUnit.ConsoleRunner.ResultReporter.WriteSummaryReport().
abstract void NUnit.Common.ExtendedTextWriter.WriteLabel (string label, object option) pure virtual
Writes the label and the option that goes with it.
Parameters
label The label.
option The option.
Implemented in NUnit.Common.ExtendedTextWrapper, and NUnit.Common.ColorConsoleWriter.
Referenced by NUnitLite.TextUI.WriteLabel(), NUnit.ConsoleRunner.ResultReporter.WriteSummaryCount(), and NUnitLite.TextUI.WriteSummaryCount().
abstract void NUnit.Common.ExtendedTextWriter.WriteLabel (string label, object option, ColorStyle valueStyle) pure virtual
Writes the label and the option that goes with it.
Parameters
label The label.
option The option.
valueStyle The color to display the value with
Implemented in NUnit.Common.ExtendedTextWrapper, and NUnit.Common.ColorConsoleWriter.
abstract void NUnit.Common.ExtendedTextWriter.WriteLabelLine (string label, object option) pure virtual
Writes the label and the option that goes with it followed by a new line.
Parameters
label The label.
option The option.
Implemented in NUnit.Common.ExtendedTextWrapper, and NUnit.Common.ColorConsoleWriter.
Referenced by NUnit.ConsoleRunner.ConsoleRunner.DisplayRuntimeEnvironment(), NUnitLite.TextUI.DisplayTestFilters(), NUnit.ConsoleRunner.ConsoleRunner.DisplayTestFilters(), NUnitLite.TextUI.WriteLabelLine(), NUnit.ConsoleRunner.ResultReporter.WriteRunSettingsReport(), and NUnit.ConsoleRunner.ResultReporter.WriteSummaryReport().
abstract void NUnit.Common.ExtendedTextWriter.WriteLabelLine (string label, object option, ColorStyle valueStyle) pure virtual
Writes the label and the option that goes with it followed by a new line.
Parameters
label The label.
option The option.
valueStyle The color to display the value with
Implemented in NUnit.Common.ExtendedTextWrapper, and NUnit.Common.ColorConsoleWriter.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/ExtendedTextWriter.cs