IGLib: NUnit.TestData.TestContextData.TestStateRecordingFixture Class Reference
NUnit.TestData.TestContextData.TestStateRecordingFixture Class Reference
Public Member Functions
void SetUp ()
void TheTest ()
void TearDown ()
Public Attributes
string stateList
bool testFailure
bool testInconclusive
bool setUpFailure
bool setUpIgnore
Member Function Documentation
void NUnit.TestData.TestContextData.TestStateRecordingFixture.SetUp () inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Assert.Fail(), NUnit.Framework.Assert.Ignore(), NUnit.Framework.TestContext.ResultAdapter.Outcome, and NUnit.Framework.TestContext.Result.
void NUnit.TestData.TestContextData.TestStateRecordingFixture.TheTest () inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Assert.Fail(), NUnit.Framework.Assert.Inconclusive(), NUnit.Framework.TestContext.ResultAdapter.Outcome, and NUnit.Framework.TestContext.Result.
void NUnit.TestData.TestContextData.TestStateRecordingFixture.TearDown () inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.TestContext.ResultAdapter.Outcome, and NUnit.Framework.TestContext.Result.
Member Data Documentation
string NUnit.TestData.TestContextData.TestStateRecordingFixture.stateList
Referenced by NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_FailingTest(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_FailureInSetUp(), NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_IgnoredInSetUp(), and NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_PassingTest().
bool NUnit.TestData.TestContextData.TestStateRecordingFixture.testFailure
Referenced by NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_FailingTest().
bool NUnit.TestData.TestContextData.TestStateRecordingFixture.testInconclusive
bool NUnit.TestData.TestContextData.TestStateRecordingFixture.setUpFailure
Referenced by NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_FailureInSetUp().
bool NUnit.TestData.TestContextData.TestStateRecordingFixture.setUpIgnore
Referenced by NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_IgnoredInSetUp().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/testdata/TestContextData.cs