IGLib: alglib.rotations Class Reference
alglib.rotations Class Reference
Static Public Member Functions
static void applyrotationsfromtheleft (bool isforward, int m1, int m2, int n1, int n2, double[] c, double[] s, ref double[,] a, ref double[] work)
static void applyrotationsfromtheright (bool isforward, int m1, int m2, int n1, int n2, double[] c, double[] s, ref double[,] a, ref double[] work)
static void generaterotation (double f, double g, ref double cs, ref double sn, ref double r)
static void applyrotationsfromtheleft (bool isforward, int m1, int m2, int n1, int n2, double[] c, double[] s, ref double[,] a, ref double[] work)
static void applyrotationsfromtheright (bool isforward, int m1, int m2, int n1, int n2, double[] c, double[] s, ref double[,] a, ref double[] work)
static void generaterotation (double f, double g, ref double cs, ref double sn, ref double r)
Member Function Documentation
static void alglib.rotations.applyrotationsfromtheleft (bool isforward, int m1, int m2, int n1, int n2, double[] c, double[] s, ref double a[,], ref double[] work) inline static
Referenced by alglib.hsschur.internalauxschur().
static void alglib.rotations.applyrotationsfromtheright (bool isforward, int m1, int m2, int n1, int n2, double[] c, double[] s, ref double a[,], ref double[] work) inline static
Referenced by alglib.hsschur.internalauxschur().
static void alglib.rotations.generaterotation (double f, double g, ref double cs, ref double sn, ref double r) inline static
References alglib.math.sqr().
static void alglib.rotations.applyrotationsfromtheleft (bool isforward, int m1, int m2, int n1, int n2, double[] c, double[] s, ref double a[,], ref double[] work) inline static
static void alglib.rotations.applyrotationsfromtheright (bool isforward, int m1, int m2, int n1, int n2, double[] c, double[] s, ref double a[,], ref double[] work) inline static
static void alglib.rotations.generaterotation (double f, double g, ref double cs, ref double sn, ref double r) inline static
References alglib.math.sqr().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/alglibinternal.cs