IGLib: IPLab.BayerFilterForm Class Reference
IPLab.BayerFilterForm Class Reference
Public Member Functions
BayerFilterForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
IFilter Filter [get]
Private Member Functions
void mosaicTypeCombo_SelectedIndexChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
BayerFilterOptimized filter = new BayerFilterOptimized()
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Button cancelButton
System.Windows.Forms.Button okButton
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.ComboBox mosaicTypeCombo
Static Private Attributes
static BayerPattern[] patterns = new BayerPattern[] { BayerPattern.GRBG, BayerPattern.BGGR }
Constructor & Destructor Documentation
IPLab.BayerFilterForm.BayerFilterForm () inline
References IPLab.BayerFilterForm.InitializeComponent(), and IPLab.BayerFilterForm.mosaicTypeCombo.
Member Function Documentation
void IPLab.BayerFilterForm.mosaicTypeCombo_SelectedIndexChanged (object sender, EventArgs e) inline private
References IPLab.BayerFilterForm.mosaicTypeCombo.
Referenced by IPLab.BayerFilterForm.InitializeComponent().
override void IPLab.BayerFilterForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IPLab.BayerFilterForm.components.
void IPLab.BayerFilterForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IPLab.BayerFilterForm.cancelButton, IPLab.BayerFilterForm.groupBox2, IPLab.BayerFilterForm.mosaicTypeCombo, IPLab.BayerFilterForm.mosaicTypeCombo_SelectedIndexChanged(), and IPLab.BayerFilterForm.okButton.
Referenced by IPLab.BayerFilterForm.BayerFilterForm().
Member Data Documentation
BayerFilterOptimized IPLab.BayerFilterForm.filter = new BayerFilterOptimized() private
BayerPattern [] IPLab.BayerFilterForm.patterns = new BayerPattern[] { BayerPattern.GRBG, BayerPattern.BGGR } static private
System.ComponentModel.IContainer IPLab.BayerFilterForm.components = null private
Required designer variable.
Referenced by IPLab.BayerFilterForm.Dispose().
System.Windows.Forms.Button IPLab.BayerFilterForm.cancelButton private
Referenced by IPLab.BayerFilterForm.InitializeComponent().
System.Windows.Forms.Button IPLab.BayerFilterForm.okButton private
Referenced by IPLab.BayerFilterForm.InitializeComponent().
System.Windows.Forms.GroupBox IPLab.BayerFilterForm.groupBox2 private
Referenced by IPLab.BayerFilterForm.InitializeComponent().
System.Windows.Forms.ComboBox IPLab.BayerFilterForm.mosaicTypeCombo private
Referenced by IPLab.BayerFilterForm.BayerFilterForm(), IPLab.BayerFilterForm.InitializeComponent(), and IPLab.BayerFilterForm.mosaicTypeCombo_SelectedIndexChanged().
Property Documentation
IFilter IPLab.BayerFilterForm.Filter get
Referenced by IPLab.ImageDoc.bayerFiltersItem_Click().
The documentation for this class was generated from the following files:
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/BayerFilterForm.cs
igsandbox/imageprocessing/iplab_new_GPL/Sources/Filters Forms/BayerFilterForm.Designer.cs