IGLib: NUnit.Engine.Runners.DirectTestRunner Class Reference
NUnit.Engine.Runners.DirectTestRunner Class Reference
DirectTestRunner is the abstract base for runners that deal directly with a framework driver.
Public Member Functions
DirectTestRunner (IServiceLocator services, TestPackage package)
override void StopRun (bool force)
Cancel the ongoing test run. If no test is running, the call is ignored.
Public Member Functions inherited from NUnit.Engine.Runners.AbstractTestRunner
AbstractTestRunner (IServiceLocator services, TestPackage package)
virtual void UnloadPackage ()
Unload any loaded TestPackage. Overridden in derived classes to take any necessary action.
TestEngineResult Explore (TestFilter filter)
Explores the TestPackage and returns information about the tests found. Loads the package if not done previously.
TestEngineResult Load ()
Loads the TestPackage for exploration or execution, saving the result.
TestEngineResult Reload ()
Reload the currently loaded test package, saving the result.
void Unload ()
Unload any loaded TestPackage.
int CountTestCases (TestFilter filter)
Count the test cases that would be run under the specified filter, loading the TestPackage if it is not already loaded.
TestEngineResult Run (ITestEventListener listener, TestFilter filter)
Run the tests in the TestPackage, loading the package if this has not already been done.
AsyncTestEngineResult RunAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
void StartRun (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses. Loads the TestPackage if not already loaded.
void Dispose ()
Protected Member Functions
override TestEngineResult ExploreTests (TestFilter filter)
Explores a previously loaded TestPackage and returns information about the tests found.
override TestEngineResult LoadPackage ()
Load a TestPackage for exploration or execution
override int CountTests (TestFilter filter)
Count the test cases that would be run under the specified filter.
override TestEngineResult RunTests (ITestEventListener listener, TestFilter filter)
Run the tests in the loaded TestPackage.
Protected Member Functions inherited from NUnit.Engine.Runners.AbstractTestRunner
virtual TestEngineResult ReloadPackage ()
Reload the currently loaded test package. Overridden in derived classes to take any additional action.
virtual AsyncTestEngineResult RunTestsAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage, returning immediately. The tests are run asynchronously and the listener interface is notified as it progresses.
virtual void Dispose (bool disposing)
bool IsProjectPackage (TestPackage package)
Properties
AppDomain TestDomain [get, set]
Properties inherited from NUnit.Engine.Runners.AbstractTestRunner
IServiceLocator Services [get, private set]
Our Service Context
IProjectService ProjectService [get, private set]
ITestRunnerFactory TestRunnerFactory [get, private set]
TestPackage TestPackage [get, set]
The TestPackage for which this is the runner
TestEngineResult LoadResult [get, set]
The result of the last call to LoadPackage
bool IsPackageLoaded [get]
Gets an indicator of whether the package has been loaded.
Private Attributes
readonly List< IFrameworkDriver > _drivers = new List<IFrameworkDriver>()
Additional Inherited Members
Protected Attributes inherited from NUnit.Engine.Runners.AbstractTestRunner
const string TEST_RUN_ELEMENT = "test-run"
bool _disposed = false
Detailed Description
DirectTestRunner is the abstract base for runners that deal directly with a framework driver.
Constructor & Destructor Documentation
NUnit.Engine.Runners.DirectTestRunner.DirectTestRunner (IServiceLocator services, TestPackage package) inline
Member Function Documentation
override TestEngineResult NUnit.Engine.Runners.DirectTestRunner.ExploreTests (TestFilter filter) inline protected virtual
Explores a previously loaded TestPackage and returns information about the tests found.
Parameters
filter The TestFilter to be used to select tests
Returns
A TestEngineResult.
Implements NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.Extensibility.IFrameworkDriver.Explore(), NUnit.Engine.TestPackage.FullName, and NUnit.Engine.TestPackage.Name.
override TestEngineResult NUnit.Engine.Runners.DirectTestRunner.LoadPackage () inline protected virtual
Load a TestPackage for exploration or execution
Returns
A TestEngineResult.
Implements NUnit.Engine.Runners.AbstractTestRunner.
Reimplemented in NUnit.Engine.Runners.TestDomainRunner.
References NUnit.Engine.TestPackage.FullName, NUnit.Engine.Extensibility.IFrameworkDriver.ID, NUnit.Engine.TestPackage.ID, NUnit.Engine.Extensibility.IFrameworkDriver.Load(), NUnit.Engine.TestPackage.Name, and NUnit.Engine.TestPackage.SubPackages.
override int NUnit.Engine.Runners.DirectTestRunner.CountTests (TestFilter filter) inline protected virtual
Count the test cases that would be run under the specified filter.
Parameters
filter A TestFilter
Returns
The count of test cases
Implements NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.Extensibility.IFrameworkDriver.CountTestCases().
override TestEngineResult NUnit.Engine.Runners.DirectTestRunner.RunTests (ITestEventListener listener, TestFilter filter) inline protected virtual
Run the tests in the loaded TestPackage.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Returns
A TestEngineResult giving the result of the test execution
Implements NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.TestPackage.FullName, NUnit.Engine.TestPackage.Name, and NUnit.Engine.Extensibility.IFrameworkDriver.Run().
override void NUnit.Engine.Runners.DirectTestRunner.StopRun (bool force) inline virtual
Cancel the ongoing test run. If no test is running, the call is ignored.
Parameters
force If true, cancel any ongoing test threads, otherwise wait for them to complete.
Implements NUnit.Engine.Runners.AbstractTestRunner.
Member Data Documentation
readonly List<IFrameworkDriver> NUnit.Engine.Runners.DirectTestRunner._drivers = new List<IFrameworkDriver>() private
Property Documentation
AppDomain NUnit.Engine.Runners.DirectTestRunner.TestDomain get set protected
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Runners/DirectTestRunner.cs