IGLib: CShell.Modules.Repl.Controls.CSRepl Class Reference
CShell.Modules.Repl.Controls.CSRepl Class Reference
Interaction logic for CommandLineControl.xaml
Public Member Functions
CSRepl ()
void SuppressWarning (string warningCode)
void ShowWarning (string warningCode)
void Clear ()
void ClearLine ()
void WritePrompt ()
void Write (string text)
void Write (string text, TextType textType)
void WriteLine ()
void WriteLine (string text)
void WriteLine (string text, TextType textType)
Color GetColor (TextType textType)
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
CSRepl ()
void SuppressWarning (string warningCode)
void ShowWarning (string warningCode)
void Clear ()
void ClearLine ()
void WritePrompt ()
void Write (string text)
void Write (string text, TextType textType)
void WriteLine ()
void WriteLine (string text)
void WriteLine (string text, TextType textType)
Color GetColor (TextType textType)
void InitializeComponent ()
InitializeComponent
void InitializeComponent ()
InitializeComponent
Properties
ScriptingEngine ScriptingEngine [get, set]
bool IsEvaluating [get]
string Font [get, set]
new double FontSize [get, set]
Color BackgroundColor [get, set]
Color OutputColor [get, set]
Color WarningColor [get, set]
Color ErrorColor [get, set]
Color ReplColor [get, set]
IEnumerable< string > SuppressedWarnings [get]
bool ShowConsoleOutput [get, set]
TextDocument Doc [get]
int Offset [get]
int PromptOffset [get]
Private Member Functions
IEnumerable< string > FilterWarnings (IEnumerable< string > warnings)
string GetWarningCode (string warning)
void CommandEntered (string command)
void ShowPreviousCommand ()
void ShowNextCommand ()
void ScriptingEngineOnEvaluateStarted (object sender, EvaluateStartedEventArgs evaluateStartedEventArgs)
void ScriptingEngineOnEvaluateCompleted (object sender, EvaluateCompletedEventArgs evaluateCompletedEventArgs)
void ScriptingEngineOnConsoleOutput (object sender, ConsoleEventArgs eventArgs)
string ToPrettyString (object o)
void TextAreaOnPreviewKeyDown (object sender, KeyEventArgs keyEventArgs)
void MoveCaretToEnd ()
bool IsCaretAtCurrentLine ()
bool IsCaretAfterPrompt ()
bool IsCaretAtPrompt ()
bool IsCaretAtWritablePosition ()
bool IsSelectionBeforePrompOffset ()
void SelectCurrentLineOnly ()
void SelectCurrentLine ()
string GetCurrentLineText ()
void
System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void
System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void
System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void
System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
IEnumerable< string > FilterWarnings (IEnumerable< string > warnings)
string GetWarningCode (string warning)
void CommandEntered (string command)
void ShowPreviousCommand ()
void ShowNextCommand ()
void ScriptingEngineOnEvaluateStarted (object sender, EvaluateStartedEventArgs evaluateStartedEventArgs)
void ScriptingEngineOnEvaluateCompleted (object sender, EvaluateCompletedEventArgs evaluateCompletedEventArgs)
void ScriptingEngineOnConsoleOutput (object sender, ConsoleEventArgs eventArgs)
string ToPrettyString (object o)
void TextAreaOnPreviewKeyDown (object sender, KeyEventArgs keyEventArgs)
void MoveCaretToEnd ()
bool IsCaretAtCurrentLine ()
bool IsCaretAfterPrompt ()
bool IsCaretAtPrompt ()
bool IsCaretAtWritablePosition ()
bool IsSelectionBeforePrompOffset ()
void SelectCurrentLineOnly ()
void SelectCurrentLine ()
string GetCurrentLineText ()
void
System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
void
System.Windows.Markup.IComponentConnector. Connect (int connectionId, object target)
Private Attributes
CSReplTextEditor textEditor
ScriptingEngine scriptingEngine
readonly CommandHistory commandHistory
bool executingInternalCommand
string partialCommand = ""
int evaluationsRunning
IVisualLineTransformer[] initialTransformers
CompletionWindow completionWindow
OverloadInsightWindow insightWindow
readonly HashSet< string > suppressedWarnings = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
string promptComplete = " > "
string promptIncomplete = " "
string prompt = " > "
bool _contentLoaded
Detailed Description
Interaction logic for CommandLineControl.xaml
CSRepl
Constructor & Destructor Documentation
CShell.Modules.Repl.Controls.CSRepl.CSRepl () inline
References CShellCore.CodeCompletion.CodeTextEditor.FileName, and CShell.Modules.Repl.Controls.CSReplTextEditor.Repl.
CShell.Modules.Repl.Controls.CSRepl.CSRepl () inline
Member Function Documentation
void CShell.Modules.Repl.Controls.CSRepl.SuppressWarning (string warningCode) inline
void CShell.Modules.Repl.Controls.CSRepl.ShowWarning (string warningCode) inline
IEnumerable<string> CShell.Modules.Repl.Controls.CSRepl.FilterWarnings (IEnumerable< string > warnings) inline private
string CShell.Modules.Repl.Controls.CSRepl.GetWarningCode (string warning) inline private
void CShell.Modules.Repl.Controls.CSRepl.Clear () inline
void CShell.Modules.Repl.Controls.CSRepl.CommandEntered (string command) inline private
References CShell.ScriptingEngine.EvaluateAsync().
void CShell.Modules.Repl.Controls.CSRepl.ShowPreviousCommand () inline private
void CShell.Modules.Repl.Controls.CSRepl.ShowNextCommand () inline private
void CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateStarted (object sender, EvaluateStartedEventArgs evaluateStartedEventArgs) inline private
References CShell.Code.EvaluateStartedEventArgs.SourceFile.
void CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateCompleted (object sender, EvaluateCompletedEventArgs evaluateCompletedEventArgs) inline private
References CShell.Code.ScriptingInteractiveBase.ClearRequested, and CShell.Code.EvaluateCompletedEventArgs.Resuslt.
void CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnConsoleOutput (object sender, ConsoleEventArgs eventArgs) inline private
References CShell.Code.ConsoleEventArgs.Text.
string CShell.Modules.Repl.Controls.CSRepl.ToPrettyString (object o) inline private
void CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown (object sender, KeyEventArgs keyEventArgs) inline private
References CShell.ScriptingEngine.Interrupt().
void CShell.Modules.Repl.Controls.CSRepl.MoveCaretToEnd () inline private
bool CShell.Modules.Repl.Controls.CSRepl.IsCaretAtCurrentLine () inline private
bool CShell.Modules.Repl.Controls.CSRepl.IsCaretAfterPrompt () inline private
bool CShell.Modules.Repl.Controls.CSRepl.IsCaretAtPrompt () inline private
bool CShell.Modules.Repl.Controls.CSRepl.IsCaretAtWritablePosition () inline private
bool CShell.Modules.Repl.Controls.CSRepl.IsSelectionBeforePrompOffset () inline private
void CShell.Modules.Repl.Controls.CSRepl.SelectCurrentLineOnly () inline private
void CShell.Modules.Repl.Controls.CSRepl.SelectCurrentLine () inline private
string CShell.Modules.Repl.Controls.CSRepl.GetCurrentLineText () inline private
void CShell.Modules.Repl.Controls.CSRepl.ClearLine () inline
void CShell.Modules.Repl.Controls.CSRepl.WritePrompt () inline
void CShell.Modules.Repl.Controls.CSRepl.Write (string text) inline
void CShell.Modules.Repl.Controls.CSRepl.Write (string text, TextType textType) inline
void CShell.Modules.Repl.Controls.CSRepl.WriteLine () inline
void CShell.Modules.Repl.Controls.CSRepl.WriteLine (string text) inline
void CShell.Modules.Repl.Controls.CSRepl.WriteLine (string text, TextType textType) inline
Color CShell.Modules.Repl.Controls.CSRepl.GetColor (TextType textType) inline
void CShell.Modules.Repl.Controls.CSRepl.InitializeComponent () inline
InitializeComponent
void System.Windows.Markup.IComponentConnector. CShell.Modules.Repl.Controls.CSRepl.Connect (int connectionId, object target) inline private
void CShell.Modules.Repl.Controls.CSRepl.InitializeComponent () inline
InitializeComponent
void System.Windows.Markup.IComponentConnector. CShell.Modules.Repl.Controls.CSRepl.Connect (int connectionId, object target) inline private
void CShell.Modules.Repl.Controls.CSRepl.InitializeComponent () inline
InitializeComponent
void System.Windows.Markup.IComponentConnector. CShell.Modules.Repl.Controls.CSRepl.Connect (int connectionId, object target) inline private
void CShell.Modules.Repl.Controls.CSRepl.InitializeComponent () inline
InitializeComponent
void System.Windows.Markup.IComponentConnector. CShell.Modules.Repl.Controls.CSRepl.Connect (int connectionId, object target) inline private
void CShell.Modules.Repl.Controls.CSRepl.SuppressWarning (string warningCode) inline
void CShell.Modules.Repl.Controls.CSRepl.ShowWarning (string warningCode) inline
IEnumerable<string> CShell.Modules.Repl.Controls.CSRepl.FilterWarnings (IEnumerable< string > warnings) inline private
string CShell.Modules.Repl.Controls.CSRepl.GetWarningCode (string warning) inline private
void CShell.Modules.Repl.Controls.CSRepl.Clear () inline
void CShell.Modules.Repl.Controls.CSRepl.CommandEntered (string command) inline private
void CShell.Modules.Repl.Controls.CSRepl.ShowPreviousCommand () inline private
void CShell.Modules.Repl.Controls.CSRepl.ShowNextCommand () inline private
void CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateStarted (object sender, EvaluateStartedEventArgs evaluateStartedEventArgs) inline private
References CShell.Code.EvaluateStartedEventArgs.SourceFile.
void CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateCompleted (object sender, EvaluateCompletedEventArgs evaluateCompletedEventArgs) inline private
References CShell.Code.ScriptingInteractiveBase.ClearRequested, and CShell.Code.EvaluateCompletedEventArgs.Resuslt.
void CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnConsoleOutput (object sender, ConsoleEventArgs eventArgs) inline private
References CShell.Code.ConsoleEventArgs.Text.
string CShell.Modules.Repl.Controls.CSRepl.ToPrettyString (object o) inline private
void CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown (object sender, KeyEventArgs keyEventArgs) inline private
References CShell.ScriptingEngine.Interrupt().
void CShell.Modules.Repl.Controls.CSRepl.MoveCaretToEnd () inline private
bool CShell.Modules.Repl.Controls.CSRepl.IsCaretAtCurrentLine () inline private
bool CShell.Modules.Repl.Controls.CSRepl.IsCaretAfterPrompt () inline private
bool CShell.Modules.Repl.Controls.CSRepl.IsCaretAtPrompt () inline private
bool CShell.Modules.Repl.Controls.CSRepl.IsCaretAtWritablePosition () inline private
bool CShell.Modules.Repl.Controls.CSRepl.IsSelectionBeforePrompOffset () inline private
void CShell.Modules.Repl.Controls.CSRepl.SelectCurrentLineOnly () inline private
void CShell.Modules.Repl.Controls.CSRepl.SelectCurrentLine () inline private
string CShell.Modules.Repl.Controls.CSRepl.GetCurrentLineText () inline private
void CShell.Modules.Repl.Controls.CSRepl.ClearLine () inline
void CShell.Modules.Repl.Controls.CSRepl.WritePrompt () inline
void CShell.Modules.Repl.Controls.CSRepl.Write (string text) inline
void CShell.Modules.Repl.Controls.CSRepl.Write (string text, TextType textType) inline
void CShell.Modules.Repl.Controls.CSRepl.WriteLine () inline
void CShell.Modules.Repl.Controls.CSRepl.WriteLine (string text) inline
void CShell.Modules.Repl.Controls.CSRepl.WriteLine (string text, TextType textType) inline
Color CShell.Modules.Repl.Controls.CSRepl.GetColor (TextType textType) inline
void CShell.Modules.Repl.Controls.CSRepl.InitializeComponent () inline
InitializeComponent
void System.Windows.Markup.IComponentConnector. CShell.Modules.Repl.Controls.CSRepl.Connect (int connectionId, object target) inline private
void CShell.Modules.Repl.Controls.CSRepl.InitializeComponent () inline
InitializeComponent
void System.Windows.Markup.IComponentConnector. CShell.Modules.Repl.Controls.CSRepl.Connect (int connectionId, object target) inline private
Member Data Documentation
CSReplTextEditor CShell.Modules.Repl.Controls.CSRepl.textEditor private
ScriptingEngine CShell.Modules.Repl.Controls.CSRepl.scriptingEngine private
readonly CommandHistory CShell.Modules.Repl.Controls.CSRepl.commandHistory private
bool CShell.Modules.Repl.Controls.CSRepl.executingInternalCommand private
string CShell.Modules.Repl.Controls.CSRepl.partialCommand = "" private
int CShell.Modules.Repl.Controls.CSRepl.evaluationsRunning private
IVisualLineTransformer [] CShell.Modules.Repl.Controls.CSRepl.initialTransformers private
CompletionWindow CShell.Modules.Repl.Controls.CSRepl.completionWindow private
OverloadInsightWindow CShell.Modules.Repl.Controls.CSRepl.insightWindow private
readonly HashSet< string > CShell.Modules.Repl.Controls.CSRepl.suppressedWarnings = new HashSet<string>(StringComparer.OrdinalIgnoreCase) private
string CShell.Modules.Repl.Controls.CSRepl.promptComplete = " > " private
string CShell.Modules.Repl.Controls.CSRepl.promptIncomplete = " " private
string CShell.Modules.Repl.Controls.CSRepl.prompt = " > " private
bool CShell.Modules.Repl.Controls.CSRepl._contentLoaded private
Property Documentation
ScriptingEngine CShell.Modules.Repl.Controls.CSRepl.ScriptingEngine get set
bool CShell.Modules.Repl.Controls.CSRepl.IsEvaluating get
string CShell.Modules.Repl.Controls.CSRepl.Font get set
new double CShell.Modules.Repl.Controls.CSRepl.FontSize get set
Color CShell.Modules.Repl.Controls.CSRepl.BackgroundColor get set
Color CShell.Modules.Repl.Controls.CSRepl.OutputColor get set
Color CShell.Modules.Repl.Controls.CSRepl.WarningColor get set
Color CShell.Modules.Repl.Controls.CSRepl.ErrorColor get set
Color CShell.Modules.Repl.Controls.CSRepl.ReplColor get set
IEnumerable< string > CShell.Modules.Repl.Controls.CSRepl.SuppressedWarnings get
bool CShell.Modules.Repl.Controls.CSRepl.ShowConsoleOutput get set
TextDocument CShell.Modules.Repl.Controls.CSRepl.Doc get private
int CShell.Modules.Repl.Controls.CSRepl.Offset get private
int CShell.Modules.Repl.Controls.CSRepl.PromptOffset get private
The documentation for this class was generated from the following files:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Repl/Controls/CSRepl.xaml.cs
shelldev/repl/CShell-0.1.2/Src/CShell/obj/Debug/Modules/Repl/Controls/CSRepl.g.cs
shelldev/repl/CShell-0.1.2/Src/CShell/obj/Debug/Modules/Repl/Controls/CSRepl.g.i.cs