IGLib: alglib.ablas Class Reference
alglib.ablas Class Reference
Static Public Member Functions
static void ablassplitlength (double[,] a, int n, ref int n1, ref int n2)
static void ablascomplexsplitlength (complex[,] a, int n, ref int n1, ref int n2)
static int ablasblocksize (double[,] a)
static int ablascomplexblocksize (complex[,] a)
static int ablasmicroblocksize ()
static void cmatrixtranspose (int m, int n, complex[,] a, int ia, int ja, ref complex[,] b, int ib, int jb)
static void rmatrixtranspose (int m, int n, double[,] a, int ia, int ja, ref double[,] b, int ib, int jb)
static void cmatrixcopy (int m, int n, complex[,] a, int ia, int ja, ref complex[,] b, int ib, int jb)
static void rmatrixcopy (int m, int n, double[,] a, int ia, int ja, ref double[,] b, int ib, int jb)
static void cmatrixrank1 (int m, int n, ref complex[,] a, int ia, int ja, ref complex[] u, int iu, ref complex[] v, int iv)
static void rmatrixrank1 (int m, int n, ref double[,] a, int ia, int ja, ref double[] u, int iu, ref double[] v, int iv)
static void cmatrixmv (int m, int n, complex[,] a, int ia, int ja, int opa, complex[] x, int ix, ref complex[] y, int iy)
static void rmatrixmv (int m, int n, double[,] a, int ia, int ja, int opa, double[] x, int ix, ref double[] y, int iy)
static void cmatrixrighttrsm (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref complex[,] x, int i2, int j2)
static void cmatrixlefttrsm (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref complex[,] x, int i2, int j2)
static void rmatrixrighttrsm (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref double[,] x, int i2, int j2)
static void rmatrixlefttrsm (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref double[,] x, int i2, int j2)
static void cmatrixsyrk (int n, int k, double alpha, complex[,] a, int ia, int ja, int optypea, double beta, ref complex[,] c, int ic, int jc, bool isupper)
static void rmatrixsyrk (int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double beta, ref double[,] c, int ic, int jc, bool isupper)
static void cmatrixgemm (int m, int n, int k, complex alpha, complex[,] a, int ia, int ja, int optypea, complex[,] b, int ib, int jb, int optypeb, complex beta, ref complex[,] c, int ic, int jc)
static void rmatrixgemm (int m, int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double[,] b, int ib, int jb, int optypeb, double beta, ref double[,] c, int ic, int jc)
static void ablassplitlength (double[,] a, int n, ref int n1, ref int n2)
static void ablascomplexsplitlength (complex[,] a, int n, ref int n1, ref int n2)
static int ablasblocksize (double[,] a)
static int ablascomplexblocksize (complex[,] a)
static int ablasmicroblocksize ()
static void cmatrixtranspose (int m, int n, complex[,] a, int ia, int ja, ref complex[,] b, int ib, int jb)
static void rmatrixtranspose (int m, int n, double[,] a, int ia, int ja, ref double[,] b, int ib, int jb)
static void rmatrixenforcesymmetricity (double[,] a, int n, bool isupper)
static void cmatrixcopy (int m, int n, complex[,] a, int ia, int ja, ref complex[,] b, int ib, int jb)
static void rmatrixcopy (int m, int n, double[,] a, int ia, int ja, ref double[,] b, int ib, int jb)
static void cmatrixrank1 (int m, int n, ref complex[,] a, int ia, int ja, ref complex[] u, int iu, ref complex[] v, int iv)
static void rmatrixrank1 (int m, int n, ref double[,] a, int ia, int ja, ref double[] u, int iu, ref double[] v, int iv)
static void cmatrixmv (int m, int n, complex[,] a, int ia, int ja, int opa, complex[] x, int ix, ref complex[] y, int iy)
static void rmatrixmv (int m, int n, double[,] a, int ia, int ja, int opa, double[] x, int ix, ref double[] y, int iy)
static void cmatrixrighttrsm (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, complex[,] x, int i2, int j2)
static void _pexec_cmatrixrighttrsm (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, complex[,] x, int i2, int j2)
static void cmatrixlefttrsm (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, complex[,] x, int i2, int j2)
static void _pexec_cmatrixlefttrsm (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, complex[,] x, int i2, int j2)
static void rmatrixrighttrsm (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, double[,] x, int i2, int j2)
static void _pexec_rmatrixrighttrsm (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, double[,] x, int i2, int j2)
static void rmatrixlefttrsm (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, double[,] x, int i2, int j2)
static void _pexec_rmatrixlefttrsm (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, double[,] x, int i2, int j2)
static void cmatrixsyrk (int n, int k, double alpha, complex[,] a, int ia, int ja, int optypea, double beta, complex[,] c, int ic, int jc, bool isupper)
static void _pexec_cmatrixsyrk (int n, int k, double alpha, complex[,] a, int ia, int ja, int optypea, double beta, complex[,] c, int ic, int jc, bool isupper)
static void rmatrixsyrk (int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double beta, double[,] c, int ic, int jc, bool isupper)
static void _pexec_rmatrixsyrk (int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double beta, double[,] c, int ic, int jc, bool isupper)
static void cmatrixgemm (int m, int n, int k, complex alpha, complex[,] a, int ia, int ja, int optypea, complex[,] b, int ib, int jb, int optypeb, complex beta, complex[,] c, int ic, int jc)
static void _pexec_cmatrixgemm (int m, int n, int k, complex alpha, complex[,] a, int ia, int ja, int optypea, complex[,] b, int ib, int jb, int optypeb, complex beta, complex[,] c, int ic, int jc)
static void rmatrixgemm (int m, int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double[,] b, int ib, int jb, int optypeb, double beta, double[,] c, int ic, int jc)
static void _pexec_rmatrixgemm (int m, int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double[,] b, int ib, int jb, int optypeb, double beta, double[,] c, int ic, int jc)
Public Attributes
const int rgemmparallelsize = 64
const int cgemmparallelsize = 64
Static Private Member Functions
static void ablasinternalsplitlength (int n, int nb, ref int n1, ref int n2)
static void cmatrixrighttrsm2 (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref complex[,] x, int i2, int j2)
static void cmatrixlefttrsm2 (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref complex[,] x, int i2, int j2)
static void rmatrixrighttrsm2 (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref double[,] x, int i2, int j2)
static void rmatrixlefttrsm2 (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, ref double[,] x, int i2, int j2)
static void cmatrixsyrk2 (int n, int k, double alpha, complex[,] a, int ia, int ja, int optypea, double beta, ref complex[,] c, int ic, int jc, bool isupper)
static void rmatrixsyrk2 (int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double beta, ref double[,] c, int ic, int jc, bool isupper)
static void cmatrixgemmk (int m, int n, int k, complex alpha, complex[,] a, int ia, int ja, int optypea, complex[,] b, int ib, int jb, int optypeb, complex beta, ref complex[,] c, int ic, int jc)
static void rmatrixgemmk (int m, int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double[,] b, int ib, int jb, int optypeb, double beta, ref double[,] c, int ic, int jc)
static void ablasinternalsplitlength (int n, int nb, ref int n1, ref int n2)
static void cmatrixrighttrsm2 (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, complex[,] x, int i2, int j2)
static void cmatrixlefttrsm2 (int m, int n, complex[,] a, int i1, int j1, bool isupper, bool isunit, int optype, complex[,] x, int i2, int j2)
static void rmatrixrighttrsm2 (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, double[,] x, int i2, int j2)
static void rmatrixlefttrsm2 (int m, int n, double[,] a, int i1, int j1, bool isupper, bool isunit, int optype, double[,] x, int i2, int j2)
static void cmatrixsyrk2 (int n, int k, double alpha, complex[,] a, int ia, int ja, int optypea, double beta, complex[,] c, int ic, int jc, bool isupper)
static void rmatrixsyrk2 (int n, int k, double alpha, double[,] a, int ia, int ja, int optypea, double beta, double[,] c, int ic, int jc, bool isupper)
Member Function Documentation
static void alglib.ablas.ablassplitlength (double a[,], int n, ref int n1, ref int n2) inline static
References alglib.ablas.ablasblocksize(), alglib.ablas.ablasinternalsplitlength(), and alglib.ablas.ablasmicroblocksize().
Referenced by alglib.ablas.rmatrixgemm(), alglib.ablas.rmatrixlefttrsm(), alglib.ablas.rmatrixrighttrsm(), alglib.ablas.rmatrixsyrk(), and alglib.ablas.rmatrixtranspose().
static void alglib.ablas.ablascomplexsplitlength (complex a[,], int n, ref int n1, ref int n2) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ablas.ablasinternalsplitlength(), and alglib.ablas.ablasmicroblocksize().
Referenced by alglib.ablas.cmatrixgemm(), alglib.ablas.cmatrixlefttrsm(), alglib.ablas.cmatrixrighttrsm(), alglib.ablas.cmatrixsyrk(), and alglib.ablas.cmatrixtranspose().
static int alglib.ablas.ablasblocksize (double a[,]) inline static
Referenced by alglib.ablas.ablassplitlength(), alglib.ablas.rmatrixgemm(), alglib.ablas.rmatrixlefttrsm(), alglib.ortfac.rmatrixlq(), alglib.ortfac.rmatrixqr(), alglib.ablas.rmatrixrighttrsm(), alglib.ablas.rmatrixsyrk(), alglib.ablas.rmatrixtranspose(), alglib.testablasunit.testablas(), alglib.testevdunit.testevd(), alglib.testmatinvunit.testmatinv(), alglib.testortfacunit.testortfac(), and alglib.testtrfacunit.testtrfac().
static int alglib.ablas.ablascomplexblocksize (complex a[,]) inline static
Referenced by alglib.ablas.ablascomplexsplitlength(), alglib.ablas.cmatrixgemm(), alglib.ablas.cmatrixlefttrsm(), alglib.ortfac.cmatrixlq(), alglib.ortfac.cmatrixqr(), alglib.ablas.cmatrixrighttrsm(), alglib.ablas.cmatrixsyrk(), and alglib.ablas.cmatrixtranspose().
static int alglib.ablas.ablasmicroblocksize () inline static
Referenced by alglib.ablas.ablascomplexsplitlength(), and alglib.ablas.ablassplitlength().
static void alglib.ablas.cmatrixtranspose (int m, int n, complex a[,], int ia, int ja, ref complex b[,], int ib, int jb) inline static
References alglib.ablas.ablascomplexblocksize(), and alglib.ablas.ablascomplexsplitlength().
Referenced by alglib.cmatrixtranspose(), alglib.ablas.cmatrixtranspose(), and alglib.testablasunit.testtrans().
static void alglib.ablas.rmatrixtranspose (int m, int n, double a[,], int ia, int ja, ref double b[,], int ib, int jb) inline static
References alglib.ablas.ablasblocksize(), and alglib.ablas.ablassplitlength().
Referenced by alglib.testminqpunit.icqptest(), alglib.rmatrixtranspose(), alglib.ablas.rmatrixtranspose(), alglib.basestat.spearmancorrm(), alglib.basestat.spearmancorrm2(), and alglib.testablasunit.testtrans().
static void alglib.ablas.cmatrixcopy (int m, int n, complex a[,], int ia, int ja, ref complex b[,], int ib, int jb) inline static
Referenced by alglib.cmatrixcopy(), alglib.ortfac.cmatrixlq(), alglib.ortfac.cmatrixqr(), and alglib.testablasunit.testcopy().
static void alglib.ablas.rmatrixcopy (int m, int n, double a[,], int ia, int ja, ref double b[,], int ib, int jb) inline static
Referenced by alglib.clustering.clusterizergetdistances(), alglib.cqmodels.cqmrebuild(), alglib.testminqpunit.ecqptest(), alglib.minbleic.rebuildcexe(), alglib.rmatrixcopy(), alglib.ortfac.rmatrixlq(), alglib.ortfac.rmatrixqr(), and alglib.testablasunit.testcopy().
static void alglib.ablas.cmatrixrank1 (int m, int n, ref complex a[,], int ia, int ja, ref complex[] u, int iu, ref complex[] v, int iv) inline static
References alglib.ablasf.cmatrixrank1f().
Referenced by alglib.cmatrixrank1(), and alglib.testablasunit.testrank1().
static void alglib.ablas.rmatrixrank1 (int m, int n, ref double a[,], int ia, int ja, ref double[] u, int iu, ref double[] v, int iv) inline static
References alglib.ablasf.rmatrixrank1f().
Referenced by alglib.rmatrixrank1(), and alglib.testablasunit.testrank1().
static void alglib.ablas.cmatrixmv (int m, int n, complex a[,], int ia, int ja, int opa, complex[] x, int ix, ref complex[] y, int iy) inline static
References alglib.ablasf.cmatrixmvf(), and alglib.math.conj().
Referenced by alglib.cmatrixmv(), and alglib.testablasunit.testmv().
static void alglib.ablas.rmatrixmv (int m, int n, double a[,], int ia, int ja, int opa, double[] x, int ix, ref double[] y, int iy) inline static
References alglib.ablasf.rmatrixmvf().
Referenced by alglib.testminqpunit.consoletest(), alglib.cqmodels.cqmrebuild(), alglib.testminqpunit.functest2(), alglib.nleq.nleqiteration(), alglib.rmatrixmv(), alglib.testfblsunit.testfbls(), and alglib.testablasunit.testmv().
static void alglib.ablas.cmatrixrighttrsm (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref complex x[,], int i2, int j2) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ablas.ablascomplexsplitlength(), alglib.ablas.cmatrixgemm(), and alglib.ablas.cmatrixrighttrsm2().
Referenced by alglib.ablas._pexec_cmatrixrighttrsm(), alglib.cmatrixrighttrsm(), alglib.ablas.cmatrixrighttrsm(), and alglib.testablasunit.testtrsm().
static void alglib.ablas.cmatrixlefttrsm (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref complex x[,], int i2, int j2) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ablas.ablascomplexsplitlength(), alglib.ablas.cmatrixgemm(), and alglib.ablas.cmatrixlefttrsm2().
Referenced by alglib.ablas._pexec_cmatrixlefttrsm(), alglib.cmatrixlefttrsm(), alglib.ablas.cmatrixlefttrsm(), and alglib.testablasunit.testtrsm().
static void alglib.ablas.rmatrixrighttrsm (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref double x[,], int i2, int j2) inline static
References alglib.ablas.ablasblocksize(), alglib.ablas.ablassplitlength(), alglib.ablas.rmatrixgemm(), and alglib.ablas.rmatrixrighttrsm2().
Referenced by alglib.ablas._pexec_rmatrixrighttrsm(), alglib.cqmodels.cqmrebuild(), alglib.rmatrixrighttrsm(), alglib.ablas.rmatrixrighttrsm(), and alglib.testablasunit.testtrsm().
static void alglib.ablas.rmatrixlefttrsm (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref double x[,], int i2, int j2) inline static
References alglib.ablas.ablasblocksize(), alglib.ablas.ablassplitlength(), alglib.ablas.rmatrixgemm(), and alglib.ablas.rmatrixlefttrsm2().
Referenced by alglib.ablas._pexec_rmatrixlefttrsm(), alglib.rmatrixlefttrsm(), alglib.ablas.rmatrixlefttrsm(), and alglib.testablasunit.testtrsm().
static void alglib.ablas.cmatrixsyrk (int n, int k, double alpha, complex a[,], int ia, int ja, int optypea, double beta, ref complex c[,], int ic, int jc, bool isupper) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ablas.ablascomplexsplitlength(), alglib.ablas.cmatrixgemm(), and alglib.ablas.cmatrixsyrk2().
Referenced by alglib.ablas._pexec_cmatrixsyrk(), alglib.cmatrixsyrk(), alglib.ablas.cmatrixsyrk(), and alglib.testablasunit.testsyrk().
static void alglib.ablas.rmatrixsyrk (int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double beta, ref double c[,], int ic, int jc, bool isupper) inline static
References alglib.ablas.ablasblocksize(), alglib.ablas.ablassplitlength(), alglib.ablas.rmatrixgemm(), and alglib.ablas.rmatrixsyrk2().
Referenced by alglib.ablas._pexec_rmatrixsyrk(), alglib.clustering.clusterizergetdistances(), alglib.basestat.covm(), alglib.cqmodels.cqmrebuild(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.icqptest(), alglib.rmatrixsyrk(), alglib.ablas.rmatrixsyrk(), alglib.basestat.spearmancorrm(), and alglib.testablasunit.testsyrk().
static void alglib.ablas.cmatrixgemm (int m, int n, int k, complex alpha, complex a[,], int ia, int ja, int optypea, complex b[,], int ib, int jb, int optypeb, complex beta, ref complex c[,], int ic, int jc) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ablas.ablascomplexsplitlength(), and alglib.ablas.cmatrixgemmk().
Referenced by alglib.ablas._pexec_cmatrixgemm(), alglib.cmatrixgemm(), alglib.ablas.cmatrixgemm(), alglib.ablas.cmatrixlefttrsm(), alglib.ortfac.cmatrixlq(), alglib.ortfac.cmatrixqr(), alglib.ablas.cmatrixrighttrsm(), alglib.ablas.cmatrixsyrk(), and alglib.testablasunit.testgemm().
static void alglib.ablas.rmatrixgemm (int m, int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double b[,], int ib, int jb, int optypeb, double beta, ref double c[,], int ic, int jc) inline static
References alglib.ablas.ablasblocksize(), alglib.ablas.ablassplitlength(), and alglib.ablas.rmatrixgemmk().
Referenced by alglib.ablas._pexec_rmatrixgemm(), alglib.basestat.covm2(), alglib.basestat.pearsoncorrm2(), alglib.rmatrixgemm(), alglib.ablas.rmatrixgemm(), alglib.ablas.rmatrixlefttrsm(), alglib.ortfac.rmatrixlq(), alglib.ortfac.rmatrixqr(), alglib.ablas.rmatrixrighttrsm(), alglib.ablas.rmatrixsyrk(), alglib.basestat.spearmancorrm2(), and alglib.testablasunit.testgemm().
static void alglib.ablas.ablasinternalsplitlength (int n, int nb, ref int n1, ref int n2) inline static private
Referenced by alglib.ablas.ablascomplexsplitlength(), and alglib.ablas.ablassplitlength().
static void alglib.ablas.cmatrixrighttrsm2 (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref complex x[,], int i2, int j2) inline static private
References alglib.ablasf.cmatrixrighttrsmf(), and alglib.math.conj().
Referenced by alglib.ablas.cmatrixrighttrsm().
static void alglib.ablas.cmatrixlefttrsm2 (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref complex x[,], int i2, int j2) inline static private
References alglib.ablasf.cmatrixlefttrsmf(), and alglib.math.conj().
Referenced by alglib.ablas.cmatrixlefttrsm().
static void alglib.ablas.rmatrixrighttrsm2 (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref double x[,], int i2, int j2) inline static private
References alglib.ablasf.rmatrixrighttrsmf().
Referenced by alglib.ablas.rmatrixrighttrsm().
static void alglib.ablas.rmatrixlefttrsm2 (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, ref double x[,], int i2, int j2) inline static private
References alglib.ablasf.rmatrixlefttrsmf().
Referenced by alglib.ablas.rmatrixlefttrsm().
static void alglib.ablas.cmatrixsyrk2 (int n, int k, double alpha, complex a[,], int ia, int ja, int optypea, double beta, ref complex c[,], int ic, int jc, bool isupper) inline static private
References alglib.ablasf.cmatrixsyrkf(), and alglib.math.conj().
Referenced by alglib.ablas.cmatrixsyrk().
static void alglib.ablas.rmatrixsyrk2 (int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double beta, ref double c[,], int ic, int jc, bool isupper) inline static private
References alglib.beta(), and alglib.ablasf.rmatrixsyrkf().
Referenced by alglib.ablas.rmatrixsyrk().
static void alglib.ablas.cmatrixgemmk (int m, int n, int k, complex alpha, complex a[,], int ia, int ja, int optypea, complex b[,], int ib, int jb, int optypeb, complex beta, ref complex c[,], int ic, int jc) inline static private
References alglib.ablasf.cmatrixgemmf(), and alglib.math.conj().
Referenced by alglib.ablas.cmatrixgemm().
static void alglib.ablas.rmatrixgemmk (int m, int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double b[,], int ib, int jb, int optypeb, double beta, ref double c[,], int ic, int jc) inline static private
References alglib.beta(), and alglib.ablasf.rmatrixgemmf().
Referenced by alglib.ablas.rmatrixgemm().
static void alglib.ablas.ablassplitlength (double a[,], int n, ref int n1, ref int n2) inline static
References alglib.ablas.ablasblocksize(), alglib.ablas.ablasinternalsplitlength(), and alglib.ablas.ablasmicroblocksize().
static void alglib.ablas.ablascomplexsplitlength (complex a[,], int n, ref int n1, ref int n2) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ablas.ablasinternalsplitlength(), and alglib.ablas.ablasmicroblocksize().
static int alglib.ablas.ablasblocksize (double a[,]) inline static
static int alglib.ablas.ablascomplexblocksize (complex a[,]) inline static
static int alglib.ablas.ablasmicroblocksize () inline static
static void alglib.ablas.cmatrixtranspose (int m, int n, complex a[,], int ia, int ja, ref complex b[,], int ib, int jb) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ablas.ablascomplexsplitlength(), and alglib.ablas.cmatrixtranspose().
static void alglib.ablas.rmatrixtranspose (int m, int n, double a[,], int ia, int ja, ref double b[,], int ib, int jb) inline static
References alglib.ablas.ablasblocksize(), alglib.ablas.ablassplitlength(), and alglib.ablas.rmatrixtranspose().
static void alglib.ablas.rmatrixenforcesymmetricity (double a[,], int n, bool isupper) inline static
Referenced by alglib.clustering.clusterizergetdistances(), alglib.basestat.covm(), alglib.rmatrixenforcesymmetricity(), and alglib.basestat.spearmancorrm().
static void alglib.ablas.cmatrixcopy (int m, int n, complex a[,], int ia, int ja, ref complex b[,], int ib, int jb) inline static
static void alglib.ablas.rmatrixcopy (int m, int n, double a[,], int ia, int ja, ref double b[,], int ib, int jb) inline static
static void alglib.ablas.cmatrixrank1 (int m, int n, ref complex a[,], int ia, int ja, ref complex[] u, int iu, ref complex[] v, int iv) inline static
References alglib.ablasf.cmatrixrank1f().
static void alglib.ablas.rmatrixrank1 (int m, int n, ref double a[,], int ia, int ja, ref double[] u, int iu, ref double[] v, int iv) inline static
References alglib.ablasf.rmatrixrank1f().
static void alglib.ablas.cmatrixmv (int m, int n, complex a[,], int ia, int ja, int opa, complex[] x, int ix, ref complex[] y, int iy) inline static
References alglib.ablasf.cmatrixmvf(), and alglib.math.conj().
static void alglib.ablas.rmatrixmv (int m, int n, double a[,], int ia, int ja, int opa, double[] x, int ix, ref double[] y, int iy) inline static
References alglib.ablasf.rmatrixmvf().
static void alglib.ablas.cmatrixrighttrsm (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, complex x[,], int i2, int j2) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ablas.ablascomplexsplitlength(), alglib.ablas.cmatrixgemm(), alglib.ablas.cmatrixrighttrsm(), and alglib.ablas.cmatrixrighttrsm2().
static void alglib.ablas._pexec_cmatrixrighttrsm (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, complex x[,], int i2, int j2) inline static
References alglib.ablas.cmatrixrighttrsm().
Referenced by alglib.smp_cmatrixrighttrsm().
static void alglib.ablas.cmatrixlefttrsm (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, complex x[,], int i2, int j2) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ablas.ablascomplexsplitlength(), alglib.ablas.cmatrixgemm(), alglib.ablas.cmatrixlefttrsm(), and alglib.ablas.cmatrixlefttrsm2().
static void alglib.ablas._pexec_cmatrixlefttrsm (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, complex x[,], int i2, int j2) inline static
References alglib.ablas.cmatrixlefttrsm().
Referenced by alglib.smp_cmatrixlefttrsm().
static void alglib.ablas.rmatrixrighttrsm (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, double x[,], int i2, int j2) inline static
References alglib.ablas.ablasblocksize(), alglib.ablas.ablassplitlength(), alglib.ablas.rmatrixgemm(), alglib.ablas.rmatrixrighttrsm(), and alglib.ablas.rmatrixrighttrsm2().
static void alglib.ablas._pexec_rmatrixrighttrsm (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, double x[,], int i2, int j2) inline static
References alglib.ablas.rmatrixrighttrsm().
Referenced by alglib.smp_rmatrixrighttrsm().
static void alglib.ablas.rmatrixlefttrsm (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, double x[,], int i2, int j2) inline static
References alglib.ablas.ablasblocksize(), alglib.ablas.ablassplitlength(), alglib.ablas.rmatrixgemm(), alglib.ablas.rmatrixlefttrsm(), and alglib.ablas.rmatrixlefttrsm2().
static void alglib.ablas._pexec_rmatrixlefttrsm (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, double x[,], int i2, int j2) inline static
References alglib.ablas.rmatrixlefttrsm().
Referenced by alglib.smp_rmatrixlefttrsm().
static void alglib.ablas.cmatrixsyrk (int n, int k, double alpha, complex a[,], int ia, int ja, int optypea, double beta, complex c[,], int ic, int jc, bool isupper) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ablas.ablascomplexsplitlength(), alglib.ablas.cmatrixgemm(), alglib.ablas.cmatrixsyrk(), and alglib.ablas.cmatrixsyrk2().
static void alglib.ablas._pexec_cmatrixsyrk (int n, int k, double alpha, complex a[,], int ia, int ja, int optypea, double beta, complex c[,], int ic, int jc, bool isupper) inline static
References alglib.ablas.cmatrixsyrk().
Referenced by alglib.smp_cmatrixsyrk().
static void alglib.ablas.rmatrixsyrk (int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double beta, double c[,], int ic, int jc, bool isupper) inline static
References alglib.ablas.ablasblocksize(), alglib.ablas.ablassplitlength(), alglib.ablas.rmatrixgemm(), alglib.ablas.rmatrixsyrk(), alglib.ablas.rmatrixsyrk2(), and alglib.ablasmkl.rmatrixsyrkmkl().
static void alglib.ablas._pexec_rmatrixsyrk (int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double beta, double c[,], int ic, int jc, bool isupper) inline static
References alglib.ablas.rmatrixsyrk().
Referenced by alglib.smp_rmatrixsyrk().
static void alglib.ablas.cmatrixgemm (int m, int n, int k, complex alpha, complex a[,], int ia, int ja, int optypea, complex b[,], int ib, int jb, int optypeb, complex beta, complex c[,], int ic, int jc) inline static
References alglib.ablas.ablascomplexblocksize(), alglib.ablas.ablascomplexsplitlength(), alglib.ablas.cmatrixgemm(), and alglib.ablasf.cmatrixgemmk().
static void alglib.ablas._pexec_cmatrixgemm (int m, int n, int k, complex alpha, complex a[,], int ia, int ja, int optypea, complex b[,], int ib, int jb, int optypeb, complex beta, complex c[,], int ic, int jc) inline static
References alglib.ablas.cmatrixgemm().
Referenced by alglib.smp_cmatrixgemm().
static void alglib.ablas.rmatrixgemm (int m, int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double b[,], int ib, int jb, int optypeb, double beta, double c[,], int ic, int jc) inline static
References alglib.ablas.ablasblocksize(), alglib.ablas.ablassplitlength(), alglib.ap.assert(), alglib.ablas.rmatrixgemm(), alglib.ablasf.rmatrixgemmk(), and alglib.ablasmkl.rmatrixgemmmkl().
static void alglib.ablas._pexec_rmatrixgemm (int m, int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double b[,], int ib, int jb, int optypeb, double beta, double c[,], int ic, int jc) inline static
References alglib.ablas.rmatrixgemm().
Referenced by alglib.smp_rmatrixgemm().
static void alglib.ablas.ablasinternalsplitlength (int n, int nb, ref int n1, ref int n2) inline static private
static void alglib.ablas.cmatrixrighttrsm2 (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, complex x[,], int i2, int j2) inline static private
References alglib.ablasf.cmatrixrighttrsmf(), and alglib.math.conj().
static void alglib.ablas.cmatrixlefttrsm2 (int m, int n, complex a[,], int i1, int j1, bool isupper, bool isunit, int optype, complex x[,], int i2, int j2) inline static private
References alglib.ablasf.cmatrixlefttrsmf(), and alglib.math.conj().
static void alglib.ablas.rmatrixrighttrsm2 (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, double x[,], int i2, int j2) inline static private
References alglib.ablasf.rmatrixrighttrsmf().
static void alglib.ablas.rmatrixlefttrsm2 (int m, int n, double a[,], int i1, int j1, bool isupper, bool isunit, int optype, double x[,], int i2, int j2) inline static private
References alglib.ablasf.rmatrixlefttrsmf().
static void alglib.ablas.cmatrixsyrk2 (int n, int k, double alpha, complex a[,], int ia, int ja, int optypea, double beta, complex c[,], int ic, int jc, bool isupper) inline static private
References alglib.ablasf.cmatrixsyrkf(), and alglib.math.conj().
static void alglib.ablas.rmatrixsyrk2 (int n, int k, double alpha, double a[,], int ia, int ja, int optypea, double beta, double c[,], int ic, int jc, bool isupper) inline static private
References alglib.beta(), and alglib.ablasf.rmatrixsyrkf().
Member Data Documentation
const int alglib.ablas.rgemmparallelsize = 64
const int alglib.ablas.cgemmparallelsize = 64
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/linalg.cs