IGLib: IG.Num.complex Struct Reference
IG.Num.complex Struct Reference
Complex number.
Public Member Functions
complex (double real)
Initializes a complex number with specified real part and imaginary part 0.
complex (double real, double imaginary)
Initializes a complex number with specified real and imaginary part.
complex (complex a)
Initializes a complex number with another complex number.
override int GetHashCode ()
Overrides the GetHashCode() appropriately.
override bool Equals (Object obj)
Overrides the Equals() appropriately.
override string ToString ()
Returns a string representation of the complec number in the form "(2.3+4.5*i)".
double Absolute ()
Returns an absolute value of the complex number.
complex Conjugate ()
Complex conjugate.
Static Public Member Functions
static bool operator== (complex a, complex b)
static bool operator!= (complex a, complex b)
static complex operator+ (complex a, complex b)
Binary operator + for summation of two complex numbers.
static complex operator- (complex a, complex b)
Binary operator - subtraction of two complex numbers.
static complex operator- (complex a)
Unary operator - changing sign of a complex number.
static complex operator* (double a, complex c)
Left multiplication of a complex number by a real number.
static complex operator* (complex c, double a)
Right multiplication of a complex number by a real number.
static complex operator* (complex a, complex b)
Complex multiplication.
static complex operator/ (complex a, complex b)
Complex division.
static implicit operator complex (double number)
Implicit conversion between from double to Complex.
static complex Polar (double r, double fi)
static double Absolute (complex a)
Returns an absolute value of the specified complex number.
static complex Conjugate (complex a)
Returns a complex conjugate of the argument.
static int Compare (complex c1, complex c2)
Compares two complex numbers and returns -1 if the first number is "smaller" than the second one, 0 if they are equal and 1 if the first number is "greater" than the second one. Comparison is artificial and does not have mathematical meaning. 0 is returned if and only if numbers are equal.
static void Example ()
Example of using the complex class.
Public Attributes
double _imaginary
Properties
double Re [get, private set]
Gets (public access) or sets (protected access) the real part of the complex number.
double Im [get, private set]
Gets (public access) or sets (protected access) the imaginary part of the complex number.
double SquaredAbs [get]
Returns squared absolute value of the current complex number.
double Abs [get]
Gets modulus (absolute value) of the complex number.
double Fi [get]
Argument of the complex number.
static complex Zero [get]
Complex constant 0 + 0*i (summation unit)
static complex One [get]
Complex constant 1 + 0*i (multiplication unit).
static complex I [get]
Complex constant 1 + 0*i (summation unit)
double this[int index] [get, set]
Index operator - index 0 for real part and 1 for imaginary part of a complex number.
double this[string index] [get, set]
Index operator where a string index defines what to get or to set. Possible indices read/write: re, Re, real, Real: real part of the complex number im, Im, imaginary, Imaginary: imaginary part of the complex number Possible indices - read only: r, R: modulus (absolute value) of the complex number fi, Fi: argument of the complex number
Properties inherited from IG.Num.IComplex
double Re [get]
Real part of the current complex number.
double Im [get]
Imaginary part of the current complex number.
double SquaredAbs [get]
Returns squared absolute value of the current complex number.
double Abs [get]
Modulus (absolute value) of the current complex number.
double Fi [get]
Argument of the current complex number.
Private Attributes
double _real
Detailed Description
Complex number.
$A Igor Sep08;
Constructor & Destructor Documentation
IG.Num.complex.complex (double real) inline
Initializes a complex number with specified real part and imaginary part 0.
Parameters
real Value assigned to the real part of the created complex number.
imaginary Value assigned to the imaginary part of the created complex number.
IG.Num.complex.complex (double real, double imaginary) inline
Initializes a complex number with specified real and imaginary part.
Parameters
real Value assigned to the real part of the created complex number.
imaginary Value assigned to the imaginary part of the created complex number.
IG.Num.complex.complex (complex a) inline
Initializes a complex number with another complex number.
Parameters
a Complex number whose copy is created in this constructor.
Member Function Documentation
static bool IG.Num.complex.operator== (complex a, complex b) inline static
References IG.Num.complex.Im, and IG.Num.complex.Re.
static bool IG.Num.complex.operator!= (complex a, complex b) inline static
References IG.Num.complex.Im, and IG.Num.complex.Re.
static complex IG.Num.complex.operator+ (complex a, complex b) inline static
Binary operator + for summation of two complex numbers.
References IG.Num.complex.Im, and IG.Num.complex.Re.
static complex IG.Num.complex.operator- (complex a, complex b) inline static
Binary operator - subtraction of two complex numbers.
References IG.Num.complex.Im, and IG.Num.complex.Re.
static complex IG.Num.complex.operator- (complex a) inline static
Unary operator - changing sign of a complex number.
References IG.Num.complex.Im, and IG.Num.complex.Re.
static complex IG.Num.complex.operator* (double a, complex c) inline static
Left multiplication of a complex number by a real number.
References IG.Num.complex.Im, and IG.Num.complex.Re.
static complex IG.Num.complex.operator* (complex c, double a) inline static
Right multiplication of a complex number by a real number.
References IG.Num.complex.Im, and IG.Num.complex.Re.
static complex IG.Num.complex.operator* (complex a, complex b) inline static
Complex multiplication.
References IG.Num.complex.Im, and IG.Num.complex.Re.
static complex IG.Num.complex.operator/ (complex a, complex b) inline static
Complex division.
References IG.Num.complex.Im, and IG.Num.complex.Re.
static implicit IG.Num.complex.operator complex (double number) inline static
Implicit conversion between from double to Complex.
Parameters
number Number that is converted.
Returns
Complex number that is a result of conversion from the specified number..
override int IG.Num.complex.GetHashCode () inline
Overrides the GetHashCode() appropriately.
Returns
override bool IG.Num.complex.Equals (Object obj) inline
Overrides the Equals() appropriately.
References IG.Num.ComplexClass.Im, and IG.Num.ComplexClass.Re.
static complex IG.Num.complex.Polar (double r, double fi) inline static
Referenced by IG.Num.ComplexClass.Polar().
override string IG.Num.complex.ToString () inline
Returns a string representation of the complec number in the form "(2.3+4.5*i)".
Referenced by IG.Num.complex.Example(), and IG.Num.ComplexClass.ToString().
double IG.Num.complex.Absolute () inline
Returns an absolute value of the complex number.
Implements IG.Num.IComplex.
Referenced by IG.Num.ComplexClass.Absolute().
static double IG.Num.complex.Absolute (complex a) inline static
Returns an absolute value of the specified complex number.
Parameters
a Complex number whose absolute value is returned.
References IG.Num.complex.Abs.
complex IG.Num.complex.Conjugate () inline
Complex conjugate.
Referenced by IG.Num.ComplexClass.Conjugate(), IG.Num.complex.Conjugate(), and IG.Num.complex.Example().
static complex IG.Num.complex.Conjugate (complex a) inline static
Returns a complex conjugate of the argument.
References IG.Num.complex.Conjugate().
static int IG.Num.complex.Compare (complex c1, complex c2) inline static
Compares two complex numbers and returns -1 if the first number is "smaller" than the second one, 0 if they are equal and 1 if the first number is "greater" than the second one. Comparison is artificial and does not have mathematical meaning. 0 is returned if and only if numbers are equal.
Parameters
c1 First number to be compared.
c2 Second number to be compared.
Returns
References IG.Num.complex.Im, and IG.Num.complex.Re.
static void IG.Num.complex.Example () inline static
Example of using the complex class.
Complex class will be seldom used, usually the complex struct will be used instead (which is a value type).
References IG.Num.complex.Conjugate(), and IG.Num.complex.ToString().
Member Data Documentation
double IG.Num.complex._real private
double IG.Num.complex._imaginary
Property Documentation
double IG.Num.complex.Re get private set
Gets (public access) or sets (protected access) the real part of the complex number.
Referenced by IG.Num.complex.Compare(), IG.Num.complex.operator!=(), IG.Num.complex.operator*(), IG.Num.complex.operator+(), IG.Num.complex.operator-(), IG.Num.complex.operator/(), and IG.Num.complex.operator==().
double IG.Num.complex.Im get private set
Gets (public access) or sets (protected access) the imaginary part of the complex number.
Referenced by IG.Num.complex.Compare(), IG.Num.complex.operator!=(), IG.Num.complex.operator*(), IG.Num.complex.operator+(), IG.Num.complex.operator-(), IG.Num.complex.operator/(), and IG.Num.complex.operator==().
double IG.Num.complex.SquaredAbs get
Returns squared absolute value of the current complex number.
double IG.Num.complex.Abs get
Gets modulus (absolute value) of the complex number.
Referenced by IG.Num.ComplexClass.Absolute(), and IG.Num.complex.Absolute().
double IG.Num.complex.Fi get
Argument of the complex number.
complex IG.Num.complex.Zero static get
Complex constant 0 + 0*i (summation unit)
complex IG.Num.complex.One static get
Complex constant 1 + 0*i (multiplication unit).
complex IG.Num.complex.I static get
Complex constant 1 + 0*i (summation unit)
double IG.Num.complex.this[int index] get set
Index operator - index 0 for real part and 1 for imaginary part of a complex number.
Parameters
index Integer index that can be 0 (for real part of the complex number) or 1 (for imaginary part).
double IG.Num.complex.this[string index] get set
Index operator where a string index defines what to get or to set. Possible indices read/write: re, Re, real, Real: real part of the complex number im, Im, imaginary, Imaginary: imaginary part of the complex number Possible indices - read only: r, R: modulus (absolute value) of the complex number fi, Fi: argument of the complex number
Parameters
index String that defines what to get or to set.
The documentation for this struct was generated from the following file:
shelldev/lib/LibCommon/0guests/Tako78/Complex.cs