IGLib: NUnit.Framework.Internal.Builders.DefaultSuiteBuilder Class Reference
NUnit.Framework.Internal.Builders.DefaultSuiteBuilder Class Reference
Built-in SuiteBuilder for all types of test classes.
Public Member Functions
bool CanBuildFrom (ITypeInfo typeInfo)
Checks to see if the provided Type is a fixture. To be considered a fixture, it must be a non-abstract class with one or more attributes implementing the IFixtureBuilder interface or one or more methods marked as tests.
TestSuite BuildFrom (ITypeInfo typeInfo)
Build a TestSuite from TypeInfo provided.
Private Member Functions
TestSuite BuildMultipleFixtures (ITypeInfo typeInfo, IEnumerable< TestSuite > fixtures)
IFixtureBuilder[] GetFixtureBuilderAttributes (ITypeInfo typeInfo)
We look for attributes implementing IFixtureBuilder at one level of inheritance at a time. Attributes on base classes are not used unless there are no fixture builder attributes at all on the derived class. This is by design.
bool HasArguments (IFixtureBuilder attr)
Private Attributes
NUnitTestFixtureBuilder _defaultBuilder = new NUnitTestFixtureBuilder()
Detailed Description
Built-in SuiteBuilder for all types of test classes.
Member Function Documentation
bool NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.CanBuildFrom (ITypeInfo typeInfo) inline
Checks to see if the provided Type is a fixture. To be considered a fixture, it must be a non-abstract class with one or more attributes implementing the IFixtureBuilder interface or one or more methods marked as tests.
Parameters
typeInfo The fixture type to check
Returns
True if the fixture can be built, false if not
Implements NUnit.Framework.Interfaces.ISuiteBuilder.
TestSuite NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildFrom (ITypeInfo typeInfo) inline
Build a TestSuite from TypeInfo provided.
Parameters
typeInfo The fixture type to build
Returns
A TestSuite built from that type
Implements NUnit.Framework.Interfaces.ISuiteBuilder.
References NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom(), NUnit.Framework.Interfaces.ITypeInfo.IsGenericType, and NUnit.Framework.Internal.PropertyNames.SkipReason.
Referenced by NUnit.TestUtilities.TestBuilder.MakeFixture().
TestSuite NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.BuildMultipleFixtures (ITypeInfo typeInfo, IEnumerable< TestSuite > fixtures) inline private
IFixtureBuilder [] NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.GetFixtureBuilderAttributes (ITypeInfo typeInfo) inline private
We look for attributes implementing IFixtureBuilder at one level of inheritance at a time. Attributes on base classes are not used unless there are no fixture builder attributes at all on the derived class. This is by design.
Parameters
typeInfo The type being examined for attributes
Returns
A list of the attributes found.
References NUnit.Framework.Interfaces.ITypeInfo.BaseType, and NUnit.Framework.Interfaces.ITypeInfo.IsType().
bool NUnit.Framework.Internal.Builders.DefaultSuiteBuilder.HasArguments (IFixtureBuilder attr) inline private
References NUnit.Framework.TestFixtureAttribute.Arguments.
Member Data Documentation
NUnitTestFixtureBuilder NUnit.Framework.Internal.Builders.DefaultSuiteBuilder._defaultBuilder = new NUnitTestFixtureBuilder() private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Builders/DefaultSuiteBuilder.cs