IGLib: NUnit.Common.TestSelectionParser Class Reference
NUnit.Common.TestSelectionParser Class Reference
Public Member Functions
string Parse (string input)
string ParseFilterExpression ()
Parse a single term or an or expression, returning the xml
string ParseFilterTerm ()
Parse a single element or an and expression and return the xml
string ParseFilterElement ()
Parse a single filter element such as a category expression and return the xml representation of the filter.
Properties
Token LookAhead [get]
Private Member Functions
string ParseExpressionInParentheses ()
Token Expect (params TokenKind[] kinds)
Token Expect (params Token[] valid)
Exception InvalidTokenError (Token token)
bool LookingAt (params Token[] tokens)
Token NextToken ()
Static Private Member Functions
static string EmitFilterElement (Token lhs, Token op, Token rhs)
static string EmitPropertyElement (Token lhs, Token op, Token rhs)
static string EmitElement (string fmt, Token lhs, Token rhs)
static string XmlEscape (string text)
Private Attributes
Tokenizer _tokenizer
Static Private Attributes
static readonly Token LPAREN = new Token(TokenKind.Symbol, "(")
static readonly Token RPAREN = new Token(TokenKind.Symbol, ")")
static readonly Token AND_OP1 = new Token(TokenKind.Symbol, "&")
static readonly Token AND_OP2 = new Token(TokenKind.Symbol, "&&")
static readonly Token AND_OP3 = new Token(TokenKind.Word, "and")
static readonly Token AND_OP4 = new Token(TokenKind.Word, "AND")
static readonly Token OR_OP1 = new Token(TokenKind.Symbol, "|")
static readonly Token OR_OP2 = new Token(TokenKind.Symbol, "||")
static readonly Token OR_OP3 = new Token(TokenKind.Word, "or")
static readonly Token OR_OP4 = new Token(TokenKind.Word, "OR")
static readonly Token NOT_OP = new Token(TokenKind.Symbol, "!")
static readonly Token EQ_OP1 = new Token(TokenKind.Symbol, "=")
static readonly Token EQ_OP2 = new Token(TokenKind.Symbol, "==")
static readonly Token NE_OP = new Token(TokenKind.Symbol, "!=")
static readonly Token MATCH_OP = new Token(TokenKind.Symbol, "=~")
static readonly Token NOMATCH_OP = new Token(TokenKind.Symbol, "!~")
static readonly Token[] AND_OPS = new Token[] { AND_OP1, AND_OP2, AND_OP3, AND_OP4 }
static readonly Token[] OR_OPS = new Token[] { OR_OP1, OR_OP2, OR_OP3, OR_OP4 }
static readonly Token[] EQ_OPS = new Token[] { EQ_OP1, EQ_OP2 }
static readonly Token[] REL_OPS = new Token[] { EQ_OP1, EQ_OP2, NE_OP, MATCH_OP, NOMATCH_OP }
static readonly Token EOF = new Token(TokenKind.Eof)
Member Function Documentation
string NUnit.Common.TestSelectionParser.Parse (string input) inline
References NUnit.Common.Tokenizer.LookAhead.
Referenced by NUnitLite.TextRunner.CreateTestFilter(), NUnit.Common.Tests.TestSelectionParserTests.TestParser(), and NUnit.Common.Tests.TestSelectionParserTests.TestParser_InvalidInput().
string NUnit.Common.TestSelectionParser.ParseFilterExpression () inline
Parse a single term or an or expression, returning the xml
Returns
string NUnit.Common.TestSelectionParser.ParseFilterTerm () inline
Parse a single element or an and expression and return the xml
string NUnit.Common.TestSelectionParser.ParseFilterElement () inline
Parse a single filter element such as a category expression and return the xml representation of the filter.
References NUnit.Common.Token.Text.
static string NUnit.Common.TestSelectionParser.EmitFilterElement (Token lhs, Token op, Token rhs) inline static private
References NUnit.Common.Token.Text.
static string NUnit.Common.TestSelectionParser.EmitPropertyElement (Token lhs, Token op, Token rhs) inline static private
References NUnit.Common.Token.Text.
static string NUnit.Common.TestSelectionParser.EmitElement (string fmt, Token lhs, Token rhs) inline static private
References NUnit.Common.Token.Text.
string NUnit.Common.TestSelectionParser.ParseExpressionInParentheses () inline private
Token NUnit.Common.TestSelectionParser.Expect (params TokenKind[] kinds) inline private
Token NUnit.Common.TestSelectionParser.Expect (params Token[] valid) inline private
Exception NUnit.Common.TestSelectionParser.InvalidTokenError (Token token) inline private
References NUnit.Common.Token.Pos, and NUnit.Common.Token.Text.
bool NUnit.Common.TestSelectionParser.LookingAt (params Token[] tokens) inline private
Token NUnit.Common.TestSelectionParser.NextToken () inline private
References NUnit.Common.Tokenizer.NextToken().
static string NUnit.Common.TestSelectionParser.XmlEscape (string text) inline static private
Member Data Documentation
Tokenizer NUnit.Common.TestSelectionParser._tokenizer private
readonly Token NUnit.Common.TestSelectionParser.LPAREN = new Token(TokenKind.Symbol, "(") static private
readonly Token NUnit.Common.TestSelectionParser.RPAREN = new Token(TokenKind.Symbol, ")") static private
readonly Token NUnit.Common.TestSelectionParser.AND_OP1 = new Token(TokenKind.Symbol, "&") static private
readonly Token NUnit.Common.TestSelectionParser.AND_OP2 = new Token(TokenKind.Symbol, "&&") static private
readonly Token NUnit.Common.TestSelectionParser.AND_OP3 = new Token(TokenKind.Word, "and") static private
readonly Token NUnit.Common.TestSelectionParser.AND_OP4 = new Token(TokenKind.Word, "AND") static private
readonly Token NUnit.Common.TestSelectionParser.OR_OP1 = new Token(TokenKind.Symbol, "|") static private
readonly Token NUnit.Common.TestSelectionParser.OR_OP2 = new Token(TokenKind.Symbol, "||") static private
readonly Token NUnit.Common.TestSelectionParser.OR_OP3 = new Token(TokenKind.Word, "or") static private
readonly Token NUnit.Common.TestSelectionParser.OR_OP4 = new Token(TokenKind.Word, "OR") static private
readonly Token NUnit.Common.TestSelectionParser.NOT_OP = new Token(TokenKind.Symbol, "!") static private
readonly Token NUnit.Common.TestSelectionParser.EQ_OP1 = new Token(TokenKind.Symbol, "=") static private
readonly Token NUnit.Common.TestSelectionParser.EQ_OP2 = new Token(TokenKind.Symbol, "==") static private
readonly Token NUnit.Common.TestSelectionParser.NE_OP = new Token(TokenKind.Symbol, "!=") static private
readonly Token NUnit.Common.TestSelectionParser.MATCH_OP = new Token(TokenKind.Symbol, "=~") static private
readonly Token NUnit.Common.TestSelectionParser.NOMATCH_OP = new Token(TokenKind.Symbol, "!~") static private
readonly Token [] NUnit.Common.TestSelectionParser.AND_OPS = new Token[] { AND_OP1, AND_OP2, AND_OP3, AND_OP4 } static private
readonly Token [] NUnit.Common.TestSelectionParser.OR_OPS = new Token[] { OR_OP1, OR_OP2, OR_OP3, OR_OP4 } static private
readonly Token [] NUnit.Common.TestSelectionParser.EQ_OPS = new Token[] { EQ_OP1, EQ_OP2 } static private
readonly Token [] NUnit.Common.TestSelectionParser.REL_OPS = new Token[] { EQ_OP1, EQ_OP2, NE_OP, MATCH_OP, NOMATCH_OP } static private
readonly Token NUnit.Common.TestSelectionParser.EOF = new Token(TokenKind.Eof) static private
Property Documentation
Token NUnit.Common.TestSelectionParser.LookAhead get private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/TestSelectionParser.cs