IGLib: CShell.Modules.Shell.ViewModels.ShellViewModel Class Reference
CShell.Modules.Shell.ViewModels.ShellViewModel Class Reference
Public Member Functions
ShellViewModel ()
void ShowTool (ITool model)
void OpenDocument (IDocument model)
void ActivateDocument (IDocument document)
void CloseDocument (IDocument document)
void Opened (string[] args)
void Close ()
IEnumerable< IResult > Closing (CancelEventArgs e)
void SaveLayout (XmlWriter xmlWriter)
void LoadLayout (XmlReader xmlReader)
ShellViewModel ()
void ShowTool (ITool model)
void OpenDocument (IDocument model)
void ActivateDocument (IDocument document)
void CloseDocument (IDocument document)
void Opened (string[] args)
void Close ()
IEnumerable< IResult > Closing (CancelEventArgs e)
void SaveLayout (XmlWriter xmlWriter)
void LoadLayout (XmlReader xmlReader)
Protected Member Functions
override void OnViewLoaded (object view)
override void OnDeactivate (bool close)
override void OnViewLoaded (object view)
override void OnDeactivate (bool close)
Properties
string Title [get, set]
ImageSource Icon [get, set]
IMenu MainMenu [get]
IToolBar ToolBar [get]
IStatusBar StatusBar [get]
IObservableCollection< ITool > ToolsObservable [get]
IEnumerable< ITool > Tools [get]
IEnumerable< IDocument > Documents [get]
Properties inherited from CShell.Framework.Services.IShell
string Title [get, set]
ImageSource Icon [get, set]
IMenu MainMenu [get]
IToolBar ToolBar [get]
IStatusBar StatusBar [get]
IScreen ActiveItem [get]
IEnumerable< IDocument > Documents [get]
IEnumerable< ITool > Tools [get]
Private Attributes
IShellView shellView
readonly ILog log = LogManager.GetLog(typeof(IShell))
string _title = "[Default Title]"
ImageSource _icon
IMenu _mainMenu
IToolBar _toolBar
IStatusBar _statusBar
readonly BindableCollection
< ITool > _tools
Constructor & Destructor Documentation
CShell.Modules.Shell.ViewModels.ShellViewModel.ShellViewModel () inline
CShell.Modules.Shell.ViewModels.ShellViewModel.ShellViewModel () inline
Member Function Documentation
override void CShell.Modules.Shell.ViewModels.ShellViewModel.OnViewLoaded (object view) inline protected
void CShell.Modules.Shell.ViewModels.ShellViewModel.ShowTool (ITool model) inline
Implements CShell.Framework.Services.IShell.
References CShell.Framework.ITool.IsVisible.
void CShell.Modules.Shell.ViewModels.ShellViewModel.OpenDocument (IDocument model) inline
Implements CShell.Framework.Services.IShell.
void CShell.Modules.Shell.ViewModels.ShellViewModel.ActivateDocument (IDocument document) inline
Implements CShell.Framework.Services.IShell.
void CShell.Modules.Shell.ViewModels.ShellViewModel.CloseDocument (IDocument document) inline
Implements CShell.Framework.Services.IShell.
void CShell.Modules.Shell.ViewModels.ShellViewModel.Opened (string[] args) inline
Implements CShell.Framework.Services.IShell.
References CShell.Constants.CShellDefaultFilePath.
void CShell.Modules.Shell.ViewModels.ShellViewModel.Close () inline
Implements CShell.Framework.Services.IShell.
override void CShell.Modules.Shell.ViewModels.ShellViewModel.OnDeactivate (bool close) inline protected
IEnumerable<IResult> CShell.Modules.Shell.ViewModels.ShellViewModel.Closing (CancelEventArgs e) inline
References CShell.Shell.Workspace.
void CShell.Modules.Shell.ViewModels.ShellViewModel.SaveLayout (XmlWriter xmlWriter) inline
Implements CShell.Framework.Services.IShell.
References CShell.Modules.Shell.Views.IShellView.DockingManager.
void CShell.Modules.Shell.ViewModels.ShellViewModel.LoadLayout (XmlReader xmlReader) inline
Implements CShell.Framework.Services.IShell.
References CShell.Modules.Shell.Views.IShellView.DockingManager, CShell.Shell.GetDocument(), CShell.Shell.GetSink(), and CShell.Shell.GetTool().
override void CShell.Modules.Shell.ViewModels.ShellViewModel.OnViewLoaded (object view) inline protected
void CShell.Modules.Shell.ViewModels.ShellViewModel.ShowTool (ITool model) inline
Implements CShell.Framework.Services.IShell.
References CShell.Framework.ITool.IsVisible.
void CShell.Modules.Shell.ViewModels.ShellViewModel.OpenDocument (IDocument model) inline
Implements CShell.Framework.Services.IShell.
void CShell.Modules.Shell.ViewModels.ShellViewModel.ActivateDocument (IDocument document) inline
Implements CShell.Framework.Services.IShell.
void CShell.Modules.Shell.ViewModels.ShellViewModel.CloseDocument (IDocument document) inline
Implements CShell.Framework.Services.IShell.
void CShell.Modules.Shell.ViewModels.ShellViewModel.Opened (string[] args) inline
Implements CShell.Framework.Services.IShell.
References CShell.Constants.CShellDefaultFilePath.
void CShell.Modules.Shell.ViewModels.ShellViewModel.Close () inline
Implements CShell.Framework.Services.IShell.
override void CShell.Modules.Shell.ViewModels.ShellViewModel.OnDeactivate (bool close) inline protected
IEnumerable<IResult> CShell.Modules.Shell.ViewModels.ShellViewModel.Closing (CancelEventArgs e) inline
References CShell.Shell.Workspace.
void CShell.Modules.Shell.ViewModels.ShellViewModel.SaveLayout (XmlWriter xmlWriter) inline
Implements CShell.Framework.Services.IShell.
void CShell.Modules.Shell.ViewModels.ShellViewModel.LoadLayout (XmlReader xmlReader) inline
Implements CShell.Framework.Services.IShell.
References CShell.Shell.GetDocument(), CShell.Shell.GetSink(), and CShell.Shell.GetTool().
Member Data Documentation
IShellView CShell.Modules.Shell.ViewModels.ShellViewModel.shellView private
readonly ILog CShell.Modules.Shell.ViewModels.ShellViewModel.log = LogManager.GetLog(typeof(IShell)) private
string CShell.Modules.Shell.ViewModels.ShellViewModel._title = "[Default Title]" private
ImageSource CShell.Modules.Shell.ViewModels.ShellViewModel._icon private
IMenu CShell.Modules.Shell.ViewModels.ShellViewModel._mainMenu private
IToolBar CShell.Modules.Shell.ViewModels.ShellViewModel._toolBar private
IStatusBar CShell.Modules.Shell.ViewModels.ShellViewModel._statusBar private
readonly BindableCollection< ITool > CShell.Modules.Shell.ViewModels.ShellViewModel._tools private
Property Documentation
string CShell.Modules.Shell.ViewModels.ShellViewModel.Title get set
ImageSource CShell.Modules.Shell.ViewModels.ShellViewModel.Icon get set
IMenu CShell.Modules.Shell.ViewModels.ShellViewModel.MainMenu get
IToolBar CShell.Modules.Shell.ViewModels.ShellViewModel.ToolBar get
IStatusBar CShell.Modules.Shell.ViewModels.ShellViewModel.StatusBar get
IObservableCollection< ITool > CShell.Modules.Shell.ViewModels.ShellViewModel.ToolsObservable get
IEnumerable< ITool > CShell.Modules.Shell.ViewModels.ShellViewModel.Tools get
IEnumerable< IDocument > CShell.Modules.Shell.ViewModels.ShellViewModel.Documents get
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Shell/ViewModels/ShellViewModel.cs