IGLib: alglib.spline2d Class Reference
alglib.spline2d Class Reference
Classes
class spline2dinterpolant
Static Public Member Functions
static double spline2dcalc (spline2dinterpolant c, double x, double y)
static void spline2ddiff (spline2dinterpolant c, double x, double y, ref double f, ref double fx, ref double fy, ref double fxy)
static void spline2dlintransxy (spline2dinterpolant c, double ax, double bx, double ay, double by)
static void spline2dlintransf (spline2dinterpolant c, double a, double b)
static void spline2dcopy (spline2dinterpolant c, spline2dinterpolant cc)
static void spline2dresamplebicubic (double[,] a, int oldheight, int oldwidth, ref double[,] b, int newheight, int newwidth)
static void spline2dresamplebilinear (double[,] a, int oldheight, int oldwidth, ref double[,] b, int newheight, int newwidth)
static void spline2dbuildbilinearv (double[] x, int n, double[] y, int m, double[] f, int d, spline2dinterpolant c)
static void spline2dbuildbicubicv (double[] x, int n, double[] y, int m, double[] f, int d, spline2dinterpolant c)
static void spline2dcalcvbuf (spline2dinterpolant c, double x, double y, ref double[] f)
static void spline2dcalcv (spline2dinterpolant c, double x, double y, ref double[] f)
static void spline2dunpackv (spline2dinterpolant c, ref int m, ref int n, ref int d, ref double[,] tbl)
static void spline2dbuildbilinear (double[] x, double[] y, double[,] f, int m, int n, spline2dinterpolant c)
static void spline2dbuildbicubic (double[] x, double[] y, double[,] f, int m, int n, spline2dinterpolant c)
static void spline2dunpack (spline2dinterpolant c, ref int m, ref int n, ref double[,] tbl)
static double spline2dcalc (spline2dinterpolant c, double x, double y)
static void spline2ddiff (spline2dinterpolant c, double x, double y, ref double f, ref double fx, ref double fy, ref double fxy)
static void spline2dlintransxy (spline2dinterpolant c, double ax, double bx, double ay, double by)
static void spline2dlintransf (spline2dinterpolant c, double a, double b)
static void spline2dcopy (spline2dinterpolant c, spline2dinterpolant cc)
static void spline2dresamplebicubic (double[,] a, int oldheight, int oldwidth, ref double[,] b, int newheight, int newwidth)
static void spline2dresamplebilinear (double[,] a, int oldheight, int oldwidth, ref double[,] b, int newheight, int newwidth)
static void spline2dbuildbilinearv (double[] x, int n, double[] y, int m, double[] f, int d, spline2dinterpolant c)
static void spline2dbuildbicubicv (double[] x, int n, double[] y, int m, double[] f, int d, spline2dinterpolant c)
static void spline2dcalcvbuf (spline2dinterpolant c, double x, double y, ref double[] f)
static void spline2dcalcv (spline2dinterpolant c, double x, double y, ref double[] f)
static void spline2dunpackv (spline2dinterpolant c, ref int m, ref int n, ref int d, ref double[,] tbl)
static void spline2dbuildbilinear (double[] x, double[] y, double[,] f, int m, int n, spline2dinterpolant c)
static void spline2dbuildbicubic (double[] x, double[] y, double[,] f, int m, int n, spline2dinterpolant c)
static void spline2dunpack (spline2dinterpolant c, ref int m, ref int n, ref double[,] tbl)
Static Private Member Functions
static void bicubiccalcderivatives (double[,] a, double[] x, double[] y, int m, int n, ref double[,] dx, ref double[,] dy, ref double[,] dxy)
static void bicubiccalcderivatives (double[,] a, double[] x, double[] y, int m, int n, ref double[,] dx, ref double[,] dy, ref double[,] dxy)
Member Function Documentation
static double alglib.spline2d.spline2dcalc (spline2dinterpolant c, double x, double y) inline static
Referenced by alglib.spline2dcalc(), alglib.testspline2dunit.testspline2d(), alglib.testspline2dunit.testspline2dvf(), alglib.testspline2dunit.testunpack(), and alglib.testspline2dunit.twodnumder().
static void alglib.spline2d.spline2ddiff (spline2dinterpolant c, double x, double y, ref double f, ref double fx, ref double fy, ref double fxy) inline static
Referenced by alglib.spline2ddiff(), and alglib.testspline2dunit.testspline2d().
static void alglib.spline2d.spline2dlintransxy (spline2dinterpolant c, double ax, double bx, double ay, double by) inline static
Referenced by alglib.spline2dlintransxy(), and alglib.testspline2dunit.testlintrans().
static void alglib.spline2d.spline2dlintransf (spline2dinterpolant c, double a, double b) inline static
Referenced by alglib.spline2dlintransf(), and alglib.testspline2dunit.testlintrans().
static void alglib.spline2d.spline2dcopy (spline2dinterpolant c, spline2dinterpolant cc) inline static
Referenced by alglib.spline2dcopy(), alglib.testspline2dunit.testlintrans(), and alglib.testspline2dunit.testspline2d().
static void alglib.spline2d.spline2dresamplebicubic (double a[,], int oldheight, int oldwidth, ref double b[,], int newheight, int newwidth) inline static
Referenced by alglib.spline2dresamplebicubic(), and alglib.testspline2dunit.testspline2d().
static void alglib.spline2d.spline2dresamplebilinear (double a[,], int oldheight, int oldwidth, ref double b[,], int newheight, int newwidth) inline static
Referenced by alglib.spline2dresamplebilinear(), and alglib.testspline2dunit.testspline2d().
static void alglib.spline2d.spline2dbuildbilinearv (double[] x, int n, double[] y, int m, double[] f, int d, spline2dinterpolant c) inline static
Referenced by alglib.spline2dbuildbilinearv(), alglib.testspline2dunit.testspline2d(), and alglib.testspline2dunit.testspline2dvf().
static void alglib.spline2d.spline2dbuildbicubicv (double[] x, int n, double[] y, int m, double[] f, int d, spline2dinterpolant c) inline static
Referenced by alglib.spline2dbuildbicubicv(), alglib.testspline2dunit.testspline2d(), and alglib.testspline2dunit.testspline2dvf().
static void alglib.spline2d.spline2dcalcvbuf (spline2dinterpolant c, double x, double y, ref double[] f) inline static
Referenced by alglib.spline2dcalcvbuf().
static void alglib.spline2d.spline2dcalcv (spline2dinterpolant c, double x, double y, ref double[] f) inline static
Referenced by alglib.spline2dcalcv(), alglib.testspline2dunit.testlintrans(), and alglib.testspline2dunit.testspline2dvf().
static void alglib.spline2d.spline2dunpackv (spline2dinterpolant c, ref int m, ref int n, ref int d, ref double tbl[,]) inline static
Referenced by alglib.spline2dunpackv(), and alglib.testspline2dunit.testspline2dvf().
static void alglib.spline2d.spline2dbuildbilinear (double[] x, double[] y, double f[,], int m, int n, spline2dinterpolant c) inline static
Referenced by alglib.spline2dbuildbilinear(), alglib.testspline2dunit.testspline2d(), alglib.testspline2dunit.testspline2dvf(), and alglib.testspline2dunit.unsetspline2d().
static void alglib.spline2d.spline2dbuildbicubic (double[] x, double[] y, double f[,], int m, int n, spline2dinterpolant c) inline static
Referenced by alglib.spline2dbuildbicubic(), alglib.testspline2dunit.testspline2d(), and alglib.testspline2dunit.testspline2dvf().
static void alglib.spline2d.spline2dunpack (spline2dinterpolant c, ref int m, ref int n, ref double tbl[,]) inline static
Referenced by alglib.spline2dunpack(), alglib.testspline2dunit.testspline2dvf(), and alglib.testspline2dunit.testunpack().
static void alglib.spline2d.bicubiccalcderivatives (double a[,], double[] x, double[] y, int m, int n, ref double dx[,], ref double dy[,], ref double dxy[,]) inline static private
static double alglib.spline2d.spline2dcalc (spline2dinterpolant c, double x, double y) inline static
static void alglib.spline2d.spline2ddiff (spline2dinterpolant c, double x, double y, ref double f, ref double fx, ref double fy, ref double fxy) inline static
static void alglib.spline2d.spline2dlintransxy (spline2dinterpolant c, double ax, double bx, double ay, double by) inline static
static void alglib.spline2d.spline2dlintransf (spline2dinterpolant c, double a, double b) inline static
static void alglib.spline2d.spline2dcopy (spline2dinterpolant c, spline2dinterpolant cc) inline static
static void alglib.spline2d.spline2dresamplebicubic (double a[,], int oldheight, int oldwidth, ref double b[,], int newheight, int newwidth) inline static
static void alglib.spline2d.spline2dresamplebilinear (double a[,], int oldheight, int oldwidth, ref double b[,], int newheight, int newwidth) inline static
static void alglib.spline2d.spline2dbuildbilinearv (double[] x, int n, double[] y, int m, double[] f, int d, spline2dinterpolant c) inline static
static void alglib.spline2d.spline2dbuildbicubicv (double[] x, int n, double[] y, int m, double[] f, int d, spline2dinterpolant c) inline static
static void alglib.spline2d.spline2dcalcvbuf (spline2dinterpolant c, double x, double y, ref double[] f) inline static
static void alglib.spline2d.spline2dcalcv (spline2dinterpolant c, double x, double y, ref double[] f) inline static
static void alglib.spline2d.spline2dunpackv (spline2dinterpolant c, ref int m, ref int n, ref int d, ref double tbl[,]) inline static
static void alglib.spline2d.spline2dbuildbilinear (double[] x, double[] y, double f[,], int m, int n, spline2dinterpolant c) inline static
static void alglib.spline2d.spline2dbuildbicubic (double[] x, double[] y, double f[,], int m, int n, spline2dinterpolant c) inline static
static void alglib.spline2d.spline2dunpack (spline2dinterpolant c, ref int m, ref int n, ref double tbl[,]) inline static
static void alglib.spline2d.bicubiccalcderivatives (double a[,], double[] x, double[] y, int m, int n, ref double dx[,], ref double dy[,], ref double dxy[,]) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/src/interpolation.cs