IGLib: alglib.testcreflectionsunit Class Reference
alglib.testcreflectionsunit Class Reference
Static Public Member Functions
static bool testcreflections (bool silent)
static bool testcreflections (bool silent)
static bool _pexec_testcreflections (bool silent)
Member Function Documentation
static bool alglib.testcreflectionsunit.testcreflections (bool silent) inline static
References alglib.math.abscomplex(), alglib.beta(), alglib.creflections.complexapplyreflectionfromtheleft(), alglib.creflections.complexapplyreflectionfromtheright(), alglib.creflections.complexgeneratereflection(), alglib.math.conj(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.math.randominteger(), alglib.math.randomreal(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testcreflectionsunit._pexec_testcreflections(), and _Test.Main().
static bool alglib.testcreflectionsunit.testcreflections (bool silent) inline static
References alglib.math.abscomplex(), alglib.beta(), alglib.creflections.complexapplyreflectionfromtheleft(), alglib.creflections.complexapplyreflectionfromtheright(), alglib.creflections.complexgeneratereflection(), alglib.math.conj(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.math.randominteger(), alglib.math.randomreal(), alglib.complex.x, and alglib.complex.y.
static bool alglib.testcreflectionsunit._pexec_testcreflections (bool silent) inline static
References alglib.testcreflectionsunit.testcreflections().
Referenced by _Test.Main().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs